### ISSUE TITLE
Insufficient PowerShell Host Version

### ISSUE THREAD

**Issue by NickPl** [PowerShell/vscode-powershell#1000]
### System Details

- Operating system name and version: Windows Server 2012 R2 Standard
- VS Code version: 1.15.0
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18728
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```
S C:\Users\plourdn3> code -v
1.15.0
8b95971d8cccd3afd86b35d4a0e098c189294ff2
PS C:\Users\plourdn3> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

PS C:\Users\plourdn3> code --list-extensions --show-versions
ms-vscode.PowerShell@1.4.1

### Issue Description

I just installed Visual Studio code and the Powershell extension. When I run my script I get this error. With Windows Powershell ISE, I have no errors. So, I tried several things and figured out what is triggering the error. 

I changed the required version in my module psd. I tried 3, 2, 1.5, 1.4. Once I reach 1.4 it worked. Since the version of the Visual Studio Code Host is 1.4.1 I think the console check the wrong the value.

PS C:\Users\plourdn3> Import-Module Microsoft.Xrm.Data.Powershell
Import-Module : The current Windows PowerShell host is: 'Visual Studio Code Host' (version 1.4.1). The module
'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.Xrm.Data.Powershell\Microsoft.Xrm.Data.Powershell.psd1' requires a minimum Windows PowerShell host
version of '1.5' to run.
At line:1 char:1
+ Import-Module Microsoft.Xrm.Data.Powershell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Windows\syst...Powershell.psd1:String) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_InsufficientPowerShellHostVersion,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by NickPl** [comment]
I think I figured out how to solve the issue. In the definition file there is this line:

PowerShellHostVersion = '4.0'

Which will check the host version. Since your version is 1.4.1, there is no bug. 

You should change your version to 4.1. So it would be compatible with the critera. Thus, the major shoud always be the lastest Powershell version supported by your tool. Does it make sense to you?

**Comment by jschmitter** [comment]
@NickPl Where can I find 'the definition file'?

**Comment by rkeithhill** [comment]
The definition file he is referring to is the `Microsoft.Xrm.Data.Powershell.psd1` file that comes with the module.  

I just installed the latest version of this module and the `PowerShellHostVersion` field has been reset back to `1.0` so it loads into the PS extension just fine.

**Comment by SydneyhSmith** [comment]
Closing this issue as resolved, will re-open if this is still an issue.
