### ISSUE TITLE
Problems running/debugging scripts with references to x86 dlls

### ISSUE THREAD

**Issue by uernst** [PowerShell/vscode-powershell#1003]
Hi,

first the specs:

### System Details

- Operating system name and version: win10prof
- VS Code version: 1.15.1 x64
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`: 
PSVersion                      5.1.14393.1532
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1532
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
code -v
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959
$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0
code --list-extensions --show-versions
DavidAnson.vscode-markdownlint@0.10.0
DotJoshJohnson.xml@1.9.2
filipw.scriptcsRunner@0.1.0
formulahendry.code-runner@0.7.0
ms-vscode.csharp@1.12.1
ms-vscode.mono-debug@0.15.7
ms-vscode.PowerShell@1.4.1
ms-vscode.Theme-MarkdownKit@0.1.4
```

### Issue Description
I've tried to run a script which references x86 dlls. In vscode 32-bit-version the setting: 'powershell.useX86Host:true' allowed me to run and debug the script in vscod. After the upgrade to vscode x64 the setting won't work anymore. I always get the error 'ERROR [IM014] [Microsoft][ODBC Driver Manager] The specified DSN contains an architecture mismatch between the Driver and
Application'. 
Do I have to downgrade to x86 version of vscode or is there a workaround to get scripts with x86 references running under x64 vscode.

Addition: After reinstalling vscode (VSCodeSetup-ia32-1.15.1.exe) everything works as intended.
best regards,
Uwe

**Comment by daviwil** [comment]
Hi Uwe, can you check and see if the `powershell.powerShellExePath` setting is present in your user settings file?  If so, remove it and the `powershell.useX86Host` setting should start working again.  If not, please let me know and I'll investigate.

**Comment by rjmholt** [comment]
@uernst You should be able to configure the extension to use x86 PowerShell now -- there's a dropdown triggered by clicking on the PowerShell version in the bottom right hand side of the window.

Going to close this issue since it's old and likely solved. Please reopen it if there's still an issue.
