### ISSUE TITLE
PowerShell Integrated Console VERY slow after silent errors in Select-Object

### ISSUE THREAD

**Issue by FireInWinter** [PowerShell/vscode-powershell#1005]
### System Details
```
- Operating system name and version: Windows 8.1
- VS Code version: 1.15.1
```
```
PS C:\> code -v
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959

PS C:\> $pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

PS C:\> code --list-extensions --show-versions
ms-mssql.mssql@1.1.0
ms-vscode.PowerShell@1.4.1

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18728
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

### Issue Description

Powershell becomes very slow and can take seconds every time I hit enter in the "PowerShell Integrated Console". To reproduce I just have to run the following:
```1..10000 | ForEach-Object { 'a'+$_} | Select-Object @{n='b';e={ $_ | Sort-Object { [ipaddress]($_) }}} | Out-Null```

At that point it is very slow.  Before that it works as expected.  The invalid sort in the select seems to have silent errors that don't show up in the PowerShell session, but do get written to the EditorServices.log every time you press enter or run something.  In the above example it will write 10000 lines to the log every time you hit enter.
```
8/23/2017 4:29:55 PM [ERROR] - Method "ExecuteCommand" at line 545 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Execution completed with errors:

   Cannot convert value "a1" to type "System.Net.IPAddress". Error: "An invalid IP address was specified."
...
   Cannot convert value "a10000" to type "System.Net.IPAddress". Error: "An invalid IP address was specified."
```
I originally found this because of a bug in a script that was trying to do some sorting based off of DNS entries.  It should have only been trying to sort by IP address if it was an A record (some have multiple IPs).  As that was a fairly complex script I simplified the script until I was able to reproduce it with the above script.

### Attached Logs

[PSLogs.zip](https://github.com/PowerShell/vscode-powershell/files/1247309/PSLogs.zip)

**Comment by FireInWinter** [comment]
Is no one able to reproduce this?  Seems like I made it really easy to reproduce and I'm fairly sure it is a bug.  It might be a low priority bug, but if it hits you, it effectively hangs the "PowerShell Integrated Console".  Sometimes it seems to even cause vs code to become sluggish and I've had to restart vs code a few times when it got bad.

**Comment by SydneyhSmith** [comment]
@FireInWinter sorry you never got a response, I am going through old issues and noticed this. I am unable to reproduce this now, and am wondering if it has been resolved--are you still running into this issue?
