### ISSUE TITLE
Windows PowerShell versions not enumerated correctly in 64-bit VS Code

### ISSUE THREAD

**Issue by brwilkinson** [PowerShell/vscode-powershell#1008]
code -v
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959

![vscode](https://user-images.githubusercontent.com/3605266/29693076-96663a5a-8901-11e7-805d-04f9d9e34215.png)

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

code --list-extensions --show-versions
bradygaster.azuretoolsforvscode@1.2.9
donjayamanne.python@0.7.0
eriklynd.json-tools@1.0.2
ipedrazas.kubernetes-snippets@0.1.3
johnpapa.azure-functions-tools@0.3.0
ms-vscode.csharp@1.12.1
ms-vscode.PowerShell@1.4.1
msazurermtools.azurerm-vscode-tools@0.3.6
PeterJausovec.vscode-docker@0.0.16
PKief.material-icon-theme@2.2.0

$psversiontable
Name                           Value
----                           -----
PSVersion                      5.1.16273.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16273.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
### System Details

Windows 10 Insider

### Issue Description

When I set the default powershell exe path to v 6 beta, I cannot swap back to  ps 5.1

"powershell.powerShellExePath": "C:\\Program Files\\PowerShell\\6.0.0-beta.5\\powershell.exe",

If I comment out that property and just launch defaults, I can them swap between versions.

I used to be able to swap between when using v6Beta, however this stopped working.

![vscode_powershell](https://user-images.githubusercontent.com/3605266/29692970-e6bcb408-8900-11e7-91b7-aeb2d6813b6b.png)

**Comment by daviwil** [comment]
Thanks Ben!

**Comment by brwilkinson** [comment]
Thanks @daviwil looks good   :)

**Comment by daviwil** [comment]
Thanks for confirming!
