### ISSUE TITLE
Missing tooltip on PS version indicator

### ISSUE THREAD

**Issue by MikeBazMSFT** [PowerShell/vscode-powershell#1009]
### System Details

- Operating system name and version: Windows 10 Creators Update (1703)
- VS Code version: 1.14.2
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

The lower-right-hand indicator of PowerShell version (e. g. ">_ 5.1" in my case) doesn't have a tooltip telling you what clicking on it does.  All the other indicators have a tooltip that tells you what the underlying button handles.

### Attached Logs

n/a

**Comment by daviwil** [comment]
Thanks for pointing that out!  Fixing it today.
