### ISSUE TITLE
No handler found for the command: 'PowerShell.RunSelection'.

### ISSUE THREAD

**Issue by feutl** [PowerShell/vscode-powershell#101]
I am lost, I have reinstalled Code, reinstalled the PS Extension, started everything as admin but everytime I open a PS1 file and hit F8 I get the error message

> No handler found for the command: 'PowerShell.RunSelection'. Ensure there is an activation event defined, if you are an extension.

Also auto-completion with ctrl+space is not showing any result.

Actually I have no idea where to start troubleshooting this.
PS on my machine works just fine because I use it regularly for different tasks.

VSCode Version: 0.10.8
PS Ext: 0.4.1
OS: Win8

**Comment by daviwil** [comment]
Hey Herbert, first thing I'd try is making sure this folder exists:

`c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell-0.4.1`

If it does exist, can you verify that it at least has a file called `package.json`?  We can proceed to debug the issue from there.

Thanks!

**Comment by gotchi** [comment]
Hi,
sorry for the delay, the folder and file is there. what are the next steps ?

**Comment by daviwil** [comment]
Insider that folder, do you see a folder called `bin` which contains a log file `EditorServices.log`?  If the file is there could you email it to me at daviwil@microsoft.com?  Another thought: what happens if you don't run VS Code as administrator?

**Comment by feutl** [comment]
Ok the mentioned file is not there :(
I also wanted to mention that I never run VS Code with Admin Privileges, but I tried and the error staid the same.
I tested VS Code with the PS plugin on another (win 10 machine) and it was working perfectly. Something hast to be special on this Win 8 box.

**Comment by daviwil** [comment]
Oh!  I totally missed the fact that you mentioned it was a Windows 8 box.  What version of PowerShell is installed there?  On Windows 8 you'll need [WMF 5.0 RTM](https://www.microsoft.com/en-us/download/details.aspx?id=50395) (which contains PowerShell 5).  We've almost gone PowerShell v4 support ready but it's not in the available release.  If you're not ready to upgrade to 5.0 yet then you should be able to use PowerShell 4.0 in the next update of the VS Code extension.

**Comment by feutl** [comment]
Ok thanks for that.
Must have overseen the requirement for the plugin. WMF 5.0 RTM is not available for Win 8.0 which I am running no this machine and an upgrade to 8.1 or 10 is not going to happen any time soon. So I am going to wait for the next update :)

Thanks for figuring that out.

**Comment by KushGoswami** [comment]
Hello, I am having same issue with VS Code, I am on VS code version 1.1.1 and I am using Windows 7 and Power shell version 2.0 , Is it not supported on Win 7 with PS 2.0 ??

**Comment by daviwil** [comment]
Hey @KushGoswami, as @rkeithhill mentioned in the other issue on the PowerShellEditorServices repo we don't currently support PowerShell 2.0.  You'll need at least PowerShell 3.0 before you can use the functionality supported by the PowerShell extension.

Going to close this issue since we've determined that it was originally coming from an incompatible PowerShell version.  We now have PowerShell v3 and v4 support so @feutl's problem should be resolved.

**Comment by nth-block** [comment]
I just tried executing Get-Date on my Windows 7 machine (with v4.0) I get the same error. To be doubly sure, I tried this on a Linux Vm (Ubuntu) with VSCode v1.10.2 running PowerShell v6.0 and it work there. I am not running VSCode as admin as I do not have admin rights.

**Comment by majkinetor** [comment]
This happens to me too, it works then it doesn't, here is the log

```
2019-06-04 10:20:25.963 [NORMAL] tid:5 in 'StartLogging' C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 183
    
    PowerShell Editor Services Host v1.12.1.0 starting (PID 12020
    
      Host application details:
    
        Name:      Visual Studio Code Host
        Version:   2019.5.0
        ProfileId: Microsoft.VSCode
        Arch:      X64
    
      Operating system details:
    
        Version: Microsoft Windows 10.0.10586 
        Arch:    X64
    
      Build information:
    
        Version: <development-build>
        Origin:  <development>
        Date:    2019-05-28T17:56:01
    

2019-06-04 10:20:26.046 [NORMAL] tid:5 in 'StartLanguageService' C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 202
    Language service started, type = NamedPipe, endpoint =  InOut pipe: PSES_hdhckfuk.jle

2019-06-04 10:20:26.052 [NORMAL] tid:5 in 'StartDebugService' C:\PowerShellEditorServices\src\PowerShellEditorServices.Host\EditorServicesHost.cs: line 279
    Debug service started, type = NamedPipe, endpoint =  InOut pipe: PSES_2yj4vrub.fac

2019-06-04 10:20:30.052 [NORMAL] tid:7 in 'Initialize' C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 221
    PowerShell runtime version: 5.0.10586.1417, edition: Desktop

2019-06-04 10:20:42.224 [NORMAL] tid:17 in 'Register' C:\PowerShellEditorServices\src\PowerShellEditorServices.VSCode\ComponentRegistration.cs: line 36
    PowerShell Editor Services VS Code module loaded.

2019-06-04 14:18:59.397 [ERROR] tid:22 in 'ListenForMessages' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs: line 344
    Stream terminated unexpectedly, ending MessageDispatcher loop
    
    Exception: EndOfStreamException
    MessageReader's input stream ended unexpectedly, terminating.
```

**Comment by SydneyhSmith** [comment]
@majkinetor thanks for commenting on this issue---it looks like this is an old issue and not likely what you are experiencing so it would be great if you could open a new issue and also provide `verbose logging`--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)..thanks!
