### ISSUE TITLE
editor.formatOnType/Paste insert extra tab at beginning of line

### ISSUE THREAD

**Issue by robe070** [PowerShell/vscode-powershell#1012]
### System Details

- Operating system name and version: WINDOWS 10 Pro Version 1703
- VS Code version: 1.15.1
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0
eamodio.gitlens@4.4.1
ms-vscode.PowerShell@1.4.1
ms-vscode.vs-keybindings@0.1.7

Key   : PSVersion
Value : 5.1.15063.502
Name  : PSVersion


Key   : PSEdition
Value : Desktop
Name  : PSEdition


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions


Key   : BuildVersion
Value : 10.0.15063.502
Name  : BuildVersion


Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

### Issue Description

I am experiencing a problem with these user settings:
   "editor.formatOnType": true,
   "editor.formatOnPaste": true

When I paste in text or press enter at the end of a line, an extra tab is inserted at the beginning of the line.,

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by SydneyhSmith** [comment]
I am having difficulty re-producing this so I am guessing it has been fixed, please let me know if this is still an issue.
