### ISSUE TITLE
Unable to debug PS5.1 module - useless errormessage

### ISSUE THREAD

**Issue by powercode** [PowerShell/vscode-powershell#1013]
### System Details

- Windows 10 RS2
- VS Code version: 1.15.1
- PowerShell extension version: 1.4.1

```
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959
E:\Source\Repos\Walrus >$pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0


E:\Source\Repos\Walrus >code --list-extensions --show-versions
donjayamanne.githistory@0.2.3
donjayamanne.python@0.7.0
DotJoshJohnson.xml@1.9.2
eamodio.gitlens@4.4.1
ms-vscode.cpptools@0.12.3
ms-vscode.csharp@1.12.1
ms-vscode.PowerShell@1.4.1
robertohuertasm.vscode-icons@7.12.0
```

### Issue Description

I am experiencing a problem with debugging a file, launched with 
```
		{
			"type": "PowerShell",
			"request": "launch",
			"name": "PowerShell Launch (debug.ps1)",
			"script": "${workspaceRoot}/test/debug.ps1",
			"args": [],
			"cwd": "${workspaceRoot}",
			"createTemporaryIntegratedConsole": false
		},
```

The only output is 
```
An error occurred while creating the pipeline.
At line:0 char:0
```

The script is doing has the following structure
```
using module E:\Source\Repos\MyModule\Release\MyModule
try {
	[SomeClass]::SomeMethod("Hello")
}
finally {
	Remove-Module -for MyModule
}
```

The module exists in my module path, and I have another version of the files opened in the editor, and maybe loaded by the languageservice.

### Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1256611/logs.zip)

**Comment by SydneyhSmith** [comment]
@powercode thanks for initially reporting this, I am going through old issues and noticed you never got a response/resolution-- I am wondering if you are still experiencing this issue?
