### ISSUE TITLE
Editor Services not starting due to "non-existent" path

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#1014]
### System Details

- Operating system name and version: MacOS Sierra
- VS Code version: 1.15.1
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
```
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-beta                                      
PSEdition                      Core                                            
GitCommitId                    v6.0.0-beta.6                                   
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: T...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0
```       

### Issue Description

I use VS Code on my Mac and access PowerShell scripts on a Parallels Windows VM. Parallels mounts the Windows disk directly as a volume on my Mac. This has been working great until I recently upgraded to Parallels 13. The Windows volume still exists called  `/Volumes/[C] VMABERTRAM01/` and I can access files fine still in VS Code but Editor Services fails to start.

I took a look inside of the EditorServices.log file and found this which is probably why it's refusing to load.

```
8/28/17 9:37:01 AM [ERROR] - Method "OnListenTaskCompleted" at line 391 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs

    ProtocolEndpoint message loop terminated due to unhandled exception:
    
    System.AggregateException: One or more errors occurred. (Cannot find path '/Volumes/[C] VMABERTRAM01/<MyWorkspaceFolder>' because it does not exist.) ---> System.Management.Automation.ItemNotFoundException: Cannot find path '/Volumes/[C] VMABERTRAM01/Users/abertram/Source/Workspaces/IS-DevOps/EO/Dev' because it does not exist.
```

I know this is not a problem with the volume as I can access it fine outside of VS Code. For some reason, Code does not like the volume path.

I've managed to work around this for now by creating a SMB share on my Windows VM and accessing it that way.

**Comment by adbertram** [comment]
This is a major PITA for me. Anyone have an idea what this might be?

**Comment by rkeithhill** [comment]
Does this work in your PS Core console?
```posh
Get-Item -LiteralPath '/Volumes/[C] VMABERTRAM01/Users/abertram/Source/Workspaces/IS-DevOps/EO/Dev'
```

**Comment by adbertram** [comment]
Hmm...no. It does not.

**Comment by rkeithhill** [comment]
Well, that could be a problem for PSES.  The `System.Management.Automation.ItemNotFoundException` says we are running a PowerShell command and it is failing.

**Comment by daviwil** [comment]
Yep, might be worth filing an issue on PowerShell/PowerShell to see if they can figure out why this path isn't accessible to PowerShell.

**Comment by adbertram** [comment]
@rkeithhill I'm looking into this again. This now works:

```
[Adams-MacBook-Pro-2.local] - /Users/adam> Get-Item -LiteralPath '/Volumes/[C] VMABERTRAM01/Users/abertram/Source/Workspaces/IS-DevOps/EO/Dev'                                                                                                        


    Directory: /Volumes/[C] VMABERTRAM01/Users/abertram/Source/Workspaces/IS-DevOps/EO


Mode                LastWriteTime         Length Name                                                                     
----                -------------         ------ ----                                                                     
d-----          11/8/17   4:32 PM                Dev    
```

However, I'm still getting that non-existent path in the session logs. Is it possible, the plugin just needs to enclose the path in quotes?

```
Adams-MacBook-Pro-2:~ adam$ ls /Volumes/[C] VMABERTRAM01/Users/abertram/Source/Workspaces/IS-DevOps/EO
ls: /Volumes/[C]: No such file or directory
VMABERTRAM01/Users/abertram/Source/Workspaces/IS-DevOps/EO:
Dev	Dev-DSC	Release
Adams-MacBook-Pro-2:~ adam$ ls "/Volumes/[C] VMABERTRAM01/Users/abertram/Source/Workspaces/IS-DevOps/EO"
Dev	Dev-DSC	Release
```

**Comment by rkeithhill** [comment]
Zip and attach the log files and I'll take a look.

**Comment by rkeithhill** [comment]
@adbertram OK I have a fix for this.  It's not the spaces, it is the `[]` chars that need to be escaped. We already have a method for escaping paths. Just need to call that method before we attempt to set the working dir.

**Comment by adbertram** [comment]
Awesome! Thanks for tracking that down.
