### ISSUE TITLE
Add option for additional coding styles

### ISSUE THREAD

**Issue by FooBartn** [PowerShell/vscode-powershell#102]
Looks like the default autocomplete indention style is K&R. Would it be possible to include the option for other styles, such as Allman?

**Comment by rkeithhill** [comment]
Not without making the snippet experience confusing.  That is we could provide `if` and `if (k&r)` but having duplicates for everything would be confusing IMO.

This style was debated and decided upon via the community [PowerShell Practice & Style project](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Style%20Guide/Code%20Layout%20and%20Formatting.md).  

You can provide your own snippets that use Allman style which is actually my favorite for C# but not for PowerShell.  

Edit the following file `C:\Users\<username>\AppData\Roaming\Code\User\snippets\powershell.json`.  For reference, look at the snippets in `C:\Users\<username>\.vscode\extensions\ms-vscode.PowerShell-0.4.1\snippets`

**Comment by daviwil** [comment]
Thanks @FooBartn! 

Once place where we could optionally set the indentation style is here:

https://github.com/PowerShell/vscode-powershell/blob/master/src/main.ts#L29

However, as Keith correctly points out, the code snippets would still be hardcoded to K&R style.  If this is acceptable then we may be able to do a halfway solution where the auto-indent for typed code could be changed but the snippets are not.

**Comment by FooBartn** [comment]
@rkeithhill Understood. A solution which resulted in a lot of duplication would not be a good solution. I got used to it because it's the default in ISESteroids for code refactoring. I suppose someone could write a similar extension for VSC if they really wanted to.

@daviwil It's not a necessity for me; changing how i write would not be that difficult and it would allow me to take advantage of the auto-completed snippets.

It was just a curiosity -- thank you both for the information! :+1:

**Comment by rkeithhill** [comment]
@FooBartn I'm going to close this issue.  If you want it to stay open, let me know.
