### ISSUE TITLE
Cmdlet help snippet does not get generated inside of workflow blocks

### ISSUE THREAD

**Issue by ricardogaspar2** [PowerShell/vscode-powershell#1025]
Just a request for improvement.

So far I didn't find a plugin or a way to auto-generate PowerShell scripts documentation. It would be great to have this automated. 

Probably there is, but I was searching online and in this repo, and I didn't find anything.

**Comment by daviwil** [comment]
Hey Ricardo, have you tried typing out a comment block above or inside of a PowerShell function?  We automatically generate the help comment for you.  See this changelog note for more details:

https://github.com/PowerShell/vscode-powershell/blob/master/CHANGELOG.md#new-dynamic-snippet-for-adding-comment-based-help-748

Are you looking for something different entirely?

**Comment by ricardogaspar2** [comment]
No, I didn't see that. Thank you very much @daviwil !

**Comment by ricardogaspar2** [comment]
@daviwil, I noticed that this trick is not possible to use in functions inside PowerShell workflows.
Do you know why?

Example:
```
workflow example {
    function f ([string] str) {
        return str
    }
}
```

**Comment by daviwil** [comment]
@ricardogaspar2 Looks like we missed this case.  I'll update the bug title.  Thanks!

**Comment by Cirzen** [comment]
@daviwil Could you also add this for scripts as a whole? i.e where a script file starts with [CmdletBinding()] Param(...), typing "<#" above the CmdletBinding line would ideally trigger the same behaviour. Workaround is to wrap the entire contents of the file in a Function definition and then delete afterwards.

**Comment by tylerl0706** [comment]
That's a reasonable ask. Good idea!

**Comment by JustinGrote** [comment]
The original ask was implemented with https://github.com/PowerShell/vscode-powershell/pull/748 so you can type '##' anywhere to get the comment help block.

@TylerLeonhardt @SydneyhSmith perhaps this should be retagged to an enhancement to trigger also in certain comment circumstances as requested by @Cirzen in https://github.com/PowerShell/vscode-powershell/issues/1025#issuecomment-360301800, or is the ## syntax considered sufficient enough to close?

**Comment by SydneyhSmith** [comment]
Thanks will close the initial issue as fixed.

@Cirzen if you still have the second request could you please open a new issue with those details. Thanks!
