### ISSUE TITLE
Add support for Types.ps1xml files

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [PowerShell/vscode-powershell#1029]
### System Details

- Operating system name and version: Windows 10 Pro x64
- VS Code version: 1.16.0
- PowerShell extension version: 1.4.2
- Output from `$PSVersionTable`:
    ```
    Name                           Value
    ----                           -----
    PSVersion                      5.1.15063.502
    PSEdition                      Desktop
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.15063.502
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    ```
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

PS C:\> code -v
1.16.0
787b31c0474e6165390b5a5989c9619e3e16f953
PS C:\> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0


PS C:\> code --list-extensions --show-versions
ms-vscode.PowerShell@1.4.2
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Currently, there's no support for Types.ps1xml files - used for augmenting PoSH/CLR types through the Extended Type System. While the built-in XML language parser kind-of works, it only handles XML language folding/highlighting - any PowerShell types/scripts/etc. are treated as basic data.

Consider the basic [Types.ps1xml](https://github.com/hmmwhatsthisdo/PSEWS/blob/0888124013b9edfe2f9c93b62bda9b9bb64f2506/PSEWS.Types.ps1xml) file in my PSEWS module project. Some potential methods for improving the experience could entail:

- Schema validation (Someone wrote [an XSD](https://jtruher3.wordpress.com/2007/02/19/powershell-extended-types-includes-a-types-xsd/) expressing the Types.ps1xml format, but I don't know if VSCode supports XSDs yet)
- Auto-completion of type/method names, where available
- Support for PowerShell language parsing inside of elements containing PowerShell scripts (Script and Get/SetScriptBlock come to mind)

**Comment by LaurentDardenne** [comment]
See also this feature request on [PSScriptnalyzer](https://github.com/PowerShell/PSScriptAnalyzer/issues/789) project

**Comment by daviwil** [comment]
@hmmwhatsthisdo yep, this would be really nice!  Not sure what it'd take, but I like the suggestion.  Always open to PRs if you want to get your hands dirty :)

**Comment by rjmholt** [comment]
The schema validation and script analysis for this probably belongs in PSScriptAnalyzer.

That would leave completions and highlighting. The completions are probably simple enough to achieve (although really all the PS1XML parsing code should just be a PowerShell API... Worth opening an issue at least). The highlighting would probably be painful since it would have to support schema'd XML embedding PowerShell, but it is definitely achievable. That would go in https://github.com/PowerShell/EditorSyntax.

**Comment by fourpastmidnight** [comment]
The same could be said for `format.ps1xml` files...

**Comment by rjmholt** [comment]
@felixfbecker actually created [PowerShellXSD](https://github.com/felixfbecker/PowerShellXSD), which allows ps1xml schema checking with the [VSCode XML extension](https://marketplace.visualstudio.com/items?itemName=IBM.XMLLanguageSupport).

I believe that currently offers the best experience.

Adding that extra functionality to PSScriptAnalyzer may be straightforward in some scenarios (anyone wanting to investigate is welcome to look at [some work I did a while ago on it](https://github.com/rjmholt/PSScriptAnalyzer/tree/xml-file-analysis/Engine/XmlAnalysis)), but some ps1xml analysis requires whole-module context, which PSScriptAnalyzer isn't really built for.

**Comment by TylerLeonhardt** [comment]
Here's also some [docs from the vscode docs page](https://code.visualstudio.com/docs/languages/powershell#_typesps1xml-and-formatps1xml-files).
