### ISSUE TITLE
Read-Host crashes debug adapter when -Prompt and -AsSecureString parameters are used

### ISSUE THREAD

**Issue by jirijanata** [PowerShell/vscode-powershell#103]
Hi,

when I try to debug script with this row:

`Read-Host 'Please write user password' -AsSecureString
`
it ends with error "Debug adapter process has terminated unexpectedly" and debug will ends. PowerShell ISE works fine.

**Comment by daviwil** [comment]
Hi Jiri,

This is likely due to the usage of the `-AsSecureString` parameter since we don't support this yet.  I apologize for the debug adapter crash, we should be able to handle this case without crashing.  Both `Get-Credential` and `Read-Host -AsSecureString` support will be added in an upcoming release.

**Comment by jirijanata** [comment]
Hi Daviwil,

thank you for your quick response. I understand that and hope, that the works on the new version is going well.

**Comment by daviwil** [comment]
Hi Jiri, can you try this with the latest release of the PowerShell extension (0.4.1) and see if the host does not crash for you anymore?  I think we might have fixed this already.

**Comment by rkeithhill** [comment]
Both of these crash the debug host.  Also, they prompt you to type in the info but the info is echoed to the debug console prompt which is not ideal.  Can we use the VSCode inpu dialog box (with hidden chars) at debug time to query for this sensitive info?

**Comment by daviwil** [comment]
Strangely I don't get a crash, I get an error written to the console:

![image](https://cloud.githubusercontent.com/assets/79405/13609683/e5032378-e50e-11e5-95ab-e92ad53257ad.png)

Do you see anything interesting in your DebugAdapter.log?

**Comment by daviwil** [comment]
Hah!  OK, there's a difference when using the `-Prompt` parameter.  This goes down my input prompt code path which isn't handling SecureStrings correctly.  I'll fix that.

**Comment by jirijanata** [comment]
Hi, the exact command is:
$pass = Read-Host 'Please write user password' -AsSecureString

= I'm saving user input AsSecureString to variable for usage in next command:
New-ADUser -Name $name -AccountPassword $pass -CannotChangePassword $true -PasswordNeverExpires $true -Enabled $true

**Comment by daviwil** [comment]
Fixed for 0.5.0 as of this commit: https://github.com/PowerShell/PowerShellEditorServices/commit/c43c84fbda8827d81c5db28c608285dddec29063

**Comment by daviwil** [comment]
And just to be clear, the fix is to throw a correct error in this case instead of crashing.  We don't support reading credentials and SecureStrings just yet, we will add this in a future release.  Thanks!
