### ISSUE TITLE
'Microsoft.PowerShell.EditorServices.dll' because it does not exist. 

### ISSUE THREAD

**Issue by rossuhrig** [PowerShell/vscode-powershell#1031]
### System Details

- Operating system name and version: Windows 10 Enterprise x64
- VS Code version: 1.16
- PowerShell extension version: 1.4.2
- Output from `$PSVersionTable`: 
Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here: I am unable to run this command. The PowerShell Integrated Console does not launch.

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

An error occurred while starting PowerShell Editor Services:

The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind parameter 'Path' to the target. E
xception setting "Path": "Cannot find path 'C:\Users\xxxx\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PowerShellEditorServices\bin\Desktop\Microsoft.P
owerShell.EditorServices.dll' because it does not exist."
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

### Attached Logs
[1505232438-6611a116-e6c6-4164-afb2-3d6af265ce2d1505232434065.zip](https://github.com/PowerShell/vscode-powershell/files/1296624/1505232438-6611a116-e6c6-4164-afb2-3d6af265ce2d1505232434065.zip)

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Hi @rossuhrig, can you give me a text dump of the output of this command:

```powershell
ls -R $HOME\.vscode\extensions\ms-vscode.powershell-1.4.2\modules`
```

Thanks!

**Comment by rossuhrig** [comment]
PS C:\Users\itpr12377> ls -R $HOME\.vscode\extensions\ms-vscode.powershell-1.4.2\modules


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/06/2017  10:49 AM                PowerShellEditorServices
d-----       09/12/2017  10:49 AM                PowerShellEditorServices - Copy
d-----       09/06/2017  10:49 AM                PSScriptAnalyzer
-a----       09/06/2017  10:49 AM            370 README.md


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PowerShellEditorServices


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/06/2017  10:49 AM                Commands
-a----       09/06/2017  10:49 AM          13557 PowerShellEditorServices.psd1
-a----       09/06/2017  10:49 AM          15274 PowerShellEditorServices.psm1


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PowerShellEditorServices\Commands


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/06/2017  10:49 AM                Private
d-----       09/06/2017  10:49 AM                Public
-a----       09/06/2017  10:49 AM          14103 PowerShellEditorServices.Commands.psd1
-a----       09/06/2017  10:49 AM          10114 PowerShellEditorServices.Commands.psm1
-a----       09/06/2017  10:49 AM          11875 PowerShellEditorServices.Commands.types.ps1xml


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PowerShellEditorServices\Commands\Private


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       09/06/2017  10:49 AM          11158 BuiltInCommands.ps1


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PowerShellEditorServices\Commands\Public


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       09/06/2017  10:49 AM          11966 CmdletInterface.ps1
-a----       09/06/2017  10:49 AM          11871 ConvertFrom-ScriptExtent.ps1
-a----       09/06/2017  10:49 AM          14102 ConvertTo-ScriptExtent.ps1
-a----       09/06/2017  10:49 AM          16151 Find-Ast.ps1
-a----       09/06/2017  10:49 AM          11109 Get-Token.ps1
-a----       09/06/2017  10:49 AM          15772 Import-EditorCommand.ps1
-a----       09/06/2017  10:49 AM          10916 Join-ScriptExtent.ps1
-a----       09/06/2017  10:49 AM          10386 Out-CurrentFile.ps1
-a----       09/06/2017  10:49 AM          13457 Set-ScriptExtent.ps1
-a----       09/06/2017  10:49 AM          11370 Test-ScriptExtent.ps1


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PowerShellEditorServices - Copy


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/12/2017  10:49 AM                Commands
-a----       09/06/2017  10:49 AM          13557 PowerShellEditorServices.psd1
-a----       09/06/2017  10:49 AM          15274 PowerShellEditorServices.psm1


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PowerShellEditorServices - Copy\Commands


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/12/2017  10:49 AM                Private
d-----       09/12/2017  10:49 AM                Public
-a----       09/06/2017  10:49 AM          14103 PowerShellEditorServices.Commands.psd1
-a----       09/06/2017  10:49 AM          10114 PowerShellEditorServices.Commands.psm1
-a----       09/06/2017  10:49 AM          11875 PowerShellEditorServices.Commands.types.ps1xml


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PowerShellEditorServices -
    Copy\Commands\Private


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       09/06/2017  10:49 AM          11158 BuiltInCommands.ps1


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PowerShellEditorServices -
    Copy\Commands\Public


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       09/06/2017  10:49 AM          11966 CmdletInterface.ps1
-a----       09/06/2017  10:49 AM          11871 ConvertFrom-ScriptExtent.ps1
-a----       09/06/2017  10:49 AM          14102 ConvertTo-ScriptExtent.ps1
-a----       09/06/2017  10:49 AM          16151 Find-Ast.ps1
-a----       09/06/2017  10:49 AM          11109 Get-Token.ps1
-a----       09/06/2017  10:49 AM          15772 Import-EditorCommand.ps1
-a----       09/06/2017  10:49 AM          10916 Join-ScriptExtent.ps1
-a----       09/06/2017  10:49 AM          10386 Out-CurrentFile.ps1
-a----       09/06/2017  10:49 AM          13457 Set-ScriptExtent.ps1
-a----       09/06/2017  10:49 AM          11370 Test-ScriptExtent.ps1


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PSScriptAnalyzer


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/06/2017  10:49 AM                coreclr
d-----       09/06/2017  10:49 AM                en-US
d-----       09/06/2017  10:49 AM                PSv3
d-----       09/06/2017  10:49 AM                Settings
-a----       09/06/2017  10:49 AM         260768 Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
-a----       09/06/2017  10:49 AM         205472 Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
-a----       09/06/2017  10:49 AM         533152 Newtonsoft.Json.dll
-a----       09/06/2017  10:49 AM          17595 PSScriptAnalyzer.cat
-a----       09/06/2017  10:49 AM          13035 PSScriptAnalyzer.psd1
-a----       09/06/2017  10:49 AM          12189 PSScriptAnalyzer.psm1
-a----       09/06/2017  10:49 AM          15640 ScriptAnalyzer.format.ps1xml
-a----       09/06/2017  10:49 AM          13493 ScriptAnalyzer.types.ps1xml


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PSScriptAnalyzer\coreclr


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       09/06/2017  10:49 AM         257184 Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
-a----       09/06/2017  10:49 AM         203424 Microsoft.Windows.PowerShell.ScriptAnalyzer.dll


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PSScriptAnalyzer\en-US


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       09/06/2017  10:49 AM          12710 about_PSScriptAnalyzer.help.txt
-a----       09/06/2017  10:49 AM          63710 Microsoft.Windows.PowerShell.ScriptAnalyzer.dll-Help.xml


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PSScriptAnalyzer\PSv3


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       09/06/2017  10:49 AM         251040 Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll
-a----       09/06/2017  10:49 AM         194720 Microsoft.Windows.PowerShell.ScriptAnalyzer.dll
-a----       09/06/2017  10:49 AM         533152 Newtonsoft.Json.dll


    Directory: C:\Users\itpr12377\.vscode\extensions\ms-vscode.powershell-1.4.2\modules\PSScriptAnalyzer\Settings


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       09/06/2017  10:49 AM          10142 CmdletDesign.psd1
-a----       09/06/2017  10:49 AM          10943 CodeFormatting.psd1
-a----       09/06/2017  10:49 AM          10944 CodeFormattingAllman.psd1
-a----       09/06/2017  10:49 AM          10944 CodeFormattingOTBS.psd1
-a----       09/06/2017  10:49 AM          10983 CodeFormattingStroustrup.psd1
-a----       09/06/2017  10:49 AM         221438 core-6.0.0-alpha-linux.json
-a----       09/06/2017  10:49 AM         221436 core-6.0.0-alpha-osx.json
-a----       09/06/2017  10:49 AM         275054 core-6.0.0-alpha-windows.json
-a----       09/06/2017  10:49 AM        1831955 desktop-5.1.14393.206-windows.json
-a----       09/06/2017  10:49 AM           9788 DSC.psd1
-a----       09/06/2017  10:49 AM          10990 PSGallery.psd1
-a----       09/06/2017  10:49 AM          10223 ScriptFunctions.psd1
-a----       09/06/2017  10:49 AM           9847 ScriptingStyle.psd1
-a----       09/06/2017  10:49 AM          10091 ScriptSecurity.psd1

Ross Uhrig

**Comment by daviwil** [comment]
Somehow the PowerShellEditorServices modules DLLs got deleted, that shouldn't happen under normal circumstances.  Can you try uninstalling the PowerShell extension, restart VS Code, then re-install the PowerShell extension?

**Comment by Jaykul** [comment]
This just happened to me after the extension upgraded to 1.5:

```
An error occurred while starting PowerShell Editor Services:

The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind parameter 'Path' to the target. Exception setting "Pat
h": "Cannot find path 'C:\Users\Joel\.vscode-insiders\extensions\ms-vscode.powershell-1.5.0\modules\PowerShellEditorServices\bin\Core\Microsoft.PowerShell.EditorServices.dll' because it
does not exist."
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

In fact, there's no `bin` folder in the PowerShellEditorServices module.

**Comment by kannan-balasubramanian** [comment]
I too have the same issue with powershell-1.5.0 extension & VSCode v1.17.1.
Even after un-installing the extension, restarting VSCode and installing, still bin directory is missing,

**Comment by TylerLeonhardt** [comment]
We've done a ton of work on the extension and I don't think this issue exists anymore.

If you're still seeing it, can you let me know? I'll close this for now.
