### ISSUE TITLE
Where-Object not coloured correctly.

### ISSUE THREAD

**Issue by richardajyoung** [PowerShell/vscode-powershell#1034]
### System Details

- Operating system name and version:
BuildNumber     : 15063
Version         : 10.0.15063

code -v
1.16.1
27492b6bf3acb0775d82d2f87b25a93490673c6d

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

code --list-extensions --show-versions

eamodio.gitlens@5.1.0
filipw.scriptcsRunner@0.1.0
formulahendry.code-runner@0.7.1
groksrc.ruby@0.0.6
jcanero.hoogle-vscode@0.0.4
johnpapa.azure-functions-tools@0.3.1
justusadam.language-haskell@2.3.2
ms-mssql.mssql@1.1.0
ms-vscode.azurecli@0.2.0
ms-vscode.csharp@1.12.1
ms-vscode.PowerShell@1.4.3
ms-vscode.vscode-azureextensionpack@0.0.6
ms-vsts.team@1.122.0
msazurermtools.azurerm-vscode-tools@0.3.7
PeterJausovec.vscode-docker@0.0.17
rebornix.Ruby@0.15.0
usqlextpublisher.usql-vscode-ext@0.2.4
Vans.haskero@1.3.1
VisualStudioOnlineApplicationInsights.application-insights@0.4.1
vsciot-vscode.azure-iot-toolkit@0.2.2
wayou.vscode-todo-highlight@0.5.11

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Where-Object is miscoloured. The verb 'where' is coloured, but the noun 'object' is not.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.
![image](https://user-images.githubusercontent.com/17741734/30573395-fb0f16ae-9d36-11e7-877f-b800ba38d0b3.png)

**Comment by rkeithhill** [comment]
This is most likely an issue with the https://github.com/powershell/editorsyntax project.

**Comment by rkeithhill** [comment]
It looks like this regex is hitting before the `Where-Object` regex:
```
		<key>controlWords</key>
		<dict>
			<key>match</key>
			<string>(\b(?&lt;!-|\$)(?i:begin|process|exit|break|return|catch|finally|for|continue|foreach|throw|from|trap|try|do|if|until|in|using|else|elseif|while|end|where)\b(?!-|\.))</string>
			<key>name</key>
			<string>keyword.control.powershell</string>
		</dict>
```
`where` is NOT a language keyword according to these [docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_keywords?view=powershell-5.1).  So perhaps it should be removed from the above.  Although you'd think that `Foreach-Object` would have the same issue.

**Comment by thezim** [comment]
This bugs me to. This is what I have for my `PowerShellSyntax.tmLanguage` installed within my vscode (1.16.1) on OSX. 

```Powershell
PS /Applications/Visual Studio Code.app/Contents> gci -Recurse -Filter Power*.tm*                                                                                                                                                                                       

    Directory: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/powershell/syntaxes


Mode                LastWriteTime         Length Name                                                                              
----                -------------         ------ ----                                                                              
------          9/19/17   9:05 PM          32062 PowershellSyntax.tmLanguage
```

File itself appears to be very different from https://github.com/PowerShell/EditorSyntax/blob/master/PowerShellSyntax.tmLanguage

`foreach` has an exclusion with `object`. `where` should get the same treatment or outright removed as @rkeithhill recommended.

```xml
<dict>
     <key>match</key>
     <string>(?&lt;!\w)((?i:begin|break|catch|continue|data|define|do|dynamicparam|else|elseif|end|exit|finally|for|foreach(?!-object)|from|if|in|inlinescript|parallel|param|process|return|switch|throw|trap|try|until|using|var|where|while)|%|\?)(?!\w)</string>
    <key>name</key>
    <string>keyword.control.powershell</string>
</dict>
```

Adding the following with the exclusion above for `where` corrects the issue in my case.

```xml
<dict>
	<key>comment</key>
	<string>Builtin cmdlets with reserved verbs</string>
	<key>match</key>
	<string>(?&lt;!\w)(?i:where-object)(?!\w)</string>
	<key>name</key>
	<string>support.function.powershell</string>
</dict>
```

**Comment by thezim** [comment]
Even stranger on vscode (1.16.1) for Windows.

```xml
<string>(?&lt;!\w)((?i:begin|break|catch|continue|data|define|do|dynamicparam|else|elseif|end|exit|finally|for|foreach(?!-object)|from|if|in|inlinescript|parallel|param|process|return|switch|throw|trap|try|until|using|var|where(?!=-object)|while)|%|\?)(?!\w)</string>
```

I don't believe `where(?!=-object)` is correct. The `=` shouldn't be there.

@rkeithhill any idea what repo we should escalate this to?

**Comment by rkeithhill** [comment]
Yes, we should move this whole issue over to https://github.com/powershell/editorsyntax

I believe @daviwil has a tool and the privs to move issues.

**Comment by rkeithhill** [comment]
I don't think the whole `where(?!=-object)` should be there.  AFAICT `where` is not a keyword.  It doesn't show up in `about_Languages_keywords`.

**Comment by thezim** [comment]
@rkeithhill but it is an alias.

**Comment by rkeithhill** [comment]
`Sort` and `Select` are aliases as well but they show up in a different color - white.

**Comment by thezim** [comment]
Per @daviwil comments https://github.com/Microsoft/vscode/pull/34701 there is a larger update to cover mutiple issues including this one. I think we can close this issue out here.

**Comment by daviwil** [comment]
Yep, we've overhauling the syntax definition, hoping to have that ready soon.  Thanks for your PR!  I'll close this issue now.
