### ISSUE TITLE
Issues with German Umlaute

### ISSUE THREAD

**Issue by krehberger** [PowerShell/vscode-powershell#1035]
### System Details

- Operating system name and version: Windows 10 Pro, 1703, 15063.608
- VS Code version: Code 1.16.1 (27492b6, 2017-09-14T16:38:23.027Z)
- PowerShell extension version: 1.4.3
- Output from `$PSVersionTable`: 
Name                           Value                                                                                                                
----                           -----                                                                                                                
PSVersion                      5.1.15063.608                                                                                                        
PSEdition                      Desktop                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                              
BuildVersion                   10.0.15063.608                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                      
WSManStackVersion              3.0                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                  
SerializationVersion           1.1.0.1 

```
code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable

**Output:**
C:\Users\klaus\Desktop> code -v
1.16.1
27492b6bf3acb0775d82d2f87b25a93490673c6d
C:\Users\klaus\Desktop> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0


C:\Users\klaus\Desktop> code --list-extensions --show-versions
dbankier.vscode-gist@1.0.0
donjayamanne.githistory@0.2.3
DotJoshJohnson.xml@1.9.2
eamodio.gitlens@5.1.0
jsynowiec.vscode-insertdatestring@2.1.0
ms-vscode.PowerShell@1.4.3
robertohuertasm.vscode-icons@7.13.0
Shan.code-settings-sync@2.8.3
tariky.easy-snippet-maker@0.0.6
vector-of-bool.gitflow@1.1.1
C:\Users\klaus\Desktop> [$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am experiencing a problem with German Umlaute in VSCode and Powershell.
1. I save a Script function in VSCode which has German Umlaute in the Code like
` $ReplacedUmlaute = $FileAs -replace "ö", "oe"`
2. When I open the same Script function in Powershell ISE all Umlaute have wrong characters e.g.: The Umlaut character "ö" is changed to the 2 characters "Ã¶".

In Addition to the wrong Umlaut representation the powershell function script works in Powershell ISE as expected, but in VSCode the Statement 
` $ReplacedUmlaute = $FileAs -replace "ö", "oe"`
doesn't work as expected. The Umlaut "ö" is not replaced with 'oe'

Attached you find the Powershell Script which doesn't work as expected in VSCode, but works in Powershell ISE (after I replace the wrong Umlaut characters "Ã¶" in the Code with the right character "ö".
 
Attached the Powershell Script function:
[Get-FBOlContacts.zip](https://github.com/PowerShell/vscode-powershell/files/1317628/Get-FBOlContacts.zip)

Logs I will send directly to David Wilson.

**Comment by skest3qc** [comment]
Hi,
this is a problem with encoding. Check the enconding of the original file and if you edit and save this file in VS code the encoding is changed to UTF-8

**Comment by daviwil** [comment]
Thanks a lot @skest3qc!  I'll close this issue for now, @krehberger let us know if this fix resolves it for you.
