### ISSUE TITLE
PSEdit not saving remote files

### ISSUE THREAD

**Issue by muzzar78** [PowerShell/vscode-powershell#1040]
@daviwil  - Could this issue be related to the following?

https://github.com/PowerShell/vscode-powershell/blob/aa86c7e6aad5aadba6d37c564f0678f868898fd4/src/features/RemoteFiles.ts#L11-L24

When I remote into a server within the integrated terminal, run psedit the file appears in VSCode. However, when I make an edit and save the file the changes aren't getting saved back to the remote server. I have attached the verbose log output. https://github.com/PowerShell/vscode-powershell/files/1309888/vscode-powershell-psedit.zip

**Comment by djobin** [comment]
Hi!
I see the same behaviour. I can remotely edit .ps1 files and it get commited back to the remote server, but when editing other file types (.cmd, .txt, .log, etc.) it does not get synced back.

vs code :  1.17
ps extensions :  1.4.3

**Comment by muzzar78** [comment]
Hi,
I can confirm the behaviour I'm seeing is the same as @djobin. Saving ps1 files do get committed back to the remote host but other extensions don't.

**Comment by muzzar78** [comment]
Here is the logic - it checks if the languageId is powershell.

https://github.com/PowerShell/vscode-powershell/blob/aa86c7e6aad5aadba6d37c564f0678f868898fd4/src/features/RemoteFiles.ts#L60-L63

So the workaround is to set the language mode to PowerShell regardless of the extension of the remote file and then the remote save works. I have tested this and it worked for me.

**Comment by daviwil** [comment]
Thanks for looking into this Adam!  I'll take that check out.

**Comment by OnurGumus** [comment]
This issue still exists if you use VSCode Powershell extension along with Powershell 7 for remote files.
