### ISSUE TITLE
Powershell debugger fails with Language Service error

### ISSUE THREAD

**Issue by aditya-sen** [PowerShell/vscode-powershell#1044]
### System Details

- Operating system name and version:Windows 7 Enterprise Service Pack 1
- VS Code version: 1.16.1
- PowerShell extension version: 1.4.3
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

code -v
1.16.1
27492b6bf3acb0775d82d2f87b25a93490673c6d

$pseditor.EditorServicesVersion
'$pseditor.EditorServicesVersion' is not recognized as an internal or external command,
operable program or batch file.

code --list-extensions --show-versions
ms-vscode.PowerShell@1.4.3

$PSVersionTable
'$PSVersionTable' is not recognized as an internal or external command,
operable program or batch file.

### Issue Description

I am experiencing a problem with...
I created a simple Powershell file with the following command and tried to run it:
Get-Help -name Get-Content -full

I get an error 
10/5/2017 2:32:59 PM [NORMAL] - Language server startup failed.
10/5/2017 2:32:59 PM [ERROR] - The language service could not be started: 
10/5/2017 2:32:59 PM [ERROR] - Timed out waiting for session file to appear.

Note that I installed Powershell 6.0 beta separately and updated VS Code User Settings to point to it as follows:
"powershell.powerShellExePath": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"

### Attached Logs
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1360677/logs.zip)

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
If you installed PS Core 6.0 beta and want to use it in VSCode that isn't the correct path.  It should be:
```
"powershell.powerShellExePath": "C:\\Program Files\\PowerShell\\6.0.0-beta.7\\powershell.exe"
```
Anyway, no need to set this manually, if you click on the green PowerShell icon on the right end of the status bar it will display a list of PowerShell installations you can switch between.

Also, this crashed starting **Windows** PowerShell.  Can you fire up a Windows PowerShell prompt and get the `$PSVersionTable` info from that and post it here?  Thanks!

**Comment by aditya-sen** [comment]
Output of $PSVersionTable:
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by aditya-sen** [comment]
I corrected the path to 
"powershell.powerShellExePath": "C:\\Program Files\\PowerShell\\6.0.0-beta.7\\powershell.exe" 

and also changed VS Code to start in admin mode. I still get the Language Service startup failure:
10/6/2017 9:39:23 AM [NORMAL] - Language server startup failed.
10/6/2017 9:39:23 AM [ERROR] - The language service could not be started: 
10/6/2017 9:39:23 AM [ERROR] - Timed out waiting for session file to appear.

**Comment by aditya-sen** [comment]
Selecting Powershell 6 Beta from the language options also does not help.

**Comment by aditya-sen** [comment]
I managed to capture a screenshot of the startup error.
![vs-code_startuperror](https://user-images.githubusercontent.com/32553641/31358977-844f3990-ad0d-11e7-92dc-f1e2d4c87357.png)

**Comment by aditya-sen** [comment]
Finally figured out the issue - I had overwritten my start-editorservices.ps1 file with another version that I copied from a github issue in order to troubleshoot other issues. This version was missing required parameters that the 1.4.3. PowerShell extension was trying to send to it.
