### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by mattmcnabb** [PowerShell/vscode-powershell#1052]
I'm planning to create another theme that will be included in the PowerShell extension, this time with a dark editor. Before I begin I'd like to get others thoughts on what they would like to see from a PowerShell ISE Theme - Dark. I think I'll leave the console coloring as-is with the blue PowerShell background, but the editor will be dark.

1. Would you like the UI elements to follow the dark theme, or should they stay the way they are now (pseudo-ISE colors)?
2. What would you like to see in the editor itself? Some of the most popular dark themes for other editors are Solarized, Monokai, Dracula, etc. Would you like to see something similar to those, or something completely different?

**Comment by pcgeek86** [comment]
Hey @mattmcnabb is this a dupe of #1051?

**Comment by mattmcnabb** [comment]
Yeah, have no idea how that happened. Closing this one, thanks!
