### ISSUE TITLE
write-progress not show in vscode 1.17.0

### ISSUE THREAD

**Issue by rickmoua** [PowerShell/vscode-powershell#1053]
write-progress gives no error, but doesn't show the progress bar like in the ISE.
Using VSCode 1.17.0 on a windows 10 PSV5.1

VSCODE 1.17.0
PSV 5.1
windows 10

C:\Users\rickym.LSI\Desktop\RM> $psEditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

**Comment by iricigor** [comment]
related to #140

**Comment by pcgeek86** [comment]
Going to close this as a duplicate for now. Please let me know if there's anything different about this compared to the issue mentioned by @iricigor.
