### ISSUE TITLE
Feature Request: Variable List continues to display values after execution is over given runspace is still live

### ISSUE THREAD

**Issue by Eric2XU** [PowerShell/vscode-powershell#1059]
The only thing that keeps me from using VS Code is the fact it doesnt show variable data when the script isnt running. It seems an obvious oversight. If the runspace is preserved (which it is since I can do $var at the command line and get values) they why wouldnt you display all variables in between runs. Is there a way to hack that in?

**Comment by rkeithhill** [comment]
The display of variables in the VARIABLES view is completely controlled by VSCode.  You might want to file a suggestion on the [VSCode repo](https://github.com/microsoft/vscode/issues).
