### ISSUE TITLE
Update extension and PSES to handle PS Core rename of binary to pwsh

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#1064]
Title says it all.  This one will be a bit tricky since we support side-by-side PS Core installations.  We can't wholesale change `powershell` to `pwsh` - just for PS Core 6.0.0-beta.9 and higher.  Do we already have an npm package pulled in that can compare semver v2 versions?

**Comment by daviwil** [comment]
Maybe just keep it simple and look for either powershell.exe or pwsh.exe in the PowerShell Core install paths?
