### ISSUE TITLE
Mac Integrated Terminal PS Core: Terminal process terminated with exit code: 64

### ISSUE THREAD

**Issue by thnk2wn** [PowerShell/vscode-powershell#1067]
### System Details

- Operating system name and version: MacOS Sierra 10.12.6 (16G29)
- VS Code version: 1.17.2 (1.17.2)
- PowerShell extension version: 1.4.3
- Output from `$PSVersionTable`:

<pre>
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3SerializationVersion           1.1.0.1
WSManStackVersion              3.0
</pre>

<pre>
$pseditor.EditorServicesVersion

Major  Minor  Build  Revision-----  -----  -----  --------
1      4      1      0
</pre>

### Issue Description

I open the integrated terminal in one of the following ways:
a) Outside the context of any PowerShell file (i.e. no windows open)
b) Within the context of a PowerShell file with the PS console open but I click the + icon to create a new terminal.

I receive the error "The terminal process terminated with exit code: 64". In the output briefly I see "Invalid argument -l. Did you mean..."

My Code User settings look like the below: 

<pre>
{
    "workbench.iconTheme": null,

    "terminal.integrated.shell.osx": "/usr/local/microsoft/powershell/6.0.0-beta.8/powershell",
    "powershell.powerShellExePath": "/usr/local/microsoft/powershell/6.0.0-beta.8/powershell"
}
</pre>

### Error Screenshot
![2017-10-22_20-20-19](https://user-images.githubusercontent.com/120529/31959143-c291287a-b8a8-11e7-97ee-65b23a8a759d.jpg)

### Attached Logs

[1508866984-54659293-7964-4069-84c9-6c22607d7e1a1508730789084.zip](https://github.com/PowerShell/vscode-powershell/files/1411865/1508866984-54659293-7964-4069-84c9-6c22607d7e1a1508730789084.zip)

### Where It Does Work
If the terminal is opened automatically in the context of opening a PowerShell file, I don't receive this behavior.

**Comment by daviwil** [comment]
Hey Geoff, when you run PowerShell by itself by opening the Integrated Terminal UI, VS Code is sending a parameter of `-l` when it executes the powershell command.  You can change the `terminal.integrated.shellArgs.osx` setting to be an empty array to make this behavior go away.  I believe the reason why it's set to `['-l']` by default is to make bash run as a login shell by default on macOS.

**Comment by thnk2wn** [comment]
Thanks. That's certainly not obvious though and I don't recall seeing anything about needing to do that in any setup info anywhere. Perhaps that could be documented somewhere or something to help prevent this in the future.
