### ISSUE TITLE
Formatter should check for end-of-line comment when moving opening brace to same line

### ISSUE THREAD

**Issue by MRWeather** [PowerShell/vscode-powershell#1069]
PS v1.0> (Get-CimInstance Win32_OperatingSystem).version
10.0.15063

PS v1.0> code -v
1.17.2
b813d12980308015bcd2b3a2f6efa5c810c33ba5
PS v1.0> $pseditor.EditorServicesVersion
PS v1.0> code --list-extensions --show-versions
donjayamanne.python@0.7.0
ms-mssql.mssql@1.2.0
ms-vscode.PowerShell@1.4.3
ms-vsts.team@1.122.0
PS v1.0> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Any variation of code formatting that moves the opening brace to the same line should check for an end-of-line comment:

# before formatting
foreach ($s in $y ) # loop through $y  
{
    Write-Host $s
}

# after formatting, the opening brace becomes part of the comment
foreach ($s in $y ) # loop through $y   {
Write-Host $s
}
I don't code comments that way, but I have run into it several times when formatting other's code.

**Comment by daviwil** [comment]
Ouch!  That's definitely wrong.  I'll move this issue over to the PSScriptAnalyzer repo.

**Comment by daviwil** [comment]
This issue was moved to PowerShell/PSScriptAnalyzer#826
