### ISSUE TITLE
Extension fails to load on Mac using pwsh.

### ISSUE THREAD

**Issue by lanrongwen** [PowerShell/vscode-powershell#1073]
017-10-26 13:06:48 [NORMAL] - Visual Studio Code v1.17.2 64-bit
2017-10-26 13:06:48 [NORMAL] - PowerShell Extension v1.4.3
2017-10-26 13:06:48 [NORMAL] - Operating System: MacOS 64-bit
error: "The terminal process command `/usr/local/bin/powershell -NoProfile -NonInteractive -Command '& '/Us..."

looks like the extension doesn't take into account the new name of Powershell core.

Powershell was installed using brew.
VScode via download from vscode's website.

**Comment by daviwil** [comment]
This has been fixed and will be shipped tomorrow: https://github.com/PowerShell/vscode-powershell/issues/1064

In the meantime you can set your `powershell.powerShellExePath` setting to the new path.
