### ISSUE TITLE
Issues with 'Using Module' and classes

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/vscode-powershell#1076]
### System Details

- Operating system name and version: Windows 10 Enterprise
```
PS > code -v
1.17.2
b813d12980308015bcd2b3a2f6efa5c810c33ba5

PS > $pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0


PS > code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.4.0
DotJoshJohnson.xml@1.9.2
ms-mssql.mssql@1.2.0
ms-vscode.PowerShell@1.4.3
streetsidesoftware.code-spell-checker@1.4.10

PS > $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.674
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.674
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When using a class from a different module, the PowerShell plugin cannot locate the class source. I have a module which contains class definitions, then in another module I use the "Using module <ModuleName>" to load the classes into the session for the module to use. It would be nice if the plugin could locate the supplied module and load in the classes to stop the editor "Unable to find type" errors from occurring.

**Comment by LethiferousMoose** [comment]
This appears to work as expected when using PowerShell Core.

**Comment by tylerl0706** [comment]
Just to understand you more, do you mean that intillisense/"go to definition" isn't working for classes?

Can you share some code and a screenshot of the "unable to find type" errors?

**Comment by LethiferousMoose** [comment]
Sure, in my code I have a module that I use to store all my "shared" classes and then I use the **Using Module** syntax to include the base classes that I use in my modules. In this case I have a class for creating a RuntimeDefinedParameter called ProductParameterBuilder that extends my base class DynamicParameterBuilder which lives in "classes" module. 
Something like the following:
\<workspace>/PSClasses/PSClasses.psm1
```powershell
class DynamicParameterBuilder {
    [System.Management.Automation.RuntimeDefinedParameter]
    CreateParameter([string] $ParameterName) {
        throw [System.NotImplementedException]::new();
    }
}
```

\<workspace>/PSEnvironment/PSEnvironment.psm1
```powershell
Using Module PSClasses
...
class ProductParameterBuilder : DynamicParameterBuilder {
    [System.Management.Automation.RuntimeDefinedParameter]
    CreateParameter([string] $ParameterName) {
        # Implementation logic
    }
}
```

If I use the PowerShell plugin with version 5.1, the base class gets underlined in red and gives the reason "Unable to find type [DynamicParameterBuilder]".
![unabletofindtype](https://user-images.githubusercontent.com/24547864/33894277-37328f02-df23-11e7-8a25-3ecab217a4dd.png)

Now if I click the PowerShell icon in the status bar and switch to PowerShell Core 6.0 rc, the error underline goes away.
![notypeerror](https://user-images.githubusercontent.com/24547864/33894919-ca518814-df24-11e7-93e6-b2cb5e16ba16.png)

Intellisense/"go to definition" does not work either, but I did not know if that was supposed to be a feature or not.

Let me know if you have anymore questions.

**Comment by tylerl0706** [comment]
Can you try one thing for me?

When you get the "Unable to find type" error, can you try F8'ing the `using module` line and see if the error goes away?

Also could you try restarting the PowerShell session using the command pallet and see if that fixes it?

**Comment by LethiferousMoose** [comment]
Okay, I just tried executing F8 on the Using Module line, and I see it executing in the Integrated Console, but the errors persist. I have also run "Restart Current Session", the result is the same.

**Comment by rjmholt** [comment]
Ok cool — I think I interpreted the "unable to find type" part as a diagnostic from PSScriptAnalyzer there, not a VSCode error.

We'll look into this. Thanks for the report!

**Comment by tylerl0706** [comment]
Just to add on to what @rjmholt said, "Go to definition" doesn't work because we are using legacy AST APIs to support PowerShell v3/v4 in the extension. 

We are [looking to drop 3,4](https://github.com/PowerShell/vscode-powershell/issues/1310) which will allow us to use [modern AST APIs](https://github.com/PowerShell/PowerShellEditorServices/issues/276) which should give us symbols for classes.

I'm going to close this issue because @LethiferousMoose's original issue is the PSScriptAnalyzer issue that @rjmholt mentioned, and the issue @AlexBillon07 is having is tracked with https://github.com/PowerShell/vscode-powershell/issues/3
