### ISSUE TITLE
Problem debugging function with a string parameter to which you send swedish characters in the string

### ISSUE THREAD

**Issue by johlju** [PowerShell/vscode-powershell#108]
A normal function:

```
function Get-Something
{   [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$true,Position=0)]        
        [ValidateNotNullOrEmpty()]       
        [string]$Title
    )

    Write-Verbose $Title    
}
```

Sending a string with Swedish characters gets a string that is corrupt.
`Get-Something -Title "Söder Ögon Åder Råd Rädd" -Verbose`
![swedishchars](https://cloud.githubusercontent.com/assets/7189721/13487437/32df6b0e-e11a-11e5-8fdf-3c9e4eb2e70c.PNG)

This call doesn't work either since it parses the string wrong.
`Get-Something -Title "Ängar" -Verbose`
![swedishchars2](https://cloud.githubusercontent.com/assets/7189721/13487472/868ce272-e11a-11e5-951f-5a5ba51b763d.PNG)

**Comment by rkeithhill** [comment]
What file encoding does VSCode indicate for that file? It should be in the status bar on the right side.

**Comment by johlju** [comment]
File encoding: UTF-8
VSCode version: 0.10.8
PowerShell extension version: 0.4.1

Also tested on the VSCode Insider version: 0.10.10-insider
Used the same version of PowerShell extension on the Insider version.

**Comment by daviwil** [comment]
Interesting, I just tried to reproduce this and it works fine for me:

![image](https://cloud.githubusercontent.com/assets/79405/13498923/d479a90c-e110-11e5-9d92-8d7a7097a4fe.png)

This is with the shipped 0.10.8 and 0.4.1 versions of VS Code and the PowerShell extension, respectively.

Can you try to reproduce this issue again and then send the contents of the following file to daviwil@microsoft.com:

`c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell\bin\DebugAdapter.log`

**Comment by johlju** [comment]
I have sent the requested information.

**Comment by johlju** [comment]
This problem still exists in the 1.3.1 version. But I now saw that in the Output pane (when runnig with F8) the problem does not exist. So it seems that the problem are only shown in the debug console.

![image](https://cloud.githubusercontent.com/assets/7189721/17291058/f5079c2c-57e1-11e6-8360-79e63cd42acc.png)

**Comment by johlju** [comment]
OK! Found that when the file has encoding `UTF-8` this problem occurs. When the Encoding is `UTF-8 with BOM` or `UTF-16 LE` this problem does not occur (only tried with those three encodings). 
Below screenshot is from the running the code with file encoding `UTF-16 LE`.
![image](https://cloud.githubusercontent.com/assets/7189721/17291198/c0c6ba28-57e2-11e6-97be-f056b71f7b34.png)

**Comment by daviwil** [comment]
Weird!  Not sure why it *would* work with UTF-16 and not with UTF-8.  Thanks for the update!  We'll keep looking into this.

**Comment by lw-schick** [comment]
It would be nice if the plugin would warn when I start writing special chars (f.e. äöü) with UTF8.
As I know it PowerShell does UTF8 only support with BOM. So it would be nice if the plugin could give me a hint here...

**Comment by johlju** [comment]
This isn't a problem anymore. I can't reproduce any longer. I guess this started working when we got the PowerShell Integration Console. I forgot about this, and I haven't used Swedish strings in a while so haven't seen it got fixed. 😄
