### ISSUE TITLE
Powershell opening in a new window instead of being integrated into VSCode terminal

### ISSUE THREAD

**Issue by nskpmg** [PowerShell/vscode-powershell#1080]
### System Details

- Operating system name and version:
Windows 10 
- VS Code vesion:
1.18-insider
- PowerShell extension version:
- Output from `$PSVersionTable`:
Name                           Value                                                                                                                                                                    
----                           -----                                                                                                                                                                    
PSVersion                      5.0.10586.1106                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                  
BuildVersion                   10.0.10586.1106                                                                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                                                                          
WSManStackVersion              3.0                                                                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                                                                      
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:
Wish I could :)
code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description
having powershell being integrated into the VScode IDE

### Attached Logs
10/31/2017 11:58:50 AM [NORMAL] - Visual Studio Code v1.18.0-insider 64-bit
10/31/2017 11:58:50 AM [NORMAL] - PowerShell Extension v1.5.0
10/31/2017 11:58:50 AM [NORMAL] - Operating System: Windows 64-bit
10/31/2017 11:58:50 AM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
10/31/2017 11:58:50 AM [NORMAL] - Language server starting --
10/31/2017 11:58:50 AM [NORMAL] -     exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
10/31/2017 11:58:50 AM [NORMAL] -     args: C:\Users\nspano\.vscode-insiders\extensions\ms-vscode.powershell-1.5.0\scripts\Start-EditorServices.ps1 -EditorServicesVersion '1.5.0' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.5.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\nspano\.vscode-insiders\extensions\ms-vscode.powershell-1.5.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\nspano\.vscode-insiders\extensions\ms-vscode.powershell-1.5.0\logs\1509465530-3d991409-a055-468b-9055-0d9a4cc64feb1509464173294\EditorServices.log' -SessionDetailsPath 'C:\Users\nspano\.vscode-insiders\extensions\ms-vscode.powershell-1.5.0\sessions\PSES-VSCode-9196-343739' -FeatureFlags @()
10/31/2017 11:58:53 AM [NORMAL] - powershell.exe started, pid: 11284
10/31/2017 11:58:57 AM [NORMAL] - Language server started.
10/31/2017 11:58:57 AM [NORMAL] - {"debugServicePort":10795,"status":"started","channel":"tcp","languageServicePort":17172}
10/31/2017 11:58:57 AM [NORMAL] - Connecting to language service on port 17172...
10/31/2017 11:58:57 AM [NORMAL] - Language service connected.
10/31/2017 12:04:34 PM [NORMAL] - powershell.exe terminated or terminal UI was closed
Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
This is by design.  The PowerShell extensions uses the PowerShell Integrated Console to host the language and debug service.  This allows you to interact with the language service via the console and interact with the debug session state during debugging.  The other issue is that users don't have to configure the terminal to use PowerShell.  On Linux for instance, the default shell for the terminal is bash.
