### ISSUE TITLE
Start-EditorServices.ps1 authenticode signature 'HashMismatch'

### ISSUE THREAD

**Issue by itjediFrank** [PowerShell/vscode-powershell#1084]
### System Details

- Operating system name and version: Windows 10 1709 16299.15 / 1706 14393.1770
- VS Code version: 1.17.2
- PowerShell extension version: 1.5.0
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      5.1.14393.1770
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1770
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
### Issue Description

The Start-EditorService.ps1 has a HashMismatch.

Get-AuthenticodeSignature "~\.vscode\extensions\ms-vscode.powershell-1.5.0\scripts\Start-EditorServices.ps1"

SignerCertificate                         Status                                 Path
-----------------                         ------                                 ----
98ED99A67886D020C564923B7DF25E9AC019DF26  HashMismatch                           Start-EditorServices.ps1

**Comment by rkeithhill** [comment]
@daviwil Is this similar to what happened with the Plaster signing?

**Comment by daviwil** [comment]
Nah, this is due to there being an edit to [Start-EditorServices.ps1](https://github.com/PowerShell/vscode-powershell/blob/master/scripts/Start-EditorServices.ps1) in 1.5.0 without re-signing the the script.  That was a screwup on my part.

@SteveL-MSFT @tylerl0706, this may warrant a patch release just to get the properly signed script sent out for the folks who are on systems with restrictive ExecutionPolicy settings.

**Comment by SteveL-MSFT** [comment]
@tylerl0706 is this something you can take care of?

**Comment by jtwaddle** [comment]
Any idea when this will be re-signed?

**Comment by rkeithhill** [comment]
I'm hoping this is something we can get out this week but it will have to be someone from the Microsoft team that publishes the update.

**Comment by tylerl0706** [comment]
@rkeithhill shall I go ahead and start getting a release ready? Are there any other issues you want to address before 1.5.1?

**Comment by rkeithhill** [comment]
There is one other issue I wanted to try to get in.  I’ll look at that tonight and see what I can do.  If not, we’ll just go with what we’ve got tomorrow.  Will that work?

I banged my head on three issues this weekend and go nowhere with any of them.  Sigh...  Maybe I'll have better luck tonight.  :-)

**Comment by tylerl0706** [comment]
Works for me! Let me know if you need a second set of eyes.

**Comment by rkeithhill** [comment]
How are you with CJK, full-width/half-width Unicode issues?  :-)  Take a look at this issue - #1036.  Copy one of the characters into the clipboard e.g `こ` and then go to the PowerShell Integrated Terminal and paste the char once.  It shows up - great!  Now paste the character again.  A new shows up but the previous char is erased.  It's not actually erased though.  If you move the cursor to the beginning of the line and press `a`, you'll see the other chars show up.  It's really weird.  And if you use the cursor to select the CJK chars when it is visible, you can select "half" the character.  

I'd be wondering if this is a VSCode terminal issue, except that when you try this in the normal "PowerShell" terminal.  It works.

**Comment by tylerl0706** [comment]
Oh wow. That's an interesting one. I see what I can dig up.

**Comment by rkeithhill** [comment]
This issue should be fixed in the upcoming 1.5.1 release.  Please re-open if it isn't.
