### ISSUE TITLE
Terminal not scrolling to the bottom when executing code

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/vscode-powershell#1085]
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T05:19:39.344Z)
- OS Version: Windows_NT x64 6.2.9200
- Extensions: PowerShell|ms-|1.5.0

Steps to Reproduce:

1. Execute code that has terminal output (PowerShell code)
2. Scroll up to see the first line of output
3. Execute the code again and notice that the terminal is not scrolled down to the bottom to see the result of the latest code run

This issue has been reported in [#18362](https://github.com/Microsoft/vscode/issues/18362) and in [#17325](https://github.com/Microsoft/vscode/issues/17325). But I don't think it's fixed or possible to set this behavior without resorting to [macro extensions](https://stackoverflow.com/questions/45175883/jump-to-bottom-of-integrated-terminal-when-running-powershell).

See [#37275](https://github.com/Microsoft/vscode/issues/37275#issuecomment-341220898) to.

**Comment by DarkLite1** [comment]
Tested this today again, with the latest insiders version:

```
 Version 1.24.0-insider
Commit d29620f2ba89327f51bb6fb2f05dfdd65e2fcafe
Date 2018-05-07T08:55:27.483Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

1. In a test file paste the code `Get-Process` and hit `F5` to run it
2. In the bottom terminal scroll upwards
3. Run the test file again
4. Notice the output is not scrolled down but stays where it was

**Comment by tylerl0706** [comment]
Sorry for the delay @DarkLite1! Yep this seems like a reasonable request. 👍

**Comment by DarkLite1** [comment]
Seems to be related to #1257

**Comment by tylerl0706** [comment]
@DarkLite1 you're right. I'm going to dupe this to #1257.

Give that issue a thumbs up so we can prioritize! :)

**Comment by Sharken03** [comment]
Workaround for PowerShell:
Install the [macros extension](https://github.com/geddski/macros), then define macros and keybindings as [outlined here](https://stackoverflow.com/questions/45175883/jump-to-bottom-of-integrated-terminal-when-running-powershell).
