### ISSUE TITLE
address tslint issues

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/vscode-powershell#1086]
After talking to @TravisEz13, we need to address all tslint issues for compliance.

**Comment by TravisEz13** [comment]
tslint not tslist

**Comment by rkeithhill** [comment]
Um, there are a **lot** of tslint issues if you go with the `tslint:recommended` rules.

**Comment by TravisEz13** [comment]
@rkeithhill feel free to recommend rules that we should not address.  We have a requirement that we run TSLint though.

**Comment by rkeithhill** [comment]
I've started this work on branch - https://github.com/PowerShell/vscode-powershell/tree/rkeithhill/enable-tslint

**Comment by rkeithhill** [comment]
I've merged in a PR to address the vast majority of these.  There are just two left.  I think in this case:

![image](https://user-images.githubusercontent.com/5177512/35258311-ac19039c-ffbb-11e7-9300-30800c05c5ed.png)

I'm just going to suppress the rule on that line of code.
