### ISSUE TITLE
Separate PSEditorServicesBuild into a separate release build

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#1087]
This line https://github.com/PowerShell/vscode-powershell/blob/master/tools/releaseBuild/images/microsoft_windowsservercore/Build.ps1#L23 shows that we are building PowerShellEditorServices along with the extension for our release build.

It is a best practice to separate these into separate builds. This is also for compliance.

**Comment by rjmholt** [comment]
This is now done I think :)
