### ISSUE TITLE
CodeLens is not finding references to function names with scope qualifiers

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#1089]
### System Details

- Operating system name and version: Windows 10 FCU
- VS Code version: 1.17.2
- PowerShell extension version: 1.5.0
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.16299.19
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.19
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I'm seeing this in the PowerShell repo's build.psm1 module.  It has a function declared like so `function script:precheck([string]$command, [string]$missedMessage)` and it says it has 0 references which I know to be not true.  I believe the `script:` is throwing off CodeLens.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by andschwa** [comment]
Oh, I can fix this.
