### ISSUE TITLE
Powershell syntax highlight suggestion: string -format, the  {0} should be highlighted

### ISSUE THREAD

**Issue by aeschli** [PowerShell/vscode-powershell#1096]
_From @DoTheEvo on November 1, 2017 17:3_

![showit](https://i.imgur.com/qDjqP0q.png)

[many ways](https://kevinmarquette.github.io/2017-01-13-powershell-variable-substitution-in-strings/) to concatenate strings in powershell.

Relatively newer but becoming popular one is format string where {0} {1} {2}.. are treated as placeholders inside string. 

Would be great if they would be highlighted as such.

_Copied from original issue: Microsoft/vscode#37425_

**Comment by rkeithhill** [comment]
Sorry to redirect you again but can you post this on the EditorSyntax repo?  This is the repo that handles syntax highlighting for all editors, including VSCode - https://github.com/powershell/editorsyntax
