### ISSUE TITLE
I am experiencing a problem with Clear-Host

### ISSUE THREAD

**Issue by TheFitITGuy** [PowerShell/vscode-powershell#1097]
I am trying to clear the host using the cmdlet Clear-host and I am still able to scroll up and see previous output in the console. 

code -v 
1.17.2
b813d12980308015bcd2b3a2f6efa5c810c33ba5

$pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      0      0       

code --list-extensions --show-versions
eamodio.gitlens@5.7.1
ms-vscode.PowerShell@1.5.0

$PSVersionTable

Name                           Value                                                                                
----                           -----                                                                                
PSVersion                      5.1.14393.1770                                                                       
PSEdition                      Desktop                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                              
BuildVersion                   10.0.14393.1770                                                                      
CLRVersion                     4.0.30319.42000                                                                      
WSManStackVersion              3.0                                                                                  
PSRemotingProtocolVersion      2.3                                                                                  
SerializationVersion           1.1.0.1

**Comment by TheFitITGuy** [comment]
New version fixed this.

**Comment by TheFitITGuy** [comment]
code -v 
1.18.0
dcee2202709a4f223185514b9275aa4229841aa7


$pseditor.EditorServicesVersion
would not run 

code --list-extensions --show-versions
eamodio.gitlens@6.0.0
ms-vscode.PowerShell@1.5.0

$PSVersionTable

Name                           Value                                                                                
----                           -----                                                                                
PSVersion                      5.1.14393.1770                                                                       
PSEdition                      Desktop                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                              
BuildVersion                   10.0.14393.1770                                                                      
CLRVersion                     4.0.30319.42000                                                                      
WSManStackVersion              3.0                                                                                  
PSRemotingProtocolVersion      2.3                                                                                  
SerializationVersion           1.1.0.1

**Comment by rkeithhill** [comment]
Are you sure you're in the `PowerShell Integrated Console`?  This works for me there.  If you try this from the default `PowerShell` terminal, it won't work.  That terminal has no connection back to PowerShell extension.

**Comment by TheFitITGuy** [comment]
It's clearing only part of the output. Not all. I wasn't able to get it to work in either the default powershell terminal or the integrated console. I was able to replicate on two different computers

**Comment by TheFitITGuy** [comment]
I have attached a zipped file of the screen recording replicating my error in PowerShell Integrated Console. 
[Recording #1.zip](https://github.com/PowerShell/vscode-powershell/files/1463106/Recording.1.zip)

**Comment by rkeithhill** [comment]
Sorry must have misread your original post.  Anyway, I don't believe there is much the PowerShell extension can do.  The terminal infrastructure in VSCode is most likely the culprit and there are a number of issues that have been submitted on it - including this one - https://github.com/Microsoft/vscode/issues/30638.  I suggest you up-vote this issue and others like it in the VSCode repo.
