### ISSUE TITLE
Feature request: On/Off toggle for the Script Analyzer

### ISSUE THREAD

**Issue by MaxTrinidad** [PowerShell/vscode-powershell#11]
By default 'ON' but would be nice to be able to turned it 'OFF'.

**Comment by daviwil** [comment]
Thanks Max!  I agree, I'll add a setting to turn script analysis off.

**Comment by daviwil** [comment]
I've added a new setting to the PowerShell extension to allow you to enable or disable the use of Script Analyzer.  To turn off Script Analyzer, click `File -> Preferences -> User Settings` and paste the following line into your settings file (the pane that opens on the right side).

`"powershell.scriptAnalysis.enable": false`

This change will be included with the 0.1.1 release which should be out in the next couple of days.
