### ISSUE TITLE
Can't install 1.5.0 on VSCODE 1.18.0

### ISSUE THREAD

**Issue by simulot** [PowerShell/vscode-powershell#1102]
### System Details

- Operating system name and version: 2008 Entreprise R2 SP1
- VS Code version: 1.18.0
- PowerShell extension version: 1.5.0
- Output from `$PSVersionTable`: 

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
1.18.0
dcee2202709a4f223185514b9275aa4229841aa7
PS D:\WeBuy> $PSVersionTable

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

code --list-extensions --show-versions
DotJoshJohnson.xml@1.9.2
eamodio.gitlens@5.6.4
ms-vscode.PowerShell@1.4.3

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.36415
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with installing 1.5.0 using VSIX file on a server not connected to internet. In need to use this version because of Extension TIMEOUT. 
Logs shows time out issue.

So I have put PowerShell-1.5.0.vsix file on this machine and used the ...> Install from a VSIX menu of extension view. Nothing visible happens, nothing is written to logs, and of course, the extension isn't loaded.

So I can't use this extension on the remote machine I have to use at work.

### Attached Logs
[1510764494-df1e0cf2-1169-4ec2-acd2-bfde67dc83471510763976816.zip](https://github.com/PowerShell/vscode-powershell/files/1475582/1510764494-df1e0cf2-1169-4ec2-acd2-bfde67dc83471510763976816.zip)
[DebugAdapter.log](https://github.com/PowerShell/vscode-powershell/files/1475583/DebugAdapter.log)

**Comment by Carlton2001** [comment]
Same here with fresh install of vscode 1.18.1 and the 1.5.1 VSIX file.

**Comment by DonPwrShellHunt** [comment]
I've also had problems installing 1.5.1 from the VSIX file on a system not connected to the internet. As a work around I first install 1.5.1 on an internet connected machine, and copy the ms-vscode.powershell-1.5.1 extensions directory to a USB device. Installation on the disconnected system is then just a directory copy to the extemsions directoy. The VSIX install method would obviously be better, so attention to this issue would be appreciated.

**Comment by tylerl0706** [comment]
I'm curious, have you had any luck installing other VSIX's for VSCode without internet?

I just want to rule out the possibility that it could be a VSCode (itself) issue.

**Comment by DonPwrShellHunt** [comment]
I installed at least five other VSIX's just fine during the session where I encountered the powershell extension VSIX issue. I tried the VSIX extension install via the GUI, and using the code command line options. (same result either way)

**Comment by tylerl0706** [comment]
Thanks for the info! I'll look into this.

**Comment by rkeithhill** [comment]
This is a consequence of us updating to the newer debug protocol.  That requires you to be on VSCode 1.19.0.  From the package.json file:
```
  "engines": {
    "vscode": "^1.19.0"
  },
```
This is why we "try" not to snap to a new VSCode engine version without waiting for a few releases (ie we try to support VS Code current version and the previous version).  In this case, the VSCode folks changed the debug protocol such that it would break PowerShell debugging if we didn't snap to that version in 1.19.0  Hence the 1.19.0 min version.

**Comment by rkeithhill** [comment]
Nevermind, 1.5.x has a min version of `1.17.0`.  I was looking at `master` instead of the 1.5.x tags.

**Comment by simulot** [comment]
I have check extenstion v1.6.0 with VSCode 1.21.1, and it works.
