### ISSUE TITLE
Sample tasks.json seems to be outdated

### ISSUE THREAD

**Issue by lipkau** [PowerShell/vscode-powershell#1111]
Hi there..

I am using this example in my project, and VS Code highlights a lot of "problems" in the file:
https://github.com/PowerShell/vscode-powershell/blob/3a929b0a38164ab6fe3da6762c09481c4f6ae3a4/examples/.vscode/tasks.json
![image](https://user-images.githubusercontent.com/4992870/33377987-ae7303d6-d513-11e7-9f11-112b315f9c5e.png)

BR
Oliver

**Comment by rkeithhill** [comment]
@lipkau can you take this version of tasks.json for a spin and see how it works for you - https://github.com/PowerShell/vscode-powershell/blob/master/examples/.vscode/tasks.json

**Comment by lipkau** [comment]
sorry for the delayed response. looks perfect from what I can tell
