### ISSUE TITLE
Debug adapter crashes trying to restore breakpoints on non-available network location

### ISSUE THREAD

**Issue by sba923** [PowerShell/vscode-powershell#1114]
I had a debugging session with a script accessed via the Remote Desktop network redirector (`\\tsclient\s\...`)

On the next day, I was unable to debug another (local) script, because the Debug Adapter would (apparently) try to restore breakpoints on the other (network) script, and the network location was no longer available.

In order to recover from that situation, I had to close VSCode, delete the `file__0.localstorage` SQLite database file, and start VSCode again.

Attached:
- a screenshot of the error ![2017-11-27 14_10_31-df ps1 - powershell - visual studio code](https://user-images.githubusercontent.com/12860484/33523304-918619b4-d803-11e7-9951-168425397de9.png)
- the extension logs in [1511791278-2cc94bad-489f-4bc5-bdfa-8565c8afb9a61511791275747.zip](https://github.com/PowerShell/vscode-powershell/files/1524558/1511791278-2cc94bad-489f-4bc5-bdfa-8565c8afb9a61511791275747.zip)
- the `file__0.localstorage` file in [file__0.zip](https://github.com/PowerShell/vscode-powershell/files/1524553/file__0.zip)

**Comment by tylerl0706** [comment]
Thesis for reporting this!

**Comment by rkeithhill** [comment]
I have a PR pending in PSES to fix this.

**Comment by sba923** [comment]
Great! Now we're just have to wait for 1.5.2 to be released...
