### ISSUE TITLE
Debug Autos Variable View Showing Almost All Variables in Session

### ISSUE THREAD

**Issue by grumpkin** [PowerShell/vscode-powershell#1116]
## Issue Description ##

I updated to version 1.5.1 recently (as well as VSCode to 1.18.1) and now the Auto variables when debugging seem to just have almost every variable in the session whereas before it was definitely 'smarter' and it would only show mostly relevant variables. It's just really cluttered now and makes finding the relevant variables difficult. Don't know if this is an issue with VSCode or the PS extension.

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.14393 |
| VSCode | 1.18.1|
| PowerShell Extension Version | 1.5.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.14393.1884|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.14393.1884|
|BuildVersion|10.0.14393.1884|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azurerm-vscode-tools|msazurermtools|0.3.7|
|Material-theme|zhuangtongfa|2.10.23|
|nord-visual-studio-code|arcticicestudio|0.6.0|
|PowerShell|ms-vscode|1.5.1|
|vscode-great-icons|emmanuelbeziat|2.1.20|;

</details>

**Comment by rkeithhill** [comment]
This is currently "by-design".  In part of our efforts to make the debugger behave more like the ISE debugger, your script is dot sourced into the PowerShell Integrated Console when you start debugging.  You can see this after the debug session ends.  All the script scope variables are still available.  So the script scope variables are essentially global variables.  What you are seeing are all the global scope variables in Auto.  If you step into a function, `Auto` should be much more useful.

**Comment by SydneyhSmith** [comment]
Closing as resolved.
