### ISSUE TITLE
Debugging with F5 doesn't output write-error output for script parameter

### ISSUE THREAD

**Issue by johndog** [PowerShell/vscode-powershell#1120]
## Issue Description ##

If I run a script with the following contents from the command-line, without providing a parameter:

```
param($branch = $(write-error "[branch] required"))
"hello world"
```

It will write the "[branch] required" error message, followed by "hello world."

If I use F5 in Code, only "hello world" is output.

The former is expected, the latter is unexpected.  Where is the "write-error" message going?

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT ia32 10.0.17035 |
| VSCode | 1.18.1|
| PowerShell Extension Version | 1.5.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17035.1000|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17035.1000|
|BuildVersion|10.0.17035.1000|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.13.1|
|dominoscript|Microsoft|0.0.2|
|markdown-mermaid|bierner|0.1.1|
|PowerShell|ms-vscode|1.5.1|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|vscode-mermaid-preview|vstirbu|0.8.2|;

</details>

**Comment by tylerl0706** [comment]
@johndog  Thanks for this! Just to clarify, are you hitting on F5 against the context of your script?
like this is what's in your editor
```
param($branch = $(write-error "[branch] required"))
"hello world"
```
and then you hit F5?

If so, (@rkeithhill and @daviwil can correct me if I'm wrong) this is different than what the ISE does. The ISE does throw an error, VSCode doesn't... and an interesting part is, powershell.exe doesn't throw an error when running:
```
param($branch = $(write-error "[branch] required")); "hello world"
```

I'm guessing the difference is that VSCode runs the contents of the file while the ISE might run the actual script itself. Just a hunch. I'd have to look deeper. Thanks again for the report!

**Comment by rkeithhill** [comment]
That's probably what the issue.  Yet another reason to not dot source scripts when debugging them.  The other is that the `Auto` variables window is kind of useless at script scope because when the script is dot sourced that becomes the global scope.  If there's a useful scenario for dot sourcing perhaps we make that a debug setting - that is off by default.

**Comment by JustinGrote** [comment]
Assuming F5 is supposed to be "run current file" debug task, this looks like it is fixed @SydneyhSmith @TylerLeonhardt 
![image](https://user-images.githubusercontent.com/15258962/80020070-4caeca00-848d-11ea-8459-677e7ee70e68.png)

It doesn't work in F5 "Interactive Mode" + F8, but that's expected.
