### ISSUE TITLE
Issue with Using Module when using PowerShell 6.0

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/vscode-powershell#1121]
## Issue Description ##

I am experiencing a problem with Using Module when switching the plugin to use PowerShell 6.0, it gets an error saying "Could not find the module <MODULE_NAME>". This also prevents me from running pester tests from within VS Code. Is PowerShell 6.0 not yet supported within the plugin?

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.15063 |
| VSCode | 1.18.1|
| PowerShell Extension Version | 1.5.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|6.0.0-rc|
|PSEdition|Core|
|GitCommitId|v6.0.0-rc|
|OS|Microsoft Windows 10.0.15063 |
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0-rc|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|1.5.1|
|markdown-all-in-one|yzhang|0.11.2|
|mssql|ms-mssql|1.2.1|
|PowerShell|ms-vscode|1.5.1|
|vscode-eslint|dbaeumer|1.4.3|
|xml|DotJoshJohnson|1.9.2|;

</details>

**Comment by rkeithhill** [comment]
Yes, the extension support PowerShell Core - with issues but this isn't one of them. PowerShell Core loads modules from a different path such that modules installed by Windows PowerShell aren't visible to PowerShell Core.  See - https://github.com/PowerShell/PowerShell/issues/4056

You can either install these modules into PowerShell Core or install the [WindowsPSModulePath](https://www.powershellgallery.com/packages/WindowsPSModulePath/1.0.0) module into PowerShell Core which will allow it to import modules from the Windows PowerShell module paths.

**Comment by LethiferousMoose** [comment]
My modules work just fine in PowerShell Core. My profile appends them to the PSModulePath. The only place they do not work is in the plugin.

**Comment by LethiferousMoose** [comment]
I found my issue, I have my modules added via the PowerShell profile. Which I was expecting to work if I enabled "powershell.enableProfileLoading" but it appears that setting does not work in the PowerShell Integrated Console.
