### ISSUE TITLE
Using enableProfileLoading to modify PSModulePath does not persist.

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/vscode-powershell#1122]
## Issue Description ##

If I enable profile loading and in a profile put the line
`$Env:PSModulePath = $Env:PSModulePath + ';<CUSTOM_PATH>'` and launch VS Code, after the integrated terminal loads, the new path does not exist and `C:\Users\<User>\.vscode\extensions\ms-vscode.powershell-1.5.1\modules` is missing. Note that other environment variables I set still exist.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.15063 |
| VSCode | 1.18.1|
| PowerShell Extension Version | 1.5.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|6.0.0-rc|
|PSEdition|Core|
|GitCommitId|v6.0.0-rc|
|OS|Microsoft Windows 10.0.15063 |
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0-rc|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|1.5.1|
|markdown-all-in-one|yzhang|0.11.2|
|mssql|ms-mssql|1.2.1|
|PowerShell|ms-vscode|1.5.1|
|vscode-eslint|dbaeumer|1.4.3|
|xml|DotJoshJohnson|1.9.2|;

</details>

**Comment by tylerl0706** [comment]
Hi there, thanks for this! Can you tell me which profile you're adding this line to?

I believe (@rkeithhill + @daviwil please correct me if I'm wrong), the extension only loads:

 $PROFILE.AllUsersAllHosts
and
$PROFILE.CurrentUserAllHosts

if you specify `enableProfileLoading`. Can you make sure that you're adding that line to one of these profiles?

**Comment by rkeithhill** [comment]
It should also load the `CurrentHost` versions - `Microsoft.VSCode_profile.ps1` e.g.:
```
2:147ms> $profile | fl * -force

AllUsersAllHosts       : C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1
AllUsersCurrentHost    : C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.VSCode_profile.ps1
CurrentUserAllHosts    : C:\Users\Keith\Documents\WindowsPowerShell\profile.ps1
CurrentUserCurrentHost : C:\Users\Keith\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1
Length          
```

And I can't repro this. If I put the following into the `CurrentUserCurrentHost` profile:
```posh
Write-Warning "Executing $($MyInvocation.MyCommand.Name)"
$env:PSModulePath = $env:PSModulePath + ";c:\ModulePath"
```
and then restart my session, I get this:
```
PowerShell Integrated Console

WARNING: Executing Microsoft.VSCode_profile.ps1
[master ≡] ~\GitHub\psake\psake
1:338ms>  $env:PSModulePath -split ';'
C:\Users\Keith\Documents\WindowsPowerShell\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\
C:\Users\Keith\.vscode\extensions\ms-vscode.powershell-1.5.1\modules
c:\ModulePath
```
However the bit about the extension's modification to the path being missing is troubling.  Which profile are you putting the PSModulePath modification in?

The `Start-EditorServices` PowerShell command does modify process-level PSModulePath env var. 

https://github.com/PowerShell/vscode-powershell/blob/93bc21c8167001a5701917c21aace9af6492e587/scripts/Start-EditorServices.ps1#L185-L188

I wonder if one of your profiles is accidentally whacking PSModulePath to its default??  Could you dump the contents of the four profiles listed above and see what modifications are being made to $env:PSModulePath?

**Comment by rkeithhill** [comment]
BTW one of the things I'd like to see is an init script for your workspace so that you could import just the modules needed to drive auto-completion for that workspace.  Something like `.vscode\psic-init.ps1`.

**Comment by LethiferousMoose** [comment]
@rkeithhill I am using the Microsoft.VSCode_profile.ps1 file you mentioned, in the .../Documents/PowerShell/. Also I did narrow down the issue cause. It only blows away the path when the directory I append to the PSModulePath is the same as the VS Code workspace. i.e. `$Env:PSModulePath = $Env:PSModulePath + ';C:\dev\<Workspace>'`, if I tell it a different directory, the .vscode directory persists as does my change.

**Comment by rkeithhill** [comment]
Are you sure you modifying the profile in `Documents\PowerShell` instead of the one in `Documents\WindowsPowerShell`?  I can't repro this with PS Core 6.0.0-rc.  

BTW, init script has been discussed here #190 and #880.

**Comment by LethiferousMoose** [comment]
Yes I am modifying the correct file. I am going to do some more testing on my end. It looks like it might be related to my workspace in particular, perhaps it's related to some setting or something with Git.

**Comment by LethiferousMoose** [comment]
Well I have no idea what is going on. If I copy my entire directory tree to a new location and open the workspace on the copy, the issue does not happen. Why the current location causes this weird defect occur is beyond me. Hopefully this is some kind of fluke and it won't happen to anyone else, but I'd really love to know what makes it happen...

**Comment by rkeithhill** [comment]
Is that directory a junction/mount point or anything else weird like that?  The other thing that would be good to know is if this happens in pure PowerShell Core - no VSCode.

**Comment by LethiferousMoose** [comment]
Nothing special about it that I can think of. It's just a folder I created to check out repos from my Stash/Bitbucket Server profile. Do you mean using a regular non-VSCode PowerShell profile? It works fine, that's how I've been able to use my modules in PowerShell Core.

**Comment by LethiferousMoose** [comment]
@rkeithhill Good news! I discovered how to reproduce the issue. This only occurs if you have a User/System Environment Variable defined for PSModulePath. I had done this for PowerShell 5.1. 

I have a User Environment Variable defined for PSModulePath = C:\dev\MyRepos\Workspace via Advanced System settings -> Environment Variables, and then have an entry in the PowerShell Code VS Code profile for $Env:PSModulePath = $Env:PSModulePath + ';C:\dev\MyRepos\Workspace'. I have tested this on a new machine and the issue is repeatable.

**Comment by tylerl0706** [comment]
Fascinating... did you ever try this in the ISE to see what happens?

**Comment by LethiferousMoose** [comment]
Doesn't the ISE only work with Windows PowerShell? This bug only shows up with the integrated console with PowerShell Core.

**Comment by tylerl0706** [comment]
Ah yes. My bad. You said 

> This only occurs if you have a User/System Environment Variable defined for PSModulePath. I had done this for PowerShell 5.1.

and thought the issue was with 5.1. :)

So when you remove that User/System Environment Variable the issue disappears?

**Comment by rkeithhill** [comment]
Something weird going on indeed.  AFAICT, PS Core doesn't reflect the PSModulePath change I made to my USER PATH env var.  I instrumented my PS Core MS.VSCode profile to display PSModulePath before and after and it looks like everything is fine:
```
PowerShell Integrated Console

WARNING: Executing Microsoft.VSCode_profile.ps1
WARNING: PSModulePath before - C:\Users\Keith\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\6.0.0-rc\Modules;C:\Users\Keith\.vscode\extensions\ms-vscode.powershell-1.5.1\modules
WARNING: PSModulePath after - C:\Users\Keith\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\6.0.0-rc\Modules;C:\Users\Keith\.vscode\extensions\ms-vscode.powershell-1.5.1\modules;C:\tmp\workspace
```
But when I inspect the final PSModulePath, two paths are missing:
```
PS C:\tmp\workspace> $env:PSModulePath -split ';'
C:\Users\Keith\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\powershell\6.0.0-rc\Modules
```
Hmm, time to look into this some more.

**Comment by LethiferousMoose** [comment]
@tylerl0706 Yes, removing the pre-set variable fixes the issue after you restart the console. 

@rkeithhill Yes, I was seeing the same thing, the profile has the correct value, but somewhere between there and the console fully loading the value gets defaulted back the original value. Also since PowerShell Core does not load the windows PSModulePath, I find it very strange that a system/user variable that Core is ignoring correctly (which we can see in the profile output) is somehow interfering with the integrated console and causing it to reset the value of the variable.

**Comment by rkeithhill** [comment]
OK this might be caused by PS Core:
```csharp
if (!string.IsNullOrEmpty(currentProcessModulePath) &&
    NeedToClearProcessModulePath(currentProcessModulePath, personalModulePath, sharedModulePath, runningSxS))
{
    // Clear the current process module path in the following cases
    //  - start sxs ps on windows [machine-wide env:PSModulePath will influence]
    //  - start sxs ps from full ps
    //  - start sxs ps from inbox nano/iot ps
    //  - start full ps from sxs ps
    //  - start inbox nano/iot ps from sxs ps
    currentProcessModulePath = null;
}
```
You don't normally see this problem in PS Core but with the VSCode extension, PS Core is started, a script is run to import and start PSES.  At this point the env var is correct.  However,once PSES starts executing it has to set up its PSHost UI and I "think" in the process of doing that, the above code is executed which resets the PSModulePath.  I haven't had a chance to verify this yet in the debugger.  It's a theory at this point.  If this is the case, perhaps we can stash and restore the PSModulePath in PSES.

**Comment by JustinGrote** [comment]
@SydneyhSmith @TylerLeonhardt I wasn't able to reproduce per https://github.com/PowerShell/vscode-powershell/issues/1122#issuecomment-351278779
1. Set PSMODULEPATH user environment variable
2. Add following to Microsoft.VSCode_profile.ps1 including the path of my folder workspace
```powershell
write-host -fore yellow "Before: $ENV:PSMODULEPATH"
$ENV:PSMODULEPATH = $ENV:PSMODULEPATH + ';C:\Users\JGrote\Desktop'
write-host -fore green "After: $ENV:PSMODULEPATH"
```

![image](https://user-images.githubusercontent.com/15258962/80021040-cd21fa80-848e-11ea-9975-12039eae851b.png)
