### ISSUE TITLE
Vscode incorrectly handling Powershell Param parameter

### ISSUE THREAD

**Issue by joejank** [PowerShell/vscode-powershell#1123]
In the following example:

Param (
[String] $JJDummy='/Users/joejank/Documents/log/', # default
[String] $OutDir='/Users/joejank/Documents/log/', # default
[String] $FileSelect="prompt", #default
[Switch] $DebugJJ
)
In Vscode the above resolves to:
$outdir=/Users/joejank/Documents/log/
$jjDummy=212

but works fine in powershell terminal. This seems to always to be a problem with the first parameter.

### System Details

- Operating system name and version:MACOS 10.13.2
- VS Code version:1.18.1
- PowerShell extension version:
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:
1.18.1
929bacba01ef658b873545e26034d1a8067445e9
PS /Users/joejank/Dropbox/PS> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      1      0


PS /Users/joejank/Dropbox/PS> code --list-extensions --show-versions
DavidAnson.vscode-markdownlint@0.12.0
DotJoshJohnson.xml@1.9.2
DougFinke.vscode-PSStackoverflow@0.0.2
Kipters.codeshell@0.2.2
MS-DevSkim.vscode-devskim@0.2.0
christian-kohler.npm-intellisense@1.3.0
eg2.vscode-npm-script@0.3.3
formulahendry.code-runner@0.8.5
formulahendry.terminal@0.0.10
ksubedi.net-core-project-manager@0.3.6
ms-vscode.csharp@1.13.1
ms-vscode.mono-debug@0.15.8
ms-vscode.PowerShell@1.5.1
ms-vscode.Theme-MarkdownKit@0.1.4
ms-vsts.team@1.122.0
remcoros.startanyshell@0.3.1
PS /Users/joejank/Dropbox/PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

I am experiencing a problem with...

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
I can't repro this.  Can you tell me how you are executing this script?  Debugger (F5) - if so which debug config and how is it configured or via F8 (with script selected or not?) or by executing the script file from the PowerShell Integrated Terminal?

**Comment by joejank** [comment]
Sorry please close - user error - I had an invalid launch.json file

**Comment by rkeithhill** [comment]
No problem.
