### ISSUE TITLE
Terminal: Mercurial occasionally crashes in the middle of output of certain commands

### ISSUE THREAD

**Issue by MHHenriksen** [PowerShell/vscode-powershell#1124]
### System Details

- Operating system name and version: Windows_NT ia32 10.0.16299
- VS Code version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- PowerShell extension version: 1.5.1
- Output from `$PSVersionTable`:

```
 >_  code -v
1.18.1
929bacba01ef658b873545e26034d1a8067445e9

 >_  $pseditor.EditorServicesVersion

 >_  code --list-extensions --show-versions
alefragnani.pascal@0.10.0
DotJoshJohnson.xml@1.9.2
hdg.live-html-previewer@0.3.0
humao.rest-client@0.16.1
lextudio.restructuredtext@44.0.0
lukehoban.Go@0.6.69
magicstack.MagicPython@1.0.12
mrcrowl.hg@1.2.3
ms-python.python@0.8.0
ms-vscode.cpptools@0.14.4
ms-vscode.csharp@1.13.1
ms-vscode.PowerShell@1.5.1
PeterJausovec.vscode-docker@0.0.22
pflannery.vscode-versionlens@0.19.1
qub.qub-msbuild@0.6.3
redhat.java@0.15.0
slevesque.vscode-hexdump@1.6.0
vivainio.robotframework@0.1.3
vscjava.vscode-java-debug@0.4.0
vscjava.vscode-java-pack@0.2.0

 >_  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.64
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.64
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


```

### Issue Description

Originally reported at https://github.com/Microsoft/vscode/issues/38938

Mercurial occasionally crashes in the middle of output of certain commands, especially log and diff, with the following error:
```
** unknown exception encountered, please report by visiting
** https://mercurial-scm.org/wiki/BugTracker
** Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
** Mercurial Distributed SCM (version 4.3.1)
** Extensions loaded: purge, rebase, record, strip, extdiff, highlight, shelve, largefiles, share, show, convert, amend
Traceback (most recent call last):
  File "hg", line 45, in <module>
  File "mercurial\dispatch.pyc", line 81, in run
  File "mercurial\dispatch.pyc", line 185, in dispatch
  File "mercurial\ui.pyc", line 914, in flush
  File "mercurial\windows.pyc", line 180, in flush
ValueError: I/O operation on closed file
```
I have not reported this to the Mercurial bugtracker as the error suggests, as it seems more likely to me to be caused by the vscode integrated terminal closing stdout too soon. I never see this error in a plain Powershell terminal.

Steps to Reproduce:

1. Have Mercurial installed (I'm using 4.3.1)
2. Open in VS Code a Mercurial repo with a little history to it, or some working dir changes
3. Open a Terminal tab (I use Powershell)
4. run `hg diff` and/or `hg log` (it may take a few tries). `hg help config` can also trigger it rarely, but it seems to have a better chance of failing the longer the command takes to print the results.

### Attached Logs
[1513168189-f00d2d44-e646-4fea-aa24-f90f6602560d1513168144751.zip](https://github.com/PowerShell/vscode-powershell/files/1555469/1513168189-f00d2d44-e646-4fea-aa24-f90f6602560d1513168144751.zip)

**Comment by MHHenriksen** [comment]
I also want to point out that this happens even with the PowerShell extension disabled, and just using the standard integrated terminal. But I was asked by the vscode team to post the issue here. I'm assuming this is because parts of the integrated terminar are shared between core vscode and this extension?

**Comment by rkeithhill** [comment]
Sorry to redirect you again but you should submit this issue to https://windowsserver.uservoice.com/forums/301869-powershell

If you can reproduce the issue in PowerShell Core, you'll have a better response submitting the issue to the PowerShell Core project on GitHub - https://github.com/powershell/powershell/issues.
