### ISSUE TITLE
Run Pester tests with custom Pester module location

### ISSUE THREAD

**Issue by Xoph** [PowerShell/vscode-powershell#1128]
### System Details

- Operating system name and version: Windows 7 64-bit
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
PS> code -v
1.18.1
929bacba01ef658b873545e26034d1a8067445e9

PS> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      1      0

PS> code --list-extensions --show-versions
DavidAnson.vscode-markdownlint@0.12.0
ms-vscode.csharp@1.13.1
ms-vscode.PowerShell@1.5.1
ms-vscode.Theme-MarkdownKit@0.1.4
Pendrica.chef@0.6.4
slevesque.perforce@3.0.0
stevejpurves.cucumber@0.9.6

PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.36415
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


```

### Issue Description

We have Pester in our source control, so the location of the Pester modules changes each release. Is there a way to change the command used to invoke Pester tests when clicking the Run tests button so that we can import the Pester module from a location relative to the current open folder?

Thank you,
Christoph Griesshammer
GE Healthcare

**Comment by rkeithhill** [comment]
The best you can do for now is to make sure that version of Pester is already imported.  You can use the PowerShell VSCode profile (~\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1) to import your version of the module.

Eventually what we want (I think) is a workspace specific initialization script that you can use to import the modules that particular workspace needs.

**Comment by Xoph** [comment]
OK, I had found documentation of that before, but didn't know if there was anything better I could do.

That profile script will only run when I first open VS Code, correct? I guess I'll just import the modules for our latest branch and call it a day.

**Comment by rkeithhill** [comment]
> That profile script will only run when I first open VS Code, correct? 

Correct.

**Comment by Xoph** [comment]
Airtight. I guess this can be closed then. Unless it stays as a feature
request but I suspect something like that is already a feature request.
Thank you!

**Comment by rkeithhill** [comment]
Yes and please feel free to chime in on the issue #190
