### ISSUE TITLE
Hashtag "#" in path breaks intellisence

### ISSUE THREAD

**Issue by weinand** [PowerShell/vscode-powershell#1129]
_From @kristjan-halldorsson on December 20, 2017 10:29_

- VSCode Version: 1.19.0
- OS Version: Windows 10

I'm working with powershell scripts.

Steps to Reproduce:

1. Put a hashtag "#" in the path where the source code is. Ex. "C:\\#temp\source\..."
2. Try the intellisence, it won't work. Loading symbols won't work either (CTRL+SHIFT+O and CTRL+T).

Reproduces without extensions: Didn't try it
Only have one extension: Powershell 1.5.1

_Copied from original issue: Microsoft/vscode#40568_

**Comment by tylerl0706** [comment]
Thanks for this! I'm having a hard time reproing the issue:
<img width="517" alt="screen shot 2017-12-20 at 9 26 58 am" src="https://user-images.githubusercontent.com/2644648/34211756-17bbf7b2-e568-11e7-82ae-3848c74ef923.png">
<img width="591" alt="screen shot 2017-12-20 at 9 27 14 am" src="https://user-images.githubusercontent.com/2644648/34211782-24e7ed2e-e568-11e7-8548-c178260a9ffe.png">

Can you elaborate on the repro steps a bit so I can get a sense of how you're running into this issue?

**Comment by kristjan-halldorsson** [comment]
Hello Tyler.

Yes I can explain.
If you open some powershell script that includes some functions and objects
then you have code intellisence when you type. Like this:
[image: Inline image 8]
In this example I have a hashtable and I get the members of it when I press
the dot ".", or CTRL+space.

If I press CTRL+SHIFT+O then I get this symbol list:
 [image: Inline image 13]
And if I press CTRL+T then I get this list:
[image: Inline image 14]
The path to that "VerifyReferences.ps1" file is like this:
"C:\src\_m\BuildSystem\EscrowScripts" (NO HASHTAG IN THE PATH)
[image: Inline image 15]


*WITH NEW PATH*

Now I close Studio Code and rename the folder "EscrowScripts" to
"#EscrowScripts". Like this:
[image: Inline image 16]
The new file path is like this: "C:\src\_m\BuildSystem\#EscrowScripts"
(WITH HASHTAG IN THE PATH)

Now when I do the same as before with the hash table:
[image: Inline image 10]
When I press the dot "." after $dict I get nothing. And when I press
CTRL+space I get a list of every variable, which has nothing to do with the
object I'm interacting with.

If I press CTRL+SHIFT+O then I get this symbol list:
 [image: Inline image 11]
And if I press CTRL+T then I get this list:
[image: Inline image 12]

I have tested this on 2 other machines (my co-workers). Always get the same
resolution. The hashtag in the path breaks the intellisence on all machines.

Regards,
Kristjan Halldorsson

**Comment by kristjan-halldorsson** [comment]
The screenshots did not go through to the website. Can you maybe see them in the email I sent?

**Comment by tylerl0706** [comment]
@kristjan-halldorsson I don't see them in the email either :( can you upload them via the website?

**Comment by kristjan-halldorsson** [comment]
I added them to the previous comment ... but they appear as links. Don't know how I can make them appear like you did.

**Comment by kristjan-halldorsson** [comment]
Found the cause: "_**Email replies do not support Markdown**_".

Here is the whole post again.
Hello Tyler.

Yes I can explain.
If you open some powershell script that includes some functions and objects
then you have code intellisence when you type. Like this:
![image](https://user-images.githubusercontent.com/459782/34249448-ad3217ee-e631-11e7-94b9-7e9c765986f8.png)
In this example I have a hashtable and I get the members of it when I press
the dot ".", or CTRL+space.

If I press CTRL+SHIFT+O then I get this symbol list:
![image](https://user-images.githubusercontent.com/459782/34249520-eaff1306-e631-11e7-931c-904b38322a53.png)

And if I press CTRL+T then I get this list:
![image](https://user-images.githubusercontent.com/459782/34249543-fdb91294-e631-11e7-8391-12af2f1419d4.png)

The path to that "VerifyReferences.ps1" file is like this:
"C:\src\_m\BuildSystem\EscrowScripts" (NO HASHTAG IN THE PATH)
![image](https://user-images.githubusercontent.com/459782/34249569-146a7b54-e632-11e7-9fdf-8a6d7b494689.png)


*WITH NEW PATH*

Now I close Studio Code and rename the folder "EscrowScripts" to
"#EscrowScripts". Like this:
![image](https://user-images.githubusercontent.com/459782/34249582-1f111496-e632-11e7-821e-3ac188761977.png)
The new file path is like this: "C:\src\_m\BuildSystem\#EscrowScripts"
(WITH HASHTAG IN THE PATH)

Now when I do the same as before with the hash table:
![image](https://user-images.githubusercontent.com/459782/34249621-414ff950-e632-11e7-9cf1-b967a14d23ac.png)
When I press the dot "." after $dict I get nothing. And when I press
CTRL+space I get a list of every variable, which has nothing to do with the
object I'm interacting with.

If I press CTRL+SHIFT+O then I get this symbol list:
![image](https://user-images.githubusercontent.com/459782/34249634-4f9af154-e632-11e7-85d1-32d66e4a4b27.png)

And if I press CTRL+T then I get this list:
![image](https://user-images.githubusercontent.com/459782/34249645-57941660-e632-11e7-94b9-1767959bc929.png)

I have tested this on 2 other machines (my co-workers). Always get the same
resolution. The hashtag in the path breaks the intellisence on all machines.

Regards,
Kristjan Halldorsson

**Comment by kristjan-halldorsson** [comment]
Could you reproduce this?

**Comment by tylerl0706** [comment]
Hey @kristjan-halldorsson. Sorry for the delay. I think I _was_ able to repro this when you first commented. Let me give it another try.

Thanks for your detailed report and patience!

**Comment by JustinGrote** [comment]
@kristjan-halldorsson hey I've just been going back through old issues, and it looks to me like this one is fixed! If not and you still have a problem let us know!
![image](https://github.com/user-attachments/assets/21d708aa-b134-4594-be7c-513216825f91)
