### ISSUE TITLE
Cannot open existing ps1 file from integrated shell using "code filename.ps1"

### ISSUE THREAD

**Issue by JorgMU** [PowerShell/vscode-powershell#1130]
Using the following command in the integrated shell does not work.

`PS D:\src> code myFile.ps1`

Shouldn't this open the file in VSCode?

**Comment by tylerl0706** [comment]
Thanks for this! I'm having trouble repo'ing this. I've tried with the insider version:
```powershell
code-insiders ./test.ps1         # file that already exists but is not open
code-insiders test.ps1           # no ./
code-insiders ./test.ps1        # file that already exists but is already open
code-insiders ./newfile.ps1  # file that doesn't exists
code-insiders ./test2.ps1     # file that already exists but isn't in the opened folder
```

In all of these cases, the file opens in VSCode. Can you describe exactly what you're doing? I'll download the stable VSCode and give it a try.

**Comment by rkeithhill** [comment]
Works for me as well on 1.19.1.  Can you specify which OS you are using, which version of VSCode and copy the output from `$PSVersionTable` here? 

FWIW, this feature is provided by VSCode and not the PowerShell extension.  You can run this command from a CMD prompt or an external PowerShell console to fire up VSCode with that file open.

**Comment by JorgMU** [comment]
Where does the 'code-insiders' command come from? From a CMD prompt I just type: code filename.ps1

Here is what I get if I try 'code-insiders' with a file that exists in the current directory:

PS D:\bba-gbe\bbaExtractor> code-insiders .\doAllAbove.ps1
code-insiders : The term 'code-insiders' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ code-insiders .\doAllAbove.ps1
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (code-insiders:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

And here is my $PSVersionTable:

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I assume the problem is that I am using the desktop version of PowerShell with VSCode and the integrated shell.

Thanks,

Jorg

Erik 'Jorg' Jorgensen
Support Systems Administrator - Principal
Vended Applications Support Services
Division of IT
University of Missouri - Columbia
jorgie@missouri.edu<mailto:jorgie@missouri.edu>
573.882.5974
"I need applause." - Jerry Lewis, 1926 - 2017, R.I.P.

**Comment by rkeithhill** [comment]
The `code-insiders` command will not work unless you have [VSCode-Insiders](https://code.visualstudio.com/insiders/) installed.  This is roughly daily build of VSCode - not a stable build of the product.

> I assume the problem is that I am using the desktop version of PowerShell with VSCode and the integrated shell.

Nope.  I'm using that configuration and it works fine for me.  When you say "code myFile.ps1 doesn't work", in what way does it fail?  Do you get any error message like you got with code-insiders.  Or does it just silently fail?  Also, what version of VSCode are you on and are you on the 32-bit or 64-bit version?

**Comment by JorgMU** [comment]
Ok, you can make this issue as unrelated to the project.

Even though I was able to launch VS Code by typing "code filename.txt" from the Start Menu, the Run dialog, or a CMD window, for some reason when I did it from within any PowerShell console, it was trying to launch a d:\bin\code, which was an old version of VS Code from more than a year ago. Why it found that version from within PowerShell, and not anywhere else, I do not know, but once I removed the old executable, things started working.

Thank you for your help!

Jorg

Erik 'Jorg' Jorgensen
Support Systems Administrator - Principal
Vended Applications Support Services
Division of IT
University of Missouri - Columbia
jorgie@missouri.edu<mailto:jorgie@missouri.edu>
573.882.5974
"I need applause." - Jerry Lewis, 1926 - 2017, R.I.P.

**Comment by rkeithhill** [comment]
Glad you got it figured out!  Thanks for replying back here.
