### ISSUE TITLE
Viewing the working tree on 2012 R2 crashes the PowerShell session

### ISSUE THREAD

**Issue by jonathanmedd** [PowerShell/vscode-powershell#1132]
### System Details

- Operating system name and version: Microsoft Windows Server 2012 R2 Datacenter (6.3.9600)
- VS Code version: 1.19.1
- PowerShell extension version: 1.5.1
- Output from `$PSVersionTable`:

```
VersionName                    Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.34209
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When viewing the changes in the Working Tree view of a modified file, the PowerShell session crashes. This only seems to happen on Windows Server 2012, can't seem to reproduce it on Windows 10

![image](https://user-images.githubusercontent.com/4677545/34296427-a525bd42-e70a-11e7-9085-f0404675d97f.png)

![image](https://user-images.githubusercontent.com/4677545/34296395-79d2d10c-e70a-11e7-8831-cee115c6b457.png)

### Attached Logs

[CrashLogs.zip](https://github.com/PowerShell/vscode-powershell/files/1582361/CrashLogs.zip)

**Comment by lafe** [comment]
The same issue also occurs on Windows Server 2008 R2.
- Operating system name and version: Windows Server 2008 R2 Enterprise (6.1.7601; SP1)
- VS Code version: 1.21.0-insider (x64, Commit 70e020b2377f12894ca11254548ce365a0e435f1)
- PowerShell extension version: 1.5.1
- Output from `$PSVersionTable`:
   ```
   Name                           Value
   ----                           -----
   PSVersion                      3.0
   WSManStackVersion              3.0
   SerializationVersion           1.1.0.1
   CLRVersion                     4.0.30319.42000
   BuildVersion                   6.2.9200.22198
   PSCompatibleVersions           {1.0, 2.0, 3.0}
   PSRemotingProtocolVersion      2.2
   ```

**Comment by rkeithhill** [comment]
The log file indicates a PathTooLongException.  I think this might be caused by VSCode giving us a special type of path for these Git diff windows.

**Comment by tylerl0706** [comment]
Ok, this must be the same issue as #1195, I'm going to dupe it to that. Let me know if you see otherwise!
