### ISSUE TITLE
unable to import Microsoft.PowerShell.Core Module

### ISSUE THREAD

**Issue by srinivaspmm** [PowerShell/vscode-powershell#1140]
### System Details

- Operating system name and version:  window 7 Enterprise SP1
- VS Code version:
- PowerShell extension version:  
- Output from `$PSVersionTable`:
   Name                                  Value
   ----                                   -----
  PSVersion                      5.0.10586.117
 PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion-------------- g
code --list-extensions --show-versions
$PSVersionTable
```
Name                                  Value
   ----                                   -----
  PSVersion                      5.0.10586.117
 PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description
Unble to Load  "Import-Module Microsoft.PowerShell.Core"  Module
I am experiencing a problem with...

### Attached Logs

PS D:\Users\masrinivas> Import-Module Microsoft.PowerShell.Core
Import-Module : The specified module 'Microsoft.PowerShell.Core' was not loaded because no valid module file was found
in any module directory.
At line:1 char:1
+ Import-Module Microsoft.PowerShell.Core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Microsoft.PowerShell.Core:String) [Import-Module], FileNotFoundExc
   eption
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
[powershell_core_modulel.log](https://github.com/PowerShell/vscode-powershell/files/1593043/powershell_core_modulel.log)

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by tylerl0706** [comment]
Thanks for the report, @srinivaspmm! 

Two questions:
Does this happen when you run it in the Integrated Console?
does it also happen when you run it in `PowerShell.exe`?

**Comment by rkeithhill** [comment]
Um, why are you trying to import `Microsoft.PowerShell.Core`?  This module is special - it is always loaded by PowerShell.  In fact, the `Import-Module` command itself is implemented in this module.

BTW the import fails in the same way in both Windows PowerShell and PowerShell Core.  I'm closing this as this is not an issue with the VSCode extension for PowerShell.
