### ISSUE TITLE
unable to see the task in Task Scheduler library list

### ISSUE THREAD

**Issue by srinivaspmm** [PowerShell/vscode-powershell#1142]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I created following task

PS D:\Users\masrinivas> $T = New-JobTrigger -Weekly -DaysOfWeek 1 -At 4:00PM
Register-ScheduledJob -Name AutoRestart1 -FilePath "D:\powershellscript\AutoRestart.ps1" -Trigger $T

Id         Name            JobTriggers     Command                                  Enabled   
--         ----            -----------     -------                                  -------   
5          AutoRestart1    1               D:\powershellscript\AutoRestart.ps1      True    

 **"but uanble to see the task in Task Scheduler library list "**

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
I don't believe this any sort of issue with the PowerShell extension for VSCode.  That said, PS scheduled jobs show up in a different location in the Task Scheduler UI:

![image](https://user-images.githubusercontent.com/5177512/34496050-3a37823c-efb5-11e7-9a90-a88ad04f4e45.png)

Look under `Task Scheduler (Local)\Task Scheduler Library\Microsoft\Windows\PowerShell\ScheduledJobs`.
