### ISSUE TITLE
unable to use New-ScheduledTaskAction cmdlet  under windows 7 enterprise sp1

### ISSUE THREAD

**Issue by srinivaspmm** [PowerShell/vscode-powershell#1144]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am unable to use New-ScheduledTaskAction cmdlet getting following error

PS D:\Users\masrinivas> $A =New-ScheduledTaskAction -Execute "Taskmgr.exe"
New-ScheduledTaskAction : The term 'New-ScheduledTaskAction' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:5
+ $A =New-ScheduledTaskAction -Execute "Taskmgr.exe"
+     ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-ScheduledTaskAction:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Is windows 7 Enterprise will support  this ?
Is up-gradation of Power shell from 2.0 to 5.0 is not showing any impact
### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
This is not a PowerShell extension for VSCode issue.  I suggest that you search https://StackOverflow.com for answers to questions like this.  See - https://stackoverflow.com/questions/32960388/creating-a-scheduled-task-on-windows-7-using-powershell-4/41227959#41227959

And yeah, that command is not supported on Windows 7.
