### ISSUE TITLE
PowerShell Integrated Terminal Issue

### ISSUE THREAD

**Issue by GHRoss** [PowerShell/vscode-powershell#1146]
### System Details

- Operating system name and version: MacOS High Sierra 10.13.2
- VS Code version: 1.19.1
- PowerShell extension version: 1.5.1
- Output from `$PSVersionTable`: 

PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.3...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

1.19.1
0759f77bb8d86658bc935a10a64f6182c5a1eeba
x64
1      5      1      0

### Issue Description

I am experiencing a problem with the integrated terminal.

I can run a script x amount of times in a row, and then try and type in the PowerShell Integrated Terminal which will return something like this: ^[[18;49R and will continue to do so until I clear the whole line, at which point I can start typing normally again, then the terminal is instantly unresponsive after executing a command resulting in having to kill the terminal and open a new one each time.

### Attached Logs

[log.txt](https://github.com/PowerShell/vscode-powershell/files/1601394/log.txt)

**Comment by rkeithhill** [comment]
@GHRoss Thanks for taking the time to file this issue.

@tylerl0706 - we need to fix how we are determining the PS version on Linux/macOS.  I see this error log files coming from macOS - including this one:
```
03/01/2018 18:21:57 [WARNING] - Method "GetVersionDetails" at line 153 of C:\projects\powershelleditorservices\src\PowerShellEditorServices\Session\PowerShellVersionDetails.cs

    Failed to look up PowerShell version, defaulting to version 5.
    
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<>c__56`1.<ExecuteScriptAndGetItem>b__56_0(PSObject pso)
       at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
       at System.Linq.Enumerable.<OfTypeIterator>d__32`1.MoveNext()
       at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.ExecuteScriptAndGetItem[TResult](String scriptToExecute, Runspace runspace, TResult defaultValue)
       at Microsoft.PowerShell.EditorServices.Session.PowerShellVersionDetails.GetVersionDetails(Runspace runspace, ILogger logger)
```
I'm not sure if that is causing the behavior that the OP sees but we should eliminate it.  Not sure what problems defaulting to PS 5 on macOS might cause.

**Comment by tylerl0706** [comment]
@rkeithhill I'll look into it! Thanks @GHRoss for the issue!

**Comment by tylerl0706** [comment]
@GHRoss how are you running the script and what do you type in the Integrated Terminal?

**Comment by SeeminglyScience** [comment]
@tylerl0706 This is probably the same issue affecting debugging.  That escape sequence is what is emitted to stdin when `Console.CursorTop` or `Left` is called on Unix platforms.  There will always be a risk that that escape sequence will bleed into input (this risk is acknowledged via comments in corefx)  But the [pending PR](https://github.com/PowerShell/PowerShellEditorServices/pull/592) should make it exceedingly rare and resolve the hanging.

@GHRoss  If you're feeling adventurous and would like to give us a hand testing out the potential fix, [here's the build from appveyor](https://ci.appveyor.com/api/buildjobs/sk1qf096ecryddm9/artifacts/PowerShellEditorServices-1.5.1-1001.zip)

**Comment by tylerl0706** [comment]
@SeeminglyScience That makes sense - and I agree with you. Do you think we should then close this as a dupe to one of the other issues? Or maybe add it to be resolved when finishing up https://github.com/PowerShell/PowerShellEditorServices/pull/592

**Comment by SeeminglyScience** [comment]
@tylerl0706 I'd like to leave it open to confirm it's the same issue, but I'm pretty sure so it's up to you. 

Now that I think about it you may want to close the vscode-powershell issues I listed as resolved in that PR. I'm not a maintainer here so I'm not sure if they'll actually close automatically.

**Comment by rkeithhill** [comment]
If they're listed in the PR (Fixes #<somenumber>) then they should close automatically when the PR is merged.

**Comment by tylerl0706** [comment]
`Resolves #<issue>` also seems to work too 🙂 on https://github.com/PowerShell/PowerShellEditorServices/pull/592

**Comment by GHRoss** [comment]
@rkeithhill Good spot.

@tylerl0706 I run the script just by pressing F5 and then any key on the keyboard will give me the unexpected output.

@SeeminglyScience I think you're right, I cannot currently debug on macOS without hitting a key between each step. Where would I put the contents of that zip file to test, please? I'm excited to see this (potentially) fixed, after hours of wasted opening and closing of the terminal!

**Comment by SeeminglyScience** [comment]
@GHRoss The easiest way is to replace the contents of the `PowerShellEditorServices` folder in you extension folder with the contents of the one in this zip.  More specifically:

1. In the integrated console, type `ii ((gmo PowerShellEditorServices.Commands).ModuleBase|Split-Path)`.  That should open the PSES folder within the extension in your file explorer.

1. Make sure all instances of VSCode are closed

1. Copy the contents of the PowerShellEditorServices folder from the zip into the window opened in step 1

1. If you get access denied errors, try running `gps pwsh|? id -ne $pid|spps` in a separate PowerShell window

**Comment by GHRoss** [comment]
@SeeminglyScience I don't get access denied errors, but I do get this...

An error occurred while starting PowerShell Editor Services:

The specified module 'PowerShellEditorServices' with version '1.5.1' was not loaded because no valid module file was found in any module directory.

The contents of the folder before I pasted those files in looks very different after I've put those files in, are you sure what you've told me is correct?

For example, there are subfolders in that folder, but all of those file are just in one folder now?

**Comment by SeeminglyScience** [comment]
@tylerl0706 another issue I missed in the PR

**Comment by tylerl0706** [comment]
Closing :)
