### ISSUE TITLE
Enter-PSSession + psedit docs for new PowerShell users

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#1153]
We should have some documentation somewhere about how to use psedit in VSCode.

**Comment by GHRoss** [comment]
Would configuration of remote debugging on macOS and Linux in VS Code documentation also be a reasonable request?

**Comment by TylerLeonhardt** [comment]
I've doc'd the psedit feature here

https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode-for-remote-editing-and-debugging?view=powershell-7

though we recommend using VS Code Remote Development instead now:
https://code.visualstudio.com/docs/remote/remote-overview
