### ISSUE TITLE
Running "Set PSScriptAnalyzer Rules" on an untitled file causes PSES to crash

### ISSUE THREAD

**Issue by jkavanagh58** [PowerShell/vscode-powershell#1155]
## Issue Description ##

I am experiencing a problem with selecting PSScriptAnalyzer Rules. I add individual elements and then press confirm. After a brief delay the PowerShell session terminates and I prompted to restart or close. I have read similar issues where it was closed but this is consistent for me.
Now I receive "command 'PowerShell.SelectPSSARules' not found"

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about capturing and sending logs.

[psscriptanlyzertermshell.zip](https://github.com/PowerShell/vscode-powershell/files/1613308/psscriptanlyzertermshell.zip)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.15063 |
| VSCode | 1.19.1|
| PowerShell Extension Version | 1.5.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.15063.726|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.15063.726|
|BuildVersion|10.0.15063.726|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.2.2|
|beautify|HookyQR|1.1.1|
|gitlens|eamodio|7.2.0|
|Material-theme|zhuangtongfa|2.11.1|
|PowerShell|ms-vscode|1.5.1|
|team|ms-vsts|1.122.0|
|Theme-Blackboard|gerane|0.0.2|
|vscode-insertdatestring|jsynowiec|2.2.0|
|vscode-PSStackoverflow|DougFinke|0.0.2|
|vscode-todo-highlight|wayou|0.5.11|
|vscode-todo-plus|fabiospampinato|1.7.2|
|vscode-wakatime|WakaTime|1.1.22|
|WeatherExtension|AndrewMoll|0.1.3|
|xml|DotJoshJohnson|1.9.2|;

</details>

**Comment by jkavanagh58** [comment]
Forget the Now I receive "command 'PowerShell.SelectPSSARules' not found"; I was not in a ps1 editor session.

**Comment by rkeithhill** [comment]
Thanks for reporting this.  I see what the issue is.  As a work-around do not set PSSA rules when you have an unsaved i.e. an `Untitled-<n>` file open.  Save the file or open a PS1 file and then set the PSSA rules.

**Comment by jkavanagh58** [comment]
Outstanding,  I was using a New File for testing the rules... thank you very much.

**Comment by daviwil** [comment]
Reopening since there's a legitmate bug here!  Thanks for the report @jkavanagh58

**Comment by rkeithhill** [comment]
OK, I think I've fixed this a better way.
