### ISSUE TITLE
Get rid of ^C^C^C^C in powershell

### ISSUE THREAD

**Issue by cmoon2000** [PowerShell/vscode-powershell#1157]
In Vscode using intergrate `Powershell`, How to get rid of these things. If I have a selection by using mouse, then I can copy the text. In other case, I have a selection using keyboard, such as shift+left/right arrow, then hit ctrl+c, it will replace the selection by ^C. Likewise with ctrl+d,...

![capture](https://user-images.githubusercontent.com/6170794/34633786-fe5933ba-f2b0-11e7-8537-f0f5b0f898e7.PNG)

And It's just happend in Vscode, as I hit ctrl+c 3 times:

![capture](https://user-images.githubusercontent.com/6170794/34697839-8ebd960a-f507-11e7-8150-22d4b1939f35.PNG)

- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro

**Comment by tylerl0706** [comment]
@cmoon2000 I'm having a hard time repoing this.

Can you confirm something for me?

If you go to this drop down on the right, can you try it with "PowerShell Integrated Console" selected?
<img width="1096" alt="screen shot 2018-01-08 at 4 49 58 pm" src="https://user-images.githubusercontent.com/2644648/34699773-02843a7c-f494-11e7-8da3-c5c433889e86.png">

From the screenshots, it looks like your in regular PowerShell shell that the vscode team ships with vscode. I can repro that in that shell, I see `^C^C^C^C^C^C^C^C`.

I think this needs to be open against vscode. @rkeithhill, @daviwil, is that correct?

**Comment by daviwil** [comment]
I'm not sure why the ^C isn't cancelling the command prompt for plain powershell.exe in the integrated terminal UI.  @cmoon2000, can you verify what you're trying to do?  Are you trying to copy text in the terminal with the keyboard or are you trying to use Ctrl+C to cancel the current prompt (like you show in the Windows PowerShell window)?  I couldn't tell which scenario is the one you are trying to get working.

**Comment by cmoon2000** [comment]
@daviwil , yeah! those are 2 different cases. I want both of them work out. Unfortunately they don't.

**Comment by cmoon2000** [comment]
@tylerl0706 It made same result like you when I use Powershell Integrated Console

**Comment by tylerl0706** [comment]
@cmoon2000 so that's good that it made the same result as me. What about copy and pasting? Does copy and pasting work as expected in the PowerShell Integrated Console?

**Comment by haingdc** [comment]
@tylerl0706 yes It works normally

**Comment by cmoon2000** [comment]
@tylerl0706 It works normally

**Comment by tylerl0706** [comment]
Great! So this is not actually a problem with the PowerShell extension for VSCode. Because we only supply the Integrated Console. Your issue is with VSCode itself.

I'd recommend filing an issue here: https://github.com/Microsoft/vscode

Although, I feel like this issue already is open over there so it might be worthwhile to search for it before opening a new one.
