### ISSUE TITLE
 PsScriptAnalyzer Falsely Says Variable Is Assigned But Not Used but it actually is

### ISSUE THREAD

**Issue by stumper66** [PowerShell/vscode-powershell#1160]
### System Details

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- PowerShell extension version:  1.5.1
- Output from `$PSVersionTable`:
PSVersion                      5.1.15063.786
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.786
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
1.19.1
0759f77bb8d86658bc935a10a64f6182c5a1eeba
x64
$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      1      0
code --list-extensions --show-versions
Darfka.vbscript@1.0.4
MS-DevSkim.vscode-devskim@0.2.0
ms-vscode.PowerShell@1.5.1
reflectiondm.classynaming@1.1.1
$PSVersionTable
PSVersion                      5.1.15063.786
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.786
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
For some reason it always complains that my variable is assigned but never used when I assign into a particular loop.  Repro code:

$RequredFiles = @("c:\somefile1.txt","c:\somefiles2.txt")
$IsMissingFiles = $false

$RequredFiles | ForEach-Object {
    if (!(Test-Path $_)){
        $IsMissingFiles = $true
        Write-Host "Required file missing: $_"
    }
}

if ($IsMissingFiles){
    Write-Host "Missing files"
}

Shows error:
file: 'file:///c%3A//test.ps1'
severity: 'Warning'
message: 'The variable 'IsMissingFiles' is assigned but never used. (PSUseDeclaredVarsMoreThanAssignments)'
at: '6,9'
source: 'PSScriptAnalyzer'
code: 'PSScriptAnalyzerdb99606b-bfb5-43be-8902-10233d7a4a8c'
I am experiencing a problem with...
False error message

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.
![ps error](https://user-images.githubusercontent.com/18266662/34786419-bec2bc2a-f5f9-11e7-99f4-07451bb27e91.png)

**Comment by klmj** [comment]
As explained in **Powershell Code format (PSScriptAnalyzer) flags variable as unused #889**, this has aleady been reported here : PowerShell/PSScriptAnalyzer#827

Go there and +1 this issue 😃

**Comment by rjmholt** [comment]
It looks like PSSA has fixed this now. Going to close
