### ISSUE TITLE
Toggling breakpoint doesn't work for PowerShell scripts.

### ISSUE THREAD

**Issue by codialsoftware** [PowerShell/vscode-powershell#1165]
This just happens to happen after I installed new version of vscode

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.8.7
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
azurerm-vscode-tools|msa|0.3.7
arm-snippets|sam|1.1.0

---

Steps to Reproduce:

1.Open powershell file
2.Try to set a breakpoint -> nothing happens on UI
3.Check list of breakpoints by going to Debug section in sidepanel (ctrl+shift+d)
4.Notice the breakpoint is listed and gets toggled whenever you click on corresponding line in powershell file. However, no red bullet gets displayed next to the line in the editor

Reproduces without extensions: Yes

**Comment by deusletum** [comment]
I am unable to repro this on same VScode build running on Windows 10, could be a Windows 8.1 problem. Also it may be a issue with user language which looks to be fr-fr or fr-ca but don't take my word from it.

**Comment by codialsoftware** [comment]
This is really weird, because this problem occurs only in one of the directories in which I open VSCode - this really must have something to do with some cached data for this folder. How can I clear any caches for folders?

**Comment by SeeminglyScience** [comment]
@codialsoftware does that project happen to load other scripts in an abnormal way? Like a psm1 that doesn't dot source but instead reads each file and dynamically create script blocks from that?

**Comment by codialsoftware** [comment]
@SeeminglyScience Yes and no, I'm loading other scripts using `Import-Module`, but this is what the scripts does

**Comment by SeeminglyScience** [comment]
I'd have to see the whole thing to know for sure.  Is this a public project, or if not could you attach the workspace here assuming it doesn't contain sensitive data?

There are certain ways of loading script files that strips the file information from the command, usually unintentionally.  I'd have to see it confirm, but if this is workspace specific I'd bet money that something like that is present.

**Comment by rkeithhill** [comment]
> Notice the breakpoint is listed and gets toggled whenever you click on corresponding line in powershell file. However, no red bullet gets displayed next to the line in the editor

I have seen similar behavior in other languages e.g. the node debugger but it will usually at display a dark gray circle where you set the breakpoint. Do you see nothing?  Also, does that path have any special/wildcard characters in it e.g. `[ ]`

**Comment by TylerLeonhardt** [comment]
Hi all, can anyone still repro this? I'm having trouble trying to repro it.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
