### ISSUE TITLE
Install-VSCode.ps1 on PowerShellGallery.com is still 1.0. Please publish new script version

### ISSUE THREAD

**Issue by detlefs** [PowerShell/vscode-powershell#1170]
### System Details

- Operating system name and version: Windows 8.1 Enterprise
- VS Code version: 1.19.2
- PowerShell extension version:
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Installing the script from PowerShellGallery via "Install-Script -Name Install-VSCode" provides version 1.0

### Attached Logs

n/a

**Comment by tylerl0706** [comment]
Thanks for this! We'll get that published soon.

**Comment by tylerl0706** [comment]
Sorry it's taken so long, was dealing with some permission issues. I'll get that done this week.

**Comment by tylerl0706** [comment]
1.2 has been published:
https://www.powershellgallery.com/packages/Install-VSCode/1.2/DisplayScript
