### ISSUE TITLE
"Go To Definition" does not jump to the definition if a variable defined with a type

### ISSUE THREAD

**Issue by exchange12rocks** [PowerShell/vscode-powershell#1171]
### System Details

- Operating system name and version: Windows 10 1709 x64 10.0.16299
- VS Code version: 1.19.2
- PowerShell extension version: 1.5.1
- Output from `$PSVersionTable`:

```
PS > code -v
1.19.2
490ef761b76b3f3b3832eff7a588aac891e5fe80
x64
PS > $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      1      0


PS > code --list-extensions --show-versions
jasonn-porch.gitlab-mr@1.3.0
ms-mssql.mssql@1.3.0
ms-vscode.PowerShell@1.5.1
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

If I specify variable's type when initializing it, "Go to Definition" function does not jump to the definition:
```
[System.Collections.ArrayList]$List = @()
$List.Add(1)
```
![non-working example](https://i.imgur.com/ueDz1uo.gif)

If I don't use a type, it works:
```
$List = @()
$List.Add(1)
```
![working example](https://i.imgur.com/ThOcJtV.gif)

The issue is reproducible even with common types like `[string]` or `[int]`.

### Attached Logs
[1516639974-84f43b59-f93c-4486-a559-5596f6f467601516639969734.zip](https://github.com/PowerShell/vscode-powershell/files/1652826/1516639974-84f43b59-f93c-4486-a559-5596f6f467601516639969734.zip)

The issue seems similar to #668, but in the `Param ()` section it does not work even if a variable has no type specified.

**Comment by SeeminglyScience** [comment]
Looks like [VisitAssignmentStatement in FindReferencesVisitor](https://github.com/PowerShell/PowerShellEditorServices/blob/dafbbc76af110e3f78d5f6cd3def1cedeea47771/src/PowerShellEditorServices/Language/FindDeclarationVisitor.cs#L77) needs to account for `Left` being an `ConvertExpressionAst` with a `VariableExpressionAst` as the `Child`.

Also needs `VisitParameter` method to check the variable inside a `ParameterAst.Name`.  May also be worth adding `VisitForEachStatement` to check `ForEachStatementAst.Variable`, but that would need logic that makes sure the symbol is within the foreach statement.

**Comment by SydneyhSmith** [comment]
I am having trouble re-producing this so I am guessing it got fixed at some point, if this is still an issue I will re-open. Thanks!

**Comment by exchange12rocks** [comment]
Yes, seems to work alright now.
