### ISSUE TITLE
region and endregion does not maintain last state when script is saved

### ISSUE THREAD

**Issue by ryanfog** [PowerShell/vscode-powershell#1176]
•VSCode Version: Code 1.19.3 (7c4205b, 2018-01-25T10:36:34.867Z)
•OS Version: Windows_NT x64 10.0.16299
•Extensions:

PowerShell ms- 1.5.1 
team ms- 1.122.0 

### Issue Description

When saving a file the #region and #endregion does not maintain the last state. I like to keep them collapsed when saving and they are always expanded when i go back into a script.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
This feature is provided by Visual Studio Code itself.  You can submit this to them at https://github.com/microsoft/vscode/issues
