### ISSUE TITLE
snippet "Function advanced"

### ISSUE THREAD

**Issue by timoline** [PowerShell/vscode-powershell#1177]
Can you add a snippet for an advanced function (just like in ISE) ?
thanks

**Comment by timoline** [comment]
Ok found it (but  not very logical to me)

> There is a snippet for advanced functions: cmdlet. There are more "example" like snippets that are prefixed ex- for DSC and advanced functions e.g. ex-cmdlet.

**Comment by tylerl0706** [comment]
That's a reasonable ask and should be just a config change. Did you want to try and contribute it?

**Comment by timoline** [comment]
If you don't mind, I leave it uo to the pros...
I'm just a customer ;-)

**Comment by tylerl0706** [comment]
Sounds good! We'll get to it as soon as we can. It _would_ be a simple change in this file:
https://github.com/PowerShell/vscode-powershell/blob/master/snippets/PowerShell.json#L515 

in case you change your mind :)

**Comment by rkeithhill** [comment]
FWIW, the `ex-` snippets are more, um, opinionated perhaps.  For the "standard" snippets like for `for`, `foreach`, etc we try to remain very vanilla.  One person's treasure is another person's garbage (and vice-versa).  :-)

**Comment by Ben-Shirley** [comment]
Hey @tylerl0706 I'd like to submit a PR for this if I may

**Comment by Ben-Shirley** [comment]
PR submitted 
https://github.com/PowerShell/vscode-powershell/pull/1182 

first PR so hope I did everything right! grateful for any guidance :)

**Comment by tylerl0706** [comment]
Thanks @Ben-Shirley! Let me take a look.
