### ISSUE TITLE
The file contains a virus or potentially unwanted software 

### ISSUE THREAD

**Issue by KarlGW** [PowerShell/vscode-powershell#1178]
### System Details

- Operating system name and version: Windows 10, 1709
- VS Code version: 1.19
- PowerShell extension version: 1.51

### Issue Description

When installing this extension (Recommended by VSCode itself, Windows Defender flagged `PSScriptAnalyzer.psd1` as malware. I know that you are not responsible for that package (and there is an issue about it as we speak). Just wanted to inform about it.

**Comment by KevinMarquette** [comment]
The Windows Defender issue is resolved in definition update 1.261.424.0

    PS:> Get-MpComputerStatus | Select AntivirusSignature*

    AntivirusSignatureLastUpdated   : 1/28/2018 8:28:37 PM
    AntivirusSignatureVersion       : 1.261.424.0

**Comment by KarlGW** [comment]
Thank you for the information!
