### ISSUE TITLE
Should not use the "onDebug" activation event

### ISSUE THREAD

**Issue by roblourens** [PowerShell/vscode-powershell#1179]
vscode-powershell is using the `onDebug` activation event, which causes it to be activated any time a debug session of any type is started. (https://github.com/PowerShell/vscode-powershell/blob/master/package.json#L29)

In 1.19 we added the more fine-grained `onDebugResolve:type` and `onDebugInitialConfigurations` activation events which let extensions be activated only when they need to be to resolve debug configs. One consequence is that when I start debugging a node app, I get a terminal popup from the powershell extension that says `An error occurred while starting PowerShell Editor Services: ...`. Ideally I'd only see that when I'm doing something powershell-related.

More details here: https://code.visualstudio.com/updates/v1_19#_debug-contributions-in-packagejson

**Comment by tylerl0706** [comment]
Thanks for the report, @roblourens. We'll address this.
