### ISSUE TITLE
Debug adapter should show validation error when launch.json 'args' parameter is not an array

### ISSUE THREAD

**Issue by laurijsd** [PowerShell/vscode-powershell#118]
VSCode Version: 0.10.11 , shell 0.35.6, Renderer 45.0.2454.85
OS Version: WIN10 Pro
Powershell 0.5.

Steps to Reproduce:
1.Have a working setup with VSCode 0.10.10 and powershell debug 0.5.0
2.Upgrade VSCode to 0.10.11. 
3.Debug fail: The error says Debug adapter process has terminated unexpectedly
4.Reinstall VSCode 0.10.10 and powershell debug 0.5.0, issue remains

[DebugAdapter.log.txt](https://github.com/PowerShell/vscode-powershell/files/174411/DebugAdapter.log.txt)

**Comment by daviwil** [comment]
Hey @laurijsd, can you paste your launch.json for me?

**Comment by laurijsd** [comment]
{
    "version": "0.2.0",
     "configurations": [ 
        { 
            "name": "PowerShell", 
            "type": "PowerShell", 
            "program": "AFASconnector.ps1",
            "args": "-Verbose"
        } 
    ] 
}

**Comment by laurijsd** [comment]
ok @daviwil,
figuring what you could possibly mean by asking for the launch.json, I tried with the launch.json in the examples-section and it works...

my new launch.json now says:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PowerShell",
            "type": "PowerShell",
            "request": "launch",
            "program": "${file}",
            "args": [],
            "cwd": "${file}"
        }
    ]
}

**Comment by daviwil** [comment]
The problem in your original launch.json is that you are passing a single string to the `args` field when it should be an array containing a single string (in this case).  When you open your launch.json in VS Code, you should see a warning about this:

![image](https://cloud.githubusercontent.com/assets/79405/13792978/c825fdd6-eab1-11e5-98be-1b7bab748db4.png)

**Comment by weinand** [comment]
@daviwil yep, I came to the same conclusion: https://github.com/Microsoft/vscode/issues/4267

**Comment by daviwil** [comment]
Thanks for helping investigate the issue Andre!  Do you think we should just accept the single string in this case or is there a more clear way to report an error so that the user knows they configured their launch.json incorrectly?

**Comment by weinand** [comment]
@daviwil I suggest to report anything that doesn't follow your spec (the schema in package.json) as errors from the 'launch' and 'attach' requests. Set the 'showUser' attribute to true and the 'sendTelemetry' to false. This will make the errors only show up as error notifications (and they don't end up in telemetry)

**Comment by daviwil** [comment]
Thanks Andre!  That sounds like the right thing to do.

**Comment by JustinGrote** [comment]
@TylerLeonhardt This one should be closeable since this has since changed to use the "script" option and any issues with the config end up passing through into the integrated terminal
![image](https://user-images.githubusercontent.com/15258962/79583127-92305900-8081-11ea-810c-65cf1a46bf57.png)
