### ISSUE TITLE
PSScriptAnalyzer.psd1 gets flagged by Windows Defender as Trojan:Powershell/peasecto.a

### ISSUE THREAD

**Issue by JasonvanBrackel** [PowerShell/vscode-powershell#1180]
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.19.2
- PowerShell extension version: 1.5.1
- Output from `$PSVersionTable`: 
```
C:\WINDOWS\system32> code -v
1.19.2
490ef761b76b3f3b3832eff7a588aac891e5fe80
x64
C:\WINDOWS\system32> $pseditor.EditorServicesVersion
C:\WINDOWS\system32> code --list-extensions --show-versions
aws-scripting-guy.cform@0.0.10
bajdzis.vscode-database@1.3.0
bbenoist.vagrant@0.5.0
cake-build.cake-vscode@0.10.1
codeflows.vaulty@0.2.0
codezombiech.gitignore@0.5.0
DavidAnson.vscode-markdownlint@0.13.0
DotJoshJohnson.xml@1.9.2
EditorConfig.EditorConfig@0.12.0
eg2.vscode-npm-script@0.3.3
erd0s.terraform-autocomplete@0.0.8
fknop.vscode-npm@3.3.0
heptio.jsonnet@0.0.15
ipedrazas.kubernetes-snippets@0.1.8
joaompinto.asciidoctor-vscode@0.3.7
mauve.terraform@0.0.20
mindginative.terraform-snippets@1.10.7
ms-mssql.mssql@1.3.0
ms-python.python@0.9.1
ms-vscode.csharp@1.13.1
ms-vscode.Theme-MarkdownKit@0.1.4
msazurermtools.azurerm-vscode-tools@0.3.8
PeterJausovec.vscode-docker@0.0.23
rebornix.Ruby@0.16.0
Zim.vsc-docker@0.34.0
C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


C:\WINDOWS\system32>
```

### Issue Description

Windows Defender Flagged PSScriptAnalyzer.psd1 as a Trojan.  Here are the details 

Trojan:PowerShell/Peasecto.A

Alert level: Severe
Status: Quarantined
Date: 1/29/2018

Recommended Action: Remove Threat now.

Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

[Learn More](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:PowerShell/Peasecto.A)

Affected Items:
file: C:\Users\jason\.vscode\extensions\ms-vscode.powershell-1.5.1\modules\PSScriptAnalyzer\PSScriptAnalyzer.psd1

**This may be incorrect detection as reported on the Learn More link, and if so just close this issue.**

**Comment by AlgorithmsAreCool** [comment]
I'm seeing the same thing as of last night 

```
C:\Users\nobody\.vscode\extensions\ms-vscode.powershell-1.5.1\modules\PSScriptAnalyzer\PSScriptAnalyzer.psd1

C:\Program Files\PowerShell\6.0.0\Modules\PackageManagement\1.1.7.0\PackageManagement.psd1

Flagged as Trojan:PowerShell/Peasecto.A
```

**Comment by tylerl0706** [comment]
Take a look at this issue.

https://github.com/PowerShell/vscode-powershell/issues/1178

It looks to be fixed in the latest Windows Defender update. Let me know if you see otherwise.

**Comment by JasonvanBrackel** [comment]
After forcing a Windows Defender update I'm no longer seeing the issue.
