### ISSUE TITLE
PS Host Fails When ExecutionPolicy Is Set to Bypass

### ISSUE THREAD

**Issue by ftischhauser** [PowerShell/vscode-powershell#119]
When setting the execution policy to 'Bypass' using the machine policy, the PS host fails to start with the following error:

> Unhandled Exception: System.Management.Automation.CmdletInvocationException: Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of Bypass

To reproduce the issue you can set the following registry values:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\PowerShell]
"EnableScripts"=dword:00000001
"ExecutionPolicy"="Bypass"
```
As this is the least restrictive setting the host should work just fine and catch this error.

Thanks for looking into this!

**Comment by daviwil** [comment]
Was scanning the bug list and noticed that this is still open, I think I meant to close it after filing the issue on the PowerShellEditorServices repo :)  I'll see about getting this fixed for the next release.  Thanks Flavio!
