### ISSUE TITLE
Daily/weekly VSIX build

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#1190]
With the comments going on in:
https://github.com/PowerShell/PowerShellEditorServices/issues/604#issuecomment-360966764

I want to talk about having a daily/weekly build of the VSIX so that folks who are waiting on a particular fix don't have to wait for us to release (or hand craft a vsix for them, or have them do it themselves) in order to get the change they need.

We have CI in place already.

This is still probably a big work item because we need to follow the correct processes, but I think it's pretty important for a product that ships every 1/2months.

I would love to hear from @daviwil , @rkeithhill , @SeeminglyScience , @TravisEz13 , @SteveL-MSFT

**Comment by daviwil** [comment]
We produce a VSIX with every AppVeyor build:

https://ci.appveyor.com/project/PowerShell/vscode-powershell/build/artifacts

Right now it only includes a compiled PSES (no PSScriptAnalyzer or Plaster) but you could probably add a step to pull those in.  The only thing you'd be missing are signed bits for PSES.  Setting up a nightly build in AppVeyor would allow a daily package to be published with the latest stuff from vscode-powershell and PSES.

**Comment by tylerl0706** [comment]
Yep, I knew we were creating the VSIX but I also knew it wasn't a complete VSIX that we ship.

I think what would be interesting is a daily/weekly/ondemand push of PSES to the Gallery or NuGet.org (signed and all) (possibly as prerelease) and then have appveyor bring in PSSA, Plaster, PSES via the Gallery.

We also need to eventually remove building PSES out of CI for vscode-powershell anyway (it's a requirement) so moving to this model might be a good way to go.

Thoughts?

**Comment by bergmeister** [comment]
We had similar discussions already on twitter about pre-releases especially with regards to pre-releases of PSSA. Apparently the shipped version of PSSA in the extension is only a fallback version if PSSA is not installed. Therefore we could offer pre-releases of PSSA and the extension independently but I think it would be a great idea to include the latest build of PSSA in the vsix as well for better integration testing. At my old team in my company we had a product that had an important dependency on another internal product so we had a 'bleeding edge' build to check to be able to push back early to the other product team if they made changes that broke the integration.

**Comment by TylerLeonhardt** [comment]
we have PowerShell Preview extension for this now.
