### ISSUE TITLE
Editor service frequently crashing immediately after opening project folder

### ISSUE THREAD

**Issue by meaderick** [PowerShell/vscode-powershell#1195]
### System Details

- Operating system name and version: Microsoft Windows NT 6.1.7601 Service Pack 1
- VS Code version: 1.20.0
- PowerShell extension version: 
- Output from `$PSVersionTable`:

```
> code -v
1.20.0
c63189deaa8e620f650cc28792b8f5f3363f2c5b
x64

> $pseditor.EditorServicesVersion
[no output]

> code --list-extensions --show-versions
alefragnani.Bookmarks@0.18.1
dbaeumer.vscode-eslint@1.4.5
donjayamanne.githistory@0.4.0
DotJoshJohnson.xml@1.9.2
eamodio.gitlens@8.0.0
felipecaputo.git-project-manager@1.4.0
johnstoncode.svn-scm@1.19.0
ms-mssql.mssql@1.3.0
ms-vscode.csharp@1.13.1
ms-vscode.PowerShell@1.5.1

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.16481
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```

### Issue Description

Editor service frequently, but not always, crashing. Stack trace says System.IO.PathTooLongException thrown but none of my source file paths are more than about 100 chars.

Was working yesterday for the first time in a while, but not again today. No significant changes I can relate.

Uninstalled, removed all files & reinstalled but issue persists. PS terminal seems to be working normally.

### Attached Logs

Cleared old logs, set level verbose, opened project folder, editor service crashed. Contents of entire logs dir attached.
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1721569/logs.zip)

**Comment by meaderick** [comment]
More info: IntelliSense seems to be working normally, but references/gotos (F12) are not.

**Comment by rkeithhill** [comment]
>> Usually, I'm getting this error when I'm looking for changes made since last commit in VSCode.

I think this is the key.  VSCode has changed the file URI format or something and we are not detecting that properly.  Thanks for info!

**Comment by tylerl0706** [comment]
> Usually, I'm getting this error when I'm looking for changes made since last commit in VSCode.
Do you think you could expand on this a little, @Glober777? What diff editor are you looking at exactly?

**Comment by kcurtis3247** [comment]
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/1812469/EditorServices.log)

I get the same type of PathTooLongExceptions. Log attached. 

In my case it's definitely only showing up with svn, as I can get rid of the errors by disabling the extension. It looks like it's including a bunch of encoded characters.

![vscode](https://user-images.githubusercontent.com/10444270/37424339-3237db66-278e-11e8-90e5-e99cc93ec2bf.png)

**Comment by rjmholt** [comment]
I'm assuming that `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` is set to `0` on these systems?

If so, I wonder what our mitigation can be if VSCode is generating the paths...

**Comment by tylerl0706** [comment]
I'm going to close this as a dupe to https://github.com/PowerShell/PowerShellEditorServices/issues/569 since this issue is actually with PowerShell Editor Services.

It's seems clear that we're not catching this exception and handling it accordingly.

**Comment by tylerl0706** [comment]
Let me know if you see otherwise! Thanks everyone :)

**Comment by rkeithhill** [comment]
Fix is coming.
