### ISSUE TITLE
There is no output when run Get-MsolPasswordPolicy -DomainName domain.com

### ISSUE THREAD

**Issue by VSCodeUser** [PowerShell/vscode-powershell#1196]
### System Details

- Operating system name and version: Windows 10 Ent 2016 LTSB  /10.0.14393/
- VS Code version:
Version 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:09:39.780Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- PowerShell extension version:
- Output from `$PSVersionTable`:

Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      5.1.14393.1944                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                            
BuildVersion                   10.0.14393.1944                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                
SerializationVersion           1.1.0.1                                                                                                                                                            

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      1      0
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

I am experiencing a problem with command "Get-MsolPasswordPolicy -DomainName domain.com" when I run it in PowerShell Integrated console terminal:

Name             : Visual Studio Code Host
Version          : 1.5.1
InstanceId       : bcb03524-ab3f-441f-a184-31bf7bf84890
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-US
PrivateData      :
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

The command doesn't return any output. If I change terminal to PowerShell.exe it is working as expected.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by tylerl0706** [comment]
Hi there, thanks for this! Couple questions:

What are you expecting to get back?
Can you attach the logs? You can follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems).

**Comment by VSCodeUser** [comment]
Thanks for the prompt reply!
I updated my VS code today to version:

Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

and everything is working now.


I expected /and now I am able/ to see the output below:
---------------------------------------------------------------------------------
ExtensionData    : System.Runtime.Serialization.ExtensionDataObject
NotificationDays : 31
ValidityPeriod   : 1000
----------------------------------------------------------------------------------
Many thanks for the prompt fix! 
This issue can be closed now.
