### ISSUE TITLE
Autocomplete/Intellisense on object properties not working correctly.

### ISSUE THREAD

**Issue by ThePSAdmin** [PowerShell/vscode-powershell#12]
When tabbing for autocomplete on a property from intellisense, either the period is removed or the entire object + property is replaced with the property name.

![powershell_vscode](https://cloud.githubusercontent.com/assets/11364812/11266304/f83af16c-8ea3-11e5-921d-05f6335c262a.gif)

**Comment by daviwil** [comment]
Ouch!  I know why that's happening.  Will fix ASAP.  Thanks for the report!

**Comment by daviwil** [comment]
Now fixed in PowerShellEditorServices, look for this is the next release!
