### ISSUE TITLE
powershell on mac 

### ISSUE THREAD

**Issue by Arshavink** [PowerShell/vscode-powershell#1200]
I Installed Visual studio code for mac OS and I am working on powershell on it when  I  update the get-help(update-help) I get this error : 
Update-Help : Failed to update Help for the module(s) 'Microsoft.PowerShell.Archive, Microsoft.PowerShell.Core, Microsoft.PowerShell.Host, Microsoft.PowerShell.Management, Microsoft.PowerShell.Security, Microsoft.PowerShell.Utility, PackageManagement, PowerShellGet, PSReadLine' with UI culture(s) {en-US} : Access to the path '/usr/local/microsoft/powershell/6.0.1/en-US/Microsoft.PowerShell.Commands.Management.dll-Help.xml' is denied.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand

**Comment by tylerl0706** [comment]
Thanks for this!

I want to see if this is first an issue with PowerShell.

Can you open a terminal (not in VSCode), 
start PowerShell by typing `pwsh` in the terminal
And try to update help here?

Let me know what you get.

**Comment by Arshavink** [comment]
Yes It works on terminal I update it

**Comment by tylerl0706** [comment]
In the terminal, are you running posh

**Comment by tylerl0706** [comment]
Question, @Arshavink... when it worked in the terminal, were you running push with sudo?

**Comment by Arshavink** [comment]
No without sudo

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.

**Comment by TylerLeonhardt** [comment]
This was actually a PowerShell issue and was fixed with 6.1 I'm pretty sure. @Arshavink can you give it another try?

I'll close this as Im pretty sure this is fixed.
