### ISSUE TITLE
Syntax highlighting on ParameterSetName not working with spaces around assignment operator

### ISSUE THREAD

**Issue by totkeks** [PowerShell/vscode-powershell#1202]
### System Details

- Operating system name and version: Windows 10, 1703
- VS Code version: 1.20.1
- PowerShell extension version: 1.5.1
- Output from `$PSVersionTable`: 

```
Name                           Value
----                           -----
PSVersion                      5.1.15063.786
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.786
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
$pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      1      0
```

### Issue Description

Syntax highlighting is not working for code like this:
```powershell
        [Parameter(Mandatory = $True, ParameterSetName = "SharedResources")]
        [String]
        $VarName,
```
![image](https://user-images.githubusercontent.com/2941389/36413655-b009e96a-161f-11e8-8d8c-6e15699170da.png)

If I remove the whitespace after the assignment operator, it works fine:
```powershell
        [Parameter(Mandatory = $True, ParameterSetName ="SharedResources")]
        [String]
        $VarName,
```
![image](https://user-images.githubusercontent.com/2941389/36413664-b7afc5f4-161f-11e8-8f9a-1859e4d88fec.png)

Since auto formatting the file places whitespaces around the assignment operator, I would assume that this is the correct way to format the parameter options.

**Comment by rkeithhill** [comment]
@tylerl0706 This probably belongs in https://github.com/powershell/editorsyntax.  Can you move it there?

**Comment by totkeks** [comment]
Closed, because the related issue (https://github.com/PowerShell/EditorSyntax/issues/73) is fixed.
