### ISSUE TITLE
PowerShell Integrated Console clarification questions (syntax highlighting and execution policy)

### ISSUE THREAD

**Issue by jeremytbrun** [PowerShell/vscode-powershell#1217]
### System Details

- Operating system name and version: Windows 10 (Build 15063.877)
- VS Code version: 1.20.1
- PowerShell extension version: 1.6.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.15063.786
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.786
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```
1.20.1
f88bbf9137d24d36d968ea6b2911786bfe103002
x64

Major  Minor  Build  Revision
-----  -----  -----  --------
1      6      0      0
ms-python.python@2018.1.0
ms-vscode.PowerShell@1.6.0
nhoizey.gremlins@0.7.0
robertohuertasm.vscode-icons@7.20.0

Key   : PSVersion
Value : 5.1.15063.786
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.15063.786
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion

### Issue Description

I have two questions about the behavior of the vscode-powershell extension.
1. How do you set the execution policy for the PowerShell Integrated Console created by the extension? I am able to use terminal.integrated.shellArgs.windows for setting the policy of the default integrated terminal shell, but it does not seem to affect the PowerShell Integrated Console created by the extension.
2. Why is it that PowerShell syntax highlighting works in the default integrated terminal shell (Get-Process is highlighted yellow, for example), but in the PowerShell Integrated Console created by the extension there doesn't seem to be any syntax highlighting.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by jeremytbrun** [comment]
Thanks for the info @dsolodow.

The default Integrated Terminal does seem to honor Set-ExecutionPolicy when set in an independent PowerShell window, but the "PowerShell Integrated Console" that loads with the vscode-powershell extension does not seem to honor it (see screenshot). It seems to default to "RemoteSigned". When I try to set the policy within the PS Integrated Console it errors (see screenshot).

Somehow the powershell process being kicked off by the vscode-powershell extension seems to be setting a policy of RemoteSigned that cannot be overwritten?

![capture1](https://user-images.githubusercontent.com/28311946/37163813-bafd336e-22c6-11e8-8dd1-1fc8e206e23e.PNG)

![capture2](https://user-images.githubusercontent.com/28311946/37163814-bd17d820-22c6-11e8-97d8-39de5b7a2407.PNG)

**Comment by dsolodow** [comment]
Fascinating. What happens if you run
```powershell
Set-ExecutionPolicy Unrestricted -Scope Process
```

**Comment by jeremytbrun** [comment]
That seems to work. Hmmm. But why does it default back to RemoteSigned after restarting the PowerShell Integrated Console? Any way to make it default to something else?

![capture1](https://user-images.githubusercontent.com/28311946/37167869-184b46e6-22d1-11e8-86a2-a96ce585da4a.PNG)

**Comment by jeremytbrun** [comment]
It appears it may be configurable by adding the following line of code to Microsoft.VSCode_profile.ps1.

`Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process`

Let me know if this is the only way you know of.

Thanks @dsolodow !

**Comment by dsolodow** [comment]
Yeah, adding it to the profile was something I mentioned earlier. :)
I personally avoid using the host specific profiles, so I'd instead add the following to profile.ps1:
```powershell
If ($host.Name -eq 'Visual Studio Code Host')
{
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process
}
```

**Comment by jeremytbrun** [comment]
Thanks. Sorry I didn't make that connection at first. :)

Thanks for the pointer on the general profile script.

**Comment by thenning** [comment]
I tried setting the execution policy in the profile for integrated console, but the integrated console won't run the profile script for the exact same reason. 

Anyone have any ideas?

**Comment by tylerl0706** [comment]
@thenning can you attach your logs so that we can better assist :) 

Here's the doc:
https://github.com/powershell/vscode-powershell/#2-capture-verbose-logs-and-send-them-to-us
