### ISSUE TITLE
Feature Request:  Add Function Picker

### ISSUE THREAD

**Issue by prkrnt** [PowerShell/vscode-powershell#1218]
### System Details

- Operating system name and version: Windows 10

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
1.20.1
f88bbf9137d24d36d968ea6b2911786bfe103002
ia3

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      6      0      0

code --list-extensions --show-versions
abusaidm.html-snippets@0.2.1
arcticicestudio.nord-visual-studio-code@0.6.0
DotJoshJohnson.xml@1.9.2
emmanuelbeziat.vscode-great-icons@2.1.27
ms-mssql.mssql@1.3.0
ms-vscode.PowerShell@1.6.0
ms-vsts.team@1.122.0
PKief.material-icon-theme@3.2.3
qrti.funclist@7.1.0
robertohuertasm.vscode-icons@7.20.0
zhuangtongfa.Material-theme@2.12.6

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Feature Request

Coming from full Visual Studio, one of my favorite things is the ease at which you can navigate a large PowerShell module based on function name.  Most of the code I write is based on functions and being able to easily click a drop down and see every function AND navigate to it with a click is a huge time saver!

Thanks for your consideration!

**Comment by rkeithhill** [comment]
This exists within a single script file - press <kbd>Ctrl+Shift+O</kbd> to view symbols.  What we don't have IIRC, is support for viewing all symbols in a workspace.

**Comment by prkrnt** [comment]
I knew it had to be there, but just didn't know where to look.

Thanks!

**Comment by rkeithhill** [comment]
I don't know about you but it bugs me slightly that this list isn't alphabetical like in VS.  But as you scroll through the list it jumps to that code location.  The VSCode folks told me that they preferred to keep that list in the order in which symbols appear in the document.  Not sure I totally buy that but ...

**Comment by prkrnt** [comment]
I think what bugs me more than that is how code folding is completely broken still.

**Comment by rkeithhill** [comment]
Have you voted on this VSCode issue related to code folding?  https://github.com/Microsoft/vscode/issues/3422
