### ISSUE TITLE
Close tag not recognized after here-string header

### ISSUE THREAD

**Issue by ExchangeTips** [PowerShell/vscode-powershell#1221]
### System Details

- Operating system name and version: Windows 10 Pro 10.0.16299
- VS Code version: 1.20.1
- PowerShell extension version: 1.6.0
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

PS C:\WINDOWS> code -v
1.20.1
f88bbf9137d24d36d968ea6b2911786bfe103002
ia32
PS C:\WINDOWS> $pseditor.EditorServicesVersion
PS C:\WINDOWS> code --list-extensions --show-versions
PS C:\WINDOWS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

The closing doublequote-@ ("@) in the following code is not interpeted as a closing tag:

$DesktopIniContent = @"
        [.ShellClassInfo]
        CLSID2={0AFACED1-E828-11D1-9187-B532F1E9575D}
        Flags=2
        ConfirmFileOp=1
"@

Everything after the close tag is interpreted as if it is still within the opening doublequote.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems
[1519942442-058a7381-2ca3-4027-8bff-b5ddb9c0669b1519942439665.zip](https://github.com/PowerShell/vscode-powershell/files/1772977/1519942442-058a7381-2ca3-4027-8bff-b5ddb9c0669b1519942439665.zip)
)
about capturing and sending logs.

**Comment by moymike** [comment]
Do you have the closing tag -->
"@ 
typed starting at column 1?  If there is a tab or space in front of it, I get that behavior, but otherwise it works.  This was true with ISE also.

**Comment by ExchangeTips** [comment]
No, I didn't. Thanks. That fixed it.

**Comment by ExchangeTips** [comment]
Well, not exactly "fixed", but good enough for now.

**Comment by rkeithhill** [comment]
I'm going to close this. If you still think there is an issue syntax colorization, please file it at https://github.com/powershell/editorsyntax.  WRT to code folding, vote here - https://github.com/Microsoft/vscode/issues/3422
