### ISSUE TITLE
found a virus in vsix file

### ISSUE THREAD

**Issue by shahwahed** [PowerShell/vscode-powershell#1222]
### System Details

- Operating system name and version:
- VS Code version: 1.6.0
- PowerShell extension version:
- Output from `$PSVersionTable`:

As I looking for a offline installation of vscode-powershell, I download the vsix file for offline download
using the following URL :  

https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/PowerShell/1.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

my clamav detect a virus in it.

I've also send this URL to virus total, and they found a suspicious file : 
https://www.virustotal.com/fr/file/17f4ad722d415b20f4fd1edf3487595b1c3886f50cfc0bb34cf6969464b93076/analysis/1520458158/

UnixConsoleEcho.dll with a trojan in it.

If I clone the git repository the virus scan is OK

**Comment by TheIncorrigible1** [comment]
Why aren't you using the [official download link](https://github.com/PowerShell/vscode-powershell/releases/download/v1.6.0/PowerShell-1.6.0.vsix)?

**Comment by shahwahed** [comment]
Thanks for the link,  but still got the same problem : 
https://www.virustotal.com/fr/file/b4d73a0323f77131de15f2d25c2e5e061f7ae382f5a9d4943e0b0e97d8b306fc/analysis/1521042496/
![vsixvt01](https://user-images.githubusercontent.com/4116493/37495120-2dcad622-28ac-11e8-9eaa-b68883a36f0a.png)

how can I be sure this is a false positive virus hit, or a truth problem

**Comment by tylerl0706** [comment]
UnixConsoleEcho is a library that @SeeminglyScience made to fix a few issues related to Unix based systems:
https://github.com/SeeminglyScience/UnixConsoleEcho

He's a contributor of this project and PowerShellEditorServices the language server this extension uses.

I don't think this is a true problem. That said, I'd be interested in getting more information on why this is getting flagged and maybe there's a way we can prevent it.

**Comment by SeeminglyScience** [comment]
If you drill down to the file, it looks like it's hitting a rule that tries to detect obfuscated PowerShell scripts.  From what I can tell it hits if the word "PowerShell" is embedded somewhere, and the file is under a specific size.

That library doesn't have the word PowerShell anywhere, but the dll from the nuget package also runs clean.  [Here's the scan](https://www.virustotal.com/en/file/044615e1a8f2921ee8f35952d49b0a206f032fd6f7ae4fcfc57862dec984bf21/analysis/).

This makes me think it's added during the signing process.  Not sure what can be done about it if that's the case.

**Comment by rjmholt** [comment]
Given that @SeeminglyScience is the author of UnixConsoleEcho and we have a pretty strong theory about why this third party tool is tagging it as possibly suspicious, I think we can close this issue.
