### ISSUE TITLE
Pester Describe blocks with tags lose integration functionality

### ISSUE THREAD

**Issue by jacerm** [PowerShell/vscode-powershell#1223]
### System Details

- Operating system name and version: Windows 10 
- VS Code version: 1.20.1
- PowerShell extension version: 1.6.0

### Issue Description
- Standard Pester Describe blocks provide Run Tests and Debug Tests buttons for easy Pester integration. When you add Tags to the Describe block, the Pester integration buttons are no longer available. See images below.

![2018-examplewithouttag](https://user-images.githubusercontent.com/10948023/37122568-e1aca820-2215-11e8-9440-d7dbab6a4caa.png)
![examplewithtag](https://user-images.githubusercontent.com/10948023/37122570-e1cf0730-2215-11e8-81cd-6ba33636c52c.png)

**Comment by rjmholt** [comment]
Ah, I can replicate this nicely and think I see [where the issue lies](https://github.com/PowerShell/PowerShellEditorServices/blob/80755157599b620c8e24517e4d36166bd2943922/src/PowerShellEditorServices/Symbols/PesterDocumentSymbolProvider.cs#L42). Hopefully a fix will be straightforward.
