### ISSUE TITLE
Possible powershell.codeFormatting.whitespaceAroundOperator bug

### ISSUE THREAD

**Issue by AWahlqvist** [PowerShell/vscode-powershell#1237]
### Issue Description

Not sure if this is an actual bug or not, but consider this example when setting powershell.codeFormatting.whitespaceAroundOperator to true:

```PowerShell
$numberOfDaysToSubtract = 10
(Get-Date).AddDays(-$numberOfDaysToSubtract)
```

When using the "auto-formatter", VSCode changes it to:

```PowerShell
$numberOfDaysToSubtract = 10
(Get-Date).AddDays( - $numberOfDaysToSubtract)
```

Is that the expected behavior? It does work of course, but I've never seen it written like that ever, so wanted to confirm if it's intented.

Thanks!

**Comment by tylerl0706** [comment]
@AWahlqvist 

So this formatting actually comes from [PSScriptAnalyzer](https://github.com/powershell/psscriptanalyzer). We just get the results from it and make the changes to the code.

Can you move this over to there so the folks that work on PSSA are aware?

**Comment by AWahlqvist** [comment]
Thanks @tylerl0706! I opened up an issue over at the PSSA repo instead!
