### ISSUE TITLE
Not rendering properly ValidatePattern with GUID regex

### ISSUE THREAD

**Issue by lwajswaj** [PowerShell/vscode-powershell#1241]
### System Details

- Operating system name and version: Windows 10 Pro - 1709
- VS Code version: 1.21.0
- PowerShell extension version: 1.6.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

PS C:\Users\Leandro> code -v
1.21.1
79b44aa704ce542d8ca4a3cc44cfca566e7720f1
x64
PS C:\Users\Leandro> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      6      0      0

PS C:\Users\Leandro> code --list-extensions --show-versions
abusaidm.html-snippets@0.2.1
donjayamanne.githistory@0.4.0
gerane.Theme-azure@0.0.2
humao.rest-client@0.17.0
mohsen1.prettify-json@0.0.3
ms-python.python@2018.2.1
ms-vscode.azurecli@0.4.1
ms-vscode.csharp@1.14.0
ms-vscode.PowerShell@1.6.0
patrys.vscode-code-outline@0.0.13
PeterJausovec.vscode-docker@0.0.25
samcogan.arm-snippets@1.1.0
Tyriar.shell-launcher@0.1.6
PS C:\Users\Leandro> $PSVersionTable
```

### Issue Description

I am experiencing a problem with rendering ValidatePattern modifier for parameters with a GUID regex. To reproduce, just create a new .ps1 file and add this code:

```powershell
param(
  [switch]$SkipSoftware,
  [switch]$SkipTest,
  [ValidatePattern("[a-zA-Z0-9]{8}-([a-zA-Z0-9]{4}-){3}[a-zA-Z0-9]{12}")]
  [string]$SubscriptionId = '55848c06-32a7-44ae-b7d6-dadbb940e538'
)

If(!$SkipSoftware)
{
  "Downloading Software..."
  & .\Download-Software.ps1
}

If(!($SkipTest)){
    $TestResults = Invoke-Pester .\azureDeploy.tests.ps1 -PassThru

    if($TestResults.FailedCount -gt 0) {
        throw "Test Task failed"
    }
}

Write-Host "Selecting subscription $SubscriptionId"
Select-AzureRmSubscription -SubscriptionId $SubscriptionId
```

If you add an extra double-quote to the ValidatePattern, it will work. 

### Attached Logs

I'm not experiencing any crash or anything.

**Comment by rkeithhill** [comment]
This is a bug with the TextMate file for PowerShell which lives in a different repo. This particular issue has been submitted on that repo. Please 👍 that issue - https://github.com/PowerShell/EditorSyntax/issues/34
