### ISSUE TITLE
Add Debug feature to set the next line to execute

### ISSUE THREAD

**Issue by MrDRamos** [PowerShell/vscode-powershell#1245]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

I am experiencing a problem with...

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
I don't think this extension can do that without support from the underlying PowerShell debug engine which this extension uses.  You might think about making this request on the https://GitHub.com/powershell/powershell repo.  That said, I'm not sure VSCode even exposes a debug UI for this feature.  We're somewhat limited by what the VSCode debugger UI/API exposes.

**Comment by tylerl0706** [comment]
So is this feature like...

I hit a breakpoint... some button lets me execute the next line without continuing? Or am I misunderstanding

**Comment by rkeithhill** [comment]
No, it's more like moving the IP (instr pointer) to another instruction and telling the program to resume there.  I use this in C# all the time. Step over a method look for a bug, notice that the method returned null when I wasn't expecting it to.  Then I set the next statement to execute up to the method I just had called and then I step into the method, see: https://msdn.microsoft.com/en-us/library/y740d9d3.aspx#Anchor_4

I'm closing this based on the fact that VSCode doesn't intend to implement the UI to support this feature until enough debuggers support it. See - https://github.com/Microsoft/vscode/issues/12514

I suggest filing a feature request on https://GitHub.com/powershell/powershell asking for this support in the PS debugger.
