### ISSUE TITLE
Update Install-VSCode on PSGallery to latest version

### ISSUE THREAD

**Issue by GavinEke** [PowerShell/vscode-powershell#1247]
The PSGallery version of `Install-VSCode` is version 1.0 and should be updated to the latest version (1.2) to include fixes and new functionality.

* PSGallery: https://www.powershellgallery.com/packages/Install-VSCode/
* GitHub: https://github.com/PowerShell/vscode-powershell/blob/master/scripts/Install-VSCode.ps1

**Comment by tylerl0706** [comment]
This is a dupe of #1170. Sorry it's taken so long, I'll get that done this week.
