### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by gabrielrojasnyc** [PowerShell/vscode-powershell#125]
Can vscode-powershell run Powershell workflow. I get
An error occurred while creating the pipeline.
At line:0 char:0

workflow get-World {
    Write-Output "hello"
}
get-World

**Comment by rkeithhill** [comment]
It "runs" for me on version 0.5.0 of the extension which is the latest available.  However I note that while you can set a breakpoint on the `Write-Output "hello"` and the debugger stops, it is in a funky state.

**Comment by daviwil** [comment]
Might have to look into this one.  I haven't tried running workflows at all inside of the language or debug servers so I have no idea what it might do in various cases.  Same for background jobs.

**Comment by maximpashuk** [comment]
Can reproduce problem if "File"->"New File", paste code and launch.
If I save file before launch, then no problem occurs, 'hello' string in output.

So I think this issue can be closed, but instead of this, another issue should be created:
vscode-powershell should not launch unsaved files.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
