### ISSUE TITLE
In the code base, change the language mode, and New-EditorFile fails

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#1250]
Swap the `return` statements, the second works (original), the one with the `language` param set fails.

![image](https://user-images.githubusercontent.com/67258/38116027-589a4678-337c-11e8-9712-5b8f60a86bae.png)

Chatted with @daviwil, could be an issue with new `untitled` files.

**Comment by tylerl0706** [comment]
I looked into this a bit. David is right the problem only happens with Untitled files. Right now, the extension can only interact with PowerShell untitled files using $psEditor:

repro:
1. new untitled file
2. Change language to PowerShell
3. $psEditor.GetEditorContext() # this works
4. Change language to Ruby
5. $psEditor.GetEditorContext() # this fails

We should be able to interact with any Untitled file.

**Comment by cameronove** [comment]
I was going to try to tackle this issue, but wouldn't it actually be an Issue with PowerShellEditorServices?  If I open a normal Powershell console in VSCode it doesn't even recognize the $psEditor variable.  $psEditor seems to only be available in the integrated console.

**Comment by tylerl0706** [comment]
@cameronove well I think the test I'd run is, when you open a new Untitled file, what messages does VSCode send to PowerShell Editor Services (if any)? What messages are sent to PowerShell Editor Services when you set the Language Mode to PowerShell in VSCode?

**Comment by tylerl0706** [comment]
But you're right, it could be an issue with Editor Services handling PowerShell files differently than non-PowerShell files

Or... It could be that VSCode is not notifying Editor Services because it's not a PowerShell file.

**Comment by JustinGrote** [comment]
> repro:

>new untitled file
>Change language to PowerShell
>$psEditor.GetEditorContext() # this works
>Change language to Ruby
>$psEditor.GetEditorContext() # this fails

Looks to me like this is fixed! @dfinke let me know if not.
![image](https://github.com/user-attachments/assets/0822c4b4-76ca-40c1-92ed-1241cec7de1e)
