### ISSUE TITLE
PowerShell intellisense support for Dockerfile

### ISSUE THREAD

**Issue by roblourens** [PowerShell/vscode-powershell#1255]
_From @kasunsjc on March 31, 2018 10:49_

Hi Team,

PowerShell intellisense support for Dockerfile will be a great feature to write Dockerfile to have less typos. This will help when typing long RUN commands in dockerfile.

Thanks 

_Copied from original issue: Microsoft/vscode#47024_

**Comment by tylerl0706** [comment]
This is an interesting ask... The first question that comes to mind is, would it make sense for this logic to exist in the PowerShell extension, or the Docker extension?

I know that it's possible to have extensions with dependent extensions... I wonder if a 3rd extension (that depends on PowerShell and Docker) could be made that glues together these extensions.

An interesting issue. Thanks for this!
