### ISSUE TITLE
Get-Item and Test-Path failes for some registry entries in Integrated console

### ISSUE THREAD

**Issue by pramodag** [PowerShell/vscode-powershell#1271]
### System Details

- Operating system name and version: Windows 10 Enterprise
- VS Code version: 1.22.2
- PowerShell extension version: 1.6.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

PowerShell Integrated Console

PS C:\Scripts\PowerShell-Modules> code -v
1.22.2
3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
x64
PS C:\Scripts\PowerShell-Modules> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      6      0      0


PS C:\Scripts\PowerShell-Modules> code --list-extensions --show-versions
DotJoshJohnson.xml@1.9.2
eliean.vscode-svn@0.1.0
in4margaret.compareit@0.0.2
johnstoncode.svn-scm@1.29.0
ms-vscode.PowerShell@1.6.0
sandy081.todotasks@0.5.0
streetsidesoftware.code-spell-checker@1.6.7
wayou.vscode-todo-highlight@0.5.12
PS C:\Scripts\PowerShell-Modules> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Get-Item and Test-Item failes with Can not find path error in Integrated console. But when the same command is executed in Windows Powershell console in VS code or the Windows PowerShell window it works fine. I am executing all sessions with admin privilages and same user.

Execution screenshots:
Integrated console:
![image](https://user-images.githubusercontent.com/649141/38796343-6d5ed6b8-415b-11e8-9e51-760826d9d517.png)

VS code PowerShell console:
![image](https://user-images.githubusercontent.com/649141/38796459-cb773812-415b-11e8-8492-09c82af2977a.png)

Windows PowerShell window:
![image](https://user-images.githubusercontent.com/649141/38796553-0314a21e-415c-11e8-8dc0-dff5d7dd30b6.png)

This was working fine earlier. I belive the issue is from Feb release.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.
[VS Code logs.zip](https://github.com/PowerShell/vscode-powershell/files/1914314/VS.Code.logs.zip)

**Comment by rjmholt** [comment]
Hi @pramodag, thanks for opening an issue!

Because I don't have the particular registry paths you've got above, I can't reproduce this issue; everything seems to work for `Get-Item "HKLM:\Software\"`. I tried it with `Get-Item "HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps" and still got the same result in all consoles.

Is there a common registry key you can reproduce this behaviour with? Otherwise, we might need some details of how that particular registry entry was created so that we create a dummy version and reproduce this bug ourselves.

I'm suspicious that this might be a permissions thing. So it could be anything from the way we handle the EditorServices process to VSCode itself having funny permissions.

**Comment by pramodag** [comment]
Dear @rjmholt 
 Thanks for your response. I believe it was something wrong with VS code. I did a complete uninstall of VS code and installed again. Now I get the same result on all consoles. I should have done it before opening the issue :(

**Comment by tylerl0706** [comment]
No worries! Glad it's fixed for you, @pramodag! If you ever have any trouble, you can always open an issue 🙂
