### ISSUE TITLE
Add Syntax Aware Code Folder (when available)

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/vscode-powershell#1276]
from the VS Code release notes

>Folding Provider API
>To enable extensions to provide language aware folding ranges, a new provider API is proposed:
>```javascript
>export namespace languages {
>  /**
>    * Register a folding provider.
>    *
>    * Multiple folding can be registered for a language. In that case providers are sorted
>    * by their [score](#languages.match) and the best-matching provider is used. Failure
>    * of the selected provider will cause a failure of the whole operation.
>    *
>    * @param selector A selector that defines the documents this provider is applicable to.
>    * @param provider A folding provider.
>    * @return A [disposable](#Disposable) that unregisters this provider when being disposed.
>    */
>  export function registerFoldingProvider(selector: DocumentSelector, provider: FoldingProvider): Disposable;
>}
>```
> See the full APIs [here](https://github.com/Microsoft/vscode/blob/21bfdd43b16707a07961f6d2b9d7782e5ea28d27/src/vs/vscode.proposed.d.ts#L42).
> The equivalent APIs are proposed [here](https://www.npmjs.com/package/vscode-languageserver-protocol-foldingprovider) as protocol extensions to the language server protocol. Feedback is welcome!

**Comment by tylerl0706** [comment]
Collapsible/expandable Functions, Regions, Comment blocks, and Comment based help blocks

**Comment by tylerl0706** [comment]
duping this to https://github.com/PowerShell/vscode-powershell/issues/1336
