### ISSUE TITLE
Command `Run Selected Text in active Terminal` doen't execute Command when a NewLine is Selected

### ISSUE THREAD

**Issue by fbehrens** [PowerShell/vscode-powershell#1278]
Hi,
i just want to report a little detail which would help my transition from sublime to vsCode.
I am used to develop in a very interactive way, where I am always pasting code from my editor to a terminal window. 

I observed that the VsVode `integrated Terminal` seem to paste line by line, and can't handle multiline snippets as:
```powershell
@{
    a=1
}
```

However this extensions comes with an own `Powershell` Terminal-Window where this is "almost" working. I said "almost" because when I select above Hash with a training newline (which happens naturally if you select with `shift`+`down` )  and then execute the command `Run Selected Text in active Terminal` the code is pasted but not executed (see following result):
```
PS C:\scripts2\libwba> @{
>>   a=1
>> }
>>
```
I have to then switch to the terminal and press `enter` to execute it.

I would consider it helpful if you would change the behaviour, 
so that the command is executed when a final newline is selected.

**Comment by tylerl0706** [comment]
@fbehrens welcome to VSCode! 😄

Let me address your comments:
* pasting multiline code will be fixed when the Integrated Console gets PSReadline support that @SeeminglyScience has been working hard on 🙂 we're tracking that with this bug here #535 

As a work around, you should try this feature of VSCode...

Select some code in your editor and hit `F8`! That will run the selected code in the Integrated terminal. That supports multiline.

**Comment by fbehrens** [comment]
@tylerl0706 Thanks a lot. `F8` works great for me. 

Looking forward for PSReadline support. 

I wonder what makes it so hard to provide a PSReadline Terminal. In my sublime world, the terminal is completely decoupled from the Terminal, whatever process is running there.

Another little feedback is the feature that i miss the most is `Goto Symbol in Workspace` having all Powershell functions.

**Comment by fbehrens** [comment]
@tylerl0706  Mucho thanks, again. I learned that the editor is connected via the Language Service to the `Powershell Integrated Console`. Yes I knew about `F12` and the forward/back navigation.  But what I am missing a little, is the feature to fuzzy search in a `CTRL-P` like selectbox with all my functions.

**Comment by tylerl0706** [comment]
I think Ctrl-T shows symbols that are loaded in the runspace. Example:

Let's say you have 2 files:

* test.psm1
* test.ps1

In test.psm1:
```powershell
function Get-Foo () {
    Write-Host "foo"
}
Export-ModuleMember -Function 'Get-Foo'
```

in test.ps1:
```powershell
Import-Module ./test.psm1
```

If you do an F8 on the Import-Module in test.ps1, then the symbol for Get-Foo shows up.

**Comment by fbehrens** [comment]
@tylerl0706  thanks for going after this issue.  Crtl-T shows only Symbols of opened editors `code 1.22.2 
 vscode-powershell 1.7.0`

![image](https://user-images.githubusercontent.com/13704/39348483-9a3b78ae-49f7-11e8-9f4e-0a7eb9e19dfe.png)

![image](https://user-images.githubusercontent.com/13704/39348921-587e8224-49f9-11e8-839c-4589b9db2e5f.png)
