### ISSUE TITLE
posh extension crashing on debian linux

### ISSUE THREAD

**Issue by SolidCore-IA** [PowerShell/vscode-powershell#1283]
## Issue Description ##

I am experiencing a problem were the powershell extension keeps crashing on Debian 9.4 linux. Error is "The powershell session has terminated due to an error, would you like to restart it?". I thought at first it was because of the integrated terminal, but I disabled the integrated terminal to auto-start. It happens with all ps1 or psm1 files when I open them or if I try to add a function using the auto-fill menu for powershell functions.
Restarting the extension, disable/enable, and reinstalled the extension same issue.

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1935985/logs.zip)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Linux x64 4.9.0-6-amd64 |
| VSCode | 1.22.2|
| PowerShell Extension Version | 1.6.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|6.1.0-preview.1|
|PSEdition|Core|
|GitCommitId|v6.1.0-preview.1|
|OS|Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02)|
|Platform|Unix|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.1.0-preview.1|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|arc-plus|ph-hawkins|1.0.1|
|nord-visual-studio-code|arcticicestudio|0.6.0|
|path-intellisense|christian-kohler|1.4.2|
|PowerShell|ms-vscode|1.6.0|
|python|ms-python|2018.3.1|
|reg|ionutvmi|0.0.2|
|vscode-github|KnisterPeter|0.27.1|;

</details>

**Comment by tylerl0706** [comment]
Hi there, thanks for this report. We'll take a look! I just want to say that if you delete the integrated terminal, you basically get rid of all the good features of the extension (rich intellisense, script analyzer squiggles, the ability to run something with F8)

Can you do me a favor and set your logs to `Diagnostic`? This will give us a 3rd log that I'm interested in. Just attach the zip of all 3 logs when the error occurs.

We'll figure this out 😀

**Comment by tylerl0706** [comment]
Is this the setting you changed?:
`"powershell.integratedConsole.showOnStartup": false`

I'm having a hard time reproducing this. 

Just curious, what do you get if you don't disable the integrated terminal?

**Comment by tylerl0706** [comment]
So the extension still crashes... Can you send me the log of it crashing without you disabling the integrated console? The error might look the same but the underlying exception might give a better idea.

The logs that you provided so far are good, but they seem to only tell me it crashes when kill the integrated console.

**Comment by SolidCore-IA** [comment]
Logs as requested below. I did the diag logs and not verb; hope that was right. 
So, I open a posh profile file, the integrated console opened, it did a bunch of verbose stuff in the console, then I stepped away for a minute, and came back to the error and the crash. Told the extension to restart and then it crashed again. I didnt even touch the file itself in vscode. 
I may try reinstalling when I have time?

[vscodelogs.zip](https://github.com/PowerShell/vscode-powershell/files/1972422/vscodelogs.zip)

**Comment by rkeithhill** [comment]
In the one log it looks like PSSA came back with 4 violations:

* The cmdlet 'check-module' uses an unapproved verb. (PSUseApprovedVerbs)
* The variable 'pscr' is assigned but never used. (PSUseDeclaredVarsMoreThanAssignments)
* The variable 'logdir' is assigned but never used. (PSUseDeclaredVarsMoreThanAssignments)
* The variable 'desk' is assigned but never used. (PSUseDeclaredVarsMoreThanAssignments)

Then a code action was invoked.  Looks like PSES read the message, returned an empty result message and then there was no more output - hard crash.   Do you remember which code fix you invoked in this case?

**Comment by SolidCore-IA** [comment]
Sorry, code fix? 
I can open that same ps1 profile in vscode (all the same extensions) on a windows 7 x64 workstation w/ posh v5.1 installed; no crashes like on my debian workstation. I am aware of those "violations" but they dont cash my extenstion on windows. Is this an issue with posh v6 on my linux?

**Comment by rjmholt** [comment]
@SolidCore-IA are you still experiencing this crash?

**Comment by SolidCore-IA** [comment]
yes I am still having this issue. With a fully update debian 9.5, vscode, and powershell core.

**Comment by SolidCore-IA** [comment]
tested today with a blank .ps1 file and still getting crashes from the powershell plug-in. A bunch of fresh logs attached. At this point I cant work with powershell files and the powershell plug-in at the same time at all.
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/2308863/logs.zip)

**Comment by rkeithhill** [comment]
Thanks for attaching the logs.  I can now repro this issue (on Windows).  Essentially, create an Untitled-1 file, paste in the following text:
```
testS\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
```
Convert the `\n` to newlines, set the editor file type to PowerShell, then go to the end of the press, press enter a few times and then back space the same number.  That caused the same exception for me:
```

    System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
    Parameter name: Position 343:1 is outside of the line range of 1 to 342.
       at Microsoft.PowerShell.EditorServices.ScriptFile.ValidatePosition(Int32 line, Int32 column)
       at Microsoft.PowerShell.EditorServices.ScriptFile.ApplyChange(FileChange fileChange)
       at Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.HandleDidChangeTextDocumentNotification(DidChangeTextDocumentParams textChangeParams, EventContext eventContext)
```

**Comment by SolidCore-IA** [comment]
I get this crash on any powershell script or module. The /n lines were just me waiting for it to crash. It happens with in 60 secs of what I think is the powershell extensions loading on any posh file.

**Comment by rjmholt** [comment]
This looks like the same cause as https://github.com/PowerShell/vscode-powershell/issues/1492

**Comment by rjmholt** [comment]
Also this one: https://github.com/PowerShell/vscode-powershell/issues/1453

**Comment by rjmholt** [comment]
I've just realised the commonality in all these issues is adding a new line to the end of the file -- there seems to be an off-by-one problem there. Seems related to https://github.com/PowerShell/PowerShellEditorServices/pull/573 maybe?

**Comment by SolidCore-IA** [comment]
I guess Im a little confused. How do I obtain this fix? Wait for the next extension release?

**Comment by tylerl0706** [comment]
Yeah we're planning on doing a release this week.

**Comment by SolidCore-IA** [comment]
I have the update on the extension and still crashing. It crashes with a blank .ps1 file open. All new logs attached; including the blank .ps1 file I created only to test this.
[morelogs.zip](https://github.com/PowerShell/vscode-powershell/files/2344251/morelogs.zip)
