### ISSUE TITLE
Integrated Console unable to run scripts.

### ISSUE THREAD

**Issue by jkavanagh58** [PowerShell/vscode-powershell#1284]
### System Details

- Operating system name and version: Windows 10 15603
- VS Code version: 1.22,2
- PowerShell extension version: 1.6.0
- Output from `$PSVersionTable`:
```
Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      5.1.15063.966                                                                                                                                                      
PSEdition                      Desktop                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                            
BuildVersion                   10.0.15063.966                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                
SerializationVersion           1.1.0.1                                                                                                                                                            
```

Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```
1.22.2
3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
x64
PS h:\.Scripts\Automation> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      6      0      0


PS h:\.Scripts\Automation> code --list-extensions --show-versions
amcdnl.ice-ice-baby@1.0.1
AndrewMoll.WeatherExtension@0.1.3
carmelopullara.material-dark-extra@0.3.0
CoenraadS.bracket-pair-colorizer@1.0.37
cpmcgrath.codealignment-vscode@2.0.19
docsmsft.docs-markdown@0.0.1
DotJoshJohnson.xml@1.9.2
DougFinke.vscode-PSStackoverflow@0.0.2
eamodio.gitlens@8.2.4
fabiospampinato.vscode-projects-plus@1.16.2
fabiospampinato.vscode-projects-plus-todo-plus@1.6.0
fabiospampinato.vscode-todo-plus@1.10.7
gerane.Theme-Blackboard@0.0.2
HookyQR.beautify@1.3.0
idbartosz.darkpp-italic@0.0.6
jeppeandersen.vstsservicestatus@1.3.0
jsynowiec.vscode-insertdatestring@2.2.2
juha-ristolainen.code-stats-vscode@1.0.8
kenhowardpdx.vscode-gist@1.2.0
mdickin.markdown-shortcuts@0.8.1
mrmlnc.vscode-remark@1.1.0
ms-vscode.azure-account@0.4.0
ms-vscode.csharp@1.14.0
ms-vscode.PowerShell@1.6.0
ms-vsts.team@1.133.0
RolandGreim.sharecode@0.4.1
shd101wyy.markdown-preview-enhanced@0.3.5
sozercan.slack@0.0.14
stefanstranger.vscode-microsoftteams@1.0.6
tittoassini.vscode-planner@0.3.1
WakaTime.vscode-wakatime@1.2.1
wayou.vscode-todo-highlight@0.5.12
yzhang.markdown-all-in-one@1.2.0
```

### Issue Description

I am experiencing a problem with...
Unable to run any scripts in the "PowerShell Integated" console: is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
VSCode Powershell "powershell", ISE, CLI, PowerShell Studio not effected. ExecutionPolicy is RemoteSigned
VS Code version: Code 1.22.2 (3aeede7, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.15063

### Attached Logs
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/1939352/EditorServices.log)
C:\Users\vndtekjxk\.vscode\extensions\ms-vscode.powershell-1.6.0\logs\1524502719-60be26c5-d91c-4067-88b5-8a1a3928c5451524500680309\vscode-powershell.log
Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by jkavanagh58** [comment]
Nothing really in this log
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/1939559/vscode-powershell.log)

**Comment by jkavanagh58** [comment]
interesting enough, select script contents and press **F8** works

**Comment by tylerl0706** [comment]
This is very strange and I can't repro it either which leads me to believe that it's a permission issue with VSCode specifically (where as powershell.exe and ISE are preinstalled so that's why we don't see it). There's a lot of talk on permissions regarding group policy over here: https://github.com/PowerShell/vscode-powershell/issues/1048 does any of that apply to you?

**Comment by jkavanagh58** [comment]
Just throwing it out there... PowerShell terminal loads the profiles, PowerShell Integrated is where it fails...
![code_2018-04-25_10-58-40](https://user-images.githubusercontent.com/4750977/39254368-eb0380aa-4877-11e8-84b3-5c75cbc3edae.png)

**Comment by rkeithhill** [comment]
Could you try disabling all your other extensions (except PowerShell of course) and try to repro the issue?

**Comment by jkavanagh58** [comment]
Same results @rkeithhill. I am thinking possibly a GPO because things were working well on Monday,  and today I noticed some odd issues with PowerCLI as well. I just don't know how in the PowerShell terminal it works without issue but in the integrated terminal it does not. No issues loading 6.0.2 shell but 5.1 x86 and x64 do experience the profile as well as any other ps1.

**Comment by rkeithhill** [comment]
So `6.0.2` uses profiles from a different directory - `~\Documents\PowerShell` instead of `~\Documents\WindowsPowerShell`.  Also, I don't "think" that group policy settings apply to PS Core. 

Are you profile scripts signed?  If so, are they blocked i.e. have the Internet Zone.Identifier on them?  You can check that with  `Get-Item <path-to-profile> -Stream *`.  If you see `Zone.Identifier` in the output then the file is blocked.

**Comment by jkavanagh58** [comment]
Yeah clearly not VSCode Powershell extension issue. I noticed that in none of my shells, hosted or standard CLI that my function prompt {..}  wasn't working. If I call prompt for testing... it fails... I made a minor change to the function profile.ps1. Works like a charm when Run As Administrator but standard start of CLI I get
Cannot invoke method. Method invocation is supported only on core types in this language mode.
Based on error message this is the offending line:
    $CurrentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())

back to the drawing board

**Comment by jkavanagh58** [comment]
Starting to appear this is a recent AppLocker policy

**Comment by jkavanagh58** [comment]
Started working through the issue, CLI and ISE is working now, VSCode still experiencing:
PowerShell Integrated Console

The term 'C:\Users\vndtekjxk\Documents\WindowsPowerShell\profile.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:0 char:0
PS C:\Users\vndtekjxk\Documents\GitHub\ServiceDelivery>

**Comment by jkavanagh58** [comment]
Working through I now have the CLI and ISE working without issue but VSCode PowerShell Integrated Console fails to load the profile.ps1 from my WindowsPowerShell folder. Not sure where the difference between a hosted instance like ISE and VSCode would be.

**Comment by tylerl0706** [comment]
@jkavanagh58 did you figure this out?
