### ISSUE TITLE
Tab completion doesn’t work inside script blocks.

### ISSUE THREAD

**Issue by benlavender** [PowerShell/vscode-powershell#1292]
Hi, it seems when attempting to use the tab completion feature in script blocks there is no completion, except a tab spaces are added instead. 

There appears to be some issues in the open issues with auto-completion but not sure if mine relates to the issue.

Thanks :+1:

**Comment by tylerl0706** [comment]
Thanks for the report. Can you please attach the log so that we can investigate?

The instructions can be found here:
https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

**Comment by benlavender** [comment]
I don’t seem to be getting the issue any more so will re-open if it occurs again and provide logs.
