### ISSUE TITLE
VSCode pause button eventually quits responding to mouse clicks in long running powershell script

### ISSUE THREAD

**Issue by osudude** [PowerShell/vscode-powershell#1294]
Have a long running powershell script that iteratively queries mssql and then queries the underlying file system and writes the results to a file.  Since code runs for a long time, I like to periodically pause execution and look at the internal progress.  Pause button works great for the first several  hours of script execution.   Some point after 24 hours of continuous running VSCode Pause button no longer acknowledges click event in powershell script even though the script is clearly still running.  Using VSCode over remote desktop if it matters.

```
1.22.2
3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
x64

Major  Minor  Build  Revision
-----  -----  -----  --------
1      6      0      0

ms-vscode.PowerShell@1.6.0

PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Windows 6.1.7601
```

**Comment by tylerl0706** [comment]
Thanks for the report! Are you running the script with F5 (aka with debugging)? Also, can you please attach the logs? Instructions can be found here:

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

I can't say this is a common use-case of the debugger. This issue could really be an issue with our debug adapter, vscode, or even PowerShell itself.

**Comment by osudude** [comment]
F5 debug

**Comment by tylerl0706** [comment]
Thanks for that! Can you also attach the logs?

**Comment by osudude** [comment]
Looks like VSCode just updated PowerShell Extension to newer version.   If I can reproduce will attach log.
