### ISSUE TITLE
Backtick ` in Terminal window not parsed correctly

### ISSUE THREAD

**Issue by sonjz** [PowerShell/vscode-powershell#1299]
### System Details

- Operating system name and version: Window 10
- VS Code version: 1.21.1
- PowerShell extension version: 1.7.0
- Output from `$PSVersionTable`:

```
1.21.1
79b44aa704ce542d8ca4a3cc44cfca566e7720f1
x64

formulahendry.dotnet@0.0.4
haaaad.ansible@0.2.8
hangxingliu.vscode-nginx-conf-hint@0.0.5
jmrog.vscode-nuget-package-manager@1.1.6
mrcrowl.hg@1.2.3
ms-vscode.csharp@1.14.0
ms-vscode.PowerShell@1.7.0
NigelRook.vscode-linter-erlc@0.5.1
prokopiy.vscode-erlang-workbench@0.0.9
shanoor.vscode-nginx@0.5.0
sysninja.vscode-ansible-mod@0.0.3
timonwong.ansible-autocomplete@0.0.2
vscoss.vscode-ansible@0.1.5

Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
I have some bootstrap code that I was testing and noticed an issue in VSC Terminal: Powershell .  Here is a portion of code I attempted to copy and paste.
```
npm install `
  redis `
  bluebird `
  json-stringify-pretty-compact `
;
```
Pasting into Powershell had no issues.
![image](https://user-images.githubusercontent.com/1714763/39365193-dbd36d30-4a06-11e8-8905-e4198ea86055.png)

But in VSC Terminal: Powershell:
![image](https://user-images.githubusercontent.com/1714763/39365348-3cd1b736-4a07-11e8-8e4f-5efe81ba0f6d.png)

It appears the backtick isn't being parsed correctly.

**Comment by tylerl0706** [comment]
This will come with the addition of PSReadLine :) drop a comment and a :+1: over there!

I'm going to dupe this to that.
