### ISSUE TITLE
missed something ? no intellisense for built-in cmdlet

### ISSUE THREAD

**Issue by kayasax** [PowerShell/vscode-powershell#13]
jsut installed vs code + powershell extension and restarted vs code.
Now create a new .ps1 file, typing get- then [ctr]>+[space]  I'm getting No suggestion message.
Go to definition don't seems to work either... 
Any thoughts ?

**Comment by badchenn** [comment]
Have you verified that Powershell v5 is installed?

**Comment by kayasax** [comment]
I've installed  wmf5 after vscode-powershell. Still have no intellisense
after restart. Should I reinstall  vscode?

**Comment by daviwil** [comment]
Hi kayasax, could you try this again and then check the file in this location and see if there's an error at the end:

c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell\bin\EditorServices.log

If you see an error at the end, copy and paste it here.

Thanks!

**Comment by kayasax** [comment]
Removing and reinstalling the extension have fixed the problem.
