### ISSUE TITLE
Linux. The console crashes if you use functions and the script is in a folder in Cyrillic.

### ISSUE THREAD

**Issue by themaximax** [PowerShell/vscode-powershell#1306]
**Description of the problem**
If the script is in the folder with the folder name in Cyrillic, the powershell console stops working, and the functions should be used in the script.

If the script is written without functions, then the integrated console works fine. Also, the integrated console works if there is no Cyrillic in the location path, regardless of whether it contains functions or not.

I attach [2 logs](https://github.com/PowerShell/vscode-powershell/files/1960862/logs.zip), one with an error (in a folder in Cyrillic), the second without an error (a folder in Latin).

**My system**
Visual Studio Code v1.22.2 64-bit
PowerShell Extension v1.7.0
Operating System: Ubuntu Linux 16.04 64-bit

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1960862/logs.zip)

**Comment by tylerl0706** [comment]
Thanks for the report! We'll look into it.

**Comment by mklement0** [comment]
@tylerl0706: I think in this case the workaround is to ensure that the PS scripts are saved as UTF-8 _with BOM_:

Click on `UTF-8` in the VS Code status bar, choose `Save with Encoding`, then select `UTF-8 with BOM` and re-execute the script - see https://github.com/PowerShell/vscode-powershell/issues/1392#issuecomment-402369250

**Comment by mklement0** [comment]
@tylerl0706: 

Actually, on Unix-like platforms there is no need for this workaround, as these are the default values there.

I can confirm that the issue still exists in VSCode 1.25.0 / PowerShell extension 1.7.0  and that it is indeed - curiously - tied to whether the script file contains at least 1 function definition or not (the encoding of the script doesn't seem to matter).

**Comment by rjmholt** [comment]
@themaximax I believe we have fixed this in the most recent release: https://github.com/PowerShell/vscode-powershell/issues/1513.

Please re-open if you see the issue recur in 1.9.0
