### ISSUE TITLE
Variable IntelliSense completion in quotation marks

### ISSUE THREAD

**Issue by valdearg** [PowerShell/vscode-powershell#1309]
### System Details

- Operating system name and version: Windows 10 1803
- VS Code version: 1.23.0
- PowerShell extension version: 1.7.0
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.17134.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v

1.23.0
7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
x64

$pseditor.EditorServicesVersion
code --list-extensions --show-versions
anweber.vscode-tidyhtml@1.10.0
azuresdkteam.azurenodeessentials@0.2.6
bbenoist.QML@1.0.0
christian-kohler.npm-intellisense@1.3.0
dbaeumer.vscode-eslint@1.4.8
DotJoshJohnson.xml@1.9.2
eg2.vscode-npm-script@0.3.4
eriklynd.json-tools@1.0.2
foxundermoon.shell-format@1.1.3
ms-python.python@2018.4.0
ms-vscode.csharp@1.14.0
ms-vscode.PowerShell@1.7.0
msazurermtools.azurerm-vscode-tools@0.4.0
msjsdiag.debugger-for-chrome@4.3.0
robertohuertasm.vscode-icons@7.23.0
samverschueren.yo@0.9.3
shakram02.bash-beautify@0.1.1
Tyriar.shell-launcher@0.1.6
```

### Issue Description

When using a string with a variable in, the variable name does not auto-complete with IntelliSense like when outside the string.

For example you have the following code:
```
$var_test_1 = "This is a variable"
Write-Host "Test string $var_test_1"
```
![img](https://u.teknik.io/xwSIQ.png)

What I would expect would be when I start typing the $var section that I would be given the created variable name.

When outside the quotes the variable name is provided. E.g.
```
$var_test_1 = "This is a variable"
Write-Host "var: " $var_test_1
```
If I just enter $v I'm provided with the full name $var_test_1

![img](https://u.teknik.io/DHBY6.png)

**Comment by joeyaiello** [comment]
Validated that this is a legitimate bug, and doesn't occur unless you're in VS Code.

**Comment by bland328** [comment]
I, too, would love to see this fixed, as well, and hoping to cover the case mentioned above...

    this_autocompletes="$this_does_not"

...as well as this case, in which the variable name is within both brackets and double quotes...

    this_autocompletes="${this_does_not}"

...not to mention this case that I run into plenty when building strings:

    this_autocompletes="But this one '${does_not}'..."

Thanks for looking at this!

**Comment by moymike** [comment]
I'm Powershell Preview 2020.2.0 and this is still an issue.

**Comment by rjmholt** [comment]
Oh I just realised this isn't a completion bug, it's a completion *trigger* issue; it you press <kbd>Ctrl</kbd>+<kbd>Space</kbd>, you get the intellisense.

We need some way of telling VSCode to trigger a completion, but I'm not sure if that's possible within strings. We'll have to look into it

**Comment by andschwa** [comment]
Hi all, I looked into this and it's actually a VS Code setting. To enable this, you need to go to the setting `editor.quickSuggestions` and then for the `strings` item set its value to `on`, then it works as desired. Cheers!

**Comment by valdearg** [comment]
Ah, that is indeed the solution. Thanks for this!
