### ISSUE TITLE
Unable to start the debugger

### ISSUE THREAD

**Issue by chaoticsoftware** [PowerShell/vscode-powershell#131]
It might be that I'm doing something wrong, but I have a script that I've been trying to debug with no success. I copy/pasted the script in a different folder, and managed to get the debugger started with the following launch.json (default):

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "PowerShell",
			"type": "PowerShell",
			"request": "launch",
			"program": "${file}",
			"args": [],
			"cwd": "${file}"
		},
		{
			"name": "PowerShell x86",
			"type": "PowerShell x86",
			"request": "launch",
			"program": "${file}",
			"args": [],
			"cwd": "${file}"
		}
	]
}
```

However in the original directory, it doesn't work, which makes little sense. The only thing I could think of was that I have more than one script file in that directory, so I tried playing with different values for "program" and tried the following values, none of which were successful. I have no idea what else should I do...

```
 			"program": "${file}",
			"program": "Do-Something.ps1",
			"program": "${workspaceRoot}Do-Something.ps1",
			"program": "${workspaceRoot}\\Do-Something.ps1",
			"program": "E:\\Do-Something.ps1",
```

Everything I tried takes me back to the launch.json with the error "Please set up the launch configuration file to debug your application."

What am I doing wrong?

**Comment by daviwil** [comment]
Could you drag and drop the following file into the comment box:

`c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell-0.5.0\bin\DebugAdapter.log`

That'll help us figure out what's going on.

**Comment by chaoticsoftware** [comment]
I noticed when I try to start the debugger from the directory where I originally had my script, and it doesn't work, nothing is logged either. All the log activity you see in the attached file, is from when I started it from the alternate location.
[DebugAdapter.txt](https://github.com/PowerShell/vscode-powershell/files/200272/DebugAdapter.txt)

**Comment by chaoticsoftware** [comment]
Weird. After I restarted my machine today, it stopped happening.

**Comment by rkeithhill** [comment]
I wonder if debug host process got wedged somehow and the restart killed the wedged process?

**Comment by daviwil** [comment]
Hmmm, if it ever shows up again, let us know.  I noticed when looking at the logs, we logged that execution had completed maybe 4 different times.  That seems a little wrong...  Is your test script really short?

**Comment by daviwil** [comment]
Closing this for now since the issue has gone away, please reopen if you see it again!
