### ISSUE TITLE
Integrated Console Failing to Start After Powershell.exe.config Binding Redirect

### ISSUE THREAD

**Issue by wesleytsai** [PowerShell/vscode-powershell#1316]
### System Details

1.23.0
7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
x64
dbankier.vscode-instant-markdown@1.4.1
ms-vscode.csharp@1.15.0
ms-vscode.PowerShell@1.7.0
streetsidesoftware.code-spell-checker@1.6.10
vscodevim.vim@0.11.6

----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

Hi, I know this isn't inherent to the vscode-powershell extension, but may be a more broad VS Code question, but I'm running into an issue where the Integrated powershell console fails to start up after I changed some assembly redirects for my in my powershell.exe.config. (Newtonsoft.Json to v10)

![image](https://user-images.githubusercontent.com/3278848/39897755-956e69fa-5468-11e8-8df1-7c34bd2c6a88.png)

![image](https://user-images.githubusercontent.com/3278848/39897595-ca5687de-5467-11e8-9547-43082c2b424b.png)

In the logs, the extension is clearly failing to start up because it requires v9 Newtonsoft.Json, so I'm wondering if I need to add another redirect elsewhere in the extension to make this work?

Thanks

### Attached Logs
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/1993457/EditorServices.log)

**Comment by tylerl0706** [comment]
Hi there!

Does the built-in powershell terminal work (the one that came with VSCode)?

If you click the little drop down by "PowerShell Integrated Console" you'll see the option.

**Comment by wesleytsai** [comment]
Hi Tyler, yes, the built in one works, it's only the "Powershell Integrated Console" that's not loading

![image](https://user-images.githubusercontent.com/3278848/39900175-d5b0ccf4-5474-11e8-85be-4c2128dfe71a.png)

**Comment by tylerl0706** [comment]
Ah ok. So you probably need to add another binding redirect for PowerShell Editor Services which is providing all the editor experiences: intellisense, symbols, etc.

That lives in the PowerShell extension folder under:

modules/PowerShellEditorServices/bin I believe.

Here's the repo for Editor Services so you can get a sense for which projects will need the binding redirects:

https://github.com/PowerShell/PowerShellEditorServices

Keep in mind that when the extension updates, you'll have to apply the redirects again.

**Comment by wesleytsai** [comment]
Annnd that worked! Thanks!
