### ISSUE TITLE
"Type not found" for types from referenced assemblies, used in PowerShell 5.0 classes in a module

### ISSUE THREAD

**Issue by madmidi** [PowerShell/vscode-powershell#1329]
- Operating system name and version: `Windows 10 x64 1709`
- VS Code version: `1.23.1`
- PowerShell extension version: `1.7.0`
- Output from `$PSVersionTable`:

```
PSVersion                      5.1.16299.431
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.431
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
code -v:
`1.23.1 d0182c3417d225529c6d5ad24b7572815d0de9ac x64`

$pseditor.EditorServicesVersion:
`1      7      0      0`

code --list-extensions --show-versions:
```
johnstoncode.svn-scm@1.29.0
MS-CEINTL.vscode-language-pack-de@1.23.3
ms-vscode.csharp@1.15.2
ms-vscode.PowerShell@1.7.0
ms-vscode.vs-keybindings@0.2.0
wmaurer.change-case@1.0.0
xyz.local-history@1.6.2
```
Dear Team,
neither your PowerShell extension in VSCode, nor the PoshTools PowerShell extension in VS implement PowerShell 5.0 feature "Classes" very well:

For using .NET types, in a class, from assemblies, you have to load, you've to reference those assemblies in your module's manifest.
If you don't reference them there, PowerShell stops parsing the psm1 file and will not exceute it.
But neither in VSCode, nor in VS, the extension checks the manifest before showing type errors.
Therefor I have 7 "Problems" in my code in VSCode (and VS), because the extensions will not find the types from those external (.NET) assemblies.

This is the bug report for the PoshTools extension in VS:
#https://github.com/adamdriscoll/poshtools/issues/622

Please fix.
You just have to check:
```
f (type is unknown) -and
   (type used in class) -and
   (class is in a module) -and
   (module has manifest) -and
   (manifest references assemblies)
then
   search in the type declaration of those assmeblies' manifests for the unknow type
```

TIA
best regards

**Comment by tylerl0706** [comment]
Hi there, thanks for the report! If you import the module manifest into the current runspace, do the problems go away? To test this, just run:

```
ipmo nameOfManifest.psd1
```

**Comment by madmidi** [comment]
FYI: In my script, which uses my module and its class, I have to refrerence
it with "using module '.\nameOfManifest.psd1'"

2018-05-21 23:25 GMT+02:00 Andreas H <andreashansberg@gmail.com>:

**Comment by madmidi** [comment]
Sorry, I was wrong, my fault:
Because I've included that command on top of the psm1 file AND then ran the
command in the Terminal, I've created that infinit module loading loop
error.
The command "Import-Module manifest.psd1" works.
I just have to edit the psm1 file once a little and the errors disappear.



2018-05-21 23:27 GMT+02:00 Andreas H <andreashansberg@gmail.com>:

**Comment by tylerl0706** [comment]
It's best practice to do something like this:

If you put your `mymodule.psm1` in the `NestedModules` portion of the `manifest.psd1` then you can remove the:
`Import-Module manifest.psd1` from your `psm1` and just import the `psd1` (which will import the `psm1` automatically) in your `ps1`.

**Comment by madmidi** [comment]
sorry, but you haven't read my last mails carefully, I wrote " I have to
refrerence it with "using module '.\nameOfManifest.psd1'" "
and that wouldn't work without referencing the psm1 file in the manifest.
And because I use a class in the psm1 file, I must use "using" and can't
use "Import-Module"
but thanks for the help

2018-05-21 23:42 GMT+02:00 Tyler James Leonhardt <notifications@github.com>:

**Comment by madmidi** [comment]
But what about the solution for the original issue ?
I don't want runt 'Import-Module manifest.psd1" in the terminal every time
after VSCode startet.
And I have to restart VSCode after EVERY debug run, because it's caching
the class code and other debugging issues ....

2018-05-22 12:55 GMT+02:00 Andreas H <andreashansberg@gmail.com>:

**Comment by SeeminglyScience** [comment]
@madmidi This is an issue with the PowerShell parser.  The ideal workflow is that you include a `using assembly ./mylib.dll` statement at the top of the `ps1` file containing the classes.  However, that currently doesn't do anything at parse time, only at runtime.

Check out PowerShell/PowerShell#6653, PowerShell/PowerShell#3641 for more info.

As a workaround until it's fixed in the parser, the next version of PSScriptAnalyzer (the module that generates syntax markers for this extension) has a change by the wonderful @bergmeister to no longer display these type not found errors in it's diagnostics.

**Comment by bergmeister** [comment]
PSScriptAnalyzer will release this week (possibly today) and will catch this error and only output a warning instead of re-throwing the parser exception (because it is still able to analyse the rest of the script). Otherwise it is a limitation of the parser.

**Comment by rjmholt** [comment]
Hi @madmidi, this is actually a PowerShell issue, rather than one with the VSCode extension. It's being worked on currently (in PowerShell).

In addition to what @SeeminglyScience linked, have a look at https://github.com/PowerShell/PowerShell/issues/6652.
