### ISSUE TITLE
Debugger crash with message _Debug adapter process has terminated unexpectedly_

### ISSUE THREAD

**Issue by vstiebe** [PowerShell/vscode-powershell#1334]
### System Details

- Operating system name and version: Microsoft Windows 10 (1803)
- VS Code version: 1.23.1
- PowerShell extension version: 1.7.0
- Output from `$PSVersionTable`:
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:
PS C:\infra> code -v
1.23.1
d0182c3417d225529c6d5ad24b7572815d0de9ac
x64
PS C:\infra> $pseditor.EditorServicesVersion
PS C:\infra> code --list-extensions --show-versions
alefragnani.Bookmarks@0.19.1
bierner.markdown-mermaid@1.0.0
DotJoshJohnson.xml@1.9.2
golf1052.code-sync@2.5.3
ms-vscode.PowerShell@1.7.0
PeterJausovec.vscode-docker@0.0.27
sensourceinc.vscode-sql-beautify@0.0.4
Wosi.omnipascal@0.15.0

PS C:\infra> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.48
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.48
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\infra>
```

### Issue Description

Can't execute scripts on debugger using _F5 - Start Debugging_.
Even a simple one like this.
```
write-host "Test"
```

Using the _F8_ shortcut it works.

### Attached Logs

[logs-diagnostic.zip](https://github.com/PowerShell/vscode-powershell/files/2039699/logs-diagnostic.zip)
[logs-verbose.zip](https://github.com/PowerShell/vscode-powershell/files/2039700/logs-verbose.zip)

**Comment by tylerl0706** [comment]
Thanks for the info! We'll take a look 👍

**Comment by raandree** [comment]
+1

Right now I cannot debug scripts anymore in vscode due to that issue. At least I have the same error message.

In general, the debug experience is quite awful and VSCode takes up to 30GB or RAM and crashes quite often when debugging DSC projects.

**Comment by rjmholt** [comment]
Looks like this particular issue is a race condition -- the script file name is unset after the task is fired.
