### ISSUE TITLE
Collapsible/expandable Functions, Regions, Comment blocks, and Comment based help blocks

### ISSUE THREAD

**Issue by Shane091490** [PowerShell/vscode-powershell#1336]
**Summary of the new feature**

As a user I want to be able to collapse and expand Functions, Regions, Comment blocks, and Comment based help blocks. This helps me goto the section/region of code that I want to work on without having to scroll through thousands of lines of code to find the section I need. 

I really like all the features in VS code however without this feature it is a deal breaker for me, I would rather use PS ISE or VS Community as they have this feature and makes my work much easier. I don't like having to scroll thru thousands of lines of code to find the section I need. I designed my tool with regions but I can't use them with VS code,

**Comment by rjmholt** [comment]
I believe VSCode recently introduced various folding features:
* https://code.visualstudio.com/docs/editor/codebasics#_folding
* https://code.visualstudio.com/updates/v1_23#_folding-provider-api

There are a number of similar user asks here:
* https://github.com/PowerShell/vscode-powershell/issues/1335
* https://github.com/PowerShell/vscode-powershell/issues/157
* https://github.com/PowerShell/vscode-powershell/issues/525
* https://github.com/PowerShell/vscode-powershell/issues/177
* https://github.com/PowerShell/vscode-powershell/issues/1276

There is currently some other work prioritised, but it looks like there are a few related pieces of functionality here that we should look into soon.

**Comment by tylerl0706** [comment]
I'm going to dupe this to https://github.com/PowerShell/vscode-powershell/issues/1276 😄

**Comment by tylerl0706** [comment]
Actually this has the most info, so I'll make this the main one.

**Comment by Shane091490** [comment]
@rjmholt I have looked at the links you posted however those shortcuts don't work with powershell which is my primary language I should have been a little more clear.  I'm looking for the equivalent shortcut to "fold" as you call it, all regions in my code like in powershell ISE it's Ctrl-M.

**Comment by tylerl0706** [comment]
@Shane091490 You are correct. This is work we need to do to support this Folding Provider. We'll get to this as soon as we can!

**Comment by rkeithhill** [comment]
@Shane091490  FYI, you can already fold/unfold all regions in VSCode using <kbd>Ctrl+K, Ctrl+8</kbd> and <kbd>Ctrl+K, Ctrl+9</kbd

**Comment by glennsarti** [comment]
@tylerl0706 I've started a WIP PR for adding this.  Will work on it when I can.

**Comment by tylerl0706** [comment]
Exciting!! We really need this 🎉

**Comment by glennsarti** [comment]
@tylerl0706 No longer WIP :-)

**Comment by mpearon** [comment]
@glennsarti Just catching up here - but does this mean there is a PowerShell folding provider available now?

**Comment by rjmholt** [comment]
@mpearon The PR is close to being merged: https://github.com/PowerShell/vscode-powershell/pull/1355

**Comment by mpearon** [comment]
@glennsarti I noticed in the docs here that this feature is hidden behind a feature flag.  Is this something we can enable in its beta form by adding a string to the array?

**Comment by tylerl0706** [comment]
@mpearon. Not yet. You will need to wait for the next release or wait for #1355 to be merged and then grab a CI build.

**Comment by glennsarti** [comment]
@mpearon If you _really_ _really_ want to try it, you can get an "in-progress" build e.g. https://ci.appveyor.com/project/PowerShell/vscode-powershell-cs82i/build/1.7.0-insiders-148/artifacts

**Comment by mpearon** [comment]
@glennsarti Awesome!  Grabbing the build now. :)

**Comment by mpearon** [comment]
@glennsarti It's working beautifully!  A bit of an oddity, though - possibly expected in its current state.
HereStrings are not breaking parent or adjacent folds, but the HereStrings themselves are not folding.
![herestring](https://user-images.githubusercontent.com/7157790/41609255-fabc12c4-73af-11e8-9ab5-46e3f034dda4.gif)

**Comment by glennsarti** [comment]
@mpearon Huh... Odd..

I've added the comments to the PR.  Probably best to raise issues for PRs that are yet-to-be-merged in the PR itself.
