### ISSUE TITLE
Loading of third-part modules

### ISSUE THREAD

**Issue by tibmeister** [PowerShell/vscode-powershell#134]
Maybe not a bug but just not obvious but I work a lot with VMware's PowerCLI and as such I have to import a lot of modules and snappins but this doesn't seem to happen in VS Code.  In using the ISE or PowerGUI when they started my Powershell Profile would be loaded which takes care of all of this but in VS Code with this extension that doesn't seem to be the case so I don't have Intellisense for the PowerCLI or custom commandlets.

**Comment by rkeithhill** [comment]
Profile script loading support will be coming in the next drop of the extension.  It will be turned off by default initially but you will be able to turn it on via user preferences.  This will support the editor host/session but IIRC not the debug host i.e. you will need to make sure your script loads all the modules it needs for execution.

**Comment by tibmeister** [comment]
So is there a way to load the modules to gain Intellisense, if not now then in a future release?

**Comment by rkeithhill** [comment]
Yes but in 0.5.0.  The next release will process your profile script (including a host-specific script for VSCode) if you enable the user preference setting.  For more info on this see  https://github.com/PowerShell/PowerShellEditorServices/issues/111

**Comment by tibmeister** [comment]
I looked through the Issue 111 but not seeing on how to enable this.  I'm sure I'm just missing it.

**Comment by rkeithhill** [comment]
The setting in the **next** update (> 0.5.0) will be `powershell.enableProfileLoading`.  You'll override that and set it to true.

**Comment by tibmeister** [comment]
Ahh, got it.  I will clone that down and check it out.

**Comment by daviwil** [comment]
Hey @tibmeister, did the new profile support solve your problem with loading third-party modules?  Let me know!

**Comment by tibmeister** [comment]
Yes, after creating the Microsoft.VSCode_profile.ps1 file and copying the contents of the standard profile file into this then things began working as expected.

**Comment by daviwil** [comment]
Thanks for confirming that Jody!  I'll go ahead and close this issue.

You can run PowerShell and the PowerShell VS Code extension on Linux and OS X right now:

https://github.com/PowerShell/PowerShell
https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/using-vscode.md

The profile support will work the same way as it does on Windows, just with OS-specific profile paths.  If you open PowerShell on Linux you can use your favorite editor to edit the file in the path that's stored in the `$profile` variable.
