### ISSUE TITLE
Using Namespace leads to error Colorization 

### ISSUE THREAD

**Issue by dotChris90** [PowerShell/vscode-powershell#1343]
Hello PS Team, 

I just wanted to ask if this happens to others too. 
When Starting Visual Studio Code and writing a script and use the "using namespace XYZ" an error colorization is shown. 
But this is wrong. The using namespace works totally fine on PS 6.x and PS 5.x. 

Not sure if the Powershell Syntax highlighting is corresponding to Version 4.x or 5.x or 6.x. ^^'

**Comment by rjmholt** [comment]
Hi @dotChris90, thanks for opening an issue!

What do you mean by "error colorization" here?

I just entered `using namespace <namespace>` in a PowerShell document in VSCode and it seems to be working:
![colour](https://user-images.githubusercontent.com/7009879/40853447-f027d68a-6582-11e8-90b0-0c0a30fc0f0d.PNG)

Would be able to upload the following details (use the commands given in the Integrated Console):
* Your VSCode version (`code -v`)
* Your PowerShell EditorServices version (`$pseditor.EditorServicesVersion`)
* Your PowerShell extension version (`code --list-extensions --show-versions`)
* Your PowerShell version (`$PSVersionTable`)
* A screenshot of what you're seeing
* A description of what you're expecting to see and how it differs from what you are seeing?

Also, if the syntax highlighting is the thing that you're having issues with, you should open an issue in the PowerShell [EditorSyntax](https://github.com/powershell/editorSyntax/issues) repo.

**Comment by dotChris90** [comment]
hm .... strange ... for me it is like this. 

![image](https://user-images.githubusercontent.com/33638852/40855062-aaaec87e-65d3-11e8-8db6-389f4513113e.png)

I tried to use Powershell for some machine learning fun. 
But it says error. In english it would be something like "before all Statements in a script must be a using stemenet". 

But I will Close this issue and reopen on Editor Syntax. ;) thanks

**Comment by rjmholt** [comment]
Oh yes, you can't use a `using` statement in PowerShell after any other statements in a script. It may be that highlighting assumes correct usage here and doesn't look nice if they aren't the first statements (although my opinion would be that highlighting should try to be flexible there).

**Comment by dotChris90** [comment]
holy! :D 
This is so easy - you are totally right. But ... funny. Powershell does not care. It works fine but just is annoying. Anyway reopened in correct repo. Let's see if can be fixed. 

@rjmholt  thanks a lot for your help. wish you a good Weekend.

**Comment by rjmholt** [comment]
Hmmmm, that's a worry about PowerShell. Well I suppose we'll consider it style advice for now...

You're very welcome and same to you 😄 !

**Comment by dotChris90** [comment]
hm understood now. before I though PS was not able to using a Namespace before its scope but it is actual able to do that. Then its not error just misunderstanding. :) happy the powershell community is so fast here haha
