### ISSUE TITLE
Syntax highlighting failure

### ISSUE THREAD

**Issue by PowerCoder** [PowerShell/vscode-powershell#1347]
I have a function that uses ValidatePattern with a RegEx pattern:

    Function Provision-VM {
      [CmdletBinding()]
      Param (
        [Parameter(Mandatory)][ValidatePattern('^[a-z]+-{0,1}[a-z]+-[a-z]+([09])[0-9]$')][System.String]$Name
      ) # Param
      Begin {
        Write-Output -InputObject $Name
      } # Begin
      Process {}
      End {}
    }
    Provision-VM -Name 'abc-abc95'

The Powershell extension turns everything after the `$` orange (as if the text is between quotes). If I remove the last bracket `]` in the Regex code block or add an extra single quote `'` after the `$`, the highlighting corrects itself. Of course the code is broken at that point.

ISE shows the highlighting correctly after copy/pasting the code as-is.

Also the function will execute correctly in VS Code (even though it's all orange).

EDIT: When placing the RegEx in the code blocks (anywhere but the parameter), it displays correctly.

**Comment by rkeithhill** [comment]
Syntax highlighting is handled by a different project - https://github.com/powershell/editorsyntax  Please repost this issue to that repo where it can be addressed.
