### ISSUE TITLE
Add links/explanations for PSScriptAnalyzer diagnostics in hover-over/lightbulb

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#1348]
**Summary of the new feature**

@bergmeister [suggested](https://github.com/PowerShell/PowerShellEditorServices/pull/669#issuecomment-394454563) that PSScriptAnalyzer rules should carry an explanation of themselves in VSCode.

If we put some work into making help for each rule available at runtime in PSScriptAnalyzer, it would probably only be a little bit more work to link it up to VSCode.

> As a user I want PSScriptAnalyzer red squigglies to link to the documentation of the relevant rule (or show it in a popup) so that I can understand what PSScriptAnalyzer rule is firing and why.

**Proposed technical implementation details (optional)**

PSScriptAnalyzer will need a way to access its own help, either in pre-stored form or by URL. From there we could either embed the link or the help documentation itself into a popup/hover-over/lightbulby-thing.

See: https://github.com/PowerShell/PSScriptAnalyzer/issues/816

**Comment by rjmholt** [comment]
It would also be nice to include a "Suppress this rule" option

**Comment by stukey** [comment]
I would love to see both of these ideas implemented.

**Comment by TylerLeonhardt** [comment]
This is already implemented :)
