### ISSUE TITLE
Intellisense provides a lot of junk

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1352]
### System Details

- Operating system name and version: Windows 10 Enterprise Insider
- VS Code version: 1.24.0

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSPulsewayManager\Public> code -v
1.24.0
6a6e02cef0f2122ee1469765b704faf5d0e0d859
x64
PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSPulsewayManager\Public> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      7      0      0


PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSPulsewayManager\Public> code --list-extensions --show-versions
aaron-bond.better-comments@1.2.5
abusaidm.html-snippets@0.2.1
alefragnani.Bookmarks@0.19.1
azemoh.one-monokai@0.3.4
ban.spellright@2.5.0
donjayamanne.githistory@0.4.1
DotJoshJohnson.xml@2.2.0
eamodio.gitlens@8.3.5
emilast.LogFileHighlighter@2.4.0
emmanuelbeziat.vscode-great-icons@2.1.33
Equinusocio.vsc-material-theme@2.1.0
felixfbecker.php-debug@1.12.3
gerane.Theme-dimmed-monokai@0.0.2
gharveymn.nightswitch@1.1.0
GrapeCity.gc-excelviewer@2.0.21
hdg.live-html-previewer@0.3.0
HookyQR.beautify@1.3.0
IBM.output-colorizer@0.1.2
ikappas.phpcs@1.0.5
ionutvmi.reg@0.0.2
JerryHong.autofilename@0.1.3
johnpapa.winteriscoming@0.7.1
KnisterPeter.vscode-github@0.28.1
mechatroner.rainbow-csv@0.3.0
ms-vscode.csharp@1.15.2
ms-vscode.PowerShell@1.7.0-insiders-557
ms-vsliveshare.vsliveshare@0.3.264
ms-vsts.team@1.136.0
redhat.java@0.26.0
robertohuertasm.vscode-icons@7.23.0
Shan.code-settings-sync@2.9.2
streetsidesoftware.code-spell-checker@1.6.10
streetsidesoftware.code-spell-checker-polish@1.0.0
vangware.dark-plus-material@1.1.3
vscjava.vscode-java-debug@0.9.0
vscjava.vscode-java-pack@0.3.0
vscjava.vscode-java-test@0.6.1
vscjava.vscode-maven@0.9.0
wayou.vscode-todo-highlight@0.5.12
whizkydee.material-palenight-theme@1.8.0
xaver.clang-format@1.6.2
zhuangtongfa.Material-theme@2.13.6
Zignd.html-css-class-completion@1.11.0
PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSPulsewayManager\Public> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17672.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17672.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

Actually enabled extensions (the list above has all installed). Probably would be better for you to give a command to get only enabled extensions right?

![image](https://user-images.githubusercontent.com/15063294/41189873-c8c69de4-6bd4-11e8-811c-b0f918824482.png)

### Issue Description

Intellisense is providing a lot of junk. 

![image](https://user-images.githubusercontent.com/15063294/41189826-2b1a040a-6bd4-11e8-8741-3b7dc5c76ce8.png)

Notice how it was able to pick up the full Set-DriveSettings definition and what it proposes for filling in. 

### Attached Logs

I've attached lots of logs in different bug report. Let me know if you need more.

**Comment by rkeithhill** [comment]
Is a PowerShell Editor Services session running?  Look in the lower right of the window and it should show the version of PowerShell it is using for the session:

![image](https://user-images.githubusercontent.com/5177512/41191586-37ba787c-6baf-11e8-960b-78069fcd3d60.png)

If the session is not running you will not get any auto-completion other than what VSCode provides - which is just the tokens in your file.

**Comment by PrzemyslawKlys** [comment]
You are right. It may be that I didn't had the 5.1 running. That's because PowerShell crashes for me very often and I often kill the window. I often see PSAnalyzer being stuck for long time (where I've fixed something and it still complains for the next 2 minutes that variable has bad name or that I have half of the screen red because it didn't notice the change. 

Below is what you get until you press - 
![image](https://user-images.githubusercontent.com/15063294/41195930-bd588578-6c36-11e8-8e40-8f88b2ad0442.png)

But I guess that's expected?

**Comment by PrzemyslawKlys** [comment]
On other hand... 

![image](https://user-images.githubusercontent.com/15063294/41196479-47c2dcb8-6c41-11e8-82de-3e4421b21575.png)

and here is the definition:

![image](https://user-images.githubusercontent.com/15063294/41196483-647f7e7e-6c41-11e8-9941-e44d0f04851f.png)

**Comment by PrzemyslawKlys** [comment]
Added. Restarted

![image](https://user-images.githubusercontent.com/15063294/41199508-c0abeda2-6c93-11e8-93d9-0e9e188bc422.png)

While the definition:
![image](https://user-images.githubusercontent.com/15063294/41199520-e6ce8bde-6c93-11e8-9d40-ccbd91cb0c38.png)

Editor is running. But like I said in earlier report it only proposes junk if you are our of 'your own' parameters.

**Comment by PrzemyslawKlys** [comment]
That's what I thought after a couple of your explanation posts above. It would be nice to know Editor Services are done with it's work and now you are using VSCode junk ;) Thanks for looking into this.

**Comment by PrzemyslawKlys** [comment]
![junk-ontype](https://user-images.githubusercontent.com/15063294/41230255-636bb40a-6d7f-11e8-9260-1ba29bb50e39.gif)

I type this method... i even run F5 to make sure powershell is initilized before trying intellisense. And it seems VSCode picks the standard token that i used above '-eq' and not the one proposed.

**Comment by PrzemyslawKlys** [comment]
![junk-ontype](https://user-images.githubusercontent.com/15063294/41509517-766a3506-7255-11e8-8012-41b2835801d3.gif)

Here is another example. As you can see it's not showing any good help for `-Bold` which is [bool[]] while it shows `[UnderlineStyle[]]` properly. 

The Add-WordText is available here: https://github.com/EvotecIT/PSWriteWord/blob/master/Public/PSWordParagraph.ps1 

Maybe it's just the way I use it...

**Comment by tylerl0706** [comment]
Hey @PrzemyslawKlys,

Thanks for the gifs, they're really helpful! So I think the gif about `Get-Test -Change` is a performance bug. I think that if you had waited a bit longer, you would have gotten a response. We're working on addressing perf-related issues - we've gotten a lot of feedback on them.

Your second gif, I think, is actually a limitation of PowerShell. If you load that cmdlet `Add-WordText` into a regular console, do you get completions for the `bool[]`?

**Comment by PrzemyslawKlys** [comment]
Hey @tylerl0706 ,

You are right. I get same behaviour in ISE and powershell for bool[]. As for the 1st example it seems variable type needs to defined. If it's not defined you won't get completion in ISE either. When I changed it to bool it works straight away. 

So I guess in both cases it's kind of expected although confusing.

Przemek

**Comment by tylerl0706** [comment]
Both the ISE and VSCode PowerShell get completions via `TabExpansion2` which is built in to PowerShell.

Definitely open an issue on [PowerShell](https://github.com/powershell/powershell) voicing this so we can fix it there 😃 

If TabExpansion2 doesn't give VSCode any results, VSCode tries to "help" by supplying completions of things you've typed previously or common PowerShell things. You might be able to disable these but I'm not sure off the top of my head - I think that's really on VSCode.

**Comment by rjmholt** [comment]
@PrzemyslawKlys, to import those types properly, you might want to try the [`using` keyword](https://info.sapien.com/index.php/scripting/scripting-classes/import-powershell-classes-from-modules). You might get better intellisense then as well.

**Comment by PrzemyslawKlys** [comment]
@rjmholt I actually followed different pattern where I've use ScriptsToProcess in .psd1 where I've put all Enums in. https://github.com/EvotecIT/PSWriteWord/blob/master/PSWriteWord.psd1 That's what I found in someones other script. In the test I did, it was just a test so haven't really verified it. Assumed it would work. I will read on Using in PowerShell. I know using in C#. Eh there's a lot to learn ;-)

**Comment by PrzemyslawKlys** [comment]
@tylerl0706 but isn't that for PowerShell 6+ only? I'm still using the standard version? Or will you port it to the Windows edition as well if I report it as a bug?

**Comment by PrzemyslawKlys** [comment]
Another example... notice how I type -Autofit ... it should only provide 4 entries (the top ones). For some reason it provides a bunch. Then i goe and change -Design... notice notice how it push me to the last entries showing me junk and I have to scroll up. 

![pswriteword-tables-example3](https://user-images.githubusercontent.com/15063294/42055504-9ea105b6-7b17-11e8-8898-a07fe9d71309.gif)

**Comment by PrzemyslawKlys** [comment]
Thought I would resurrect this:

![image](https://user-images.githubusercontent.com/15063294/51906240-f9ea7d80-23c3-11e9-9297-68c31791b83b.png)

ValidateSet is simple 1 to 6. Lots of other options that shouldn't show up.

**Comment by SeeminglyScience** [comment]
@PrzemyslawKlys those are snippets, VSCode will display them regardless of what this extension says the results should be.  You can disable that with this setting:

```json
"editor.snippetSuggestions": "none",
```

**Comment by PrzemyslawKlys** [comment]
@SeeminglyScience Did I ever told you I love you? If not, here's the first time! Works as advertised. 

Now question is, should I close this one? Or do you think that earlier issue requires any work?

**Comment by SeeminglyScience** [comment]
> Now question is, should I close this one? Or do you think that earlier issue requires any work?

Looks like the other issues in the thread are related to the completions provided by the engine.  I didn't look close enough to tell if they've already been reported, but any issues for improving the engine's completion would need to be on the PowerShell repo.
