### ISSUE TITLE
Default TS Lint line length is too small (120)

### ISSUE THREAD

**Issue by glennsarti** [PowerShell/vscode-powershell#1357]
While developing code for the VSCode PowerShell extension, TS lint kept giving me line length warnings for exceeding 120 chars.  This is a pretty small value and seems like a really limiting rule with no real value.  With most modern IDEs and terminals easily exceeding 120 chars, this rule does not seem to add any value, while limiting developers abilities to write code. 

It's also exacerbated by the 4 space indentation rule.  In practice if you have a single if statement, in a function, in a class, you actually only have 108 chars to work with.

Could we please increase the line length rule to a larger number, or remove it completely.

Editor: VSCode 1.24.0
Windows 10 - 1803
vscode-powershell master is currently at commit: 790e6e2c4f0909a620740e38ef2fc5caf4572fdd

**Comment by rkeithhill** [comment]
We can consider this but I've been trying to follow the coding style that already exists in this codebase. @daviwil has been pretty consistent in his style which naturally keeps line length short.  I would encourage you to peruse around the other source code (ts) files and try to follow the coding style in those files.  In particular, for long `if` conditions see:

https://github.com/PowerShell/vscode-powershell/blob/790e6e2c4f0909a620740e38ef2fc5caf4572fdd/src/session.ts#L122-L144

**Comment by rkeithhill** [comment]
BTW, another practical reason for the line length limit is to try to make PR reviews easier.  No one wants to have to scroll around in these diffs.  :-)

![image](https://user-images.githubusercontent.com/5177512/41204766-1ca0a5e6-6ca6-11e8-9846-39634c03c436.png)

**Comment by glennsarti** [comment]
I guess it just irks me that modern IDEs are still restricted from "green screen" column widths.  Closing issue.

**Comment by rkeithhill** [comment]
Well, FWIW it irks me that GitHub refuses to make adequate use of my 1900 px wide monitor width in the diff viewer.  Check out the unused whitespace on the left/right of the diff:

![image](https://user-images.githubusercontent.com/5177512/41208957-203e15d2-6ce5-11e8-96d4-943c5435f483.png)

**Comment by glennsarti** [comment]
Yup
