### ISSUE TITLE
PowerShell preview executables no longer at /usr/[local/]bin/pwsh on *nix

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#1361]
PowerShell 6.1.0-preview.3 will install its executable as `pwsh-preview` as of the upcoming release.

We will need to work out how to handle this.

@s2p16 reported this and a workaround here: https://github.com/PowerShell/PowerShell/issues/6132#issuecomment-396079102.

Essentially, for now, the best solution is to specify a new `powerShellExePath`:
```json
{
  "powershell.powerShellExePath": "/usr/bin/pwsh-preview"
}
```

Another alternative would be to use @rkeithhill's EXE path feature:
https://github.com/PowerShell/vscode-powershell/pull/1270

But we should also fix this so that it works out of the box. Since preview and ordinary releases are now allowed side-by-side, we should figure out which we prefer if both are present.

**Comment by s2p16** [comment]
I will suggest powershell extensions in visual studio code could allow you to choose which one to use in a project basis, saving the setting into .vscode or similar (something similar that is already doing with the typescript engine). I am saying that ps extensions on code should support both executables, enable to choose one per project in case both are detected.
I will keep them separate (powershell or pwsh, and pwsh-preview) executables in order to allow the user know which one to use explicitly at OS level.

**Comment by rjmholt** [comment]
@s2p16 we already support a feature like that with https://github.com/PowerShell/vscode-powershell/pull/1270.

The main issue here is that the default PowerShell executable path is going to need changing with newer PowerShell releases.

For that, I think a change will need to be made here:
https://github.com/PowerShell/vscode-powershell/blob/9bf58a7ab21275653ee1f9ff7571060fc094e0c7/src/platform.ts#L50-L83

**Comment by s2p16** [comment]
Thanks for the information!
I see... 
for an easy workaround the function getDefaultPowerShellPath may return an enumerable of {
                versionName: [version_name],
                exePath: [exePath],
} and the function getAvailablePowerShellExes must add all them instead of just resolving the path as it's doing now.

**Comment by s2p16** [comment]
Yes, you're right, 
I was trying to enable user interaction at session start when no defaults is set, allowing to choose option 1 pwsh and 2 -preview, but this requires some signature change and a bit of more lines in other source files. It may not follow the easy thing xD
But it will prevent the user experimenting the same problem I was running on visual studio code whit vs-code-extensions while the stable version is not fixed.
