### ISSUE TITLE
Detect accidentally use of automatic variables as local variables

### ISSUE THREAD

**Issue by madmidi** [PowerShell/vscode-powershell#1363]
I expect an IDE to detect bugs like that:
```
function Demo
{
    Param (
    [string] $input
    )
}
```
I've declared $input as local variable/function parameter with no warning from the IDE.
And needed 30 minutes to find the problem. :-(
A typical PowerShell/ScriptLanguage issue, which would never happen in real programming languages.
An IDE/Extension for script languages therefore has to be much more clever. (than yours)

**Comment by rkeithhill** [comment]
This sort of linting functionality is provided by the PSScriptAnalyzer.  Please open this issue on that repo - https://github.com/PowerShell/ScriptAnalyzer.
