### ISSUE TITLE
Include reference to command palette logs command in README.md

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#1364]
There is a section of the README devoted to reporting errors and inspecting the logs.

We should include a reference to using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> to view the logs in that section.

**Comment by tylerl0706** [comment]
I feel like it took you longer to write this issue then just submitting a PR 😝

**Comment by tylerl0706** [comment]
We should actually include the "Upload Bug Report to GitHub" steps
