### ISSUE TITLE
Extension searches for second user snippet file

### ISSUE THREAD

**Issue by madmidi** [PowerShell/vscode-powershell#1365]
In the debug output for the extension I've found:

` [renderer1] [error] Error: ENOENT: no such file or directory, open '%USERPROFILE%\.vscode\extensions\ms-vscode.powershell-1.7.0\snippets\PowerShell.json' `

But my user snippet file is located, found and used under:
`"%USERPROFILE%\AppData\Roaming\Code\User\snippets\powershell.json"`

**So why you try to load another one ?**

_(I've replace my path with %USERPROFILE%)_

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.16299 |
| VSCode | 1.24.0|
| PowerShell Extension Version | 1.7.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.16299.431|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.16299.431|
|BuildVersion|10.0.16299.431|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|change-case|wmaurer|1.0.0|
|csharp|ms-vscode|1.15.2|
|local-history|xyz|1.6.2|
|PowerShell|ms-vscode|1.7.0|
|svn-scm|johnstoncode|1.29.2|
|vs-keybindings|ms-vscode|0.2.0|
|vscode-language-pack-de|MS-CEINTL|1.24.3|;

</details>

**Comment by rkeithhill** [comment]
If you have installed the PowerShell extension (v 1.7.0) then this path is supposed to exist:
```
'%USERPROFILE%\.vscode\extensions\ms-vscode.powershell-1.7.0\snippets\PowerShell.json'
```
These are the PowerShell snippets that are provided by this extension.  The extensions at the path `%USERPROFILE%\AppData\Roaming\Code\User\snippets\powershell.json` are user-specific snippets that combine with the VSCode base-level snippets and the PowerShell extension snippets.

**Comment by madmidi** [comment]
my fault, I've accidentially deleted the file since this folder is empty and therefore the debug warning, thx

**Comment by rkeithhill** [comment]
No problem.  Glad we got it sorted out.
