### ISSUE TITLE
Question: Adding Custom Functions and scripts to Intellisense

### ISSUE THREAD

**Issue by keposet** [PowerShell/vscode-powershell#1372]
Is there a way i can add functions and scripts i've written into intellisense? 
i've added a few commands into my profile, like creating log files, connecting to external services etc 

I'd like to call those commands within other scripts. is it possible to load their signatures/expressions into the intellisense engine?

**Comment by tylerl0706** [comment]
Yes! All you need to do is highlight them and hit `F8`. That will load them into the session.

**Comment by tylerl0706** [comment]
Let me know if you have any trouble. I'm going to close this for now :)

**Comment by keposet** [comment]
No issues at all, except for my general lack of understanding of powershell. But that is an issue which is far out of scope for this repo lol
