### ISSUE TITLE
The time zone with ID  was not recognized on the server. 

### ISSUE THREAD

**Issue by Madest25** [PowerShell/vscode-powershell#1380]
PS D:\Downloads> d:\Downloads\CreateBCSandbox.ps1
Solicitud de credenciales para Windows PowerShell.
Using Windows Authentication. Please enter your Windows credentials.
Password for user Esteban: *************
Pulling docker Image microsoft/bcsandbox:12.0.21405.22470-es
12.0.21405.22470-es: Pulling from microsoft/bcsandbox
Digest: sha256:7ed84de3ae51551dd05d97d736853b5c11e86916188cf6344bd8e1b30083daeb
Status: Image is up to date for microsoft/bcsandbox:12.0.21405.22470-es
Creating Nav container MyDynamic365
Using image microsoft/bcsandbox:12.0.21405.22470-es
NAV Version: 12.0.21405.22470-ES
Generic Tag: 0.0.5.6
Removing container MyDynamic365
Removing MyDynamic365 from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\MyDynamic365
Creating container MyDynamic365 from image microsoft/bcsandbox:12.0.21405.22470-es
Waiting for container MyDynamic365 to be ready
Initializing...
Starting Container
Hostname is MyDynamic365
PublicDnsName is MyDynamic365
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user Esteban
Setting SA Password and enabling SA
Creating SUPER user
Assign Premium plan for MYDYNAMIC365\ESTEBAN
Container IP Address: 172.31.178.16
Container Hostname  : MyDynamic365
Container Dns Name  : MyDynamic365
Web Client          : http://MyDynamic365/NAV/
Dev. Server         : http://MyDynamic365
Dev. ServerInstance : NAV

Files:
http://MyDynamic365:8080/al-0.15.18771.vsix

You are running a container which is 77 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 92 seconds
Ready for connections!
Reading CustomSettings.config from MyDynamic365
Creating Desktop Shortcuts for MyDynamic365
Nav container MyDynamic365 successfully created
Downloading C:\Users\Esteban\AppData\Local\Temp\CreateTestUsers.fob
Copy C:\Users\Esteban\AppData\Local\Temp\CreateTestUsers.fob to container MyDynamic365 (c:\run\CreateTestUsers.fob)
Importing Objects from c:\run\CreateTestUsers.fob (container path)
Objects successfully imported

The time zone with ID 'Hora estándar romance' was not recognized on the server. Update your computer's time zone definitions.
En C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.9.6\ObjectHandling\Invoke-NavContainerCodeunit.ps1: 41 Carácter: 5
+     Invoke-Command -Session $session -ScriptBlock { Param($tenant, $C ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Invoke-NAVCodeunit], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/default,Microsoft.Dynamics.Nav.Management.Cmdlets.InvokeNavCodeunit

**Comment by rjmholt** [comment]
Hi @Madest25, thanks for opening an issue!

It actually looks like this might be an issue in the PowerShell module you're using. Try opening an issue here: https://github.com/Microsoft/navcontainerhelper/issues.

Going to close for now since it doesn't look like the VSCode extension is involved. Can reopen later if need be.

**Comment by Madest25** [comment]
Thanks
