### ISSUE TITLE
Pester test failure NOT in the Problems View.

### ISSUE THREAD

**Issue by successhawk** [PowerShell/vscode-powershell#1381]
## Issue Description ##

I am experiencing a problem with Pester test failures being captured in the Problems view.  I opened the examples project using:
![image](https://user-images.githubusercontent.com/3745327/41797657-ee7f9c48-7638-11e8-8542-4e2ea6468fe6.png)

I ran the Test task and all unit tests were successful.  I modified a single test so that it would fail, because I wanted to see the failure in the Problems view.  the test fails in the terminal view, but it does not display in the Problems view.  I made more fail and they showed in the Problems view, but the original did not.

Here is the 1 failing test.
![image](https://user-images.githubusercontent.com/3745327/41798388-825068ec-763b-11e8-8f21-d72fbea704f4.png)
It is not in the Problems tab.
![image](https://user-images.githubusercontent.com/3745327/41798415-99afad72-763b-11e8-84e7-f6a1627321e2.png)

Code snippet that I modified to make failure (removed 'A' from expected READMENew.md).
```
    It 'Processes non-wildcard absolute path to non-existing file via -Path param' {
        New-File -Path $WorkspaceRoot\ReadmeNew.md | Should Be "$WorkspaceRoot\REDMENew.md"
    }

```

I also tried modifying the Test task as reported in another issue as a workaround.
```
            "label": "Test",
            "type": "shell",
            "command": "Write-Host 'Invoking Pester...'; $ProgressPreference = 'SilentlyContinue'; Invoke-Pester -PesterOption @{IncludeVSCodeMarker=$true};",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "problemMatcher": [
                "$pester"
            ]
```

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.15063 |
| VSCode | 1.24.1|
| PowerShell Extension Version | 1.7.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.15063.1088|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.15063.1088|
|BuildVersion|10.0.15063.1088|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azurecli|ms-vscode|0.4.2|
|bracket-pair-colorizer|CoenraadS|1.0.58|
|gitlens|eamodio|8.4.1|
|markdown-all-in-one|yzhang|1.4.0|
|PowerShell|ms-vscode|1.7.0|
|team|ms-vsts|1.136.0|
|vscode-eclipse-keybindings|alphabotsec|0.9.7|
|vscode-markdownlint|DavidAnson|0.18.0|
|vscode-terminals|fabiospampinato|1.11.7|;

</details>

**Comment by rkeithhill** [comment]
I think we already have a fix for this in #1362.  The regex was looking for time in `ms` and not `s` (seconds).  If you want, you can apply this fix locally until we ship the next update.  Just open your `~\.vscode\extensions\ms-vscode.powershell-1.7.0\package.json` file and edit line 179 to this:
```
"regexp": "^\\s*(?:\\[-\\]\\s+)(.*?)(?:\\s+\\d+\\.?\\d*\\s*m?s)\\s*$",
```
Save and restart VSCode and try again. That should fix it.

**Comment by successhawk** [comment]
Yes.  That fixes the issue. thanks

**Comment by tylerl0706** [comment]
We'll be getting a new release out soon so you can get this fix there's just some (hopefully) one time processes that need to be dealt with this time.
