### ISSUE TITLE
Align groups of assignments (=)

### ISSUE THREAD

**Issue by hanpq** [PowerShell/vscode-powershell#1385]
I would love to see an option to allow alignment of assignmentgroups. Its easiest to show what I mean with an example. (Github wouldn't allow me to format the code manually and trimmed the whitespaces automatically so I had to attach a printscreen)

![bild](https://user-images.githubusercontent.com/33247576/41896787-d51c55f8-7925-11e8-8036-5845b3c5ea0d.png)

So that '=' are aligned in columns within a group of assignments. A group could be interpreted as delimitered with a blank line. 

I can see that not everyone would like this so this feature should probably be activated by an powershell.codeformating -setting.

**Comment by rjmholt** [comment]
Formatting is actually provided by [PSScriptAnalyzer's `Invoke-Formatter` command](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Engine/Commands/InvokeFormatterCommand.cs). We hook into it in EditorServices [here](https://github.com/PowerShell/PowerShellEditorServices/blob/b57b44fe66d9ede9a84d8415b3a0345e1ed4a80d/src/PowerShellEditorServices/Analysis/AnalysisService.cs#L295-L325).

I think the best thing to do is to [open a new issue in PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer/issues/new?template=Feature_request.md). Then we'll have a little bit of integration work to do but it should be pretty straightforward.

**Comment by hanpq** [comment]
Ah, I see! I've made another feature request in PSScriptAnalyzer here: [https://github.com/PowerShell/PSScriptAnalyzer/issues/1029](url)
<p>
Should I leave this feature request open since you said it might need integration work later on if the feature is implemented in PSScriptAnalyzer?
<p>
Thanks!

**Comment by rjmholt** [comment]
Awesome! Yeah I think we should leave the issue open here both to track the work to integrate and also for anyone else who is looking for this feature.

**Comment by TylerLeonhardt** [comment]
Let's actually close this issue here for now until it's implemented in PSSA since there's (currently) no action item on the extension.
