### ISSUE TITLE
Clicking on an element of Outline does not work

### ISSUE THREAD

**Issue by AlexBillon07** [PowerShell/vscode-powershell#1386]
## Issue Description ##

I am experiencing a problem with the Outline feature in the Explorer view. When I click on an element of the Outline, the active editor closes or nothing happens.

![ms-vscode powershell-1 7 0-outline-close-editor](https://user-images.githubusercontent.com/33461310/41906001-0c3d9044-793d-11e8-8eb9-39b652bbf3d2.gif)

## Attached Logs ##

[1530008985-8037a55e-b901-4ff8-8ef1-6281b0ce2cb61530008980459.zip](https://github.com/PowerShell/vscode-powershell/files/2136762/1530008985-8037a55e-b901-4ff8-8ef1-6281b0ce2cb61530008980459.zip)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 6.1.7601 |
| VSCode | 1.24.1|
| PowerShell Extension Version | 1.7.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.14409.1012|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.14409.1012|
|BuildVersion|10.0.14409.1012|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.7.0|;

</details>

**Comment by rkeithhill** [comment]
That "Outline" view is not a feature of the PowerShell extension nor is it a native feature of VSCode.  I believe you have installed an extension that is providing that view.  Perhaps https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline ?  I suggest you file an issue on their repo.

**Comment by AlexBillon07** [comment]
Outline view has been shipped in version 1.24 of VSCode
https://code.visualstudio.com/updates/v1_24#_outline-view


Only the Powershell extension were enabled (see original post created by the "Powershell: Upload Bug Report to Github" command)

**Comment by rkeithhill** [comment]
Thanks, that's good to know but it is a "Preview version" of the feature.  We can add it to the backlog but it might be a while before it gets addressed.  We do take PRs although this feature would probably require work in the PowerShellEditorServices repo as well.

**Comment by AlexBillon07** [comment]
Should I submit the issue to PowerShell/PowerShellEditorServices ?

**Comment by rkeithhill** [comment]
Until we dig into this issue to figure out what is going wrong with the new Outline feature, having the issue submitted here is fine.  In fact, we often get issues submitted here that are really PSES issues just because the "extension" is what folks see.

**Comment by tylerl0706** [comment]
Yeah I agree. Lets wait for Outline to mature as a feature.

**Comment by AlexBillon07** [comment]
Hello,

The Outline feature is now out of preview : https://code.visualstudio.com/updates/v1_25#_outline-view

I don't have the bug anymore.
