### ISSUE TITLE
Find files in folder by typing first letters

### ISSUE THREAD

**Issue by fsackur** [PowerShell/vscode-powershell#1387]
When a folder is selected, allow keystrokes to select the file (similar to Windows File Explorer)

Scenario: I am in the folder view and looking at files called:
* a
* b
* bat
* c

I hit the 'b' key. I would like the file 'b' to be selected.
I hit the 'b' key then the 'a' key in quick succession. I would like the 'bat' file to be selected.

After selecting a file like this, I would like the file to display temporarily (with name in italics) in the editor pane.
I would like hitting 'Enter' to open the file permanently.

**Comment by rkeithhill** [comment]
This behavior is not specific to nor implemented by the PowerShell "extension" for VSCode.  You should make this suggestion on the VSCode repo - https://github.com/Microsoft/vscode/issues
