### ISSUE TITLE
PowerShell extension should supply initialConfiguration for launch.json

### ISSUE THREAD

**Issue by mattmcnabb** [PowerShell/vscode-powershell#14]
I installed VS Code from Chocolatey and updated with the Powershell language extension then restarted Code. when I try to enter debugging I am presented with this message:
![vslaunch](https://cloud.githubusercontent.com/assets/6998507/11272307/df1e7fa0-8e99-11e5-954c-711f31a3ae8b.png)

Shouldn't this be included with the Powershell extension? If not, how should this be configured? Thanks!

**Comment by ThePSAdmin** [comment]
There is an example powershell folder in the respository, and it looks like this:

```json
{
	"version": "0.1.0",
	"configurations": [
		{
			"name": "PowerShell",
			"type": "PowerShell",
			"program": "DebugTest.ps1"
		}
	]
}
```

But I'm still don't get it to work either, I get a green squiggle under ```"type": "PowerShell"``` and it says the only valid value is node.

**Comment by daviwil** [comment]
Thanks @ThePSAdmin!  Yes, there isn't a default configuration provided.  This is a little confusing, I'll see if I can get something in there by default.

**Comment by mattmcnabb** [comment]
Thanks PSAdmin!

**Comment by kavaliro** [comment]
If I go into a directory and launch the debugger, and there's not a launch.config, I would expect a prompt to create one (this exists) that is pre-populated with the values needed to run the script I am currently viewing (this does not.)

And thanks guys; this plug-in is great stuff!

**Comment by daviwil** [comment]
Hey James, this will be added in a future release.  The VS Code team told me what I need to do to make it happen.

**Comment by artisticcheese** [comment]
Is this issue fixed? I'm still seeing the same problem with latest VSCode and Powershell Extension.
VSCode 0.10.10

**Comment by daviwil** [comment]
Yep, it's been fixed for a long time.  Can you tell me the sequence of steps you take and what you observe?

**Comment by artisticcheese** [comment]
Here is problems steps recorder what is happening

[a.zip](https://github.com/PowerShell/vscode-powershell/files/163492/a.zip)

**Comment by daviwil** [comment]
Thanks!  That was helpful.  I'm pretty sure Visual Studio Code does not allow you to debug a single opened file.  You'll need to open the folder that this file is contained in using `File -> Open Folder` before the debugger will be able to generate a launch.json for your project.

**Comment by artisticcheese** [comment]
Not sure what I'm doing wrong but the same thing happens when I open folder.
[b.zip](https://github.com/PowerShell/vscode-powershell/files/163499/b.zip)

**Comment by daviwil** [comment]
Now you've got a launch.json file, click the green debug 'start' button again :)  VS Code has to generate the default launch.json first as a one-time step when one doesn't exist.  Now that you have one, your script will be able to run.

**Comment by artisticcheese** [comment]
Thanks, that did it
