### ISSUE TITLE
unpaired parenthesis inside comment inside quoted string subexpression yields errors

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/vscode-powershell#1401]
Issue Type: <b>Bug</b>

I run in to an example of code, where the unexpected behavior occurs, and it occurs in both VS Code and PowerShell ISE, and seems to occur on the actual PowerShell console too, which probably means PSReadLine is affected as well.   All the editors color the sample as expected, but they all flag errors.  The colorizers are correct, but the interpreters are not.

This is the good image, and this code works.
![image](https://user-images.githubusercontent.com/26179051/42194375-558771f6-7e39-11e8-9f62-e89ad165af48.png)

This fails, note the missing parenthesis in the comment at the end and the substring expression.
![image](https://user-images.githubusercontent.com/26179051/42194429-99eae40e-7e39-11e8-910d-e8a4b418e277.png)

Here is the code as text:
`            $datablock.value = "``r``n        $(((([System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes(
                        # convert from Base64String
                        ((([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($datablock.value)
                                        # split the lines (terminated with CRLF)
                                    ) -split "``r``n"
                                    # remove empty records
                                ) -notmatch "^S3..........(FF)+..$"
                                # combine back to one large string to return back to Base64String
                            ) -join "``r``n"
                        )
                    # take the new Base64String and break it into 80 character lines (keeping only the 'delimeters') and then rejoin them in the assumed original format
                    ))) -split '(.{1,80})') -notmatch '^$') -join "``r``n        ")``r``n"
`
I realize there may be more at fault here than just the VS Code PowerShell extension, but I really feel this is a technical error.  A missing parenthesis in a comment should not have any affect on the interpreter.

Extension version: 1.7.0
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.91GB (9.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by tylerl0706** [comment]
Interesting... Does the code without the parenthesis actually execute properly in a PowerShell terminal? 

If it doesn't, you should definitely open this on PowerShell itself... 
https://github.com/PowerShell/PowerShell
If it does execute properly, this would likely be a PSScriptAnalyzer issue...
https://github.com/PowerShell/PSScriptAnalyzer

**Comment by msftrncs** [comment]
I've put a link to this issue on the UserVoice site, under issue:
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11297838-parsing-error-on

Looks like they have known about it for a bit.   Just shows how something so powerful can still have a little weakness.

**Comment by tylerl0706** [comment]
Software, in a nutshell 😅

**Comment by tylerl0706** [comment]
Thanks for doing that! I'm going to close this since it's an issue with actual PowerShell. Let me know if you see otherwise
