### ISSUE TITLE
Code provider folding is not folding here strings

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#1417]
### System Details

- Operating system name and version: Windows 10 1803
- VS Code version: 1.25.0 32-bit
- PowerShell extension version: daily build with PR #1416 pulled down
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.17134.137
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.137
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Code folding via the folding provider seems to be working for everything except here strings:

![image](https://user-images.githubusercontent.com/5177512/42487356-dcc74a4a-83bd-11e8-95d3-57fda2a13bc7.png)

FWIW the npm tests fail on my dev machine:

![image](https://user-images.githubusercontent.com/5177512/42487403-24205a08-83be-11e8-9420-69f2e66ed00c.png)

### Attached Logs

```
7/9/2018 9:13:36 PM [NORMAL] - Visual Studio Code v1.25.0 32-bit
7/9/2018 9:13:36 PM [NORMAL] - PowerShell Extension v1.7.0
7/9/2018 9:13:36 PM [NORMAL] - Operating System: Windows 64-bit
7/9/2018 9:13:36 PM [DIAGNOSTIC] - Succesfully required c:\Program Files (x86)\Microsoft VS Code\resources\app/node_modules.asar/vscode-textmate
7/9/2018 9:13:36 PM [DIAGNOSTIC] - Loaded the vscode-textmate module
7/9/2018 9:13:36 PM [DIAGNOSTIC] - Created the textmate Registry
7/9/2018 9:13:36 PM [DIAGNOSTIC] - PowerShell grammar file specified as c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\powershell\syntaxes\powershell.tmLanguage.json
7/9/2018 9:13:36 PM [NORMAL] - Language server starting --
7/9/2018 9:13:36 PM [NORMAL] -     exe: C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe
7/9/2018 9:13:36 PM [NORMAL] -     args: C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\module\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.7.0'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\module'-EnableConsoleRepl -LanguageServicePipeName LanguageService_55b445f8a3da0175246c.pipe -DebugServicePipeName DebugService_55b445f8a3da0175246c.pipe -LogLevel 'Diagnostic' -LogPath 'C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\logs\1531192416-someValue.sessionId\EditorServices.log' -SessionDetailsPath 'C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\sessions\PSES-VSCode-21924-436123' -FeatureFlags @()
7/9/2018 9:13:36 PM [NORMAL] - Syntax Folding Provider registered
7/9/2018 9:13:37 PM [NORMAL] - powershell.exe started, pid: 29196
7/9/2018 9:13:41 PM [NORMAL] - Language server started.
7/9/2018 9:13:41 PM [NORMAL] - {"status":"started","debugServiceTransport":"NamedPipe","languageServiceTransport":"NamedPipe","debugServicePipeName":"DebugService_55b445f8a3da0175246c.pipe","languageServicePipeName":"LanguageService_55b445f8a3da0175246c.pipe"}
7/9/2018 9:13:41 PM [NORMAL] - Connecting to language service on pipe LanguageService_55b445f8a3da0175246c.pipe...
7/9/2018 9:13:41 PM [NORMAL] - Language service connected.
```

**Comment by rkeithhill** [comment]
Ping @glennsarti

**Comment by rkeithhill** [comment]
Could it be something to do with me running 32-bit VSCode?  That'd be odd but not unheard of.  Are you looking at this file via the extension debug host?

**Comment by glennsarti** [comment]
yes and I'm running 32bit too.

**Comment by glennsarti** [comment]
What's the green squiggle saying underneath your `$I`

**Comment by rkeithhill** [comment]
That the variable `$I` is never used.

**Comment by glennsarti** [comment]
So the test failure is on that particular piece of text.   The plot thickens...

**Comment by glennsarti** [comment]
Oh that's super weird.  The tokenizer didn't see the heredoc.

**Comment by rjmholt** [comment]
Yeah I wondered if it was a grammar problem...

**Comment by rjmholt** [comment]
In that case, we should open an issue in EditorSyntax and mark as Resolution-External

**Comment by glennsarti** [comment]
Nope...not so fast.  I can repro the test failure, but not the actual failure.

**Comment by glennsarti** [comment]
Currently thinking this is a test fixture issue and it's loading the wrong powershell grammar file...

**Comment by rkeithhill** [comment]
I noticed when the VSCode instance pops up during the test, it is v1.24.1.  Even though I have v1.25 installed.

**Comment by glennsarti** [comment]
@rkeithhill Can you please try changing the file from CRLF to LF to see if it makes a difference

**Comment by rkeithhill** [comment]
You may have Git configured to use LF but the repo configures itself to use `auto` via `* text=auto` in `.gitattributes`.  Unless that is, you're on Linux/macOS, in which case `auto` would select LF.

**Comment by glennsarti** [comment]
@rkeithhill Ok so, it looks like I'm using the `tokenizeLine` method wrong.  I should really be feeding it a line by line, instead of jamming the whole file in there.  e.g.

1. It first splits the document into a line array
https://github.com/Microsoft/vscode/blob/d2b6bbb46fbdf535e2c96b3e00ac56ac1d427a69/src/vs/workbench/parts/themes/test/electron-browser/themes.test.contribution.ts#L227

2. And then for each line it calls tokenize
https://github.com/Microsoft/vscode/blob/d2b6bbb46fbdf535e2c96b3e00ac56ac1d427a69/src/vs/workbench/parts/themes/test/electron-browser/themes.test.contribution.ts#L131-L162

This would mean the CRLF / LF problem would disappear.

**Comment by glennsarti** [comment]
Started a WIP PR, with tests and janky workaround.
