### ISSUE TITLE
Update ScriptAnalyzer

### ISSUE THREAD

**Issue by ITCTOM** [PowerShell/vscode-powershell#1419]
Hi,
is it possible to update the Script Analyzer Plugin in PowerShell VSC Extension?

regards

  thomas

* Slack Community Chat: https://powershell.slack.com (you can sign-up at http://slack.poshcode.org/ for an invite)
* Gitter Chat: https://gitter.im/PowerShell/vscode-powershell

**Comment by rkeithhill** [comment]
With the 1.8.0 release (released today), the extension should the latest version of the ScriptAnalyzer it finds on your machine.  Although this version shipped with `1.17.1`.

**Comment by ITCTOM** [comment]
Thanks for the response.

I´ve installed the new version today it´s great.

 

Is there a documentation out there how to update the Script Analyser by myself?

 

Kind regards

 

Thomas Paetzold

**Comment by rkeithhill** [comment]
For install instructions, see https://www.powershellgallery.com/packages/PSScriptAnalyzer/1.17.1

**Comment by rkeithhill** [comment]
The PowerShell extension (v1.8.0) ships PSSA 1.17.1 in the folder `~\.vscode\extensions\ms-vscode.powershell-1.8.0\modules\PSScriptAnalyzer`.  You should not modify that version.  However if a newer release of PSSA comes out, you can install it using the instructions I pointed you to.  The extension (>= 1.8.0) will search for the latest version of PSSA on your system and load that.  If you don't have PSSA separately installed, it will use the version in the extension's install dir.

**Comment by rjmholt** [comment]
As @rkeithhill says, installing a newer version of PSSA anywhere on your module path should give you that version in the extension
