### ISSUE TITLE
Request: Support #region collapsing

### ISSUE THREAD

**Issue by harbars** [PowerShell/vscode-powershell#142]
not sure if this is something that the extension can do or if it needs implemented in VSCode itself but it would be nice if the code collapsing feature of the editor worked with #region commonly used with ISE.

**Comment by daviwil** [comment]
Yep, this is something the VS Code team is working on.  See here for more information: https://github.com/PowerShell/vscode-powershell/issues/129

**Comment by harbars** [comment]
great - thanks!
