### ISSUE TITLE
The language service could not be started

### ISSUE THREAD

**Issue by abbgrade** [PowerShell/vscode-powershell#1423]
## Issue Description ##

After startup of VSCode i get the error message "The language service could not be started".

## Attached Logs ##

[1531298684-cba3b6d9-9142-4ef9-a52a-21986de530eb1531298680271.zip](https://github.com/PowerShell/vscode-powershell/files/2183723/1531298684-cba3b6d9-9142-4ef9-a52a-21986de530eb1531298680271.zip)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 6.1.7601 |
| VSCode | 1.25.0|
| PowerShell Extension Version | 1.8.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|4.0|
|WSManStackVersion|3.0|
|SerializationVersion|1.1.0.1|
|CLRVersion|4.0.30319.42000|
|BuildVersion|6.3.9600.18728|
|PSCompatibleVersions|1.0 2.0 3.0 4.0|
|PSRemotingProtocolVersion|2.2|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.15.2|
|live-html-previewer|hdg|0.3.0|
|mssql|ms-mssql|1.4.0|
|PowerShell|ms-vscode|1.8.0|
|team|ms-vsts|1.136.0|
|xml|DotJoshJohnson|2.3.1|;

</det

**Comment by Diederikjh** [comment]
Similar problems logged at #1421 and #1422. Workaround in last issue got terminal up, but debugger stil crashes sometimes.

**Comment by rjmholt** [comment]
Hi @abbgrade, I've just pushed a patch. Would you be able to upgrade your installed extension and report back on whether the crash still occurs?

**Comment by rjmholt** [comment]
Going to close this for now, since it looks like we resolved the other two issues. We can reopen if it looks like this was a different issue.

**Comment by abbgrade** [comment]
Hello,

Version 1.8.1 does not crash.

Thanks
