### ISSUE TITLE
The term 'New-Guid' is not recognized as the name of a cmdlet, function

### ISSUE THREAD

**Issue by nsleigh** [PowerShell/vscode-powershell#1424]
OS: Windows 7
PowerShell version: 4.0
$pseditor.EditorServicesVersion: 1.8

On upgrading version 1.8 I am seeing this error: PowerShell Editor Services The term 'New-Guid' is not recognized as the name of a cmdlet, function.

It looks like Start-EditorServices.ps1 is making use of the New-Guid function that was introduced in PS v5.

Workaround: edit Start-EditorServices.ps1 line 175 and change it to: 
    $PipeName = "PSES_$([guid]::newguid())"

**Comment by andrewducker** [comment]
Cheers for the workaround, same issue here.

**Comment by andrewducker** [comment]
Although even when I do that, if I then try to save a file, it displays "Formatting PowerShell document..." at the bottom of the screen, and then "The PowerShell session has terminated due to an error, would you like to restart it?"

(This happens every time.)

**Comment by rkeithhill** [comment]
Can you zip and attach the log files?  For instructions, see https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

**Comment by andrewducker** [comment]
[SaveCrash.zip](https://github.com/PowerShell/vscode-powershell/files/2185079/SaveCrash.zip)

**Comment by andrewducker** [comment]
This is probably a different bug to the one this issue was created for.  That one doesn't actually start the editor services up, because of the failure to create a named pipe, because new-guid doesn't exist.

Should I create a separate issue for this?

**Comment by rkeithhill** [comment]
Can you submit this issue to https://github.com/powershell/powershelleditorservices  Title something like PSES crash in `HandleDocumentRangeFormattingRequest` and attach the zip to that issue.  Thanks!

**Comment by rkeithhill** [comment]
As a work-around, try disabling code analysis with the user setting:
```
 "powershell.scriptAnalysis.enable": false,
```
I think that should disable the formatting but unfortunately it also disables analysis.

**Comment by rjmholt** [comment]
I've opened a PR for the `New-Guid` issue:
https://github.com/PowerShell/PowerShellEditorServices/pull/699

**Comment by andrewducker** [comment]
Done:
https://github.com/PowerShell/PowerShellEditorServices/issues/700

**Comment by rkeithhill** [comment]
@andrewducker Thanks!!  Closing the original issue in favor of https://github.com/PowerShell/PowerShellEditorServices/pull/699
