### ISSUE TITLE
PowerShell Extension 1.8.1 breaks editor folding on region tags

### ISSUE THREAD

**Issue by msm-fc** [PowerShell/vscode-powershell#1428]
### System Details

- Operating system name and version:  Windows 10.1803.17134.137
- VSCode Version: 1.25.0
- PowerShell extension version: 1.8.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.17134.137
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.137
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
1.25.0
0f080e5267e829de46638128001aeb7ca2d6d50e
x64

Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1      0
cdsama.tortoise-svn-for-vscode@0.1.1
dakara.transformer@1.6.0
emmanuelbeziat.vscode-great-icons@2.1.36
GrapeCity.gc-excelviewer@2.1.24
ilich8086.coldfusion@1.0.1
mechatroner.rainbow-csv@0.4.2
ms-vscode.csharp@1.15.2
ms-vscode.PowerShell@1.8.1
PKief.material-icon-theme@3.5.1
schneiderpat.aspnet-helper@0.6.4
tuxtina.json2yaml@0.2.0

Key   : PSVersion
Value : 5.1.17134.137
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.17134.137
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion

### Issue Description

Searched for existing issues, didn't find anything.
Others in the chat room also confirmed
Reproduced with latest Insiders Build of vscode.

Steps to Reproduce:

1.  Install vscode
2. Open a powershell script file containing working region and endregion tags
3. Observe that the editor folding works
4.  Install Powershell Extension (ms-vscode.powershell) version 1.8.1
5. Relaunch vscode
6. Observe that editor folding is not working

**Comment by rjmholt** [comment]
Thanks for opening an issue @msm-fc!

We think 1.8.0 broke this as well.

VSCode seems to implement [its own `#region` folding](https://code.visualstudio.com/updates/v1_17#_folding-regions), so maybe this got overridden?

/cc @glennsarti @rkeithhill

**Comment by glennsarti** [comment]
The new syntax folder is all or nothing, i.e. when active, only the folding ranges supplied willbe used.  None of the vscode default ones will be used.

The vscode region folding is defined here;
https://github.com/Microsoft/vscode/blob/master/extensions/powershell/language-configuration.json#L26-L31

The syntax folder uses this;
https://github.com/PowerShell/vscode-powershell/blob/master/src/features/Folding.ts#L425-L426

One difference I see is casing.

However without the source document debugging/reproing this issue is almost impossible.

@msm-fc 
1. Can you please provide the document you used when you saw the issue
2. Preferably adds some screenshots with the syntax-folding enabled and disabled (requires a VSCode reload to take effect)

VSCode setting;
`"powershell.codeFolding.enable": "false",`

**Comment by rjmholt** [comment]
Thanks @glennsarti!

**Comment by stukey** [comment]
I am experiencing this issue too.

Syntax folding enabled (powershell.codeFolding.enable = true):

![9d4bfac6-4166-4e1a-a52e-dc721fe22e5a](https://user-images.githubusercontent.com/12292623/42626982-98352f8e-85c3-11e8-8afb-dbf2f30cc99e.jpeg)

Syntax folder disabled (powershell.codeFolding.enable = false):

![6f0d0f44-7ec9-4ffd-a2b1-f42fbec9f287](https://user-images.githubusercontent.com/12292623/42627043-c455db2c-85c3-11e8-9231-8e622254a3a0.jpeg)

I noticed the problem with version 1.8.0 of the PowerShell extension too. Also version 1.8.0 or 1.8.1 appears to have made Region Folding case-sensitive again. So even with ‘powershell.codeFolding.enable’ set to false, #Region #EndRegion sections are not folded but #region #endregion sections are folded. Prior to 1.8.0 I noticed that Region Folding became non case-sensitive (which was better).

**Comment by glennsarti** [comment]
@stukey Thanks.  That makes it make easier to track down what's going on.  I've repro'd locally and working on a fix.

**Comment by stukey** [comment]
@glennsarti Great thanks Glenn.

**Comment by glennsarti** [comment]
So PR #1430 is up to fix the region case sensitivity problem.

The PowerShell region folding doesn't actually come from the PowerShell extension, it's embedded in VSCode by default, which is why the behaviour can seem odd i.e. Code Folding Disabled, with VSCode 1.23 and PowerShell Extension 1.8.1 will have case sensitive region folding :-)

Interestingly, VSCode only fixed that in 1.24.0 which is probably why I missed it orginally (https://github.com/Microsoft/vscode/commit/64186b0a262f0ff89a060cf8dbbf8de7ff831a00)

**Comment by glennsarti** [comment]
@stukey If you know how to use one-off extension builds, https://ci.appveyor.com/project/PowerShell/vscode-powershell-cs82i/build/1.8.1-insiders-236/artifacts has the VSIX file for that PR

**Comment by stukey** [comment]
Thanks @glennsarti I don’t know how to do that so I will wait for the release version. Just so I’m clear do I still have to disable syntax folding in order for region folding to work properly in ps1 scripts (as it did before 1.8.0)?

**Comment by glennsarti** [comment]
Yes.  Once the new version is released, you can re-enable syntax folding.

**Comment by wsmelton** [comment]
@glennsarti I pulled down the VSIX file and can confirm that region folding is working again under that artifact.

**Comment by glennsarti** [comment]
Excellent!! Thankyou!

**Comment by stukey** [comment]
When will this be merged into a release version? I have no idea how that works...

**Comment by glennsarti** [comment]
@rjmholt and @rkeithhill will be able to answer that

**Comment by wsmelton** [comment]
@stukey there is a menu option to "install from vsix file" that lets you manually add the extension:
![image](https://user-images.githubusercontent.com/11204251/42639243-28ef9ab4-85b5-11e8-9688-e5b137fae021.png)

Just download the file and browse to it when prompted. There is another prompt that you have an "earlier version" of the extension but just let it overwrite that version.

**Comment by rjmholt** [comment]
Also @stukey if you have the VSIX file downloaded, you can install it in the CLI like this:
```
code --install-extension /path/to/PowerShell-insiders.vsix
```

**Comment by econba** [comment]
I've installed the update and can also confirm that code folding an regions is working again and it is non case sensitiv. But unfortunately I recognized that code folding on regions now fails if a comment line follows the region start:
![image](https://user-images.githubusercontent.com/41182456/42677405-e96a6190-867b-11e8-8314-1dd629a08476.png)
only the commented line is folded:
![image](https://user-images.githubusercontent.com/41182456/42677440-0d0c83a8-867c-11e8-82ad-1b1d4927ec85.png)
Can someone test to confirm?

**Comment by glennsarti** [comment]
I can't repro that.

| Expanded | Collapsed |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/5819622/42677849-a75b492a-86af-11e8-9c49-3b1b76916311.png) | ![image](https://user-images.githubusercontent.com/5819622/42677884-bf5e93ce-86af-11e8-8f9c-a799de9ff1c2.png) |

**Comment by msm-fc** [comment]
@glennsarti using ms-vscode.PowerShell@1.8.1-insiders-236 with vscode 1.25.1, the issue appears resolved.  Thanks!!

I'm using this test code to verify:

`#Region Capitalized
#somecomment

#Endregion

#region lowercase
#somecomment

#endregion`

**Comment by rjmholt** [comment]
The release went out this morning with a fix for this in it
