### ISSUE TITLE
Type resolution fails in certain circumstances with JSON.NET

### ISSUE THREAD

**Issue by jduncanator** [PowerShell/vscode-powershell#143]
I've just run into a weird case where debugging a script in VS Code would cause an exception to be thrown, and running it inside PowerShell ISE works fine. After a few hours of pulling my hair out, and further hours debugging I've managed to pin it down to a type resolution issue inside JSON.NET that only occurs in certain situations.

From what I can tell, the issue only occurs when JSON.NET attempts to deserialize a JSON file with a type hint in it (eg. `"$type": "NameSpaceAndClassName, AssemblyName"`). JSON.NET will parse this type hint, and attempt to load the assembly based on the `AssemblyName` in the type hint into the current AppDomain by way of `Assembly.LoadWithPartialName` or `Assembly.Load`. Inside VS Code this fails, however inside PS ISE the Assembly loading succeeds and the type is resolved.

The only thing I've been able to put this down to is the fact that Assemblies and Modules loaded into PowerShell running under VS Code that reference JSON.NET will use the JSON.NET packaged with the VS Code extension as can be seen when debugging the PowerShell Script running in VS Code and looking at the loaded modules:

![VS Code Loaded Modules](https://cloud.githubusercontent.com/assets/1518948/14552464/fe68e84e-0321-11e6-856b-c1277b02810d.png)

And then comparing this to the modules loaded in PS ISE:

![PowerShell ISE Loaded Modules](https://cloud.githubusercontent.com/assets/1518948/14552491/572f8f78-0322-11e6-9e43-69840e312c16.png)

This is the [function it fails at](https://github.com/JamesNK/Newtonsoft.Json/blob/6d7c94e69fa2f52b91fb22972321cb9b51b9abed/Src/Newtonsoft.Json/Serialization/DefaultSerializationBinder.cs#L43-L97) in JSON.NET. The specific line depends on which macro is used, but under VS Code [this](https://github.com/JamesNK/Newtonsoft.Json/blob/6d7c94e69fa2f52b91fb22972321cb9b51b9abed/Src/Newtonsoft.Json/Serialization/DefaultSerializationBinder.cs#L56) call to `Assembly.LoadWithPartialName` function will return null, where as it returns the correct Assembly under PS ISE.

I'm not fluent enough with how the entire extension works to offer my suggestions on how this can be remedied, but I'm willing to submit a PR if someone can point me in the correct direction!

**Comment by daviwil** [comment]
Thanks for the detailed report!  What version of JSON.net is your module using?  Also, is the type you're deserializing something that comes with the .NET framework or is it in another DLL that ships with your module?

**Comment by jduncanator** [comment]
It's using an identical version of JSON.NET, 7.0.0.0, to the one which is packaged with the extension.

The type that is trying to be deserialized is one that is shipped with the module's DLL. I thought that this might be the issue as well, however, the type is marked public. The fact that JSON.NET can't load the assembly based on the provided assembly name (partial or fully qualified) suggests to me that it's not the type, rather some weird quirk in assembly resolution.

**Comment by CodyALohse** [comment]
@jduncanator It's been awhile since you posted this, but did you ever find a resolution? I'm running into a similar issue and based on your screenshots it looks like you're using AcmeSharp module which I am as well. 

I noticed that when running my script in the Powershell  Integrated console I get the type error, but if I run in the standard Powershell console the script runs fine.

**Comment by jduncanator** [comment]
@CodyALohse It's been a while, but I think I ended up giving up trying to debug using the PowerShell integration with VS Code, and just resorted to using the PowerShell ISE.

Your issue sounds slightly different to mine, so may not be related.

As a side note, I've just tried to reproduce this @daviwil and the issue still remains. I'm not sure if its possible to blacklist the packaged dependencies from assembly resolution (might be able to hook the assembly resolution event, and skip the assembly if it's packaged with the extension). If I find some more time towards the end of the week I'll see if I can resolve the issue.

**Comment by CodyALohse** [comment]
I think you nailed the issue personally, here is a similar ticket filed [ref](https://github.com/ebekker/ACMESharp/issues/139) on the AcmeSharp project where a version of the Newtonsoft lib was loaded in the GAC, the resolution there was to remove the GAC version.

**Comment by jduncanator** [comment]
@CodyALohse If you're still facing this issue, you may be able to forcibly load the correct version of the Newtonsoft.JSON assembly into the current AppDomain using reflection to force .NET to use that version of the assembly for future type resolution, and skip .NET from resolving to the packaged VS Code assembly (or one in the GAC). I haven't tested this, so your mileage may vary but something along the following lines may do the trick: `Assembly.LoadFrom("PATH TO YOUR JSON.NET")`.

**Comment by rjmholt** [comment]
We handle dependency resolution differently now, so this should no longer be an issue
