### ISSUE TITLE
Custom snippets don't show up among other snippets

### ISSUE THREAD

**Issue by fullenw1** [PowerShell/vscode-powershell#1431]
## Issue Description ##

Custom snippets don't show up among other snippets.
I am talking about those snippets:
[https://github.com/PowerShell/vscode-powershell/blob/master/docs/community_snippets.md](https://github.com/PowerShell/vscode-powershell/blob/master/docs/community_snippets.md)

Did I miss something?
I think there is nothing to install beside the vscode-powershell extension... or is it?

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 6.1.7601 |
| VSCode | 1.25.0|
| PowerShell Extension Version | 1.8.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.14409.1012|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.14409.1012|
|BuildVersion|10.0.14409.1012|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.8.1|
|vscode-icons|robertohuertasm|7.24.0|;

</details>

**Comment by rkeithhill** [comment]
These are snippets that users can add to their own, custom snippets file. You can create one of those by following these instructions](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets).  

In general, we tend to add only **widely applicable** (general use) snippets to the extension itself.
