### ISSUE TITLE
PSScriptAnalyser misreporting

### ISSUE THREAD

**Issue by ciejepro** [PowerShell/vscode-powershell#1432]
Issue Type: <b>Bug</b>

If statements comparing with $null aren't evaluated properly

if($Credential.UserName -ne $null) labelled as null on wrong side of operator

Several instances of "trailing whitespace' yet none exists

Extension version: 1.8.1
VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:11.248Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz (2 x 3292)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|4.00GB (1.23GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe D:\github\At-A-Glance|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rkeithhill** [comment]
I believe the "trailing whitespace" issue is a problem.  The $null warnings are probably correct - see https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/PossibleIncorrectComparisonWithNull.md

However, you can exclude both of these rules by adding a `PSScriptAnalyzerSettings.psd1` file to your workspace.  Then add a workspace settings file to `${workspaceRoot}/.vscode/workspace.json` with this setting:
```
{
    // Use a custom PowerShell Script Analyzer settings file for this workspace.
    // Relative paths for this setting are always relative to the workspace root dir.
    "powershell.scriptAnalysis.settingsPath": "./PSScriptAnalyzerSettings.psd1"
}
```

Then in the `PSScriptAnalyzerSettings.psd1` add this content:
```
# Use the PowerShell extension setting `powershell.scriptAnalysis.settingsPath` to get the current workspace
# to use this PSScriptAnalyzerSettings.psd1 file to configure code analysis in Visual Studio Code.
# This setting is configured in the workspace's `.vscode\settings.json`.
#
# For more information on PSScriptAnalyzer settings see:
# https://github.com/PowerShell/PSScriptAnalyzer/blob/master/README.md#settings-support-in-scriptanalyzer
#
# You can see the predefined PSScriptAnalyzer settings here:
# https://github.com/PowerShell/PSScriptAnalyzer/tree/master/Engine/Settings
@{
    # Only diagnostic records of the specified severity will be generated.
    # Uncomment the following line if you only want Errors and Warnings but
    # not Information diagnostic records.
    #Severity = @('Error','Warning')

    # Analyze **only** the following rules. Use IncludeRules when you want
    # to invoke only a small subset of the default rules.
    IncludeRules = @('PSAvoidDefaultValueSwitchParameter',
                     'PSMisleadingBacktick',
                     'PSMissingModuleManifestField',
                     'PSReservedCmdletChar',
                     'PSReservedParams',
                     'PSShouldProcess',
                     'PSUseApprovedVerbs',
                     'PSAvoidUsingCmdletAliases',
                     'PSUseDeclaredVarsMoreThanAssignments')

    # Do not analyze the following rules. Use ExcludeRules when you have
    # commented out the IncludeRules settings above and want to include all
    # the default rules except for those you exclude below.
    # Note: if a rule is in both IncludeRules and ExcludeRules, the rule
    # will be excluded.
    #ExcludeRules = @('PSAvoidTrailingWhitespace', 'PSPossibleIncorrectComparisonWithNull', )

    # You can use rule configuration to configure rules that support it:
    #Rules = @{
    #    PSAvoidUsingCmdletAliases = @{
    #        Whitelist = @("cd")
    #    }
    #}
}
```

In general, PSSA the default rules are going to rub some set of folks the wrong way.  That's why I recommend folks use this settings file to configure PSSA with the rules they find valuable.

**Comment by rjmholt** [comment]
For any issues with PSScriptAnalyzer, you should report them [here](https://github.com/PowerShell/PSScriptAnalyzer/issues/new/choose)

**Comment by rjmholt** [comment]
Going to close this issue in favour of #1429.
