### ISSUE TITLE
Crashed on script start

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1433]
### System Details

- Operating system name and version: Windows 10 Insiders
- VS Code version: 1.25
- PowerShell extension version: 1.81
- Output from `$PSVersionTable`:

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

1.25.0
0f080e5267e829de46638128001aeb7ca2d6d50e
x64
PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSTeams> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1      0


PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSTeams> code --list-extensions --show-versions
aaron-bond.better-comments@1.2.6
abusaidm.html-snippets@0.2.1
alefragnani.Bookmarks@0.19.1
azemoh.one-monokai@0.3.4
ban.spellright@2.5.16
donjayamanne.githistory@0.4.1
DotJoshJohnson.xml@2.3.1
eamodio.gitlens@8.4.1
emilast.LogFileHighlighter@2.4.0
emmanuelbeziat.vscode-great-icons@2.1.36
Equinusocio.vsc-material-theme@2.3.0
felixfbecker.php-debug@1.12.3
formulahendry.code-runner@0.9.3
gerane.Theme-dimmed-monokai@0.0.2
gharveymn.nightswitch@1.1.0
GrapeCity.gc-excelviewer@2.1.24
hdg.live-html-previewer@0.3.0
HookyQR.beautify@1.3.2
IBM.output-colorizer@0.1.2
ikappas.phpcs@1.0.5
ionutvmi.reg@0.0.2
JerryHong.autofilename@0.1.3
johnpapa.winteriscoming@0.7.1
Kelvin.vscode-sshfs@1.9.2
KnisterPeter.vscode-github@0.30.0
mechatroner.rainbow-csv@0.4.2
mkloubert.vscode-remote-workspace@0.31.0
ms-mssql.mssql@1.4.0
ms-vscode.csharp@1.15.2
ms-vscode.PowerShell@1.8.1
ms-vsliveshare.vsliveshare@0.3.395
ms-vsts.team@1.136.0
redhat.java@0.28.0
robertohuertasm.vscode-icons@7.24.0
Shan.code-settings-sync@2.9.2
streetsidesoftware.code-spell-checker@1.6.10
streetsidesoftware.code-spell-checker-polish@1.0.0
vangware.dark-plus-material@1.2.0
vscjava.vscode-java-debug@0.10.0
vscjava.vscode-java-pack@0.3.0
vscjava.vscode-java-test@0.7.1
vscjava.vscode-maven@0.9.1
wayou.vscode-todo-highlight@0.5.12
whizkydee.material-palenight-theme@1.8.0
xaver.clang-format@1.6.2
zhuangtongfa.Material-theme@2.15.1
Zignd.html-css-class-completion@1.11.0
PS C:\Users\pklys\OneDrive - Evotec\Support\GitHub\PSTeams> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17713.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17713.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with... crashing of PowerShell Extension. Copied script from internet. Pasted. Saved. Crashed.

### Attached Logs
[EditorServices.zip](https://github.com/PowerShell/vscode-powershell/files/2189294/EditorServices.zip)

**Comment by nathan-alden-hp** [comment]
I am noticing massive problems with this update. Yesterday I was using 1.8.0 with absolutely no issues. Today, VS Code installed 1.8.1 automatically and I've had nothing but problems. Long terminal start times, long debugging times, frequent crashes... at one point I tried logging out of Windows thinking there was a process hanging somewhere.

The slowdowns and crashes happen even with the simplest of scripts.

**Comment by rjmholt** [comment]
Hi @nathan-alden-hp, would you be able to provide more information about your environment?

The following would be helpful in diagnosing the problem:
* The output of the following commands from the integrated console:
  - `$PSVersionTable`
  - `code -v`
  - `code --list-extensions --show-versions`
* Your operating system name/version
* Your [extension logs](https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us)

**Comment by nathan-alden-hp** [comment]
```
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
```
PS > code -v
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
```
```
PS > code --list-extensions --show-versions
ms-vscode.csharp@1.15.2
ms-vscode.PowerShell@1.8.1
```
OS: Windows 10 Enterprise 1803

I can't get you extension logs at the moment.

**Comment by rjmholt** [comment]
Okie doke, no worries. That sounds positive, but please do open an issue if you have any problems. And thanks for uploading that info too!

**Comment by rkeithhill** [comment]
@PrzemyslawKlys the logs you attached indicate the extension is failing right after a debug session has been started.  This is happening within 4 secs of the extension starting up PSES.  What exactly are you repro steps?  I see you listed:

> Copied script from internet. Pasted. Saved. Crashed.

But I'm not sure how any of that would initiate a debug session.

**Comment by PrzemyslawKlys** [comment]
@rkeithhill I may have pressed F5... however keep in mind that I've switched F5 with CTRL+F5 just for this reason. And even thou I don't use debugging at all. I am constantly getting VSCode hanging with that debugging in place. I am not sure where is it coming from.

![image](https://user-images.githubusercontent.com/15063294/42722552-27563290-874e-11e8-8c00-9766e1533fea.png)

I get VSCode to hang quite often for no reason.

**Comment by rkeithhill** [comment]
@PrzemyslawKlys Thanks.  With that, I can reproduce this.  The twist is that you are attempting to "run" the script before the PS editor (and debug) services (PSES) has fully initialized.  To avoid this for now, wait until this message in the status bar:

![image](https://user-images.githubusercontent.com/5177512/42726005-b2323732-874a-11e8-9e54-eb6984684932.png)

Changes to:

![image](https://user-images.githubusercontent.com/5177512/42726015-cdb17df6-874a-11e8-809b-d2b9b4d7e729.png)

Before attempt to start or debug a script.  Initialization can take ~5-10 seconds for the PSES to fully initialize.  In the meantime, we'll be looking for ways to prevent run/launch from VSCode until PSES is initialized.

**Comment by PrzemyslawKlys** [comment]
Great! I guess I am just impatient. Maybe I don’t know how to properly debug scripts in powershell and i essentially press f5 get errors/output, fix things, rerun and so on.

**Comment by rkeithhill** [comment]
@tylerl0706 @rjmholt Debugged this to this line:
```csharp
        public Task SendEvent<TParams, TRegistrationOptions>(
            NotificationType<TParams, TRegistrationOptions> eventType,
            TParams eventParams)
        {
            // Some requests may still be in the SynchronizationContext queue
            // after the server stops so don't act on those requests because
            // the protocol channel will already be disposed
            if (this.currentState == ProtocolEndpointState.Shutdown)
            {
                return Task.FromResult(true);
            }

            // Some events could be raised from a different thread.
            // To ensure that messages are written serially, dispatch
            // dispatch the SendEvent call to the message loop thread.

            if (!this.InMessageLoopThread)
            {
                TaskCompletionSource<bool> writeTask = new TaskCompletionSource<bool>();

                this.SynchronizationContext.Post( <<<<===== SynchronizationContext is null at this point
                    async (obj) =>
                    {
                        await this.protocolChannel.MessageWriter.WriteEvent(
                            eventType,
                            eventParams);

                        writeTask.SetResult(true);
                    }, null);

                return writeTask.Task;
            }
```
This is happening because VSCode, seeing that the extension has been activated, allows run/debug session to be started **before** PSES is fully initialized.

**Comment by rkeithhill** [comment]
I have one attempt fix in the extension where we pop a warning dialog if the user attempts to debug/run a script before PSES has finished initializing.  The result is this warning notification:
![image](https://user-images.githubusercontent.com/5177512/42729343-3014f4c2-8792-11e8-9a38-e02ff4cb07f8.png)
Which expands to:
![image](https://user-images.githubusercontent.com/5177512/42729344-35ff50e4-8792-11e8-9672-df51f8fcea2a.png)
The one downside to this approach is that VSCode opens `launch.json` in the active editor when we "abort" the call to `resolveDebugConfiguration`.  I have added some comments to a VSCode issue related to this unfortunate side-effect: https://github.com/Microsoft/vscode/issues/54213

Ideally, we could either indicate to VSCode that our debugger isn't ready yet OR during the `resolveDebugConfiguration` call wait 10 secs or so for PSES to finish initializing. But my JS fu isn't quite strong enough to make that work.  :-(

**Comment by tylerl0706** [comment]
I'd rather just indicate that it's not ready yet. I think that's a reasonable approach/response considering it's rare people run into this.

I also really like the words on that warning!
