### ISSUE TITLE
Logpoints

### ISSUE THREAD

**Issue by General-Gouda** [PowerShell/vscode-powershell#1434]
I did not see an open or closed issue related to the newer VS Code Logpoint feature so I thought I'd add one. 

Having the ability to have specific log output to console without needing to write the code directly through the Logpoint functionality would be useful for debug purposes.

**Comment by rjmholt** [comment]
Looks like the feature for VSCode is [here](https://code.visualstudio.com/docs/editor/debugging#_logpoints).

@General-Gouda would you be able to give a small motivating example?

**Comment by rkeithhill** [comment]
I have started work on this but got side-tracked.  We already support a form Logpoints way before VSCode added the concept. Take a look at the `Tracepoints` section of this blog post - https://blogs.technet.microsoft.com/heyscriptingguy/2017/02/06/debugging-powershell-script-in-visual-studio-code-part-1/

**Comment by General-Gouda** [comment]
@rjmholt I do a lot of work with Active Directory and with Exchange Online. Many of the cmdlets do not return any console output and so I need to inject some sort of output to know what user I'm iterating through. Or, I will simply output the index number. 

Since VS Code doesn't (yet) support Write-Output I could see where outputting the index number through logpoints would be helpful rather than killing kittens with a Write-Host or something. It would also keep the code cleaner. I don't always need output on a saved script. Sometimes I just want to know it worked the first time I wrote it and then save it for later.

@rkeithhill I'll give tracepoints a try the next time I write a script like this. One point of feedback is that tracepoints appear to need more complex expressions. Is it possible to simply output a variable by typing in "$var" as the expression or does it have to be contained in a logic statement such as IF?

**Comment by rkeithhill** [comment]
> tracepoints appear to need more complex expressions

Agreed,  Keep in mind the trace points implementation is just using `Set-PSBreakpoint -Line xx -Action {}`.  That is, you can get the same functionality with raw PowerShell.

Implementing logpoints, will simplify take an expression like this `$var` and integrate it into an Action like `{ <script to execute>; continue }`.

**Comment by TylerLeonhardt** [comment]
This is supported now 🎉

**Comment by rkeithhill** [comment]
How does this work? I tried with the Examples folder DebugTest.ps1 file on line 12.  I set up a Log Point message of `i is $i` and the `$i` is not interpolated.  Neither is `i is {$i}`.   How do you specify a variable that you want its value to be logged?

**Comment by TylerLeonhardt** [comment]
It would appear that I used the wrong quotes 😅

https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointApiUtils.cs#L180

**Comment by rkeithhill** [comment]
I'll do that tonight, if you can wait.

**Comment by rkeithhill** [comment]
Issue submitted #2654

**Comment by rkeithhill** [comment]
I'll see if I can get a PR in here on my lunch break.

**Comment by rkeithhill** [comment]
Bah, should have submitted that issue to PSES.  Can you move it or should we leave it where it is?

**Comment by rkeithhill** [comment]
PR submitted - https://github.com/PowerShell/PowerShellEditorServices/pull/1270

**Comment by TylerLeonhardt** [comment]
It's ok where it is :)
