### ISSUE TITLE
VSCode Peek / Go to Definition functions do not work when variable is cast as specific type

### ISSUE THREAD

**Issue by stukey** [PowerShell/vscode-powershell#1439]
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.25.1
- PowerShell extension version: 1.8.1
- Output from `$PSVersionTable`: see below 

```
S C:\Users\me> code -v
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
PS C:\Users\me> $psEditor.EditorServicesVersion
 
Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1      0
 
PS C:\Users\me> code --list-extensions --show-versions
bobmagicii.autofoldyeah@1.0.6
ms-vscode.PowerShell@1.8.1
wengerk.highlight-bad-chars@0.0.3
 
PS C:\Users\me> $psversiontable
 
Name                           Value
----                           -----
PSVersion                      5.1.14393.2248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
I am not sure whether this is a VSCode issue or a PowerShell Extension issue so please forgive me if I have logged this in the wrong place.
 
In the latest version of VSCode (1.25.1) with the latest version of the PowerShell Extension (1.8.1) on Windows 10:
 
If you cast your variables by prefixing them with the type, e.g. [string], the “Go to Definition” and “Peak Definition” functions do not work.
 
```
Example:
 
[string]$testVar = "Test123"
 
$testVar
```
 
Right-click on the second ‘$testVar’ and select either “Go to Definition” or “Peak definition” and you’ll get an error “No definition found for $testVar”. Screenshot:

![6f3ab4e0-72eb-41d7-b439-18c5670e824e](https://user-images.githubusercontent.com/12292623/42840758-c2c5877c-89ff-11e8-9576-c15037d1c672.jpeg)

Try it without casting it as a [string] and it works as expected.

**Comment by tylerl0706** [comment]
I have a fix for this - plus some bonus fixes :)

**Comment by stukey** [comment]
@tylerl0706 Great news. Thanks Tyler. Any more info on the bonus fixes 👍

**Comment by tylerl0706** [comment]
```
$var1 = "string"
$var1

[string] $var2 = "string"
$var2

[NJsonSchema.Annotations.NotNull()] $var3 = "string"
$var3

$a, $var4 = "string", "sss"
$var4

$a, [string] $var5 = "string", "sss"
$var5
```

will all go to the correct spot.

**Comment by mklement0** [comment]
@stukey: Just to aid in discovery of this issue, can you please correct the typo in the title (and body)? `peak` -> `peek`

**Comment by stukey** [comment]
Sure if you can tell me how to do that. I can’t see an option to edit the title, only the body of the original post.

**Comment by stukey** [comment]
Ah looks like @tyler0706 already did it.

**Comment by mklement0** [comment]
@stukey: Great; in general, look for the button labeled `Edit` to the right of the title:

![image](https://user-images.githubusercontent.com/588825/43154471-728aa90c-8f42-11e8-8280-e16a026e4f1e.png)

**Comment by stukey** [comment]
Yup 🤯 I did edit the post but didn’t see any option to edit the title. Maybe it’s because Im getting the mobile view on my iPhone.
