### ISSUE TITLE
VSCode PowerShell Insiders versioning?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1445]
**Summary of the new feature**
VSCode PowerShell Insiders versioning for Insiders keeps on saying it's older then newest released version. It would be "easier" to manage if it would be version higher. For example current 1.8.1 would be 1.8.2 Insiders then Insiders would be dropped for 1.8.2 and then Insiders would 1.8.3 Insiders. 

I'm asking because to be able to use insiders I had to disable Auto-Update for all other plugins with VsCode and I have to manually update them. It's not hard or anything. Just annoying a bit. And it's a bit counter-intuitive that you put new insider version and you get message 'update' already.

**Comment by rjmholt** [comment]
Hi @PrzemyslawKlys, that actually sounds like a pretty good idea.

@tylerl0706 and I are thinking that every release, we should increment the `master` branch version immediately after so the insiders version is always ahead.

And then, we would only need to change the version in the following scenarios:
- Dropping the `insiders` for releases
- Incrementing the version number after releases
- Incrementing the `master` version number when breaking/significant changes are merged.

See also: https://github.com/PowerShell/vscode-powershell/issues/1425

**Comment by PrzemyslawKlys** [comment]
Sounds good to me.
