### ISSUE TITLE
Folding on #region tag in powershell broken

### ISSUE THREAD

**Issue by travis-sobeck** [PowerShell/vscode-powershell#1447]
The latest update broke Folding on #region tag in powershell files.
VS code version 1.25.0 and 1.25.1

**Comment by rkeithhill** [comment]
Duplicate of #1428 which has been fixed.  Fix will show up in the next release due sometime later this week - I hope.

**Comment by travis-sobeck** [comment]
Sorry, I missed that when I searched.

**Comment by rkeithhill** [comment]
No problem.  :-)

**Comment by rjmholt** [comment]
@travis-sobeck The release went out this morning with a fix for this in it

**Comment by travis-sobeck** [comment]
Thanks, so far its working great!
