### ISSUE TITLE
Entering a string for a switch parameter causes powershell to crash

### ISSUE THREAD

**Issue by andy2002a** [PowerShell/vscode-powershell#1450]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version: 1.8.1
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      5.1.14393.2312
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2312
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64

$pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      1      0

code --list-extensions --show-versions
joshbax.mdhelper@0.0.11
ms-vscode.PowerShell@1.8.1

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2312
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2312
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Steps to Reproduce:

1.Run the command block below
2.Enter random text when prompted in the console
3.You get an error saying that powershell crashed

If you launch the same code in the ISE you will get an error in the console saying that the switch param will not accept a string. However, the shell will not crash.

```
[cmdletbinding()]
param(
    [Parameter(Mandatory = $true, HelpMessage = 'test')]
    [Switch]$ServerName,

    [Parameter(Mandatory = $true, HelpMessage = 'test')]
    [Switch]$Server2Name

)#End cmdletbinding
```

### Attached Logs

Sent to vscode-powershell@microsoft.com

**Comment by tylerl0706** [comment]
I managed to grab a picture of the crash that flashes when executing the code above

<img width="1680" alt="screen shot 2018-07-30 at 11 42 25 pm" src="https://user-images.githubusercontent.com/2644648/43442273-579001aa-9452-11e8-86f8-30abf8bf9449.png">
