### ISSUE TITLE
Uninstalling Powershell Extension Error

### ISSUE THREAD

**Issue by Outek** [PowerShell/vscode-powershell#1455]
### System Details

- Operating system name and version: Windows Server 2016
- VS Code version: 1.25.1
- PowerShell extension version: 1.8.2
- Output from `$PSVersionTable`:
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.2368
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2368
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:
```
code -v
```powershell
PS C:\> code -v
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
```

```powershell
PS C:\> $pseditor.EditorServicesVersion
PS C:\>
```
```
PS C:\> code --list-extensions --show-versions
DotJoshJohnson.xml@1.9.2
lukehoban.Go@0.6.77
mauve.terraform@1.1.2
redhat.vscode-yaml@0.0.12
vscoss.vscode-ansible@0.1.3
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 40.77.226.250:443
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '40.77.226.250',
    port: 443 } ]
```

### Issue Description

When i try to uninstall the powershell extension:

```
PS D:\vscode_powershell> code --uninstall-extension ms-vscode.powershell
Uninstalling ms-vscode.powershell...
Extension 'ms-vscode.powershell' was successfully uninstalled!
code : ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 65.55.44.109:443
At line:1 char:1
+ code --uninstall-extension ms-vscode.powershell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ApplicationInsi...5.55.44.109:443:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '65.55.44.109',
    port: 443 } ]
```

Is there a silent extension uninstall command?

**Comment by rjmholt** [comment]
This looks like it might be a bug in VSCode. See the following issues:
* https://github.com/Microsoft/vscode/issues/19377
* https://github.com/Microsoft/vscode/issues/1320#issuecomment-283606443
* https://github.com/Microsoft/ApplicationInsights-node.js/issues/128
* https://github.com/Azure/azure-xplat-cli/issues/3287
* https://github.com/Microsoft/ApplicationInsights-node.js/issues/180

Looks like there might be [a proxy issue](https://github.com/Microsoft/vscode/issues/1320#issuecomment-166322394).

Otherwise, it might be an availability issue with the server.

It might be worth trying to uninstall again just like before to see if it's the second issue.

If that doesn't work, the `--verbose` flag will give more information: `code --verbose --uninstall-extension ms-vscode.powershell`.

Finally, VSCode doesn't document a `--silent` option, but it seems to accept one. I'm not sure if it works though.

**Comment by Outek** [comment]
This Server isn't connected to the internet, the address: '65.55.44.109' isn't reachable.

**Comment by rjmholt** [comment]
I just tried the following command:
```powershell
nmap -A 65.55.44.109 -p 443
```

Which gives the following result:
```
Starting Nmap 7.70 ( https://nmap.org ) at 2018-07-30 22:30 PDT
Nmap scan report for 65.55.44.109
Host is up (0.093s latency).

PORT    STATE SERVICE  VERSION
443/tcp open  ssl/upnp Microsoft IIS httpd
|_http-title: Not Found
| ssl-cert: Subject: commonName=*.vortex.data.microsoft.com
| Subject Alternative Name: DNS:*.vortex.data.microsoft.com, DNS:vortex.data.microsoft.com
| Not valid before: 2018-01-30T15:54:41
|_Not valid after:  2020-01-30T15:54:41
|_ssl-date: 2018-07-31T05:31:18+00:00; -1s from scanner time.

Host script results:
|_clock-skew: mean: -1s, deviation: 0s, median: -1s

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 29.55 seconds
```

So it looks like the server is up, just isn't responding to ICMP (so `ping` won't see it).

Are you behind an HTTP(S) proxy maybe?

Either way, it looks like this is a problem in VSCode — it probably shouldn't fall over when telemetry fails.

**Comment by rjmholt** [comment]
If you're behind a proxy, this may be the solution: https://github.com/Microsoft/vscode/issues/69#issuecomment-218074273

**Comment by rjmholt** [comment]
I've opened an issue in VSCode. We'll see what they say, but this looks like it's unrelated to the PowerShell extension itself, so I'll close this issue for now.
