### ISSUE TITLE
PSScript Analyzer Very Slow

### ISSUE THREAD

**Issue by dpallen12** [PowerShell/vscode-powershell#1457]
Issue Type: <b>Bug</b>

After the addition of the whitespace checker that the pscript analyzer does, it takes a really long time, sometimes minutes before it realizes that the fix has been applied to the code to satisfy the analyzer.

Extension version: 1.8.2
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (9.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rjmholt** [comment]
Hi @dpallen12, thanks for opening an issue. This is an area of active work for us at the moment, so we should hopefully have some improvements for this soon.

**Comment by tylerl0706** [comment]
We can dupe this to the active issue here:
https://github.com/PowerShell/vscode-powershell/issues/1232

Let me know if you feel otherwise
