### ISSUE TITLE
Still having problems with Regions folding on 1.8.2

### ISSUE THREAD

**Issue by MayPLaY** [PowerShell/vscode-powershell#1458]
## Issue Description ##

Hi, 
I saw with 1.8.0/1.8.1 you guys had some problems with regions folding, and 1.8.2 was supposed to fix it. But as you see in this gif, I'm still having problems with everything getting folded instead of my designed regions. 

I'm using "ctrl+k ctrl+8" and "ctrl+k ctrl+9" to fold/unfold. With the extentsion installed, I'm having trouble, but without it, I got no problem at all. I can't recall I moment where it didn't work before 1.8.x.

Thanks !!

![powershellextension_regionsproblem](https://user-images.githubusercontent.com/31284372/43540437-bd1772b2-9595-11e8-90ce-c5cb3ae97ca9.gif)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.25.1|
| PowerShell Extension Version | 1.8.2 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17134.165|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.165|
|BuildVersion|10.0.17134.165|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.8.2|;

</details>

**Comment by rjmholt** [comment]
Hi @MayPLaY, I've watched through the GIF a couple of times, but just want to be clear about the behaviour you're seeing vs the behaviour you're expecting.

Can you restate, in words, (1) the behaviour you're expecting and (2) the behaviour you're experiencing that differs from that expectation?

Also worth noting that this folding feature can be disabled with:
```
"powershell.codeFolding.enable": false
```

**Comment by MayPLaY** [comment]
Sorry for the confusion.

**Expected**
- Calling command "Un/Fold All Regions" : Get only "#region" and "#endregion" tag folding.
- Calling command "Un/Fold All" : Get everything fold (regions, statements, functions, etc.)
- This is what happen when the folding feature is disable (as you suggested), or extension is uninstalled.

**What it does**
- "Un/Fold All Regions" and "Un/Fold All" commands act exactly the same, they both fold everything.

I hope it's a bit more clear :).

Thanks.

**Comment by tylerl0706** [comment]
@glennsarti for the awareness.

I think we currently mark a lot of these folds [as Region](https://github.com/PowerShell/vscode-powershell/blob/master/src/features/Folding.ts#L449) ... Except [for `<# #>`](https://github.com/PowerShell/vscode-powershell/blob/master/src/features/Folding.ts#L485-L491)

As a test... Does the "Un/Fold All Regions" fold block comments `<#    #>`?

**Comment by tylerl0706** [comment]
@MayPLaY for the notification just in case

**Comment by MayPLaY** [comment]
Your guess is right ,"Un/Fold All Regions" doesn't fold block comments, but "Un/Fold All" does.

![powershellextension_commandproblemfold](https://user-images.githubusercontent.com/31284372/43551927-cdbe1492-95b6-11e8-8e5c-3764e98047ae.gif)

**Comment by glennsarti** [comment]
This seems like expected behaviour.   

* Line comments (`# line comment`) and region comments (`<# ..... #>`) are Comments (Unfold/Fold all Block Comments)

* Everything else is a Region (Unfold/Fold all Regions)

**Comment by tylerl0706** [comment]
Yeah, Glenn's right. I think we should probably open an issue on vscode to add another item to the enum... Maybe like a "Code" FoldingRangeKind

**Comment by glennsarti** [comment]
I haven't tried using an invalid enum integer e.g. -1

**Comment by rjmholt** [comment]
Actually, that's not a bad idea. Does assigning `4` work?

**Comment by glennsarti** [comment]
Okay...so quick test, it does work.  Can't say I'm happy about it though.  It's definitely a hack

Changed the following

From:
``` typescript
        // Find matching comment regions   #region -> #endregion
        this.matchScopeElements(
            this.extractRegionScopeElements(tokens, document),
            "custom.start.region",
            "custom.end.region",
            vscode.FoldingRangeKind.Region, document)
            .forEach((match) => { matchedTokens.push(match); });
```

To

``` typescript
        // Find matching comment regions   #region -> #endregion
        this.matchScopeElements(
            this.extractRegionScopeElements(tokens, document),
            "custom.start.region",
            "custom.end.region",
            56, document)
            .forEach((match) => { matchedTokens.push(match); });
```

**Comment by tylerl0706** [comment]
Ok. Let's maybe have a const static variable called like `FoldingRangeKindCode`? That's set to some arbitrary int?

Then we can have the expected behavior at least.

**Comment by rjmholt** [comment]
Wow, issue 55,686!

**Comment by rjmholt** [comment]
To quote from the VSCode issue:

> Region is only to be used for ranges originating from folding range marked by #region and #endregion
>
> For syntax ranges, don't set kind. kind is optional.

**Comment by tylerl0706** [comment]
Nice find, Rob!

**Comment by glennsarti** [comment]
OKay, I sense another PR on the way

**Comment by glennsarti** [comment]
Might have to PR a docs edit to the VS Code API.  As it doesn't mention that bit.  The only thing to indicate it's optional is the `?` in the interface definition, which is pretty obtuse.

**Comment by glennsarti** [comment]
Fix PR is up - https://github.com/PowerShell/vscode-powershell/pull/1467

**Comment by MayPLaY** [comment]
Thanks @glennsarti
