### ISSUE TITLE
Set Language+Debug Engine Ports?

### ISSUE THREAD

**Issue by WithHolm** [PowerShell/vscode-powershell#1462]
Hi!

Is there a way to set language and debug engine ports to a specific range?

Im trying to get vscode+powershell to work within a citrix enviorment, but they have a filtering rule saying that x user can only use a specific portrange. all other attempts to reach network traffic on ports that are not assigned to the user at just dropped. This means that when the integrated console starts it will never connect to the avalible port as the port selected is outside the range the specific user is allowed to access.

There is a set range of globally avalible ports but this is way outside the range that the language and debug engine normally runs on, but if this could be specified i could have it run on that range instead.

```
2018-8-2 11:12:27 [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
2018-8-2 11:12:27 [NORMAL] - Language server starting --
2018-8-2 11:12:27 [NORMAL] -     exe: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
2018-8-2 11:12:27 [NORMAL] -     args: C:\Users\*******\.vscode\extensions\ms-vscode.powershell-1.5.1\scripts\Start-EditorServices.ps1 -EditorServicesVersion '1.5.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.5.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\adm.phimeh\.vscode\extensions\ms-vscode.powershell-1.5.1\modules' -EnableConsoleRepl -LogLevel 'Verbose' -LogPath 'C:\Users\******\.vscode\extensions\ms-vscode.powershell-1.5.1\logs\1533201147-b64f13ed-3f9a-45e5-a402-4d0ce56461221533198640290\EditorServices.log' -SessionDetailsPath 'C:\Users\******\.vscode\extensions\ms-vscode.powershell-1.5.1\sessions\PSES-VSCode-14784-786245' -FeatureFlags @()
2018-8-2 11:12:28 [NORMAL] - powershell.exe started, pid: 996
2018-8-2 11:12:44 [NORMAL] - Language server started.
2018-8-2 11:12:44 [NORMAL] - {"debugServicePort":10295,"status":"started","channel":"tcp","languageServicePort":22533}
2018-8-2 11:12:44 [NORMAL] - Connecting to language service on port 22533...
```

**Comment by tylerl0706** [comment]
Hi @WithHolm, you have an outdated version of the extension.

We've switched away from using TCP ports to Named Pipes for communication which is file based.

This has allowed us to close all the network issue related bugs.

I suggest you grab the latest update. 

Let me know if you have any problems.

**Comment by tylerl0706** [comment]
I'm going to close this issue since it's not relevant anymore but feel free to open a new issue or reply here if you run into any problems.
