### ISSUE TITLE
Hashtable expression key.

### ISSUE THREAD

**Issue by TEH30P** [PowerShell/vscode-powershell#1463]
![vscode-powershell bug colorization](https://user-images.githubusercontent.com/15148944/43579075-8540b05a-9659-11e8-8b71-80d64fd99bea.png)

**Comment by tylerl0706** [comment]
Hi @TEH30P, not sure I understand the issue. Could you clarify?

**Comment by TEH30P** [comment]
A letters above red line should be white. It is a method call not a type.

**Comment by tylerl0706** [comment]
Oh I see. Thanks for clarifying! Syntax Highlighting is provided by [EditorSyntax](https://github.com/PowerShell/EditorSyntax).

Can you open this over there?

**Comment by tylerl0706** [comment]
I'm going to close this since it's not related to the actual extension code.

If you feel otherwise, please let me know 👍

**Comment by TEH30P** [comment]
Done!
https://github.com/PowerShell/EditorSyntax/issues/126
