### ISSUE TITLE
DSC resource intellisense support

### ISSUE THREAD

**Issue by PleaseStopAsking** [PowerShell/vscode-powershell#1469]
### System Details

- Operating system name and version:
```
Windows 10
```
- VS Code version:
```
 1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
```
- PowerShell extension version:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      2      0
```
- Output from `$PSVersionTable`:
```
PSVersion                      5.1.14393.2368
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2368
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am seeing an issue with intellisense loading custom DSC module resource definitions/syntax. Attached is the functionality working as expected in ISE vs. VSCode. I know there is an outstanding performance issue with scripts that contain the Import-DscResource cmdlet but I am not sure if this would be due to that issue.

![ise](https://user-images.githubusercontent.com/35308946/43775049-4449a1ec-9a19-11e8-8be4-69529cfa3f30.png)
![vscode](https://user-images.githubusercontent.com/35308946/43775055-4ecb307c-9a19-11e8-85ff-3360166d735c.png)

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rjmholt** [comment]
Are these completions provided in PowerShell? Tagging @SeeminglyScience here in case he has any insight :)

**Comment by SeeminglyScience** [comment]
@rjmholt That's `Get-DscResource ResourceName -Syntax`.  We already do something similar with `Get-Command -Syntax`, so we likely just need to check if it's a DSC resource at that step.  I'll include a link to where we do that later tonight.

**Comment by PleaseStopAsking** [comment]
Any update on this one?

**Comment by danielboth** [comment]
I'm also still waiting for proper DSC support in vscode, one of the major blockers in using vscode.

**Comment by SydneyhSmith** [comment]
Going to mark this as up for grabs for now, until we get more bandwidth...if anyone has some knowledge of C# and wants to contribute we would be happy to help you get started!
