### ISSUE TITLE
how do i import other powershell modules and snapins- exchange, scom, lync etc.

### ISSUE THREAD

**Issue by egamma** [PowerShell/vscode-powershell#147]
_From @lkowitz on April 15, 2016 19:46_
- VSCode Version: 1.0
- OS Version: 2012 R2

Steps to Reproduce:
1. Not sure how to import other snapins like the powershell exchange cmdlets.  i'd like to have intelli sense and the ability to debug these commands.

_Copied from original issue: Microsoft/vscode#5359_

**Comment by dfinke** [comment]
This is on the list of enhancements. Hopefully a REPL is not to far off as is having a $profile for vsc PowerShell.

Check out this thread https://github.com/PowerShell/vscode-powershell/issues/124

This comment specifically.
https://github.com/PowerShell/vscode-powershell/issues/124#issuecomment-201073752

**Comment by daviwil** [comment]
Profile support is coming in the 0.6.0 update of the PowerShell extension in a couple of weeks, this will make it easier for users to load modules into their session for IntelliSense use.

**Comment by daviwil** [comment]
Both profile support and integrated console have been implemented, closing this old issue :)
