### ISSUE TITLE
Start-EditorServices failure loading ps1 files

### ISSUE THREAD

**Issue by weloytty** [PowerShell/vscode-powershell#1474]
Issue Type: <b>Bug</b>

Occasionally (not every time), I open a .ps1 file and get the following error:

```
The terminal process command 'C:\Program Files\PowerShell\6.0.3\pwsh.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command '& 'C:\Users\Loyttyw\.vscode\extensions\ms-vscode.powershell-1.8.2\modules\PowerShellEditorServices\Start-EditorServices.ps1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.8.2'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\Loyttyw\.vscode\extensions\ms-vscode.powershell-1.8.2\modules'-EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'C:\Users\Loyttyw\.vscode\extensions\ms-vscode.powershell-1.8.2\logs\1533716573-5d7c6d0c-db8c-4e27-b713-84553e9420e11533716490676\EditorServices.log' -SessionDetailsPath 'C:\Users\Loyttyw\.vscode\extensions\ms-vscode.powershell-1.8.2\sessions\PSES-VSCode-20104-170759' -FeatureFlags @()'' failed to launch (exit code: 3221225477)
```

So I set "powershell.developer.editorServicesLogLevel": "Diagnostic", in my settings, and got this output.

```
8/8/2018 4:22:53 AM [NORMAL] - Visual Studio Code v1.25.1 64-bit
8/8/2018 4:22:53 AM [NORMAL] - PowerShell Extension v1.8.2
8/8/2018 4:22:53 AM [NORMAL] - Operating System: Windows 64-bit
8/8/2018 4:22:53 AM [DIAGNOSTIC] - Succesfully required c:\Program Files\Microsoft VS Code\resources\app/node_modules.asar/vscode-textmate
8/8/2018 4:22:53 AM [DIAGNOSTIC] - Loaded the vscode-textmate module
8/8/2018 4:22:53 AM [DIAGNOSTIC] - Created the textmate Registry
8/8/2018 4:22:53 AM [DIAGNOSTIC] - PowerShell grammar file specified as c:\Program Files\Microsoft VS Code\resources\app\extensions\powershell\syntaxes\powershell.tmLanguage.json
8/8/2018 4:22:53 AM [NORMAL] - Language server starting --
8/8/2018 4:22:53 AM [NORMAL] -     exe: C:\Program Files\PowerShell\6.0.3\pwsh.exe
8/8/2018 4:22:53 AM [NORMAL] -     args: C:\Users\Loyttyw\.vscode\extensions\ms-vscode.powershell-1.8.2\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.8.2'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\Loyttyw\.vscode\extensions\ms-vscode.powershell-1.8.2\modules'-EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'C:\Users\Loyttyw\.vscode\extensions\ms-vscode.powershell-1.8.2\logs\1533716573-5d7c6d0c-db8c-4e27-b713-84553e9420e11533716490676\EditorServices.log' -SessionDetailsPath 'C:\Users\Loyttyw\.vscode\extensions\ms-vscode.powershell-1.8.2\sessions\PSES-VSCode-20104-170759' -FeatureFlags @()
8/8/2018 4:22:53 AM [NORMAL] - Syntax Folding Provider registered
8/8/2018 4:22:54 AM [NORMAL] - powershell.exe terminated or terminal UI was closed
8/8/2018 4:23:10 AM [VERBOSE] - Formatting on type at position {"line":16,"character":4} - file:///d%3A/code/tfs/XXX/YYY/Source/src/TFS/Merge-CamstarChangeset.ps1...
8/8/2018 4:23:53 AM [NORMAL] - Language server startup failed.
8/8/2018 4:23:53 AM [ERROR] - The language service could not be started: 
8/8/2018 4:23:53 AM [ERROR] - Timed out waiting for session file to appear.
```

This behavior seems to have started with 1.8.x, I don't recall seeing this before that.

Extension version: 1.8.2
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.88GB (11.05GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rjmholt** [comment]
Just looked up the exit code (`0xC0000005` in hex). Possibly an access violation, which is pretty unexpected — we're not running any unmanaged code.

If this is an access violation, the best thing to do is probably get a core dump, which you can do by following the instructions here: https://docs.microsoft.com/en-us/windows/desktop/wer/collecting-user-mode-dumps.

Is it a specific ps1 file you're opening when it crashes? Or maybe it's doing something unusual like pInvoking or using COM? This is just the first I've seen an unmanaged crash for not just the extension but even PowerShell. Ideally we can reproduce it, but I imagine that might be tricky.

**Comment by weloytty** [comment]
The problem usually happens when I do Open Folder on a folder of mixed .net (classic) and powershell code.  I captured the dumps, and them along with logs at https://github.com/weloytty/issue1474-vscode-powershell (The dumps were all >100MB, so I had to zip them)

**Comment by weloytty** [comment]
Problem does not reoccur on 1.26.1

**Comment by tylerl0706** [comment]
Glad to hear it @weloytty! If you ever hit this again, please reach out. Closing for now 👍
