### ISSUE TITLE
powershell.enableProfileLoading not observed

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/vscode-powershell#1479]
### System Details

```
PS C:\Users\pwatson\ws\001> code -v
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
PS C:\Users\pwatson\ws\001> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      2      0


PS C:\Users\pwatson\ws\001> code --list-extensions --show-versions
abusaidm.html-snippets@0.2.1
alefragnani.project-manager@8.0.0
austin.code-gnu-global@0.2.2
christian-kohler.path-intellisense@1.4.2
DavidAnson.vscode-markdownlint@0.19.0
donjayamanne.githistory@0.4.2
DotJoshJohnson.xml@2.3.1
felixfbecker.php-debug@1.12.3
felixfbecker.php-intellisense@2.3.3
formulahendry.auto-close-tag@0.5.6
formulahendry.code-runner@0.9.4
k3a.theme-dark-plus-contrast@0.1.101
ms-mssql.mssql@1.4.0
ms-python.python@2018.7.1
ms-vscode.cpptools@0.17.7
ms-vscode.csharp@1.15.2
ms-vscode.PowerShell@1.8.2
PeterJausovec.vscode-docker@0.1.0
redhat.java@0.29.0
robertohuertasm.vscode-icons@7.25.0
vscodevim.vim@0.16.0
xabikos.JavaScriptSnippets@1.7.0
Zignd.html-css-class-completion@1.17.1
PS C:\Users\pwatson\ws\001> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with controlling the terminals created. On startup, a "powershell" terminal is created. But, it does not observe the settings I have given.

    "powershell.enableProfileLoading": false,

When I open a .ps1 file, a "PowerShell Integrated Console" starts and does observe the ProfileLoading setting. But, I cannot remove the previous "powershell" terminal.

**Comment by joeyaiello** [comment]
`powershell.enableProfileLoading` is only respected by the PowerShell Integrated Console. The `powershell` terminal you are using is just a generic VS Code terminal launching `powershell.exe` (just as it could be launching `cmd` or WSL/Linux `bash` or any other terminal). 

If you can't remove the previous `powershell` terminal, that's likely a VS Code issue. There should be a little trash can that lets you close it here: 

![image](https://user-images.githubusercontent.com/1255187/44118727-e48d266c-9fcb-11e8-959f-e6b785700a8a.png)
