### ISSUE TITLE
Debugger stopped working after upgrading vscode to 1.0

### ISSUE THREAD

**Issue by ftischhauser** [PowerShell/vscode-powershell#149]
Hi everyone

As the title says, my previously working setup suddenly stopped doing anything after the upgrade. I can see the the Microsoft.PowerShell.EditorServices.Host.exe process running in the background, but the GUI just waits forever for any output. Unfortunately I can't find any error messages in the [log files](https://github.com/PowerShell/vscode-powershell/files/223307/logfiles.zip) which makes this very hard to track. Could anyone point me into the right direction? Thanks!

**Comment by daviwil** [comment]
Hey Flavio, 1.0 appears to have changed some things that might have broken our debug adapter.  Thanks for sending along the logs!

**Comment by daviwil** [comment]
Another hit: https://github.com/Microsoft/vscode/issues/5429

**Comment by rkeithhill** [comment]
BTW the updated debug protocol for 1.0.0 says this:

> - adapters sends InitializedEvent (after the InitializeRequest has returned)

We may need to merge that [ordering change PR ](https://github.com/PowerShell/PowerShellEditorServices/pull/204)to a 0.5.1 branch and post it.

**Comment by jackmusick** [comment]
I believe I have the same issue. When starting the debugger, nothing happens. However, if I set a breakpoint, everything runs as expected.

**Comment by daviwil** [comment]
Sorry for the trouble guys, we'll get a new update out to fix this in the next few days.

**Comment by daviwil** [comment]
This is verified to be fixed in the 0.6.0 version of the extension, coming out very soon.  I'll close this bug once the update has been shipped.  Thanks for your patience!

**Comment by daviwil** [comment]
0.6.0 is now released!  Let me know if you run into any further trouble.
