### ISSUE TITLE
VSCode Update failed - Open Process

### ISSUE THREAD

**Issue by danielschwensen** [PowerShell/vscode-powershell#1491]
### System Details

- Operating system name and version:
Windows 10, 10.0.17134

- VS Code version:
1.26

- PowerShell extension version:
1.83

code -v
code : Die Benennung "code" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder
eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt
ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ code -v
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

$pseditor.EditorServicesVersion
code --list-extensions --show-versions
Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      3      0

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am experiencing a problem with the update process. I had to restart VSCode in order to install the latest update but then I got an error message. It stated that I should raise an issue on GitHub.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by danielschwensen** [comment]
[vscode-inno-updater.zip](https://github.com/PowerShell/vscode-powershell/files/2302433/vscode-inno-updater.zip)

**Comment by tylerl0706** [comment]
Hi @danielschwensen, thanks for this! When you say "it stated you should raise an issue" I take it you mean VSCode?

**Comment by danielschwensen** [comment]
@tylerl0706 Yes, that is correct. Please find the message attached
![inno_updater_2018-08-20_16-47-00](https://user-images.githubusercontent.com/36114476/44347665-bac11380-a498-11e8-86c0-69f14f209184.png)
.

**Comment by tylerl0706** [comment]
This is actually VSCode, itself, failing to update - not the vscode extension for VSCode.

You're going to want to open this over in:

https://github.com/Microsoft/vscode

They'll be able to help you further, much more than we can here.

**Comment by tylerl0706** [comment]
I'm going to close this since it's vscode and not the vscode PowerShell extension - let me know if you feel otherwise

**Comment by danielschwensen** [comment]
@tylerl0706  Thanks!
