### ISSUE TITLE
Document settings

### ISSUE THREAD

**Issue by trondhindenes** [PowerShell/vscode-powershell#15]
It would be nice to have a readme for all configurable settings related to PowerShell in VS Code, such as 
"PowerShell.editorServicesHostPath"
"PowerShell.waitForDebugger"
"PowerShell.enableLogging"

**Comment by daviwil** [comment]
When you open the user settings screen it has comments for the settings:

![image](https://cloud.githubusercontent.com/assets/79405/11274300/ee7f32c6-8e8c-11e5-9a15-c0b24eebb075.png)

Where else would you like to see documentation for those?

**Comment by trondhindenes** [comment]
Oh - I was ust assuming there might be more than these three.

**Comment by daviwil** [comment]
Not yet!  Will be adding more soon.  Any requests?

**Comment by trondhindenes** [comment]
Nice! Toggling on/off for the code analyzer is the main one for me. There's a separate issue for that one already, so we're all good :-)

**Comment by daviwil** [comment]
Yep, I'm going to get that in ASAP :)
