### ISSUE TITLE
Number sign in path breaks highlighting

### ISSUE THREAD

**Issue by ghost** [PowerShell/vscode-powershell#150]
When a number sign is part of a path, the highlighting breaks for everything on that line after the number sign.

Here's how it looks with a number sign:
![bad](https://cloud.githubusercontent.com/assets/18548867/14633323/f2497c06-05d1-11e6-9530-0c4ad258b9d1.PNG)

And If I delete the number sign, it works again.
![good](https://cloud.githubusercontent.com/assets/18548867/14633326/f45cb878-05d1-11e6-806d-b0c27e516208.PNG)

**Comment by rkeithhill** [comment]
Hmm, looks like the tm definition of single line comments isn't quite right.  IIRC a comment char `#` must have at least one (non-escaped) whitespace char in front of it.  Or it must be at the beginning of a line.

**Comment by daviwil** [comment]
We'll need to fix this for the shared syntax definition.  Really need to get the repo created for that...

**Comment by tylerl0706** [comment]
You mean [this repo](https://github.com/powershell/editorsyntax), @daviwil  😄

**Comment by rkeithhill** [comment]
Yeah, this issue should be moved to that repo - if it's still an issue (I suspect it is).

**Comment by tylerl0706** [comment]
It is, for the record

**Comment by tylerl0706** [comment]
Opened there so I'll close it here.
