### ISSUE TITLE
Inserting help inside a function is broken

### ISSUE THREAD

**Issue by ghost** [PowerShell/vscode-powershell#1509]
Using VS Code to write PowerShell scripts. When writing an Advance function I used to be able to type '##' (that's a double hash) at the top of the function between the function name and the [cmdletbinding()] and it would automatically add the PowerShell help descriptions.

Now when I do this it doesn't add the help but breaks all of my formatting. 

I logged a previous bug report but was told this is fixed in the current version, https://github.com/PowerShell/vscode-powershell/issues/1493. 

Still broken sorry. :(

Can someone please fix this awesome feature. Thanks!

Kind regards
Garry

### System Details
Major  Minor  Build  Revision
-----  -----  -----  --------
1      8      4      0

PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by nlsdg** [comment]
Same problem here. Logs and screenshots in the attached .zip.
[1509_log.zip](https://github.com/PowerShell/vscode-powershell/files/2343314/1509_log.zip)

Repo: create a new powershell file, paste the following and type ## on line 2. (Same as issue #1488.)
```
function Write-HelloWorld {
    
    [CmdletBinding(DefaultParameterSetName="Default")]
    param (
        $Hello,
        $World
    )
    Write-Host "$Hello $World"
}
```

It turns into this:

```
function Write-HelloWorld {
    #
    [CmdletBinding(DefaultParameterSetName="Default")]
    param (
    ,
    
    )
    Write-Host " "
    }
    [CmdletBinding(DefaultParameterSetName="Default")]
    param (
        $Hello,
        $World
    )
    Write-Host "$Hello $World"
}
```

**Comment by rjmholt** [comment]
I'm having some trouble reproducing this. Here's my current build of `master` branch (the fix commits being the same as the build):
![functionsnippet](https://user-images.githubusercontent.com/7009879/44962846-f49a1b80-af68-11e8-9f27-6dae626f725e.gif)

**Comment by rjmholt** [comment]
@ghost, @nlsdg can you try using the extension build attached and see if the error still occurs?

[psvsix.zip](https://github.com/PowerShell/vscode-powershell/files/2343920/psvsix.zip)

**Comment by DWOF** [comment]
@rjmholt I'm having the same issue. I have installed the extension build but still experience the incorrect behaviour.

[1509.zip](https://github.com/PowerShell/vscode-powershell/files/2345046/1509.zip)

I have also changed to the user version of the install but the issue persisted.


`Function ExportFSAPI {
    
    Param(
        [Parameter(Mandatory = $True)][SecureString]$APIString,
        [Parameter(Mandatory = $True)][String]$APIPath
    )

    Write-Verbose "**START $($MyInvocation.MyCommand)**"
    Write-Verbose "Test $APIPath"
    if (!$APIString) {
        write-warning "No API supplied."
        return
    }
    elseif (!$(test-path $(Split-Path $APIPath))) {
        Write-Verbose "Creating $(Split-Path $APIPath)"
        new-item $(Split-Path $APiPath) -itemtype directory
    }
    Write-Verbose "Import APIstring and decrypting"
    ConvertFrom-SecureString $APIString | Out-file $APIPath

    Write-Verbose "**END $($MyInvocation.MyCommand)**"
}`

`Function ExportFSAPI {
    #
    Param(
    [Parameter(Mandatory = )][SecureString],
    [Parameter(Mandatory = )][String]
    )
    
    Write-Verbose "**START $(.MyCommand)**"
    Write-Verbose "Test "
    if (!) {
    write-warning "No API supplied."
    return
    }
    elseif (!$(test-path $(Split-Path ))) {
    Write-Verbose "Creating $(Split-Path )"
    new-item $(Split-Path ) -itemtype directory
    }
    Write-Verbose "Import APIstring and decrypting"
    ConvertFrom-SecureString  | Out-file 
    
    Write-Verbose "**END $(.MyCommand)**"
    }
    Param(
        [Parameter(Mandatory = $True)][SecureString]$APIString,
        [Parameter(Mandatory = $True)][String]$APIPath
    )

    Write-Verbose "**START $($MyInvocation.MyCommand)**"
    Write-Verbose "Test $APIPath"
    if (!$APIString) {
        write-warning "No API supplied."
        return
    }
    elseif (!$(test-path $(Split-Path $APIPath))) {
        Write-Verbose "Creating $(Split-Path $APIPath)"
        new-item $(Split-Path $APiPath) -itemtype directory
    }
    Write-Verbose "Import APIstring and decrypting"
    ConvertFrom-SecureString $APIString | Out-file $APIPath

    Write-Verbose "**END $($MyInvocation.MyCommand)**"
}
`

**Comment by rkeithhill** [comment]
Yup, I can repro.  In 1.8.4 if you use `##` before the function keyword, doc comment help completion works but it doesn't if you try to place the doc comments inside the function.
