### ISSUE TITLE
Error: The language client requires VS Code version ^1.26 but recevied version 1.25.1

### ISSUE THREAD

**Issue by shnipov** [PowerShell/vscode-powershell#1511]
## Issue Description ##
After downgrade VS Code from 1.26 to 1.25.1 version I get this error when openning any powershell script.

## Attached Logs ##
```
2018-9-2 16:49:55 [NORMAL] - Visual Studio Code v1.25.1 64-bit
2018-9-2 16:49:55 [NORMAL] - PowerShell Extension v1.8.4
2018-9-2 16:49:55 [NORMAL] - Operating System: Windows 64-bit
2018-9-2 16:49:55 [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
2018-9-2 16:49:55 [NORMAL] - Language server starting --
2018-9-2 16:49:55 [NORMAL] -     exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
2018-9-2 16:49:55 [NORMAL] -     args: C:\Users\shdp\.vscode\extensions\ms-vscode.powershell-1.8.4\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.8.4'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\shdp\.vscode\extensions\ms-vscode.powershell-1.8.4\modules'-EnableConsoleRepl -LogLevel 'Verbose' -LogPath 'C:\Users\shdp\.vscode\extensions\ms-vscode.powershell-1.8.4\logs\1535896195-809b3bee-c179-4e41-82d1-02683d6de7c41535896191587\EditorServices.log' -SessionDetailsPath 'C:\Users\shdp\.vscode\extensions\ms-vscode.powershell-1.8.4\sessions\PSES-VSCode-2296-127040' -FeatureFlags @()
2018-9-2 16:49:55 [NORMAL] - Syntax Folding Provider registered
2018-9-2 16:49:55 [NORMAL] - powershell.exe started, pid: 13836
2018-9-2 16:49:57 [NORMAL] - Language server started.
2018-9-2 16:49:57 [NORMAL] - {"status":"started","debugServiceTransport":"NamedPipe","languageServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_fb40ad76-190a-4b9c-b295-e45fe5aaaa9f","languageServicePipeName":"\\\\.\\pipe\\PSES_ba844aa8-66fd-449a-b1ae-29386b74e32e"}
2018-9-2 16:49:57 [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_ba844aa8-66fd-449a-b1ae-29386b74e32e...
2018-9-2 16:49:57 [ERROR] - The language service could not be started: 
2018-9-2 16:49:57 [ERROR] - Error: The language client requires VS Code version ^1.26 but recevied version 1.25.1
2018-9-2 16:50:30 [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
```
### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.25.1|
| PowerShell Extension Version | 1.8.4 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17134.48|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.48|
|BuildVersion|10.0.17134.48|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.15.2|
|mssql|ms-mssql|1.4.0|
|PowerShell|ms-vscode|1.8.4|
|rest-client|humao|0.19.1|
|sqlops-debug|ms-mssql|1.1.0|;

</details>

**Comment by tylerl0706** [comment]
Opened issue on the vscode-languageclient ^

**Comment by shnipov** [comment]
Thanks. Your comment helped me to find workaround.

You have dependency on `"vscode-languageclient": "~5.0.0"` and on my machine it has requirement of `"vscode": "^1.26"` in `C:\Users\user\.vscode\extensions\ms-vscode.powershell-1.8.4\node_modules\vscode-languageclient\package.json`. May be it changed after update of vs code.

I've changed it manually to `"^1.25"`, looks like it's working now.

**Comment by tylerl0706** [comment]
Glad you're unblocked! I'll work with the folks over there and investigate this.

**Comment by tylerl0706** [comment]
Now that `1.27` is released, I think we're going to close this issue. We only support versions `latest` and `latest - 1`.

If you have any concerns please let me know.
