### ISSUE TITLE
JSON Syntax Highlighting in String of JSON within Powershell file

### ISSUE THREAD

**Issue by animusyosho** [PowerShell/vscode-powershell#1519]
I like to define objects in json and convert to hashtable object. That works well, but it's hard to troubleshoot JSON when it's not colored, and I have to copy and paste to a json file for vscode to color things in and show where I am missing a bracket or comma or whatnot. Would be nice if this is doable inside the powershell files themselves via this great plugin! If somehow that could just use the default VScode bevavior for json files inside a defined block of json, that would be perfect.

Thanks!

**Comment by tylerl0706** [comment]
Hi there! So what you'd like is JSON syntax highlighting inside of a string? Is that right?

**Comment by rkeithhill** [comment]
If you figure out how to do that, we need to tell the folks who provide TypeScript support. I'd love to have HTML/CSS highlighting within strings in my Angular component (ts) files.   :-)

**Comment by animusyosho** [comment]
Correct! If it's doable, that would make this even better. :)

**Comment by tylerl0706** [comment]
I think you should open an issue on [VSCode](https://github.com/Microsoft/vscode) first to allow programatic ways to define regions of code - so that we could embed other syntax highlighting into a powershell file.

AFAIK, this is not possible for us to do based on what VSCode gives us.

**Comment by rkeithhill** [comment]
Vote up https://github.com/Microsoft/vscode/issues/1751.  I just did.

**Comment by rkeithhill** [comment]
Given this is a VSCode limitation. I'm closing this issue.
