### ISSUE TITLE
Debugging psm1 file

### ISSUE THREAD

**Issue by rroman81** [PowerShell/vscode-powershell#152]
I am having an issue where i am attempting to debug a psm1 module script. When I launch the debugger with standard Powershell launch.json settings, I get an error "Cannot run a document in the middle of a pipeline: C:\<path to module>\samplemodule.psm1."
Any specific way i can invoke the "import-module .\samplemodule" somehow?

**Comment by rkeithhill** [comment]
You can create a debug.ps1 file that imports the module and runs exported commands.  Or you can create a Pester test (SampleModule.Tests.ps1) file that imports the module and tests the commands in that file.  You can than run the debug.ps1 or Pester test file under the debugger.

**Comment by rroman81** [comment]
Gotcha. Thank you.
