### ISSUE TITLE
Incorrect color 

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/vscode-powershell#1522]
Methods look like a string when called between `$()`:

![image](https://user-images.githubusercontent.com/10828570/45346286-1a4aa480-b5a9-11e8-8c85-b997117fdead.png)

```
Version: 1.28.0-insider (user setup)
Commit: ee6a21fa49bd1906bd1378c2f2714cd656409e5c
Date: 2018-09-11T05:18:39.589Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by tylerl0706** [comment]
Hi @DarkLite1, thanks for this! Since this is a syntax highlighting issue, can you please open it under https://github.com/PowerShell/EditorSyntax ? That's the syntax that's used everywhere.

I'm going to close this since it's an issue with Editor Syntax. Thanks!
