### ISSUE TITLE
Intellisense: Splatting support

### ISSUE THREAD

**Issue by TheIncorrigible1** [PowerShell/vscode-powershell#1527]
As a frequent author of powershell scripts, I find myself using the splatting feature commonly.  When defining the hashtable for the cmdlet, I usually have the cmdlet below the hashtable so I can go back-and-forth with figuring out parameters and valid values with intellisense.  It would be nice if there was a DSC-esque autocompletion for keys and values.

I'm unsure how this should be accomplished, but it could be triggered when a naming standard to variables applies (such as `$newItemArgs = @{}`?).

[about_Splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-5.1)

**Comment by SeeminglyScience** [comment]
@TheIncorrigible1 All of our completion results come from the PowerShell engine via the `System.Management.Automation.CommandCompletion.CompleteInput()` method.

I've opened a feature request there to track it (PowerShell/PowerShell#7789)

**Comment by TylerLeonhardt** [comment]
I think we can close this as external since this feature would need to come from PowerShell. Let me know if you feel otherwise!
