### ISSUE TITLE
Contributor Guidelines say to use Insiders version but doesn't explain why

### ISSUE THREAD

**Issue by glennsarti** [PowerShell/vscode-powershell#1534]
The extension development document says to Install the Visual Studio Code Insiders Release ([Reference](https://github.com/PowerShell/vscode-powershell/blob/master/docs/development.md#4-install-visual-studio-code-insiders-release)) however it doesn't say why.

As a user
I would like to know
Why I need to use the Insiders Release
And what happens if I do not.

**Comment by rkeithhill** [comment]
I suspect it is to find bugs in the extension due to changes in VSCode which happens more often than one might think.  We'd (hopefully) see those early in the Insiders build, fix them and make available before the Insiders build becomes the Stable build.

**Comment by tylerl0706** [comment]
We were talking about docs (in general) for PowerShell... All our repos are going to get cleaned up in the docs department soon.

@SteveL-MSFT this is another aspect we should consider across repos. Fixing README and CONTRIBUTING.md
