### ISSUE TITLE
No indication that PowerShell code is running

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#154]
VSCode Version: 1.0.1-insiders
OS: Windows 10 RTM 1511
- Ran some PowerShell code (F8)
- Closed the Output window
- Ran more PowerShell code (F8)
- Had no indication it was running / VSCode GUI was static
- Finally thought to open Output window and check
- Changed Output window from "Tasks" to "PowerShell Output"
- Found output

Is there an opportunity here to improve the user experience? Perhaps not a priority, but it would be nice to know that "something is happening" when you use the "PowerShell: Run Selection" command in VSCode.

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment]
That's a great point.  Maybe we can change the status bar text while the script is running to indicate that something is happening?

**Comment by pcgeek86** [comment]
@daviwil yep, something like that would be cool.

**Comment by sevenam** [comment]
+1 for this. I really, really miss this functionality!

I think this is the only thing missing to make Powershell ISE obsolete for my part.

As far as I can see, there is no real indication that code is running, even with the Powershell Output window up (other than any output that is to be written to shell is missing).

**Comment by daviwil** [comment]
Good point!  I'll do something about this soon.

**Comment by pcgeek86** [comment]
@tylerl0706 This minor enhancement could be an easy win for the VSCode-PowerShell development experience.

**Comment by tylerl0706** [comment]
Thanks for that @pcgeek86! This looks relatively trivial.

**Comment by SeeminglyScience** [comment]
The easiest way to do this would probably be to create `ExecutionStartedEvent` and `ExecutionEndedEvent` notifications for PowerShellEditorServices to send to the editor.  One way to send the events would be to have the [LanguageService](https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Language/LanguageService.cs) attach to the `ExecutionStatusChanged` event on [PowerShellContext](https://github.com/PowerShell/PowerShellEditorServices/blob/f534ae64c9982d3a6c5261ae2303c12dfd5ccef0/src/PowerShellEditorServices/Session/PowerShellContext.cs#L1204).

**Comment by rjmholt** [comment]
I have a working implementation for this (just a text-in-status-bar update): [client](https://github.com/rjmholt/vscode-powershell/tree/execution-status-notifications) and [server](https://github.com/rjmholt/PowerShellEditorServices/tree/execution-status-notifications).

I'll add some tests and open PRs for each component.

I'm fairly new to the PowerShell extension client/server codebase and to VS Code's API, so looking for any feedback on my implementation (particularly suspect is [this bit](https://github.com/rjmholt/vscode-powershell/blob/b80cb4ec99038ac20dccad795bb49d932c94bc67/src/features/Console.ts#L254)).

**Comment by tylerl0706** [comment]
Fixed in #1227 🎉

Now you'll see a little spinner as well as some text 😄

all thanks to @rjmholt 🎉

**Comment by pcgeek86** [comment]
@tylerl0706 Awesome!
