### ISSUE TITLE
Debug adapter has terminated unexpectedly

### ISSUE THREAD

**Issue by Myrlin1** [PowerShell/vscode-powershell#1542]
### System Details

- Operating system name and version:
Windows 10 version 1803 build 17134.285
- VS Code version:
1.27.2 (user setup)
- PowerShell extension version: 
v1.8.4
- Output from `$PSVersionTable`: 
<table>
<tr><th>Name</th><th>Value</th></tr>
<tr><td>PSVersion</td><td>5.1.17134.228</td>
<tr><td>PSEdition</td><td>Desktop</td></tr>
<tr><td>PSCompatibleVersions</td><td>{1.0, 2.0, 3.0, 4.0...}</td></tr>
<tr><td>BuildVersion</td><td>10.0.17134.228</td></tr>
<tr><td>CLRVersion</td><td>4.0.30319.42000</td></tr>
<tr><td>WSManStackVersion</td><td>3.0</td></tr>
<tr><td>PSRemotingProtocolVersion</td><td>2.3</td></tr>
<tr><td>SerializationVersion</td><td>1.1.0.1</td></tr>
</table>

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

> code -v
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64

> $pseditor.EditorServicesVersion <- no output
> code --list-extensions --show-versions
[createInstance] extensionManagementService depends on downloadService which is NOT registered.
AlanWalk.markdown-toc@1.5.6
alefragnani.Bookmarks@9.1.0
alexdima.copy-relative-path@0.0.2
Angular.ng-template@0.1.10
austin.code-gnu-global@0.2.2
christian-kohler.npm-intellisense@1.3.0
CoenraadS.bracket-pair-colorizer@1.0.60
DavidAnson.vscode-markdownlint@0.20.0
dbaeumer.jshint@0.10.20
dbaeumer.vscode-eslint@1.6.0
ecmel.vscode-html-css@0.2.0
eg2.tslint@1.0.39
esbenp.prettier-vscode@1.6.1
fabianlauer.vs-code-xml-format@0.1.5
fabiospampinato.vscode-diff@1.3.3
formulahendry.auto-rename-tag@0.0.15
HookyQR.beautify@1.4.4
humao.rest-client@0.19.1
mdickin.markdown-shortcuts@0.8.1
mohsen1.prettify-json@0.0.3
ms-vscode.cpptools@0.18.1
ms-vscode.csharp@1.16.1
ms-vscode.PowerShell@1.8.4
msjsdiag.debugger-for-chrome@4.10.1
octref.vetur@0.12.6
rbbit.typescript-hero@2.3.2
ritwickdey.LiveServer@5.1.1
sdras.night-owl@0.4.1
sdras.vue-vscode-extensionpack@0.1.3
sdras.vue-vscode-snippets@1.3.0
Shan.code-settings-sync@3.1.2
tombonnike.vscode-status-bar-format-toggle@1.4.0
wmaurer.vscode-jumpy@0.3.1
xabikos.JavaScriptSnippets@1.7.0
Zignd.html-css-class-completion@1.17.1

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When I attempt to run the debugger on a powershell script, I get an error saying 

> Debug adapter has terminated unexpectedly

If I hit F8, I get the error:

> command 'PowerShell.RunSelection' not found

### Attached Logs

Followed the instructions for collecting logs in the README, but there are no log files being generated.  Log directory does not exist under $HOME\.vscode\extensions\ms-vscode.powershell-1.8.4

**EDIT**
Created logs directory, and DebugAdapter.log was generated successfully. 
[DebugAdapter.log](https://github.com/PowerShell/vscode-powershell/files/2408328/DebugAdapter.log)

Additionally, running the command

> Open PowerShell Extension Logs Folder

returns the error

> command 'PowerShell.OpenLogFolder' not found

### Troubleshooting steps taken
* Removed the powershell extension from vscode and reinstalled

Not really sure what else to do.  Any guidance would be appreciated.

**Comment by Tnk1972** [comment]
Also getting the same debug termination error when debugging any script in extension version 1.8.4, logs do not show anything obvious but crash always generates a "Socket closed, shutting down." message in DebugAdapter.log which is probably to be expected, but not seeing anything else even with Verbose logging enabled.

**Comment by rjmholt** [comment]
I'm going to dupe this to https://github.com/PowerShell/vscode-powershell/issues/1494 so we can keep all the discussion there.
