### ISSUE TITLE
Disable matching word highlighting

### ISSUE THREAD

**Issue by baespey** [PowerShell/vscode-powershell#1543]
Visual Studio Code settings allow you to disable matching words with an option called Selection Highlight.  But when I added the PowerShell extension, this feature came back.

How do I disable it for the PowerShell extension?

**Comment by rjmholt** [comment]
@baespey Does it disable again if you disable it now with the PowerShell extension installed? Are you sure the setting persists between sessions? You may need to set something in the [VSCode settings](https://code.visualstudio.com/docs/getstarted/settings). Also see https://github.com/Microsoft/vscode/issues/5351.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive/answered by settings--will re-open if this is not resolved
