### ISSUE TITLE
Cutting/Deleting folded code affects only one line

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1563]
Having something like this:
![image](https://user-images.githubusercontent.com/15063294/46576165-fd489c00-c9c3-11e8-8260-649b32a6abd6.png)

Folding it...

![image](https://user-images.githubusercontent.com/15063294/46576167-08033100-c9c4-11e8-99c0-4a9ef707d384.png)

Now when you delete that line or CTRL+X it my expectation would be that it would affect whole folded section and not just highlighted line. Or am I wrong? I believe this is how it works in Visual Studio 2015+ although I've not checked recently.

**Comment by rjmholt** [comment]
My first thought is that this is probably something VSCode itself controls, rather than us. Maybe open an issue in https://github.com/Microsoft/vscode and see what they say?

I'll close here, since I don't think we can change this behaviour from the extension. But if it turns out we can, we can reopen.

**Comment by rkeithhill** [comment]
Hmm, I don't think so.  I've deleted entire collapsed regions in TS and that is supposed to work.  I think the bug is in the PS extension.  @glennsarti ?

**Comment by PrzemyslawKlys** [comment]
There is same behaviour for `markdown` and json in 1.28 so @rjmholt may be right on this.

**Comment by rkeithhill** [comment]
This might be a difference based on a new setting that doesn't show the ending `}`.  What I do is TS is collapse a section of code and the following closing `}` and press <kbd>delete</kbd>.  That deletes the entire section.  I have to say that I really, really DISLIKE the current code-folding default that collapses the entire folding region to a single line - for this very reason.  And I'm not seeing a setting to revert back to the old behavior. Think I'll need to submit an issue.

**Comment by PrzemyslawKlys** [comment]
If you select it this way

![image](https://user-images.githubusercontent.com/15063294/46627037-761d3480-cb39-11e8-875c-2f1460b5e828.png)

It will work properly. So it seems you have explicitly select 2nd line start for it to copy whole section.

**Comment by rkeithhill** [comment]
OK, I see the same behavior with the C# extension where it collapses to a single line so yeah, I guess it's a VSCode issue after all.

**Comment by glennsarti** [comment]
> I have to say that I really, really DISLIKE the current code-folding default that collapses the entire folding region to a single line

Will that be fixed by https://github.com/PowerShell/vscode-powershell/pull/1557 ?

**Comment by glennsarti** [comment]
@rkeithhill ^^

**Comment by rkeithhill** [comment]
Well, yes and no.  :-)  I wouldn't really mind the "collapse to single line" behavior **if** cut/copy/delete worked as expected. But it seems that may be a VSCode bug that we can't control.  :-(  Either that or the C# extension has the same folding bug.  But that's a bit hard to believe.
