### ISSUE TITLE
Request textDocument/codeLens failed

### ISSUE THREAD

**Issue by tmknight** [PowerShell/vscode-powershell#1565]
PowerShell Integrated Console crashes when pasting over entirety of content loaded in editor.  Seems to occur when there are several dozens of lines.

[3-PowerShell Editor Services (2).log](https://github.com/PowerShell/vscode-powershell/files/2456842/3-PowerShell.Editor.Services.2.log)
[4-PowerShell Editor Services (2).log](https://github.com/PowerShell/vscode-powershell/files/2456843/4-PowerShell.Editor.Services.2.log)

### VSCode extensions:
CoenraadS.bracket-pair-colorizer@1.0.60
Compulim.compulim-vscode-closetag@1.2.0
Darfka.vbscript@1.0.4
DotJoshJohnson.xml@2.3.2
felixfbecker.php-debug@1.12.6
felixfbecker.php-intellisense@2.3.5
formulahendry.auto-close-tag@0.5.6
formulahendry.code-runner@0.9.4
ikappas.phpcs@1.0.5
jamiewest.theme-light-vs-mac@0.4.5
mrmlnc.vscode-apache@1.1.1
ms-mssql.mssql@1.4.0
ms-python.python@2018.8.0
ms-vscode.cpptools@0.19.0
ms-vscode.csharp@1.16.1
ms-vscode.PowerShell@1.9.0
ms-vsts.team@1.136.0
raymondcamden.htmlescape-vscode-extension@0.0.4
redhat.vscode-yaml@0.0.17
Shan.code-settings-sync@3.1.2
yuichinukiyama.vscode-preview-server@1.1.1

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by rjmholt** [comment]
Hi @tmknight thanks for opening an issue. I'm having trouble reading those logs -- are they the ones described [here](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md)?

**Comment by tmknight** [comment]
Sorry, try these:
[1_EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2457106/1_EditorServices.log)
[2_vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/2457107/2_vscode-powershell.log)

**Comment by rjmholt** [comment]
It doesn't look like there's anything in the second set of logs describing any errors. The first set seems to imply the connection broke, but to diagnose why we would need the logs from EditorServices.

I'm pretty certain a crash would show in the logs (EditorServices has pretty reliable crash-logging behaviour), so it might just be a question of reproducing the issue and immediately grabbing the logs.

With all that said, from what you describe I'm thinking this is the same as https://github.com/PowerShell/vscode-powershell/issues/1561.

**Comment by tmknight** [comment]
Agreed.  Closing as duplicate of  https://github.com/PowerShell/vscode-powershell/issues/1561
