### ISSUE TITLE
Indented #region does not work beyond 7 spaces

### ISSUE THREAD

**Issue by johlju** [PowerShell/vscode-powershell#157]
If the #region tag (the # character) is present withing the first 8 characters on a new line, the #region gives you a minus sign to collapse the region. But beyond 8 it does not. I'm using spaces instead of tabs for indent. I have not tested if the same problem exist when using tabs.

```
# This work
function Get-Something {
    if (condition) {
       #region My region test
        Write-Information "Test #Region"
       #endregion My region test
    }
}

# This does not work
function Get-Something {
    if (condition) {
        #region My region test
        Write-Information "Test #Region"
        #endregion My region test
    }
}
```

**Comment by rkeithhill** [comment]
Code folding is purely a VSCode feature at this point based upon indentation and nothing else.  There is no support for language participation in code folding.  See this [VSCode issue](https://github.com/Microsoft/vscode/issues/4787)
