### ISSUE TITLE
PowerShell Intellisense does not work

### ISSUE THREAD

**Issue by elliottgaryusa** [PowerShell/vscode-powershell#1575]
### System Details

VSCode
Version: 1.28.0 (user setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

### VSCode extensions:
Darfka.vbscript@1.0.4
formulahendry.code-runner@0.9.4
GrapeCity.gc-excelviewer@2.1.26
KnisterPeter.vscode-github@0.30.0
luggage66.VBScript@0.0.2
ms-vscode.csharp@1.16.2
ms-vscode.powershell@1.9.0

### PowerShell version:
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

System Details Output
```

```

### Issue Description

I am experiencing a problem with...
Microsoft PowerShell extension 1.9.0

How to reproduce:
1. Open new file with .ps1 extension
2. Enter Get-Child (or any partial PowerShell command)
3. Result, no suggestions and no code complete
4. Enter a complete PS command like Get-ChildItem -
5. Result, no parameter suggestions

Background:
This seems to have started since the latest VSCode update 1.28.0 (user setup).
The code snippets seem to work OK but not the commands themselves.
I tried re-installing the extension but it did not help.

#### Expected Behaviour

I would expect normal intellisense behavior as before, which worked great before VSCode 1.28.0

#### Actual Behaviour

Intellisense does not work at all.
Snippets seem to work OK.

**Comment by rjmholt** [comment]
Hi @elliottgaryusa, thanks for opening an issue.

Can you please attach your logs, as described in [the troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md)? Without them, reproducing the issue (and fixing it) is much harder.

We ship independently of the VSCode version, so unless a breaking change has occurred in VSCode, that shouldn't affect the extension's functionality. (We develop against the insiders version so that we are aware of those). So maybe worth trying with the extension installed in [VSCode Insiders](https://code.visualstudio.com/insiders/) as well?

**Comment by elliottgaryusa** [comment]
Here's the logs but, for some reason, they are out of date (10/3) and do not show any current activity.
I changed the logging to both Verbose and Diagnostic with no change.

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2473024/EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/2473025/vscode-powershell.log)

**Comment by elliottgaryusa** [comment]
I noticed that intellisense seems to work as expected on another pc that I upgraded from VSCode 1.27.1 to 1.28.0.  So it appears that my install is goofed up somehow.

**Comment by elliottgaryusa** [comment]
A complete uninstall then new install of all extensions and VSCode seems to have fixed the problem.  So now I'm not sure if the root of the issue is with the extension or VSCode.  The issue is resolved for now.
