### ISSUE TITLE
Read-Host should accept empty input

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#158]
it isn't unheard of for a read-host prompt to show a default value that will be used if the user just presses enter.  While this works at the console, it doesn't in VSCode.  I have to type something.  Even a space isn't accepted.

**Comment by daviwil** [comment]
Is this when the Read-Host prompt shows up in the VS Code UI?  I think I handled the empty input case correctly when it's done in the debug console, so maybe I just need to fix it for the UI case.

**Comment by rkeithhill** [comment]
I didn't see a UI. I was just putting the cursor in the Debug Console `>` prompt and pressing enter.  Nothing happened i.e. my script didn't move on.

**Comment by daviwil** [comment]
Ahhh...  And putting in a space and pressing Enter didn't do anything either?  I bet they're throwing out empty command lines and not sending them to the debug adapter...

**Comment by rkeithhill** [comment]
That's correct.  Just a space doesn't work either.  I was testing a module that prompts for input but the user can accept the "default" by just pressing <kbd>Enter</kbd>.

**Comment by daviwil** [comment]
I filed an issue for this here: https://github.com/Microsoft/vscode/issues/5773

**Comment by daviwil** [comment]
They fixed this issue in master so I assume that won't show up until after 1.1.0.  I'll move this to 0.7.0.

**Comment by tylerl0706** [comment]
This looks like an old issue from pre-PSIC days. Read-Host in the PSIC works just fine without supplying input. Is there another scenario we care about?

**Comment by rkeithhill** [comment]
No.
