### ISSUE TITLE
restarting Integrated Console does not respect powershell.powerShellDefaultVersion setting

### ISSUE THREAD

**Issue by fbehrens** [PowerShell/vscode-powershell#1586]
### System Details

System Details Output
```
### VSCode version: 1.28.1 3368db6750222d319c851f6d90eb619d886e08f5 x64

### VSCode extensions:
adammaras.overtype@0.2.0
alefragnani.project-manager@9.0.1
DavidAnson.vscode-markdownlint@0.20.0
DotJoshJohnson.xml@2.3.2
eamodio.gitlens@8.5.6
EditorConfig.EditorConfig@0.12.5
EFanZh.graphviz-preview@1.3.0
emmanuelbeziat.vscode-great-icons@2.1.44
fatihacet.gitlab-workflow@1.2.0
Ionide.Ionide-fsharp@3.28.0
Ionide.Ionide-Paket@1.12.0
mohsen1.prettify-json@0.0.3
ms-mssql.mssql@1.4.0
ms-python.python@2018.9.0
ms-vscode.csharp@1.16.2
ms-vscode.PowerShell@1.9.0
ms-vsliveshare.vsliveshare@0.3.790
msjsdiag.debugger-for-chrome@4.10.2
ritwickdey.LiveServer@5.1.1
robinbentley.sass-indented@1.4.9
Shan.code-settings-sync@3.1.2
vstirbu.vscode-mermaid-preview@0.10.1
wesbos.theme-cobalt2@2.1.6
woodywoodsta.vscode-material-syntax-dark@0.1.1
zhuangtongfa.Material-theme@2.17.4


### PSES version: 1.9.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14393.2485
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2485
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I have set the setting`"powershell.powerShellDefaultVersion": "Windows PowerShell (x86)"`

When I start `code` and the `Powershell Integrated Terminal` is and shows the correct Version(`5.1 (x86)`)
![image](https://user-images.githubusercontent.com/13704/47018089-40d59f80-d154-11e8-955a-94d1e84c322d.png)

When I kill the Terminal 
![image](https://user-images.githubusercontent.com/13704/47018302-c8231300-d154-11e8-97a6-02ded349418e.png)

and say `YES`, I like to restart it.

I am not getting an `Windows PowerShell (x86)` ,

but a 64bit

![image](https://user-images.githubusercontent.com/13704/47018467-1801da00-d155-11e8-9541-f67e71f0b913.png)

### Attached Logs

Here are diagnostics log
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/2483190/logs.zip)

**Comment by rjmholt** [comment]
It looks like this is deliberate:
https://github.com/PowerShell/vscode-powershell/blob/0388343e13e4baadfffc34b25d6d49a6200fee58/src/session.ts#L286-L299

@rkeithhill do you know what `powerShellDefaultVersion` is supposed to mean here? Is this a by-design scenario?

@fbehrens If you set the `powershellExePath` setting instead, that will be honoured.

**Comment by rkeithhill** [comment]
From the configuration comments:
```
  // Specifies the name of the PowerShell version used in the startup session when the extension loads e.g "Windows PowerShell (x86)" or "PowerShell Core 6.0.2 (x64)".
  "powershell.powerShellDefaultVersion": "",
```
This is a true "user" preference while this:
```
  // Specifies the full path to a PowerShell executable. Changes the installation of PowerShell used for language and debugging services.
  "powershell.powerShellExePath": "",
```
is what the "extension" uses to store the last selected PowerShell version's path.

**Comment by eedwards-sk** [comment]
I just ran into this while using multiple powershell versions.

```
    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "/usr/local/bin/pwsh",
            "versionName": "pwsh"
        },
        {
            "exePath": "/usr/local/bin/pwsh-preview",
            "versionName": "pwsh-preview"
        }
    ],
    "powershell.powerShellDefaultVersion": "pwsh-preview"
```

after closing the integrated terminal using the trashcan, and re-opening it using the warning dialog (as per the issue author), it loads `pwsh` instead of `pwsh-preview`:

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by davesbrown** [comment]
seems to be loading 7 by default even when changing
"powershell.powerShellDefaultVersion": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"

**Comment by rjmholt** [comment]
> seems to be loading 7 by default even when changing
"powershell.powerShellDefaultVersion": "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe"

The default needs to be specified by name rather than path; try:

```json
"powerShell.powerShellDefaultVersion": "Windows PowerShell (x64)"
```

**Comment by TylerLeonhardt** [comment]
The original issue is fixed now. If you still see this behavior please let us know.
