### ISSUE TITLE
Interactive debugging within Temporary Integrated Console hangs

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#1589]
Issue Type: <b>Bug</b>

I'm having an issue with interactive debugging through Temporary Integrated Console ("createTemporaryIntegratedConsole": true). In particular, when the debugger breaks at a breakpoint and I issue a command the prompt never re-appears so I'm limited to just one command that I can run to test something.

Extension version: 1.9.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rjmholt** [comment]
Looks like this is a duplicate issue of https://github.com/PowerShell/vscode-powershell/issues/1263. I'm afraid we haven't gotten around to investigating it yet, however getting the debugging experience stabilised is next on our agenda.
