### ISSUE TITLE
Show IntelliSense suggestions in manifest (psd1) files

### ISSUE THREAD

**Issue by lucdekens** [PowerShell/vscode-powershell#159]
As far as I can see, Intellisense for manifests (.psd1) is not yet implemented.
Is that on the list of features to come, or am I missing something ?

**Comment by daviwil** [comment]
Hey Luc!  I believe that we don't get IntelliSense for manifest files because it's not provided by the PowerShell engine.  I just tried getting IntelliSense for a manifest file in the PowerShell ISE and nothing came up.  Have you seen IntelliSense in manifest files anywhere before?

This might be a good feature request for UserVoice if we determine that it isn't already being provided by the engine.

**Comment by lucdekens** [comment]
You are right David.
Most of the commercial PowerShell editors also just provide a template, no intellisense either.

Is that possible, a template based on the file extension ?

**Comment by daviwil** [comment]
Yep!  @rkeithhill and I are working on something for this for a future version of the VS Code extension.

**Comment by lzybkr** [comment]
The engine doesn't provide completions for a manifest, so it'd be good to put this on uservoice.

The engine would have to guess it's completing in a manifest because the api doesn't accept a filename, so at best, it would have to guess based on some heuristics, but I think it might work well.

**Comment by rkeithhill** [comment]
Another uservoice idea would be to support PSD1 schema files.  Perhaps that is just a fully fleshed out set of key/value pairs for all nested hashtables?

**Comment by lucdekens** [comment]
Raised the idea on UserVoice
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13585962-provide-intellisense-template-for-manifests

**Comment by daviwil** [comment]
Thanks Luc!

**Comment by tylerl0706** [comment]
Should we defer this issue (close it) to PowerShell's issue that JohnLudlow has opened? If PowerShell adds completions for psd1's we should get intellisense for free, right?

**Comment by rkeithhill** [comment]
Yup.

**Comment by tylerl0706** [comment]
Sounds good!
