### ISSUE TITLE
Debugging a script with no breakpoints set hangs without even starting

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#160]
I've noticed that if I F5 the script (or use the Play button on the debug pane) and it doesn't have any breakpoints set, the status bar turns orange, but it seems like the execution doesn't start actually (at least nothing is being spit out to the Debug console). If I do put a breakpoint (even if it's not active) the script does run as expected. Is that something wrong with my instance or that's a known issue?

**Comment by rkeithhill** [comment]
This will be fixed in the upcoming 0.6.0 release.  Basically the debug protocol changed slightly in VSCode 1.0 and that broke the 0.5.0 release.
