### ISSUE TITLE
Upgrade to VS Code's webview API 

### ISSUE THREAD

**Issue by mjbvz** [PowerShell/vscode-powershell#1602]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by rkeithhill** [comment]
Thanks for the heads up!

**Comment by mjbvz** [comment]
Just a heads up: in VS Code 1.32 (the February update), using the previewHtml command will show an alert to the user, although the command should still work. We plan to remove the command entirely with VS Code 1.33 (March update)

**Comment by rkeithhill** [comment]
I started the switch over but am having a bit of a tough go at it.  Folks who use this feature with the PowerShell extension expect to be able to run their own personal JavaScript files (not under some extension's subdir). They tend to put these JS files in a workspace or their home dir.  I guess I could inline the JavaScript in the HTML?

**Comment by wycats** [comment]
I discovered this problem after trying to understand why this wasn't working. What's the status of this?

**Comment by TylerLeonhardt** [comment]
@mjbvz do you have any insight on how we could accomplish running a users own personal js files (besides just inlining)?

**Comment by TylerLeonhardt** [comment]
@wycats it is indeed broken as of 1.33 of vscode. We'll get it fixed but there might be some breaking changes that come with it as the underlying API is very different.

**Comment by mjbvz** [comment]
@TylerLeonhardt Your webview can pass any set of paths to `localResourceRoots`. Try passing in the path to the user scripts

**Comment by TylerLeonhardt** [comment]
@mjbvz that sadly doesn't seem to work:

See the variables section:
![image](https://user-images.githubusercontent.com/2644648/56693588-ad989c00-6699-11e9-9b95-97b610bb8a5f.png)

The URI to my js file is there... but the function defined in said js file is not available
![image](https://user-images.githubusercontent.com/2644648/56693693-fbad9f80-6699-11e9-9a50-b2ec3f0174d2.png)

**Comment by mjbvz** [comment]
Are the scripts also referenced on the page using `vscode-resource` URIs? Can you share a branch that has your current code?

**Comment by TylerLeonhardt** [comment]
Ah... wasn't also including them in the body of the html... sorry about that.

Now that I've referenced them using `vscode-resource:///full/path/to/fdsa.js` everything works as expected!

**Comment by TylerLeonhardt** [comment]
There doesn't seem to be a way to _update_ the `localResourceRoots` once you've already created a webview. Is that true, @mjbvz?

**Comment by mjbvz** [comment]
The options objects are immutable but `Webview.options` is mutable

**Comment by TylerLeonhardt** [comment]
#1919 fixed in this.
