### ISSUE TITLE
language server startup failed on macOS 10.14.1 (18B75)

### ISSUE THREAD

**Issue by azureandbeyond** [PowerShell/vscode-powershell#1603]
### VSCode version:
1.28.2 7f3ce96ff4729c91352ae6def877e59c561f4850 x64

### VSCode extensions:
donjayamanne.githistory@0.4.3
ms-kubernetes-tools.vscode-kubernetes-tools@0.1.14
ms-mssql.mssql@1.4.0
ms-python.python@2018.9.2
ms-toolsai.vscode-ai@0.3.1
ms-vscode.azure-account@0.5.1
ms-vscode.cpptools@0.20.1
ms-vscode.PowerShell@1.9.0
ms-vsts.team@1.144.1
PeterJausovec.vscode-docker@0.3.1
redhat.vscode-yaml@0.1.0
vsciot-vscode.vscode-arduino@0.2.22

### PowerShell version:

```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

The PowerShell console in VSCode cannot start. After 2 minutes of starting it stops with the error message "The language service could not be started".

### Attached Logs
```
11/7/2018 3:50:39 PM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
11/7/2018 3:50:42 PM [NORMAL] - Language server starting --
11/7/2018 3:50:42 PM [NORMAL] -     exe: /usr/local/bin/pwsh
11/7/2018 3:50:42 PM [NORMAL] -     args: /Users/Tom/.vscode/extensions/ms-vscode.powershell-1.9.0/modules/PowerShellEditorServices/Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.9.0'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/Tom/.vscode/extensions/ms-vscode.powershell-1.9.0/modules'-EnableConsoleRepl -LogLevel 'Normal' -LogPath '/Users/Tom/.vscode/extensions/ms-vscode.powershell-1.9.0/logs/1541602239-f4c34257-a983-41bb-a211-d260bd964adb1541602224073/EditorServices.log' -SessionDetailsPath '/Users/Tom/.vscode/extensions/ms-vscode.powershell-1.9.0/sessions/PSES-VSCode-10449-748238' -FeatureFlags @()
11/7/2018 3:50:43 PM [NORMAL] - Syntax Folding Provider registered
11/7/2018 3:52:43 PM [NORMAL] - Language server startup failed.
11/7/2018 3:52:43 PM [ERROR] - The language service could not be started: 
11/7/2018 3:52:43 PM [ERROR] - Timed out waiting for session file to appear.
```

**Comment by rjmholt** [comment]
Hi @azureandbeyond, thanks for opening an issue. The log snippet you included doesn't suggest anything specific beyond "it failed to start".

Can you try looking through the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md)?

It looks like either the startup script or the initialisation logic is failing on the server side, but we'll need more information to reproduce and diagnose it.

**Comment by azureandbeyond** [comment]
Hi @rjmholt, thanks for answering on the issue.
I've increased the log level to diagnostic with the following output:
```
11/7/2018 7:37:38 PM [NORMAL] - Visual Studio Code v1.28.2 64-bit
11/7/2018 7:37:38 PM [NORMAL] - PowerShell Extension v1.9.0
11/7/2018 7:37:38 PM [NORMAL] - Operating System: MacOS 64-bit
11/7/2018 7:37:38 PM [DIAGNOSTIC] - Succesfully required /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate
11/7/2018 7:37:38 PM [DIAGNOSTIC] - Loaded the vscode-textmate module
11/7/2018 7:37:38 PM [DIAGNOSTIC] - Created the textmate Registry
11/7/2018 7:37:38 PM [DIAGNOSTIC] - PowerShell grammar file specified as /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/powershell/syntaxes/powershell.tmLanguage.json
11/7/2018 7:37:38 PM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
11/7/2018 7:37:40 PM [NORMAL] - Language server starting --
11/7/2018 7:37:40 PM [NORMAL] -     exe: /usr/local/bin/pwsh
11/7/2018 7:37:40 PM [NORMAL] -     args: /Users/Tom/.vscode/extensions/ms-vscode.powershell-1.9.0/modules/PowerShellEditorServices/Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.9.0'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/Tom/.vscode/extensions/ms-vscode.powershell-1.9.0/modules'-EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath '/Users/Tom/.vscode/extensions/ms-vscode.powershell-1.9.0/logs/1541615858-83021f92-2198-4c6c-b1dd-cea54568b3db1541615851210/EditorServices.log' -SessionDetailsPath '/Users/Tom/.vscode/extensions/ms-vscode.powershell-1.9.0/sessions/PSES-VSCode-11625-329905' -FeatureFlags @()
11/7/2018 7:37:40 PM [NORMAL] - Syntax Folding Provider registered
11/7/2018 7:39:40 PM [NORMAL] - Language server startup failed.
11/7/2018 7:39:40 PM [ERROR] - The language service could not be started: 
11/7/2018 7:39:40 PM [ERROR] - Timed out waiting for session file to appear.
```

Unfortunately, there is no more output.

**Comment by TylerLeonhardt** [comment]
@azureandbeyond are you opening the log folder and copying that or copying the contents of the `Output` tab at the bottom of VSCode?

**Comment by rjmholt** [comment]
@azureandbeyond If you use <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and type "powershell logs" and select "Open PowerShell Logs Folder" it should open the log folder of the PowerShell extension. Do you see any other logs there?

**Comment by azureandbeyond** [comment]
@rjmholt unfortunately not. There only is "Open PowerShell _Extension_ Logs Folder" and it contains exactly the same log content I've posted above.

**Comment by rjmholt** [comment]
Yep that’s the command — missed a word there.

It looks our usual options aren’t available then.

If that’s the only file in the logs folder then the failure is probably pretty early and there’s a good chance it’s in `Start-EditorServices.ps1`.

Try putting a `Wait-Debugger` in there and tracing through.

**Comment by azureandbeyond** [comment]
After purging all elements and re-installation VSCode and the PS extension everything seems to work, again. Not sure what it was but for now I'm fine.

Thank you for your effort.
