### ISSUE TITLE
Please do not use `vscode` in the `dependencies` section of `package.json`

### ISSUE THREAD

**Issue by alexandrudima** [PowerShell/vscode-powershell#1604]
The `vscode` npm module contains some helper stuff which can download vscode for testing purposes if you use continuous integration, which can download the `vscode.d.ts`, but which also drags in a lot of dependencies. The `engines` field is the place which captures that this is a vscode extension and it is enforced at runtime.

Using `vscode` in the `dependencies` section leads to a lot larger extension size (for no good reason).

The correct place to put it is in `devDependencies`.

**Comment by rkeithhill** [comment]
Thanks for letting us know.  We'll make that switch.

**Comment by rkeithhill** [comment]
@alexandrudima Do you guys happen to have an extension that acts as a "linter" for VSCode extensions?

**Comment by alexandrudima** [comment]
Actually we do and it's bundled with VS Code -- https://github.com/Microsoft/vscode/tree/master/extensions/extension-editing -- we could perhaps catch this automatically.
