### ISSUE TITLE
PowerShell extension 0.5.0 error in VSCode 1.0 w/o admin

### ISSUE THREAD

**Issue by OtterKring** [PowerShell/vscode-powershell#161]
As discussed previously on Twitter:
I have VSCode 1.0 on Windows 10 with PowerShell 0.5.0. If I start it "as admin", no problems, if I start it "as user" I get "The language service couldnot be started: Error: spawn UNKNOWN".

I was instructed to turn on verbose logging using...
"powershell.developer.editorServicesLogLevel": "Verbose"

Where do I set this?

**Comment by daviwil** [comment]
Click `File -> Preferences -> User Settings`.  Two editor panes will now appear, type that string into the one on the right (but don't include the ending comma, that was my mistake).  After you save that file, restart VS Code and open a PowerShell file.  After you see the error, post the following file to this issue:

`c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell-0.5.0\bin\EditorServices.log`

**Comment by OtterKring** [comment]
No EditorServices.log file appears. :-( User settings were save correctly, no typos found.

**Comment by daviwil** [comment]
In that same `bin` directory, what happens if you directly launch `Microsoft.PowerShell.EditorServices.Host.exe`?  Does it crash, or does an empty console window appear and hang around for a while?

**Comment by OtterKring** [comment]
Does the extension execute any code from the profile? Our user accounts are locked down to only execute programs from %programfiles% or %...(x86)%.

**Comment by OtterKring** [comment]
LOL! Guess I just unswered your question. :-)

**Comment by daviwil** [comment]
Yep ;)  Sounds like that's the problem.  Good to know!  I didn't know that this was a possibility.

**Comment by OtterKring** [comment]
-> AppLocker

**Comment by OtterKring** [comment]
ok, then I will have to stick to starting it as admin for now.

Off topic ... do you know if there is a possibility to print from VSCode?

**Comment by daviwil** [comment]
I haven't heard of any plans to add it and I don't see a user request.  Maybe you can file an issue here:

https://github.com/Microsoft/vscode/issues

I'll go ahead and close this issue for now since we've uncovered the source of the problem.  Thanks for the report!

**Comment by OtterKring** [comment]
Thanks for your help!
