### ISSUE TITLE
No option to restart session in some instances

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1614]
### Issue Description

There are times that PowerShell session will crash. Normally you can restart it but there are instances where it won't allow you too. 

![image](https://user-images.githubusercontent.com/15063294/48674939-73f3c000-eb52-11e8-9dd3-e9b84f4e3f73.png)

The status in the bottom:

![image](https://user-images.githubusercontent.com/15063294/48674952-a8677c00-eb52-11e8-9c67-eccc18d73e19.png)

Most likely it happens when you are told that session crashed, it asks you if you want to restart it, you respond no, and there is no option to "start" it again. 

#### Expected Behaviour

Ability to restart the session, always.

**Comment by TylerLeonhardt** [comment]
`Ctrl` + `Shift` + `P` -> "PowerShell Restart Session" or something similar is what you want.

**Comment by PrzemyslawKlys** [comment]
Right, but that's how it normally looks like:

![image](https://user-images.githubusercontent.com/15063294/48675731-f4b7b980-eb5c-11e8-994e-3fc4c21569a4.png)

I'm just reporting this for consistency reasons. I can use workarounds, keybindings but still, GUI fix would be cool? ;-)

**Comment by TylerLeonhardt** [comment]
Oh interesting. I see so it doesn't show `Restart Current Session` when you click on "Session Exited" at the bottom. Yeah that seems like a bug.

Of course... It shouldn't crash... But that's a different story.

**Comment by PrzemyslawKlys** [comment]
I noticed it crashes a lot if you delete a file outside of session and recreate it, especially if a recreated file has errors in it. I'm currently playing with dynamic .psd1/.psm1 building and I have those files open and during the process, the file is deleted, and then recrreated and further modified outside of VSCode. It would very often crash if something was wrong with it (for example a wrong amount of **,** or so. But my guess is that it suddenly loses track of what the file had in comparison to what it has now.

**Comment by rjmholt** [comment]
Looks like the logic for this is here:
https://github.com/PowerShell/vscode-powershell/blob/2a282b178ec3f9a1608b3e5a48a0cc6c0d150850/src/session.ts#L738-L765

If it's a valid thing to do, perhaps we should just always add the restart option?

**Comment by rjmholt** [comment]
Ok we think the `powershellItems` concat line should be under `if (status == SessionStatus.Running)` and the restart option should be at the bottom, outside the `if` statement.

**Comment by PrzemyslawKlys** [comment]
Thanks! :-)
