### ISSUE TITLE
"ISE compatibility mode" on first startup

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#1620]
### Summary of feature

Users familiar with or migrating from the ISE often find VSCode unintuitive, difficult or lacking in features. Often this is something we have already addressed, but requires configuration, which is hard to discover. While we should document these configurations better, that doesn't help out-of-box experience.

We should provide a dialogue at first startup to offer setting all the various configurations to be "ISE-compatible". We should try and list in this issue all the settings that should be set and how by such a mode.

**Comment by helplessJ** [comment]
ISE type intelisense tab completion
"editor.tabCompletion": "on"

**Comment by rjmholt** [comment]
Yeah, I think a good first step here would be to add a new doc [here](https://github.com/PowerShell/vscode-powershell/tree/master/docs) about ISE compatibility configuration. That would also be much easier for community contributions.

While that happens, we can use it as a blueprint for a longer-term ISE compatibility startup config.

**Comment by timoline** [comment]
Why not providing a user settings file by default?

`
{
    "workbench.colorTheme": "PowerShell ISE",
    "window.zoomLevel": 0,
    "powershell.powerShellExePath": "c:/Program Files/PowerShell/6/pwsh.exe",
    //"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\6\\pwsh.exe",
    "powershell.integratedConsole.showOnStartup": true,
    "powershell.integratedConsole.focusConsoleOnExecute": false,
    "powershell.startAutomatically": true,
    "powershell.enableProfileLoading": false,
    "powershell.scriptAnalysis.enable": true,
    "powershell.developer.editorServicesLogLevel": "verbose",
    "powershell.codeFormatting.openBraceOnSameLine": false,
    "powershell.codeFormatting.newLineAfterOpenBrace": true,
    "editor.tabCompletion": "on",
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "editor.formatOnPaste": true,
    "files.autoSave": "afterDelay",
    "files.defaultLanguage": "powershell",
    "window.menuBarVisibility": "default",
    "telemetry.enableTelemetry": false,
    //"terminal.integrated.rendererType": "dom"
}
`

**Comment by timoline** [comment]
Hi Robert,
I understand the "problems" my question could give

But i'm asking this as a user.
My question was just a functional question, andI just want to have a good old ISE experience
It took me hours to get this old ISE experience, I can imagine how many people is looking for this.

**Comment by rjmholt** [comment]
No no, understood that the desire is there and we want to do what we can.

GitHub issues for us are just as much for work tracking and design discussions as registering feedback and suggestions -- you're now looped in on the ugly sausage-making steps.
