### ISSUE TITLE
PowerShell extension stuck at "Starting PowerShell.."

### ISSUE THREAD

**Issue by compwiz32** [PowerShell/vscode-powershell#1626]
## Issue Description ##

I am experiencing a problem with PowerShell extension. I have checked issue #752 and I am confident that the fixes in that bug report are applied.

The PowerShell extension hangs when the second terminal (PowerShell Integrated Console) starts. It never times out and it never crashes, it just stays stuck at "Starting PowerShell..."

I have noticed the issue on another PC in my org so I am wondering if it is an issue with our image build with our laptops but... I can't get anything to show in the logs, so I am stuck trying to figure out what is hanging the extension up. 

I enabled diagnostic mode but it doesn't seem to have caught any additional info. 

## Attached Logs ##

[Start-EditorServices-EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2640035/Start-EditorServices-EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/2640036/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2640038/EditorServices.log)

### Visual Studio Code ###
1.29.1
bc24f98b5f70467bc689abf41cc5550ca637088e
x64

| Name | Version |
| --- | --- |
| Operating System | Windows 10  1709|
| VSCode | 1.29.1|
| PowerShell Extension Version | 1.9.0 |

### PowerShell Information ###

PS C:\Scripts\Git-Repo\PS-ADHeath> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.16299.666
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.666
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Visual Studio Code Extensions ###

AlanWalk.markdown-toc@1.5.6
CoenraadS.bracket-pair-colorizer-2@0.0.25
formulahendry.code-runner@0.9.5
gerane.Theme-Blackboard@0.0.2
in4margaret.compareit@0.0.2
jprestidge.theme-material-theme@1.0.1
mdickin.markdown-shortcuts@0.9.0
ms-vscode.PowerShell@1.9.0
ms-vscode.wordcount@0.1.0
PKief.material-icon-theme@3.6.1
shd101wyy.markdown-preview-enhanced@0.3.11
streetsidesoftware.code-spell-checker@1.6.10
yzane.markdown-pdf@1.2.0
yzhang.markdown-all-in-one@1.7.0

</details>

**Comment by rkeithhill** [comment]
Can you change the `"powershell.developer.editorServicesLogLevel"` setting to Diagnostic in your user settings and repro this again and attach that EditorServices.log file?  That should provide a lot more detail during startup.

**Comment by compwiz32** [comment]
Hi @rkeithhill 

I had enabled that prior to the first upload. I just went back through the logs and can't find anything that jumps out. I am going to attach two zips: the last two launches of VSCODE in case I am missing something really obvious.

```
{
    "editor.minimap.enabled": false,
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Blackboard",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "powershell.powerShellExePath": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "files.associations": {
        "*.ps1": "powershell"
    },
    "powershell.enableProfileLoading": true,
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": true,
    "files.trimTrailingWhitespace": true,
    "breadcrumbs.enabled": false,
    "powershell.integratedConsole.showOnStartup": false,
    "powershell.developer.editorServicesLogLevel": "Diagnostic"

}

```

[1543850094-c1b1601a-e9ac-4afd-afe2-46fa771a60f31543850083161.zip](https://github.com/PowerShell/vscode-powershell/files/2640316/1543850094-c1b1601a-e9ac-4afd-afe2-46fa771a60f31543850083161.zip)
[1543854564-4b234fa9-b485-4a84-af31-946de20c890b1543854525112.zip](https://github.com/PowerShell/vscode-powershell/files/2640317/1543854564-4b234fa9-b485-4a84-af31-946de20c890b1543854525112.zip)

**Comment by rkeithhill** [comment]
Doh!  Not much of anything to go on there. Can you check the EventViewer on Windows.  See if there is any error related to PowerShell in the Application log around the time it crashes/terminates. If you see nothing there, check the `Windows PowerShell` log here:

![image](https://user-images.githubusercontent.com/5177512/49387788-f9917700-f6df-11e8-8a59-f9745ba77cb9.png)

**Comment by compwiz32** [comment]
I'll check now... the problem is that I don;t think the extension ever crashes. it just sits at starting powershell, the only real issue I have notified is not being about to debug. 

Looking at Event Viewer now...

![image](https://user-images.githubusercontent.com/16006392/49387907-f5218a00-f6f0-11e8-92b6-790c3f00b615.png)

**Comment by compwiz32** [comment]
nothing in the logs other informational stuff.  :(  Frustrating how little I have to go on here.

**Comment by SydneyhSmith** [comment]
@compwiz32 Is the device you are using, restricted or locked down in anyway, for example with Group Policy?
We are also releasing a new version of the extension this week, lets see if that helps this problem at all

**Comment by compwiz32** [comment]
@SydneyhSmith My hunch going into opening this thread was that, yes, my issue is environment specific. Yes, I have a decent amount of GPO's and defense industry lock-downs (but not too bad). I am cool waiting for the next version.

However, I am frustrated that I can't seem to generate an error that would point me in the direction of where the error may lie. Other than switching from diagnostic to verbose logging, anything else I could try to possibly highlight where my issue may be?

**Comment by rjmholt** [comment]
If you're able to edit the `Start-EditorServices.ps1` script (should be at `$HOME\.vscode\extensions\ms-vscode.powershell-1.9.0\modules\PowerShellEditorServices\Start-EditorServices.ps1`) you might be able to put `$ErrorActionPreference = 'Stop'` at the top. That script imports the PowerShellEditorServices module, uses `Add-Type` to bring in the required DLLs for the platform, and calls the entry API to start EditorServices within the PowerShell process it starts up. You can find all those bits [here](https://github.com/PowerShell/PowerShellEditorServices/tree/master/module/PowerShellEditorServices).

If you can see any other possibilities for logging in [Start-EditorServices.ps1](https://github.com/PowerShell/PowerShellEditorServices/blob/master/module/PowerShellEditorServices/Start-EditorServices.ps1), let us know as well.

I've seen one or two of these mysterious failures now, where I'm really not sure what's causing the issue. The fundamental problem is that we have a client/server architecture, so when the server doesn't reply, the client doesn't know what's failed.

**Comment by rjmholt** [comment]
Another thought I've had: it may end up that the script is not "failing" just blocked forever on something. If so, it might be possible to put a `Wait-Debugger` in the top of the script and then step through one line at a time in the Integrated Console with `s`.

**Comment by SeeminglyScience** [comment]
@compwiz32 

This looks sort of similar to when something is blocking `nodepty.exe`.  Are you able to specify which anti-virus you are using?  I know someone reported needing to white list it within McAfee, though that may have been an internal rule set.

**Comment by TheoNordstrom** [comment]
I do have same problem with PowerShell Extension in VSCode. At first, the editor would not start because it could not find 'api-ms-win-core-sysinfo-l1-2-0.dll' - I found a workaround - see #1633 

If a debug session run until end of script, the debugger will not start on 2nd run. If I break and stop the debug session, then a 2nd debug session works fine.
The problem starts this morning after reload of vscode to
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by darkocobe** [comment]
I have exactly same problem since 1.10 update. Didn't had this problem before. Did you already found any solution/workaround or we need to wait until next release?

**Comment by TylerLeonhardt** [comment]
Can everyone here try this workaround:
https://github.com/PowerShell/vscode-powershell/issues/1633#issuecomment-444814977

**Comment by rjmholt** [comment]
See https://github.com/PowerShell/vscode-powershell/issues/1633#issuecomment-444955893 for the DLL to download

**Comment by compwiz32** [comment]
> @compwiz32
> 
> This looks sort of similar to when something is blocking `nodepty.exe`. Are you able to specify which anti-virus you are using? I know someone reported needing to white list it within McAfee, though that may have been an internal rule set.

My A/V: Symantec AV
I took a good look through the AV logs and don't see anything pointing to a file block. 

FYI - v1.10.0 made no difference for me and I did import the new DLL listed in #1633 as directed by @TylerLeonhardt 

I am working through @rjmholt suggestions now re ErrorAction Stop and Wait-Debugger. I'll comment after testing. I also believe that this probably a case of "just blocked forever on something" rather than a bug.

**Comment by compwiz32** [comment]
@rjmholt 
I found a workaround that has temporarily solved my issue... I went back to the system version of VSCODE and success!!!

So this tells me that we have a permissions issue somewhere. Our laptops have some "unique" lockdowns so I am not sure how to troubleshoot that... Any ideas? 

![image](https://user-images.githubusercontent.com/16006392/49613516-c10acb00-f975-11e8-98d2-8b891ee0a598.png)

**Comment by rjmholt** [comment]
@compwiz32 That's excellent. I'm following up now to see if there are any ways in general to do something like turn one of these hangs into a crash or something similar.

**Comment by compwiz32** [comment]
@rjmholt 

Maybe I can save you some time. I know of issues we have had in the past due to security requirements that block us from interacting with the "Windows Store". If you can think of any reason why VScode may be waiting for an answer from an online MS service, that may be the issue here. 

I say that knowing that there should not be any talk to an online service just to load a language but throwing it out there as a remote possibility. I will put into place whatever you might come up with for a future test.

**Comment by rjmholt** [comment]
So after looking into this, it looks like there are a couple of avenues to explore:

1. [Open an issue on VSCode](https://github.com/Microsoft/vscode/issues/new/choose), since it seems that there is something in their User-build preventing startup from occurring properly. They have had funny network-based hangs in the past.
2. In Task Manager, look for VSCode and you should be able to find it and its child processes. Create a dump file of powershell.exe or pwsh.exe as well as a dump of VSCode and send it to us (it may have some private information in it depending on your program, so send it to vscode-powershell@microsoft.com if you're not sure.

**Comment by compwiz32** [comment]
Can I run the user and system versions side by side?

**Comment by rjmholt** [comment]
[Looks like side-by-side is possible](https://github.com/Microsoft/vscode/issues/56260) although you might get warnings about it.

**Comment by darkocobe** [comment]
For me nothing helped. I tried all kind of things and I was already running system version. I tried also user version but same issue with 1.10 version. I finally gave up and uninstalled 1.10 and returned back to 1.9 which works perfectly fine. If you have any updates please inform me so I can test.

**Comment by pdahlgren** [comment]
I had the same problem and noticed that I had a deleted folder in my vscode workspace. After I removed this folder from the workspace everythin was working fine.

**Comment by compwiz32** [comment]
Hello gents... i am back again...
I am still suffering from this issue.... It went away after a system install months ago and then came back a very short while after (like maybe next reboot). I was just dealing with it until I got fed up today. I reinstalled the user version and I am still hung at "Starting PowerShell..."  I am attaching the **editorservices.log** and the **vscode-powershell.log** files with the hope that maybe they will reveal something i haven't noticed, but there isn't much in there... 




[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/2997833/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2997834/EditorServices.log)

**Comment by compwiz32** [comment]
I am wondering if there's a permissions issue where the pipe points to. Is there a way to figure out where a pipe is on my machine?

**Comment by zachmerrill** [comment]
Just found this thread, I'm running into the same problem on my `work` machine. It seems to hang on the line 

> 3/22/2019 3:27:02 PM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_untqesdw.qj4...

Also, my PowerShell window pops out (it's not integrated). This was working when I first tried it, but stopped a few hours later. It's a shame because this extension is extremely useful for my PowerShell development.

**Comment by zachmerrill** [comment]
@compwiz32 I was able to solve my problem by installing PowerShell Core (https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6) with administrator permissions and then changing the `Power Shell Exe Path` in vscode to point to it.

It now starts up correctly! Maybe this will work for you as well :)

**Comment by compwiz32** [comment]
@zachmerrill so are you saying you installed PSCore and then in VSCODE pointed the PS executable path to PSCORE  PS Exe ? 

Just very interesting but I wonder what changes for your everyday PS experience?

**Comment by zachmerrill** [comment]
@compwiz32 Correct. I now have two versions of PowerShell installed (PSCore and the version preinstalled on my system). I only use PSCore for the VSCode extension, so it shouldn't affect my day to day too much. 

Here's the things I tried if you're interested...

1. I modified the pipe location in the extension script `Start-EditorServicesHost.ps1` but this didn't have any effect. 
2. I then tried to run `Start-EditorServicesHost.ps1` manually in a terminal and got the following error:
`The specified module 'PowerShellEditorServices' was not loaded because no valid module file was found in any module directory.`
3. After searching, I found this doc online https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-6#installing-the-powershell-extension-on-restricted-systems
But this still didn't work for me...
4. As a final effort I installed PSCore and that worked! 

Good luck :)

**Comment by rjmholt** [comment]
After discussing this a bit more, it seems that different people reporting this issue have different configurations and may not all be experiencing the same problem.

Certainly it seems like there may be a problem with the User-version of VSCode -- so for now I'd recommend trying the system version.

Given that this seems to be machine-setup specific but that we've been unable to reproduce it ourselves, I think the best way forward at this point is:
- For anyone hitting this issue, try to record all the configurations and steps that occurred before the startup hang (what VSCode you have, which PowerShell, any permissions or GPO settings you might have) and report here
- For us, see if we can improve the logging in the startup script, since we don't seem to be logging enough information to diagnose this yet.

**Comment by compwiz32** [comment]
ok... i am sort of embarrassed to share what has worked for my issue. First, a little background...

just setup a new laptop and had the same issue as old laptop (hung up on "Starting PowerShell"). However, I didn't even get to install the apps that I thought might be fouling up the program (Anti-virus, etc). I ran vscode non domain-joined and had no issues, then I ran it after domain joined and i started getting this "Starting PowerShell" nonsense again...

Started thinking about it. Did I ever try running VSCODE by right-clicking and **running as administrator**? No, I haven't... gave that a whirl and my starting PowerShell issue goes away EVERY TIME I test....

The only reason I thought of this was because I had to do that like 10x today setting up new laptop. otherwise, i don;t normally run apps that way... 

So the question is why? My guess is that my corp locked the environment and we must have a security setting in place that is preventing the PowerShell terminal to create temp file or something along those lines due to non-elevated status. To eliminate having to right click and run each time, I browsed to the EXE and checked off the "run as administrator" check box under compatibility just to save me some clicks... and so I could call the EXE if need be and have it run correctly. 

I am going to test this on my old laptop which is also domain joined and suffering the same issue but i cant do that until i return to the office. I'll follow up after testing on old laptop.

**Comment by compwiz32** [comment]
Just tested this on my old laptop and my suspicions have been confirmed. Running VSCODE as Administrator solved the issue on my old laptop as well. Again, i did not need to do this on a standalone desktop. I only had to do this once I joined my company's domain. This leads me to believe that we locked down some settings that interfere with the starting of the PowerShell extension.

**Comment by sdsalyer** [comment]
I found that Comodo Internet Security Premium was creating this issue for me. It can be corrected by going to Settings -> Advanced Protection -> Script Analysis, then find powershell.exe in the list and toggle off Heuristic Command-Line Analysis -> click OK.

Hope this helps!

**Comment by rjmholt** [comment]
> This leads me to believe that we locked down some settings that interfere with the starting of the PowerShell extension.

@compwiz32 I know it's been a while, but if you were able to identify what settings were causing this, that might help us to fix the underlying problem here

**Comment by PorkyProgs** [comment]
Hi *,
The hot tip from @compwiz32 worked for me. I already had Powershell 6.0 installed and was experiencing the hanging intergrated terminal issue.
I closed VS Code & installed Powershell 7.0 restarted VS Code & all is working now for me.
So it would appear that installing Powershell again straightens something out that the Extension bends. Just for the Brains among you, upon uninstalling the PowerShell preview extension, also resolved the problem, but of course I did not have the all singing & dancing integrated terminal any longer.

Thanks for the Tip
Porky

**Comment by compwiz32** [comment]
> > This leads me to believe that we locked down some settings that interfere with the starting of the PowerShell extension.
> 
> @compwiz32 I know it's been a while, but if you were able to identify what settings were causing this, that might help us to fix the underlying problem here

@rjmholt  I wish i knew what the issue was.... but i don't have any more info to share on that issue.

**Comment by venkat1017** [comment]
I had the same issue and found the installing extension version back to v2020.1.0 solves the issue but cannot use the latest v2020.6.0

**Comment by yuvarajselva** [comment]
Even I had the same problem with the extension version. Downgrading to v2020.1.0 helped me! 👍

**Comment by kristianBirkThim** [comment]
Hi everyone. I just wanted to mention that I solved this by installing PowerShell 7.1, so that VS code "booted" with 7.1 and then I switched back to 5.1 and it worked fine.

**Comment by nashiooka** [comment]
FYI previous advice from @kristianBirkThim worked for me too. I believe the problem started after upgrading to 1.511 with extension version 2020.6.0.

**Comment by M-Pixel** [comment]
I was able to resolve this issue by upgrading from PowerShell Core 6 to 7, but it was a wild guess.  The error reporting and resiliency still need a lot of work.

**Comment by nashiooka** [comment]
Sorry but I'm still having this issue. At first it seemed like it went away after formally installing PowerShell 7.1, then switching back to 5.1, but I can't seem to completely shake it.  Seems like it particularly occurs when I'm using a second or third window.  However it's not consistent. I just updated to 1.53 and that seemed to fix it for the 2 windows I had, but I just opened a 3rd and it's back.

**Comment by Curtisbrinkman** [comment]
I had this issue on my Mac and updating PowerShell using these instructions fixed it: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2

I ran: `brew install --cask powershell`

Reloaded visual studio and it started working again.

**Comment by schnajberkp** [comment]
Same thing happened to me, I tried almost everything you said.
But to fix the issue for me, it was actually needed to not install Powershell through the .msi but through CMD.
winget install --id Microsoft.Powershell --source winget
winget install --id Microsoft.Powershell.Preview --source winget
Now im able to run PS1 scripts in VS Code

**Comment by yudindm** [comment]
I run into this issue after I updated PowerShell from 7.1 to 7.3.

I have configured VS Code to use Windows PowerShell because it's my default target
`"powershell.powerShellDefaultVersion": "Windows PowerShell (x64)"`

But sometimes I use PowerShell 7 for some experimental work, so I have PowerShell 7 installed on my machine.

All works correctly when I change powerShellDefaultVersion to "PowerShell (x64)" or uninstall PowerShell 7.

**Comment by benblank** [comment]
Changing the execution policy for the local machine worked for me, too. I did note, however, that my non-administrator user account had its own execution policy, which overrode the local machine's. All I had to do to fix that was to unset it (as the non-administrator user).

```powershell
Set-ExecutionPolicy -ExecutionPolicy Undefined -Scope CurrentUser
```

**Comment by andschwa** [comment]
Hey @compwiz32, I know this issue is from 2018. Is it still reproducing for you? I'm going to mark as "needs feedback" so it will auto-close in a week if I don't hear back from. For other users posting, if you are having problem today, please file a new issue so we can get back to you. Thanks all!

**Comment by compwiz32** [comment]
Hi guys! I apologize. I thought I closed this issue a long time ago. I do remember this issue and do remember that future builds fixed my issue. definitely no lingering issues...

**Comment by andschwa** [comment]
Yay, glad to hear that! Thanks for the follow-up.
