### ISSUE TITLE
(Get-Item -Path ".\").Name doesnt return .ps path 

### ISSUE THREAD

**Issue by guidorobben** [PowerShell/vscode-powershell#1629]
### System Details

System Details Output
```
VSC: 1.29.1
PS: 1.9.0

Name                           Value
----                           -----
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with the command (Get-Item -Path ".\").Name

#### Expected Behaviour

If I run this in WP ISE, I get the path of .ps1 file. This is what I want to have,

#### Actual Behaviour

What happens in VSC, I get the user folder. The Output is not the same. I looks like the file is in a temp folder and it is returning that folder instead of the folder where the .ps1 file is actually located.

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by rjmholt** [comment]
Hi @guidorobben, thanks for opening an issue.

Some follow up questions:
- Can you provide a small repro script?
- Is this occurring in the interactive terminal or in your PowerShell script?
- Is this a local or a remote session?
- Does this issue occur in PowerShell without an editor?

**Comment by guidorobben** [comment]
Hi @rjmholt 

    _Can you provide a small repro script?_ 
Sure. See script
[GetPath.zip](https://github.com/PowerShell/vscode-powershell/files/2662663/GetPath.zip)

 _Is this occurring in the interactive terminal or in your PowerShell script?_
Just a .ps1 script on local HDD

_Is this a local or a remote session?_
Local c:\

_Does this issue occur in PowerShell without an editor?_
just running the script works fine. Running it in PS IDE goes fine. Running it in VSC goes incorrect.

I use this to get the foldername the ps file is in. It contains a version no. I use in filename I am generating.

**Comment by rjmholt** [comment]
Have you tried using `$PSScriptRoot` instead?

```powershell
Write-Output $PSScriptRoot
```

**Comment by rjmholt** [comment]
`Get-Path "."` will return the location of the executing PowerShell session, not the script.

**Comment by guidorobben** [comment]
Thanks Robert. This seems to work. 

But it does have a issue. If you test the $PSScriptRoot value in ISE or VSC, the value is empty unless you run the script from explorer. So pressing F8 on the line _Write-Output $PSScriptRoot_ gives no result.  But I think this is more of a issue with powershell than then Extenssion
