### ISSUE TITLE
Add support for drop down auto completion for commands and parameters in the PowerShell Intergrated Console

### ISSUE THREAD

**Issue by jessekirk** [PowerShell/vscode-powershell#1637]
I'd like to request support for a drop-down menu auto completion of commands and parameters in the PowerShell Integrated Console. 

[Image - Example of drop down menu auto completion in the console](http://www.powertheshell.com/wp-content/uploads/2012/10/argumentcompletion3.png)

**Comment by rjmholt** [comment]
Hi @jessekirk, we're currently engaging in work to bring PSReadLine to the Integrated Console.

PSReadLine has menu completions, enabled by:

```powershell
 Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
```

These wouldn't work with a mouse, but would with the <kbd>Tab</kbd> key.

You can try this out in PowerShell today by executing the PowerShell above and pressing <kbd>Tab</kbd> to complete.

Would that work for you?

**Comment by rjmholt** [comment]
My concern is that adding new UI features like this is something we are probably not able to do, since VSCode controls the UI -- we are only able to embed text in the console window. However, depending on how you respond, we can possibly investigate further.

**Comment by jessekirk** [comment]
The tab function will work, but it would be easier to see a visual drop down of all the commands/parameters available in the console. If this feature is not something that can be added that's understandable since the UI is controlled by VSCode. Thank you for looking into it.

**Comment by rjmholt** [comment]
@jessekirk `MenuComplete` will give a drop-down, but you just won't be able to click on it. You should run the code I posted above in your PowerShell console (not the Integrated Console) and play with it to see if you like it.

**Comment by rjmholt** [comment]
Looks like this:
![vscode-ps-saveas](https://user-images.githubusercontent.com/7009879/49613798-551c6880-f95d-11e8-9109-7a4834fd332a.gif)

**Comment by jessekirk** [comment]
Got it. That will work for me. I wasn't executing the command in the PowerShell console itself, only in VSCode PowerShell Console. Thanks!

**Comment by rjmholt** [comment]
Ok awesome. Here's the issue: https://github.com/PowerShell/vscode-powershell/issues/535. Obviously it's been a long time in the making, but you should be able to follow along with our progress there.
