### ISSUE TITLE
Error using Command Explorer

### ISSUE THREAD

**Issue by detlefs** [PowerShell/vscode-powershell#1639]
With the latest version that introduces the PowerShell Command Explorer, whenever I click on Refresh in that panel, I get the following output:

12/7/2018 10:16:21 AM [ERROR] - <GetCommandsFeature>: Unable to instantiate; language client undefined.

**Comment by rjmholt** [comment]
Hi @detlefs, thanks for opening an issue.

This is a community-contributed feature. We are always happy to accept PRs to improve features.

/cc @corbob.

**Comment by SydneyhSmith** [comment]
@detlefs thanks for the issue, this is a community developed feature and we would happily accept any PRs to enhance/fix this issue. Please also attach the logs, find troubleshooting [here](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs).

cc\ @corbob

**Comment by corbob** [comment]
I would be very much interested in logs or reproduction steps for this. We initially check for the language client since we need it to do things. If it's undefined we error out. Unfortunately it's not something I was ever able to actually get to happen.

**Comment by detlefs** [comment]
When the error message pops up and I click on "Show logs", I get this:
12/13/2018 3:46:59 PM [NORMAL] - Visual Studio Code v1.29.1 64-bit
12/13/2018 3:46:59 PM [NORMAL] - PowerShell Extension v1.10.1
12/13/2018 3:46:59 PM [NORMAL] - Operating System: Windows 64-bit
12/13/2018 3:47:03 PM [ERROR] - <GetCommandsFeature>: Unable to instantiate; language client undefined.

If you need more details from other logs, please point me to the needed files and I'll provide them.

Reproduction for me is easy:
I start VSCode, open a ps1 file, show the command explorer (initially empty), then click on the Refresh button. Next, the error popup is displayed

**Comment by corbob** [comment]
Have you set the logging to be Verbose or Diagnostic as per https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs ?

Which version of Windows are you using?
When you type a command in the ps1 file, what happens when you select it and press `Ctrl+F1` (or right click and choose "Get Help for Command")?

**Comment by detlefs** [comment]
Sorry for the delay. I'm quite busy until end of the year.
I have tested with verbose and diagnostic setting and also tested the Ctrl-F1 kommand on a selected Powershell command.
The resulting log though, is not much more comprehensive:
12/20/2018 1:42:23 PM [NORMAL] - Visual Studio Code v1.30.0 64-bit
12/20/2018 1:42:23 PM [NORMAL] - PowerShell Extension v1.10.1
12/20/2018 1:42:23 PM [NORMAL] - Operating System: Windows 64-bit
12/20/2018 1:42:28 PM [ERROR] - <GetCommandsFeature>: Unable to instantiate; language client undefined.
12/20/2018 1:43:11 PM [ERROR] - <ShowHelpFeature>: Unable to instantiate; language client undefined.
12/20/2018 1:43:18 PM [ERROR] - <GetCommandsFeature>: Unable to instantiate; language client undefined.

I'm using Windows 8.1 64-bit, withg Powershell updated to 5.1:
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by corbob** [comment]
OK, I think I see why I didn't see the `<GetCommandFeature>` in your previous comments. It appears to have put it in as an HTML tag (or something, I'm not actually seeing it on the page). I'll try to track down a Windows 8.1 install media (I think I have some through VLSC or MSDN or something).

Some other information that might prove helpful in tracking down the issue is running this from the Integrated Console (although it appears PSIC isn't initializing as I don't see it in the log you submitted): 

```
& {"### VSCode version: $(code -v)"; "`n### VSCode extensions:`n$(code --list-extensions --show-versions | Out-String)"; "`n### PSES version: $($pseditor.EditorServicesVersion)"; "`n### PowerShell version:`n$($PSVersionTable | Out-String)"}
```

(the output of the above can be copy pasted into the comment window without worry of formatting)

As an aside, there is now 1.10.2 out, you could try it with that.

**Comment by corbob** [comment]
So I've got my 8.1 VM updated to what appears to be the same version. When I launch vscode I get this when Diagnostic logging is enabled:

```
12/21/2018 1:59:32 PM [NORMAL] - Visual Studio Code v1.30.1 64-bit
12/21/2018 1:59:32 PM [NORMAL] - PowerShell Extension v1.10.2
12/21/2018 1:59:32 PM [NORMAL] - Operating System: Windows 64-bit
12/21/2018 1:59:32 PM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
12/21/2018 1:59:32 PM [NORMAL] - Language server starting --
12/21/2018 1:59:32 PM [NORMAL] -     exe: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
12/21/2018 1:59:32 PM [NORMAL] -     args: C:\Users\tester\.vscode\extensions\ms-vscode.powershell-1.10.2\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.10.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\tester\.vscode\extensions\ms-vscode.powershell-1.10.2\modules' -EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'C:\Users\tester\.vscode\extensions\ms-vscode.powershell-1.10.2\logs\1545429572-a2979375-0dd7-4728-a4cc-f5b4067dd36a1545429565906\EditorServices.log' -SessionDetailsPath 'C:\Users\tester\.vscode\extensions\ms-vscode.powershell-1.10.2\sessions\PSES-VSCode-916-269613' -FeatureFlags @()
12/21/2018 1:59:33 PM [NORMAL] - powershell.exe started, pid: 4016
12/21/2018 1:59:38 PM [NORMAL] - Language server started.
12/21/2018 1:59:38 PM [NORMAL] - {"languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_uenj55nb.bdh","debugServiceTransport":"NamedPipe","status":"started","debugServicePipeName":"\\\\.\\pipe\\PSES_etqvd1go.ct4"}
12/21/2018 1:59:38 PM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_uenj55nb.bdh...
12/21/2018 1:59:38 PM [NORMAL] - Language service connected.
```

This is my PowerShell Version:
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Based on the difference in output, it looks like PowerShell Editor Services isn't loading for you. Unfortunately I'm not sure where to go from that point...

**Comment by corbob** [comment]
@detlefs is this still an issue? It looks like it was resolved by removing everything and reinstalling. If that's the case, should this issue be closed?

**Comment by detlefs** [comment]
I'm closing the issue as per corbob's suggestion
