### ISSUE TITLE
Is it possible to replicate 2 "drag'n'drop" file onto a PS script in order to debug?

### ISSUE THREAD

**Issue by swinster** [PowerShell/vscode-powershell#164]
Hey All,

This is probably not the greatest place to post this as it more of a question than a feature request or bug , but I could not think where else to ask.

I want to write mainly PowerShell scripts that it be used to manipulate other files/folder. In the main, this will be a simple case of users dragging and dropping the files/folder they wish to process onto the PS script file, or use the Shell:Sendto menu. But how can I capture this action in the debugger in VSCode? 

Apologies if this is super simple answer, I am no real developer ;)

**Comment by swinster** [comment]
For reference, it does not as straight forward to achieve a Drag'n'drop to SentTo for PS script as you would do for Batch files, however you can achieve this by creating a short cut to the PS1 file, but target the PowerShell Executable and pass the PS1 script in, such as:

```C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe C:\Tools\Scripts\myscript.ps1```

**Comment by daviwil** [comment]
In PowerShell v5 there is a new cmdlet called [`Wait-Debugger`](https://technet.microsoft.com/en-us/library/dn807182.aspx?f=255&MSPPError=-2147217396) which causes your script to wait for a debugger to be attached before continuing.  However, the PowerShell extension for VS Code doesn't currently support the user of `Enter-PSHostProcess` which would be necessary to attach to the powershell.exe process that's running your script.  It'll probably take a couple more months until we get around to that.

The best thing you can do for now is design your code in a way where you can test the logic of what happens after the drag'n'drop without needing that event to occur.  Usually you'd do this by having a separate function that defines the logic for handling the dropped file and then use Pester to test the behavior of that function.

**Comment by swinster** [comment]
Thanks @daviwil.... and down the rabbit hole I go ;)

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive/resolved.
