### ISSUE TITLE
PowerShell extension for VSCode Freezing after running a .ps1 file

### ISSUE THREAD

**Issue by msurasky** [PowerShell/vscode-powershell#1645]
### System Details

- Operating system name and version
Windows 10 Version 1709 (OS Build 16299.755)

- VS Code version: 
code - v
1.29.1
bc24f98b5f70467bc689abf41cc5550ca637088e
x64

- PowerShell extension version
Here are all my extensions together with the versions (where you can see PowerShell extension is at 1.10.1)
adammaras.overtype@0.2.0
alefragnani.Bookmarks@10.0.0
jpogran.puppet-vscode@0.14.0
ms-vscode.PowerShell@1.10.1
ms-vsts.team@1.144.1

- Output from `$PSVersionTable`
Here is my $PSVersionTable
PSVersion                               5.1.16299.666
PSEdition                                Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                           10.0.16299.666
CLRVersion                             4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion  2.3
SerializationVersion                1.1.0.1

### Issue Description

I am experiencing a problem with the extension. When I load my .ps1 file and hit Debug --> Start Debugging or Debug --> Start without Debugging I sometimes see that VSCode "freezes". The state at which is freezes is when you have the little window on top with the Stop/Pause/Play buttons for the debugger and the little animation of a line moving on the top/left corner of the IDE

![2018_2019_tasks_not_found](https://user-images.githubusercontent.com/25614072/49747086-3c1afc80-fc68-11e8-95dc-75b04a911f62.gif)

After a while, I usually get the message "Debug adapter process has terminated unexpectedly (read error)"

![10-12-2018 10-27-58 am](https://user-images.githubusercontent.com/25614072/49747214-87cda600-fc68-11e8-88f8-979ee7b3af48.png)

I only manage to run the script by killing the terminal and starting again. Even if I do that, I noticed that more often than not, each other execution (#3 #5 #7, etc) freezes (this is, the "kill terminal" trick only works for one execution and the one following that freezes again).

#### Expected Behaviour

I would have expected the script to run to completion (there is nothing wrong with the script perse. I have executed it a zillion times in PowerShell IDE)

#### Actual Behaviour

As mentioned, the VSCode IDE PowerShell extension freezes

### Attached Logs

[1544458445-3a452c52-d1d8-45d0-aa8e-8af335ab7b631544457258116.zip](https://github.com/PowerShell/vscode-powershell/files/2664028/1544458445-3a452c52-d1d8-45d0-aa8e-8af335ab7b631544457258116.zip)

**Comment by rjmholt** [comment]
I've reopened https://github.com/PowerShell/vscode-powershell/issues/1634 to track this. We are looking into the issue, but it is complex.

**Comment by PrzemyslawKlys** [comment]
@rjmholt are you sure 1634 is the same thing? I've seen Debug adapter process has terminated in different circumstances.

**Comment by rjmholt** [comment]
It may also be https://github.com/PowerShell/vscode-powershell/issues/1579. But without knowing what the bug is, I'm not sure.

My feeling is that juggling a number of issues to track what will probably be fixed by a single effort is only going to confuse us. There's a weakness in the debugging part of the code that has been complex enough to go unfixed for some time and we just need to allocate time to clean it up. All these different issues will be related and if they aren't all fixed together, the remaining ones will probably change the way they are expressed anyway.

**Comment by PrzemyslawKlys** [comment]
Thanks. I will revist my issues and close some. I've not seen some of them for a while now.
