### ISSUE TITLE
Do not appear to be able to press "Shift+Alt+A" to toggle a block comment

### ISSUE THREAD

**Issue by swinster** [PowerShell/vscode-powershell#165]
However, navigating to the command via `Ctrl+P` works a treat.

**Comment by daviwil** [comment]
It's working for me, you might want to check your keyboard shortcuts settings: `File -> Preferences -> Keyboard Shortcuts`.  Two editor panes will appear next to each other.  On the left side, search for `shift+alt+a` to see if it's bound to `editor.action.blockComment`.  On the right side, make sure you don't have a setting there that can be overriding this keybinding.

If everything still looks good when you check that, you might want to file a bug on the VS Code team here: http://github.com/Microsoft/vscode/issues.

**Comment by swinster** [comment]
Thank @daviwil. Yes, all is OK this side, with nothing overridden. Will file a bug with VScode team as you suggest.

Please close this issue
