### ISSUE TITLE
Issues with Powershell DSC folding 

### ISSUE THREAD

**Issue by ewhitesides** [PowerShell/vscode-powershell#1653]
I'm seeing a lot of issues since we moved to 1.10 with folding code.  

also in regular module writing it seems like it's gets 'hung up' on select-object statements

### System Details

System Details Output
```

```

### Issue Description

I am experiencing a problem with...

#### Expected Behaviour

-- Description of what *should* be happening --

#### Actual Behaviour

-- Description of what actually happens --

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by rjmholt** [comment]
Hi @ewhitesides, thanks for the report.

This is being worked on in https://github.com/PowerShell/PowerShellEditorServices/pull/814 and https://github.com/PowerShell/PowerShellEditorServices/pull/806.

**Comment by BjornNordblom** [comment]
Not enough details to test but probably same issue as https://github.com/PowerShell/vscode-powershell/issues/1631 and thus can be closed.
