### ISSUE TITLE
Add a search field for the "Powershell Command Explorer".

### ISSUE THREAD

**Issue by ChadThomsen** [PowerShell/vscode-powershell#1656]
**Summary of the new feature**
Would be nice to have a field just below the title bar that is a search field.  That way you could put in a string of characters and only commands that match the string you are searching for would show up in the  command explorer.  I do like the Command Explorer as that is a nice feature!  Keep up the good work. 

**Proposed technical implementation details (optional)**

**Comment by TylerLeonhardt** [comment]
Glad you like it! 

vscode would have to provide us a mechanism for a search box or we'd have to do a lot of additional work to get something kind of working...

that said... one of the folks on the vscode team hinted at such a feature on Twitter:
https://twitter.com/joaomoreno/status/1073107112702685184

So for us, it's probably best we wait and see what that team does and then we get it for free/little effort 😄

**Comment by corbob** [comment]
There's a vscode issue tracking this as well: https://github.com/Microsoft/vscode/issues/50062

**Comment by moymike** [comment]
The "Todo Tree" extension does it by using a 'filter' icon on it's panel that activates the main input box in the top center on vscode.

**Comment by TylerLeonhardt** [comment]
We're going to get a filter feature very soon:

https://twitter.com/joaomoreno/status/1087365894983073793?s=19

So it might not be worth investing too much time in a custom solution. 😊

**Comment by superfliege** [comment]
+1 realy need this feature. It should also not be too hard to implement this. Thanks guys!

**Comment by corbob** [comment]
> +1 realy need this feature. It should also not be too hard to implement this. Thanks guys!

I don't think it's quite as simple to implement as you're implying. It also  might not be worth investing too much time in a custom solution if vscode is working to include the functionality for us.

That being said, if I determine I have the time, I might take a stab at something like what @moymike noted in using a filter through input box.

**Comment by superfliege** [comment]
@corbob I do not know your code structure, but adding a textbox that filters a ListView should not be that hard.

Do not get me wrong. I'm sure you're doing a good job and I'm happy about this upcoming feature.

**Comment by rjmholt** [comment]
> I do not know your code structure

Indeed.

The extension doesn't have direct control of the UI; it uses a VSCode API called [Tree View](https://code.visualstudio.com/api/extension-guides/tree-view) which we use [here](https://github.com/PowerShell/vscode-powershell/blob/master/src/features/GetCommands.ts). It just takes data and displays it, so there's no way to alter the UI to include a filter.

There's an [outstanding feature request](https://github.com/Microsoft/vscode/issues/50062) to add a filter functionality to APIs like this in VSCode and, as @TylerLeonhardt said, it looks like the VSCode team are looking to implement it.

**Comment by goyzhang** [comment]
The type-and-navigate feature has been added https://github.com/Microsoft/vscode/issues/10026
Is it possible to adapt it to this extension?

**Comment by dahifi** [comment]
I consider the PS command explorer essential for working in the ISE. Since it's been abandoned by MS, it would be nice if VSCode could implement this....

**Comment by corbob** [comment]
> 
> 
> I consider the PS command explorer essential for working in the ISE. Since it's been abandoned by MS, it would be nice if VSCode could implement this....

This is definitely being worked on. As @rjmholt  mentioned there's an outstanding feature request with vscode to ad a filter functionality. As of June 5th this was still planned, just delayed: https://twitter.com/CoryKnox/status/1135945751509504000 As for what @goyzhang mentioned, I haven't seen the type-and-navigate, so I don't know how difficult it might be for adapting to the TreeView.

**Comment by TylerLeonhardt** [comment]
@joaomoreno for visibility

**Comment by joaomoreno** [comment]
This is already implemented in Insiders using the new tree's highlight/filter functionality. Just start typing when focused in the tree. https://github.com/microsoft/vscode/issues/63566

**Comment by corbob** [comment]
Can confirm this is working for me in insiders. 😍 
![TreeViewTypeToHighlight](https://user-images.githubusercontent.com/30301021/61735019-ed722c80-ad37-11e9-84aa-857dca694bb0.gif)

Guess this means I need to get #1972 done so that this can be even more useful...

**Comment by TylerLeonhardt** [comment]
Awesome! I'm going to go ahead and close this issue since it's in insiders. Let me know if anyone feels otherwise

**Comment by filippobottega** [comment]
In my opinion type-and-navigate is not so useful because a filter is better. If you need to search "Item" for example, you can't find Get-Item, the only result is the first command with "I" as first character. Definitely not useful to search.

Thank you for your support,
Filippo

**Comment by moymike** [comment]
Yes, a "filter" would be much more useful.  Filter "item" and narrow down the list to just the commands that contain "item".  
(I'm sure there are better examples...)
