### ISSUE TITLE
Format document converting timestamp within single quotes

### ISSUE THREAD

**Issue by sk82jack** [PowerShell/vscode-powershell#1657]
### System Details

System Details Output
```
### VSCode version: 1.30.0 c6e592b2b5770e40a98cb9c2715a8ef89aec3d74 x64

### VSCode extensions:
CoenraadS.bracket-pair-colorizer@1.0.61
eamodio.gitlens@9.2.0
ms-azure-devops.azure-pipelines@1.145.1
ms-python.python@2018.12.0
ms-vscode.csharp@1.17.1
ms-vscode.PowerShell@1.10.1
ms-vsliveshare.vsliveshare@0.3.1013


### PSES version: 1.10.1.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When running format document on a script it is converting an ISO 8601 timestamp within a string to a more human-readable string.

The issue has been reproduced by someone in the PowerShell slack and if you want to try and reproduce it yourself then feel free. Script here https://github.com/sk82jack/PSFPL/blob/master/Tests/Private/ConvertTo-FplObject.Tests.ps1#L48

I am trying to copy the timestamp string from line 67 into line 48

#### Expected Behaviour

I'd expect text in quotes to not be altered.

#### Actual Behaviour

Probably best described by a gif:
![2018-12-11_18-32-28](https://user-images.githubusercontent.com/20758758/49974238-2c353e00-ff30-11e8-9f9d-7eb44677b5d2.gif)

Once it converts it it then starts being weird and reporting errors that weren't reported before:
![2018-12-13_23-45-09](https://user-images.githubusercontent.com/20758758/49974448-3f94d900-ff31-11e8-8e63-04ecd0050f66.png)

So, if I Ctrl+Z and then format again and then it doesn't convert it but it does remove the single quote from the end of line 48. I think that must be related to the previously reported errors but it still reports errors after removing the quote:
![2018-12-13_23-48-57](https://user-images.githubusercontent.com/20758758/49974534-c0ec6b80-ff31-11e8-98e6-bfe0e771c6a8.png)

So, I Ctrl+Z again and try and format again but the integrated console usually crashes at this point.

### Attached Logs

[VSCodeDiagnosticLogs.zip](https://github.com/PowerShell/vscode-powershell/files/2678180/VSCodeDiagnosticLogs.zip)

**Comment by rkeithhill** [comment]
Document formatter is provided by the PowerShell ScriptAnalyzer.   @rjmholt Do you have perms to move this issue to the PSSA repo?

**Comment by rjmholt** [comment]
No, sorry. I'll do it the old way

**Comment by rjmholt** [comment]
This issue was moved to PowerShell/PSScriptAnalyzer#1110

**Comment by rjmholt** [comment]
This is very odd. I'm struggling to reproduce it myself. Here's my script:

```powershell
Context 'Banana' {
    BeforeAll {
	$Object = [pscustomobject]@{
	    Id = 1
	    DeadlineTime = '2018-10-08T18:00:00Z'
	    AverageEntryScore = 53
	}
    }

    It "Succeeds" {
	$Object.DeadlineTime | Should -Be Exactly '2018-10-08T18:00:00Z'
    }
}
```

Both `Get-Content -Raw ./file.ps1 | % { Invoke-Formatter -ScriptDefinition $_ }` and running the formatter in VSCode seem to work for me.

However, in that full script file, this repro's using just the extension command.

**Comment by rjmholt** [comment]
I've been playing around with this. Noticed that the linked gist has the date in the converted format, so inconvenient for testing. At first I thought I'd reproed it, but realised I was just seeing what's in the actual file.

I haven't been able to reproduce this yet.
