### ISSUE TITLE
Rename lowercase functions on Format

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1659]
**Summary of the new feature**

I sometimes type functions like `get-childitem`. I sometimes copy it from Internet like that. I like my code to be nice looking. Would it be possible to rename functions to their proper case variant on Format? For example `Get-ChildItem`.

**Proposed technical implementation details (optional)**

**Comment by TylerLeonhardt** [comment]
Formatting in the PowerShell extension is provided by https://github.com/PowerShell/PSScriptAnalyzer.  I'm going to move this issue over to that repo 🙂

**Comment by TylerLeonhardt** [comment]
actually looks like I can't transfer the issue over to that repo... (tried the new "Transfer this issue" feature in github) ... can you open this feature request over there?
