### ISSUE TITLE
CodeLens - References for function not showing up after 1.10.1 update.

### ISSUE THREAD

**Issue by rishav19** [PowerShell/vscode-powershell#1660]

**Comment by SydneyhSmith** [comment]
@rishav19 thanks for opening this issue, could you please provide more information so we can figure out what is causing the issue? Check out our [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#reproducing-the-issue) for more information about helpful repros  and providing useful data about your environment. Thanks!
