### ISSUE TITLE
PS Script Analyzer custom rule is not working after VS code 1.30 upgrade

### ISSUE THREAD

**Issue by manigandan-jegannathan-developer** [PowerShell/vscode-powershell#1665]
## Issue Description ##

I am experiencing a problem with PSScriptAnlyzer extension setting path. I wrote couple of custom PS script analyzer rules which I am trying to invoke from VSCode. But it does not seems to work after I upgraded to 1.30. It was working fine with the previous version. 

ScriptAnalyzer default rules itself not working when I overwrite PS Script Analyzer setting path,

`"powershell.scriptAnalysis.settingsPath": "\\foo\bar.psd1"
`

I have the below values in the settings file. 
```
@{
    CustomRulePath      = "CustomRules.psm1"
    IncludeDefaultRules = $true
}
```

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.30.0|
| PowerShell Extension Version | 1.10.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17134.407|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.407|
|BuildVersion|10.0.17134.407|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.17.1|
|json-schema-validator|tberman|0.1.0|
|material-icon-theme|PKief|3.6.1|
|material-palenight-theme|whizkydee|1.9.4|
|Material-theme|zhuangtongfa|2.18.1|
|PowerShell|ms-vscode|1.10.1|
|team|ms-vsts|1.144.1|
|Theme-FlatlandMonokai|gerane|0.0.4|
|theme-onedark|azemoh|0.5.2|
|Theme-TomorrowKit|ms-vscode|0.1.4|
|vscode-icons|robertohuertasm|8.0.0|
|vscode-pull-request-github|GitHub|0.3.2|
|vscode-theme-darcula|rokoroku|1.1.3|
|vscode-theme-onedark|akamud|2.1.0|
|vsliveshare|ms-vsliveshare|0.3.1071|;

</details>

**Comment by rkeithhill** [comment]
You're missing in extra backslash in your settings path, should be:
```
"powershell.scriptAnalysis.settingsPath": "\\foo\\bar.psd1" 
```
Although will look for foo at the root of the current drive.  Is that what you intended?  Or did you want to look for bar.psd1 in your workspace?

**Comment by manigandan-jegannathan-developer** [comment]
@rkeithhill 

Oh sorry about that. The value which I am supplying has correct number of backslash. I really don't think I am doing anything wrong with the path, because I tried every combination. 

In fact, what I think the problem here is that VSCode is not displaying the violations on the problem pane. looks like a bug to me ? I am not sure though.

If it helps, I could see that it processes file in question & even finds the number of violations. But I don't see anything on the VSCode problems window. 

logs from EditorSevices.log
```
2018-12-20 11:31:20.272 [VERBOSE] tid:3 in 'GetDiagnosticRecordsAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices\Analysis\AnalysisService.cs: line 523
    Found 21 violations
```

**Comment by rkeithhill** [comment]
Is there a log entry a few past the one above that shows the diagnostic info being sent back to VSCode?  It looks like this:
```
2018-12-19 23:18:02.363 [VERBOSE] tid:21 in 'WriteMessage' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: line 88
    Writing Event 'textDocument/publishDiagnostics'
    
    {
      "jsonrpc": "2.0",
      "method": "textDocument/publishDiagnostics",
      "params": {
        "uri": "c:\\Users\\Keith\\.vscode\\extensions\\ms-vscode.powershell-1.10.2\\examples\\DebugTest.ps1",
        "diagnostics": [
          {
            "range": {
              "start": {
                "line": 21,
                "character": 9
              },
              "end": {
                "line": 21,
                "character": 16
              }
            },
            "severity": 2,
            "code": "PSUseApprovedVerbs",
            "message": "The cmdlet 'Do-Work' uses an unapproved verb.",
            "source": "PSScriptAnalyzer"
          }
        ]
      }
    }
```

**Comment by manigandan-jegannathan-developer** [comment]
@rkeithhill 
No, I could not find anything like that.

**Comment by rkeithhill** [comment]
Well, that right there is part of the problem. Did you find any exceptions/stack trace listings in the log file?  If you could zip and attach that log file here, it would help with the back & forth on its contents.

**Comment by manigandan-jegannathan-developer** [comment]
Can you tell me which log file you want ?

**Comment by rkeithhill** [comment]
The one you've been looking at and posting snippets from: `EditorServices.log`.

**Comment by rjmholt** [comment]
> Can you tell me which log file you want ?

https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs

Just upload a zip of the folder if you can.

**Comment by manigandan-jegannathan-developer** [comment]
@rjmholt @rkeithhill 

I have sent the log folder (zipped) to vscode-powershell@microsoft.com. Let me know if that helps.

**Comment by manigandan-jegannathan-developer** [comment]
@rjmholt @rkeithhill

Can you please acknowledge my previous update ?

**Comment by rkeithhill** [comment]
Sorry, I don't work for Microsoft so I can't access that mailbox - only @rjmholt can and a lot of US employees take off between Christmas and New Years day.  If you can attach the zip of the log files here, I can take a look at it.

**Comment by rjmholt** [comment]
I'm away for a while, but the logs have been sent through. Had a brief look and looks like the settings file is on a UNC path. What happens if you try using a local settings file?

**Comment by manigandan-jegannathan-developer** [comment]
Something weird happened. It started working from this week. I have not changed anything on the settings side.
