### ISSUE TITLE
Run `Invoke-Pester` on tests.ps1 file using right-click context menu on file tab and/or shortcut

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/vscode-powershell#1667]
**Summary of the new feature**

As a user, I quite often want to run ALL Pester tests of a `tests.ps1` file but I have either multiple `Describe` blocks or don't want to scroll up and down to run tests. I then use the `Copy Path` context menu on the file tab just to run `Invoke-Pester` on that in the console.

**Proposed technical implementation details (optional)**

If the file ends in `tests.ps1` (case insensitive lookup), then a context menu on the file tab should be there that says `Run Pester Tests` and `Debug Pester Tests` and under the hood it just calls `Invoke-Pester -Path ` with the full path of the file in the integrated PowerShell console. A keyboard shortcut for this would be cool as well.

**Comment by rkeithhill** [comment]
Fixed in the next update.
