### ISSUE TITLE
F8 key command 'PowerShell.RunSelection' not found

### ISSUE THREAD

**Issue by tommcewen** [PowerShell/vscode-powershell#1672]
Windows 10 up to date
VSCode version: 1.20.1
PowerShell Extension: V1.10.2
Selecting commands in PS1 file edit gets the error message:
command 'PowerShell.RunSelection' not found
I checked the previous postings on this subject, and nothing seems to work.
Since this just started occurring in the last couple of days after an update to PS Extension V1.10.2 I tried changing back to V1.10.1 and this fixed the problem. Then changing back to V1,10.2 the problem recurs.
So finally went back to V1.10.1 which has it working again.

**Comment by rkeithhill** [comment]
I suspect this is happening because the extension is starting properly.  Does the PowerShell Integrated Console start up successfully?  Also, are there any log files you can zip and upload for us to look at?  These need to be from a failing 1.10.2 session.  Here are the instructions on how to upload your log files:

https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs

**Comment by SydneyhSmith** [comment]
Closing, will re-open if more info is provided. Thanks!

**Comment by tmknight** [comment]
Version: 1.32.0 (user setup)
Commit: 507312a3e3b34b084b467dfd983263bc7c9d87e0
Date: 2019-03-06T18:57:55.589Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
ms-vscode.powershell-preview: v2.0.0-preview.1

Integrated console does not start.
"Command Explorer" "There is no data provider registered that can provide view data".  Refresh generates: "command 'PowerShell.RefreshCommandsExplorer' not found".

F8 generates: "command 'PowerShell.RunSelection' not found"

![2019-03-07 14 39 10](https://user-images.githubusercontent.com/548588/53984205-e333f680-40e6-11e9-8eca-4a7543fd0fd8.png)
![2019-03-07 14 39 36](https://user-images.githubusercontent.com/548588/53984215-e6c77d80-40e6-11e9-9916-7cedd28a8730.png)
I've tried uninstalling both PS extensions (yes, the stable was disabled from the start), then installing only preview to no avail.

**Comment by TylerLeonhardt** [comment]
@tmknight do you have a folder open in vscode? Or is this in an untitled workspace?

**Comment by tmknight** [comment]
Untitled workspace

**Comment by TylerLeonhardt** [comment]
This is a known issue. It's already fixed it's just pending a new release which we are shooting for next week. Stay tuned!

**Comment by tmknight** [comment]
Cheers
