### ISSUE TITLE
Variable explorer crashes with most objects from VMWare PowerCLI 10+

### ISSUE THREAD

**Issue by dt-iland** [PowerShell/vscode-powershell#1674]
Issue Type: <b>Bug</b>

Applies to VMware PowerCLI version 10+
https://www.powershellgallery.com/packages/VMware.PowerCLI

```powershell
$vCloudServer = Connect-CIServer -Server $vCloudServerFQDN -Org System -User $UserName -Password $PlainTextPassword
$Org = Get-Org -Name $OrgName -Server $vCloudServer
$OrgVdc = Get-OrgVdc -Name $OrgVdcName -Org $Org -Server $vCloudServer
$OrvView = $Org | Get-CIView
$OrgVdcView = $OrgVdc | Get-CIView
Disconnect-CIServer -Server $vCloudServer -Confirm:$false -Force:$true
```

If you attempt to expand `$Org` or `$OrgVdc` in the variable explorer, a spin-wheel turn forever next to the variable name and then eventually timeout or the variable explorer will crash the plugin and/or Visual Studio Code all together. However, the objects returned by the `Get-CIView` cmdlet expand in the variable explorer without issue. 

Extension version: 1.10.2
VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz (2 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details>

### VSCode extensions:
dbaeumer.vscode-eslint@1.7.2
eg2.tslint@1.0.42
humao.rest-client@0.20.4
ms-python.python@2018.12.1
ms-vscode.PowerShell@1.10.2
streetsidesoftware.code-spell-checker@1.6.10

### PowerShell version:

```
Name                           Value
----                           -----
PSVersion                      5.1.17134.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rjmholt** [comment]
Thanks for opening an issue @dt-iland. Can you please provide a screenshot of the variable explorer you're referring to?

**Comment by SydneyhSmith** [comment]
Closing as inactive, will re-open if more info is provided. Thanks!
