### ISSUE TITLE
[Command Explorer] Type search ability

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#1678]
**Summary of the new feature**

I'm not sure if this is an option that can be done.  I noticed that we have the ability to click on a given command in the explorer window with no action being taken.

It would be nice in waiting for Code to support a search feature that we have the ability to type-search (?). What I mean by that is say in Windows Explorer you are in a given folder that has 100 files listed. You can select a file at the top and type a name, the focus will jump down to that name or the first letter found.

Again not sure if this ability exist in VS Code, but would be nice if it is possible...at least until the search feature is added that is referenced in #1656 .

**Comment by SydneyhSmith** [comment]
@wsmelton we would need to get this feature from vs code so we are asking them if that is a possibility https://twitter.com/joaomoreno/status/1072759548514058241

**Comment by jupiterneptune** [comment]
If possible, an enhanced search mode would be excellent! For example, search-as-you-type/filtering the whole list of possible commands in the explorer.

**Comment by wsmelton** [comment]
This feature is available and works if I'm in Insiders, but does not in Stable. Any reason it would not work in both? The type by filter feature for Explorer pane works in both Editions.

![image](https://user-images.githubusercontent.com/11204251/62329342-4437de80-b47b-11e9-8ef7-57fecf532191.png)

I'm not using the Preview build of PS extension either.

**Comment by TylerLeonhardt** [comment]
@wsmelton it's because it hasn't been released to stable yet :) next release it should be there.

**Comment by TylerLeonhardt** [comment]
I'm gonna go ahead and close this. since 1) it's a vscode issue 2) it's addressed and making its way through the bands (insiders first, then stable)

**Comment by wsmelton** [comment]
Can you clarify @TylerLeonhardt is has not been released to the stable PS Extension? The type-to-search feature is in the VS stable edition already, at least for the Explorer panel; is there something else this depends on that VSC team has not released to stable yet?

**Comment by TylerLeonhardt** [comment]
The explorer panel has had this type-to-search feature for a while.

They recently (currently only in insiders) made type-to-search work on _any_ tree view. We have to wait for the next stable VS Code release for type-to-search to work in the Command Explorer
