### ISSUE TITLE
Here-String does not work with tab/space

### ISSUE THREAD

**Issue by tonidy** [PowerShell/vscode-powershell#169]
When I tried to write this:
`
<space> or <tab>$aTestVariable = @"
<space> or <tab>       Test 
<space> or <tab>       Satu
<space> or <tab>       Dua
<space> or <tab>       Tiga
<space> or <tab>"@
`

Then what I saw:
![test](http://i.imgur.com/bSfjS6r.png)

But this code works:
`
<space> or <tab>$aTestVariable = @"
<space> or <tab>       Test 
<space> or <tab>       Satu
<space> or <tab>       Dua
<space> or <tab>       Tiga
<empty space>"@
`

Is this by design? I could not find any information about this.

**Comment by rkeithhill** [comment]
The accepted form of a here-string is:
```
@"<whitespace>*<newline>
<zero or more lines of text>
"@ 
```
The closing quotation mark must be the first character of a new line.  See the help topic `about_Quoting_Rules`.

**Comment by daviwil** [comment]
Yep, this is a facet of the PowerShell language rather than a VS Code extension bug.  I'll close this, we can reopen if you feel that there's another issue here.  Thanks!
