### ISSUE TITLE
(get-culture).DateTimeFormat.ShortDatePattern is readonly

### ISSUE THREAD

**Issue by raj-julha** [PowerShell/vscode-powershell#1693]
### System Details

System Details Output
```
### VSCode version: 1.26.1 493869ee8e8a846b0855873886fc79d480d342de x64

### VSCode extensions:
dbaeumer.vscode-eslint@1.8.0
DotJoshJohnson.xml@2.4.0
eamodio.gitlens@9.4.1
eg2.tslint@1.0.42
formulahendry.code-runner@0.9.5
ms-mssql.mssql@1.4.0
ms-vscode.csharp@1.17.1
ms-vscode.PowerShell@1.10.2
redhat.java@0.36.0
vscjava.vscode-java-debug@0.16.0
vscjava.vscode-java-dependency@0.3.0
vscjava.vscode-java-pack@0.5.0
vscjava.vscode-java-test@0.13.0
vscjava.vscode-maven@0.13.0


### PSES version: 1.10.2.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with setting the (get-culture).DateTimeFormat.ShortDatePattern

#### Expected Behaviour

I expected the statement below to run without errors
(get-culture).DateTimeFormat.ShortDatePattern = "yyyy-MM-dd"

When I execute this in a normal powershell window it changes the ShortDatePattern property to the new value whereas when I do this inside the powershell console in VS Code I get an error that the property is readonly.

#### Actual Behaviour

I get the error

Exception setting "ShortDatePattern": "Instance is read-only."
At line:1 char:1
+ (Get-Culture).DateTimeFormat.ShortDatePattern = "yyyy-MM-dd"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by doctordns** [comment]
The System.Globalization.CultureInfo object is the one returned from the call to Get-Culture. ALL the key properties are read/only. I believe this is by design and is not a bug.

**Comment by raj-julha** [comment]
Well I tried this and as you can see the property states get;set so I assume it is assignable.

```powershell
PS D:\working> (Get-Culture).DateTimeFormat | Get-Member -Name ShortDatePattern
   TypeName: System.Globalization.DateTimeFormatInfo

Name             MemberType Definition
----             ---------- ----------
ShortDatePattern Property   string ShortDatePattern {get;set;}
```

**Comment by rkeithhill** [comment]
This happens in a normal PowerShell console.  If you believe this to be a bug, you should file it in the PowerShell repo - https://github/com/powershell/powershell

**Comment by shem-sargent** [comment]
You may need to use ```(Get-Culture).Clone()``` to get a writeable copy. That worked for me.
