### ISSUE TITLE
VSCode support for ISE's Ctrl+mouse

### ISSUE THREAD

**Issue by doctordns** [PowerShell/vscode-powershell#1694]
## Issue Description ##

I am experiencing a problem with VSCode editor. I am trying to finish my personal transformation away from ISE and move to VS Code.

One thing I use a lot in ISE is using the ctrl-mouse combination to highlight (and cut/paste) a block of text. That way I can pick out a block of code and cut/past it, THis is a feature I use heavily. 

There appears to be no way to do this in VSCode. Unless, of course, I am missing something.

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18309 |
| VSCode | 1.30.1|
| PowerShell Extension Version | 1.10.2 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.18309.1000|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18309.1000|
|BuildVersion|10.0.18309.1000|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|1.6.10|
|csharp|ms-vscode|1.17.1|
|githistory|donjayamanne|0.4.4|
|PowerShell|ms-vscode|1.10.2|
|rainbow-csv|mechatroner|0.8.0|
|vscode-icons|robertohuertasm|8.0.0|
|vscode-markdownlint|DavidAnson|0.22.0|;

</details>

**Comment by SeeminglyScience** [comment]
@doctordns Try `Alt` instead of `Ctrl`

**Comment by SeeminglyScience** [comment]
A note about keybindings, mouse related shortcuts are one of the few things you can't customize at the moment.  See Microsoft/vscode#3130

**Comment by rkeithhill** [comment]
On my Windows machine I have to use <kbd>Alt+Shift</kbd> + mouse to block select.  

@doctordns doing this with the mouse is cool but you can also do this with the keyboard in VSCode.  Move the cursor to the first line, first col you want to block select, press <kbd>Ctrl+Alt+DownArrow</kbd> until you get to the last line you want to copy/paste.  This creates multiple cursors.  When you get to the last line, press <kbd>Shift+RightArrow</kbd> to select by column.  If you want to select to the end of the line instead, press <kbd>Shift+End</kbd>.  

Multi-cursor editing is *wicked cool*.  Once you use it, you'll have a hard time going back to an editor that doesn't support it.

**Comment by SeeminglyScience** [comment]
> On my Windows machine I have to use Alt+Shift + mouse to block select.

Ah yes, `Alt` + mouse is for block selecting the terminal, `Alt+Shift` + mouse for editor. (Forgot about that, vim mode's block select spoils me 😉)

**Comment by doctordns** [comment]
Thanks folks for all the feedback. 

Alt+Shift does what I need.  Using Ctrl+Alt+DownArrow works very well.  It would be nice if these key combinations worked in the PowerShell console frame (as in ISE), but I can learn to live without it...
