### ISSUE TITLE
VSCode PowerShell exetension crashes

### ISSUE THREAD

**Issue by doctordns** [PowerShell/vscode-powershell#1695]
## Issue Description ##

I am experiencing a problem with VSCode Crashing, which I can reproduce.

To reproduce:
1. Open VSCode and create a new PowerShell file.
2. Enter a few lines of text.
3. Move your cursor to the bottom of the text in the editor pane
4. In the editor pane, hold down the ctrl key and highlight some text.
5. BANG - PowerShell extension crashes
## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18309 |
| VSCode | 1.30.1|
| PowerShell Extension Version | 1.10.2 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.18309.1000|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18309.1000|
|BuildVersion|10.0.18309.1000|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|1.6.10|
|csharp|ms-vscode|1.17.1|
|githistory|donjayamanne|0.4.4|
|PowerShell|ms-vscode|1.10.2|
|rainbow-csv|mechatroner|0.8.0|
|vscode-icons|robertohuertasm|8.0.0|
|vscode-markdownlint|DavidAnson|0.22.0|;

</details>

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

Can you set the log level to `Diagnostic`?

**Comment by doctordns** [comment]
Here are the logs

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2750415/EditorServices.log)
[Start-EditorServices-EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/2750416/Start-EditorServices-EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/2750417/vscode-powershell.log)

**Comment by rkeithhill** [comment]
Although I'm not seeing a crash in this log file, I can tell you there is a known bug with the code folding provider when used on an untitled file.  For now to get around this bug save the file as a ps1 file.

**Comment by doctordns** [comment]
Ahh - saving the file does indeed resolve this issue.

**Comment by TylerLeonhardt** [comment]
The fix for that is already in master, it's just pending a new release 👍

**Comment by SydneyhSmith** [comment]
Closing this as the update is now out! Will re-open if this issue persists.
