### ISSUE TITLE
PowerShell Event Support

### ISSUE THREAD

**Issue by Castillu84** [PowerShell/vscode-powershell#1700]
Add support EngineEvent to PowerShell integrated Console.

Actualy in VSC can't register a Engine Event in the integrated Console with Register-EngineEvent Cmdlet.

Example: Register-EngineEvent -SourceIdentifier PowerShell.Exiting -SupportEvent -Action {Get-History -Count 25 | Export-Csv -Path $PSHistoryPath}

With PowerShell and PowerShellISE this feature is support. I put a screenshare below with VSC and ISE using Get-EventSubscriber after Register-EngineEvent.

![powershellengineeventsupport](https://user-images.githubusercontent.com/17143635/51245891-3ca26380-1989-11e9-96e3-b57401495183.png)

**Comment by SydneyhSmith** [comment]
@Castillu84 thanks for reporting this! I am having difficulty re-producing this result and I am wondering if you use the PowerShell terminal in VSCode (not the Integrated Console) 
![image](https://user-images.githubusercontent.com/43417619/51266712-d3aef180-1970-11e9-9522-558ae9349936.png)
if you also reach this issue?

**Comment by Castillu84** [comment]
Hey sorry,

This flag **SuportEvent** is set to 'True' when is used a -SupportEvent parameter in Register-EngineEvent cmdlet.

Register-EngineEvent -SourceIdentifier PowerShell.Exiting **-SupportEvent** -Action {Get-History -Count 25 | Export-Csv -Path $PSHistoryPath}

But the real fact is that when exit VSC or his PS console (PowerShell Integrated or PowerShell) the event action never is executed. But in Power Shell ISE or Windows PowerShell console it works. 

The powerShell versión I executed is PowerShel 5.1.

Best regards,

**Comment by SydneyhSmith** [comment]
Got it, thanks. I am able to repro this now. I wonder if it has to do with the integrated console not having a true Exit experience.
![image](https://user-images.githubusercontent.com/43417619/51339184-a2055b80-1a40-11e9-833f-19ff849e8ef3.png)

 It would be interesting to know there are any `SourceIdentifiers` that _do_ work in the integrated console?

**Comment by rkeithhill** [comment]
I could believe that because the PSIC is meant to run for the entire editing session.  If you could close it, you'd lose a lot of PS language features in the editor (tab-completion, code analysis/code fix, code lens, debugging, etc).  Perhaps we could emit a warning message to this effect?

**Comment by rjmholt** [comment]
I think adding engine event support could be dicey. As nice as it would be, we do a lot of strange things behind the scenes to make all the intellisense work and share the pipeline thread, and giving a hook into engine with events would exponentiate the complexity of handling all that.

**Comment by Castillu84** [comment]
Hi Sydneyh

If we would know any SourceIdentifiers that work in VSC would be cool.

**Comment by naveensaigit** [comment]
Has there been any progress for the `exit` issue? `exit` still doesn't work

**Comment by rjmholt** [comment]
I was under the impression that we actually added engine event support with PSReadLine. However, the PSIC doesn't implement the `exit` keyword at the top level today (I'm not sure there's a good reason for it to, since that process can't exit &mdash; it's needed to run the PowerShell extension). Hence no exit event support (theoretically it's supported, but you can't exit...).

I'll close this issue, since PSReadLine added engine event handling.
