### ISSUE TITLE
not able to get back default color scheme.

### ISSUE THREAD

**Issue by revoorunischal** [PowerShell/vscode-powershell#1708]
Hi , 

   I have been using visual studio code and terminal from 6 months and it was working fine but all of a sudden now text is coming in highlighted mode and not able to read the text. Can you please suggest any solutions. Have attached screenshot for reference 

![image](https://user-images.githubusercontent.com/10596777/51423942-167cfd80-1bed-11e9-90c8-269069ceb62a.png)

**Comment by SydneyhSmith** [comment]
@revoorunischal it looks like this is actually a VSCode bug, could you please re-open this issue in their repo https://github.com/Microsoft/vscode/issues
