### ISSUE TITLE
PowerShell Editor Services - FATAL UNHANDLED EXCEPTION - Illegal characters in path

### ISSUE THREAD

**Issue by itzik-h** [PowerShell/vscode-powershell#171]
PowerShell Editor Services keeps on crashing with "FATAL UNHANDLED EXCEPTION".
Mostly when clicking "F12" for "go to definition".
There are no special characters in the path of any of the files in the project.
See attached log.
Win 7 and 10.
Powershell 5 and 3.

[EditorServices.txt](https://github.com/PowerShell/vscode-powershell/files/258863/EditorServices.txt)

**Comment by daviwil** [comment]
Hey @itzik-h, thanks for the report and for including the logs.  It looks like we might have a bug in our path resolution algorithm for finding referenced files.  If it's possible, could you give me the full file paths of the file you were in when you pressed F12 and any files you've dot-sourced in that file?

**Comment by wellsluo** [comment]
I encountered the same issue here. refer post "Editor service crashed" https://github.com/PowerShell/vscode-powershell/issues/224 

I tested on follow path with different project/folder names:
C:\Temp\
D:\Code\

**Comment by itzik-h** [comment]
Added test sample to #224

**Comment by daviwil** [comment]
The final work for this is being checked in with https://github.com/PowerShell/PowerShellEditorServices/pull/314.  You should see an improvement in the upcoming 0.8.0 release!
