### ISSUE TITLE
Execute Pester Describe block using interpolated string using new Pester 4.6 parameter

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/vscode-powershell#1710]
**Summary of the new feature**

As a result of discussing issue #827, [this](https://github.com/pester/Pester/pull/122) PR added a Pester option for specifying the line instead of a test name, this means that this enables us to run Pester tests that contain interpolated describe block strings. However, we cannot just simply change the syntax because we cannot rely on the latest version of Pester being installed. This outlines the high level behaviour

**Proposed technical implementation details (optional)**

- PSES should additionally send the line number (`pesterSymbol.ScriptRegion.StartLineNumber`) to the vscode extension [here](https://github.com/PowerShell/PowerShellEditorServices/blob/161a3ed45fafacfc225d3bc335cd6f5e84a255e5/src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs#L57) and [here](https://github.com/PowerShell/PowerShellEditorServices/blob/161a3ed45fafacfc225d3bc335cd6f5e84a255e5/src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs#L66).
- In the extension we need to make a decision then based on the Pester version number to determine the syntax to Invoke-Pester:
   - I propose to use `(Get-Module -ListAvailable Pester).Version | Sort-Object -Descending | Select-Object -First 1` to retrieve the latest version. The first time it takes ~250ms, after that it's ~50ms. Should we cache the version or just always check? Or I should I do this expensive work at startup in the background? Although `Get-Module` has better performance compared to `Get-Command`, the check is not 100% accurate because one can technically import an older specific version of Pester via `Import-Module` and at runtime this older  version would be used. Please respond and discuss this point
   - If the Pester version is determined to be too old, then the extension should fall back to the existing behaviour whereby it asks the user if he/she wants to Invoke-Pester just against the whole file.
   - Where is the best way of checking the version? Should we do this in PSES by calling into the PS API or should we pre-pend code before the `Invoke-Pester` call in the extension? IF PSES has the info, then I guess we would also send another boolean parameter to the extension whether to use the describeblockname or the describeblocknumber?

cc @rkeithhill @TylerLeonhardt  @rjmholt  for discussion

**Comment by rjmholt** [comment]
> I propose to use (Get-Module -ListAvailable Pester).Version | Sort-Object -Descending | Select-Object -First 1 to retrieve the latest version. The first time it takes ~250ms, after that it's ~50ms. Should we cache the version or just always check? Or I should I do this expensive work at startup in the background? Although Get-Module has better performance compared to Get-Command, the check is not 100% accurate because one can technically import an older specific version of Pester via Import-Module and at runtime this older version would be used. Please respond and discuss this point

The logic we use to load the right PSSA [uses `Get-Module -ListAvailable`](https://github.com/PowerShell/PowerShellEditorServices/blob/93587095ae957a634515ab4d4f8665f21a0fa9aa/src/PowerShellEditorServices/Analysis/AnalysisService.cs#L589-L606).

We then just check the version of the `PSModuleInfo` against what we want.

**Comment by TylerLeonhardt** [comment]
We have this feature now thanks to @bergmeister and @rkeithhill!

**Comment by bergmeister** [comment]
Yes, sorry, I forgot to close the issue
