### ISSUE TITLE
Error while debugging

### ISSUE THREAD

**Issue by RagRawat** [PowerShell/vscode-powershell#1712]
## Getting Error while debugging ##

I am experiencing a problem when I am debugging . even I am not able to get the new version of AL Language.

## Attached Logs ##
![image](https://user-images.githubusercontent.com/39081613/51514271-02c3d800-1e35-11e9-976f-f21818b73835.png)

Error: This AL extension version for Visual Studio Code cannot be used with the specified server.
Please update the AL extension from the Visual Studio Code marketplace.

Additional information:
Server details
- Runtime: 2.3
- Web API: 2.0
- Debugger: 2.0

AL extension details
- Supported runtimes: 1.0, 2.0, 2.1, 2.2
- Supported Web API: 1.0, 2.0
- Supported debuggers: 1.0, 2.0

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.30.2|
| PowerShell Extension Version | 1.10.2 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17763.134|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17763.134|
|BuildVersion|10.0.17763.134|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|al|ms-dynamics-smb|2.1.69331|
|al-code-outline|andrzejzwierzchowski|0.0.12|
|al-formatter|rasmus|3.0.0|
|al-object-designer|martonsagi|0.0.5|
|crs-al-language-extension|waldo|1.0.11|
|githistory|donjayamanne|0.4.4|
|mssql|ms-mssql|1.4.0|
|PowerShell|ms-vscode|1.10.2|
|rest-client|humao|0.21.1|
|snippet-creator|nikitaKunevich|0.0.5|
|vscode-pull-request-github|GitHub|0.3.2|;

</details>

**Comment by rjmholt** [comment]
@RagRawat, looks like you want to open thing in the [AL extension repo](https://github.com/Microsoft/AL/issues/new/choose).

**Comment by RagRawat** [comment]
Thanks,

I got the solution.
https://saurav-nav.blogspot.com/2019/01/msdyn365bc-error-this-al-extension.html

Raghubir
