### ISSUE TITLE
Preview extension not loading

### ISSUE THREAD

**Issue by dsolodow** [PowerShell/vscode-powershell#1721]
### System Details

```
### VSCode version: 1.30.2 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8 x64

### VSCode extensions:
bierner.github-markdown-preview@0.0.2
bierner.markdown-checkbox@0.1.1
bierner.markdown-emoji@0.0.7
bierner.markdown-preview-github-styles@0.1.4
bierner.markdown-yaml-preamble@0.0.2
DavidAnson.vscode-markdownlint@0.23.0
eamodio.gitlens@9.4.1
ms-mssql.mssql@1.4.0
ms-vscode.azure-account@0.8.0
ms-vscode.PowerShell@1.11.0
ms-vscode.PowerShell-Preview@2.0.0
redhat.vscode-yaml@0.2.1
streetsidesoftware.code-spell-checker@1.6.10
yzhang.markdown-all-in-one@2.0.1


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18317.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18317.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with getting the preview extension to load, after disabling the release extension

#### Expected Behaviour

Extension should load; be able to open the Integrated Console, access PowerShell options from the command pallet; etc.

#### Actual Behaviour

command 'PowerShell.OpenLogFolder' not found
command 'PowerShell.ShowSessionConsole' not found
command 'PowerShell.RestartSession' not found

### Attached Logs

Logs never generate. 👎

**Comment by rkeithhill** [comment]
Have you disabled the non-preview version of the PowerShell extension?

**Comment by dsolodow** [comment]
Yes. Even tried uninstalling it as well.

**Comment by TylerLeonhardt** [comment]
Odd... Random question... Did you open a folder with vscode or just a blank instance?

**Comment by dsolodow** [comment]
Blank instance

**Comment by andrewtchilds** [comment]
Having the same problem, and it only seems to happen if I'm not working within a folder (workspace?) in VS Code.

**Comment by SeeminglyScience** [comment]
Same thing for me when in an untitled workspace.  It's *almost* like the activation event doesn't get sent, but the extension host log does indeed show it.

```raw
[2019-01-24 09:26:14.884] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.PowerShell-Preview {"startup":false,"activationEvent":"onLanguage:powershell"}
[2019-01-24 09:26:14.884] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\user\.vscode\extensions\ms-vscode.powershell-preview-2.0.0\out\src\main
```

**Comment by TylerLeonhardt** [comment]
So strange... I wonder if this has something to do with the extension name being "PowerShell Preview" I'll run some tests.

**Comment by TylerLeonhardt** [comment]
I can repro this with a local build of the extension too

**Comment by alexandair** [comment]
Another confirmation. Opening a new file, doesn't trigger loading of the preview extension. If I load a folder, and then open a .ps1 file, preview extension is loaded as expected.

**Comment by dsolodow** [comment]
Interesting note; it works fine on my work PC.
```
### VSCode version: 1.30.2 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8 x64

### VSCode extensions:
bierner.github-markdown-preview@0.0.2
bierner.markdown-checkbox@0.1.1
bierner.markdown-emoji@0.0.7
bierner.markdown-preview-github-styles@0.1.4
bierner.markdown-yaml-preamble@0.0.2
DavidAnson.vscode-markdownlint@0.23.0
eamodio.gitlens@9.4.1
Kelvin.vscode-sshfs@1.11.2
kenhowardpdx.vscode-gist@2.1.2
ms-mssql.mssql@1.4.0
ms-vscode.azure-account@0.8.0
ms-vscode.PowerShell@1.11.0
ms-vscode.PowerShell-Preview@2.0.0
redhat.vscode-yaml@0.2.1
streetsidesoftware.code-spell-checker@1.6.10
TaoKlerks.poor-mans-t-sql-formatter-vscode@1.6.10
yzhang.markdown-all-in-one@2.0.1


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jeremytbrun** [comment]
>           Another confirmation. Opening a new file, doesn't trigger loading of the preview extension. If I load a folder, and then open a .ps1 file, preview extension is loaded as expected.

Same here.

**Comment by TylerLeonhardt** [comment]
I've figured this out and have a fix for it. Will submit a PR soon.

**Comment by TylerLeonhardt** [comment]
PR here ^ for those interested in testing it out. You can grab a CI build here:

https://ci.appveyor.com/project/PowerShell/vscode-powershell/builds/21895485/artifacts

Let me know if that fixes it for you 😄

**Comment by corbob** [comment]
I imagine this is related, so I'll post it here:

When building master, I was getting the message "Activating extension 'ms-vscode.PowerShell' failed: Cannot read property 'toLowerCase' of undefined." pop up. When I loaded a workspace then it loaded without problem.

![Activating extension 'ms-vscode.PowerShell' failed: Cannot read property 'toLowerCase' of undefined.](https://user-images.githubusercontent.com/30301021/51881479-2785e700-2330-11e9-93a5-9b72795d30b8.png)

Based on this line: https://github.com/PowerShell/vscode-powershell/pull/1728/files#diff-8cfead41d88ad47d44509a8ab0a109adR163 I'll leave this here as related. If it's not related let me know and I'll open a new issue.

**Comment by TylerLeonhardt** [comment]
I updated https://github.com/PowerShell/vscode-powershell/pull/1728 to have a default of `__dirname` if all else fails.
