### ISSUE TITLE
Unable to import newer Package Management module in integrated console

### ISSUE THREAD

**Issue by splatteredbits** [PowerShell/vscode-powershell#1724]
### System Details
* MacOS 10.12.6
* Code 1.30.2
* Extension 1.11.0
* `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am unable to import a new version of the Package Management module into my integrated console because the integrated console has already loaded it. The Package Management module has assemblies that get loaded. Once one version of the module is imported, those assemblies get loaded, and new/different versions can't get imported. We have a build tool that auto downloads and installs modules. I can't debug any of these tests in Visual Studio Code because our tool can't import the new version of Package Management.

#### Expected Behaviour

I expect the integrated console to not import the Package Management module when it launches.

#### Actual Behaviour

It is importing the Package Management module somehow.

### Steps to Reproduce

1. Open Visual Studio Code.
2. Open the integrated console.
3. Run `Save-Module PackageManagement -Path '.'`
4. Close Visual Studio Code.
5. Re-open Visual Studio Code and launch the integrated PowerShell console.
4. Run `Import-Module .\PackageManagement`.
5. Note the error about an assembly already being loaded.

You can see that the default Package Management module's assemblies are loaded by running `[AppDomain]::CurrentDomain.GetAssemblies()` from the integrated console.

**Comment by SydneyhSmith** [comment]
@splatteredbits The command Save-Module imports PackageManagement because PowerShell Get imports PackageManagement so this is why the assemblies are already loaded when you run Import-Module

**Comment by SydneyhSmith** [comment]
@splatteredbits sorry for the very long delay in getting back to you, I am still having difficulty re-proing this, any gifs/logs/screenshots would be helpful!

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
