### ISSUE TITLE
The [S]uspend option doesn't seem to be working in PowerShell when a write-debug statement is reached.

### ISSUE THREAD

**Issue by autocloudarc** [PowerShell/vscode-powershell#1726]
### System Details

System Details Output
```

```

### Issue Description
When using a write-debug statement in a PowerShell script, the [S]uspend option is ignored and I keep getting prompted to enter a selection again.
I am experiencing a problem with...
Write-Debug options.

#### Expected Behaviour
When selecting the [S] option, the console should transition to a nested prompt, as with the PowerShell ISE, where I can pause to troubleshoot and attempt to resolve before returning to options selection and continue running the code.
-- Description of what *should* be happening --
The [S]uspend option is ignored, and the console does not transition to the nested debugging level.

#### Actual Behaviour
-- Description of what actually happens --
The suspend option is ignored.
### Attached Logs
The report for inactive computers has been saved to C:\Users\adm.infra.user\Remove-InactiveComputerAccounts\OLD_Servers-12-26-2018-9.23.46-AM-2019-01-25-0923-Days.csv
DEBUG: $statusList.count = 0
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"): S
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"): S
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"): S
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
![debug-suspend-option-does-not-seem-to-work-25jan2019](https://user-images.githubusercontent.com/15109536/51737131-c3d79180-2083-11e9-8631-c40d581dedfb.png)

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by SeeminglyScience** [comment]
This is due to missing support for `PSHost.EnterNestedPrompt`.

That support was added as part of the PSReadLine integration changes, and is available in the [preview version](https://blogs.msdn.microsoft.com/powershell/2019/01/23/announcing-the-powershell-preview-extension-in-vscode/) of the extension.

**Comment by SydneyhSmith** [comment]
Closing for now as this is available in the Preview Version of the extension
