### ISSUE TITLE
Enhancement: Please provide a code.ps1 alongside code.cmd and code in bin directory

### ISSUE THREAD

**Issue by marking** [PowerShell/vscode-powershell#173]
I was directed over here by @isidorn 
- VSCode Version:
  Version 1.1.0
  Commit c212f0908f3d29933317bbc3233568fbca7944b1
  Date 2016-05-09T12:53:58.929Z
  Shell 0.37.6
  Renderer 49.0.2623.75
  Node 5.10.0
- OS Version: Windows 10 Professional

not so much a bug as a feature request. I'd like to see a code.ps1 along with the code.cmd and code scripts.  Here's a skeleton to get started (blatantly copied from code.cmd and translated):

``` powershell
[CmdletBinding()]
    Param
    (
    [parameter(mandatory=$false, position=0, ValueFromRemainingArguments=$true)]$Remaining
    )

Remove-Item env:\VSCODE_DEV
$env:ATOM_SHELL_INTERNAL_RUN_AS_NODE=1
$dp0 = Split-Path -parent $PSCommandPath;
$exePath = [System.Io.Path]::Combine($dp0, "..\code.exe");
Write-Verbose "exePath is $exePath";
$jsPath =  [System.Io.Path]::Combine($dp0, "..\resources\app\out\cli.js");
Write-Verbose "jsPath is $jsPath";
Write-Verbose "remaining is $remaining"
Write-Verbose "command line is [$exePath] [$jsPath] [$remaining]"

&"$exePath" "$jsPath" $remaining

```

**Comment by daviwil** [comment]
Hey Mark, is this basically just a way to launch VS Code from within a PowerShell console?  Interesting idea, but I'm not sure if the PowerShell extension is the right place to put that.  I could see this being shipped as a module on the PowerShell Gallery but that'd still require a separate installation from VS Code.  Even VS Code couldn't ship such a file effectively because it'd require that they manipulate the user's PSModulePath.  I'll think on this a little bit more.

**Comment by marking** [comment]
I didn't really think this was the right place either, which is why I started over in vscode. When vscode installs, it adds its own bin directory to the path (on windows) and places a code.cmd, code (bash), and code.js files there to help launch. I was just thinking that it would be nice to have a code.ps1 to go along with those.

It kind of made sense to me, however, that perhaps only those that install the powershell extensions for vscode would be interested in this type of launcher, so here I am.

If code.ps1 is placed alongside the other launcher files, no modification of $PSModulePath would be required because the bin directory is already in $env:Path.

**Comment by tylerl0706** [comment]
Maybe I'm missing something but you can already run code.cmd from within a PowerShell console and it will launch VSCode. Do we get any benefit from having a `code.ps1`?

Also, this issue should probably be opened against [vscode itself](http://github.com/microsoft/vscode).

If I'm missing something, please clue me in! 😄

**Comment by marking** [comment]
no, you are not missing anything. Just seems like the right thing to do. I filed an older issue against vscode, but once they saw ".ps1", the referred me to here. I'm not pushing for this anymore; was actually surprised to see a fresh comment.
