### ISSUE TITLE
Preview extension: There is no document formatter for 'powershell'-files installed.

### ISSUE THREAD

**Issue by fullenw1** [PowerShell/vscode-powershell#1730]
When I use the preview extension, the formatter does not work.
There is no auto-format when I type and when I press SHIFT + ALT + F, I get this error message:

> There is no document formatter for 'powershell'-files installed.

## Attached Logs ##

Successfully activated to **Diagnostic** but got this error when I typed **Open PowerShell Extension Logs Folder** in the command palette:

> command 'PowerShell.OpenLogFolder' not found

### Visual Studio Code ###

| Name | Version |
|---|---|
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.30.2|
| PowerShell Extension Version | 1.11.0 - DISABLED |
| PowerShell Extension Version Preview | 2.0.0-preview.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|6.1.2|
|PSEdition|Core|
|GitCommitId|6.1.2|
|OS|Microsoft Windows 10.0.17763 |
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.1.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.0|
|azurerm-vscode-tools|msazurermtools|0.4.2|
|code-settings-sync|Shan|3.2.4|
|gitlens|eamodio|9.4.1|
|PowerShell|ms-vscode|1.11.0|
|shell-launcher|Tyriar|0.3.0|
|vscode-icons|robertohuertasm|8.0.0|;

</details>

**Comment by SydneyhSmith** [comment]
@fullenw1 we are trying to re-pro your issue and I am wondering if you are using an empty workspace? Thanks!

**Comment by fullenw1** [comment]
@SydneyhSmith

Yes that's correct.
When I load a workspace the formatter is working fine again.

**Comment by TylerLeonhardt** [comment]
This will be fixed in the next release. #1728

**Comment by pdhimate** [comment]
Downgrading to a previous version worked for me.

**Comment by KaylorDave** [comment]
Seeing the same issue. If I open up a workspace this is resolved.

**Comment by SydneyhSmith** [comment]
Hi all, wondering if you are still reaching this issue after our recent updates?

**Comment by fullenw1** [comment]
Hi, it's working fine for me now.
Good job!

**Comment by SydneyhSmith** [comment]
Great, I will close this issue for now!

**Comment by MalcolmAnderson** [comment]
This is an issue for me in 1.47.3

**Comment by necoras** [comment]
I'm having this issue in v 1.5.1.1. I have version 2020.6.0 of the PowerShell extension.

**Comment by rsb177** [comment]
@necoras , if it helps any, I was having the same issue and reinstalling the extension fixed it for me.

**Comment by necoras** [comment]
My issue ended up being a corrupted path environment variable.

**Comment by henrivdr01** [comment]
Same issue after upgrading to 1.56.2 while using PowerShell Extension 2021.2.2

**Comment by charlesroper** [comment]
I had the same issue and, like @rsb177, uninstalling and reinstalling the extensions fixed it.

**Comment by konrad-lapinski** [comment]
Using x86 powershell worked for me
![obraz](https://github.com/PowerShell/vscode-powershell/assets/21232347/cba4a68e-4e0f-4741-98de-b7939f9a38dc)

**Comment by NestDream** [comment]
> Using x86 powershell worked for me ![obraz](https://private-user-images.githubusercontent.com/21232347/295859485-cba4a68e-4e0f-4741-98de-b7939f9a38dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMzk3ODgsIm5iZiI6MTcxNjMzOTQ4OCwicGF0aCI6Ii8yMTIzMjM0Ny8yOTU4NTk0ODUtY2JhNGE2OGUtNGUwZi00NzQxLTk4ZGUtYjc5MzlmOWEzOGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAwNTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YzkzZjVhODA5NmQ1OTVmMmZmYzg4NDAzOTIxMmEwYTQwMWRiMTljZWEyM2JjMjNjYjg2Nzk1ZGM0ZDEwYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pDbb0AWy9jGGS2oK2Ui-uSwpdGkZE-zffi-bpCBi0qs)

This works for me. 
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
