### ISSUE TITLE
Preview extension: command 'PowerShell.GenerateBugReport' not found

### ISSUE THREAD

**Issue by fullenw1** [PowerShell/vscode-powershell#1731]
## Issue Description ##

When I use the built-in function **Upload bug report to Github**, I get this error message:

> command 'PowerShell.GenerateBugReport' not found

## Attached Logs ##

Successfully activated to **Diagnostic** but got this error when I typed **Open PowerShell Extension Logs Folder** in the command palette:

> command 'PowerShell.OpenLogFolder' not found

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.30.2|
| PowerShell Extension Version | 1.11.0 |
| PowerShell Extension Version | 1.11.0 - DISABLED |
| PowerShell Extension Version Preview | 2.0.0-preview.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|6.1.2|
|PSEdition|Core|
|GitCommitId|6.1.2|
|OS|Microsoft Windows 10.0.17763 |
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.1.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.0|
|azurerm-vscode-tools|msazurermtools|0.4.2|
|code-settings-sync|Shan|3.2.4|
|gitlens|eamodio|9.4.1|
|PowerShell|ms-vscode|1.11.0|
|shell-launcher|Tyriar|0.3.0|
|vscode-icons|robertohuertasm|8.0.0|;

</details>

**Comment by TylerLeonhardt** [comment]
This was an early bug if you opened an untitled workspace. This should be fixed in the current latest beta.

@fullenw1 are you still seeing this issue?

**Comment by fullenw1** [comment]
Now it opens a blank page in the default browser. Not sure it is the expected behavior...
But I don't have the error message anymore.

**Comment by TylerLeonhardt** [comment]
Ah that will be fixed in the next release.

**Comment by SydneyhSmith** [comment]
Closing as the fix (and the release) are now available
