### ISSUE TITLE
Comment for powershell.powerShellDefaultVersion should not complete full PowerShell Core Version

### ISSUE THREAD

**Issue by DerAlbertCom** [PowerShell/vscode-powershell#1734]
In the comment for the setting

`powershell.powerShellDefaultVersion`  is stated that the Version nummber should be given is something like **PowerShell Core 6.0.2 (x64)**, which would be in my case *PowerShell Core 6.1.2 (x64)* no other version is installed. 

https://github.com/PowerShell/vscode-powershell/blob/08f0bc5a590c457631ac5b6b943b5e22e008fbb2/package.json#L537

But this does not work. With the full version number the Plugin falls back to PowerShell  5.1.x (Full Framework) .

But ` "powershell.powerShellDefaultVersion": "PowerShell Core 6 (x64)"` is working fine.

I don't know what the expected behavior is, so i didn't provide a PR for that now.

**Comment by rkeithhill** [comment]
Looks like we grab the expected version number from the path to pwsh.exe.  And over time, the PS team has changed their version number strategy for that path.

**Comment by DerAlbertCom** [comment]
Yes. I digged in the Source to get this information how the Version Information is created.

On my the path is `C:\Program Files\PowerShell\6\pwsh.exe`. That's why my Version Number works.

**Comment by SydneyhSmith** [comment]
Thanks for catching this @DerAlbertCom we should provide a better comment that is inclusive for all versions of PowerShell.
