### ISSUE TITLE
Right-click Get Help for Command returns help for Get-Help cmdlet

### ISSUE THREAD

**Issue by BernieWhite** [PowerShell/vscode-powershell#1740]
## Issue Description ##

_Get Help for Command_ in right-click menu has different behaviour then command bar _PowerShell: Get Help for Command_.

The right-click menu gets online help for the `Get-Help` cmdlet. Where as the command bar actually returns the online help for the specified cmdlet under the cursor.

## Attached Logs ##

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/2816314/logs.zip)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.30.2|
| PowerShell Extension Version | 1.11.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17763.134|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17763.134|
|BuildVersion|10.0.17763.134|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-pipelines|ms-azure-devops|1.147.1|
|code-spell-checker|streetsidesoftware|1.6.10|
|DocFX|ms-docfx|0.1.3|
|docs-article-templates|docsmsft|0.1.4|
|docs-authoring-pack|docsmsft|0.1.1|
|docs-markdown|docsmsft|0.2.2|
|docs-preview|docsmsft|0.3.16|
|github-issues-prs|ms-vscode|0.9.1|
|gitlens|eamodio|9.4.1|
|PowerShell|ms-vscode|1.11.0|
|vscode-markdownlint|DavidAnson|0.23.0|
|vscode-pull-request-github|GitHub|0.3.2|
|vscode-yaml|redhat|0.2.1|;

</details>

**Comment by swiatek25** [comment]
Confirmed. Experiencing the same issues.

**Comment by corbob** [comment]
This is also happening in the Preview extension. The only thing I can think is that VSCode doesn't have a cursor when you right click and so it doesn't know what to send (and the default is get-help).

Perhaps the default should be to return a message that we didn't run it because there was no command sent?

**Comment by corbob** [comment]
It would seem that when we added the Command Explorer and added an optional parameter to the vscode command to show help that right click passes an object in. This object doesn't have a name which is what we use from Command Explorer. I've got a fix and will create a PR in the morning to get this fixed.
