### ISSUE TITLE
PowerShell global variables value not shown on mouse over while debugging

### ISSUE THREAD

**Issue by ChristianTroll** [PowerShell/vscode-powershell#1742]
Hello Team!
i have issues while debugging my PS scripts. Because i´m using scripts that call some others i work with global variables to ensure that specific variables are available in called scripts as well.

Problem is that if you debug you cannot see the value of a $Global:Variable at mouse over.
All other variables you can see the value. 
Sure you can watch these variables. This works as expected. 
But it would make it more comfortable if you could just see the value on mouse over too.

Can you please have a look?

I have PS version 5.1 and VS Code 1.30.2

Many thanks
Chris

**Comment by SydneyhSmith** [comment]
Thanks for reporting this @ChristianTroll! IT would also be helpful to know the version of the PowerShell extension you are using and any screen shots of what you are seeing, vs what you would hope to see. Thanks!

**Comment by ChristianTroll** [comment]
I have standard Windows 10 PS version
PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

What is miss now is the little popup to enter script parameters. 
If i perform a normal debugging (F5) it shows up as usual.

This is what comes up when you press ctrl-m to debug with multiple files. So far so good.
![grafik](https://user-images.githubusercontent.com/16152497/52284330-7d781180-2964-11e9-8787-bb46a3bf4c75.png)

Usually you get this popup right afterwards to enter the script parameter:
![grafik](https://user-images.githubusercontent.com/16152497/52284475-c4660700-2964-11e9-8e5a-9fb7dd117226.png)

But this one is missing now. And no debugging starts.
Many thanks in advance.
Christian

**Comment by SydneyhSmith** [comment]
@ChristianTroll What editor are you using, this doesn't look familiar to VSCode? Could it be PowerShell studio, in which you may want to report the issue to them
