### ISSUE TITLE
Alias --> Command completion doesn't work in Intellisense mode

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#175]
When you're typing a command alias, and want to convert it to a command (`CTRL + ALT + E`), the keyboard shortcut doesn't work, unless the Intellisense window is gone. This is inconvenient if you want to finish the command name, without finishing typing the alias.

![image](https://cloud.githubusercontent.com/assets/466713/15228752/f5fe59d0-184a-11e6-8793-73dd6fd851c5.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment]
Hmmm, haven't seen that before.  It's possible that our command registration has a boolean that prevents it from being used while IntelliSense is open.  Otherwise it might just be a bug/feature request for the VS Code team. I'll look into it.

**Comment by tylerl0706** [comment]
I can't repro this anymore on Windows. However, on macOS I can't expand aliases at all via the command pallet.

I'm going to close this issue and open a new one with that info since it is unrelated to this issue.
