### ISSUE TITLE
Send-MailMessage: Positional Parameter Error

### ISSUE THREAD

**Issue by hobbsjm** [PowerShell/vscode-powershell#1751]
Issue Type: <b>Bug</b>

Run the following script with appropriate values for sender, recipient and SMTP relay:
```
 $from		= "\<Sender\>"
 $recipient	= "\<Recipient\>"
 $smtpRelay	= "\<SMTP Relay\>"
 $subject		= "E-mail Encryption (SMTP): Test 1"
 $body		= "Testing FuseMail SMTP..."
 Send-MailMessage –From $from –To $recipient –Subject $subject –Body $body -SmtpServer $smtpRelay -Port 25
```
This generates the following error:
```
Send-MailMessage : A positional parameter cannot be found that accepts argument 'Testing FuseMail SMTP...'.
At C:\Users\<User>\<OneDrive>\Development\PowerShell\Scripts\Send-EmailUsingSmtpRelay.ps1:6 char:1
+ Send-MailMessage â€“From $from â€“To $recipient1 â€“Subject $subject  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Send-MailMessage], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SendMailMessage
```
Running the same script in the PowerShell console or PowerShell ISE works without issue.

Also note the unexpected characters 'â€“' in the error message.

Extension version: 1.11.0
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by SydneyhSmith** [comment]
Thanks for reporting this @hobbsjm ! It would be really helpful in terms of diagnosing the issue if you could provide logs, instructions for how to do that are [here](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)

**Comment by rjmholt** [comment]
This looks like an encoding problem; your PowerShell session is trying to read CP-1252, but VSCode has written the file in UTF-8 without a BOM.

The simplest solution is to set `"files.encoding": "utf8bom"` in your VSCode settings (<kbd>Ctrl</kbd>+<kbd>,</kbd>).

The PowerShell extension can't see this or configure around it -- it's a configuration problem between the PowerShell session and VSCode, one that's fixed in PowerShell 6.

See https://github.com/PowerShell/vscode-powershell/issues/1744.

If you hit another issue here, please let us know below and we can look into it.

**Comment by rjmholt** [comment]
To be really sure the file is UTF-8 with BOM, you can save it with that encoding like here: https://github.com/Microsoft/vscode/issues/44005#issuecomment-366924405.
