### ISSUE TITLE
PowerShell Preview: issue with host implementation dropping the first letter

### ISSUE THREAD

**Issue by sk82jack** [PowerShell/vscode-powershell#1753]
### VSCode extensions:
CoenraadS.bracket-pair-colorizer-2@0.0.26
eamodio.gitlens@9.5.0
ms-azure-devops.azure-pipelines@1.147.1
ms-mssql.mssql@1.4.0
ms-python.python@2019.1.0
ms-vscode.csharp@1.17.1
ms-vscode.PowerShell-Preview@2.0.0
ms-vsliveshare.vsliveshare@0.3.1151

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

System Details Output
```

```

### Issue Description

When prompting for input from the host (i.e. `Read-Host` or `Get-Credential`) the first letter that you type gets ignored resulting in the intended value of the command to be incorrect. It then writes the initial letter that got committed onto the next line in the console. Please see the gif below:

![2019-02-08_22-45-22](https://user-images.githubusercontent.com/20758758/52510569-62233580-2bf4-11e9-993e-13533d17c638.gif)

#### Expected Behaviour

From the example in the gif I would expect the output of the command to be `test` and then have an empty line to continue typing commands.

#### Actual Behaviour

The example in the gif shows that the initial `t` typed is not registered as part of the input and so the command outputs `est` and then you can see the intial `t` is the written in the console on the next line.

### Attached Logs

Haven't attached logs as it's not crashing but let me know if you need me to.

**Comment by SydneyhSmith** [comment]
@sk82jack thanks for reporting this, it looks like this is a buffer issue likely caused by the PSReadLine implementation.

**Comment by SeeminglyScience** [comment]
Yeah I believe this is due to an incorrect assumption on my part.  I had thought that if two threads were invoking `Console.ReadKey(true)` at the same time (on Windows at least) then both threads would get the same key at the same time.  I thought I had tested that, but it appears I did not.

A possible fix would be to use the same [ReadKey override field](https://github.com/PowerShell/PowerShellEditorServices/blob/db09f56579f904ba1fbb3a242b813ab3e550cd62/src/PowerShellEditorServices/Session/PSReadLineProxy.cs#L102-L105) we use for non-Windows to inject our `ReadKey` implementation.

**Comment by ili101** [comment]
I can confirm that it is still a problem in preview 2.

**Comment by sba923** [comment]
I confirm this issue; if I run the following script 

````
Write-Host -NoNewline ("Enter password: ")
$password = Read-Host -AsSecureString


$RIOM = [Runtime.InteropServices.Marshal]
$bStr = $RIOM::SecureStringToBSTR($password)
$ctpassword = $RIOM::PtrToStringAuto($bStr)
$RIOM::ZeroFreeBSTR($bStr)

Write-Host ("Password is: '{0}'" -f $ctpassword)

Remove-Variable ctpassword
````
and enter `12345` I get:

![image](https://user-images.githubusercontent.com/12860484/59740089-519c5f00-9267-11e9-95d9-25b38f05f877.png)

**Comment by TylerLeonhardt** [comment]
I've got a PR out to fix this.

**Comment by ili101** [comment]
Not fully fixed
1. Copy something
2. Run a file with Read-Host with F5
3. Paste in console
![Paste](https://user-images.githubusercontent.com/6960531/68282672-bc1d3280-0082-11ea-96c8-1ab92672f354.gif)

**Comment by TylerLeonhardt** [comment]
@ili101 looks like that's dropping a few characters on paste. A different issue than this one. Can you open a new issue so we can track this separately?
