### ISSUE TITLE
Powershell Preview: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made

### ISSUE THREAD

**Issue by skest3qc** [PowerShell/vscode-powershell#1756]
Hi,

i just tried this piece of code:

"out " | Set-Clipboard

and got this error:
Set-Clipboard : Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it.

It works in Windows Powershell 5.1 

#1571

**Comment by SydneyhSmith** [comment]
@skest3qc thanks for reporting that you are still having an issue I will re-open #1571 and we will do more investigation to the root cause.
