### ISSUE TITLE
Installation of vscode-powershell replaced File Explorer right-click menus for .ps1 files

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [PowerShell/vscode-powershell#176]
In VSCode I've run 
ext install PowerShell
and after this noticed that I am not able from File Explorer run 
“Run with PowerShell”
or "Open with PowerGUI".

You shouldn't hijack these menu. 

When I am trying to associate .PS1 with "C:\Program Files (x86)\PowerGUI\ScriptEditor.exe", Windows 10 reports an error "[Content]
The program you have selected cannot be associated with this file type. Please choose another program."
It was associated before the installation. Please advice how to fix the issues.

**Comment by michael-freidgeim-webjet** [comment]
Thanks to http://superuser.com/questions/655600/i-cant-set-a-program-as-the-default-to-open-a-filetype-with-in-windows-7
I've open 
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ps1\OpenWithList]
I had the values
"a"="notepad.exe"
"MRUList"="feabcd"
"b"="powershell.exe"
"c"="powershell_ise.exe"
"d"="ScriptEditor.exe"
"e"="{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\\PowerGUI\\ScriptEditor.exe"
"f"="Code.exe"


I've changed MRUList to move 'f' last "MRUList"="eabcdf" and context menus "Open with PowerGUI Script Editor" and  “Run with PowerShell” are restored now.

Anyway you should prevent such corruptions.

**Comment by daviwil** [comment]
Hey Michael, sorry about the file association problem.  Visual Studio Code takes care of file associations so it might be good to file this bug here:

https://github.com/Microsoft/vscode

**Comment by tylerl0706** [comment]
Seems to be very quiet, plus it was a vscode bug. Closing it.
