### ISSUE TITLE
Console hanging after the PowerShell Integrated Console loads

### ISSUE THREAD

**Issue by janegilring** [PowerShell/vscode-powershell#1760]
## Issue Description ##

I am experiencing a problem where the console is hanging after the PowerShell Integrated Console loads. If Enter is pressed multiple times (5 or more I think), the console becomes available.

A funny thing is that the issue does not happen when the Editor Log Level is set to Diagnostic.

## Attached Logs ##

Logs:
[vscode-powershell-logs.zip](https://github.com/PowerShell/vscode-powershell/files/2869340/vscode-powershell-logs.zip)

Gif: Editor Log Level is set to Verbose (be patient, it takes a while):
![powershell_console_hang](https://user-images.githubusercontent.com/2039662/52859197-5ff93380-312c-11e9-9043-bb638690708c.gif)

Gif: Editor Log Level is set to Diagnostic
![powershell_console_hang_diag_enabled](https://user-images.githubusercontent.com/2039662/52859627-7fdd2700-312d-11e9-999b-d213fa6a3505.gif)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.31.1|
| PowerShell Extension Version | 1.11.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|6.1.2|
|PSEdition|Core|
|GitCommitId|6.1.2|
|OS|Microsoft Windows 10.0.17763 |
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.1.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|armsnippet|artofshell|0.7.0|
|azure-account|ms-vscode|0.8.0|
|azure-pipelines|ms-azure-devops|1.147.1|
|azurecli|ms-vscode|0.4.2|
|azurerm-vscode-tools|msazurermtools|0.4.2|
|code-settings-sync|Shan|3.2.5|
|gitblame|waderyan|2.6.3|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.5.1|
|guides|spywhere|0.9.3|
|markdown-all-in-one|yzhang|2.0.1|
|material-icon-theme|PKief|3.6.3|
|PowerShell|ms-vscode|1.11.0|
|python|ms-python|2019.1.0|
|rainbow-csv|mechatroner|1.0.0|
|swagger-viewer|Arjun|2.2.0|
|team|ms-vsts|1.144.1|
|vscode-azurefunctions|ms-azuretools|0.14.0|
|vscode-azureterraform|ms-azuretools|0.2.2|
|vscode-coverage-gutters|ryanluker|2.3.0|
|vscode-docker|PeterJausovec|0.5.2|
|vscode-instant-markdown|dbankier|1.4.3|
|vscode-logicapps|ms-azuretools|0.1.8|
|vscode-markdownlint|DavidAnson|0.24.0|
|vscode-pandoc|DougFinke|0.0.8|
|vsliveshare|ms-vsliveshare|0.3.1182|;

</details>

**Comment by janegilring** [comment]
Similar issue: https://github.com/PowerShell/vscode-powershell/issues/1682

**Comment by janegilring** [comment]
According to @Tyriar the issue is within Windows: https://github.com/Microsoft/vscode/issues/57803

**Comment by SydneyhSmith** [comment]
@janegilring  thanks for reporting the issue and for the additional context with the Windows issue. I will close this as that seems to be the root cause, let us know if you feel differently

**Comment by janegilring** [comment]
That's fine.

FYI: One possible workaround is adding "cls" to the PowerShell profile. Not optimal, but might save some keystrokes until the issue is fixed in Windows.
