### ISSUE TITLE
PowerShell does not support debugging this file type: 'extension-output-#4'.

### ISSUE THREAD

**Issue by ramroumlevrai** [PowerShell/vscode-powershell#1763]
### System Details

System Details Output
```
### VSCode version: 1.26.1 493869ee8e8a846b0855873886fc79d480d342de x64

### VSCode extensions:
DotJoshJohnson.xml@2.4.0
eamodio.gitlens@9.5.1
etmoffat.pip-packages@0.4.3
formulahendry.auto-close-tag@0.5.6
formulahendry.auto-rename-tag@0.0.15
ms-python.python@2019.1.0
ms-vscode.azure-account@0.8.0
ms-vscode.PowerShell@1.11.0
msazurermtools.azurerm-vscode-tools@0.4.2
pranaygp.vscode-css-peek@2.2.0
rafaelmaiolla.remote-vscode@1.1.0
ritwickdey.LiveServer@5.5.1
robertohuertasm.vscode-icons@8.2.0
spences10.vba@1.2.0
Tyriar.theme-sapphire@0.8.1
zhuangtongfa.Material-theme@2.18.2
Zignd.html-css-class-completion@1.18.0


### PSES version: 1.11.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with the debugger, I get the following Error: PowerShell does not support debugging this file type: 'extension-output-#4'.

I've tried with different scripts, even simple ones and still the same error happens.

#### Expected Behaviour

I should be able to debug a PowerShell Script

#### Actual Behaviour

I can't the debug doesn't even execute due to the error

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by TylerLeonhardt** [comment]
Screenshots or gifs of your issue would be most helpful too!

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive but will re-open if more info is provided!

**Comment by markcelo** [comment]
I experienced this issue with the debugger, even when the debugger worked right after installation. 

It is easy to mistakenly add extra debugging configurations from the Debugger view of VC. If you got extra template of actions they are generic and not fully specified which caused the issue for me.
