### ISSUE TITLE
[cultureinfo]::CurrentCulture is Read-Only in the Powershell Integrated Console

### ISSUE THREAD

**Issue by AlexBillon07** [PowerShell/vscode-powershell#1765]
Issue Type: <b>Bug</b>

[cultureinfo]::CurrentCulture is Read-Only in the Powershell Integrated Console whereas it can be modified in a standard powershell console

In the Powershell Integrated Console of VS Code 
```powershell
PowerShell Integrated Console

PS C:\> 1.23
1,23
PS C:\EDI> [cultureinfo]::CurrentCulture.NumberFormat.NumberDecimalSeparator = "."
Exception setting "NumberDecimalSeparator": "L'instance est en lecture seule."
At line:1 char:1
+ [cultureinfo]::CurrentCulture.NumberFormat.NumberDecimalSeparator = " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
PS C:\> 1.23
1,23
```

In a normal Windows Powershell console
```powershell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\EDI> 1.23
1,23
PS C:\EDI> [cultureinfo]::CurrentCulture.NumberFormat.NumberDecimalSeparator = "."
PS C:\EDI> 1.23
1.23
```

Extension version: 1.11.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by SydneyhSmith** [comment]
@AlexBillon07 thanks for reporting this--I can reproduce this in the PowerShell extension. This feature is available in the [PowerShell Preview Extension ](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) which you may want to give a look to and see if it meets your needs. Thanks!

**Comment by AlexBillon07** [comment]
@SydneyhSmith, I have installed  [PowerShell Preview Extension ](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) but still get the same error in the PowerShell Integrated Console

```powershell
PowerShell Integrated Console

PS C:\> [cultureinfo]::CurrentCulture.NumberFormat.NumberDecimalSeparator="."
Exception setting "NumberDecimalSeparator": "L'instance est en lecture seule."
At line:1 char:1
+ [cultureinfo]::CurrentCulture.NumberFormat.NumberDecimalSeparator="."
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\>

```
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-edifact|DAX|0.5.1
xml|Dot|2.4.0
gitlens|eam|9.5.1
reg|ion|0.0.2
mssql|ms-|1.4.0
PowerShell-Preview|ms-|2.0.0
vsc-jsonsnippets|wmo|0.1.4


</details>

**Comment by BjornNordblom** [comment]
Setting [cultureinfo]::CurrentCulture.NumberFormat.NumberDecimalSeparator="." works in Powershell [cultureinfo]::CurrentCulture.NumberFormat.NumberDecimalSeparator="." but for Powershell 7 it is a read-only property.

**Comment by rjmholt** [comment]
> [cultureinfo]::CurrentCulture.NumberFormat.NumberDecimalSeparator="." but for Powershell 7 it is a read-only property.

Looks like this is true in the ordinary PowerShell console as well and is likely to be a .NET Core change, meaning it's something that the extension should not seek to fix

**Comment by rjmholt** [comment]
Thanks for looking into it @BjornNordblom!
