### ISSUE TITLE
Enable Experimentation Mode use in the editor

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/vscode-powershell#1767]
With PowerShell v6.2-preview4 we had this new experimental feature being enabled - https://github.com/PowerShell/PowerShell/pull/8109

Whilst I can get this working in the pwsh preview console it is not currently working within either the Console or the Editor even when I have set Vscode to use the v6.2-preview4 version 

This would be an awesome addition and would allow much easier testing as part of the authoring experience

**Comment by SydneyhSmith** [comment]
@kilasuit did you also try enabling the feature in the integrated console? To do this run 
`Enable-ExperimentalFeature` in the integrated console

**Comment by kilasuit** [comment]
I don't think I had but on testing this in 6.2 with the Experimental feature enabled this works as expected (although isn't that quick)

Using v7 preview 2 works as expected
