### ISSUE TITLE
Current master branch cannot debug PowerShell files

### ISSUE THREAD

**Issue by corbob** [PowerShell/vscode-powershell#1768]
### System Details

System Details Output
```
### VSCode version: 1.32.0-insider aeaef41d51201e555735f5e8d2f38a9d0ddb9026 x64

### VSCode extensions:
bmaupin.theme-solarized-dark-high-contrast@1.0.2
clarkio.twitch-highlighter@0.1.3
CoenraadS.bracket-pair-colorizer-2@0.0.26
DavidAnson.vscode-markdownlint@0.24.0
eamodio.gitlens@9.5.1
EditorConfig.EditorConfig@0.13.0
eg2.tslint@1.0.43
Equinusocio.vsc-material-theme@2.7.0
ms-mssql.mssql@1.4.0
ms-vscode.csharp@1.17.1
ms-vscode.PowerShell-Preview@2.0.0
ms-vscode.vscode-typescript-tslint-plugin@1.0.0
msjsdiag.debugger-for-chrome@4.11.2
rrudi.vscode-dired@0.0.4
slevesque.vscode-autohotkey@0.2.2


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18836.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18836.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with debugging PowerShell scripts when building master after commit https://github.com/PowerShell/vscode-powershell/commit/f0886cd9edf58e12c612a209b77c5140740b9ecc

Steps I  have taken to reproduce issue:

1. clone PSES Master and vscode-powershell master to fresh directories
2. In vscode-powershell directory run: `git checkout f0886cd9edf58e12c612a2`
3. Launch Extension from vscode (stable or insiders)
4. Open a PowerShell file
5. Why can't I F5???

Note: F8 works just fine.

#### Expected Behaviour

It should debug the script

#### Actual Behaviour

It doesn't appear to do anything.

### Attached Logs

[1550730182-someValue.sessionId.zip](https://github.com/PowerShell/vscode-powershell/files/2887928/1550730182-someValue.sessionId.zip)

**Comment by corbob** [comment]
Was discussing this with a coworker and I noticed this change: https://github.com/PowerShell/vscode-powershell/commit/f0886cd9edf58e12c612a209b77c5140740b9ecc#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R311 I can't fathom is being the cause, but at this point I'll take anything. Just adding this comment in case anyone else is taking a look and can test changing this line to lowercase `powershell` 🤷‍♂️

**Comment by rkeithhill** [comment]
Hmm, I'll take a look at this over the weekend.  Been busy trying to get a `posh-git 1.0.0-beta3` release ready.

**Comment by rkeithhill** [comment]
I've updated to latest on `master` and I can see my changes to package.json.  But when I debug the extension, I can debug just fine from the extension host.  Not sure what is going on but I certainly do not see say "launch" requests in your log file.  Can you describe which debug config you are using?  PoweShell Launch Current File, PowerShell Interactive Session?  Maybe you could paste the debug config json you're using here?

**Comment by rkeithhill** [comment]
Well, on my laptop I can repro this. I have a "fix" but I'd like to understand a little better why this isn't working.  Will have a PR in the next day or two.
