### ISSUE TITLE
After Modifying (and save) a Powershell script, the debugger seems to debug the old version of the file

### ISSUE THREAD

**Issue by Delamater** [PowerShell/vscode-powershell#1770]
VS Code Version: 1.3.1
Powershell (ms-vscode.powershell) extension version: 1.11.0

Steps to duplicate:
1. Create a powershell script
2. Debug it, it works fine, no problems
3. Modify the script in step 1 in some way
4. Save the modification
5. Attempt to debug it again. Even though the file was saved, the code previously written is what the debugger is using. 

Workaround: 
Close Visual Studio Code and relaunch. 

Is this an issue, or am I making a silly mistake? In my case, I have two Powershell scripts. One of them imports the other module and the debugger steps into it from the first script.

**Comment by Delamater** [comment]
Update: 

Another workaround is to kill the Powershell Terminal. When you do that VS Code will ask you to restart the terminal, say yes. 

At least this way you don't have to relaunch VS Code as administrator in the event your development code needs that.

**Comment by SydneyhSmith** [comment]
@Delamater thanks for reporting this!  I am having some trouble re-producing this so it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) so we can better track down the issue...or if you could include a GIF showing this issue, that would also be great!

**Comment by Delamater** [comment]
Hi @SydneyhSmith ,

Sure thing. Attached are the logs. 

File 1 looks like this: 
Import-Module .\SomeScript.ps1
Function-Foo

File2 has the function in it. I don't think it matters what code is in file 2. Simply write something, then debug it once. Then change the code and try to debug it again without killing the Powershell terminal window. 

Hope this helps. 


[logs.zip](https://github.com/PowerShell/vscode-powershell/files/2891528/logs.zip)

**Comment by rkeithhill** [comment]
Ah, so what is going on here is that the debugger runs in the context of the PowerShell Integrated Console.  IOW the debug "context" carries from one debug session to the next.  So when you debug the first time, your module is imported.  The second time you debug, the module is already imported so the line that imports the module does nothing. It's a no-op.  This is just like debugging in the console.  You have manually remove the module OR use `-Force` when you import the module to get PS to reload the potentially updated module.  

Note: if you module adds .NET types via Add-Type, you CANNOT reload that module unless you rename your types. This is one of several reasons I personally don't like the default debug behavior. I much prefer debugging in a *clean session* every time.  But in our efforts to be more like ISE, the current behavior became the default.  You might try the debug config file option: 
```
createTemporaryIntegratedConsole": true
```
Unfortunately there seems to be some bugs with this option.  It needs some TLC.

**Comment by rkeithhill** [comment]
Unfortunatley this behavior is "by design".  I suggest you use `Import-Module .\SomeScript.psm1 -Force`.
