### ISSUE TITLE
PowerShell console colors behave like the stand alone powershell console in Windows 10.

### ISSUE THREAD

**Issue by ChadThomsen** [PowerShell/vscode-powershell#1777]
**Summary of the new feature**

Since I upgraded from Windows 7 to Windows 10 on my company laptop I noticed the colors of the standalone PowerShell console change as you type stuff in depending on what you are typing which is a nice feature.  PowerShell Integrated Console is in all plain white, and the only color is red if my script runs and throws an error.  I reviewed the PSreadline stuff and that does not seem to apply here, but I could be using wrong?  I am currently using "Dark+ (default dark)" theme. 

**Proposed technical implementation details (optional)**

**Comment by rjmholt** [comment]
The highlighting is indeed provided by [https://github.com/lzybkr/PSReadLine](PSReadLine).

That's tracked by https://github.com/PowerShell/vscode-powershell/issues/535.

PSReadLine functionality is currently available in the extension by installing the preview version, available as a separate VSCode extension called [`powershell-preview`](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview). If you find that in the marketplace, it should have all the instructions in the README.
