### ISSUE TITLE
#1777 - Issue was closed but not resolved. 

### ISSUE THREAD

**Issue by ChadThomsen** [PowerShell/vscode-powershell#1778]
https://github.com/PowerShell/vscode-powershell/issues/1777 - Is not resolved.   See comments below.  

I loaded the powershell-preview and the integrated console for powershell does NOT have the coloring that is found with PSReadLine.   When Powershell loads, it does load another console session of powershell, and that does have the PSReadline coloring.  Not sure why it launches two terminals either.  Is there a setting I can disable the one that is not the "integrated one" assuming we can get the coloring working for the "integrated one"?   Keep up the great work!  Thanks!

**Comment by rkeithhill** [comment]
Even with the preview, I think you still have to enable the PSReadLine experimental feature with the setting:
```
"powershell.developer.featureFlags": [ "PSReadLine" ]
```

**Comment by ChadThomsen** [comment]
That worked!!  Thanks again!

Thanks,

Chad Thomsen

**Comment by rjmholt** [comment]
Looks like we need some better documentation here. I know we insert a snippet into the README, but we need to write up some stuff into the repo README I think. I know @TylerLeonhardt's written a blog post somewhere

**Comment by SydneyhSmith** [comment]
We mention the steps in this blog post: https://devblogs.microsoft.com/powershell/announcing-the-powershell-preview-extension-in-vscode/ but yes-there is definitely room for improvement in documenting this

**Comment by TylerLeonhardt** [comment]
We might be able to have this feature flag enabled by default for only Windows
