### ISSUE TITLE
Integrated terminal not loading

### ISSUE THREAD

**Issue by Szeraax** [PowerShell/vscode-powershell#1789]
Issue Type: <b>Bug</b>

I believe same issue as #1721 (https://github.com/PowerShell/vscode-powershell/issues/1721)

Close everything in VSCode. Right click a .ps1 file and select "Open with Code". Integrated terminal doesn't load and running restart terminal has an error. after closing the file, opening VSCode, opening a folder, and selecting a ps1 file, it loads. And forever loads even if I close the folder. Or the file. Or everything and right click the file to select "Open with Code" again. Good to know that its a 1 time error per install. 

Extension version: 2.0.0
VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (27.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by TylerLeonhardt** [comment]
Yes, this sounds like the same issue. This is fixed in the next version which should come out in the next couple weeks. Stay tuned!

**Comment by SydneyhSmith** [comment]
@Szeraax we have released the update, if you haven't already would you mind updating, and letting us know if you still hit the issue?

**Comment by SydneyhSmith** [comment]
Closing this issue as resolved by the last update will re-open if this is still an issue.
