### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by jahshuah** [PowerShell/vscode-powershell#179]
Maybe I'm new, maybe I missed something, but I cannot for the life of me figure out how to get Intellisense working with this extension. I'm running VSCode on a new Win 10 build (installed yesterday) and the latest version of both VSCode and the PowerShell extension.

Any help on what I might be doing wrong would be greatly appreciated. Thanks!

**Comment by daviwil** [comment]
Hey @jahshuah, no problem.  The first thing we should do is check the logs.  Open up your VS Code User Settings (`File -> Preferences -> User Settings`) and insert this line into the file that appears in the pane on the right side:

`"powershell.developer.editorServicesLogLevel": "Verbose"`

Now restart VS Code and open a PowerShell file and try getting IntelliSense a few times.  Now you should be able to navigate to this path on your hard drive:

`c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell-0.6.0\bin`

There should be a file there called `EditorServices.log`.  Could you drag and drop it into your reply to this issue?

**Comment by jahshuah** [comment]
So, it took restarting VSCode twice to get IntellSense working, but it works now. You'll find the EditorServices.log file attached. Not sure what changed after the second restart of VSCode, but as I said, it's working now. Th

anks for the assist.
[EditorServices.txt](https://github.com/PowerShell/vscode-powershell/files/264670/EditorServices.txt)

**Comment by daviwil** [comment]
Yep the logs look good to me now.  Not sure why you needed to restart VS Code a couple of times, but I've seen instances where a fresh install of the extension doesn't get activated correctly the first time.  Not sure if it's a VS Code bug or something else.

I'll close this issue for now since it seems to be working for you.  Let me know if you run into it again and we'll debug it further!

**Comment by daviwil** [comment]
Hey @jahshuah, turns out that there's actually a bug here due to a timing issue in initialization.  Since it's likely that you'll see this happen again I just wanted to let you know that I'm looking into it.  Tracking the fix using bug #183.

**Comment by jahshuah** [comment]
@daviwil You're so right. I just opened VS Code and sure enough, no IntelliSense. I'll follow #183 going forward. Thanks again for your help.

**Comment by daviwil** [comment]
Just fixed it!  Will be shipping an update in an hour or two.
