### ISSUE TITLE
PowerShell Preview Does Not Load Integrated Terminal

### ISSUE THREAD

**Issue by HJLBX** [PowerShell/vscode-powershell#1795]
Issue Type: <b>Bug</b>

PowerShell extension is disabled. But it doesn't matter because get the same result whether it is installed and disabled or uninstalled.

After installing PowerShell Preview v2.0.0-preview.1, select PowerShell Command Explorer.

Nothing loads.

And get the following message:

"There is no data provider registered that can provide view data."

Extension version: 2.0.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (6.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by TylerLeonhardt** [comment]
Did you open an empty workspace or a folder when you opened vscode?

There's currently a bug in Preview that is fixed and pending a deployment that will fix this issue.

**Comment by Cazs03** [comment]
Same here

**Comment by tmknight** [comment]
![image](https://user-images.githubusercontent.com/548588/55417601-0499ce00-553f-11e9-9c8e-997195f9cd92.png)

I experience PowerShell Integrated not fully loading.  It requires, placing focus on the terminal and hitting ENTER x2
![image](https://user-images.githubusercontent.com/548588/55417533-de742e00-553e-11e9-892b-4f47abd14373.png)

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by tmknight** [comment]
Additional info: If you kill the PS Integrated Terminal and reload it, it will completely load without issue.

**Comment by rjmholt** [comment]
@tmknight Thanks for that info. I believe this is a Windows bug that VSCode itself has been trying to fix. The fact that it occurs outside of the extension means I don't think we can do much about it on our side.

@HJLBX, @Cazs03 can you let us know if you're seeing similar behaviour to this? If so, the fix will lie with Windows Update and the next VSCode release.

**Comment by SydneyhSmith** [comment]
VSCode 1.35 should mean that this issue is fixed so I am going to go ahead and close it --please let us know if you are still hitting this issue and we will reopen/investigate further
