### ISSUE TITLE
Refresh Explorer Causes an Extension Error Message

### ISSUE THREAD

**Issue by HJLBX** [PowerShell/vscode-powershell#1797]
Issue Type: <b>Bug</b>

Refreshing the Explorer generates an error message:

https://imgur.com/a/Y0tSK4B

Extension version: 1.11.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (6.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by SydneyhSmith** [comment]
Thanks for reporting this issue @HJLBX--it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by HJLBX** [comment]
Hello Sydney,

This is the result of deleting the PoSH ISE using the trash can in the terminal window and then immediately after using the command list refresh button.

Since the ISE is not to be deleted, I'm thinking this issue is not a bug.

**Comment by rkeithhill** [comment]
Agreed.  If you kill the PS Integrated Console then you will get various errors because it houses most of the functionality of the PowerShell extension.
