### ISSUE TITLE
When the language service crashes, show a message that tells user where to find the logs

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#18]
Right now when the language service crashes the user has no idea that it has happened.  They just see that features have generally stopped working.  There needs to be some kind of indication that an error occurred so that the user can check the log file and potentially send it in for analysis.

**Comment by tylerl0706** [comment]
This for sure is fixed, right? I get a pop up that says it crashed and even a button to show the output.

**Comment by tylerl0706** [comment]
I spent a solid 10min trying to get PSES to crash... couldn't do it :)

**Comment by tylerl0706** [comment]
I'm gonna close this since we have the button that shows the output
