### ISSUE TITLE
syntax highlighting bug with #Requires -Modules

### ISSUE THREAD

**Issue by Conan1989** [PowerShell/vscode-powershell#1814]
Issue Type: <b>Bug</b>

Hi,

For the following
#Requires -Modules  ('Hyper-V', 'FailoverClusters')

Looks like the "-v" part of "Hyper-V" module name isn't bening coloured correctly.

Screenshot shows it well

Extension version: 1.11.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (11.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Conan1989** [comment]
![vscode powershell](https://user-images.githubusercontent.com/6946596/55069929-d8122c00-50d0-11e9-8b4e-32097827d7c3.png)

See how the -v part on line 2 is coloured green

**Comment by rkeithhill** [comment]
The syntax highlighting feature is maintained in a separate repo and IIRC ships directly with VSCode to provide PowerShell syntax even when you don't have this extension installed. Can you submit this issue to the https://github.com/powershell/editorsyntax project?
