### ISSUE TITLE
No PSReadLine Colors

### ISSUE THREAD

**Issue by HJLBX** [PowerShell/vscode-powershell#1824]
Issue Type: <b>Bug</b>

Once again, no PSReadLine colors showing in this latest extension.

I am assuming that PSReadLine is a full replication of the PSReadLine in the Windows-based PowerShell console.

No colors, it's no use to me.

Extension version: 2.0.1
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (6.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rkeithhill** [comment]
Do you have the developFlags configured to add PSReadLine? 
```
    "powershell.developer.featureFlags": [ "PSReadLine" ],
```
This preview was supposed to enable this feature by default but that apparently isn't working as intended.  With this setting, I see PSRL working w/colors:

![image](https://user-images.githubusercontent.com/5177512/55271599-0cbee880-5275-11e9-84e7-c9ff7df99fec.png)

**Comment by HJLBX** [comment]
And how do you set the developer flags? Documentation ?

**Comment by corbob** [comment]
You would set it in one of your settings.json files (workspace or user settings). The original announcement is here: https://devblogs.microsoft.com/powershell/announcing-the-powershell-preview-extension-in-vscode/

**Comment by HJLBX** [comment]
That just says to put it into a json file. Where is the step-by-step, how to documentation ?

**Comment by corbob** [comment]
https://code.visualstudio.com/docs/getstarted/settings has information about the settings files.

**Comment by rkeithhill** [comment]
PSReadLine and colors are available if the feature flag for PSReadLine has been enabled for the preview.
