### ISSUE TITLE
CodeLens Crashing Integrated Terminal

### ISSUE THREAD

**Issue by BruceAWilliams** [PowerShell/vscode-powershell#1826]
### System Details

System Details Output
```

```

### Issue Description

I am experiencing a problem with...

#### Expected Behaviour

-- Description of what *should* be happening --

#### Actual Behaviour

-- Description of what actually happens --

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
Not enough info.
