### ISSUE TITLE
bruce.williams@outlook.com

### ISSUE THREAD

**Issue by BruceAWilliams** [PowerShell/vscode-powershell#1828]
CodeLens is causing interactive powershell console   
This is similar to #887

**Comment by BruceAWilliams** [comment]
I'm wondering if a solution for this issue has been found.
I'm seeing the same behavior both with code in the repo (github and Enterprise), it seems to have just started a week ago or so, after adding the latest upgrade. The video shown here is the same thing i'm seeing. 

* PS> [system.environment]::OsVersion.Version *
Major  Minor  Build  Revision
-----  -----  -----  --------
6      3      9600   0

* PS> code -v *
1.32.3
a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
x64

* $PsVersionTable *

Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

* $pseditor.EditorServicesVersion  *
Major  Minor  Build  Revision
-----  -----  -----  --------
1      12     0      0

I have logfiles and gifs but I'm not able to attach them

**Comment by BruceAWilliams** [comment]
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3026979/EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3026980/vscode-powershell.log)
![2019-03-31_10-22-05](https://user-images.githubusercontent.com/15788723/55292870-6cbca880-53b5-11e9-9138-067bfd2a97dd.gif)

**Comment by BruceAWilliams** [comment]
@johlju

**Comment by rkeithhill** [comment]
This issue has sufficient info/details.  Why did you close it?
