### ISSUE TITLE
Timing issue in LanguageServer initialization

### ISSUE THREAD

**Issue by selfvoid** [PowerShell/vscode-powershell#183]
[Like was here](https://github.com/PowerShell/vscode-powershell/issues/179)
On Windows 10 and latest VS Code and PowerShell extension.

[Got log like in this comment](https://github.com/PowerShell/vscode-powershell/issues/179#issuecomment-219232869) (attached)

[EditorServices.txt](https://github.com/PowerShell/vscode-powershell/files/264996/EditorServices.txt)

But, unfortunately double app restart and computer restart not solve the problem.

Please, give an advise how to get intellisense working. Thanks.

p.s.: debug is working properly

**Comment by daviwil** [comment]
Thanks for the report, @selfvoid!  @rkeithhill is able to reproduce the same issue.  This appears to be a timing issue in the initialization of the language server.  I think I should be able to reproduce this issue consistently enough to work on a fix.  Will ship an updated version of the extension this week with this issue resolved.

**Comment by daviwil** [comment]
Fixed in PowerShell Editor Services, update coming out today.

**Comment by daviwil** [comment]
Just shipped the 0.6.1 update, let me know if things are working right for you now!
