### ISSUE TITLE
Feature request: Line breaks after separators in code formatting

### ISSUE THREAD

**Issue by huettenhain** [PowerShell/vscode-powershell#1836]
**Option to insert a line break after separators in PowerShell code formatting:**

I am suggesting an option for the PowerShell code formatter that allows to insert line breaks after each separator. For example, the following code:
```
$foo=9;$bar=10;
```
currently becomes formatted as follows with the default settings:
```
$foo = 9; $bar = 10;
```
Enabling line breaks after separators should produce the following result instead:
```
$foo = 9;
$bar = 10;
```

**Comment by rkeithhill** [comment]
Code formatting is provided by the PSScriptAnalyzer. Please submit this issue to that repo https://github.com/powershell/scriptanalyzer

**Comment by huettenhain** [comment]
this went here: https://github.com/PowerShell/PSScriptAnalyzer/issues/1203
