### ISSUE TITLE
PowerShell extension 2.0.1. preview 2 fails to load

### ISSUE THREAD

**Issue by TheUntouchable** [PowerShell/vscode-powershell#1841]
```

### OS: WinSrv 2016 1607

### VSCode version: 1.32.3 a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4 x64

### VSCode extensions:

DotJoshJohnson.xml@2.4.0
ms-vscode.powershell-preview@2.0.1


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14393.2828
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2828
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

After installing the latest preview, I got the following errors:

1. PowerShell Intergrated Console:
An error occurred while starting PowerShell Editor Services:

```
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
   at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
```

2.  After some time I got that error message:

```
2019-4-3 10:27:21 [NORMAL] - Visual Studio Code v1.32.3 64-bit
2019-4-3 10:27:21 [NORMAL] - PowerShell Extension v2.0.1
2019-4-3 10:27:21 [NORMAL] - Operating System: Windows 64-bit
2019-4-3 10:27:21 [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
2019-4-3 10:27:21 [NORMAL] - Language server starting --
2019-4-3 10:27:21 [NORMAL] -     exe: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
2019-4-3 10:27:21 [NORMAL] -     args: C:\Users\admbloechmi\.vscode\extensions\ms-vscode.powershell-preview-2.0.1\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2.0.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\admbloechmi\.vscode\extensions\ms-vscode.powershell-preview-2.0.1\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\admbloechmi\.vscode\extensions\ms-vscode.powershell-preview-2.0.1\logs\1554280041-8377f28a-d51c-4b22-95f5-5430daa0a9df1554280038778\EditorServices.log' -SessionDetailsPath 'C:\Users\admbloechmi\.vscode\extensions\ms-vscode.powershell-preview-2.0.1\sessions\PSES-VSCode-13828-457692' -FeatureFlags @()
2019-4-3 10:27:21 [NORMAL] - powershell.exe started, pid: 1624
2019-4-3 10:29:21 [NORMAL] - Language server startup failed.
2019-4-3 10:29:21 [ERROR] - The language service could not be started: 
2019-4-3 10:29:21 [ERROR] - Timed out waiting for session file to appear.
```

1.X extension is not installed.

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by TheUntouchable** [comment]
Sadly I can only reproduce that error at work.. And the next time I am there is on monday.. :(

**Comment by TheUntouchable** [comment]
This is all I could get, hope it helps!

`VERBOSE: 
#-- Console Encoding ---------------------------------------------------------
VERBOSE: System.Text.ASCIIEncoding
VERBOSE: 
#-- Updated PSModulePath to: -------------------------------------------------
VERBOSE: C:\Users\admbloechmi\Documents\WindowsPowerShell\Modules
VERBOSE: C:\Program Files\WindowsPowerShell\Modules
VERBOSE: C:\Windows\system32\WindowsPowerShell\v1.0\Modules
VERBOSE: C:\Program Files\AppFabric 1.1 for Windows Server\PowershellModules
VERBOSE: c:\Users\admbloechmi\.vscode\extensions\ms-vscode.powershell-preview-2.0.1\modules
VERBOSE: 
#-- Check required modules available -----------------------------------------
VERBOSE: Testing module availability PowerShellGet 
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1'.
VERBOSE: PowerShellGet  found
VERBOSE: 
#-- Start up PowerShellEditorServices ----------------------------------------
VERBOSE: Importing PowerShellEditorServices
VERBOSE: Loading module from path 'C:\Users\admbloechmi\.vscode\extensions\ms-vscode.powershell-preview-2.0.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'.
VERBOSE: Loading module from path 'C:\Users\admbloechmi\.vscode\extensions\ms-vscode.powershell-preview-2.0.1\modules\PowerShellEditorServices\PowerShellEditorServices.psm1'.
VERBOSE: ERRORS caught starting up EditorServicesHost
VERBOSE: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
   at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()


An error occurred while starting PowerShell Editor Services:

Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
   at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()`

**Comment by SydneyhSmith** [comment]
@TheUntouchable This might be caused by anti-virus, which we'll have a fix for in the coming release. See https://github.com/PowerShell/vscode-powershell/issues/1831

However, the specific assembly/type loading problem looks like it might not be caused by that. To get the reason why it's failing, you'll need to collect a fusion log using [these instructions](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer). That should give you a pretty good explanation of precisely why the assembly isn't loading. Please try that and let us know here.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
