### ISSUE TITLE
When open Powershell files, it crashes

### ISSUE THREAD

**Issue by w-Yuan** [PowerShell/vscode-powershell#1848]
Issue Type: <b>Bug</b>

Go to a folder and try to open a powershell files. It crashes and asks for reopen or close. 

Extension version: 1.12.0
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:46.685Z)
OS version: Windows_NT ia32 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz (16 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (16.88GB free)|
|Process Argv|analog\Input\Eyes\Tools\ETN|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by Tadimsky** [comment]
I'm having the same issue.
I attached my logs here - it doesn't look like it has much of interest though.

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/3049896/logs.zip)

**Comment by w-Yuan** [comment]
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/3050049/logs.zip)

Hope this will be helpful. If enable powershell extension, I will not be able to open VSCode as it keeps crashing.

**Comment by TylerLeonhardt** [comment]
Are any of you opening files/folders with UNC paths?

**Comment by hypercube33** [comment]
I specifically am working on files that sit on a unc path almost exclusively.

**Comment by TylerLeonhardt** [comment]
That's being tracked with https://github.com/PowerShell/vscode-powershell/issues/1830
Fixed in https://github.com/PowerShell/PowerShellEditorServices/pull/908
