### ISSUE TITLE
How to prevent code formatting "findstr--->findstr.exe"

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/vscode-powershell#1849]
vscode version = 1.33
powershell version = win10-17763.379

In my path there is grep.exe findstr.exe
My ps1 code will be formatted incorrectly.
ps | grep xxx ---->ps | grep.exe xxx
Findstr ---->findstr.exe
I need block this formatting rule.
Also, keep this code formatted  "? --->where-object"

I put PSScriptAnalyzerSettings.psd1 to：
both
 ```
c:\Users\userabcd\.vscode\extensions\ms-vscode.powershell-1.12.0\modules\PSScriptAnalyzer\1.18.0\Settings\PSScriptAnalyzerSettings.psd1
```
and
```
c:\Users\userabcd\.vscode\extensions\ms-vscode.powershell-1.12.0\modules\PSScriptAnalyzer\1.18.0\PSScriptAnalyzerSettings.psd1
```
Text content：
```
@{
    Severity=@('Error','Warning')
    ExcludeRules=@(' PSAvoidUsingCmdletAliases '  =  @ {
             ' Whitelist '  =  @（' cd '）
    })
}
```
rerurn format crlf,file format utf8+bom.
but ,dont work.
**Can't stop this formatting  "? --->where-object"**

Q1：Where is the default path for PSScriptAnalyzerSettings.psd1?
i no set powershell.scriptAnalysis.settingsPath
Q2：How to write exclusion rules?

Q3：Which exclusion rule meets my needs?

**Comment by mkht** [comment]
@chuanjiao10 
I am able to reproduce it.
This issue is related #1842 (and there is some duplication)

My testing code before formatting
```PowerShell
gci -Path $TempFile | ? { test-path -Path $_ -PathType Leaf } | % { get-content $_ } | findstr 'aaa'
```

This code is formatted by vscode-powershell@1.12.0.
```PowerShell
Get-ChildItem -Path $TempFile | Where-Object { Test-Path -Path $_ -PathType Leaf } | ForEach-Object { Get-Content $_ } | findstr.exe 'aaa'
```

<details><summary>Testing environment</summary>
<p>

### Operating system
```
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### VSCode version: 1.33.0 0dd516dd412d42323fc3464531b1c715d51c4c1a x64

### VSCode extensions:
ms-vscode.powershell@1.12.0

### PSES version: 1.12.0.0

### PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

</p>
</details>

### Attach logs
[Logs.zip](https://github.com/PowerShell/vscode-powershell/files/3050166/Logs.zip)

**Comment by blairconrad** [comment]
Excuse my ignorance, but I assume that the same code that's adding extensions to my executables is responsible for removing the explicit path to those executables?

e.g.
`D:\bconrad\bin\backup.py` → `backup.py`

**Comment by rjmholt** [comment]
> Excuse my ignorance, but I assume that the same code that's adding extensions to my executables is responsible for removing the explicit path to those executables?
>
> e.g.
> D:\bconrad\bin\backup.py → backup.py

Would you be able to open a new issue with a full repro for that? I can't reproduce it on my machine currently using the PSSA formatter

**Comment by rkeithhill** [comment]
That is a known issue that has been submitted to the PSSA project - https://github.com/PowerShell/PSScriptAnalyzer/issues/1206.  Please upvote the issue there.
