### ISSUE TITLE
winpty-agent.exe trig Cynet Antivirus False positive.

### ISSUE THREAD

**Issue by da9l** [PowerShell/vscode-powershell#1853]
System Details Output
```

### VSCode version: 1.32.3 a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4 x64
n### VSCode extensions:n2gua.rainbow-brackets@0.0.6
danmannock.vscode-fsharp-refactor@0.5.5
EditorConfig.EditorConfig@0.13.0
evilz.vscode-reveal@3.4.0
fernandoescolar.vscode-solution-explorer@0.3.1
Gruntfuggly.todo-tree@0.0.126
hbenl.vscode-test-explorer@2.9.2
heaths.vscode-guid@1.4.7
Ionide.Ionide-FAKE@1.2.3
Ionide.Ionide-fsharp@3.35.0
Ionide.Ionide-Paket@1.12.0
jebbs.plantuml@2.10.9
mdickin.markdown-shortcuts@0.11.0
ms-mssql.mssql@1.5.0
ms-vscode.csharp@1.18.0
ms-vscode.powershell@1.12.0
PeterJausovec.vscode-docker@0.6.1
shd101wyy.markdown-preview-enhanced@0.3.13
zhuangtongfa.Material-theme@2.21.0

n### PSES version:
n### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When I install Powershell extension version 1.12.0 I get a Cynet Alert Notification (antivirus). Most likely a false positive. It disappear when I uninstall the plugin.

The specific file it reacts on is `...\microsoft vs code\...\node-pty\build\release\winpty-agent.exe`

![2019-04-08 10_41_02-npm](https://user-images.githubusercontent.com/146797/55710721-87ad9f00-59eb-11e9-86e7-ded64a1993b8.png)

I'd guess that this can be closed if it is verified that this file comes from a trusted source.

#### Expected Behaviour

There should be no antivirus warning

#### Actual Behaviour

Attached antivirus warning pops up.

### Attached Logs

See image.

**Comment by TylerLeonhardt** [comment]
win-pty-agent.exe is used by vscode for the consoles. Without this, you can't show the PowerShell console in vscode.

Even though this is issue would show up when using the PowerShell extension, it's actually a [vscode](https://github.com/Microsoft/vscode)... Or rather... A [winpty](https://github.com/rprichard/winpty) issue. You should probably open this over there. 

Also, `winpty` is on its way out within vscode. The 1.33 version of vscode enables a built-in (to Windows) pty called `conpty`. I believe that if you grab the latest vscode, you shouldn't see this issue.

cc @Tyriar who knows a lot more about vscode's terminal implementation

**Comment by rkeithhill** [comment]
VSCode 1.33 will use conpty if you are Windows 10 >= 18309 IIRC.  So you'd have to be on a Windows 10 Insider build at least for another month or so until 1903 is released.

**Comment by da9l** [comment]
I'm on 1803/17134 so I guess I have to wait. 
Just for the record, the problem did not go away by upgrading vscode to 1.33.

Thanks for looking into this!

**Comment by TylerLeonhardt** [comment]
I think we can close this now since you have an issue opened on winpty and it's not something the PowerShell extension can help with.
