### ISSUE TITLE
Integrated Powershell terminating upon starting

### ISSUE THREAD

**Issue by rayholtz** [PowerShell/vscode-powershell#1855]
Issue Type: <b>Bug</b>

All I have to do is start VSCode and I get a popup message at the bottom right corner of the application: 

"The PowerShell session has terminated due to an error, would you like to restart it?
Source: Powershell (Extension)"

Clicking Yes tries to restart the Powershell Integrated Console, but then it terminates again.

I enabled Verbose logging in the Powershell Extension.  Here are the logs.  There is an error near the bottom of the 'EditorServcies.log' file.

[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3055031/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3055032/EditorServices.log)

Here are the versions of code, extensions, and powershell:
[Versions.txt](https://github.com/PowerShell/vscode-powershell/files/3055098/Versions.txt)

Extension version: 1.12.0
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by SydneyhSmith** [comment]
Your error looks similar to this (one)[https://github.com/PowerShell/vscode-powershell/issues/1830#issuecomment-479205787] are you on a network share or  is your environment restricted in any way (group policy etc.)?

**Comment by rayholtz** [comment]
Thank you @SydneyhSmith 
I do save all my powershell scripts from my user directory on a network share.  I copied a script to my C: Drive to open it, and Powershell did not crash within VSCode.  It does seem like its the same issue as you linked #1830.
I will close this issue, and comment on that one.  Thank you for your help!

**Comment by TylerLeonhardt** [comment]
Hi all, can you try one of these builds:

[PowerShell and PowerShell Preview release candidates.zip](https://github.com/PowerShell/vscode-powershell/files/3070929/PowerShell.and.PowerShell.Preview.release.candidates.zip)

This should have the UNC path fix. Note, if you've never used the Preview extension, [look at these steps](https://devblogs.microsoft.com/powershell/announcing-the-powershell-preview-extension-in-vscode/).

If you've never installed a VSIX before, [here are the steps](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

**Comment by rayholtz** [comment]
@TylerLeonhardt The Powershell Extension v1.12.1 .vsix file installed correctly, and upon initial use seems to be working correctly, a file opened from a UNC path does not crash the Powershell extension. 
Thank you!
