### ISSUE TITLE
Script output gets mixed up with prompt when run under debugger

### ISSUE THREAD

**Issue by sba923** [PowerShell/vscode-powershell#1862]
### Issue Description

Take the following script, stored at `C:\private_sba\PowerShell\TestPowerShellDebuggerBehaviorWithPrompt.ps1`:

````
Write-Host("WH1")
Write-Host("WH2")
Write-Host("WH3")
````

If you run this via F5 in the Windows PowerShell ISE you get:

````
PS ~> C:\private_sba\PowerShell\TestPowerShellDebuggerBehaviorWithPrompt.ps1
WH1
WH2
WH3
````

But if you do the same in VScode, you get:

````
PS ~/PowerShell/work> WH1private_sba\PowerShell\TestPowerShellDebuggerBehaviorWithPrompt.ps1
WH2
WH3
````

if you're using the "PowerShell Launch Current File" configuration, and

````
PS ~/PowerShell/work> c:\private_sba\PowerShell\TestPowerShellDebuggerBehaviorWithPrompt.ps1

                      WH1
WH2
WH3
````

if you're using the "PowerShell Launch Current File w/Args Prompt" configuration.

#### Expected Behaviour

The script's output should be displayed after / below the prompt + name of script being debugged.

#### Actual Behaviour

The script's output is intermingled with the prompt / name of the script being debugged.

### Attached Logs
[PSES_logs_201904101012.zip](https://github.com/PowerShell/vscode-powershell/files/3062707/PSES_logs_201904101012.zip)

### System Details
System Details Output
```
### VSCode version: 1.33.0 0dd516dd412d42323fc3464531b1c715d51c4c1a x64

### VSCode extensions:
alefragnani.Bookmarks@10.4.2
anseki.vscode-color@0.4.5
anweber.vscode-tidyhtml@1.10.0
bierner.lit-html@1.11.0
christian-kohler.npm-intellisense@1.3.0
christian-kohler.path-intellisense@1.4.2
DavidAnson.vscode-markdownlint@0.26.0
DotJoshJohnson.xml@2.4.0
ecmel.vscode-html-css@0.2.0
eg2.tslint@1.0.43
eg2.vscode-npm-script@0.3.5
esbenp.prettier-vscode@1.8.1
Flixs.vs-code-http-server-and-html-preview@2.2.2
generalov.vscode-tfs@1.0.1
GrapeCity.gc-excelviewer@2.1.32
Gruntfuggly.todo-tree@0.0.126
hdg.live-html-previewer@0.3.0
hnw.vscode-auto-open-markdown-preview@0.0.4
HookyQR.beautify@1.4.11
idleberg.nsis@3.16.1
ionutvmi.reg@0.0.2
manuth.markdown-converter@1.1.2
mdickin.markdown-shortcuts@0.11.0
mechatroner.rainbow-csv@1.0.0
mikeburgh.xml-format@1.0.2
mortenhenriksen.perl-debug@0.5.0
ms-vscode.cpptools@0.22.1
ms-vscode.csharp@1.18.0
ms-vscode.powershell@1.12.0
ms-vscode.powershell-preview@2.0.1
msjsdiag.debugger-for-chrome@4.11.3
nobuhito.printcode@3.0.0
redhat.java@0.42.1
swyphcosmo.spellchecker@1.2.13
VisualStudioExptTeam.vscodeintellicode@1.1.5
vscjava.vscode-java-debug@0.17.0
vscjava.vscode-java-dependency@0.4.0
vscjava.vscode-java-pack@0.6.0
vscjava.vscode-java-test@0.16.0
vscjava.vscode-maven@0.16.1
yanz.markdown-authoring@0.1.5
yuichinukiyama.vscode-preview-server@1.2.1
yzane.markdown-pdf@1.2.0
yzhang.markdown-all-in-one@2.2.0


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by PrzemyslawKlys** [comment]
Are you using PSReadLine? 

https://github.com/PowerShell/vscode-powershell/issues/1727

**Comment by sba923** [comment]
Yes I am. Debugging a PowerShell script under VScode when you have no history at the [DBG] prompt is pretty impossible if you ask me ;-)

See also #1850

**Comment by PrzemyslawKlys** [comment]
Yes, thats why I disabled PSReadline.

**Comment by SydneyhSmith** [comment]
Thanks for opening @sba923

**Comment by sba923** [comment]
> Yes, thats why I disabled PSReadline.
@PrzemyslawKlys: you got me wrong; I meant that one cannot (decently) debug under VScode _without_ PSReadline

**Comment by PrzemyslawKlys** [comment]
I see, well I am not that experienced in debugging. I am pressing F5, stop and check what's there and try again, and again :-)

**Comment by sba923** [comment]
Sure, but when you're at the [DBG] prompt, you typically want to look at multiple things one after another, so you need up/down arrow command history to run the same commands (e.g. to evaluate an expression) over and over again!

**Comment by PrzemyslawKlys** [comment]
Right now, when I touch any code while in debug (like trying to fix code when stopped VSCode crashes). Not sure why I would need to evaluate expression over and over but it may be I'm just too weak :-)

**Comment by SydneyhSmith** [comment]
Marking as fixed as the PR for this has been merged...should be available in the next update
