### ISSUE TITLE
Integrated Powershell Hangs on Get-Credential

### ISSUE THREAD

**Issue by ErvM** [PowerShell/vscode-powershell#1863]
### System Details

```
### VSCode version: 1.33.0 0dd516dd412d42323fc3464531b1c715d51c4c1a x64

### VSCode extensions:
DougFinke.vscode-PSStackoverflow@0.0.2
formulahendry.code-runner@0.9.8
ms-vscode.powershell@1.12.0


### PSES version: 1.12.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

System Details Output
```

```

### Issue Description

I am experiencing a problem when I am running my script, everytime I do a Get-Credential to login to Office365, it will hang on me. Now I want to say this was working before but for some reason it is not working now. I can copy parts of my script and put it in a new file and run it, and it will work. I have even tried just copying the text to a new file and saving it as something different, but still the issue persists.

#### Expected Behaviour

-- In Powershell ISE, it will ask me for credentials in a Credentiaol GUI window, In VSCode it will only ask for them in the terminal, but both are successful and work, well VSCode is successful when its not in my entire script.

#### Actual Behaviour

-- In VSCode it asks me for my password in the terminal, but wont let me type it in and just hangs.

![Video_2019-04-10_133812](https://user-images.githubusercontent.com/13369085/55901055-96848500-5b96-11e9-9ed7-441365eb852e.gif)

### Attached Logs

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3064897/EditorServices.log)
[Start-EditorServices-EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3064898/Start-EditorServices-EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3064899/vscode-powershell.log)

**Comment by ErvM** [comment]
Attached is my script, I think I took anything sensitive out :/


[Alpha Admin Tool - Copy.txt](https://github.com/PowerShell/vscode-powershell/files/3064920/Alpha.Admin.Tool.-.Copy.txt)

**Comment by corbob** [comment]
I can confirm this happens on latest insiders vscode with Preview extension. I have no reason why, Fluent Terminal and conemu with credential's captured in terminal don't have this issue. Ditto for Integrated Terminal provided by vscode. 

PSIC seems to be the cause, but that's about as far as I've been able to determine.

**Comment by ErvM** [comment]
I have even taken out a part of my script that calls the function that does the Get-Credential and starts a PSSession, and that works 100%, I have tried so many things to see what could be causing it, its driving me mad!

--Reply to the Ninja Edit!
I cant believe I didn't see that trashcan, that indeed kills it! Thanks for that!

**Comment by SydneyhSmith** [comment]
There is a known issue, where the dialog boxes appear behind the VSCode window, this issue is being tracked here (https://github.com/Microsoft/vscode/issues/42356), any chance this is the same issue you are facing?

**Comment by SydneyhSmith** [comment]
@ErvM sorry that you are hitting this, thanks for reporting the issue! We will try to investigate the cause.

**Comment by YohannJourniac** [comment]
I confirm i have the same problem.
Windows 7 Pro x64
Powershell 5.1
Visual Studio Code 1.36.0
PowerShell Language Support for Visual Studio Code 2019.5.0

I add Get-Credential into AddClick Button.

**Comment by bgsz** [comment]
@SydneyhSmith any update?
also ran into this problem

**Comment by Selman555** [comment]
I'm having this issue even in powershell terminal. running `Get-Credential` gives me the dialog window, but after that powershell freezes. I can't even force close the process (access denied)

**Comment by tibmeister** [comment]
This continues to be a problem.

VSCode: 1.63.2
Powershell Extension: v2021.12.0

**Comment by andschwa** [comment]
I'm going to assume this is fixed as we haven't heard back from you, thank you!
