### ISSUE TITLE
Some key combinations that use AltGr on French keyboards do not work

### ISSUE THREAD

**Issue by sba923** [PowerShell/vscode-powershell#1868]
### Issue Description

I'm running the 2.0.1 preview with PSReadLine 2.0.0 beta 4 and am experiencing the following:

- AltGr+2 (dead key) followed by SPACE yields `é~` instead of `~` (the `é` is displayed immediately, before I hit SPACE)
- AltGr+7 (dead key) followed by SPACE yields ``é` `` instead of `` ` `` (the `è` is displayed immediately, before I hit SPACE)

Workaround: Use Ctrl+Alt+2 / Ctrl+Alt+7

(I've also reported this [here](https://github.com/lzybkr/PSReadLine/issues/832))

#### Expected Behaviour

- AltGr+2 followed by SPACE should yield `~`
- AltGr+7 followed by SPACE should yield `` ` ``

#### Actual Behaviour

- AltGr+2 followed by SPACE yields ``é~``
- AltGr+7 followed by SPACE yields ``è` ``

### Attached Logs

(can't gather logs at this point -- all I get is "command 'PowerShell.OpenLogFolder' not found)

### System Details
System Details Output
```
### VSCode version: 1.33.0 0dd516dd412d42323fc3464531b1c715d51c4c1a x64

### VSCode extensions:
af4jm.vscode-m3u@1.0.0
akamud.vscode-javascript-snippet-pack@0.1.5
alefragnani.Bookmarks@10.4.3
anseki.vscode-color@0.4.5
anweber.vscode-tidyhtml@1.10.0
chenxsan.vscode-standardjs@1.2.3
christian-kohler.path-intellisense@1.4.2
DavidAnson.vscode-markdownlint@0.26.0
ecmel.vscode-html-css@0.2.0
eg2.vscode-npm-script@0.3.5
esbenp.prettier-vscode@1.8.1
GrapeCity.gc-excelviewer@2.1.32
HookyQR.beautify@1.4.11
jasonnutter.github-pr@1.0.0
mechatroner.rainbow-csv@1.0.0
ms-azure-devops.azure-pipelines@1.147.2
ms-vscode.cpptools@0.22.1
ms-vscode.csharp@1.18.0
ms-vscode.powershell@1.12.0
ms-vscode.powershell-preview@2.0.1
nobuhito.printcode@3.0.0
twxs.cmake@0.0.17

The variable '$pseditor' cannot be retrieved because it has not been set.
At line:1 char:145
+ ... how-versions | Out-String)"; "`n### PSES version: $($pseditor.EditorS ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (pseditor:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined
 

### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rjmholt** [comment]
If this is occurring the the PowerShell console host as well (with the same behaviour), it's probably best to track this in PSReadLine -- the fix will come from there

**Comment by sba923** [comment]
Yes it does also occur in the PowerShell console host, so it's definitely a PSRL issue that needs to be tracked there.

In the meantime, it does impair the VScode/PS experience, so the extension can't leave preview status until this is fixed if you ask me.

Oh BTW, the Ctrl+Alt workaround seems to work reliably in VScode, but not in the PowerShell console host, for some reason.

**Comment by SydneyhSmith** [comment]
Closing this as this is a PSRL issue, and should be tracked there...also tracking the preview status of PSRL not being ready to leave preview status here #1793 thanks!
