### ISSUE TITLE
No PowerShell is running in progress on Preview 2.0.2

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1877]
### System Details

System Details Output
```
### VSCode version: 1.33.1 51b0b28134d51361cf996d2f0a1c698247aeabd8 x64

### VSCode extensions:
aaron-bond.better-comments@2.0.3
aeschli.vscode-css-formatter@1.0.1
atomiks.moonlight@0.8.3
CoenraadS.bracket-pair-colorizer-2@0.0.28
donjayamanne.githistory@0.4.6
eamodio.gitlens@9.6.0
ecmel.vscode-html-css@0.2.0
emmanuelbeziat.vscode-great-icons@2.1.47
esbenp.prettier-vscode@1.8.1
GitHub.vscode-pull-request-github@0.6.0
GlenBuktenica.unicode-substitutions@2.0.1
HookyQR.beautify@1.4.11
johnpapa.read-time@0.2.0
johnpapa.vscode-peacock@2.1.0
Kelvin.vscode-sshfs@1.14.7
liximomo.remotefs@0.0.14
mechatroner.rainbow-csv@1.0.0
monokai.theme-monokai-pro-vscode@1.1.12
ms-vscode.powershell@1.12.0
ms-vscode.powershell-preview@2.0.2
ms-vsts.team@1.149.2
PKief.material-icon-theme@3.7.0
sdras.night-owl@1.1.3
shd101wyy.markdown-preview-enhanced@0.3.13
softwaredotcom.swdc-vscode@0.14.5
WakaTime.vscode-wakatime@1.2.14
yzhang.markdown-all-in-one@2.2.0


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

When you run a script there's no PowerShell progress information in the status bar. This makes it hard to know that something is happening.

#### Expected Behaviour

Progress was there in the earlier version.

#### Actual Behaviour

No progress.

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by rjmholt** [comment]
Thanks for opening this issue @PrzemyslawKlys.

Would you be able to attach a screenshot (ideally a comparison) of the affected behaviour?

**Comment by PrzemyslawKlys** [comment]
![Problem-VSCode](https://user-images.githubusercontent.com/15063294/56147435-8d395500-5fa8-11e9-89dd-a5b9c0b246d3.gif)

Here you go. Currently, I've reverted back to the older version.

**Comment by PrzemyslawKlys** [comment]
Just so you know, after reverting back I still had this problem and then by some dumb luck, I've highlighted code and pressed F5 to run it, and ever since it's working correctly (on the old version). I'm still a bit afraid to upgrade to a new version to not break what I have thou :)
