### ISSUE TITLE
Include App.config for mixed-mode assemblies with extension distribution

### ISSUE THREAD

**Issue by Sharpiro** [PowerShell/vscode-powershell#189]
Command:

```
$data = Invoke-Sqlcmd -Query "SELECT * FROM dbo.Configurations" -ServerInstance xx -Username xxx -Password xxx-Database xxx
```

Error:

```
Invoke-Sqlcmd : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 
4.0 runtime without additional configuration information.
```

I receive this error in VS Code w/ vscode-powershell , as well as VS tools for powershell 2013. Works fine in a normal powershell window/ISE.

[possibly related issue](https://github.com/adamdriscoll/poshtools/issues/410)

**Comment by rkeithhill** [comment]
Go to the extensions's install bin dir `$home\.vscode\extensions\ms-vscode.PowerShell-0.6.1\bin` and create a file called `Microsoft.PowerShell.EditorServices.Host.exe.config` and put this in it:
```xml
<?xml version ="1.0"?> 
<configuration> 
    <startup useLegacyV2RuntimeActivationPolicy="true">
        <supportedRuntime version="v4.0"/>
    </startup>
</configuration>
```
Save the file in UTF8 encoding.  Close VSCode, open it and try again.

**Comment by daviwil** [comment]
Damn, Keith beat me to it :)  But yes, this is the solution that the ISE uses.  I'll make sure we include this file in future releases of the extension.

**Comment by Sharpiro** [comment]
thanks for the quick response guys.  This fix worked for me.

**Comment by tylerl0706** [comment]
😃

**Comment by tylerl0706** [comment]
wait there's still more work here.

**Comment by tylerl0706** [comment]
Actually, looks like @daviwil added the file. This _is_ fixed 😄 

context: https://github.com/PowerShell/vscode-powershell/issues/232
