### ISSUE TITLE
PowerShell Integrated Console hanging

### ISSUE THREAD

**Issue by johnnolanilim** [PowerShell/vscode-powershell#1912]
### System Details

System Details Output
```
### VSCode version: 1.33.1 51b0b28134d51361cf996d2f0a1c698247aeabd8 x64

### VSCode extensions:
DotJoshJohnson.xml@2.4.0
formulahendry.code-runner@0.9.8
GrapeCity.gc-excelviewer@2.1.32
howardzuo.vscode-favorites@1.4.0
ms-mssql.mssql@1.6.0
ms-vscode.csharp@1.19.0
ms-vscode.powershell@1.12.1


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

The Powershell Integrated Console hangs on startup and never loads.

#### Expected Behaviour

It should start.

#### Actual Behaviour

From the verbose log:
`#-- Waiting for EditorServicesHost to complete execution ---------------------`

The task never completes, and so the console never starts.

I've tried uninstalling and reinstalling the extension, but no impact.

![image](https://user-images.githubusercontent.com/22317873/56598489-7cae5d80-65ec-11e9-9db4-22fb42d28b5b.png)

### Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/3108192/logs.zip)

**Comment by SydneyhSmith** [comment]
@johnnolanilim sorry to hear that you are having this issue, thanks for reporting it--is the device you are using, restricted or locked down in anyway, for example with Group Policy?

**Comment by johnnolanilim** [comment]
@SydneyhSmith Yes, it's a corporate machine, so is restricted though group policy, etc. It worked as recently as last week, however.

I'm perfectly prepared to accept that this is something down to my environment, but I was hoping to be able to do some more digging before getting to that point.

**Comment by SydneyhSmith** [comment]
@johnnolanilim one thing to try is this: https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-6#installing-the-powershell-extension-on-restricted-systems 
It seems like your issue is likely related to https://github.com/PowerShell/vscode-powershell/issues/1626#issuecomment-476859102

**Comment by johnnolanilim** [comment]
@SydneyhSmith I'm able to import that step without any issues or being prompted, so don't think that's at fault.

I was able to uninstall my user version and get the system version installed, but I still see the same symptoms, so it's entirely possible that there's something weird going on with my system.

**Comment by johnnolanilim** [comment]
@SydneyhSmith Actually, I've just tried installing PS Core and point VS Code to that, as recommended [here](https://github.com/PowerShell/vscode-powershell/issues/1626#issuecomment-476680429), and that appears to be working.

It's not perfect, as I'd prefer to be pointing at Windows Powershell rather than PS Core, but it's a lot better than nothing.

Really, I probably need to wait until the logging is improved, as suggested by rjmholt.

**Comment by SydneyhSmith** [comment]
@johnnolanilim thanks for trying those workarounds, I am going to close this item and continuing tracking the issue with #1626
