### ISSUE TITLE
PSD1 files used for DSC Configuration Data showes script analyser error for whole file

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/vscode-powershell#192]
Currently if you open a PSD1 file that is used to pass configuration data to a DSC configuration (as per the [guidance on how to handle configuration data](https://msdn.microsoft.com/en-us/powershell/dsc/configData)) when I open these in VS Code I get the below error about it not being a valid manifest. 

![image](https://cloud.githubusercontent.com/assets/1332611/15411337/906cfcc0-1e62-11e6-89fa-76e5c358c547.png)

We need some mechanism for the PowerShell extension to not treat these like a normal module manifest. Either implicitly (if it sees a hashtable with AllNodes or NonNodeData perhaps?) or some mechanism that we can put at the top of the file or something to tell the analyzer to treat the file differently so the entire thing isn't underlined in green.

**Comment by daviwil** [comment]
Hey Brian, this marker is coming from PSScriptAnalyzer.  It seems that the [PSMissingModuleManifestField](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Rules/MissingModuleManifestField.cs) rule is not checking whether a .psd1 file is not actually a module manifest file.  Could you file this as an issue over at the PSScriptAnalyzer repo?

https://github.com/PowerShell/PSScriptAnalyzer/issues

/cc @kapilmb

**Comment by rkeithhill** [comment]
This issue has already been submitted for PSScriptAnalyzer.  See  https://github.com/PowerShell/PSScriptAnalyzer/issues/472

**Comment by daviwil** [comment]
Ahhh, thank you!  I could have sworn I had seen one before but couldn't find it...  I'll close this issue since there's already an issue tracking the bug.

**Comment by rkeithhill** [comment]
@BrianFarnhill For now you can create a file like this and put in your home folder or elsewhere:

```powershell
# The PowerShell Script Analyzer will generate a warning
# diagnostic record for this file due to a bug -
# https://github.com/PowerShell/PSScriptAnalyzer/issues/472
@{
    # Only diagnostic records of the specified severity will be generated.
    # Uncomment the following line if you only want Errors and Warnings but
    # not Information diagnostic records.
    #Severity = @('Error','Warning')

    # Analyze **only** the following rules. Use IncludeRules when you want
    # to invoke only a small subset of the defualt rules.
    IncludeRules = @('PSAvoidDefaultValueSwitchParameter',
#                     'PSMissingModuleManifestField',
                     'PSReservedCmdletChar',
                     'PSReservedParams',
                     'PSShouldProcess',
                     'PSUseApprovedVerbs',
                     'PSUseDeclaredVarsMoreThanAssigments')

    # Do not analyze the following rules. Use ExcludeRules when you have
    # commented out the IncludeRules settings above and want to include all
    # the default rules except for those you exclude below.
    # Note: if a rule is in both IncludeRules and ExcludeRules, the rule
    # will be excluded.
    #ExcludeRules = @('PSAvoidUsingWriteHost')
}
```
Then open up VSCode's User Preference Settings and add this to your user settings:
```json
    "powershell.scriptAnalysis.settingsPath": "<absolute path to the file above>",
```

**Comment by BrianFarnhill** [comment]
@rkeithhill I literally just finished doing that after reading through the related issues and PRs in the sciprt analyzer repo. Thanks for the tip guys!
