### ISSUE TITLE
Doing local PS Azure Function development - PowerShell intellisense stops working

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#1947]
In VS Code, editing a PowerShell Azure Function, `run.ps1`, in the console I run `func start`. All is good. I make edits to the `run.ps1`, the `func start` detects the change and recompiles. After a few times, the PowerShell instance for the Editor Window stops formatting the code and intellisense stops working. 

*Workaround*: Stop the `func start` and `restart the PowerShell instance`, do the `func start` again in the console.

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
