### ISSUE TITLE
Can't run PowerShell.ShowAdditionalCommands

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#195]
You need to have opened a PowerShell file before this works.

![image](https://cloud.githubusercontent.com/assets/67258/15450968/adc82208-1f7b-11e6-81b7-e65f6310b6b6.png)

**Comment by daviwil** [comment]
I'll need to find a smoother way of handling this.  Maybe if someone invokes the method I could activate the extension?  That would allow the user to get editor commands even if PowerShell files hadn't been opened yet.

**Comment by daviwil** [comment]
Also thanks to @gerane's blog post I've realized that I need to remove the PowerShell file type restriction on this command, it should be available in any file.  Probably shouldn't require editor focus either.

**Comment by tylerl0706** [comment]
Care to share that blog post? 😄 

I'm trying to hunt down this restriction you mention, @daviwil.

**Comment by rjmholt** [comment]
I think this is now fixed (to the extent we can fix it).

If you haven't opened a PowerShell, VSCode won't activate the PowerShell extension, which there's not much we can do about.

But you can open a new file (VSCode refers to them as "untitled") and set the language to PowerShell (using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>, entering the command `Change language mode` and selecting `PowerShell`).

**Comment by rjmholt** [comment]
See also https://github.com/PowerShell/vscode-powershell/issues/194
