### ISSUE TITLE
Clear-Host does not clear terminal window

### ISSUE THREAD

**Issue by AlexHimself** [PowerShell/vscode-powershell#1955]
## Issue Description ##

Clear-Host does not clear the powershell terminal window, but appears to do so. If you scroll up, there's a bunch of text that shouldn't be there.

Run the following code a couple of times and scroll around to see:

```
Clear-Host

[xml]$Doc = New-Object System.Xml.XmlDocument
$dec = $Doc.CreateXmlDeclaration("1.0","UTF-8",$null)
$doc.AppendChild($dec)
$text = @"
 
Test commment
Generated $(Get-Date)
v1.0
 
"@

$doc.AppendChild($doc.CreateComment($text))

Clear-Host

$doc.OuterXml
```

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about
capturing and sending logs.

## Environment Information ##
Windows 10 Pro (18362.86)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.33.1|
| PowerShell Extension Version | 1.12.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.18362.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.1|
|BuildVersion|10.0.18362.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.2|
|gitlens|eamodio|9.7.1|
|powershell|ms-vscode|1.12.1|
|powershellprotools|ironmansoftware|4.5.1|
|team|ms-vsts|1.149.2|
|vscode-azurefunctions|ms-azuretools|0.17.0|
|vscode-gist|kenhowardpdx|3.0.3|;

</details>

**Comment by SydneyhSmith** [comment]
Thanks for reporting this...This is not an isolated issue to the PowerShell Integrated Console issue...if you  open up a regular "PowerShell" terminal in VSCode - note that this is the PowerShell console. Execute 1..100 and then cls. Note that you can still scroll back through the terminal history. This is a function of the terminal feature in VSCode. You can clear that terminal history using Ctrl+k. See microsoft/vscode#50225 for more details.

**Comment by SteveL-MSFT** [comment]
See https://github.com/PowerShell/PowerShell/issues/8606

**Comment by TylerLeonhardt** [comment]
I have some PR's out to address this since it's highly requested - https://github.com/PowerShell/vscode-powershell/pull/2316

**Comment by fourthborngoose** [comment]
[System.Console]::Clear() should work.  Not ideal, but should still do the needful.
