### ISSUE TITLE
Add a hotkey for PowerShell.ShowAdditionalCommands

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#196]
It'd be useful to have a hotkey for the "PowerShell: Show additional commands from PowerShell modules" command which is the entry point for the editor command menu.

**FEEDBACK NEEDED:**  Any suggestions for a good hotkey?

/cc @gerane

**Comment by gerane** [comment]
I am writing a blog post right now about the new features in the Extension, and one of my recommendations is to set a Key Binding for this. It actually makes using the editor commands a real pleasure. I went ahead and added instructions to update the keybindings and what to add, but mentioned that my guess was that this would eventually be handled by the Powershell Extension itself.

The PowerShell.ShowAdditionalCommands is available for a hotkey, but just doesn't have one set by default. 

There is also an issue with instructing people to use "addi" to launch the commands. If you install an extension with conflicting command names, typing "addi" is not enough, which becomes confusing. The Go extension is a good example, when typing "addi", it is option 1.

**Comment by dfinke** [comment]
Searching for ShowAdditionalCommands  can also be a "fuzzy" search. I use `ps a`. I believe David is working to implement the custom commands at the root menu, and with shortcut keys.

**Comment by daviwil** [comment]
Yep, I am going to make that happen at some point.  In the meantime it'd be faster if there was a hotkey like `Ctrl+Shift+P` that brings you to the PowerShell-based command menu, would be faster than using the fuzzy search.

**Comment by gerane** [comment]
Well, don't set any KeyBinding that uses `ctrl+shift+alt`, it will break multiline select. I am trying out `alt+p` atm.

**Comment by tylerl0706** [comment]
This is a simple change to https://github.com/PowerShell/vscode-powershell/blob/master/package.json#L61

just need to find a good keybinding.

I'll make it up-for-grabs since it's a good "1st time contributor" issue.
