### ISSUE TITLE
Formatting a powershell script corrupts the dot sourced file paths

### ISSUE THREAD

**Issue by MarkKharitonov** [PowerShell/vscode-powershell#1967]
I have the following line in my code:
```powershell
. .\vsts\ServerSide\Get-TestResultsDir.ps1
```
After pressing Alt+Shift+F (i.e. format) it becomes
```powershell
. Get-TestResultsDir.ps1
```
I use version v1.12.1 of the extension.

P.S.
The same behavior happens if & is used instead of .

**Comment by rkeithhill** [comment]
This issue is with the PSScriptAnalyzer which this extension uses for fomatting. Looks like this issue has been reported there: https://github.com/PowerShell/PSScriptAnalyzer/issues/1206  Vote it up.
