### ISSUE TITLE
User Setting: Remember Terminal Status

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#1968]
**Summary of the new feature**

User Setting to not automatically reopen terminal on reload

**Proposed technical implementation details (optional)**

A user setting, terminal.integrated.RememberTerminalState, that will prevent the integrated terminal from reopening if it was already closed, **even if the terminal window is visible at time of reload**

Currently, when using the powershell extension, even if you have the "native" terminal closed and only had the Powershell Integrated Console open, if you issue a "Reload Window" command, the native terminal comes back, in addition to the integrated console, and both load at the same time. This has the effect of adding a lot of CPU to the startup time (and consequently several seconds) as both consoles are started.

This doesn't happen if the terminal pane was not visible at the time of reload.

This is related to https://github.com/PowerShell/vscode-powershell/issues/580, but that is the opposite problem: Remembering the status of the Powershell Integrated Terminal. It can be used as an implementation reference.

**Comment by TylerLeonhardt** [comment]
Hi @JustinGrote can you try using this setting:

```
"powershell.integratedConsole.showOnStartup": false
```

**Comment by JustinGrote** [comment]
That's for the PS integrated console. I want the opposite, for the vscode
integrated terminal to not show and only show PS into grated.

May be more appropriate for the vscode repository directly.

**Comment by rjmholt** [comment]
Ah right -- yeah I think that's most appropriate in the VSCode repo. I looked for a configuration on that briefly, but couldn't find one

**Comment by SydneyhSmith** [comment]
Going to close this, as it needs to be done on the VSCode end
