### ISSUE TITLE
In debug session, if error happened at the first part of pipeline "Please start a debug session to evaluate" shows up

### ISSUE THREAD

**Issue by vors** [PowerShell/vscode-powershell#197]
In any debug session try this

```powershell
ls fooooo | cat
Please start a debug session to evaluate
Cannot find path 'D:\dev\platyPS\test\Pester\fooooo' because it does not exist.
At line:1 char:1
+ ls fooooo | cat
+ ~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (D:\dev\platyPS\test\Pester\fooooo:String) [Get-ChildItem], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

```

Notice "Please start a debug session to evaluate" message.
Why does it appear?

**Comment by daviwil** [comment]
Hey Sergei, can you tell me the steps you took to start the debug session before running this command in the console?  The 'Please start a debug session to evaluate' message comes from VS Code so it must have thought you weren't debugging something at the moment.  Maybe you found a bug?

**Comment by daviwil** [comment]
If I open a workspace, select a .ps1 file and then press F5, a debug session starts.  If I run the same line as you did I get this output:

```
ls fooooo | cat
ls : Cannot find path 'C:\dev\vscode-powershell\examples\fooooo' because it does not exist.
At line:1 char:1
+ ls fooooo | cat
+ ~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (C:\dev\vscode-powershell\examples\fooooo:String) [Get-ChildItem], ItemN 
otFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


[DBG]: PS C:\dev\vscode-powershell\examples
```

**Comment by vors** [comment]
@daviwil interesting, indeed I cannot repro it now. Sorry for a vague repro, I though it just error handing in debug session and was too tired to analyze it more yesterday.

I did A LOT of steps. I will keep eye on it.

**Comment by daviwil** [comment]
That's OK man, definitely let me know if you see it again.  I write out debugger logs to the following path so we might be able to find something there next time:

`c:\Users\sevoroby\.vscode\extension\ms-vscode.PowerShell-0.6.1\bin\DebugAdapter.log`
