### ISSUE TITLE
vscode insists there is a parse-time error, but code executes fine

### ISSUE THREAD

**Issue by vors** [PowerShell/vscode-powershell#198]
![image](https://cloud.githubusercontent.com/assets/816680/15455839/b02dd972-2014-11e6-86f8-4c0dea84f7e4.png)

``` powershell
...
Context 'Generated markdown features' {
        function global:Test-PlatyPSFunction
        {
            param(
                [Switch]$Common,
                [Parameter(ParameterSetName="First")]
                [string]$First,
                [Parameter(ParameterSetName="Second")]

                [string]$Second
            )
        }

        It 'generate markdown with (All)' {

        }
    }
...
```

That's a weird problem.
I didn't  understand how to repro it.
Re-opening file didn't help. Re-opening VSCode did help.

**Comment by daviwil** [comment]
Hmmm...  What happens if you open the same file in the ISE?  Those errors could only be coming from the PowerShell parser of Script Analyzer

**Comment by rkeithhill** [comment]
Yeah, I was just going to suggest running script analyzer from the command line against the test script.  Also, @vors, can you check the error/warning messages <kbd>Ctrl+Shift+M</kbd>?

**Comment by vors** [comment]
So it happened again. It's clearly error from PS parser.
It repros along the lines, when you typing `type.name`, then add `[` and `]` 
For some reason, when it reports error after the first `[` added, it doesn't refresh results, when you continue typing and error persists.

I will continue work on a simple repro

![image](https://cloud.githubusercontent.com/assets/816680/15456760/2bea59c2-202f-11e6-8094-d02627a06832.png)

**Comment by rkeithhill** [comment]
Does this only happen with types from assemblies that aren't loaded by default?

**Comment by vors** [comment]
Same thing again, different use-case. Re-open helps.

![image](https://cloud.githubusercontent.com/assets/816680/15993308/a58c9f5c-3096-11e6-9fc3-1cd7b19c5a68.png)

**Comment by daviwil** [comment]
You're missing a dollar sign on `ConvertNotesToList`, maybe that's the issue?

**Comment by vors** [comment]
oh, sorry my bad

**Comment by daviwil** [comment]
No problem!

**Comment by tylerl0706** [comment]
Has anyone run into this issue recently?

**Comment by vors** [comment]
Not me

**Comment by tylerl0706** [comment]
I'll close this for now. If it shows up again, feel free to open a new one!
