### ISSUE TITLE
Terminal Process Terminated with Exit Code 5

### ISSUE THREAD

**Issue by freak27** [PowerShell/vscode-powershell#1991]
### System Details
**OS:**
Windows 10 Enterprise 64-bit
Version: 1803
OS Build: 17134.765
**VSCODE:**
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
**PS Extension**
v1.12.1
**PSVersionTable**
PSVersion                      5.1.17134.765
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.765
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
**MORE DETAILS**
### VSCode extensions:
aws-scripting-guy.cform@0.0.23
DavidAnson.vscode-markdownlint@0.26.0
donjayamanne.githistory@0.4.6
DotJoshJohnson.xml@2.4.0
eamodio.gitlens@9.8.1
eriklynd.json-tools@1.0.2
formulahendry.auto-close-tag@0.5.6
HookyQR.beautify@1.5.0
loganarnett.lambda-snippets@1.0.0
mark-tucker.aws-cli-configure@0.3.0
mauve.terraform@1.3.11
mohsen1.prettify-json@0.0.3
ms-mssql.mssql@1.6.0
ms-vscode.notepadplusplus-keybindings@1.0.3
ms-vscode.powershell@1.12.1
nextfaze.json-parse-stringify@1.0.2
pradiphudekar.cf-templates@0.1.1
quicktype.quicktype@12.0.46
redhat.vscode-yaml@0.4.1
vscode-aws-console.vscode-aws-console@0.0.5
vscode-icons-team.vscode-icons@8.7.0
wholroyd.HCL@0.0.5

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17134.765
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.765
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description
Termina Exists with Code 5

#### Expected Behaviour

PS Extension was working last week :(

#### Actual Behaviour

See Screenshots

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by freak27** [comment]
Please find screenshots and logs here: https://drive.google.com/drive/folders/1EdweZ5JlHYbkbPZkyLlmOhMWZ9K_5FeP?usp=sharing

I really appreciate it

**Comment by rjmholt** [comment]
Hi @freak27, thanks for opening an issue.

It looks like this could be https://github.com/microsoft/vscode/issues/43169.

You've said that the PowerShell extension was working last week -- was this caused by a VSCode update perhaps?

If so, it might be worth trying VSCode Insiders to see if it's still present there.

**Comment by freak27** [comment]
@rjmholt - like I said it was working last week before applying 1.34.0

Here's what's happening (from the Debug Log)

```
[VERBOSE: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
VERBOSE: C:\opscode\chefdk\modules\
VERBOSE: C:\Program Files (x86)\AWS Tools\PowerShell\
VERBOSE: C:\Users\rrivero\.vscode\extensions\ms-vscode.powershell-2019.5.0\modules
VERBOSE: 
#-- Check required modules available -----------------------------------------
VERBOSE: Testing module availability PowerShellGet 
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1'.
VERBOSE: Loading module from path 'C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1'.
VERBOSE: PowerShellGet  found
VERBOSE: 
#-- Start up PowerShellEditorServices ----------------------------------------
VERBOSE: Importing PowerShellEditorServices
VERBOSE: Loading module from path 'C:\Users\rrivero\.vscode\extensions\ms-vscode.powershell-2019.5.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'.
VERBOSE: Loading module from path 'C:\Users\rrivero\.vscode\extensions\ms-vscode.powershell-2019.5.0\modules\PowerShellEditorServices\PowerShellEditorServices.psm1'.
VERBOSE: Exporting function 'Start-EditorServicesHost'.
VERBOSE: Exporting function 'Compress-LogDir'.
VERBOSE: Exporting function 'Get-PowerShellEditorServicesVersion'.
VERBOSE: Importing function 'Compress-LogDir'.
VERBOSE: Importing function 'Get-PowerShellEditorServicesVersion'.
VERBOSE: Importing function 'Start-EditorServicesHost'.
PowerShell Integrated Console

VERBOSE: Invoking Start-EditorServicesHost
VERBOSE: Start-EditorServicesHost returned Microsoft.PowerShell.EditorServices.Host.EditorServicesHost
VERBOSE: Writing session file with contents:
VERBOSE: {"languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_ndkwvrro.uy5","debugServiceTransport":"NamedPipe","status":"started","debugServicePipeName":"\\\\.\\pipe\\PSES_qolzvjb5.5ro"}
VERBOSE: Wrote out session file
VERBOSE: 
#-- Waiting for EditorServicesHost to complete execution ---------------------]
```

Right then I get the infamous:
**the Terminal Process terminated with error code: 5** error :(

**Comment by rjmholt** [comment]
That does indeed sound like VSCode caused it then.

Try VSCode Insiders and let us know if the problem is resolved in that.

If so, the solution in VSCode Stable is to wait for the next update. Until then the options are to continue using VSCode Insiders or to roll back your VSCode version temporarily.

If that doesn’t fix it, I think we’ll need to move this issue over to the VSCode repo

**Comment by freak27** [comment]
This might be just Company Policies as I have the exact same VSCode Version and Extensions on my personal PC and it just works. Trailing down IT to see what the did ;(
