### ISSUE TITLE
PSScriptAnalyzer Incorrect Warnings on brackets, parenthesis

### ISSUE THREAD

**Issue by fatherofinvention** [PowerShell/vscode-powershell#1997]
Issue Type: <b>Bug</b>

When typing the following code into the editor, I receive red squigglies on all curly brackets and parenthesis (open and closed) with the following message: "Missing closing '}' in statement block or type definition." and "Missing ')' in function parameter list."

Code:
=========
```powershell
function TestFunction {
    param (
        OptionalParameters
    )
}
```

Extension version: 2019.5.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by TylerLeonhardt** [comment]
I think it's because you don't have a `$` in front of `OptionalParameters`

**Comment by rjmholt** [comment]
Yeah that's a parse error because the script is invalid (no PSSA involvement even)

```
 > function TestFunction {
>>     param (
>>         OptionalParameters
>>     )
>> }
At line:2 char:12
+     param (
+            ~
Missing ')' in function parameter list.
At line:1 char:23
+ function TestFunction {
+                       ~
Missing closing '}' in statement block or type definition.
At line:4 char:5
+     )
+     ~
Unexpected token ')' in expression or statement.
At line:5 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingEndParenthesisInFunctionParameterList
```
