### ISSUE TITLE
Help Completion Crashes PowerShell Integrated Console Session

### ISSUE THREAD

**Issue by fatherofinvention** [PowerShell/vscode-powershell#1998]
Issue Type: <b>Bug</b>

When Help Completion is set to "BlockComment" or "LineComment" and ## is entered inside of a function, the PowerShell session immediately terminates with error: "The PowerShell session has terminated due to an error, would you like to restart it?".

The workaround appears to be turning off Help Completion.

Extension version: 2019.5.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by rjmholt** [comment]
@fatherofinvention Just following up here. For a crash like this, there will almost certainly be a stack trace in the logs that we can use to fix this.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
