### ISSUE TITLE
Configuration type not recognized in launch.json

### ISSUE THREAD

**Issue by pascalberger** [PowerShell/vscode-powershell#20]
I used the launch.json sample from `c:\Users\<yourusername>\.vscode\extensions\daviwil.PowerShell\examples`:

```JSON
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "PowerShell",
			"type": "PowerShell",
			"program": "DebugTest.ps1"
		}
	] 
}
```

For type Visual Studio Code shows a warning: `Value is not an accepted value. Valid values: ["node"]`. 

There is also another warning `Missing property "request"` in launch.json

**Comment by daviwil** [comment]
You may need to use version 0.1.0.  If that doesn't work let me know and I'll see if I can help diagnose.

**Comment by pascalberger** [comment]
I just installed it through `ext install` which installed 0.2.0. Shouldn't it work with this version?

**Comment by daviwil** [comment]
Right, what I mean is that in your JSON file, use 0.1.0 as the version, not 0.2.0.  The result:

```json
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "PowerShell",
            "type": "PowerShell",
            "program": "DebugTest.ps1"
        }
    ] 
}
```

**Comment by daviwil** [comment]
Also, hopefully this isn't a dumb question, but have you installed the PowerShell extension in VS Code?  Ctrl+Shift+P, type 'Install Extension', press enter, type 'PowerShell' press enter, restart VS Code.

**Comment by pascalberger** [comment]
@daviwil Yes I installed it through `ext install`. If I enter `ext` it says PowerShell is at version 0.1.0.

Changing `version` in launch.json to `0.1.0` doesn't help.

**Comment by daviwil** [comment]
Sorry Pascal, I think I misunderstood the core issue that you're reporting.  It seems like you're just pointing out that there are some validation errors in the launch config.  I believe that their launch.json validation just hasn't been updated to take different debug adapter types into account.  These warnings can safely be ignored.

Have you tried debugging a script yet?  Does it work for you despite the warnings?

**Comment by pascalberger** [comment]
Yeah, I know that I can ignore the warning and the launcher also works.

Just wanted to report that validation is not up to date atm. Don't know if something is missing which the extension needs to provide or a bug in vscode.

**Comment by daviwil** [comment]
I apologize, for some reason I originally interpreted it as "debugging isn't working" :)  Thanks for pointing this out!  I've filed a bug against Microsoft/vscode for this:

https://github.com/Microsoft/vscode/issues/546

**Comment by pascalberger** [comment]
Thanks!

**Comment by roslanr18** [comment]
Recognice lounch
 jasson
