### ISSUE TITLE
Show logs in output window when the language server crashes

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#200]
Opened a C# file. An information message popped up saying there was a problem. Two buttons were presented, `show log` or `close`. Clicked `show log` and the stacktrace was shown in the output window.

Seems like a nice to have.

**Comment by daviwil** [comment]
Your problem is that you opened a C# file ;)  Nah, that's a good suggestion.  @gerane gave me a similar idea a while back:  https://github.com/PowerShell/vscode-powershell/issues/18

I just improved the way that I store logs for the extension so I should be able to do this pretty easily.

**Comment by tylerl0706** [comment]
This for sure is fixed, right? I get a pop up that says it crashed and even a button to show the output.

**Comment by tylerl0706** [comment]
Closing because we have a popup now.
