### ISSUE TITLE
Problems: should use SecureString

### ISSUE THREAD

**Issue by ryanfog** [PowerShell/vscode-powershell#2012]
Issue Type: <b>Feature Request</b>

The "Problems" section appears to identitfy any vairable with some form of the word cred, credential etc. in it and flags it as an issue. We typically store password in encrypted .xml files using (Get-Credential) | Export-Clixml -Path .\pswd.xml
In order to use those encrypted credentials we would create a variable called $retrievedCreds = Import-Clixml -Path .\pswd.xml 

The problems section would flag $retrievedCreds as being an issue of not using SecureString. 

Extension version: 2019.5.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.16299

**Comment by rjmholt** [comment]
That's PSScriptAnalzyer's [AvoidUsingPlaintextForPassword rule](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/AvoidUsingPlainTextForPassword.md), which has some naive assumptions in it.

If you're looking to disable it, there are some possibilities:
- You can [suppress the rule](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/AvoidUsingPlainTextForPassword.md) inline for your script or function
- You can write your own [settings file](https://github.com/PowerShell/PSScriptAnalyzer#explicit) and plumb that through to VSCode with the `powershell.scriptAnalysis.settingsPath` setting, pointing that to the absolute path of your settings file (or relative to the root of your workspace)

If you're looking for a particular change in the behaviour of that rule, we should move this issue to PSScriptAnalyzer.

I'm not sure what you're asking for here though, so please let me know.

**Comment by SydneyhSmith** [comment]
Going to close this issue as inactive but would be happy to re-open/transfer with more details provided--thanks!
