### ISSUE TITLE
Not processing string functions correctly

### ISSUE THREAD

**Issue by ckmscott** [PowerShell/vscode-powershell#2016]
Issue Type: <b>Bug</b>

I am trying to concatenate a long, muti-line string using the Powersheel extension.  The functionality I am trying to use is:

```powershell
$String = "Hello"`
+ "World"`
+ "And Goodbye"
```

When I process this in VSC, I get  an "Incomplete Item Token" error. When I process this same command in Powershell ISE it works.

Extension version: 2019.5.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment]
Hi @ckmscott, thanks for opening an issue.

How are you invoking this?

If it's by highlighting it and running in the Integrated Console (e.g. with <kbd>F8</kbd>), that's tracked by https://github.com/PowerShell/vscode-powershell/issues/569.

We've been investing in PSReadLine to bring this feature to the PowerShell extension, and it's currently available in the PowerShell Preview extension.

**Comment by ckmscott** [comment]
Robert,

Thanks for your reply.  I am highlighting running it in the Integrated Console.  I’ll refer to #659 for more info and will check out the Preview Extension.

Chris

________________________________

**Comment by rjmholt** [comment]
Thanks @ckmscott!
