### ISSUE TITLE
If a class called from a script throws an exception, the powershell integrated console will fail on subsequent calls

### ISSUE THREAD

**Issue by carsontwilson** [PowerShell/vscode-powershell#2023]
I can reproduce this every time. If I have a script that calls a function, and that function calls a class... if that class throws an exception the script will exit as expected.

If you then try to run the script again, the powershell integrated console will fail. I could not see any entries at all in any of the debug logs even on verbose settings. VSCode is essentially locked, in time a message will appear to wait or reopen the window.

One point of clarification - the class has to re-throw the exception where the function does not subsequently catch it.

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

Also, any screenshots or sample code would be most helpful!

**Comment by rkeithhill** [comment]
A minimal repro along with your version info (VSCode/Extenion/PowerShell) would help a lot.  I tried with this but can't repro what you're seeing:
```powershell
class Foo {
    Crash() {
        throw "Kaboom"
    }
}

function CallFooCrash {
    [Foo]::new().Crash()
}

CallFooCrash
```

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
