### ISSUE TITLE
Flag machine specific configurations like paths as machine scoped

### ISSUE THREAD

**Issue by sandy081** [PowerShell/vscode-powershell#2024]
I am developer from VS Code and we introduced Machine Scope for configurations in [1.34](https://code.visualstudio.com/updates/v1_34#_machinespecific-settings) which will help in [remote set ups](https://code.visualstudio.com/docs/remote/remote-overview).

I would like to encourage extension authors to adopt to machine scope if you have any settings that you think they are scoped to machine like `powershell.powerShellExePath` 

For example, If you have settings that allow users to customize an executable path that exists on the machine in which extension is running, then you can tag such settings as `machine` scoped. This will let VS Code to read this setting from the location where the extension is running.

- When extension is running locally, VS Code reads this setting **only** from User settings on the same machine.
- When extension is running remotely, VS Code reads this setting **only** from Remote settings on the remote machine.

If the extension is running remotely in a [remote set up](https://code.visualstudio.com/docs/remote/remote-overview), then this will help the extension not to read paths configured in local machine user settings and bail as the paths not exist in the remote machine.

Note that machine scoped settings are overridable only in user or remote settings.

**Comment by rjmholt** [comment]
@sandy081 would you be able to link to your documentation for how we adopt this scoping?

**Comment by rkeithhill** [comment]
Was just trying WSL Debug with PowerShell in today's VSCode Insider build and got this:

![image](https://user-images.githubusercontent.com/5177512/59526821-2694c280-8e97-11e9-8e3c-0892dcb50109.png)

@sandy081 Is this what we can expect from 1.36 when it ships unless we make this change?

**Comment by rkeithhill** [comment]
Nevermind.  Helps if you install the extension in the WSL Remote for Insiders.  🤦‍♂

**Comment by sandy081** [comment]
@rjmholt Here it is https://code.visualstudio.com/updates/v1_34#_machinespecific-settings

**Comment by TylerLeonhardt** [comment]
@sandy081 in the WSL remote development, is WSL still considered "remote and not technically this machine"

**Comment by sandy081** [comment]
No, it is considered remote and paths varies in WSL.

**Comment by TylerLeonhardt** [comment]
Right, what I'm getting at is that marking something as "machine" scoped so the setting is marked "different in remote scenarios" is confusing since WSL is still on the same machine.

Apologies if this came off as bike-shedding, but I was confused by the ask initially and didn't want customers to be confused as well.

Something like "host" might have been a better name, IMO.

Anyway, we'll mark our settings that pertain to executable paths as `scope:"machine"` 👍
