### ISSUE TITLE
Running PowerShell - instant return - yet code runs

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2026]
Issue Description
=====

It's a bit strange problem so I don't expect much but maybe it will give you something. I sometimes run F5 and get the instant finish of code (like less than 1 second), while I can see PowerShell continues to run as seen in the bottom (progress bar).

![image](https://user-images.githubusercontent.com/15063294/59596973-05331100-90f9-11e9-9d90-f7d6474f6b81.png)

I am not sure how this happens, but after that, I usually can't run anything anymore. I often get into a state where I've to kill Visual Studio or at very least kill Powershell to run things again. Probably some kind of race condition of sorts. 

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

[1560761129-daf5c381-4653-4d79-b101-93d3a47dd4971560678388341.zip](https://github.com/PowerShell/vscode-powershell/files/3296333/1560761129-daf5c381-4653-4d79-b101-93d3a47dd4971560678388341.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.35.1|
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.145|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|code-settings-sync|Shan|3.2.9|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.8.2|
|markdown-all-in-one|yzhang|2.3.1|
|markdown-preview-enhanced|shd101wyy|0.4.1|
|material-icon-theme|PKief|3.8.0|
|polacode|pnp|0.3.2|
|powershell|ms-vscode|2019.5.0|
|project-manager|alefragnani|10.5.2|
|rainbow-csv|mechatroner|1.1.1|
|theme-monokai-pro-vscode|monokai|1.1.13|
|vscode-pull-request-github|GitHub|0.8.0|
|vscode-wakatime|WakaTime|2.1.2|
|xml|DotJoshJohnson|2.5.0|

**Comment by SydneyhSmith** [comment]
Thanks--pulling out the error message
```

2019-06-17 12:10:31.358 [ERROR] tid:1 in 'PopRunspace' C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 2109
    Caller attempted to pop a runspace when no runspaces are on the stack.

2019-06-17 12:10:31.358 [ERROR] tid:1 in 'PopRunspace' C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 2109
    Caller attempted to pop a runspace when no runspaces are on the stack.
```

**Comment by SydneyhSmith** [comment]
@PrzemyslawKlys what is your F5 configured to, I know you had changed it in the past? Thanks!

**Comment by PrzemyslawKlys** [comment]
Reverted back to defaults since PSScriptAnalyzer and VSCode made huge performance improvements.

So F5 = Start Debugging.
