### ISSUE TITLE
Variable Explorer

### ISSUE THREAD

**Issue by tbone4711** [PowerShell/vscode-powershell#2034]
**Explore the content of variables all the time**

At the moment you can only view the content of variables in debugger by setting a breakpoint and run the code. There is no way to select multiple lines and run them by pressing F8 and see the value of all variables like in debugger. Or run a small script by pressing F5. I suggest a pane like the "Variables" in debug but visible all the time(F5 and F8). This helps beginners to get a feeling what's going on during execution, without  to start an debug session. It could be like the "PowerShell Command Explorer". An good proposal was posted by logg-sar in [issue 1204 "Wish: Is there a way to show Variables when executing line (F5) or block (F8)](https://github.com/PowerShell/vscode-powershell/issues/1204)"

**Comment by SydneyhSmith** [comment]
Thanks for the feedback @tbone4711 I went ahead and added your comment to issue #1204 so we can continue to track the request in a single place, and I will close this issue as a duplicate--Thanks!
