### ISSUE TITLE
Add command to open Microsoft.VSCode_profile.ps1 in the editor

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#204]
It'd be easier for users to set up their VS Code profile if we add a command that they can launch to have their `Microsoft.VSCode_profile.ps1` opened in the editor whether it exists or not.  This should probably be implemented using an editor command written with the $psEditor API.

**Comment by gerane** [comment]
This is the one that I am using

```powershell
Register-EditorCommand `
    -Name "Helpers.OpenVSCodeProfile" `
    -DisplayName "Open VS Code Profile" `
    -SuppressOutput `
    -ScriptBlock {
        param([Microsoft.PowerShell.EditorServices.Extensions.EditorContext]$context)
        If (!(Test-Path -Path $Profile)) { New-Item -Path $Profile }
        $psEditor.Workspace.OpenFile($Profile)
    }
```

**Comment by daviwil** [comment]
Yeah, basically that.  I'm actually planning to include a standard set of $psEditor commands with PSES so that stuff like this can easily be added to all editors.  Maybe you'd want to contribute this command to that?

**Comment by gerane** [comment]
I guess this one can be closed now.

**Comment by daviwil** [comment]
Good point, closing it, thanks for contributing those commands!
