### ISSUE TITLE
Install / Update  is pointing to incorrect link

### ISSUE THREAD

**Issue by lcanastreiro** [PowerShell/vscode-powershell#2041]
Issue Type: <b>Bug</b>

When trying to Install or Update the Powershell extension it is failing because it's pointing to the incorrect link - https://sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery.json/publishers/Microsoft/vsextensions/powershell/2019.5.0/vspackage (Manual Option). The automatic install/update is generating a failed exception.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.18362

**Comment by lcanastreiro** [comment]
![image](https://user-images.githubusercontent.com/33402915/60041019-3c359380-96b2-11e9-85fd-9a1fba602445.png)

When Clicking on Update to 2019.5.0

**Comment by lcanastreiro** [comment]
![image](https://user-images.githubusercontent.com/33402915/60041150-8e76b480-96b2-11e9-871c-4b06b464f1be.png)

When Clicking on the "Download Manually" I'm getting an error - blob not found

**Comment by SydneyhSmith** [comment]
@lcanastreiro thanks for reporting this issue--this is happening in Azure Data Studio correct? 
It may be related to this [change](https://github.com/microsoft/azuredatastudio/pull/6109#issuecomment-504217662 ). As a work around [this link ](https://sqlopsextensions.blob.core.windows.net/extensions/powershell/ms-vscode.PowerShell-2019.5.0.vsix)should work to manually download.

**Comment by tillig** [comment]
I'm seeing it in Azure Data Studio.

The workaround link does allow you to download the VSIX, but you can't just double-click the downloaded VSIX. After failing to install the update and clicking "Download Manually," you _must_ use the "Install from VSIX..." button that comes up in Azure Data Studio.

So:

- Attempt to install the update and let that fail.
- Click the "Download Manually" button.
- Ignore the BlobNotFound page that pops up.
- Use [the workaround link](https://sqlopsextensions.blob.core.windows.net/extensions/powershell/ms-vscode.PowerShell-2019.5.0.vsix) to download the updated VSIX.
- Back in Azure Data Studio, click the "Install from VSIX..." button that's available.
- Select the downloaded VSIX and you're good to go.

Also, If you list the `@installed` extensions in Azure Data Studio, you'll see the PowerShell extension is installed... but listing `@recommended will _also_ show the PowerShell extension and _that one_ will appear _uninstalled_.

Not a huge deal, but kind of confusing if you're not prepared for it.

**Comment by SydneyhSmith** [comment]
@alanrenmsft we are seeing this issue, wondering if you have any idea on the cause/fix? Let me know if we should transfer it to the ADS repo?

**Comment by alanrenmsft** [comment]
@SydneyhSmith oops, just noticed there was a typo in the link, I have corrected it. It might take a while for the changes to take effect. I have verified locally by deleting my cache and now it is pointing to the correct vsix file.

sorry about that.

**Comment by alanrenmsft** [comment]
I'll make sure to test that as well as letting your team also do the testing after each version update.

**Comment by SydneyhSmith** [comment]
Thanks @alanrenmsft!
