### ISSUE TITLE
Install-VSCode doesn't support "Stable-User" BuildEdition

### ISSUE THREAD

**Issue by JMGEHMAN** [PowerShell/vscode-powershell#2048]
The **BuildEdition** parameter of the Install-VSCode.ps1 script should support the *"Stable-User"* option - it currently only allows *"Stable"*, which results in an install of *"Stable-System*.

If a user wants to install the Insiders version of VS Code, they have the option of specifying *"Insider-System"* or *"Insider-User"*. However, there is only one option if selecting the *"Stable"* version.

**Proposed technical implementation details (optional)**
Add *"Stable-User"* to the ValidateSet check for the **BuildEdition** parameter. With the necessary changes to code to support the additional option. This creates an inconsistency between naming conventions for Stable and Insider editions - not sure what, if anything, should be done to address.

- Option 1
Keep *"Stable"* and simply add *"Stable-User"*.
```
[parameter()]
[ValidateSet("Stable", "Stable-User", "Insider-System", "Insider-User")]
[string]$BuildEdition = "Stable",
```

- Option 2
Rename *"Stable"* to *"Stable-System"* in addition to adding *"Stable-User"*.
```
[parameter()]
[ValidateSet("Stable-System", "Stable-User", "Insider-System", "Insider-User")]
[string]$BuildEdition = "Stable-System",
```

**Comment by ghvanderweg** [comment]
The ValidateSet used to be just Stable and Insider, and [was changed to Stable, Insider-System and Insider-User when that functionality became available for VS Code Insider](https://github.com/PowerShell/vscode-powershell/pull/1477). So Option 2 would be the way to go in my opinion.

I'd like to pick this up :)

**Comment by JMGEHMAN** [comment]
Thanks, ghvanderweg. I'd like to take as well. Planning on using it as a demo on contributing to PowerShell/open source.

**Comment by ghvanderweg** [comment]
Alright, it's all yours then 😀

**Comment by TylerLeonhardt** [comment]
Awesome!

**Comment by corbob** [comment]
@TylerLeonhardt if @JMGEHMAN is picking this one up, should the Up-for-Grabs label be removed?

**Comment by TylerLeonhardt** [comment]
I'll leave the tag for tracking but I did just assign it to @JMGEHMAN and we can use that for ownership.

**Comment by JMGEHMAN** [comment]
It took too long for me to get approval. Thanks to @Lothindir for fixing.
