### ISSUE TITLE
Add an option to disable automatic parenthesis insertion

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/vscode-powershell#2067]
# Add an option to disable automatic parenthesis insertion

Currently, when entering a function using <kbd>TAB</kbd> auto completion, a parenthesis is automatically added.

For me this is very confusing as I'm used to type parentheses myself (on German keyboards this may be simpler than on US-English keyboards as with German keyboards parentheses are available via <kbd>SHIFT</kbd>+<kbd>8</kbd> to <kbd>9</kbd>):

![Automatic parenthesis insertion](https://user-images.githubusercontent.com/9283914/60684838-3739c680-9ea0-11e9-8a89-5e85cf895d76.gif)

Can you please add an option to the PowerShell extension so that auto completion does _not_ add an opening parenthesis?

I suggest that option to be a boolean option, called `powershell.autoOpeningParenthesisOnTab` being selected by default. (Don't call it "disable...". See /microsoft/vscode/issues/40987 )

**Comment by TylerLeonhardt** [comment]
Completions in the extension are provided by PowerShell itself (Imagine hitting TAB in a PowerShell console on `ToBool`) and AFAIK that behavior is not configurable.

In a perfect world, we would ask PowerShell to ignore the parentheses. You should open an issue [over there](https://github.com/PowerShell/PowerShell) to support this.

The extension _could_ offer a setting to chop off the parentheses... But that'd be a perf hit as we'd have to take the time to chop it off.

**Comment by SetTrend** [comment]
Ah, I comprehend. Sure, you are right. I'll open an issue over there then.

Thanks für enlightening me!
