### ISSUE TITLE
Extension should not keep EditorServices.log file locked while running

### ISSUE THREAD

**Issue by troshko111** [PowerShell/vscode-powershell#207]
`ms-vscode.PowerShell-0.6.1\bin\EditorServices.log` is locked by `Microsoft.PowerShell.EditorServices.Host.exe` and thus cannot be synced across machines while `vscode` is opened and running

Use case: I sync `vscode` settings through Dropbox using symlinking, but said file cannot be synced and causing "infinite" sync retries since it's locked (access denied).

I checked the file and it's not even written to, there should be no reason this file needs to be exclusively locked all the time

**Comment by daviwil** [comment]
Hey Taras, thanks for the report!  I hadn't considered this possibility.  The file does actually get written to but you won't see much detail there when the log level isn't set to `Verbose`.  I'll see about changing the logging code to not keep the file open constantly and only open it when a write needs to be made.

Alternatively I could provide a setting that would allow you to change the log file path in special cases such as this.

**Comment by TarasRoshko** [comment]
Oh I see. I would suggest only opening the file when you are about to flush the log buffer to it, that way you still have good logging performance when necessary but no handle is being kept most of the time.

Adding an option specifying the file location seems unnecessary, I can hardly imagine anybody using such feature (except for trying to work around cases as this)

**Comment by daviwil** [comment]
Great point, I'll just try to batch writes and only flush when I need to.

**Comment by rjmholt** [comment]
I think this issue no longer applies, since our logging infrastructure has been rewritten

**Comment by corbob** [comment]
Unfortunately I think this issue still exists:

![7-zip error dialog indicating access denied](https://user-images.githubusercontent.com/30301021/76898167-69cef800-6852-11ea-9783-a753b4898d36.png)

**Comment by SydneyhSmith** [comment]
@corbob thanks for the additional info, based on how our logging is set up, and this issue you show it appears that the issue must now be coming from Serilog because of this I will mark it as external.
