### ISSUE TITLE
codeFormatting.IgnoreOneLineBlock / hashtable problem

### ISSUE THREAD

**Issue by itfranck** [PowerShell/vscode-powershell#2071]
Issue Type: <b>Bug</b>

Code formatting does not behave properly when declaring a hashtable in a IF condition. 

Set your codeFormatting options to: 

```
"powershell.codeFormatting.ignoreOneLineBlock": true,
"powershell.codeFormatting.openBraceOnSameLine": true,
"powershell.codeFormatting.newLineAfterCloseBrace": true,
"powershell.codeFormatting.newLineAfterOpenBrace": true,
```

Write the following statement
```
    if ($test -eq $null) {$test = @{}}
    if ($test -eq $null) {
        $test = @{ }
    }
```

Once formatted, they will appear as : 

```
    if ($test -eq $null) { $test = @{ } 
    }
    if ($test -eq $null) {
        $test = @{ }
    }

```
Trying the same thing with test assignment being an array @() instead of a hashtable work properly .

```
if ($test -eq $null) { $test = @() }
if ($test -eq $null) {
    $test = @()
}
```

Extension version: 2019.5.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (13.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rkeithhill** [comment]
Code formatting functionality is provided by PSScriptAnalyzer.  Can you submit this bug on that project - https://github.com/powershell/scriptanalyzer/issues?  Thanks.

**Comment by TylerLeonhardt** [comment]
cc @bergmeister for visibility

**Comment by itfranck** [comment]
https://github.com/PowerShell/PSScriptAnalyzer/issues/1284
