### ISSUE TITLE
Executing commands during debugging that expand the max screen width result in error

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/vscode-powershell#2077]
Issue Type: <b>Bug</b>

When I debug a PowerShell script and the command hits the end of the screen width, an error is thrown and I cannot that command:
```PowerShell
Hit Line breakpoint on 'C:\Users\[userid]\Documents\GitHub\PowershellScriptLibrary\SharePointDsc\Customer\Configs\Deploy_SharePoi(HERE THE END OF THE SCREEN WIDTH IS HIT)

An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 15.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex) 
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__95.MoveNext()
```
Extension version: 2019.5.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SydneyhSmith** [comment]
@ykuijs thanks for reporting this issue it looks like it is  likely the same problem as #702 it might be worth trying the [PowerShellPreview extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) since that can enable PSReadline (with `"powershell.developer.featureFlags": [ "PSReadLine" ]` in your vscode settings) which handles scrolling the buffer

**Comment by ykuijs** [comment]
@SydneyhSmith I can confirm that installing and enabling the PowerShellPreview extension fixes this issue. Will close this issue, since the issue is already being tracked in the other issue.

Thanks!
