### ISSUE TITLE
Expand aliases works silently, needs 'running indicator'

### ISSUE THREAD

**Issue by vors** [PowerShell/vscode-powershell#208]
When I worked on https://github.com/PowerShell/platyPS/issues/126 
I tried use "Expand aliases" on a file with 1.5k lines.

There was no feedback from vscode that it started to do something.
I thought it's not working, but then I checked it in 20 seconds and it was done.
I'm not sure how much time did it take, but since the operation is not instant it requires some visual progress indication for better UX.

It could be applicable to other refactorings as well.

**Comment by daviwil** [comment]
Thanks Sergei!

**Comment by dfinke** [comment]
Wow, that worked?! :-)

**Comment by kapilmb** [comment]
With ScriptAnalyzer providing the ability to expand aliases through its SuggestCorrections property, the question I would like to ask is, should we have "expand aliases" have and maintain it's own implementation or use ScriptAnalzyer''s service?

**Comment by daviwil** [comment]
Script Analyzer's expansion is nice when the user wants to expand a single alias into the fully-qualified command name.  Doug's Expand Alias command does it automatically across the whole file, so I think the intent is a little different.  However, if we want to provide this type of "whole-file correction" operation in Script Analyzer we can definitely discuss how to make that happen.

**Comment by tylerl0706** [comment]
It would be cool if this could do like:

"50 alias expanded" though a simple "Aliases expanded" would be a good first step.

**Comment by tylerl0706** [comment]
@rjmholt can you test to see if this is fixed for free with #1227 😄

**Comment by rjmholt** [comment]
The running indicator I added in #1227 seems to work for this. Closing

**Comment by vors** [comment]
Great!
