### ISSUE TITLE
Powershell Command Explorer keeps loading but shows nothing

### ISSUE THREAD

**Issue by portTack** [PowerShell/vscode-powershell#2083]
![Capture](https://user-images.githubusercontent.com/5780033/61141927-7c06c400-a483-11e9-8526-1fd0226eac28.PNG)
Issue Type: <b>Bug</b>

The Powershell Command Explorer extension on the sidebar keeps loading but not showing anything. The same thing happens to two other sidebar icons as well Test and Leetcode.

Extension version: 2019.5.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by corbob** [comment]
It feels like if other extensions are doing similar things, that it might be a vscode thing.

In any case, could you provide [logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs) to help us with troubleshooting what the issue might be?

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue--Thanks!
