### ISSUE TITLE
Timed out waiting for session file to appear.

### ISSUE THREAD

**Issue by rgoldhor** [PowerShell/vscode-powershell#2085]
### System Details

System Details Output
```
### VSCode version: 1.36.1 2213894ea0415ee8c85c5eea0d0ff81ecc191529 x64

### VSCode extensions:
aaron-bond.better-comments@2.0.5
austin.code-gnu-global@0.2.2
cstrap.python-snippets@0.0.8
felipecaputo.git-project-manager@1.7.1
Gruntfuggly.todo-tree@0.0.138
magicstack.Chromodynamics@0.0.14
ms-python.anaconda-extension-pack@1.0.1
ms-python.python@2019.6.24221
ms-vscode.cpptools@0.24.0
ms-vscode.powershell@2019.5.0
njpwerner.autodocstring@0.3.0
redhat.vscode-yaml@0.4.1
seanwu.vscode-qt-for-python@0.3.0
sterin.msbuild-tools@0.0.9
tintoy.msbuild-project-tools@0.2.55


### PSES version: 

### PowerShell version:

Name                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      5.1.14409.1018                                                                                                                
PSEdition                      Desktop                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                       
BuildVersion                   10.0.14409.1018                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                               
WSManStackVersion              3.0                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                           
SerializationVersion           1.1.0.1            
```

### Issue Description

I am experiencing a problem initializing the PowerShell VSCode extensions.

#### Expected Behaviour

The PowerShell VSCode extension should initialize successfully.

#### Actual Behaviour

The PowerShell VSCode extenstion tries for many seconds to initialize, and eventually fails with the error message "Language server startup failed...The language service could not be started...Timed out waiting for session file to appear."

### Attached Logs

The attached log file was generated with the logging level set to "Diagnostic"
[vscode-powershell.zip](https://github.com/PowerShell/vscode-powershell/files/3389381/vscode-powershell.zip)

**Comment by SydneyhSmith** [comment]
Hi @rgoldhor  thanks for opening an issue. It looks like this might be an issue caused by a system configuration like group policy or execution policy.

Can you please try trusting the Microsoft signing certificate on the startup script by [following these steps](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-6#installing-the-powershell-extension-on-restricted-systems).

Some other things that might be responsible:

A group policy configuration
Antivirus
Another form of system lockdown or restriction

**Comment by SydneyhSmith** [comment]
Hi @rgoldhor wanted to check in--did you get a chance to try the steps above?

**Comment by rjmholt** [comment]
Deduplicating this issue to https://github.com/PowerShell/vscode-powershell/issues/2014

**Comment by cluber22** [comment]
I am getting a very similar issue when trying to start VS Code. I am on a restricted system and my ExecutionPolicy is set to RemoteSigned.

Error from VS Code:
`'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command 'Import-Module 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; 

Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1588837667-563346d4-8618-4e50-b59d-2664ec20e8fc1588837662748\EditorServices.log' -SessionDetailsPath 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-8688-547158' -FeatureFlags @() '' failed to launch (exit code: {2})


Start-EditorServices failed to launch`

C:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1588837667-563346d4-8618-4e50-b59d-2664ec20e8fc1588837662748\vscode-powershell.log

`07/05/2020 08:47:47 [NORMAL] - Language server starting --
07/05/2020 08:47:47 [NORMAL] -     PowerShell executable: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
07/05/2020 08:47:47 [NORMAL] - powershell.exe started.
07/05/2020 08:47:47 [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1588837667-563346d4-8618-4e50-b59d-2664ec20e8fc1588837662748\EditorServices.log' -SessionDetailsPath 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-8688-547158' -FeatureFlags @() 
07/05/2020 08:47:47 [NORMAL] - Waiting for session file
07/05/2020 08:47:47 [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1588837667-563346d4-8618-4e50-b59d-2664ec20e8fc1588837662748\EditorServices.log' -SessionDetailsPath 'c:\Users\<username>\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-8688-547158' -FeatureFlags @() 
07/05/2020 08:49:47 [NORMAL] - Error occurred retrieving session file:
Timed out waiting for session file to appear.
07/05/2020 08:49:47 [ERROR] - Timed out waiting for session file to appear.
07/05/2020 08:49:47 [NORMAL] - Language server startup failed.
07/05/2020 08:49:47 [ERROR] - The language service could not be started: `

**Comment by STDSA** [comment]
Hello

Has this issue been resolved? I have a similar issue which I cannot fix, i.e. "Error occurred retrieving session file: Timed out waiting for session file to appear.". My execution policy is set to RemoteSigned, and I've run the following Powershell command
Import-Module $HOME\.vscode\extensions\ms-vscode.powershell*\modules\PowerShellEditorServices\PowerShellEditorServices.psd1
Strangely the issue goes away when I switch to WindowsPowerShell x86. Can you please advise what I should do?

**Comment by TylerLeonhardt** [comment]
@STDSA do you use Avecto/BeyondSoft or some other privilege management?

**Comment by STDSA** [comment]
Yes i have Avecto on my machine. I can still open applications with Elevated Privileges, but not admin privileges. For example, when opening powershell with  Elevated Privileges, I can change the execution policy, and install modules.

**Comment by SydneyhSmith** [comment]
@STDSA thanks for the additional information this is[ a known issue](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#known-issues-in-the-extension)
