### ISSUE TITLE
PSReadLine Command History is not saving to the HistorySavePath location

### ISSUE THREAD

**Issue by stevenjudd** [PowerShell/vscode-powershell#2086]
### System Details

System Details Output
```
### VSCode version: 1.36.1 2213894ea0415ee8c85c5eea0d0ff81ecc191529 x64

### VSCode extensions:
CoenraadS.bracket-pair-colorizer-2@0.0.28
eamodio.gitlens@9.8.5
humao.rest-client@0.21.3
ms-azure-devops.azure-pipelines@1.152.0
ms-azuretools.vscode-apimanagement@0.1.1
ms-azuretools.vscode-azureappservice@0.15.0
ms-azuretools.vscode-azurefunctions@0.17.1
ms-azuretools.vscode-azurestorage@0.7.0
ms-azuretools.vscode-cosmosdb@0.10.2
ms-azuretools.vscode-docker@0.7.0
ms-kubernetes-tools.vscode-kubernetes-tools@1.0.1
ms-mssql.mssql@1.6.0
ms-vscode.azure-account@0.8.4
ms-vscode.azurecli@0.4.6
ms-vscode.powershell@2019.5.0
ms-vscode.vscode-node-azure-pack@0.0.9
msazurermtools.azurerm-vscode-tools@0.6.0
oderwat.indent-rainbow@7.4.0
redhat.vscode-yaml@0.4.1
Shan.code-settings-sync@3.3.1
vsciot-vscode.azure-iot-toolkit@2.8.0
vscode-icons-team.vscode-icons@8.8.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with the PSReadline HistorySavePath file. First, it is not saving the command history to the defined file location. 

Second, it would be preferred to have the default file name to not have white space characters in the name. Thus "Visual Studio Code Host_history.txt" would be "VisualStudioCodeHost_history.txt" 

Third, the Set-PSReadlineOption -HistorySavePath command does not seem to save the path for the history file.

#### Expected Behaviour

The file specified in the HistorySavePath should be created and should contain the commands entered into the Integrated Console.

#### Actual Behaviour

The file is not created and the command history is not stored in this file.

### Attached Logs

[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3390443/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3390444/EditorServices.log)
[Start-EditorServices-EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3390445/Start-EditorServices-EditorServices.log)

**Comment by SydneyhSmith** [comment]
Thanks @stevenjudd for opening this issue, you have some very valid concerns. 

> First, it is not saving the command history to the defined file location.

It looks like you are using the PowerShell extension, rather than the PowerShell Preview extension which unfortunately is the only place where PSReadline support is available in VSCode, we are tracking this issue with #1793 

> Second, it would be preferred to have the default file name to not have white space characters in the name. Thus "Visual Studio Code Host_history.txt" would be "VisualStudioCodeHost_history.txt"

This is a result of PSReadLine using the host name to create this file path--changing our host name would be a substantial breaking change so we are unlikely to update this, although we agree it would be nicer to not have white spaces.

**Comment by rjmholt** [comment]
FYI our host name is defined [here](https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Session/HostDetails.cs#L18-L22). It imitates the ISE's host name, which is `Windows PowerShell ISE Host`.

**Comment by SeeminglyScience** [comment]
As a work around, you can put this in your profile:

```powershell
if ($psEditor -and (Get-Module PSReadLine)) {
    $currentSavePath = (Get-PSReadLineOption).HistorySavePath
    Set-PSReadLineOption -HistorySavePath $currentSavePath.Replace($Host.Name, 'ConsoleHost')
}
```
