### ISSUE TITLE
Intellisense makes suggestions when typing comments

### ISSUE THREAD

**Issue by rsgoheen** [PowerShell/vscode-powershell#209]
When typing comments, both single line and block comments, intellisense is making keyword suggestions.  

![powershellvscodecomment](https://cloud.githubusercontent.com/assets/806850/15984153/d9c67092-2fb8-11e6-8139-3dd34745d117.png)

**Comment by daviwil** [comment]
Yep, this is a common problem in VS Code, here are some relevant issues:

- https://github.com/Microsoft/vscode/issues/719
- https://github.com/Microsoft/vscode/issues/7326

They seem to suggest that the extension shouldn't be providing completions inside comment blocks but in this case VS Code seems to be giving you snippet suggestions and a word-based completion (the `for` with the `abc` icon).  I'll investigate this to see if there's anything that can be done on my end to get rid of those suggestions in comments.

One thing you could try in the meantime in VS Code 1.2.0 is to try this new setting:

```
"editor.wordBasedSuggestions": false
```

It's set to `true` by default so you'll need to go into your User Settings and change it.  Let me know if it improves the situation at all for you.

**Comment by rsgoheen** [comment]
Still getting suggestions in block comments after adding that to the user settings.json.  It's more annoying than anything, and I'd rather live with that over turning off suggestions globally.

**Comment by rsgoheen** [comment]
Closing this bug since it's being handled under the main VSCode project.
