### ISSUE TITLE
Powershell Terminal Memory issues

### ISSUE THREAD

**Issue by CreaterNo1** [PowerShell/vscode-powershell#2097]
Whenever I am running a larger PowerShell script and debugging it, if I make steps quickly, the terminal crashes. This also happens when I for instance Get a lot of backup jobs, and if I try to cancel it, the terminal also crashes.
I gave back this error code:
The terminal process terminated with exit code: 3221225477
According to my research that seems like a bad memory mapping issue. I have made sure that I use both x64 vscode and x64 PowerShell.
If this could be fixed, vscode would be my dream workspace for coding.

**Comment by SydneyhSmith** [comment]
@CreaterNo1 thanks for opening this--sorry to hear that you are hitting this issue! It would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by CreaterNo1** [comment]
Visual Studio Code version
PS C:\temp> code -v
1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
x64
____________________
PowerShell Extension version
PS C:\temp> code --list-extensions --show-versions
formulahendry.code-runner@0.9.11
ms-vscode.powershell@2019.5.0
ms-vsts.team@1.149.2
vscode-icons-team.vscode-icons@8.8.0
______________________________
Editor Service Version
PS C:\temp> $psEditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      12     1      0
__________________________________
PS Version
PS C:\temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.765
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.765
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by CreaterNo1** [comment]
The logs have been sent by e-mail from the levlords@gmail.com to the vscode-powershell@microsoft.com

**Comment by rjmholt** [comment]
@CreaterNo1 could you provide a screenshot of this error please? It sounds like this is a native issue, which is unlikely to be occurring in our codebase (no native code).

**Comment by CreaterNo1** [comment]
![image](https://user-images.githubusercontent.com/46622461/61946067-e64e5700-afa1-11e9-96e8-a02f6bb7acb7.png)
I don't think this will help the case, but this is what I get.

**Comment by rjmholt** [comment]
> The terminal process terminated with exit code: 3221225477

Where are you seeing that message?

**Comment by CreaterNo1** [comment]
I see it on the same place as this alert. Sadly I can't reproduce it for some reason, only this.
