### ISSUE TITLE
Attribute "Locked" is missing

### ISSUE THREAD

**Issue by McProgger** [PowerShell/vscode-powershell#2098]
Issue Type: <b>Feature Request</b>

Hi,

Forms cannot be set the Locked attribute like in C#.

Extension version: 2019.5.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by SydneyhSmith** [comment]
@McProgger thanks for opening this issue, and providing the feature request---I am not too familiar with the "Locked" attribute and how that could be incorporated into the PowerShell Vscode extension...any repro steps or screenshots showing what you would like/expect to see would be super helpful! Thanks!
