### ISSUE TITLE
Troubles with cyrillic symbols

### ISSUE THREAD

**Issue by JohnyL** [PowerShell/vscode-powershell#2100]
VSCode 1.36.1. Default encoding in settings is UTF-8.
Trying to output cyrillic symbols:
```
Write-Host "договор"
```
Output:
1. PowerShell 5.1 x64 output:
>РґРѕРіРѕРІРѕСЂ
2. PowerShell Core 6.2 output:
> договор

**Comment by SydneyhSmith** [comment]
Thanks for opening this issue @JohnyL have you tried [our steps](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/understanding-file-encoding?view=powershell-6#configuring-vscode) for configuring encoding in VsCode?

**Comment by JohnyL** [comment]
@SydneyhSmith I know that I should set windows-1251, but I wonder why UTF-8 worked for PS Core 6.2?

**Comment by rjmholt** [comment]
> but I wonder why UTF-8 worked for PS Core 6.2

PS 6+ defaults to UTF-8 when it sees no BOM. This is not the case in Windows PowerShell 5.1-.
