### ISSUE TITLE
References doesn't work for 2nd project within one workspace

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2112]
Issue Description
=====

When you have one folder within one workspace it's fine. But if you choose to add another folder to workspace (like in the screenshot below) 2nd folder doesn't seem to get any References tracking. 

![image](https://user-images.githubusercontent.com/15063294/62203103-d613ee80-b38a-11e9-8f73-8452eeb20c8b.png)

Normally this should show at least 1 reference. 

![image](https://user-images.githubusercontent.com/15063294/62203269-196e5d00-b38b-11e9-8cb6-dd099a388709.png)

It seems that only the first project tracks references. Not sure if any other features are affected.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.36.1|
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.145|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|auto-rename-tag|formulahendry|0.1.0|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|code-settings-sync|Shan|3.4.1|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.9.1|
|html-css-class-completion|Zignd|1.19.0|
|live-html-previewer|hdg|0.3.0|
|markdown-all-in-one|yzhang|2.4.2|
|markdown-preview-enhanced|shd101wyy|0.4.3|
|markdown-shortcuts|mdickin|0.11.0|
|material-icon-theme|PKief|3.8.1|
|powershell|ms-vscode|2019.5.0|
|project-manager|alefragnani|10.6.0|
|theme-monokai-pro-vscode|monokai|1.1.13|
|vscode-html-css|ecmel|0.2.0|
|vscode-markdownlint|DavidAnson|0.29.0|
|vscode-peacock|johnpapa|2.5.2|
|vscode-pull-request-github|GitHub|0.9.1|
|vscode-wakatime|WakaTime|2.2.0|
|vscode-yaml|redhat|0.4.1|
|wordcount|ms-vscode|0.1.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by rjmholt** [comment]
This wasn't implemented when VSCode added multiple workspace support. No plans to implement it imminently, but we'll get there soon hopefully. Thanks for raising this.

**Comment by andschwa** [comment]
Ugh I betcha this isn't actually fixed. But @PrzemyslawKlys could you check and verify the latest behavior in preview?

**Comment by PrzemyslawKlys** [comment]
@andschwa It doesn't work :-)

**Comment by andschwa** [comment]
Thought so. The client is aware of multi-root workspaces, but the server still has some notion of a single workspace root. Grr.
