### ISSUE TITLE
Symbol renaming incorrectly changes symbols that start with the original symbol's name

### ISSUE THREAD

**Issue by rs38** [PowerShell/vscode-powershell#212]
Currently it (called "change all occurancies") can only find&replace which is not usefull to refactor (as it also changes comments and unrelated similar variables). This is not like rename.refactor e.g. for C#
Example:  

```
$URI= "http://localhost:8080/"
$URI2= "http://Server2"
$IEexe= "C:\Program Files\Internet Explorer\iexplore.exe" 
& $IEexe $URI
& $IEexe $URI2
```

renaming `$URI` to `$URIOriginal` will also change unrelated `$URI2`

**Comment by daviwil** [comment]
Yep, I think there's a bug with the renaming here.  We'll get it fixed.  Thanks!

**Comment by tylerl0706** [comment]
Interesting. If you highlight just "URI" on line one, I can repro your issue.

However, if you don't highlight anything, renaming works as expected.

**Comment by JustinGrote** [comment]
@TylerLeonhardt I can't reproduce, though there is a difference between "clicking" a symbol and "dragging" over the symbol. Dragging will be any characters you select.

![Capture](https://user-images.githubusercontent.com/15258962/79587288-2e109380-8087-11ea-832c-2ee9bbb21bda.gif)

**Comment by SydneyhSmith** [comment]
I think its also important to note that we dont officially support renaming #1440
