### ISSUE TITLE
Debugging in Temporary Console Fails

### ISSUE THREAD

**Issue by GQnzo** [PowerShell/vscode-powershell#2124]
Issue Description
=====

When I attempt to debug a script in "PowerShell Launch Current File in Temporary Console" I get the following error:

```
PowerShell Integrated Console

chmod: /var/folders/nx/qf4td1pd7fx6spbvp3czsp040000gn/T/CoreFxPipe_PSES_ivhgzmjd.3yf: No such file or directory
stat: /var/folders/nx/qf4td1pd7fx6spbvp3czsp040000gn/T/CoreFxPipe_PSES_ivhgzmjd.3yf: stat: No such file or directory


Permissions to the pipe file were not set properly. Expected: 600 Actual:  for file: /var/folders/nx/qf4td1pd7fx6spbvp3czsp040000gn/T/CoreFxPipe_PSES_ivhgzmjd.3yf
[DebugSession-5.log](https://github.com/PowerShell/vscode-powershell/files/3473526/DebugSession-5.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3473527/vscode-powershell.log)
```

This happens even if I try to run a oneliner Write-Host command in the script. If I don't use the Temporary Console option it runs fine.

Attached Logs
=====

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Darwin x64 18.7.0 |
| VSCode | 1.36.1|
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|6.2.2|
|PSEdition|Core|
|GitCommitId|6.2.2|
|OS|Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019, root:xnu-4903.270.47~4/RELEASE_X86_64|
|Platform|Unix|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.2.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|powershell|ms-vscode|2019.5.0|

**Comment by GQnzo** [comment]
Logs:
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3473564/vscode-powershell.log)
[DebugSession-5.log](https://github.com/PowerShell/vscode-powershell/files/3473566/DebugSession-5.log)

**Comment by SydneyhSmith** [comment]
@GQnzo thanks for opening this issue...based on the error message you are getting 
```
Permissions to the pipe file were not set properly. Expected: 600 Actual:  for file: /var/folders/nx/qf4td1pd7fx6spbvp3czsp040000gn/T/CoreFxPipe_PSES_ivhgzmjd.3yf
```
 this is an issue that we are aware of and should be fixed in the [Preview version of our extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview)...are you able to ugrade to this version and let us know if you still hit the issue.

**Comment by GQnzo** [comment]
That worked!!! Thanks.
