### ISSUE TITLE
PowerShell Command Explorer doesn't display commands in VSCode Sidebar

### ISSUE THREAD

**Issue by mkanet** [PowerShell/vscode-powershell#2125]
I'm using the latest PowerShell Preview Extension.  When I select, "PowerShell Command Explorer" from the VSCode Activity Bar, instead of seeing all the commands in the Sidebar, this happens in the VSCode Terminal:
![MKANET (Workspace) - Visual Studio Code 2019-08-06 20-15-00](https://user-images.githubusercontent.com/811008/62592303-9156ee80-b887-11e9-80a1-457534ee4980.gif)

**PowerShell Command Explorer works correctly on the same setup using the standard PowerShell Extension**

**Windows 10 64bit (Version 1903)
VSCode Version: 1.36.1 (user setup)**

PowerShell Preview Extension: enabled
PowerShell Extension: disabled
**$PSVersionTable**
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by SydneyhSmith** [comment]
@mkanet  thanks for opening this issue, and providing the gif...it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by mkanet** [comment]
My apologies.  The problem went away after I rebooted my PC.
