### ISSUE TITLE
F8 to run current line/selection takes a long time to react

### ISSUE THREAD

**Issue by janegilring** [PowerShell/vscode-powershell#2129]
Issue Description
=====

I am experiencing a problem with F8 sometime taking a very long time to react, sometimes just a few seconds - other times it doesn`t seem to have been registered. Hence, you try again and after some time the selected line runs several times.

It is not very easy to reproduce, but I wanted to report it anyway since it affects day-to-day usability. Yesterday I was working on a script which uses the SharePointPnPPowerShellOnline, and eventually had to drop back to PowerShell ISE in order to get things done.

I will go ahead and update the issue if I find a reliable way to re-produce. However, at the moment the issue seems very sporadic.

Attached Logs
=====

I will attach logs when the problem can be reliably re-produced.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.37.0|
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.145|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|armsnippet|artofshell|0.7.0|
|azure-account|ms-vscode|0.8.4|
|azure-pipelines|ms-azure-devops|1.155.0|
|azurecli|ms-vscode|0.4.6|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|code-settings-sync|Shan|3.4.1|
|gitblame|waderyan|3.0.1|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.9.3|
|guides|spywhere|0.9.3|
|indent-rainbow|oderwat|7.4.0|
|markdown-all-in-one|yzhang|2.4.2|
|material-icon-theme|PKief|3.8.1|
|night-owl|sdras|1.1.3|
|powershell|ms-vscode|2019.5.0|
|powershellprotools|ironmansoftware|4.8.2|
|python|ms-python|2019.8.29288|
|rainbow-csv|mechatroner|1.2.0|
|shell-launcher|Tyriar|0.3.0|
|swagger-viewer|Arjun|2.2.2|
|team|ms-vsts|1.149.2|
|terraform|mauve|1.3.12|
|vscode-azureappservice|ms-azuretools|0.15.0|
|vscode-azurefunctions|ms-azuretools|0.17.1|
|vscode-azurestorage|ms-azuretools|0.7.1|
|vscode-azureterraform|ms-azuretools|0.2.4|
|vscode-coverage-gutters|ryanluker|2.4.0|
|vscode-instant-markdown|dbankier|1.4.4|
|vscode-logicapps|ms-azuretools|0.2.9|
|vscode-markdownlint|DavidAnson|0.29.0|
|vscode-pandoc|DougFinke|0.0.8|
|vscode-peacock|johnpapa|3.0.1|
|vsliveshare|ms-vsliveshare|1.0.657|

**Comment by wsmelton** [comment]
Just curious are you using the system setup or the user setup of VS Code? I've had little quirks happen in the User setup that I've had to stop using it because they were not reproducible, or stopped noticing them happening when I used the system install.

**Comment by janegilring** [comment]
Interesting. I'm using the user setup.

**Comment by SydneyhSmith** [comment]
@janegilring sorry to hear that you are hitting this--thanks for opening this issue. As you mention it would be super helpful to know if there are certain cmdlets that this happens with and logs are even better. We have also had reports that disabling code lens `"editor.codeLens": false` can be a work around for improving the speed of F8 an issue that we are tracking in #1326
