### ISSUE TITLE
Pipe DebugAdapter errors to console on failure

### ISSUE THREAD

**Issue by tillig** [PowerShell/vscode-powershell#213]
In trying to write a script that has a `PSCredential` parameter, it took a bit to convert the ambiguous error message that appears ("Debug adapter process has terminated unexpectedly") into something meaningful. Finding the `DebugAdapter.log` wasn't really straightforward - the message didn't indicate I should look there; nothing in the docs or the README indicate where to look.

As it turns out, the error was:

`System.NotSupportedException: Input fields of type 'PSCredential' are currently not supported`

That's unfortunate, but I could have saved a lot of time debugging the debugger if the log message had appeared somewhere in VS Code - a debug console, part of the pop-up error message, or somewhere else more obvious.

**Comment by daviwil** [comment]
That's a great point, I'll find a way to make the logs of these failures more easy to locate in the editor.

**Comment by SydneyhSmith** [comment]
Closing as resolved.
