### ISSUE TITLE
Frequent crashes (10-30) daily with no discernible pattern

### ISSUE THREAD

**Issue by carsontwilson** [PowerShell/vscode-powershell#2131]
While attempting to debug VS Code using the powershell console, the console itself will crash many, many times per day.

The behaviour is always the same, but I can't determine why it happens or see any pattern. When it does happen, it's always when you first start debugging, console just sits there as if frozen.

After a few moments, VS will alert me of an issue with the window, ask me to re-open or wait. Waiting doesn't seem to be helpful (though I've not waited for more than 5 minutes). Re-opening the window will basically restart VS Code and I can typically proceed from there.

I can mitigate this, somewhat, if I "trash" all console instances before I start (i.e. hit the little garbage can on the bottom of the console essentially restarting it), though that doesn't always work either.

VS Version:
![image](https://user-images.githubusercontent.com/4393519/62888088-748d4180-bcf3-11e9-8681-5701abcba59c.png)

Extensions:
![image](https://user-images.githubusercontent.com/4393519/62888107-7eaf4000-bcf3-11e9-9a32-97b53fae4155.png)

Powershell Version:
![image](https://user-images.githubusercontent.com/4393519/62888131-87a01180-bcf3-11e9-924b-c87538bd1f36.png)

Logs:
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3493795/vscode-powershell.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3493797/EditorServices.log)
[DebugSession-1.log](https://github.com/PowerShell/vscode-powershell/files/3493799/DebugSession-1.log)

In this case, I consistently see this error across multiple sessions:

```
2019-07-29 16:53:25.033 [ERROR] tid:15 in 'ExecuteCommand' C:\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs: line 565
    Execution of the following command(s) completed with errors:
c:\Work\devops\powershell\test.ps1
        Out-Default
```

There are days when my extension can crash 30+ times which is challenging to say the least.
I've completely uninstalled / reinstalled the extension, VS Code etc. but the results remain the same. 

One thing that may or may not be worth noting, in that script (and all my scripts basically) I reference multiple powershell classes as well, that are being imported like this:

```
using module .\modules\EnvironmentData.psm1
using module .\modules\Tenant.psm1
using module .\modules\ADManager.psm1
using module .\modules\AzureFunction.psm1

```
Thanks!

**Comment by carsontwilson** [comment]
Here are my user settings in case these are helpful:
{
    "git.autofetch": true,
    "git.confirmSync": false,
    "window.menuBarVisibility": "default",
    "editor.minimap.enabled": false,
    "powershell.developer.editorServicesWaitForDebugger": true,
    "window.zoomLevel": 0,
    "terminal.integrated.rendererType": "dom",
    "workbench.colorTheme": "One Monokai",
    "powershell.codeFormatting.useCorrectCasing": true,
    "workbench.iconTheme": "vscode-icons",
    "powershell.debugging.createTemporaryIntegratedConsole": true,
    "csv-preview.resizeColumns": "all"
}

**Comment by SydneyhSmith** [comment]
@carsontwilson thanks for reporting this, if you do notice a pattern please let us know..more examples of logs from the crashes you are experiencing would also be helpful in determining the cause...thanks!

**Comment by carsontwilson** [comment]
The logs don't seem to show much, but I've included a zip file with all logging information - I just had two such crashes in a row. Many of the log files are 0kb with no data, but there are a couple with sparse info.

Let me know if I can do more or if there's more logging elsewhere I can include (this is coming from: C:\Users\CarsonWilson\AppData\Roaming\Code\logs)

[20190823T093944.zip](https://github.com/PowerShell/vscode-powershell/files/3536072/20190823T093944.zip)

**Comment by carsontwilson** [comment]
Ok I have additional logging - I do have it set to verbose, but it doesn't seem to have added much in the logging. The crash occurred right about 9:20a...
[2-PowerShell Extension Logs.log](https://github.com/PowerShell/vscode-powershell/files/3560722/2-PowerShell.Extension.Logs.log)
[exthost.log](https://github.com/PowerShell/vscode-powershell/files/3560724/exthost.log)
[main.log](https://github.com/PowerShell/vscode-powershell/files/3560725/main.log)
[4-PowerShell Editor Services.log](https://github.com/PowerShell/vscode-powershell/files/3560727/4-PowerShell.Editor.Services.log)
[2-PowerShell Extension Logs.log](https://github.com/PowerShell/vscode-powershell/files/3560730/2-PowerShell.Extension.Logs.log)

**Comment by SydneyhSmith** [comment]
@carsontwilson thanks for providing these logs..every bit of information helps! Some of these logs files arent ones we typically see though...where are you grabbing these files from?

**Comment by carsontwilson** [comment]
Hey there - I'm getting the logs from this location:
C:\Users\CarsonWilson\AppData\Roaming\Code\logs

Is there somewhere else I should get them from as well / instead of?

**Comment by SydneyhSmith** [comment]
@carsontwilson the logs we are looking for should live in:
`$HOME/.vscode/extensions/ms-vscode.powershell-2019.5.0/logs/`
Thanks!

**Comment by carsontwilson** [comment]
Ok I"ve got logs from a crash that happened just a moment ago from that location. My script threw an exception and the powershell shell then terminated. I fixed my code, and start the shell via debug again and that's when it locked.

I can see the exception that my code threw in the logs, but I didn't see anything else that indicated an error. Still, I've attached the errors.

Thanks!
[DebugAdapter.log](https://github.com/PowerShell/vscode-powershell/files/3602058/DebugAdapter.log)
[DebugSession-1.log](https://github.com/PowerShell/vscode-powershell/files/3602059/DebugSession-1.log)
[DebugSession-2.log](https://github.com/PowerShell/vscode-powershell/files/3602060/DebugSession-2.log)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/3602061/EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3602062/vscode-powershell.log)

**Comment by rkeithhill** [comment]
This is a curious exception:
```
System.Management.Automation.RuntimeException: t is not a valid choice
```
Are you (or a script you're using) prompting with `$Host.UI.PromptForChoice`?
