### ISSUE TITLE
$True , $false.Why is 【f】 lowercase?it is bug？

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/vscode-powershell#2133]
$True , $false,Why is 【f】 lowercase?it is bug？

**Note the difference between capitalization**

$True , $false ，in vscode powershell automatic completion.
$true , $false ，in ise  automatic completion.
$true , $false ，in powergui powershell automatic completion.

i think $True,$False as well!

vscode powershell version = 2019.5
vscode powershell version = preview 2019.5

**Comment by SydneyhSmith** [comment]
@chuanjiao10 thanks for opening this issue--I am having some trouble reproducing this...are you able to provide a gif or screenshot of what you are seeing?
