### ISSUE TITLE
The language service could not be started

### ISSUE THREAD

**Issue by ralf-escher** [PowerShell/vscode-powershell#2134]
This bug relates to [#2119](https://github.com/PowerShell/vscode-powershell/issues/2119)
Can't start any kind of terminal, which always result in "terminal process stopped with exit code (0)".

This issue occurs for another two collegues. One colleques can still work fine.
The difference: we have installed the latest [Windows 10 Version 1809 update](https://support.microsoft.com/en-us/help/4507469/windows-10-update-kb4507469)

```
14.8.2019 07:33:36 [NORMAL] - Visual Studio Code v1.37.0 64-bit
14.8.2019 07:33:36 [NORMAL] - PowerShell Extension v2019.5.0
14.8.2019 07:33:36 [NORMAL] - Operating System: Windows 64-bit
14.8.2019 07:33:36 [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
14.8.2019 07:33:36 [NORMAL] - Language server starting --
14.8.2019 07:33:36 [NORMAL] -     exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
14.8.2019 07:33:39 [NORMAL] - powershell.exe terminated or terminal UI was closed
14.8.2019 07:35:37 [NORMAL] - Language server startup failed.
14.8.2019 07:35:37 [ERROR] - The language service could not be started: 
14.8.2019 07:35:37 [ERROR] - Timed out waiting for session file to appear.
```

```
Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Datum: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.17763
```

Tried several approaches to fix this issue (like mentioned in the other bug report), reinstalled Visual Studio Code twice, disabled all extensions...

**Comment by ralf-escher** [comment]
Windows Update doesn't seems to be the problem, since we now get the same error message on our server:

```
Version: 1.37.0 (system setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Datum: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.14393
```

**Comment by SydneyhSmith** [comment]
@ralf-escher we sometimes see this issue with a system configuration like group policy or execution policy...is this something that is in place on your machine? If so you may want to also try trusting the Microsoft signing certificate on the startup script by [following these steps](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-6#installing-the-powershell-extension-on-restricted-systems).

**Comment by ralf-escher** [comment]
@SydneyhSmith this really looks like some kind of policy issue since it happens on several machines of my colleagues. Due to a hint of our IT I tried the command `"gpupdate /force"` to update the group policy with no improvement.

Additionally I tried a normal cmd and bash as terminal.
`"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"`
which both also crashed (couldn't find some appropriate log files)

Therefore I am not sure if this issue is really related to PowerShell.

**Comment by SydneyhSmith** [comment]
@ralf-escher thanks for that additional info, another thing that may be helpful would be to know what the Execution Policy you have set for PowerShell, one way to get this is by running `Get-ExecutionPolicy` thanks!

**Comment by ralf-escher** [comment]
```
PS C:\WINDOWS\system32> Get-ExecutionPolicy -list

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    Unrestricted
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine    RemoteSigned
```

**Comment by ralf-escher** [comment]
Seems to be a problem with BitDefender, see [stackoverflow](https://stackoverflow.com/questions/57520651/the-terminal-process-command-failed-to-launch-exit-code0-and-exit-code2)
