### ISSUE TITLE
Debugging hangs for a powershell script containing git commands.

### ISSUE THREAD

**Issue by dbaeumer** [PowerShell/vscode-powershell#214]
_From @lawrencebr on June 21, 2016 22:26_
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. Create a script with "git clone" in it, my script is below:

`Write-Host "Start Git Test";

$result = git clone <git repo> "$PSScriptRoot\test.git" 2>&1;

Write-Host "Finished Git Command";
Write-Host $result;`

please note that the <git repo> I am attempting to clone is a local bare repository on my hard drive, so no credentials are needed.
2. Debug the script
3. At this point, for me, the script hangs, the only way I can get it to finish is to pause it, wait a minute, then it will go to the next line, and I can either step through or continue to the end.  I have attached the error displayed on the console in the developer's tools.

If I run the same script from powershell it does not hang, but completes fine.

_Copied from original issue: Microsoft/vscode#7941_

**Comment by gerane** [comment]
I was just going to file the same issue. I am seeing the same issue.

@daviwil This was the debug hanging issue I was talking to you about. Took me a while to pinpoint the cause.

**Comment by daviwil** [comment]
Interesting, thanks for the report, I'll have to look into this.

**Comment by rkeithhill** [comment]
Is this a case of exe stdio interfering with the stdio between the debug host and vscode?

**Comment by lawrencebr** [comment]
By exe stdio I assume you mean Visual Studio 2015 interfering with Visual Studio Code?  If that is what you are asking, then I don't think so because I was working on a larger script and debugging with VS Code the entire time, and I didn't run into problems until I reached the git portion of that script.

To test my theory I wrote a script with just the Git code and found the same issues, and that is what I submitted in my bug report.

If there is a conflict like you are suggesting, it is very specific to Git commands.

**Comment by rkeithhill** [comment]
No, not referring to VS 2015.  We've seen exe's that somehow manage to interfere with the stdio channel between VSCode and the debug host. https://github.com/PowerShell/PowerShellEditorServices/issues/147

**Comment by daviwil** [comment]
@rkeithhill: The stdio thing could be possible, I'll have to look into it.  I'll try it in a newer build with the named pipes setup to see if I get the same hang.

**Comment by rkeithhill** [comment]
@daviwil This is indeed fixed, based on my limited testing, in 0.7.0 by the new (pipe) approach to connecting with the VS code client.

**Comment by daviwil** [comment]
Awesome!  I'll keep this open until we get ready to ship so I can verify it again once we're ready.

**Comment by rkeithhill** [comment]
Hmm, tried this again with 0.7.2 and it eventually worked but git clone seems to be generating ErrorRecords for the clone progress messages.

**Comment by daviwil** [comment]
Sounds like the ISE ;)  The situation is a little more complicated now due to stdout from native apps not being written correctly when using CoreCLR PowerShell.  Hopefully one of my approaches to using the native console host will help solve this problem for good...

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
