### ISSUE TITLE
Code Signing Certificate Expired

### ISSUE THREAD

**Issue by Ryoken0367** [PowerShell/vscode-powershell#2140]
### Issue Description

The terminal is failing to load, language service failed to start. Same issue I have run into before when the code signing certificate wasn't loaded on my machine. I run in a strict AllSigned PowerShell environment, so only scripts signed with a valid signing cert will run. When digging into it more, I found the certificate PowerShellEditorServices is signed with, and the certificate is expired (as of 7/26/2019).

If you need any logs or any other information I can provide it. However, it seems at this time that it just needs to be re-signed with an updated certificate.

**Comment by SydneyhSmith** [comment]
@Ryoken0367 thanks for reporting this--we were able to verify this...we will do a release as soon as possible

**Comment by corbob** [comment]
Is this still an issue 9 months later?

**Comment by TylerLeonhardt** [comment]
Probably not since we've shipped several versions since then. I'll close it but we can reopen if it's still happening.
