### ISSUE TITLE
Necessary updates for the new ternary operator added in PowerShell language

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/vscode-powershell#2142]
The ternary operator will soon be added to the PowerShell language. Necessary updates may be needed for the vscode-powershell extension:
1. New AST type `TernaryExpressionAst` is added. Changes are made to the visitors in PowerShell. The visitors in powershell extension may need to be updated too.
2. The new ternary operator may cause syntax colorization issue.

/cc @rjmholt @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
> The new ternary operator may cause syntax colorization issue.

Can you open an issue here:
https://github.com/PowerShell/EditorSyntax

**Comment by daxian-dbw** [comment]
Done: https://github.com/PowerShell/EditorSyntax/issues/184
