### ISSUE TITLE
Pasting from editor to the Powershell Integrated Console fails using line continuation

### ISSUE THREAD

**Issue by gbritton1** [PowerShell/vscode-powershell#2143]
Issue Type: <b>Bug</b>

If I start creating a new Powershell script and enter
```

Get-Process `
-Name code

```

using line continuation in a powershell script, copy and paste that into the integrated terminal, the command fails.

![image](https://user-images.githubusercontent.com/12263288/63341162-9ea7ba80-c316-11e9-8679-2b4dfe38d041.png)

Pasting into a regular powershell window works just fine:

![image](https://user-images.githubusercontent.com/12263288/63341251-cdbe2c00-c316-11e9-957e-4fd9241987fa.png)

Extension version: 2019.5.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SydneyhSmith** [comment]
@gbritton1 thanks for opening this issue, multi-line editing support comes from the PSReadline module which is now available in the [PowerShell Preview extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview), we are tracking that PSReadLine is not available in the main PowerShell Extension here #1793

**Comment by gbritton1** [comment]
@sydneyhsmith the repro info is in the top post

**Comment by rjmholt** [comment]
This is solved by PSReadLine, which is still in preview. You can get that by uninstalling the `powershell` extension and installing the `powershell-preview` extension.
