### ISSUE TITLE
Not able to step through script after the latest update to VSCode

### ISSUE THREAD

**Issue by westerdaled** [PowerShell/vscode-powershell#2144]
Issue Description
=====

I work a lot  with PowerShell in VSCode and it generally very stable. Today I upgraded VSCode to the latest release and this seems to have broken the PowerShell Preview Extension  IMHO 
e.g. both "Step Over" &   "Step Into"  disabled  No highlighting of current line. Help, I am back to using the ISE 😫
[PowerShell extension log.txt](https://github.com/PowerShell/vscode-powershell/files/3520307/PowerShell.extension.log.txt)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.37.1|
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.145|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.4|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|code-spell-checker|streetsidesoftware|1.7.18|
|csharp|ms-vscode|1.21.0|
|debugger-for-chrome|msjsdiag|4.11.7|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.9.3|
|markdown-all-in-one|yzhang|2.4.2|
|markdown-shortcuts|mdickin|0.11.0|
|powershell-preview|ms-vscode|2019.5.0|
|python|ms-python|2019.8.30787|
|quicktype|quicktype|12.0.46|
|rest-client|humao|0.22.0|
|shell-launcher|Tyriar|0.3.0|
|team|ms-vsts|1.149.2|
|tslint|eg2|1.0.44|
|vscode-apache|mrmlnc|1.2.0|
|vscode-azurefunctions|ms-azuretools|0.18.0|
|vscode-browser-preview|auchenberg|0.5.9|
|vscode-docker|ms-azuretools|0.7.0|
|vscode-edit-csv|janisdd|0.1.2|
|vscode-guid|heaths|1.4.15|
|vscode-icons|vscode-icons-team|9.2.0|
|vscode-spfx-deploy-package|RencoreGmbH|1.1.0|

**Comment by SydneyhSmith** [comment]
@westerdaled sorry to hear that you are hitting crashes, and thanks for opening this issue and providing this info/logs---It would be really helpful if you could also attach diagnostic logging--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by rjmholt** [comment]
@westerdaled are there other indications the extension is working? Do you get completions? Does the Integrated Console work?

**Comment by westerdaled** [comment]
@rjmholt  Yes the syntax completion works. Indeed most things but not the debugger
![Issue with debugger](https://user-images.githubusercontent.com/937208/63411699-011fba00-c3ee-11e9-9472-9c3d768da39e.PNG).
I could debug this successfully in the IDE but in VSCode I never even see a breakpoint reached. very weird!

**Comment by westerdaled** [comment]
@SydneyhSmith 
Diagnostic level now set ( despite what is indicated in the logs). 
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/3524162/vscode-powershell.log)
![PowerShell Log files](https://user-images.githubusercontent.com/937208/63413457-a4be9980-c3f1-11e9-8b58-eb7108c5e8d0.PNG)

**Comment by SydneyhSmith** [comment]
@westerdaled thanks for providing that log...the one that would be most helpful in that folder is the EditorServices file (the whole folder is the best option)...if you could also provide a GIF or screenshots of the completions you are getting that would be awesome! Thanks!

**Comment by westerdaled** [comment]
@SydneyhSmith  ,  I actually witnessed the debugger work today after starting the VScode in my project directory ( normally, I just start "Code" from the Windows 10 Start) .  However, this was short lived so still have an issue. Looks to me that debugger just hangs after it gets used . 
[issue2144_logs.zip](https://github.com/PowerShell/vscode-powershell/files/3534056/issue2144_logs.zip)
![VScode PowerShell Extension Code complete](https://user-images.githubusercontent.com/937208/63586195-b5f5da80-c598-11e9-9344-9de35659fd88.png)

**Comment by westerdaled** [comment]
@SydneyhSmith 

`
{
    "window.zoomLevel": 0,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "powershell.developer.featureFlags": [ "PSReadLine" ],
    "git.autofetch": true,
    "markdown.extension.preview.autoShowPreviewToSide": true,
    "team.showWelcomeMessage": false,
    "workbench.colorTheme": "Monokai",
    "workbench.iconTheme": "vscode-icons",
    "vsicons.dontShowNewVersionMessage": true,
    "azureFunctions.enableSlots": true,
    "azureFunctions.projectLanguage": "PowerShell",
    "terminal.integrated.rendererType": "dom",
    "powershell.powerShellExePath": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "editor.fontSize": 12,
    "powershell.developer.editorServicesLogLevel": "Diagnostic"
}

`

**Comment by westerdaled** [comment]
@rjmholt   can you please confirm that this is the [procdump](https://gallery.technet.microsoft.com/scriptcenter/Getting-SysInternals-027bef71) your are referring to 
if so I click   F5 debugger  and as usual the VScode just suspends .  In the terminal window I ran
`
.\procdumper.ps1  -exception 1  "NullReferenceException" $PID
`
It doesn't appear to be doing a lot tho 🤨

**Comment by westerdaled** [comment]
@rjmholt  I am glad we are getting close.  I did look at the code: is this node or typescript?

**Comment by westerdaled** [comment]
Hmmmm I am running v1.371  so I am not sure how this will help.  There must be others out there with the same issue.. Will look at your suggestions tomorrow.

**Comment by westerdaled** [comment]
@SydneyhSmith  @rjmholt  I have been doing some more testing on this issue and ..... I thing my problem is due to typos in the script.   Now these aren't being picked until I attempt to debug the script and then I see the issue.  Thanks for your patience.

**Comment by rjmholt** [comment]
I just noticed the disconnect request you're receiving has `"restart": true` on it. I wonder if we handle that properly

**Comment by TylerLeonhardt** [comment]
I've got a fix for this out now.
