### ISSUE TITLE
Add InvokeRegisteredEditorCommand to package.json

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/vscode-powershell#2145]
You used to be able to (or at least I could have sworn you could) set a key binding to a specific editor command like this:

```json
{
    "key": "alt+shift+s",
    "command": "PowerShell.InvokeRegisteredEditorCommand",
    "args": { "commandName": "ConvertTo-SplatExpression" },
    "when": "editorLangId == 'powershell'"
},
```

I think they added validation to the keybindings.json so that it would no longer work with "non-public" commands.

We should add the following to `package.json > contributes > commands`

```json
{
  "command": "PowerShell.InvokeRegisteredEditorCommand",
  "title": "Invoke Registered Editor Command",
  "category": "PowerShell"
},
```

And also the under `package.json > contributes > menus > commandPalette`

```json
{
  "command": "PowerShell.InvokeRegisteredEditorCommand",
  "when": "false"
},
```

After adding these to my local copy it works as expected.

**Comment by SydneyhSmith** [comment]
@SeeminglyScience seems like a good suggestion, thanks for providing some steps to get started in case someone has time to do this work
