### ISSUE TITLE
Support PowerShell installed from MSIX package

### ISSUE THREAD

**Issue by maximpashuk** [PowerShell/vscode-powershell#2147]
Hi

Latest **[PowerShell 7.0.0-preview.3](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0-preview.3)** has added support for **MSIX** package in addition to classic .msi package.

VSCode powershell extensions can't automatically pick up PowerShell installed from MSI package.
Workaround from issue #2110 works fine, I can use following pattern in VSCode:

```json
"powershell.powerShellAdditionalExePaths": [
    {
        "exePath": "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.0.0.3_neutral__8wekyb3d8bbwe/pwsh.exe",
        "versionName": "Powershell Core"
    }
]
```

And its working fine for me, but this will be fine to have built-in support in vscode-powershell

**Comment by TylerLeonhardt** [comment]
Yep! We should add this. 

cc @SteveL-MSFT

**Comment by rjmholt** [comment]
@maximpashuk is this now solved for you?

**Comment by maximpashuk** [comment]
@rjmholt Not tested yet. Will wait while powershell team provide msix package for powershell 7 (see https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5519)

**Comment by TylerLeonhardt** [comment]
The added logic is in so we can close this for now. Once you get around to testing it and if it doesn't work, we can reopen!
