### ISSUE TITLE
Copying code from Insider build 1.38.0 to Word will show &nbsp instead of blankspace

### ISSUE THREAD

**Issue by PsPsam** [PowerShell/vscode-powershell#2148]
### System Details

System Details Output
```
ms-vscode.powershell@2019.5.0
Tyriar.shell-launcher@0.3.0
vscode-icons-team.vscode-icons@9.2.0


### PSES version: 1.12.1.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Copying code from Insider build 1.38.0 to Word will show &nbsp instead of blankspace. The format of the document is PowerShell.

This doesn't happen in the stable version

#### Expected Behaviour

Copy the show text as it show without the &nbsp as show in the image

#### Actual Behaviour

When copy text or code in PowerShell format it will instead of blankspace add the html code for blankspace &nbsp

### Attached Logs

![image](https://user-images.githubusercontent.com/20344934/63503282-76af8700-c4cf-11e9-8521-a94a0a314aa3.png)

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by PsPsam** [comment]
Don't know if this was the right place or if it should go to Editor Syntax Colorization bug report?

**Comment by TylerLeonhardt** [comment]
This should be opened in the vscode main repo:

https://github.com/Microsoft/vscode

Can you open it over there, please?

**Comment by PsPsam** [comment]
@TylerLeonhardt issue opened at the main repo. Thanks for pointing me to the correct place.

https://github.com/microsoft/vscode/issues/79677
