### ISSUE TITLE
Avoid using `workspace.rootPath`

### ISSUE THREAD

**Issue by roblourens** [PowerShell/vscode-powershell#2153]
`workspace.rootPath` is a deprecated property and may not work as expected. Please use `workspaceFolders` instead. More info:  https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath

https://github.com/microsoft/vscode/issues/69335

**Comment by markm77** [comment]
Yes, just want to echo that integrated console is opening in root of first (unrelated) project rather than root of project containing scripts in a multi-root workspace. Which is not desirable but understand you are tracking this.

**Comment by TylerLeonhardt** [comment]
The problem is, the extension has been working with the assumption that there's one root for so long that switching to mult-root is non-trivial unfortunately.. but we do want to support this.
