### ISSUE TITLE
powershell ext - colorizer has issues with quoted string containing @

### ISSUE THREAD

**Issue by mlhickey** [PowerShell/vscode-powershell#216]
Using VSC 1.3.0-insider and PowerShell 0.6.1. The colorizer portion exhibits odd behavior then a quoted string contains the @ character.  The behavior changes depending on whether single- or double-quote character is used, but both are incorrect/

1. Edit/create .ps1 file with multiple lines of code, add line like $next = $jsonObj.'@odata.nextlink'  
[colorizer-bug.ps1.txt](https://github.com/PowerShell/vscode-powershell/files/341861/colorizer-bug.ps1.txt)
in body
2. Notice incorrect coloration of remaining code
3. Change single quote to double quote like $next = $jsonObj."@odata.nextlink"
4. Notice incorrect coloration of remaining code

**Comment by gerane** [comment]
@gravejester is this related to the issue you just fixed?

**Comment by gravejester** [comment]
Yes, I think this one is related, but not fixed by my latest PR, will fix and push new commit to get this fixed as well :)

**Comment by daviwil** [comment]
Since @gravejester has fixed this I'll go ahead and close the issue.  @mlhickey, you may not see the fix until the next VS Code release (or an upcoming VS Code Insiders build if you use that).  Thanks!
