### ISSUE TITLE
System.ArgumentOutOfRangeException crashing Services with Preview

### ISSUE THREAD

**Issue by eedwards-sk** [PowerShell/vscode-powershell#2161]
### System Details

System Details Output
```
### VSCode extensions:
alefragnani.Bookmarks@10.5.0
bmarkovic.haproxy@0.1.2
bungcip.better-toml@0.3.2
castwide.solargraph@0.21.1
eriklynd.json-tools@1.0.2
flesler.url-encode@1.1.0
foxundermoon.shell-format@6.1.1
hangxingliu.vscode-systemd-support@0.1.1
iciclesoft.workspacesort@1.5.7
idleberg.applescript@0.16.0
joshuapoehls.json-escaper@1.1.0
mads-hartmann.bash-ide-vscode@1.3.3
maelvalais.autoconf@0.1.0
mauve.terraform@1.4.0
ms-azuretools.vscode-docker@0.7.0
ms-python.python@2019.8.30787
ms-vscode.Go@0.11.4
ms-vscode.powershell-preview@2019.5.0
rebornix.ruby@0.24.2
redhat.vscode-yaml@0.5.2
rogalmic.bash-debug@0.3.5
ryu1kn.partial-diff@1.4.0
shanoor.vscode-nginx@0.6.0
timonwong.shellcheck@0.8.1
zhouronghui.propertylist@0.0.2


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

Integrated Console (Services) constantly crashing while doing editing in the IDE. It's not clear exactly what I'm doing that's causing it. See logs.

#### Expected Behaviour

Doesn't crash

#### Actual Behaviour

Crashes

### Attached Logs

https://gist.github.com/eedwards-sk/1edd1ea14cbb7706ed0abcc340d7aaf7

**Comment by SydneyhSmith** [comment]
@eedwards-sk thanks for opening this issue...looking at the logs you provided it seems that the issue is occurring in the code lens provider, in order for us to fully debug this issue it would be really helpful if you could provide `Diagnostic` logging--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) this will allow us to see the message being sent by the code lens provider

**Comment by rjmholt** [comment]
The particular code in EditorServices seems to be [here](https://github.com/PowerShell/PowerShellEditorServices/blob/161a3ed45fafacfc225d3bc335cd6f5e84a255e5/src/PowerShellEditorServices/Language/FindReferencesVisitor.cs#L120-L151).

However, the stack trace actually indicates that this is a bug in PowerShell itself, [here](https://github.com/PowerShell/PowerShell/blob/8b9f4124cea30cfcd52693cb21bcd8100d39a796/src/System.Management.Automation/engine/parser/Position.cs#L493-L505).

**Comment by rjmholt** [comment]
@eedwards-sk We might be able to reproduce this outside of EditorServices with just the function definition in the script where the crash happens, if you can provide that

**Comment by eedwards-sk** [comment]
@rjmholt I believe it was crashing while editing this file (and specifically, when using intellisense) https://github.com/edgetools/mise/blob/vscode-powershell-GH-2161/mise/lib/context/context.ps1

Is that what you mean by function definition or is there something else you're referring to? Thanks for the response.

**Comment by rjmholt** [comment]
Yeah, function definitions are where you use the `function` keyword to define a function.

For example, you can find all the ones in that file with:

```powershell
$path = ./context.ps1
iwr 'https://raw.githubusercontent.com/edgetools/mise/vscode-powershell-GH-2161/mise/lib/context/context.ps1' -outfile $path
$path = (Resolve-Path $path).Path

$toks = $errs = $null
$ast = [System.Management.Automation.Language.Parser]::ParseFile($path, [ref]$toks, [ref]$errs)

$funcDefs = $ast.FindAll({ $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)

$funcDefs
```

**Comment by eedwards-sk** [comment]
@rjmholt thanks! I linked the wrong file at first on accident, so I appended the funtiondefs using your example script to the original gist:

https://gist.github.com/eedwards-sk/1edd1ea14cbb7706ed0abcc340d7aaf7#file-functiondefs-ps1

**Comment by rjmholt** [comment]
Ok, I haven't been able to repro this yet. If you can turn on diagnostic logging and send those through when this happens, I should be able to work out where this happens

**Comment by eedwards-sk** [comment]
Thanks, of course I'm not able to repro it now, either. I don't even remember what I was doing 4 days ago to exactly trigger it 😢

**Comment by eedwards-sk** [comment]
I'm going to close this until I can reproduce it again.
