### ISSUE TITLE
xxx Not recognized as the name of a cmdlet, function, script file,

### ISSUE THREAD

**Issue by hwassinger** [PowerShell/vscode-powershell#2167]
Have multiple functions defined within a script. When I attempt to run the script it returns the error {function name} is not recognized as the name of a cmdlet, function, script file,

Spelling of function is correct and if I take the entire text into Powershell ISE it sees it as correct. I have not yet determined reproduction steps.

Thanks!

**Comment by SydneyhSmith** [comment]
@hwassinger thanks for reporting this issue---as you mention repro steps (for example the actual script you are trying to run) would be very helpful for us in terms of debugging...if this is something that you prefer to share privately you can also send this to vscode-powershell@microsoft.com...additionally system information [including the following version information would be great ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#visual-studio-code-version)...thanks!
