### ISSUE TITLE
PromptForChoice() Multiple choice selection not working in integrated console

### ISSUE THREAD

**Issue by ili101** [PowerShell/vscode-powershell#2169]
Issue Type: <b>Bug</b>

The MultipleChoiceSelection variant of PromptForChoice() not allowing to select multiple options.
[Definition](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.host.ihostuisupportsmultiplechoiceselection.promptforchoice?view=pscore-6.2.0#System_Management_Automation_Host_IHostUISupportsMultipleChoiceSelection_PromptForChoice_System_String_System_String_System_Collections_ObjectModel_Collection_System_Management_Automation_Host_ChoiceDescription__System_Collections_Generic_IEnumerable_System_Int32__)
[Example](https://activedirectoryfaq.com/2014/12/user-interactive-powershell-scripts/#PromptForChoice-Let-the-user-select)

This is a problem only in the PowerShell Integrated Console, It works in a regular console in VSCode.

``` Powershell
$title = "Backup"
$message = "Please select resources for backup!"
$option1 = New-Object System.Management.Automation.Host.ChoiceDescription "Personal &Account", "Account"
$option2 = New-Object System.Management.Automation.Host.ChoiceDescription "Personal &Folder", "Folder"
$option3 = New-Object System.Management.Automation.Host.ChoiceDescription "Personal &Database", "Database"
$option4 = New-Object System.Management.Automation.Host.ChoiceDescription "&Public Folder", "Public"
$options = [System.Management.Automation.Host.ChoiceDescription[]]($option1, $option2, $option3, $option4)
$backup=$host.ui.PromptForChoice($title, $message, $options, [int[]](1))
```

Expected:
![image](https://user-images.githubusercontent.com/6960531/64530081-f4b7be80-d314-11e9-981f-02c29da21cae.png)

But got:
![image](https://user-images.githubusercontent.com/6960531/64530148-1fa21280-d315-11e9-985e-a507fa47bec7.png)

Extension version: 2019.5.0
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details>

**Comment by SydneyhSmith** [comment]
@ili101 thanks for opening this issue, and providing detailed repro...looks like we will need to make an update to our host...we are in the middle of some architecture work right now so may not get to this issue right away but I will mark as up for grabs and we will get to it as soon as we can. Thanks!

**Comment by andschwa** [comment]
Hey, this looks like it works with the latest preview! Please re-open if not.
