### ISSUE TITLE
Output window only opens first time run selection (F8) is used

### ISSUE THREAD

**Issue by jimbrownthrowaway** [PowerShell/vscode-powershell#217]
Extremely new to using both VS Code and the PowerShell Extension so please forgive me if I'm missing something obvious or if this shouldn't even be filed as an issue.

When you use F8 to run a selection of code the first time you do it the output window opens to show the results.  If you then close the output window and use F8 again it doesn't open the output window again, if you open it manually it shows the output.  I thought that the F8 command wasn't working at first because it was no longer opening the window so I didn't know it was actually executing the code.

I'm using VS Code 1.2.1 and PowerShell Extension 0.6.1 on Windows 10

**Comment by daviwil** [comment]
Yeah, the assumption I made here is that if the window had been auto-opened the first time and the user manually closed it, then it might get annoying if we auto reopen it each time output gets written.  I'm hoping to avoid this problem entirely in the near future by removing the current Run Selection functionality in favor of using the new integrated terminal for an ISE-like interactive experience.

**Comment by rkeithhill** [comment]
ISE will make the console pane visible on pressing F8, if it is not visible.  If "run selection" runs in the terminal window, and the terminal window is closed, the terminal window would be opened by the extension, right?  I think folks would expect that.

**Comment by daviwil** [comment]
Good point, Keith.  The correct trigger for opening the window should be the invocation of Run Selection rather than just from receiving output.

**Comment by daviwil** [comment]
Moving this to 0.8.0 because I might be able to get rid of it entirely if the new integrated terminal approach (#293) works out!
