### ISSUE TITLE
Intelisense defaults to last parameter when hitting CTRL-Space or TAB after '-'

### ISSUE THREAD

**Issue by chughesvf** [PowerShell/vscode-powershell#2173]
![intelisense](https://user-images.githubusercontent.com/32402463/64628919-4701e980-d3c0-11e9-85e8-2e3515cb4e49.jpg)

### System Details

System Details Output
```
### VSCode version: 1.39.0-insider 55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5 x64

### VSCode extensions:
bmaupin.copy-without-formatting@0.1.0
CoenraadS.bracket-pair-colorizer-2@0.0.28
eamodio.gitlens@9.9.3
huizhou.githd@2.1.0
jpogran.puppet-vscode@0.20.0
ms-vscode.csharp@1.21.2
ms-vscode.powershell-preview@2019.5.0
oderwat.indent-rainbow@7.4.0
Shan.code-settings-sync@3.4.2
Tyriar.theme-sapphire@0.9.1


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with intellisense when hitting ctrk-space or tab after a hyphen when filling out parameters. This seems to always default to the last one(typically pipelinevariable), which then starts triggering code blocks being inserted when pressing TAB and having to restart typing your parameter.

#### Expected Behaviour

-- Description of what *should* be happening --
I believe it should follow the order of the parameters as defined in the underlying function/cmdletso you can tab through them

#### Actual Behaviour

-- Description of what actually happens --
As described in the issue and seen in the two screen shots (one built in cmdlet and one custom function). Please advise if logs will assist with your troubleshooting

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.
![intelisense](https://user-images.githubusercontent.com/32402463/64629472-428a0080-d3c1-11e9-9b9c-eaa5648a7a4c.jpg)
![intellisense2](https://user-images.githubusercontent.com/32402463/64629473-428a0080-d3c1-11e9-9771-18527e3147fe.jpg)

**Comment by SydneyhSmith** [comment]
@chughesvf  thanks for opening this issue, looking at the details it seems this is a vscode bug so there unfortunately isnt much we can do to help...it would be great if you could open an issue in their repo....Thanks!

**Comment by PhilipHaglund** [comment]
Did anyone create an issue in the VSCode repository? My "search-fu" is failing. Or perhaps a workaround is present? :)

**Comment by SydneyhSmith** [comment]
@PhilipHaglund it does not appear that anyone has opened the issue in the VSCode repository, feel free to do the honors 😄

**Comment by MartinGC94** [comment]
Add `"editor.suggestSelection": "first"` to your settings.json file.
This will make the intellisense pop-up always show the first option in the list, and should solve your problem.
