### ISSUE TITLE
Vscode  can't Starting Expansion program Powershell

### ISSUE THREAD

**Issue by t105362506** [PowerShell/vscode-powershell#2174]
![image](https://user-images.githubusercontent.com/54572002/64664696-8133bf80-d482-11e9-87da-a14d86f769c5.png)

![image](https://user-images.githubusercontent.com/54572002/64664762-bb9d5c80-d482-11e9-9893-3d4961847e0f.png)

**Comment by t105362506** [comment]
Error log
![image](https://user-images.githubusercontent.com/54572002/64667006-cd82fd80-d48a-11e9-948e-eb17c24e368f.png)

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

Also, just your environment have any GPO requirements?

**Comment by t105362506** [comment]
What is GPO?
Attached log. Upside

**Comment by TylerLeonhardt** [comment]
@t105362506 GPO is Group Policy - restrictions enforced by your organization.

I don't see the attached logs. The link I sent shows you the steps on how to upload them. The screenshot of the logs that you supplied is good, but there's another log file we care about.

**Comment by t105362506** [comment]
Like this?

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/3614595/logs.zip)

**Comment by SydneyhSmith** [comment]
@t105362506 thanks for the logs, to help us debug better though it would be great if you could [provide diagnostic logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment), in other works set: 
`"powershell.developer.editorServicesLogLevel": "Diagnostic"`
