### ISSUE TITLE
PowerShell session crashes when ANSI escape codes are used

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#2176]
Issue Description
=====

I'm trying to use ANSI escape codes in Visual Studio Code, and experiencing frequent crashes of the extension.

```
Write-Host -Object "$([char]27)c"
Write-Host -Object "$([char]27)invalid"
```

After running this 5 - 10 times, the PowerShell extension eventually crashes and requires me to manually restart it. So far, I have only tested this on the system configuration included in this bug report.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Darwin x64 18.7.0 |
| VSCode | 1.38.0|
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|6.2.2|
|PSEdition|Core|
|GitCommitId|6.2.2|
|OS|Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019, root:xnu-4903.271.2~2/RELEASE_X86_64|
|Platform|Unix|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.2.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|LiveServer|ritwickdey|5.6.1|
|one-monokai|azemoh|0.3.7|
|powershell|ms-vscode|2019.5.0|
|python|ms-python|2019.9.34911|
|remote-containers|ms-vscode-remote|0.74.0|
|vscode-ansible|vscoss|0.5.2|
|vscode-icons|vscode-icons-team|9.3.0|

**Comment by rjmholt** [comment]
@pcgeek86 are you able to include any information about how the extension crashes? Can you please attach your [logs](https://github.com/PowerShell/vscode-powershell%23reporting-problems).

**Comment by pcgeek86** [comment]
@rjmholt I just sent the diagnostic logs to the `vscode-powershell` alias. Here's a screenshot of what I'm seeing when it crashes.

![Screen Shot 2019-09-15 at 5 46 00 PM](https://user-images.githubusercontent.com/466713/64930144-ac9c0e80-d7e2-11e9-8e53-7c2b0b617169.png)

**Comment by SydneyhSmith** [comment]
@pcgeek86 thanks for the screenshot! I did not see the logs searching through our mail, did you send them to  vscode-powershell@microsoft.com? Thanks!

**Comment by pcgeek86** [comment]
Hello @SydneyhSmith, yes I did send them to that address on September 15th. I just reproduced the issue again and sent a fresh copy though. Please confirm receipt!

**Comment by rjmholt** [comment]
Ah, now I've seen it with highlighting, my suspicion is that this is a crash I've seen happen with any subexpression in a string

**Comment by pcgeek86** [comment]
This isn't inactive. It's pending a resolution. The bot shouldn't be closing issues that haven't been addressed. 

Have you found anything further with subexpressions in strings @rjmholt?

**Comment by rjmholt** [comment]
I just tried making this happen in all the various ways:

- Writing a subexpression
- Using an ANSI code
- Both of the above while debugging

I wasn't able to reproduce the issue though.

It might be worth trying out preview and seeing if the problem is fixed there.

From your logs it looks like this occurred while debugging and our next preview release should have some improvements there.

**Comment by pcgeek86** [comment]
I've tried the PowerShell 7 preview, and even built some content around it, but haven't tried upgrading my development environment yet. Maybe I'll see if I can repro with VSCode devcontainers, although I don't want to introduce too many variables.

**Comment by rjmholt** [comment]
Hmmm, I just looked through the logs again and it looks like the only unhandled error there is a debugger crash.

That debugger crash has been fixed variously in:

- https://github.com/PowerShell/PowerShellEditorServices/pull/1022 (preview fix)
- https://github.com/PowerShell/PowerShellEditorServices/pull/1026 (stable fix)
- https://github.com/PowerShell/PowerShellEditorServices/pull/1043 (where the whole debug adapter in `master` runs on different, more robust infrastructure)

But I do remember seeing a similar crash to the one you report at some point, so let us know if you're hitting it still.
