### ISSUE TITLE
Powershell PSScriptAnalyser not working in Insiders builds

### ISSUE THREAD

**Issue by joaomoreno** [PowerShell/vscode-powershell#218]
_From @simon-michaud on July 6, 2016 13:3_

- VSCode Version:1.3.0-Insiders / Commit a1293f50
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. VSCode + Powershell Extension + Install-Module PSScriptAnalyser
2. No automatic analysys of ps1 / psm1 when  **"powershell.scriptAnalysis.enable": true** in _Default Settings_

Works from command line **Invoke-ScriptAnalyser** 

_Copied from original issue: Microsoft/vscode#8801_

**Comment by daviwil** [comment]
Hi @simon-michaud, we use a minimal set of Script Analyzer rules by default in the VS Code extension.  It's somewhat likely that you just haven't triggered any of the rules with your current code.  Could you give an example of some code which you expect to trigger a Script Analyzer rule?

**Comment by simon-michaud** [comment]
Ok, then I should try to set the rules to the ones Script Analyser on the
command line uses...

Can you tell me how to do this ?

**Comment by rkeithhill** [comment]
For a quick test, copy the following to a file under your home dir (say $home\pssa-settings.psd1):
```powershell
@{}
```
Then open up your user settings file in VSCode (Ctrl+Shift+P - type 'user' and select Open user settingss). Add the following to your user preferences settings:
```json
    "powershell.scriptAnalysis.settingsPath": "C:\\users\\your-username\\pssa-settings.psd1"
```
Save the user settings file and reload VSCode.  Now the extension will use the default rules for the script analyzer.

**Comment by simon-michaud** [comment]
Thanks for the info, everything works as expected now.

**Comment by daviwil** [comment]
Thanks for confirming, Simon!  I'll close this issue since it's resolved.
