### ISSUE TITLE
extra line after submitting command in VS Code terminal

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/vscode-powershell#2187]
Originally in https://github.com/PowerShell/PSReadLine/issues/1042

### System Details

System Details Output
```
### VSCode version: 1.38.1 b37e54c98e1a74ba89e03073e5a3761284e3ffb0 x64

### VSCode extensions:
eamodio.gitlens@9.9.3
GitHub.vscode-pull-request-github@0.11.1
GitHub.vscode-pull-request-github-insiders@2019.9.23035
le0zh.vscode-regexp-preivew@0.0.3
ms-mssql.mssql@1.6.0
ms-vscode.cpptools@0.25.1
ms-vscode.csharp@1.21.2
ms-vscode.powershell@2019.5.0
ms-vscode.powershell-preview@2019.5.0
ms-vscode.Theme-TomorrowKit@0.1.4
Serhioromano.vscode-st@1.7.1
vscode.theme-monokai-less-dimmed@0.0.1


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.18980
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
FYI, only the preview version is enabled.  VS Code indicates that the non preview version is not actually installed.

From PSReadLine:
```
PS version: 7.0.0-preview.3
PSReadline version: 2.0.0-beta4
os: 10.0.18975.1000 (WinBuild.160101.0800)
PS file version: 7.0.0.0
BufferWidth: 174
BufferHeight: 25
```
This is actually a build of PSReadLine using PR PowerShell/psreadline#979

Steps to reproduce
--------------------------------------
Using the Integrated PowerShell Console in VS Code's terminal (currently 1.38.1 Stable and Nightly) enter commands until the buffer (screen) is full.  At that time, every command entered seems to receive a blank line immediately after the last line of the command, before the results or next prompt appears.   This can be demonstrated with a blank command entry.

![image](https://user-images.githubusercontent.com/26179051/64835205-ad4a6000-d5aa-11e9-8c49-cc912e5bd418.png)

This does not happen with the normal Windows console, nor does this happen if I switch to CMD in a Integrated PowerShell Console session, inside VS Code's terminal.

![image](https://user-images.githubusercontent.com/26179051/64835279-0e723380-d5ab-11e9-8798-53cc45110b0b.png)

It would seem that when PSReadLine is enabled, an additional step is occurring that causes the extra line feed, only when the cursor is already at the bottom of the buffer.  If PSReadLine support is disabled (pasting scripts become more difficult), the issue goes away.

This does not happen in the regular VS Code terminal when PowerShell is the shell, regardless of PSReadLine.

**Comment by TylerLeonhardt** [comment]
@msftrncs does this repro in the non-"PowerShell Integrated Console" in vscode? Open a new terminal with the plus button and type `pwsh-preview` and see if it repros there.

**Comment by msftrncs** [comment]
I had previously determined that this only happens in the Integrated PowerShell Console from the VSCode-PowerShell extension, and that it only occurs while PSReadLine support in the integrated console is enabled.  I also checked that Posh-Git didn't affect the issue any, no change when Posh-Git is removed.  Only the integrated console with the experimental PSReadLine support enabled causes extra lines once the cursor reached the bottom.

@SeeminglyScience seems to know something about it.  😃 (https://github.com/PowerShell/PSReadLine/issues/1042#issuecomment-532457580)

**Comment by msftrncs** [comment]
I might also add, it does seem to happen regardless of the version of PowerShell.  I just quickly checked Windows PowerShell and PowerShell Core 6 selections for the Integrated PowerShell Console, and both had the same issue occurring as well.

**Comment by whitTech** [comment]
Hey @TylerLeonhardt and @SeeminglyScience,

Just wanted to bump this niggly little issue. Patrick indicated in 1042 that this was likely a quick fix. If someone could take 10 mins and confirm if this is the case or not (and then manage expectations accordingly), it would be much appreciated.

Thanks all (esp. @msftrncs for opening the issue).

**Comment by SeeminglyScience** [comment]
> Patrick indicated in 1042 that this was likely a quick fix. If someone could take 10 mins and confirm if this is the case or not (and then manage expectations accordingly), it would be much appreciated.

Nah those fixes are already in afaik.  I haven't personally ran into the double new line issue in a pretty long while.

**Comment by rjmholt** [comment]
This would be fixed by PowerShell/PowerShellEditorServices#1295

**Comment by o-l-a-v** [comment]
Soon two years since this issue was created. Are we waiting for the PowerShellEditorServices issue 1295? Any ETA?

![image](https://user-images.githubusercontent.com/6450056/130568173-2cc7b84a-5505-4150-b787-0f5d416b528d.png)

**Comment by andschwa** [comment]
Indeed, we are. It is progressing! @rjmholt just replaced the entire prompt logic, much simplifying it, and is working on plumbing through cancellation tokens now. We can't commit to any particular date, but we are actively working on it and hope to have it as soon as possible.
