### ISSUE TITLE
Status bar items have bad contrast

### ISSUE THREAD

**Issue by misolori** [PowerShell/vscode-powershell#2188]
### Issue Description

I am experiencing a problem with the status bar item because the color used does not have enough contrast.

#### Expected Behaviour

A status bar item that is readable on all themes

#### Actual Behaviour

The status bar item is explicitly settings color that isn't a color token, which means it's going to look bad on other themes because it isn't themeable:

![image](https://user-images.githubusercontent.com/17877082/65108075-ae8fe880-da01-11e9-9296-e083bb249bd9.png)

![image](https://user-images.githubusercontent.com/17877082/65107878-94eea100-da01-11e9-9f5b-c289bac326bd.png)

Code reference:
https://github.com/PowerShell/vscode-powershell/blob/66a39de11087fe3ecc60cf04ed4b587fd8b4c317/src/session.ts#L652-L666

**Comment by SydneyhSmith** [comment]
@misolori thanks for opening this issue, I am going to mark this as a duplicate of #1779 but please let me know if you do not believe this to be the same issue, thanks!

**Comment by misolori** [comment]
@SydneyhSmith that will work, I'll leave a comment there. Thanks!
