### ISSUE TITLE
Shortcut to change the current directory in the PowerShell console to the currently opened file?

### ISSUE THREAD

**Issue by skataben** [PowerShell/vscode-powershell#2189]
I am running the PowerShell extension in Visual Studio Code with its PowerShell Integrated Console attached. I have two PowerShell scripts each open in separate tabs. The files are located in different directories.

I would like to quickly change the current directory to the currently active tab in the PowerShell console using a keyboard shortcut (e.g. Ctrl+Alt+D).

How does one accomplish this?

https://stackoverflow.com/questions/57893791

**Comment by TylerLeonhardt** [comment]
You would do it like this in script:

```pwsh
Set-Location ([IO.Path]::GetDirectoryName($PSEditor.GetEditorContext().CurrentFile.Path))
```

You could register an Editor Command to be quick about it:

```pwsh
Register-EditorCommand -Name ChangeToDir -DisplayName "Change to the Directory of the Current File" -ScriptBlock {
    Set-Location ([IO.Path]::GetDirectoryName($PSEditor.GetEditorContext().CurrentFile.Path))
}
```

Then you can do:

`cmd+shift+s (or ctrl+shift+s on non-macOS I think)`

Then find `"Change to the Directory of the Current File"` in the list!

**Comment by code-glue** [comment]
Thank you for the response. It works.

Is there no way to assign a keyboard shortcut directly to "ChangeToDir"?

**Comment by SeeminglyScience** [comment]
Not currently due to #2145, but after that's fixed it'll be possible.

**Comment by skataben** [comment]
Thank you

**Comment by code-glue** [comment]
I found a better solution from StackOverflow that works in both the cmd and PowerShell consoles. (Better because it is a keyboard shortcut and not a menu selection.)

In the keybindings.json file, add the following key binding:

{
    "key": "ctrl+alt+d",
    "command": "workbench.action.terminal.sendSequence",
    "args": {"text": "cd \"${fileDirname}\"\u000D"}
}

https://stackoverflow.com/questions/57893791

**Comment by skataben** [comment]
I found a better solution from StackOverflow that works in both the cmd and PowerShell consoles. (Better because it is a keyboard shortcut and not a menu selection.)

In the keybindings.json file, add the following key binding:

{
"key": "ctrl+alt+d",
"command": "workbench.action.terminal.sendSequence",
"args": {"text": "cd "${fileDirname}"\u000D"}
}

https://stackoverflow.com/questions/57893791
