### ISSUE TITLE
Debugger cannot find [System.Drawing.Color] when in script

### ISSUE THREAD

**Issue by gerane** [PowerShell/vscode-powershell#219]
When debugging a script that contains a Color type it throws an error.

Example is using `New-SlackMessageAttachment -Color $([System.Drawing.Color]::red)`

```powershell
Unable to find type [System.Drawing.Color].
+ New-SlackMessageAttachment -Color $([System.Drawing.Color]::red) `
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Drawing.Color:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
Unable to find type [System.Drawing.Color].
+ ... SlackMessageAttachment -Color $([System.Drawing.Color]::LightGreen) `
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Drawing.Color:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

**Comment by rkeithhill** [comment]
You need to load that assembly `Add-Type -Assembly System.Drawing`

**Comment by gerane** [comment]
Why does the debugger need to load it? Running in any other context does
not require it to be loaded.

**Comment by rkeithhill** [comment]
Well, if I fire up a PowerShell v5 console with `-NoProfile` it doesn't have the assembly loaded either:
```
PS C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices> [System.Drawing.Color]::LightGreen
Unable to find type [System.Drawing.Color].
At line:1 char:1
+ [System.Drawing.Color]::LightGreen
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Drawing.Color:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```
However, once I execute `Out-GridView` that assembly is loaded.  It would also be loaded by default for ISE since ISE is a WPF app.  

I wouldn't rely on PowerShell loading an assembly meant for GUI apps.  For instance, you could get the debugger to work by simply calling this command before referencing the color:
```powershell
Microsoft.PowerShell.Management\Get-Clipboard | Out-Null
```
That command pulls in WinForms, which pulls in System.Drawing.  IMO it is better to explicitly add the assembly.

**Comment by daviwil** [comment]
Yep, that assembly is not loaded by default.  Keith is correct, it gets loaded when anything UI-related gets loaded into the PowerShell session.  Out-GridView is one way, running your code in the ISE is another way.  If the Slack module depends on that type it needs to call `Add-Type -Assembly System.Drawing` when the module gets loaded.

If you start `powershell.exe` with `-NoProfile` and try to run that command, does it work?

**Comment by gerane** [comment]
This isn't actually a GUI app, but is sending a slack message. The color was for the color of the notification. I will just have to add the type before hand.

**Comment by rkeithhill** [comment]
It doesn't have to be a GUI app.  I have PSReadline handler function loaded in my profile that loads WinForms to copy stuff to the clipboard.  When testing, I try to always fire up PowerShell with `-NoProfile` to make sure that I'm testing in more of a "clean state".

**Comment by rkeithhill** [comment]
Closed issue as "by design".
