### ISSUE TITLE
How to suppress analysis warnings?

### ISSUE THREAD

**Issue by bigheadzen** [PowerShell/vscode-powershell#22]
Some analysis warnings are really annoying. Can I suppress the warnings?
For example, it there's a issue about the Function Name, it will put a green line under all the content in that function.

**Comment by daviwil** [comment]
I've fixed this issue for the next release which should hopefully be out today.  The issue is already being tracked by the following issue so I'll go ahead and close yours:

https://github.com/PowerShell/vscode-powershell/issues/11

Let me know if you have any questions!
