### ISSUE TITLE
Link in generated text for Command Palette "Powershell: Upload Bug Report to Github points to 404 page

### ISSUE THREAD

**Issue by Line40** [PowerShell/vscode-powershell#2201]
### System Details

```
### VSCode version: 1.38.0 3db7e09f3b61f915d03bbfa58e258d6eee843f35 x64

### VSCode extensions:
DotJoshJohnson.xml@2.5.0
formulahendry.auto-close-tag@0.5.6      
magicstack.MagicPython@1.1.0
MS-CEINTL.vscode-language-pack-de@1.37.5
ms-python.python@2019.9.34474
ms-vscode-remote.remote-wsl@0.39.2      
ms-vscode.cpptools@0.25.1
ms-vscode.powershell@2019.5.0
naco-siren.gradle-language@0.2.3
openhab.openhab@0.5.1
telesoho.vscode-markdown-paste-image@0.12.2
tushortz.python-extended-snippets@0.0.1


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I just tried to file a bug report, with the Visual Studio Code Command Palette Tool "Powershell: Upload Bug Report to Github" and in the page opened by the browser, the link in the text template on how to report a bug report, contains ```%23``` instead of a ```#```. When pasted into the browser's address bar, it opens the github 404 page,.

#### Expected Behaviour

The link in the generated text template should be ```https://github.com/PowerShell/vscode-powershell#reporting-problems```

#### Actual Behaviour

The link is currently ```https://github.com/PowerShell/vscode-powershell%23reporting-problems```

### Attached Logs

N/A

**Comment by TylerLeonhardt** [comment]
This seems to be an issue with vscode. I've opened it here:
https://github.com/microsoft/vscode/issues/81398
