### ISSUE TITLE
Powershell Integrated Console Error with ConstrainedLanguage Mode

### ISSUE THREAD

**Issue by Stingrey** [PowerShell/vscode-powershell#2208]
In our company they changed the language mode and now the integrated console wont start and just quits with an Error. Is that an expected behavior?

PowerShell Integrated Console
PowerShell is configured with an unsupported LanguageMode (ConstrainedLanguage), language features are disabled.

24.9.2019 09:11:37 [NORMAL] - Visual Studio Code v1.38.1 64-bit
24.9.2019 09:11:37 [NORMAL] - PowerShell Extension v2019.9.0
24.9.2019 09:11:37 [NORMAL] - Operating System: Windows 64-bit
24.9.2019 09:11:37 [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
24.9.2019 09:11:37 [NORMAL] - Language server starting --
24.9.2019 09:11:37 [NORMAL] -     exe: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
24.9.2019 09:11:37 [NORMAL] -     args: c:\Users\ABCDE\.vscode\extensions\ms-vscode.powershell-2019.9.0\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2019.9.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\ABCDE\.vscode\extensions\ms-vscode.powershell-2019.9.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\ABCDE\.vscode\extensions\ms-vscode.powershell-2019.9.0\logs\1569309097-56e556dc-18eb-4fd1-86df-8b0c97dd23ce1569309090540\EditorServices.log' -SessionDetailsPath 'c:\Users\ABCDE\.vscode\extensions\ms-vscode.powershell-2019.9.0\sessions\PSES-VSCode-17304-211679' -FeatureFlags @()
24.9.2019 09:11:39 [ERROR] - PowerShell language features are disabled due to an unsupported LanguageMode: ConstrainedLanguage

**Comment by rjmholt** [comment]
Constrained Language Mode is not currently supported by the extension because the way the extension starts requires type invocations/things that don't work in Constrained Language Mode. The solution is for us to migrate to a binary module for startup, but we haven't planned for that work yet.

We're tracking this in https://github.com/PowerShell/vscode-powershell/issues/606.
