### ISSUE TITLE
Syntax highlighting broken for braced variable in string

### ISSUE THREAD

**Issue by otstrel** [PowerShell/vscode-powershell#221]
Syntax highlighting appears to be broken for braced variable in string surrounded by curly braces (`{"${t}_"}`):
![image](https://cloud.githubusercontent.com/assets/3508928/16683870/a478ca2c-450a-11e6-8cec-23512549fe67.png)
Works fine without outer braces (`"${t}_"`):
![image](https://cloud.githubusercontent.com/assets/3508928/16683878/ad6dab3e-450a-11e6-8c73-35a4dcd6987c.png)

Worst part is that highlighting becomes messed up that point forward:
![image](https://cloud.githubusercontent.com/assets/3508928/16683945/f0558a8e-450a-11e6-8cdf-fd1c94d8691d.png)

**Comment by daviwil** [comment]
Hey @okallstad, is this something you could add to your PR?

**Comment by gravejester** [comment]
I'm on it :)

**Comment by bahaula** [comment]
Just adding to this one.
I'm not yet sure if it's related but a similar case:
![image](https://cloud.githubusercontent.com/assets/518296/16802014/db60e894-4906-11e6-9131-39b1aec6f1f8.png)
I guess it's broken when using properties with spaces also.

**Comment by daviwil** [comment]
Should be fixed with this commit: https://github.com/gravejester/EditorSyntax/commit/990a2ca3db8afed4b124d18083070728c70fa5cd

We'll be submitting a PR to VS Code to get the syntax definition updated for their next release.
