### ISSUE TITLE
'Run tests|Debug tests' Pester code lens does not scroll to bottom

### ISSUE THREAD

**Issue by Sharken03** [PowerShell/vscode-powershell#2210]
When running either of the `Run tests|Debug tests` code lens commands and the Terminal window is not at the bottom, then new output will be added but not shown.
It would be great if Scroll to bottom could be performed before the code lens command executes.

This was tested with PowerShell Preview 2019.5.0 and VS Code 1.37.1.

**Comment by fflaten** [comment]
This was fixed somewhere around the PSES rewrite (v2022.5.0) AFAIK. Please verify 🙂 
/cc @andschwa
