### ISSUE TITLE
Frequent crashes when debugging a script that uses Microsoft.Office.Interop.Excel assembly

### ISSUE THREAD

**Issue by brobdingbat** [PowerShell/vscode-powershell#2218]
### System Details
OS: Windows 10 1803

VS Code: Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

PowerShell extension: 2019.9.0

PSVersion: 5.1.17134.858
PSEdition: Desktop
PSCompatibleVersions: {1.0, 2.0, 3.0, 4.0...}
BuildVersion: 10.0.17134.858
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

System Details Output
```

```

### Issue Description

I am experiencing frequent crashes when debugging such script. The PowerShell extension crashes and wants to reload itself. Actually, impossible to debug such script because of the number of crashes.

#### Expected Behaviour

Such script can be debugged without any problems, just like in the Windows PowerShell ISE. This error does not occur in the ISE.

#### Actual Behaviour

The script debugging breaks and the PowerShell extension displays an error message saying it has been terminated due to an error and do I want to reload that?!

### Attached Logs

Created the diagnostic log and sent to vscode-powershell@microsoft.com
The sent log file has this name: 1569850878-c4a1936b-c3df-4643-9080-2cc886dca7531569849859452.zip

**Comment by rjmholt** [comment]
Hi @brobdingbat, thanks for opening an issue.

We took a look at the log file you sent through, but in the case of a crash that issues the dialog you get, it should be logging an error, which wasn't present in the log file.

Would you be able to recollect the logs with the following steps:

- Set the log level to `diagnostic`
- Restart the PowerShell extension and use it until it crashes
- Do not restart the PowerShell extension or any settings at that point
- Collect the logs and send them through
- Then make any settings changes and restart the extension

Thanks!

**Comment by brobdingbat** [comment]
Hi!

Thanks for your letter (and re-opening the bug)! Now, I have followed your
instructions and collected the diagnostic logs as you requested. The e-mail
I sent had this subject: "Log file to issue #2218"

Thanks and best regards,

Brob

**Comment by SydneyhSmith** [comment]
@brobdingbat thanks for providing the logs, there is nothing obvious in these logs that indicate what is causing this problem, therefore it may be tied to general instability in the extension which is currently being addressed with major re-architecture changes, hopefully the next release of the extension will address these issue but if not we will re-investigate....thanks again for opening this issue and being patient with our improvements.

**Comment by rjmholt** [comment]
Also you might want to try the powershell-preview extension to see if that fixes anything

**Comment by andschwa** [comment]
Hello! The latest code is available in the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview), and includes a myriad of fixes. Could you verify if this issue still reproduces using the preview extension? Please note that this preview is likely to include other bugs, and you should feel free to file new issues for those so we can work through them. Thanks again!

**Comment by andschwa** [comment]
Going to assume it's no longer an issue, thanks!
