### ISSUE TITLE
PowerShell Integrated Console freezes at startup

### ISSUE THREAD

**Issue by quonic** [PowerShell/vscode-powershell#2219]
Issue Type: <b>Bug</b>

PowerShell Integrated Console freezes at startup. It happens nearly every time VSCode is started. Sometimes hitting enter multiple times gets it unstuck, but isn't a reliable way to work around the problem. I do have multiple Powershell projects opening. Testing with just one Powershell project, exhibits the same problem. A normal Powershell terminal does almost the same things, but hitting enter gets it unstuck.

PowerShell Integrated Console output:
```
PowerShell Integrated Console

[] <-- cursor stuck here
```

powershell terminal:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.





PS C:\Users\quonic\Documents\Projects\work> PS>
```

Extension version: 2019.9.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by TylerLeonhardt** [comment]
This issue has come up before I believe... and you say it also happens in a regular powershell terminal in vscode.

@tyriar this might be a vscode terminal issue - what do you think?

**Comment by quonic** [comment]
@TylerLeonhardt It only happens on my work computer, but my home computer seems fine.
The work computer has had this problem for quite some time.

I don't know if this help, but the home computer for reference:

Extension version: 2019.9.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (24.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by TylerLeonhardt** [comment]
Thanks @Tyriar. I'll close this as a duplicate then. Thanks!
