### ISSUE TITLE
Syntax highlighting broken when accessing a csv-file

### ISSUE THREAD

**Issue by BornToBeRoot** [PowerShell/vscode-powershell#222]
Maybe it's the same as #221

![image](https://cloud.githubusercontent.com/assets/16019165/16695512/9a6f7e6e-4540-11e6-8a63-ca5aac1e8b99.png)

Edit: VSCode 1.3.0 & PowerShell Extension 0.6.1

**Comment by gravejester** [comment]
Yes, this bug will be fixed in the next update.

**Comment by daviwil** [comment]
This will be fixed in VS Code as soon as we get our fixed syntax definition merged in the VS Code repo.  Thanks for the report!
