### ISSUE TITLE
Powershell extension errors on OSX V 10.14.6 

### ISSUE THREAD

**Issue by zlDev** [PowerShell/vscode-powershell#2220]
Issue Type: <b>Bug</b>

I'm getting the following errors on OSX V 10.14.6  : 
"The language service could not be started" 
and 
"The terminal shell path "/usr/local/bin/pwsh" does not exist"

10/2/2019 3:09:28 PM [NORMAL] - Visual Studio Code v1.38.1 64-bit
10/2/2019 3:09:28 PM [NORMAL] - PowerShell Extension v2019.9.0
10/2/2019 3:09:28 PM [NORMAL] - Operating System: MacOS 64-bit
10/2/2019 3:09:28 PM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
10/2/2019 3:09:28 PM [NORMAL] - Language server starting --
10/2/2019 3:09:28 PM [NORMAL] -     exe: /usr/local/bin/pwsh
10/2/2019 3:09:28 PM [NORMAL] -     args: /Users/dmitrijsizotovs/.vscode/extensions/ms-vscode.powershell-2019.9.0/modules/PowerShellEditorServices/Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2019.9.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/dmitrijsizotovs/.vscode/extensions/ms-vscode.powershell-2019.9.0/modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath '/Users/dmitrijsizotovs/.vscode/extensions/ms-vscode.powershell-2019.9.0/logs/1570025368-66fbbab0-fa48-4f73-b077-e830e3ae43f41570025365431/EditorServices.log' -SessionDetailsPath '/Users/dmitrijsizotovs/.vscode/extensions/ms-vscode.powershell-2019.9.0/sessions/PSES-VSCode-6074-645231' -FeatureFlags @()
10/2/2019 3:09:28 PM [NORMAL] - powershell.exe terminated or terminal UI was closed
10/2/2019 3:11:28 PM [NORMAL] - Language server startup failed.
10/2/2019 3:11:28 PM [ERROR] - The language service could not be started: 
10/2/2019 3:11:28 PM [ERROR] - Timed out waiting for session file to appear.
10/2/2019 3:12:13 PM [NORMAL] - Shutting down language client...
10/2/2019 3:12:13 PM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
10/2/2019 3:12:13 PM [NORMAL] - Language server starting --
10/2/2019 3:12:13 PM [NORMAL] -     exe: /usr/local/bin/pwsh
10/2/2019 3:12:13 PM [NORMAL] -     args: /Users/dmitrijsizotovs/.vscode/extensions/ms-vscode.powershell-2019.9.0/modules/PowerShellEditorServices/Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2019.9.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/dmitrijsizotovs/.vscode/extensions/ms-vscode.powershell-2019.9.0/modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath '/Users/dmitrijsizotovs/.vscode/extensions/ms-vscode.powershell-2019.9.0/logs/1570025533-66fbbab0-fa48-4f73-b077-e830e3ae43f41570025365431/EditorServices.log' -SessionDetailsPath '/Users/dmitrijsizotovs/.vscode/extensions/ms-vscode.powershell-2019.9.0/sessions/PSES-VSCode-6074-564638' -FeatureFlags @()
10/2/2019 3:12:13 PM [NORMAL] - powershell.exe terminated or terminal UI was closed
10/2/2019 3:14:13 PM [NORMAL] - Language server startup failed.
10/2/2019 3:14:13 PM [ERROR] - The language service could not be started: 
10/2/2019 3:14:13 PM [ERROR] - Timed out waiting for session file to appear.

Extension version: 2019.9.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|-psn_0_1073414|
|Screen Reader|no|
|VM|29%|
</details>

**Comment by TylerLeonhardt** [comment]
@zlDev do you have PowerShell installed on your machine? If so, how did you install it?

**Comment by zlDev** [comment]
Silly me. I have installed the PS now and the error is gone. Closed.

**Comment by TylerLeonhardt** [comment]
Great!
