### ISSUE TITLE
Set start path

### ISSUE THREAD

**Issue by ustcfdm** [PowerShell/vscode-powershell#2227]
The start path of the integrated console is user's home path. It will be convenient if I can set the start path to be the current file folder. I found that this can be set in vs code terminal, but not in PowerShell Integrated Console. In vs code terminal, the configuration is
```
// Open the terminal in the currently opened file's directory
  "terminal.integrated.cwd": "${fileDirname}"
```
I just need a similar configuration for integrated console, such as 
`"powershell.cwd": "${fileDirname}"`

**Comment by SydneyhSmith** [comment]
@ustcfdm thanks for bringing this issue up, looks like a great idea--I will mark it up for grabs!

**Comment by SydneyhSmith** [comment]
The way to add this feature would be to set the cwd of the integrated console when we create the terminal using this API https://code.visualstudio.com/api/references/vscode-api#TerminalOptions
