### ISSUE TITLE
Install-VSCode has stopped working for installing user-builds with Windows Powershell greater than 5

### ISSUE THREAD

**Issue by hanpq** [PowerShell/vscode-powershell#2229]
The install-vscode.ps1 script seems to be broken for Windows PowerShell versions greater than 5 combined with running buildversions of type "user". 

Recently added line 463 targets versions less than 5, however, shouldn't it be less than 6?
463: if ($BuildEdition.EndsWith('User') -and -not ($IsWindows -or $PSVersionTable.PSVersion.Major -lt 5)) {

This line excludes all Windows Powershell versions greater than 5 like 5.1.

The same check is also performed within the function Get-CodePlatformInformation but correctly specifies "less than 6"

209: if ($IsWindows -or $PSVersionTable.PSVersion.Major -lt 6) {

The error message I get when running this script on Windows Powershell version 5.1 is:
"User builds are not available for non-Windows systems"

Kind regards
Hannes Palmquist

**Comment by TylerLeonhardt** [comment]
Yep, you're right! @rjmholt fixed that conditional.
