### ISSUE TITLE
Install via vsix behind coperate proxy

### ISSUE THREAD

**Issue by GitChow** [PowerShell/vscode-powershell#223]
proxy issue, how can I install it manually via download? I try to put the git resources as a folder under "extension", but it seems not working. I saw relevant documentation talking about  .vsix file, how can I create it from your source? or do you provide? thanks a lot !

**Comment by daviwil** [comment]
Hey @GitChow, check out our [Releases](https://github.com/PowerShell/vscode-powershell/releases) page.  For each release I prepare a ZIP file containing the extension files.  You should be able to extract this zip file into the path `$HOME\.vscode\extensions`.  Let me know if you have any trouble with this.

**Comment by GitChow** [comment]
Great, thank you @daviwil , it works now !!
