### ISSUE TITLE
Configure launch.json for VSCode to execute PowerShell commands in the debug session

### ISSUE THREAD

**Issue by Hypernut** [PowerShell/vscode-powershell#2231]
Is it possible to create an entry in the launch.json, which executes a PowerShell script or scriptblock, in the **same runspace** as the then to-be-launched-and-debugged script?

The reason is, I would like to reset the runspace (remove variables + background jobs, unload modules etc.) **before** debugging a script. 
The "temporary integrated console" which was created for that purpose, unfortunately has an unfixed [bug ](https://github.com/PowerShell/vscode-powershell/issues/1263)for over a year now, which prevents interactive debugging in the temporary console and therefore makes it useless to me.
Thanks!

**Comment by SydneyhSmith** [comment]
@Hypernut thanks for bringing this issue back up to our attention..unfortunately there is no configuration that achieves what you are looking for. We are currently doing significant work in the debugger and hope to resolve this issue, we will continue to track this issue with #1263

**Comment by Hypernut** [comment]
That would be great.
