### ISSUE TITLE
terminal path not found and powershell language service fails to start on MAC

### ISSUE THREAD

**Issue by yefimovah** [PowerShell/vscode-powershell#2243]
Issue Type: <b>Bug</b>

Hi there,

I've been getting the following two errors for about a month now. "The langage service could not be started" and "The terminal shell path "/usr/local/bin/pwsh" does not exist" 

Extension version: 2019.9.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (6.00GB free)|
|Process Argv|-psn_0_311372|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yefimovah** [comment]
It’s working fine now.. thank you

**Comment by TylerLeonhardt** [comment]
Looks like you're good now. I'll close this issue. Feel free to reach out if you have any other issues!
