### ISSUE TITLE
2019.9.0 does not honor the powershell.codeFormatting.WhitespaceInsideBrace setting

### ISSUE THREAD

**Issue by adegutis** [PowerShell/vscode-powershell#2245]
### System Details

System Details Output
```
### VSCode
Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.14393

### VSCode extensions:
christian-kohler.path-intellisense@1.4.2
CoenraadS.bracket-pair-colorizer@1.0.61
contagio.vs-edit-hosts@0.0.1
DavidAnson.vscode-markdownlint@0.31.0
GitHub.vscode-pull-request-github@0.12.0
GrapeCity.gc-excelviewer@2.1.32
mechatroner.rainbow-csv@1.3.1
mhutchie.git-graph@1.17.0
ms-vscode.powershell@2019.9.0


### PSES version: 1.13.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.14393.3053
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3053
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with the powershell.codeFormatting.WhitespaceInsideBrace setting in v2019.9.0

#### Expected Behaviour

When that settings is disabled in the User and Workspace settings, it should not change the whitespace in between braces

#### Actual Behaviour

Spaces are added after the `{` and before the `}`

```powershell
Get-ChildItem -Path $Destination -Recurse -File |
    ForEach-Object { $_.FullName }
```

The attached GIF shows that the behavior worked correctly in 2019.5.0 but is now broken in 2019.9.0

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.
![vscode-powershell 2019 9 0-whitespace-brace-bug](https://user-images.githubusercontent.com/6013968/67114240-1cfecc80-f1a1-11e9-81e0-a1738ff86495.gif)

**Comment by corbob** [comment]
I believe this is resolved with the next release by PowerShell/PowerShellEditorServices#1050 (assuming I'm understanding the issue correctly and it's the same as #2214 )
