### ISSUE TITLE
IntelliSense does not work when variables and functions of external files are read.

### ISSUE THREAD

**Issue by kurisan1623** [PowerShell/vscode-powershell#2256]
```powershell
#include.ps1

$a = 1

#test.ps1
.".\include.ps1"
# I want to use variable a here
```

**Comment by SydneyhSmith** [comment]
@kurisan1623 thanks for opening this issue...if you run `.".\include.ps1"` (by pressing F8) you will get the completions, we do not automatically run scripts because this could be potentially dangerous...let us know if this is not what you were asking for--thanks

**Comment by kurisan1623** [comment]
I want to supplement the functions and variables defined in include.ps1 with test.ps1.
For example, if you define $ include in include.ps1, enter $ inc in test.ps1 and press tab to complete $ include.
Sorry for the lack of explanation.

**Comment by rjmholt** [comment]
> I want to supplement the functions and variables defined in include.ps1 with test.ps1.
For example, if you define $ include in include.ps1, enter $ inc in test.ps1 and press tab to complete $ include.

The current supported way to get that intellisense here is to run `include.ps1` in your session.

We get our completions from PowerShell's completion API, which doesn't pick up things like variables exported by a dot-source.

The biggest reason for this is that variable definition in PowerShell is not something that can be statically determined. It depends on how the script executes at runtime. The only way to know this is to execute the script. If we did that, it could do anything and would be dangerous.

**Comment by kurisan1623** [comment]
@SydneyhSmith
@rjmholt
Thank you very much.  I was mistaken.  The code was completed by selecting the code in include.ps1 and pressing f8.
