### ISSUE TITLE
The closing single or double quote of a member name is treated like the start of a string.

### ISSUE THREAD

**Issue by treestryder** [PowerShell/vscode-powershell#226]
Example
`# This is the normal color of a comment.
$TestObject = New-Object -Properties 'Member With A Space'
$TestObject.'Member With A Space' # This is orange because vscode-powershell behaves as if the closing quote starts a new string.`

Screen Shot
![vscode_member_with_space](https://cloud.githubusercontent.com/assets/3682967/16816393/b134dabc-490b-11e6-8af9-c16403877c6f.png)

**Comment by daviwil** [comment]
I think @gravejester has fixed this issue: https://github.com/PowerShell/EditorSyntax/issues/10.  It should be resolved for you in the next VS Code release.

**Comment by treestryder** [comment]
Yep. Looks the same to me. Thanks.
