### ISSUE TITLE
$host.UI.RawUI.ReadKey() -method "not implemented" in integrated console

### ISSUE THREAD

**Issue by Hypernut** [PowerShell/vscode-powershell#2265]
Issue Description
=====

`$host.UI.RawUI.ReadKey() `results in an "**method not implemented**"-Error in the integrated console.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.39.2|
| PowerShell Extension Version | 2019.9.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.17134.858|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.858|
|BuildVersion|10.0.17134.858|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|ayu|teabyii|0.18.0|
|Bookmarks|alefragnani|10.5.0|
|code-runner|formulahendry|0.9.14|
|MagicPython|magicstack|1.1.0|
|markdown-preview-enhanced|shd101wyy|0.5.0|
|material-icon-theme|PKief|3.9.1|
|powershell|ms-vscode|2019.9.0|
|python|ms-python|2019.10.44104|
|referenceshelper|gayanhewa|0.2.3|
|xml|DotJoshJohnson|2.5.0|

**Comment by TylerLeonhardt** [comment]
This should be implemented already in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension. Can you install that and give it a try?
