### ISSUE TITLE
Support comment-based help expansion above script param block

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#2268]
The extension currently supports `##` expanding out to comment based help above functions, but not above script param blocks.

Ideally in a script, I'd be able to do this:

```powershell
## <-- expand comment-based help here
param([string]$Name)

Write-Host $Name
```

**Comment by TylerLeonhardt** [comment]
@rjmholt do you know if PSSA warns for this on param blocks at the start of scripts?

**Comment by rjmholt** [comment]
Oh good question! Will have to look into it

**Comment by TylerLeonhardt** [comment]
Gave it a try, PSSA does not give us that so we need to ask them for that first. If they leverage the same rule, this experience could "just work"

**Comment by TylerLeonhardt** [comment]
Opened an issue on PSSA https://github.com/PowerShell/PSScriptAnalyzer/issues/1363 lets close this issue for now until that's done.
