### ISSUE TITLE
Cursor placed incorrectly on PowerShell Extension Version 2019.11.0

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2276]
Issue Description
=====

I am experiencing a problem with... cursor being moved/placed incorrectly on the screen if there's no output to console. 

![image](https://user-images.githubusercontent.com/15063294/68113539-4f742d80-fef4-11e9-9a01-077447e80b6d.png)

Please keep in mind I have not typed @ at all. Reported in another issue. 

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.39.2|
| PowerShell Extension Version | 2019.11.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.17763.771|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17763.771|
|BuildVersion|10.0.17763.771|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|gitlens|eamodio|10.1.1|
|material-icon-theme|PKief|3.9.1|
|open-in-browser|techer|2.0.0|
|powershell-preview|ms-vscode|2019.11.0|
|theme-monokai-pro-vscode|monokai|1.1.14|
|vscode-wakatime|WakaTime|2.2.1|

**Comment by rjmholt** [comment]
Debugging this, the script is executed [here](https://github.com/PowerShell/PowerShellEditorServices/blob/1af798809ed832299d55e50b6fad16134295d983/src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs#L62).

Eventually this reaches the execution context [here](https://github.com/PowerShell/PowerShellEditorServices/blob/1af798809ed832299d55e50b6fad16134295d983/src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs#L105-L106).

Finally, watching the console, the indentation seems to occur [here](https://github.com/PowerShell/PowerShellEditorServices/blob/1af798809ed832299d55e50b6fad16134295d983/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L672).

**Comment by PrzemyslawKlys** [comment]
This: #1727 can probably be closed because it changed with this new version - but still related on how you handle it. 

#2274 some insight in this issue are related to this issue.

**Comment by SydneyhSmith** [comment]
This should be fixed by: https://github.com/PowerShell/PowerShellEditorServices/pull/1162
