### ISSUE TITLE
Ctrl+Click opens browser to Microsoft Documentation

### ISSUE THREAD

**Issue by cbb330** [PowerShell/vscode-powershell#2277]
As a user, I want to have a shortcut to use on Powershell Commands so that when activated, the user's browser will open to the official Microsoft Documentation on the Command.

**Comment by corbob** [comment]
If I understand the request properly, you can do this with Ctrl+F1 (also available in right click menu):
![image](https://user-images.githubusercontent.com/30301021/68149044-058a4800-fef2-11e9-9d67-fb719c55fa50.png)

This will take you to the online help if it exists (and returns a successful HTTP code), or show the help in the console if it doesn't.

**Comment by cbb330** [comment]
Ah, yes! That's exactly what I was looking for. Thank you for the help.
