### ISSUE TITLE
Execution status indicator no longer appearing/working in status bar

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#2284]

**Comment by rjmholt** [comment]
Is it possible that the UI for this API has changed? I do see a blue indicator under the top left when I run things. My suspicion is that our API call still works, but that VSCode has changed the way they present it.

**Comment by rjmholt** [comment]
Link to @corbob's description: https://github.com/PowerShell/vscode-powershell/issues/2175#issuecomment-549606784

**Comment by TylerLeonhardt** [comment]
Yeah I can't see where the difference is. Stable it shows up, Preview it doesn't. Even though PSES hits the code path the same way.

**Comment by corbob** [comment]
FWIW: I'm getting the indicator when I run commands at the PSIC... just not if I run the commands from the editor window.

Easy demo:

in a ps1 file:

```powershell
Start-Sleep -Seconds 15
```

Run with either F5 or F8

Copy the command and run it directly in PSIC.

**Comment by rjmholt** [comment]
Ah interesting. That's helpful. Thanks @corbob!

**Comment by TylerLeonhardt** [comment]
I wonder if this is because we have to cancel the PSRL prompt in the F8 example and so the notification is getting fired but since there's a second executionStatus event that gets fired (where the state is Cancelled I think) theres a bit of a race condition.

**Comment by TylerLeonhardt** [comment]
PR out for this
