### ISSUE TITLE
Pipeline-ify release process

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#2286]
Super-issue for https://github.com/PowerShell/vscode-powershell/issues/1921.

Supercedes https://github.com/PowerShell/vscode-powershell/issues/1425.

Pipeline should have steps:

- **Manual step**: do changelog generation and ensure versions are correct
- **Manual step(?)**: Optionally create and push release branches
- Build PSES
- Build vscode-PS with PSES_BRANCH set
- Run tests on VSIX and PSES.zip
  - Validate certs
  - Validate structure
  - Run all tests on artefact
- **Manual step**: validate VSIX and authorise release
- Publish GitHub release
- Publish VSIX to marketplace
- Publish PSES to NuGet gallery
- Update ADS
- Open PRs to increment versions in source of PSES and vscode-PS

**Comment by andschwa** [comment]
We did it!!!
