### ISSUE TITLE
Different Preview Behavior for debugging

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2289]
Issue Description
=====

I am experiencing a problem with... debugging. I set a breakpoint as I would normally do. The code stops. 

![image](https://user-images.githubusercontent.com/15063294/68312475-6614b300-00b3-11ea-9494-8fc1c0e61179.png)

I see what I want to see - I press SHIFT+F5 to stop PowerShell and fix the issues. 

In production the code is stopped, and nothing more is happening. In Preview the data that is currently in place seems to flow to terminal. 

Normally you should be able to reproduce it with something similar to:

```powershell
for ($i = 0; $i -lt 10; $i++) {
    'test'
}
```
After it hits breakpoint, when you do Shift + F5 it will throw everything else into the  

![image](https://user-images.githubusercontent.com/15063294/68313236-898c2d80-00b4-11ea-96e0-68a14754075e.png)

But while working on this easy to use example I seem to hit #2175 issue all the time. After I run the code, nothing happens (F5 stops working). And after I restart PowerShell

![image](https://user-images.githubusercontent.com/15063294/68313540-09b29300-00b5-11ea-969b-62b223b6b698.png)

And can't run any code either. I have to close VSCode to be able to work again.. however finally I was able to run different code, and again try to build a working example:

```powershell
$Testor = for ($i = 0; $i -lt 10; $i++) {
    $Tes2 = for ($i = 0; $i -lt 10; $i++) {
        'test'
    }
    $Tes2
    'test'

}
$Testor
```
![image](https://user-images.githubusercontent.com/15063294/68313920-aa08b780-00b5-11ea-9aec-475f249bf23e.png)

It will display all tests from Tes2. 

But I can pretty much catch #2175 90% of the time using:
```
for ($i = 0; $i -lt 10; $i++) {
    'test'
}
```

Sorry for mixing up two problems, but it just came while I was trying to reproduce so maybe related. 

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.39.2|
| PowerShell Extension Version | 2019.11.1 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.17763.771|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17763.771|
|BuildVersion|10.0.17763.771|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|gitlens|eamodio|10.1.2|
|material-icon-theme|PKief|3.9.1|
|open-in-browser|techer|2.0.0|
|powershell-preview|ms-vscode|2019.11.1|
|theme-monokai-pro-vscode|monokai|1.1.14|
|vscode-tldr|bmuskalla|1.0.0|
|vscode-wakatime|WakaTime|2.2.1|

**Comment by rjmholt** [comment]
I wonder if this is a semantic issue for us. In most languages, leaving the debugger means "detach the debugger and allow the program to continue", but in PowerShell I think the norm is "end execution of the program I'm debugging". If that's the case, the solution is to get the script to terminate immediately in the detach handler.

**Comment by PrzemyslawKlys** [comment]
To be honest with the way PowerShell behaves I'm not sure leaving it as it is a good idea. Because if I want to continue I just remove breakpoints and it will continue. If I want to stop, it means STOP. 

The behavior I'm referring to is that you don't need to assign variables and it goes up. In case of my HTML module when I stop debugging I get full HTML 50 pages long thrown into a console (because it doesn't just continue to run saving to file and all) but throws everything out to console.

**Comment by rjmholt** [comment]
> Because if I want to continue I just remove breakpoints and it will continue. If I want to stop, it means STOP.

Indeed, that's what I meant above. Although other languages treat this like that, I think in our case the expectation is for script execution to stop immediately.

**Comment by TylerLeonhardt** [comment]
I think wrt other languages, a decent amount follow this model:

`launch` requests will give you the ability to STOP the code that's running (spin down a web server, stop a script from continuing, etc) where `attach` requests typically just detach from the attached process but leave it running.

**Comment by rjmholt** [comment]
> launch requests will give you the ability to STOP the code that's running (spin down a web server, stop a script from continuing, etc) where attach requests typically just detach from the attached process but leave it running.

That makes sense to me

**Comment by andschwa** [comment]
Ok @PrzemyslawKlys I'm assuming this one was closed as irrelevant today lol

**Comment by PrzemyslawKlys** [comment]
Yes, it no longer acts like that. So I closed it.
