### ISSUE TITLE
Where-Object does not seem to highlight properly

### ISSUE THREAD

**Issue by dotps1** [PowerShell/vscode-powershell#23]
when using code this like this
```PowerShell
Get-Process | Where-Object -FilterScript {
    # do things
}
```
the Where-Object does not highlight properly.  the 'Where' goes purple and the '-Object' goes white (default theme).
![image](https://cloud.githubusercontent.com/assets/1016996/11347152/2ea2fc98-91ee-11e5-8b94-e012160d4a27.png)

not a huge deal, just an FYI.  Thanks!

**Comment by dotps1** [comment]
lol, after posting that, I see GitHub does not work correctly either.

**Comment by daviwil** [comment]
That's because we all use the same syntax definition from Sublime Text :)

https://github.com/SublimeText/PowerShell/blob/master/Support/PowershellSyntax.tmLanguage

**Comment by dotps1** [comment]
Should I submit a bug there?

**Comment by daviwil** [comment]
Yeah, that would be a good place to track it.

**Comment by dotps1** [comment]
great!  thanks, ill close this!
