### ISSUE TITLE
Automatically add required .vscode assets

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#230]
I was playing around with ASP.NET Core today in VSCode and noticed the following.  First I scaffolded a webapi project just `yo aspnet`.  It created no VSCode artifacts.  When I loaded this folder into VSCode it popped two messages.  It wanted to do a `dotnet restore` and it told me my project was missing `assets`.  I clicked yes to add the missing assets and noticed that the .vscode dir appeared.  Now I can run my webapi project under the debugger. This is pretty cool. I'd like to figure out how they did that and see if we could do the same for folders containing PowerShell script.

**Comment by daviwil** [comment]
I noticed that recently using the OmniSharp extension too.  Agreed, that would be nice to have.  I think it should be fairly easy to add logic for.  At the very least it'd be nice to have a launch.json file.  Anything else that might be nice to have?

**Comment by SydneyhSmith** [comment]
Closed by the default debugging configurations (F8 just works), let us know if there is still an open request...thanks!
