### ISSUE TITLE
integrated console introduced Â 

### ISSUE THREAD

**Issue by smartpcr** [PowerShell/vscode-powershell#2305]
### System Details

Here is what I got (with both powershell extension and preview): 
```
ifÂ ($certSecretExistÂ -eqÂ $true)Â 
```
It's working on linux/mac.

System Details Output
```

```

### Issue Description

I am experiencing a problem with...

#### Expected Behaviour

-- Description of what *should* be happening --

#### Actual Behaviour

-- Description of what actually happens --

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by rjmholt** [comment]
HI @smartpcr can you include the information asked for in the issue template about your operating system and PowerShell version?

Could you describe how this is being run in the integrated console? Are you using <kbd>F5</kbd> or <kbd>F8</kbd> or are you running the script directly in the terminal (like `./script.ps1`)? Are you using Windows PowerShell? Is this script a file you're editing in VSCode? If so, what's the encoding of the file? I assume it's UTF-8.

Without knowing any of the above, I can't say for sure, but I suspect this is an encoding issue. Your script is encoded in UTF-8 and Windows PowerShell reads it as latin-1. You should instead configure VSCode's file encoding to use UTF-8 with BOM in VSCode. Please see [this document we wrote about this](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/understanding-file-encoding?view=powershell-6) for more information.

**Comment by jhoneill** [comment]
Not sure if its the same problem. but in the last few days I have started getting @ prepended to command lines in the integrated console (not the differentiated one*).
It seems to happen on the next line after I run some code from the editor window with [f8] or right_click / run_selection. and if I am executing lines via the debugger. it **may** be new with this weeks vs code build. 

*Sorry. Don't throw small stones**.
** Really sorry.

**Comment by TylerLeonhardt** [comment]
> Not sure if its the same problem. but in the last few days I have started getting @ prepended to command lines in the integrated console (not the differentiated one*).

This is already fixed and will be in the next version of the extension.

**Comment by jhoneill** [comment]
@TylerLeonhardt  excellent. As a friend of mine would say "loving your work".
