### ISSUE TITLE
In VS Code 1.4.0, IntelliSense has stopped working

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#231]
Something about VS Code 1.4.0 has caused PowerShell IntelliSense to stop working.  Must be an API change of some sort, will investigate.

**Comment by daviwil** [comment]
Details from @tonidy:


I experienced this issue with the following environment:
* VS Code 1.4.0
* VS Code PS 0.6.1

![image](https://cloud.githubusercontent.com/assets/823034/17454860/0dc1752a-5bd0-11e6-9c59-ca2336150b86.png)


With VS Code 1.3.1 the intelliSence works well. Here my log https://gist.github.com/tonidy/ed0e9a056a24ebf2a9fc02372ce2a6fe

**Comment by pcgeek86** [comment]
I'm having this problem in version 1.4.0 on Windows 10 RTM Anniversary Update.

![image](https://cloud.githubusercontent.com/assets/466713/17493414/777dc2d6-5d6d-11e6-932f-e0073e10f71b.png)

**Comment by dotps1** [comment]
I have had this for a while, I thought it was something I broke!  lol.

I am using the insider preview
![image](https://cloud.githubusercontent.com/assets/1016996/17493681/6c5f3b0c-5d7f-11e6-8fea-82335aca26dd.png)

**Comment by daviwil** [comment]
I'm also seeing the problem in 1.4.0, looks like something changed in VS Code's completion engine. PS Editor Services is getting a completion request and returning the correct results, they're just not being displayed.  Investigating...

**Comment by FooBartn** [comment]
Not sure if it helps at all, but the completions are working for actual parameter options. I.E.

New-Item -ItemT  <--- Nada
New-Item -ItemType F <-- I get the menu, with File at the top of the options.

Like so:
![autocomplete](https://cloud.githubusercontent.com/assets/8498617/17521338/8edcfec8-5e18-11e6-9651-4c344c98bc84.png)

**Comment by daviwil** [comment]
IntelliSense behavior has indeed changed in VS Code 1.4.0 but it should be something easy to fix on my side, will give it a shot today.

**Comment by gerane** [comment]
@FooBartn the F for File is not a recommendation from PSES. It is completing based on it being used before.

**Comment by gerane** [comment]
You can tell by the ABC logo next to the name

**Comment by BornToBeRoot** [comment]
Same problem after the latest vscode update. 

![image](https://cloud.githubusercontent.com/assets/16019165/17621119/977c4612-6091-11e6-8775-19e873a5426e.png)

Hope you can fix it soon.

BTW: Great Job with this Extension. :+1:

**Comment by richardhenke** [comment]
I'm having an issue with my  IntelliSense is giving me problems as well.
Here's my version:
![image](https://cloud.githubusercontent.com/assets/9287136/17629435/9294caee-6077-11e6-952b-d5f6b6ee4a6d.png)

Whenever I hover over anything I just get "Loading...". I'm also not able to use the ctrl+D command for multiple cursors and when I try to refactor a variable in a file by pressing "F2" on it it just keeps searching and never finds anything.

I've tried closing down all instances of vs code, rebooting my computer and I'm not sure what else to do. How can I downgrade my version back to a working point?

**Comment by daviwil** [comment]
New extension release is up with a fix for this!

**Comment by tonidy** [comment]
@daviwil I have tried it and it working now. Awesome :+1:
