### ISSUE TITLE
[Preview] Performance Optimization: ScriptAnalyzer Typing Delay?

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#2320]
@TylerLeonhardt noticed this when my computer was running particularly slow and working in a powershell class.

It looked like it was evaluating scriptanalyzer on every single keystroke. To improve performance maybe add a 300ms delay by default, with the delay configurable in the settings?
![AnalyzerDelay](https://user-images.githubusercontent.com/15258962/69366139-86637680-0c4a-11ea-9b27-e9b20718a07a.gif)

**Comment by SydneyhSmith** [comment]
@JustinGrote thanks for opening this issue, we already have a delay in place but it seems like our cancellation logic might not behaving properly--thanks!

**Comment by TylerLeonhardt** [comment]
@JustinGrote how big is your file/workspace? I'm having a hard time reproing this.

**Comment by JustinGrote** [comment]
@TylerLeonhardt for this item it was not very big. I tried reproducing today and doesn't seem to be doing it, I'm running the VSIX that fixed the deadlocks so it may have been related.

Closing for now until I consistently repro it on master.

**Comment by TylerLeonhardt** [comment]
Sounds good. Feel free to reach out if you see it again.
