### ISSUE TITLE
[Preview] Powershell.OpenLogFolder command missing when trying to use "Open Extensions Log Folder" Palette Command

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#2321]
@TylerLeonhardt 
![image](https://user-images.githubusercontent.com/15258962/69442206-ffbda080-0d00-11ea-9096-f04ac7c1271c.png)

![image](https://user-images.githubusercontent.com/15258962/69442142-e3216880-0d00-11ea-8ff7-03f4c91e72d8.png)

**Comment by SydneyhSmith** [comment]
@JustinGrote thanks for opening this issue, I cant seem to reproduce this issue, how often are you hitting it?

**Comment by JustinGrote** [comment]
@SydneyhSmith I can no longer repro it, but it was when I was on a build VSIX, so I'll close for now unless I can consistently reproduce on master.
