### ISSUE TITLE
Get-WmiObject is not recognized

### ISSUE THREAD

**Issue by NikhilRajNR** [PowerShell/vscode-powershell#2333]
```
Get-Wmiobject : The term 'Get-Wmiobject' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-Wmiobject
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-Wmiobject:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by TylerLeonhardt** [comment]
@NikhilRajNR what version of PowerShell are you running in?

`$PSVersionTable`

If it's PowerShell 6+, WMI cmdlets don't work and the recommendation is to use the CIM cmdlets which can basically do the same thing.

**Comment by rjmholt** [comment]
If you're running on Windows, you have started in PowerShell 6+ when intending to start Windows PowerShell.

Click on the version indicator on the bottom right to select the PowerShell you wish to run.

**Comment by NikhilRajNR** [comment]
Yup, I was using PowerShell 6 . I changed it to 5.1 working fine.
Thanks, for sharing your knowledge.
