### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Tjindarr** [PowerShell/vscode-powershell#2343]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2019.11.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.40.2`

```json 
{
	"messages": [
		{
			"type": 1,
			"message": "Command `workbench.action.debug.start` appears multiple times in the `commands` section.",
			"extensionId": {
				"value": "ms-vscode.powershell",
				"_lower": "ms-vscode.powershell"
			},
			"extensionPointId": "commands"
		}
	],
	"activationTimes": {
		"codeLoadingTime": 205,
		"activateCallTime": 12,
		"activateResolvedTime": 2,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-vscode.powershell",
				"_lower": "ms-vscode.powershell"
			},
			"activationEvent": "onLanguage:powershell"
		}
	},
	"runtimeErrors": []
}
```

**Comment by rjmholt** [comment]
Hi @Tjindarr, can you describe the issue you're seeing (with the expected behaviour and actual behaviour) and update the title please?

**Comment by cavo789** [comment]
Hi!

I was trying to speed up the loading of VSCode and, for this, I'm reading that URL: https://github.com/Microsoft/vscode/wiki/Performance-Issues

It's said to start "Developer: Show Running Extensions" to get an idea on which vscode extension is taking a lot of time.

And there I can see this warning:

![2020-05-26_16h20_40](https://user-images.githubusercontent.com/355999/82912046-e249e780-9f6c-11ea-920a-44398a763422.png)

Googling that message, I see this closed issue... So, if this can help; the message is displayed by vscode and it seems that there is some place for improvement if I correctly understand the "appears multiple times" warning.

**Comment by SydneyhSmith** [comment]
@cavo789 thanks for bringing that to our attention
