### ISSUE TITLE
Repeat last command in Terminal in debug (PowerShell)

### ISSUE THREAD

**Issue by KollSimonds** [PowerShell/vscode-powershell#2344]
Like the PowershellIDE, there _must_ be a facility to repeat the last command from the debug terminal?

Arrow-up does nothing, same for PgUp.  I've hit almost every key on the keyboard thinking maybe you have mapped a better 

If this isn't a bug, but a feature request, let me know where the best place to request that.

Thank you!

**Comment by KollSimonds** [comment]
Looks like <CTRL> F7 does this.  However, it appears to just do the last one.  Why not copy the PSIDE's behavior and cycle through the MRUs?  Doesn't look like the arrow keys are being pressed into service for any other need.

**Comment by TylerLeonhardt** [comment]
Can you give this a go in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension? Arrow up should cycle through the commands while debugging.

**Comment by KollSimonds** [comment]
Looking good!  Working right out of the box.

VSCode is awesome, thanks Tyler
