### ISSUE TITLE
Allow extending PSModulePath in settings.json

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/vscode-powershell#2356]
**Summary of the new feature**

Right now, PowerShell has very limited capabilities for IntelliSense due to how dynamic the language is and some specific bugs with its implementation.  The only pattern that seems to work is to create a custom modules folder in the workspace, update PSModulePath to include the custom modules folder, then reference the modules in code by name (instead of path).  This works around the language limitations, but requires running initialization scripts in the session or modifying global environment variables to work.  Users should be able to update PSModulePath in their vscode settings.json so they can define classes/functions that are discovered by IntelliSense without confusing manual tasks (initializing VS Code's session) or modifying their global environment for a single workspace (setting environment variables).

**Proposed technical implementation details (optional)**

Add a field `"powershell.psModulePath"` to settings.json that takes an array of string paths and prepends them to the `PSModulePath` environment variable prior to loading intellisense.

**Comment by rkeithhill** [comment]
I think a more generic solution would be to support workspace specific initialization/profile scripts.  This would let you set up $env:PSModulePath among other things.

**Comment by SydneyhSmith** [comment]
@chriskuech thanks for opening this issue, looks like we are already tracking this request with #880
Agree with @rkeithhill that a generic approach is likely the best option--we are tracking that particular request with #190 so I will mark this as duplicate.
