### ISSUE TITLE
Timed out waiting for the PowerShell extension to start when Start debugging before extension starts

### ISSUE THREAD

**Issue by gbuktenica** [PowerShell/vscode-powershell#2358]
### System Details

- Operating System
   Windows 10
- VS Code version
   1.40.2
- PowerShell extension version
  2019.11.0
- Output from `$PSVersionTable`
  7.0.0-preview.6
  5.1.18362.145
### Issue Description
I am experiencing a problem with running a PowerShell debug configuration.
"PowerShell: Launch a Script"
If I do not open a ps1 file first the debugger will time out waiting for PowerShell to start.
Error: Timed out waiting for the PowerShell extension to start.

#### Repro Instructions
Open VSCode
Open a **Folder** with a launch.json and a PowerShell Script
Note: **DO NOT open any POWERSHELL scripts**
Open the debugger Control + Shift + D
Launch a configuration PowerShell Launch a script.

#### Expected Behaviour
The Launch should Run

#### Actual Behaviour
Error: Timed out waiting for the PowerShell extension to start.

#### Work around
Open a PowerShell script in the editor
Extension starts PowerShell
Run the debug configuration.
It will now work.

**Comment by gbuktenica** [comment]
### VSCode extensions:
bencoleman.armview@0.3.3
bierner.markdown-mermaid@1.4.1
bpruitt-goddard.mermaid-markdown-syntax-highlighting@1.0.1
brunnerh.insert-unicode@0.7.1
christian-kohler.npm-intellisense@1.3.0
CoenraadS.bracket-pair-colorizer-2@0.0.29
Compulim.indent4to2@0.1.2
DavidAnson.vscode-markdownlint@0.32.0
dbaeumer.vscode-eslint@1.9.1
donjayamanne.githistory@0.4.11
DotJoshJohnson.xml@2.5.0
dracula-theme.theme-dracula@2.19.0
eamodio.gitlens@10.2.0
eamodio.tsl-problem-matcher@0.1.0
eg2.vscode-npm-script@0.3.9
fabianlauer.vs-code-xml-format@0.1.5
faustinoaq.javac-linter@1.3.1
fcrespo82.markdown-table-formatter@2.0.2
GlenBuktenica.unicode-substitutions@2.2.5
humao.rest-client@0.23.0
mechatroner.rainbow-csv@1.3.1
mhutchie.git-graph@1.19.1
mohsen1.prettify-json@0.0.3
ms-mssql.mssql@1.7.1
ms-python.python@2019.11.50794
ms-vscode-remote.remote-wsl@0.40.3
ms-vscode.azure-account@0.8.7
ms-vscode.csharp@1.21.8
ms-vscode.powershell@2019.11.0
ms-vscode.vscode-typescript-tslint-plugin@1.2.3
ms-vsts.team@1.161.0
msjsdiag.debugger-for-chrome@4.12.3
piotrpalarz.vscode-gitignore-generator@1.0.1
Shan.code-settings-sync@3.4.3
sidneys1.gitconfig@2.0.1
slevesque.vscode-autohotkey@0.2.2
sohamkamani.code-eol@0.3.3
streetsidesoftware.code-spell-checker@1.7.20
vstirbu.vscode-mermaid-preview@1.4.0
waderyan.gitblame@3.0.1
zeithaste.cursorCharCode@0.1.1


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by gbuktenica** [comment]
$psEditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1       13      1       0

**Comment by gbuktenica** [comment]
vscode-powershell.log
11/12/2019 1:26:18 pm [NORMAL] - powershell.exe terminated or terminal UI was closed

**Comment by SydneyhSmith** [comment]
@gbuktenica thanks for opening this issue, we recently published an update to our [Preview extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) that may solve this issue, please let us know if you are able to try it out..thanks!

**Comment by gbuktenica** [comment]
Hi @SydneyhSmith I have just tried with the Preview Extension and I get the same behaviour.
I see you have tagged this issue with "Needs-Repro-Info".  What more information is required?

**Comment by SydneyhSmith** [comment]
@gbuktenica thanks for opening providing the steps, I am able to reproduce this...we are still investigating how to best resolve this issue--thanks!

**Comment by virovets64** [comment]
I have the same problem with v2020.4.0

**Comment by gbuktenica** [comment]
@virovets64 yes I still have the problem with
* Operating System
    Windows 10

* VS Code version
    1.44.2

* PowerShell extension version
    2020.4.0

* Output from $PSVersionTable

PSVersion                      7.0.0
PSEdition                      Core

**Comment by TylerLeonhardt** [comment]
I have a partial fix to this... pressing play with start the extension now, but it'll say you need to wait for it to finish starting.

At least it's two clicks of the same button, rather than opening a PS file.
