### ISSUE TITLE
PowerShell Find?Install modules from PSGallery advertises kbd shortcut that doesn't work

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#236]
The command says the keyboard shortcut is `Ctrl+K Ctrl+F` but when I use that shortcut VSCode tells me that the key combination is not a command.

**Comment by daviwil** [comment]
The key combo just worked for me, it just took about 8 seconds for the list to finally show up.  After I hit the key combo I saw "Initializing..." in the status bar.  Strange that you're not seeing it...  How far into your session are you before you hit the combo?  Just wondering if maybe PSES isn't fully initialized at that point.

**Comment by rkeithhill** [comment]
I don't think it is a timing thing as I opened up VSCode and it opened my last PowerShell project.  I pressed the key combo within a few seconds and it worked.  I *can* repro this behavior if I end the language server host process.  So this is not a bug related to this functionality.  At the time I submitted this, my language server host process must have died.
