### ISSUE TITLE
PowerShell Find/Install module from PSGallery takes long time to show list

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#237]
I think it might be better to show a "search" text box immediately while still waiting for results of a list of everything.  If I start to type in a search term, the code should wait for a pause (say 1 sec) and then search PSGallery with what is typed in so far.  Of course a change in typing, should spawn off a new find-module command and update the results list accordingly.

**Comment by daviwil** [comment]
Yep, agreed.

**Comment by SydneyhSmith** [comment]
Going to close this issue as we are improving the speed Find/Install from the PowerShellGet side
