### ISSUE TITLE
CodeLens References link only jumps to definition

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/vscode-powershell#2374]
### System Details

System Details Output
```powershell
### VSCode version: 1.42.0-insider 26f5dfcd76c9a02f116a706844611aeb09ae8c0b x64

### VSCode extensions:
alexcvzz.vscode-sqlite@0.8.1
christian-kohler.path-intellisense@1.4.2
CoenraadS.bracket-pair-colorizer-2@0.0.29
DavidAnson.vscode-markdownlint@0.33.0
DotJoshJohnson.xml@2.5.0
eamodio.gitlens@10.2.0
mechatroner.rainbow-csv@1.3.1
ms-python.python@2019.11.50794
ms-vscode.powershell-preview@2019.12.1-CI.41180
streetsidesoftware.code-spell-checker@1.7.20
vscode-icons-team.vscode-icons@9.6.0

### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

CodeLens References link is shown but does not respond to mouse clicks:

![references](https://user-images.githubusercontent.com/16168755/71093109-d3366080-21a8-11ea-91e7-e9f123b1e075.gif)

#### Expected Behaviour

When clicking on references link the overlay window with references should be shown

#### Actual Behaviour

When clicking on references link nothing happens.

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

[1576678486-6dd3db75-6cd7-4cba-9919-dbb47d81c4031576678485019.zip](https://github.com/PowerShell/vscode-powershell/files/3978773/1576678486-6dd3db75-6cd7-4cba-9919-dbb47d81c4031576678485019.zip)

**Comment by SydneyhSmith** [comment]
@kborowinski thanks for opening this issue and providing detailed information! I am having some trouble reproducing this behavior...do you have any PowerShell specific settings enabled?

**Comment by mrboring** [comment]
I'm having the same issue.

```
### VSCode version: 1.41.0 9579eda04fdb3a9bba2750f15193e5fafe16b959 x64

### VSCode extensions:
alefragnani.Bookmarks@10.6.0
eamodio.gitlens@10.2.0
Ionide.Ionide-FAKE@1.2.3
Ionide.Ionide-fsharp@4.4.1
Ionide.Ionide-Paket@1.12.0
ms-vscode.csharp@1.21.9
ms-vscode.powershell@2019.12.0        
ms-vscode.powershell-preview@2019.12.0
streetsidesoftware.code-spell-checker@1.7.20


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Experimental Settings:

Name                                                       Enabled
----                                                       -------
PSCommandNotFoundSuggestion                                   True
PSImplicitRemotingBatching                                    True
PSNullConditionalOperators                                    True
Microsoft.PowerShell.Utility.PSGetError                       True
Microsoft.PowerShell.Utility.PSManageBreakpointsInRunspace    True
PSDesiredStateConfiguration.InvokeDscResource                 True

### $Profile.CurrentUserAllHosts:
# https://github.com/dahlbyk/posh-git
Import-Module posh-git

# If you would like to make your prompt span two lines, with a
# newline after the Git status summary, use this setting:
$GitPromptSettings.DefaultPromptBeforeSuffix.Text = '`n'

#Add-WindowsPSModulePath
$env:PSModulePath = $env:PSModulePath + ';C:\Data\PowerShell\Modules'

Set-Alias -Name 'ge' -Value 'Get-Error'

Import-Module HelperFunctions
```

I've attached my `settings.json` file.
[settings.zip](https://github.com/PowerShell/vscode-powershell/files/3980383/settings.zip)

**Comment by kborowinski** [comment]
@SydneyhSmith : Yep, a bunch actually:
```json
	"powershell.powerShellAdditionalExePaths": [
		{
			"exePath": "C:\\Program Files\\PowerShell\\Nightly\\pwsh.exe",
			"versionName": "PowerShell Core Nightly (x64)"
		}
	],
	"powershell.developer.featureFlags": [
		"PSReadLine"
	],
	"powershell.scriptAnalysis.enable": true,
	"powershell.codeFormatting.preset": "OTBS",
	"powershell.integratedConsole.focusConsoleOnExecute": false,
	"powershell.integratedConsole.showOnStartup": false,
	"powershell.sideBar.CommandExplorerVisibility": false,
	"powershell.promptToUpdatePowerShell": false
```

**Comment by kborowinski** [comment]
I did some digging right now and found that not only the *references* link does not work but shows wrong number of references. In fact I went through my code to find that it always shows **2** references **regardless** of factual reference number. Have a look:

![references](https://user-images.githubusercontent.com/16168755/71166528-3ed50800-2253-11ea-8517-c19301ecd18b.gif)

**Comment by mrboring** [comment]
As per @kborowinski, I get both issues:

1. Clicking on references flashes function name, but does not bring up a list of references.
2. Functions show `2 References`.

Here are my steps to reproduce the issues:

1. 	Started  Windows Sandbox
2. 	Installed PowerShell-7.0.0-rc.1-win-x64.msi
3. 	Installed VSCodeUserSetup-x64-1.41.0
4. 	Installed PowerShell Preview 2019.12.0 extension
5. 	Add the following to settings.json
```	   
           "powershell.developer.featureFlags": [
	       "PSReadLine"
	   ],
	   "editor.fontSize": 11,
	   "terminal.integrated.fontSize": 11
```
6. 	Closed VS Code
7. 	Unzipped test project ([CodeLens-Issue.zip](https://github.com/PowerShell/vscode-powershell/files/3983566/CodeLens-Issue.zip)) to a folder on the desktop
8. 	Right clicked on folder and selected `Open with Code`

There are two functions in the test project. Neither has a reference to it. However, for both, I get the following after doing `Find All References` (Shift+Alt+F12):

![image](https://user-images.githubusercontent.com/5991977/71173665-37b1f800-225b-11ea-9ea9-6282f8440092.png)

**Comment by SydneyhSmith** [comment]
@kborowinski @mrboring thanks for all the additional information and re-pro steps! We are still investigating this issue and will follow up with any other questions!

**Comment by TylerLeonhardt** [comment]
Can you both please provide the [language server logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs)?

**Comment by kborowinski** [comment]
@TylerLeonhardt : Here you go: [plsp.txt](https://github.com/PowerShell/vscode-powershell/files/3986754/plsp.txt)

**Comment by mrboring** [comment]
@TylerLeonhardt As requested: [PES Output.txt](https://github.com/PowerShell/vscode-powershell/files/3987320/PES.Output.txt)

**Comment by PrzemyslawKlys** [comment]
Same issue on my end: https://github.com/PowerShell/vscode-powershell/issues/2388

**Comment by TylerLeonhardt** [comment]
Yep saw this on Twitter as well. It's fixed in the PR above ^

Silly boolean logic - I had it backwards!
