### ISSUE TITLE
Syntax highlight doesn't recognize '#text' property 

### ISSUE THREAD

**Issue by stej** [PowerShell/vscode-powershell#238]
I have this code:

```
Get-SomeXml | 
Select-Object -ExpandProperty Node |
        % { if ($_.'#text') { $_.'#text'.Trim() -split ',\s*' }
            else            { @() }
        }
```

The syntax highlighter is confused from the ending apostrophe behind the ```#text``` property. 

![image](https://cloud.githubusercontent.com/assets/253560/17693228/183d8aea-639e-11e6-9d4e-078560d0aa31.png)

The problem is probably caused by the hash sigh ```#```, because once I remove it, it is ok.

_Workaround_
```
$textProp = '#text' # just workaround because of syntax highlighter

Get-SomeXml | 
Select-Object -ExpandProperty Node |
        % { if ($_.$textProp) { $_.$textProp.Trim() -split ',\s*' }
            else            { @() }
        }
```

**Comment by daviwil** [comment]
Hi @stej, I apologize for the long delay in replying to this.  We're tracking all of our syntax highlighting issues over at the [PowerShell/EditorSyntax](https://github.com/PowerShell/EditorSyntax) repo now.  I've moved your issue there to be addressed.  Thanks!
