### ISSUE TITLE
[Preview] powerShellDefaultVersion workspace setting doesn't work for autodiscovered paths

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#2380]
@TylerLeonhardt, likely related to @rjmholt's detection logic.

Issue Description
=====
Workspace Settings does not work for powershellDefaultVersion for the autodiscovered powershell paths. It triggers but does not switch correctly. This is probably due to something in the new discovery code. User Settings works fine.

![Capture](https://user-images.githubusercontent.com/15258962/71196373-ca936800-2244-11ea-9ca0-aec7843a3ced.gif)

Interestingly, the "setting" in vscode still knows it as x86, even though it loads x64, so it's not a settings loading issue.

Probably related, it appears to only happen with "built-in" shells. Using AdditionalExePath entries works fine.

![Capture](https://user-images.githubusercontent.com/15258962/71197307-2e6a6080-2246-11ea-91af-48972562f334.gif)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.42.0-insider|
| PowerShell Extension Version | 2019.12.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.0-preview.6|
|PSEdition|Core|
|GitCommitId|7.0.0-preview.6|
|OS|Microsoft Windows 10.0.19041|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0-preview.6|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|better-align|wwm|1.1.6|
|better-comments|aaron-bond|2.0.5|
|better-powershell-syntax-highlighting|justin-grote|0.0.2|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|code-settings-sync|Shan|3.4.3|
|gc-excelviewer|GrapeCity|2.1.32|
|gistfs|vsls-contrib|0.0.22|
|git-graph|mhutchie|1.19.1|
|gitlens|eamodio|10.2.0|
|indent-rainbow|oderwat|7.4.0|
|markdown-all-in-one|yzhang|2.6.1|
|powershell-preview|ms-vscode|2019.12.0|
|remote-containers|ms-vscode-remote|0.96.0|
|remote-ssh-edit-nightly|ms-vscode-remote|2019.12.24000|
|remote-ssh-nightly|ms-vscode-remote|2019.12.24000|
|remote-wsl|ms-vscode-remote|0.41.6|
|todo-tree|Gruntfuggly|0.0.162|
|vscode-icons|vscode-icons-team|9.6.0|
|vscode-peacock|johnpapa|3.2.0|
|vscode-sort-json|richie5um2|1.18.0|
|vscode-zipexplorer|slevesque|0.3.1|

**Comment by TylerLeonhardt** [comment]
Yes I think @rjmholt made this discovery earlier this week. Thanks for capturing it in an issue. It seems to be an issue with how we find the 32bit version of PowerShell. It's easy to get wrong as the paths are totally different if you open VS Code 64 bit vs VS Code 32bit.

**Comment by rjmholt** [comment]
I think this is actual a case-sensitivity issue; try changing `Windows Powershell (x86)` to `Windows PowerShell (x86)`. When the given configuration doesn't match anything, it defaults to the first PowerShell it finds.

**Comment by JustinGrote** [comment]
@rjmholt I wouldn't be surprised, half the reason I use Powershell is I suck at aligning cases :) I'll try to repro but I agree it should be case insensitive, since they are descriptors and not hard paths that might have issue cross platform e.g. on linux.
