### ISSUE TITLE
Interacting With Integrated Terminal Causes VSCode to Stop Working

### ISSUE THREAD

**Issue by RatliffCam** [PowerShell/vscode-powershell#2389]
Issue Type: <b>Bug</b>

Whenever I launch VScode, it works as expected. As soon as I even click on the integrated terminal, I can no longer:
1. Open a new file in the editor
2. Created a new file in the explorer panel
3. Rename a file from the explorer panel
4. Create a new folder from the explorer panel
5. Save any changes to settings, though I can make the changes, they just don't save.
6. Close VScode out, I have to kill it from task manager
7. Run any command from the command pallet
8. Interact with source control providers
9. Interact with extensions
I'm sure there's more, this is just what i've noticed the most. It seems like most of vscode just stops responding or gets stuck in an infinite loop or something.

Whenever this problem happens, a loading bar will start dragging across whatever part of VSCode I just invoked. For example, if I try to open a new file in the editor, a new tab with the file's name will be created but the editor will be completely blank and the blue bar will be dragging across the editor. The same happens for the issues described with the panels, etc as well.

I've narrowed it down to the powershell extension, all other extensions are disabled.

Extension version: 2019.12.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|6.00GB (0.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details>

**Comment by RatliffCam** [comment]
I can provide screenshots and videos if needed because it's a really weird issue to explain. Really my only work around for now is to just completely avoid using the integrated console which is.... Unfortunate.

**Comment by tlisiecki** [comment]
Interesting, I seem to be facing a very similar problem. Since the update to the 2019.12.0 I find the extension completely unusable and it locks the VSCode UI completely until the timeout on waiting for the language service occurs.

In the logs I can only see the following:
```
12/27/2019 9:13:12 AM [NORMAL] - Language server starting --
12/27/2019 9:13:12 AM [NORMAL] -     exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
12/27/2019 9:13:12 AM [NORMAL] -     args: Import-Module 'c:\Users\***t\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2019.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\***\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\modules' -EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'c:\Users\***\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\logs\1577434392-2e98066b-8106-4f84-9004-0c53647184e01577434373401\EditorServices.log' -SessionDetailsPath 'c:\Users\***\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\sessions\PSES-VSCode-16392-752007' -FeatureFlags @() 
12/27/2019 9:15:12 AM [NORMAL] - Language server startup failed.
12/27/2019 9:15:12 AM [ERROR] - The language service could not be started: 
12/27/2019 9:15:12 AM [ERROR] - Timed out waiting for session file to appear.
12/27/2019 9:15:32 AM [NORMAL] - powershell.exe started, pid: 2724
```

The session file entry in the log is unclear - the file PSES-VSCode-16392-752007 does get created and is readable.
The content is:

```
"{"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_khdgvval.kg4","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_gzraipt4.uuz"}"
```

So the question is what is actually not readable? Maybe the pipes? Could there be something specific on my system that prevents the extension to create the pipes?

When the timeout occurs the vscode UI is unlocked but the extension fails to start properly :(

Previous version worked very well for me. Were there any significant changes that could have introduced such a problem?

VSCode :
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Best Regards,
Tomasz

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on? 

If you're using the PowerShell Preview extension, can you also [attach the payload logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs)?

**Comment by tlisiecki** [comment]
Hi all,

I can provide the logs, but unfortunately not the payload logs. Don`t know why, but despite using powershell-preview-2019.12.0 the parameter specified in the docs is not recognized and it also seems to do nothing as the Powershell Editor Services is not visible in the dropdown list in Output tab.

![settings](https://user-images.githubusercontent.com/11217187/71577212-8b420280-2af3-11ea-8e98-ff7b23492aac.png)

![outputTab](https://user-images.githubusercontent.com/11217187/71577487-a2cdbb00-2af4-11ea-90dd-b747dab52496.png)

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4009462/logs.zip)

**Comment by RatliffCam** [comment]
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4010275/logs.zip)
Attached are my logs as well.

**Comment by tlisiecki** [comment]
By the logs I see that we have two different cases, where the significant difference is how the Powershell Editor Services are loaded. In the preview version of the extension it is a dll binary while in stable version it is still a psm1 powershell module. @TylerLeonhardt should I open a separate issue for the preview version?

**Comment by SydneyhSmith** [comment]
@RatliffCam  @tlisiecki thanks for providing this information, no need to open another issue as this looks to be the same issue as #2377 thanks!
