### ISSUE TITLE
PowerShell Integrated Console Hangs

### ISSUE THREAD

**Issue by James-Livingston** [PowerShell/vscode-powershell#2394]
Issue Type: <b>Bug</b>

Opening any PowerShell script causing the PowerShell Integrated Console to startup.  The console never starts up it just hangs after the output "PowerShell Integrated Console."

Extension version: 2019.12.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by tlisiecki** [comment]
Hi @James-Livingston. Are you experiencing this issue in the powershell-preview version of the extension or the stable one?

**Comment by James-Livingston** [comment]
Diagnostic logs after and including the "PowerShell Integrated Console" message:
```
PowerShell Integrated Console

VERBOSE: Invoking Start-EditorServicesHost
VERBOSE: Start-EditorServicesHost returned Microsoft.PowerShell.EditorServices.Host.EditorServicesHost
VERBOSE: Writing session file with contents:
VERBOSE: {"debugServicePipeName":"\\\\.\\pipe\\PSES_1ne0t0v0.toq","status":"started","languageServiceTransport":"NamedPipe","debugServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_1akt5abr.v1k"}
VERBOSE: Wrote out session file
VERBOSE: 
#-- Waiting for EditorServicesHost to complete execution ---------------------
```

This issue is with the stable extension.  As far as I can tell... the issue is present in version 2019.9.0 and newer.  The issue is not present in 2019.5.0 and older.

**Comment by andyhoffman12** [comment]
I'm also having similar issues. very basic scripts within code, pressing f5 to debug and i essentially endup getting hung for instance: `PowerShell Integrated Console

c:\Scripts\Powershell\Install-AmazonChime.ps1

`
or the terminal dies or crashes. Basically i get one shot at running a script then must close and reopen code. I tried preview but thats all crashy.

**Comment by rjmholt** [comment]
Can you let us know whether the VSCode window (other than the terminal) responds to input like mouse clicks when you see this hang. If so, it's almost certainly #2377.

**Comment by BooTheHamster** [comment]
21.04.2020 09:11:20 [NORMAL] - Visual Studio Code v1.44.2 64-bit
21.04.2020 09:11:20 [NORMAL] - PowerShell Extension v2020.4.0
21.04.2020 09:11:20 [NORMAL] - Operating System: Windows 64-bit
21.04.2020 09:11:20 [NORMAL] - Language server starting --
21.04.2020 09:11:20 [NORMAL] -     PowerShell executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
21.04.2020 09:11:20 [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\Олег\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Олег\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\Олег\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1587445880-b9792888-1d9d-4c28-b78b-93b4a3eb59721587445878776\EditorServices.log' -SessionDetailsPath 'c:\Users\Олег\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-12936-204649' -FeatureFlags @() 
21.04.2020 09:11:20 [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\Олег\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Олег\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\Олег\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1587445880-b9792888-1d9d-4c28-b78b-93b4a3eb59721587445878776\EditorServices.log' -SessionDetailsPath 'c:\Users\Олег\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-12936-204649' -FeatureFlags @() 
21.04.2020 09:11:20 [NORMAL] - powershell.exe started.
21.04.2020 09:11:20 [NORMAL] - Waiting for session file
21.04.2020 09:11:22 [NORMAL] - Session file found
21.04.2020 09:11:22 [NORMAL] - Registering terminal close callback
21.04.2020 09:11:22 [NORMAL] - Registering terminal PID log callback
21.04.2020 09:11:22 [NORMAL] - powershell.exe PID: 12796
21.04.2020 09:11:22 [NORMAL] - Language server started.
21.04.2020 09:11:22 [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_b4nwxoaz.jv3","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_pixrovi0.ara"}
21.04.2020 09:11:22 [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_b4nwxoaz.jv3...
21.04.2020 09:11:22 [NORMAL] - Language service connected.
21.04.2020 09:11:23 [WARNING] - Invalid Version: null

**Comment by BooTheHamster** [comment]
![screenshot 1](https://user-images.githubusercontent.com/489605/79827830-6cbc8b80-83b0-11ea-8f83-9433e131a5f8.png)

**Comment by BooTheHamster** [comment]
Powershell integrated console hangs on. Running any powershell code by pressing F5 also hangs on.

**Comment by SydneyhSmith** [comment]
@BooTheHamster could you please open a new issue with all this information, it would  be really helpful if you could also attach the diagnostic logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by BooTheHamster** [comment]
Done. #2658
