### ISSUE TITLE
args not passed to script being debugged from launch.json

### ISSUE THREAD

**Issue by pkskelly** [PowerShell/vscode-powershell#24]
I have tried several combinations of "args": [] and none of them produce a $args in the debugger.  Should the "args" parameter for a configuration work?  Looking through the source but not finding anything yet.
{
	"version": "0.1.0",
	"configurations": [
		{
			"name": "PowerShell",
			"type": "PowerShell",
			"program": "PowerShell Scripts/output.ps1",
			"args": ["Verbose:$true"],
			"request": "launch"
		}
	]
}

The debugger launches fine, but attempts using "-Verbose",  "-Verbose:$true",  or "/Verbose:$true" do not get passed to $args.  The "output.ps1" file is very simple:

   Write-Output $args	 
   Get-Process
   Write-Verbose -Message "Debugging PS in VSCode!"

**Comment by daviwil** [comment]
Hi Pete,

Currently this 'args' parameter is for arguments to the launched process, they currently don't get sent along to the script that is debugged.  This is great feedback though, I'll try to make this possible in a future release.

Thanks!

**Comment by pkskelly** [comment]
Thanks @daviwil

**Comment by rkeithhill** [comment]
I have a working prototype for this.  It requires changes mostly on the PSES side but there are a few changes required to the package.json file as well.
