### ISSUE TITLE
Unable to start debugging interactive session

### ISSUE THREAD

**Issue by avezinaATastus** [PowerShell/vscode-powershell#2401]
Hi,

When launching a debug session, the powershell session crashes with this error (found it in the event viewer)
```
Error Message = The process cannot access the file 'c:\Users\avezina\.vscode\extensions\ms-vscode.powershell-preview-2019.12.0\logs\1578329950-8940193b-522e-41b2-b5f5-c1fce8b387181578329944994\StartEditorServices.log' because it is being used by another process.
Fully Qualified Error ID = System.IO.IOException,Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand
```
I tried with PS5.1 and PS7, with the Preview extension and the normal one.

**Comment by avezinaATastus** [comment]
Gonna open a new Issue correctly and from VSCode.

**Comment by rjmholt** [comment]
If you're able to provide a stack trace for this, that should be most of what we need to fix this

**Comment by avezinaATastus** [comment]
@rjmholt : I reopened the issue correctly from VSCode : #2402 

I'm not sure how to get you a strack trace, since the terminal closes so quickly, and there isn't much details in the event viewer. 

Let's continue this discussion in #2402
