### ISSUE TITLE
Custom tabexpansion tooltip shows in ISE but not VS Code

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#2405]
## ISE

![image](https://user-images.githubusercontent.com/67258/71990196-f9c44600-3200-11ea-9fb5-8029565fd603.png)

## VS Code

![image](https://user-images.githubusercontent.com/67258/71990262-11033380-3201-11ea-87e8-000fc857ee03.png)

## Script

```powershell
function MyTestCompletion {
	param($wordToComplete, $commandAst)

	$commandTree = & {
		    New-CommandTree build "Compile the current package" {
			    New-CommandTree "--quiet" "output printed to stdout"
			    New-CommandTree "--package" "Package to build (see `cargo help pkgid`)"
			    New-CommandTree "--all" "for --workspace (deprecated)"
			    New-CommandTree "-workspace" "all packages in the workspace"
			    New-CommandTree "-exclude" "Exclude packages from the build"
	    }
    }

	Get-CommandTreeCompletion $wordToComplete $commandAst $commandTree
}

Register-ArgumentCompleter -CommandName mytest -Native -ScriptBlock $function:MyTestCompletion
```

**Comment by SydneyhSmith** [comment]
@dfinke thanks for opening this issue, and providing the screenshots...it would be really helpful if you could also attach the logs so that we can see where the message is getting lost--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs)

**Comment by dfinke** [comment]
Here's the log, let me know if I need to provide other info.

[vscode.log](https://github.com/PowerShell/vscode-powershell/files/4043242/vscode.log)

**Comment by TylerLeonhardt** [comment]
I've got a fix out for this. ^

**Comment by dfinke** [comment]
What version of the ext is this expected in? Tried in the latest, doesn't seem to work.

**Comment by TylerLeonhardt** [comment]
The next version.
