### ISSUE TITLE
The 'PowerShell' extension is recommended for this file type

### ISSUE THREAD

**Issue by arcotek-ltd** [PowerShell/vscode-powershell#2406]
### System Details

System Details Output
```
### VSCode version: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64

### VSCode extensions:
ms-vscode.powershell-preview@2019.12.0


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.771
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.771
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I have just uninstalled VSCode and deleted `%AppData%\Code` and `%UserProfile%\.vscode`, before reinstalling VSCode and _only_ the PowerShell Preview extension, just to make sure there isn't any dodgy extension causing the problem(s).

#### Expected Behaviour

Nothing.

Preferably, even though I have the _Preview_ version installed, I shouldn't see this.

#### Actual Behaviour

After opening VSCode and then *opening a `.ps1` file, I get a VSCode notification in the bottom right of the screen that reads: "The 'PowerShell' extension is recommended for this file type"

`*` If a `.ps1` file was open in the last session, I get the notification on start-up.

![image](https://user-images.githubusercontent.com/26305145/72171006-e2848480-33c9-11ea-816e-af6288d2363c.png)

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by rjmholt** [comment]
This is tracked in https://github.com/microsoft/vscode/issues/80178
