### ISSUE TITLE
Language server startup failed

### ISSUE THREAD

**Issue by QuyenLy73** [PowerShell/vscode-powershell#2417]
Issue Description
=====
PS session fails to start with these errors. I have taken the cert from Start-EditorServices.ps1 and imported into my local machine's Trusted Publisher's store. I confirmed it's there with an expiration date of 5/2/2020. I have also executed this command but nothing happens.

Import-Module $HOME\.vscode\extensions\ms-vscode.powershell*\modules\PowerShellEditorServices\PowerShellEditorServices.psd1

1/14/2020 2:47:41 PM [NORMAL] - Language server startup failed.
1/14/2020 2:47:41 PM [ERROR] - The language service could not be started: 
1/14/2020 2:47:41 PM [ERROR] - Timed out waiting for session file to appear.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.16299 |
| VSCode | 1.41.1|
| PowerShell Extension Version | 2019.12.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.16299.1146|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.16299.1146|
|BuildVersion|10.0.16299.1146|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|All-Autocomplete|Atishay-Jain|0.0.23|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|powershell|ms-vscode|2019.12.0|
|python|ms-python|2020.1.58038|
|todo-tree|Gruntfuggly|0.0.162|

**Comment by rjmholt** [comment]
> 1/14/2020 2:47:41 PM [NORMAL] - Language server startup failed.
> 1/14/2020 2:47:41 PM [ERROR] - The language service could not be started:
> 1/14/2020 2:47:41 PM [ERROR] - Timed out waiting for session file to appear.

These logs just indicate that the client waited for the server to start and that it didn't. When you try to start the PowerShell extension, does anything flash in the terminal? Unfortunately, because of the way VSCode works, capturing the screen at that moment (like with a video/gif recorder) might be the only way to get any error message there.

> I have also executed this command but nothing happens.

You might also have some luck trying to execute the following from cmd:

```cmd
powershell.exe -NoProfile -NoLogo -ExecutionPolicy Bypass -Command "$PSES_BUNDLE_PATH/PowerShellEditorServices/Start-EditorServices.ps1 -BundledModulesPath $PSES_BUNDLE_PATH -LogPath $SESSION_TEMP_PATH/logs.log -SessionDetailsPath $SESSION_TEMP_PATH/session.json -FeatureFlags @() -AdditionalModules @() -HostName 'My Client' -HostProfileId 'myclient' -HostVersion 1.0.0 -LogLevel Diagnostic"
```

With the following set inline:

- `$PSES_BUNDLE_PATH`: `~\.vscode\extensions\ms-vscode.powershell-2019.12.0\modules`
- `$SESSION_TEMP_PATH`: An empty temp directory

If that works, it should print a bunch of information and then block at the point where it waits for a client to connect (you should then kill the process, since there won't be a client to connect). If it doesn't work (which is what I'm hoping, since we need to reproduce this error in an environment where we control the terminal process), then you should see the error in the CMD console.

**Comment by QuyenLy73** [comment]
The cursor just blinks like it's waiting for something?

**Comment by rjmholt** [comment]
> The cursor just blinks like it's waiting for something?

Is this in the Integrated Console after startup? It might be worth trying pressing <kbd>Enter<kbd> or entering some input there.

Also see if you're able to run the other command listed above.

**Comment by QuyenLy73** [comment]
Actually looks like I didn't wait long enough. There are now 3 files in my temp directory. logs.ext, Start-EditorServices-logs.txt, and session.json. In the Integrated Console in VSCode, the last status is
 
#-- Waiting for EditorServicesHost to complete execution ---------------------

**Comment by rjmholt** [comment]
>  In the Integrated Console in VSCode, the last status is
>
> #-- Waiting for EditorServicesHost to complete execution ---------------------

That means it should be ready to go. Do you get a prompt?

**Comment by QuyenLy73** [comment]
The PS Integrated Console does not let me type anything in there. It tries to start up with a Starting Powershell message and eventually throws an initialization error which is the Language server startup error that I posted here. I ran the command in a different Powershell terminal session within VS code. I assume this is just the PS on the OS. In this window, I get the Waiting for EditorServicesHost message but I can't type anything after that message. I'm still not able to run any of my PS scripts from within VSCode because it says Cannot Debug or Run Powershell Script until the Powershell session has started.

**Comment by rjmholt** [comment]
> There are now 3 files in my temp directory. logs.ext, Start-EditorServices-logs.txt, and session.json

Can you post those files here? (Or send them through by email: see [the troubleshooting doc](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md))

>  I assume this is just the PS on the OS

That's indeed what that is.

---

From what you've described so far, it sounds like the PowerShell process that runs the server is correctly getting to the point where it's waiting on a client connection but for some reason the client never connects properly. If the logs don't reveal anything, it might be worth trying the preview extension instead, especially since that will be stable within the month.

**Comment by QuyenLy73** [comment]
[Start-EditorServices-logs.log](https://github.com/PowerShell/vscode-powershell/files/4066714/Start-EditorServices-logs.log)
[logs.log](https://github.com/PowerShell/vscode-powershell/files/4066719/logs.log)
[session.txt](https://github.com/PowerShell/vscode-powershell/files/4066731/session.txt)

**Comment by QuyenLy73** [comment]
Files uploaded. Where do I get the preview extension? I've tried rolling back to an older version but still same issue.

**Comment by rjmholt** [comment]
> Where do I get the preview extension?

It's in the VSCode marketplace as `powershell-preview`. You'll need to uninstall the `powershell` extension for it to work properly.

**Comment by QuyenLy73** [comment]
Unfortunately same issue with the preview version. Might try uninstalling VSCode and re-install.

**Comment by QuyenLy73** [comment]
Re-installing VSCode didn't help.

**Comment by rjmholt** [comment]
Can you post of a GIF of the whole VSCode window as the extension starts up?

**Comment by rjmholt** [comment]
The other thing I noticed is that the Windows version you're using (RS3) may be end-of-life. Sometimes these kinds of hang issues that we can't reproduce are caused by changes in Windows fixed by patches.

**Comment by QuyenLy73** [comment]
The terminal is blank with a Starting Powershell... message at the bottom right. Are you wanting a screenshot of the Output window? Unfortunately I can't control the Windows version. This machine is my work laptop. The Powershell extension is a Microsoft product correct? My next route will have to be to submit a ticket to MS.

**Comment by rjmholt** [comment]
> Are you wanting a screenshot of the Output window?

A GIF/video of the startup would be ideal, something that shows the extension load when the first PowerShell file is opened and then the Integrated Console appear and start, right until the last message that you posted earlier is logged. It might not show any new information, but sometimes there's a clue in the greater VSCode window.

> Unfortunately I can't control the Windows version. This machine is my work laptop.

In that case I believe RS3 is good until April. But in an enterprise context, sometimes anti-virus or group policy prevent startup. It's not entirely clear how we'd show that, but some users have found they can reproduce the same issue on various work devices with different Windows and PowerShell versions, while also having no problem starting the extension on personal devices. If you find that's the case, we'd be grateful for any data you can provide since this is something that crops up from time to time but is very hard to reproduce.

> The Powershell extension is a Microsoft product correct?

This is indeed software developed, maintained and made available by Microsoft. I am a Microsoft engineer.

**Comment by QuyenLy73** [comment]
This was working fine before the holiday break. I upgraded to the latest extension recently so not sure what triggered the issue. Could very well be Windows hotfix, GPO, etc... I just need to figure out what exactly. I can try and record VSCode but it pretty much shows me a blank terminal window while it's starting up. I don't see anything else.

**Comment by QuyenLy73** [comment]
Any advice on what specific group policy to look for? Isn't this just trying to run a PS script behind the scenes? ie Start-EditorServices.ps1?

**Comment by rjmholt** [comment]
> This was working fine before the holiday break. I upgraded  to the latest extension recently so not sure what triggered the issue.

Yeah we've heard similar in other cases. Often it seems the extension hasn't changed, or even VSCode (since they're totally separate). But one day it just stops working. Possibly a Windows patch, perhaps more likely a policy rollout.

> Isn't this just trying to run a PS script behind the scenes? ie Start-EditorServices.ps1?

Yeah, VSCode starts a child process like `powershell.exe -noprofile -nologo -command 'C:\path\to\Start-EditorServices.ps1 ... <parameters for connecting, like named pipe name>'`

> I can try and record VSCode but it pretty much shows me a blank terminal window while it's starting up. I don't see anything else.

In the absence of other information it could be helpful. It likely won't shed new light, but sometimes there's a clue.

> Any advice on what specific group policy to look for?

Unfortunately I don't know very much about GPO or how exactly it could interact with the extension, just that some other users have reported it doing so. I'll try and do some research on it. In the meantime, this issue is marked for triage so I'll discuss it with some other team members tomorrow.

**Comment by rjmholt** [comment]
At the point the extension seems to be stuck, the server has created an ACL'd named pipe and the client should be connecting over that named pipe

**Comment by QuyenLy73** [comment]
Hopefully you'll have some more ideas after speaking with your team members. In the meantime I'll look into submitting a MS support case ticket. That way I can talk with someone and do screen sharing.

**Comment by doug4772** [comment]
Any updates on this issue?  I am experiencing the same symptoms.  The the OP, this also worked prior to the holidays and no longer does.  I've even gone as far as installing PS Core 6.2 to test both Windows PS 5.1 and PSC 6.  No change in either behavior.  Attached are the session logs.

[Start-EditorServices-logs.log](https://github.com/PowerShell/vscode-powershell/files/4078590/Start-EditorServices-logs.log)
[logs.log](https://github.com/PowerShell/vscode-powershell/files/4078591/logs.log)

**Comment by TylerLeonhardt** [comment]
@doug4772  Can you give this a go in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension? It has a ton of fixes in it and it might be fixed in that already.

**Comment by doug4772** [comment]
@TylerLeonhardt That was the last thing I tried since it was already suggested.  I was hoping that resolved the issue.

**Comment by TylerLeonhardt** [comment]
Is this your work machine? If so, I'd like to know what kind of restrictions they put on your device. GPO is possibly a culprit. We sometimes refer folks to try this workaround:
https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-6#installing-the-powershell-extension-on-restricted-systems

For some folks, Anti-virus was the culprit.

We can't reproduce this at all, so it's hard to diagnose.

**Comment by doug4772** [comment]
@TylerLeonhardt Yes, this is my work machine (Win10 1809).  I can check with one of the admins about GPOs but I don't think anything new was rolled out in the last few weeks.  Plus, this impacts a few VSCode users but not all of us.  We are all on the latest VSCode and PS Extension.  I'm the only one that tried the preview extension.  

I did try disabling the Malwarebytes real-time protection, but that didn't seem to impact it either.

The import-module command referenced in the link succeeded, but did not change the VSCode behavior.

**Comment by doug4772** [comment]
Any updates on this issue?  I've been forced to use the ISE for PS Scripts that I need an integrated terminal.  Blah.

**Comment by QuyenLy73** [comment]
I have also tried the preview extension and same issue. I highly doubt that there was been any GPO changes but it would be helpful if it was known what particular GPO could cause this so that I can check the setting.

**Comment by TylerLeonhardt** [comment]
Anything that messes with Execution Policy is usually suspicious.

Also, you folks don't run in constrained language mode, right?

```
PS > $ExecutionContext.SessionState.LanguageMode
```

Also, the PowerShell extension uses a named pipe for communication... Are there any bizarre file restrictions?

It's really hard to debug this without a solid repo, unfortunately.

**Comment by QuyenLy73** [comment]
My execution policy is unrestricted and I'm not even sure what language mode is so no. I just got off of a sharing session with MS customer support. He recorded my screen and said that he will reach out to the product team. Hopefully that will be helpful to you guys.

**Comment by doug4772** [comment]
I updated Windows 10 from 1809 to 1909 and my issues is resolved.  It was an option that was available to me, but likely isn't in all cases.  On the bright side, now I can install the Windows Terminal preview as well!  Good luck to everyone else.

**Comment by QuyenLy73** [comment]
I am on 1709. I don't control what gets installed on my laptop. I'll have to see how I can get an exception to install a newer Win10 version.

**Comment by Crossady** [comment]
same issue here, I use powershell core 6.2.3, windows 1909,
while I managed to solve it by reinstall powershell core from msi.
previously I installed it by dotnet global tools
hope it helps

**Comment by doug4772** [comment]
> same issue here, I use powershell core 6.2.3, windows 1909,
> while I managed to solve it by reinstall powershell core from msi.
> previously I installed it by dotnet global tools
> hope it helps

I installed solely with the MSI from the onset.  So, I have no clue what ultimately solved this issue for me.

**Comment by QuyenLy73** [comment]
I don't have powershell core at all. I'm at 5.1.

**Comment by QuyenLy73** [comment]
i just installed 6.2.3 via dotnet global tools. same issue.

**Comment by TylerLeonhardt** [comment]
@QuyenLy73 the 6.2.3 release of the global tool had a bug in it that made it not work with the extension. That bug is fixed and will be included in 6.2.4 released this week.

**Comment by TylerLeonhardt** [comment]
@QuyenLy73 can you try installing PowerShell Core 6.2.3 via the MSI or some other method and try again?

**Comment by TylerLeonhardt** [comment]
Also, I'd appreciate it if those affected could dig around in "Event Viewer" both in the PowerShell events section and Security events section for anything that might be blocking PowerShell in some way.

**Comment by QuyenLy73** [comment]
I can't unfortunately. We don't have full admin privileges to our machines here at my company. I'm trying to find out if there's a way for me to get privileges temporarily to install 6.2.3.

**Comment by TylerLeonhardt** [comment]
PowerShell Core is xcopy-able. Just download the zip and then add this to your settings:

```json
    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "C:\\path\\to\\pwsh.exe",
            "versionName": "PowerShell Core download"
        }
    ],
    "powershell.powerShellDefaultVersion": "PowerShell Core download",
```

**Comment by QuyenLy73** [comment]
Sure I'll look but Powershell isn't an issue. I can run powershell scripts just fine. The ISE also works fine. Just an issue with the VS Code extension.

**Comment by QuyenLy73** [comment]
Okay thanks I'll give that a try.

**Comment by TylerLeonhardt** [comment]
Yeah I know the issue is scoped to VS Code extension but at this time, I don't have enough information to work with. Since I can't repro the issue, I need to explore as many avenues as possible.

**Comment by TylerLeonhardt** [comment]
How powerful is the machine that you're seeing this issue on?

**Comment by QuyenLy73** [comment]
Core i5-6440HQ 16GB ram

**Comment by QuyenLy73** [comment]
I was just able to install 6.2.3. It was installed at C:\Program Files\PowerShell. Unless I'm in this folder, my PS version shows as 5.1. Not sure if that's expected behavior?

**Comment by QuyenLy73** [comment]
Actually never mind. Looks like 5.1 and Core are installed side by side. I'll add the VS Code setting to point to 6.2.3 and see what happens.

**Comment by TylerLeonhardt** [comment]
@QuyenLy73 for future reference, you can click on the green PowerShell version number in the bottom right to change what version of PowerShell you want to use. The green version number only shows up if you have a PowerShell script file opened.

**Comment by QuyenLy73** [comment]
So installing 6.2.3 and defaulting to that works. I guess I only need to worry about not using any PS Core specific functionality since none of the servers that I work with use PS Core.

**Comment by doug4772** [comment]
For what it's worth, I'm having similar issues on my Mac w/ the latest VS Code and PS Core 6.x.

**Comment by SydneyhSmith** [comment]
@QuyenLy73 thanks that is a helpful piece of information...we will continue to investigate this issue and update as appropriate and ask any questions that come up...in the meantime you may want to investigate PSSA compatibility rules as a way to target 5.1 in your development while running core. 
More info on that here : https://devblogs.microsoft.com/powershell/using-psscriptanalyzer-to-check-powershell-version-compatibility/

**Comment by pseudobacon** [comment]
Installing 6.2.3 x64 with the MSI fixed this for me

**Comment by TylerLeonhardt** [comment]
@doug4772 I don't think you're experiencing the same issue on macOS. Can you add the logs & screenshots here?

**Comment by rjmholt** [comment]
Ok, I've just managed to spin up a fresh RS3 VM with VSCode 1.14.1 and PS 5.1 to try this out. I wasn't able to reproduce a startup freeze with either the current stable extension or the current master build. That may mean that rather than being a Windows bug this is a policy or antivirus issue.

One last resort is to collect a [procdump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) of the frozen process to see where it's stuck. We've tried that in the past and in cases like this it hasn't shown clear results, but might be worth a try anyway.

**Comment by SlkRck** [comment]
I'm receiving the error mentioned above PLUS the fact I cannot open a terminal.  I uninstalled VSCode completely, rebooted, reinstalled and before installing any PowerShell extensions, tried to open a terminal and it failed with the error:  

_**The terminal process command 'C:\Program Files\PowerShell\7\pwsh.exe' failed to launch (exit code: {2})**_

**Comment by davesbrown** [comment]
Happening on all my PROD api servers now

**Comment by erobillard** [comment]
Same issue. Started when Code was updated. Neither the last stable version nor the Preview work. Username obfuscated below.

4/22/2020 7:06:42 PM [NORMAL] - Visual Studio Code v1.44.2 64-bit
4/22/2020 7:06:42 PM [NORMAL] - PowerShell Extension v2020.4.0
4/22/2020 7:06:42 PM [NORMAL] - Operating System: Windows 64-bit
4/22/2020 7:06:42 PM [NORMAL] - Language server starting --
4/22/2020 7:06:42 PM [NORMAL] -     PowerShell executable: C:\Users\myself\.dotnet\tools\pwsh.exe
4/22/2020 7:06:42 PM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\myself\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\myself\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\myself\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1587596802-25479203-0f29-4890-bbd5-951e79fadd981587596783837\EditorServices.log' -SessionDetailsPath 'c:\Users\myself\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-17948-194532' -FeatureFlags @() 
4/22/2020 7:06:42 PM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\myself\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.4.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\myself\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\myself\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs\1587596802-25479203-0f29-4890-bbd5-951e79fadd981587596783837\EditorServices.log' -SessionDetailsPath 'c:\Users\myself\.vscode\extensions\ms-vscode.powershell-2020.4.0\sessions\PSES-VSCode-17948-194532' -FeatureFlags @() 
4/22/2020 7:06:42 PM [NORMAL] - pwsh.exe started.
4/22/2020 7:06:42 PM [NORMAL] - Waiting for session file
4/22/2020 7:08:42 PM [NORMAL] - Error occurred retrieving session file:
Timed out waiting for session file to appear.
4/22/2020 7:08:42 PM [NORMAL] - Language server startup failed.
4/22/2020 7:08:42 PM [ERROR] - The language service could not be started: 
4/22/2020 7:08:42 PM [ERROR] - Timed out waiting for session file to appear.

**Comment by TylerLeonhardt** [comment]
Do you run any privilege management software like BeyondTrust?

**Comment by ahohenschuh** [comment]
I have the same problem that Posh 5.1 crashes with "initialization error" in vscode. Posh7 works.

[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4580355/vscode-powershell.log)

**Comment by TylerLeonhardt** [comment]
> I have the same problem that Posh 5.1 crashes with "The language service could not be started" in vscode. Posh7 works.
> 
> [vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4580355/vscode-powershell.log)
> 

Do you run any privilege management software like BeyondTrust?

**Comment by mkanet** [comment]
So.. what's the solution to this issue?  It just started happening today on my main PC.  Surely with this many people having this issue, there has to be a way to fix it.  

I'm using Windows 10 Version 2004 (OS Build 19041.630) using PowerShell 5.1.  I've tried both the PowerShell Preview extension as well as the regular PowerShell Extension.

**Comment by sweenb1** [comment]
Also getting this issue in VS Code:
10/2/2021 12:15:52 [NORMAL] - Visual Studio Code v1.53.1 64-bit
10/2/2021 12:15:52 [NORMAL] - PowerShell Extension v2020.6.0
10/2/2021 12:15:52 [NORMAL] - Operating System: Windows 64-bit
10/2/2021 12:15:52 [NORMAL] - Language server starting --
10/2/2021 12:15:52 [NORMAL] -     PowerShell executable: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
10/2/2021 12:15:52 [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\*****\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\****\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\****\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1612959352-1492f77d-a1fb-4083-82da-059fc7ae41d31612959230672\EditorServices.log' -SessionDetailsPath 'c:\Users\*****\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-19512-642239' -FeatureFlags @() 
10/2/2021 12:15:52 [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\*****\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\*****\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\*****\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1612959352-1492f77d-a1fb-4083-82da-059fc7ae41d31612959230672\EditorServices.log' -SessionDetailsPath 'c:\Users\*****\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-19512-642239' -FeatureFlags @() 
10/2/2021 12:15:52 [NORMAL] - powershell.exe started.
10/2/2021 12:15:52 [NORMAL] - Waiting for session file
10/2/2021 12:19:52 [NORMAL] - Timed out waiting for session file to appear.
10/2/2021 12:19:52 [NORMAL] - Language server startup failed.
10/2/2021 12:19:52 [ERROR] - The language service could not be started: 
10/2/2021 12:19:52 [ERROR] - Error: Timed out waiting for session file to appear.

Powershell version is 5.1.17763.1490

**Comment by mmunchandersen** [comment]
I'm getting this on a Window 2013R2 server. Anyone with a solution?

29.9.2021 21.08.33 [NORMAL] - Visual Studio Code v1.60.2 64-bit
29.9.2021 21.08.34 [NORMAL] - PowerShell Extension v2021.9.0
29.9.2021 21.08.34 [NORMAL] - Operating System: Windows 64-bit
29.9.2021 21.08.34 [NORMAL] - Language server starting --
29.9.2021 21.08.34 [NORMAL] -     PowerShell executable: C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe
29.9.2021 21.08.34 [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\Administrator\.vscode\extensions\ms-vscode.powershell-2021.9.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.9.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Administrator\.vscode\extensions\ms-vscode.powershell-2021.9.0\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.9.0 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\Administrator\.vscode\extensions\ms-vscode.powershell-2021.9.0\logs\1632942514-d5eecef5-00e9-478c-8d45-2edb094747141632942501054\EditorServices.log' -SessionDetailsPath 'c:\Users\Administrator\.vscode\extensions\ms-vscode.powershell-2021.9.0\sessions\PSES-VSCode-4128-329853' -FeatureFlags @() 
29.9.2021 21.08.34 [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\Administrator\.vscode\extensions\ms-vscode.powershell-2021.9.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.9.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Administrator\.vscode\extensions\ms-vscode.powershell-2021.9.0\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.9.0 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\Administrator\.vscode\extensions\ms-vscode.powershell-2021.9.0\logs\1632942514-d5eecef5-00e9-478c-8d45-2edb094747141632942501054\EditorServices.log' -SessionDetailsPath 'c:\Users\Administrator\.vscode\extensions\ms-vscode.powershell-2021.9.0\sessions\PSES-VSCode-4128-329853' -FeatureFlags @() 
29.9.2021 21.08.34 [NORMAL] - powershell.exe started.
29.9.2021 21.08.34 [NORMAL] - Waiting for session file
29.9.2021 21.12.37 [NORMAL] - Timed out waiting for session file to appear.
29.9.2021 21.12.37 [NORMAL] - Language server startup failed.
29.9.2021 21.12.37 [ERROR] - The language service could not be started: 
29.9.2021 21.12.37 [ERROR] - Error: Timed out waiting for session file to appear.
