### ISSUE TITLE
Intellisense creates duplicate warnings when commenting/uncommenting code

### ISSUE THREAD

**Issue by musaugurlu** [PowerShell/vscode-powershell#2419]
OS Version: Win 10 -1903 (Windows_NT x64 10.0.18362)
PS Version : 5.1
VSCode version: 1.41.1 (user setup)
Powershell (ms-vscode.powershell) extension Version: 2019.12.0

### Steps to reproduce the issue:
* open a new tab
* select the language as PowerShell
* Create a variable and assign a string: `$Test = "test"`
* create cmdlet from snippeds
``` 
function Verb-Noun {
    [CmdletBinding()]
    param (
        
    )
    
    begin {
        
    }
    
    process {
        
    }
    
    end {
        
    }
}
```
* Intellisense should show the warning the the variable is never used
* comment out the cmdlet
```
# function Verb-Noun {
#     [CmdletBinding()]
#     param (
        
#     )
    
#     begin {
        
#     }
    
#     process {
        
#     }
    
#     end {
        
#     }
# }
```
* Now, intellisense shows 11 duplicate warning

**Comment by rjmholt** [comment]
Thanks for opening an issue @musaugurlu. Would you be able to show:

- The full script that generates the warnings (ideally in text)
- A screenshot of the phenomenon occurring, including the warnings you see?
