### ISSUE TITLE
Paste a string for the password of Get-Credential crashes PSIC

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/vscode-powershell#2420]
### Issue Description
PSIC crashe

### Steps to reproduce
1. Create a file with the following content:

**File.ps1**
```powershell
(Get-Credential -UserName 'Test' -Message 'Password please')
```
2. Press `F5` and the `PSIC` will ask you for the password.
3. Copy a random string in the terminal and watch the `PSIC` crash

```
Version: 1.42.0-insider (system setup)
Commit: 33c79d5ad447956814a2a3658029dffb9e28bae6
Date: 2020-01-15T09:36:35.018Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393
```

PowerShell Preview version `2020.10`

**Comment by rjmholt** [comment]
Hey @DarkLite1, would be able to give some more info or maybe a screen recording of this?

I tried this on Windows with PowerShell 5.1 and 7-rc.1 with <kbd>Ctrl</kbd>-<kbd>V</kbd> and also right-click paste and haven't been able to reproduce the issue yet. Here's a screen grab:

![password](https://user-images.githubusercontent.com/7009879/72555540-97e38c00-3851-11ea-86bb-e3f3bd37b013.gif)

Maybe this is happening on a particular OS or with a particular PowerShell version. Also worth seeing what the PSReadLine version is, in case that's wrong.

**Comment by rjmholt** [comment]
Also, knowing how the PSIC crashes (like any error messages) would be good info

**Comment by DarkLite1** [comment]
I've had this problem on our `Windows Server 2016` which is running `PowerShell 5.1`. For making my first animated GIF file I had to install an app and I didn't want this app on the server so I did a fresh install on `Windows 10` with the latest `PowerShell Preview` extension. Nothing else is on the box.

Here's the requested screen grab:

![Failure2](https://user-images.githubusercontent.com/10828570/72597186-865fba00-390d-11ea-9380-e2432fa0b1eb.gif)

**Comment by SydneyhSmith** [comment]
@DarkLite1 thanks for the screen grab that helps us to determine the issue, it looks like the crash may be occuring when you hover over the password which may be triggering something in VSCode. 
It would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by DarkLite1** [comment]
All bug reports attached as requested. Thank yoiu for looking into this.
[bug vscode.zip](https://github.com/PowerShell/vscode-powershell/files/4097672/bug.vscode.zip)

**Comment by SydneyhSmith** [comment]
@DarkLite1 thanks for providing those logs.. interestingly digging through them there is no obvious crash, we will have to give this a deeper look and will update if we find anything. Would it also be possible for you to provide logs using PowerShell 7?

**Comment by DarkLite1** [comment]
We're running `PowerShell 5.1` currently on all our production systems. This will last for a long time until `PowerShell 7` is widely available and properly tested. Probably after a `7.2` release or something will we upgrade.

Strange that you can't replicate the issue. This even happened on a fresh install of `vscode-insiders` on a clean `Windows 10` with `PowerShell 5.1` and no extra config. Anyhow, thanks for looking into this.

**Comment by TylerLeonhardt** [comment]
Totally understand - just want to make sure this is scoped to Windows PowerShell for you and not all versions of PowerShell.

**Comment by rjmholt** [comment]
I'll see if I can try to reproduce this on your particular Windows version.

We have a small menagerie of hangs that occur only on Windows and sometimes they seem quite OS version specific.

**Comment by DarkLite1** [comment]
Thank you, this is the version we're currently on:

![image](https://user-images.githubusercontent.com/10828570/73245015-884a3880-41ab-11ea-8c97-2949396f98af.png)

**Comment by rjmholt** [comment]
I've managed to reproduce this now, and quite consistently.

For some reason `_readLineCancellationSource` is null [here](https://github.com/PowerShell/PowerShellEditorServices/blob/e051a89b2d639cea5e2771d92f314dc99cd44ab7/src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs#L75).

**Comment by rjmholt** [comment]
Looking into the solution now
