### ISSUE TITLE
CodeLens References not working if function is in another file

### ISSUE THREAD

**Issue by mrboring** [PowerShell/vscode-powershell#2421]
### System Details

System Details Output
```
### VSCode version: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64

### VSCode extensions:
alefragnani.Bookmarks@10.6.0
eamodio.gitlens@10.2.0
Ionide.Ionide-FAKE@1.2.3
Ionide.Ionide-fsharp@4.4.4
Ionide.Ionide-Paket@1.12.0
ms-vscode.csharp@1.21.9
ms-vscode.powershell@2020.1.0        
ms-vscode.powershell-preview@2020.1.0
streetsidesoftware.code-spell-checker@1.7.20


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Issue Description

CodeLens References does not work if the function is in another file. Both files shown below are in the same folder.

![image](https://user-images.githubusercontent.com/5991977/72516902-5ef3e900-384a-11ea-86f4-c52b23d1416a.png)

Note the `1 reference` above the `Y` function definition. This is in the same file as the reference.
Note the `0 reference` above the `X` function definition. This is in a different file to the referenc.

I wonder if this is related to: [CodeLens References link only jumps to definition #2374](https://github.com/PowerShell/vscode-powershell/issues/2374).

#### Expected Behaviour

In `TestModule.psm1` I expected to see ` 1 references` above the `X` function definition.

#### Actual Behaviour

In `TestModule.psm1` I  see ` 0 references` above the `X` function definition

Also `Find All References` for function `X` shows:

![image](https://user-images.githubusercontent.com/5991977/72515897-a6797580-3848-11ea-8973-43247887e641.png)

`Find All References` for function `Y` shows:

![image](https://user-images.githubusercontent.com/5991977/72517502-6bc50c80-384b-11ea-8d27-4393682ce407.png)

### Attached Logs

[PowerShell Extension Logs.txt](https://github.com/PowerShell/vscode-powershell/files/4070570/PowerShell.Extension.Logs.txt)
[PowerShell Editor Services Log.txt](https://github.com/PowerShell/vscode-powershell/files/4070657/PowerShell.Editor.Services.Log.txt)

**Comment by TylerLeonhardt** [comment]
Nice find! I've fixed this and it will be available in the next version.

**Comment by PrzemyslawKlys** [comment]
Does this change cover the whole workspace? I have modules separated within multiple layers of folders and just got the same issue but with a bit diffferent thing. 

It shows 0 references

![image](https://user-images.githubusercontent.com/15063294/72618751-14529980-393c-11ea-947b-824eb30298d2.png)

Find References shows only 1 find in 1 file (the file the function is defined in) but clearly I have it in other files.


![image](https://user-images.githubusercontent.com/15063294/72618876-64c9f700-393c-11ea-9228-9b5b68c8faea.png)

**Comment by mrboring** [comment]
@TylerLeonhardt I'm also having problems with `Go to Definition`. I wonder if it could be related. If it's not, let me know and I'll create another issue.

[Go to Definition not working.zip](https://github.com/PowerShell/vscode-powershell/files/4077523/Go.to.Definition.not.working.zip)

In the attached zip there is a small test project.

### Expected behaviour

Go to Definition should work for all functions.

### Actual behaviour

#### PowerShell-Preview-2019.12.0.vsix

Go to Definition works for all functions.

#### PowerShell-Preview-2020.1.0.vsix

Go to Definition does work for:
- Test-FunctionLocal
- Test-FunctionAnotherDifferentFolder

Go to Definition does not work for:
- Test-FunctionDifferentFolder

**Comment by TylerLeonhardt** [comment]
Would you like to give it a try and see if it works for you?
[PowerShell-insiders.vsix.zip](https://github.com/PowerShell/vscode-powershell/files/4093559/PowerShell-insiders.vsix.zip)

@PrzemyslawKlys, this also includes https://github.com/PowerShell/PowerShellEditorServices/pull/1162 so I'm curious how the PSIC looks for you.

Let me know if you have trouble installing. This is an unsigned build and has 0 official support so keep that in mind.

**Comment by PrzemyslawKlys** [comment]
Installing :-)

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/72841001-c15b4800-3c95-11ea-8b28-7e27eec15063.png)

Won't run :)

**Comment by mrboring** [comment]
@TylerLeonhardt I've installed the new VSIX and done a quick test. Both `references` and `Go to Definition` are working.

**Comment by PrzemyslawKlys** [comment]
That's so weird that it works for you 👱‍♂️

**Comment by TylerLeonhardt** [comment]
@PrzemyslawKlys you've had trouble with dev build vsix's in the past IIRC

**Comment by TylerLeonhardt** [comment]
oh wait - that's because I built on a mac and it has to be built on Windows. gah. give me a sec.

**Comment by mrboring** [comment]
@PrzemyslawKlys Don't know if it helps, but this is my current configuration:

```
### VSCode version: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64

### VSCode extensions:       
alefragnani.Bookmarks@10.6.0 
eamodio.gitlens@10.2.0       
Ionide.Ionide-FAKE@1.2.3     
Ionide.Ionide-fsharp@4.5.0   
Ionide.Ionide-Paket@1.12.0   
mohsen1.prettify-json@0.0.3  
ms-vscode.csharp@1.21.9      
ms-vscode.powershell@2020.1.0
ms-vscode.powershell-preview@2020.1.0       
streetsidesoftware.code-spell-checker@1.7.21


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mrboring** [comment]
@TylerLeonhardt I'm on Windows 10 and it's working for me!

**Comment by PrzemyslawKlys** [comment]
PowerShell 7, i tried on 5.1.

**Comment by PrzemyslawKlys** [comment]
You also have both extensions enabled.... disable the primary one.

**Comment by TylerLeonhardt** [comment]
I can't build the part that's needed to get the extension working on 5.1 cause I use a mac. Only the part for PS6+. - for context.

**Comment by PrzemyslawKlys** [comment]
On PowerShell 7 seems to work. Thanx

**Comment by mrboring** [comment]
> 
> 
> You also have both extensions enabled.... disable the primary one.

@PrzemyslawKlys It was disabled. I've now removed it and it still works. As you've summised it works because I'm using PowerShell 7.

**Comment by PrzemyslawKlys** [comment]
Yes, but I mean it only shows enabled extensions so it must have been "within the session".

**Comment by mrboring** [comment]
@PrzemyslawKlys OK. I see. Thanks for the info.

**Comment by TylerLeonhardt** [comment]
Glad to here this issue is fixed :)

**Comment by mrboring** [comment]
@TylerLeonhardt I've done a bit more testing of the new VSIX and found a little issue.

![image](https://user-images.githubusercontent.com/5991977/72986983-57e85000-3de1-11ea-95f3-62eb3e6ff5fb.png)

The above is a screenshot of the project I attached above (https://github.com/PowerShell/vscode-powershell/issues/2421#issuecomment-576867256). Note that for the file: `Test-FunctionDifferentFolder.ps1` that two entries appear. This file contains the definition of the function only. So, I would expect to only see one reference.

I also have a question. Would you expect `Go to Definition` to work across workspaces?

**Comment by TylerLeonhardt** [comment]
> I've done a bit more testing of the new VSIX and found a little issue.

I'll look into this but please open a new issue so we don't lose this thread.

> Would you expect Go to Definition to work across workspaces?

I believe there is some expectation that this should work. Right now, we are focused on closing gaps between the PowerShell Preview extension and PowerShell Stable extension. Can you try the `Go to definition` in the Stable extension to compare?

**Comment by PrzemyslawKlys** [comment]
Well I've opened this issue a while ago: https://github.com/PowerShell/vscode-powershell/issues/2112

It wasn't supported for multiple workspaces in the "old version'. But that would be cool if it would be possible. During development, I am often separating some code into different modules and it makes it much harder to debug things if only 1 workspace shows references.

**Comment by TylerLeonhardt** [comment]
I hear ya. There are a ton of opportunities for rich feature experiences for PowerShell in VS Code.

Unfortunately/fortunately, we had to focus on stability and performance for the past 2 years, peppering in small features as we go.

Plus there's really only 1 dev working on this at any given time so the resources are slim.

We're trying though. I hope that's visible.

**Comment by PrzemyslawKlys** [comment]
You don't have to tell me that :-) While I code only in PowerShell over my modules I get how hard some things are and that resources are slim. I have 40 PS modules that I manage mostly alone with some help from the community. I appreciate all the work you and your team do. I'll keep opening bugs/feature requests to make sure everything runs great. Even my F5 debug issue is no big deal now after you taught me how to "workaround" it - since I see what is happening now.

So take your time :-) I just wish there was a much faster process for preview between fix and release date so those small bugs like this one would go away faster than once per month. But as you explained, it's not an automated process so until that is done I'm fine :-) I automated my PowerShell modules building just so I don't have to spend time doing manual releases because I release modules daily, even multiple times per day.

**Comment by mrboring** [comment]
@TylerLeonhardt As requested:

[[2020.1.0 Preview] Find All References shows two entries for the function definition #2433](https://github.com/PowerShell/vscode-powershell/issues/2433)

**Comment by mrboring** [comment]
@TylerLeonhardt With regard to `Go to Definition` and workspaces, I've tried the latest stable and test versions of the extension. Both give the following message: `No definition found for '<function name>'`.

Looking at the comments on the issue created by @PrzemyslawKlys, it looks like this functionality has not yet been added.
