### ISSUE TITLE
Starting Visual Studio Code changes display resolution from 4K to FullHD with Powershell plugin installed (and enabled) 

### ISSUE THREAD

**Issue by dirk-adams** [PowerShell/vscode-powershell#2423]
Very strange (but very annoying) behavior since this afternoon (started after reload from Powershell plugin update to v2020.1.0). 
After starting Visual Studio Code (not immediately, but a few seconds later) the display resolution of my screen is downgraded (from 3840x2160 to 1920x1080) (consistently, every time). Uninstalling (or disabling) the Powershell plugin in Visual Studio Code stops this behavior.

**Comment by rjmholt** [comment]
@dirk-adams is this issue ongoing? If it's not, what fixed it?

**Comment by dirk-adams** [comment]
Hi Robert,

 

Thanks for checking in. The issue has indeed been fixed.

Apparently my ‘modules’ were getting parsed (executed?) in the background. One of the module files contains a function ‘set-screenresolution’ (the name explains what it does…) that had an executable line for testing (outside of the function block) which called the function… Removing this line stopped the behavior…

A mystery however remains why this all of a sudden started occurring, as that file has always been there (unchanged) for quite a number of weeks…

 

Kind regards,

Dirk

 

--

Dirk Adams

Zaakvoerder

 

AS-Consultants bvba

Zakstraat 12

3700 Tongeren – Belgium

 

 <mailto:dirk.adams@visysglobal.com> mailto:dirk.adams@as-consultants.be

 

Confidentiality Notice:   This e-mail and any attachments or associated files are transmitted for the exclusive and confidential use of the intended recipient(s), and may contain information that is privileged, confidential, information that constitutes a trade secretor or otherwise protected from disclosure.  Where opinions are expressed, they are not necessarily those of AS-Consultants bvba.  If you receive this e-mail in error, please immediately notify AS-Consultants (e-mail  <mailto:dirk.adams@logitron.be> dirk.adams@as-consultants.be), delete the e-mail and its attachments from your computer system, and destroy all copies.

**Comment by rjmholt** [comment]
Possibly related to https://github.com/PowerShell/vscode-powershell/issues/715

**Comment by rjmholt** [comment]
I did think we had a more recent issue for this
