### ISSUE TITLE
[2020.1.0 Preview] F8 not working while using "Interactive Session" debuging

### ISSUE THREAD

**Issue by ili101** [PowerShell/vscode-powershell#2424]
Issue Type: <b>Bug</b>

Start.ps1
```powershell
. .\File2.ps1
```
File2.ps1
```powershell
1
2
3
```
.vscode\launch.json
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PowerShell Launch Current File",
            "type": "PowerShell",
            "request": "launch",
            "script": "${file}",
            "cwd": "${file}"
        },
        {
            "name": "PowerShell: Interactive Session",
            "type": "PowerShell",
            "request": "launch",
            "cwd": ""
        }
    ]
}
```

1. Start "PowerShell: Interactive Session" debug.
2. Set breakpoint anywhere on File2.ps1.
3. Go to Start.ps1 and F8 on the line (debug will start and take you to the breakpoint on File2.ps1).
4. F8 on any line (it will not work).
5. F5 to finish debugging (All previous F8s will execute at once after the script finished).

![F8](https://user-images.githubusercontent.com/6960531/72567986-b84a2f80-38bf-11ea-9ce7-bf832906a780.gif)

Logs:
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4074102/EditorServices.log)
F8 presses are the `2020-01-17 00:39:29.212 +02:00 [DBG] Finding descriptor for evaluate` log lines. The lines after that are the F5

Extension version: 2020.1.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|4.00GB (1.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by rjmholt** [comment]
I'm able to reproduce this. Looking into it

**Comment by ili101** [comment]
Still a problem on 2020.2.0 Preview

**Comment by TylerLeonhardt** [comment]
PR out for this.
