### ISSUE TITLE
Add buttons for moving the terminal around

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/vscode-powershell#2430]
**Add buttons for moving the terminal around**

The ISE has buttons for moving the console/script pane around so you can quickly maximize one or the other, or put them side by side. This is a nice feature to have in situations where you want maximum screen space for the script pane, or want to look through a big list of objects in the console pane.

**Proposed technical implementation details**

Add 3 buttons in the tabs bar similar to the recently added Run and Run Selection buttons with the following built-in VS code functions:

- "View: Move Panel Left" (Maybe add a setting that changes it to right instead of left?)
- "View: Move Panel To Bottom"
- "View: Toggle Panel"

**Comment by rkeithhill** [comment]
You can do this today with keyboard shortcuts:
```
[
    { "key": "ctrl+shift+a",     "command": "workbench.action.togglePanelPosition" },
    { "key": "ctrl+shift+q",     "command": "workbench.action.toggleMaximizedPanel" }
]
```

**Comment by SydneyhSmith** [comment]
Thanks for making this request, I am going to mark this enhancement as up for grabs..if you chose to implement this looking at PR #2224 should give you a good starting place....thanks!

**Comment by MartinGC94** [comment]
Fixed in: https://github.com/PowerShell/vscode-powershell/pull/2704
