### ISSUE TITLE
[2020.1.0 Preview] write-progress nested progress bars do not work as expected

### ISSUE THREAD

**Issue by Nanocephalic** [PowerShell/vscode-powershell#2431]
When using the current preview build, write-progress doesn't handle nested progress bars properly. The following code runs properly in the CLI but in vscode, the middle progress bar shows the percentage in the wrong place and doesn't reliably fill the progress field with "o" glyphs.

```
$LoopCount = 10

Write-Progress -id 1 -Activity "Running loops..."

for ($i = 0; $i -lt $LoopCount; $i++) {

  $percentComplete = ($i / $LoopCount) * 100
  Write-Progress -Activity 'External loop' -Status "Processing external iteration $i" -PercentComplete $percentComplete -ParentId 1 -id 2
  Start-Sleep -Milliseconds 500

  for ($j = 0; $j -lt $LoopCount; $j++) {

    $percentComplete = ($j / $LoopCount) * 100
    Write-Progress -Activity 'Nested loop' -Status "Processing nested iteration $j" -PercentComplete $percentComplete -ParentId 2 -id 3
    start-sleep  -Milliseconds 500

  }      

}
start-sleep -Milliseconds 1000

```

**Comment by SydneyhSmith** [comment]
@Nanocephalic thanks for opening this issue--I am having a bit of difficulty reproducing this, it would be really helpful if you could also provide a GIF or screen grab of what you are seeing, it would also be helpful to know what encoding you have 
![image](https://user-images.githubusercontent.com/43417619/72848786-314bdd00-3c5a-11ea-9706-aa374ac21454.png)

**Comment by Nanocephalic** [comment]
Thanks for that. I prepared to repro and record, which led to interesting results.

Turns out that it's by design. The terminal was sized just a bit too small (i.e. too few rows) and the progress bar hid that part of itself. After giving it more space, I was able to see the bars perfectly.

So... it's not a bug. It's a feature. _He said, non-ironically, for the first time ever._
