### ISSUE TITLE
Debugging Powershell in new install of VScode result is an Orange Banner in the footer

### ISSUE THREAD

**Issue by swinster** [PowerShell/vscode-powershell#2432]
Issue Type: <b>Bug</b>

Install Vscode
Install Powershell extension.
Open ps1 file
Open Debugger
Click "Debug in powershel", nothing happens.
Click add config
Add Integrated  PS config
Go back to ps1 file, debug oragne footer

Extension version: 2020.1.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 2100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|32.00GB (28.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details>

**Comment by swinster** [comment]
Looks like default config added to `launch.json` is:

```
        {
            "name": "PowerShell: Interactive Session",
            "type": "PowerShell",
            "request": "launch",
            "cwd": ""
        }
```

**Comment by swinster** [comment]
if I add something like (copied from another VScode install)

```
		{
			"name": "PowerShell x86",
			"type": "PowerShell x86",
			"request": "launch",
			"script": "${file}",
			"args": [],
			"cwd": "${file}"
		}
```

It now seem to be working.

Why would a default installation result in a no functional debug configuration?

**Comment by swinster** [comment]
One other issue. I wanted to set the terminal that is use NOT be the integrated terminal (as this give much better output, and doesn't truncate long commands) . This is simple through the use of the following setting :

``
"powershell.integratedConsole.showOnStartup": false
```

However, Even with the changes made to the `launch.json` above, as soon as I click on Debug, the terminal flips back to the Integrated one, which of course means I don;t have any session modifications made in the other terminal.

**Comment by SydneyhSmith** [comment]
@swinster thanks for opening this issue...
In the first debug configuration you discovered, which we call the "PowerShell: Interactive Session", it has no file specified , therefore it starts the debugger but it does not run any file-- this is the expected behavior.

It looks like you also found the debug configuration "PowerShell: Launch Current file" which should have the behavior you are looking for. Let us know if this doesnt help to clarify or if you have questions about the behaviors of these debug configurations...thanks!
