### ISSUE TITLE
[2020.1.0 Preview] Find All References shows two entries for the function definition

### ISSUE THREAD

**Issue by mrboring** [PowerShell/vscode-powershell#2433]
### System Details

System Details Output
```
### VSCode version: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64

### VSCode extensions:
ms-vscode.powershell-preview@2020.1.0


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

`Find All References` shows two entries for the function definition.

Note: The extension used was an insider build (https://github.com/PowerShell/vscode-powershell/issues/2421#issuecomment-576867256).

#### Expected Behaviour

I expected `Find All Issues` to display a single entry for the function definition.

![image](https://user-images.githubusercontent.com/5991977/73013156-af051980-3e0f-11ea-9286-e4c7a96e0fd2.png)

#### Actual Behaviour

`Find All References` shows two entries for the function definition.

![image](https://user-images.githubusercontent.com/5991977/73012946-4027c080-3e0f-11ea-9f5f-601cee1e6107.png)

Here are my steps to reproduce the issues:

1.    Started Windows Sandbox
2.    Installed PowerShell-7.0.0-rc.2-win-x64.msi
3.    Installed VSCodeUserSetup-x64-1.41.0
4.    Add the following to settings.json

```
{
    "powershell.developer.featureFlags": [
        "PSReadLine"
    ],
    "editor.fontSize": 11,
    "terminal.integrated.fontSize": 11,
    "extensions.ignoreRecommendations": true,
    "extensions.autoCheckUpdates": false,
    "extensions.autoUpdate": false,
    "powershell.developer.editorServicesLogLevel": "Diagnostic",
    "powershell editor services.trace.server":"verbose"
}
```

5.    Installed PowerShell Preview 2019.12.0 Insiders extension (https://github.com/PowerShell/vscode-powershell/issues/2421#issuecomment-576867256)
6.    Closed VS Code
7.    Unzipped test project ([Go to Definition not working.zip](https://github.com/PowerShell/vscode-powershell/files/4104878/Go.to.Definition.not.working.zip)) to a folder on the desktop
8.    Right clicked on folder and selected `Open with Code`
9.    Open `Functions\Test-FunctionDifferentFolder.ps1`
10.   Right click on function name, then select `Find All References`
      - Two references are displayed for the function definition

### Attached Logs

[PowerShell Extension Logs.txt](https://github.com/PowerShell/vscode-powershell/files/4104867/PowerShell.Extension.Logs.txt)

[PowerShell Editor Services Logs.txt](https://github.com/PowerShell/vscode-powershell/files/4104868/PowerShell.Editor.Services.Logs.txt)

**Comment by andschwa** [comment]
Hey @mrboring I know this is an old issue, but can you verify that this is fixed in the latest preview? We just redid all the symbols logic, and _duplicates_ shouldn't occur; however, I'd point out that find all references is supposed to include all definitions and usages of said symbol.

**Comment by andschwa** [comment]
Hey surprisingly your zip of code was still available so I was able to download and follow your repro steps, and can confirm this no longer repros! 🥳
