### ISSUE TITLE
Starting powershell status bar item doesn't go away if powershell isn't installed

### ISSUE THREAD

**Issue by Tyriar** [PowerShell/vscode-powershell#2435]
<img width="474" alt="Screen Shot 2020-01-24 at 8 26 26 AM" src="https://user-images.githubusercontent.com/2193314/73085279-4bb4cf00-3e83-11ea-8fc0-0ba907a3f927.png">

Clicking it results in that notification.

**Comment by Tyriar** [comment]
<img width="471" alt="Screen Shot 2020-01-24 at 8 28 16 AM" src="https://user-images.githubusercontent.com/2193314/73085387-7bfc6d80-3e83-11ea-83a5-40ff9d634239.png">

Eventually after a minute or so it turned into this, seems like a long time to allow for init.

**Comment by Tyriar** [comment]
Restarting the session after it failed gives you the useful error message, can this be handled explicitly with instructions to install powershell on the platform in question? (mac here)

<img width="464" alt="Screen Shot 2020-01-24 at 8 30 29 AM" src="https://user-images.githubusercontent.com/2193314/73085638-d85f8d00-3e83-11ea-9c12-a0fc4c7efc11.png">

**Comment by TylerLeonhardt** [comment]
@Tyriar were you using the [PowerShell](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) extension or [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension. I recall we handle no PowerShell being installed more gracefully in Preview... but maybe there's more work to be done.

**Comment by TylerLeonhardt** [comment]
What's in the PowerShell Preview extension is expected to make it into stable around mid-Feb.

**Comment by Tyriar** [comment]
This was in stable, if preview is better you can close this.

**Comment by TylerLeonhardt** [comment]
Yeah we have a whole dialog now: https://github.com/PowerShell/vscode-powershell/blob/master/src/session.ts#L148-L164
