### ISSUE TITLE
Extension is not working if windows username contains spaces

### ISSUE THREAD

**Issue by maksims-prieditis** [PowerShell/vscode-powershell#244]
Installed extension today for the first time and it seems like I'm the only one who got spaces in windows account. :) Basically, EditorServices couldn't be started (log attached) and I guess debugger fails for the same reason. Added local account without spaces -- everything works.

[1471546041-PowerShell.txt](https://github.com/PowerShell/vscode-powershell/files/425686/1471546041-PowerShell.txt)

**Comment by daviwil** [comment]
Ouch, I immediately see the issue.  Sorry for the trouble!  Will get this fixed in the next couple of days.

**Comment by daviwil** [comment]
The path to Start-EditorServices.ps1 needs to be enclosed with quotation marks:

```
powershell.exe started --
    pid: 12428
    exe: C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe
    bundledModulesPath: C:\Users\Maksims Prieditis\.vscode\extensions\ms-vscode.PowerShell-0.7.0\modules
    args: C:\Users\Maksims Prieditis\.vscode\extensions\ms-vscode.PowerShell-0.7.0\scripts\Start-EditorServices.ps1 -EditorServicesVersion "0.7.0" -HostName "Visual Studio Code Host" -HostProfileId "Microsoft.VSCode" -HostVersion "0.7.0" -BundledModulesPath "C:\Users\Maksims Prieditis\.vscode\extensions\ms-vscode.PowerShell-0.7.0\modules" -LogLevel "Normal" -LogPath "C:\Users\Maksims Prieditis\.vscode\extensions\ms-vscode.PowerShell-0.7.0\logs\1471546041-EditorServices.log" 
```

**Comment by pl4x** [comment]
Same issue... after about 2 hours of debugging i finally decided to check out the bugs section.  Thanks for filing this, thanks for fixing this and thanks for the fix!

**Comment by daviwil** [comment]
Hey Andrew, sorry for the trouble, I'll definitely get this fixed soon!  Working on fixes for an upcoming 0.7.1 update right now.

**Comment by daviwil** [comment]
I just released an update to the extension, check it out and see if it resolve the issue for you!

**Comment by maksims-prieditis** [comment]
It works like a charm! Thank you!

**Comment by daviwil** [comment]
Excellent, thanks a lot for confirming!
