### ISSUE TITLE
MSI installation stalls with update PowerShell feature on Windows

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#2449]
When the update PowerShell feature is run on Windows from the VSCode PowerShell extension, the MSI will try and close all running PowerShell processes. When the PSIC/EditorServices is one of these processes, it will try and close it and sometimes gets stuck.

If you try to unblock the MSI by disposing of the PSIC (thus ending the PSES process), the MSI will silently disappear/crash.

**Comment by TylerLeonhardt** [comment]
This seems to be a PowerShell issue as I can repro this outside of the PowerShell extension. I've opened an issue over there:

https://github.com/PowerShell/PowerShell/issues/11796
