### ISSUE TITLE
Bundle the PowerShell extension

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#2450]
See https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by andschwa** [comment]
This is for the warning we get when we build the package:

> This extension consists of 973 files, out of which 477 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

And yes, it probably improve performance!
