### ISSUE TITLE
PowerShell checking extension, forever ?

### ISSUE THREAD

**Issue by SheepDomination** [PowerShell/vscode-powershell#2453]
I want to know why in the status bar is the PowerShell cycling, as if it's checking the extension and this goes on forever ?

**Comment by TylerLeonhardt** [comment]
Hi @SheepDomination - can you provide a gif or screenshot of what you're seeing? Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by rjmholt** [comment]
Hi @SheepDomination are you able to provide more details of what you’re experiencing? If you follow the issue template it will help you provide the information we need to understand your issue, like:

- your PowerShell extension version
- your VSCode version
- your PowerShell version
- your operating system name and version
- the behaviour you’re expecting
- the behaviour you’re experiencing
- possibly a screenshot/GIF of the issue

You might also want to take a look at [our troubleshooting doc](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md).

**Comment by SheepDomination** [comment]
@TylerLeonhardt Here is the screen shot, as well as the [logs](https://ln2.sync.com/dl/1d0dfd910/bj443mjr-brnzvjx9-v8m2fzhd-6n5d3gnh).
![powershell_rotatingsync](https://user-images.githubusercontent.com/6827459/73795467-ad751300-4778-11ea-859a-440d5cdd8f26.jpg)

@rjmholt 
PowerShell Extension - 2020.1.0
VSCode Version - 1.41.1
PowerShell version - 5.1.18362.145
Operating System - Windows10 1909

The behavior which I'm experiencing and expecting is for the rotating or what appears to be similar to that of a rotating sync, not to rotate continuously; and what is this behavior ?

**Comment by SydneyhSmith** [comment]
@SheepDomination we recently published an update to our [Preview Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) which has addressed a number of underlying architectural issues, would you mind giving it a try and letting us know if you are still hitting this issue?

**Comment by SheepDomination** [comment]
@SydneyhSmith I assume recently is the January 13, 2020 preview release of the PowerShell Preview ?

**Comment by SheepDomination** [comment]
Unfortunately as shown in my previous screen shot of the continuously cycling of Powershell still continues.

**Comment by SydneyhSmith** [comment]
@SheepDomination sorry to hear that you are still hitting this issue. What were you hoping to do when you hit this issue i.e. just starting the extension? debugging? formatting? thanks!

**Comment by SheepDomination** [comment]
I was hoping that the recycling PowerShell icon as seen in a previous screen shot would not be shown continuously ? 
What is the reason behind this to begin with ?

**Comment by SydneyhSmith** [comment]
@SheepDomination the "recycling PowerShell icon" means that a PowerShell script (could be coming from the extension or not) is running in the background...this can be triggered by any number of issues so it is difficult to pin point your specific issue without knowing what was going on beforehand, what were you running when it occurred? Had you just opened VSCode?

**Comment by SheepDomination** [comment]
When I'm in Bash or the command-line, the recycling PowerShell icon appears, but when I'm in a Powershell, the icon is not visible ?

**Comment by rjmholt** [comment]
@SheepDomination could you walk us through the steps from opening VSCode to having this issue? Ideally, if you're able to capture a GIF of going from startup to this behaviour, that would help us work out what's going on.

The little cycling icon is just there to indicate that the PowerShell process powering the PowerShell extension and the integrated console is running. When it sends a runspace state change notification indicating it's started to the client, it starts spinning. Then when the client gets another state change notification indicating it's stopped, it stops spinning. So it's entirely possible there's an issue there.

**But**, we won't be able to fix anything if we don't know what you're doing when you hit this issue.

**Comment by SheepDomination** [comment]
@rjmholt When switching between shells as seen in the video below; it is really odd, as you'll see when I use the word; _exit_, I can stop the powershell icon from spinning when and only when I'm in powershell. 

Although if I'm in the command-line shell and type powershell, the powershell cycling icon continues to spin ? If there is a way to access logs, that may be more helpful.

![powershell_cyclingIcon](https://user-images.githubusercontent.com/6827459/74801141-c23ac600-52a3-11ea-9da3-c48ef453df2d.gif)

**Comment by rjmholt** [comment]
> Although if I'm in the command-line shell and type powershell, the powershell cycling icon continues to spin 

Oh wait, are you in the integrated console and running `bash` or `powershell.exe` within it?

If so, then the PowerShell running spinner is very much expected. The PowerShell process driving the extension is busy, because you are synchronously running a command as a subprocess within it. PowerShell is busy running your command.

**Comment by SheepDomination** [comment]
> Oh wait, are you in the integrated console and running bash or powershell.exe within it?

Yes, the terminal in vscode. Oh, I see 👍

**Comment by rjmholt** [comment]
> Yes, the terminal in vscode

Ah! Yes, essentially the PowerShell pipeline/runspace is occupied running the command as a subprocess. As far as it's concerned, it's busy while you interact with the command as a subprocess. So this is intended behaviour, but even if it weren't I don't think we'd be able to change it; there's no way to tell the difference from PowerShell's perspective from an interactive `cmd` subprocess and a long-running non-interactive command like `chkdsk` or similar
