### ISSUE TITLE
2020.1.0-Preview - Terminal went all black after unlock from lock screen

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/vscode-powershell#2462]
## System info
* Windows 10 Enterprise 1909 18363.628
* VS Code 1.42.0
* Extension v2020.1.0-Preview
* PowerShell Core 7 rc 2 as default, used in this example

## Steps to reproduce
Not 100% reproducable.

* Do a lot of scripting in a PS1 file so that terminal has a lot of output
* Lock computer screen, go to the toilet, come back and all text is gone
* Try to get text to reappear, but you can't. Running more code, writing stuff in the terminal, nothing works.

![image](https://user-images.githubusercontent.com/6450056/74032360-0da3c900-49b4-11ea-8ab0-217ea258557c.png)

## Logs
* Can't find anything relevant in those. Will see if I can reproduce, and if I get get som logs for it later.

**Comment by rjmholt** [comment]
@o-l-a-v hsve you seen this behaviour at all with the ordinary non-integrated powershell console only VSCode?

I’ve actually noticed similar behaviour in PowerShell’s own Windows console when I move it between screens of different resolutions. I lose the prompt and cursor and there’s no suggestion that it responds to input. Sometimes I can get it back by resizing the window repeatedly.

**Comment by o-l-a-v** [comment]
I think it might be related to scaling, I've had other programs (ConnectWise Manage client) act wierd after unlocking after sleep mode.

**Comment by o-l-a-v** [comment]
Can't remember that I've managed to reproduce this in a long time (years), so I'll close it.
