### ISSUE TITLE
constructor of 'System.Windows.Window' ->binding constraints exception.

### ISSUE THREAD

**Issue by PeterHodges15** [PowerShell/vscode-powershell#2463]
Unzip this to c:\1\
Script Code:
$XamlRaw = (Get-Content "c:\1\TestXAML.XAML")
    $XamlRaw = $XamlRaw -replace 'mc:Ignorable="d"', '' -replace "x:N", 'N' -replace '^<Win.*', '<Window'
    $Xml = [Xml]$XamlRaw
    $reader = (New-Object System.Xml.XmlNodeReader $Xml)
    $XAMLWindow = $N
ull #Can only read once, else a ~Corrupted $XAMLWindow
    $XAMLWindow = [System.Windows.Markup.XamlReader]::Load($Reader) #Throws
Run it with PowerShell 5 and there is no error.
Run it in Powershell 7 (visual Studio Code) and you get:
Exception calling "Load" with "1" argument(s): "The invocation of the constructor on type 'System.Windows.Window' that matches the specified binding constraints threw an exception."

[TestXAML (2).zip](https://github.com/PowerShell/vscode-powershell/files/4174509/TestXAML.2.zip)

**Comment by TylerLeonhardt** [comment]
Hi @PeterHodges15

Does this reproduce outside of VS Code in PowerShell 7?

**Comment by rjmholt** [comment]
I believe this is the same issue in https://github.com/PowerShell/vscode-powershell/issues/2459, which is solved by changes in the preview extension, coming to stable this month
