### ISSUE TITLE
Debug adapter process has terminated unexpectedly for OS X

### ISSUE THREAD

**Issue by robbiepc30** [PowerShell/vscode-powershell#247]
I think this might be a bug of some sort. I downloaded the PowerShell that just came out for OS X v6.0.0-alpha.9 and updated the Visual studio code version to the latest 0.7.0. When I try to run simple script I get the following Error "Debug adapter process has terminated unexpectedly" if I press F5 or if I select a line and press F8 I get command I get error " 'PowerShell.RunSelection' not found"

under vscode/extensions/ms-vscode.PowerShell-0.7.0/logs the "DebugAdapterClient.log" is blank. the
PowerShell.log can be seen here https://gist.github.com/robbiepc30/38e6afca1f4ff6a63fa475a783473892

**Comment by daviwil** [comment]
Hey Robbie, thanks for sending your log file, that was helpful.  Judging from the error I think you may need to install OpenSSL using a tool like [Homebrew](http://brew.sh/):

```
brew install openssl
```

After installing OpenSSL you should be able to launch the extension successfully.

**Comment by robbiepc30** [comment]
Thanks! that did the trick

**Comment by daviwil** [comment]
Glad to hear it!  I'll have to add that to the documentation since I've heard this from another user as well.
