### ISSUE TITLE
Comment-based help is not shown in intellisense

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/vscode-powershell#2472]
Issue Type: <b>Bug</b>

1. Create a module in %PSMODULEPATH%.
1. Export a function from the module with some parameters.
1. Insert a comment-based help snippet and populate the fields.
1. Import the module in a different script.
1. Notice that tab completion works with the exported function, but no help synopsis/description is shown when hovering over the function call.

Extension version: 2019.5.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (2.95GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment]
Getting comment-based help directly from PowerShell source is not currently supported (and I'm not sure any other experiences support it either). Instead, we pick up module help from external help files, which you can generate from comment-based help with [platyPS](https://github.com/PowerShell/platyPS).

PowerShell itself doesn't do anything special to surface comment-based help, and it isn't recorded in a script AST. Instead, to support this, we would need to do extra work to sift through the tokens of a script file. Given this, I'll mark this feature request as up for grabs for now while we wait to see if others also want this feature.

**Comment by SeeminglyScience** [comment]
@chriskuech works for me, can you post a simple repro?  Remember to restart the session after adding the CBH as help content is cached per session.

Also if restarting the session doesn't work, check that your CBH is *inside* the function.  e.g.

```powershell
function Test-Function {
    <# cbh #>
    param()
}
```

instead of

```powershell
<# cbh #>
function Test-Function {
    param()
}
```

Not sure if it still matters, but there was a point where `FunctionDefinitionAst.GetHelpContent()` (which I believe is what `Get-Help`) would only work if the CBH was *inside* the function definition.

**Comment by staspk** [comment]
Yeah, neither version works for me either, in 2024. Even with the Powershell extension.

**Comment by JustinGrote** [comment]
@staspk works for me.
![image](https://github.com/user-attachments/assets/e39a718a-3d5b-4ac6-b854-19814652b7ed)

**Comment by staspk** [comment]
It has never worked for me. I'm not _100%_ sure what "has to be loaded into the current session" means, but it does _seem_ to be in the session, implied (I assume) by the intellisense tooltip showing the function name when hovering. Without Microsoft's Powershell extension, VsCode doesn't even do that.

![Image](https://github.com/user-attachments/assets/ab0fd425-384b-480c-b744-e704188f391a)

![Image](https://github.com/user-attachments/assets/8911b611-8fc3-4ee5-baf1-85b59385f7d2)

By the way, I've tried moving the comments into the function as you do in your example, and a plethora of other variations, in comment and function syntax. Multiple sessions, over this last half year, I've attempted to get this to work (this functionality works basically out-of-the-box for me in every other language). In the beginning, I assumed it's some stupid error on my part. I'm now convinced it's most likely a bug in the environment/runtime itself, judging by the amount of people complaining they can't get this to work online, without resolution.

If you have any other ideas on how to fix this, would love to hear them! Is there perhaps some specific message in the output window after an extension host restart to look for?

**Comment by JustinGrote** [comment]
It means the comment-based help won't show until `Get-Help Get-Test` shows it, which means you have to actually have it loaded into the `PowerShell Extension` terminal session by dot sourcing the script or just cut-pasting it in.

If you can see the help in `Get-Help your-command` in the `PowerShell Extension` terminal (not any pwsh terminal, that one specifically) but the hover still doesn't work for you, then we can investigate.

**Comment by staspk** [comment]
Thank you for your reply! I went ahead and followed your instructions...

So, it looks like copy-pasting the function into my PowerShell Extension terminal finally got it to work. Was the goal of the Powershell Extension devs that this process is somehow done automatically by the extension, or was it always assumed that the user would always setup this "linkage" on their own, perhaps by setting up a "profile" file for the Powershell Extension terminal where it dot-sources every powershell file you want used?

Dot-sourcing my module file: `". C:\Users\{username}\Documents\PowerShell\Kozubenko.Utils.psm1"` into the terminal doesn't work, by the way. Not sure what that could point at, in this context.

**Comment by JustinGrote** [comment]
@staspk dot sourcing all files in a repo is a huge risk. What if one of them is malicious? That's why it's not opt-in. This is the same behavior as ISE. Basically, when you get completion results in VSCode, it's just as if you hit ctrl-space or tab in the console. If it's not visible there, it won't be visible in vscode. This is consistent behavior. Hope that helps.

**Comment by mmcintyre123** [comment]
I came up with a [PowerShell profile for VSCode](https://gist.github.com/mmcintyre123/ac940364805200d35778bd62496f4508) that solves this issue in a genericized way. Please feel free to download and use or adapt it to your purposes! Read on for details!

## Workaround: Hover Help for Comment-Based Help in `.ps1` Scripts

The [VSCode PowerShell extension's](https://github.com/PowerShell/vscode-powershell) hover tooltips use `Get-Help`, which only works for functions loaded into the active session. Functions defined in `.ps1` script files don't get hover help unless you manually dot-source the script or paste them into the terminal. This workaround automatically loads all functions from `.ps1` files in your workspace and open editor tabs on session startup, so hover help and `Get-Help` work immediately. To refresh after editing doc blocks, restart the session with `Ctrl+Shift+P` → **PowerShell: Restart Session** (or use the optional keyboard shortcut below).

### What It Does

On session startup, it discovers `.ps1` files from **two sources**:

1. **Workspace scan** — recursively finds all `.ps1` files under `$pwd`
2. **Open editor tabs** — reads VS Code's internal `state.vscdb` (SQLite) to find `.ps1` files open in _any_ VS Code window, even files outside the workspace

For each file, it uses the **PowerShell AST** to extract function definitions and their preceding comment-based help blocks, then loads them into the global scope. The script body is never executed.

**Why both sources?** The workspace scan finds all `.ps1` files in your project — even ones you haven't opened. This provides hover help for functions that may be defined in utility script not currently open in your editor. The editor-tab scan catches `.ps1` files you've opened from _outside_ the workspace (e.g., your PowerShell profile, scripts in other directories). Together they give you complete IntelliSense coverage.

### Architecture

```
Import-WorkspaceFunctions              ← main entry point (also callable manually)
├── Get-WorkspacePS1Files              ← finds .ps1 files in the workspace
├── Get-VSCodeOpenPS1Files             ← finds .ps1 files open in VS Code editors
│   ├── Get-VSCodeStorageRoot          ← auto-detects Code vs Code Insiders
│   ├── Assert-PSSQLiteModule          ← validates PSSQLite is available
│   └── Get-EditorPathsFromStateDb     ← reads one state.vscdb for file paths
├── Import-FromFileList                ← deduplicates and imports from a file list
│   └── Import-FunctionsFromScript     ← loads functions from one .ps1 file
│       ├── Get-FunctionAsts           ← AST-parses a file for function nodes
│       └── Get-FunctionDefinitionText ← builds function text with help block
└── Write-ImportSummary                ← prints the colored result summary
```

### Setup

**1. Install the PSSQLite module** (needed to read VS Code's SQLite state database):

```powershell
Install-Module PSSQLite -Scope CurrentUser
```

**2. Save [`Microsoft.VSCode_profile.ps1`](https://gist.github.com/mmcintyre123/ac940364805200d35778bd62496f4508)** to your VS Code profile directory.

To find your profile path, run this in any PowerShell terminal:

```powershell
$PROFILE.CurrentUserCurrentHost
```

Save the file to the **same directory** as the path shown above, with the name `Microsoft.VSCode_profile.ps1`.

This is the VS Code-specific profile path — it loads automatically when the PowerShell Extension starts.

**3. Remove `-NoProfile`** from any custom terminal profiles in your `settings.json`, if present:

```json
"terminal.integrated.profiles.windows": {
    "PowerShell": {
        "args": ["-NoLogo"]  // make sure -NoProfile is NOT here
    }
}
```

**4. (Optional) Add a keyboard shortcut** to quickly restart the PowerShell session after editing doc blocks. Add this to your `keybindings.json`:

```json
{
   "key": "ctrl+shift+r",
   "command": "PowerShell.RestartSession",
   "when": "editorLangId == 'powershell'"
}
```

### Usage

-  **Hover tooltips** and **`Get-Help`** work immediately for all functions in your workspace and open `.ps1` files
-  After editing doc blocks or opening new `.ps1` files, refresh the powershell session with `Ctrl+Shift+R` (if you added the shortcut) or `Ctrl+Shift+P` → **PowerShell: Restart Session**
-  Run `Import-WorkspaceFunctions -Verbose` to see exactly which files and functions were loaded

### How This Addresses Concerns Raised in This Thread

| Concern                                                            | Raised By            | How This Solution Addresses It                                                                                                                                                                                                                                                                                                                |
| ------------------------------------------------------------------ | -------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Comment-based help not shown in hover                              | @chriskuech, @staspk | Functions are loaded into the session automatically on startup, so `Get-Help` and hover tooltips work immediately                                                                                                                                                                                                                             |
| "You have to load the function into your current session"          | @JustinGrote         | The profile does this automatically — no manual dot-sourcing or copy-pasting required                                                                                                                                                                                                                                                         |
| Having to manually dot-source or paste functions into the terminal | @staspk              | Fully automatic on session startup; just restart the session after edits                                                                                                                                                                                                                                                                      |
| Hard-coding paths / per-project configuration                      | @staspk              | Completely generic — scans the workspace directory and all open VS Code editor tabs with no project-specific config                                                                                                                                                                                                                           |
| **"Dot sourcing all files in a repo is a huge risk"**              | @JustinGrote         | **This solution avoids ever dot-sourcing anything.** It uses `[System.Management.Automation.Language.Parser]::ParseInput()` to extract only function definitions via the AST. The script body is never executed — only function definitions (and their help blocks) are loaded into scope. This is the same level of risk as `Import-Module`. |

### Why This Should Be Built-In...

The PowerShell extension's language server already parses open files for syntax highlighting, error detection, and symbol navigation. It should be able to provide hover help from comment-based help blocks in those same files without requiring them to be loaded into a runtime session. Other language servers (TypeScript, Python/Pylance, Go, etc.) all provide documentation-on-hover directly from source.
