### ISSUE TITLE
The language service could not be started

### ISSUE THREAD

**Issue by BartKlaasse** [PowerShell/vscode-powershell#2475]
### System Details
Windows 10 version 1903 build 18326.657
Extension: Powershell 2020.1.0

System Details Output
```
### VSCode version: 1.42.1 c47d83b293181d9be64f27ff093689e8e7aed054 x64

### VSCode extensions:
adrianwilczynski.asp-net-core-snippet-pack@1.50.2
ChakrounAnas.turbo-console-log@1.3.1
christian-kohler.npm-intellisense@1.3.0
christian-kohler.path-intellisense@1.4.2
CoenraadS.bracket-pair-colorizer@1.0.61
dariofuzinato.vue-peek@1.0.2
dbaeumer.vscode-eslint@2.0.15
eamodio.gitlens@10.2.1
ecmel.vscode-html-css@0.2.3
eg2.vscode-npm-script@0.3.11
esbenp.prettier-vscode@3.20.0
felixfbecker.php-intellisense@2.3.14
formulahendry.auto-close-tag@0.5.6
formulahendry.auto-rename-tag@0.1.1
formulahendry.code-runner@0.9.15
Fudge.auto-using@0.7.9
hnw.vscode-auto-open-markdown-preview@0.0.4
humao.rest-client@0.23.1
Leopotam.csharpfixformat@0.0.84
ms-vscode-remote.remote-wsl@0.42.3
ms-vscode.csharp@1.21.11
ms-vscode.powershell@2020.1.0
ms-vsliveshare.vsliveshare@1.0.1615
mubaidr.vuejs-extension-pack@1.1.5
octref.vetur@0.23.0
ritwickdey.LiveServer@5.6.1
robertoachar.vscode-essentials-snippets@2.0.0
Shan.code-settings-sync@3.4.3
tombonnike.vscode-status-bar-format-toggle@2.0.0
xabikos.JavaScriptSnippets@1.7.2


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with the language service.

#### Expected Behaviour

As soon as i open a powershell file in vscode the language service should be started

#### Actual Behaviour

I get a error message saying: The language service could not be started. it show the following output in the integrated console: 

18/02/2020 10:35:50 [NORMAL] - Language server starting --
18/02/2020 10:35:50 [NORMAL] -     args: c:\Users\BART_\.vscode\extensions\ms-vscode.powershell-2020.1.0\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.1.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\BART_\.vscode\extensions\ms-vscode.powershell-2020.1.0\modules' -EnableConsoleRepl -LogLevel 'Diagnostic' -LogPath 'c:\Users\BART_\.vscode\extensions\ms-vscode.powershell-2020.1.0\logs\1582018550-a8ff2b07-3a80-45a0-99d4-e67b922c72621582018198413\EditorServices.log' -SessionDetailsPath 'c:\Users\BART_\.vscode\extensions\ms-vscode.powershell-2020.1.0\sessions\PSES-VSCode-16024-604405' -FeatureFlags @()
18/02/2020 10:35:50 [NORMAL] -     exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
18/02/2020 10:35:50 [NORMAL] - powershell.exe started, pid: 14776
18/02/2020 10:35:52 [NORMAL] - powershell.exe terminated or terminal UI was closed
18/02/2020 10:37:50 [NORMAL] - Language server startup failed.
18/02/2020 10:37:50 [ERROR] - The language service could not be started: 
18/02/2020 10:37:50 [ERROR] - Timed out waiting for session file to appear.

after configuring the log level to diagnostics in vscode preferences it shows the following error multiple times

```
PS>TerminatingError(Write-Verbose): "Cannot process command because of one or more missing mandatory parameters: Message."
Write-Verbose : Cannot process command because of one or more missing mandatory parameters: Message.
At C:\Users\BART_\.vscode\extensions\ms-vscode.powershell-2020.1.0\modules\PowerShellEditorServices\Start-EditorServices
.ps1:124 char:12
+     $msg | Write-Verbose
+            ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-Verbose], ParameterBindingException
    + FullyQualifiedErrorId : MissingMandatoryParameter,Write-Verbose
```

I tried switching from powershell x64 to x86 without any result.
Also tried using the powershell preview extension with the normal powershell extension disabled. 

### Attached Logs
[vslog.zip](https://github.com/PowerShell/vscode-powershell/files/4218534/vslog.zip)

**Comment by rjmholt** [comment]
Interesting that that error looks fairly basic but we've never seen it reported before.

In the `powershell-preview` extension, we've rewritten the startup logic to not use a PowerShell script at all, so this likely doesn't occur there. So it might be worth trying that out (you'll need to install the `powershell` extension).

The next release of the `powershell` extension will be using that, so it would be good if you can try that and let us know if that works.

**Comment by BartKlaasse** [comment]
Switching to preview seems to fix the issue indeed... When i tried Switching about a week or two ago it didnt...

I guess ill be using the preview untill the next release
