### ISSUE TITLE
Stuck at starting powershell

### ISSUE THREAD

**Issue by kizzle911** [PowerShell/vscode-powershell#2480]
Issue Type: <b>Bug</b>

Unable to start powershell in VSCode's terminal session.  Stuck at "Starting Powershell".

Extension version: 2020.1.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 7, 4|
|Memory (System)|16.00GB (1.50GB free)|
|Process Argv|-psn_0_18317687|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment]
Hi @kizzle911, thanks for opening an issue.

We'll need some more information to have a chance of diagnosing your issue. In particular:

- Are you using the `powershell` or the `powershell-preview` extension?
- Please have a read through the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) and send through your logs
- Have you been able to start the extension before? Has anything on your system changed recently (OS update, VSCode update, extension update)?
- If you're running the `powershell` extension, can you try running the `powershell-preview` extension instead and reporting on the result?

**Comment by kizzle911** [comment]
Hi @rjmholt,

1) I was using powershell extension but now I switched to powershell-preview extension, and still noticing the same issue.
2) 
[Archive.zip](https://github.com/PowerShell/vscode-powershell/files/4226230/Archive.zip)

3) I believe there was a VSCode update and possible a powershell extension update.

Here's the current error message:
2/19/2020 11:57:15 AM [ERROR] - Timed out waiting for session file to appear.
2/19/2020 11:57:15 AM [ERROR] - The language service could not be started:

**Comment by rjmholt** [comment]
It's timing out because, for some reason, the backend PowerShell process isn't starting. Normally the invocation you see at the top of the log files will start a PowerShell process which fires a command and launches PowerShell Editor Services, which should write a new log out into a different file right next to the ones you've uploaded.

I'm assuming you've got PowerShell installed and can run it? Is there any lockdown, antivirus or security solution installed on your machine (less common on macOS, but on Windows this can seriously interfere with startup)?

What happens if you try to run this from a terminal:

```
/usr/local/bin/pwsh -NoProfile -NonInteractive -EncodedCommand SQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgACcALwBVAHMAZQByAHMALwBrAHMAYQBsAGcAYQBkAG8ALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtAHAAcgBlAHYAaQBlAHcALQAyADAAMgAwAC4AMQAuADAALwBtAG8AZAB1AGwAZQBzAC8AUABvAHcAZQByAFMAaABlAGwAbABFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALwBQAG8AdwBlAHIAUwBoAGUAbABsAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAuAHAAcwBkADEAJwA7ACAAUwB0AGEAcgB0AC0ARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzACAALQBIAG8AcwB0AE4AYQBtAGUAIAAnAFYAaQBzAHUAYQBsACAAUwB0AHUAZABpAG8AIABDAG8AZABlACAASABvAHMAdAAnACAALQBIAG8AcwB0AFAAcgBvAGYAaQBsAGUASQBkACAAJwBNAGkAYwByAG8AcwBvAGYAdAAuAFYAUwBDAG8AZABlACcAIAAtAEgAbwBzAHQAVgBlAHIAcwBpAG8AbgAgACcAMgAwADIAMAAuADEALgAwACcAIAAtAEEAZABkAGkAdABpAG8AbgBhAGwATQBvAGQAdQBsAGUAcwAgAEAAKAAnAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC4AVgBTAEMAbwBkAGUAJwApACAALQBCAHUAbgBkAGwAZQBkAE0AbwBkAHUAbABlAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBrAHMAYQBsAGcAYQBkAG8ALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtAHAAcgBlAHYAaQBlAHcALQAyADAAMgAwAC4AMQAuADAALwBtAG8AZAB1AGwAZQBzACcAIAAtAEUAbgBhAGIAbABlAEMAbwBuAHMAbwBsAGUAUgBlAHAAbAAgAC0ATABvAGcATABlAHYAZQBsACAAJwBEAGkAYQBnAG4AbwBzAHQAaQBjACcAIAAtAEwAbwBnAFAAYQB0AGgAIAAnAC8AVQBzAGUAcgBzAC8AawBzAGEAbABnAGEAZABvAC8ALgB2AHMAYwBvAGQAZQAvAGUAeAB0AGUAbgBzAGkAbwBuAHMALwBtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALQBwAHIAZQB2AGkAZQB3AC0AMgAwADIAMAAuADEALgAwAC8AbABvAGcAcwAvADEANQA4ADIAMQAzADEAMwAxADUALQA5ADEAYwA5ADYAMAA4ADcALQA4AGYAYQBjAC0ANAA4AGIAZQAtADkAZQA1ADAALQA4ADQAYgBhADMAZQA5AGUAOQAwAGMAMQAxADUAOAAyADEAMwAwADcAMgAyADcAMQAxAC8ARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC4AbABvAGcAJwAgAC0AUwBlAHMAcwBpAG8AbgBEAGUAdABhAGkAbABzAFAAYQB0AGgAIAAnAC8AVQBzAGUAcgBzAC8AawBzAGEAbABnAGEAZABvAC8ALgB2AHMAYwBvAGQAZQAvAGUAeAB0AGUAbgBzAGkAbwBuAHMALwBtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALQBwAHIAZQB2AGkAZQB3AC0AMgAwADIAMAAuADEALgAwAC8AcwBlAHMAcwBpAG8AbgBzAC8AUABTAEUAUwAtAFYAUwBDAG8AZABlAC0AOQAxADAAMgAxAC0AMwAzADEANgA4ADEAJwAgAC0ARgBlAGEAdAB1AHIAZQBGAGwAYQBnAHMAIABAACgAKQAgAA==
```

**Comment by rjmholt** [comment]
Another relevant recurrence from the logs is this:

> 2/19/2020 11:55:16 AM [NORMAL] - powershell.exe started, pid: 92498
> 2/19/2020 11:55:17 AM [NORMAL] - powershell.exe terminated or terminal UI was closed

So it looks like it's able to start a process, but that process crashes for some reason. If you're able to try that command, hopefully it crashes in the same way and we can study the error message. The first thing we do on startup is log, so it sounds like it's happening quite early.

**Comment by kizzle911** [comment]
I get the following message when I attempt the above: 

Import-Module : Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
At line:1 char:1
+ Import-Module '/Users/ks/.vscode/extensions/ms-vscode.powershel ...

+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Start-EditorServices : The term 'Start-EditorServices' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:154
+ ... Services/PowerShellEditorServices.psd1'; Start-EditorServices -HostNa ...

+ CategoryInfo          : ObjectNotFound: (Start-EditorServices:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by rjmholt** [comment]
Ah interesting, what's the output of `$PSVersionTable` in `/usr/local/bin/pwsh`?

**Comment by kizzle911** [comment]
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.2                                                                                   
PSEdition                      Core                                                                                    
GitCommitId                    v6.0.2                                                                                  
OS                             Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-61...
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0

**Comment by rjmholt** [comment]
> 6.0.2 

Ah! If you upgrade to 6.2.4 or 7.0.0-rc.2, you should no longer experience this issue.

6.0.2 went out of support on Jul 20, 2018. This error is caused by a mismatch between the .NET version it uses and the version we compile against since we target the lowest supported version (Unfortunately there's no way I can find the improve the error reporting here &mdash; it happens before our code runs in-process and VSCode doesn't give us any options to collect the error message from the process). You can find the PowerShell support lifecycle [here](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7).

**Comment by kizzle911** [comment]
@rjmholt  - You're totally right.  Upgrading the PS version to 6.2.4 did the trick.

Thank you.
