### ISSUE TITLE
Path is lost in console PSReadLine

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2487]
Issue Description
=====

I am experiencing a problem with... PSReadline. In the last preview release, you've fixed the output in the console and it's much better experience now. 

However, there is still the last thing to fix. If you run code that doesn't return anything straight after starting VSCode it will lose the path.

```powershell
function Test {

}
```   

![image](https://user-images.githubusercontent.com/15063294/75092815-ecc6a080-557b-11ea-90b0-ade1d32e23dc.png)

If you modify the code a bit and try the same it will fail for few first tries and then starts working. 

```powershell
function Test {
    write-host 'test'
}

Test
```

![image](https://user-images.githubusercontent.com/15063294/75092839-2dbeb500-557c-11ea-98c9-baccee62f135.png)

I am not sure what could be an issue here. Initially, I thought it works for one and doesn't work for the other but it seems it's some kind of delay.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.42.1|
| PowerShell Extension Version | 2020.2.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.628|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.628|
|BuildVersion|10.0.18362.628|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|code-settings-sync|Shan|3.4.3|
|codesnap|adpyke|1.0.27|
|excel-to-markdown-table|csholmq|1.2.0|
|gistfs|vsls-contrib|0.0.55|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.1|
|html-preview-vscode|george-alisson|0.2.5|
|markdown-all-in-one|yzhang|2.7.0|
|markdown-preview-enhanced|shd101wyy|0.5.2|
|markdown-shortcuts|mdickin|0.12.0|
|material-icon-theme|PKief|3.9.3|
|pdf|tomoki1207|0.5.1|
|powershell-preview|ms-vscode|2020.2.0|
|project-manager|alefragnani|10.10.0|
|reg|ionutvmi|1.0.1|
|theme-monokai-pro-vscode|monokai|1.1.15|
|vscode-html-css|ecmel|0.2.3|
|vscode-markdownlint|DavidAnson|0.34.0|
|vscode-pull-request-github|GitHub|0.14.0|
|vscode-toggle-quotes|BriteSnow|0.3.2|
|vscode-versionlens|pflannery|0.24.0|
|vscode-wakatime|WakaTime|2.3.1|
|vscode-yaml|redhat|0.7.2|
|xml|DotJoshJohnson|2.5.0|

**Comment by SydneyhSmith** [comment]
@PrzemyslawKlys thanks for reporting this, we are able to reproduce the issue...since there is a work-around (hitting "enter") for this it is not our highest priority but we still hope to fix it when possible

**Comment by andschwa** [comment]
Hey @PrzemyslawKlys, is this still in an issue with the latest preview?

**Comment by PrzemyslawKlys** [comment]
No longer a problem 🥳
