### ISSUE TITLE
[Preview-2020.2.0] F5 works only once

### ISSUE THREAD

**Issue by ili101** [PowerShell/vscode-powershell#2488]
Issue Type: <b>Bug</b>

#### Setup:
Preview-2020.2.0 + PS7
(Do not create launch.json)
#### Steps to reproduce:
1. F5 (file will run)
2. F5 (debugger will start and do nothing)

![F5](https://user-images.githubusercontent.com/6960531/75121077-67391280-5699-11ea-8034-5a6b192b3755.gif)
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4242519/EditorServices.log)
Extension version: 2020.2.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|4.00GB (1.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by TylerLeonhardt** [comment]
@ili101 do you have any workspace open?

**Comment by ili101** [comment]
It happens with and without workspace.
I tested it only on windows.
Hitting enter or Ctrl+C between F5s actually prevent the problem.
Maybe another clue after the second F5 if I F6 to pause it stops on a temporary script with only `0` in it.

**Comment by TylerLeonhardt** [comment]
That's really great information @ili101. Thank you!

**Comment by TylerLeonhardt** [comment]
I was unable to repro this on Windows, however, I did reproduce this on @SydneyhSmith 's machine.

It seems to happen when a machine is totally bogged down and so the PowerShell extension runs very slowly and gets into some bad state.

Still investigating...

**Comment by TylerLeonhardt** [comment]
I'm able to reproduce when I comment out my personal changes to the `prompt` function.

**Comment by rjmholt** [comment]
This seems to have the same root cause as https://github.com/PowerShell/vscode-powershell/issues/2364

**Comment by DarkLite1** [comment]
I think I'm having the same issue. The code never finishes execution and the debug pop-up at the top stays. Quitting it is not always possible, so I'm forced to kill the terminal and restart it. It might be related but code unfolding is also no longer possible in some cases. Thank you for looking in to this nasty little bug.
