### ISSUE TITLE
Editor no longer uses ambient PSModulePath when launched from command line

### ISSUE THREAD

**Issue by chrisvanderpennen** [PowerShell/vscode-powershell#249]
I've got a DSC project set up that includes a folder for modules intended to be packed and deployed to a pull server, including some custom ones for our own software.  I created a small script, to the effect of:

```
$env:PSModulePath = (Resolve-Path './src/modules') + ';' + $env:PSModulePath
code .
```

in the project root, which until recently launched VS Code and provided completion over the DSC resources in `./src/modules`.

As of 0.7.0, this no longer works. Code launches, but code analysis reports an error resolving any of the modules in `./src/modules` for `Import-DscResource` and executing `$env:PSModulePath` as a selection shows the system default module path.

Any ideas on how I can restore this functionality?

**Comment by chrisvanderpennen** [comment]
I just tried `"powershell.enableProfileLoading": false`, didn't help.

**Comment by rkeithhill** [comment]
You can create a profile called `Microsoft.VSCode_profile.ps1` and configure $env:PSModulePath in there plus set `"powershell.enableProfileLoading": true`.   That should work on 0.7.0.

**Comment by chrisvanderpennen** [comment]
Great, that worked.  Thanks!

I've just tinkered with making the PS host name configurable so you can load a project-specific profile, would you like me to open a pull request?

**Comment by daviwil** [comment]
I think we're actually looking at a different way to accomplish this through an additional settings parameter in the project's settings.json file.  Definitely would be interested in a PR for that!  If you want, we can discuss this a little bit more before you get started.

**Comment by daviwil** [comment]
Oh, and regarding the initial issue, we've changed the way that we launch our language service using a new instance of PowerShell.exe so maybe the context doesn't get carried across anymore.  I'll look into it a bit more to understand the core issue.

**Comment by rkeithhill** [comment]
@daviwil I looked briefly at how we use child_proces.spawn() and it would appear that the child processes are supposed to inherent the env block.  So the env var should have been defined in the PowerShell process.  With ProcExp I do see it defined in some of the various code.exe instances.  

Man, why does it load so many code.exe processes when I only have one editor instance open?

**Comment by daviwil** [comment]
Yeah, the problem is that VS Code is launching their plugin hosts in child processes and apparently those don't always inherit the env variables without Code doing some extra work.  This has actually caused a problem in VS Code running on Linux because Electron there is more strict about env var inheritance for some weird reason.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
