### ISSUE TITLE
Command filter hides helpful shortcuts

### ISSUE THREAD

**Issue by rrmistry** [PowerShell/vscode-powershell#2497]
# Summary
![PowerShellFilterBug](https://user-images.githubusercontent.com/25514145/75272725-72408f80-57cc-11ea-9f26-72bc72526bdd.gif)

### System Details

System Details Output
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with the user interface. The filter on PowerShell commands is extremely useful to have. But the filter overlaps the first row of commands and I can't click on the `"Get Help for Command"` or the `"Insert Command"` shortcuts.

#### Expected Behaviour

Don't hide the shortcuts on the first row.

Would be nice to have padding above the first row if filter applied.

Similar to VS code find-and-replace functionality:
![PowerShellFilterBugSolution](https://user-images.githubusercontent.com/25514145/75273284-5807b100-57ce-11ea-952f-4bff0e9faf4b.gif)

#### Actual Behaviour

Hides helpful shortcuts on first row of commands after filter is applied.

### Attached Logs

Not Applicable

**Comment by SydneyhSmith** [comment]
@rrmistry thanks for reporting this, it looks like this is a UI issue that come from VSCode, please open an issue in their repo. Thanks
