### ISSUE TITLE
Use new language status items API for status bar info

### ISSUE THREAD

**Issue by Tyriar** [PowerShell/vscode-powershell#2499]
PowerShell uses the very right of the right status bar to show both initializing and version number:

![image](https://user-images.githubusercontent.com/2193314/75381461-a16b0580-588d-11ea-94b3-f5f086a2922c.png)

![image](https://user-images.githubusercontent.com/2193314/75381440-97490700-588d-11ea-977c-82ce5764fc6e.png)

This is bad since it makes the status bar unstable; all items left of the PS item will shift to the left and again to the right. I suggest aligning with the TS extension and show the initializing item on the right side of the left status bar:

![image](https://user-images.githubusercontent.com/2193314/75381557-ca8b9600-588d-11ea-8cdb-24ea290b2a43.png)

![image](https://user-images.githubusercontent.com/2193314/75381573-d24b3a80-588d-11ea-99ca-4769571e890a.png)

Also getting closer to the wording of the TS extension might be a good idea; "Initializing PS language features" or "Initializing PS session" (no "...")?

Related: https://github.com/PowerShell/vscode-powershell/issues/2436

**Comment by andschwa** [comment]
While I want to say we should wait on https://github.com/microsoft/vscode/issues/129037, it will be long between that being finalized, implemented, and then subsequently stabilized such that we can drop all the old code that I think we _should_ at least improve the existing code somewhat and fix this issue.

**Comment by andschwa** [comment]
Yay, the new awesome new [API](https://code.visualstudio.com/updates/v1_65#_language-status-items) is out!

**Comment by andschwa** [comment]
It took a while, but we got it! Thanks @Tyriar.
