### ISSUE TITLE
Command and argument completions should cycle when Tab is pressed

### ISSUE THREAD

**Issue by Satak** [PowerShell/vscode-powershell#25]
Tab completion doesn't work for anything (enum, validate set, parameters). It should work like in ISE so you could tab complete your enum sets and validate sets as arguments, parameters for functions and commands.

**Comment by daviwil** [comment]
It should work for any of these things because we're using the same PowerShell APIs to get the completion lists.  Are you getting IntelliSense suggestions for cmdlets that you're typing?  Can you give me a specific example that I can try?  What version of Windows and PowerShell are you using?

**Comment by Satak** [comment]
Make a function with parameter set in parameter 
function Get-Item 
{
	Param(
		[ValidateSet('one','two')]
		[string]$arg
	)
	return $arg
}

Get-Item -arg <**here if you try to tab it doesn't cycle through the validate set 'one' 'two' it just makes tab space** >

**Comment by daviwil** [comment]
This currently works in VS Code with the PowerShell extension installed, you just have to hit `Ctrl+Space` or start typing one of the values to get the completion:

![image](https://cloud.githubusercontent.com/assets/79405/11374973/acd01304-928d-11e5-90cf-25d2de215e64.png)

Does that work for you if you try it?

If the request is that the completion suggestions should immediately pop up without any keypress other than 'space', we can file that request against the VS Code team.

**Comment by Satak** [comment]
Here is a video how much worse the tab completion is compared to ISE:
https://youtu.be/TPNLdsMg3j4

Ctrl + Space works but then it opens that menu and you have to use arrow up and down on the list, you can't tab cycle through it.

**Comment by daviwil** [comment]
Thanks, this video is helpful and demonstrates what you're looking for really well.  I'll look into how this might be possible.

**Comment by Satak** [comment]
There are also lot of problem when dealing with Classes. Static methods are not listed even with Ctrl + Space it shows nothing. Public methods are listed but when you select it, it clears your variable name. See the video: https://youtu.be/GbbemOOiDnQ

**Comment by daviwil** [comment]
Yep, there are a couple issues around this already:

https://github.com/PowerShell/vscode-powershell/issues/12
https://github.com/PowerShell/PowerShellEditorServices/issues/45

Can you post your example file in a Gist somewhere?  It'd be useful for testing.

Thanks!

**Comment by pcgeek86** [comment]
I was about to report this issue, but searched for "values" first, and came across this thread. I'm not seeing auto-completion for parameter values for the `New-AzureRmStorageAccount -Type` parameter.

![image](https://cloud.githubusercontent.com/assets/466713/14712173/5c77ae68-0799-11e6-9e76-d1cc9a718ed7.png)

In the PowerShell ISE, it would look like this:

![image](https://cloud.githubusercontent.com/assets/466713/14712195/742655be-0799-11e6-8ac6-326031335c06.png)

**Comment by rkeithhill** [comment]
Is the completion list correct if you remove `@StorageAccount` (or move it after -Type)?  Just wondering if splatting is confusing auto-completion in this case.

**Comment by pcgeek86** [comment]
@rkeithhill 

I doubt it. It works alright in the ISE.

![image](https://cloud.githubusercontent.com/assets/466713/14714275/a31291a0-07a1-11e6-8345-d51c0b2f9597.png)

Still broken, even without Splatting.

![image](https://cloud.githubusercontent.com/assets/466713/14714308/c00a0c98-07a1-11e6-9b18-2bff9bd18f5a.png)

Good thought though! Thanks

**Comment by rkeithhill** [comment]
@pcgeek86 Thanks for that extra info.

**Comment by mpriem** [comment]
Would love to hear the latest on this one! Any chance of this getting addressed?

**Comment by pcgeek86** [comment]
Closing, as this currently works. Please comment if there's something specific that isn't working, and we'll reopen it.

![vscode-autocomplete-githubissue25](https://user-images.githubusercontent.com/466713/27257887-90624a02-539d-11e7-9b1e-12623e1ce0a0.gif)

**Comment by daviwil** [comment]
I think what Sami was asking for was the ISE's behavior of cycling through completions when you hit tab, like this:

![012a64b3-8fa4-4d7f-bfa6-892494b9ed25](https://user-images.githubusercontent.com/79405/27262214-f96450b8-5406-11e7-875c-62967f2495b3.GIF)

I think we can certainly provide that behavior, just haven't had time to look into it recently.

**Comment by pcgeek86** [comment]
Gotcha. I was looking at the original request, not the follow-on comments.

It looks like the original request was for any type of tab completion, which works for parameters, parameter values, functions, etc.

**Comment by kapilmb** [comment]
I think a very simple fix would be rebind `selectNextSuggestion` and `selectPrevSuggestion` actions to `tab` and `shift+tab` keys. This will not give a complete parity with the ISE behavior but the user will be able to tab through the suggestions instead of using the up/down arrow keys.

**Comment by daviwil** [comment]
I think we could make the ISE-style completion work with a general rebind of Tab and a new request to the language server, should be fairly straightforward.  I'll take a look at it next month sometime.

**Comment by aarontheadmin** [comment]
In relation to the original post, when you backspace a command, parameter, or argument, and try tab completion, it doesn't complete - just inserts a tab character, making you manually type it in. This happens in the script editor pane, whereas the Integrated Terminal does not have this problem.

**Comment by 0-0-1-0-1-0-1-0** [comment]
@daviwil Has there been any progress on this? It would be nice to have a setting to choose the type of tab completion you want, ISE style or current style.

I prefer the ISE style as it cycles cmdlets, variables, classes, argument lists etc...

**Comment by rjmholt** [comment]
@SeeminglyScience were you discussing this recently in Slack? Possibly with @Jaykul?

**Comment by SeeminglyScience** [comment]
Yeah, with @Jaykul and @0-0-1-0-1-0-1-0 actually.

My thoughts on this is that it shouldn't come from us.  In order to implement this we would need to essentially rewrite all of the intellisense logic that VSCode already provides.  That would be a rather hefty initial chunk of work, a entire new system to maintain, and would pretty drastically change the experience of using this extension vs other language extensions.

If it this change would come from somewhere, it should come from VSCode itself.  That said, the ISE-style doesn't really make sense in an editor, and only really made sense at the time because it was trying to emulate the pre-PSReadLine console experience.

I do understand the frustration, and I went through the same thing when I switched over to VSCode.  I'd personally recommend to those who are having issues to give the current system a try long enough for your muscle memory to switch.  Once you get used to using <kbd>CTRL+SPACE</kbd> to bring up the list of completions, you may find that it's faster and a bit less strenuous on the fingers.  PSReadLine has a similar option (even with tooltips in later versions!) also bound to <kbd>CTRL+SPACE</kbd>, so your muscle memory should translate in the console as well.

**Comment by rjmholt** [comment]
@0-0-1-0-1-0-1-0 given the fact that completion UX essentially happens at VSCode's layer, it might be worth opening an issue on VSCode itself. Building and maintaining a second completion stack would represent a pretty big resource drain for us

**Comment by MartinGC94** [comment]
This feature was recently implemented as an option in VS code: "editor.tabCompletion": "on"
More details here: https://github.com/Microsoft/vscode/issues/28215#issuecomment-422310232 So I guess this issue can be closed now.

**Comment by rjmholt** [comment]
@MartinGC94 Thanks for that info -- really great news! Closing this issue -- if there are outstanding issues in the experience (i.e. there are missing functionalities) we can reopen.
