### ISSUE TITLE
Debug command/abort race condition causes bad state in PSES

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#2508]
From https://github.com/PowerShell/PowerShellEditorServices/pull/1210.

While https://github.com/PowerShell/PowerShellEditorServices/pull/1210 patches this, it is likely to not be enough to fully prevent the issues occurring here.

Instead we need to sift through the interaction between the debugger, PSReadLine and the PowerShellContextService to ensure that our internal conceptual state machine makes sense and that the way multiple threads interact with the state of PowerShell is sensible and well-defined.

**Comment by andschwa** [comment]
I'm going to move this to the Editor Services Pipeline project, as that's really the meat of this issue.
