### ISSUE TITLE
Periodically my whole screen goes black

### ISSUE THREAD

**Issue by RoscoeT** [PowerShell/vscode-powershell#2519]
Issue Description
=====
While using VsCode periodically my whole screen goes black for a few seconds, except for the mouse pointer. It did not do this prior to updating to Version: 1.42.1 using ms-vscode.powershell-2020.1.0.
I see several errors in the logs which I will attach. 
Since I use code in a Windows 10 VM in virutal box I tries starting it with the command line switch --disable-gpu and this had no change.

Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
ms-vscode.powershell-2020.1.0

Attached Logs
=====

```
abstractExtensionService.ts:400 [ms-vscode.powershell]: Command `workbench.action.debug.start` appears multiple times in the `commands` section.
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'callback' of undefined
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'callback' of undefined	at c:\Users\username\.vscode\extensions\ms-vscode.powershell-2020.1.0\out\src\session.js:568:52
t.log @ console.ts:137
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'callback' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'callback' of undefined
	at c:\Users\username\.vscode\extensions\ms-vscode.powershell-2020.1.0\out\src\session.js:568:52
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'callback' of undefined
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'callback' of undefined	at c:\Users\username\.vscode\extensions\ms-vscode.powershell-2020.1.0\out\src\session.js:568:52
t.log @ console.ts:137
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'callback' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'callback' of undefined
	at c:\Users\username\.vscode\extensions\ms-vscode.powershell-2020.1.0\out\src\session.js:568:52
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'callback' of undefined
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'callback' of undefined	at c:\Users\username\.vscode\extensions\ms-vscode.powershell-2020.1.0\out\src\session.js:568:52
t.log @ console.ts:137
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'callback' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'callback' of undefined
	at c:\Users\username\.vscode\extensions\ms-vscode.powershell-2020.1.0\out\src\session.js:568:52
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
```

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.42.1|
| PowerShell Extension Version | 2020.1.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.628|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.628|
|BuildVersion|10.0.18362.628|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

|Extension|Author|Version|
|---|---|---|
|markdown-preview-github-styles|bierner|0.1.6|
|powershell|ms-vscode|2020.1.0|
|remote-ssh|ms-vscode-remote|0.49.0|
|remote-ssh-edit|ms-vscode-remote|0.49.0|
|remote-wsl|ms-vscode-remote|0.42.3|
|shell-launcher|Tyriar|0.4.1|

**Comment by rjmholt** [comment]
Hi @RoscoeT does VSCode do this if you uninstall the PowerShell extension?

**Comment by RoscoeT** [comment]
TBH I'm not 100% sure if the screen blacking out is linked to vscode or not but the errors exist regardless. It does seem to only happen when i am using vscode. And only started after updating vscode.
The errors mentioned are all related to the PowerShell extension so I don't imagine they would not persist if I were to uninstall. Sorry I don't know how to reproduce the issue as it just seems to happen randomly.

**Comment by SydneyhSmith** [comment]
Given that the screen blacking out is not at our abstraction layer, and is likely unrelated to other errors you may be experiencing, I am going to close this issue for now (happy to re-open if you have more re-pro info)
