### ISSUE TITLE
Using Windows Forms Unexpected behaviour and errors

### ISSUE THREAD

**Issue by DanteNahuel** [PowerShell/vscode-powershell#2520]
System Details Output
```
### VSCode extensions:
eamodio.gitlens@10.2.1
ms-vscode.powershell@2020.1.0
ms-vscode.powershell-preview@2020.2.0    
msazurermtools.azurerm-vscode-tools@0.8.4


### PSES version: 1.13.3.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

When trying to use Windows Forms in a Powershell script I get errors that I don't get when running the same script/lines in Powershell ISE or Powershell 7 console

#### Expected Behaviour

Running this:
```
# Init PowerShell Gui
Add-Type -AssemblyName System.Windows.Forms

# Create a new form
$LocalPrinterForm                    = New-Object system.Windows.Forms.Form

# Define the size, title and background color
$LocalPrinterForm.ClientSize         = '500,300'
$LocalPrinterForm.text               = "LazyAdmin - PowerShell GUI Example"
$LocalPrinterForm.BackColor          = "#ffffff"

# Display the form
[void]$LocalPrinterForm.ShowDialog()
```
Should run smoothly without any errors.

#### Actual Behaviour

However, I get the following errors:
```

SetValueInvocationException:
Line |
   8 |  $LocalPrinterForm.ClientSize         = '500,300'
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "ClientSize": "Cannot convert the "500,300" value of type "System.String" to type "System.Drawing.Size"."

SetValueInvocationException:
Line |
  10 |  $LocalPrinterForm.BackColor          = "#ffffff"
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "BackColor": "Cannot convert the "#ffffff" value of type "System.String" to type "System.Drawing.Color"."
```

I get it to work with the following changes :
```
$LocalForm.ClientSize         = New-Object System.Drawing.Size(500,300)
$LocalForm.text               = "Azure VM Decommission"
$LocalForm.BackColor          = [System.Drawing.Color]::White

```

Notice that if I tried to use:
`$LocalForm.BackColor          = New-Object System.Drawing.Color("White")
`
I would get:
` A constructor was not found. Cannot find an appropriate constructor for type System.Drawing.Color.`

So I had to use
`$LocalForm.BackColor          = [System.Drawing.Color]::White`

The same code works fine without any errors in PowerShell, Powershell ISE and Powershell 7

**Comment by rjmholt** [comment]
Hi @DanteNahuel, can you give us:

- a small reproduction of the issue
- a description of your expected behaviour
- a description of the actual behaviour

**Comment by rjmholt** [comment]
Did the issue resolve? If so what was the resolution? (Even if it's a small thing, it might help another user)

**Comment by DanteNahuel** [comment]
@rjmholt I closed it because I'm able to reproduce it in Powershell 7 console as well, so I'm guessing this is not Visual Code related.
