### ISSUE TITLE
Ubiquitous parameters don't always auto-complete

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#2521]
### System Details

System Details Output
```
### VSCode version: 1.42.1 c47d83b293181d9be64f27ff093689e8e7aed054 x64

### VSCode extensions:
abusaidm.html-snippets@0.2.1
bierner.github-markdown-preview@0.0.2
bierner.markdown-checkbox@0.1.3
bierner.markdown-emoji@0.0.9
bierner.markdown-preview-github-styles@0.1.6
bierner.markdown-yaml-preamble@0.0.4
DavidAnson.vscode-markdownlint@0.34.0
DotJoshJohnson.xml@2.5.0
eamodio.gitlens@10.2.1
EditorConfig.EditorConfig@0.14.4
eg2.tslint@1.0.44
Mikael.Angular-BeastCode@8.1.2
ms-dotnettools.csharp@1.21.13
ms-python.python@2020.2.64397
ms-vscode-remote.remote-containers@0.101.1
ms-vscode-remote.remote-ssh@0.49.0
ms-vscode-remote.remote-ssh-edit@0.49.0
ms-vscode-remote.remote-ssh-explorer@0.49.0
ms-vscode-remote.remote-wsl@0.42.3
ms-vscode-remote.vscode-remote-extensionpack@0.19.0
ms-vscode.cpptools@0.26.3
ms-vscode.powershell@2020.3.0
ms-vscode.vscode-typescript-tslint-plugin@1.2.3
msjsdiag.debugger-for-chrome@4.12.6
msjsdiag.debugger-for-edge@1.0.14
robinbentley.sass-indented@1.5.1
sibiraj-s.vscode-scss-formatter@1.4.3
SimonSiefke.svg-preview@2.8.3
twxs.cmake@0.0.17
vsls-contrib.gistfs@0.0.61
wayou.vscode-todo-highlight@1.0.4
yzhang.markdown-all-in-one@2.7.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

Trying to complete `invoke-webrequest -error` is not supplying the expected `ErrorAction` completion.

#### Expected Behaviour

The auto-complete list should provide `-ErrorAction`

#### Actual Behaviour

The auto-complete list initially does not supply it:

![image](https://user-images.githubusercontent.com/5177512/76013931-fd5d0c00-5ed5-11ea-8d1b-487e2476ef0f.png)

If I type `invoke-webrequest -erroractio` then it finds it in the auto-complete list but at this point I've typed nearly the whole parameter name.  Something's not quite right here.

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

[1583432852-d0e516fc-13f8-444b-877f-cecf115455871583432271941.zip](https://github.com/PowerShell/vscode-powershell/files/4294520/1583432852-d0e516fc-13f8-444b-877f-cecf115455871583432271941.zip)

**Comment by rjmholt** [comment]
That's strange

**Comment by rkeithhill** [comment]
This is stranger (maybe).  Read-Host parameter completion shows only the ubiquitous parameters. Where is `Prompt` (other than in the description)?

![image](https://user-images.githubusercontent.com/5177512/76018003-c9d1b000-5edc-11ea-8edd-94641b211e53.png)

Wait a tic, if I scroll up they are there:

![image](https://user-images.githubusercontent.com/5177512/76018218-1e752b00-5edd-11ea-99e3-868a67380ccf.png)

Why would VSCode not have the completion list scrolled to the top by default?

**Comment by rjmholt** [comment]
I'm seeing this now too

**Comment by rjmholt** [comment]
> I'm seeing this now too

And now I can't repro it again!

**Comment by TylerLeonhardt** [comment]
I feel like this could be a PowerShell bug because we don't really mess with the result of the `CompleteInput` call.

**Comment by rkeithhill** [comment]
You might be onto something.  When I use command-line (PSRL) completion with no chars specified, I don't get any of the ubiquitous parameters:

![image](https://user-images.githubusercontent.com/5177512/76039871-ee448100-5f0a-11ea-881c-62dcc00c5bc3.png)

This has changed since 5.1.  Not sure what the behavior of 6.x was since the 7 install removed it.  :-(  

However, once I type in a char like `-e` then I see the ubiquitous parameters:

![image](https://user-images.githubusercontent.com/5177512/76039971-3cf21b00-5f0b-11ea-85cd-e6d307ed91e2.png)

**Comment by TylerLeonhardt** [comment]
hmm yeah... it might be worth opening this in the PowerShell repo.

**Comment by TylerLeonhardt** [comment]
There's nothing we can really do for this since we rely on TabExpansion2 so I'm going to close this. If you wanna open this in the PowerShell repo I think that would be helpful.
