### ISSUE TITLE
Duplicating Comment Based Help

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/vscode-powershell#2528]
### VSCode extensions:
eamodio.gitlens@10.2.1
Equinusocio.vsc-community-material-theme@1.4.1
Equinusocio.vsc-material-theme@32.5.0
equinusocio.vsc-material-theme-icons@1.1.4
johnpapa.vscode-peacock@3.5.0
ms-dotnettools.csharp@1.21.13
ms-vscode.powershell@2020.3.0
ms-vsliveshare.vsliveshare@1.0.1711
ms-vsliveshare.vsliveshare-audio@0.1.80
ms-vsliveshare.vsliveshare-pack@0.3.4
vscode-icons-team.vscode-icons@10.0.0
wix.vscode-import-cost@2.12.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

When using the `##` command to create comment-based help, it's very slow and then when it does execute, it duplicates the help 3x. 

#### Expected Behaviour

Should be faster and not duplicate the help. 

#### Actual Behaviour

![GlONRBXYat](https://user-images.githubusercontent.com/1256531/76126474-66b74a80-5fbc-11ea-9b57-768378dc4688.gif)

### Attached Logs

I enabled logs, it restarted the PowerShell extension and now it's not doing it anymore. I'll leave logs on and keep an eye out for the issue again.

**Comment by rjmholt** [comment]
Given how difficult PSSA has been with comment help generation, I almost wonder if we should just write out own comment help generator

**Comment by TylerLeonhardt** [comment]
I think if this bug shows up more often we should consider that
