### ISSUE TITLE
Couldn't start client PowerShell Editor Services & Could not start language service: undefined

### ISSUE THREAD

**Issue by phunkodelic** [PowerShell/vscode-powershell#253]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Start Visual Studio Code
2. Open a .ps1 file to edit.
3. I am getting two errors: Couldn't start client PowerShell Editor Services & Could not start language service: undefined

PowerShell Version 4.0
Windows 7 x64. 
Visual Studio Power Shell Plugin Version 0.7.0

This started to happen immediately after I updated the PowerShell Plugin.  Worked fine before the update.

**Comment by daviwil** [comment]
Just shipped a new release with a fix for this issue!  Let me know if it resolves everything for you.
