### ISSUE TITLE
Have Session Menu also change default shell for VS Code's integrated terminal

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2531]
Issue Description
=====

Is this an oversight or by design?

![image](https://user-images.githubusercontent.com/15063294/76150975-14efec80-60b0-11ea-822d-603d82c645d2.png)

Even though the PowerShell Integrated Console is PS 7, PowerShell isn't. 

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.42.1|
| PowerShell Extension Version | 2020.3.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.0|
|PSEdition|Core|
|GitCommitId|7.0.0|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|autoit|Damien|1.0.4|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|code-settings-sync|Shan|3.4.3|
|codesnap|adpyke|1.0.27|
|excel-to-markdown-table|csholmq|1.2.0|
|gistfs|vsls-contrib|0.0.62|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.1|
|html-preview-vscode|george-alisson|0.2.5|
|kixtart|cyann|0.0.1|
|markdown-all-in-one|yzhang|2.7.0|
|markdown-preview-enhanced|shd101wyy|0.5.2|
|markdown-shortcuts|mdickin|0.12.0|
|material-icon-theme|PKief|4.0.1|
|pdf|tomoki1207|0.5.1|
|powershell|ms-vscode|2020.3.0|
|project-manager|alefragnani|10.11.0|
|reg|ionutvmi|1.0.1|
|theme-monokai-pro-vscode|monokai|1.1.15|
|vscode-html-css|ecmel|0.2.3|
|vscode-markdownlint|DavidAnson|0.34.0|
|vscode-pull-request-github|GitHub|0.14.0|
|vscode-toggle-quotes|BriteSnow|0.3.2|
|vscode-versionlens|pflannery|0.25.0|
|vscode-wakatime|WakaTime|4.0.0|
|vscode-yaml|redhat|0.7.2|
|xml|DotJoshJohnson|2.5.0|

**Comment by TylerLeonhardt** [comment]
That is provided by VS Code, not the PowerShell extension. It's configurable though via the command pallet.

![image](https://user-images.githubusercontent.com/2644648/76151223-5c05bf80-6067-11ea-9535-b1bdd928ac4f.png)

**Comment by PrzemyslawKlys** [comment]
But is it possible to bind it so it switches when you switch? I guess from my perspective it would be cool to have?

**Comment by TylerLeonhardt** [comment]
I see. I guess we could do that but I would want more user feedback saying they want that... and it would need to be configurable because I'm not sure everyone would want that behavior.

**Comment by rjmholt** [comment]
Yeah I could see us getting a whole bunch of cranky bug reports about that

**Comment by brianary** [comment]
Is this why the first time I **View: Toggle Terminal** (`Ctrl`+ <code>\`</code>), it opens "pwsh" without `$psEditor` defined, and without starting in the workspace directory as I've configured for the extension? I always have to **PowerShell: Show Extension Terminal**, then toggling the terminal pane uses the correct PowerShell session.

**Comment by andschwa** [comment]
@brianary `Ctrl+` is the VS Code binding for opening the Terminals pane, and so it'll open Code's configured default terminal. That's explicitly not the Extension Terminal, as that has to be spawned by activation of the Extension (ergo it doesn't always exist and therefore can't be set as the default). This issue probably shouldn't have been left open. It's essentially by-design since they're separate things.

**Comment by brianary** [comment]
Why can't it be registered as the default once it _does_ exist?

After the extension's terminal is open, <code>Ctrl+\`</code> works fine, so it's possible.

**Comment by andschwa** [comment]
Because it can just as easily stop existing 😬
