### ISSUE TITLE
Nested errors in debugging not shown in console

### ISSUE THREAD

**Issue by ili101** [PowerShell/vscode-powershell#2534]
Issue Type: <b>Bug</b>

Example from https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_trap?view=powershell-7#using-the-break-and-continue-keywords
``` powershell
function break_example {
    trap {
        "Error trapped"
        break
    }
    1/$null
    "Function completed."
}

break_example
```
1. Save example to file (Optional).
2. Run with F5.

Expected output (and is working correctly on 2020.2.0):
Error trapped + Error
![image](https://user-images.githubusercontent.com/6960531/76167850-737d9f00-6172-11ea-8a49-e90ba7e2569c.png)

Actual output on 2020.3.0:
No error shown
![image](https://user-images.githubusercontent.com/6960531/76167928-16361d80-6173-11ea-9ebb-086d96bf9009.png)

Extension version: 2020.3.0
Tested on PS7 and 5.1
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (2 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|2.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by TylerLeonhardt** [comment]
I can repro this on macOS as well...

![image](https://user-images.githubusercontent.com/2644648/76244613-a6b64180-61f7-11ea-8d62-4104ca957b3d.png)

It only seems to have started occurring in the last update as it doesn't repro in the PowerShell Preview extension

**Comment by rjmholt** [comment]
Started looking into this, and there's definitely a race condition at work here; in some debugging sessions, choosing the right breakpoints actually gets the errors to print.

We correctly catch the `RuntimeException` and process it [here](https://github.com/PowerShell/PowerShellEditorServices/blob/47d45630dd1a21f42b2f0a32171427f7746c6c35/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L828-L840).

That fires off an `Out-Default` execution without awaiting it.

When errors are written as expected, they go through [this method](https://github.com/PowerShell/PowerShellEditorServices/blob/47d45630dd1a21f42b2f0a32171427f7746c6c35/src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs#L570-L589) in our host implementation, but this isn't reliably called...
