### ISSUE TITLE
Startup fails due to Serilog GAC linking

### ISSUE THREAD

**Issue by soulwiper** [PowerShell/vscode-powershell#2539]
After PowerShell Extention updated itself with 2020.3.0 within Visual Studio Code I was getting the following errors:
- Cannot debug or run a PowerShell script until the PowerShell session has started. Wait for the PowerShell session to finish starting and try again.
- Language Startup issue (can not remember the exact error)

Downgrading back to the previous PowerShell Extention version 2020.1.0 the errors went away.

**Comment by andystumph** [comment]
Had the same issue. Downgraded until issue is resolved.

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by soulwiper** [comment]
Hi Tyler.
As requested I zipped the log files but I also attached a word file.  Hope this helps.  I tried to follow the instructions as best I could on your page for providing inforrmation about your environmen.  tPlease let me know if you need anything else.


Regards
Costa Zachariou 

    On Monday, 9 March 2020, 14:06:28 GMT-5, Tyler James Leonhardt <notifications@github.com> wrote:  
 
 
Thanks for the info! Can you also attach the logs here so we can get a better idea of what's going on?

**Comment by rjmholt** [comment]
@soulwiper unfortunately GitHub won't upload email attachments to the comment. If you'd prefer to email the logs directly, try sending them to vscode-powershell@microsoft.com

**Comment by rjmholt** [comment]
I'm going to deduplicate this issue to https://github.com/PowerShell/vscode-powershell/issues/2538
