### ISSUE TITLE
Select $variable with double click in editor

### ISSUE THREAD

**Issue by TheDanishDynamo** [PowerShell/vscode-powershell#2546]
As a developer I want to select a variable including the $ so that I don't have to select it manually by sliding.

When a user double-click a variable, the whole variable including the $ is selected

**Comment by TylerLeonhardt** [comment]
```json
"[powershell]": {
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
}
```

Add this to your settings JSON in VS Code and now your double clicks on a variable names include the dollar sign '$'.

From my tweet:
https://twitter.com/TylerLeonhardt/status/1102749805233737729

**Comment by TylerLeonhardt** [comment]
I need to add this to the [ISE compat doc](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/how-to-replicate-the-ise-experience-in-vscode?view=powershell-6)

**Comment by TylerLeonhardt** [comment]
We should also consider this for ISE Mode
