### ISSUE TITLE
Formatter does not run properly when  saving <filename> -hangs on Running Powershell formatter

### ISSUE THREAD

**Issue by taipva** [PowerShell/vscode-powershell#2549]
Issue Type: <b>Performance Issue</b>

Formatter hangs when saving file with the message Saving 'filename': Running "PowerShell" Formatter

Extension version: 2020.3.0
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    78	  8224	code main
    0	    15	  1528	   electron-crash-reporter
    1	    60	 11980	   window (Issue Reporter)
   30	    79	 18412	   shared-process
    0	    31	 20236	   utility
    2	   277	 20364	   window (● dsc_configuration_sqlserver.ps1 - Platform (Workspace) - Visual Studio Code)
   12	   403	  3540	     "C:\Program Files\PowerShell\7\pwsh.exe" -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "Import-Module 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.3.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2020.3.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2020.3.0\logs\1584018959-aa0fc16d-fbd6-404e-b353-6329d5a1dbbc1584018954787\EditorServices.log' -SessionDetailsPath 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2020.3.0\sessions\PSES-VSCode-8224-122587' -FeatureFlags @() "
    0	   194	 13852	     extensionHost
    0	    35	 14788	       "C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=13852
    0	     8	 19804	     console-window-host (Windows internal process)
    0	    16	 21284	     watcherService 
    0	    12	   488	       console-window-host (Windows internal process)
    0	    36	 21540	     searchService
    2	   228	 23960	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● dsc_configuration_sqlserver.ps1 - Platform (Workspace) - Visual Studio Code)
|    Folder (Platform): 17716 files
|      File types: ps1(4421) psd1(1218) psm1(1196) xml(987) mof(885) json(689)
|                  tf(573) sql(420) md(295) pol(178)
|      Conf files: settings.json(14) sln(5) csproj(4) launch.json(2)
|                  makefile(1) gulp.js(1);
```

</details>

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

Also, the script that has the formatting problem would be very helpful.

This could be a dupe of #2543
