### ISSUE TITLE
Code Collapsing is in the wrong place

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/vscode-powershell#2556]
### VSCode extensions:
eamodio.gitlens@10.2.1
Equinusocio.vsc-community-material-theme@1.4.1
Equinusocio.vsc-material-theme@32.5.0
equinusocio.vsc-material-theme-icons@1.1.4
johnpapa.vscode-peacock@3.6.0
ms-dotnettools.csharp@1.21.14
ms-vscode.powershell@2020.3.0
ms-vscode.powershell-preview@2020.3.0
ms-vsliveshare.vsliveshare@1.0.1742
ms-vsliveshare.vsliveshare-audio@0.1.80
ms-vsliveshare.vsliveshare-pack@0.3.4
vscode-icons-team.vscode-icons@10.0.0
wix.vscode-import-cost@2.12.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I've seen this with the stable build but I'm using the preview build at the moment. 

### Issue Description

I'm seeing code collapsing regions appear in invalid locations. See the below gif. 

![](http://g.recordit.co/MrVG4Wqtfp.gif)
https://recordit.co/MrVG4Wqtfp

#### Expected Behaviour

The code collapsing should be based on blocks etc. 

#### Actual Behaviour

The code collapsing is happening in the middle of lines. Even blank lines have code collapse handles that cause other lines to disappear. 

### Attached Logs

[log.txt](https://github.com/PowerShell/vscode-powershell/files/4330018/log.txt)

**Comment by TylerLeonhardt** [comment]
For this issue I think it would be really helpful to provide the [Language Server payload logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs) and also the script/repo you have open so I can give it a try myself (if possible)

**Comment by adamdriscoll** [comment]
I'll work on getting those logs tomorrow. 

This is from the UD repo: https://github.com/ironmansoftware/universal-dashboard

It's this script: https://github.com/ironmansoftware/universal-dashboard/blob/master/src/poshud/dashboard.ps1

**Comment by TylerLeonhardt** [comment]
I cloned it and opened that file and didn't see any unusual folds so I'll wait and see what your logs say.
