### ISSUE TITLE
Function without arguments not colorized

### ISSUE THREAD

**Issue by gsscoder** [PowerShell/vscode-powershell#2558]
Hi **vscode-powershell** team, thank you for great job!

It's more easy if I show you a screenshot:
![ps-colorcoding-vscode](https://user-images.githubusercontent.com/1194228/76704966-d3c59100-66dc-11ea-908f-d19cee0f2184.PNG)

I expect `ScriptName` function to be colorized with a color different from the rest of the string.

Have a nice day.

Regards,
Giacomo S. S.

**Comment by TylerLeonhardt** [comment]
This should go in: https://github.com/PowerShell/EditorSyntax

Can you open this over there?

**Comment by rkeithhill** [comment]
FWIW that regex's that drive the colorization are pretty complicated and brittle IMO.  This would just work at the point we have semantic (AST) based colorization supported by the extension.  I believe VSCode is looking into enabling this capability.

**Comment by TylerLeonhardt** [comment]
Yeah when that is something that is possible, we can probably move to that. That said, I would expect a new issue to be opened for "Support semantic colorization" when that's possible for us to do so.

**Comment by gsscoder** [comment]
@TylerLeonhardt, yes and _sorry for delay_. The issue was cloned here: https://github.com/PowerShell/EditorSyntax/issues/198.

Bye
