### ISSUE TITLE
Word Wrap STILL Not Working on PowerShell Integrated Terminal

### ISSUE THREAD

**Issue by arcotek-ltd** [PowerShell/vscode-powershell#2564]
Issue Description
=====

The issues reported in #90835, #78967 with PSReadLine in the integrated console still exist.
(It is my understanding the release of PS code extension (v. 2020.3.0) has taken so long because of issues like this and debug DosKey not working - to name but a few)

I have observed the following:
1. Fill the console with characters up to 99%
2. As one tries to type the next character, the following error is produced:

(This is particularly frustrating when one's current directory path is long and/or the VS Code window width is narrow).

![image](https://user-images.githubusercontent.com/26305145/76806470-64819700-67d9-11ea-8006-689281c14d4d.png)

When the command consumes 100%, the following error is generated:
```
An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 21.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.ConsoleReadLine.<InvokeLegacyReadLineAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.<InvokeReadLineAsync>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContext.EditorServicesPSHostUserInterface.<StartReplLoopAsync>d__109.MoveNext()
```
If I run `Clear-Host` although the buffer is not cleared, "word wrap" works again.

Should the functionality of `Clear-Host` not be integrated to prevent this error?

Thanks.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.43.0|
| PowerShell Extension Version | 2020.3.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.628|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.628|
|BuildVersion|10.0.18362.628|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.8|
|azure-pipelines|ms-azure-devops|1.165.1|
|csharp|ms-dotnettools|1.21.14|
|powershell|ms-vscode|2020.3.0|
|terraform|mauve|1.4.0|
|vscode-azurefunctions|ms-azuretools|0.21.0|
|vscode-docker|ms-azuretools|1.0.0|
|vscode-nuget-package-manager|jmrog|1.1.6|

**Comment by TylerLeonhardt** [comment]
From your screenshot, it doesn't look like PSReadLine is enabled.

Can you send me what VS Code settings you have configured?

**Comment by rjmholt** [comment]
Closing now that PSRL is integrated into the console experience

**Comment by rjmholt** [comment]
Closing now that PSRL is integrated into the console experience

**Comment by arcotek-ltd** [comment]
Hi,
It looks like I may have some settings leftover from the development branch of PS extension:
```
{
    "telemetry.enableTelemetry": false,
    "powershell.developer.featureFlags": [
        "PSReadLine"
    ],
    "files.autoSaveDelay": 50000,
    "files.autoSave": "onFocusChange",
    "window.zoomLevel": 1,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "explorer.confirmDragAndDrop": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.scrollback": 10000,
    "powershell.integratedConsole.useLegacyReadLine": true,
    
}
```

I've removed:
```
"powershell.developer.featureFlags": [
        "PSReadLine"
    ],
```
and
```
"powershell.integratedConsole.useLegacyReadLine": true,
```

Could the extension installation check for these and remove or at least warn the user that they're enabled.

Thanks.

**Comment by TylerLeonhardt** [comment]
`useLegacyReadLine` is the setting that you needed to remove. The feature flag setting for PSReadLine is a no-op at this point so that didn't cause your issue.

> Could the extension installation check for these and remove or at least warn the user that they're enabled? This would be especially useful for people who have been using the development branch.

Considering `useLegacyReadLine` is a setting that you have to opt-in to using and is specifically designed to allow you to fall back to the legacy experience (not PSReadLine), I don't think it would be a good idea to notify people that they are using that experience or change it automatically because it's unclear that they would want it to be changed automatically. 

It's very clear when they are using that setting, because they don't get syntax highlighting in the console.

We haven't had anyone else report something like this before so it'll be better to leave the current behavior as it is today.
