### ISSUE TITLE
Doc issue: broken link

### ISSUE THREAD

**Issue by DSotnikov** [PowerShell/vscode-powershell#257]
https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/using-vscode.md#editing-with-vs-code has a broken link at the end of the article:

[Debugging PowerShell in Visual Studio Code](https://github.com/PowerShell/vscode-powershell-ops/tree/master/vscode-powershell/examples) is linked to https://github.com/PowerShell/vscode-powershell-ops/tree/master/vscode-powershell/examples which currently give 404

**Comment by rkeithhill** [comment]
That's because that repo is currently private.  @daviwil Is the plan to make that public at some point?

**Comment by daviwil** [comment]
Whoops!  That one slipped through the cracks.  Thanks for reporting that @DSotnikov!  I'll submit a PR over there to fix it.  The correct path is in this repo:

https://github.com/PowerShell/vscode-powershell/tree/master/examples

The other repo was only meant for pre-launch work and won't be made public :)

**Comment by daviwil** [comment]
Got a PR out to fix this: https://github.com/PowerShell/PowerShell/pull/2053

**Comment by daviwil** [comment]
PR has been merged.  Thanks for the report!
