### ISSUE TITLE
Quotation doubling not understood by syntax colorizer (re: about_Quoting_Rules PS topic)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [PowerShell/vscode-powershell#2573]
* Please submit editor syntax colorization issues with PowerShell scripts
  to the [EditorSyntax](https://github.com/powershell/editorSyntax/issues) repo on GitHub.

Hope I'm getting this submitted correctly....

This doesn't properly highlight:

`$Recipient = Get-EXORecipient -Filter "Name -eq '$($cmp.User -replace ""'"",""''"")'" -Properties DisplayName, PrimarySmtpAddress, RecipientTypeDetails, Guid, ExternalDirectoryObjectId -ErrorAction Stop`

It does highlight properly in PowerShell ISE.  In VS Code, everything after this:
`$Recipient = Get-EXORecipient -Filter "Name -eq '$($cmp.User -replace ""'`
...is colored as though it is quoted text.

What I'm doing in the code, in case it's not obvious is escaping single quotes that may end up in the variable's value, when the user stored in that variable has an apostrophe in their name (e.g. O'Donnell).  So I'm replacing singe instances of single quotes with two instances instead.  And to do that, I also have to use doubling of the double quotes for the find/replace parts of my -replace operator.  It's perfectly fine code, but not understood by the colorizer.

Coincidentally, the new Exchange Online V2 cmdlets' -Filter parameter no longer can understand it either.  Only the reason there is said to be OPath's fault (however I'm awaiting confirmation on that point).

**Comment by TylerLeonhardt** [comment]
> Please submit editor syntax colorization issues with PowerShell scripts to the [EditorSyntax](https://github.com/powershell/editorSyntax/issues) repo on GitHub.

Please file this issue over in that repo.

**Comment by JeremyTBradshaw** [comment]
Thanks @TylerLeonhardt .  I'm just going to close this , I've found in the other location, many have reported the same issue already.  I got thrown off by the fact that there's a template here for these issues.  I would almost just not still have that template here, but maybe it's just me who found it confusing.
