### ISSUE TITLE
Execution path issue + F5 run

### ISSUE THREAD

**Issue by homezonebenny** [PowerShell/vscode-powershell#2575]
# To reproduce this issue follow this steps

**Create this file structure:**

* Folders:\
`.\Project\Test`

* VSCode project file:\
`.\Project\Project.code-workspace`

* PowerShell file:\
`.\Project\Test\Get-MD5.ps1`

* Text file:\
`.\Project\Test\Test.txt`

&nbsp;

## VSCode workspace file

\
Edit `.\Project\Project.code-workspace` like this:

```Json
{
  "folders": [
    {
      "name": "PowerShell Project",
      "path": "."
    },
  ]
}
```

&nbsp;

## Powershell file

\
Edit `.\Project\Test\Get-MD5.ps1` like this:

```Powershell
# This scripts location
$thisScriptPath = $PSScriptRoot


# Define file variables
$vsCodeFile = "$thisScriptPath/Test.txt"
$file = "Test.txt"


# MD5
$md5 = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider


#! Get hash - Only works in VSCode
$vsCodeHash = [System.BitConverter]::ToString($md5.ComputeHash([System.IO.File]::ReadAllBytes($vsCodeFile)))

#! Get hash - Works outside of VSCode only !!! Like normal PowerShell execution.
$normalHash = [System.BitConverter]::ToString($md5.ComputeHash([System.IO.File]::ReadAllBytes($file)))


## Write output: Hash
Write-Host "`n`nVSCode Hash:`n$vsCodeHash`n`n"
Write-Host "`n`nHash:`n$normalHash"
Read-Host -Prompt "`n`nPress Enter to close this script"

```

&nbsp;

## Test phase

When you double click:\
`.\Project\Project.code-workspace`

to start VSCode with this new generated project and you open:\
`.\Project\Test\Get-MD5.ps1` 

inside of VSCode and execute the PowerShell-Code with **F5** it will show you an error that:\
`.\Project\Test\Test.txt` \
got not found!

&nbsp;

On the other side when you just double click the PowerShell-File:\
`.\Project\Test\Get-MD5.ps1` 

in windows explorer you'll get no error message at all.\
Both pathes are found.

Somehow VSCode needs the:\
`$PSScriptRoot`

Even this:\
`Set-Location $PSScriptRoot`

is not working since VSCode debugger thinks we are in:\
`.\Project\`

instead of:
`.\Project\Test\`

which is totally strange.\
This only happens with this command:
`[System.BitConverter]::ToString($md5.ComputeHash([System.IO.File]::ReadAllBytes($file)))`

Everything else works perfect inside of VSCode!
\
&nbsp;

Like if you put this code at the end of the PowerShell-File:
```Powershell
$test = Get-Content $file
Write-Host $test
```

&nbsp;

## Conclusion

For me it seems like a bug somewhere and I hope you can reproduce this and find a solution for it.\

Maybe it's just wrong how this is written:\
`[System.BitConverter]::ToString($md5.ComputeHash([System.IO.File]::ReadAllBytes($file)))`

I'm not that deeply into PowerShell, so I don't know.

&nbsp;

BTW my `.vscode\launch.json` is default like this:
```Json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "PowerShell",
      "type": "PowerShell",
      "request": "launch",
      "script": "${file}",
      "cwd": "${file}"
    }
  ]
}
```

And I know you can just use:\
`Get-FileHash <filepath> -Algorithm MD5`

**Comment by SydneyhSmith** [comment]
@homezonebenny thanks for opening this issue, when you mention "Normal PowerShell Execution" where exactly are you running this code (PowerShell 7 console?, Windows PowerShell Console?, Windows ISE?)...thanks!

**Comment by homezonebenny** [comment]
@SydneyhSmith 
Sorry, my bad. With "normal" I meant:
**Windows PowerShell Console**

I never tried it in Windows ISE and never tried PowerShell 7 at all.

**Comment by TylerLeonhardt** [comment]
@homezonebenny I'm a bit confused by this issue... When I open your example `Project.code-workspace`

The console is in the directory:

```
.\Project
```

Not in `.\Project\Test`... so in your Windows PowerShell Console, do the same thing.

```
PS > cd .\Project
PS > .\Test\Get-MD5.ps1
```

That fails for me with the error you showed above:
```
"Could not find file '/Users/tyleonha/Code/PowerShell/Misc/Project/Test.txt'."
```

**Comment by homezonebenny** [comment]
I tested it again, here a screenshot:\
[Imgur screenshot](https://i.imgur.com/SHoEkjm.png)

I also edited the comments in the .ps1 code above.\
Since this was a bit confusing too!

```Powershell
#! Get hash - Works in VSCode AND directly in powershell.exe
$vsCodeHash = [System.BitConverter]::ToString($md5.ComputeHash([System.IO.File]::ReadAllBytes($vsCodeFile)))

#! Get hash - ONLY works in powershell.exe but NOT in VSCode
$normalHash = [System.BitConverter]::ToString($md5.ComputeHash([System.IO.File]::ReadAllBytes($file)))
```

If you look into the screenshot you see the results.\
I hope this helps further.

**Comment by TylerLeonhardt** [comment]
@homezonebenny can you add these two lines to your scipt:

```pwsh
$pwd
[Environment]::CurrentDirectory
```

Let me know what it gets you!

**Comment by rjmholt** [comment]
This looks like https://github.com/PowerShell/vscode-powershell/issues/2557
