### ISSUE TITLE
command 'PowerShell.RunSelection' not found

### ISSUE THREAD

**Issue by marfoned** [PowerShell/vscode-powershell#2578]
Hi All,

when i try to execute part of script with visual studio code i get the following message:

command 'PowerShell.RunSelection' not found

this appens both using F8 Key, Run Selection button and from drop-down menù.

i'm using windows 10 x64 and latest Visual Studio Code 1.43.1 with powershell extension enabled. full script works fine.

**Comment by TylerLeonhardt** [comment]
What version of PowerShell are you using? Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by marfoned** [comment]
Hello TylerLeonhardt,

PS Version 5.1.18362.628

instead i'm not able to get the logs.
i've enabled them from visual studio, 
![image](https://user-images.githubusercontent.com/62553852/77334570-4958df00-6d25-11ea-98be-33750e2c19f9.png)

rebooted the machine, confirmed $home Path

but no Logs folder in C:\users\Username\.vscode\extensions\ms-vscode.powershell-2020.3.0

![image](https://user-images.githubusercontent.com/62553852/77334639-61306300-6d25-11ea-976e-a8531cdfa5df.png)

where i'm wrong?

**Comment by TylerLeonhardt** [comment]
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2526 then.

**Comment by marfoned** [comment]
Installed the vsix from this link 
https://github.com/PowerShell/vscode-powershell/files/4299919/psvsix.zip

with the following commands

expand-archive ./psvsix.zip ./psext.vsix
code --install-extension ./psext.vsix

disabled the powershell addin in vscode and now looks good.

thank you!
