### ISSUE TITLE
Language server startup failed

### ISSUE THREAD

**Issue by patrickq1236** [PowerShell/vscode-powershell#2579]
Hello.

I've been trying for a while to get this to work. I've tried everything I can think of to no avail. I've been getting met with an error every time I try to use vscode. 

When I open vscode, and try to edit a PowerShell script it hangs for a while, then Windows tell me it's unresponsive, and asks if I want to reopen, wait, or close the program. I'll choose to wait. Then I'll see in the lower corner a box that says :The terminal process terminated with exit code: {0}" about a minute after, another box will appear saying "The language service could not be started"

![image](https://user-images.githubusercontent.com/62443472/77350270-9c756680-6d12-11ea-889e-f0b27074387d.png)

the vscode-powershell.log contains
3/23/2020 2:21:54 PM [NORMAL] - powershell.exe started.
3/23/2020 2:21:54 PM [NORMAL] - Waiting for session file
3/23/2020 2:23:55 PM [NORMAL] - Error occurred retrieving session file
3/23/2020 2:23:55 PM [NORMAL] - Language server startup failed.
3/23/2020 2:23:55 PM [ERROR] - The language service could not be started: 
3/23/2020 2:23:55 PM [ERROR] - Timed out waiting for session file to appear.

I've tried running the command listed here: https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-6#installing-the-powershell-extension-on-restricted-systems and the output is nothing.

It should be noted that:
-  I can press "enter" in the terminal and I can run cmdlets in that terminal window. I just can't run the script, or parts of it directly from the editor.
- if I switch to PowerShell (x86) it works fine. This is not ideal, however.
- If I reinstall an earlier version of vscode (1.33) it works fine. the version it does not work on is: 1.43.1
fe22a9645b44368865c0ba92e2fb881ff1afce94
x64
- I cannot run $psEditor.EditorServicesVersion

**Comment by TylerLeonhardt** [comment]
This is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2377 most likely...

**Comment by patrickq1236** [comment]
@TylerLeonhardt Thanks, I installed an earlier version of the extension (2020.1.0) and it works fine. I should have thought of that sooner.
