### ISSUE TITLE
New "Run Selection" method breaks on switch statement

### ISSUE THREAD

**Issue by mbiver** [PowerShell/vscode-powershell#2581]
I was working on my script last Friday and the switch statement below was working just fine when using "Run Selection" in VS Code. The PowerShell below also runs fine when the script is executed in a regular PowerShell window. There must have been an upgrade to VS Code over the weekend and now the "Run Selection" seems to be behaving differently and the switch statement below throws an error.
```
"At line:1 char:28

Switch($addressPrefix){
                       ~
Missing condition in switch statement clause.
+ CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingSwitchConditionExpression
"

Sample.

Switch($addressPrefix){

    10.0.0.0/16{$subnetPrefix = "10.0.0.0/24";$gwSubnetAddressPrefix = "10.0.1.0/24"}
    10.1.0.0/16{$subnetPrefix = "10.1.0.0/24";$gwSubnetAddressPrefix = "10.1.1.0/24"}
    10.2.0.0/16{$subnetPrefix = "10.2.0.0/24";$gwSubnetAddressPrefix = "10.2.1.0/24"}
    10.3.0.0/16{$subnetPrefix = "10.3.0.0/24";$gwSubnetAddressPrefix = "10.3.1.0/24"}
    10.4.0.0/16{$subnetPrefix = "10.4.0.0/24";$gwSubnetAddressPrefix = "10.4.1.0/24"}
    10.5.0.0/16{$subnetPrefix = "10.5.0.0/24";$gwSubnetAddressPrefix = "10.5.1.0/24"}
    10.6.0.0/16{$subnetPrefix = "10.6.0.0/24";$gwSubnetAddressPrefix = "10.6.1.0/24"}
    10.7.0.0/16{$subnetPrefix = "10.7.0.0/24";$gwSubnetAddressPrefix = "10.7.1.0/24"}
    10.8.0.0/16{$subnetPrefix = "10.8.0.0/24";$gwSubnetAddressPrefix = "10.8.1.0/24"}
    10.9.0.0/16{$subnetPrefix = "10.9.0.0/24";$gwSubnetAddressPrefix = "10.9.1.0/24"}        

}
```
VS Code version: Code 1.43.1 (fe22a96, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.17763

**Comment by SydneyhSmith** [comment]
@mbiver thanks for opening this issue, could you please provide any settings you have related to the PowerShell extension? 
It would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by bobbytreed** [comment]
I've seen this with if/else statements as well.  When selecting branched code, there seems to be a parsing error.  

Mine complains with elseif: The term 'elseif' is not recognized as the name of a cmdlet, function, script file, or operable program. And 
     | Unexpected token '{' in expression or statement.

if ($false) {
       Write-Verbose "1"
}
elseif ($true {
        Write-Verbose "2"
}
else {
        Write-Verbose "3" 
}

**Comment by TylerLeonhardt** [comment]
@bobbytreed you seem to be missing a right paren `) ` after the `$true` in your `elseif`

**Comment by corbob** [comment]
> 
> 
> @bobbytreed you seem to be missing a right paren `) ` after the `$true` in your `elseif`

which wouldn't explain the actual error... That being said, I can't reproduce it with `F8` under WinPS or PS7. I can however reproduce with copy + paste into prompt (because the `elseif` is on a new line the parser ends the if statement I imagine)
