### ISSUE TITLE
Add "function explorer" tree in the Explorer panel

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#259]
Is there any chance at getting a function explorer window like this?

![image](https://cloud.githubusercontent.com/assets/4306938/17972546/b8ec2840-6aa4-11e6-815f-32f8c9793d0a.png)

**Comment by daviwil** [comment]
Absolutely.  I've got a plan to enable some helpful UI panels for the PowerShell extension within the next few months.  I'll make sure this is a part of it.

**Comment by Golosok** [comment]
Please make it also to support PS classes, memebrs and methods.

**Comment by Bill-Stewart** [comment]
Have you tried `workbench.action.gotoSymbol` (default key mapping <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd>), then type <kbd>:</kbd>?

**Comment by daviwil** [comment]
This will be possible in the very near future thanks to VS Code's new explorer tree API:

- https://github.com/Microsoft/vscode/issues/26948
- https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-explorer-sample

**Comment by SydneyhSmith** [comment]
Closing as resolved.
