### ISSUE TITLE
[Feature Request] Wire up new debug console icon to PS Integrated Editor

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#2593]
**Summary of the new feature**

I want this new insiders button in the debug revamp:
![image](https://user-images.githubusercontent.com/15258962/77933030-32554800-7263-11ea-9928-455e45dd138f.png)

to open PS Integrated console, if possible (explore feasibility)

**Comment by TylerLeonhardt** [comment]
First time I'm seeing this... it _looks_ like it's just a short cut to the Debug Console which has already existed... I don't think there's any sort of configuration for us to say "hey use this for that". But it's brand new so I may be wrong.

Not using the Debug Console is a totally valid thing to do:
![image](https://user-images.githubusercontent.com/2644648/77936197-6b8fb700-7267-11ea-92ef-93e8ccf2a6bb.png)

So they'd be hurting extensions that don't use it if they keep this not configurable...

**Comment by TylerLeonhardt** [comment]
Moved this over to https://github.com/microsoft/vscode/issues/94063
