### ISSUE TITLE
Enumeration support

### ISSUE THREAD

**Issue by Satak** [PowerShell/vscode-powershell#26]
The whole enumeration / enum keyword feels like it's not implemented to have a support for it. Doesn't highlight the keyword or it's content and doesn't offer any snippets.

**Comment by Satak** [comment]
You can see that enum keyword the name or it's content is not color coded
![image](https://cloud.githubusercontent.com/assets/10957012/11375617/ec5685a6-92e4-11e5-826f-bb50a03af7db.png)

**Comment by daviwil** [comment]
This seems to be a problem with the TextMate bundle we're using from Sublime Text.  GitHub also uses it, this is how the same code gets highlighted here:

```powershell
enum test
{
    listItem1
    listItem2
    listItem3
}
```

Looks like there's already a bug filed against the Sublime Text repo for this:

https://github.com/SublimeText/PowerShell/issues/124

@Jaykul, any interest in trying to fix that one?

**Comment by adbertram** [comment]
I just ran into this today as well. It would be nice to at least get syntax coloring for enums.

**Comment by rkeithhill** [comment]
Shouldn't this be moved to http://github.com/powershell/editorsyntax and closed here?

**Comment by daviwil** [comment]
Yep!

**Comment by daviwil** [comment]
This issue was moved to PowerShell/EditorSyntax#29
