### ISSUE TITLE
ctrl+click inside a class

### ISSUE THREAD

**Issue by gekmcfh** [PowerShell/vscode-powershell#2601]
Is there a possibility to fall into variables or methods definition **inside a class** in a roadmap? Right now i can only use ctrl+click on a functions and variables defined outside of any class, but not inside of it.

**Comment by TylerLeonhardt** [comment]
This is something we haven't gotten to just yet. (Duplicate of https://github.com/PowerShell/vscode-powershell/issues/3)

We want to do it, just haven't had the time.
