### ISSUE TITLE
Extension fails to refresh problems after fixing code

### ISSUE THREAD

**Issue by nascentt** [PowerShell/vscode-powershell#2602]
A number of times now I've had the extension report that I have problems with my code.  However either the problem doesn't cease to be reported after being fixed.  
I find this occurs most when creating new code blocks, and having the extension report closing braces are missing when they aren't.

I'll create a new code block such as a function, and then some if statements/loops etc and see the problem that a closing brace is missing.  However, the closing brace exists.

I don't know how to reproduce this on demand, however it's bitten me a few times now.  I'll waste a ton of time cycling through all my braces  and ensure the closing brace exists, or i'll reformat my code to ensure the indentation matches.  Or i'll temporarily remove code reducing the number of code blocks until I get down to the last braces in the file, and see that with a file with literally only an opening and closing brace, the error will still be reported that the closing brace is missing.

I've tried finding ways of having the extension refresh to see the brace exists, by reverting the file from disk, or adding extra braces (closing/or opening) but nothing seems to cause the code to be rescanned properly.

The only fix I've found so far is to literally close the tab with the code and re-open the file.

This is an especially annoying bug with large projects,  when I first saw this bug I spent hours trying to 'fix' the 'missing brace'.

**Comment by TylerLeonhardt** [comment]
Can you give this a go in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension? It has some perf fixes in it and it might be fixed in that already.

**Comment by nascentt** [comment]
Ok thanks.  I shall try that extension instead.  It might take a while to
know if the issue is resolved on that as I'm unable to reproduce the issue
on demand.
