### ISSUE TITLE
"Auto correct alias" setting of PowerShell extension not working

### ISSUE THREAD

**Issue by Nicicalu** [PowerShell/vscode-powershell#2608]
Issue Type: <b>Bug</b>

## Problem
The "Auto correct alias" setting of the PowerShell extension is not working as it should. If you activate it, nothing will change. 

## Expected result
After typing an alias, the extension should switch it out with the correct expanded Cmdlet. It should do the same as the shortcut `Shift + Alt + E`.

## Actual result
Nothing happens. The aliases are still reported as problems and are not being replaces with the correct expanded Cmdlet.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.43.2|
| PowerShell Extension Version | 2020.3.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.17134.858|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.858|
|BuildVersion|10.0.17134.858|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|powershell|ms-vscode|2020.3.0|
|vscode-html-css|ecmel|0.2.3|

**Comment by TylerLeonhardt** [comment]
Thanks for the info! @Nicicalu, which aliases did you see not change and can you please also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by Nicicalu** [comment]
No aliases changed and in the logs you can't see anything because nothing happenes 👎

**Comment by TylerLeonhardt** [comment]
I need the [language server payload logs]. Those will have important information.

**Comment by wingers999** [comment]
I am having this issue still - has it been fixed?

For example typing 

measure -distance

would expect it to expand it to Measure-Distance -distance 

?

**Comment by corbob** [comment]
> I am having this issue still - has it been fixed?
> 
> For example typing 
> 
> measure -distance
> 
> would expect it to expand it to Measure-Distance -distance 
> 
> ?

@wingers999 It looks like Tyler was waiting for payload logs, and so the bot closed it 9 months ago. Likely the issue still persists, but no information on how or when it happens means it can't really be investigated. If you're able to consistently repro it, I'd recommend opening a new issue and including the payload logs along with all the other logs.

**Comment by wingers999** [comment]
@corbob - yes I can repro it, it happens all the time on any script.  If someone can tell me how I get the payload logs needed then I would be more than happy to open a new issue to get this resolved - thanks

**Comment by corbob** [comment]
@wingers999  - you'll want to get the logs mentioned here: https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment and the payload logs mentioned here: https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs

**Comment by wingers999** [comment]
@corbob - okay thanks, am I better to start a new issue, or could this one be re-opened as it already has all the previous discussion / history about it?

**Comment by corbob** [comment]
Personally, if it were me, I would open a new issue and reference this one. Reason being: Neither you nor I can reopen this issue, that's only maintainers and OP that can do that (I think). By opening a new issue, you become the reporter on the issue and can keep the issue open by keeping engaged with it.
