### ISSUE TITLE
Color coding is off when using parameter validation attributes

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#262]
It seems like it's not "seeing" the end quote in the parameter validation attribute.

http://www.screencast.com/t/jdE5iVbYtLeI

**Comment by rkeithhill** [comment]
The PowerShell extension doesn't actually do the PowerShell syntax colorization.  That TextMate file is provided with VSCode. However, you can submit this issue on that [project](https://github.com/PowerShell/EditorSyntax).  There are currently quite a few issues folks are raising.  

Ultimately, you can only do so much with the regex approach before it starts to get too hard to manage.  The right answer IMO is for VSCode to allow language extensions to provide syntax colorization, which AFAIK, it doesn't.

**Comment by rkeithhill** [comment]
@adbertram I'm going to close this as the syntax colorization is handled by another [project](https://github.com/PowerShell/EditorSyntax).

**Comment by daviwil** [comment]
I think this is actually fixed in the updated version of the syntax definition, we just have to work through some of the issues with it before we can roll it back out again.
