### ISSUE TITLE
Theme switching during install of the extension

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#2624]
**Summary of the new feature**

I see this a fair amount as I switch between installs of stable and preview:

![image](https://user-images.githubusercontent.com/5177512/78933652-dced1800-7a66-11ea-88cb-a0ad00fe2f39.png)

I'll NEVER EVER EVER want the ISE color scheme in VSCode. 😛 

Rather than just switching the whole color scheme (even if just temporarily), what if the extension popped up a notification asking if the user wants to try the ISE (light) color scheme before switching (or even previewing) the color scheme.  Or maybe add a setting to disable this?  

What I don't know is if this something we do in the extension or if this is just a "feature" of VSCode when it detects a theme in an extension.   Hmm, looks like this might just be a feature of VSCode.

**Comment by rjmholt** [comment]
See https://github.com/PowerShell/vscode-powershell/issues/1943. VSCode closed as wontfix in https://github.com/microsoft/vscode/issues/73224

**Comment by rjmholt** [comment]
To expand, we've always bundled the theme, and one day VSCode changed behaviours to be more helpful, now this happens and the onus has been shifted to us to create a new deployment pipeline for a second extension just so that this doesn't happen.

**Comment by rkeithhill** [comment]
Gotcha.  You can close this then if you want.  Not too much we can atm.
