### ISSUE TITLE
Unexpected characters in VSCode PS Integrated shell commands

### ISSUE THREAD

**Issue by ZZStoner** [PowerShell/vscode-powershell#2637]
Issue Description
=====

After upgrading the PS Extension in VS Code to 2020.4.0, I noticed the PS Integrated Shell showing garbage characters when trying to type any commands.

Example showing strange extra characters after only typing `dir`:
![VSCode.PS.CmdLineMess.jpg](https://user-images.githubusercontent.com/63821108/79513094-dc6cf800-7ff7-11ea-972b-77d00da5598e.jpg)

Attached Logs
=====
> _Note to Team: The README link to the Reporting Problems below returns a 404 Not Found._

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 6.3.9600 |
| VSCode | 1.44.1|
| PowerShell Extension Version | 2020.4.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.14409.1018|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.14409.1018|
|BuildVersion|10.0.14409.1018|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.17|
|gc-excelviewer|GrapeCity|2.1.34|
|kuskus-extensions-pack|rosshamish|1.0.1|
|kuskus-kusto-color-themes|rosshamish|0.1.0|
|kuskus-kusto-language-server|rosshamish|1.0.1|
|kuskus-kusto-syntax-highlighting|rosshamish|1.1.8|
|material-icon-theme|PKief|4.0.1|
|mssql|ms-mssql|1.9.0|
|powershell|ms-vscode|2020.4.0|
|rainbow-csv|mechatroner|1.6.0|
|team|ms-vsts|1.161.0|

**Comment by TylerLeonhardt** [comment]
Hi @ZZStoner I'm having trouble repro'ing this. Can you comment out everything in your `$PROFILE` and see if this still repros?

![image](https://user-images.githubusercontent.com/2644648/79516438-42f61400-8000-11ea-8e2b-91bbfa12c929.png)

**Comment by ZZStoner** [comment]
Currently with `v2020.4.0`:
> I cleared out my Microsoft.VSCode_profile.ps1 (well, it only has a single line which is a comment)
> Then reloaded VS Code.  It still reproed.
> I then chose to downgrade to `v2020.3.0`

Downgraded to `v2020.3.0`:
> The PS Profile is empty.
> Typing the first command worked as expected with no artifacts...
> ![VSCode PS 2020 3 0 OK](https://user-images.githubusercontent.com/63821108/79518531-3379c980-8006-11ea-9213-afbd9ceebf44.jpg)
> I closed and reopened VS Code to make sure things worked consistently.
> I then chose to upgrade back to `v2020.4.0`

Upgraded back to `v2020.4.0` again:
> The PS Profile is empty.
> Still have crazy artifacts while typing.
> ![VSCode PS 2020 4 0 Back](https://user-images.githubusercontent.com/63821108/79518685-910e1600-8006-11ea-8667-45034f620db8.jpg)

Potentially related:
> I noticed the garbage text seems to have the same format as the properties from `Get-PSReadLineOption`.

Sample from `Get-PSReadLineOption`:
> ```
> ParameterColor                         : [90m"$([char]0x1b)[90m"[0m
> PredictionColor                        : [38;5;238m"$([char]0x1b)[38;5;238m"[0m
> SelectionColor                         : [30;47m"$([char]0x1b)[30;47m"[0m
> ```

The value of `PredictionColor` is interesting because the "`238m`" is also seen in my snips.

**Comment by TylerLeonhardt** [comment]
Ah this is the new prediction feature in PSReadLine.

@daxian-dbw can you take a look at this?

**Comment by daxian-dbw** [comment]
>Sample from `Get-PSReadLineOption`:
> ```
> ParameterColor                         : [90m"$([char]0x1b)[90m"[0m
> PredictionColor                        : [38;5;238m"$([char]0x1b)[38;5;238m"[0m
> SelectionColor                         : [30;47m"$([char]0x1b)[30;47m"[0m
> ```

This indicates that the VT100 escape sequences are not correctly handled by the VS Code terminal.
@TylerLeonhardt are you aware of any issues of the VS Code terminal related to VT100 support?

**Comment by TylerLeonhardt** [comment]
Hmm they should be handled correctly... @Tyriar do you have any thoughts?

@ZZStoner what version of Windows are you on?

**Comment by dnelson6** [comment]
I am also experiencing this same garbage text. Downgraded to v2020.3.0 and all is well.

```
Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' | select EditionID, ProductName, CurrentBuildNumber

EditionID      ProductName                     CurrentBuildNumber
---------      -----------                     ------------------
ServerStandard Windows Server 2012 R2 Standard 9600 
```

**Comment by Tyriar** [comment]
If the terminal is printing then the terminal is likely not getting the escape character. You can check exactly when the terminal gets by following this https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by ZZStoner** [comment]
To follow up, I am also using Windows 2012 R2.

**Comment by TylerLeonhardt** [comment]
Just to get you unblocked... you can remove this folder:

```
C:\Users\[YOUR USER]\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PSReadLine\
```
> NOTE: If you're on insiders it's `\.vscode-insiders\`

If your console doesn't give you syntax highlighting, simply reinstall PSReadLine the normal way:

```pwsh
Install-Module PSReadLine -Force -AllowClober
```

**Comment by ZZStoner** [comment]
Thanks.  The workaround unblocked me.

**Comment by Schwanowski** [comment]
I have had the same issue and the workaround worked for me too.

**Comment by merlinfrombelgium** [comment]
> ```powershell
> Install-Module PSReadLine -Force -AllowClober
> ```

 ```powershell
Install-Module : A parameter cannot be found that matches parameter name 'AllowClober'.
```

Serves me right for copy-pasting code from a forum thread 🤣
