### ISSUE TITLE
Add check for OpenSSL on OS X before starting the language service

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#264]
The extension should check for the existence of OpenSSL on OS X before starting the language service.  If it cannot be found, the user should be directed to the documentation which guides them through the OpenSSL installation.

One way to check for existence could be to test for the existence of `/usr/local/opt/openssl`

**Comment by MarlonRodriguez** [comment]
That check on the path only works if you are using homebrew.  For MacPorts:
```
ln -s /opt/local/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /opt/local/lib/libssl.1.0.0.dylib /usr/local/lib/
```
fixes it.

**Comment by daviwil** [comment]
Thanks a lot @MarlonRodriguez!  I'll include your fix in the troubleshooting notes.

**Comment by adbertram** [comment]
It'd be nice if a link to some instructions on how to resolve this were added to the notification as well.

**Comment by daviwil** [comment]
That's what the "Show Documentation" button on the notification does, did it not show up for you?

**Comment by adbertram** [comment]
I'm blind. Thanks but I had originally installed it. It wasn't until I
updated again to this latest version that I saw that popup and Intellisense
isn't working.
When I run brew install openssl I get:

openssl-1.0.2h_1 already installed

**Comment by daviwil** [comment]
Interesting, @RamblingCookieMonster mentioned the same thing to me yesterday.  If you follow the steps in the documentation page about [creating symbolic links](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#installing-openssl-via-macports) it should fix the problem for you.

Quick question before you do that though: was IntelliSense working for you without a problem on OS X before the latest update?  Maybe I'm checking the incorrect path for Brew's install of OpenSSL.

**Comment by RamblingCookieMonster** [comment]
@adbertram try this (probably a way to script this out, but, a bit busy, sorry!:

* `brew info openssl`
* Pick out the path to the latest, e.g. `/usr/local/Cellar/openssl/1.0.2h_1` - `find /usr/local/Cellar -name libssl.1.0.0.dylib` might also work.
* Create links mentioned above.

Example:

```bash
ln -s /usr/local/Cellar/openssl/1.0.2h_1/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/Cellar/openssl/1.0.2h_1/lib/libssl.1.0.0.dylib /usr/local/lib/
```

Cheers!

**Comment by adbertram** [comment]
Thanks @RamblingCookieMonster! That did it.

**Comment by adbertram** [comment]
@daviwil Yes. This was working fine before I updated.

**Comment by daviwil** [comment]
Damn, so apparently my path check gave a false negative for Homebrew installs...  I'll need to look into that.

**Comment by daviwil** [comment]
Tracking the false negative problem here: https://github.com/PowerShell/vscode-powershell/issues/286.  Thanks Adam!
