### ISSUE TITLE
Display extension edition & version in PSIC banner

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#2643]
As long as we are displaying this banner:
```
=====> PowerShell Integrated Console <=====
```
It would be more useful if it displayed this:
```
=====> PowerShell Preview Integrated Console v2020.4.2 <=====
```
or
```
=====> PowerShell Integrated Console v2020.4.0 <=====
```
I switch between four different computers and on some I use preview and others I use stable.  It would be nice to see which I'm using without having to look through my extensions list.  I know, first world problems.  :-)

**Comment by rkeithhill** [comment]
Any opinion on whether it should be `v2020.4.2` or `2020.4.2`?

**Comment by TylerLeonhardt** [comment]
I like it with the `v` personally :)
