### ISSUE TITLE
Install-VSCode nuget package project site link is broken

### ISSUE THREAD

**Issue by Tyriar** [PowerShell/vscode-powershell#2647]
Might just be because it hasn't been published in a while, but there's a broken link elsewhere.

**Comment by Tyriar** [comment]
Actually maybe this is correct:

https://github.com/PowerShell/vscode-powershell/blob/26d3821a5a0f60afa3eaddcd7b4290d02108bb0e/scripts/Install-VSCode.ps1#L60

Regardless, it needs to get released so this link works again:

![image](https://user-images.githubusercontent.com/2193314/79786358-2d336800-82fa-11ea-939f-fa3a297f416f.png)

**Comment by TylerLeonhardt** [comment]
It's the branch that doesn't exist anymore.

**Comment by TylerLeonhardt** [comment]
Yeah looks like I updated this a while back but haven't pushed it. I'll wait to see if anyone contributes the other issues before pushing this.
https://github.com/PowerShell/vscode-powershell/commit/9033f149b04f967853915964566e5a8c8f82eea0

**Comment by SydneyhSmith** [comment]
Closing as the fix has been made.
