### ISSUE TITLE
cannot read property onDidStop of null

### ISSUE THREAD

**Issue by sandy081** [PowerShell/vscode-powershell#265]
_From @maxcli on August 23, 2016 16:49_
- VSCode Version: 1.4.0
- OS Version: win 10 ver 1601
  
  I see error :   cannot read property onDidStop of null

Steps to Reproduce:
1.  debugging powershell, 
2. 

_Copied from original issue: Microsoft/vscode#10848_

**Comment by sandy081** [comment]
I wonder it could be related to the power shell extension on VS Code. I would suggest to check with the extension - https://github.com/PowerShell/vscode-powershell

Please reopen the issue if not so. Sorry for not being very helpful here.

**Comment by sandy081** [comment]
_From @maxcli on August 25, 2016 17:7_

i upgraded to 0.7.1 today. It actually makes it worse :-( 
The program hangs when I hit F5
I will open a new issue since you closed this one.

**Comment by rkeithhill** [comment]
@maxcli Can you zip up and attach the log files found under `$home\.vscode\extensions\ms-vscode.PowerShell-0.7.1\logs`.

**Comment by maxcli** [comment]
Keith,
 here is the zip you asked for
Thanks.

**Comment by daviwil** [comment]
@maxcli sorry, just realized there are two issues now :)  Looks like your attachment didn't show up on GitHub, can you come to this GitHub issue page and upload it directly?  Thanks!

**Comment by daviwil** [comment]
Hey @maxcli, can you try out today's update of the PowerShell extension (0.7.2) and see if the problem has been resolved?

**Comment by daviwil** [comment]
Closing due to no response.  @maxcli let us know if you still see this issue and we can reopen to investigate.
