### ISSUE TITLE
Completions while remoting are from local context

### ISSUE THREAD

**Issue by lookcloser** [PowerShell/vscode-powershell#2661]
### System Details

System Details Output
```
### VSCode version: 1.44.2 ff915844119ce9485abfe8aa9076ec76b5300ddd x64

### VSCode extensions:
ms-vscode-remote.remote-ssh@0.51.0
ms-vscode-remote.remote-ssh-edit@0.51.0
ms-vscode.notepadplusplus-keybindings@1.0.5
ms-vscode.powershell-preview@2020.3.0


### PSES version: 2.1.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When I use the integrated console with version 2020.4.0 of the extension, and I am connected to a remote server using PowerShell remoting, file path autocompletion does not run in the remote session.

I type "cd ", then the first few letters of the file path, then hit Tab, and nothing happens. I expect it to start autocompleting the file path when I hit Tab.

* File path autocompletion works when accessing the local file system (i.e. when not using remoting).
* It works when using remoting if I set "powershell.integratedConsole.useLegacyReadLine" to true.
* It also works when using remoting in the initial console that VS Code loads (as opposed to the "PowerShell Integrated Console").

This problem does not happen when using version 2020.3.0 of the extension.

I believe that this issue was introduced in the 2020.3.1-preview release, because it works for me in 2020.3.0-preview but not in 2020.3.1-preview.

The log entries for a successful use of autocompletion with 2020.3.0-preview look like this:
```
2020-04-24 08:59:57.925 -05:00 [VRB] StartReadLoop called while read loop is already running
2020-04-24 08:59:57.925 -05:00 [VRB] Attempting to execute command(s):

    prompt

2020-04-24 08:59:57.925 -05:00 [VRB] Session state changed --

    Old state: Ready
    New state: Running
    Result: NotFinished
2020-04-24 08:59:58.002 -05:00 [VRB] Session state changed --

    Old state: Running
    New state: Ready
    Result: Completed
2020-04-24 08:59:58.002 -05:00 [VRB] Execution completed successfully.
2020-04-24 08:59:58.003 -05:00 [VRB] Attempting to execute command(s):

    
            [System.Diagnostics.DebuggerHidden()]
            [System.Diagnostics.DebuggerStepThrough()]
            param()
            return [Microsoft.PowerShell.PSConsoleReadLine, Microsoft.PowerShell.PSReadLine2, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]::ReadLine(
                $Host.Runspace,
                $ExecutionContext,
                $args[0]) System.Threading.CancellationToken
```

Meanwhile, they look like this for 2020.3.1-preview:

```
2020-04-24 08:53:32.884 -05:00 [VRB] StartReadLoop called while read loop is already running
2020-04-24 08:53:32.884 -05:00 [VRB] Attempting to execute command(s):

    prompt

2020-04-24 08:53:32.888 -05:00 [VRB] Session state changed --

    Old state: Ready
    New state: Running
    Result: NotFinished
2020-04-24 08:53:32.971 -05:00 [VRB] Session state changed --

    Old state: Running
    New state: Ready
    Result: Completed
2020-04-24 08:53:32.971 -05:00 [VRB] Execution completed successfully.
2020-04-24 08:53:32.977 -05:00 [VRB] Attempting to execute command(s):

    __Invoke-ReadLineForEditorServices -CancellationToken System.Threading.CancellationToken

2020-04-24 08:53:47.898 -05:00 [VRB] Execution completed successfully.
```

### Attached Logs
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4530087/logs.zip)

**Comment by TylerLeonhardt** [comment]
This could be a PSReadLine bug. Can you try downgrading to the latest stable PSReadLine:

Just to get you unblocked... you can remove this folder:

```
C:\Users\[YOUR USER]\.vscode\extensions\ms-vscode.powershell-2020.4.0\modules\PSReadLine\
```
> NOTE: If you're on insiders it's `\.vscode-insiders\`

If your console doesn't give you syntax highlighting, simply reinstall PSReadLine the normal way:

```pwsh
Install-Module PSReadLine -Force -AllowClober
```

**Comment by lookcloser** [comment]
If I remove the PSReadLine directory and restart VS Code, then the integrated console reverts to using the default PSReadLine 2.0.0, and autocomplete starts working again.

However, if I put the PSReadLine directory in my ~\Documents\WindowsPowerShell\Modules directory and then launch Windows Terminal or the legacy PowerShell command line app, they load version 2.1.0 of PSReadLine and are still able to perform file path autocompletion when using remoting.

This makes me think that it may be an interaction between the newer PSReadLine and this extension, rather than a bug in the newer PSReadLine per se.

**Comment by andschwa** [comment]
I know the bot closed this due to inactivity, but I wanted to point out that the latest extension bundles PSReadLine 2.1.0, and will also no longer attempt to load other versions of PSReadLine on the system. So if this issue still repros with the latest extension, that would be good to know!

**Comment by lookcloser** [comment]
I just tested with 2021.8.0 and this problem is still happening.

I am not sure why this issue is marked as needing repro info. As far as I can tell, this issue shows up whenever you attempt to use autocompletion in a remoting session. I don't think it's necessary to do anything special to reproduce it.

**Comment by andschwa** [comment]
Good to know! Thanks for the update. Sorry, I updated the bot and allowed it to close inactive issues marked "Needs: Repro Info" and then learned a lot of issues hadn't had that label properly removed. Live and learn 🤷

**Comment by apurvparekh30** [comment]
Did anyone find solution to this issue?

**Comment by lookcloser** [comment]
It looks like the 2022.5.0 release has fixed this problem: the integrated console is once again suggesting file paths on the remote computer when using remoting.

I believe that this issue can be closed, but leaving it open in case anything else needs to be done here.

**Comment by andschwa** [comment]
Woo-hoo! Thanks @lookcloser.
