### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Imannurein** [PowerShell/vscode-powershell#2669]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2020.4.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rjmholt** [comment]
Hi @Imannurein, would you be able to attach any details of the bug you'd like to report to your issue here by replying or editing your original issue description?
