### ISSUE TITLE
Use a customized rule (PowerShell script) with PSScriptAnalyzer ?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/vscode-powershell#267]
Is it possible to use a customized rule (PowerShell script) with PSScriptAnalyzer and VsCode ?
Or is it preferable to use rules written in C# ?

**Comment by rkeithhill** [comment]
At this point in time, the extension doesn't allow you to specify a path for `-CustomRulePath` which is how you'd supply your custom rules to Invoke-ScriptAnalyzer.  Ditto for `-RecurseCustomRulePath`.  It would be nice if this could be specified in the settings file but right now that only accepts the keys `ExcludeRules`, `IncludeRules` and `Severity`.

**Comment by daviwil** [comment]
@kapilmb is working on a new way for PSScriptAnalyzer to load settings which should support all of the parameters Invoke-ScriptAnalyzer can take.  Hopefully we'll have that in for 0.8.0!

**Comment by daviwil** [comment]
Hey @kapilmb, is it possible to include a custom script-based rule using the new settings file work you did?  Do you have an example of that somewhere?

**Comment by kapilmb** [comment]
As of now, PSSA settings file does not support have the `CustomRulePath` field. However, after its inclusion in PSSA settings file, VSCode should be able to run custom rules. I will create a issuse PSSA repo to track this issue.

**Comment by kapilmb** [comment]
here is the issue PowerShell/PSScriptAnalyzer#675

**Comment by bergmeister** [comment]
You can specify `CustomRules` in the settings file but currently there is  this feature (or bug, not sure) that using CustomRules, the default rules are disabled.

**Comment by LaurentDardenne** [comment]
@bergmeister  Thank you :-)
I try this with VSCode.

**Comment by LaurentDardenne** [comment]
It works with this [prototype](https://github.com/LaurentDardenne/ParameterSetRules) :
![image](https://user-images.githubusercontent.com/4894452/38238928-ae2e4294-372b-11e8-9ed5-8a6a7580777c.png)
In the file ''C:\Users\Laurent\AppData\Roaming\Code\User\settings.json'' I changed the entry _"powershell.scriptAnalysis.settingsPath":".//ScriptAnalyzerSettings.psd1"_
I still have a doubt about the location of this parameter file with regard to the files opened in VSCode.

I test again before closing.

**Comment by LaurentDardenne** [comment]
We can use the global or local configuration file (settings.json) of the project (Workspace) but once declared the global file, the local file is not taken into account.
This seems exclusive.
