### ISSUE TITLE
Can't run Pester Tests in PowerShell Extension

### ISSUE THREAD

**Issue by randyram-at-ms** [PowerShell/vscode-powershell#2673]
Issue Type: <b>Bug</b>

From a file with a Pester test, hit Run tests:

```
Invoke-Pester : A parameter cannot be found that matches parameter name 'Show'.
At C:\Users\<deleted>\.vscode\extensions\ms-vscode.powershell-2020.4.0\InvokePesterStub.ps1:137 char:113
+ ... Option @{IncludeVSCodeMarker=$true} -TestName $TestName -Show $pester ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Pester], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Invoke-Pester
```
PS> 

Extension version: 2020.4.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (15.10GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by randyram-at-ms** [comment]
3.4.0

**Comment by SydneyhSmith** [comment]
@randyram-at-ms looks like you are using an older version of Pester, are you able to update to the latest version and see if this issue still repros? This will help us determine if the cause is specific to this version of the module

**Comment by randyram-at-ms** [comment]
I could… but I’m using RTM Windows 10 Enterprise Version 1909, build 18363.778 and simply using the powershell that comes with that Windows build.
Seems you’d want to avoid people having to upgrade powershell to fix this – it was working fine for me a month ago so there’s clearly an issue with the vscode-powershell upgrade on my box.

Still willing to update powershell if it helps you debug.

**Comment by TylerLeonhardt** [comment]
Well the ask was to just update Pester, not PowerShell itself.

This will update to the latest v4 of Pester.
```pwsh
Install-Module -Name Pester -Force -MaximumVersion 4.99.99
```

That should unblock you though I'm not sure how compatible v3 Pester tests are for v4.

I think we just need to not include the `-Show` parameter for v3 Pester:
https://github.com/PowerShell/vscode-powershell/blob/master/InvokePesterStub.ps1#L109

**Comment by TylerLeonhardt** [comment]
Actually if you wanna just update the script here:

```
$HOME\.vscode-insiders\extensions\ms-vscode.powershell-2020.4.0\InvokePesterStub.ps1
```

to not include the `-Show` parameter in any of the `Invoke-Pester` calls... that should unblock you too.

**Comment by rkeithhill** [comment]
Heh, I thought at the time we did this that teasing out this logic into an accessible PS script would come in handy.  :-)
