### ISSUE TITLE
Extension must not steal focus on load

### ISSUE THREAD

**Issue by FallenGameR** [PowerShell/vscode-powershell#2677]
**Summary of the new feature**

When VS Code starts it loads Powershell extension if it is enabled. On load it starts new terminal and terminal window pops up stealing focus. It should not do that. I want to edit the code and I want the code editor to be in the focus. Instead I have to close the terminal window every time extension is loaded. It is so annoying I tend to disable the extension altogether when I'm writing Powershell code.

**Proposed technical implementation details (optional)**

If you need to open terminal for the extension to work, do that in background. Or provide some option that would instruct the extension how it should start.

**Comment by rkeithhill** [comment]
There is a setting for this already:

![image](https://user-images.githubusercontent.com/5177512/81003672-74e0e600-8e08-11ea-9778-703aff7a460f.png)

When this setting is not checked, the integrated console is still created so that various editor features like completions work but the console is not shown and therefore won't steal focus.

**Comment by rjmholt** [comment]
I think there's been some discussion of the various configurable subtleties of the integrated console in other issues too. In particular, should the console:

1. Appear and be in focus
2. Appear but not be in focus
3. Not pop up, but be added to the list of terminals
4. Be completely hidden

(I may have missed some choices, and I'm not sure which are not possible today in VSCode)

So we may want to deduplicate this request to one of the other issues that discusses this; configuring for (3) or (4) may not perfectly satisfy the request for (2).

**Comment by rkeithhill** [comment]
The option I've shown above implements #4 - PSIC is completely hidden **until** you start a debug session.  After the debug session ends, PSIC does not hide again.  So yeah, there are some subtleties here that need some work.  :-)
