### ISSUE TITLE
"Disable ISE mode" reverts to default instead of previous settings

### ISSUE THREAD

**Issue by borisimple** [PowerShell/vscode-powershell#2683]
When we disable ISE mode, it will revert VS Code to it's default settings.
It would be nice if when we disable it, it goes back to the previous settings, and not the default ones.

### Example:

- I am using a theme called "One Dark Pro"
- I am enabling PowerShell ISE
- When finished with my work, I am disabling ISE mode
- **My theme is back to default theme (Dark+) and not my preferable/previous one**

**Comment by corbob** [comment]
I think this is a duplicate of #2527

It's something I took a look at and got sidetracked with my myriad of other projects 😬

**Comment by TylerLeonhardt** [comment]
I'm just curious... Why are you disabling ISE Mode?

The intent of ISE Mode was to give users who are afraid of vscode a way to use a simpler experience.

If you don't need an simpler experience, then you can pick and choose the settings you want to keep from ISE Mode by either turning it on and removing the ones you don't want

Or

Read our doc that breaks down the settings that ISE Mode applies and add the ones you want:

aka.ms/isecompat

**Comment by borisimple** [comment]
It seems that this is identical to #2527.

@TylerLeonhardt I am not using PowerShell all the time, but when I do, I find this ISE mode pretty nice! Most of my work is done in AL (Business Central), and PowerShell is needed for some communication with Docker containers.

I am closing this as it's a duplicate request.
