### ISSUE TITLE
Integrated Terminal displayed spurious characters

### ISSUE THREAD

**Issue by gabrielmccoll** [PowerShell/vscode-powershell#2694]
Issue Description
=====
When I type in in the integrated terminal I get nonsense from other repos that were open at one point etc.  Screens should show it. in the picture with p[36,5 only the p is actually typed the rest is display nonsense. it doesn't actually go through if I hit return. 
I am experiencing a problem with...

![image](https://user-images.githubusercontent.com/25871665/81802884-ca0aaf00-950e-11ea-9b61-fd600668d550.png)
![image](https://user-images.githubusercontent.com/25871665/81802973-e9094100-950e-11ea-9b49-21f52c5917f8.png)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.  

This link didn't work sorry

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 6.1.7601 |  (Windows 7 VDI)
| VSCode | 1.45.0|
| PowerShell Extension Version | 2020.4.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.14409.1018|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.14409.1018|
|BuildVersion|10.0.14409.1018|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.11|
|azure-pipelines|ms-azure-devops|1.165.1|
|markdown-mermaid|bierner|1.5.0|
|mermaid-export|Gruntfuggly|0.0.8|
|mermaid-markdown-syntax-highlighting|bpruitt-goddard|1.0.2|
|powershell|ms-vscode|2020.4.0|
|team|ms-vsts|1.161.0|
|vscode-mermaid-editor|tomoyukim|0.5.0|
|vscode-mermaid-preview|vstirbu|1.5.2|
|vscode-sprint-planner|ipatalas|0.4.0|

**Comment by SydneyhSmith** [comment]
@gabrielmccoll thanks for opening this issue, it looks like it is the same issue as #2640 , the workaround is here: https://github.com/PowerShell/vscode-powershell/issues/2637#issuecomment-615430305 the fix should be available in the next stable release of the extension (this may also already be resolved in the latest update to the preview extension)

**Comment by gabrielmccoll** [comment]
Ah thanks ! I actually only searched for open issues so there probably why I missed it
