### ISSUE TITLE
Editor hangs /run selection stops working

### ISSUE THREAD

**Issue by Lysakers** [PowerShell/vscode-powershell#2699]
Issue Description
=====

I am experiencing a problem running selected code in editor pane.
It usually works flawless for the first 20-50 runs, after that F8 gives no respons and "run selection" gives no respons.
This issue has started happening the last week.

Attached Logs
=====

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4626940/logs.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.45.0|
| PowerShell Extension Version | 2020.4.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.752|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.752|
|BuildVersion|10.0.18362.752|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.1.2|
|code-settings-sync|Shan|3.4.3|
|powershell|ms-vscode|2020.4.0|
|vscode-icons|vscode-icons-team|10.1.1|

**Comment by PrzemyslawKlys** [comment]
Related: https://github.com/PowerShell/vscode-powershell/issues/2695

**Comment by SydneyhSmith** [comment]
Thanks @PrzemyslawKlys going to dupe this one back to your meta-issue #2627
