### ISSUE TITLE
PowerShell extension cannot be upgraded cleanly

### ISSUE THREAD

**Issue by gerane** [PowerShell/vscode-powershell#27]
I had multiple windows open. The editor I updated the Powershell Extension in only had xml files loaded in the open window and the working files section. I had a second window open with a .bat file in the editor and an assortment of files in the working files section. A few being ps1 files. I am unsure if the Powershell editor services will still be loaded/locked if there are files in the working files section or not.

I updated the extension and it reloaded the current editor with the xml files. At this point the extension plugin stopped working and could no longer load extensions. I then relaunched the editor and I started getting errors where the extensions plugin was crashing. A second restart cleared this up, but the Powershell plugin was left in a broken state. What was left in the directory was the following:

.vsixmanifest
bin --> Microsoft.PowerShell.EditorServices.dll
      --> Microsoft.PowerShell.EditorServices.Host.DebugAdapter.cmd
      --> Microsoft.PowerShell.EditorServices.Host.exe
      --> Microsoft.PowerShell.EditorServices.Protocol.dll

I am assuming the second open editor kept the Editor Services locked and broke the update. @daviwil we talked about the log maybe being the culprit, but I did not have the editor services log still loaded in cmtrace, so that was not what had the lock. 

Should VS Code require a full restart before fully updating it's plugins instead of just the currently open editor? If we compare VSCode to Atom, I believe Atom requires a complete restart. When you use the Restart prompt presented by a extension install or update, it only restarts the current window and not all windows. I am unsure if this would be something this plugin should fix or VS Code itself.

I can try to find some more logs if you need, I didn't see any at first glance since I had restarted the editor so many times. I am also going to try to reproduce this in a few different ways later when i have more time.

**Comment by daviwil** [comment]
Thanks for filing this!  I experienced the same problem when I tried to upgrade yesterday.  This is something that VS Code has to help with and they already having a bug tracking the issue:

https://github.com/Microsoft/vscode/issues/537

**Comment by daviwil** [comment]
This issue will be fixed with the next update of VS Code and the fix to this issue:

https://github.com/PowerShell/PowerShellEditorServices/pull/70

If after that you still see it we can reopen this bug and investigate some more.
