### ISSUE TITLE
PowerShell Preview 2020.5.0 - References GUI doesn't seem to show things properly

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2701]
Issue Description
=====

I am experiencing a problem with...references GUI not showing references.

![image](https://user-images.githubusercontent.com/15063294/81984393-02a4a880-9635-11ea-8292-af2263f5ef11.png)

Confirmed in both VSCode and VSCode Insiders.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.45.1|
| PowerShell Extension Version | 2020.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.752|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.752|
|BuildVersion|10.0.18362.752|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.1.3|
|code-settings-sync|Shan|3.4.3|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.1|
|material-icon-theme|PKief|4.1.0|
|powershell-preview|ms-vscode|2020.5.0|
|project-manager|alefragnani|10.12.0|
|vscode-markdownlint|DavidAnson|0.35.1|
|vscode-pull-request-github|GitHub|0.16.0|
|vscode-toggle-quotes|BriteSnow|0.3.2|
|vscode-wakatime|WakaTime|4.0.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by TylerLeonhardt** [comment]
Does your file path have any odd characters in it by chance?

**Comment by PrzemyslawKlys** [comment]
nope. English only. Tested on multiple files/different modules.

**Comment by PrzemyslawKlys** [comment]
I even went ahead and copied it to C:\Module\ and still the same.

**Comment by TylerLeonhardt** [comment]
Yep I can repro this.

**Comment by TylerLeonhardt** [comment]
I've got a fix for this.
