### ISSUE TITLE
Comparison operator help tooltip

### ISSUE THREAD

**Issue by serivas** [PowerShell/vscode-powershell#2706]
**Summary of the new feature**

PowerShell ISE provides useful tooltips (especially for beginners) for comparison operators and other basic syntax that can be confusing or easy to forget for people (like me) who don't actively use PowerShell frequently but who may need more complex scripts.

Reproduce:

Type "Get-Process | Where-Object{$_.ID -" and you'll see, in both VSCode and ISE, a list of comparison operators. Difference is, in ISE you get a nice explanation of what the operators do, unlike in VSCode where you only get the list and a constant tooltip about "Where-Object" instead.

**Comment by TylerLeonhardt** [comment]
I have a PR out for this now. We were filtering them out on accident.
