### ISSUE TITLE
Add options for reducing intellisense sensitivity

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/vscode-powershell#2707]
**Summary of the new feature**

I feel that the intellisense feature gets in my way more frequently in VS code than in the ISE.
There's 3 situations where I feel it gets in my way:

1. Whenever I type in a keyword like "foreach" or "process" (inside a function).

The irrelevant suggestions are distracting and when I want to go to the next line I first have to press escape to close the intellisense window.

2. Whenever I'm typing an unquoted path as a parameter value.

The irrelevant suggestions are distracting. If I didn't start with a quote then it's because I know the path doesn't contain a space, so when I press space I'm moving on to the next parameter/command. Even if I wasn't sure I would have typed something reasonably close and pressed tab instead of space to auto complete to that path.

3. Whenever I'm typing in a command.

The irrelevant suggestions are distracting. When the intellisense list shrinks down to 1 it's a quick visual cue to say you've typed enough to tab complete to your desired command but you need to do a lot more typing to get to that point in VS code. IMO the naming scheme used for commands in Powershell makes the fuzzy text searching for commands/parameters unnecessary.

**Proposed technical implementation details (optional)**

The first issue could be fixed with an option for not invoking the completion automatically until you type in the first "-" in a command (Get-, Set-, etc.) I think the ISE did it this way.

The second issue could be fixed with an option for stopping all suggestions after the first space in an unquoted parameter value.

The third issue could be fixed by having an option to use whatever algorithm the ISE used to find intellisense suggestions.

**Comment by TylerLeonhardt** [comment]
Can you elaborate on the "irrelevant completions"?

Also, the fuzzy completions is our of our control and is a vscode feature. If you want to be able to disable the fuzzy completions, give this issue a +1!:
https://github.com/microsoft/vscode/issues/64367

Also I usually have my `"editor.snippetSuggestions"` set to... Bottom I think it is... So that the snippets are always on the bottom of the list. You can also get rid of them all together if you want.

Lastly, the ISE and vscode use the exact same API for completions. The only difference is _when the trigger_ and how the client filters them out (obviously vscode has fuzzy completions being a client difference)

**Comment by MartinGC94** [comment]
@TylerLeonhardt Irrelevant suggestions are just any suggestions that are too far away from what I actually had in mind. I don't want commands when I'm thinking about keywords. I don't want additional path suggestions when I'm thinking about the next parameter/command. I don't want commands like "Get-VMSwitchExtension" when I've typed in "Get-Chi".

VS code can't read my mind to know what I feel is/isn't relevant, but it can stop making suggestions before it has a good idea of what I want and it can assume I know how to spell simple command names.

Thanks for finding that issue, I've upvoted it but it's from 2018 and it's in the Backlog milestone so I guess I'll have to wait a long time before I see this feature.

Thanks for the explanation about the API, does this extension control the trigger? Would it be possible to not trigger it in a command/parameter context until the first "-"?

**Comment by TylerLeonhardt** [comment]
> Would it be possible to not trigger it in a command/parameter context until the first "-"?

I see that you suggest this to not include so many things in the intellisense list but how will completions work for anything that doesn't contain a dash? What if I'm working in a script that has some functions in it that aren't going to be exported like: `getAuthToken` or `sortMyComplexObject`? Then those won't show up unless you manually trigger with Ctrl+Space.

That would be confusing for customers that expect intellisense to "just work when typing". I want to be able to help you and the customers that don't have the same expectation but I'm not sure we can at the extension level.

**Comment by MartinGC94** [comment]
The list would not show unless manually activated but you could still press tab to complete, so in case of "sortMyComplexObject" I would just type "sortm<tab>". That's the experience people see in the actual console and it's how the ISE did it so I don't think it would be a problem for the average Powershell user.

Maybe it shouldn't be the default experience, but I don't see why it couldn't be an option like every other setting VS code and this extension offers. (Assuming of course enough people are interested to justify the development time).

**Comment by TylerLeonhardt** [comment]
Actually looks like vscode already can do this. Try:

```jsonc
// TURN OFF AUTOCOMPLETION
// Controls if quick suggestions should show up or not while typing
"editor.quickSuggestions": false,
```
and
```jsonc
// Controls if suggestions should automatically show up when typing trigger characters
"editor.suggestOnTriggerCharacters": false,
```

I found this on:
https://ourcodeworld.com/articles/read/505/how-to-disable-autocompletion-and-intellisense-in-microsoft-visual-studio-code

I don't think we need to do anything in this extension given these settings.

**Comment by MartinGC94** [comment]
Wow editor.quickSuggestions works perfectly, thank you. When I first read the name and description of that setting I thought it would disable automatic intellisense completely but it works exactly like I wanted it to and starts suggesting stuff after the first "-".

This solves issue 1 and half of issue 3 (the other half will be fixed when fuzzy search can be disabled). Issue 2 is such a minor issue that I can live with that + disabling fuzzy search would fix that issue in most situations so I feel like this issue can be closed.

**Comment by TylerLeonhardt** [comment]
Glad to hear!
