### ISSUE TITLE
PSScriptAnalyzer settings path isn't being passed along

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#271]
It appears that we might not be passing along the `powershell.scriptAnalysis.settingsPath` setting to PSScriptAnalyzer in the language service.  This is likely caused by the recent changes to our PSScriptAnalyzer integration so I'll just need to wire that back up.

**Comment by kilasuit** [comment]
Just to add I was making use of the settings.json that pops up when you click through the UI to User Settings and it seems just this setting doesn't seem to be "sticking" through.

Also for clarification if this was to be changed whilst VSCode is open would that then take instant effect (like adding keys or changing the integrated terminal does) or would it require for VSCode to be closed completely to take effect?

**Comment by daviwil** [comment]
If you change the VS Code setting which specifies the Script Analyzer settings path, the change will be reflected immediately.  However if you change the contents of your settings file, it won't be reflected until you change the code in one of your files again.  This is because we aren't watching the contents of the settings file (yet).

I have a fix for this issue, will go out with the 0.7.2 release on Friday!
