### ISSUE TITLE
When starting a debug session, the Terminal window is pasted with previous, obsolete content

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/vscode-powershell#2714]
When I start a debugging session on a PowerShell script in Visual Studio Code, the Terminal window blinks some trash screen buffer content, depicting some obsolete terminal content, before the Terminal window is getting cleared.

Most of the time that garbage content shows errors from a previous debugging session, so I regularly get a heart attack when I start a debugging session.

Here's a short screencast, depicting the issue:

![PowerShell extension doesn't correctly clear terminal window when debugging starts](https://user-images.githubusercontent.com/9283914/82391872-bc8b8280-9a42-11ea-84b8-b0ba25f9b5c7.gif)

I'm not sure if I'm right here, probably I need to report to the PowerShell or the Visual Studio Code team? Please advise if so.

**Comment by corbob** [comment]
It looks like you're using a temporary session for debugging, so the flash looks like it's when the old session is being closed and a new one opened (notice the terminal changes to number 1 which looks like). I suspect you won't see this error by disabling the temporary session for debugging, and can work around it by switching to the other session and clearing the buffer.

**Comment by SetTrend** [comment]
Ahh, thanks for clarifying! 👍

I disabled the temporary session option now. And when I need to enable it later again I will know about the consequences.

Perhaps one note: I couldn't find documentation on _why_ it should be handy to use this option. What would be the consequences of keeping this option disabled? What could happen incidentally?
