### ISSUE TITLE
[Preview 2020.5.0] The PowerShell session has terminated due to an error

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2717]
Issue Description
=====

I am experiencing a problem with... error.

![image](https://user-images.githubusercontent.com/15063294/82695534-9691f800-9c65-11ea-8fd6-497310114958.png)

This is the first time it happened for me since a while. Not reproducible yet. Feel free to close if logs don't have anything useful. 

Attached Logs
=====

[1590169710-eba46535-4219-421f-b832-bbf600d6267f1590152987154.zip](https://github.com/PowerShell/vscode-powershell/files/4669574/1590169710-eba46535-4219-421f-b832-bbf600d6267f1590152987154.zip)

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.45.1|
| PowerShell Extension Version | 2020.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.1|
|BuildVersion|10.0.19041.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.1.3|
|code-settings-sync|Shan|3.4.3|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.1|
|grammarly|znck|0.12.1|
|markdown-all-in-one|yzhang|2.8.0|
|material-icon-theme|PKief|4.1.0|
|powershell-preview|ms-vscode|2020.5.0|
|project-manager|alefragnani|11.0.1|
|vscode-markdownlint|DavidAnson|0.35.2|
|vscode-pull-request-github|GitHub|0.16.0|
|vscode-toggle-quotes|BriteSnow|0.3.2|
|vscode-wakatime|WakaTime|4.0.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by SydneyhSmith** [comment]
Thanks @PrzemyslawKlys there unfortunately doesnt seem to be a crash captured in the logs..if you see this again could you please upload another set of logs? thanks!

**Comment by PrzemyslawKlys** [comment]
Sure, let me close this one for now, as I believe the work on the other issue is fixing some possible crashes I had.
