### ISSUE TITLE
ISE Theme hides input boxes in settings menu

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/vscode-powershell#2718]
This is what the "default language" setting looks in it's default state in the ISE theme:

![image](https://user-images.githubusercontent.com/24977523/82719456-cbf41100-9c78-11ea-8bef-1910c9a3f273.png)

The input box is still there, if you click it you can type:

![image](https://user-images.githubusercontent.com/24977523/82719469-dca48700-9c78-11ea-880e-8988dfcacab9.png)

Here's what it looks like in default dark:

![image](https://user-images.githubusercontent.com/24977523/82719480-ee862a00-9c78-11ea-94b5-3e2d37cee397.png)

**Comment by TylerLeonhardt** [comment]
lol
