### ISSUE TITLE
Syntax highlighting problem with ValidateScript parameter attribute

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#272]
# Issue
The `[ValidateScript({ ... })]` parameter attribute is commonly used to perform customized validation on parameter values that a caller passes into a PowerShell function. In Visual Studio Code `1.4.0`, running on Windows 10 Anniversary Update, with version `0.7.1` of the PowerShell extension, the syntax highlighting inside this parameter attribute is incorrectly handled.

![image](https://cloud.githubusercontent.com/assets/466713/18104457/691a4514-6eb8-11e6-95ee-646bd7f8c3cf.png)

# Expected Result

The syntax highlighting should work consistently both inside and outside of a `[ValidateScript({ ... })]` parameter attribute.

**NOTE**: This issue was previously reported, fixed, and then closed #262 

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by rkeithhill** [comment]
@pcgeek86 Can you submit this on the http://GitHub.com/powershell/editorsyntax project?  That is the project that tracks the syntax highlighting for PowerShell in VSCode, as well as other editors.

**Comment by pcgeek86** [comment]
Closing this issue. Please use this one instead: https://github.com/PowerShell/EditorSyntax/issues/17
