### ISSUE TITLE
Terminal inconsistent and sometimes hangs after repeated runs with F8

### ISSUE THREAD

**Issue by vllama** [PowerShell/vscode-powershell#2720]
Issue Description
=====

I am experiencing a problem with the terminal window after running code selections ( using F8)
After a while F8 stops working and the terminal window has a new line that looks like this after the prompt. The words "fwd-i-search: _" appear on the new line after the prompt line.

Usually I have to kill the terminal to recover.
```
PS C:\Projects\powershell>
fwd-i-search: _
```

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.45.1|
| PowerShell Extension Version | 2020.4.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.752|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.752|
|BuildVersion|10.0.18362.752|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azurerm-vscode-tools|msazurermtools|0.10.0|
|mssql|ms-mssql|1.9.0|
|powershell|ms-vscode|2020.4.0|
|remote-wsl|ms-vscode-remote|0.44.2|
|vscode-antlr4|mike-lischke|2.2.3|
|vscode-dotnet-runtime|ms-dotnettools|0.1.2|

**Comment by PrzemyslawKlys** [comment]
Your problem is described here: https://github.com/PowerShell/vscode-powershell/issues/2627

It is being worked on. Duplicate.
