### ISSUE TITLE
Code formatting not working properly

### ISSUE THREAD

**Issue by itfranck** [PowerShell/vscode-powershell#2724]
Issue Type: <b>Bug</b>

Create a new powershell file.

Add the following statement
```

$CustomerInfos = @{
       CustomerName = 'Customer'  
    CustomerID   = 'abcd'
}

$CustomerInfos = @{
       CustomerName            = 'Customer'  
    CustomerID   = 'abcd'
}

```
Format the document or save the document (if settings are set to format on save)
CustomerName should be indented properly after the format document command is issued.
It does not happens. 

That being said, the equals signs get aligned and extra spaces are removed, as expected. 

The issue only happens with Powershell Preview.
If only Powershell is enabled (or both extensions) then the formatting occurs properly, which seems to indicate that both Powershell extension (stable) and PSScriptAnalyzer are not a fault. 

This happens in both VSCode and VSCode Insiders. 
I also formatted my computer (for unrelated reasons) and experience the same issues .

Relevant formatting settings for reference.
```
 "powershell.codeFormatting.ignoreOneLineBlock": true,
    "powershell.codeFormatting.openBraceOnSameLine": true,
    "powershell.codeFormatting.newLineAfterCloseBrace": true,
    "powershell.codeFormatting.newLineAfterOpenBrace": true,
    "editor.formatOnType": false,
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
```

Extension version: 2020.5.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3570)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (22.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ili101** [comment]
It's Probably this https://github.com/PowerShell/PSScriptAnalyzer/issues/1508 (Use the workaround setting from there)

@SydneyhSmith is there a way to leave some trace of the tickets moved to other repos here?
Because what happen to me (and probably @itfranck) is that we search here, don't find it and open a duplicate. Maybe instead of moving the issue, duplicate to the other repository and close the original with a link to the one in the other repo (Don't know if it's possible just throwing it out there, there is probably a better solution)

**Comment by itfranck** [comment]
Indeed, the issue is the PipelineIndentationStyle. 
The link provided solved my issue. 

There's at least an issue already (closed) regarding this problem in this repository already:
https://github.com/PowerShell/vscode-powershell/issues/2696

https://github.com/PowerShell/vscode-powershell/issues/2696#issuecomment-628199121
