### ISSUE TITLE
Process is terminated due to StackOverflowException

### ISSUE THREAD

**Issue by Firmbyte** [PowerShell/vscode-powershell#2727]
### System Details

I couldn't get the output from the command because vs code keeps crashing....
here's what I gathered manually:
vs code 1.45.1
ms-vscode.powershell-2020.4.0

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/4695535/logs.zip)

```

### Issue Description

VS Code keeps crashing with error: Process is terminated due to StackOverflowException.

#### Expected Behaviour

-- Description of what *should* be happening --

#### Actual Behaviour

![image](https://user-images.githubusercontent.com/8867903/83143141-1a5d4180-a0b7-11ea-820b-7c5c9594ddbd.png)


### Attached Logs

**Comment by SydneyhSmith** [comment]
Thanks @Firmbyte looks like this is the same error as this issue https://github.com/PowerShell/vscode-powershell/issues/2609 likely a duplicate cause...did you notice anything different about the issue this time? Thanks again!

**Comment by Firmbyte** [comment]
Sydney,
In this case VS Code is running on my Windows 10 laptop and it's different
version of VS Code. It's also occurring in a permanent cycle, ie it
crashes, it restarts, it crashes. On the Windows 2012 R2 server where I'd
the similar problem, it wasn't occurring so frequently.

Regards,
*Iain Barnetson*
