### ISSUE TITLE
Debugger crashes after multiple runs.

### ISSUE THREAD

**Issue by antonyoni** [PowerShell/vscode-powershell#273]
Versions:
VSCode: 1.4.0
OS: Windows 10.1607
Extension: 0.7.1

After running the debugger multiple times, there is a 'powershell has stopped working' error:
![vscode-error-3](https://cloud.githubusercontent.com/assets/17799601/18108008/471076c4-6f02-11e6-885e-3800eccc60ee.png)
and the following in the Console:
```
[Extension Host] Uncaught Exception:  Error: read ECONNRESET
[Extension Host] Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at TCP.onread (net.js:552:26)
read ECONNRESET: Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at TCP.onread (net.js:552:26)
[Extension Host] powershell.exe terminated with exit code: 2
[Extension Host] rejected promise not handled with 1 second
This socket is closed.: Error: This socket is closed.
    at Socket._writeGeneric (net.js:648:19)
    at Socket._write (net.js:700:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Socket.Writable.write (_stream_writable.js:215:11)
    at Socket.write (net.js:626:40)
    at StreamMessageWriter.write (C:\Users\Antony\.vscode\extensions\ms-vscode.PowerShell-0.7.1\node_modules\vscode-jsonrpc\lib\messageWriter.js:22:23)
    at C:\Users\Antony\.vscode\extensions\ms-vscode.PowerShell-0.7.1\node_modules\vscode-jsonrpc\lib\main.js:195:31
    at Object.connection.sendRequest (C:\Users\Antony\.vscode\extensions\ms-vscode.PowerShell-0.7.1\node_modules\vscode-jsonrpc\lib\main.js:186:20)
    at Object.result.shutdown (C:\Users\Antony\.vscode\extensions\ms-vscode.PowerShell-0.7.1\node_modules\vscode-languageclient\lib\main.js:48:51)
```

Once this happens I get a 'Debuger adapter process has terminated unexpectedly' error when debugging further:
![vscode-error-2](https://cloud.githubusercontent.com/assets/17799601/18107962/1b8c895c-6f02-11e6-8266-55e6b2d283b7.png)

This issue occurs on two separate machines with the same versions of everything. Only started happening after update to extension version 0.7.1.

Can be fixed by restarting vscode.

**Comment by daviwil** [comment]
Hey @antonyoni, can you zip up the following folder and e-mail it to me, `daviwil [at] microsoft.com`:

`$HOME\.vscode\extensions\ms-vscode.PowerShell-0.7.1\logs`

Thanks!

**Comment by daviwil** [comment]
Could be related to this issue: https://github.com/PowerShell/vscode-powershell/issues/243

**Comment by gpuido** [comment]
I experience the same bug, I'll send you my logs.

**Comment by antonyoni** [comment]
I've just sent the logs. I also noticed some strange behaviour where not all expected output is showing in the Debug Console. If I run the following:

```
Write-Host "line 1"
#Write-Warning "warning 1"
#Write-Error "error 1"
Write-Host "line 2"
```

I get nothing in the output console. Uncommenting the warning still produces nothing. If the warning and error are uncommented, then I get everything including the error, but not "line 2". Stdout not getting flushed?

I don't think this was happening with 0.6.1.

Not sure if it's related to [PowerShellEditorServices#138](https://github.com/PowerShell/PowerShellEditorServices/issues/138)

**Comment by rkeithhill** [comment]
I've seen this as well on 0.7.1.  If you set a breakpoint on line 1 and step over it, you'll see its output.  But when you stop over the last line, you probably won't - at least I don't.  Seems like a flushing issue as you will see the outputting while stepping but if the script executes fast enough, there is no output.

**Comment by alex-hempel** [comment]
I'm experiencing the same issue on the same config, although it's been like that for me since 0.7.0.

**Comment by daviwil** [comment]
Thanks for sending your logs, guys, I am looking at them now.

@antonyoni: You're right, the output issue is related to the one you found.  Need to investigate that as well.

**Comment by daviwil** [comment]
I think I fixed the problem!  Filed an issue on the PowerShellEditorServices repo to track it: https://github.com/PowerShell/PowerShellEditorServices/issues/284

New release with the fix within 24 hours!

**Comment by bughit** [comment]
Why isn't 0.6.2 on the releases page?

**Comment by daviwil** [comment]
Sometimes I just forget to do it :/ For this release I'm going to put together a script to automate the release uploads on GitHub so that they're always available.

**Comment by antonyoni** [comment]
@daviwil that's fixed it - haven't had to restart vscode yet today. thanks!

**Comment by daviwil** [comment]
Excellent, thanks a lot for confirming!  Please let me know if you hit another crash, I've added some additional logging which should help diagnose future issues.
