### ISSUE TITLE
Troubleshooting does not mention log file location on Windows

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/vscode-powershell#2731]
Issue Description
=====
I am experiencing a problem with documentation.

In ./vscode-powershell/docs/troubleshooting.md, the section on Providing Information About Your Environment does not describe locations in the Windows environment.

Making this change would increase the probability that the Windows user would more quickly and successfully attach their log files.

These are mentioned:
```
$HOME/.vscode[-insiders]/extensions/ms-vscode.powershell-<version>/logs/
$HOME/.vscode[-insiders]/extensions/ms-vscode.powershell-preview-<version>/logs/
$HOME/vscode/extensions/ms-vscode.powershell-2019.5.1/logs
```
It should also mention:
```
%USERPROFILE%\.vscode[-insiders]\extensions\ms-vscode.powershell-<version>\logs\
%USERPROFILE%\.vscode[-insiders]\extensions\ms-vscode.powershell-preview-<version>\logs\
%USERPROFILE%\.vscode\extensions\ms-vscode.powershell-2020.4.0\logs
```
=====

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.45.1|
| PowerShell Extension Version | 2020.4.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.0-preview.1|
|PSEdition|Core|
|GitCommitId|7.0.0-preview.1|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 7.0.0-preview.1|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.11|
|debugger-for-chrome|msjsdiag|4.12.8|
|powershell|ms-vscode|2020.4.0|
|remote-wsl|ms-vscode-remote|0.44.2|
|vscode-markdownlint|DavidAnson|0.36.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|

**Comment by corbob** [comment]
Since this is a PowerShell extension, I believe the variables are expected to be PowerShell variables. If you put this in your terminal you should see that it returns True: `$env:USERPROFILE -eq $home`

**Comment by Liturgist** [comment]
@corbob - Yes, you are right. I am still used to dealing with cmd.exe. I wasn't thinking.
