### ISSUE TITLE
[Preview of Preview(2020.5.1)] Can't import-module MicrosoftTeams

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2733]
Issue Description
=====

I am experiencing a problem with...

![image](https://user-images.githubusercontent.com/15063294/83362387-1ff5a880-a391-11ea-93e0-e5d526220308.png)

The same thing works in normal console, terminal or Windows PowerShell

![image](https://user-images.githubusercontent.com/15063294/83362396-2f74f180-a391-11ea-9fa6-c64f803f4a44.png)

Just in the integrated console, it doesn't. Works fine with old preview (different machine tho). I am on the Preview of the Preview version. Not sure how is that related.

On PS 7.1 the same thing

![image](https://user-images.githubusercontent.com/15063294/83362491-fdb05a80-a391-11ea-8f01-09ee41ca160a.png)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.45.1|
| PowerShell Extension Version | 2020.5.1 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.1|
|BuildVersion|10.0.19041.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.1.4|
|code-settings-sync|Shan|3.4.3|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.1|
|grammarly|znck|0.12.1|
|markdown-all-in-one|yzhang|3.0.0|
|material-icon-theme|PKief|4.1.0|
|powershell-preview|ms-vscode|2020.5.1-CI.54138|
|project-manager|alefragnani|11.0.1|
|vscode-markdownlint|DavidAnson|0.36.0|
|vscode-pull-request-github|GitHub|0.16.0|
|vscode-toggle-quotes|BriteSnow|0.3.2|
|vscode-wakatime|WakaTime|4.0.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by rkeithhill** [comment]
You have a typo in your import command.  It should be `microsoftteams` not `microsofteams` i.e. two `t's`, not one.

**Comment by PrzemyslawKlys** [comment]
Grr, sorry.
