### ISSUE TITLE
Read-Host paste dropping letters after F8/F5

### ISSUE THREAD

**Issue by ili101** [PowerShell/vscode-powershell#2741]
Issue Type: <b>Bug</b>

This is similar to fixed bug https://github.com/PowerShell/vscode-powershell/issues/2291
On the original issue it was happening every time `Read-Host` was used.

Apparently now it happens only if you F8 or F5 (Run anything doesn't matter) then F8 or F5 again this time with `Read-Host` and paste something.
Random characters from the string pasted will be missed.
If you Enter/Ctrl+C between the 2 actions this doesn't happen.

![Read](https://user-images.githubusercontent.com/6960531/83648645-f5893280-a5be-11ea-87bb-b32562cc0e24.gif)

Extension version: 2020.6.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

[1591194302-8adf92aa-6105-406f-97ea-3c9013c8ba161591191688507.zip](https://github.com/PowerShell/vscode-powershell/files/4724005/1591194302-8adf92aa-6105-406f-97ea-3c9013c8ba161591191688507.zip)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (2 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|2.00GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by jpalo** [comment]
I'm struggling with this same issue. Copy&pasting credentials from password management tool to the integrated PS console is somewhat difficult as it keeps dropping/replacing characters. 

In the image at the left you see GUID pasted to PS integrated console and the beginning is strangely messed up, haven't figured out any logic what it is doing there. Next I pasted it into Notepad and that is correct.

![image](https://user-images.githubusercontent.com/6917905/84125294-05809680-aa45-11ea-88f9-5dc983720386.png)

**Comment by ili101** [comment]
@jpalo Yes looks like the same thing. 100% reproducible for me also with `Get-Credential`

**Comment by ili101** [comment]
Bug regression - this was fixed in stable in 2020-2021 but is happening again in PowerShell Preview (tested on v2022.3.0)

**Comment by andschwa** [comment]
@ili101 Can you test the build I just posted in https://github.com/PowerShell/vscode-powershell/issues/3876#issuecomment-1074527145? I'm not sure if this is the fix for this issue, but would like to see...

**Comment by andschwa** [comment]
I don't think that build is going to fix your issue, it seems separate. Like, I just repro'd it. Very strange.

**Comment by andschwa** [comment]
How big an issue is this for you @ili101, is it blocking any scenarios or can you just call `Read-Host` interactively and paste that way?

**Comment by ili101** [comment]
@andschwa Did some more testing (with the build you mentioned).
No problem when using terminal directly without F8/F5.
With F8/F5 when typing it will miss the first letter.
With F8/F5 when pasting unpredictable.

I think it's maybe related to https://github.com/PowerShell/vscode-powershell/issues/3881

**Comment by ili101** [comment]
Rewrite part 2 cumming up? 🤔😁
Just an uninformed idea, will it be easier or harder to use the VSCode input thingy instead of the terminal for input?
![image](https://user-images.githubusercontent.com/6960531/161146045-98bb12f9-e103-4540-a911-fb3c43d6df6d.png)

**Comment by andschwa** [comment]
...that's a brilliant idea. We'd need to rewire Read-Host to send a message over LSP to ask for input, and then handle that in the client...but doable. @SeeminglyScience add this to the list of ideas!

**Comment by andschwa** [comment]
Hi there, we just released [v2022.4.0-preview](https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.4.0-preview)! Could you please try [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) and verify this is fixed? It seemed to be in my testing, so marking as resolved, but please let me know if it's still occurs (or if new bugs show up)!

**Comment by andschwa** [comment]
> Rewrite part 2 coming up?

It happened!!!
