### ISSUE TITLE
Suggestions for parameter types not working

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2743]
Issue Description
=====

I am experiencing a problem with... suggestions for parameter types not working.

![ThisUsedToWork](https://user-images.githubusercontent.com/15063294/83676060-5ffb9c00-a5da-11ea-9045-d4c06d9fbe9e.gif)

![image](https://user-images.githubusercontent.com/15063294/83676185-8faaa400-a5da-11ea-8cf8-d6087cff8d24.png)

In code:

![image](https://user-images.githubusercontent.com/15063294/83676097-70ac1200-a5da-11ea-97c8-719fafcf017d.png)

This used to work. It's not working in production and preview. It's very useful in ISE. 

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.45.1|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.1|
|BuildVersion|10.0.19041.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.1.4|
|code-settings-sync|Shan|3.4.3|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.1|
|grammarly|znck|0.12.1|
|markdown-all-in-one|yzhang|3.0.0|
|material-icon-theme|PKief|4.1.0|
|powershell-preview|ms-vscode|2020.6.0|
|project-manager|alefragnani|11.0.1|
|vscode-markdownlint|DavidAnson|0.36.0|
|vscode-pull-request-github|GitHub|0.16.0|
|vscode-toggle-quotes|BriteSnow|0.3.2|
|vscode-wakatime|WakaTime|4.0.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/83678235-b74f3b80-a5dd-11ea-93b0-a071222d3211.png)

I can replicate it every single time.

**Comment by PrzemyslawKlys** [comment]
Same machine in ISE doesn't have a problem. Not sure if that helps:

![image](https://user-images.githubusercontent.com/15063294/83678443-0bf2b680-a5de-11ea-87a7-2854723afb87.png)

![image](https://user-images.githubusercontent.com/15063294/83678456-11e89780-a5de-11ea-8e07-bfa29f95f7c2.png)

**Comment by SeeminglyScience** [comment]
After you get that error can you run this pls:

```powershell
$e = $Error[0].Exception
while ($e -and $null -eq $e.LoaderExceptions) {
    $e = $e.InnerException
}

$e.LoaderExceptions | fl * -for
```

**Comment by PrzemyslawKlys** [comment]
```
Message        : Method 'get_Line' in type 'EditorServicesCommandSuite.EditorServices.LspPosition' from assembly 'EditorServicesCommandSuite.EditorServices, Vers
                 ion=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
TypeName       : EditorServicesCommandSuite.EditorServices.LspPosition
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233054
```

**Comment by PrzemyslawKlys** [comment]
After I've removed module from loading - it works.

**Comment by SeeminglyScience** [comment]
Yep that's a JIT time exception for sure.  FWIW that won't affect completion in PS7 since the type completion API now catches those exceptions during type discovery.

@TylerLeonhardt You know if there's any more breaking changes coming in the near future? (I know we've already discussed this one in particular, just trying to see if I should expect more shortly).

**Comment by PrzemyslawKlys** [comment]
Thank you @SeeminglyScience, appreciate your help!
