### ISSUE TITLE
IntelliSense fails occasionally - again

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2745]
Issue Description
=====

I am experiencing a problem with... IntelliSense failing.

[1591449835-872343d1-59b3-436d-a112-c71c820037db1591449833798.zip](https://github.com/PowerShell/vscode-powershell/files/4740089/1591449835-872343d1-59b3-436d-a112-c71c820037db1591449833798.zip)

I feel a bit stupid filling this again but again got this issue. I am not sure if it's:
- https://github.com/PowerShell/vscode-powershell/issues/2627

Or it's more about this: 

- https://github.com/PowerShell/vscode-powershell/issues/2737

But I still see hiccups that never recover. I deleted a lot of offending PowerShell modules, but since I have no clue about reasons it never recovering it's hard to say. 

If you tell me what to look for, check I'm happy to do my own investigations.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.45.1|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.1|
|BuildVersion|10.0.19041.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.1.4|
|code-settings-sync|Shan|3.4.3|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.1|
|grammarly|znck|0.12.1|
|markdown-all-in-one|yzhang|3.0.0|
|material-icon-theme|PKief|4.1.0|
|powershell-preview|ms-vscode|2020.6.0|
|project-manager|alefragnani|11.0.1|
|vscode-markdownlint|DavidAnson|0.36.0|
|vscode-pull-request-github|GitHub|0.16.0|
|vscode-toggle-quotes|BriteSnow|0.3.2|
|vscode-wakatime|WakaTime|4.0.0|
|vscode-yaml|redhat|0.8.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by TylerLeonhardt** [comment]
I found an instance in the logs of a completion request taking 35seconds (for future self, open the log file in vscode and do a regex search: `\d\d\d\d\dms`):

```
2020-06-06 15:27:34.289 +02:00 [VRB] Request 514 was abandoned due to content be modified
2020-06-06 15:27:34.289 +02:00 [DBG] Completion request canceled for file: file:///c:/Support/GitHub/Testimo/Private/SourcesDomain/GroupPolicyADM.ps1
2020-06-06 15:27:34.290 +02:00 [DBG] Finished: Routing Request (514) textDocument/completion in 35591ms
2020-06-06 15:27:34.290 +02:00 [VRB] Request 514 was cancelled
2020-06-06 15:27:34.290 +02:00 [DBG] Finished: Processing request textDocument/completion 514 in 35591ms
```

But I'm not sure if it was stuck in PowerShell or not. Either way, I think completion should be a cancellable action... I'm hoping PowerShell itself will handle it gracefully... so I think we should dupe this to https://github.com/PowerShell/PowerShellEditorServices/issues/1295

because I want a requirement if that work to support cancellation.

Let me discuss this in Triage tomorrow before I mark it.

**Comment by rkeithhill** [comment]
Or `\d{5,}ms`.  :-)

**Comment by mattpwhite** [comment]
I can confirm that 2020.6.0 is better, but still falls over regularly.  The extension logs show requests for completions just hanging until I give up after 20+ seconds (at which point they are "cancelled", which I believe is a lie in the current implementation).  This is different than the behavior seen in earlier versions in that the extension itself isn't quite toast (in those cases I'd just see the log basically stop updating), but the user experience is still similar.  I still have to kill the extension all the time to get it back into a working state.

I'll try to collect some useful logs later today.

**Comment by mattpwhite** [comment]
Here's an interesting snippet from a couple minutes ago:
* Does a command lookup for a function defined in the file I'm currently editing.  That fails.
* An exception with a very long async stack trace about concurrent access to the pipeline
* A 52 second hang (request 8064) on a textDocument/definition call right after that, during which various extension features like folding were not working.

[pses-excerpt.log](https://github.com/PowerShell/vscode-powershell/files/4749006/pses-excerpt.log)

My log is pretty rotten with sequences like that.  Also a fair number of these exceptions about entering nested pipelines.

[other-exceptions.txt](https://github.com/PowerShell/vscode-powershell/files/4749020/other-exceptions.txt)

**Comment by rjmholt** [comment]
Thanks for looking into that @mattpwhite! Looks like further motivation for https://github.com/PowerShell/PowerShellEditorServices/issues/1295

**Comment by PrzemyslawKlys** [comment]
[1596305359-91a018eb-cd5f-4159-a261-8ba50c0e8b2f1596305357826.zip](https://github.com/PowerShell/vscode-powershell/files/5011073/1596305359-91a018eb-cd5f-4159-a261-8ba50c0e8b2f1596305357826.zip)

Another log. Basically after first cancelled event everything goes to hell. It can go to hell as quick as 5-20 minutes in.

**Comment by raandree** [comment]
The last years I have always moved to the ISE when writing more then 5 lines of code in PowerShell as IntelliSense is still not reliable at all. This week I am developing for Universal Dashboard and tried with the VSCode as there is a plugin for UD. It is extremely painful. If the script gets a bit bigger, IntelliSense does not work at all. Closing the terminal does not solve the issue. It feels like in the old VBS times.

What data would help working on this?

**Comment by SydneyhSmith** [comment]
We recently published an update to our preview extension which has addressed a number of  issues, would you mind giving it a try and letting us know if you are still hitting this?

**Comment by SydneyhSmith** [comment]
@raandree when you reference the script getting bigger, what size of script are you roughly seeing?

**Comment by raandree** [comment]
@SydneyhSmith, right after commenting on this issue I got the notification about the new version of the PowerShell Preview extension. It feels much better!

One issue is still there. IntelliSense works in the terminal but not in the code editor. I have created a screen recording of the behavior: https://1drv.ms/v/s!AuCqmYWYQ_kMnohF-j93qXWJsmtBXA?e=SLid98

**Comment by SydneyhSmith** [comment]
Thanks @raandree for the screengrab that is super helpful! Noticed the red squigglies when you are expecting the completions---this may be due to the placement of the the cmd not being valid so we wouldnt expect completions to work there...what is the squiggly you are getting? 
![image](https://user-images.githubusercontent.com/43417619/93937018-e4823f80-fcdb-11ea-80c3-dbc63421e9a0.png)

**Comment by tmknight** [comment]
I am still seeing regularly seeing this in both latest (as of this message) stable and preview of PowerShell Integrated Console
![image](https://user-images.githubusercontent.com/548588/94270685-740f3480-ff0e-11ea-9f28-8f3787233021.png)

This is expected:
![image](https://user-images.githubusercontent.com/548588/94270889-cfd9bd80-ff0e-11ea-80f4-a07cc1bdc428.png)

> Version: 1.49.2 (user setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by PrzemyslawKlys** [comment]
I just want to add that for me, my problems happen on minutes/hourly basis. It's not occasional anymore. It may be related to my other issue https://github.com/PowerShell/vscode-powershell/issues/2908 but generally, it's pretty bad. I either stop using IntelliSense and try to pick things from memory or I restart session all the time. I can only imagine how it works for other people that never report issues thinking code just sucks.

**Comment by danstur** [comment]
@SydneyhSmith  I'm still experiencing this issue pretty regularly. Do you need extra logs to analyse the issue or what's the reason the Needs: Attention flag was removed? 

If there's a way I can help get to the root of this issue, I'd be more than willing to help.

**Comment by SydneyhSmith** [comment]
Thanks @danstur this issue is actively being worked on--the reason the "Needs:Attention" was removed is because no immediate response was needed on the issue comment thread-- the fact that the issue is still open indicates it has not been resolved. Thanks!

**Comment by ztrhgf** [comment]
In our team we have same problem so in case I can help, let me know!

**Comment by ztrhgf** [comment]
Is there any progress? It's real pain to use vsc for Powershell scripting right now. Intellisense doesn't work and formatting neither.

Most of my colleague already gave up and are using different editors. I don't blame them...

**Comment by andschwa** [comment]
@ztrhgf Have you tried the Preview extension? A lot of these "occasional failures" issues were resolved in the pipeline thread rewrite.

**Comment by ztrhgf** [comment]
Yes, I was running powershell preview extension for several months now but that didn't help, unfortunately. I will give a try to Rider IDE it seems.

**Comment by JustinGrote** [comment]
@ztrhgf maybe you can provide some specific examples of where it fails? I'm on preview and intellisense works just fine for me.

**Comment by PrzemyslawKlys** [comment]
Sure ;-)

![image](https://user-images.githubusercontent.com/15063294/151632588-c0cdb8cb-1c57-4a34-8599-3b1cbe8bdb9c.png)

**Comment by JustinGrote** [comment]
Hard to say if #1 is reasonable, it feels like the editor should be showing you an error that the type doesn't exist (yet), but that's a whole 'nuther can of worms), and it shouldn't intellisense on invalid functions in my opinion

For #2, how is it supposed to know those two .ps1 files are related? Say you have the function defined in two different completely unrelated files in the same workspace, which one is it supposed to intellisense?

Powershell is not a statically typed language, it really can't analyze across multiple files safely to my knowledge. Maybe a "best effort" could be done if only one function is found in the AST tree for all files, but then this will feel like inconsistent behavior to the user.

**Comment by PrzemyslawKlys** [comment]
1. It was just showing it fails for unknown types. This can be when you're not connected to Exchange and you work with Exchange types, or when you are using some DLL and it's not loaded yet, but you want to type some code. I do know it's a problem on the PowerShell side. 
2. All good points - yet I do work with modules and as I am building them I have 2 choices - push PSM1 wildcard and psd1 wildcard and let it load everything or deal with lack of autocomplete for private functions and type in blindly. 

I just want to make sure we're on the same page - I know where it's coming from, and the validity of it - just I believe that most of the problems will keep on coming from the problems I've described. Since VSCode is workspace based you could assume that I want to see everything within the workspace - or maybe even go as far as creating a distinction between what is there given by PowerShell (you already have an icon for that) and highlight it somehow when doing autocomplete, and what is there coming from the workspace. 

Right now from the workspace, I get all sorts of bullshit (no icon) and it's well useless. Users are expecting help. Will it sometimes load 2 functions with the same name from 2 different files - sure. Will it be better than having 0 help - yes! Because alternative is 0 help at all, and a bunch of random strings.

**Comment by SeeminglyScience** [comment]
One thing you can try for a lot of these issues (and I know it's stop gap, not a real solution) is to import the module and enter a nested prompt. e.g.

```powershell
# Exit any previously nested prompts, only needed when updating
$Host.ExitNestedPrompt()
. (Import-Module ./src/module.psd1 -PassThru -Force) { $Host.EnterNestedPrompt() }
```

Far from perfect, especially since it isn't updated automatically with changes. But it can help with those scenarios.

I have some thoughts about how to build more support for workspace concepts into the PowerShell engine but it's too early to tell if any of them are feasible. It's something I'm thinking about a lot and I hope to see them realized one day. In the mean time, give the above a go and see if that helps alleviate the gap in functionality.

**Comment by JustinGrote** [comment]
We could try an experimental feature with a filewatcher that watches for .ps1 changes and automates this process, that might be better suited to a one-off extension since it probably could use the API that's already there :)

**Comment by ztrhgf** [comment]
> @ztrhgf Have you tried the Preview extension? A lot of these "occasional failures" issues were resolved in the pipeline thread rewrite.

I was using preview version of PS extension for several months, now I've switched to stable release. But issues are still the same. Intellisense stopps working even for native commands (like get-process etc). Result is that I have to restart PS session in VSC twice a day at least which is not good user experience.

If you need logs etc let me know.

**Comment by JustinGrote** [comment]
@ztrhgf Specific examples would be great or a screenshot when it happens. Note that intellisense requires the PSIC to be active and available, so if you for instance run `sleep 30`, Intellisense will not be available until that command completes.

**Comment by andschwa** [comment]
FWIW there is support to analyze across PowerShell files in the same workspace, but it's predicated on the files being explicitly interdependent (e.g. one dot-sources another). So if File A dot-sources File B, then IntelliSense in File A will complete stuff in File B, but not otherwise (which is fair, since if you _didn't_ dot-source File B but tried to use one of its functions, it would fail in PowerShell anyway since it's not been defined). You can review how all of this currently works (and so what functionality is expected or not) in the [`SymbolsServiceTests`](https://github.com/PowerShell/PowerShellEditorServices/blob/master/test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs).

**Comment by ztrhgf** [comment]
> @ztrhgf Specific examples would be great or a screenshot when it happens. Note that intellisense requires the PSIC to be active and available, so if you for instance run `sleep 30`, Intellisense will not be available until that command completes. In my experience running preview I almost never need to restart anymore to "fix" intellisense.

<img width="221" alt="image" src="https://user-images.githubusercontent.com/2930419/151941710-e6aa0114-40bf-421f-a8ae-9c42b378ba45.png">

**Comment by PrzemyslawKlys** [comment]
To be honest I can replicate that on my server. My server is somehow very slow with PowerShell (probably antivirus) and it sits there about 5-10 seconds on the loading part then gives me bullshit, but when I press ctrl+space again it fills that in. The subsequent request works much faster. Is that your experience @ztrhgf ? 

On the other hand on my desktop, it's fairly fast - but I've configuration most people don't.

**Comment by JustinGrote** [comment]
That's a good point, where are you running the PSIC extension? Is this a remoting session?

**Comment by ztrhgf** [comment]
No it local session.

As I said I was using preview version for several months now and result was quite same. Once session restart per day at minimum.

Can I check some logs to get more insight into this issue?

**Comment by PrzemyslawKlys** [comment]
But the new Preview version is much younger than several months. Are you sure it's a new preview and could you retest with the current preview just to make sure?

**Comment by JustinGrote** [comment]
There are extended logs but they may not cover just simple completion services, especially just "hangs". You may want to try making a "fresh" portable vscode installation so you don't have to affect your existing setup, just download the zip of vscode and add a "data" folder to the extract.

**Comment by ztrhgf** [comment]
> > That doesn't seem to help. Btw we use VSC to manage our company PowerShell GIT repository which contains approximately 3000 files (1000 of them are ps1) and 800 directories, so maybe it is somehow related to its size?
> 
> Yeah that'll cause some issues for sure. Try adding this to your `settings.json`
> 
> ```json
> "[powershell]": {
>     "editor.codeLens": false,
> },
> ```

This seems to help, but to be sure I will test it for a longer period. Thanks anyway!

**Comment by SeeminglyScience** [comment]
@andschwa just a thought, we might want to look at using some heuristics to turn that off automatically in some workspaces. Ideally with an option to force it on always.

As much as I'd like to guide folks to smaller workspaces, an very high number of folks just want to open up all their stuff at the same time. To the point where if someone is talking about issues with intellisense on discord, half the time I open with "how big is the workspace" and the answer is often "all of the stuff".

**Comment by ztrhgf** [comment]
(from my point of view) would be better to allow define folders that should
be searched. Or some sort of customizable solution.

Because it is very user friendly to have all your organization code at one
place and be able to search it at once etc.

Thanks in advance
Sebela

**Comment by JustinGrote** [comment]
@ztrhgf FYI that sparse checkout is also a thing:
https://git-scm.com/docs/git-sparse-checkout

**Comment by ztrhgf** [comment]
I see. Unfortunately, it is of no use for us because we have a custom CICD solution that requires all data to be locally available. But thanks for the tip anyway!

I will test this further, but so far it seems that setting
```
"[powershell]": {
    "editor.codeLens": false,
}
```

when combined with the Preview version of the PowerShell extension helped a lot. It is definitely not perfect but is usable.

**Comment by andschwa** [comment]
@PrzemyslawKlys should we close this issue or are you still seeing the same thing?

**Comment by PrzemyslawKlys** [comment]
@andschwa We can close it because in my cases I believe it's related to [Types] stopping working and I believe @SeeminglyScience once explained it's a problem on PS 5.1. So I just try to use PS 7 most of the time. 

I am not sure whether you want that one as part of "issues", something that would be considered for a fix in a workaround in VSCode extension? Also I've also mentioned my problems here: https://github.com/PowerShell/vscode-powershell/issues/2745#issuecomment-1024724420 but those are edge cases and I guess it would be again workaround in VSCode extension rather than anything else. Do you want them as issue/issues or should we just assume those are non-fixable and we should stop wasting time on that?

**Comment by andschwa** [comment]
@PrzemyslawKlys I'm looking at the screenshots in your linked comment...for the first example:

```pwsh
function Set-Test {
    [cmdletBinding()]
    param(
        [string] $Test,
        [UnknownType] $Test1
    )
}

Set-Test -
```

If I understand correctly you're expecting at least `-Test` to show up under parameter hints, but it doesn't. And it doesn't because the bound parameters are broken since `$Test1` has a type constraint of `UnknownType`. Removing that (or changing the type to something real, like `object`) makes parameter hints work just fine. So yeah, I think that's less an edge and more an "expected failure" since the code it's parsing is broken. Would I like PSSA to throw a problem at `[UnknownType]`? Totally, but oh well. @SeeminglyScience is there something better we can do there?

For the second example with `New-HTMLGroupDiagramSummaryHierarchical` I think you already hit the nail on the head: PowerShell isn't giving us parameter hints for it, so there's not much we can do there. Unless @SeeminglyScience knows a brilliant solution 😉

For the third example...I have no idea why that isn't working. I went to test it and expected it to work in the preview. Ok can you please file a separate issue about "Parameter hints are broken"? I was looking at them a little bit while improving the symbols, and realized they are very oddly implemented (for instance, we only look at parameter sets, which leads to weird suggestions) and clearly there's an issue where it's not getting any parameters for a function defined elsewhere in the workspace. It should, and I don't like that it's not!

**Comment by PrzemyslawKlys** [comment]
The idea around the first example is that I sometimes develop something without a library. For instance working on Exchange 2010/2013 script where you need to connect to Exchange to get cmdlets available, and that means if you don't have them connected/at hand, developing for it will be a nightmare. So it's not about UnknownType, it's about type that developer is not having at the moment. Sure PSScriptAnalyzer could help in detecting typos in "types" (is there such a rule?), but it's not about thatin that case.

I guess with Github CoPilot things are a bit easier ... so maybe the effort is not worth it.

![image](https://user-images.githubusercontent.com/15063294/220849594-c08a9ce3-158d-4ff7-93b0-2b0c254cbba2.png)

The 2nd and 3rd examples are basically the same thing - the functions are stored in separate files, often in a Private folder. If you try to call them up outside of those files they will not work (in both cases). If you call them up at least once they will be in the session and work, but any changes to them won't be reflected. I would say this is how PowerShell works in VSCode now and there's no difference between my 2nd and 3rd example. 

So unless you're willing to Prescan all folders somehow and provide parameters hints even for private functions (after all you're not reading PSD1/PSM1 to deliver information) it won't work.

![image](https://user-images.githubusercontent.com/15063294/220850404-a957ff9a-1fb3-4e7c-afa4-93ce5060ba52.png)

My projects are always done the same way Private, Public folders, one function per file, and then all that is loaded up thru PSM1 and PSD1. In PSM1 during development, I have `Export-ModuleMember -Function '*' -Alias '*'`, but in PSD1, during development, my FunctionsToExport is always set to specific values. Sure enough, I could change it to "*" and once you load module all private/public functions will be available within session so parameters and everything else will work.  

So, in my opinion, the current implementation "works as expected", according to the rules of PowerShell (where files are their own boundaries), but what would be cool from sysadmin/dev perspective that spends lots of time writing modules is the ability to "switch" between standard behavior and developer behavior somehow. Where by Developer behavior I mean working cross-files (within single workspace) regardless if those are loaded to specific session or not. After all you already have References up and running so extension is aware of functions existence. This would be helpful for developers to get a bit of that "C#" magic that they get. I understand this may not be your target audience to help those very few "devs" like me, who like to separate every function into their own existence. 

So I don't believe opening an issue "Parameter hints are broken" makes sense unless you're thinking @andschwa  on going the extra mile on this because I believe those are as "expected" regardless of my feelings :-)

**Comment by andschwa** [comment]
Ok fair! One day it would be nice to go that extra mile, because honestly I agree with you. As a developer, I'd expect these to just work. But at least know why they aren't and it's "expected." Thanks!

**Comment by JustinGrote** [comment]
@PrzemyslawKlys as a non-optimal workaround, I have an alias in my profile that basically dot sources everything in my project, and if you do that you will get the intellisense.

**Comment by PrzemyslawKlys** [comment]
@JustinGrote I mostly switch to modifying PSD1 to * and just rerunning module and it works, or just take a bullet. I have plans to learn on how to create VSCode extensions and just create some GUI for actions I do frequently such as Importing module, maybe "live" edit PSD1 and rerun, things like that. Something that will make my development a bit less painful in some situations. I don't know yet when I will be able to do it - but I have been thinking on it for a while. 

Dot sourcing for hybrid modules is usually not enough.
