### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ifuseandprint** [PowerShell/vscode-powershell#2746]
- Issue Type: `Bug`
- Extension Name: `powershell-preview`
- Extension Version: `2020.6.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.46.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by TylerLeonhardt** [comment]
Looks like you forgot to paste the important information.

**Comment by ifuseandprint** [comment]
thanks
