### ISSUE TITLE
Color coding issue with Export-ModuleMember

### ISSUE THREAD

**Issue by gsscoder** [PowerShell/vscode-powershell#2752]
It's more easy to see the screenshot:
![psvscode-colorcoding](https://user-images.githubusercontent.com/1194228/84116625-7d909180-aa30-11ea-871e-3194973a8cb4.PNG)

Exported functions should be all of same color.

Thank you for great extension.

Regards,
Giacomo S. S.

**Comment by TylerLeonhardt** [comment]
Please open this over here:

https://github.com/PowerShell/EditorSyntax

For future reference, this is called out in our new issue page:

![editor syntax for colorization bugs](https://user-images.githubusercontent.com/2644648/84157222-554c6700-aa1f-11ea-84c2-29ac01873a92.jpg)
