### ISSUE TITLE
Intellisense results not returned by Visual Studio Code, but Windows Terminal works fine

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#2753]
### System Details

System Details Output
```
### VSCode version: 1.45.1 5763d909d5f12fe19f215cbfdd29a91c0fa9208a x64

### VSCode extensions:
amazonwebservices.aws-toolkit-vscode@1.10.0
arcticicestudio.nord-visual-studio-code@0.13.0
dracula-theme.theme-dracula@2.22.1
EliverLara.andromeda@1.7.0
formulahendry.code-runner@0.10.0
icsharpcode.ilspy-vscode@0.7.11
johnpapa.vscode-peacock@3.7.2
ms-azuretools.vscode-docker@1.2.1
ms-dotnettools.csharp@1.22.0
ms-python.python@2020.5.86398
ms-vscode-remote.remote-containers@0.117.1
ms-vscode-remote.remote-ssh@0.51.0
ms-vscode-remote.remote-ssh-edit@0.51.0
ms-vscode-remote.remote-wsl@0.44.2
ms-vscode.powershell@2020.4.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am experiencing a lack of consistency with Intellisense handlers running successfully inside Visual Studio Code, while the same code runs perfectly fine in the Windows Terminal. I reproduced the problem inside a PowerShell container, using Docker Desktop with WSL2 support in conjunction with the Remote-Containers extension. The problem exists both inside the container and outside the container, natively on Windows.

#### Expected Behaviour

Intellisense results should be returned.

![image](https://user-images.githubusercontent.com/466713/84194331-b68d2e00-aa51-11ea-9f8a-e739fd1c11de.png)

#### Actual Behaviour

No Intellisense results are returned.

![image](https://user-images.githubusercontent.com/466713/84194355-c147c300-aa51-11ea-983b-d8a960be5654.png)

### Attached Logs

Sent via e-mail

**Comment by SydneyhSmith** [comment]
Thanks @pcgeek86 we recently published an update to our Preview extension which has addressed an issue with intellisense not working, would you mind giving it a try and letting us know if you are still hitting this issue? We are also planning to release this through the stable channel in the next week.

**Comment by pcgeek86** [comment]
@SydneyhSmith I tried the preview version today as well, and I believe the logs that I e-mailed to you are using the preview extension version. Could you please check those out?

**Comment by SydneyhSmith** [comment]
@pcgeek86 sorry about that (and apologies for the delay in the response) you are correct, in your logs it shows that you were using the latest preview...because I am going to track this issue under #2745

**Comment by pcgeek86** [comment]
Thanks @SydneyhSmith!

**Comment by nippyin** [comment]
![image](https://user-images.githubusercontent.com/41337248/84838959-d0a6ad80-b009-11ea-975c-d01f4dbad135.png)
ms-vscode.powershell-preview@2020.6.1 & PSVersion    7.1.0-preview.3

Please refer screen shot and it used to be autocomplete any command in history but it does not work now.
