### ISSUE TITLE
Format-Table output breaks with VT100/ANSI escape sequences

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/vscode-powershell#2755]
### System Details Output
```
### VSCode version: 1.46.0-insider 9f89da69154ac6c99dfa7c82986e2df95b7bbe0b x64

### VSCode extensions:
ms-vscode.powershell-preview@2020.6.1

### PSES version: 2.2.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
Output from Format-Table breaks inside the integrated console when you add vt100 sequences to change the colors. This works fine in every other terminal I've tried that supports this feature.
You can try this out with the following code:
```
$TableOutput=Get-NetIPAddress -AddressFamily IPv4 | Format-Table
$i=0
foreach ($Line in $TableOutput)
 {
     $FieldList=$Line.formatEntryInfo.formatPropertyFieldList

     if ($FieldList)
     {
        $i++
         if ($i%2 -eq 0)
         {
             foreach ($Property in $FieldList)
             {
                 $Property.propertyValue="$([char]27)[92m$($Property.propertyValue)$([char]27)[0m"
             }
         }
     }
 }
$TableOutput
```

#### Expected Behaviour
![Expected](https://user-images.githubusercontent.com/42123497/84265754-9ded4880-ab23-11ea-9923-37b2741cd56d.PNG)

#### Actual Behaviour
![Actual](https://user-images.githubusercontent.com/42123497/84265720-8f9f2c80-ab23-11ea-824c-4cf52ec49e12.PNG)

**Comment by SydneyhSmith** [comment]
@MartinGC94 thanks for opening this, we are able to repro this

**Comment by corbob** [comment]
It look like this is related to the PSES issue: https://github.com/PowerShell/PowerShellEditorServices/issues/840

**Comment by TylerLeonhardt** [comment]
I'll mark this as a duplicate to the PSES issue since that has some more information on how we could fix this.
