### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dudi72** [PowerShell/vscode-powershell#2756]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2020.4.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.46.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [
		{
			"type": 1,
			"message": "Command `workbench.action.debug.start` appears multiple times in the `commands` section.",
			"extensionId": {
				"value": "ms-vscode.powershell",
				"_lower": "ms-vscode.powershell"
			},
			"extensionPointId": "commands"
		}
	],
	"activationTimes": {
		"codeLoadingTime": 394,
		"activateCallTime": 18,
		"activateResolvedTime": 23,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-vscode.powershell",
				"_lower": "ms-vscode.powershell"
			},
			"activationEvent": "onLanguage:powershell"
		}
	},
	"runtimeErrors": []
}

It seems this extension causes the VS Code to get stuck for a half a minute on startup.

**Comment by SydneyhSmith** [comment]
@dudi72 thanks for opening this issue! Could you please provide a little more detail on what you mean by stuck (screenshots or gifs are helpful)? It would also be great to know what other extensions you have?

**Comment by dudi72** [comment]
Sure. Here is a screen recording of me starting the VS Code including P.SH.
Please change the extension to mp4 and play the file.
![PowerShellIssue mp4](https://user-images.githubusercontent.com/5675751/84533161-3cc6a000-acf0-11ea-9e2f-7166ec3e7011.jpg)

**Comment by dudi72** [comment]
![image](https://user-images.githubusercontent.com/5675751/84569567-60412780-ad90-11ea-86f2-d975bddea421.png)
I have the following extensions:
Excel Viewer
Remote - WSL
PowerShell

**Comment by SydneyhSmith** [comment]
Thanks @dudi72 for providing this info it is super helpful! I noticed at the end of the video that the console appears to have to started...is that the case? Thanks!
