### ISSUE TITLE
Azure Powershell commands return string error

### ISSUE THREAD

**Issue by mattcamp47** [PowerShell/vscode-powershell#2759]
We have written the needed data into your clipboard because it was too large to send. Please paste.
![image](https://user-images.githubusercontent.com/28009620/84434547-d9f0de00-abf5-11ea-9fce-41de2049ee10.png)

normal powershell core 7.0.1 will return proper responses to basic commands like get-azresource.   With powershell  extension for integrated console, I get the response of Get-AzResource: Method not found: 'System.String Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.get_AzVersion()'.
In  the environment variables for Mac are inclusive  of PSModulePath=/Users/adm29965/.vscode/extensions/ms-vscode.powershell-2019.11.0/modules which  seems  to be the  issue.  If I remove the  extension. the issue goes away.

**Comment by SydneyhSmith** [comment]
@mattcamp47 thanks for opening this issue, what version of the extension were you running?

**Comment by mattcamp47** [comment]
I have tried multiple versions, both the preview version from 2020.6.1 to 2019.5.0. and the current version 2020.4.0 to 2019.5.0.  the earlier ones provide no output,  the latter provide that error.  I can reproduce this error and remove it by adding and removing the extension.   I have already completely removed all powershell and removed it, removed all the .vscode dirs. And even run the MS recommended  uninstall script for vscode.   https://raw.githubusercontent.com/MicrosoftDocs/visualstudio-docs/master/mac/resources/uninstall-vsmac.sh

So I have really tried to exhaust all options to troubleshoot.  😊

Thanks for the quick reply, let me know if need to  provide further  details

**Comment by SydneyhSmith** [comment]
Thanks @mattcamp47 could you please also try running `$psversiontable` in the integrated console latest version of the extension (2020.6.0)? Thanks!

**Comment by mattcamp47** [comment]
So I  actually overcame this issue by doing the following:

Removal of all components for vscode (according to the ms script). Removal of all powershell components based on what was in the powershell path env variable.  Complete uninstall of Powershell via Homebrew.  And then reinstallation of Powershell through same process only this time, Powershell 7.0.2 was installed based on latest “brew cask install powershell”.  Then downloading the latest Vscode and installing the latest powershell extension.

I did most of the above before but I think the two latest factors that derived success were removal of all the powershell components in the path and the fact that Powershell 7.0.2 is now available.  At any  rate, I am happy to be working again.  Thanks for the check in.

**Comment by TylerLeonhardt** [comment]
Glad to hear it! Let us know if you end up continuing to see the issue.
