### ISSUE TITLE
Create a script to automate pushing releases to GitHub

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#276]
Needs to do the following things:
1. Run `vsce package` and unpack to a folder
2. Gather extension files into a folder called `ms-vscode.PowerShell-<version>`
3. Zip up the extension folder to `ms-vscode.PowerShell-<version>.zip`
4. Gather the CHANGELOG.md notes for the latest release
5. Create a release using the [GitHub API](https://developer.github.com/v3/repos/releases/#create-a-release)
6. Upload the release ZIP using the [GitHub API](https://developer.github.com/v3/repos/releases/#upload-a-release-asset)

**Comment by rjmholt** [comment]
Closed in https://github.com/PowerShell/vscode-powershell/pull/1937
