### ISSUE TITLE
Register-EditorCommand no longer seems to work

### ISSUE THREAD

**Issue by NJK-HOME** [PowerShell/vscode-powershell#2760]
### System Details

System Details Output
```
### VSCode version: 1.46.0 a5d1cc28bb5da32ec67e86cc50f84c67cc690321 x64

### VSCode extensions:
DavidAnson.vscode-markdownlint@0.36.0
ms-dotnettools.csharp@1.22.0
ms-vscode.powershell@2020.6.0        
sirmspencer.vscode-autohide@1.0.5    
tht13.html-preview-vscode@0.2.5      
vscode-icons-team.vscode-icons@10.1.1


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Interesting, this no longer seems to work for the above output:
$pseditor.EditorServicesVersion

I manually checked and it is 2020.6.0
### Issue Description

I am experiencing a problem with registering an editor command from my Microsoft.VSCode_profile.ps1 profile.   I use this command (in combination with the alt-f2 key combo assigned in my keybindings.json file) to sign my PowerShell script and compile my script into an executable.  This was working up until today.  I updated to the latest PowerShell extension today...so that seems to be the cause.  But I also enabled the "Auto Hide" extension yesterday so that may be the cause too.  When I disabled that extension, it is still broke.

Here is how I register the command in my profile:
Register-EditorCommand -Name SignCurrentScript -DisplayName 'Sign Current Script' -ScriptBlock `
{
code here...
}

Here is my keybindings file:
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "alt+f2",
        "command": "PowerShell.InvokeRegisteredEditorCommand",
        "args": {
            "commandName": "SignCurrentScript"
        },
        "when": "editorLangId == 'powershell'"
    }
]

#### Expected Behaviour

I should be able to type alt-f2 or use command palette and with the "PowerShell: Show additional commands" and have it run my SignCurrentScript script block code.

#### Actual Behaviour

With the alt-f2, now nothing happens.  With the command palette I get "No extension commands have been loaded into the current session."

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by NJK-HOME** [comment]
I should have checked this earlier, but going back to the 2020.4 version fixes the problem.  So this seems to be related to 2020.6.  Also, the "$pseditor.EditorServicesVersion" still does not work now that I am back in the 2020.4 version.  I am not sure why that is, or if that is even related to my problem.

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by NJK-HOME** [comment]
I see the problem.  Your code signing certificate for the PowerShellEditorServices.Commands.psm1 shows as being revoked.  I am having the same problem with Visual Studio 16.6.1 - that product will not install for me either and it is showing a revoked certificate for a specific MSI included in the package.  Also the latest .NET Core 3.1.5 will not install - but I have not be able to locate a revoked certificate for that package - but I suspect that is the same issue.

Here is a screenshot of the certificate revocation.  It is probably failing for me because I require AllSigned for any script (and hence module) I run on my machine.

![Revocation](https://user-images.githubusercontent.com/61813693/84560263-d2215e80-ad07-11ea-81c5-89fd07616a1d.png)

**Comment by NJK-HOME** [comment]
Here is a screenshot of 2020.4 - no revocation error on the PSM file.

![OldVersion](https://user-images.githubusercontent.com/61813693/84560422-95566700-ad09-11ea-8216-09418516c312.png)

**Comment by rjmholt** [comment]
@NJK-HOME I'm not seeing the same revocation on my machine. The fact that multiple applications seem to have this issue for you seems to suggest you might have a certificate configuration issue on your machine

![revoked](https://user-images.githubusercontent.com/7009879/84829762-1ef18780-afdd-11ea-8ab8-25efb5ac5138.PNG)

**Comment by NJK-HOME** [comment]
OK - thank you for checking.
