### ISSUE TITLE
Powershell debugger crashing

### ISSUE THREAD

**Issue by ankugarg** [PowerShell/vscode-powershell#2762]
Issue Type: <b>Bug</b>

Powershell debugger keeps crashing. Have attached exception logs

Extension version: 2020.6.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

[Logs.log](https://github.com/PowerShell/vscode-powershell/files/4770760/Logs.log)

**Comment by SydneyhSmith** [comment]
Thanks @ankugarg for opening this issue and providing logs, could you please provide a little more context around what you were trying to do when this issue occurred--repro steps, gifs and screen shots are all great!

**Comment by ankugarg** [comment]
![Powershell_VSCode_Issue](https://user-images.githubusercontent.com/13931015/84915497-7f1a2380-b0da-11ea-907e-405258abd14d.gif)

@SydneyhSmith have attached a gif. Although debugger is not crashing but getting error timeout now.
Please let me know if more info is needed.

**Comment by ankugarg** [comment]
![Powershell_VSCode_Issue](https://user-images.githubusercontent.com/13931015/84917607-2d26cd00-b0dd-11ea-855a-b1d6c1e69c0a.gif)

@SydneyhSmith sorry for not providing information earlier. Have attached gif. Please have a look at it.

Steps to reproduce:
1. Apply breakpoint and start debugging via pressing F5
2. When debugger stop at breakpoint, press F5 again

Please let me know if more info is required.

**Comment by SydneyhSmith** [comment]
@ankugarg thanks that information is really helpful, does the crash happen just after the GIF ends?

**Comment by ankugarg** [comment]
@SydneyhSmith - Yes.
I have uploaded the video to give more clarity on the issue - https://www.youtube.com/watch?v=8plhDp3ZCvM

**Comment by SydneyhSmith** [comment]
Thanks @ankugarg really appreciate you taking the time to upload a video, really helps us better understand the issue.
Could you please also attach the payload logs, instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs)

**Comment by ankugarg** [comment]
@SydneyhSmith have attached the logs but there is no error [PayloadLogs.log](https://github.com/PowerShell/vscode-powershell/files/4825640/PayloadLogs.log)

Although debugger did crash on UI

**Comment by rjmholt** [comment]
Ok this looks like a good old bug in the debugger to do with the current pipeline thread issues. Working on a fix currently, but it's large and complex -- will take several weeks to implement

**Comment by rajeshpaddy** [comment]
Any ETA on this bug fix, I'm having the same issue. I hit F5, the debugger stops on the first break point and when i continue, it crashes -- @rjmholt

**Comment by SydneyhSmith** [comment]
You can track this work item more closely using this issue: https://github.com/PowerShell/PowerShellEditorServices/issues/1295
