### ISSUE TITLE
Debug Status Not Cleared after Restart Powershell Session

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#2765]
Issue Type: <b>Bug</b>

When starting a debug session and then restarting the console, this extension used to reset the debug status in vscode. It no longer does and users may erroneously think that debug is "running" even though all breakpoints have been cleared by the session restart.

Often a "timeout after 1000ms" will come up as well, I assume something in omnisharp isn't being notified when a session restart takes place?

![Capture](https://user-images.githubusercontent.com/15258962/84535050-e2055800-ac9f-11ea-92cc-42fb01765012.gif)

Extension version: 2020.6.1
VS Code version: Code - Insiders 1.47.0-insider (7e4cc2c435927e5a2845897961a2af10ee7f784d, 2020-06-12T06:03:53.183Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by TylerLeonhardt** [comment]
Ha. This is probably because of this PR https://github.com/PowerShell/vscode-powershell/pull/2672

Thanks for this!
