### ISSUE TITLE
ResourceUnavailable: "The named pipe target process has ended."

### ISSUE THREAD

**Issue by carct** [PowerShell/vscode-powershell#2772]
Issue Description
=====

I am experiencing a problem with debugger crashing after a change is saved in the project (AzFunctionApps-V3 / PowerShell Context).
The FunctionApp Runtime **does not crash**, it reloads and most likely by doing so, the process will have a different PID then the one for which the debug pipe was created, resulting in a crash
behavior is persistent across different versions of azure-functions-core-tools, tested on:
`npm i -g azure-functions-core-tools@3.0.2534 --unsafe-perm true`
`npm i -g azure-functions-core-tools@3.0.2245 --unsafe-perm true`

how it should be: debugger should re-attach to the new process, based on PipeName / DebugRunspace ID

**workaround**:
i have set 
`"azureFunctions.stopFuncTaskPostDebug": false,`
so that i can continue to use the Runtime and hit it with Postman, but in order to have again breakpoints i need to hit F5 again
this would re-launch my runtime, so i've created another launch command in vscode :
```
{
            "name": "Re-attach to PS FunctionApp",
            "type": "PowerShell",
            "request": "attach",
            "customPipeName": "AzureFunctionsPSWorker",
            "runspaceId": 1
        }
```
after debugger crashing, i can launch the above and all works fine

configuration files
=====
.vscode/settings.json
```
{
    "azureFunctions.deploySubpath": ".",
    "azureFunctions.projectLanguage": "PowerShell",
    "azureFunctions.projectRuntime": "~3",
    "azureFunctions.showExplorer": true,
    "azureFunctions.stopFuncTaskPostDebug": false,
    "azureFunctions.validateFuncCoreTools": true,
    "debug.internalConsoleOptions": "openOnSessionStart",
    "debug.allowBreakpointsEverywhere": true,
    "debug.extensionHost.useV3": true,
    "powershell.powerShellDefaultVersion": "~7",
    "terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
}
```

.vscode/launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Start&Attach to PS FunctionApp",
            "type": "PowerShell",
            "request": "attach",
            "customPipeName": "AzureFunctionsPSWorker",
            "runspaceId": 1,
            "preLaunchTask": "func: start --script-root src"
        },
        {
            "name": "Re-attach to PS FunctionApp",
            "type": "PowerShell",
            "request": "attach",
            "customPipeName": "AzureFunctionsPSWorker",
            "runspaceId": 1
        }
    ]
}
```

Attached Logs
=====
Output Logs:
```
6/17/2020 11:46:52 AM [NORMAL] - Visual Studio Code v1.46.0 64-bit
6/17/2020 11:46:52 AM [NORMAL] - PowerShell Extension v2020.6.0
6/17/2020 11:46:52 AM [NORMAL] - Operating System: Windows 64-bit
6/17/2020 11:46:53 AM [NORMAL] - Language server starting --
6/17/2020 11:46:53 AM [NORMAL] -     PowerShell executable: C:\Program Files\PowerShell\7\pwsh.exe
6/17/2020 11:46:53 AM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\andrei.morarescu\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\andrei.morarescu\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\andrei.morarescu\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1592383612-4dae5baf-1b65-426d-852c-67e750f61e1f1592383305641\EditorServices.log' -SessionDetailsPath 'c:\Users\andrei.morarescu\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-21236-731834' -FeatureFlags @() 
6/17/2020 11:46:53 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\andrei.morarescu\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\andrei.morarescu\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\andrei.morarescu\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1592383612-4dae5baf-1b65-426d-852c-67e750f61e1f1592383305641\EditorServices.log' -SessionDetailsPath 'c:\Users\andrei.morarescu\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-21236-731834' -FeatureFlags @() 
6/17/2020 11:46:53 AM [NORMAL] - pwsh.exe started.
6/17/2020 11:46:53 AM [NORMAL] - Waiting for session file
6/17/2020 11:46:55 AM [NORMAL] - Session file found
6/17/2020 11:46:55 AM [NORMAL] - Registering terminal close callback
6/17/2020 11:46:55 AM [NORMAL] - Registering terminal PID log callback
6/17/2020 11:46:55 AM [NORMAL] - pwsh.exe PID: 10740
6/17/2020 11:46:55 AM [NORMAL] - Language server started.
6/17/2020 11:46:55 AM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_5zmzulmw.aep","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_0hh2qihx.g3t"}
6/17/2020 11:46:55 AM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_5zmzulmw.aep...
6/17/2020 11:46:55 AM [NORMAL] - Language service connected.
```

Terminal Logs:
```
=====> PowerShell Integrated Console v2020.6.0 <=====
PS> Debugging Runspace: PowerShellManager1
To end the debugging session type the 'Detach' command at the debugger prompt, or type 'Ctrl+C' otherwise.

ResourceUnavailable: The background process reported an error with the following message: "The named pipe target process has ended.".
```

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.46.0|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.2|
|PSEdition|Core|
|GitCommitId|7.0.2|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.11|
|azure-pipelines|ms-azure-devops|1.170.0|
|AzureFunctionsSnippets|hhawkins|0.1.0|
|azurerm-vscode-tools|msazurermtools|0.10.0|
|csharp|ms-dotnettools|1.22.1|
|githistory|donjayamanne|0.6.5|
|gitlens|eamodio|10.2.2|
|kubernetes-snippets|ipedrazas|0.1.9|
|live-sass|ritwickdey|3.0.0|
|LiveServer|ritwickdey|5.6.1|
|powershell|ms-vscode|2020.6.0|
|prettier-vscode|esbenp|5.0.0|
|react-snippets|runningcoder|0.1.2|
|remote-wsl|ms-vscode-remote|0.44.3|
|sass-indented|syler|1.8.6|
|terraform|hashicorp|2.0.1|
|vscode-ansible|vscoss|0.5.2|
|vscode-azurefunctions|ms-azuretools|0.22.1|
|vscode-azureterraform|ms-azuretools|0.3.0|
|vscode-docker|ms-azuretools|1.3.0|
|vscode-dotnet-runtime|ms-dotnettools|0.1.2|
|vscode-eslint|dbaeumer|2.1.5|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.2.1|
|vscode-sql-connect|dvdbrink|0.2.1|
|vscode-yaml|redhat|0.8.0|
|vsliveshare|ms-vsliveshare|1.0.2302|

**Comment by TylerLeonhardt** [comment]
When you make a change to your Function, the Azure Functions extension kills the Azure Function that's running on your machine.

This probably why you're seeing this.
