### ISSUE TITLE
Extension fails to start: Invalid Version: null

### ISSUE THREAD

**Issue by arcotek-ltd** [PowerShell/vscode-powershell#2776]
I'll preempt this and say I am trying to run this is a heavily locked down environment, that said, I have the ability to run in admin mode that gives me around 95% of the control available to a local administrator. The security tool's logs do not show anything of note.

## Issue
Extension fails to load.
1. On VSCode startup, it appears to freeze for about 1 minute before:
![image](https://user-images.githubusercontent.com/26305145/85157754-d2fc4800-b253-11ea-8ce3-55067ffe88a3.png)
2. Clicking Keepwaiting returns control.

The language server appears to start and then I get the message in the output console: 
```
Invalid Version: null
```

The only error I can see in the logs is that the extension is trying to `Set-ExecutionPolicy` to Remote Signed, however, the session is already set to `Unrestricted` - by GPO, so the extension is unable to override the setting. `EditorService.log`, [line 295](https://gist.github.com/arcotek-ltd/1b29a4359372b2cf0704d25746384b5e#file-editorservice-log).

I read that in locked-down environments we should run the extension's module manually.
```
PS C:\Temp\Test-Code> Import-Module 'c:\Users\jsmith\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1' -Verbose -Force
VERBOSE: Loading module from path 'C:\Users\jsmith\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'.
VERBOSE: Loading module from path 'C:\Users\jsmith\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\bin/Desktop/Microsoft.PowerShell.EditorServices.Hosting.dll'.
VERBOSE: Exporting cmdlet 'Start-EditorServices'.
VERBOSE: Importing cmdlet 'Start-EditorServices'.
PS C:\Temp\Test-Code> Start-EditorServices `
>> -HostName 'Visual Studio Code Host' `
>> -HostProfileId 'Microsoft.VSCode' `
>> -HostVersion '2020.6.0' `
>> -AdditionalModules @('PowerShellEditorServices.VSCode') `
>> -BundledModulesPath 'c:\Users\jsmith\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' `
>> -EnableConsoleRepl `
>> -StartupBanner \"=====> PowerShell Integrated Console v2020.6.0 <=====\" `
>> -LogLevel 'Diagnostic' `
>> -LogPath 'c:\Users\jsmith\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1592576770-1488fe9d-79f3-4ac7-a90e-76d18a85b0391592576764308\EditorServices.log' `
>> -SessionDetailsPath 'c:\Users\jsmith\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-7560-239168' `
>> -FeatureFlags @()
DEBUG: Logging started
DEBUG: Beginning EndProcessing block

... (See Log 1)

DEBUG: Creating/running editor services
DEBUG: Creating startup info object
VERBOSE: Starting server, deregistering host logger and registering shutdown listener
\=====> PowerShell Integrated Console v2020.6.0 <=====\
```

I'm not sure what the `-SessionDetailsPath` is for, but I noticed it's pointing to a file that doesn't exist. If I give a file that doesn't exist, it gets as far as `\=====> PowerShell Integrated Console v2020.6.0 <=====\`, but an hour later nothing.

I've tried pointing it to one that does exist, with varying results:
```
VERBOSE: Starting server, deregistering host logger and registering shutdown listener
=====> PowerShell Integrated Console v2020.6.0 TESTING <=====

== Press any key to close terminal ==
```
Pressing any key gives the error about an invalid path. 

All extension logs: https://gist.github.com/arcotek-ltd/1b29a4359372b2cf0704d25746384b5e

VSCode 1.46.0 is installed in %appdata%

This is the only extension installed, via .vsix from this repo.

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Any help on this one would make a lot of people very happy.

Thanks

**Comment by EdCallahan** [comment]
I have that delay as well. I also have the invalid version and the Set-ExecutionPolicy errors as well, but they do not seem to be causing any actual issues. My issue is the powershell server startup not being recognized. In the PowerShell extension log there is a long delay after "Waiting for session file". Are you seeing that?

If so, are you running BeyondTrust PriviledgeGuard? Updating to version 5.6.126 may help.

See https://github.com/PowerShell/vscode-powershell/issues/2526#issuecomment-611122644 and later comments in that issue thread.

**Comment by arcotek-ltd** [comment]
Hi @EdCallahan,
Thanks for your reply.

The lockdown seems to be done by an application called Avecto Defendpoint. I have to right-click `code.exe` and click `CWD - Run with elevated privileges (Audited)`. I have no control over it.

Aha, so from #2526, I see "Avecto" is the same as "BeyondTrust". From looking at the properties of DefendpointService.exe, I see my device has version `5.3.229`.


Yes, in the output - PowerShell Extension Log, there is a long wait for `Waiting for session file` before it eventually comes back with:
```
Registering terminal PID log callback
Session file found
{"status":"stared","languageServiceTransport":<snip>...
Language service started.
Registering terminal close callback
Connecting to language service on pipe \\.\pipe\PSES_xw2hqmay.abn...
Language service connected.
Invalid Version: null
```
And then, as debug logging is on it spews loads of logs as per the Gist.

**Comment by arcotek-ltd** [comment]
Duplicate of #2526 , caused by Avecto/BeyondTrust.
