### ISSUE TITLE
new instance opened when running or debugging script

### ISSUE THREAD

**Issue by PhilMEFL** [PowerShell/vscode-powershell#2778]
Issue Type: <b>Bug</b>

when I try to run or debug a PS script, a new VScode windows opens and nothing else happens.

Extension version: 2020.6.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SydneyhSmith** [comment]
@PhilMEFL thanks for opening this, what debug configuration are you using?
