### ISSUE TITLE
Debugger throw an exception : An attempt was made to transition a task to a final state when it had already completed

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/vscode-powershell#279]
### System Details

_Seven x64 Fr_
- VS Code version:   _1.4.0_
- PowerShell extension version: _0.7.2_
- $PSVersionTable :

``` Powershell
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0.10586.117}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

I am experiencing a problem with the debbuger.
The debug console throw an exception : 
_An attempt was made to transition a task to a final state when it had already completed_
### Attached Logs

[Demo File](http://ottomatt.pagesperso-orange.fr/Temp/IssueWithDebugger.zip)

**Comment by daviwil** [comment]
Hey Laurent, thanks for reporting this!  I'll have to dig in a bit to see why this exception is being thrown.  There might be a regression in the debugger's command evaluation logic somewhere.

**Comment by LaurentDardenne** [comment]
I had the problem with the version 0.7.1
I have not taken the time to find a simpler demo ...

**Comment by daviwil** [comment]
No problem!  I can work with the current repro.

**Comment by LaurentDardenne** [comment]
VScode version 1.5.0 seems to correct the problem.

**Comment by daviwil** [comment]
Hmmm, not sure how it did that, but let me know if you see it again :)

**Comment by JustinGrote** [comment]
I can reproduce this consistently with this code:
```
function test {
    [CmdletBinding()]
    param (
        [String]$test1 = "test1",
        [String]$test2 = "test2"
    )
    $test = ""
    $PSCmdlet.MyInvocation.BoundParameters
}

test "test1" "test2"
```

and a breakpoint on $test = ""

start a debug session with F5 and then running the following command in the debug console:
$pscmdlet.myinvocation.boundparameters | foreach {$PSItem} | gm

it shows the Get-member output and then shows the error.
http://imgur.com/a/w5o8U 

With other commands it seems random whether it errors or not, but it almost always eventually does with this code.

**Comment by daviwil** [comment]
Interesting, I had a report from @gerane earlier about debugger problems when messing with $PSBoundParameters:

> For some reason, when debugging, if I am interacting with $PSBoundParameters in the debugger, it blows up in an odd way. No errors or anything weird in the logs, and the debugger just kind of stalls out and stops responding to input. The PSES is still running and giving intellisense etc

Not sure if there's some relation there...  Thanks for the repro script, that will be helpful!
