### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by enema17484** [PowerShell/vscode-powershell#2790]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2020.6.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.46.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rjmholt** [comment]
Please add the details of the issue you’re experiencing to the issue — there’s no way to understand what’s happening as is
