### ISSUE TITLE
older version of pacakageManagemnt

### ISSUE THREAD

**Issue by jmthia** [PowerShell/vscode-powershell#2791]
![2020-07-02_16h19_58](https://user-images.githubusercontent.com/19535773/86372509-8b79b100-bc82-11ea-8afe-a5235b12afc4.png)

Issue Type: <b>Bug</b>

Whenever I start VS Code, when the terminal starts I have a notification You have an older version of Package Mangement..
When clicking yes to update : powershell.exe -NoLogo -NoProfile -Command 'Install-Module -Name PackageManagement -Force -MinimumVersion 1.4.6 -Scope CurrentUser -AllowClobber'
But I do have 1.4.7 installed :
1.4.7      PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a new way to discover and install so...

I am running PowerShell 5.1, I also have PoSh 7 installed.

Extension version: 2020.6.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by TylerLeonhardt** [comment]
can you run:

```
Get-Module -ListAvailable PackageManagement
```

in Windows PowerShell 5.1 and share it here?

**Comment by melbit-anthonyw** [comment]
I get the same issue. My default shell for vscode is set to use PowerShell Core 7.0.2 and the moment vscode launches it opens a new terminal Window against PowerShell 5.1

PowerShell 5.1
```
PS C:\Users\Anthony> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Package Management versions in 5.1
```
PS C:\Users\Anthony> Get-Module -ListAvailable PackageManagement


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...


    Directory: C:\Users\Anthony\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.4.7      PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...


    Directory: C:\Program Files (x86)\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
```
PowerShell 7.0.2
```
PS C:\Users\Anthony> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Package Management versions in 7.0.2
```
PS C:\Users\Anthony> Get-Module -ListAvailable PackageManagement


    Directory: C:\Users\Anthony\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.4.7                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-Package…

    Directory: C:\program files\powershell\7\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.4.6                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-Package…

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     1.0.0.1               PackageManagement                   Desk      {Find-Package, Get-Package, Get-Package…
```

**Comment by jmthia** [comment]
here is my module information. 
PS > Get-Module -ListAvailable PackageManagement


    Répertoire : C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                           ExportedCommands
----------       -------    ----                                                ----------------
Binary            1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...


PS > Get-InstalledModule

Version     Name                                                Repository           Description
-------       ----                                                     ----------           -----------
5.3.0          Azure                                                 PSGallery            Microsoft Azure PowerShell - Service Management
0.5.4          Azure.AnalysisServices                      PSGallery            Microsoft Azure PowerShell - Analysis Services s...
4.6.1          Azure.Storage                                    PSGallery            Microsoft Azure PowerShell - Storage service cmd...
2.0.2.105    AzureADPreview                               PSGallery            Azure Active Directory V2 Preview Module. ...
5.8.3           AzureRM.profile                                PSGallery            Microsoft Azure PowerShell - Profile credential ...
1.0.113       dbatools                                            PSGallery            The community module that enables SQL Server Pro...
16.0.20...     Microsoft.Online.SharePoint.Powe... PSGallery            Microsoft SharePoint Online Services Module for ...
2.0.66         Microsoft.PowerApps.Administrati... PSGallery            PowerShell interface for Microsoft PowerApps and...
1.0.13         Microsoft.PowerApps.PowerShell      PSGallery            PowerShell interface for Microsoft PowerApps and...
1.0.25         MicrosoftTeams                                 PSGalleryInt         Microsoft Teams cmdlets preview module for Windo...
1.1.183.57  MSOnline                                           PSGallery            Microsoft Azure Active Directory Module for Wind...
4.2.6           NTFSSecurity                                     PSGallery            Windows PowerShell Module for managing file and ...
0.7.3           posh-git                                             PSGallery            Provides prompt with Git status summary informat...
3.22.20...     SharePointPnPPowerShellOnline       PSGallery            SharePoint Patterns and Practices PowerShell Cmd...
1.4.7           PackageManagement                        PSGallery            PackageManagement (a.k.a. OneGet) is a new way t...

the error is not blocking as answering not now will enable the extension to work. It is a little annoying, as the notification timer ends up, I must close and reopen the terminal.

It is not really the place, but I am trying to move away from ISE for debugging my PoSh code...

**Comment by jmthia** [comment]
Hurray!! found the solution. 
After installation of the lastest version of PowerShellGet (I wanted the allowPreRelease option) the powershell extension loaded without complain :)
Althought I launched update-module, PowerShellGet was still at 1.0.0.1 and did not shows up in installedModule

PS C:\WINDOWS\system32> Get-InstalledModule | select version, name

Version          Name
-------          ----
5.3.0            Azure
0.5.4            Azure.AnalysisServices
4.6.1            Azure.Storage
2.0.2.105        AzureADPreview
5.8.3            AzureRM.profile
1.0.113          dbatools
16.0.20212.12000 Microsoft.Online.SharePoint.PowerShell
2.0.66           Microsoft.PowerApps.Administration.PowerShell
1.0.13           Microsoft.PowerApps.PowerShell
1.1.3-preview    MicrosoftTeams
1.1.183.57       MSOnline
4.2.6            NTFSSecurity
1.4.7            PackageManagement
0.7.3            posh-git
2.2.4.1          PowerShellGet
3.22.2006.2      SharePointPnPPowerShellOnline

so PowerShellGet should be add to the fix command generated by the extension.
 Have a nice week-end and stay safe
