### ISSUE TITLE
The PowerShell session has terminated

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2802]
Issue Description
=====

I am experiencing a problem with... crashes

![image](https://user-images.githubusercontent.com/15063294/87232394-f338a600-c3be-11ea-8262-eac5318ad0bb.png)

Attached Logs
=====

[1594496114-7bd55350-ef45-4945-8dca-25e1aea6be2e1594492769663.zip](https://github.com/PowerShell/vscode-powershell/files/4907512/1594496114-7bd55350-ef45-4945-8dca-25e1aea6be2e1594492769663.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.47.0|
| PowerShell Extension Version | 2020.6.1 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.0-preview.5|
|PSEdition|Core|
|GitCommitId|7.1.0-preview.5|
|OS|Microsoft Windows 10.0.19041|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.0-preview.5|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|code-settings-sync|Shan|3.4.3|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.2|
|markdown-all-in-one|yzhang|3.1.0|
|material-icon-theme|PKief|4.2.0|
|powershell-preview|ms-vscode|2020.6.1|
|project-manager|alefragnani|11.1.0|
|run-in-powershell|tobysmith568|1.0.1|
|vscode-markdownlint|DavidAnson|0.36.1|
|vscode-pull-request-github|GitHub|0.17.0|
|vscode-toggle-quotes|BriteSnow|0.3.3|
|vscode-wakatime|WakaTime|4.0.0|
|vscode-yaml|redhat|0.8.0|
|xml|DotJoshJohnson|2.5.0|

**Comment by SydneyhSmith** [comment]
Thanks @PrzemyslawKlys looking at your logs seems like this could be a race condition issue that Rob is actively working  on
