### ISSUE TITLE
Intellisense when developing on Raspbian

### ISSUE THREAD

**Issue by injector22** [PowerShell/vscode-powershell#2803]
Does anyone know if Intellisense works when developing on Raspbian? I have installed pwsh on the pi and that runs fine. I can also remote connect to the pi via SSH (using Remote Development extension), I can create files, run bash commands and even run pwsh.

But intellisense does not work, I have the slight feeling that this is related to the default terminal being bach and now pwsh. However, I do not see an option to switch over to pwsh in the same way you can in Windows.

**Comment by TylerLeonhardt** [comment]
Can you verify that the PowerShell extension is installed on the server side?

**Comment by injector22** [comment]
By server side, do you mean on the Pi?

**Comment by injector22** [comment]
Found the issue, The PowerShell extension doesn't install remote SSH support by default. When I looked up the extension (even though I already had it installed) it has a green message stating "Install in SSH"

![image](https://user-images.githubusercontent.com/5377979/87256677-d2299100-c462-11ea-94b6-c351ba04e95e.png)

After it installed and I reloaded vscode, Intellisense works fine.

**Comment by TylerLeonhardt** [comment]
Yep! That's exactly what I was asking to check for :) thanks!
