### ISSUE TITLE
Provide progress indicator for language/debug server startup

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#281]
Some users are attempting to start debugging just after loading a PowerShell script for the first time in a session.  In some cases the language and debug servers have not yet finished initializing so there needs to be some indication in the UI that the extension isn't fully initialized yet.

**Comment by daviwil** [comment]
Adding this to 0.8.0 but I might fix it in a patch release if it turns out to be a common source of confusion.

**Comment by daviwil** [comment]
Also need to have a better error message when the user tries to run the debugger when PSES hasn't finished starting.

**Comment by rkeithhill** [comment]
BTW, depending on what's in the user's profile this can take several seconds.  I've seen PowerShell take as much as ~15 seconds to cold start.  The 5.1 version of PowerShell will tell you how long it took to process your profile - giving you a strong hint that if you want PowerShell to load faster - lighten up your profile.  I wonder if we could do the same?  Display a progress message like "Processing your PowerShell profile scripts...", "Importing and initializing the PowerShellEditorServices module...".

**Comment by daviwil** [comment]
Based on the way I do startup I'm not sure if I'll be able to give updates to the UI between those phases.  I launch powershell.exe and it basically takes care of loading the PSES module.  Maybe after loading is complete I could give some message if a certain part of the process takes longer than a certain time expectation?

**Comment by daviwil** [comment]
I've decided to do this work for 0.8.0 since there are a few things I want to do to make it easier for users to easily understand the state of PSES when the extension is running:

- [ ] Implement new status bar item like the C# extension which makes it obvious whether PSES is initializing, running, or failed.
- [ ] Create a new output channel which will contain client-side PSES log output
- [ ] Hook up a command to the status bar item which shows the PSES log output window in case any error occurs

**Comment by daviwil** [comment]
I've pushed a branch with the initial work on this here: https://github.com/PowerShell/vscode-powershell/tree/daviwil/extension-status.  Will continue after I've completed some other things.
