### ISSUE TITLE
Debug session reports timeout after 10000 ms.

### ISSUE THREAD

**Issue by mverbaas** [PowerShell/vscode-powershell#2821]
Issue Type: <b>Bug</b>

After debug sessions ends, it errors out with "timeout after 10000 ms" message and doesn't close the debug controls.

Extension version: 2020.6.0
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (4 x 3196)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (8.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by SydneyhSmith** [comment]
Thanks @mverbaas for opening this issue, it would be great it you could provide a bit more context around what you were doing/what vscode looked like when this happened (screen shots and gifs are great!) it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by mverbaas** [comment]
Hi @SydneyhSmith, sorry for the lack of the data. Hope this attachment contains some leads.
[github#2821.zip](https://github.com/PowerShell/vscode-powershell/files/4958362/github.2821.zip)

**Comment by DAD713** [comment]
I see the same issue debugging powershell scripts.  It happens often when sitting at a breakpoint for a bit.

**Comment by SydneyhSmith** [comment]
Thanks for all the additional information, are you experiencing any issues beyond the strange notification...or if you just ignore the notification are you otherwise able to perform your desired tasks.

Looks like a race condition within the debugger between cleaning up the pipe, and responding to that message.

**Comment by DAD713** [comment]
Ya, I just ignore it, click through it.  It restarts without an issue.

**Comment by mverbaas** [comment]
I just stop the debugger at the top (for me) and can continue without any noticeable effects.

**Comment by andschwa** [comment]
@mverbaas Can you test if this is still reproducing with v2021.9.0? Thanks!

**Comment by mverbaas** [comment]
> @mverbaas Can you test if this is still reproducing with v2021.9.0? Thanks!

@andschwa, to be honest I forgot about this as I haven't seen it in a long time!

**Comment by andschwa** [comment]
That's fantastic @mverbaas. I'm going to mark this as resolved for now, please let us know if you see it again!
