### ISSUE TITLE
First execution of PowerShell script changes context into debugger

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#283]
### System Details
- Operating system name and version:
- VS Code version: 1.4.0
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`: 

```
PS C:\Users\TrevorSullivan> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.103
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.103
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### Issue Description

When you open VSCode and run a PowerShell script, for the first time in the new session, the PowerShell Extension switches VSCode from the Explorer context, into the Debugging context. Subsequent executions do not do this.
### Reproduction Steps
- Open VSCode
- Open a project with a PowerShell script (in my case, a Pester test script)
- Hit F5 to run the script
- **NOTICE**: VSCode changes into debugging context, and script runs/exits
- Go back to Explorer context in VSCode (CTRL + SHIFT + E)
- Hit F5 to run the script again
- **NOTICE**: VSCode doesn't change into the debugger context

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment]
This is VS Code's doing and I don't think there's any way for me to turn it off.  Might be worth filing a feature request to them to provide an option to not automatically jump to the debugging workspace when debugging starts for the first time.

**Comment by SydneyhSmith** [comment]
Closing this as resolved, as I am unable to repro--will reopen if this is still an issue.
