### ISSUE TITLE
PowerShell Integrated Console does not appear

### ISSUE THREAD

**Issue by torx25** [PowerShell/vscode-powershell#2835]
PowerShell Integrated Console does not appear at all. When I hit F5 to run random .ps1 script, I got error "Couldn't find a debug adapter descriptor for debug type 'PowerShell' (extension might have failed to activate)".

![2020-07-27 13_03_51-Get-Uptime ps1 - PowerShell - Visual Studio Code  Administrator](https://user-images.githubusercontent.com/52157013/88528015-1abe7e00-d00f-11ea-911e-8bdc98231fd5.png)

![2020-07-27 13_44_14-Clipboard](https://user-images.githubusercontent.com/52157013/88528620-eac3aa80-d00f-11ea-95b0-65a967c61587.png)

I can't get PS extension logs due to error: "command 'PowerShell.GenerateBugReport' not found".

![2020-07-27 13_03_38-](https://user-images.githubusercontent.com/52157013/88528019-1befab00-d00f-11ea-96ff-c13d21702783.png)

I tried to reinstall VS Code, to reinstall the PS extension, to install the preview version of the extension.
I have two user accounts on my PC - 1) admin and 2) non-admin user. And I'm getting issues only when I run VS code as an administrator. 
Of course, I tried replacing all admin VSCode settings with non-admin user settings - that didn't work.

-----------------------------------------------------------------------------------------------
launch.json:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File",
            "script": "${file}",
            "args": [],
            "cwd": "${file}"
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File in Temporary Console",
            "script": "${file}",
            "args": [],
            "cwd": "${file}",
            "createTemporaryIntegratedConsole": true
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File w/Args Prompt",
            "script": "${file}",
            "args": [
                "${command:SpecifyScriptArgs}"
            ],
            "cwd": "${file}"
        },
        {
            "type": "PowerShell",
            "request": "attach",
            "name": "PowerShell Attach to Host Process",
            "processId": "${command:PickPSHostProcess}",
            "runspaceId": 1
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Interactive Session",
            "cwd": ""
        }
    ]
}

-----------------------------------------------------------------------------
 code -v
1.47.2
17299e413d5590b14ab0340ea477cdd86ff13daf
x64

code --list-extensions --show-versions
aeschli.vscode-css-formatter@1.0.1
luggage66.VBScript@0.0.2
ms-vscode.powershell@2020.6.0
zehfernando.theme-actual-obsidian@2.1.0

$PSVersionTable

Name                               Value
----                                   -----
PSVersion                         5.1.18362.752
PSEdition                          Desktop
PSCompatibleVersions      {1.0, 2.0, 3.0, 4.0...}
BuildVersion                       10.0.18362.752
CLRVersion                        4.0.30319.42000
WSManStackVersion           3.0
PSRemotingProtocolVersion 2.3
SerializationVersion            1.1.0.1

---------------------------------------------------------------------

**Comment by Gabrielbidou** [comment]
Having the exact same issue here, but didn't have it before...

**Comment by SydneyhSmith** [comment]
Thanks--looks like the same issue as https://github.com/PowerShell/vscode-powershell/issues/2808

**Comment by torx25** [comment]
> Thanks--looks like the same issue as #2808

You're right, updating to 1.47.3 VSCode has resolved my issue. Now I can run scripts as admin - without any errors. Thank you!

![2020-07-29 10_02_47-Clipboard](https://user-images.githubusercontent.com/52157013/88762978-5417fa80-d183-11ea-9a50-97ca06e85615.png)

**Comment by jsantoro339as** [comment]
This error seems to be back again today. 

![image](https://github.com/user-attachments/assets/00df4fac-890e-43fc-afce-08c49a7b66d6)

![image](https://github.com/user-attachments/assets/eeaa631a-d653-4559-b3d4-5556f166f0f3)

![image](https://github.com/user-attachments/assets/96fb95a9-fb70-40f2-a072-305d57eeb187)

![image](https://github.com/user-attachments/assets/ec6d17c2-b55a-42d1-86ea-8065f9af5e6e)

![image](https://github.com/user-attachments/assets/8bc9b97a-9283-475b-9493-5111ebdd9fb8)

**Comment by andyleejordan** [comment]
@jsantoro339as hi, your issue appears to be a duplicate of #5084. Please try PowerShell 7, or rollback to the previous stable version, while we work on addressing the root cause. Thanks!

**Comment by jsantoro339as** [comment]
I tried with PS 7 and same result.  Then I completely removed it and all references of it and did a clean install of version 1.94.2 and am getting the same errors seen above.  I have more of a feeling that maybe it is the Official PowerShell Extension, any thoughts?

**Comment by andyleejordan** [comment]
We're pushing out a pre-release soon that should hopefully address it. I'll let you know when to try it.
