### ISSUE TITLE
debug console doesn't show breaks

### ISSUE THREAD

**Issue by JustinWebDev** [PowerShell/vscode-powershell#2838]
Issue Type: <b>Bug</b>

Open DebugTest.ps1
set a breakpoint for write-output
run debug - it stops/breaks on a write-output cmd (as expected)
  - the CALL STACK section of the Debug view confirms this

But, the "DEBUG CONSOLE" is empty.

ref https://devblogs.microsoft.com/scripting/debugging-powershell-script-in-visual-studio-code-part-1/

Extension version: 2020.6.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (27.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details>

**Comment by SydneyhSmith** [comment]
Thanks @JustinWebDev-- the debug console is not integrated with the PowerShell extension today, because the integrated console serves this purpose
