### ISSUE TITLE
Notebook Mode: The comment block is not recognized as a Markdown block

### ISSUE THREAD

**Issue by mkht** [PowerShell/vscode-powershell#2845]
Well, can I post any feedback on the Notebook mode that Tyler Leonhardt has posted on the PowerShell blog?
https://devblogs.microsoft.com/powershell/public-preview-of-notebook-mode-in-the-powershell-preview-extension-for-visual-studio-code/

### Issue Description
The comment block style that our team normally uses doesn't seem to be correctly parsed as a Markdown block in the Nodebook mode.

```PowerShell
<# =========================
# Write comment here
============================ #>
```

I hope this is improved.

### Text mode
![image](https://user-images.githubusercontent.com/25482642/89039695-7b3a1c00-d37d-11ea-80cd-dcd95fcbd57f.png)

### Notebook mode
![image](https://user-images.githubusercontent.com/25482642/89039718-855c1a80-d37d-11ea-901d-d0c5f662e06c.png)

**Comment by TylerLeonhardt** [comment]
That's odd. That should work. Do normal block comments work?

```
<#
Foo
#>
```

**Comment by mkht** [comment]
Hi @TylerLeonhardt 
Yes, normal block comments are working fine.

![note](https://user-images.githubusercontent.com/25482642/89047511-767b6500-d389-11ea-91f9-8698336b4fd7.png)

**Comment by rjmholt** [comment]
What about this one:

```powershell
<# x
# Comment
#>
```

**Comment by TylerLeonhardt** [comment]
I bet the first case is broken

**Comment by rjmholt** [comment]
The code indicates that we expect the whole line to be the comment delimiter, rather than just contain it:

https://github.com/PowerShell/vscode-powershell/blob/2d30df76eec42a600f97f2cc28105a9793c9821b/src/features/PowerShellNotebooks.ts#L125

https://github.com/PowerShell/vscode-powershell/blob/2d30df76eec42a600f97f2cc28105a9793c9821b/src/features/PowerShellNotebooks.ts#L100

**Comment by mkht** [comment]
Unfortunately, this is not good in all three cases.
Is this an issue specific to my environment? Is everyone OK?

### Case 1
![case1](https://user-images.githubusercontent.com/25482642/89048481-dc1c2100-d38a-11ea-9cfd-f5a250021f97.png)

### Case 2
![case2](https://user-images.githubusercontent.com/25482642/89048501-e0483e80-d38a-11ea-91b4-b3d39767cd12.png)

### Case 3
![case3](https://user-images.githubusercontent.com/25482642/89048514-e63e1f80-d38a-11ea-9f46-927e5b9453fe.png)

**Comment by rjmholt** [comment]
> Is this an issue specific to my environment?

It's a general bug that we'll fix in the next update. For now cells must start with the line `<#` and end with the line `#>`

**Comment by TylerLeonhardt** [comment]
Yep, should be a straightforward fix and you've given us a great test case :)
