### ISSUE TITLE
Debug adapter does not restart correctly when client connection gets forcibly terminated

### ISSUE THREAD

**Issue by sethreidnz** [PowerShell/vscode-powershell#285]
**Please fill in these details so that we can help you!**
### System Details
- Operating system name and version: Windows 10
- VS Code version: 1.4.0
- PowerShell extension version:     0.7.2
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### Issue Description

I have been trying to debug PowerShell and lately it has been crashing powershell itself. From a fresh restart it is fine and works. But if I stop the debugger (or sometimes just randomly) I will get this happening:

![powershell-has-stopped-working](https://cloud.githubusercontent.com/assets/4713713/18337439/c67b2722-75e4-11e6-8adf-1906f5cfb587.PNG)
### Attached Logs

Have emailed these with issue details as well.

**Comment by daviwil** [comment]
Thanks for sending the logs Seth!  I'll take a look today.

**Comment by justsayno** [comment]
Thanks let me know if you need anything else. It's pretty consistent I can
repro it every time I restart. Frustrating cuz it forces me back to the
dreaded PowerShell ISE :-)

**Comment by justsayno** [comment]
Any progress on this? It's has happened to me about 4-5 time in the last 30 minutes... I love using vsCode for this so much more than Powershell ISE that I just restart my computer and keep going :-)

Do you know how I could restart the powershell process without a reboot?

**Comment by daviwil** [comment]
Hmmm, you shouldn't have to restart your computer to resolve the issue. Does restarting VS Code not make the problem go away? I was looking over your logs on Friday and nothing was fully jumping out at me yet. Will take another look tomorrow!

**Comment by justsayno** [comment]
No it seems that vsCode is crashing the powershell process. And if I restart it still is crashed. It's almost like it keeps a record of which process it spawned and won't just spawn another one... I can successfully debug without restarting in PowerShell ISE after vscode crashes so I don't think its a system wide issue now that I think about it.

**Comment by daviwil** [comment]
@justsayno It only crashes the current session's process.  Each new VS Code session creates a new powershell.exe process.  It's likely that the next time you start VS Code you are attempting to start the debugger too fast before the next powershell.exe starts up.

Issue #281 should address that so it's more clear that the language/debug server hasn't fully initialized yet.  For now if you wait another 5-10 seconds after startup you should be able to start debugging again without restarting your computer.

**Comment by justsayno** [comment]
Thanks for that. Any ideas on what is crashing it? It's very intermittent and I can't really figure out if it's something that my scripts are doing (I don't **think** so)

**Comment by daviwil** [comment]
Your folder contained a lot of logs and it was hard to pinpoint where the crashing was happening.  How reliably can you reproduce the issue? If you can do it pretty reliably, could you clear out your logs folder and reproduce the issue then send me the targeted logs?  If it's not easy to reproduce I'll just continue sorting through the logs to see what I can find.

**Comment by daviwil** [comment]
Actually, I think I do see the issue now.  I'm not sure what's causing it, but it looks like the connection between VS Code and the debugger is getting forcibly closed at times.  This could be an unexpected issue with the debugger client but I'm not quite sure yet.

At least on my side, there's an issue where this type of forced close isn't causing the debug adapter to shut down correctly so it's impossible to connect again from VS Code (requiring the session restart like you're experiencing).  I'll try to solve that issue so that you don't have to restart VS Code at least.

In the future if you see this issue again, could you copy/paste the logs that show up inside VS Code's developer console?  You can get to it from the menu `Help -> Toggle Developer Tools`.

**Comment by justsayno** [comment]
Yes I will. I will clear my logs now as I am working on a PowerShell scripts and it might happen. Thanks for your help.

**Comment by carlosrfernandez** [comment]
Is there any workaround for this? I've just updated to VSCode 1.6 and while restarting was working before, it isn't working with 1.6.

**Comment by SydneyhSmith** [comment]
We recently published an update to our extension which has addressed a number of underlying architectural issues, would you mind giving it a try and letting us know if you are still hitting this issue?
