### ISSUE TITLE
Cannot create process, error code 740

### ISSUE THREAD

**Issue by PhilMEFL** [PowerShell/vscode-powershell#2853]
Issue Type: <b>Bug</b>

As soon I install  the Powershell extension, I get the message The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 740).

Extension version: 2020.6.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (0.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SydneyhSmith** [comment]
Thanks @PhilMEFL it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by rjmholt** [comment]
In addition to the logs, any extra info about where you see this error and how would be useful. The most useful is a screenshot or a gif of the error occurring and the full text of it.

**Comment by huseeiin** [comment]
i'm getting the same error, too

**Comment by rjmholt** [comment]
> i'm getting the same error, too

Please see the comments above. We need more information to help you

**Comment by BestUsernameEver2** [comment]
Hi,
While I can't speak for OP, I can say that this is currently happening for me. Just got Visual Studio Code today since PowerShell ISE doesn't support powershell 7 by default.
It happens only when I'm running Visual Studio Code as a standard user. If I run Visual Studio Code with administrative rights, it works fine, which is not ideal.
Also, is your ms-vscode.powershell extension supposed to be a Preview? Because that's what it's set to. You have two 'Preview' powershell extensions of different versions, but no production/non-preview extension. The second one is ms-vscode.powershell-preview.
I tried installing 2020.4.0 of ms-vscode.powershell but still get the "Cannot create process, error code: 740" error
![image](https://user-images.githubusercontent.com/75814523/101839326-ca504480-3b07-11eb-9f7a-8698c56b360a.png)

I'll get some logs tomorrow and e-mail those to vscode-powershell@microsoft.com and run procmon on VSC to see what it's getting hung up on.

**Comment by rjmholt** [comment]
@BestUsernameEver2 the preview issue is https://github.com/PowerShell/vscode-powershell/issues/2774.

Can you provide a screenshot of the startup issue as you see it in the UI?

**Comment by BestUsernameEver2** [comment]
@rjmholt Ahh, that solves the preview mystery then, thank you!

For the startup issue, here's what the UI looks like launching powershell, bottom-right of screenshot:
![image](https://user-images.githubusercontent.com/75814523/101913159-42f6e580-3b88-11eb-8448-cc89b31ef391.png)

I e-mailed the trace logs over to vscode-powershell just now
I'll see what procmon finds

**Comment by BestUsernameEver2** [comment]
To followup:
![image](https://user-images.githubusercontent.com/75814523/101916866-24471d80-3b8d-11eb-96a2-3e6d0e8fd331.png)

**Comment by BestUsernameEver2** [comment]
I'm silly. Powershell 7's exe had 'Run this program as an administrator' checked in the Compatibility tab, but a UAC prompt wasn't coming up when VSC tried using it so I was none the wiser
Unchecked the box, everything's communicating properly now hehe
Happy Friday!

**Comment by rajumu1297** [comment]
> I'm silly. Powershell 7's exe had 'Run this program as an administrator' checked in the Compatibility tab, but a UAC prompt wasn't coming up when VSC tried using it so I was none the wiser Unchecked the box, everything's communicating properly now hehe Happy Friday!

-----------------------------------------------------------------------------------------------------------------------------------------
@BestUsernameEver2 
I faced the same issue today. Your fix helped. I have disabled UAC and had set PowerShell 7 to open as Admin.
Thank you for posting the fix.

**Comment by NidusUmbra** [comment]
I still think it would be great if we could successfully start a ps session when launching vs code although ps is set to launch as admin at the system level.

The de facto context is this: Right-click-"run as admin" is tedious and shouldn't even be a thing on an admin-account but Windows is the way it is, and people who proactively use terminals for anything at all is going to want to launch it as admin. Having once figured out how to do that, you would rather not switch back. 

Of course I see the problem of disparate privileges when ps has admin rights and vs code does not, but that really just points to the issue of vs code not playing well with elevated privileges. One thing it will break is the "open with vs code" context menu.

Having to sacrifice either auto-running terminals as admin or "open in vs code" in context menu is a no-win.
