### ISSUE TITLE
Cannot insert commands from extensions

### ISSUE THREAD

**Issue by vrajwanshi** [PowerShell/vscode-powershell#2864]
Issue Type: <b>Bug</b>

Click on Pen Icon (Insert Command)

Error running command PowerShell.InsertCommand: Running the contributed command: 'PowerShell.InsertCommand' failed.. This is likely caused by the extension that contributes PowerShell.InsertCommand.

Extension version: 2020.6.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G630 @ 2.70GHz (2 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.91GB (2.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SydneyhSmith** [comment]
Thanks @vrajwanshi it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)..a screenshot/GIF would also be great! 

cc: @corbob

**Comment by andrewsav-bt** [comment]
https://github.com/PowerShell/vscode-powershell/issues/2793
