### ISSUE TITLE
Support Untitled files with Notebook Mode

### ISSUE THREAD

**Issue by EmmanuelDefranc** [PowerShell/vscode-powershell#2865]
**Summary of the new feature**

Allow the possibility of switching to Notebook Mode without the need to save the ps1 file first.

**Proposed technical implementation details (optional)**

It would be easier to just be able to switch back and forth between the Notebook Mode (enable / disable) without the necessity of saving the ps1 file first.

**Comment by TylerLeonhardt** [comment]
The ability for this to work at vscode level was added over the weekend. So we can do this now but it won't exactly work as expected because

We can't close any open file if it's Untitled without prompting the user with "do you want to save or discard this"
