### ISSUE TITLE
Notebook Mode enabled for specific files

### ISSUE THREAD

**Issue by EmmanuelDefranc** [PowerShell/vscode-powershell#2866]
**Summary of the new feature**

Include a new keyword that allows VSCode to open the .ps1 with Notebook Mode enable right away.

**Proposed technical implementation details (optional)**

Since the idea of the PowerShell Notebook Mode is to have the same file extension for scripts or interactive books, it would be great if there was such a code instruction that would open the ps1 right away either with Notebook Mode enabled or disabled.

e.g. #Requires -NotebookMode enabled
The keyword 'requires' does not suit the case, but I meant to show how the idea could be somehow implemented

**Comment by TylerLeonhardt** [comment]
We can probably do this with just a vscode setting.

@rebornix is it possible to dynamically control this behavior of which editor the file gets open with?

Could that setting I used in the beginning of Notebook support be used? I forget the name of the setting.

**Comment by EmmanuelDefranc** [comment]
Hey Tyler,

What I have in mind is a setting on a per file level. if this value would be present on the file (like e.g. #Requires) it would make VSCode open the the .ps1 directly on Notebook Mode, We might not want all ps1 files to be opened only on 1 way for all files.

Having tens of .ps1 some suitable for the Notebook Mode, still others would suit to stay on the old scripting editor view, with this 'parameter' in the file itself, we would save the end-user a lot of clicks on the .ps1 files.

**Comment by TylerLeonhardt** [comment]
I'd rather do that at the file level like `foo.Notebook.ps1` because vscode already provides a mechanism for handling files with certain extensions.

**Comment by EmmanuelDefranc** [comment]
That is a cool feature I was not aware of.

Is this something I should configure on my own on my local VSCode, or would this be included as a feature within Notebook Mode?

**Comment by TylerLeonhardt** [comment]
This would be a feature of Notebook Mode that would need to be added. If you open a file called `foo.Notebook.ps1`, it would open the file in Notebook Mode automatically.

I'm still not sure exactly how to solve for this yet.
