### ISSUE TITLE
Notebook Mode - #Require statement appear as markdown cells

### ISSUE THREAD

**Issue by EmmanuelDefranc** [PowerShell/vscode-powershell#2867]
Issue Description
=====

When putting a #Require statement in a .ps1 file and enabling Notebook Mode, the line appears as a markdown cell.
![image](https://user-images.githubusercontent.com/46925220/89405398-c5bfed80-d71b-11ea-9fac-eba35813aae9.png)

Attached Logs
=====

No logs required

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.48.0-insider|
| PowerShell Extension Version | 2020.7.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.3|
|PSEdition|Core|
|GitCommitId|7.0.3|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.3|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.1|
|powershell-preview|ms-vscode|2020.7.0|
|vscode-azurefunctions|ms-azuretools|0.23.0|

**Comment by TylerLeonhardt** [comment]
What do you expect to happen?

It's technically a comment and the play button, just like F8, isn't smart enough to check if you can run that code block.

**Comment by EmmanuelDefranc** [comment]
Hey Tyler,

I did not know that #Requires does not run on F8 (it treats it like a comment) - thanks for the info!

The idea is that the '#Requires' should be hidden from the Notebook. As of now it gets included in the markdown cell either we want it or not. I do not see the reason to show it in the Notebook, still I see the need to keep it in some ps1 files, in order to prevent from running when some predefine requisites are not met.

**Comment by SydneyhSmith** [comment]
While we would rather not special case not seeing the Require block as markdown, the issue that this creates  space between # and Require warrants fixing, and likely the easiest way to do that is through a special casing

**Comment by andschwa** [comment]
We've removed the experimental notebook support in #3176, going to mark this resolved.
