### ISSUE TITLE
Notebook Mode switching with New/Untitled file (2 bugs)

### ISSUE THREAD

**Issue by EmmanuelDefranc** [PowerShell/vscode-powershell#2868]
Issue Description
=====

1. Created a new file,

2. Pressed F1 and chose Lang -> PowerShell,

3. Wrote some code,
![image](https://user-images.githubusercontent.com/46925220/89405966-b42b1580-d71c-11ea-9d60-b146ed1c4240.png)

4. Enable: Notebook Mode,
![image](https://user-images.githubusercontent.com/46925220/89406036-ca38d600-d71c-11ea-8beb-4ccaceef94e8.png)

5. This message appears:
![image](https://user-images.githubusercontent.com/46925220/89406043-cefd8a00-d71c-11ea-87af-579589cb326f.png)

6. Using the 'Don't save' button causes this:
![image](https://user-images.githubusercontent.com/46925220/89406067-dc1a7900-d71c-11ea-876d-1bbef0e30362.png)
**AND** the file is **LOST**

7. Using the 'Save' button causes a similar thing:
![image](https://user-images.githubusercontent.com/46925220/89406233-256ac880-d71d-11ea-9748-71e3bd55c628.png)
so far so good, but after saving with a name e.g. Test1.ps1, this happens:
![image](https://user-images.githubusercontent.com/46925220/89406367-59de8480-d71d-11ea-9871-27013cd5afb3.png)
Note: It is Untitled-2 with a '2' because the '1' was used on the 'Don't save' example/screenshots
**AND** The file is closed from VSCode:
![image](https://user-images.githubusercontent.com/46925220/89406485-82ff1500-d71d-11ea-98ea-33289c048dc7.png)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.48.0-insider|
| PowerShell Extension Version | 2020.7.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.3|
|PSEdition|Core|
|GitCommitId|7.0.3|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.3|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.1|
|powershell-preview|ms-vscode|2020.7.0|
|vscode-azurefunctions|ms-azuretools|0.23.0|

**Comment by TylerLeonhardt** [comment]
Really Notebook Mode needs to support Untitled files all up. I'm gonna dupe this to https://github.com/PowerShell/vscode-powershell/issues/2865#issuecomment-669220338 and we'll use that issue to track support for Untitled files in Notebook Mode.
