### ISSUE TITLE
Feature Request: Prompts for things like 'Get-Credential'

### ISSUE THREAD

**Issue by rasmus91** [PowerShell/vscode-powershell#287]
### System Details

- Operating system name and version: Windows 10 Enterprise
- VS Code version: 1.5.1
- PowerShell extension version: Newest available
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.0.10240.16384                                                                         
WSManStackVersion              3.0                                                                                     
SerializationVersion           1.1.0.1                                                                                 
CLRVersion                     4.0.30319.42000                                                                         
BuildVersion                   10.0.10240.16384                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     

```

### Issue Description

Well, it's really a matter of  certain features not functioning very well, like for instance if you open Powershell and do: "Get-Credential -Message 'Some Message" -UserName 'john@doe.com'" you get a login prompt. When you do it in the VSCode PS extension however, you get this:

`Get-Credential -Message "some message" -UserName 'john@doe.com'

Get-Credential : 'Get-Credential' is not yet supported.
At line:1 char:1
+ Get-Credential -Message "some message" -UserName 'john@doe.com'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Credential], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.PowerShell.Commands.GetCredentialCommand`

I understand the difficulties of implementing something like that cross platform and all, I also know i can make a work around by doing a "$pw = (Read-Host -Prompt 'Enter john@doe.com's password')" even in this case though, i can't use "-AsSecureString" switch, but i would have to either convert it after, or pipe it. 

having these prompts is part of what makes it a nice experience to use powershell over other terminals and scripting languages though, because when you make a script that performs some function, it feels highly interactive, and non-tech colleagues even, understand a login box. So just something to consider.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Hey @rasmus91, support for anything requiring secure prompts has been on our backlog for a while: #57.  I am about to start working on a new way of integrating a PowerShell terminal into VS Code that should hopefully solve this problem for good.  I'll go ahead and close this issue since we're already tracking that feature request, but thanks for filing it!
