### ISSUE TITLE
Modern authentication prompts open in background

### ISSUE THREAD

**Issue by danmyhre** [PowerShell/vscode-powershell#2873]
Issue Type: <b>Bug</b>

When you call something like "Connect-ExchangeOnline", the modern auth (web-based) auth dialog opens behind VS Code

Extension version: 2020.6.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by corbob** [comment]
This is an issue vscode/electron and being tracked here: https://github.com/PowerShell/vscode-powershell/issues/621
