### ISSUE TITLE
PowerShell takes a long time to start

### ISSUE THREAD

**Issue by danmyhre** [PowerShell/vscode-powershell#2874]
Issue Type: <b>Performance Issue</b>

Should at least be as fast as ISE.  Takes too long from opening a ps1 file to being able to run it.

Extension version: 2020.6.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by SydneyhSmith** [comment]
Thanks @danmyhre it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)...it would also be helpful to know if you are running on a system with configuration like group policy or execution policy.
