### ISSUE TITLE
Language Service Startup Failure

### ISSUE THREAD

**Issue by mrfusion9k** [PowerShell/vscode-powershell#2883]
Issue Type: <b>Bug</b>

I get the following error as soon as I install the Powershell Module.  I've tried the other remediations with this issue before but they didn't help resolve the issue:

```
8/11/2020 3:38:29 PM [NORMAL] - Visual Studio Code v1.47.3 64-bit
8/11/2020 3:38:29 PM [NORMAL] - PowerShell Extension v2020.6.0
8/11/2020 3:38:29 PM [NORMAL] - Operating System: Windows 64-bit
8/11/2020 3:38:29 PM [NORMAL] - Language server starting --
8/11/2020 3:38:29 PM [NORMAL] -     PowerShell executable: C:\Users\USERNAME\.dotnet\tools\pwsh.exe
8/11/2020 3:38:29 PM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\USERNAME\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\USERNAME\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\USERNAME\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1597185509-1cd41081-ba13-46ce-a521-04fac2c8e3641597185490324\EditorServices.log' -SessionDetailsPath 'c:\Users\USERNAME\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-39288-708804' -FeatureFlags @() 
8/11/2020 3:38:29 PM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\USERNAME\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\USERNAME\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\USERNAME\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1597185509-1cd41081-ba13-46ce-a521-04fac2c8e3641597185490324\EditorServices.log' -SessionDetailsPath 'c:\Users\USERNAME\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-39288-708804' -FeatureFlags @() 
8/11/2020 3:38:29 PM [NORMAL] - pwsh.exe started.
8/11/2020 3:38:29 PM [NORMAL] - Waiting for session file
8/11/2020 3:42:30 PM [NORMAL] - Timed out waiting for session file to appear.
8/11/2020 3:42:30 PM [NORMAL] - Language server startup failed.
8/11/2020 3:42:30 PM [ERROR] - The language service could not be started: 
8/11/2020 3:42:30 PM [ERROR] - Error: Timed out waiting for session file to appear.
```

Extension version: 2020.6.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment]
Are you seeing any errors in the console?

**Comment by mrfusion9k** [comment]
I see them as popup notifications when I start powershell or install the
powershell module.  I then get the prompt to copy the console from there
and file a bug or try to fix it.

**Comment by rjmholt** [comment]
But in the console, which is to say the terminal, what do you see?

Can you try the extension build from https://github.com/PowerShell/vscode-powershell/issues/2719#issuecomment-671676720

**Comment by mrfusion9k** [comment]
Nothing appears in the terminal. I only see something in the notifications box and get the button to show logs to send to support.  I also tried the extension you recommended and it immediately errored.

**Comment by rjmholt** [comment]
> and it immediately errored.

Did it error in the same way? We need as much information you can provide to try and fix the problem. That means:

- Where the error appeared
- The error text/message
- Ideally a screenshot/gif

**Comment by tronster** [comment]
If it helps: The Powershell version caused this issue for me. 

Was just having the same issue when I came across this thread; I was running 6.2.3 but my coworkers had no issues and I learned they were on 7.0.3.  Installed the latest Powershell and now the plug-in works fine.  That pwsh.exe path looks like it may be 6.x.x (Powershell Core) and not the latest 7.x.x which is installed to: C:\Program Files\PowerShell\7\

**Comment by rjmholt** [comment]
> I was running 6.2.3 but my coworkers had no issues and I learned they were on 7.0.3. Installed the latest Powershell and now the plug-in works fine. That pwsh.exe path looks like it may be 6.x.x (Powershell Core) and not the latest 7.x.x which is installed to: C:\Program Files\PowerShell\7\

This is the issue solved by the build in https://github.com/PowerShell/vscode-powershell/issues/2719#issuecomment-671676720

**Comment by mrfusion9k** [comment]
When I tried to install that extension it threw this: 

8/12/2020 12:29:33 PM - Microsoft VSIX Installer
8/12/2020 12:29:33 PM - -------------------------------------------
8/12/2020 12:29:33 PM - vsixinstaller.exe version:
8/12/2020 12:29:33 PM - 16.8.1017
8/12/2020 12:29:33 PM - -------------------------------------------
8/12/2020 12:29:33 PM - Command line parameters:
8/12/2020 12:29:33 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\brdunc\Downloads\PowerShell-insiders.vsix
8/12/2020 12:29:33 PM - -------------------------------------------
8/12/2020 12:29:33 PM - Microsoft VSIX Installer
8/12/2020 12:29:33 PM - -------------------------------------------
8/12/2020 12:29:33 PM - Initializing Install...
8/12/2020 12:29:34 PM - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__67_1(String s)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by rjmholt** [comment]
> When I tried to install that extension it threw this:

You're running it with Visual Studio's VSIX installer. You need to install it with VSCode's.

In the command line: `code --install-extension ./path/to/PowerShell-Insiders.vsix`

**Comment by mrfusion9k** [comment]
> If it helps: The Powershell version caused this issue for me.
> 
> Was just having the same issue when I came across this thread; I was running 6.2.3 but my coworkers had no issues and I learned they were on 7.0.3. Installed the latest Powershell and now the plug-in works fine. That pwsh.exe path looks like it may be 6.x.x (Powershell Core) and not the latest 7.x.x which is installed to: C:\Program Files\PowerShell\7\

I thought that might be a similar problem and updated my version as well but it didn't help.

**Comment by mrfusion9k** [comment]
That fixed it.  I can run powershell commands and scripts now without errors.  Thanks for your help.

**Comment by rjmholt** [comment]
Duplicate of #2719
