### ISSUE TITLE
The terminal process terminated with exit code: 64.

### ISSUE THREAD

**Issue by jfevansjr** [PowerShell/vscode-powershell#2886]
Issue Type: <b>Bug</b>

Open Visual Studio Code
Select Terminal\New Terminal
Error: The terminal process "C:\Program Files\PowerShell\7\pwsh.exe c:/Program Files/PowerShell/7/pwsh.exe" terminated with exit code: 64.

Extension version: 2020.6.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (8.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment]
Based on https://github.com/microsoft/vscode/issues/89582, I'm guessing this isn't the PowerShell extension at all but a configured shell for the VSCode terminal.

The error message suggests you're trying to call it with a bad path or options.

This isn't the PowerShell extension, so this repo isn't really the right place for it, but if you share your configuration and ideally a gif of the error occurring, I can try and help you fix it.

**Comment by jfevansjr** [comment]
Thank you for the response.
After reading your comment, I believe you are correct. I'll go back and have another look at it.
