### ISSUE TITLE
Full type name when using ctrl+space

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2898]
**Summary of the new feature**

Right now when you type in `[SomeType]` and try to tab ctrl+space complete it displays list of types which is great, but it's a short type name. I often have to go thru 2-5 different types before I pick the correct one I want. Can you maybe allow a choice between short (if you want to keep old version) and full type? 

![image](https://user-images.githubusercontent.com/15063294/90725384-625bc100-e2c0-11ea-9737-9c245683494d.png)

or 

![image](https://user-images.githubusercontent.com/15063294/90725920-2e34d000-e2c1-11ea-9f79-4be5f773922e.png)

**Comment by TylerLeonhardt** [comment]
I think it seems reasonable that the tooltip for types can include the full type name.

**Comment by TylerLeonhardt** [comment]
https://github.com/PowerShell/PowerShellEditorServices/blob/8cfbf2b4eb636956c31ba6ad258bb3d1b09155eb/src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs#L254

I think if we just add `case CompletionType.Type:` right above this line, this will work.

**Comment by TylerLeonhardt** [comment]
This will be in the next preview thanks to @AspenForester!

**Comment by PrzemyslawKlys** [comment]
Wohoo :-D Thank you @AspenForester
