### ISSUE TITLE
PowerShell's Read-Host command does not work in VS Code 

### ISSUE THREAD

**Issue by kliemohn** [PowerShell/vscode-powershell#29]
If you run a line with Read-Host you get "Read-Host : The method or operation is not implemented."

**Comment by daviwil** [comment]
Hi Kirk!  Read-Host hasn't been implemented yet because we don't have a full console in VS Code.  I'll get that in once the interactive console has been added.

**Comment by daviwil** [comment]
This has been fixed for the next release 0.4.0 which hopefully should be released tomorrow.  When it's out, give it a shot and let me know if it works for your scenarios!
