### ISSUE TITLE
Bring back selectable bitness (x64, x86) for script debugging

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#290]
In the move to the new PowerShell-based hosting model for the language and debug servers we lost the ability to allow the user to easily select which bitness of PowerShell to use (x64 or x86) via the debugger configuration UI.  We need to bring this back somehow.

Currently my thinking is that we can use the debug adapter's new "launch in integrated terminal" setting to launch an independent PowerShell selection at the desired bitness, load up PSES and then run the script purely for that single session.  There could be some performance concerns there but we'll deal with those when they come up.

**Comment by rjmholt** [comment]
Closing as defunct
