### ISSUE TITLE
PowerShell Integrated Console (PSIC) is not created on VSCode startup

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#2900]
### System Details Output
```
### VSCode version: 1.48.0 db40434f562994116e5b21c24015a2e40b2504e6 x64

### VSCode extensions:
amazonwebservices.aws-toolkit-vscode@1.12.0
arcticicestudio.nord-visual-studio-code@0.14.0
dracula-theme.theme-dracula@2.22.1
eamodio.gitlens@10.2.2
EliverLara.andromeda@1.7.0
formulahendry.code-runner@0.11.0
icsharpcode.ilspy-vscode@0.9.0
johnpapa.vscode-peacock@3.8.0
ms-azuretools.vscode-azurefunctions@0.23.0
ms-azuretools.vscode-docker@1.5.0
ms-dotnettools.csharp@1.23.1
ms-python.python@2020.8.101144
ms-vscode-remote.remote-containers@0.134.1
ms-vscode-remote.remote-ssh@0.51.0
ms-vscode-remote.remote-ssh-edit@0.51.0
ms-vscode-remote.remote-wsl@0.44.4
ms-vscode.azure-account@0.9.2
ms-vscode.cpptools@0.29.0
ms-vscode.powershell@2020.6.0
ms-vscode.powershell-preview@2020.7.0
ritwickdey.LiveServer@5.6.1
usernamehw.errorlens@3.2.0
webrender.synthwave-x-fluoromachine@0.0.12


### PSES version: 

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

### Issue Description

I was trying to debug the root cause for Intellisense not working in the VSCode-PowerShell extension, when I came across the following error message in the `vscode-powershell.log` file, in my diagnostic logs folder.

![image](https://user-images.githubusercontent.com/466713/90804037-e3be4e00-e2d6-11ea-8860-2c16ad25481b.png)

```
PSIC is not active terminal. Running in active terminal using 'runSelectedText'
```

I had to create a dummy script, use F5 to run that, and then the PSIC got created. Suddenly, Intellisense for third-party modules / objects started working again.

**Question**: Is there some way to ensure that PSIC is **always** spun up when VSCode is re-launched, when a PowerShell script file is opened up? I wonder if this is partly why people are having so many problems with broken Intellisense.

#### Expected Behaviour

Intellisense works at startup

#### Actual Behaviour

Intellisense for third-party entities (modules, .NET libraries, etc.) doesn't work on VSCode startup. 

### Known Work-around

1. Create a dummy PowerShell script
2. Use `F5` to invoke the dummy script
3. Intellisense starts working in PSIC

### Related Issues 

#2745 

There are only two mentions of the exact log message that I pasted above, but neither one seems to address the PSIC not being created at startup time.

![image](https://user-images.githubusercontent.com/466713/90805061-58de5300-e2d8-11ea-989c-94e111c5742f.png)

**Comment by TylerLeonhardt** [comment]
@pcgeek86 can you please share your vscode settings here?

**Comment by rjmholt** [comment]
I believe this is a question of VSCode activating the PowerShell extension, which is configured by the extension's declared [activation events](https://code.visualstudio.com/api/references/activation-events).

I think these are static for the extension, and not configurable on a user basis. Meaning any configuration for this that the extension ships would apply to all users.

Here are the currently configured activation events:

https://github.com/PowerShell/vscode-powershell/blob/a150199bac794c937cf97b443a5dc51b4a85852c/package.json#L30-L49

That's:

- When a PowerShell file is opened
- When a debug configuration is found
- When any exported commands are used
- When the PowerShell Command Explorer is opened

The remaining events that might help here are:

- `onUri`: seems to be for when custom extension URIs are opened, but could be a hook for us to use here?
- `workspaceContains`: it would be possible to create a simple file to function as a workspace to trigger extension startup
- `onStartupFinished`: this would achieve the desired outcome, but would start the extension for **all** users, and is an experience I don't think we want to force on people

The ideal solution I think would be a VSCode setting to start listed extensions at startup. We would need to ask for that in the VSCode repo.

**Comment by pcgeek86** [comment]
Here's my VSCode settings.

```
{
    "telemetry.enableTelemetry": false,
    "window.zoomLevel": 0,
    "editor.fontFamily": "'UbuntuMono Nerd Font', Consolas, 'Courier New', monospace",
    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "C:\\Users\\TrevorSullivan\\scoop\\apps\\pwsh\\current\\pwsh.exe",
            "versionName": "PowerShellCore"
        }
    ],
    "powershell.powerShellDefaultVersion": "PowerShellCore",
    "terminal.integrated.shell.windows": "C:\\Users\\TrevorSullivan\\scoop\\apps\\pwsh\\current\\pwsh.exe",
    "powershell.integratedConsole.focusConsoleOnExecute": false,
    "powershell.integratedConsole.suppressStartupBanner": true,
    "powershell.integratedConsole.showOnStartup": false,
    "debug.openDebug": "neverOpen",
    "explorer.confirmDelete": false,
    "git.autofetch": true,
    "aws.telemetry": false,
    "explorer.confirmDragAndDrop": false,
    "workbench.colorTheme": "Nord",
    "workbench.startupEditor": "newUntitledFile",
    // "powershell.developer.editorServicesLogLevel": "Diagnostic"
}
```

**Comment by pcgeek86** [comment]
@rjmholt But when I do a `Reload Window` operation, I already have a PowerShell file opened up. The extension isn't being activated despite that. This is a bug, not an enhancement.

**Comment by pcgeek86** [comment]
In case it matters, the PowerShell file that I have opened up is being saved using the VSCode persistence mechanism. It has **not** been saved to disk. Perhaps that is why PSIC isn't being activated?

**Comment by TylerLeonhardt** [comment]
@pcgeek86 do you have any workspace-level settings?

**Comment by rjmholt** [comment]
@pcgeek86 your video doesn't show the crucial part where VSCode and the first script file are opened. Nothing works from that point because there's no PowerShell session (hence no PSIC). But the question is why is there no PSIC initially. We need further information about that point where the first file is opened to find out why the PowerShell extension isn't being triggered.

**Comment by pcgeek86** [comment]
@TylerLeonhardt No workspace-level settings.

@rjmholt The video shows me doing a "reload window" at 1:00.

**Comment by pcgeek86** [comment]
Here's another repro from scratch. You can see me close all workspaces / files, and then reopen VSCode again. There is no PSIC each time that I start up VSCode.

* The PowerShell extension is activated
* There is no PSIC, until I manually execute the workaround in the OP

![pwsh](https://user-images.githubusercontent.com/466713/90821983-f8a7db00-e2f0-11ea-9253-66e3c839f16c.gif)

**Comment by TylerLeonhardt** [comment]
@pcgeek86 get rid of this setting:

```
"powershell.integratedConsole.showOnStartup": false,
```

does that change anything?

**Comment by pcgeek86** [comment]
@TylerLeonhardt Yes, that solves it. I can't remember why I added that in there, a long while back. Probably because there are duplicate PowerShell terminals, that makes VSCode a little more confusing. Is there some way for the extension to piggy back on the `pwsh` instance, instead of spinning up a second one (PSIC)?

**Comment by TylerLeonhardt** [comment]
It's not possible. That terminal is created by VS Code and not the extension.

We've thought about killing that terminal at start up, but if the user has important info there (like they ran a command), then we would cause them harm.

**Comment by rjmholt** [comment]
It seems like a bug that completions don't occur if the PSIC isn't visible though. I wonder what causes that.

> Is there some way for the extension to piggy back on the pwsh instance, instead of spinning up a second one (PSIC)?

To do that, the extension client would need to find that PowerShell process and inject the server into it. In general with other processes, that's not possible, but PowerShell does listen for `Enter-PSHostProcess` connections. Naturally to connect to one of those you need an `Enter-PSHostProcess` client, which means a PowerShell process, so you're back to where you started. Moreover, it would just take your initial `pwsh` instance and turn it into the PSIC; any reason you might have to use `pwsh` over the PSIC would evaporate.
