### ISSUE TITLE
Run PSES's PowerShell session inside of the integrated terminal

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#293]
Recent improvements to VS Code's APIs, specifically the new `createTerminal` API, have made it possible for our extension to programmatically launch PowerShell inside of the integrated terminal UI.  This will allow the user to directly interact with the PowerShell session in which PSES is running for a complete integrated console experience that works even while debugging a script.

**Things to consider**
- Might need to work around the issues with passing terminal arguments on Windows by dynamically generating a .bat file: https://github.com/Microsoft/vscode/issues/8429#issuecomment-235919828
- Is there a setting to never show the debug console since we don't need it anymore?
- PSReadline will need to be disabled initially so that the Runspace will be available for command execution when the user isn't typing commands.  @lzybkr and I have discussed a way to make this work while PSReadline is active but it will require some extra intelligence in PowerShell Editor Services, so I _might_ put that off for a release.

**Comment by hash** [comment]
Just my 3 cents, what was wrong with the Debug Console? 
Now this extension works differently to others that use Debug Console. 
Also something like this returns different results every debug run: 
`$a`
`if ($a -lt 1) {`
`    $a = 1`
`}`
`$a += 1`
`$a`
