### ISSUE TITLE
Terminated due to an error (PowerShell Preview 7.1)

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2933]
Issue Description
=====

I am experiencing a problem with...

![image](https://user-images.githubusercontent.com/15063294/92217606-32074b80-ee98-11ea-80c8-f7b34e8db6bf.png)

Crashes pretty often on code that normally works fine on PowerShell 5.1

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

[1599205059-7015219d-fc87-4e0d-be85-0b4fdefd29921599158419835.zip](https://github.com/PowerShell/vscode-powershell/files/5173543/1599205059-7015219d-fc87-4e0d-be85-0b4fdefd29921599158419835.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19042 |
| VSCode | 1.48.2|
| PowerShell Extension Version | 2020.7.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.0-preview.6|
|PSEdition|Core|
|GitCommitId|7.1.0-preview.6|
|OS|Microsoft Windows 10.0.19042|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.0-preview.6|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|errorlens|usernamehw|3.2.1|
|format-selection-as-html|adrianwilczynski|2.3.0|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.2|
|line-endings|steditor|1.0.3|
|markdown-all-in-one|yzhang|3.3.0|
|material-icon-theme|PKief|4.2.0|
|open-in-browser|techer|2.0.0|
|powershell-preview|ms-vscode|2020.7.0|
|project-manager|alefragnani|11.2.0|
|run-in-powershell|tobysmith568|1.1.0|
|vscode-markdownlint|DavidAnson|0.36.3|
|vscode-toggle-quotes|BriteSnow|0.3.3|
|vscode-wakatime|WakaTime|4.0.7|
|vscode-yaml|redhat|0.10.1|
|xml|DotJoshJohnson|2.5.1|

**Comment by SydneyhSmith** [comment]
Thanks @PrzemyslawKlys we are working on a preview release right now and then will give this another look, once we have those fixes out

**Comment by SydneyhSmith** [comment]
Thanks for your patience, the new preview release is out and we think it solves this issue--when you have a chance would you mind giving it a try and letting us know? Thanks!

**Comment by PrzemyslawKlys** [comment]
Still there:

![image](https://user-images.githubusercontent.com/15063294/93531071-edbb8700-f93e-11ea-9c50-cf5efd3bcda7.png)

[1600376767-94cf5bad-3b86-450a-9064-eaf9146c23271600368026495.zip](https://github.com/PowerShell/vscode-powershell/files/5242000/1600376767-94cf5bad-3b86-450a-9064-eaf9146c23271600368026495.zip)

**Comment by rjmholt** [comment]
Ah now we have a stack trace!

**Comment by SydneyhSmith** [comment]
Likely not related but looks like this stack trace is occurring repeatedly: 
```
System.ArgumentNullException: Pipeline response (OmniSharp.Extensions.LanguageServer.Protocol.Models.Hover) must not be null (Parameter 'request')
   at OmniSharp.Extensions.JsonRpc.Pipelines.ResponseMustNotBeNullProcessor`2.Process(T request, R response, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(TDescriptor descriptor, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext()
```

cc: @david-driscoll vscode might have changed the hover request FYI

**Comment by PrzemyslawKlys** [comment]
[1600964135-61374922-774f-4bfd-8572-71f93b778d7d1600964134180.zip](https://github.com/PowerShell/vscode-powershell/files/5279379/1600964135-61374922-774f-4bfd-8572-71f93b778d7d1600964134180.zip)

Another log. Keep in mind that this crash is not ever X days, but we're talking every X minutes if at all. I'm unable to use PowerShell 7.1 at all in code.

**Comment by david-driscoll** [comment]
This is actually fixed in the latest version of the library, it was a bug I introduced (I got a little happy 😢 )

**Comment by PrzemyslawKlys** [comment]
Thats great. Thank you. Just wanted to make sure it's fixed before next stable release.

**Comment by SydneyhSmith** [comment]
@david-driscoll thanks, just curious what was the issue and how did you manage to fix it?

**Comment by david-driscoll** [comment]
oh I had added a `IPipelineBehavior<,>` that was checking for null returns... because I clearly forgot null returns were valid.  It made sense at the time, but I wasn't paying attention to spec at that point.
Needless to say I was wrong and removed it.

PR where I removed them: https://github.com/OmniSharp/csharp-language-server-protocol/commit/0b9e85dc111a75578bd00103bc3c87852543d76b

**Comment by andschwa** [comment]
When #3294 is finished, this should be resolved as the preview will contain OmniSharp v0.19 with this fix.

**Comment by andschwa** [comment]
@PrzemyslawKlys can you verify that this no longer repros with the latest preview release?

**Comment by PrzemyslawKlys** [comment]
I've not seen this issuee since very long time now. Even before you "fixed it" on Apr14
