### ISSUE TITLE
PowerShell Extension in vscode language client undefined

### ISSUE THREAD

**Issue by hatahetahmad** [PowerShell/vscode-powershell#2934]
Hello, I am facing a problem with PowerShell Extension in vscode

### PowerShell log from vscode

9/5/2020 7:29:05 PM [NORMAL] - Visual Studio Code v1.48.2 64-bit
9/5/2020 7:29:05 PM [NORMAL] - PowerShell Extension v2020.6.0
9/5/2020 7:29:05 PM [NORMAL] - Operating System: Windows 64-bit
9/5/2020 7:30:53 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.

### System Details

Windows 10 Home version 1909 (update 11.07.2020)

### PowerShell Version

Name                                     Value
----                                         -----
PSVersion                               5.1.18362.752
PSEdition                                Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                           10.0.18362.752
CLRVersion                              4.0.30319.42000
WSManStackVersion               3.0
PSRemotingProtocolVersion   2.3
SerializationVersion                 1.1.0.1

### VSCode Version

Version: 1.48.2 (system setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

### Issue Description

<ConsoleFeature>: Unable to instantiate; language client undefined.

#### Expected Behavior

Using F8 to run selection as in PowerShell ISE

#### Actual Behavior

Error appear and no execution done, but if I run the whole script using F5 the script runs correctly

### All my vscode extensions (all latest update)

Dart-Code.dart-code
Dart-Code.flutter
donjayamanne.jupyter
dsznajder.es7-react-js-snippets
felixfbecker.php-intellisense
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-vscode-remote.remote-wsl
ms-vscode.powershell
msjsdiag.vscode-react-native
Nash.awesome-flutter-snippets

**Comment by SydneyhSmith** [comment]
Thanks @hatahetahmad it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by hatahetahmad** [comment]
Thank you Ms. Smith for responding.

I did exactly what the instructions said, but no log file found

I added the following lines to my JSON settings:
> "powershell.developer.editorServicesLogLevel": "Diagnostic"
> "powershell editor services.trace.server":"verbose"

But this log is generated in my console when I run my script

> 9/9/2020 9:57:37 PM [NORMAL] - Visual Studio Code v1.48.2 64-bit
> 9/9/2020 9:57:37 PM [NORMAL] - PowerShell Extension v2020.6.0
> 9/9/2020 9:57:37 PM [NORMAL] - Operating System: Windows 64-bit
> 9/9/2020 9:57:40 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
> 9/9/2020 9:58:39 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
> 9/9/2020 9:58:40 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
> 9/9/2020 9:58:40 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
> 9/9/2020 9:58:40 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
> 9/9/2020 9:58:41 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
> 9/9/2020 10:00:04 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.

Hop this will help
Thank you

**Comment by SydneyhSmith** [comment]
Thanks @hatahetahmad you mentioned that you are able to run the script using F5, are you able to get any other features of the extension working i.e. do you have highlighting, completions etc. in the editor? 
Thanks!

**Comment by hatahetahmad** [comment]
Hi, Yes I am able to use F5 and I can use the code snippet.

I went through the settings and found 'PoewrShell: Start Automatically'
I checked it again, then restart vscode, magically now everything back to normal.
I am able to use Run Selection using F8 without the "language client undefined" error.

Thanks a lot, I hop I didn't cause any extra trouble.
