### ISSUE TITLE
Integrate Plaster into the PowerShell extension

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#294]
The time has come for Plaster to get integrated into the PowerShell extension so that it can provide the "New Project" and "New File" experiences for PowerShell.  At first it may be prudent to use a more hard-coded integration with top-level commands being registered in the package.json file.  These commands will cause requests to be sent to PowerShell Editor Services to have Plaster be invoked so that the user gets prompted for template creation.

Ultimately though, the Plaster integration should happen via the `$psEditor` API but more work needs to be done there before all of the necessary extensibility points are in place.

**Issues to investigate**
- How does the "New Project" experience work when the user hasn't yet loaded a PowerShell project folder (thus causing PSES to be initialized)?  This creates a "chicken-and-egg" problem which needs to be addressed.
  - Is there a way to accomplish this without PSES by launching PowerShell and Plaster independently?
- How will UI prompts work with the switch to using the mainline console host instead of our custom host implementation?  Might need some additional APIs in $psEditor...  Though Plaster will then need to understand two different prompting APIs.

/cc @rkeithhill

**Comment by rkeithhill** [comment]
As for hard-coded commands, yeah we should specify the -Editor VSCode parameter directly. If they're invoking Plaster from VSCode I think it is reasonable to create the appropriate VSCode files (.vscode\tasks.json and settings.json).

RE Chicken and egg problem, if we register the built-in Plaster template's as extension commands, can't those commands force startup of PSES?  We could certainly launch a powershell.exe process and import/run Plaster but then we wouldn't get the "prompting" to occur in the VSCode UI, right?
