### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Yrysbek03** [PowerShell/vscode-powershell#2948]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2020.6.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rjmholt** [comment]
Closing due to lack of information. If you've got more details about the issue you're experiencing, please add them and reopen.
