### ISSUE TITLE
Apply Custom Rules in VSCode with Shift+Alt+F

### ISSUE THREAD

**Issue by VWACRansom** [PowerShell/vscode-powershell#2954]
Our team has created several custom rules that return suggested corrections. We are in the process of going back an reformatting our existing scripts.
The issues are correctly highlighted in the code. When select Quick Fix it correctly applies the suggested correction.

The problem is that our old scripts frequently have a very large number of issues that need corrected. But, when we do Shift-Alt-F, none of our custom rules are applied.

**What needs to be done to get all suggested corrections from custom rules to be applied when pressing Shift+Alt+F in Visual Studio Code?**

**Comment by SydneyhSmith** [comment]
Thanks @VWACRansom this looks like the same request as https://github.com/PowerShell/vscode-powershell/issues/733

**Comment by VWACRansom** [comment]
Thanks! I'll follow that.
