### ISSUE TITLE
Terminal Never Loads

### ISSUE THREAD

**Issue by juvtib** [PowerShell/vscode-powershell#2956]
I was able to reproduce my issue in [Windows Sandbox](https://techcommunity.microsoft.com/t5/windows-kernel-internals/windows-sandbox/ba-p/301849).

# VSCode Setup
[VSCodeUserSetup-x64-1.49.0](https://code.visualstudio.com/Download)

# PowerShell Setup
[PowerShell-7.0.2-win-x64.msix](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.2)
[PowerShell-6.2.6-win-x64.msix](https://github.com/PowerShell/PowerShell/releases/tag/v6.2.6)

# OS Build
``` powershell
Version InstalledOn         OSBuild   Edition
------- -----------         -------   -------
2004    9/6/2020 4:25:31 PM 19041.508 Windows 10 Enterprise
```

*Enterprise* shows in Sandbox. The underlying desktop is Windows 10 Pro. 

# PowerShell Extension
[PowerShell v2020.6.0](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell)

# Issue 

When I have the PowerShell 7.0.2 MSIX and PowerShell 6.2.6 MSIX packages installed, the terminal pane in VSCode never loads. Clicking on *Starting PowerShell* in the corner gives: 

> Running the contributed command PowerShell.ShowSessionMenu failed

Since, I was able to reproduce this in Sandbox on v2004, you can test this yourself. 

In case you are unaware, you can install MSIX from PowerShell 5.1 using: 

``` powershell
Add-AppxPackage -Path .\PowerShell-7.0.2-win-x64.msix
Add-AppxPackage -Path .\PowerShell-6.2.6-win-x64.msix
```

I keep all three PowerShell versions (5, 6; 7) installed side-by-side so that I can test syntax differences. 

I had this working before: possibly the previous version of the extension. 

Regards,

**Comment by rjmholt** [comment]
MSIX discovery code for reference:

https://github.com/PowerShell/vscode-powershell/blob/c1160820917e3d815104323361409bb2fddf916f/src/platform.ts#L262-L290

**Comment by SydneyhSmith** [comment]
Thanks @juvtib it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment). 

It would also be great to know if this repros outside of this Windows sandbox. I am not sure we support installing multiple MSIXs of non-preview PowerShell 6+ (btw 6.2.6 is EOL). 

We discover the MSIX using a logic which only supports finding one stable PowerShell by default.

**Comment by juvtib** [comment]
[GitHub Logs.zip](https://github.com/PowerShell/vscode-powershell/files/5242488/GitHub.Logs.zip)

I am able to produce this issue outside of Sandbox. 

I am using MSIX in my environment. 6.2.7 is [not available](https://github.com/PowerShell/PowerShell/issues/13284#issuecomment-664553496) as MSIX.

**Comment by juvtib** [comment]
For clarity, my issue will be resolved when the terminal tab loads. I don't care which PowerShell version is chosen. As I recall, I could change shells after loading.

**Comment by SydneyhSmith** [comment]
Thanks @juvtib for the additional logs/information--wanted to clarify what I said earlier in that all PowerShell 6 versions are EOL, we recently made some updates to the PowerShell preview extension which has addressed a number of underlying issues, as well as added some additional error messages, would you mind giving it a try and letting us know if you are still hitting this issue?

**Comment by juvtib** [comment]
In that case, I will uninstall 6.
