### ISSUE TITLE
Intellisense element location not at index 0

### ISSUE THREAD

**Issue by itfranck** [PowerShell/vscode-powershell#2957]
Issue Type: <b>Bug</b>

Intellisense does not open at "index 0" 
For instance, typing  `Write-Host -` open up the intellisense at pretty much the end of all parameters.
![image](https://user-images.githubusercontent.com/1980296/93335335-48949780-f7f4-11ea-9516-157d04c366c6.png)

This is annoying because it forces me to scroll up all the time when looking for parameters. 

Here's how I would expect the intellisense to open. 
![image](https://user-images.githubusercontent.com/1980296/93336079-467f0880-f7f5-11ea-9283-d9780d39e4e2.png)

Extension version: 2020.7.0
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3570)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (16.21GB free)|
|Process Argv|--crash-reporter-id fd7dadc3-3996-4873-b435-49640578090f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MartinGC94** [comment]
There's a VS code setting for this. Adding this: `"editor.suggestSelection": "first"` to your settings.json file should fix this issue.

**Comment by itfranck** [comment]
@MartinGC94 Thank you so much. I never considered that was a setting as I never thought this behavior would make sense for any reason at all. Indeed, it fixed the problem. No more snippets and common parameters as the first thing I see each time for each cmdlets. Hurray !
