### ISSUE TITLE
Remote PSSession Incorrect autocomplete path

### ISSUE THREAD

**Issue by neugan** [PowerShell/vscode-powershell#2961]
In the remote pssession (with enter-pssession, windows desktop->windows server), when tab-ing for path (eg. cd or set-location), the autocomplete (also shown in psreadline) iterates through the local desktop path (folders/files), instead of iterating to the remote server paths (folders/files). 

Visual Studio Code Powershell extension (2020.6.0)

**Comment by rjmholt** [comment]
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2661
