### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Dudiov** [PowerShell/vscode-powershell#2981]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2020.6.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rjmholt** [comment]
Closing due to lack of information. Please feel free to add the necessary information outlined in the template and reopen
