### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Dudiov** [PowerShell/vscode-powershell#2984]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2020.6.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rjmholt** [comment]
Hi @Dudiov, please update the issue description with information about what you're seeing. The issue template is a good guide about what information to provide. As is, there are no details about your issue to go on, so we won't be able to help you. With that in mind I'll close this issue, but feel free to reopen it once you've added more details.
