### ISSUE TITLE
Always visible progress notifications when running a subshell from PowerShell terminal

### ISSUE THREAD

**Issue by LinqLover** [PowerShell/vscode-powershell#2985]
### System Details

```powershell
❯ & {"### VSCode version: $(code -v)"; "`n### VSCode extensions:`n$(code --list-extensions --show-versions | Out-String)"; "`n### PSES version: $($pseditor.EditorServicesVersion)"; "`n### PowerShell version:`n$($PSVersionTable | Out-String)"}
### VSCode version: 1.49.1 58bb7b2331731bf72587010e943852e13e6fd3cf x64

### VSCode extensions:
ACharLuk.easy-cpp-projects@2.0.0
ajshort.latex-preview@0.5.1
arthurwang.vsc-prolog@0.8.23
auchenberg.vscode-browser-preview@0.6.7
Darfka.vbscript@1.0.4
dbaeumer.vscode-eslint@2.1.8
donjayamanne.githistory@0.6.11
DotJoshJohnson.xml@2.5.1
eamodio.gitlens@10.2.2
eyhn.vscode-vibrancy@1.0.9
felixrieseberg.vsc-travis-ci-status@1.1.0
formulahendry.code-runner@0.11.0
GitHub.github-vscode-theme@1.1.5
GitHub.vscode-pull-request-github@0.20.0
GrapeCity.gc-excelviewer@3.0.40
ionutvmi.reg@1.0.1
James-Yu.latex-workshop@8.13.2
k--kato.docomment@0.1.18
kevinglasson.cornflakes-linter@0.5.1
mikestead.dotenv@1.0.1
mohsen1.prettify-json@0.0.3
MS-CEINTL.vscode-language-pack-de@1.49.1
ms-dotnettools.csharp@1.23.2
ms-ossdata.vscode-postgresql@0.3.0
ms-python.python@2020.9.112786
ms-vscode-remote.remote-containers@0.140.1
ms-vscode-remote.remote-ssh@0.55.0
ms-vscode-remote.remote-ssh-edit@0.55.0
ms-vscode-remote.remote-wsl@0.44.5
ms-vscode.cpptools@1.0.1
ms-vscode.powershell@2020.6.0
nobuhito.printcode@3.0.0
openhab.openhab@0.7.0
PleasedSkin.smalltalk@0.0.1
redhat.java@0.68.0
SimonSiefke.svg-preview@2.8.3
slevesque.vscode-autohotkey@0.2.2
tht13.html-preview-vscode@0.2.5
torn4dom4n.latex-support@3.2.0
twxs.cmake@0.0.17
VisualStudioExptTeam.vscodeintellicode@1.2.10
vscjava.vscode-java-debug@0.28.0
vscjava.vscode-java-dependency@0.13.0
vscjava.vscode-java-pack@0.10.0
vscjava.vscode-java-test@0.24.2
vscjava.vscode-maven@0.24.2
xaver.clang-format@1.9.0
yzhang.markdown-all-in-one@3.3.0
znck.grammarly@0.12.5


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Steps to reproduce:
1. Open a PowerShell terminal
2. Type "powershell", "wsl", or something else
3. Now your terminal is responsive and waiting for user feedback, so ...

#### Expected Behaviour

... I would expect the PS item in the bottom bar of VS Code to display any "idle" state ...

#### Actual Behaviour

... Instead, it shows all the time a loading icon, which can be quite confusing because I already nest some subshells the whole day, and the whole time, a "busy" state is displayed in the bottom bar.

I think this behavior should be changed. Would it be possible to detect whether the process is waiting for the stdin, and if yes, disable the loading icon?

**Comment by SydneyhSmith** [comment]
Thanks @LinqLover for opening the issue...want to make sure I understand what you are seeing screenshots/GIFs or recordings would be super helpful

**Comment by LinqLover** [comment]
Of course, here is a screencast:

![PowerShell--vscode-powershell#2985](https://user-images.githubusercontent.com/38782922/95171307-0092e000-07b6-11eb-9e04-5505e013f3f1.gif)

Sorry for the German text when starting the PowerShell, it only shows the usual welcome message.

**Comment by SeeminglyScience** [comment]
When in a nested shell, the original PowerShell instance is busy waiting for that process to exit.  That original instance is the only one that the extension has any visibility into, and it's where all language services run.

Part of why it's important to keep the status the way it is currently is that folks may not expect intellisense and such to stop working when entering a nested shell.

**Comment by LinqLover** [comment]
Hm, maybe this issue should be treated as a feature request rather than as a bug report. Is there really no way to detect from the extension whether the running process is blocked and waiting for stdin or whether the opposite is the case?

> folks may not expect intellisense and such to stop working when entering a nested shell.

Could you explain this more in detail? How is IntelliSense related to the PowerShell console?

**Comment by SeeminglyScience** [comment]
> Hm, maybe this issue should be treated as a feature request rather than as a bug report. Is there really no way to detect from the extension whether the running process is blocked and waiting for stdin or whether the opposite is the case?

It can't really be done arbitrarily after process start is the problem.  The PSIC launched with a custom host that sets up the hooks for the extension.

> Could you explain this more in detail? How is IntelliSense related to the PowerShell console?

The PowerShell extension shares state with that console, similar to how the ISE works.  If you set a variable interactively in the shell, it'll show up in intellisense.  Import a module interactively, it shows up.  Dot source a script, see it's state.  That kinda thing.

VSCode (and all other editors afaik) get their intellisense directly from the PowerShell engine's tab completion API.  In order to do that and share state with the interactive console, the responsiveness of editor features is directly tied to whether the shared instance is busy.

**Comment by LinqLover** [comment]
Thanks for the explanation. Why isn't a second instance of the ISE used for the terminal? Then we could turn off the busy bar for the terminal instance only.

**Comment by corbob** [comment]
> Thanks for the explanation. Why isn't a second instance of the ISE used for the terminal? Then we could turn off the busy bar for the terminal instance only.

That would break the sharing of the session state. If you're looking for just another terminal, you can add one from the drop down, you can even specify which shell to launch in vscode configuration.

**Comment by LinqLover** [comment]
That's probably the best solution, thanks for the help!

**Comment by rjmholt** [comment]
@SeeminglyScience and @corbob are on the money.

Basically if you start a command, it becomes a subprocess. That command might be `powershell.exe` running interactively or it might be `chkdsk.exe` performing a long-running disk check non-interactively.

From the point of view of the parent process (the integrated console), there's no difference. Both subprocesses have access to stdio and may or may not use it. It doesn't get signaled to say "this subprocess is interactive".

And in all cases, the subprocess synchronously blocks PowerShell's pipeline thread, meaning the integrated console is busy. We've talked a few times about decoupling them, but then you lose all the ability to supplement the completions in the editor from the console, like with `Register-ArgumentCompleter` etc.
