### ISSUE TITLE
Please Update the Preview Extension in Azure Data Studio - Insiders Marketplace

### ISSUE THREAD

**Issue by SQLvariant** [PowerShell/vscode-powershell#2993]
### System Details

System Details Output
```
Version: 1.24.0-insider (user setup)
Commit: 23e2a5dd122f877822f34ccd4c90cded6a018d95
Date: 2020-10-07T05:31:13.894Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

### Issue Description

In Azure Data Studio - Insiders edition, the version of the PowerShell Preview Extension in that Marketplace is not in sync with the version available in the VS Code Insiders Marketplace.

#### Expected Behaviour

The version PowerShell Preview Extension in the Marketplace for Azure Data Studio - Insiders edition should be the same version available in VS Code - Insiders edition's Marketplace.

#### Actual Behaviour

Not only is the version of the version of the PowerShell Preview Extension in the Marketplace for Azure Data Studio - Insiders edition [v2020.4.0] far behind the version available in VS Code - Insiders edition's Marketplace [v2020.9.0]; it is even behind version available in Azure Data Studio (non-Insiders) edition's Marketplace [v2020.6.0].
![image](https://user-images.githubusercontent.com/18595280/95469633-de33ca80-094d-11eb-81cd-17b59ee5b406.png)

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by SydneyhSmith** [comment]
Thanks for the reminder @SQLvariant 😄

**Comment by SQLvariant** [comment]
Adding @rjmholt to see if we can get some traction on this one.

**Comment by SydneyhSmith** [comment]
@SQLvariant we are planning to do a release in the next few weeks so we will be sure to update it then...thanks for your patience 😄

**Comment by SydneyhSmith** [comment]
For clarity, we are are responsible for updating the versioning that gets picked up by ADS, but ADS ships its marketplace as a part of it, rather than a separate entity that can be independently updated-- in other words we update the versioning at https://github.com/microsoft/azuredatastudio/tree/main/extensions but that only gets updated in the client when new versions of ADS come out

**Comment by andschwa** [comment]
v2021.2.2 is now set to be in the next release of ADS!
