### ISSUE TITLE
Allow to resolve multiple similar problems.

### ISSUE THREAD

**Issue by Alex-0293** [PowerShell/vscode-powershell#2996]
**Summary of the new feature**
Allow to resolve more then one similar problem on the problem pane.
![изображение](https://user-images.githubusercontent.com/5895448/95575115-ac8a3480-0a1d-11eb-9d84-a1bd691047e6.png)
powershell extension doesnt have group action.
![изображение](https://user-images.githubusercontent.com/5895448/95575178-c592e580-0a1d-11eb-9713-28d838c8ce54.png)

**Comment by rjmholt** [comment]
This sounds like a feature that VSCode would need to provide. I'll leave it here for now so we can discuss at next issue triage

**Comment by SydneyhSmith** [comment]
You may also want to add this setting to resolve this specific issue:
    `"files.trimTrailingWhitespace": true,`
