### ISSUE TITLE
Remote language and debugging experience from non-Windows OS

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#30]
# Scenario

I'm using a Macbook Pro, running Mac OS X El Capitan 10.11.1. I'm authoring PowerShell scripts in Visual Studio Code, but for obvious reasons, I don't have Intellisense capabilities, or line-by-line debugging support.
# Proposed Solutions

A couple of potential options for solving this scenario are:
1. Add support for PowerShell to execute natively on non-Windows operating systems (Mac OS X)
2. Support remote debugging through PowerShell Remoting (PSSession) / Windows Remote Management (WinRM), via the [Visual Studio Code Debug Adapter](https://code.visualstudio.com/docs/extensionAPI/api-debugging).

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

/cc @daviwil

**Comment by BrendanThompson** [comment]
This would be excellent! Then can utilise windows VM in the background for debugging. Would also be fantastic if it had intellisense as well! If only Microsoft would contribute to the PaSH project and get PowerShell on more than just Windows. For writing PoSH scripts only though, it could never replace ZSH :)

**Comment by daviwil** [comment]
Thanks Trevor!  Many people have asked for this feature so I'll start investigating options in the next month or so.

**Comment by ducke** [comment]
:+1:

**Comment by jariangibson** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwj1tevyvtfJAhVEJiYKHUjNCDMQjRwIBw&url=http%3A%2F%2Fknights-and-dragons.wikia.com%2Fwiki%2FFile%3ADo-it.png&psig=AFQjCNET9QY14dmbn_qUb42AovHwlkVnGg&ust=1450049879584936

**Comment by daviwil** [comment]
I've expanded the title of this to include the language service aspect as well since OS X is also missing the full IntelliSense, code navigation, script analysis, etc that it provides.

**Comment by tylerl0706** [comment]
I'm going to close this since this dates back before PS Core was a thing. If you have any issues, please let me know/open a new issue 😄
