### ISSUE TITLE
Stable version of the extension still marked as preview. Intended?

### ISSUE THREAD

**Issue by J0F3** [PowerShell/vscode-powershell#3006]
### Issue Description

The stable version of the extension has still "(Preview)" in the description and the "Preview" Tag set?
Is this really intended? I think it is a bit misleading.

![image](https://user-images.githubusercontent.com/12759579/95840808-ea9c9680-0d44-11eb-80db-4ed49432a11f.png)

#### Expected Behaviour

The stable release of the extension should not show anywhere "preview" as it may be confusing.

Thanks!

**Comment by rjmholt** [comment]
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2774

**Comment by J0F3** [comment]
Oh, sorry for the duplicate! I had searched for existing issues but obviously not enough. 😳 So I will close mine now again.
