### ISSUE TITLE
Option to ignore snippets from the extension, but keep user's `powershell.json` snippets 

### ISSUE THREAD

**Issue by ninmonkey** [PowerShell/vscode-powershell#3007]
**Summary of the new feature**

allowing alowwing 

An option to disable the extension's snippets `powershell.json`, without also disabling user's `powershell.json`.
Without it, the user's menu is filled up. [It adds ~70 snippets](https://github.com/PowerShell/vscode-powershell/blob/master/snippets/PowerShell.json)

I first tried this setting:

> "editor.snippetSuggestions": "none"

It affects autocomplete and `ctrl+space` , but [not `ctrl+alt+j` hotkey in the manifest](https://github.com/PowerShell/vscode-powershell/blob/ee5521fd8dd8bd1a973362facea2aa5d658d90b3/package.json#L162)

**Solution**

1] A setting `"powershell.loadSnippets": "false"`

2] If there is a way to override an extension's `contributes.snippets` setting? 

Other projects said they had to implement a 'opt-out' setting (It wasn't automatic)

**The Current Solution**

Delete `"$Env:UserProfile\.vscode\extensions\ms-vscode.powershell[-preview]-<version>-\snippets\PowerShell.json"`

**Comment by TylerLeonhardt** [comment]
@ninmonkey I don't think the PowerShell extension should be responsible for this since it's a generic VS Code problem. Maybe you can use this?

https://marketplace.visualstudio.com/items?itemName=svipas.control-snippets

I've heard great things.
