### ISSUE TITLE
Invalid Problem detection with DSC template

### ISSUE THREAD

**Issue by robharman** [PowerShell/vscode-powershell#3009]
Issue Type: <b>Bug</b>

Within a node configuration block in a DSC PowerShell template the following code triggers a Problem with the Target property.  According to the PowerShell [documentation]( https://docs.microsoft.com/en-us/powershell/scripting/dsc/reference/resources/windows/environmentresource?view=powershell-7), the property set is valid.

        Environment HomeStorageRoot {
            Ensure              =   'Present'
            Name                =   'HomeStorageRoot'
            Value               =   "$HomeStorageRoot"
            Target              =   'Machine'
        }

The member 'Target' is not valid. Valid members are
'DependsOn', 'Ensure', 'Name', 'Path', 'PsDscRunAsCredential', 'Value'.

Extension version: 2020.6.0
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (18.83GB free)|
|Process Argv|--crash-reporter-id f3869b95-0ef3-4f27-8ad7-c55a9bfe8542|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment]
> The member 'Target' is not valid. Valid members are
> 'DependsOn', 'Ensure', 'Name', 'Path', 'PsDscRunAsCredential', 'Value'.

Where are you seeing this? Can you provide a screenshot?

Does this work if you execute it from VSCode? What about from the powershell.exe console?

**Comment by robharman** [comment]
It seems like this is a issue with the documentation, not with the VS Code PowerShell extension. Compiling my configurations completed, but applying them fails with the same error. Closing this issue now, sorry for the hassle!

**Comment by rjmholt** [comment]
> It seems like this is a issue with the documentation

Ah, I wondered! Would you be able to open an issue on the doc page you got the information from -- hopefully we can correct it so that everything agrees

**Comment by robharman** [comment]
Just opened an issue with documentation. Hopefully, this is an issue with the documentation and not yet **another** issue with the user reading the documentation. :P

**Comment by rjmholt** [comment]
> not yet another issue with the user reading the documentation

Unclear documentation can still be a bug in the documentation 😄
