### ISSUE TITLE
Characters like "ä/ü/ö" don't get saved right

### ISSUE THREAD

**Issue by modzilla99** [PowerShell/vscode-powershell#3010]
### System Details

Windows 10 Pro 2004
VSCode 1.50.0
ms-vscode.powershell@2020.6.0

System Details Output
```
### VSCode version: 1.50.0 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3 x64

### VSCode extensions:
foxundermoon.shell-format@7.0.1
ms-azuretools.vscode-docker@1.6.0
ms-dotnettools.vscode-dotnet-runtime@0.1.2
ms-vscode-remote.remote-ssh@0.55.0
ms-vscode-remote.remote-ssh-edit@0.55.0
ms-vscode-remote.remote-wsl@0.50.0
ms-vscode.powershell@2020.6.0
msazurermtools.azurerm-vscode-tools@0.13.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.19041.546
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.546
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When writing characters like ä,ü,ö and saving the file, those characters will become corrupted. If you then open the file in PS IDE you can see it, even though they're still displayed fine in vscode (even after reopening). When replacing them in PS IDE they'll be replaced with � in vscode. Butt executing the script shows that they are set correctly now. I attached 2 powershell documents to show it off, one's been edited with powershell IDE and one with vscode.

#### Expected Behaviour

Saving the file won't result in ä,ö,ü getting replaced by different characters

#### Actual Behaviour

'ä' for eg. will be replaced by 'Ã¤' and 'Ä' with 'Ã„'. The latter is obviously particularly bad as it hinders your script from running.

### Attached Logs

[Powershell-Logs.zip](https://github.com/PowerShell/vscode-powershell/files/5376213/Powershell-Logs.zip)
[Saved-Scripts.zip](https://github.com/PowerShell/vscode-powershell/files/5376221/Saved-Scripts.zip)

**Comment by rjmholt** [comment]
Please take a look at [this doc that we wrote](https://docs.microsoft.com/powershell/scripting/dev-cross-plat/vscode/understanding-file-encoding) about configuring your editor encoding correctly

**Comment by modzilla99** [comment]
Thank you! It's now solved with windows-1252 encoding!
It would be great to make that more obvious though! I already thought that it might be the cause but since UTF-8 was already ticked...

**Comment by rjmholt** [comment]
> It would be great to make that more obvious though!

Yeah, it would be nice to help users preempt encoding issues, it's just hard to (1) detect that they are issues and (2) hard to notify the user in an appropriate way given that the extension just sits between VSCode (which controls the file encoding) and PowerShell (which controls the parse encoding). Some followup questions:
- What in particular would you like made more obvious?
- Where would you expect such a communication about encoding in the VSCode/PowerShell experience?

**Comment by modzilla99** [comment]
Thank you for caring! Hm that's a good question. I think I would like to get a small notification that contains a link to the docs when you start to type special characters and haven't changed anything in terms of encoding. Or maybe do it like you do with echo and cd. If that's in your code you'll get asked to change it to Write-Host or Set-Location respectively. Hope this helps a little

**Comment by rjmholt** [comment]
Ah interesting. Now that I think about it, I suspect the best way for us to surface this is with a PSScriptAnalyzer rule actually. See https://github.com/PowerShell/PSScriptAnalyzer/issues/1436.
