### ISSUE TITLE
Integrated Console Hangs On Load

### ISSUE THREAD

**Issue by jkdba** [PowerShell/vscode-powershell#3011]
Issue Description
=====

I recently upgraded from v2020.4.3 to v2020.6.0 and the console no longer loads at launch it just hangs.

![image](https://user-images.githubusercontent.com/3289404/95989354-28a6c280-0df8-11eb-9f9e-b5d1694a3846.png)

## Steps taken
1. If I revert the back to v2020.4.3 the issue goes away.
2. I have tried completely removing extension and reinstalling, 
3. I have tried disabling this version and installing the preview version v2020.9.0, results in the same hanging behaviour but it does produce this exception.

```
=====> PowerShell Preview Integrated Console v2020.9.0 <=====

Exception encountered starting EditorServices. Exception logged in D:\a\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 248 in EndProcessing:
System.TypeLoadException: Method 'DisposeAsync' in type 'Microsoft.Extensions.DependencyInjection.ServiceProvider' from assembly 'Microsoft.Extensions.DependencyInjection, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer..ctor(LanguageServerOptions options)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.<From>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.<StartAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesRunner.<CreateEditorServicesAndRunUntilShutdown>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing()
```

Attached Logs
=====

[1602679083-a6a6c747-6583-4c6f-8f66-0550151ba63b1602678259376.zip](https://github.com/PowerShell/vscode-powershell/files/5378229/1602679083-a6a6c747-6583-4c6f-8f66-0550151ba63b1602678259376.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.49.3|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.1|
|BuildVersion|10.0.19041.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|AWK|luggage66|0.0.2|
|bash-beautify|shakram02|0.1.1|
|bash-ide-vscode|mads-hartmann|1.11.0|
|Bookmarks|alefragnani|11.3.1|
|code-settings-sync|Shan|3.4.3|
|cpptools|ms-vscode|1.0.1|
|csharp|ms-dotnettools|1.23.3|
|empty-indent|DmitryDorofeev|0.2.0|
|gc-excelviewer|GrapeCity|3.0.40|
|githistory|donjayamanne|0.6.12|
|gitlens|eamodio|10.2.2|
|html-css-class-completion|Zignd|1.19.0|
|indentation-level-movement|kaiwood|1.2.1|
|indenticator|SirTori|0.7.0|
|mssql|ms-mssql|1.9.0|
|path-intellisense|christian-kohler|2.3.0|
|pgsql|doublefint|0.1.3|
|powershell|ms-vscode|2020.6.0|
|project-snippets|rebornix|0.5.0|
|remote-wsl|ms-vscode-remote|0.44.5|
|sqlops-debug|ms-mssql|1.3.0|
|team|ms-vsts|1.161.1|
|theme-atom-one-dark|andischerer|0.0.1|
|Theme-Github|gerane|0.0.6|
|vscode-awk-hint|hangxingliu|0.0.2|
|vscode-dimmer|hoovercj|2.1.0|
|vscode-input-sequence|tomoki1207|0.2.0|
|vscode-markdownlint|DavidAnson|0.37.1|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|vscode-settings-cycler|hoovercj|1.0.1|
|vscode-simple-icons|LaurentTreguier|1.13.5|
|vscode-todo-highlight|wayou|1.0.4|
|vsliveshare|ms-vsliveshare|1.0.2902|
|xml|DotJoshJohnson|2.5.1|

**Comment by rjmholt** [comment]
That exception is helpful, thanks. In 2020.6.0, it will be producing the same exception but not surfacing it.

It looks like this is an issue with assembly linking, due to how we manage our dependencies.

Can you let us know what your .NET version is, with the output of this:

```powershell
Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\'
```

**Comment by jkdba** [comment]
Great, here is the output.

|Name|Value|
|---|---|
|CBS|1|
|Install|1|
|InstallPath|C:\Windows\Microsoft.NET\Framework64\v4.0.30319\|
|Release|528372|
|Servicing|0|
|TargetVersion|4.0.0|
|Version|4.8.04084|
|PSPath|Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\|
|PSParentPath|Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4|
|PSChildName|Full|
|PSDrive|HKLM|
|PSProvider|Microsoft.PowerShell.Core\Registry|

**Comment by Garfius** [comment]
Happens same here too.

When working on local, seems to freeze, but a keyboard enter brings PowerShell Terminal alive. So, not important working on local.

Environment:
Client: Windows 10 1809 17763.1518 

```
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
```

Server: CentOS Linux release 7.7.1908 (Core)

```
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
`


Already tried removing /root/.vscode-server

Freezes at:
`=====> PowerShell Integrated Console v2020.6.0 <=====`

**Comment by TylerLeonhardt** [comment]
likely unrelated but @Garfius PowerShell Core 6 is EOL. You'll want to upgrade to PowerShell 7. PS7 does have a better experience in the extension so it's worth switching too... (assuming it can start 😅 )

**Comment by rjmholt** [comment]
@Garfius please try out the current PowerShell Preview extension and see if you get an error stack trace

**Comment by Garfius** [comment]
> likely unrelated but @Garfius PowerShell Core 6 is EOL. You'll want to upgrade to PowerShell 7. PS7 does have a better experience in the extension so it's worth switching too... (assuming it can start 😅 )

YES!

Solution:
yum update powershell

Thank you very much.

My apologies for posting before trying to update.
