### ISSUE TITLE
Trojan:PowerShell/Mountsi.A!ml <- Installed via VSCode Update on 10/2/2020

### ISSUE THREAD

**Issue by mcc85sx** [PowerShell/vscode-powershell#3017]
Windows Defender picked up an anomaly that was deposited to my machine, via a Visual Studio Code update for PowerShell.

10/2/2020 - pwsh.exe Trojan:PowerShell/Mountsi.A!ml

I didn't take a screenshot unfortunately. I was having issues being able to copy/paste and select and press F8 to run. I was able to fix the problem by completely reinstalling the software, but felt I should advise your team.

**Comment by SydneyhSmith** [comment]
Thanks for letting us know @mcc85sx if you have more details please follow [our security bug guidance](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#note-on-security)....when you mentioned reinstalling the software, are you referring to Visual Studio code?

**Comment by potatoqualitee** [comment]
Please reopen, this is a critical problem for the PS community. @mcc85sx can you please provide additional information?
