### ISSUE TITLE
Parameter Aliases do not appear in Auto Completion

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/vscode-powershell#3018]
### VSCode extensions:
eamodio.gitlens@10.2.2
Equinusocio.vsc-community-material-theme@1.4.2
Equinusocio.vsc-material-theme@33.0.0
equinusocio.vsc-material-theme-icons@1.2.0
Hyzeta.vscode-theme-github-light@7.14.2
ironmansoftware.powershell-universal@1.5.1
ironmansoftware.powershellprotools@5.15.4
k--kato.docomment@0.1.18
ms-azuretools.vscode-docker@1.7.0
ms-dotnettools.csharp@1.23.4
ms-vscode-remote.remote-wsl@0.50.1
ms-vscode.powershell@2020.6.0
octref.vetur@0.28.0
PKief.material-icon-theme@4.3.0
streetsidesoftware.code-spell-checker@1.9.2

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Issue Description

```
function Test {
     param([Alias('AL')$PR)
}
```

![image](https://user-images.githubusercontent.com/1256531/96619231-25fa1080-12c3-11eb-8b44-1b422bcbb613.png)

Tab completion works for the Alias in the Integrated Terminal. 

#### Expected Behaviour

I should see the `-AL` parameter as well. 

#### Actual Behaviour

Only `-PR` is shown. 

### Attached Logs

```
20/10/2020 08:13:01 [NORMAL] - Visual Studio Code v1.50.1 64-bit
20/10/2020 08:13:01 [NORMAL] - PowerShell Extension v2020.6.0
20/10/2020 08:13:01 [NORMAL] - Operating System: Windows 64-bit
20/10/2020 08:13:02 [NORMAL] - Language server starting --
20/10/2020 08:13:02 [NORMAL] -     PowerShell executable: C:\Program Files\PowerShell\7\pwsh.exe
20/10/2020 08:13:02 [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\adamr\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\adamr\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\adamr\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1603203181-064af6ab-8ef2-4b13-8528-3c659892e98d1603203178417\EditorServices.log' -SessionDetailsPath 'c:\Users\adamr\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-1800-778370' -FeatureFlags @() 
20/10/2020 08:13:02 [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\adamr\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\adamr\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\adamr\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1603203181-064af6ab-8ef2-4b13-8528-3c659892e98d1603203178417\EditorServices.log' -SessionDetailsPath 'c:\Users\adamr\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-1800-778370' -FeatureFlags @() 
20/10/2020 08:13:02 [NORMAL] - pwsh.exe started.
20/10/2020 08:13:02 [NORMAL] - Waiting for session file
20/10/2020 08:13:06 [NORMAL] - Session file found
20/10/2020 08:13:07 [NORMAL] - Registering terminal close callback
20/10/2020 08:13:07 [NORMAL] - Registering terminal PID log callback
20/10/2020 08:13:07 [NORMAL] - pwsh.exe PID: 2092
20/10/2020 08:13:07 [NORMAL] - Language server started.
20/10/2020 08:13:07 [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_jpd5krtg.ibb","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_4g43naso.mrr"}
20/10/2020 08:13:07 [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_jpd5krtg.ibb...
20/10/2020 08:13:07 [NORMAL] - Language service connected.
```

**Comment by TylerLeonhardt** [comment]
This is weird PowerShell behavior, unfortunately. A great example of this is `-EA`. It doesn't show up in _Tab Completion_ results:

![image](https://user-images.githubusercontent.com/2644648/96631735-8ee58680-12cb-11eb-99ab-57347be9ed30.png)

 _until_ you include the first letter of the alias:

![image](https://user-images.githubusercontent.com/2644648/96631769-9c027580-12cb-11eb-83f1-ec40ae9e2f0b.png)

The question is... would you want to see `-EA` when you do `Get-Process -` when there are so many other parameters? Maybe. Even so, we should probably have this discussion in the main PowerShell/PowerShell repo.

**Comment by adamdriscoll** [comment]
Ahhh ok. Didn't realize that. I'll close this since it's not related to the extension. Thanks for the heads up.

**Comment by TylerLeonhardt** [comment]
I don't see an issue in PS/PS if you wanted to open it there!
