### ISSUE TITLE
Variable hover/data tips not working in the debugger

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#302]
**Please fill in these details so that we can help you!**
### System Details
- Operating system name and version: Windows 10 1607
- VS Code version: 1.5.3
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.187
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.187
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### Issue Description

I can no longer hover over a variable in the debugger and get a hover tip.  This used to work not too long ago.  
### Attached Logs

In looking at the log, we return false for `supportsEvaluateForHovers`.  Is that right?  We do support hover though, right?  OTOH I don't think our eval is side-effect free.  Maybe that's why this is false?

**Comment by daviwil** [comment]
Hmmm, I think that parameter may cause it to be evaluated in the REPL but I'm not sure...  Worth investigating though.  I wonder if the debugger client has changed the way they request these?  We're a little out of date with the latest protocol I think.

**Comment by rkeithhill** [comment]
Yeah, I've been "loosely" following debug protocol updates but I really need to sink my teeth into the updated protocol and see where we should update our implementation.

**Comment by rkeithhill** [comment]
And indeed it was the change "expensive" on the Autos variable container that broke this.  What's more, if I back out the change, the `Auto` variables node still stays open.  If you remember, that was the original bug we were trying to fix - the Auto variable container kept closing as you'd step through code.  Sigh.  Guess I'll poke around the VSCode debug issues to see what changed.

**Comment by daviwil** [comment]
This is fixed in VS Code 1.6 now, right?

**Comment by rkeithhill** [comment]
Yup.

**Comment by rkeithhill** [comment]
If VSCode thinks there are no duplicate variable names in non-expensive scopes it will display debug hover tips.  I believe 1.7 and higher will remove the whole "don't display debug hover on a duplicate variable name check".  What I do notice in 1.6 is that Autos isn't starting open during a debug session.  I believe it used to do that.  Sigh...  Nothing like chasing a moving target.  :-)

At this point, should we target 0.8.0 to coincide with the 1.7 VSCode release?  If so, I can try to make sure this is all working correctly on the insider's build.

**Comment by rkeithhill** [comment]
This seems to be working correctly in VSCode Insider builds.

**Comment by daviwil** [comment]
Yep, working correctly for me too.  Closing this.
