### ISSUE TITLE
v2020.7.0 release?

### ISSUE THREAD

**Issue by jwfx** [PowerShell/vscode-powershell#3021]
Was v2020.7.0 ever really released to the marketplace?

There is a tag for that version on github, but I cannot seem to find that version in the marketplace.

**Comment by SydneyhSmith** [comment]
Thanks @jwfx we have not done a 2020.07 release to the marketplace--sorry for any confusion

**Comment by jwfx** [comment]
What is the general timeline for a new stable release, be it that version or even a later one?

**Comment by jwfx** [comment]
@msftbot 

Rude..
