### ISSUE TITLE
How to sync PSScriptAnalyzerSettings.psd1 file using VSCode Setting Sync feature?

### ISSUE THREAD

**Issue by ALIENQuake** [PowerShell/vscode-powershell#3022]
Hi,

How to sync PSScriptAnalyzerSettings.psd1 file using VSCode Setting Sync feature?

Can 'vscode-powershell' extension contribute a custom file to some kind of 'sync file list'?

**Comment by SydneyhSmith** [comment]
Thanks @ALIENQuake that is a great question/request... however this (connecting a file to the setting sync) does not seem to be currently supported by VSCode...you may want to open an issue in the VSCode repository for this request
