### ISSUE TITLE
Encoding/Emoji of PowerShell Integrated Terminal?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3029]
Issue Description
=====

I am experiencing a problem with... encoding/emoji in the terminal. 

![image](https://user-images.githubusercontent.com/15063294/97092077-1e2ec900-1641-11eb-96e0-38fed3c7cc71.png)

I've found: 
- https://github.com/microsoft/vscode/issues/19837
- https://github.com/Microsoft/vscode/issues/45520

And I don't have much luck with: `"terminal.integrated.shellArgs.windows": ["-NoExit", "/c", "chcp.com 65001"]`

I see Tyriar was asking why this can't be included as part of PowerShell Extension and dawii says he will include it. But was it? 

It seems special char is shown so maybe encoding is correct and just emoji are missing? 

![image](https://user-images.githubusercontent.com/15063294/97092135-b0cf6800-1641-11eb-8bd1-6fd779df8050.png)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19042 |
| VSCode | 1.50.1|
| PowerShell Extension Version | 2020.9.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.546|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.546|
|BuildVersion|10.0.19041.546|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|errorlens|usernamehw|3.2.3|
|github-linker|gimenete|0.2.3|
|line-endings|steditor|1.0.3|
|markdown-all-in-one|yzhang|3.3.0|
|material-icon-theme|PKief|4.3.0|
|open-in-browser|techer|2.0.0|
|path-intellisense|christian-kohler|2.3.0|
|pin-up|saekiraku|1.4.0|
|powershell-preview|ms-vscode|2020.9.0|
|project-manager|alefragnani|11.3.1|
|rainbow-brackets|2gua|0.0.6|
|run-in-powershell|tobysmith568|1.1.0|
|swdc-vscode|softwaredotcom|2.3.14|
|vscode-css-formatter|aeschli|1.0.1|
|vscode-markdownlint|DavidAnson|0.37.1|
|vscode-toggle-quotes|BriteSnow|0.3.3|
|vscode-wakatime|WakaTime|4.0.9|
|vscode-yaml|redhat|0.11.1|
|xml|DotJoshJohnson|2.5.1|

**Comment by SydneyhSmith** [comment]
Thanks @PrzemyslawKlys what encoding does the file have? It would also be great to have a simpler re-pro with Write-Host ...unfortunately that setting doesnt apply to the integrated console. Thanks!

**Comment by PrzemyslawKlys** [comment]
UTF8-BOM. 

```powershell
Write-Host "😊😂👌😘 testing "
```

It may be just the way I type emoji which is using Windows + dot. It works correctly for displaying in HTML / Outlook and other places where PowerShell sends it, however it fails to display in console. 

But it seems it's not related to VSCode. 

![image](https://user-images.githubusercontent.com/15063294/97359924-cf319f80-189d-11eb-9cb7-5aa0e09707b9.png)

Yesterday during debugging on discord we found out that only sparks seems to work which seem to have different unicode code.

![image](https://user-images.githubusercontent.com/15063294/97360010-e83a5080-189d-11eb-88fb-1878ae4412e8.png)

It seems to be more general for shell in Windows. Up to you how to classify it - close/move?

**Comment by rjmholt** [comment]
@PrzemyslawKlys can you report on the following values:

- `$OutputEncoding`
- `[Console]::OutputEncoding`
- `[Console]::InputEncoding`
- `chcp`

In my (WinPS) terminal, I have no issues displaying the output character, but when it's input into the REPL I get a `?` character:

![image](https://user-images.githubusercontent.com/7009879/97640904-feabed80-19fe-11eb-8fc7-124a9902f52c.png)

That's fixed with `[Console]::OutputEncoding = [Text.Encoding]::Utf8`:

![image](https://user-images.githubusercontent.com/7009879/97640966-18e5cb80-19ff-11eb-9002-6dd15ab54976.png)

**Comment by PrzemyslawKlys** [comment]
In VSCode

```
PS C:\Support\GitHub\PSTeams> $OutputEncoding



BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 65001



PS C:\Support\GitHub\PSTeams> [Console]::OutputEncoding



BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : False
CodePage          : 65001



PS C:\Support\GitHub\PSTeams> [Console]::InputEncoding



BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : False
CodePage          : 65001



PS C:\Support\GitHub\PSTeams> chcp

Active code page: 65001
```

In terminal:

```
PS C:\Users\przemyslaw.klys> $OutputEncoding


IsSingleByte      : True
BodyName          : us-ascii
EncodingName      : US-ASCII
HeaderName        : us-ascii
WebName           : us-ascii
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 20127



PS C:\Users\przemyslaw.klys> [Console]::OutputEncoding


IsSingleByte      : True
BodyName          : IBM437
EncodingName      : OEM United States
HeaderName        : IBM437
WebName           : IBM437
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : False
IsMailNewsSave    : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : False
CodePage          : 437



PS C:\Users\przemyslaw.klys> [Console]::InputEncoding


IsSingleByte      : True
BodyName          : IBM437
EncodingName      : OEM United States
HeaderName        : IBM437
WebName           : IBM437
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : False
IsMailNewsSave    : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 437

```

I have that in my vscode profile:
```powershell
$OutputEncoding = [System.Text.Encoding]::UTF8
[console]::InputEncoding = [System.Text.Encoding]::UTF8
[console]::OutputEncoding = [System.Text.Encoding]::UTF8
```
When I do the same in terminal

![image](https://user-images.githubusercontent.com/15063294/97804677-bdf7e280-1c51-11eb-922e-909f3563c750.png)

![image](https://user-images.githubusercontent.com/15063294/97804703-e253bf00-1c51-11eb-8ef8-cab2a8d900bc.png)

![image](https://user-images.githubusercontent.com/15063294/97804760-2f379580-1c52-11eb-8d9c-c6b8939ec5c9.png)

**Comment by SeeminglyScience** [comment]
PSReadLine doesn't handle surrogate pairs from the emoji keyboard correctly.  The issue to track is PowerShell/PSReadLine#1329

**Comment by PrzemyslawKlys** [comment]
The question is whether it's PSReadLine issue for both VSCode and Terminal? Once it's fixed there it will work in both places?

**Comment by SeeminglyScience** [comment]
Try copy and pasting an emoji that doesn't work instead.  If it works in both, then yeah it should be fixed in both places.

Make sure you use PSRL's paste though, don't right click.

**Comment by PrzemyslawKlys** [comment]
Maybe basic question - how to trigger PSRL paste? :)

**Comment by SeeminglyScience** [comment]
<kbd>Ctrl</kbd> + <kbd>V</kbd>

**Comment by PrzemyslawKlys** [comment]
On copy from VSCode Code window, pasted using CTRL+V in Terminal PowerShell without PSReadline

![image](https://user-images.githubusercontent.com/15063294/97806576-8cd0df80-1c5c-11eb-8478-947b21643996.png)

With PSReadline PS7

![image](https://user-images.githubusercontent.com/15063294/97806600-bc7fe780-1c5c-11eb-93f4-7c2687d4786e.png)

With PSReadLine PS5

![image](https://user-images.githubusercontent.com/15063294/97806706-4e87f000-1c5d-11eb-9c22-f92ae7144310.png)

So PS7 seems to be working, sort of.

**Comment by SeeminglyScience** [comment]
Check the PSRL versions between 5.1 and 7

**Comment by SeeminglyScience** [comment]
What about when setting the encoding info?

**Comment by PrzemyslawKlys** [comment]
That's all on UTF-8 as I added it on profile in 3 places (ps5,ps7, code)

**Comment by SeeminglyScience** [comment]
Then 🤷 

Almost looks like a bug in the .NET framework encoding APIs, but I haven't looked into that.  I saw a few issues about that encoding error on PSRL, but I haven't dug around. I thought it was more of the old stuff that's been fixed, but I'm guessing I never ran into it because I don't touch 5.1 much anymore.

Either way, I think it's still safe to say it's not something to do with vscode-powershell.  Probably needs to be handled in PSRL

**Comment by PrzemyslawKlys** [comment]
It's not a big deal :-) It was more "let's see if it can be fixed" but it's not really a problem. I have so many other problems that this one is non-existing for me.

**Comment by SydneyhSmith** [comment]
Thanks for all the debugging, looks like this issue is tied to .NET framework so we likely cannot fix that 
@daxian-dbw in case you have any thoughts
