### ISSUE TITLE
Constantly asked to install PowerShell extension

### ISSUE THREAD

**Issue by Bourmatnov** [PowerShell/vscode-powershell#3035]
Visual Studio code constantly asks me if I want to install the PowerShell extension despite the fact that I have already installed one.  This appears as a small blue box on the bottom right.  I suspect this may be caused by the fact that it is looking for "PowerShell" not "PowerShell Preview".  Any way to turn this off?

**Comment by corbob** [comment]
When you click the notification to Show Recommendations there is an option to "Ignore Recommendation". If you click that it shouldn't notify you anymore.

![image](https://user-images.githubusercontent.com/30301021/97234662-87781e80-179e-11eb-8432-efcfcd8847d6.png)


Alternatively you could install the extension, then disable it.

**Comment by SydneyhSmith** [comment]
Thanks unfortunately that is controlled by VSCode so we cant stop recommendations....another workaround is to use VSCode Insiders which prefers the preview extension and therefore wont ask you to install the PowerShell extension
