### ISSUE TITLE
Debugger not catching mistyped commands

### ISSUE THREAD

**Issue by ChadThomsen** [PowerShell/vscode-powershell#304]
**Please fill in these details so that we can help you!**
### System Details
- Operating system name and version:
  Windows 7
- VS Code version:
  1.5.3
- PowerShell extension version:
  0.7.2
- Output from `$PSVersionTable`:
  Name                           Value
  ---
  
  PSVersion                      4.0
  WSManStackVersion              3.0
  SerializationVersion           1.1.0.1
  CLRVersion                     4.0.30319.42000
  BuildVersion                   6.3.9600.16406
  PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
  PSRemotingProtocolVersion      2.2

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```
### Issue Description

I am experiencing a problem with... debugger.

The feature that catches miss-typed commands is not working.  It usually puts a red squiggly line under the miss-typed command to let you know you made a mistake.  It is working with brackets, parentheses if you happen to leave off the closing bracket or parentheses.  
### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by SydneyhSmith** [comment]
@ChadThomsen I am going through old issues and am wondering if with the updates you are still running into this issue? Thanks!

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
