### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by PraveenADPP** [PowerShell/vscode-powershell#3040]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2020.6.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by SydneyhSmith** [comment]
@PraveenADPP please add more details and re-open the issue--thanks!
