### ISSUE TITLE
script debugging slow when multiple vscode instances open

### ISSUE THREAD

**Issue by mpowrie** [PowerShell/vscode-powershell#3042]
Issue Type: <b>Bug</b>

Powershell script debugging is very slow when multiple vscode instance are open.

This happens with bother Powershell 7.0.3 and Powershell 5.1

Extension version: 2020.6.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (2.41GB free)|
|Process Argv|C:\Users\MarcusPowrie\Desktop\Test provision of Encompaas to EncompaaS.txt --crash-reporter-id edf1a949-3c50-486c-9eb2-9f9c67268292|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SydneyhSmith** [comment]
Thanks @mpowrie for opening this issue, it would be great if you could provide any additional context into what is slow (stepping through, variable pane etc.), what you are debugging, as well as any logs you can collect-- instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)...thanks!
