### ISSUE TITLE
Update examples-module to use Pester 5

### ISSUE THREAD

**Issue by fflaten** [PowerShell/vscode-powershell#3049]
**Summary of the new feature**

The example-module included in vscode-powershell uses Pester-tests that are not compatible with Pester v5. Is it time to update the examples?

**Proposed technical implementation details (optional)**

Update tests in example module to Pester v5-compatible code.

**Comment by SydneyhSmith** [comment]
Thanks @fflaten we should update this: https://github.com/PowerShell/vscode-powershell/tree/master/examples/Tests I will mark this as up for grabs in case someone has time to get to this before we do--thanks!
