### ISSUE TITLE
Function name highlighting not correct

### ISSUE THREAD

**Issue by Bill-Stewart** [PowerShell/vscode-powershell#305]
### System Details
- Operating system name and version: Windows 7 x64
- VS Code version: 1.5.3
- PowerShell extension version:  0.7.2
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### Issue Description

See picture - when function definition is indented, highlighting of function name is not correct.

![vscode-powershell-highlight-problem](https://cloud.githubusercontent.com/assets/22036935/18850589/6fddf97a-83f5-11e6-9506-d7d721bd6318.png)

(As an aside, how do we disable automatic highlighting of function names, variables, etc.?)

**Comment by rkeithhill** [comment]
Does this behave any better if you save the file with a .ps1 extension? From the picture, I can't tell if you've set the file type to PowerShell.  Even then, I seem to recall an issue where that really doesn't work quite right until you've "saved" the file with a .ps1 extension.

**Comment by Bill-Stewart** [comment]
Yes, file type is PowerShell; issue presents whether file saved or not.

**Comment by daviwil** [comment]
For disabling the automatic highlight you could try this setting but I'm not sure it will turn off the 'occurrences' highlighting: `"editor.selectionHighlight": false`.  Wasn't able to find a specific setting for that one unfortuantely.

I've never seen incorrect file offsets being sent back before, mind capturing logs from a clean launch of the editor/extension so that I can take a look?

**Comment by rkeithhill** [comment]
It is pretty easy to repro.  Open VSCode, set the Untitled-1 file to type PowerShell, type in
```
function Test-Function {
}
```
Double click Test and the whole function name is highlighted.  Indent the whole function and double-click in Test again and the selection highlight is wrong.

**Comment by Bill-Stewart** [comment]
Keith is correct; that is the behavior. I have `editor.selectionHighlight` setting set to `false` but the highlighting still happens in PowerShell. (I would prefer no automatic highlighting.)

**Comment by daviwil** [comment]
Cool, I'll investigate, thanks!

**Comment by JustinGrote** [comment]
This is an issue with the TextMate definition, I actually made an add-on vscode extension to fix this very thing as a workaround:

https://github.com/JustinGrote/vscode-better-powershell-syntax-highlighting
https://marketplace.visualstudio.com/items?itemName=justin-grote.better-powershell-syntax-highlighting

https://github.com/PowerShell/EditorSyntax

An upstream issue should be created in EditorSyntax

**Comment by TylerLeonhardt** [comment]
I've got a fix out for this one.

**Comment by TylerLeonhardt** [comment]
Also if you want to disable this for just PowerShell:

```jsonc
"[powershell]": {
    // PowerShell specific settings here
    "editor.selectionHighlight": false
}
```
