### ISSUE TITLE
The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread.

### ISSUE THREAD

**Issue by rachaelsingleton** [PowerShell/vscode-powershell#3057]
I am getting the following error when using visual studio code & powershell 7 and running a commandlet.

The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread.

I do not get this error in the native PowerShell 7 terminal (outside of VS Code).

**Comment by rjmholt** [comment]
Hi @rachaelsingleton can you provide more information:

- What cmdlet?
- What module?
- Please give us a reproduction of the issue so we can try to replicate it locally
- Providing your extension logs will help. You can find instructions for this in the issue template.

**Comment by rachaelsingleton** [comment]
What cmdlet? - Register-PnPManagementShellAccess and/or Connect-PnPOnline -PnPManagementShell 
What module? PnP.PowerShell 

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/5531014/EditorServices.log)

**Comment by rjmholt** [comment]
Thanks for that info.

Where are you seeing the error message you report? Are you seeing it consistently? If the error is shown in the terminal, can you run `Get-Error` and share the full error output there -- hopefully we can get a stack trace so we can properly work out what's going on here.

**Comment by rachaelsingleton** [comment]
Exception :
Type : System.Management.Automation.PSInvalidOperationException
ErrorRecord :
Exception :
Type : System.Management.Automation.ParentContainsErrorRecordException
Message : The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and
they can only be called from within the same thread. Validate that the cmdlet makes these calls correctly, or contact Microsoft Customer Support Services.
HResult : -2146233087
CategoryInfo : InvalidOperation: (:) [], ParentContainsErrorRecordException
FullyQualifiedErrorId : InvalidOperation
TargetSite :
Name : ProcessRecord
DeclaringType : PnP.PowerShell.Commands.Base.ConnectOnline
MemberType : Method
Module : PnP.PowerShell.dll
StackTrace :
at PnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\ConnectOnline.cs:line 264
at System.Management.Automation.CommandProcessor.ProcessRecord()
Message : The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they
can only be called from within the same thread. Validate that the cmdlet makes these calls correctly, or contact Microsoft Customer Support Services.
Data : System.Collections.ListDictionaryInternal
Source : PnP.PowerShell
HResult : -2146233079
CategoryInfo : InvalidOperation: (:) [Connect-PnPOnline], PSInvalidOperationException
FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Base.ConnectOnline
InvocationInfo :
MyCommand : Connect-PnPPnPOnline
ScriptLineNumber : 1
OffsetInLine : 1
HistoryId : 37
Line : Connect-PnPOnline -Url "removed" -PnPManagementShell -verbose
PositionMessage : At line:1 char:1
+ Connect-PnPOnline -Url "removed …
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
InvocationName : Connect-PnPOnline
CommandOrigin : Internal
ScriptStackTrace : at , : line 1

**Comment by SydneyhSmith** [comment]
Thanks--closing in favor of https://github.com/pnp/powershell/issues/24
