### ISSUE TITLE
Add an option to put one whitespace before and after each pipeline in the formatter settings.

### ISSUE THREAD

**Issue by yuusakuri** [PowerShell/vscode-powershell#3059]
# Summary of the new feature

Add an option to put one whitespace before and after each pipeline in the formatter settings.
However, if there is a line break immediately after the pipeline, no whitespace will be added after the pipeline.

Add the following to the options.

**settings.json**
```json
"powershell.codeFormatting.whitespaceAfterPipeline": true,
"powershell.codeFormatting.whitespaceAfterPipeline": true,
```

With these settings, a script will be formatted as follows:

**Before formatting**
```powershell
ls | Where-Object { Test-Path $_ }|
Out-Null
```
**After formatting**
```powershell
ls | Where-Object { Test-Path $_ } |
Out-Null
```

**Comment by SydneyhSmith** [comment]
Thanks @yuusakuri this feature is currently available with the setting `"powershell.codeFormatting.addWhitespaceAroundPipe": true"`
