### ISSUE TITLE
Network path broke when using auto complete

### ISSUE THREAD

**Issue by monghuz** [PowerShell/vscode-powershell#306]
**Please fill in these details so that we can help you!**
### System Details
- Operating system name and version: Win 10
- VS Code version: 1.5.3
- PowerShell extension version: 0.7.2
### Issue Description

When I using the auto complete feature for network path the leading double backslash changed to single one. As a result of it after every time I need to read the missing backslash to the beginning of the path. 

Example before the autocomplete feature used
`\\my\share` 
At this point I see the sub folders and files as expected. 
Then:
`\my\share\folder1`

**Comment by mpearon** [comment]
I encountered the same behavior, and got a response:
[#681](https://github.com/PowerShell/vscode-powershell/issues/681)

**Comment by daviwil** [comment]
Hey @monghuz, I apologize for the extremely long delay in response!  Are you still seeing this issue in the latest VS Code and PowerShell extension versions?

**Comment by monghuz** [comment]
Hey @daviwil,

Sadly yes. I just upgraded to 1.12.2 but the issue is still there.
To repro the issue you can create a share (abc) on your local pc and try to resolve the address 
type: \\yourPC\a   
hit ctrl + space

result should be
\yourPD\abc

**Comment by daviwil** [comment]
Can you try it in the VS Code Insiders release? I believe they fixed it recently but the fix hasn't made it to the main VS Code release yet.

**Comment by mpearon** [comment]
Rejoice, @monghuz As of 1.13.0, this is corrected! :)

**Comment by daviwil** [comment]
Yep, this should be fixed now, let me know if you still see it after installing the VS Code 1.13.0 update which just got released yesterday.
