### ISSUE TITLE
ms-vscode.powershell creates folders in My Documents

### ISSUE THREAD

**Issue by FrederikSeyns** [PowerShell/vscode-powershell#3063]
When this plugin gets installed, a folder 'WindowsPowerShell' is being created in the MyDocuments folder.

Can this folder be created at another location? 
Or is there a specific reason it gets created in the MyDocuments folder?

**Comment by SydneyhSmith** [comment]
Thanks @FrederikSeyns this is PowerShell's current user directory (for storing profile, modules etc.) and is created by PowerShell/PowerShellGet, and not VSCode...had you ever started PowerShell before using VSCode? Also is there anything being placed in this folder or is it empty? Thanks!
