### ISSUE TITLE
Remote debugging session hangs the PowerShell Integrated Terminal

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#3065]
### System Details

System Details Output
```
### VSCode version: 1.51.1 e5a624b788d92b8d34d1392e4c4d9789406efe8f x64

### VSCode extensions:
amazonwebservices.aws-toolkit-vscode@1.15.0
arcticicestudio.nord-visual-studio-code@0.15.0
cweijan.vscode-autohotkey-plus@2.6.1
daylerees.rainglow@1.5.2
donjayamanne.githistory@0.6.14
DotJoshJohnson.xml@2.5.1
dracula-theme.theme-dracula@2.22.2
eamodio.gitlens@11.0.2
EliverLara.andromeda@1.7.0
Equinusocio.vsc-community-material-theme@1.4.2
Equinusocio.vsc-material-theme@33.0.0
equinusocio.vsc-material-theme-icons@1.2.0
felipe-mendes.slack-theme@1.9.12
formulahendry.code-runner@0.11.1
hbenl.vscode-test-explorer@2.19.3
icsharpcode.ilspy-vscode@0.9.0
influxdata.flux@0.5.9
johnpapa.vscode-peacock@3.8.0
kenhowardpdx.vscode-gist@3.0.3
littlefoxteam.vscode-python-test-adapter@0.6.3
ms-azuretools.vscode-azurefunctions@1.0.1
ms-azuretools.vscode-docker@1.8.0
ms-dotnettools.csharp@1.23.6
ms-kubernetes-tools.vscode-kubernetes-tools@1.2.1
ms-python.python@2020.11.371526539
ms-toolsai.jupyter@2020.11.372831992
ms-vscode-remote.remote-containers@0.148.1
ms-vscode-remote.remote-ssh@0.56.0
ms-vscode-remote.remote-ssh-edit@0.56.0
ms-vscode-remote.remote-wsl@0.51.4
ms-vscode.azure-account@0.9.4
ms-vscode.cpptools@1.1.2
ms-vscode.powershell@2020.6.0
ms-vscode.powershell-preview@2020.9.0
ms-vsliveshare.vsliveshare@1.0.3206
Nuuf.theme-hackershaze@2.0.1
octref.vetur@0.30.2
redhat.vscode-yaml@0.13.0
ritwickdey.LiveServer@5.6.1
RobbOwen.synthwave-vscode@0.1.8
samrapdev.outrun@0.2.2
Unity.unity-debug@3.0.2
usernamehw.errorlens@3.2.4
vscodevim.vim@1.17.1
webrender.synthwave-x-fluoromachine@0.0.12
ymotongpoo.licenser@1.5.0


### PSES version: 

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am trying to use the [remote debugging](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/using-vscode-for-remote-editing-and-debugging) capabilities of PowerShell to debug a script. As I've explored this feature, it repeatedly causes the PowerShell Integrated Console to hang.

This seems to happen with both the 2020.06 release as well as the 2020.09 preview release of the VSCode PowerShell extension.

### Reproduction Steps

1. Start VSCode
1. In the PowerShell Integrated Console:
1. `$Sess = New-PSSession -Hostname xyz -Username xyz`
1. `Enter-PSSession $Sess`
1. `touch test.ps1`
1. `psedit test.ps1`
1. Add some code, similar to the below
1. Save file and hit F5 to start debugging
1. After a few debugging attempts, the remote session completely hangs
1. If not, add another line to the script, save it, and try debugging again

```
$ProcList = Get-Process

foreach ($Proc in $ProcList) {
  Write-Host $Proc.Name
}

Write-Host done
```

#### Expected Behaviour

* PowerShell Remote Debugging works consistently.
* Breakpoints defined in the remote script are hit.

#### Actual Behaviour

* PowerShell Integrated Console in Visual Studio Code hangs in a remote session.
* Breakpoints in remote script are skipped over.

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by SydneyhSmith** [comment]
Thanks @pcgeek86 for all the info, looks like this one will need a deeper dive, unfortunately with the holidays coming up quickly we may be a bit slow for the full investigation

**Comment by SydneyhSmith** [comment]
Looking at this a bit further it looks like this may be related to https://github.com/PowerShell/PowerShellEditorServices/issues/1295 given that the debugging initially works and then eventually dies... looks like you are using ssh remoting, have you tried the [Remote SSH extension for VSCode](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)? It may serve as a work around as we fix this issue.
