### ISSUE TITLE
Unable to run scripts in Editor if folders in explorer or workspace

### ISSUE THREAD

**Issue by baldieavenger** [PowerShell/vscode-powershell#3066]
Issue Type: <b>Bug</b>

Hi team,

Im new to Code from ISE so apologies for the lack of knowledge around it but trying to figure things out. Other than this.

When adding a local directory folder to my saved workspace, when I try to use F5 to run the script in my editor, Im given this error:
```
PS C:\LOCALPATH> C:serssernameocumentsindowsPowerShellicrosoft.VSCode_profile.ps1
The term 'C:serssernameocumentsindowsPowerShellicrosoft.VSCode_profile.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
+ CategoryInfo : ObjectNotFound: (C:serssername...ode_profile.ps1:String) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : CommandNotFoundException
```
Looks like its trying to run my already run and loaded Microsoft.VSCode_profile.ps1 which contains my 365 modules and I have no idea why or how to start to figure it out.

Its only when I pin the same folder my current powershell directory is set to. If I dont pin that folder, even with multiple other folders pinned then its fine!

I thought maybe a file ext in there tying it up so deleted most but still have the issue.

I tried changing my directory to something else and pinning the folder again but when I hit F5, it changes my directory back to that pinned location with the same error ( I use "CD C:\Etc\Etc" to set my directory on log in in Microsoft.VSCode_profile.ps1.) but now at a loss as to whats causing it.

Extension version: 2020.6.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (11.30GB free)|
|Process Argv|--crash-reporter-id 65dcdb6a-001e-48a3-9408-857c412d154f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by baldieavenger** [comment]
Looks like a subfolder named .vscode with 2 files inside, launch.json and tasks.json
I assume I dont need them as it seems to work fine if I delete the folder! 
Only took 3 hours to slowly add everything back and close and open to test.....

**Comment by SydneyhSmith** [comment]
@baldieavenger thanks for this issue, sounds like you've unblocked yourself...unfortunately we are having some trouble figuring out how to reproduce this (so we can investigate what you might be experiencing), it would be awesome if you could provide more detailed reproduction steps including what f5 was set to (your launch configuration), and any workspace layout (what files and directories you have), workspace configurations you have as well as any settings you may have in VSCode...thanks!

**Comment by baldieavenger** [comment]
Hi @SydneyhSmith !
Happy to help out and give you whatever I can! Ill need some help with getting the information you need though as im not overly familiar with how everything works, the terms or what it is you would need.
Happy to go via Private message (If thats a thing here) and restore files or export configs for you to try and reproduce if you need?

________________________________

**Comment by SydneyhSmith** [comment]
Thanks @baldieavenger if you are able to get a consistent reproduction of this issue please we prefer you share info in this issue so that we can collaborate openly (if there is any private info please send to vscode-powershell@microsoft.com)..if you are no longer hitting an issue also feel free to just close this out.

**Comment by baldieavenger** [comment]
Thanks Sydney,

I can reproduce it by restoring the folder ".vscode" and adding the folder to my workspace but im no longer impacted by it.
Up to you if youd like to figure it out or not!
Happy to provide you with whatever you need if you want to look further into it?
John
________________________________
