### ISSUE TITLE
Syntax highlighting for commented out code incorrect (Doc

### ISSUE THREAD

**Issue by Aculeo** [PowerShell/vscode-powershell#307]
### System Details
- VS Code version: 1.5.3
- PowerShell extension version: 0.7.2

Found a minor issue with the highlighting for commented out code. It highlights '.Description' like it is part of the documentation for a cmdlet. PowerShell ISE highlights this correctly. Not really a big deal, just found it a bit irritating :)

**VS Code / PowerShell**:
![vscode-powershell-highlighting-bug](https://cloud.githubusercontent.com/assets/3977620/18910889/4d0dbbde-857a-11e6-84cc-6cfa6176cec3.PNG)

**ISE**:
![ise-highlighting](https://cloud.githubusercontent.com/assets/3977620/18910808/f0ae6514-8579-11e6-8d7e-ffa2babac34c.PNG)

**Comment by rkeithhill** [comment]
Syntax highlighting is done by a different project - https://github.com/PowerShell/EditorSyntax  Can you submit this issue on that project?

**Comment by SydneyhSmith** [comment]
Closing, as this issue is for another project.
