### ISSUE TITLE
cannot debug or run a powershell script after installeding the bug fix in #2897

### ISSUE THREAD

**Issue by ftpex1** [PowerShell/vscode-powershell#3076]
### System Details

System Details Output
```

```

### Issue Description

I am experiencing a problem with...

#### Expected Behaviour

-- Description of what *should* be happening --

#### Actual Behaviour

-- Description of what actually happens --

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by efie45** [comment]
Not sure if this is along the same vein but I've also been having issues trying to debug scripts inside of vscode. The behavior is a little erratic so it's been hard to track down a good reproduction scenario.

 Essentially when debugging a script, the debugger will skip over breakpoints. I don't seem to see an exact pattern but for instance if they are just a few lines apart, pressing the run/continue key will skip to the next breakpoint. However, if I set a breakpoint with a few more lines of code between, it never hits the next breakpoint and just executes it and finishes executing the script. In fact, once it decides to start skipping breakpoints it never breaks into the debugger again, even if all lines are selected as breakpoints. 
 
 I uninstalled powershell preview and was able to get it working. For reference, this started happening both on vscode on my mac running PowerShell 7 and on my Windows VM vscode running PowerShell 5.1. The issue appears to be resolved after uninstall the PowerShell Preview extension and installing the regular PowerShell extension.

**Comment by namedtoaster** [comment]
I've been having issues with debugging scripts as well. The behavior is not consistent: sometimes the debugger works without question, sometimes it is just pending and doesn't even hit a breakpoint I set at the first line in the script. It might be worth noting I am running VS Code in an elevated window
