### ISSUE TITLE
Variables in Invoke-Expression arguments do not get counted as used. 

### ISSUE THREAD

**Issue by vpr5703** [PowerShell/vscode-powershell#3083]
Issue Type: <b>Bug</b>

When setting variables that are later used in Invoke-Expression commands, VS Code flags the variables as never used, even if they appear in the Invoke-Expression command. 

1. Set a variable
2. Use the variable in an Invoke-Expression cmdlet. 
3. Note that VS Code flags a warning that the command is assigned but not used. 

Extension version: 2020.6.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz (12 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.69GB (52.26GB free)|
|Process Argv|--crash-reporter-id c1d64596-d05d-4a27-95a4-1f9c4a13a4af|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by vpr5703** [comment]
This code recreates the issue in the current public release version of VS Code

`$PATHWEB = "C:\Windows\WEB\Wallpaper\Windows"
$USERACCOUNT = "System"
$PERMISSION = ":(OI)(CI)F" #(OI) Object Inherit; (CI) Container Inherit; (F) Full Access 
Invoke-Expression -Command ('ICACLS $PATHWEB /GRANT *S-1-1-0:F /T "${$USERACCOUNT}${$PERMISSION}"')`

**Comment by SeeminglyScience** [comment]
`Invoke-Expression` can't really be statically analyzed accurately.  That's one of the many downsides.

Side note, `${$USERACCOUNT}` actually references a variable named `$USERACCOUNT`, not one named `USERACCOUNT`.  You probably want `"$USERACCOUNT$PERMISSION"` or `"${USERACCOUNT}${PERMISSION}"`.

Also you don't need `Invoke-Expression` there.  You can do this instead:

```powershell
$PATHWEB = "C:\Windows\WEB\Wallpaper\Windows"
$USERACCOUNT = "System"
$PERMISSION = "(OI)(CI)F" #(OI) Object Inherit; (CI) Container Inherit; (F) Full Access

ICACLS $PATHWEB /GRANT "${USERACCOUNT}:${PERMISSION}" /T
```

**Comment by vpr5703** [comment]
Ah ok. I am fairly new to all of this, so I am still learning. Thanks for the tip, I appreciate it.

**Comment by rjmholt** [comment]
> Invoke-Expression can't really be statically analyzed accurately. That's one of the many downsides.

Yes, [you should avoid `Invoke-Expression`](https://devblogs.microsoft.com/powershell/invoke-expression-considered-harmful/) wherever possible. [We've been trying to collect use-cases where it's unavoidable](https://github.com/PowerShell/PowerShell/issues/11662) but there don't seem to be many.

Because `Invoke-Expression` can assemble arbitrary strings at runtime before executing them, it's impossible to statically analyse. For example, you could make a web request that resolves a string that you then send to `Invoke-Expression` &mdash; there's no way to know before that web request is made whether `$PATHWEB` is going to be referenced by the executed string.

**Comment by vpr5703** [comment]
Awesome, thanks for the reply. I will close the issue since it is a known effect of the command. Thank You.
