### ISSUE TITLE
[UI] Status bar coloring of Session indicator is unreadable for accessibility

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#3084]
### System Details

System Details Output
```
### VSCode version: 1.52.0-insider bc13785d3dd99b4b0e9da9aed17bb79809a50804 x64

### VSCode extensions:
2gua.rainbow-brackets@0.0.6
DavidAnson.vscode-markdownlint@0.38.0
DotJoshJohnson.xml@2.5.1
DougFinke.vscode-pandoc@0.0.8
GitHub.vscode-pull-request-github@0.21.4
mhutchie.git-graph@1.28.0
ms-azuretools.vscode-docker@1.8.1
ms-mssql.mssql@1.9.0
ms-mssql.sqlops-debug@1.3.0
ms-python.python@2020.11.371526539
ms-toolsai.jupyter@2020.11.399280825
ms-vscode-remote.remote-containers@0.152.1
ms-vscode-remote.remote-ssh@0.58.0
ms-vscode-remote.remote-ssh-edit@0.58.0
ms-vscode-remote.remote-wsl@0.52.0
ms-vscode-remote.vscode-remote-extensionpack@0.20.0
ms-vscode.azure-account@0.9.4
ms-vscode.powershell@2020.6.0
ms-vscode.powershell-preview@2020.9.0
ms-vsliveshare.vsliveshare@1.0.3206
ms-vsliveshare.vsliveshare-audio@0.1.91
ms-vsliveshare.vsliveshare-pack@0.4.0
oderwat.indent-rainbow@7.4.0
redhat.vscode-yaml@0.13.0
sdras.night-owl@2.0.0
streetsidesoftware.code-spell-checker@1.10.2
usernamehw.errorlens@3.2.4
vscode-icons-team.vscode-icons@11.0.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

The status bar indicator color for the session indicator, where it shows the PowerShell version, is not readable in all themes due to the color hardcoded. This should be overwritable using the `"statusBar.foreground"` setting for `workbench.colorCustomizations` but the extension is not allowing it.

![image](https://user-images.githubusercontent.com/11204251/101396914-98ce4380-3891-11eb-9247-a74e6182e2ec.png)

![image](https://user-images.githubusercontent.com/11204251/101396825-7ccaa200-3891-11eb-86c1-8faa7da0a8b4.png)

#### Expected Behaviour

The color chosen when customizing Themes is honored.

#### Actual Behaviour

The setting is being ignored as the coloring of that value is hardcoded (it seems) in the extension because it keeps the same color no matter what theme is used.

**Comment by corbob** [comment]
I believe there's a previous (perhaps closed) issue for this... IIRC there was talk of getting the color from the theme, but that wasn't available or something. Perhaps even if there isn't a way to derive the color from extension, until there is the color should be set as the foreground (ie: remove any custom coloring).

**Comment by wsmelton** [comment]
If it was made a configurable item would be nice if there is an insistent in having it be a set color.

**Comment by ninmonkey** [comment]
@corbob I believe this is new functionality that can allow users to customize the color

https://code.visualstudio.com/api/references/contribution-points#contributes.colors

**Comment by rjmholt** [comment]
In term of the issue as described in the title, I think this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/2436.

Configuration of the colour is discussed in https://github.com/PowerShell/vscode-powershell/issues/1779.

**Comment by wsmelton** [comment]
I tried searching for `status bar` and such but never came across those two for some reason.

I'll close this since #1779 addresses my concerns.
