### ISSUE TITLE
PSScriptAnalyzer is unavailable when using the specific PowerShell statement

### ISSUE THREAD

**Issue by msl0** [PowerShell/vscode-powershell#3090]
### System Details

System Details Output
```
### VSCode version: 1.51.1 e5a624b788d92b8d34d1392e4c4d9789406efe8f x64

### VSCode extensions:
ms-vscode.powershell@2020.6.0
ms-vscode.powershell-preview@2020.9.0


### PSES version: 2.3.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

PSScriptAnalyzer not works code when using PSUseCompatibleCmdlets rule only with with following. 
![image](https://user-images.githubusercontent.com/59068696/101883614-c966f380-3b97-11eb-855c-2af4fe2a542f.png)

Works when I run PSScriptAnalyzer from PowerShell Integrated Console via command Invoke-ScriptAnalyzer <filename.ps1>. When coment last line or PSUseCompatibleCmdlets rule section in PSScriptAnalyzer settings file it works
![image](https://user-images.githubusercontent.com/59068696/101883717-f0bdc080-3b97-11eb-82a0-478c2c967c9a.png)

PSScriptAnalyzerSettings.psd1
```
@{
    Rules = @{
        PSUseCompatibleCmdlets  = @{
            'compatibility' = @("desktop-2.0-windows")
        }
        PSUseCompatibleCommands = @{
            # Turns the rule on
            Enable         = $true

            # Lists the PowerShell platforms we want to check compatibility with
            TargetProfiles = @(
                'ubuntu_x64_18.04_7.0.0_x64_3.1.2_core'
            )
        }
    }
}
```

I tested when ms-vscode.powershell-preview was enabled and ms-vscode.powershell disabled, and next time when ms-vscode.powershell-preview was disabled and ms-vscode.powershell enabled - same results

#### Expected Behaviour

Script analysis should works.

#### Actual Behaviour

Script analysis not works.

**Comment by rjmholt** [comment]
@msl0 are you saying that script analysis in the editor only works after you've edited the file? Or even after you've edited it, does it not work until you've commented out the last line? Or do you need to run a command in the Integrated Console to make things work? Does that command have to be `Invoke-ScriptAnalyzer`?

If you could include your logs as requested in the issue template, that might help us understand the issue better.

**Comment by msl0** [comment]
> @msl0 are you saying that script analysis in the editor only works after you've edited the file? Or even after you've edited it, does it not work until you've commented out the last line? Or do you need to run a command in the Integrated Console to make things work? Does that command have to be `Invoke-ScriptAnalyzer`?
> 
> If you could include your logs as requested in the issue template, that might help us understand the issue better.

Yes, using first example I don't see new problems after I add for instance new never used variable. I don't see updates in "PROBLEMS" until I delete or comment line 4.

When I use Integrated Console it works (even if last line exists or not or exists uncommented), but I see output in console and I need run command every time manually when I want to check analyzer output. But I use powershell extension because I don't want to run command for perform the analysis every time but see errors immediately without manual steps.

Yes, command have to be `Invoke-ScriptAnalyzer`, its command which we can use to run PSScriptAnalyzer manually
https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/markdown/Invoke-ScriptAnalyzer.md#examples

I sent the logs by e-mail
