### ISSUE TITLE
Format Document fails to run at all, when script contains certain valid syntax 

### ISSUE THREAD

**Issue by moymike** [PowerShell/vscode-powershell#3103]
VS-Code Version: 1.52.1
PowerShell Extension 2020.6.0

I could not find any issue that gave me any fix. 

I stole this example and am submitting it as an example where "Format Document" fails when I issue either the command or hit the Shift-Alt-F shortcut.  (The code is a non-nothing just to illustrate)
(on a side note, the "<>" insert code is not working right for me... I'll fix it if somebody tells me what I am doing wrong)

```powershell
@{
      foo      = "dfsf"
    bar = "dddff"
}
$breakformat = "Results: $(@{foo = $foo; bar = $bar } | Out-String)"
    foreach ($Test in $Test1) {
    foreach ($Test2 in $TEst3) {

    }
    }
```

When I hit "Format Document" on this, nothing happens.  The key is the line that sets the variable `$breakformat`.  The formatter fails on this line as it contains code within the quotes, and within the $().  Specifically the use of a pipe '|' is what kills the formatter here.

From a post I found here, I tried the `Invoke-Formatter`.  This example outputs the formatted code into the terminal.

```powershell
Invoke-Formatter -ScriptDefinition @'
@{
      foo      = "dfsf"
    bar = "dddff"
}
$breakformat = "Results: $(@{foo = $foo; bar = $bar } | Out-String)"
    foreach ($Test in $Test1) {
    foreach ($Test2 in $TEst3) {

    }
    }
'@
```

This works, but when the same code (within the ScriptDefinition ) is in the editor, the "Format Document" fails.

**Comment by rjmholt** [comment]
I tried reproducing this locally but was unable to:

![format](https://user-images.githubusercontent.com/7009879/103704292-eb1c8600-4f5d-11eb-8d60-1586ab093a46.gif)

Can you please provide the requested information, including logs, from the issue template?

**Comment by moymike** [comment]
It's nuts.  I was able to duplicate it over and over before I posted.  Now, a different day, it appears to work.  If I run into it again, I'll dig deeper and post if I can duplicate.  (test on a second machine also)

**Comment by moymike** [comment]
I figured it out.  I had an older version of PSScriptAnalyzer (1.16.1) hiding out in my user\Documents\WindowsPowerShell\Modules folder.   I removed it and the Format Document works as expected.
