### ISSUE TITLE
Hide PowerShell Command Explorer from Activity Bar

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#3104]
When I want to find PowerShell commands, I typically use the `Get-Command` or `Get-Module` commands that are built into PowerShell. Hence, I don't have a need for the Command Explorer feature in the VSCode PowerShell extension. It would be nice to clean this up off the VSCode Activity Bar.

I understand that it's somewhat trying to replicate the ISE functionality, but I don't personally need this.

**Comment by corbob** [comment]
Just set this to false and it shouldn't show up: `powershell.sideBar.CommandExplorerVisibility`

**Comment by pcgeek86** [comment]
Thanks, I was searching for an option with "activity" in the name. Might be advisable to add that into the setting name somewhere.
