### ISSUE TITLE
Cannot change PSVersion 5.1.18362.1171 from Powershell Integrated Console

### ISSUE THREAD

**Issue by npalmer1452** [PowerShell/vscode-powershell#3118]
I'm trying to have the VS Code Powershell integrated console run in powershell 7, however i cannot seem to be able to remove version 5.  Even when i have the "terminal.integrated.shell.windows" set to the file location for pwsh.exe.  I even tried uninstalling and re-installing the PS extension in VS code.

**Comment by npalmer1452** [comment]
Adding this to the settings.json in vscode ended up correcting the issue.  

    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": C:\\Windows\\System32\\WindowsPowerShell\\7\\pwsh.exe",
            "versionName": "pwsh"
        }
    ],
    "powershell.powerShellDefaultVersion": "pwsh",

**Comment by rjmholt** [comment]
> Even when i have the "terminal.integrated.shell.windows" set to the file location for pwsh.exe

Yes, this is VSCode's terminal shell configuration, not the PowerShell extension's Integrated Console configuration.

> C:\\Windows\\System32\\WindowsPowerShell\\7\\pwsh.exe

This is a strange installation path. The extension looks for the MSI's default installation path, which is `C:\Program Files\PowerShell\7\pwsh.exe`.

But as you've discovered, you can add a custom installation path for the extension to find using the `powershel.powerShellAdditionalExePaths` configuration.
