### ISSUE TITLE
Cannot load assembly <assembly name>

### ISSUE THREAD

**Issue by Koan-om** [PowerShell/vscode-powershell#3119]
Issue Description
=====
1.VSCode Clean install
2.Install Powershell extention v2020.6.0
3.Open a .ps1 file with the first lines:
Using Assembly System.windows.forms
Using Assembly System.Drawing
Using Assembly System.XML

Squiggly lines appear after all Using Assembly commands with the message "Cannot load assembly . Powershell"

On the other hand the "Using NameSpace System.windows.forms" does not cause a warning message.

If i try to run the .ps1 file i get:
ParserError: C:\PS1\PD\PD.ps1:3:16
Line |
3 | Using Assembly System.windows.forms
| ~~~~~~~~~~~~~~~~~~~~
| Cannot load assembly 'System.windows.forms'.

The same .ps1 file runs alright on old Powershell ISE.

Attached Logs
=====

[1609881539-3a03f4e3-bb0a-4ba9-adbd-c7724f0b1b24160988133210620210106_0026.zip](https://github.com/PowerShell/vscode-powershell/files/5772681/1609881539-3a03f4e3-bb0a-4ba9-adbd-c7724f0b1b24160988133210620210106_0026.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.52.1|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.0|
|PSEdition|Core|
|GitCommitId|7.1.0|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|powershell|ms-vscode|2020.6.0|

**Comment by rjmholt** [comment]
> The same .ps1 file runs alright on old Powershell ISE.

This occurs because you're running PowerShell 7.1, which doesn't allow you to use `using assembly` the same way. If you try to run your script with PowerShell 7.1, it won't work.

You should configure your VSCode PowerShell extension session to use PowerShell 5.1 if you're looking for a Windows PowerShell 5.1 editing experience. You can do this by clicking on the PowerShell icon in the lower right hand corner of VSCode and selecting Windows PowerShell 5.1. Let me know if you have any issues with this.

**Comment by Koan-om** [comment]
Good day.
Thank you.
Since Powershell progresses to newer and newer versions, is it reasonable, in your opinion, to hold on to version 5.1?
