### ISSUE TITLE
Automatically add the "internalConsoleOptions" setting to existing launch.json files

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#312]
With the upcoming integrated console support, VS Code's debug console will automatically appear when the user starts the debugger unless the following setting is added to `launch.json`:

``` json
"internalConsoleOptions": "neverOpen"
```

To simplify the user experience moving into the new version, it'd be better if we can use the new configuration APIs to manipulate any existing `launch.json` file to insert this setting to `PowerShell` configurations so that the user doesn't have to.

**Comment by TylerLeonhardt** [comment]
This doesn't happen anymore. Closing.
