### ISSUE TITLE
Cyrillic letters are misrepresented in the terminal panel at runtime

### ISSUE THREAD

**Issue by Koan-om** [PowerShell/vscode-powershell#3122]
Issue Description
=====
Only at runtime the Cyrillic letters are misrepresented in the terminal panel.
If i select a piece of code in the editor and run selection (F8) - the characters are displayed correctly.
The same lines at runtime are misrepresented.
The situation repeats itself if i use pwsh.exe in the Windows' command window.
At runtime - wrong. If i type the same line manually - right.

Attached Logs
=====

[1609930968-7c63cc95-2ff6-4fd9-8e38-c306c09f6640160993095743420210106_1404.zip](https://github.com/PowerShell/vscode-powershell/files/5775426/1609930968-7c63cc95-2ff6-4fd9-8e38-c306c09f6640160993095743420210106_1404.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.52.1|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.0|
|PSEdition|Core|
|GitCommitId|7.1.0|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|powershell|ms-vscode|2020.6.0|

**Comment by corbob** [comment]
If I'm understanding correctly, it sounds like an encoding issue with the files being used. Look at this article on encoding issues in PowerShell: https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/understanding-file-encoding?view=powershell-7.1

**Comment by Koan-om** [comment]
Thanks to your advice i was able to solve the problem.
i opened .ps1 file with Windows 1251 encoding and saved it as UTF-8 with BOM.
