### ISSUE TITLE
Out-Host -Paging doesn't work in DeBug (DBG)

### ISSUE THREAD

**Issue by Andy-AO** [PowerShell/vscode-powershell#3127]
Issue Description
=====

Out-Host -Paging doesn't work in DeBug (DBG).

This bug is very easy to repeat.

![image](https://user-images.githubusercontent.com/38101170/104399551-deb2b180-558b-11eb-885c-d85e41bcb491.png)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.52.1|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.0|
|PSEdition|Core|
|GitCommitId|7.1.0|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|calva|betterthantomorrow|2.0.149|
|cjk-word-handler|SharzyL|0.1.1|
|clj-kondo|borkdude|2020.12.120|
|html-preview-vscode|tht13|0.2.5|
|ini-for-vscode|DavidWang|0.0.4|
|java|redhat|0.73.0|
|jupyter|ms-toolsai|2020.12.414227025|
|LogFileHighlighter|emilast|2.10.0|
|markdown-all-in-one|yzhang|3.4.0|
|niketa-theme|selfrefactor|9.19.0|
|output-colorizer|IBM|0.1.2|
|powershell|ms-vscode|2020.6.0|
|rainbow-csv|mechatroner|1.8.0|
|tiny-light|luqimin|0.7.2|
|vscode-java-debug|vscjava|0.30.0|
|vscode-java-dependency|vscjava|0.16.0|
|vscode-java-pack|vscjava|0.12.1|
|vscode-java-test|vscjava|0.27.0|
|vscode-language-pack-zh-hans|MS-CEINTL|1.52.2|
|vscode-languagetool|adamvoss|3.8.0|
|vscode-maven|vscjava|0.27.1|
|vscode-paste-image|mushan|1.0.4|
|vscode-test-explorer|hbenl|2.19.4|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|

**Comment by rjmholt** [comment]
So this seems to work properly in pwsh.exe, implying there's something we might be able to do to improve this experience.

**Comment by SydneyhSmith** [comment]
Thanks @Andy-AO this issue should be fixed in https://github.com/PowerShell/PowerShellEditorServices/issues/1295 but we will want to include it in our testing to verify
