### ISSUE TITLE
Marketplace direct download link for vsix package not working.

### ISSUE THREAD

**Issue by TheRealBenForce** [PowerShell/vscode-powershell#313]
**Please fill in these details so that we can help you!**
### System Details
- Operating system name and version: n/a
- VS Code version: 0.7.2
- PowerShell extension version: n/a 
- Output from `$PSVersionTable`: n/a

```
n/a
```
### Issue Description

I found this link for assistance in determining the link to resolve to an extension for direct downloads from the marketplace. 
https://code.visualstudio.com/docs/editor/extension-gallery

The link I came up with for Powershell 0.7.2 is this, however it does not resolve. I tried a few variations.
https://Microsoft.gallery.vsassets.io/_apis/public/gallery/publisher/Microsoft/extension/PowerShell/0.7.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

I tested the example link, and this does resolve.
https://dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/0.10.18/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

The direct download link is nowhere to be found. Can you please update some documentation such as the wiki with this information?

**Comment by rkeithhill** [comment]
This is an extension for "Visual Studio Code" not "Visual Studio".   Visual Studio Code does not use the VSIX package format.  If you're looking for a PowerShell extension for Visual Studio, check out the excellent [PowerShell Tools for Visual Studio](https://visualstudiogallery.msdn.microsoft.com/c9eb3ba8-0c59-4944-9a62-6eee37294597).

**Comment by daviwil** [comment]
Surprisingly, VS Code does use VSIX as the packaging format for extensions!  Don't ask me why...  

However, gallery link issues should be directed to the Visual Studio Code team since we have no control over the ilnks on the extension marketplace.  We usually package a side-loadable ZIP file upon each release of the extension, you can find them here:

https://github.com/PowerShell/vscode-powershell/releases

**Comment by rkeithhill** [comment]
>>  VS Code does use VSIX 

Well, I learned something new today.  :-)  I've only seen the ZIP's on the GitHub repo.

**Comment by daviwil** [comment]
Closing this since it isn't related to our extension.
