### ISSUE TITLE
Cannot inspect variables or use debug commands in Azure Functions in terminal

### ISSUE THREAD

**Issue by yobyot** [PowerShell/vscode-powershell#3137]
Issue Description
=====

Debugging an Azure Function using the PowerShell extension for VS Code.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Darwin x64 20.2.0 |
| VSCode | 1.52.1|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.1|
|PSEdition|Core|
|GitCommitId|7.1.1|
|OS|Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020, root:xnu-7195.60.75~1/RELEASE_X86_64|
|Platform|Unix|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.1|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|aws-toolkit-vscode|amazonwebservices|1.18.0|
|azure-account|ms-vscode|0.9.4|
|azurerm-vscode-tools|msazurermtools|0.14.0|
|gitlens|eamodio|11.1.3|
|powershell|ms-vscode|2020.6.0|
|vscode-azurefunctions|ms-azuretools|1.1.0|
|vscode-dotnet-runtime|ms-dotnettools|1.0.0|
|vscode-icons|vscode-icons-team|11.1.0|
|vscode-logicapps|ms-azuretools|1.0.2|
</details>

Problem description
----

I hope the two attached animations make the point: I cannot debug an Azure Function in VS Code. As you can see, it's possible to do so in pwsh consoles. If there's a setting that enables a regular debugging session in VS Code, I can't find it so I am reporting this as a bug. I hope it's a user error (caused by pitiful doc) and not one of those "You just can't do it in VS Code" issues that seem to plague the PowerShell environment in VS Code.

_Debugging in a pair of consoles (works)_:

![2021-01-18_16-17-17 (1)](https://user-images.githubusercontent.com/14332263/104967819-4e70d400-59b2-11eb-90b2-458ce5df0ee0.gif)

_Debugging in VS Code (no input possible)_:

![2021-01-18_15-57-26 (1)](https://user-images.githubusercontent.com/14332263/104968385-a22fed00-59b3-11eb-8ae5-d251f879ce99.gif)

**Comment by SydneyhSmith** [comment]
Thanks @yobyot it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)! Thanks for providing the GIFs and description those are great!

**Comment by yobyot** [comment]
@SydneyhSmith 

Hi. I've sent a .zip of the requested logs to vscode-powershell@microsoft.com.

**Comment by yobyot** [comment]
FWIW, here's a screenshot from a virgin Windows 10 machine, running pwsh 7.1.1, latest pwsh extension and Core Tools running the default Azure Functions HTTP project with a breakpoint set. This VM is in a client environment completely separate from the macOS environment from which I first reported this problem.

It's been, literally, years and years now that the PowerShell extension hasn't played nice with the VS Code debugger. I've reporting only a few of the issues I've experienced, all of which either were closed with pointed fingers elsewhere or were "wait for us to rearchitect." It makes one long for the ISE -- however limited it was, it was reliable. I just don't understand how PowerShell developers can be expected to depend on this extension, which is still labelled "preview" (and not to be confused with the "preview, preview" version of the extension).

<img width="1636" alt="2021-01-21_15-47-16" src="https://user-images.githubusercontent.com/14332263/105410971-c2a0b700-5c00-11eb-87d0-06300d3eb977.png">

If I'm doing something wrong, I'd be happy to fix it -- providing it's documented. As it is, the [paragraph or two](https://docs.microsoft.com/en-us/azure/azure-functions/functions-debug-powershell-local#debug-in-visual-studio-code) on debugging a function in VS Code is embarrassingly thin.

**Comment by SydneyhSmith** [comment]
Thanks @yobyot for all the detailed information, we really appreciate it. Unfortunately, this will take more investigation on our part--thanks for your patience!

**Comment by yobyot** [comment]
Hello, pwshTeam.

Any update on this issue? A workaround? _Anything?_

It's so hard to write an Az Function using the command line debugger.

Thanks.

**Comment by andschwa** [comment]
Can you confirm it's not working in the same manner with the latest release? We switched to use the Debug Adapter Protocol in February. On that note, the debugger is actually getting rewired (again, but it's necessary) as part of https://github.com/PowerShell/PowerShellEditorServices/issues/1295

**Comment by yobyot** [comment]
Confirmed. Exactly the same problem.

**Comment by andschwa** [comment]
Dang, well, we're actively fixing some threading issues in https://github.com/PowerShell/PowerShellEditorServices/issues/1295 which will also change the underlying debugger implementation quite a bit, perhaps it'll be fixed then.

**Comment by yobyot** [comment]
*Perhaps*? _Maybe_? **_Possibly_**? That's not especially comforting -- especially when this Azure Functions PowerShell support is GA and debugging a function *has never worked correctly.* Isn't anyone at Microsoft embarrassed that one cannot accurately and conveniently debug PowerShell Azure Functions? (Even a local PowerShell script debug session isn't all that reliable, either.)

Sorry to be a pain but the agony inflicted on PowerShell developers by never really completely replacing the ISE has gone on too long.

**Comment by andschwa** [comment]
We're working on it!

**Comment by yobyot** [comment]
Hello, is this problem being worked on as part of https://github.com/PowerShell/vscode-powershell/projects/9?

**Comment by andschwa** [comment]
Yes @yobyot! And it's under review, @rjmholt has made excellent progress.

**Comment by CallumCrowley** [comment]
Is there an update on this?

**Comment by andschwa** [comment]
@CallumCrowley the previously mentioned work has been long since merged and we've been stabilizing it. Can you please test the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) and let me know if this is resolved?

**Comment by yobyot** [comment]
Preview extension didn’t work for me.

**Comment by andschwa** [comment]
Oh, _oh_, I see you are trying to use attach to runspace. This is almost fixed! @SeeminglyScience has been hard at work on it and https://github.com/PowerShell/PowerShellEditorServices/pull/1752 is under review!

**Comment by CallumCrowley** [comment]
> @CallumCrowley the previously mentioned work has been long since merged and we've been stabilizing it. Can you please test the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) and let me know if this is resolved?

Great, I'll give it a go! 😊

**Comment by CallumCrowley** [comment]
@andschwa great! I'll give it a go 😊

**Comment by yobyot** [comment]
Let's pause for a moment and remind ourselves that GA of Azure Functions support for PowerShell was [announced](https://azure.microsoft.com/en-us/updates/powershell-support-in-azure-functions-is-now-generally-available/) in November of **_2019_**.

In the nearly three year since, nobody AFAIK has ever been able to use VS Code to write and debug a Function. Since the ISE is long dead, in essence that means _nobody has been able to write a Function in PowerShell suitable for production deployment_.

Yes, I'm being critical of the PowerShell team here for their lack of understanding the requirements of production-quality code in their product and in the customers' environments. And, yes, they had every excuse in the book ready: we don't have people, this requires a re-write, and on and on.

As a PowerShell fan, this is a tragedy.

**Comment by JustinGrote** [comment]
@yobyot good news! The latest preview 2022.4.1 when it releases should have fixed this finally. It was a very difficult bug to remediate.

![image](https://user-images.githubusercontent.com/15258962/163893318-cd8eff84-d24d-4626-867e-bb8cfa14705c.png)

**Comment by yobyot** [comment]
_Preview_? What I care about is GA code. My client that does not permit public preview tools or resources.

**Comment by JustinGrote** [comment]
@yobyot this latest preview is a release candidate, it's expected to make it to stable in the next few weeks!

**Comment by andschwa** [comment]
> _Preview_? What I care about is GA code. My client that does not permit public preview tools or resources.

@yobyot things take time! Please be patient, there was a _ton_ that went into fixing this, and it _is_ fixed now. Please test the preview extension (if you cannot do so for work, test it in another environment).

**Comment by CallumCrowley** [comment]
@JustinGrote @andschwa thanks for your work on this! 😄

**Comment by andschwa** [comment]
It was @SeeminglyScience that fixed it!
