### ISSUE TITLE
Support environment variables in powerShellAdditionalExePaths

### ISSUE THREAD

**Issue by PunkIslamist** [PowerShell/vscode-powershell#3145]
**Summary of the new feature**

As a user I want to use variables like `${env:HOME}` when setting paths so that I can reuse my settings across different PCs.
My use case: I have PowerShell Core installed via scoop. This places it under my user directory. I also sync my settings.json between different PCs where I use different user names, so the absolute path is different. But the relative path would be the same, starting from the home dir.

**Proposed technical implementation details (optional)**

The setting `terminal.integrated.shell.windows` already allows to use `${env:HOME}` so maybe it is possible to reuse its logic.
The variables feature itself is documented here: https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables

**Comment by andschwa** [comment]
Unfortunately, extension-contributed settings such as this explicitly don't support VS Code built-in variables (including the `env:` scope) as the APIs aren't available to us per https://github.com/microsoft/vscode/issues/46471. It would be great, but to do it reliably we need that support upstream from VS Code.
