### ISSUE TITLE
[ValidatePattern()] regex breaks SyntaxHighlighting

### ISSUE THREAD

**Issue by OCram85** [PowerShell/vscode-powershell#315]
### System Details

- Operating system name and version: `Win 7 Prof 64Bit`
- VS Code version: `1.5.3`
- PowerShell extension version: `0.7.2`
- Output from `$PSVersionTable`:
``` 
Name                           Value                                                                                                   
----                           -----                                                                                                   
PSVersion                      5.0.10586.117                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                 
BuildVersion                   10.0.10586.117                                                                                          
CLRVersion                     4.0.30319.42000                                                                                         
WSManStackVersion              3.0                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                     
SerializationVersion           1.1.0.1 
```

### Issue Description

I noticed a syntax highlight issue while using regex in `[ValidatePattern()]`. 
#### Example1:
![2016-10-11 08_24_43-invoke-2fausersync ps1 - visual studio code](https://cloud.githubusercontent.com/assets/13993700/19260724/4bf892f2-8f8c-11e6-868f-0e3eebdf3e59.png)
#### Example2:
![2016-10-11 08_15_56-invoke-2fausersync ps1 - visual studio code](https://cloud.githubusercontent.com/assets/13993700/19260655/99171316-8f8b-11e6-9414-de977462ebad.png)

**Comment by rkeithhill** [comment]
Syntax highlighting is done by a different project.  Can you submit this bug on that project?  https://github.com/powershell/editorsyntax

**Comment by OCram85** [comment]
Sure! Thanks for your advice...
https://github.com/PowerShell/EditorSyntax/issues/26

**Comment by daviwil** [comment]
Thanks Marco!  Closing this issue since you filed it over on the EditorSyntax repo.
