### ISSUE TITLE
Setting $ErrorActionPreference = Stop doesn't work

### ISSUE THREAD

**Issue by TPMartin** [PowerShell/vscode-powershell#3164]
- Operating system name and version - Windows 10 Enterprise x64 
- VS Code version - 1.52.1
- PowerShell extension version - v2020.6.0

### Issue Description

When I define ErrorActionPreference = Stop at the top of a script, then debug the script, the commands do not use the ErrorActionPreference

`$ErrorActionPreference = Stop

try { 
$service = Get-Service -DisplayName 'VSCodeTestService'
}
catch {
Write-Host "Service does not exist"
}`

with that script, as there is no service with that name it should throw an error, which should be caught by the catch because of the ErrorActionPreference, but the error is still thrown in the terminal

#### Expected Behaviour

Commands that would normally throw and continue should throw and stop

#### Actual Behaviour

Commands just throw the error and continue

**Comment by mklement0** [comment]
Change `$ErrorActionPreference = Stop` to `$ErrorActionPreference = 'Stop'`.

With the former (lack of quoting), the assignment itself fails, because `Stop` is interpreted _as a command to trun_.

**Comment by TPMartin** [comment]
Thats sorted it, thanks!
