### ISSUE TITLE
PSScriptAnalyzer problems don't refresh without opening the file

### ISSUE THREAD

**Issue by revolter** [PowerShell/vscode-powershell#3169]
Issue Description
=====

I am experiencing a problem with problems not refreshing without opening the file.

Steps to reproduce
=====

1. Enable the PSScriptAnalyzer setting.
2. Have a PowerShell script with at least one problem.

Current behaviour
=====

The problem doesn't appear in the `Problems` view. If you open the script, it does show up.

Expected behaviour
=====

The problem should appear automatically in the `Problems` view.

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Darwin x64 20.3.0 |
| VSCode | 1.53.0|
| PowerShell Extension Version | 2020.6.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.1|
|PSEdition|Core|
|GitCommitId|7.1.1|
|OS|Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021, root:xnu-7195.81.3~1/RELEASE_X86_64|
|Platform|Unix|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.1|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|1.2.0|
|platformio-ide|platformio|2.2.1|
|powershell|ms-vscode|2020.6.0|
|prettier-vscode|esbenp|5.9.1|
|remote-containers|ms-vscode-remote|0.158.0|
|vetur|octref|0.32.0|
|vscode-docker|ms-azuretools|1.9.1|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|
|vsliveshare|ms-vsliveshare|1.0.3629|

</details>

Moved from https://github.com/microsoft/vscode/issues/115989.

**Comment by SydneyhSmith** [comment]
Thanks @revolter, today PSScriptAnalyzer only runs when a file is opened by design, partially because of the expensive nature of running the analysis

**Comment by revolter** [comment]
I see. Kinda makes sense 🤔
