### ISSUE TITLE
 New-EditorFile FileName.ps1 fails with Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred. (Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.)"

### ISSUE THREAD

**Issue by AlejoSQL** [PowerShell/vscode-powershell#3180]
### System Details

System Details Output
```
PowerShell extension for Azure Data Studio fails when creating a new file. 


Azure data studio Version: 1.25.3 (user setup)
Commit: b277eafb8f5328ea26c6edfddd1999292ac27937
Date: 2021-02-09T23:10:35.151Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

### Issue Description

I am experiencing a problem with...

Trying to create a new ps file from within Azure data studio

#### Expected Behaviour

-- Create a file :)

#### Actual Behaviour

-- Error thrown 

.azuredatastudio\extensions\microsoft.powershell-2020.4.0\modules\PowerShellEditorServices\Commands\Public\CmdletInterface.ps1:128:9
    $editorContext = $psEditor.GetEditorContext()

Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred. (Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.)"

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by corbob** [comment]
🤔 I didn't even know about this command 🤷‍♂️ 

However, I can reproduce this in preview extension 2020.9.0 and vscode insiders.

**Comment by corbob** [comment]
Well this is fun...

I ran `Set-PSBreakpoint -Command New-EditorFile`, stepped through the code and investigated the `$pseditor` object, then couldn't reproduce the error... Now I can't reproduce it at all under either Windows PowerShell or PowerShell 7 🤦‍♂️
