### ISSUE TITLE
Integrated console not responding....

### ISSUE THREAD

**Issue by MHacker9404** [PowerShell/vscode-powershell#3190]
Issue Description
=====

I am experiencing a problem with...the integrated console not responding

Attached Logs
![image](https://user-images.githubusercontent.com/4184348/108510839-02ed6680-728d-11eb-9847-c99ca1edd7d9.png)

=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19042 |
| VSCode | 1.53.2|
| PowerShell Extension Version | 2020.9.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.2|
|PSEdition|Core|
|GitCommitId|7.1.2|
|OS|Microsoft Windows 10.0.19042|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.2|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|abracadabra|nicoespeon|4.13.1|
|Angular-BeastCode|Mikael|10.0.3|
|angular-console|nrwl|16.0.2|
|aws-toolkit-vscode|amazonwebservices|1.20.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|code-runner|formulahendry|0.11.2|
|debugger-for-chrome|msjsdiag|4.12.12|
|debugger-for-edge|msjsdiag|1.0.15|
|git-autoconfig|shyykoserhiy|0.0.2|
|git-graph|mhutchie|1.28.0|
|git-merger|shaharkazaz|0.4.1|
|gitblame|waderyan|6.0.2|
|gitflow|vector-of-bool|1.2.1|
|githistory|donjayamanne|0.6.14|
|gitignore|codezombiech|0.6.0|
|gitlens|eamodio|11.2.1|
|god|basarat|0.0.99|
|indent-rainbow|oderwat|7.5.0|
|markdown-all-in-one|yzhang|3.4.0|
|material-icon-theme|PKief|4.5.0|
|mongodb-vscode|mongodb|0.4.2|
|ng-template|Angular|11.2.2|
|npm-intellisense|christian-kohler|1.3.1|
|open-in-browser|techer|2.0.0|
|powershell-preview|ms-vscode|2020.9.0|
|prettier-vscode|esbenp|5.9.2|
|remote-containers|ms-vscode-remote|0.158.0|
|remote-wsl|ms-vscode-remote|0.53.4|
|render-crlf|medo64|1.5.17|
|vim|vscodevim|1.18.9|
|vs-code-prettier-eslint|rvest|0.4.1|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.1.2|
|vsc-material-theme-icons|equinusocio|1.2.2|
|vscode-commitizen|KnisterPeter|0.12.1|
|vscode-docker|ms-azuretools|1.10.0|
|vscode-edge-devtools|ms-edgedevtools|1.1.3|
|vscode-eslint|dbaeumer|2.1.14|
|vscode-firefox-debug|firefox-devtools|2.9.1|
|vscode-git-tags|howardzuo|1.4.4|
|vscode-jest-runner|firsttris|0.4.31|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.0|
|vscode-npm-script|eg2|0.3.16|
|vscode-print|pdconsec|0.8.3|
|vscode-profile-switcher|aaronpowell|0.3.3|
|vscode-relative-line-numbers|extr0py|0.0.5|
|vscode-sort-json|richie5um2|1.19.2|
|vscode-stylelint|stylelint|0.86.0|
|vscode-view-in-browser|koppt|1.0.5|
|vscode-yaml|redhat|0.15.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.11|

**Comment by JustinGrote** [comment]
Do you have a custom profile? It looks like it might be getting stuck loading that.

If you can provide a log dump it'd be easier to find out exactly.

**Comment by MHacker9404** [comment]
here you go...BTW - i'm using windows terminal...
[settings.json.txt](https://github.com/PowerShell/vscode-powershell/files/6015582/settings.json.txt)
[powershell-extension-log.pdf](https://github.com/PowerShell/vscode-powershell/files/6015583/powershell-extension-log.pdf)
[powershell-editor-services.pdf](https://github.com/PowerShell/vscode-powershell/files/6015584/powershell-editor-services.pdf)

**Comment by JustinGrote** [comment]
@MHacker9404 PSES shows a config error, you may also want to check your omnisharp logs, and try it with Powershell 5.1 instead of 7 since you've specified a custom 7 path for your terminal.

I can't reproduce personally, works fine for me :). Try it on a new profile or make a separate test local user account and see if it works there? If so it's something probably with your config or profile state.
