### ISSUE TITLE
New-EditorFile posts input to currently open editor

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/vscode-powershell#3192]
Issue Type: <b>Bug</b>

Have an editor open, with some content, and for ease, place cursor at begining of the document, with it visible.

Execute `"contents" | New-EditorFile "somefile"`

You will find "contents" pasted at the cursor in the currently opened document, but will be switched to a new editor with a blank document.  (Note, if some text was selected in the current document, it will be replaced by the pasted text meant for the new document.)

Extension version: 2020.6.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.81GB free)|
|Process Argv|--crash-reporter-id b4df00f3-aa06-4238-a0b4-aaf53730304f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by msftrncs** [comment]
I thought I was running PowerShell Preview extension, but for some reason the preview extension was disabled ...  switched to the preview extension, version 2020.9.0 and the issue occurs exactly the same.

**Comment by SydneyhSmith** [comment]
Thanks @msftrncs we are able to reproduce this issue.
