### ISSUE TITLE
Wire up ILogger implementation through LanguageClient

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#320]
I'd like to get the logs of the `LanguageClient` class to show up in our new logging infrastructure but the `LanguageClient` class currently doesn't accept an `ILogger` parameter.  Since upgrading the `vscode-languageclient` class might wreak havoc on our protocol implementation, I'm deferring this task until I have time to reconcile any protocol changes that would come from upgrading after the `ILogger` parameter has been added to their code.

**Comment by rjmholt** [comment]
Closing as defunct
