### ISSUE TITLE
Add "debug.saveBeforeStart": "none" to ISE Mode/for PowerShell files in general

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#3200]
**Summary of the new feature**

Last stable vscode, we introduced a "feature" that would prompt you to save an untitled file before debugging it. This is because most debug adapters don't support debugging untitled files... But PowerShell does!

A setting was added in insiders to control this behavior now so Untitled PowerShell files are now debuggable again. 

More info: https://github.com/microsoft/vscode/issues/114890

**Proposed technical implementation details (optional)**

At a minimum, I think this setting should be added to ISE Mode. Users will expect F5 to run their script, even if it's not saved on disk, and ISE Mode was made for the beginner in mind.

Additionally, consider adding the following setting to the user's setting on start up/install:

```
"[powershell]" : {
    "debug.saveBeforeStart": "none";
}
```

Which will only apply this setting to PowerShell files.

**Comment by SydneyhSmith** [comment]
Thanks for the update @TylerLeonhardt! We will update this for ISE mode.

**Comment by andschwa** [comment]
Fixed with #3357.
