### ISSUE TITLE
 error `(command 'PowerShell.EnableNotebookMode' not found)` (in Preview on Insiders)

### ISSUE THREAD

**Issue by fbehrens** [PowerShell/vscode-powershell#3209]
Hi,

just want to try out Powershell Notebook Style again, and got the following error I report hereby:

When I run the command `PowerShell: (Preview) Enable Notebook Mode`

it resulted in an error `(command 'PowerShell.EnableNotebookMode' not found)`

### System Details

```
### VSCode version: 1.54.0-insider 3290f9a73ba6fc3b1063ea32476067434ee91b1d x64

### VSCode extensions:
ms-vscode.powershell-preview@2021.2.1


### PSES version: 2.3.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by andschwa** [comment]
Hi @fbehrens. We removed the PowerShell notebook mode in #3176; however, I missed a few things (such as the listing of the command itself). I will get the rest removed for the next release so this confusion is resolved. Thanks for the report!

**Comment by corbob** [comment]
FWIW: The [.NET Interactive Notebooks](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode) extension has a PowerShell kernel you can use so you can get notebooks with that extension. Not sure how full featured they are though.
