### ISSUE TITLE
Extension overrides other theme color settings

### ISSUE THREAD

**Issue by timothyscottsmith** [PowerShell/vscode-powershell#3215]
It seems that the addition of the semantic highlighting is overriding theme preferences. In the attached example, you can see that parameters and function names are given color, when previously they were not (something I preferred). Is here a way to disable this feature? This extension was not set as my primary theme.

![2021-02-28 20_30_58-Test ps1 - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/46531580/109442021-fbecf380-7a04-11eb-82ee-ca52a8859f2a.png)
![2021-02-28 20_30_08-Test ps1 - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/46531580/109442025-fc858a00-7a04-11eb-8511-21b8ec8af05b.png)

**Comment by timothyscottsmith** [comment]
Closing, found the setting to be per theme. Once they opt-in to allowing semantic highlighting, users can disable. Sorry, I was not able to immediately find this information.

`    "editor.semanticTokenColorCustomizations": {
        "[One Dark Pro]": {
            "enabled": false
        }
    }`

**Comment by rjmholt** [comment]
Thanks for following up @timothyscottsmith, and no need to apologise. This information may help other users
