### ISSUE TITLE
Default dark color scheme is broken

### ISSUE THREAD

**Issue by GreatTeacherBasshead** [PowerShell/vscode-powershell#3220]
### Environment

- Editor: VS Code
- Version: 1.53.2 (system setup)
- Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
- Date: 2021-02-11T11:48:04.245Z
- Electron: 11.2.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT x64 10.0.19041
- Your primary theme: Dark+ (default dark)

### Issue Description

After enabling `ms-vscode.powershell` extension the default dark color scheme shows different (not as good) colors.
When I disable the extension it works as expected.
Also when I execute `Restart current [PowerShell] session`, while its restarting it shows expected colors. Once restarted, the colors are "broken" again.

#### Screenshots

![expected](https://user-images.githubusercontent.com/5768845/109793546-11d10300-7c15-11eb-8475-accad45a910c.png)
![actual](https://user-images.githubusercontent.com/5768845/109793502-04b41400-7c15-11eb-89d8-2ca7244ce9bd.png)

### Expected Behavior

`-Path` displayed in `white` color.
`$destination` displayed in `blue` color.

### Actual Behavior

`-Path` displayed in `blue` color.
`$destination` displayed in `blue` color.

### Code Samples

```PowerShell
New-Item -Path $destination
```

**Comment by peetrike** [comment]
As a workaround, You can add next section to settings.json

```js
  "editor.semanticTokenColorCustomizations": {
    "[Default Dark+]": {
      "rules": {
          // make it different from variable
        "parameter": "#d4d4d4"
      }
    }
  },
```
