### ISSUE TITLE
Version v2021.2.2 syntax highlighting is "poor" compared to previous version

### ISSUE THREAD

**Issue by LuluTchab** [PowerShell/vscode-powershell#3221]
### Environment

- Editor and Version (VS Code, Atom, Sublime): VSCode 1.53.2
- Your primary theme: dark (default)

### Issue Description

Since the new extension for PowerShell was installed, the highliting became very "poor". Almost everything is now in blue and before there was white and yellow. Now, it's difficult to identify things... it's impossible to see when a function is called on an object and also when we access an object member. And it's also difficult to identify function parameter tags... 

#### Screenshots

![image](https://user-images.githubusercontent.com/11942430/109797617-fb797600-7c19-11eb-853a-922c9e429225.png)

### Expected Behavior

Previous version of the extension
![image](https://user-images.githubusercontent.com/11942430/109797667-0b915580-7c1a-11eb-838b-e5edc4f8bd98.png)

### Code Samples

Here's the code that is on the screenshots

```PowerShell
# Création d'une connexion au serveur vRA pour accéder à ses API REST
	$logHistory.addLineAndDisplay("Connecting to vRA...")
	$vra = [vRAAPI]::new($configVra.getConfigValue(@($targetEnv, "infra", "server")),
						 $targetTenant, 
						 $configVra.getConfigValue(@($targetEnv, "infra", $targetTenant, "user")),
						 $configVra.getConfigValue(@($targetEnv, "infra", $targetTenant, "password")))

    # Parcours de la liste des BG
    Foreach ($bg in $vra.getBGList() )
    {
        $logHistory.addLineAndDisplay(("Processing BG '{0}'..." -f $bg.name))

        $logHistory.addLineAndDisplay("> Getting VM List...")   

        $vmList = $vra.getBGItemList($bg, "Virtual Machine")

        $logHistory.addLineAndDisplay(("> {0} VMs found" -f $vmList.count))

        Foreach($vm in $vmList)
        {
            $logHistory.addLineAndDisplay((">> Processing VM '{0}'..." -f $vm.name))

			if(((getvRAObjectCustomPropValue -object $vm -customPropName $global:VRA_CUSTOM_PROP_VRA_BG_NAME) -ne $bg.name) -or 
				((getvRAObjectCustomPropValue -object $vm -customPropName $global:VRA_CUSTOM_PROP_VRA_TENANT_NAME) -ne $targetTenant))
			{
				$logHistory.addLineAndDisplay("Values need to be updated")
			}

        }

    }

```

**Comment by ParkHost** [comment]
Please revert the previous syntax highlighting back or at least let us choose between the 2, after the update my code isn't readable. I tried all different kind of theme's but they are all broken now.

**Comment by PrzemyslawKlys** [comment]
You can disable it:

```
    "editor.semanticHighlighting.enabled": false,
```

**Comment by SydneyhSmith** [comment]
Thanks we will use this as the meta-issue for Semantic highlighting

**Comment by metablaster** [comment]
Hello, I'll just post my question posted in wrong place, current behavior is... AHH
https://stackoverflow.com/questions/66890420/changed-powershell-extension-syntax-highlighting-in-vs-code

**Comment by MMAgeek** [comment]
It would be nice to be able disable semantic highlighting for PowerShell only. Right now I had to disable it as l dont like the way it displayed PowerShell code, but then every time I switch to JavaScript or another language I have to turn it back on. Its annoying to have to keep doing this.

**Comment by PrzemyslawKlys** [comment]
You can...


```

"[powershell]": {
    "editor.semanticHighlighting.enabled": false
}

```

**Comment by ParkHost** [comment]
> 
> 
> You can...
> 
> ```
> 
> "[powershell]": {
>     "editor.semanticHighlighting.enabled": false
> }
> ```

beautiful, thanks!

**Comment by andschwa** [comment]
Uh, we pinned this as the meta issue. Re-opening...

**Comment by ninmonkey** [comment]
[Here's a solution without disabling `semantic highlighting`](https://gist.github.com/ninmonkey/536ccc5cfaac4445cc7095d1bfafb2fb)

I copied @LuluTchab 's screenshot for a comparison. I'm getting the diversity of the original. I'm using `Dark+`
![image](https://user-images.githubusercontent.com/3892031/114322182-62752f00-9ae4-11eb-8780-72b33eb70e6c.png)

If you're using a different theme, you can fix it:
```json
    "editor.semanticTokenColorCustomizations": {
        // per-theme
        "[Default Dark+]": {
            "enabled": true,
            "rules": {
                "parameter": "#d4d4d4",
        }
    },
```

## How to find token names

Run this command:
![image](https://user-images.githubusercontent.com/3892031/114322399-9e5cc400-9ae5-11eb-937c-07ffb84c57ed.png)


The token inspector will give you `textmate scopes` and `semantic tokens`

![image](https://user-images.githubusercontent.com/3892031/114322334-46be5880-9ae5-11eb-87bf-aee1675cd56e.png)

![attach](https://user-images.githubusercontent.com/3892031/114322368-79685100-9ae5-11eb-943f-2fbdabd1f7c3.gif)
