### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by APA2527** [PowerShell/vscode-powershell#3223]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2021.2.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rjmholt** [comment]
Unfortunately there's not enough information here to determine what problem you might be experiencing. If you're able to provide more information, we can reopen this issue to help you
