### ISSUE TITLE
PowerShell update checker ignores `POWERSHELL_UPDATECHECK` environment variable

### ISSUE THREAD

**Issue by trolleyboy** [PowerShell/vscode-powershell#3226]
### System Details

System Details Output
```
### VSCode version: 1.53.2 622cb03f7e070a9670c94bae1a45d78d7181fbd4 x64

### VSCode extensions:
azsdktm.SecurityIntelliSense@0.8.0     
AzurePolicy.azurepolicyextension@0.1.1 
DotJoshJohnson.xml@2.5.1
eamodio.gitlens@11.2.1
everettjf.filter-line@2.0.1
jinsihou.diff-tool@0.0.1
ms-azure-devops.azure-pipelines@1.183.0
ms-azuretools.vscode-azureappservice@0.21.0
ms-azuretools.vscode-azureresourcegroups@0.3.0
ms-dotnettools.vscode-dotnet-runtime@1.0.0
ms-vscode.azure-account@0.9.6
ms-vscode.powershell@2021.2.2
msazurermtools.azurerm-vscode-tools@0.14.1
ryu1kn.text-marker@1.11.0
Summer.azure-event-hub-explorer@0.1.2


### PSES version: 2.3.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.5
PSEdition                      Core
GitCommitId                    7.0.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am experiencing a problem with...
VS Code notifies as follows...
```
You have an old version of PowerShell (7.0.5). The current latest release is v7.1.2. Would you like to update the version? (This will close ALL pwsh terminals running in this Visual Studio Code session)
```
However I have set $Env:POWERSHELL_UPDATECHECK to "LTS" per https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-70?view=powershell-7.1#new-version-notification

#### Expected Behaviour

I'd expect the notification to only appear when updates to the LTS version of Powershell 7 are available. EG: 7.0.6.

#### Actual Behaviour

VS Code notifies as follows...
```
You have an old version of PowerShell (7.0.5). The current latest release is v7.1.2. Would you like to update the version? (This will close ALL pwsh terminals running in this Visual Studio Code session)
```

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs
[vscode-powershell.zip](https://github.com/PowerShell/vscode-powershell/files/6087283/vscode-powershell.zip)
[vscode-powershell.zip](https://github.com/PowerShell/vscode-powershell/files/6087288/vscode-powershell.zip)

)
about capturing and sending logs.

**Comment by rjmholt** [comment]
Do you get the update notification when you start `pwsh.exe` with that environment variable set?

**Comment by trolleyboy** [comment]
No, it only seems to occur when the Powershell Integrated Console in VS Code starts up (which is every time I start VS Code). 
I can see that pwsh is started first, but no notification. Then the integrated console is started and the notification appears. 

I was getting this notification in pwsh.exe before I set the environment variable a few weeks ago.

**Comment by rjmholt** [comment]
How/where are you setting the environment variable?

**Comment by trolleyboy** [comment]
I have it set as a System variable (I vaguely recall running `$Env:POWERSHELL_UPDATECHECK = 'LTS'` in an elevated PS console). 

![image](https://user-images.githubusercontent.com/44885244/110061257-2e636b80-7dcc-11eb-9bd2-5b9ca2638a50.png)

**Comment by Liturgist** [comment]
I am experiencing the same issue. VSCode tells me that the current latest release is v7.2.0. It does not mention that it is the preview version, rc1. It really should.

https://github.com/PowerShell/PowerShell/releases/download/v7.2.0-rc.1/PowerShell-7.2.0-rc.1-win-x64.msi

![image](https://user-images.githubusercontent.com/2530958/140793245-7dbc1388-0263-4db1-9677-0e400328068d.png)

```
PS C:\Users\pwatson2> code --version
1.61.2
6cba118ac49a1b88332f312a8f67186f7f3c1643
x64
PS C:\Users\pwatson2> code --list-extensions --show-versions | Select-String -Pattern powershell

ms-vscode.powershell@2021.10.2
ms-vscode.powershell-preview@2021.11.0

PS C:\Users\pwatson2> $PSVersionTable                          

Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by JustinGrote** [comment]
@Liturgist 7.2 is an LTS version, unless I'm missing something, this is as-expected. If it prompts you for 7.3.x when that chain starts, then there is a problem.

**Comment by andschwa** [comment]
I think this still might be misbehaving. Ideally if you're on an LTS it wouldn't prompt you to update to the "next LTS," just updates to your current LTS until it's out of support. Confirming now if the 7.2 update means 7.0 LTS Is no longer supported.

**Comment by andschwa** [comment]
Yeah, 7.0 LTS isn't end-of-life until [December 3, 2022](https://docs.microsoft.com/en-us/powershell/scripting/install/PowerShell-Support-Lifecycle?view=powershell-7.2#powershell-end-of-support-dates), so while 7.2 is _an_ LTS, in this case I do not think the update check should be prompting the user.

**Comment by andschwa** [comment]
Closer examination of this issue is that it is still a feature request for the editor to respect this variable. But I agree with @Liturgist that this is a bug in PowerShell's update checker.

**Comment by andschwa** [comment]
I almost filed a bug...but actually @Liturgist you're running a non-LTS, 7.1.5. So nevermind all I said! It is strange that the update is pointing you at an RC, I'm guessing this was a cache issue and it prompted you to update before the 7.2 release (non-RC) refreshed on GitHub.

**Comment by Liturgist** [comment]
> I almost filed a bug...but actually @Liturgist you're running a non-LTS, 7.1.5. So nevermind all I said! It is strange that the update is pointing you at an RC, I'm guessing this was a cache issue and it prompted you to update before the 7.2 release (non-RC) refreshed on GitHub.

@andschwa, what steps can I take to remove this "cache issue?"

**Comment by JustinGrote** [comment]
@andschwa so I agree the end-behavior (confirmed by tests) should be as such:
1. If you are on an LTS, do not prompt to update your LTS until it is 30 days to EOS or something (how would we know? More info in the Powershell repo metadata.json?)
2. If you are on non-LTS, prompt to always update to the latest, and if LTS is latest, then so be it.

**Comment by andschwa** [comment]
> @andschwa, what steps can I take to remove this "cache issue?"

It should be gone now!

**Comment by andschwa** [comment]
> (confirmed by tests)

Are you saying this is indeed working as intended @JustinGrote?

**Comment by JustinGrote** [comment]
No I'm saying we should have tests to confirm that if we fix it :)

**Comment by andschwa** [comment]
It took a while, but I got around to fixing this 😄
