### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by PrometheusRising1** [PowerShell/vscode-powershell#323]
On the extensions page at visual studio code, MS notes that you can download an extension for reuse from a share:
https://code.visualstudio.com/docs/editor/extension-gallery?pub=ms-vscode&ext=PowerShell

The format is as follows (reproduced from the above linked page):
https://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${extension name}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

When I go to your Marketplace page, I can get the publisher and version information, but cannot see the correct extension name:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell&showReviewDialog=true

Inserting "PowerShell" or "ms-vscode.PowerShell" into the URL yields an error:
{"$id":"1","innerException":null,"message":"The requested extension 'microsoft.ms-vscode.PowerShell' doesn't exist.","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionDoesNotExistException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"ExtensionDoesNotExistException","errorCode":0,"eventId":3000}

Please indicate the correct extension name for the purposes of using the download link.

**Comment by SydneyhSmith** [comment]
@PrometheusRising1 I am having trouble reproing this, maybe it has been fixed. Are you still running into this issue?

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
