### ISSUE TITLE
Watch not working when debugging

### ISSUE THREAD

**Issue by soulwiper** [PowerShell/vscode-powershell#3233]
### System Details

System Details Output
```

```

### Issue Description

I am experiencing a problem with the Watch when debugging in Visual Studio Code.  This behavior happens after version 2020.1.0 of the PowerShell extention.  Version 2020.1.0 works.

If there is any other information you need from me, other than what I am sharing below, please let me know. I am sharing so you can try to replicate the issue.

Visual Studio Code Info:
Version: 1.54.1 (system setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z (4 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

[OK] [Copy]

System Info:
OS Name Microsoft Windows 10 Enterprise
Version 10.0.19042 Build 19042
Other OS Description Not Available
OS Manufacturer Microsoft Corporation
System Name <Device name>
System Manufacturer LENOVO
System Model 20NQS07200
System Type x64-based PC
System SKU LENOVO_MT_20NQ_BU_Think_FM_ThinkPad X390 Yoga
Processor Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz, 1800 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date LENOVO N2LET82W (1.82 ), 10/29/2020
SMBIOS Version 3.1
Embedded Controller Version 1.19
BIOS Mode UEFI
BaseBoard Manufacturer LENOVO
BaseBoard Product 20NQS07200
BaseBoard Version SDK0L22696 WIN
Platform Role Mobile
Secure Boot State On
PCR7 Configuration Elevation Required to View
Windows Directory C:\WINDOWS
System Directory C:\WINDOWS\system32
Boot Device \Device\HarddiskVolume2
Locale United States
Hardware Abstraction Layer Version = "10.0.19041.844"
User Name <Username>
Time Zone Central Standard Time
Installed Physical Memory (RAM) 8.00 GB
Total Physical Memory 7.75 GB
Available Physical Memory 1.40 GB
Total Virtual Memory 24.1 GB
Available Virtual Memory 11.9 GB
Page File Space 16.4 GB
Page File C:\pagefile.sys
Kernel DMA Protection On
Virtualization-based security Not enabled
Device Encryption Support Elevation Required to View
Hyper-V - VM Monitor Mode Extensions Yes
Hyper-V - Second Level Address Translation Extensions Yes
Hyper-V - Virtualization Enabled in Firmware Yes
Hyper-V - Data Execution Protection Yes

#### Expected Behaviour

Watch variables and/or expressions need to update when stepping through you code.

#### Actual Behaviour

Nothing happens.  You can't add or delete watched and has "not available" when it should have a value.

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by andschwa** [comment]
@ebmarquez Can you please test v2021.11.0-preview and if it still repros, open a new issue?
