### ISSUE TITLE
I can't open the terminal in VSC.

### ISSUE THREAD

**Issue by Richard33333** [PowerShell/vscode-powershell#3239]
* Slack Community Chat: https://powershell.slack.com (you can sign-up at http://slack.poshcode.org/ for an invite)
* Gitter Chat: https://gitter.im/PowerShell/vscode-powershell

When I open the VSC and implement the terminal, the next error occur and I couldn't open it.
And also, I couldn't find the solution on the VSC web site regarding exit code : 4294901760
please somebody help me TT.
I'm a beginner of SW.

It is my first time and my operation conditions are below.
- OS : Window10(64bit)
- Installed SW : Python(2021.2.636928669), Python for VSCode(0.2.3), Python Extension Pack(1.6.0)

![image](https://user-images.githubusercontent.com/80504660/110896183-6aec1580-833e-11eb-88b6-04c3b8d156c8.png)

**Comment by andschwa** [comment]
Hi @Richard33333, could you run `winver` in the run dialog (Win+R) and tell me what version of Windows you're using? Try following the steps here: https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

> If you're on Windows 10 1809 (build 17763) or below, the issue is related to the legacy "winpty" backend. Upgrading to Windows 1903 (build 18362) will move you onto the new "conpty" backend that is built by Microsoft and could fix your problem.
