### ISSUE TITLE
PNP.Powershell and VS Code

### ISSUE THREAD

**Issue by baldieavenger** [PowerShell/vscode-powershell#3249]
Hi all,
Im having trouble using PNP.Powershell in VS code. I can open and connect in ISE easily enough but it seems to stall in Code when trying to run and connect using Connect-PnPOnline on its own and entering the URL when prompted, it should pop up a credential box, but doesnt. Using Connect-PnPOnline -Url https://domain-admin.sharepoint.com/ -Credentials $PNPLiveCred also behaves similarly that it does not and should not have a credential box pop up, but it just spins and never successfully connects where as ISE does.
How can I start to troubleshoot this? (Code newbie still!) 
Thanks!

**Comment by SydneyhSmith** [comment]
Thanks @baldieavenger It would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)...it would also be really great if you could also provide a GIF and/or screenshots...also worth checking to ensure  that the credential box does not appear behind the window...thanks!
