### ISSUE TITLE
Duplicate PSSA-entries in Problem-tab after reopening file

### ISSUE THREAD

**Issue by fflaten** [PowerShell/vscode-powershell#3252]
Issue Description
=====

Every time I open the same powershell-files, the same issues caught by the PSSA-integration are duplicated over and over in the Problems-tab in VSCode.

Steps to reproduce:
1. Open VSCode with vscode-powershell enabled in a new folder with the following files:

demo.ps1
```
$myVar = "foo"
```

PSScriptAnalyzerSettings.psd1
```
@{
    Severity = @('Error','Warning')
    IncludeDefaultRules = $true
}
```
2. Click on demo.ps1 and wait for the "variable never used"-problem
![image](https://user-images.githubusercontent.com/3436158/111907903-7a164600-8a57-11eb-924c-a664c85cbd7d.png)
3. Close the file-tab (or click on PSScriptAnalyzerSettings.ps1 so it replaces the demo.ps1 file tab) and then open demo.ps1 again. The problem will now be shown twice or as many times as you reopen it
![image](https://user-images.githubusercontent.com/3436158/111908007-d711fc00-8a57-11eb-8c0b-060c3b139bb2.png)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19042 |
| VSCode | 1.54.3|
| PowerShell Extension Version | 2021.2.2 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.1.3|
|PSEdition|Core|
|GitCommitId|7.1.3|
|OS|Microsoft Windows 10.0.19042|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0 7.1.3|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|powershell|ms-vscode|2021.2.2|

**Comment by SydneyhSmith** [comment]
Thanks @fflaten I can reproduce this
