### ISSUE TITLE
Function reference "bounces" upon typing

### ISSUE THREAD

**Issue by ChadMcCaffery** [PowerShell/vscode-powershell#3254]
https://user-images.githubusercontent.com/22089594/112020367-81882e80-8aed-11eb-9a4d-d82c3185f73c.mp4

Issue Type: <b>Bug</b>

1. Create a new PS1 script with a function
2. Notice '0 references' above the declaration
3. Keep typing and watch it "bounce" with each keypress

Extension version: 2021.2.1
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (20.75GB free)|
|Process Argv|--folder-uri file:///d%3A/repo/Imaging/PhysicalDeviceImaging --crash-reporter-id 5e7fed8b-d57d-47d5-b701-62d0c82bb2ea|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by andschwa** [comment]
Does this happen in other language modes too?

**Comment by ChadMcCaffery** [comment]
I haven't been able to repro in other languages because I don't have 'references' link above any functions.
I've tried C++, C#, and TypeScript projects.

**Comment by andschwa** [comment]
I don't believe our extension does anything with the actual rendering of those "references," it just supplies the count to the editor. If you install the C# extension with id `ms-dotnettools.csharp` you should get the same "references" above functions and methods in C# code.

**Comment by ChadMcCaffery** [comment]
I agree the issue is more likely with VS Code or Electron, but thought I'd start here since I was in PowerShell at the time.

The issue does not repro in our team's C# project.

Well, it's a new day. I can no longer repro the issue in my PowerShell project either. 😏
I turn off my machine overnight, so perhaps it was a weird interaction with the graphics driver on my machine.

I'm closing this for now.
