### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by gillug** [PowerShell/vscode-powershell#3258]
- Issue Type: `Bug`
- Extension Name: `powershell`
- Extension Version: `2021.2.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by andschwa** [comment]
Hi, this bug has no report. Can you please provide more details? Thanks!
