### ISSUE TITLE
Powershell last statement output not seen

### ISSUE THREAD

**Issue by weinand** [PowerShell/vscode-powershell#326]
_From @jbruns2015 on October 25, 2016 17:21_

- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: ms-vscode.PowerShell-0.7.2

Steps to Reproduce:

This shows me '1' in debug console
$a = 1
Write-Host $a
Exit

This shows me nothing in debug console
$a = 1
Write-Host $a

_Copied from original issue: Microsoft/vscode#14458_

**Comment by weinand** [comment]
_From @jbruns2015 on October 25, 2016 17:32_

If I do not use breakpoints and run this:

$a = 1
Write-Host $a
Exit

I don't see the '1' in the Output console or the Debug Console.

**Comment by daviwil** [comment]
Hey @jbruns2015, this is a known issue with the PowerShell extension, see issue #284 for more information.  I'm hoping to have this issue resolved for the next release.

Thanks @weinand for passing the issue along!

**Comment by jbruns2015** [comment]
ETA on next release?

**Comment by daviwil** [comment]
The ETA keeps shifting gradually but for now I'm *hoping* it'll happen the second week of November.  Lots of things going on between now and then so it's hard to say for sure.
