### ISSUE TITLE
Powershell extension should not be noisy when it activates

### ISSUE THREAD

**Issue by connor4312** [PowerShell/vscode-powershell#3266]
### System Details

- Operating system: Win 10
- VS Code version: 1.55 Insiders
- PowerShell extension: 2021.2.1

If you are running VSCode Insiders, use this expression instead (and paste the result inside the backticks):

System Details Output

<details>

```

### VSCode version: 1.55.0-insider c185983a683d14c396952dd432459097bc7f757f x64

### VSCode extensions:
adamhartford.vscode-base64@0.1.0
bierner.github-markdown-preview@0.0.2       
bierner.markdown-checkbox@0.1.3
bierner.markdown-emoji@0.1.0
bierner.markdown-preview-github-styles@0.1.6
bierner.markdown-yaml-preamble@0.0.4  
codezombiech.gitignore@0.6.0
connor4312.codesong@1.0.2
connor4312.css-theme-completions@0.0.4
dbaeumer.vscode-eslint@2.1.19
eamodio.gitlens-insiders@2021.3.2905  
eamodio.simple@0.0.1
eamodio.tsl-problem-matcher@0.4.0
earshinov.permute-lines@1.1.0
EditorConfig.EditorConfig@0.16.4
EFanZh.graphviz-preview@1.4.0
esbenp.prettier-vscode@6.3.1
gerane.Theme-Earthsong@0.0.5
GitHub.codespaces@0.9.1
GitHub.vscode-pull-request-github-insiders@2021.3.42303
golang.go@0.23.3
hbenl.vscode-mocha-test-adapter@2.10.2
hbenl.vscode-test-explorer@2.19.6
JakeBecker.elixir-ls@0.6.5
kavod-io.vscode-jest-test-adapter@0.8.0
mjmlio.vscode-mjml@1.0.4
ms-azuretools.vscode-azurefunctions@1.3.0
ms-azuretools.vscode-azureresourcegroups@0.3.0
ms-azuretools.vscode-docker@1.11.0
MS-CEINTL.vscode-language-pack-es@1.55.1
MS-CEINTL.vscode-language-pack-zh-hans@1.55.1
ms-dotnettools.csharp@1.23.9
ms-dotnettools.dotnet-interactive-vscode@1.0.2180041
ms-dotnettools.vscode-dotnet-runtime@1.0.0
ms-dotnettools.vscode-dotnet-sdk@0.0.2
ms-edgedevtools.vscode-edge-devtools@1.1.6
ms-python.python@2021.3.680753044
ms-toolsai.jupyter@2021.5.702919634
ms-vscode-remote.remote-containers@0.166.0
ms-vscode-remote.remote-ssh@0.65.1
ms-vscode-remote.remote-ssh-edit@0.65.1
ms-vscode-remote.remote-ssh-edit-nightly@2021.3.36900
ms-vscode-remote.remote-ssh-nightly@2021.3.36900
ms-vscode-remote.remote-wsl@0.54.6
ms-vscode-remote.vscode-remote-extensionpack@0.20.0
ms-vscode.azure-account@0.9.7
ms-vscode.cpptools@1.2.2
ms-vscode.hexeditor@1.4.0
ms-vscode.js-debug@1.55.1
ms-vscode.js-debug-companion@1.0.9
ms-vscode.js-debug-nightly@2021.3.2417
ms-vscode.powershell-preview@2021.2.1
ms-vscode.vscode-github-issue-notebooks@0.0.75
ms-vscode.vscode-js-profile-flame@0.0.14
ms-vscode.vscode-selfhost-test-provider@0.1.12
ms-vscode.wordcount@0.1.0
ms-vsliveshare.vsliveshare@1.0.4070
msazurermtools.azurerm-vscode-tools@0.15.0
msjsdiag.debugger-for-chrome@4.12.12
msjsdiag.debugger-for-edge@1.0.15
octref.vetur@0.33.1
redhat.vscode-yaml@0.17.0
ritwickdey.LiveServer@5.6.1
rust-lang.rust@0.7.8
silvenon.mdx@0.1.0
slevesque.shader@1.1.5
slevesque.vscode-autohotkey@0.2.2
Stephanvs.dot@0.0.1
Tyriar.lorem-ipsum@1.2.0
vscode.vscode-test-resolver@0.0.1
vsls-contrib.codetour@0.0.49
wmaurer.change-case@1.0.0
zxh404.vscode-proto3@0.5.3

### PSES version: 2.3.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

</details>

### Issue Description

1. With everything on its default settings, open a new empty folder
2. Do something that triggers activation. In my case: in Debug view, click `create a launch.json` file
3. The powershell extension opens a terminal on activation, which makes the quickpick disappear. It also gives a notification that I don't care about (because I'm not doing anything with powershell at the moment.)

#### Expected Behaviour

I don't want to be interrupted here. I want to use the powershell on certain projects and it should _never_ get in my way when I don't want it to. In this case I was going to debug a JavaScript project in a project that didn't have any `.ps1` files in the workspace/anything that would indicate I wanted to do something with powershell.

It also prompts me with a notification when this happens, which is again also quite annoying. One option would be for me to globally disable the extension and only re-enable it in select workspaces, or dig through the settings to figure out which ones to toggle in order to disable this behavior, but in this case I ended up uninstalling the extension since I do involved powershell work very rarely.

#### Actual Behaviour

Terminals and notifications pop up.

![recording](https://user-images.githubusercontent.com/2230985/113067576-69f61900-9171-11eb-8cee-3dbd7fc3044f.gif)

The gif doesn't capture it, but the configuration quickpick popped up briefly before the powershell terminal opening dismissed it.

**Comment by andschwa** [comment]
Thanks for the suggestion! Looks like you have a workaround for now. I agree we can make some improvements on the "noise" here.
