### ISSUE TITLE
support for dot source

### ISSUE THREAD

**Issue by chantisnake** [PowerShell/vscode-powershell#327]
When I dot source another file `a.ps1`, is it possible to get all the intellisense for the function and classes for `a.ps1` in my current script?

**Comment by daviwil** [comment]
Hey @chantisnake, this is something that isn't currently provided by the PowerShell engine but I'd like to find a way to support it.  We've got issue #144 tracking this already so I'll close this issue in favor of the existing one.  You can subscribe to the other issue to be notified when any progress gets made.

Thanks!
