### ISSUE TITLE
Can Intellisense be smarter?

### ISSUE THREAD

**Issue by Summpot** [PowerShell/vscode-powershell#3270]
I noticed that by default, entering a new character within an if statement and before an existing character will not display the completion list.
![7](https://user-images.githubusercontent.com/29229273/113480531-385db480-94c7-11eb-8de1-bf35d1af09c8.gif)
Just like the gif picture above.
But if the cursor is on a new line or there are only characters before the cursor.
![8](https://user-images.githubusercontent.com/29229273/113480667-203a6500-94c8-11eb-9ffd-9c8f6bda9104.gif)
It can work very well.
A similar situation occurs in if statements.
![9](https://user-images.githubusercontent.com/29229273/113480817-e027b200-94c8-11eb-8b92-fbe830c8801a.gif)
I want to know if this behavior can be configured.
Thank you very much.

**Comment by rjmholt** [comment]
@Summpot  what PowerShell version are you using? Behaviours like this tend to come from the PowerShell engine's own completion functionality rather than the editor and as such it's likely a fix would come from PowerShell rather than PSES. But if you're using PS 5.1, it's possible a fix has since been implemented in PS 7.

**Comment by Summpot** [comment]
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
I am sure there is no fix on this version.

**Comment by Summpot** [comment]
And I noticed that sometimes the whole language server will not respond after certain operations. But I don't know how to reproduce it.

**Comment by Summpot** [comment]
Any news?

**Comment by andschwa** [comment]
Hi,

I was unable to reproduce this in my environment.

Could you please provide more [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)?

Thanks!
