### ISSUE TITLE
IntelliSense missing in comment blocks

### ISSUE THREAD

**Issue by andschwa** [PowerShell/vscode-powershell#3277]
I would have expected completion / IntelliSense for the built-in PowerShell headers in comment help blocks:

```powershell
<#
.SYNOPSIS
    Short description
.DESCRIPTION
    Long description
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>
```

All the supported headers like `.SYNOPSIS` ought to auto-complete (but they don't).

**Comment by andschwa** [comment]
@rjmholt is this perhaps a request for PSSA?

**Comment by MartinGC94** [comment]
I think Powershell itself should implement this. It should be a pretty easy thing to add here: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L4925

Simply check if you are currently in a comment block and the current line starts with "." and if so run the completion logic you build. The logic probably just needs to have a list of valid headers and exclude existing headers in the comment block (unless they can be used multiple times like ".Example").

Ideally the completion would also help complete the parameters for the various headers for example ".Parameter" would suggest the parameters used in the script and ".EXTERNALHELP" would have file path completion.

I've considered doing a PR for this myself but I currently have a pending one for the #requires keywords that I want to see finished first.
