### ISSUE TITLE
Incorrect syntax highlighting for numeric digits in type names

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#328]
### System Details

- Operating system name and version: Windows 10 Anniversary Update
- VS Code version: 1.6.1
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:

```
PS C:\Users\TrevorSullivan> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When I utilize a .NET class that exists within a .NET namespace, whose name contains a number character, the syntax highlighter incorrectly colors the numeric characters in the fully qualified type name.

![image](https://cloud.githubusercontent.com/assets/466713/19795531/7ecf408a-9c99-11e6-9f5b-f21ab03e257a.png)

**Comment by daviwil** [comment]
This issue was moved to PowerShell/EditorSyntax#28
