### ISSUE TITLE
2021.4.1-preview Includes an old version of PowerShell Editor Services

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/vscode-powershell#3282]
The latest Powershell extension preview changelog includes updates about editor services but those changes aren't actually in this release.  
If the file version of Microsoft.PowerShell.EditorServices.dll can be trusted then the version used is 2.3.0 whereas the version I get when I manually build the extension from the source is 2.4.0-preview.1 so either there's some sort of build/release issue or the patch notes are wrong.

**Comment by andschwa** [comment]
That's strange...

**Comment by andschwa** [comment]
Well, darn. I'm sorry. Re-releasing ASAP.
