### ISSUE TITLE
get_SerializationSettings with specific Azure Stack Az commands, but only in vscode

### ISSUE THREAD

**Issue by schmidtytg** [PowerShell/vscode-powershell#3285]
Issue Type: <b>Bug</b>

1. Install AzureRM modules
2. Remove all AzureRM modules
3. Install Azure Az module
4. Use any of the following commands: New-AzStorageAccount, New-AzNetworkSecurityGroup, or Get-AzVirtualNetworkGatewayConnection (There are likely more commands that don't work, but I've not tried them yet)
5. Get the the following error or something similar for all of them in vscode: 
"New-AzStorageAccount : Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Storage.StorageManagementClient' from assembly 'Microsoft.Azure.Management.Storage"
"New-AzNetworkSecurityGroup : Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Network.NetworkManagementClient' from assembly 
'Microsoft.Azure.Management.Network"
6. Run same commands in Powershell ISE and don't get any errors
7. `PS C:\Users\***> New-AzStorageAccount  -Location *** -ResourceGroupName "TestPolicyRG1" -Name "testsa" -SkuName Standard_LRS`

```
ResourceGroupName      : TestPolicyRG1
StorageAccountName     : testsa
Id                     : ***/testsa
Location               : ***
Sku                    : Microsoft.Azure.Management.Storage.Models.Sku
Kind                   : Storage
Encryption             : Microsoft.Azure.Management.Storage.Models.Encryption
AccessTier             : 
CreationTime           : 4/9/2021 3:43:56 PM
CustomDomain           : 
Identity               : 
LastGeoFailoverTime    : 
PrimaryEndpoints       : Microsoft.Azure.Management.Storage.Models.Endpoints
PrimaryLocation        : ****
ProvisioningState      : Succeeded
SecondaryEndpoints     : 
SecondaryLocation      : 
StatusOfPrimary        : Available
StatusOfSecondary      : 
Tags                   : 
EnableHttpsTrafficOnly : False
NetworkRuleSet         : 
Context                : Microsoft.WindowsAzure.Commands.Common.Storage.LazyAzureStorageContext
ExtendedProperties     : {}"
```

Extension version: 2021.2.2
VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>
|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.21GB free)|
|Process Argv|--disable-gpu --disable-gpu-compositing|
|Screen Reader|no|
|VM|44%|
</details>

**Comment by rjmholt** [comment]
> Get the the following error or something similar for all of them in vscode:

Can we have the actual full error message please? There's not much we can do without this. In PS 7 you can get this with `Get-Error`. In PS 5.1 you will need `$error[0] | fl * -force`.
