### ISSUE TITLE
Can't open terminal after update pwsh with this extension, because `terminal.integrated.shell.windows` still point old version and it is deleted while updating

### ISSUE THREAD

**Issue by sukumo28** [PowerShell/vscode-powershell#3288]
#### PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I can't open terminal after update pwsh with this extension, because `terminal.integrated.shell.windows` still point old version and it is deleted while updating.   
  
When I opened the ps1 file in VS Code, I got the message `You are using an older version of pwsh. Please update` at the bottom right of the screen.  
There was a `YES` button at the bottom of the message, so I pressed it to update pwsh from `6.X` to `7.X`.  
After that, when I pressed `Ctrl + @` to open the terminal, I got the following error and could not open the terminal.  
```  
The terminal process failed to launch: Path to shell executable "C:/Program Files/PowerShell/6/pwsh.exe" does not exist.   
```   
Upon examination, it seems that `C:/Program Files/PowerShell/6` was deleted during the update and ` C:/Program Files/PowerShell/7` was generated. Nevertheless, it seemed that I was getting an error trying to open the old version of the directory.  
So, change the VS Code settings `terminal.integrated.shell.windows` from` C:/Program Files/PowerShell/6/pwsh.exe` to `C:/Program Files/PowerShell/7/pwsh.exe`, it can be opened without any problem.

If this solution is correct, I want the value of `terminal.integrated.shell.windows` to be automatically rewritten to the new version when updating with the extension.
If not, please tell me the correct action.

**Comment by SydneyhSmith** [comment]
Thanks @sukumo28 for opening this issue-- the setting `terminal.integrated.shell.windows` is controlled by VSCode so we do not control the error messaging there, the update pattern is determined by PowerShell so I will mark this as external-- thanks
