### ISSUE TITLE
Intellisense does not work properly with workspace

### ISSUE THREAD

**Issue by pilgi3** [PowerShell/vscode-powershell#3289]
Issue Type: <b>Bug</b>

I am open from my workspace in VS Code a Powershell script and wait until the Integrated console was loaded.
Then I start writing (for example) 'start-process' but the IntelliSense does not appear.
If I move and hold the pointer on the command I can see a little box 'Loading ...'.

![image](https://user-images.githubusercontent.com/44865075/114348484-df48ed00-9b66-11eb-91a4-b9d858073732.png)

Restarting the current session did not help, restarting VS Code did not help either.
If I create a new file (in the workspace) and choose the file type powershell did not help too.
But when I close the workpace and open a new single file the IntelliSense working properly!
This happens on two devices (Windows 10 20H2, and Server 2016).
I am using the same (big) workspace on both devices.
That's very annoying, because of this behavior I cannot use VS Code anymore!
Would be greate if this bug get fixed!

Extension version: 2021.2.2
VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (13.28GB free)|
|Process Argv|--file-uri file://sccm.engel.int/apps%24/sccm-workspace.code-workspace --crash-reporter-id ff4ed618-203b-4bcd-8784-2b376987aec6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SydneyhSmith** [comment]
Thanks @pilgi3 could yo please provide a screenshot of this it would be really helpful if you could also attach the logs--instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by pilgi3** [comment]
I hope this helps.
Actually it works a few minutes after reopening vscode or restarting the powershell session.

![image](https://user-images.githubusercontent.com/44865075/115553643-f21d9900-a2ad-11eb-9a7e-4f66976ff874.png)
[vscode.zip](https://github.com/PowerShell/vscode-powershell/files/6350764/vscode.zip)

**Comment by SydneyhSmith** [comment]
Thanks @pilgi3 looks like this issue could be caused by the way we are loading files in the workspace-- we will need to investigate this area

**Comment by andschwa** [comment]
This was actually still pending (on me, in fact) for investigation. The bot got a little over-eager, sorry about that!
