### ISSUE TITLE
Errors / warnings in VSCode not cleaned up after file rename

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#329]
### System Details
- Operating system name and version: Windows 10 Anniversary 
- VS Code version: 1.6.1
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.206                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.206                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```
### Issue Description

When you rename a file, the syntax errors don't get cleaned up. Over time, you end up accumulating a large number of reported errors, that don't actually exist. When you click on one of these errors in a non-existent file, VSCode asks if you want to create the file.

![image](https://cloud.githubusercontent.com/assets/466713/19796588/bc03997a-9ca2-11e6-8942-cf9044cf0ebc.png)

![image](https://cloud.githubusercontent.com/assets/466713/19796595/c64d047a-9ca2-11e6-8c40-b0cbe3011b7a.png)

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by daviwil** [comment]
Hmmm, interesting.  I've seen VS Code not be very thorough about cleaning up warning/errors but maybe we're causing this somehow.  I'll look into it, thanks!

**Comment by GHRoss** [comment]
I have seen this too. A restart seems to clear.

**Comment by daviwil** [comment]
Verified the issue,  I suspect this is due to using a sorely outdated version of `vscode-languageclient`.  I'll check on this again after we update to the latest version.

**Comment by SydneyhSmith** [comment]
I am having trouble re-producting this issue and am guessing it has been fixed. Will re-open if it is still an issue.
