### ISSUE TITLE
Remote pssession shows incorrect folder/files with tab completion

### ISSUE THREAD

**Issue by neugan** [PowerShell/vscode-powershell#3296]
version v2021.2.2

When remoting to other server using pssession, the tab completion incorrectly show the local folder/files instead of the folder/files in the remote server.

To reproduce,
enter-pssession -computername <remoteserver>
cd <tab completion>, it iterates the local folder/file list on the workstation, instead of the remote server

To make it more obvious, change the path to other folder that only exists in the server.

**Comment by rjmholt** [comment]
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/2661
