### ISSUE TITLE
Creating a new launch.config for powershell produces an empty launch.json

### ISSUE THREAD

**Issue by isidorn** [PowerShell/vscode-powershell#33]
This is because the powershell extension does not contribute an `"initialConfiguration"`.
Examples can be found [here] (https://github.com/Microsoft/vscode-mock-debug/blob/master/package.json#L59)

I can also do a PR, but your probably know better what should be the default launch configuraiton

**Comment by daviwil** [comment]
Thanks for that example link, it's really helpful.  Is there any env variable that I can use in this section to plug in the workspace-relative path of the current file to make things easier for the user when the launch config gets created?

**Comment by isidorn** [comment]
No problem. Yes, if you want to reference an env variable we use the following syntax:
`{ env.name }`
e.g
`{ env. PATH }`

Let me know how it works.

**Comment by daviwil** [comment]
Perfect!  I'll give that a shot.

**Comment by daviwil** [comment]
Just realized there was already an open issue on this, #14.  I'll track the fix for it there.
