### ISSUE TITLE
join

### ISSUE THREAD

**Issue by he852100** [PowerShell/vscode-powershell#3303]
### System Details

System Details Output
```
### VSCode version: 1.55.2 3c4e3df9e89829dce27b7b5c24508306b151f30d x64

### VSCode extensions:
MS-CEINTL.vscode-language-pack-zh-hans@1.55.2
ms-vscode.powershell@2021.2.2


### PSES version: 2.3.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Issue Description
```
@"
a
b
c
"@ -split '\n' -join ''
```
I am experiencing a problem with...

#### Expected Behaviour

-- Description of what *should* be happening --
```
abc
```
#### Actual Behaviour

-- Description of what actually happens --
```
c
```
### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/6355281/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/6355283/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/6355284/vscode-powershell.log)

**Comment by andschwa** [comment]
Hi, can you please give us some more repro info? I cannot reproduce this:

## PowerShell Integrated Terminal
```powershell
=====> PowerShell Preview Integrated Console v2021.4.1 <=====

@Andys-Mac-mini ~/src/vscode-powershell master ≡
> @"
>> a
>> b
>> c
>> "@ -split '\n' -join ''

abc
@Andys-Mac-mini ~/src/vscode-powershell master ≡
> 
```

Visual Studio Code Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:39:47.234Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0

PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Using the preview extension. About to go test on a Windows machine too.

**Comment by SeeminglyScience** [comment]
You'll see it on Windows.  Pretty sure it has to do with how carriage returns are rendered in xterm.js

I always split with `-split '\r?\n'` to work around the line ending differences personally.

**Comment by andschwa** [comment]
That's what I'm thinking too. Just slowly getting my Windows machine updated and back in working order 😅

**Comment by andschwa** [comment]
I cannot reproduce this on Windows either:

```powershell
=====> PowerShell Integrated Console v2021.2.2 <=====

PS C:\Users\andschwa\src> @"
>> a
>> b
>> c
>> "@ -split '\n' -join ''

abc
PS C:\Users\andschwa\src> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core 
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\andschwa\src>
```

**Comment by SeeminglyScience** [comment]
Gotta save it to a file with CRLF line endings and run that (PSRL seems to render with LF regardless of platform).

That said, it happens in the non-integrated console as well so it's not really extension related.

**Comment by andschwa** [comment]
Oh, you are right @SeeminglyScience. In which case I'm marking this answered. Can't split on `\n` if your newlines are actually `\r\l`. Thanks!
