### ISSUE TITLE
Duplicate commands registered 

### ISSUE THREAD

**Issue by Charles-Gagnon** [PowerShell/vscode-powershell#3320]
Upon startup see these errors in the log : 

```
[ms-vscode.powershell]: Command `workbench.action.positionPanelLeft` appears multiple times in the `commands` section.
[ms-vscode.powershell]: Command `workbench.action.positionPanelBottom` appears multiple times in the `commands` section.
```

The reason for this is because you define the commands here : https://github.com/PowerShell/vscode-powershell/blob/master/package.json#L285

using the command IDs `workbench.action.positionPanelLeft` and `workbench.action.positionPanelBottom`. But these are the command IDs used by VS Code : https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/parts/panel/panelActions.ts#L100

so it sees that there's duplicate commands and throws the error (which admittedly isn't actually accurate in this case).

Given that it doesn't seem like you actually try to define this action in your extension currently these commands should be removed from your package.json since currently they aren't actually doing anything. (or given a different command ID and then just have that command call the workbench one if you still want this to show up in the contributions section of the gallery)

**Comment by MartinGC94** [comment]
I added that while knowing nothing about how VS code extensions work so I'm not too surprised I made a mistake. What's the correct way to do this? The purpose of my change was to add buttons for those built-in actions because people who are used to ISE are used to having buttons for moving the console around.

**Comment by Charles-Gagnon** [comment]
You can just make your own command and then register it which just calls the built-in command.

So you'd define `powershell.action.positionPanelLeft` and then in your extension activation call 

```
            vscode.commands.registerCommand(
                'powershell.action.positionPanelLeft',
                async () => { await vscode.commands.executeCommand('workbench.action.positionPanelLeft'); }),
```

**Comment by andschwa** [comment]
@MartinGC94 Do you want to fix this? That'd be awesome. It was on my to-do list but not something I was going to get to today. I can assign to you if you'd like 😁

**Comment by MartinGC94** [comment]
@andschwa sure although I probably won't look at it today either.
