### ISSUE TITLE
Multiple lines on terminal causes command exec

### ISSUE THREAD

**Issue by baldurfour** [PowerShell/vscode-powershell#3323]
Hi,

I've been googling for the last week and couldn't find any solution. What i could find is that i needed powershell preview and psreadline. However: 

I have the same problem which is every time i try to copy and paste multiple lines on the terminal the lines stop my script and are interpreted as separated commands... I've tried to add the line on the flags settings.json file to o and psreadline too but nothing.

Any ideas?
I'm new on Code and my pc is heavily blocked by proxys so installing modules is kind of a pain in the ass.

**Comment by SydneyhSmith** [comment]
Thanks @baldurfour for opening this issue-- can you please describe how you are pasting and provide and GIFs/screenshots of what you are experiencing, as well as the extension and PSReadLine version info--thanks!
