### ISSUE TITLE
Add support for file icons in Explorer viewlet

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#333]
I see this in 1.7 insider's (could have existed before) but I think it would be nice to add some icons for the standard PS files:

![image](https://cloud.githubusercontent.com/assets/5177512/19911030/8a367568-a056-11e6-9408-dce5b8bcbc69.png)

**Comment by tylerl0706** [comment]
I see the PowerShell logo for `.ps1`, `.psm1`, `.psd1`. I think we can close this now, right?

**Comment by rkeithhill** [comment]
Yup.
