### ISSUE TITLE
Add support for attaching to a powershell script

### ISSUE THREAD

**Issue by nojvek** [PowerShell/vscode-powershell#334]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

### Issue Description

I am experiencing a problem with...

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Hey @nojvek, looks like this issue is already captured in issue #206, will go ahead and close this one in favor of that.  If I'm misunderstanding the feature request, please let me know.  Thanks!
