### ISSUE TITLE
Debug Powershell Untitled Files Not Working

### ISSUE THREAD

**Issue by SoulSeekkor** [PowerShell/vscode-powershell#3343]
Issue Description
=====

Porting an issue from [here](https://github.com/microsoft/vscode/issues/123179) that was determined to be an extension issue specifically.

Unless my memory is incorrect, one of the biggest advantages to VS Code over ISE was that we used to be able to set breakpoints and debug Powershell files that were untitled and not saved yet.

With this version I've noticed that no longer works, I can set a breakpoint on an untitled tab and it does not stop, it simply runs the entire script without stopping.

![image](https://user-images.githubusercontent.com/16005426/117465502-63e51c00-af17-11eb-8f0d-58c353870a5b.png)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19042 |
| VSCode | 1.56.0|
| PowerShell Extension Version | 2021.2.2 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.906|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.906|
|BuildVersion|10.0.19041.906|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|4.6.0|
|powershell|ms-vscode|2021.2.2|
|vscode-inline-values-powershell|TylerLeonhardt|0.0.5|

**Comment by SydneyhSmith** [comment]
Thanks @SoulSeekkor when you ran the debugger were you prompted to save the file?

**Comment by SoulSeekkor** [comment]
I was not!  Thankfully that bug was fixed with the recent addition of the setting for VS Code to allow us to change the behavior back to not prompt on debug.  I currently have it set to "nonUntitledEditorsInActiveGroup' so that it behaves like it used to, where we could run/debug untitled files without getting prompted.

**Comment by SoulSeekkor** [comment]
Was this mistakenly closed?  I didn't mean by my last comment that this issue was resolved, only that the other VS Code prompt to save on debug problem was fixed by them adding that setting in that particular repo....  The issue with debug not working on untitled files is a whole other issue specific to this extension.
