### ISSUE TITLE
Strange scrolling behaviour

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/vscode-powershell#3344]
### System Details

System Details Output
```
### VSCode version: 1.56.0 cfa2e218100323074ac1948c885448fdf4de2a7f x64

### VSCode extensions:
MS-CEINTL.vscode-language-pack-de@1.56.1
ms-vscode.powershell@2021.2.2


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am experiencing a problem with the PowerShell terminal scrolling behaviour when switching from side panel view to full panel view:

![Strange scrolling behaviour](https://user-images.githubusercontent.com/9283914/117493211-f8309c80-af72-11eb-8db7-365aae3850e9.gif)

#### Expected Behaviour

When I hit the `ARROW UP` key, I would expect to see different versions of my execution history, but I don't expect a scrolling behaviour.

#### Actual Behaviour

When I hit the `ARROW UP` key after having switched the PowerShell terminal from side panel to full panel, scrolling is performed that's mimicking the previous side panel layout.

**Comment by SydneyhSmith** [comment]
Thanks @SetTrend it looks like this may be an issue with how PSReadLine interfaces with the console, it seems as though PSReadLine may not be detecting the resize event...since this is happening outside the context of the extension/integrated console I will mark this as external--you may want to open an issue in https://github.com/PowerShell/PSREadline

**Comment by SetTrend** [comment]
Thank you, @SydneyhSmith. Following your suggestion I opened a corresponding sibling issue [here](/PowerShell/PSReadLine/issues/2450)
