### ISSUE TITLE
Tabbing [PSCustomObject] adds an additional ']'

### ISSUE THREAD

**Issue by SwarfegaGit** [PowerShell/vscode-powershell#3349]
### System Details

```
### VSCode version: 1.56.0 cfa2e218100323074ac1948c885448fdf4de2a7f x64

### VSCode extensions:
eamodio.gitlens@11.4.1
mechatroner.rainbow-csv@1.8.1
ms-python.python@2021.5.840043038
ms-python.vscode-pylance@2021.5.2
ms-toolsai.jupyter@2021.6.832593372
ms-vscode.powershell@2021.2.2
oderwat.indent-rainbow@7.5.0


### PSES version: 2.3.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
System Details Output
```

### Issue Description

AutoCompleting with tab when typing [PSCustomObject] adds an additional square bracket at the end.

In a blank file if you type a '[' the editor will automatically add a ]. Then type ps which it will recommend [PSCustomObject] so press tab to accept this.  The autocomplete works but there's an additional ']'.  See the actual behaviour section below.

#### Expected Behaviour
```
[PSCustomObject]@{
    Name = Value
}
```
#### Actual Behaviour
```
[PSCustomObject]@{
    Name = Value
}]
```

**Comment by wsmelton** [comment]
I would mention this is a VS Code issue more than extension. @TylerLeonhardt fixed this issue at one point in VS Code in microsoft/vscode#114235. An additional change was made in the extension for preview 2020.5.0 #3129 to address it, but I think this is still on Code's side if it is to be fixed.

The proper use of snippets is not to include the brackets first. Type the alias and then tab key will create a proper object based on the snippet. I create snippets based on projects and use the [snippet-generator.app](https://snippet-generator.app/) site to take scripts or code blocks and convert them more easily.

![vscode_snippet_usage](https://user-images.githubusercontent.com/11204251/119264805-3b615100-bbaa-11eb-95b9-6ee87bae7520.gif)

**Comment by TylerLeonhardt** [comment]
So there are actually 2 different behaviors of accepting a completion.

You can see what options are available if you have the setting `editor.suggest.showStatusBar` on.

One will be mapped to Enter, one will be Shift+Enter.

The default behavior of Enter is controlled via the setting `editor.suggest.insertMode`.

* insert (default): doesn't replace any trailing characters. It only inserts them.
* replace: will replace characters after the cursor if the snippet can

> Note: Tab I believe has the same behavior of Enter so if you see Enter above it should also apply to Tab I think.

So I think if you use Shift+Enter or set the insertMode to `replace` this should work.
