### ISSUE TITLE
$_ doesn't work for conditional breakpoints

### ISSUE THREAD

**Issue by N6UDP** [PowerShell/vscode-powershell#335]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version:Windows 10 
- VS Code version:1.7.1
- PowerShell extension version:0.7.2
- Output from `$PSVersionTable`:
   
```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14931.1000                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14931.1000                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1        
```

### Issue Description
```
0..200 | %{ 
    $_ # Try setting a conditional on $_ -gt 10 or similar
}
```
This works fine with 
```
foreach ($i in (0..200)){
    $i
}
```

**Comment by rkeithhill** [comment]
This doesn't work in ISE either.  The problem is that `$_` has special meaning inside the scriptblock passed to the Action parameter.  In this context, `$_` refers to the breakpoint.  You can inspect the breakpoint's HitCount and other properties. 

It is easy to work around this like so:
```
0..200 | %{ 
    $i = $_
    $_ # Try setting a conditional on $_ -gt 10 or similar
}
```
Then use a condition expression of `$i -gt 10`.

**Comment by N6UDP** [comment]
I could have sworn I did a conditional on that at one point in ISE but I must have been imagining things ;) I didn't even think to try it in ISE.  It actually does work with $script:_
```Set-PSBreakpoint -Line 2 -Action {if($Script:_ -gt 10){break}} -Script t.ps1```
works with 
```
0..200 | %{ 
    $_
}
```
FWIW

**Comment by N6UDP** [comment]
Confirmed ```$script:_ -gt 10``` works in code -- closing this.

**Comment by rkeithhill** [comment]
Thanks for the tip on `$script:_`!

**Comment by N6UDP** [comment]
I suppose the only thing that could be done is to warn folks in the help/documentation (or during entry into the textbox)

**Comment by Liturgist** [comment]
Still a bug in 2021. Is this bug a "will not fix"? Requiring the creation of `$hack_variable = $_` is less than desirable.

**Comment by andschwa** [comment]
> Still a bug in 2021. Is this bug a "will not fix"? Requiring the creation of `$hack_variable = $_` is less than desirable.

The work-around is to use `$script:_` instead, since the scope needs to be stated explicitly.
