### ISSUE TITLE
Update Status Bar `terminal` icon to `terminal-powershell` icon

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#3351]
As of 1.56 (current latest as of the creation of this issue), there is a `terminal-powershell` [codicon](https://microsoft.github.io/vscode-codicons/dist/codicon.html)!
![image](https://user-images.githubusercontent.com/2644648/118335633-ec8a2c00-b4c4-11eb-9ec9-2f445edad3b2.png)

Feel free to use it everywhere, but a good spot for sure would be replacing `terminal` here with `terminal-powershell`:
https://github.com/PowerShell/vscode-powershell/blob/db40d973ace14f4b1286341e992e7a385b88419e/src/session.ts#L659

**Comment by andschwa** [comment]
Thanks @TylerLeonhardt!
