### ISSUE TITLE
MisleadingBacktick from script analyzer is not raising a warning in vscode

### ISSUE THREAD

**Issue by eugeneniemand** [PowerShell/vscode-powershell#336]
### System Details

- Operating system name and version: Windows 7
- VS Code version: 1.7.1
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:

> PSVersion                      5.0.10514.6
> WSManStackVersion              3.0
> SerializationVersion           1.1.0.1
> CLRVersion                     4.0.30319.42000
> BuildVersion                   10.0.10514.6
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> PSRemotingProtocolVersion      2.3

### Issue Description

When using back ticks for line continuation and a white space exists after the back tick the parameters on the following lines are ignored. I would ideally like a red/green squiggly to appear under the white space. Below is an example where the first one does not have a white space and the second one does. In vs code they render exactly the same without any warnings

```
function Test-BackTick ($param1, $param2) {
	Write-Host "Param 1: $param1"
	Write-Host "Param 2: $param2"
}

Test-BackTick -param1 1 `
	-param2 2

Test-BackTick -param1 1 ` 
	-param2 2
```

**Comment by eugeneniemand** [comment]
Looks like github is removing the trailing whitespace

**Comment by rkeithhill** [comment]
Our default ruleset is pretty minimal after much feedback that we had too many rules enabled. That said, I think this rule should be in the default ruleset.  

You can workaround this for now by creating a `ScriptAnalyzerSettings.psd1` file and putting it in work space.  Add the following contents to this file:
```
# The PowerShell Script Analyzer will generate a warning
# diagnostic record for this file due to a bug -
# https://github.com/PowerShell/PSScriptAnalyzer/issues/472
@{
    # Only diagnostic records of the specified severity will be generated.
    # Uncomment the following line if you only want Errors and Warnings but
    # not Information diagnostic records.
    #Severity = @('Error','Warning')

    # Analyze **only** the following rules. Use IncludeRules when you want
    # to invoke only a small subset of the defualt rules.
    IncludeRules = @('PSAvoidDefaultValueSwitchParameter',
                     'PSMissingModuleManifestField',
                     'PSReservedCmdletChar',
                     'PSReservedParams',
                     'PSShouldProcess',
                     'PSUseApprovedVerbs',
                     'PSUseDeclaredVarsMoreThanAssigments',
                     'PSMisleadingBacktick')

    # Do not analyze the following rules. Use ExcludeRules when you have
    # commented out the IncludeRules settings above and want to include all
    # the default rules except for those you exclude below.
    # Note: if a rule is in both IncludeRules and ExcludeRules, the rule
    # will be excluded.
    #ExcludeRules = @('PSAvoidUsingWriteHost')
}
```
Then add a `.vscode\settings.json` with this in it:
```
{
    // Use a custom PowerShell Script Analyzer settings file for this workspace.
    // Relative paths for this setting are always relative to the workspace root dir.
    "powershell.scriptAnalysis.settingsPath": "./ScriptAnalyzerSettings.psd1"
}
```
Now VSCode will use the ruleset (IncludeRules) that you want it to use.

**Comment by rkeithhill** [comment]
Completed.
