### ISSUE TITLE
Extension should not duplicate integrated console terminals

### ISSUE THREAD

**Issue by Tyriar** [PowerShell/vscode-powershell#3360]
You can get some context on this here: https://github.com/microsoft/vscode/issues/123805

Basically PS integrated consoles get reconnected when the window is reloaded currently by design, the PS extension should detect these and kill them before trying to start up another one (or even better re-establish the connection if that's possible).

**Comment by TylerLeonhardt** [comment]
@rjmholt @andschwa  You _should_ be able to terminals with name "PowerShell Integrated Console" and kill them before creating the one the new session will use... but I thought I saw this bug so just heads up if you do:
https://github.com/microsoft/vscode/issues/123805#issuecomment-846017342

**Comment by andschwa** [comment]
Wee! I tested out the proposed API and it works great. Just waiting for it to be available in a release 😄

**Comment by TylerLeonhardt** [comment]
cc @meganrogge

**Comment by meganrogge** [comment]
Great to hear @andschwa. It will be available in our February release this week
https://github.com/microsoft/vscode/blob/261adce05c180fbe1802dd26d8d802c00bfedbe5/src/vscode-dts/vscode.d.ts#L10040-L10044

**Comment by andschwa** [comment]
Hm, interesting. In my testing of this I've discovered that "reload window" (which kills extensions) does _not_ kill subprocesses of the extensions, so you can end up with orphaned `pwsh` processes around. Fortunately the new API at least doesn't leave around confusing consoles, so from the UX perspective it's fine. And _eventually_ the processes seem to close, just not right away.

**Comment by andschwa** [comment]
Ok there's some delayed process cleanup, but it works!
