### ISSUE TITLE
Add breakpoint hit counter feature 

### ISSUE THREAD

**Issue by lucdekens** [PowerShell/vscode-powershell#337]
In VSC 1.7, the new breakpoint hit counter feature was introduced.
Currently it only works in the Node.js debugger.

Can this feature be implemented for PowerShell breakpoints in the PowerShell extension?

**Comment by rkeithhill** [comment]
Work is under way.  See https://github.com/PowerShell/PowerShellEditorServices/issues/298.  

I should have this work committed in a few days but you will have to wait until the next drop of the PowerShell extension (hopefully in a few weeks). 

 Today you can do a simple hit count breakpoint in VSCode 1.7 by adding a conditional breakpoint with this expression:
```
if ($_.HitCount -eq <user hit count>) {  break  }
```

**Comment by lucdekens** [comment]
Great to hear.
Looking forward to that one

**Comment by rkeithhill** [comment]
Implemented over in the PowerShellEditorServices.  Waiting for PR acceptance.  https://github.com/PowerShell/PowerShellEditorServices/pull/300
