### ISSUE TITLE
VSCode system.typeloadexception

### ISSUE THREAD

**Issue by Big2thaE** [PowerShell/vscode-powershell#3385]
Issue Type: <b>Bug</b>

Start Powershell Integrated Console.  Results in: VSCode system.typeloadexception: could not load type 'system.management.automation.subsystem.predictionresult' from assembly.......

Extension version: 2021.2.2
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.41GB (2.62GB free)|
|Process Argv|--crash-reporter-id 6e23fc86-de8f-44cf-ae28-78c663b580ed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943cf:30300583
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30307505
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by Big2thaE** [comment]
https://user-images.githubusercontent.com/36280037/120222506-a8599400-c205-11eb-9256-51cc33a3e999.mp4

**Comment by andschwa** [comment]
This appears to be a bug relating to an interface change in PowerShell Preview and PSReadLine, and not a VS Code PowerShell extension specific issue. To resolve your issue here, install the stable PowerShell version instead of the preview. See https://github.com/PowerShell/PSReadLine/issues/2511

**Comment by andschwa** [comment]
This is weird...this _should not_ be happening with PSReadLine 2.1.0 based on the PowerShell 7 preview release notes: https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.6

**Comment by andschwa** [comment]
@Big2thaE have you installed a beta version of PSReadLine on your machine?

**Comment by andschwa** [comment]
Also see https://github.com/PowerShell/PowerShell/issues/15496

**Comment by andschwa** [comment]
Ah I found it in the GIF, you do have PSReadLine 2.2.0-beta2 installed. Ok, please revert to 2.1.0 (just install PSReadLine and let the extension use its bundled version instead).

**Comment by Big2thaE** [comment]
Thank you so much!!

Closing VSCode and then running

Install-Module -Name PSReadLine -RequiredVersion 2.1.0 -force

in a PS Terminal was the winning version that set it back.



-Erik
________________________________
