### ISSUE TITLE
Install-VSCode.ps1 not detecting 64-bit architechture in Windows 10

### ISSUE THREAD

**Issue by mat-ocl** [PowerShell/vscode-powershell#3390]
### System Details

System Details Output
```
### PowerShell version:
 
Name                           Value                                                                     
----                           -----                                                                      
PSVersion                      5.1.18362.1474                                                            
PSEdition                      Desktop                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                   
BuildVersion                   10.0.18362.1474                                                           
CLRVersion                     4.0.30319.42000                                                           
WSManStackVersion              3.0                                                                       
PSRemotingProtocolVersion      2.3                                                                       
SerializationVersion           1.1.0.1   
```

### Issue Description

I'm installing VSCode on a 64-bit Windows 10 but i get a message like this:
`WARNING: 64-bit install requested on 32-bit system. Installing 32-bit VSCode`

#### Expected Behaviour

64-bit VSCode should install on a 64-bit Windows 10

#### Actual Behaviour

The function Test-IsOsArchX64 is testing the OS Architechture with:
`(Get-CimInstance -ClassName Win32_OperatingSystem).OSArchitecture -eq '64-bit'`

Because of language version different from English the answer is not '64-bit' even though the system is 64-bit. In my case it's '64-bittinen' as my OS is in Finnish. Other languages probably have this issue too.

**Comment by andschwa** [comment]
Thanks @mat-ocl!
