### ISSUE TITLE
"Learn"-link in marketplace is broken (404)

### ISSUE THREAD

**Issue by SrTobi** [PowerShell/vscode-powershell#34]
![learn](https://cloud.githubusercontent.com/assets/4148534/11423045/60594a44-9441-11e5-92c1-efe84cf5e5c7.PNG)

**Comment by daviwil** [comment]
Thanks @SrTobi!  Really appreciate that you sent a PR as well!

**Comment by daviwil** [comment]
This is resolved by SrTobi's pull request #35.  Not sure why GitHub didn't auto-resolve, but closing now.
