### ISSUE TITLE
PowerShell IntelliSense is showing incorrect suggestions

### ISSUE THREAD

**Issue by niktastik** [PowerShell/vscode-powershell#3412]
Issue Type: <b>Bug</b>

I just upgraded today and have been experiencing many errors with PowerShell IntelliSense. For example, if I want to have my closing parenthesis for a Param block on the next line after the final parameter, that's shown as an error.

I'm also seeing that IntelliSense is reporting errors with lines that are commented out.

Extension version: 2021.5.1
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (17.79GB free)|
|Process Argv|--crash-reporter-id 59131029-c1e1-4dda-ac84-7f802d99a41e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by andschwa** [comment]
Hi,

Could you please provide more [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)?

Thanks!

**Comment by niktastik** [comment]
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/6640875/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/6640877/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/6640878/vscode-powershell.log)

**Comment by andschwa** [comment]
Could you also provide a script that this reproduces on, and perhaps a GIF? What you're describing doesn't sound like an IntelliSense issue but maybe a parser issue, could you share exactly what error messages are being reported? A screenshot or GIF of the full code and error message(s) would be great.
