### ISSUE TITLE
Add a "Getting Started" Experience for vscode-powershell

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3414]
**Summary of the new feature**
The new getting started experience lets extension authors contribute tour walkthroughs of their extension.
https://code.visualstudio.com/updates/v1_57#_new-getting-started-experience

**Proposed technical implementation details (optional)**

VSCode-Powershell would be a good candidate, and this would be a good `up-for-grabs` item for a community member to develop, maybe using the [existing documentation as a base](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/using-vscode?view=powershell-7.1). Extracting the luna paint extension .vsix into a zip, you can see the "Getting Started" is just a sequence of markdown files and an addition to the `contributes` section of the package.json.

```
		"walkthroughs": [
			{
				"id": "exampleProject",
				"title": "Edit Images With Luna Paint",
				"description": "Everything you need to get started editing images inside VS Code",
				"steps": [
					{
						"id": "luna.interfaceOverview",
						"title": "Interface Overview",
						"description": "Luna Paint features a canvas, several windows and bars on the top and bottom.",
						"media": {
							"image": "getting-started/images/1-interface-overview.png",
							"altText": ""
						}
					},
					{
						"id": "luna.pencilTool",
						"title": "Pencil Tool",
						"description": "",
						"media": {
							"markdown": "getting-started/2-pencil-tool.md"
						}
					},
					{
						"id": "luna.selectionTools",
						"title": "Selection Tools",
						"description": "",
						"media": {
							"markdown": "getting-started/3-selection-tools.md"
						}
					},
					{
						"id": "luna.cropTool",
						"title": "Crop Tool",
						"description": "",
						"media": {
							"markdown": "getting-started/4-crop-tool.md"
						}
					},
					{
						"id": "luna.lineTool",
						"title": "Line Tool",
						"description": "",
						"media": {
							"markdown": "getting-started/5-line-tool.md"
						}
					},
					{
						"id": "luna.colorPickerTool",
						"title": "Color Picker Tool",
						"description": "",
						"media": {
							"markdown": "getting-started/6-color-picker-tool.md"
						}
					},
					{
						"id": "luna.rectangleTool",
						"title": "Rectangle Tool",
						"description": "",
						"media": {
							"markdown": "getting-started/7-rectangle-tool.md"
						}
					},
					{
						"id": "luna.viewportTools",
						"title": "Viewport Tools",
						"description": "",
						"media": {
							"markdown": "getting-started/8-viewport-tools.md"
						}
					}
				]
			}
```

**Comment by andschwa** [comment]
Hey, I think this would be really cool. Our documentation in general needs a major revamp. While this would take a fair bit of shepherding and then maintenance work once we have it, I think I'm willing to see that through. @SydneyhSmith and @rjmholt  should we start a whole "documentation" project? I need to get the `docfx` site back up, write releasing docs, write an architecture doc...so much to do.
