### ISSUE TITLE
Extension incorrectly attempts x64 update on Arm64 platform

### ISSUE THREAD

**Issue by pb5050** [PowerShell/vscode-powershell#3435]
I use nothing but native arm64..... 

I get this alert in visual studio code (arm64) an alert about an updated version of powershell.

![Powershell Issue](https://user-images.githubusercontent.com/58855947/120072346-0dbc5200-c059-11eb-946e-80d5d2071bd9.png)

when clicking it tries to install x64 version  instead of arm. would be nice to have an arm installer or recognize im using arm and not x64.

**Comment by andschwa** [comment]
We (unfortunately) have our own logic in the extension to suggest updating PowerShell. Perhaps we'll fix this bug, but frankly I've been contemplating removing that logic entirely. PowerShell _already_ has its own logic to prompt users to update; I don't think the extension has any business adding duplicative logic on top of that, especially (as evidenced by this bug, among several) that it's _buggy_. It's not worth the maintenance cost.
