### ISSUE TITLE
the powershell success stream seems to quit working while connected to Exchange PSSession

### ISSUE THREAD

**Issue by acelaya77** [PowerShell/vscode-powershell#3436]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

the terminal in VSCode seems to stop responding on the success stream (write-output), but write-warning and write-host still seem to work.

### PowerShell Version

```console
Name                      Value                  
----                      -----                  
PSVersion                 5.1.19041.1023         
PSEdition                 Desktop                
PSCompatibleVersions      {1.0, 2.0, 3.0, 4.0...}
BuildVersion              10.0.19041.1023        
CLRVersion                4.0.30319.42000        
WSManStackVersion         3.0                    
PSRemotingProtocolVersion 2.3                    
SerializationVersion      1.1.0.1
```

### Visual Studio Code Version

```console
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
```

### Extension Version

```console PS> code --list-extensions --show-versions | Select-String powershell
ms-vscode.powershell@2021.5.1
ms-vscode.powershell@2021.6.1
```

### Steps to Reproduce

while working in various scripts, the session will quit sending output to the terminal on the success stream, but will output if using the write-host cmdlet.

### Visuals

https://user-images.githubusercontent.com/18290882/123188875-afb13d80-d451-11eb-9606-9218f6743e7c.mov

### Logs

[powershell_editor_service.zip](https://github.com/PowerShell/vscode-powershell/files/6705671/powershell_editor_service.zip)

**Comment by andschwa** [comment]
Do you know if this repros with PowerShell 7?
