### ISSUE TITLE
Inconsistent user-selection word highlighting behaviour

### ISSUE THREAD

**Issue by ThubLives** [PowerShell/vscode-powershell#345]
### System Details

- Operating system name and version:  Windows 7 SP1
- VS Code version:  1.71
- PowerShell extension version:  0.7.2
- Output from `$PSVersionTable`:
```
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Placing the cursor on a word doesn't always auto-highlight other words like it within the file (depends on language parsing?).  Manually highlighting the word with the mouse or keyboard does seem to consistently highlight the instances of the word throughout the file, but the scroll bar does not update with the locations of those instances.

I've seen cases of long sessions (over a week) where automatic similar-word highlighting stops altogether and requires closing and relaunching Code, but I haven't been able to reproduce it or isolate the vscode-powershell extension while capturing logs.

### Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/604350/logs.zip)

**Comment by ThubLives** [comment]
I haven't experienced this problem for the last few VSCode and vscode-powershell releases, so I think it's safe to say it's resolved.  I'm closing this issue.

**Comment by daviwil** [comment]
That's awesome, glad to hear it!
