### ISSUE TITLE
Word Separator configuration for "$" ignored

### ISSUE THREAD

**Issue by FriedrichWeinmann** [PowerShell/vscode-powershell#3456]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

After modifying the VSCode settings for `Editor: Word Separators`, removing both `-` and `$` from the default list will have VSCode ignore some of that setting _for the PowerShell extension only_ :

> In PowerShell script file

+ Removing the `-` is honored - doubleclicking on a cmdlet selects the full name
+ Removing the `$` is _ignored_ - doubleclicking on a variable does not select the $ of the variable

> In a Markdown file

+ Removing the `-` is honored - doubleclicking on a cmdlet selects the full name
+ Removing the `$` is honored - doubleclicking on a variable selects the full name

> Configuration value

The full current value of the `Editor: Word Separators` setting is:

```text
`~!@#%^&*()=+[{]}\|;:'",.<>/?
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.6
PSEdition                      Core
GitCommitId                    7.1.0-preview.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.58.0
2d23c42a936db1c7b3b06f918cde29561cc47cd6
x64
```

### Extension Version

```console PS> code --list-extensions --show-versions | Select-String powershell
ms-vscode.powershell@2021.5.1
ms-vscode.powershell@2021.6.2
ms-vscode.powershell-preview@2021.6.1
```

### Steps to Reproduce

Set Word Separators to:

```text
`~!@#%^&*()=+[{]}\|;:'",.<>/?
```

Then doubleclick on a variable in a PowerShell script

**Comment by andschwa** [comment]
You'll need to set those options for PowerShell files as well, as we supply a [default value](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#double-click-isnt-selecting-the-whole-variable) for PowerShell files. So just add this to your `settings.json`:

```json
"[powershell]": {
    "editor.wordSeparators": "<copy/paste from your general editor.wordSeparators>"
}
```

**Comment by andschwa** [comment]
Also, you may want to inspect why you have three separate extensions installed 🧐

**Comment by FriedrichWeinmann** [comment]
Heya Andy,
thanks for the swift and precise information on how to resolve this!
Worked just fine :)

Any way to get this setting exposed to the config UI though? As it is there is zero discoverability to find this on your own.

**Comment by andschwa** [comment]
I'd love to do it through the UI, I just need to learn more about the VS Code extension API to do it right. I'd say that's totally up for grabs if you wanted to make it happen!
