### ISSUE TITLE
PowerShell extension doesn't stop powershell Integrated Console process when project is closed

### ISSUE THREAD

**Issue by peetrike** [PowerShell/vscode-powershell#3489]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Every time I open new project folder, the PowerShell extension starts new PowerShell process.  Closing folder doesn't stop now redundant PowerShell process(es).  Opening next project (folder), starts new process.  Opening scirpt in separate VS Code window starts yet again new PowerShell process (and closing that window leaves PowerShell process running).

After switching between several projects, that makes quite some bit of memory.

The same occurred with PowerShell-Preview extension.  It also doesn't matter, which version of PowerShell is used by extension: Windows PowerShell 5.1 is loaded and left running the same way.

All processes are stopped, when last VS Code window will be closed.

### PowerShell Version

```console
PS ❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS ❯ code --version
1.58.2
c3f126316369cd610563c75b1b1725e0679adfb3
x64
```

### Extension Version

```console
PS ❯ code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2021.6.2 (enabled)
ms-vscode.powershell-preview@2021.7.0 (disabled)
```

### Steps to Reproduce

1. Open project containing PowerShell files.  Have some PowerShell files opened (to get PowerShell extension started)
2. Open another project (and some PowerShell files)
3. Open code with .ps1 file from command line (`code -n file.ps1`)

Now there will be 3 PowerShell processes visible in VS Code Project Explorer and in Windows Task Manager.

### Visuals

This is VS Code Process Explorer after opening 2 project folders and one file in separate window:
![image](https://user-images.githubusercontent.com/34946805/127666833-66c089b8-3ba8-4a8c-80ff-6cfcc351021e.png)

**Comment by peetrike** [comment]
It might be connected to the Workspace Trust feature introduced recently.  I have added next configuration to my settings.json:
```json
  "extensions.supportUntrustedWorkspaces": {
    "ms-vscode.powershell": {
      "supported": true
    },
    "ms-vscode.powershell-preview": {
      "supported": true
    },
  },

```

**Comment by andschwa** [comment]
@peetrike Can you please clarify: do you have these projects marked "trusted" or "untrusted"? I have to assume "trusted" or the extension wouldn't/shouldn't be starting in the first place at all.

**Comment by peetrike** [comment]
> @peetrike Can you please clarify: do you have these projects marked "trusted" or "untrusted"? I have to assume "trusted" or the extension wouldn't/shouldn't be starting in the first place at all.

I have those projects marked as trusted.  And configuration mentioned above marks the PowerShell extension always trusted.

I usually switch between projects several times a day and in the past there was no problems.  But then recently I noticed, that ~20 GB of my machine memory was taken by pwsh processes, while I had only couple of them running (to my knowledge).  So it might be connected to recent (within couple of months) change in either VS Code or PowerShell extension.  Or change in my configuration (the one connected to workspace trust).

**Comment by andschwa** [comment]
Sounds like the changes made upstream to VS Code isn't allowing for spawned processes to be closed :/

**Comment by andschwa** [comment]
@TylerLeonhardt is this something VS Code could look at?

**Comment by TylerLeonhardt** [comment]
@Tyriar @meganrogge

**Comment by peetrike** [comment]
Yes, VS Code v1.61.1 still has same issue

**Comment by StevenBucher98** [comment]
Thanks @peetrike, we had a few clarifying questions we want to get answered to help us get a better picture of the issue

- Which processes the integrated console can get to? You can work out which process by executing `$pid` and will give you the pid's back. We want to work out which process is the "zombie" one. 

-Are you able to access the third process through the drop down of the vscode terminal display?

-What, if anything happens, when you kill that third process that is not using a lot of memory. We suspect it might show nothing. The low memory usage to us, makes us suspect it might be trying to shut down but has some handle that it can't shut down.

**Comment by peetrike** [comment]
There will be as many processes as many times the PowerShell extension spawns new instance.  It means that every time I open new fonder (or open script in new window), the new process is created.  And these processes don't go away.

I haven't tried to connect to those processes.  When i kill it, nothing notable happens in VS Code (I usually close all folders and separate windows before starting to kill processes).  All those processes are also closed, when VS Code is closed.

I will try to turn on logging and post the resultant logs here.

**Comment by peetrike** [comment]
The captured logs are here.  Let me know if You need more.

[1634625748-80020a2b-ead1-460a-8497-192267392d681634625746108.zip](https://github.com/PowerShell/vscode-powershell/files/7370904/1634625748-80020a2b-ead1-460a-8497-192267392d681634625746108.zip)

**Comment by andschwa** [comment]
I wonder if this is related to https://github.com/PowerShell/vscode-powershell/issues/3360, so when we fix that bug, let's test this again.

**Comment by andschwa** [comment]
@Tyriar Hey, just FYI, I see this same bug exist with the C# extension where the spawned `dotnet` processes aren't closed. I'm frequently having to go to my activity manager and force close a dozen of them, even though Code is no longer open. So I don't think this problem is unique to the PowerShell extension. Code is losing track of its child processes.

**Comment by Tyriar** [comment]
If this still happens after #3360 you could try the `Terminal: Attach to Session` command, if the process is classified as an "orphan" without a window you should be able to reattach to it.

**Comment by peetrike** [comment]
Still the same.  When I open folder and one PowerShell file, and then close the folder, the PowerShell Integrated Console protsess still remains in Process explorer.  And when I open next folder (and .ps1 file within), then new process will be launched and previous process just sits in Process Explorer and takes memory.

**Comment by peetrike** [comment]
VS Code version 1.65.2, PowerShell Extension Preview version v2022.3.0

**Comment by peetrike** [comment]
and as soon as I make PSIC visible (and then I can close the PSIC terminal window), when closing folder, the PSIC process is correctly terminated.  I have [PSIC hidden](https://github.com/PowerShell/vscode-powershell/issues/3489#issuecomment-946811609)

**Comment by andschwa** [comment]
> 

Hey, that's a good find and will help us narrow it down.
