### ISSUE TITLE
suggested extension `msjsdiag.debugger-for-chrome` has been deprecated

### ISSUE THREAD

**Issue by corbob** [PowerShell/vscode-powershell#3499]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

The extensions suggested for working on the extension include `msjsdiag.debugger-for-chrome` this has been deprecated as per the extension: https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome

### PowerShell Version

```console
N/A: This is not an issue with the extension per se, more the developer experience working on the extension.
```

### Visual Studio Code Version

```console
1.59.0-insider
379476f0e13988d90fab105c5c19e7abc8b1dea8
x64
```

### Extension Version

```console PS> code --list-extensions --show-versions | Select-String powershell
ms-vscode.powershell@2021.5.1
N/A: This is not an issue with the extension per se, more the developer experience working on the extension.
```

### Steps to Reproduce

1. On a system with relatively few extensions, open the workspace to work on the extension.
2. View the recommended extensions.
3. Note that this extension is recommended despite it being deprecated.

**Comment by andschwa** [comment]
Feel free to open a PR to fix!
