### ISSUE TITLE
Got message about ps v7.1.4  But how "Upgrade now"?

### ISSUE THREAD

**Issue by gfmoore** [PowerShell/vscode-powershell#3508]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

As title - you should put a link to explanation in message!

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.60.0-insider
58454f7bec838f79fe2422ab5914419147d82e40
x64
```

### Extension Version

```console PS> code --list-extensions --show-versions | Select-String powershell
ms-vscode.powershell@2021.5.1
Nothing
```

### Steps to Reproduce

Open Terminal and see message

**Comment by scotto88** [comment]
I got the same message. How do you "Upgrade now" ?

**Comment by rkeithhill** [comment]
It depends on how you installed and which platform.  For Windows, you could have installed via the MSI package, Microsoft Store, or dotnet tool.  For MSI package, go to https://aka.ms/getpowershell and download 7.1.4 and install it.  Or if you have winget installed you can run `winget upgrade powershell`.  For MS Store, open up the Store and select `Downloads and udpates` and `Get Updates`.  For dotnet tool, run `dotnet tool update powershell`.

**Comment by rkeithhill** [comment]
This is the current upgrade message for reference. It appears to be the same for all platforms:

![image](https://user-images.githubusercontent.com/5177512/129592624-95b23b60-adfa-4739-9876-cff3508b7c22.png)

Rather than just dumping folks off at the downloads page, it does seem like taking them to a "How to upgrade PowerShell" page would be better.  It would be even better if the URL generated could include info on the platform and the type of PowerShell install.  That way the upgrade info could be more specific.  The other option being kicked around is to have an upgrade command in PowerShell. See #8663

**Comment by rjmholt** [comment]
> That said, this is really a PowerShell issue and not an extension issue. See PowerShell/PowerShell#8663

Closing as external

**Comment by gfmoore** [comment]
Thanks @rkeithhill.
I had just discovered wget which worked from within VS Code  terminal, but I had no idea about other methods.

I hadn't realised it was a PS message, I thought it was a message provided by VS Code, sorry my bad.

Thanks everyone. Hope this will prove useful to others
