### ISSUE TITLE
Run Powershell generates "Running the contributed command: 'Powershell.Debug.Start' Failed

### ISSUE THREAD

**Issue by brenttempleton** [PowerShell/vscode-powershell#3509]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I initially posted this in the [Azure Data Studio forum](https://github.com/microsoft/azuredatastudio/issues/16793), that is the only place I am seeing this, within VS Code it is working.

When running a Powershell file if I want to run the entire file it generates this error:
"Running the contributed command: 'Powershell.Debug.Start' failed.

https://user-images.githubusercontent.com/54143062/129629598-93053504-ab03-4dfb-b62b-ed97dbc16bdc.png

I can highlight all the content and use the "run selected" command and that works
I can put the content in a notebook cell and that works, just when I open a file and try to run the entire file without highlighting.

I have tried this on a few computers (co-workers, virtual machines, etc), so I'm pretty sure it is not something with my installation.

### PowerShell Version

```console
PS C:\> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS C:\> azuredatastudio --version

1.31.1
65fb22cc7c36db9c53af1ed2fdbdf48f66c682be
x64
PS C:\>
```

### Extension Version

```console PS> code --list-extensions --show-versions | Select-String powershell
ms-vscode.powershell@2021.5.1
PS C:\> azuredatastudio --list-extensions --show-versions | select-string powershell


ms-vscode.powershell@2021.8.0

PS C:\>
```

### Steps to Reproduce

Start New File in Azure Data Studio, Select Powershell, write any powershell command, try to run, above error is is produced.  When you select all and run selection, it works.

**Comment by andschwa** [comment]
Hey, the last validated extension that Azure Data Studio accepted was [v2021.2.2](https://github.com/microsoft/azuredatastudio/pull/14467), but your bug report indicates that you're running v2021.8.0. This isn't really supported. @Charles-Gagnon, do you know what's up? How is this user running a non-bundled version of the extension?

Also, @rjmholt is vaguely aware that debugging in ADS is not supported, so this seems like it's failing as expected.

**Comment by Charles-Gagnon** [comment]
@brenttempleton How did you install the extension?

It's likely they just installed the VSIX manually - the ADS gallery does still only point to 2021.2.2.

Debugging in ADS is disabled currently so that won't work unfortunately if you're relying on the VS Code debugging API. We're working on re-enabling that but no ETA currently.

**Comment by brenttempleton** [comment]
I have tried with older version of the extension as well, manually installed newer to see if that worked.

If debug is not supported, should still be able to run the script file without having to highlight all the text and then run selected (F8)

Thanks

Brent

**Comment by andschwa** [comment]
Launching the script file is still done through the debugging APIs of VS Code, so since ADS disables that, it's not supported.

**Comment by brenttempleton** [comment]
hmm, okay -- I guess this is now a feature request.  would that go into this forum or back on the ADS one?

Thanks

Brent

**Comment by andschwa** [comment]
ADS, for enabling debugging in their editor. What you're looking to do _should_ work just fine in normal Visual Studio Code with the regular PowerShell extension installed from the marketplace.
