### ISSUE TITLE
Syntax Highlighting Fails on Where-Object

### ISSUE THREAD

**Issue by richardcox13** [PowerShell/vscode-powershell#351]
### System Details

- Operating system name and version: Server 2012 R2
- VS Code version: 1.7.2
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

### Issue Description

Syntax highlighting of

    $s = $x['system.applicationHost'].sites.site | Where-Object -Property name -eq -Value  'Site1'

only highlights the `Where` of `Where-Object`:

![image](https://cloud.githubusercontent.com/assets/4578827/20709050/f44c30a2-b62a-11e6-885d-54e82078c9ca.png)

(It seems the `where` keyword is taking precedence over the cmdlet.)

**Comment by daviwil** [comment]
Hey @richardcox13, we're tracking this issue over at another repo: https://github.com/PowerShell/EditorSyntax/issues/22.  I'll close this issue in favor of the other, please subscribe to it to be notified when the issue gets fixed.  Thanks!

**Comment by richardcox13** [comment]
No problem... I did have a quick look, but not that far back :-)
