### ISSUE TITLE
Powershell extension won't start

### ISSUE THREAD

**Issue by technofab** [PowerShell/vscode-powershell#3526]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Running the extension, also in a new computer with a fresh install with latest compontens, i obtain this error:

The terminal process "C:\Program Files\PowerShell\6\pwsh.exe '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', 'Import-Module 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2021.8.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.8.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2021.8.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.8.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2021.8.2\logs\1629890092-e9128c08-26bb-4a7a-8b04-ec955914db821629890016515\EditorServices.log' -SessionDetailsPath 'c:\Users\user\.vscode\extensions\ms-vscode.powershell-2021.8.2\sessions\PSES-VSCode-29028-233472' -FeatureFlags @() '" terminated with exit code: 1.

### PowerShell Version

```console
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.19041.1151                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.19041.1151                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.59.1
```

### Extension Version

```console
Fresh install.
```

### Steps to Reproduce

Fresh install of code, and extension and running the extension.

**Comment by rjmholt** [comment]
> The terminal process "C:\Program Files\PowerShell\6\pwsh.exe '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', 'Import-Module 'c:\Users\user.vscode\extensions\ms-vscode.powershell-2021.8.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.8.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\user.vscode\extensions\ms-vscode.powershell-2021.8.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.8.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\user.vscode\extensions\ms-vscode.powershell-2021.8.2\logs\1629890092-e9128c08-26bb-4a7a-8b04-ec955914db821629890016515\EditorServices.log' -SessionDetailsPath 'c:\Users\user.vscode\extensions\ms-vscode.powershell-2021.8.2\sessions\PSES-VSCode-29028-233472' -FeatureFlags @() '" terminated with exit code: 1.

We need more information to understand this situation (the process terminating with exit code 1 just means it failed, which we already know since it won't start). Can you please follow the [troubleshooting doc](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#reproducing-the-issue) to provide more information about what's happening (such as error messages and logs)?

**Comment by technofab** [comment]
As for I understand, doing the command, must appear a new menu option called "SESSION"

![image](https://user-images.githubusercontent.com/14272723/131222155-b27f3f79-3e9a-4917-80ae-81a80c4c5c39.png)

**Comment by andschwa** [comment]
Please click that highlighted command, and then show me what you see after you've clicked it.

Also, I see in your screenshot that the extension has started, as the integrate console banner displayed and the prompt is available.

**Comment by technofab** [comment]
After I remove another time the extension and PS 6 too now works. I can upgrade.. to ps7 ?

**Comment by andschwa** [comment]
Oh, ok, cool. Maybe some weird state on your machine.

Yes, you _should_ update to PowerShell 7 since PowerShell 6 is not supported (at all, not just be the extension).
