### ISSUE TITLE
Cannot run debugger when offline

### ISSUE THREAD

**Issue by CendaL** [PowerShell/vscode-powershell#353]
When one is offline, the debugger does not start. Here is a log:
```
Connecting to port: 13464
Socket connect ERROR: Error: getaddrinfo ENOENT undefined:13464
Socket closed, shutting down.
```

**Comment by daviwil** [comment]
Hi Lukas, thanks for the report!  I'll take a look.

**Comment by daviwil** [comment]
Hey Lukas, I can't seem to reproduce this issue even after trying it a few different ways.  Some questions:

- How are you offline when you see the problem?  Airplane mode?  No available wifi/ethernet connection? 
- Which operating system are you running? 
- Are you using VS Code Stable or Insiders?  Can you try it with the Insiders release if you haven't yet?

Thanks!

**Comment by CendaL** [comment]
I run Win10 enterprise. I have tried it again now with LAN not connected and WiFi adapter disabled (previously WiFi was unavailable) in both stable and insider version. Logs are basically the same: [logs.zip](https://github.com/PowerShell/vscode-powershell/files/654877/logs.zip)

```
PSVersion                      5.1.14393.206                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.206                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1  
```

**Comment by daviwil** [comment]
Hey Lukas, can you try something for me?  Open the following file in VS Code:

`c:\Users\<your username>\.vscode\extensions\ms-vscode.PowerShell-0.7.2\out\debugAdapter.js`

Go down to line 24, it should look like this:

```javascript
let debugServiceSocket = net.connect(sessionDetails.debugServicePort);
```

Change that line so that it looks like this:

```javascript
let debugServiceSocket = net.connect(sessionDetails.debugServicePort, '127.0.0.1');
```

Save the file then completely restart VS Code and try debugging a PowerShell script again.  Any improvement?  If so, I'll try to include a fix for today's release.

**Comment by CendaL** [comment]
Yep - that works for me!

**Comment by CendaL** [comment]
Yep, that works for me!

**Comment by daviwil** [comment]
Awesome, thanks for confirming!  I'll get a fix in for that :)
