### ISSUE TITLE
Current directory is included in PowerShell "launch" option; breaking launch configurations that run a command 

### ISSUE THREAD

**Issue by JamesLear92** [PowerShell/vscode-powershell#3537]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I like to run PowerShell scripts into external windows. I have been using the same launch configs for years now without problem, but suddenly none of them now work. Here is an example launch.json:

    {
        "version": "0.2.0",
        "configurations": [
            {
                "type": "PowerShell",
                "request": "launch",
                "name": "PS5",
                "script": "Start-Process",
                "args": [
                    "-FilePath ($Env:SystemRoot + '\\system32\\WindowsPowerShell\\v1.0\\powershell.exe')",
                    "-Argumentlist '-NoExit -NoProfile -ExecutionPolicy Bypass -File \"${file}\"'"
                ]
            }
        ]
    }

What should happen when running launching a .PS1 file with the debug option, is this:

    PS C:\Test> Start-Process -FilePath ($Env:SystemRoot + '\system32\WindowsPowerShell\v1.0\powershell.exe') -Argumentlist '-NoExit -NoProfile -ExecutionPolicy Bypass -File "c:\Users\TestUser\desktop\TestScript.PS1"'
    
However it actually runs:

    PS C:\Test> C:\Test\Start-Process -FilePath ($Env:SystemRoot + '\system32\WindowsPowerShell\v1.0\powershell.exe') -Argumentlist '-NoExit -NoProfile -ExecutionPolicy Bypass -File "c:\Users\TestUser\desktop\TestScript.PS1"'

Which of course leads to the error message:

    C:\Test\Start-Process: The term 'C:\Test\Start-Process' is not recognized as a name of a cmdlet, function, script file, or executable program.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.59.1
3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2021.8.2
```

### Steps to Reproduce

Use the Launch config from above, and select it as the debug option. Then attempt to run any **SAVED** script.

**Comment by JamesLear92** [comment]
Issue is not present in:
ms-vscode.powershell-preview@2021.8.0

Is present in:
ms-vscode.powershell-preview@2021.8.3

**Comment by andschwa** [comment]
Oh, crap, sorry about that.

**Comment by rkeithhill** [comment]
I don't think this has anything to do with the `cwd` field.  The `script` field name was picked because we wanted to allow not just a filename but arbitrary script e.g. `"script": "Invoke-Pester"`.  It seems that something (either the extension or PSES) is prepending a path to the `script` field value assuming it always specifies a path to a PS1 file.  Whatever it is, It should not make that assumption.  

BTW this only seems to happen when you specify `"args":` so there must be something about argument processing that is causing this.  Ah, this is from the PSES log file:
```
2021-08-31 14:53:45.541 -06:00 [VRB] Prepending working directory C:\Users\Keith\.vscode\extensions\ms-vscode.powershell-2021.8.2\examples\Tests to script path Invoke-Pester
```
Yeah, that's yer problem right there.

**Comment by andschwa** [comment]
Interesting...I will dig into PSES changes and see how we broke it. Thanks Keith!

**Comment by andschwa** [comment]
Ah, it was https://github.com/PowerShell/PowerShellEditorServices/pull/1540/commits/da439373a5dc0d83e8a53ad9417e5a34973afdba 🙃

**Comment by andschwa** [comment]
All right. Fixed this and covered it with a test. Will get it into the next preview.

**Comment by andschwa** [comment]
Thanks for the issue! Keep them coming.

**Comment by JamesLear92** [comment]
Awesome work, thanks for the quick fix.

**Comment by andschwa** [comment]
This fix is available in the preview that went out yesterday!
