### ISSUE TITLE
Powershell debugger is freezing in VS code

### ISSUE THREAD

**Issue by olegk25** [PowerShell/vscode-powershell#3539]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

PowerShell debugger becomes absolutely irresponsive after ANY breakpoint stop.

### PowerShell Version

```console
Name                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      5.1.19041.1151                                                                                                                
PSEdition                      Desktop                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                       
BuildVersion                   10.0.19041.1151                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                               
WSManStackVersion              3.0                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                           
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
Extension version: 2021.8.2
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
```

### Extension Version

```console
ms-vscode.powershell@2021.8.2
```

### Steps to Reproduce

Consider a very simple script like

Get-ChildItem -Path 'c:\' | ForEach-Object {
    $f = $_.FullName
    $f
}

1. Put a breakpoint on line 2 ($f = $_.FullName) and hit F5. 
2. The breakpoint is reached.
3. Hit the Step Over (F10) - debugger hangs. the same is with F5

c

**Comment by olegk25** [comment]
![image](https://user-images.githubusercontent.com/43548822/131571421-75cee8c0-ba0d-4827-9ac9-923cd753b740.png)

**Comment by olegk25** [comment]
vscode-powershell.log:

8/31/2021 4:45:39 PM [NORMAL] - Session file found
8/31/2021 4:45:39 PM [NORMAL] - Registering terminal close callback
8/31/2021 4:45:39 PM [NORMAL] - powershell.exe PID: 24340
8/31/2021 4:45:39 PM [NORMAL] - Language server started.
8/31/2021 4:45:39 PM [NORMAL] - Registering terminal PID log callback
8/31/2021 4:45:39 PM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_t3wn3kr4.o2c...
8/31/2021 4:45:39 PM [NORMAL] - Language service connected.
8/31/2021 4:45:39 PM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_t3wn3kr4.o2c","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_gvv5irya.nib"}
8/31/2021 4:45:41 PM [WARNING] - Invalid Version: null

EditorServices.log:

2021-08-31 16:46:51.922 -04:00 [WRN] Runtime exception occurred while executing command
2021-08-31 16:46:51.927 -04:00 [ERR] Exception occurred while executing debugger command
2021-08-31 16:46:51.928 -04:00 [ERR] Execution of the following command(s) completed with errors:

    Get-Variable -Scope 1


2021-08-31 16:46:51.928 -04:00 [WRN] Runtime exception occurred while executing command
2021-08-31 16:46:51.933 -04:00 [ERR] Exception occurred while executing debugger command
2021-08-31 16:46:51.934 -04:00 [ERR] Execution of the following command(s) completed with errors:

    Get-Variable -Scope 1

**Comment by andschwa** [comment]
Hi,

Can you reproduce this using PowerShell Core? I cannot. About to try with Windows PowerShell.

**Comment by andschwa** [comment]
Also @olegk25 could you please provide more [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)? Specifically please turn on diagnostic logging. It's helpful to see where it failed, but I want to know what it was doing as it got to that point.

**Comment by olegk25** [comment]
Hello @andschwa , I've found a workaround by removing (disabling did not help) all other extensions. Now I'll be adding them back and see if I can reproduce the issue again. And thank you for the diagnostics tip :)

**Comment by andschwa** [comment]
Hey that's interesting...let me know which one you find that causes the issue!

**Comment by olegk25** [comment]
well, no luck catching it again so far... Maybe it was something else. Closing the ticket as non-reproducible

**Comment by andschwa** [comment]
There's a new version of the preview extension out today too!
