### ISSUE TITLE
Provide a simple way to execute scripts when a folder hasn't been opened

### ISSUE THREAD

**Issue by chrmarti** [PowerShell/vscode-powershell#354]
_From @TheKnightCoder on December 1, 2016 11:35_

- VSCode Version: 1.8.0-insider
- OS Version: Windows 7

Steps to Reproduce:

1. install powershell extension
2. make a script using $PSScriptRoot   (directory of script)
3. Highlight code and press F8

$PSSScriptRoot is always C:\Program Files (x86)\Microsoft VS Code Insiders

This messes up all my scripts. and this is the only easy way of running code. The only way I can get the script to run correctly is to open the folder and run debug. 

Love visual code but why is there no way of running code easily

_Copied from original issue: Microsoft/vscode#16319_

**Comment by daviwil** [comment]
Have you tried running your script in the debugger (F5)?  Here's what I see:

![image](https://cloud.githubusercontent.com/assets/79405/20804241/fa9f24be-b7a6-11e6-9306-1d1f8c078918.png)

When you run script code with F8, it's basically just executing that text directly so no `$PSScriptRoot` gets set.  Even the ISE doesn't populate `$PSScriptRoot` in that case.  Running the script in the debugger causes the file itself to be executed so `$PSScriptRoot` is set to the expected path.

**Comment by daviwil** [comment]
Sorry, didn't read all of the initial report, seems like you figured out that it works in the debugger.  Does this work correctly for you in the ISE or any other editor?

**Comment by TheKnightCoder** [comment]
Thanks this has helped. So I guess my issue isn't as bad as I thought. 
basically I would like to be able to right click a script "Open with code" then press F5 to run.
Currently you must right click the folder the script is in, "open with code", select the file then press F5.
So opening a single file with code feel kinda useless

**Comment by daviwil** [comment]
Good point, this is one of the confusing aspects of VS Code for people who move over from the ISE.  I'll see if I can find a good way to allow script execution easily without opening a folder.

**Comment by daviwil** [comment]
I just created another issue to track this request, forgot that this one already existed!  I'll close this in favor of the other.

https://github.com/PowerShell/vscode-powershell/issues/359
