### ISSUE TITLE
ANSI Escape Code received from the SSH from the Linux's BASH breaks the output in the PowerShell Integrated Console

### ISSUE THREAD

**Issue by michal037** [PowerShell/vscode-powershell#3543]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I wrote a very simple script to execute the `ssh` command on the `Raspberry Pi OS`. When I run this script from the new `Windows Terminal` (with `pwsh`) or the integrated `VSCode` terminal (with `pwsh`), everything works fine. The problem only occurs when I run this script via `PowerShell Integrated Console`. `ssh` is configured with `Key-Based Authentication`. The problem is that the script output in `PowerShell Integrated Console` is broken. In my opinion `PowerShell Integrated Console` does not remove or convert `ANSI Escape Code` properly. Which results in the destruction of the result text.

While generating the logs, I disabled all extensions except `PowerShell`.

---

VSCode does not recognize this setting. Therefore, I do not provide this log.
[Provide Language Server Protocol payload logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md): `"powershell editor services.trace.server":"verbose"`

---

This result is also empty:
```
PS C:\Users\michal> $psEditor.EditorServicesVersion
PS C:\Users\michal>
```

---

Below, in the logs section, I attach the logs, my VSCode settings and the script.

### PowerShell Version

```console
PS C:\Users\michal> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS C:\Users\michal> code --version
1.60.0
e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
x64
```

### Extension Version

```console
PS C:\Users\michal> code --list-extensions --show-versions
funkyremi.vscode-google-translate@1.4.13
golang.go@0.27.2
liviuschera.noctis@10.40.0
ms-python.python@2021.9.1191016588
ms-python.vscode-pylance@2021.9.0
ms-toolsai.jupyter@2021.8.2031190714
ms-toolsai.jupyter-keymap@1.0.0
ms-vscode-remote.remote-ssh@0.65.7
ms-vscode-remote.remote-ssh-edit@0.65.7
ms-vscode.cpptools@1.6.0
ms-vscode.powershell@2021.8.2
njpwerner.autodocstring@0.5.4
SanaAjani.taskrunnercode@0.3.0
```

### Steps to Reproduce

1. Configure any `Debian OS` (with `BASH`) and turn on the `ssh` server on it
2. Open `VSCode` with `PowerShell` extension on Windows
3. Save this source to file and edit it with VSCode:

```powershell
# Windows 10; PowerShell 7.1.4
# Build and run the example program on the `Raspberry Pi Computer`

ssh pi @"
hostname
date
"@
```

4. Run this script as file in the `PowerShell Integrated Console` so that Linux returns you the result as when calling a normal `ssh` command

---

`pi` hostname doesn't matter

### Visuals

![bug](https://user-images.githubusercontent.com/7441419/131950456-3b1afde1-f7d4-40d0-b5d1-feb298282889.gif)

### Logs

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/7103331/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/7103332/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/7103333/vscode-powershell.log)

---
[BuildAndRun.ps1.txt](https://github.com/PowerShell/vscode-powershell/files/7103345/BuildAndRun.ps1.txt)
[settings.json.txt](https://github.com/PowerShell/vscode-powershell/files/7103335/settings.json.txt)

---

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (26.05GB free)|
|Process Argv|--crash-reporter-id 115d5e1c-df42-47e2-8ae1-76ba0eec26f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2021.8.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
javagetstartedt:30351793
vsdyn420:30356812
pydsgsc2:30361791
vscus224:30358039
```
</details>

**Comment by andschwa** [comment]
> VSCode does not recognize this setting. Therefore, I do not provide this log.
> [Provide Language Server Protocol payload logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md): `"powershell editor services.trace.server":"verbose"`

Hi, while Code won't recognize and highlight it, it's a valid option and enables tracer logs on the server. Please enable this setting and provide these logs. Thanks!

**Comment by andschwa** [comment]
> This result is also empty:
> 
> ```
> PS C:\Users\michal> $psEditor.EditorServicesVersion
> PS C:\Users\michal>
> ```

If this is empty it means you're executing in a regular `pwsh` shell in VS Code, and _not_ in the integrated terminal. Can you please confirm your bug is extant in the integrated terminal (and provide a screenshot)?

Thanks!

**Comment by andschwa** [comment]
> This result is also empty:
> 
> ```
> PS C:\Users\michal> $psEditor.EditorServicesVersion
> PS C:\Users\michal>
> ```

If this is empty it means you're executing in a regular `pwsh` shell in VS Code, and _not_ in the integrated terminal. 

Per your attached screenshot, this is happening in a regular `pwsh` shell, and _not_ in the integrated terminal. Therefore this is not an extension-specific bug. Transferring to VS Code... FYI @TylerLeonhardt

**Comment by michal037** [comment]
> Hi, while Code won't recognize and highlight it, it's a valid option and enables tracer logs on the server. Please enable this setting and provide these logs. Thanks!

Thank you for making this clear.

I raised the bug again with the following settings:
```json
{
    "powershell.developer.editorServicesLogLevel": "Diagnostic",
    "powershell editor services.trace.server":"verbose"
}
```

log: 
[PowerShell_Editor_Services.txt](https://github.com/PowerShell/vscode-powershell/files/7109863/PowerShell_Editor_Services.txt)

> If this is empty it means you're executing in a regular pwsh shell in VS Code, and not in the integrated terminal. Please run it in the integrated terminal instead.

You're right! My bad.

```
PS C:\Workspace\github\driver-ST7735S> $psEditor.EditorServicesVersion


Major  Minor  Build  Revision
-----  -----  -----  --------
2      4      9      0

PS C:\Workspace\github\driver-ST7735S>
```

**Comment by andschwa** [comment]
Could you try getting the output of `stty` for us? Like what @SeeminglyScience describes here: https://github.com/PowerShell/PowerShellEditorServices/pull/1571#issuecomment-914498100

**Comment by michal037** [comment]
> Could you try getting the output of `stty` for us? Like what @SeeminglyScience describes here: [PowerShell/PowerShellEditorServices#1571 (comment)](https://github.com/PowerShell/PowerShellEditorServices/pull/1571#issuecomment-914498100)

I don't have `stty` on Windows. Therefore, it won't work for me in PowerShell.

I found a better solution:

1. Download PuTTY: https://www.chiark.greenend.org.uk/~sgtatham/putty/
2. Run putty.exe
3. Change logging: Session -> Logging -> Session logging -> All session output
4. Set host: Session -> Host Name
5. Open session

---

### printable

```
=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2021.09.07 21:30:50 =~=~=~=~=~=~=~=~=~=~=~=
login as: pi
pi@192.168.0.15's password: 
Linux raspberrypi 5.10.52+ #1441 Tue Aug 3 18:08:18 BST 2021 armv6l

Last login: Tue Sep  7 21:29:49 2021 from 192.168.0.172

pi@raspberrypi:~ $ hostname
raspberrypi
pi@raspberrypi:~ $ date
Tue  7 Sep 21:31:03 CEST 2021
pi@raspberrypi:~ $ exit
logout
```

---

### raw

```
=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2021.09.07 21:29:41 =~=~=~=~=~=~=~=~=~=~=~=
login as: pi
pi@192.168.0.15's password: 
Linux raspberrypi 5.10.52+ #1441 Tue Aug 3 18:08:18 BST 2021 armv6l

Last login: Tue Sep  7 21:22:55 2021 from 192.168.0.172

]0;pi@raspberrypi: ~[01;32mpi@raspberrypi[00m:[01;34m~ $[00m hostname
raspberrypi
]0;pi@raspberrypi: ~[01;32mpi@raspberrypi[00m:[01;34m~ $[00m date
Tue  7 Sep 21:29:59 CEST 2021
]0;pi@raspberrypi: ~[01;32mpi@raspberrypi[00m:[01;34m~ $[00m exit
logout

```

![raw](https://user-images.githubusercontent.com/7441419/132401044-82897f82-d983-4dd5-a91f-7b6ff78a27b4.png)

---

[putty.log](https://github.com/PowerShell/vscode-powershell/files/7123942/putty.log)
[raw_putty.log](https://github.com/PowerShell/vscode-powershell/files/7123943/raw_putty.log)

**Comment by SeeminglyScience** [comment]
> > Could you try getting the output of `stty` for us? Like what @SeeminglyScience describes here: [PowerShell/PowerShellEditorServices#1571 (comment)](https://github.com/PowerShell/PowerShellEditorServices/pull/1571#issuecomment-914498100)
> 
> I don't have `stty` on Windows. Therefore, it won't work for me in PowerShell.

Oh I thought you were on linux my bad, not related then. Might be [console mode](https://docs.microsoft.com/en-us/windows/console/console-modes) related. There isn't really a quick way to test that like there is for stty though afaik

**Comment by andschwa** [comment]
Can you confirm this is still reproducing with v2021.9.0? I mean, it probably does, but it'd be helpful to know. Otherwise we're hoping the editor services pipeline work (https://github.com/PowerShell/PowerShellEditorServices/issues/1295) _may_ fix it as it replaces much of our custom console host implementation with re-use of PowerShell's own (which clearly works).

**Comment by michal037** [comment]
> Can you confirm this is still reproducing with v2021.9.0?

I have tested and the problem persists.


https://user-images.githubusercontent.com/7441419/132886654-6c4e4e32-b9c3-4788-9a1b-ac0334aa85ce.mp4

**Comment by andschwa** [comment]
Thought so. We'll have to try to repro it, but also are hopeful the work Rob is doing may fix it. Unfortunately these kinds of issues tend to be the most difficult to fix.
