### ISSUE TITLE
Debug Console Output

### ISSUE THREAD

**Issue by TheKnightCoder** [PowerShell/vscode-powershell#355]
### System Details

- Operating system name and version:
- VS Code version: 1.8.0-insider
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:

### Issue Description

I am experiencing a problem with powershell Debug console output.
When I run a script with no break points the last few write-hosts/write-outputs do not display in the debug console.
for instance if I make a script that only has one write-host there will be no output in the debug console:
Write-Host "hi"

(this does not happen in the powershell ISE)

I can add 
Start-Sleep -s 1
at the end and it works

**Comment by daviwil** [comment]
I just fixed this issue but it hasn't been released yet: https://github.com/PowerShell/vscode-powershell/issues/284.  I'm planning to push out a new update at the end of next week.

You can try a build which has the fix here: https://github.com/PowerShell/vscode-powershell/issues/284#issuecomment-263687307
