### ISSUE TITLE
Powershell terminal is default even though git bash is set to default

### ISSUE THREAD

**Issue by u84six** [PowerShell/vscode-powershell#3550]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

After installing the Powershell extension and using the terminal, whenever I start vscode and open terminal, it defaults to Powershell even though I have Git Bash set as default.

This is on Windows 10 using the latest vscode

### PowerShell Version

```console
PSVersion                      5.1.18362.1171
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1171
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363
```

### Extension Version

```console
ms-vscode.powershell@2021.8.2
```

### Steps to Reproduce

1. Install PS extension
2. Open terminal
3. Open a ps prompt
4. Open a bash prompt
5. Click on Bash in terminal list
6. Select drop-down menu and choose "Select Default Profile"

Whenever I start vscode and open terminal, PS is the default

**Comment by andschwa** [comment]
Are you opening VS Code with a PowerShell file in the foreground? If so that starts the extension and so the integrated terminal as well.

**Comment by andschwa** [comment]
Ah, this looks like it was a bug upstream in VS Code, and has since been resolved: https://github.com/microsoft/vscode/issues/132607
