### ISSUE TITLE
vscode-powershell extension Installation failing

### ISSUE THREAD

**Issue by yarecki** [PowerShell/vscode-powershell#3568]
I'm trying to install the extension on an isolated system using a downloaded vsix file. VSCode version is 1.50.1 and the extension version I'm installing is 2021.8.2. Installation fails with following error

```
(node:40632)[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.aloc(),Buffer.allocUnsafe(), or Buffer.from() methods instead. 
```

Anything I can do on my end to get the extension install successfully?

**Comment by rjmholt** [comment]
> Installation fails with following error

I believe what you're seeing there is warning and not related to the actual issue.

> VSCode version is 1.50.1

The 2021.8.2 release of the PowerShell extension [only supports VSCode version 1.53 and up](https://github.com/PowerShell/vscode-powershell/commit/ec63b415865b6a6292a9fda2352fd5739c7f8d83).

Please try upgrading your VSCode installation (the latest is 1.56) and installing the PowerShell extension then.
