### ISSUE TITLE
Closing round bracket breaks syntax highlighting on ValidatePattern parameter attribute

### ISSUE THREAD

**Issue by jlucktay** [PowerShell/vscode-powershell#357]
### System Details

- Operating system name and version: Windows 10 Pro, version 1607, build 14393.447
- VS Code version: 1.7.2
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`: 

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with syntax highlighting inside a ValidatePattern attribute on a parameter.

The highlighting seems to break if I make use of a closing round bracket `)` inside the validation pattern.

In that part of the pattern, I want the URL to optionally have `videos/` in it.

Here is the code from the screenshots, to save from having to type it out when reproducing:
```
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Convert-UrlForApi {
    param(
        [Parameter(Mandatory=$true)]
        [ValidatePattern('^http:\/\/www.giantbomb.com\/(videos\/)?[a-z0-9\-]+\/[0-9]+-')]
        [ValidateScript({[Uri]::IsWellFormedUriString($($_), [UriKind]::Absolute)})]
        [String]$Url
    )

    if ($Url -match "\/3030\-[0-9]+\/$") {
        return "http://www.giantbomb.com/api/game$($Matches[0])"
    } elseif ($Url -match "\/2300\-[0-9]+\/$") {
        return "http://www.giantbomb.com/api/video$($Matches[0])"
    } else {
        return $null
    }
}
```

Please see the screenshots below.

The function itself executes fine and works absolutely as expected and desired with the round bracket in place, so it's just the syntax highlighter getting confused about the round bracket inside the pattern string.

#### OK without the round bracket
![image](https://cloud.githubusercontent.com/assets/460028/20867345/50f4ab8c-ba3a-11e6-98aa-a03f2ff59908.png)

#### Not OK with the round bracket
![image](https://cloud.githubusercontent.com/assets/460028/20867349/5a6342aa-ba3a-11e6-8150-7e4f55dc5ac7.png)

**Comment by tonylea** [comment]
I've also noticed this issue.

Using:
- Windows 10 Pro
- VS Code version: 1.9.1
- PowerShell extension version: 0.9.0

Validate pattern am using: `[ValidatePattern("^([0-9a-fA-F]{2}[:-]{0,1}){5}[0-9a-fA-F]{2}$")]`

**Comment by cantrellj** [comment]
Appears to happen in ValidateScript also

System Details
Operating system name and version: Windows 10 Pro 10.0.10586.0
VS Code version: 1.19.3
PowerShell extension version: 1.6.0
Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.0.10586.1295
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.1295
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
![image](https://user-images.githubusercontent.com/28454901/36555354-57ce3144-17c7-11e8-925e-3bb58db1e25c.png)

**Comment by rkeithhill** [comment]
Syntax highlighting is being managed out of the https://GitHub.com/powershell/editorsyntax project.  @tylerl0706 Can you move this issue over to that repo?

**Comment by gazm81** [comment]
This is still an issue in VS code 1.21.1 with PowerShell plugin 1.60.
Doesn't appear on any other IDE we have tested.

**Comment by tylerl0706** [comment]
This issue was moved to PowerShell/EditorSyntax#74
