### ISSUE TITLE
Set-PnPPage gives 'Method not found' issue in VSC integrated PS

### ISSUE THREAD

**Issue by timtatam** [PowerShell/vscode-powershell#3594]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Hi guys,
I get an issue with the Set-PnPPage cmdlet when I use the PS integrated console v2021.9.0 but not when I use the Windows PS.
**Cmdlet:** Set-PnPPage -Identity "Collaboration-News" -ContentType "Collaboration News Post" -PromoteAs Template

**Issue:**
`Set-PnPPage : Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> Enumerator.MoveNextAsync()'.
At C:\Users\i01002441\Dev\EH_O365_Scripts\SharePointOnline\hotfix\FixContentTypeMissingOnSitePages.ps1:48 char:5
+     Set-PnPPage -Identity "Collaboration-News" -ContentType "Collabor ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPPage], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.SetPage`

BR Timo

### PowerShell Version

```console
the same for Windows and VSC
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.60.2
7f6ab5485bbc008386c4386d08766667e155244e
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.9.0
```

### Steps to Reproduce

simply run the cmdlet

### Logs

```CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Set-PnPPage                                        1.7.61     PnP.PowerShell```

**Comment by andschwa** [comment]
This looks like the same issue as #3510, or at least close enough to track there too.
