### ISSUE TITLE
Enable the `OpenExamplesFolder` unit test

### ISSUE THREAD

**Issue by andschwa** [PowerShell/vscode-powershell#3598]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Added but also disabled in #3570:

https://github.com/PowerShell/vscode-powershell/blob/bf1091669aa8b0983bc17d85b156f847ffdae115/test/core/paths.test.ts#L14-L19

**Comment by andschwa** [comment]
I need to delete that test, it's never going to work.

**Comment by SydneyhSmith** [comment]
#4420
