### ISSUE TITLE
When extension (any extesion) is reloaded old PowerShell sessions are not discarded

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3601]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When an extension (not PowerShell one) is updated it often requires a restart of code. When that happens you can notice that old PowerShell/PowerShell Integrated Console are left as they were and new ones are added to the list. 

![image](https://user-images.githubusercontent.com/15063294/135764159-6d9f9e0e-5636-4011-a351-ebe5ae251eaf.png)

This changed in some recent version of code - as I don't remember seeing this earlier. 

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.60.2
7f6ab5485bbc008386c4386d08766667e155244e
x64
```

### Extension Version

```console
ironmansoftware.powershell-universal@2.3.0
ms-vscode.powershell@2021.9.2
ms-vscode.powershell-preview@2021.9.2
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

1. Open Code
2. Work as usual
3. Wait till some extension requires update
4. press the button to restart 
5. Notice how the powershell session is left as is with all errors
6. Notice how new powershell sessions are added

**Comment by andschwa** [comment]
I believe this changed when VS Code upstream enabled reconnection to terminals. So Code no longer throws away terminals on reconnect, it instead saves them and brings them back. But it doesn't bring back the connection to Editor Services, so our extension is doing what it's always done: spawn an Integrated Console to host Editor Services and connect. This behavior was fine when Code would throw away the old terminals for us, now we need to figure out a better solution.

**Comment by andschwa** [comment]
Yup, it's this work: https://github.com/PowerShell/vscode-powershell/issues/3360 I'm going to mark this as a duplicate as the work to be done is known and triaged.
