### ISSUE TITLE
UI width, possibly word wrap, in PowerShell Integrated console is causing an input error while debugging

### ISSUE THREAD

**Issue by LNGU** [PowerShell/vscode-powershell#3602]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I have a PowerShell script that prompts a user input via Read-Host command. 
I reduced the width of the PowerShell integrated console terminal just right at the edge of the prompt and it returns error. **however, by widening the UI width fixes the issue.**

Please see below for the error:

Do you also want to generate FULL PERMS html reports from the Delegation dataset? (y/n):y **(<-- my input would sit very edge of the terminal UI)**
Read-Host Prompt failed, check inner exception for details
At \\execweb\Toolbox\frhwang\0NetworkRepo\ExecMailboxAudit-onPrem\Start-ESSMailboxAudit.
ps1:71 char:18
+ ... nSection5 = Read-Host -Prompt "Do you also want to generate FULL PERM ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Read-Host], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.PowerShell.Commands.ReadHostCo
   mmand

### PowerShell Version

```console
$PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
code --version
1.60.2
7f6ab5485bbc008386c4386d08766667e155244e
x64
```

### Extension Version

```console
code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2021.9.2
```

### Steps to Reproduce

1. while in debugging, invoke a read-host prompt with some prompt sentence and have the input cursor sit at the very last line of the available width of the terminal. (if cursor warp to the next line, invoke it again)
2. type something as an input. it will trigger the read-host prompt failed error.
3. you can immediately remedy this by widening the UI or shortening it for the prompt to warp to the next line.

I can reproduce this at will. please contact me if you have a hard time reproducing it.

### Visuals

![image](https://user-images.githubusercontent.com/3292835/135772193-07c5c1f6-6a16-496e-ad56-295ff342d749.png)

**Comment by andschwa** [comment]
Hi @LNGU, could you please share a full repro with us? Either the script you were using or a scaled down one which you know to repro. Thank you!

**Comment by rjmholt** [comment]
Yeah the following will help us to reproduce the issue:

- The `Read-Host` part of the script with the full prompt
- The result of `[console]::windowwidth`
- The result of `gmo PSReadLine` and `gcm PSConsoleHostReadLine`

**Comment by LNGU** [comment]
so dragging UI has to happen. I had to drag between 73 and 72 in micro movement to repro this. If there is a value that tracks in smaller increments than whole numbers, please let me know.
```
PS C:\temp\ExecMailboxAudit-onPrem> [console]::windowwidth
73
PS C:\temp\ExecMailboxAudit-onPrem> Read-Host -Prompt "Do you want to generate html reports from the Delegation dataset? (y/n)"                 
Do you want to generate html reports from the Delegation dataset? (y/n):**Read-Host: Prompt failed, check inner exception for details**  (my response y was overwritten by the error msg)            
PS C:\temp\ExecMailboxAudit-onPrem> [console]::windowwidth
72
```
```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove…

```
```
CommandType     Name                                               Version    Source    
-----------     ----                                               -------    ------    
Function        PSConsoleHostReadLine                              2.1.0      PSReadLine
```
