### ISSUE TITLE
Outline should also support #Region

### ISSUE THREAD

**Issue by emrgcl** [PowerShell/vscode-powershell#3604]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Outline pane in vscode should also include / support #region blocks in Powershell. 

Outline is a great tool for navigating hundreds of lines. If there are hundred of lines the Powershell Developer utilises region of code blocks using the #region / #endregion blocks to navigate easier. If this is implemented in the outline it will add a lot value to the PowerShell developer.

**Comment by andschwa** [comment]
Oh that's a great idea! Do you know what it would look like? I'm going to mark this as up for grabs because I'd happily take a PR that enabled it, but am unsure of when I'd be able to get to it myself.
