### ISSUE TITLE
Add troubleshooting note about slow IntelliSense results in PowerShell v5

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#361]
I've heard from a couple people recently that IntelliSense results are sometimes slow to return.  I'd like to investigate the cause of that issue.

@GHRoss: could you give me more details about the IntelliSense slowness that you reported [here](https://github.com/PowerShell/vscode-powershell/issues/284#issuecomment-263896329)?  Does it only give you 30 seconds delay on the first time you get IntelliSense in an editing session or every single time?  Can you give me a more complete picture of what's going on?

It'd be great if you could capture some logs for me by following [these instructions](https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us).  Start up a fresh VS Code session and reproduce the IntelliSense logs then zip them up an email them to me at `daviwil [at] microsoft.com`.

**Comment by GHRoss** [comment]
Hi David,

No problem. I've sent the logs over to you.

I can only describe the problem as typing, for example...

Get-Chil

And then having to wait for Intellisense to catch up.

**Comment by GHRoss** [comment]
I'm actually seeing very different results on both computers.

Here is what I see on my current machine...

![1](https://cloud.githubusercontent.com/assets/5963184/20968549/dc3860c8-bc7c-11e6-859d-7cdae4a60396.png)

And here is what I see on my old machine (and believe to be what I should be seeing).

![2](https://cloud.githubusercontent.com/assets/5963184/20968566/e8fbdbb4-bc7c-11e6-92c4-9f55e2ba4c2c.png)

**Comment by daviwil** [comment]
Judging from the logs, it seems that IntelliSense takes about 10 seconds to return for cmdlet names but it's pretty much instant for cmdlet parameters.  Is that correct?

This is pretty weird, my assumption was that Get-Help was causing a problem but it seems that the IntelliSense engine is lagging behind.

**Comment by daviwil** [comment]
By the way, if you go into the ISE on the same machine do you get the same IntelliSense slowness?

**Comment by GHRoss** [comment]
In ISE I get...

Intellisense...

Stopping Intellisense...

Intellisense timed out.

This all happens with about 5 seconds.

**Comment by GHRoss** [comment]
Interestingly I was searching around for a potential solution to this and came across the following article...

http://windowsitpro.com/windows-client/solve-intellisense-hangs-integrated-scripting-environment

I did as it said and deleted all the files.

Upon trying Intellisense again, it hangs for much longer and then the files in that folder are all regenerated.

Then trying Intellisense a final time gives the same error as my previous post.

I have a feeling this is a problem with my PC rather than the extension.

**Comment by daviwil** [comment]
Thanks, that's really helpful!  I'll ask someone if there's a known issue in PowerShell 5.0.

**Comment by daviwil** [comment]
Looks like this is indeed a known issue with PowerShell 5.  It's been fixed in PowerShell 5.1 which explains why IntelliSense works fine for you on your other machine.

**Comment by GHRoss** [comment]
That's great news! Although I'm in two minds about updating to WMF 5.1 as it's still in preview, my experience can't get much worse at the moment, so I think I'm going to update it as soon as possible.

I guess that means this bug can be closed?

**Comment by daviwil** [comment]
I'll keep it open to remind myself to put a note in the Troubleshooting document about this in case other people have issues.  Thanks again for your help investigating the issue!
