### ISSUE TITLE
Tab completion fails in certain scopes

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#362]
_From @bobbytreed on December 6, 2016 17:26_

Not sure if this has been reported, but it is a very odd specific case.

If you create a script (Untitled.ps1) and put one line in it $host.EnterNestedPrompt().
When you run the script you will enter a nested prompt, obviously, at that point if you create any variables you will not be able to tap complete to them.  You can see them with Get-VAriable and you can type them in manually to retrieve them, but tab completion fails.  This only happens with psreadline, if I remove the module while in the nestedprompt, tab completion works.  This can also affect debugging scenarios where you are nested as well.

Thanks

Bobby

_Copied from original issue: Microsoft/vscode#16688_

**Comment by daviwil** [comment]
Hey @bobbytreed, I haven't heard of this issue before, will investigate.  Thanks!

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.

**Comment by BjornNordblom** [comment]
Issue fixed in Powershell 7, but still an issue with 5.1.18362.628. Tested with VSCode 1.44.1 and PS extension 2020.3.0.

**Comment by TylerLeonhardt** [comment]
@SeeminglyScience do you have any thoughts about this?
