### ISSUE TITLE
PSIC "Run Hint" should show a dot source to more accurate depict what is happening

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3625]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

When using a run action, the script being run is shown in the PSIC as `PS> C:\path\to\script`. This is misleading to expect the variables would not return to the PSIC, and confusion if you didn't initialize your variables properly

Context:
![image](https://user-images.githubusercontent.com/15258962/137948145-17e55b40-8ffc-411e-89e9-5351c4f92d9f.png)
![image](https://user-images.githubusercontent.com/15258962/137948164-bcabd5bf-6e71-429f-9dc6-9af199a44f6b.png)
![image](https://user-images.githubusercontent.com/15258962/137948176-9aeec203-e124-40a6-8dc1-a6aa7a08202a.png)

### Proposed Design

When a run task is started in the PSIC, the path should show as ". C:\path\to\script" to more accurately reflect that the script will run in the PSIC scope and preserve variables/state upon exit

**Comment by andschwa** [comment]
Hey @JustinGrote I think we actually fixed this! Can you please confirm?

**Comment by JustinGrote** [comment]
@andschwa can confirm at least a few spot checks appear that this now appears as expected to avoid confusing the user. Thanks!
![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/00d89aaa-7ccb-4bc6-9c72-9c02114adacd)
