### ISSUE TITLE
Unable to see Write-Host output

### ISSUE THREAD

**Issue by ssaari** [PowerShell/vscode-powershell#363]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: Caption        : Microsoft Windows Server 2012 R2 Standard
CSDversion     :
BuildNumber    : 9600
OSArchitecture : 64-bit
- VS Code version: 1.7.2
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/638243/logs.zip)

PSRemotingProtocolVersion      2.2
```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

### Issue Description

I am experiencing a problem with seeing any output from scripts.  In a script that Write-Host, it does not display the text in either the PowerShell Output or Debug Output.  I've tried several color themes in case output color equals background color.  If I set a debug, have a line that is just a variable that should display its value when run, I can hover and see the value.  However it does not output, nor do any variables show up in the Variables window.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Hey @ssaari, can you try the preview build I posted [here](https://github.com/PowerShell/vscode-powershell/issues/284#issuecomment-263687307) and see if it resolves your issue?

**Comment by ssaari** [comment]
Yes, sir, @daviwil, it sure did.  Thank you!

**Comment by daviwil** [comment]
Glad to hear it!  I'll be shipping an official update with that fix early next week.

**Comment by ssaari** [comment]
Hi,

I had started VS Code (the 0.7.10) in another RPD session, got kicked off, and was in another session when I logged back in.  Same logon but different session.  I can't open VS Code from its shortcut or from File Explorer.  Same environment as at the beginning of this thread.  Here's a Get-Process.  I guess I will pipe this to Stop-Process.
DF_PS> gps *code*

Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id ProcessName
-------  ------    -----      ----- -----   ------     -- -----------
    389      46    97972     135256   480   171.34   6924 Code
    203      22    23720      33072   200     2.84  20956 Code
    145      12     3484       9188   153     0.05  21324 Code
    638      53    33664      93280   530    64.30  28976 Code
    204      19    24740      36236   199     3.08  31576 Code
    168      17    20688      30168   192     1.64  37052 Code
    212      14     9716      12304   147     0.09  38268 CodeHelper

**Comment by daviwil** [comment]
This might be caused by the fact that code tries to reuse existing windows if you open another instance with the same workspace path.  This could be an instance where the process starts up and then tries to load the previous session then it realizes there's already another window with that session so it tries to activate it.  Through some weird interaction with Windows the window might be lost and not able to be activated on the desktop.

If you see this again, might be worth letting the VS Code team know about it:

https://github.com/Microsoft/vscode/issues

**Comment by ssaari** [comment]
okay, thanks.
