### ISSUE TITLE
Connect-AzAccount does not work in PowerShell Integrated Console

### ISSUE THREAD

**Issue by markr-rpc** [PowerShell/vscode-powershell#3633]
Note, **the solution is posted in the Azure PowerShell module**. They have a temporary engineering built of the Az.Accounts module, with version 2.6.2 with instructions on how to install. The link is here:
https://github.com/Azure/azure-powershell/issues/16340

---

### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I have setup VS Code on 2 new computers and they are both having the same issue. I have the Integrated PowerShell Console set to load Windows PowerShell 5.1.
When I run a script, the PowerShell Integrated Console (PIC) gives the error shown below. Even if I type the Connect-AzAccount manually in the PIC I get the same error. However, if I switch the terminal to Windows PowerShell (not Integrated), the command works fine (it loads the login prompt in an external PowerShell window). But when I run any script it automatically switches back to the PIC. Note that PowerShell Core works fine, it loads the login prompt in a browser window.

I have one older computer running Windows 10 that has had VS Code configured for years that is not showing the problem. I tried copying all the settings in the %appdata%, but it did not solve the problem.

Error:
WARNING: Unable to acquire token for tenant 'organizations' with error 'Method 'GetTokenAsync' in type 'Azure.Identity.InteractiveBrowserCredential' from assembly 'Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.'                                                                                                                                                                    
Connect-AzAccount : Method 'GetTokenAsync' in type 'Azure.Identity.InteractiveBrowserCredential' from assembly 'Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an 
implementation.
At line:1 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], TypeLoadException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.61.2
6cba118ac49a1b88332f312a8f67186f7f3c1643
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.10.1
```

### Steps to Reproduce

Install VS Code
Install PowerShell Az modules (Install-Module -Name Az)
Set the default console to be Windows PowerShell 5.1 so that the PowerShell Integrated Console runs with Windows PowerShell.
Type the command in the PowerShell Integrated Console window or put the command in a script and run: Connect-AzAccount

### Visuals
![image](https://user-images.githubusercontent.com/93016768/140438475-f199b05e-057d-4aa8-8b0d-002d5bd4f557.png)

![image](https://user-images.githubusercontent.com/93016768/138586433-776ffd76-3ee7-454f-b93e-4aad38ddc33f.png)

### Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/7404347/logs.zip)

**Comment by andschwa** [comment]
> Windows PowerShell is a hard requirement right now.

Oof, well I'm sorry about that. I'll see if we can figure out which dependencies are conflicting, though still not sure if it'll be fixable. One of the modules would (most likely) need to change its dependent version to match the other, and then go through a release, and then it'll work until they diverge again. And that's assuming that is indeed the issue.

**Comment by andschwa** [comment]
Ok between #3645 and reports on the PowerShell Discord, I am quite sure this is indeed the problem!

If someone can figure out _which_ dependency now conflicts between [PSES](https://github.com/PowerShell/PowerShellEditorServices/network/dependencies) and [Az.Accounts](https://github.com/Azure/azure-powershell/network/dependencies) (which I'm pretty sure is actually going to be from their update to [Azure.Core](https://github.com/Azure/azure-sdk-for-net/network/dependencies) to [v1.20.0](https://www.nuget.org/packages/Azure.Core/1.20.0)), then we can update it and fix this for you, at least for a while 😅

**Comment by bvbeek** [comment]
Same problem here

**Comment by teqqra** [comment]
Hi, we have same problem here on the last update of vsc.


Connect-AzAccount : Method 'GetTokenAsync' in type 'Azure.Identity.InteractiveBrowserCredential' from assembly 'Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'      
does not have an implementation.

I found a workarround that is open a new powershell window (not integrated console) , but we cannot debug for example till this get solved.

If i can provide any information to help solve the problem pls update me, thanks!

br

**Comment by andschwa** [comment]
> Ok between #3645 and reports on the PowerShell Discord, I am quite sure this is indeed the problem!
> 
> If someone can figure out _which_ dependency now conflicts between [PSES](https://github.com/PowerShell/PowerShellEditorServices/network/dependencies) and [Az.Accounts](https://github.com/Azure/azure-powershell/network/dependencies) (which I'm pretty sure is actually going to be from their update to [Azure.Core](https://github.com/Azure/azure-sdk-for-net/network/dependencies) to [v1.20.0](https://www.nuget.org/packages/Azure.Core/1.20.0)), then we can update it and fix this for you, at least for a while 😅

If someone can figure this out, we can bandage this temporarily. But we're up against .NET Framework constraints with this kind of bug. Maybe loop in the Azure module devs?

**Comment by meCoding** [comment]
Same problem here. It started when Az.Accounts was updated to 2.6.0. Running Connect-AzAccount in PS7 in VSCode terminal works, also running the command in PowerShell 5.1 (outside of VSCode) works.

**Comment by FingerlessGlov3s** [comment]
Same here, this used to work fine but no anymore. Hopefully we can get this working in VSCode again soon

**Comment by andschwa** [comment]
> so it does look to be VSCode itself related

As I've said, there is a dependency conflict between the Az.Accounts module and PSES. I just don't know which dependency as there are a _lot_ to sift through.

**Comment by andschwa** [comment]
Would really appreciate it if one of you would file a bug at the [Azure PowerShell module](https://github.com/Azure/azure-powershell) itself so we can start a conversation with their devs. I would also suggest testing their [Az Preview module](https://www.powershellgallery.com/packages/AzPreview/6.6.0) to check if it continues to repro.

**Comment by andschwa** [comment]
Actually, you don't need to test their preview module. Both it and their stable [module](https://www.powershellgallery.com/packages/Az/6.6.0) updated to 6.6.0 just two days. Please re-test!

**Comment by markr-rpc** [comment]
I have updated the Azure PowerShell modules to 6.60 and am getting the same results. I have created an issue with the Azure PowerShell team, as noted above. The Az.Accounts is now at version 2.61

**Comment by teqqra** [comment]
I have tested this on a new VM with fresh install and fail's out of the box, also on preview. If i downgrade VSC and powershell extension, still's the same.

Any workarround  (downgrade) we can do to make it working till a fix goes out?

Thanks all and have a great day!

**Comment by bizon80** [comment]
Hi,
Had the same issue, and not sure but there is a workaround that worked for me at least. When you get the error message in VS Code:
WARNING: Unable to acquire token for tenant 'organizations' with error 'Method 'GetTokenAsync' in type 'Azure.Identity.InteractiveBrowserCredential' from assembly 'Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.'
Connect-AzAccount : Method 'GetTokenAsync' in type 'Azure.Identity.InteractiveBrowserCredential' from assembly 'Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does no 
t have an implementation.

Just click 'New Terminal Window' and rerun. It worked for me.
![image](https://user-images.githubusercontent.com/29863994/140492800-6fbf5c35-eab5-42af-8486-a16f72d9f6c2.png)

**Comment by andschwa** [comment]
Thanks @markr-rpc!

**Comment by djansen1987** [comment]
> Hi, Had the same issue, and not sure but there is a workaround that worked for me at least. When you get the error message in VS Code: WARNING: Unable to acquire token for tenant 'organizations' with error 'Method 'GetTokenAsync' in type 'Azure.Identity.InteractiveBrowserCredential' from assembly 'Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.' Connect-AzAccount : Method 'GetTokenAsync' in type 'Azure.Identity.InteractiveBrowserCredential' from assembly 'Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does no t have an implementation.
> 
> Just click 'New Terminal Window' and rerun. It worked for me. ![image](https://user-images.githubusercontent.com/29863994/140492800-6fbf5c35-eab5-42af-8486-a16f72d9f6c2.png)

Also same issue, workaround from @bizon80  worked for as well

**Comment by elvrum** [comment]
Thanks!

**Comment by FingerlessGlov3s** [comment]
> Hi, Had the same issue, and not sure but there is a workaround that worked for me at least. When you get the error message in VS Code: WARNING: Unable to acquire token for tenant 'organizations' with error 'Method 'GetTokenAsync' in type 'Azure.Identity.InteractiveBrowserCredential' from assembly 'Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.' Connect-AzAccount : Method 'GetTokenAsync' in type 'Azure.Identity.InteractiveBrowserCredential' from assembly 'Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does no t have an implementation.
> 
> Just click 'New Terminal Window' and rerun. It worked for me. ![image](https://user-images.githubusercontent.com/29863994/140492800-6fbf5c35-eab5-42af-8486-a16f72d9f6c2.png)

Yeah this this a workaround, it doesn't use the Integrated console.

**Comment by markr-rpc** [comment]
workaround will not work for me since I use a setting to create a temporary integrated console. I have modules with functions and classes, so I need to reload the environment for any changes to take effect. Every run creates a new console and fails. I am using Visual Studio 2019 for now, which has an free extension for Windows PowerShell 5.1...doesn't work as well as VS Code though.

**Comment by teqqra** [comment]
Hi! Install powershell 7.2 seems to solve the problem for me.(installed
from the msi installer and work out of the box with vsc)

Some of the scripts will need a rework ,but at least I can now use vsc for
some deploys that uses the git path and I had problems with the workaround
since it was not the integrated console.

I will test 7.2 for some time to check if everything works fine.

Thanks!

**Comment by markr-rpc** [comment]
Note, the solution is posted in the Azure PowerShell module. They have a temporary engineering built of the Az.Accounts module, with version 2.6.2 with instructions on how to install. The link is here:
https://github.com/Azure/azure-powershell/issues/16340

**Comment by candybaby407** [comment]
I have same issue. Installed 2.6.2 but still seeing the issue...

**Comment by JustinGrote** [comment]
This issue was fixed here:
https://github.com/Azure/azure-powershell/pull/16337

And this issue should be closed either now or when that associated release occurs.

**Comment by andschwa** [comment]
I've pinned this issue and am marking it as resolved externally thanks to @dingmeng-xue's great work fixing it.
