### ISSUE TITLE
Add debug configurationSnippets to package.json to light up "Add Configuration" experience

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#364]
See https://github.com/Microsoft/vscode/issues/16937 for details.

**Comment by rkeithhill** [comment]
What do you think about this impl of the debug configurationSnippets:

![image](https://cloud.githubusercontent.com/assets/5177512/21076693/3ff663d4-beef-11e6-9858-8761ed99a963.png)

This is what the Start Debugging target drop down looks like.  Note that I want to rename the current target `PowerShell` to `PowerShell Launch (current file)`.  This will allow the user to use the `Add Configuration` button in VSCode 1.8 to add new configurations that launch specific scripts.  The user can then switch between the various targets in the Debug view drop down.

![image](https://cloud.githubusercontent.com/assets/5177512/21076685/1f10f77e-beef-11e6-9a43-752e4f1cacc9.png)

By renaming to `PowerShell Launch ...` this makes room for an eventual `PowerShell Attach`.  :-)

Thoughts?  I'd like to get this in for 0.8.0.  I need to test this in VSCode 1.7 but @isidorn says 1.7 should just ignore the new configurationSnippets section.

**Comment by rkeithhill** [comment]
Been playing with this.  I like it! It is not uncommon to have different scripts with a workspace that you want launched for debugging.  This feature allows you to do that:

![image](https://cloud.githubusercontent.com/assets/5177512/21076987/b13c63d2-bef8-11e6-9de3-4962c3a2ecb3.png)

**Comment by daviwil** [comment]
I like the config naming a lot, makes things really clear.  I think we'll get attach to process going pretty soon so it's good to leave room for that, as you have.  Also good to be consistent with other extensions.

Hmmm, seems they're running a little late on 1.8, but maybe they'll ship soon after we do and it won't matter.  I guess the biggest issue is whether there will be a way to create a default PowerShell launch config in that window of time.  If it won't be possible then maybe we should either delay the release or hold off on the change until January.  What do you think?

**Comment by rkeithhill** [comment]
I tried the extension in VSCode 1.7 and was able to create a launch.json file from the Debug view. The only differences are that the configuration name is the updated name and instead of "program" it uses "script".  That should work just fine for a person using the launch.json file on the same machine they upgraded to 0.8.0.  However if that get's checked in and someone else clones it and tries to debug from a machine with <= 0.7.2 they will get an error.   Easy solution though - they upgrade to 0.8.0.

**Comment by isidorn** [comment]
@rkeithhill looks great!

**Comment by rkeithhill** [comment]
@isidorn Thanks for the feedback!
