### ISSUE TITLE
Get-AzStorageAccount : Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.

### ISSUE THREAD

**Issue by justPaulo** [PowerShell/vscode-powershell#3645]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

This error relates 100% with VS Code because the one-liner pwsh statement only generates errors when executed in VS Code. Executing it pwsh prompt or PowerShellISE works just great as expected.

### PowerShell Version

```console
Name                           Value                                                                                                                                      
----                           -----                                                                                                                                      
PSVersion                      5.1.18362.1801                                                                                                                             
PSEdition                      Desktop                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                    
BuildVersion                   10.0.18362.1801                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                            
WSManStackVersion              3.0                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                        
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.61.2
6cba118ac49a1b88332f312a8f67186f7f3c1643
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.10.1
```

### Steps to Reproduce

https://user-images.githubusercontent.com/1660842/139047131-bbbdccee-6e4a-42bb-8671-8a49dc5d5705.mp4

### Visuals

https://user-images.githubusercontent.com/1660842/139047180-d460b650-0dd0-495a-9faf-73f1e6e0e7e6.mp4

### Logs

[1635329024-b39e1c8e-7939-492d-a531-aa7c87b6354c1635329022195.zip](https://github.com/PowerShell/vscode-powershell/files/7425275/1635329024-b39e1c8e-7939-492d-a531-aa7c87b6354c1635329022195.zip)

**Comment by andschwa** [comment]
@justPaulo I'm going to mark this as a duplicate because I'm pretty sure it's the same issue as #3633.
