### ISSUE TITLE
`Write-Host -NoNewLine` not respected

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3651]
### Prerequisites

- [x] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I have written PowerShell module PSWriteColor which uses Write-Host -NoNewLine pretty much all the time

![image](https://user-images.githubusercontent.com/15063294/139388191-49badd61-c1e0-451e-8da1-4e89b638368a.png)

```powershell
Write-Host -NoNewline -BackgroundColor Red -Object 'Test'
Write-Host -NoNewline -BackgroundColor Blue -Object 'Test 1'
Write-Host -NoNewline -BackgroundColor DarkGray -Object 'Test 2'
```

![image](https://user-images.githubusercontent.com/15063294/139388397-3da6e9d2-289d-4f19-a753-7400f0e07ba5.png)

```powershell
Write-Color -Text 'Test1 ', 'Test2 ','Test3' -Color Red, Blue, DarkGray
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.61.2
6cba118ac49a1b88332f312a8f67186f7f3c1643
x64
```

### Extension Version

```console
ironmansoftware.powershell-universal@2.3.0
ms-vscode.powershell@2021.10.2
ms-vscode.powershell-preview@2021.10.3
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

Type in powershell editor, press F5

```powershell
Write-Host -NoNewline -BackgroundColor Red -Object 'Test'
Write-Host -NoNewline -BackgroundColor Blue -Object 'Test 1'
Write-Host -NoNewline -BackgroundColor DarkGray -Object 'Test 2'
```

**Comment by andschwa** [comment]
Well now this one is weird!

**Comment by fflaten** [comment]
I see this with Pester too. Formatting using NoNewLine, ForegroundColor and BackgroundColor with `Write-Host` doesn't work, so output is broken.

ANSI and `[System.Console]::ForegroundColor + WriteLine` seems to work fine.

**Comment by fflaten** [comment]
Does the new method rely on stream-redirection? I just remembered [this issue](https://github.com/pester/Pester/issues/1384#issuecomment-843617873) in Pester about formatting being lost when information stream (which `Write-Host` in 5+ uses) is being redirected.

**Comment by andschwa** [comment]
I think the color problem is likely due to https://github.com/PowerShell/PowerShellEditorServices/issues/1607

**Comment by SeeminglyScience** [comment]
[EditorServicesConsolePSHostUserInterface](https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs) needs to implement the virtual (and otherwise empty) method `WriteInformation(InformationRecord)`.

**Comment by fflaten** [comment]
> [EditorServicesConsolePSHostUserInterface](https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs) needs to implement the virtual (and otherwise empty) method `WriteInformation(InformationRecord)` (it can just redirect to the origin host like the other methods).

Yeah that's sounds more like what I'd expect as it would also affect the NoNewLine-part. 👍

Not really related to this issue but should it also implement `WriteLine(ConsoleColor, ConsoleColor, String)`? It's also missing unlike the `Write(ConsoleColor...`-equivalent.

**Comment by SeeminglyScience** [comment]
> Not really related to this issue but should it also implement `WriteLine(ConsoleColor, ConsoleColor, String)`? It's also missing unlike the `Write(ConsoleColor...`-equivalent.

You'd want to open an issue on PowerShell/PowerShell for that, we don't control that particular API surface.

**Comment by fflaten** [comment]
> > Not really related to this issue but should it also implement `WriteLine(ConsoleColor, ConsoleColor, String)`? It's also missing unlike the `Write(ConsoleColor...`-equivalent.
> 
> 
> 
> You'd want to open an issue on PowerShell/PowerShell for that, we don't control that particular API surface.

I meant implemented in EditorServicesConsolePSHostUserInterface. 🙂

**Comment by SeeminglyScience** [comment]
> I meant implemented in EditorServicesConsolePSHostUserInterface. 🙂

Oops! 😁 

Yeah that'd be good to add as well, thanks for catching that.  I don't think it'll cause any bugs since the method does have a default implementation but `ConsoleHost` does override it so might as well.

**Comment by andschwa** [comment]
Interesting...I wonder why we didn't manage to get this as fleshed out.

**Comment by SeeminglyScience** [comment]
> Interesting...I wonder why we didn't manage to get this as fleshed out.

Incredibly easy to miss tbh.  They don't get generated from the code action to implement an abstract type.  You need the one that says "Generate all overrides" or something like that.  Though even with that you need to be careful not to override a method with a default implementation you need to keep.  Kind of a rough extension model to have empty virtual methods rather than abstract, but it's what you gotta to to not introduce breaking changes.

**Comment by andschwa** [comment]
Ohh, I see! Thanks Patrick.

**Comment by andschwa** [comment]
Unfortunately @SeeminglyScience there seems to be a bit more to it than just overriding those abstract methods. I'll open a draft PR, but in my testing it's not seeming to fix it. There's also a `_consoleHostUI` that perhaps comes into play?

**Comment by andschwa** [comment]
Fix for this has been merged!
