### ISSUE TITLE
Pester code lens broken in latest preview

### ISSUE THREAD

**Issue by fflaten** [PowerShell/vscode-powershell#3652]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

"Run/Debug Tests" Pester code lense no longer work in latest extension preview. Caused by `InvokePesterStub.ps1` being called with parameters with embedded single quotes.

Fails with
```powershell
& '/root/.vscode-server/extensions/ms-vscode.powershell-preview-2021.10.3/modules/PowerShellEditorServices/InvokePesterStub.ps1' -ScriptPath '''/workspaces/Pester/Samples/demoIssueCodeLensPreview.tests.ps1''' -LineNumber 3 -MinimumVersion5 -Output '''Diagnostic'''

Get-ChildItem: /workspaces/Pester/bin/Pester.psm1:3512:13
Line |
3512 |              & $SafeCommands['Get-ChildItem'] -Recurse -Path $p -Filte …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path '/workspaces/Pester/Samples/'/workspaces/Pester/Samples/' because it does not exist.

System.Management.Automation.RuntimeException: No test files were found and no scriptblocks were provided. Please ensure that you provided at least one path to a *.Tests.ps1 file, or a directory that contains such file. Or that you provided a ScriptBlock test container.
at Invoke-Pester<End>, /workspaces/Pester/bin/Pester.psm1: line 5220
at <ScriptBlock>, /root/.vscode-server/extensions/ms-vscode.powershell-preview-2021.10.3/modules/PowerShellEditorServices/InvokePesterStub.ps1: line 164
at <ScriptBlock>, <No file>: line 1
```

### PowerShell Version

```console
PS /workspaces/Pester/Samples> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.6
PSEdition                      Core
GitCommitId                    7.0.6
OS                             Linux 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS /workspaces/Pester/Samples> code --version
1.61.2
6cba118ac49a1b88332f312a8f67186f7f3c1643
x64
```

### Extension Version

```console
PS /workspaces/Pester/Samples> code --list-extensions --show-versions | Select-String powershell

Extensions installed on Dev Container: Pester C# (.NET Core) w/ PowerShell:
ms-vscode.powershell-preview@2021.10.3
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

1. Install latest Pester and vscode-powershell-preview-2021.10.3
2. Make sure legacy code lens is disabled `"powershell.pester.useLegacyCodeLens": false`
3. Create sample "demoIssueCodeLensPreview.tests.ps1" with content
```powershell
Describe "DescribeName" {
    Context "ContextName" {
        It "ItName" {
            1 | Should -Be 1
        }
    }
}
```
4. Use `Run Tests` or `Debug Tests` code lens on any level in the file above.

### Visuals

![image](https://user-images.githubusercontent.com/3436158/139439242-79060fc9-c0cf-4949-b112-1dbbdc290840.png)

**Comment by fflaten** [comment]
Updated the console output in first post to match the image to show that it affects multiple string arguments, ex Output. 

I'm not very familiar with VSCode debugger and PSES, but I bet the launch debugger-command provided by PSES now auto-quotes string-arguments, something the caller used to do until now: https://github.com/PowerShell/vscode-powershell/blob/4d4911a639cfd7ce9dbff14dd0d79895fde1036b/src/features/PesterTests.ts#L80-L126

I'm not sure if this issue belongs here, in PSES or both. Code lens, launch command and InvokePesterStub.ps1 are in PSES iirc, however the problem also occurs with the "Run/Debug Pester Tests" commands in this extension due to the same underlying change.

**Comment by JustinGrote** [comment]
I'm seeing the same, was trying to dig into where that might ahve changed.

**Comment by JustinGrote** [comment]
Args look correct in the request so it's definitely in the handler
![{D4822CA3-BB8E-4195-9088-06F885480C4E}](https://user-images.githubusercontent.com/15258962/139502590-52b00c54-2ed9-4782-a617-9160d0f7ff4d.png)

**Comment by JustinGrote** [comment]
This is the new code causing the problem
https://github.com/PowerShell/PowerShellEditorServices/blob/8c568bceecfc8f188e6cb53f23b1ed5673bd5af2/src/PowerShellEditorServices/Utility/StringEscaping.cs#L9-L36

**Comment by andschwa** [comment]
I thought that might cause an issue. I'd hoped tests covered it. They apparently did not!

**Comment by JustinGrote** [comment]
Track on this issue in PSES:
https://github.com/PowerShell/PowerShellEditorServices/issues/1608

**Comment by andschwa** [comment]
Which means hopefully also fixed by https://github.com/PowerShell/PowerShellEditorServices/pull/1609

**Comment by JustinGrote** [comment]
Here's a build of #1609 that fixes it until it gets merged if anyone needs this right away: https://github.com/pester/vscode-adapter/issues/88#issuecomment-958015991

**Comment by fflaten** [comment]
Thanks @JustinGrote and @andschwa for the quick fix (once released) 🎉

**Comment by andschwa** [comment]
@fflaten Should be out now! Still far from bug-free, but one by one we squash them!
