### ISSUE TITLE
Go to definition on binary cmdlet or command that doesn't exist times out

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/vscode-powershell#3654]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Go to definition does not fail properly. This performs as expected in stable.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.61.0
ee8c7def80afc00dd6e593ef12f37756d8f504ea
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2021.10.3
```

### Steps to Reproduce

1. Put `Get-ChildItem` in a file
2. Run "Go to definition".
3. The extension host locks up for ~10-15 seconds before giving up.

Expectation here is to get `No definition found for 'Get-ChildItem'` (currently displays nothing) and to complete much quicker.

**Comment by andschwa** [comment]
Very strange indeed. Please keep us updated if you find a repro.
