### ISSUE TITLE
Run Launch config on unsaved File is broken

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3655]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Currently when you invoke an unsaved script with this launch config:
```
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell: Current File",
            "script": "${file}",
            "args": [],
            "cwd": "${file}"
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell: Current File w/ Args",
            "script": "${file}",
            "args": [
                "${command:SpecifyScriptArgs}"
            ],
            "cwd": "${file}"
        },
```

Given a simple unsaved script that says:
```ps
"This is a {0} test" -f $args[0]
```
The run occurs like this:
```ps
. $args[0] "This is a test -f $args[0]"
```
(Note the first args[0] isn't specified in the script)
And produces no output.

Instead it should be using either the call operator or the '.' operator (this should be a configurable preference to determine if variables remain in scope of the PSIC or not):
`.{<scriptGoesHere>} <argsGoHere>`

So for this example, running the script with the 'fun' arg should result in the command:
`.{"This is a {0} test" -f $args[0]} fun`

Which produces the intended result.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.62.0-insider
dc1a6699060423b8c4d2ced736ad70195378fddf
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2021.10.3
```

### Steps to Reproduce

See description

**Comment by andschwa** [comment]
@JustinGrote Looks like this may be fixed by https://github.com/PowerShell/PowerShellEditorServices/pull/1609?

**Comment by JustinGrote** [comment]
> @JustinGrote Looks like this may be fixed by [PowerShell/PowerShellEditorServices#1609](https://github.com/PowerShell/PowerShellEditorServices/pull/1609)?

It doesn't, this is a separate issue.

**Comment by andschwa** [comment]
Oh dang, ok! Thanks for the confirmation.

**Comment by andschwa** [comment]
Oh this looks like a breakage due to the buggy behavior in #3666.

**Comment by andschwa** [comment]
This is weird since I don't think the extant behavior in the stable channel is correct either, it produces the output:

```
> This is a  test
PS> 
```

**Comment by andschwa** [comment]
@JustinGrote Sooo upon digging, the logic around this hasn't changed in [two years](https://github.com/PowerShell/PowerShellEditorServices/blob/1cf808f973c845e894ab2b575baa4fd24810a90b/src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs#L103-L125)...

**Comment by andschwa** [comment]
This is super broken in general. Might punt from the next stable release because it was already broken.

**Comment by andschwa** [comment]
@JustinGrote Can you verify that your scenario is just as broken in the stable channel too?

**Comment by JustinGrote** [comment]
@andschwa haven't verified but I do know that the new `Powershell: Run` seems to work on unsaved files just fine, so that's a good enough workaround to punt to the next "sprint"

**Comment by andschwa** [comment]
I have a stashed change that definitely makes your scenario work _better_ with respect to running the untitled script as `. {<contents>} <args>` without shifting the args array around with the hack..._but_ this breaks debugging it (as in, any set breakpoints don't work because they're set on lines that aren't actually being run). The current hack (it's literally labeled "hack") is just untenable. Sure it kind of got untitled script debugging working...but not in a sustainable way.

**Comment by andschwa** [comment]
@JamesWTruher is ruminating on potential solutions for us 😄
