### ISSUE TITLE
Add option in launch.json to create a new PS process for each script debug session

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#367]
There are some cases where it's useful to create an entirely new PowerShell process instance when debugging a script.  For example, when writing PowerShell classes it isn't easy to quickly make tweaks to your class code in the same session because PS classes are generated into assemblies at runtime and can't be unloaded/reloaded.  In this case, creating a fresh PowerShell process for each run of the debugger would enable the developer to have a faster turnaround time when writing PowerShell code with classes.

We should add a new option in launch.json which causes our debug adapter to create a new PowerShell process, load PSES and start a fresh debug server.

**Comment by rkeithhill** [comment]
Definitely. I have been worried about this sort of thing leading to an incorrect assumption that a script is working because of "left-overs" in the debug session. Or in the case you outline, troubles debugging on subsequent runs.

**Comment by daviwil** [comment]
From @Glober777:

I was wondering if there's a clean way of getting the integrated console automatically restarted when I'm starting the debug session (preferably configurable through launch.json, i.e. by referencing a task or via a separate attribute)? What I currently do, is I'm deleting the integrated console, which brings up a prompt suggesting me to restart it, but there were a few times when I forgot to do that and got burned by that.
