### ISSUE TITLE
Null Stack if debugging in separate process

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3673]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When starting Wait-Debugger, a nullpointerexception happens due to the lack of stackFrameDetails

### PowerShell Version

```console
7.1
```

### Visual Studio Code Version

```console
1.63.0-insider
```

### Extension Version

```console
Preview
```

### Steps to Reproduce

1. `Enter-PSHostSession <some other pwsh.exe>`
1. `Wait-Debugger`

### Visuals

![image](https://user-images.githubusercontent.com/15258962/140528991-deb99ec9-0504-4067-87b9-ccb69f291fe2.png)

### Logs

Exception has occurred: CLR/System.NullReferenceException
An exception of type 'System.NullReferenceException' occurred in Microsoft.PowerShell.EditorServices.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at Microsoft.PowerShell.EditorServices.Services.DebugService.<OnDebuggerStopAsync>d__53.MoveNext() in C:\Users\JGrote\Projects\PowerShellEditorServices\src\PowerShellEditorServices\Services\DebugAdapter\DebugService.cs:line 953

**Comment by andschwa** [comment]
What do you think would be the proper behavior here?

**Comment by JustinGrote** [comment]
@andschwa found this as a side effect of the variable stuff, I'll probably fix it in that PR, just wanted to note it here.

**Comment by andschwa** [comment]
Love it, keep it all coming! You rock.
