### ISSUE TITLE
Enter key does not produce a new line in terminal and output is incorrect

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3675]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

![image](https://user-images.githubusercontent.com/15258962/140807943-5356e0e4-2151-491e-9ba7-76b92b17da86.png)

### PowerShell Version

```console
7.2.0
```

### Visual Studio Code Version

```console
1.63.0-insiderrote\Projects\PoshNmap> code --version
a7104f13ff61bcd9f4c827d8fe3c0d27bb479fd8
x64
```

### Extension Version

```console
Preview
```

### Steps to Reproduce

1. Open PSIC terminal
1. Hit enter key
1. Type "THIS SHOULD BE ON A NEW LINE" and note it doesn't roll over

### Logs

None

**Comment by JustinGrote** [comment]
This may be PSReadline 2.1 related, I get lots of REPL loop and pipeline errors on occasion too

**Comment by andschwa** [comment]
@JustinGrote Have you overrode PSReadLine? [PSES 3.0 bundles PSReadLine 2.2.0-beta4](https://github.com/PowerShell/PowerShellEditorServices/blob/78cb9ad50465042490a284d2d4500176397796d0/modules.json#L9). Can you verify what's loaded in your session?

**Comment by JustinGrote** [comment]
@andschwa that's on me, I did a dev build and for some reason it scooped in 2.1
![image](https://user-images.githubusercontent.com/15258962/140824745-5a88d2fe-2419-4944-b6aa-212381b9cf43.png)

**Comment by JustinGrote** [comment]
Closing for now, will reopen if there's a better way to handle.

**Comment by andschwa** [comment]
That's so strange! Or, "that's a weird one!" 🤣
