### ISSUE TITLE
VSCode PowerShell Preview PSES no longer shows history from previous F8/F5 command in buffer

### ISSUE THREAD

**Issue by brwilkinson** [PowerShell/vscode-powershell#3683]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

The current behavior of the PowerShell Extension is to show the history in the Terminal after using F5 or F8
- This is available with the up arrow to re-execute the previous command; however this is missing in the current preview.

Typo on my video: "Up arrow does **not** show history"

There are also some artifacts and clearing of the screen when executing the second command, however I didn't open this issue for that.

https://user-images.githubusercontent.com/3605266/141012338-b3f9dd95-575d-4dc5-a06f-bc7d8d98a37e.mp4

issue starts at 30 seconds onwards.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.22499
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.62.0
b3318bc0524af3d74034b8bb8a64df0ccf35549a
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.10.2     # disabled
ms-vscode.powershell-preview@2021.11.0
```

### Steps to Reproduce

run a command from the script pane with F8
watch it execute
Go to the terminal and press the up arrow, the previous command is not in the buffer
It is shown in the history

### Visuals

video is above, you can skip to 30 seconds.

**Comment by MartinGC94** [comment]
Some people actually want this behavior: https://github.com/PowerShell/vscode-powershell/issues/2307 so this should get turned into an option. I personally use F8 to load functions or run other big sections of code so when I press arrow up and my entire console gets filled up with a function definition I get annoyed.

**Comment by andschwa** [comment]
I think @MartinGC94 is right and this should be configurable, moving to consideration milestone.

**Comment by andschwa** [comment]
This might get a little messy. Someone tell me what the want the setting name to be 😂 the whole subblock of settings under `powershell.integratedConsole` are all client-side settings, so while this is kind of for the integrated console, since it would be the first server-size setting it would mean adding a bunch of boiler plate if we want it there. What about just `powershell.includeEvaluateInHistory` with a default of `false`?

**Comment by brwilkinson** [comment]
Ignoring the naming of the setting... 🙂for now.

I was thinking of optional different behaviors, *i likely should have mentioned this before.*

Also I was trying to also think back to ISE behavior.

Here are a few more considerations or options of how code might be executed/presented. I am not sure what work has already been done etc or if this fits with this work?

1) you have an unsaved or saved script and you select/highlight some code or just have the cursor on the line and you run F8
2) you have an unsaved script file e.g. ps1 open and you press F5 
3) you have a saved PS1 and you press F5.

What is the expectations.... I would tentatively say for the options listed the outcome might be (assuming the new setting is true)

1) I would see the text in the output or at least if I up arrow or execute history the whole command would be there
2) in ISE it forces you to say, I have autosave in vscode as well, so for me this becomes the same as option 3.
   - I didn't test disabling auto save, maybe this becomes the same as option 1 if unsaved?
3) in ISE it just puts the path to the ps1 file in the history, so up arrow allows you to invoke the script again by fully qualified path.

Sorry for the late reply on this with the extra specifications Etc.

**Comment by ruudhanegraaf** [comment]
It looks likes this change has made it into the stable channel. :-(
This is *extremely* annoying behavior. When writing scripts, a lot of us execute the selection using F8, and when you get an error, you recall the command in the terminal window using the cursor and change it until you've found the correct syntax.

The previous behavior was one of the thing I really liked in VSCode compared to ISE.

Please revert this change until you've made it configurable. :-(

**Comment by brwilkinson** [comment]
It's been a while since we chatted over this experience. We had too many options to consider and it was difficult to select one in time.

I do miss having the command history.

I figured I would see if there were any decisions that we needed to make over this? Seems since this shipped, it's now breaking change in both directions, so we will need a configurable setting, default to the current behavior for now, then people can opt back into getting the history shown?!

I will just add (again), An optional experience that I like is, that If you press F5, it can just place the dot sourced script file path in the history, that way up arrow you can invoke the script by path. However if the file was not saved, it's basically F8 behavior that it just pastes the command in the history and up arrow shows the whole buffer of the previous command.

So not sure on others' opinions or preferences on that?

**Comment by andschwa** [comment]
> Seems since this shipped, it's now breaking change in both directions, so we will need a configurable setting, default to the current behavior for now, then people can opt back into getting the history shown?!

Oops... @SeeminglyScience I think we should change it back to the old setting until we have it be configurable, what do you think?

> If you press F5, it can just place the dot sourced script file path in the history, that way up arrow you can invoke the script by path.

Ugh, ok, it gets put in PowerShell's history e.g. `Get-History` but not in PSReadLine's. I remember now, and it was annoying to fix. We'll investigate.

**Comment by AvrumFeldman** [comment]
I agree with @ruudhanegraaf, this was one of the features I loved from vscode vs ise. A lot of times I run my initial command in the editor and then modify it in the console after by pressing up. I was hoping there can be at least an optional setting for this.

**Comment by brwilkinson** [comment]
Didn't realize just how much productivity I gained back from having commands in history.

So thankful this is back 👍🏼🙏🏼✅😎🙂

**Comment by andschwa** [comment]
Sorry it took us so long to fix!
