### ISSUE TITLE
After eval with F8, PSReadLine prompt appears in command output

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/vscode-powershell#3685]
### Prerequisites

- [ ] I have written a descriptive issue title.
- [ ] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When press F8, the prompt and PSReadLine repl area should appear *after* command input. Currently it does not rerender after command completion, and retains it's position.

This makes me think we are not cancelling the call to `PSConsoleReadLine.ReadLine` but are instead just taking it over via the delegate.  The call needs to be actually cancelled before invocation and then restarted after invocation. The old code for this shows how to do this while still preserving the current repl input.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.61.0
ee8c7def80afc00dd6e593ef12f37756d8f504ea
x64
```

### Extension Version

```console
justin-grote.better-powershell-syntax-highlighting@0.0.2
ms-vscode.powershell@2021.10.2
ms-vscode.powershell-preview@2021.11.0
```

### Steps to Reproduce

1. Open untitled editor pane with language set to PowerShell
2. Type Get-ChildItem
3. Press F8
4. Move focus to integrated console
5. Type some stuff, hit enter, etc

### Visuals

![image](https://user-images.githubusercontent.com/24977523/141133323-eb9db510-7b8a-4d38-81a7-de56288b242a.png)

### Logs

N/A

**Comment by JustinGrote** [comment]
In my case it appears "prior" to the code running, probably a race condition or unawaited async involved here.

**Comment by StevenBucher98** [comment]
Thanks for the information on this one! @SeeminglyScience We marked as bug and will work to fix

**Comment by andschwa** [comment]
@SeeminglyScience Could you point me toward that "old code" and where in the new code you think this could be fixed?

**Comment by SeeminglyScience** [comment]
@andschwa sorry for the delay

Old code:

https://github.com/PowerShell/PowerShellEditorServices/blob/6b1e77d6223ff61c4af3cbeedf687e1f65f3ac18/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L612-L649

New code probably around here:

https://github.com/PowerShell/PowerShellEditorServices/blob/99b523ef9fb6b3894a71291182a42ab280584eb9/src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs#L263-L266

**Comment by andschwa** [comment]
Thanks!

**Comment by ocarela** [comment]
hi alll, i have the issue of colors in windows 2012 r2 wiht command prompt and or powershell, i saw the solution but dont know how to implement it, anyone can help please? thanks
