### ISSUE TITLE
[Preview] Run Selection doesn't re-present the prompt after running

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3689]
Issue Type: <b>Bug</b>

The prompt does not re-present after "Run Selection" (F8). Pressing Enter will display it. and the prompt does work fine at this point, it just doesn't run the `prompt` function I don't think.
![image](https://user-images.githubusercontent.com/15258962/141509751-fd58eab5-175f-48f8-8792-72866ba32de9.png)

Extension version: 2021.11.0
VS Code version: Code - Insiders 1.63.0-insider (c1096372119bcf83b9bd8ccee96dcf266f35de76, 2021-11-11T13:18:41.690Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (5.30GB free)|
|Process Argv|--crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30382699
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
vscexrecpromptt3:30397560

```

</details>

**Comment by JustinGrote** [comment]
![image](https://user-images.githubusercontent.com/15258962/141509751-fd58eab5-175f-48f8-8792-72866ba32de9.png)

**Comment by ili101** [comment]
Duplicate? https://github.com/PowerShell/vscode-powershell/issues/3685

**Comment by JustinGrote** [comment]
Yup, after checking the prompt comes up just prior, not in the middle, but probably same problem.
