### ISSUE TITLE
CPU Load hit 99% while vscode running

### ISSUE THREAD

**Issue by jeffpatton1971** [PowerShell/vscode-powershell#37]
I think this is related to the powershell extension. I installed vs-code last week, and then late last week was an update. Today when I fired up vscode and started working I noticed the fan starting spinning up and stayed up.

<img width="505" alt="powershell-editor-cpu-load" src="https://cloud.githubusercontent.com/assets/1192315/11478590/8c23e6e2-9753-11e5-8393-5ea62aaa9796.PNG">

After I closed vscode down that went away. In defense of vscode here I only had 6 files open and only editing one, and honestly it was about an hour before I actually started editing a file, but I noticed the fan spin up before then. I thought perhaps I was getting an update via windows updates so I didn't think anything about it, until after a while I realized the fan never stopped.

**Comment by daviwil** [comment]
Hi Jeff,

So if I understand you correctly, the high CPU usage happened before you started typing in the file?  Have you seen the issue occur more than once?  Could you send the file at the following location to me via e-mail (my GitHub username @ microsoft.com):

`%USERPROFILE%\.vscode\extensions\ms-vscode.PowerShell\bin\EditorServices.log`

Thanks!

**Comment by fromthewoods** [comment]
![cap1](https://cloud.githubusercontent.com/assets/5445673/11481309/ec578b76-9759-11e5-8f67-41adf9340176.gif)
I'm seeing high CPU usage as well.

**Comment by daviwil** [comment]
@fromthewoods Thank you!  I did not know that '$' was being treated as a function.  This would explain why completing variable names would cause a significant CPU spike.  I'll get this fixed for the next release.

**Comment by hunter-xue** [comment]
I run into the same issue.

**Comment by daviwil** [comment]
I was able to investigate another user's repro of this issue and I've narrowed it down to the usage of PowerShell Script Analyzer.  Something about the source file causes script analysis to get hung at some point and it never finishes.  If you want a temporary workaround for this issue, try the following:

1. In VS Code, click `File -> Preferences -> User Settings`
2. Two editor panes will appear.  In the right-most pane, paste this line between the curly braces { } :

    `“powershell.scriptAnalysis.enable” = false`

**Comment by larssb** [comment]
We also experience this issue....

@daviwil - Thank you for the workaround. Will use that for now. Looking forward to a fix though, as the ScriptAnalysis functionality is a great tool :-).

Thank you in advance.

**Comment by daviwil** [comment]
Just realized I made a typo in the setting string for the above workaround:  instead of the equals sign '=' there should be a colon ':'.  I've updated the comment to reflect that change.

**Comment by DmitryLobanov** [comment]
The same issue for me. It makes editing PowerShell scripts impossible.

**Comment by rkeithhill** [comment]
@DmitryLobanov Which version of the extension are you using?  I thought this issue had been fixed.  The latest is version 0.3.1.  To update, Ctrl+Shift+P, type ext and select "Extensions: Show Outdated Extensions".  That should allow you to update to 0.3.1.

**Comment by DmitryLobanov** [comment]
@rkeithhill thanks, this seems to be fixed! I've updated the extension and now the issues seems gone.

**Comment by daviwil** [comment]
Hey guys, I think this issue should be long gone by now.  I'll close this issue for now but please feel free to leave a comment here if it shows up again and I'll reopen the bug.  Thanks!

**Comment by waldo1001** [comment]
For some reason, I'm hitting 99% with the latest VSCode update.. .
I haven't been able to repro the above, because frankly, I'm not able to get into VSCode anymore :-/
