### ISSUE TITLE
Pressing CTRL+C to cancel script doesn't stop debugging in preview extension

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3700]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I just installed preview extension to see if Write-Host is fixed yet, and noticed it wasn't, so during a long time script running I press CTRL+C, but while the script stopped, GUI doesn't think so. 

![image](https://user-images.githubusercontent.com/15063294/142990293-f474ab29-00db-43a5-b60b-0e0c99cd2c00.png)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.62.3
ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
x64
```

### Extension Version

```console
ironmansoftware.powershell-universal@2.5.0
ms-vscode.powershell@2021.10.2
ms-vscode.powershell-preview@2021.11.1
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

1. Run a script
2. CTRL+C the script
3. Notice how debugging is still on

**Comment by andschwa** [comment]
@PrzemyslawKlys Can you link the tracking issue for "Write-Host is fixed yet, and noticed it wasn't"?

**Comment by andschwa** [comment]
Also can you test if this repros with PowerShell 7.2? While I wired up a stop debugging notification so that stopping the PowerShell debugger informs Code to stop the GUI, I don't think it is supported with PowerShell 5.1

**Comment by PrzemyslawKlys** [comment]
It's not only PowerShell 5.1

![image](https://user-images.githubusercontent.com/15063294/143084714-e0aa90bd-88dc-4b15-9d7a-2b7809d1fa58.png)

Notice how I stopped CTRL+C and was able to type stuff in a terminal, while the GUI was showing something different. 

- This is the issue for Write-Host https://github.com/PowerShell/vscode-powershell/issues/3651

I refuse to use preview until this is fixed because it ruins the output of my programs. My modules heavily rely on Write-Host and it makes it really bad.

![image](https://user-images.githubusercontent.com/15063294/143085152-2846a058-00bb-40ff-a4a5-b50a517d22b4.png)

**Comment by andschwa** [comment]
Cool, thanks for the information.

**Comment by andschwa** [comment]
It looks like the wiring up I did in https://github.com/PowerShell/PowerShellEditorServices/pull/1570 was unfortunately not carried over in the pipeline threading rewrite https://github.com/PowerShell/PowerShellEditorServices/pull/1459.
