### ISSUE TITLE
Microsoft Graph Runtime EventData objects being emitted in PSIC when they do not emit normally

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3705]
Issue Type: <b>Bug</b>

1. `Get-MgGroup`

![image](https://user-images.githubusercontent.com/15258962/143829997-1c8aeadc-5bc1-4bfe-a0e0-39c711388257.png)

Extension version: 2021.11.1
VS Code version: Code - Insiders 1.63.0-insider (d18d093403b12a65350c58a7b0d5771cc1f42aba, 2021-11-26T08:21:30.810Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (0.95GB free)|
|Process Argv|--crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt3:30397560
vscop804cf:30404767
vs360:30404995

```

</details>

**Comment by JustinGrote** [comment]
@andschwa @SydneyhSmith this should be added to the Pipeline revamp to-do

**Comment by o-l-a-v** [comment]
That's what you'll see if setting $InformationPreference to Continue and run any Microsoft.Graph.* cmdlet. Be it Windows PS 5.1, PS ISE, or PS core.

https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/373

So maybe a issue with the Microsoft.Graph module?

**Comment by JustinGrote** [comment]
@o-l-a-v it happens even if informationpreference is 'silentlycontinue'. Maybe this is exposing something in the new PSIC host that isn't respecting informationpreference?

![image](https://user-images.githubusercontent.com/15258962/143934395-95a95c0e-5e65-4370-af2d-31569e508925.png)

**Comment by JustinGrote** [comment]
I'm pretty sure this is a host implementation issue, if you redirect it doesn't happen.
![image](https://user-images.githubusercontent.com/15258962/144142747-9902743a-7f87-494c-a22d-8b28da437639.png)

**Comment by andschwa** [comment]
@JustinGrote Can you confirm this is now fixed?
