### ISSUE TITLE
Enable ISE Mode command fails in Azure Data Studio

### ISSUE THREAD

**Issue by williammsft** [PowerShell/vscode-powershell#3709]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

After installing the PowerShell Extension for Azure Data Studio and then attempting to enable the ISE mode an error comes up with  "Command 'PowerShell: Enable ISE Mode' resulted in an error (Running the contributed command: "PowerShell:EnableISEMode' failed.)". This is preventing ISE mode from fully loading and being useable. All that needs to be done to reproduce this with the PowerShell Extension installed is running the PowerShell: Enable ISE Mode. 

![image](https://user-images.githubusercontent.com/95380233/144338674-eaf68674-dc85-48f2-a3da-1ffd924960b9.png)

I would expect this to be similar to Visual Studio Code after launching. The version being reported by **code --list-extensions --show-versions | Select-String powershell** in Azure Data Studio is the same as the latest for Visual Studio Code, but the download reports 2021.8.2.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.62.3
ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.10.2
```

### Steps to Reproduce

1. Install Azure Data Studio (latest version 1.33.1). 
2. Does` not matter if it is the insider build or not
3. Add the Extension PowerShell v2021.8.2 (current).
4. After adding the PowerShell Extension press F1.
5. Then type >PowerShell: Enable ISE Mode. 

Result:
1. While the ISE mode attempts to start and few of the objects in Azure Data Studio load it does not complete successfully
2. The below error is what is produced.
3. Command 'PowerShell: Enable ISE Mode' resulted in an error (Running the contributed command: "PowerShell:EnableISEMode' failed.)

**Comment by andschwa** [comment]
Hi, you should not be "Adding the Extension PowerShell v2021.8.2 (current)." to Azure Data Studio, it comes with a bundled and tested PowerShell extension. Can you reinstall ADS and use the bundled extension? Having multiple copies of an extension can cause issues, especially when they try to set each other's settings (like the Enable ISE Mode command does).

**Comment by andschwa** [comment]
@SQLvariant I think this user may be hitting a bug in the old version of the extension (though I'm not entirely sure, I also suspect there's some weird state with two extensions being installed). Anyway, as ADS has four month old copy, could you please pull in [v2021.10.2](https://github.com/PowerShell/vscode-powershell/releases/tag/v2021.10.2)?

**Comment by Charles-Gagnon** [comment]
Would be glad to! Typically in the past you've had some sort of automated pipeline that opens up the PR to update the gallery, is that still active? I can do it manually if needed but we generally prefer customers maintain their own extensions when possible 😁

**Comment by andschwa** [comment]
@Charles-Gagnon In our last sync we all decided to disable that as it was broken and difficult to maintain, and ADS would just manually check if there's a new release when doing updates. I suggested automating opening an issue, but at the time you didn't want that. That suggestion is still open though! CC: @StevenBucher98 (Did you happen to take notes in that meeting?)

**Comment by Charles-Gagnon** [comment]
Ah thanks, I recall that now. Yeah opening an issue seems like a good idea for now then, at least serve as a reminder of what to do.

Did you want me to handle updating the gallery this time or is someone on your team able to take care of it?

**Comment by andschwa** [comment]
Maybe I'm not recalling correctly but I thought you'd offered to update your gallery, at least until such time that the ADS gallery became updatable by third-parties. I thought there was some pending work to make submissions easier. I can setup a step in our release process to open an issue against https://github.com/microsoft/azuredatastudio/issues when we do a stable release.

**Comment by Charles-Gagnon** [comment]
I can do the updates if you don't have resources yourself to do it, but we generally prefer that extension owners handle updating their own extensions (trying to keep track of updates of all the various partners gets overwhelming quickly).

**Comment by Charles-Gagnon** [comment]
PR to update to 2021.10.2 https://github.com/microsoft/azuredatastudio/pull/17931

**Comment by andschwa** [comment]
@williammsft Are you able to update via the ADS gallery to v2021.10.2, and if so, did it resolve your issue?

**Comment by williammsft** [comment]
@andschwa I did try going to v2021.10.2, still seeing the issue there when running the PowerShell: Enable ISE Mode. I even tried the vsix instead of using the market place one and that has not helped either.

**Comment by andschwa** [comment]
This turned out to be an issue related to the Azure Data Studio itself.
