### ISSUE TITLE
Mac OS X :: PowerShell Intellisense not invoking

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#371]
### System Details

- Operating system name and version: Mac OS X 10.11.6
- VS Code version: 1.7.2
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.13
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

PowerShell Intellisense not working for cmdlets, similar to #250. I simply receive a PowerShell code snippets auto-complete correctly, however.

- I have the latest PowerShell Alpha installed (Alpha 13).
- I already have Mac OS X Homebrew installed, and installed the OpenSSL package, per the VSCode PowerShell directions.
- The `logs` folder never gets created, despite following the directions to modify the **User Settings** file, to enable Verbose logging.

### Attached Logs

I followed the instructions to enable verbose logging, but no logs are emitted.

**Comment by pcgeek86** [comment]
![screen shot 2016-12-12 at 2 19 16 pm](https://cloud.githubusercontent.com/assets/466713/21117234/0a0d4dea-c076-11e6-9cfe-109e87329b35.png)

**Comment by daviwil** [comment]
Those instructions were updated in anticipation of the 0.8.0 release on Wednesday, you'll need to follow an extra step for now:

```
sudo ln -s /opt/local/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
sudo ln -s /opt/local/lib/libssl.1.0.0.dylib /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
```

After Wednesday's update this will no longer be necessary.  I'd release it today but we've got a couple more things to finish up.

**Comment by pcgeek86** [comment]
@daviwil Should those arguments be reversed? I just get "file exists," and the `/opt/local` directory doesn't exist.

**Comment by daviwil** [comment]
Crap, sorry, I tried to copy/paste those on the fly but got the parameters wrong.  Here's the correct lines:

```
mkdir /usr/local/lib
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/libcrypto.1.0.0.dylib
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/libssl.1.0.0.dylib
```

**Comment by pcgeek86** [comment]
I can confirm that these steps work. Thank you @daviwil.

![screen shot 2016-12-12 at 2 31 13 pm](https://cloud.githubusercontent.com/assets/466713/21117613/af9dc61c-c077-11e6-80f5-e5c4d01e9e26.png)

**Comment by daviwil** [comment]
Thanks for confirming!
