### ISSUE TITLE
F5 on a saved script isn't dot sourcing

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/vscode-powershell#3715]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Looks like we're creating a new scope for invocation of script files, leaving any set variables and functions no longer accessible.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.60.0
e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2021.11.1
```

### Steps to Reproduce

1. New file
2. Add `$a = 50`
3. Save it
4. <kbd>F5</kbd>
5. Type `$a` in the PSIC
6. See it's not set

**Comment by JustinGrote** [comment]
I feel like I called this out earlier that it was using `&` instead of `.` in the code.

**Comment by andschwa** [comment]
@rjmholt Do you remember why you changed from dot-source to ampersand-execute?

**Comment by andschwa** [comment]
Feels to me like something we should change back just for consistency among user expectations.

**Comment by rjmholt** [comment]
Probably an oversight. Moving away from dot-sourcing in the API is done for constrained language mode compatibility. In this case (if I've read correctly) that doesn't make sense because the debugger isn't going to work in CLM. Just remember that anything that dot-sources or uses `useLocalScope: false` (the default setting) will fail in CLM.

**Comment by Harryki** [comment]
Just wanna thank you for opening this issue. I've been searching "how to auto dot source when save file" and taught me F5 does dot source current file

**Comment by JustinGrote** [comment]
@harryki just to clarify, F5 runs the default debug configuration, which typically is run current PS file by default. 
![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/4634c7d5-1dcb-437d-89f9-0ee61e9fd415)


If you set the debug config to something else (like interactive mode or attach), it will always do that until you switch it again. Just an FYI to anyone else coming here who isn't sure why it isn't working for them, make sure your debug dropdown has run current file selected.
