### ISSUE TITLE
Remove-Variable can cause `cls` and `Clear-Host` to throw `You cannot call a method on a null-valued expression.`

### ISSUE THREAD

**Issue by ruffin--** [PowerShell/vscode-powershell#3718]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

If I use this command, somewhat blindly copied from [this answer](https://stackoverflow.com/a/17680309/1028230):

`Get-Variable -Exclude PWD,*Preference | Remove-Variable -EA 0`

And then use `cls` or `Clear-Host` in a script or in the integrated terminal, I receive the following error:

```
You cannot call a method on a null-valued expression.
At C:\Users\MyUser\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules\PowerShellEditorServices\Commands\Public\Clear-Host.ps1:12 char:9
+         $psEditor.Window.Terminal.Clear()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
```

The terminal _is_ otherwise cleared.

Because it's referencing a script in the `.vscode` folder, I'm assuming this is an extension issue. Entering this command in a `pwsh` terminal does _not_ cause the error to appear on `cls`.

Restarting the terminal (clicking the trash icon, for instance) "fixes" the issue until the command is re-executed.

![restarting the terminal with the kill switch](https://user-images.githubusercontent.com/5659878/145586379-924eea11-7fcc-41ce-82d2-9206e3c0d488.png)

Adding `$psEditor` to the `-Exclude` parameter in `Get-Variable` also seems to sidestep the issue.

`Get-Variable -Exclude PWD,*Preference,psEditor | Remove-Variable -EA 0`

The bug is likely (?) that `$psEditor` is exposed to the terminal window and is removable. 

### PowerShell Version

```console
PS C:\projects\pslint> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS C:\projects\pslint> code --version

1.62.3
ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
x64
```

### Extension Version

```console
PS C:\projects\pslint> code --list-extensions --show-versions | Select-String powershell


ms-vscode.powershell@2021.10.2
```

### Steps to Reproduce

```
PS> Get-Variable -Exclude PWD,*Preference | Remove-Variable -EA 0
PS> cls
```

### Visuals

![image](https://user-images.githubusercontent.com/5659878/145583403-77798b8f-ea96-4534-a335-0b2e6ddd2a2b.png)

### Logs

[logs20211210.zip](https://github.com/PowerShell/vscode-powershell/files/7693275/logs20211210.zip)

**Comment by ruffin--** [comment]
Changing the line to `Get-Variable -Exclude PWD,*Preference,psEditor | Remove-Variable -EA 0` does seem to remove this issue, so the bug is likely (?) that `$psEditor` is exposed to the terminal window.

**Comment by andschwa** [comment]
I'm not really sure what can be done here. `$psEditor` is [intentionally exposed](https://github.com/PowerShell/PowerShellEditorServices/issues/81) to the user in the integrated console because it's a user interface to the extension. If you remove it, things break. Don't do that!

@daxian-dbw do you know if it's possible to make a variable non-removable via `Remove-Variable`? If so, we could prevent users from accidentally doing this.

```
> $psEditor | Get-Member

   TypeName: Microsoft.PowerShell.EditorServices.Extensions.EditorObject

Name                  MemberType Definition
----                  ---------- ----------
Equals                Method     bool Equals(System.Object obj)
GetCommands           Method     Microsoft.PowerShell.EditorServices.Extensions.EditorCommand[], Microsoft.PowerShell.EditorServices, Version=3.0.2.0, Culture=neutral, PublicKeyToken…
GetEditorContext      Method     Microsoft.PowerShell.EditorServices.Extensions.EditorContext, Microsoft.PowerShell.EditorServices, Version=3.0.2.0, Culture=neutral, PublicKeyToken=n…
GetHashCode           Method     int GetHashCode()
GetType               Method     type GetType()
RegisterCommand       Method     bool RegisterCommand(Microsoft.PowerShell.EditorServices.Extensions.EditorCommand, Microsoft.PowerShell.EditorServices, Version=3.0.2.0, Culture=neut…
ToString              Method     string ToString()
UnregisterCommand     Method     void UnregisterCommand(string commandName)
EditorServicesVersion Property   version EditorServicesVersion {get;}
Window                Property   Microsoft.PowerShell.EditorServices.Extensions.EditorWindow, Microsoft.PowerShell.EditorServices, Version=3.0.2.0, Culture=neutral, PublicKeyToken=nu…
Workspace             Property   Microsoft.PowerShell.EditorServices.Extensions.EditorWorkspace, Microsoft.PowerShell.EditorServices, Version=3.0.2.0, Culture=neutral, PublicKeyToken…
```

**Comment by andschwa** [comment]
I'm wondering if creating the variable with `-Option Constant` would work...

**Comment by SeeminglyScience** [comment]
`Constant | AllScope` is probably what we want, that's what a few other similar variables (like `$Host`) are set with. We should definitely guard against this.

---

But for the record this is not a particularly advisable practice. A better approach is to consistently declare variables, e.g.

```powershell
# Less advisable example
foreach ($thing in $stuff) {
    if ($thing -eq 5) {
        $found = $true
    }
}

if (-not $found) { throw }

# Better
$found = $false
foreach ($thing in $stuff) {
    if ($thing -eq 5) {
        $found = $true
    }
}

if (-not $found) { throw }
```

That said, there is a middle ground:

```powershell
$existingVariables = Get-Variable
try {
    whole script here
} finally {
    Get-Variable |
        Where-Object Name -notin $existingVariables.Name |
        Remove-Variable
}
```

**Comment by daxian-dbw** [comment]
`Constant` should do the trick, but I recommend to not use `AllScope`, as that will copy this variable to very new scope created later on, for example, it will be created for every module scope when you load a module, or every local scope when running a script in a new local scope.

**Comment by SeeminglyScience** [comment]
Good point, could break someone if they happen to use `$psEditor` as a local. Thanks for catching that!

**Comment by andschwa** [comment]
Thanks both! I'll resolve this with a code change that prevents users from accidentally removing the variable.

**Comment by ruffin--** [comment]
🙏

**Comment by andschwa** [comment]
I was able to repro this, fix it, and verify the fix:

```pwsh
@andys-mac-mini ~ 
> Remove-Variable psEditor
Remove-Variable: Cannot remove variable psEditor because it is constant or read-only. If the variable is read-only, try the operation again specifying the Force option.
@andys-mac-mini ~ 
> $psEditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
3      0      2      0
```
