### ISSUE TITLE
Execute PowerShell-Code with 'F8' or 'F5' in integrated console failed

### ISSUE THREAD

**Issue by v2kiran** [PowerShell/vscode-powershell#3725]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Hello,
I have the problem, that I could not execute PowerShell code in the PowerShell integrated console by pressing 'F5' or selected code by pressing 'F8'. 

I noticed that someone else who had the same issue resolved it up updating the extension. No such luck for me because i am using the latest.

Note: this dosent happen with the PowerShell preview extension so something seems to be conflicting or broken with the "stable" 🙂 version.
I usually have one disabled when I run the other.

Regards,
Kiran Reddy

### PowerShell Version

```console
❯ $PSVersionTable


Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
❯ code --version

1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64

❯ $psEditor.EditorServicesVersion


Major  Minor  Build  Revision
-----  -----  -----  --------
2      5      2      0
```

### Extension Version

```console
❯ code --list-extensions --show-versions | Select-String powershell


justin-grote.powershell-extension-pack@0.0.5
ms-vscode.powershell@2021.10.2
ms-vscode.powershell-preview@2021.11.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

hit f5 to run the script or f8 to run selected code. nothing happens
See the vscode recorder zip file attached below for a visual representation.

### Visuals

Please see the attached zip file.
[vscode recorder.zip](https://github.com/PowerShell/vscode-powershell/files/7733596/vscode.recorder.zip)

### Logs

[Vscode all logs.zip](https://github.com/PowerShell/vscode-powershell/files/7733565/Vscode.all.logs.zip)

**Comment by andschwa** [comment]
Since it's not happening with the Preview, and that extension will soon(ish) move to the stable channel, I will close this as resolved. Thanks for the report and for testing!
