### ISSUE TITLE
Better user awareness of documentation of Powershell extension install with AllSigned group policy

### ISSUE THREAD

**Issue by ardunster** [PowerShell/vscode-powershell#3729]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Would like to request this documentation be a little more obvious somewhere, I installed the PowerShell vscode extension for the first time today hoping it would help me set up a profile script and had to follow a daisychain of multiple pages from googling the error message to find [this issue](https://github.com/PowerShell/vscode-powershell/issues/1048) and a way to activate the scripts in question to manually mark them as trusted.   Even just a "click here for additional instructions if you have the AllSigned group policy" in the "Installing the Extension" page would have helped a lot.   I know it is mentioned as documented, but I wouldn't even know where to find that documentation from just trying to install the VSCode extension.

**Comment by MN-Joe** [comment]
Based on your description above you have this working.  If so please enlighten me as to how you accomplished this.  I too am working get the PowerShell plugin to work in an AllSigned environment.  Thanks !

**Comment by ardunster** [comment]
I'm not in a position to give copy paste commands, but what I did was to look at which filename was causing errors, then manually run it with powershell and select "always run" for the Microsoft signature. For whatever reason I actually had to do this twice (two different files), I'm not sure why the signature differed. 

The documentation change in [this commit](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/3612/commits/a271ff37bb0681b6fc61c0b938ff1efe2cec05a6) might help you more directly.

**Comment by MN-Joe** [comment]
Yep - I did that but still won't run - the Microsoft Certificate expired on 12-2-2021 so maybe with the Allsigned GPO that's still preventing it from running.  When I run the script I do accept always and the expired certificate shows in my trusted publisher but still VSCode refused to start powershell.

**Comment by MN-Joe** [comment]
If anyone else is running into this issue the documentation tells you to import-module  c:\users\youruser\\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1

This is good but I don't know of a way for it to generate a prompt for you to load the certificate - you need to use powershell and load the following file: C:\Users\youruser\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PowerShellEditorServices\Start-EditorServices.ps1

**Comment by StevenBucher98** [comment]
We have instruction on how to install PS extenion on restricted systems [here](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/vscode/using-vscode?view=powershell-7.2#installing-the-powershell-extension-on-restricted-systems)
