### ISSUE TITLE
Code formatting repeats part of the code

### ISSUE THREAD

**Issue by 50Wliu** [PowerShell/vscode-powershell#3736]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Well I certainly haven't seen _this_ before. Let me know if I should move this to the PSSA repo instead.

I find myself in a bizarre situation where formatting causes part of my code to be repeated. I think a GIF explains it the best:
![vscode-powershell-formatting-quirk](https://user-images.githubusercontent.com/2766036/146991917-d85e1d09-5f4d-4c3d-ac89-84a0b81b062f.gif)
(Title is cut off because of the height - I can't share too much of the file :/)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22524
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.10.2
```

### Steps to Reproduce

I have no clue...
` and installs it` _is_ something I typed shortly before noticing this behavior, but I'm fairly certain I also typed other stuff later on.

The comment this is happening on is the first line of the file.

### Visuals

See above :)

### Logs

After setting the log level to Debug and restarting PS, the issue stopped reproducing.

**Comment by JustinGrote** [comment]
@50Wliu can you try it again with the latest preview extension?

**Comment by 50Wliu** [comment]
That's because it's the holidays, msftbot :(.
I can install the preview extension, but since I can't reliably reproduce it, I'm not sure how useful of a baseline that will be.

**Comment by 50Wliu** [comment]
Yeah, feel free to keep this one closed. I haven't had the opportunity to use PowerShell since opening this issue. If it does happen again later down the road, I'll let you know.

**Comment by andschwa** [comment]
Thanks @50Wliu! Hopefully by then we'll have the latest code deployed to the "stable" extension too.
