### ISSUE TITLE
Syntax error markers sometimes don't update for a long time

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#374]
This issue is hard to reproduce so it'd be nice if someone can come up with a solid repro.  Sometimes when editing a script file the error markers don't get cleared away when the syntax issue has been fixed in the code.  Not sure what's causing this yet, but there's some chance it could be caused by our use of a super-outdated `vscode-languageclient` library,

Reported by @adbertram, I've also seen it a few times while working on the Plaster codebase.

**Comment by rkeithhill** [comment]
Yup, I've seen the same thing.  It usually catches up though. I've sometimes tried saving the file to see if that helps and sometimes I'll just do a `reload window`.
