### ISSUE TITLE
Script path prepended when doing remote debugging. 

### ISSUE THREAD

**Issue by ptrxyz** [PowerShell/vscode-powershell#3748]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I created a `launch.json` file from the default configurations and edited it slightly to always run a specific script:

```json
{
    "configurations": [
        {
            "name": "PowerShell Launch Script",
            "type": "PowerShell",
            "request": "launch",
            "script": "z:\\world.ps1",
            "cwd": "z:\\"
        }
    ]
}
```
I do then open a remote connection to another machine where the file `world.ps1` exits on `z:\`. I then edit the file and try to debug that script and find in the interactive console that it's prepended with a temporary path `/tmp/..../z:\\world.ps1` and thus can not be found on the remote machine.

### PowerShell Version

```console
--- Remote PowerShell Version ---                                                                                                                                                                   
PSVersion                      5.1.14409.1005                                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                     
BuildVersion                   10.0.14409.1005                                                                                                                                                             
CLRVersion                     4.0.30319.34003                                                                                                                                                             
WSManStackVersion              3.0                                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                                         
SerializationVersion           1.1.0.1          


--- Local PowerShell Version ---
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.15.12-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 29 Dec 2021 12:04:52 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

- Create a file "world.ps1" on dirve "Z:\" on a remote machine.
- create a launch.json with the content above.
- Open a remote session using something like this in the interactive console:
```
$cred = [pscredential]::new('administrator@domain.net', ('password' | ConvertTo-SecureString -AsPlainText))
Enter-PSSession -ComputerName 192.168.56.101 -Authentication Negotiate -Credential $cred
```
- do `psedit z:\world.ps1` to edit the file.
- use VSCode's side pane to debug the file.
- find the file path being prepended with stuff and PowerShell not being able to execute the file.

Note: local debugging works well, no tmp-path is prepended.
Note: according to the docs, the script parameter is an absolute path.

### Visuals

![1](https://user-images.githubusercontent.com/209056/147864459-0ff3f9f9-18b9-4730-b532-3b0399ebd1eb.png)

**Comment by ptrxyz** [comment]
Added screenshot, upgraded to PS v7.2 on remote machine.

**Comment by andschwa** [comment]
Can you try the PowerShell Preview extension?
