### ISSUE TITLE
Get-Childitem works differently than in Windows Powershell

### ISSUE THREAD

**Issue by SamLowryMOI** [PowerShell/vscode-powershell#3757]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Get-Childitem shows different results in PowerShell Integrated Console v2021.12.0 and Windows ISE/PowerShell

### PowerShell Version

```console
PS> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
PS> code --version                        

1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
PS> code --list-extensions --show-versions | Select-String powershell


ironmansoftware.powershellprotools@2021.12.3
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

In PowerShell Integrated Console v2021.12.0
PS> $res = Get-ChildItem -Path 'C:\windows\system32\\*' 
PS> $res.Count
3116

In Windows ISE/PowerShell
PS> $res = Get-ChildItem -Path 'C:\windows\system32\\*' 
PS> $res.Count
4967

In $res in PowerShell Integrated Console v2021.12.0 are files listed that neither Windows ISE/PowerShell nor Windows Explorer can find.

**Comment by JustinGrote** [comment]
Can't reproduce on Win11, can you do this on a fresh computer or Azure VM?

![image](https://user-images.githubusercontent.com/15258962/148806996-747385fc-106a-415c-9285-df977f63e1fc.png)
![image](https://user-images.githubusercontent.com/15258962/148807127-217cc30e-af11-47de-b4b3-e58307e358b6.png)

**Comment by SamLowryMOI** [comment]
> ![image](https://user-images.githubusercontent.com/15258962/148806996-747385fc-106a-415c-9285-df977f63e1fc.png) 

I am really very sorry. The green circle in the picture brought the solution. For some reason Windows Powershell (x86) was chosen. Mea culpa! Everything works as expected.

Thank you for your prompt reply! And again sorry.

**Comment by JustinGrote** [comment]
@SamLowryMOI no worries we are here to help! You can try aka.ms/PSDiscord for more help if you just want to ask people if something is weird before submitting an issue.
