### ISSUE TITLE
PowerShell extension crashing when calling new elevated PS Host from script, then deletes source file

### ISSUE THREAD

**Issue by EM-HKleyn** [PowerShell/vscode-powershell#3764]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Issue Type: <b>Bug</b>

Observed behaviour:
* VSCode experiences a crash to desktop
* File on filesystem is deleted
* A restart and Git discard are required to bring back script file

Extension version: 2021.12.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.91GB free)|
|Process Argv|C:\\.dev\\Repos\\MSAdminTools\\NTFS-Tools\\Get-PermissionsReport.ps1 --crash-reporter-id fb654d2c-630b-45bd-83d3-f6fa139d4ccd|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

Steps to reproduce:
1. Run the following commands from the VSCode PowerShell terminal (VSCode is not run in Administrator mode for this)

`If (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]"Administrator")) {
	Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
	Exit
}`

### Visuals

N/A

### Logs

N/A

**Comment by StevenBucher98** [comment]
Hi @EM-HKleyn are you using this in the Integrated Console or the standalone PowerShell terminal? 

If you could also clarify your scenario, it would be super helpful for us to better understand what you are trying to do.

**Comment by EM-HKleyn** [comment]
Hey Steven,

I am using the integrated console to accomplish this. The idea behind that snippet is to escalate the script if the user hasn't opened the script as an administrator.

Cheers!


Kind regards,
Hendrik Kleyn
Office:1300 363 308
***@***.***
Website:www.eManaged.com.au

**Comment by EM-HKleyn** [comment]
That does not function the same way as the initial problem code which first checks the session elevation, then requests elevation. Additionally,  you are not using the VSCode inbuilt PowerShell terminal.


Kind regards,
Hendrik Kleyn
Office:1300 363 308
***@***.***
Website:www.eManaged.com.au
