### ISSUE TITLE
Extension Formatter Line Wrap Indentation for PowerShell Classes

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/vscode-powershell#3766]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I didn't see anything obvious in the extension settings. but maybe I missed it. When I format a PowerShell file with classes defined. there does not appear to be a setting to stop the formatter from removing/setting indentations for wrapped lines for class methods.

For example this:
```powershell
class TestClass {
    [void] MethodWithLongArgs([string] $argumentOne, [string] $argumentTwo,
            [string] $argumentThree, [string] $argumentFour) {
        [string] $stringVarWithLongAssignment =
            'this is a very long string that needs to be wrapped onto the next line'
    }
}
```
Becomes this after I run the formatter:
```powershell
class TestClass {
    [void] MethodWithLongArgs([string] $argumentOne, [string] $argumentTwo,
        [string] $argumentThree, [string] $argumentFour) {
        [string] $stringVarWithLongAssignment =
        'this is a very long string that needs to be wrapped onto the next line'
    }
}
```

It would be nice the have the ability to specify the indentation size for line wrapping, rather than it basically being no indentions, which IMO makes the code incredibly hard to read sine everything is all smooshed together at the same indentation level.

Let me know your thoughts or it I just missed the setting that controls this.

**Comment by JustinGrote** [comment]
PSScriptAnalyzer is used to actually do the formatting, so there may be a tweak in the .psd1. Have you considered just going vertical with it though?

```ps
class TestClass {
    [void] MethodWithLongArgs(
        [string] $argumentOne, 
        [string] $argumentTwo,
        [string] $argumentThree, 
        [string] $argumentFour) 
    ) {
        [string] $stringVarWithLongAssignment =
        'this is a very long string that needs to be wrapped onto the next line'
    }
}

```

Much easier to read and see what you are doing in my opinion, plus easier to quickly comment out an argument, set a breakpoint, etc.

**Comment by LethiferousMoose** [comment]
I only do vertical for PowerShell param blocks, for classes in any language I liked parameters wrapped and lined up. And thanks I will take a look at their settings. Does the plugin not expose all their options via the VS Code extension?

**Comment by JustinGrote** [comment]
@LethiferousMoose not all I don't think, you can find the settings info here:
https://github.com/PowerShell/PSScriptAnalyzer#settings-support-in-scriptanalyzer
