### ISSUE TITLE
Step Over does not return the caller and debugger locks up

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/vscode-powershell#378]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version:
- VS Code version: 1.8.0
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:
PSVersion                      5.0.10240.17146
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
### Issue Description

I am running a module (psm1) from a script and debugging it. If I place a breakpoint on a function or cmdlet call and press step over, the debugger never seems to return the caller and just sits there forcing me to kill the debugger. I have seen similar behavior if you try to step over from a function call, it does not return to the calling code. If I try to debug again following this issue, the debugger stops working with the error "Debug adapter process has terminated unexpectedly".

FYI, the logs don't seem to show any useful data, all I see is the function call and then myself killing the debugger. Likewise, all I see for what is causing the error after this occurs for way the debugger is throwing an error is this:

Socket connect ERROR: Error: read ECONNRESET
Socket closed, shutting down.

### Attached Logs

[StepOver1.zip](https://github.com/PowerShell/vscode-powershell/files/655191/StepOver1.zip)
[Debugger-Crash.zip](https://github.com/PowerShell/vscode-powershell/files/655190/Debugger-Crash.zip)

**Comment by daviwil** [comment]
Hey @LethiferousMoose, thanks for the report!  I'm missing the EditorServices.log files in the two ZIPs you sent, those will be the ones with useful information.  Can you follow [these instructions](https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us) and try to reproduce the problem again?

**Comment by LethiferousMoose** [comment]
You can probably close this one... It seems after I rebooted my computer the issue no longer occurs. I will re-log it if I see it happening again. Until then I will not be able to supply new logs.
