### ISSUE TITLE
Analyzer says a variable is declared and not used but it is

### ISSUE THREAD

**Issue by JoeBrunsTR** [PowerShell/vscode-powershell#3781]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I have some variables that are declared and then used right under.  The analyzer is saying they are not used.

![image](https://user-images.githubusercontent.com/67018945/150570564-dd97e1c5-b07e-4119-b2d8-ddd033493730.png)
![image](https://user-images.githubusercontent.com/67018945/150570589-155c7404-9ef2-47a1-9730-edf5029024f7.png)

If I take the variable and move it out of the if block, it is fine with it.

![image](https://user-images.githubusercontent.com/67018945/150570680-1056b861-7c27-4f4c-9b48-5508391d571d.png)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

I have some variables that are declared and then used right under.  The analyzer is saying they are not used.

![image](https://user-images.githubusercontent.com/67018945/150570564-dd97e1c5-b07e-4119-b2d8-ddd033493730.png)
![image](https://user-images.githubusercontent.com/67018945/150570589-155c7404-9ef2-47a1-9730-edf5029024f7.png)

If I take the variable and move it out of the if block, it is fine with it.

![image](https://user-images.githubusercontent.com/67018945/150570680-1056b861-7c27-4f4c-9b48-5508391d571d.png)

### Visuals

![image](https://user-images.githubusercontent.com/67018945/150570564-dd97e1c5-b07e-4119-b2d8-ddd033493730.png)
![image](https://user-images.githubusercontent.com/67018945/150570589-155c7404-9ef2-47a1-9730-edf5029024f7.png)
![image](https://user-images.githubusercontent.com/67018945/150570680-1056b861-7c27-4f4c-9b48-5508391d571d.png)

**Comment by JustinGrote** [comment]
In this example you're not actually using the variable, you're just assigning it again
https://user-images.githubusercontent.com/67018945/150570564-dd97e1c5-b07e-4119-b2d8-ddd033493730.png

Once you reference it the warning goes away
![image](https://user-images.githubusercontent.com/15258962/150588970-0535021b-1346-4b64-8089-22d4fdac9322.png)

**Comment by JoeBrunsTR** [comment]
One could argue that is should remove the warning in this case.
