### ISSUE TITLE
PowerShell Extension can not start in macOS (M1)

### ISSUE THREAD

**Issue by niheaven** [PowerShell/vscode-powershell#3782]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When I use PowerShell extension in a MacBook Air (M1), it always says "Loading PowerShell extension is taking longer than expected.", and it will get error at last.

The log stopped at "Waiting for session file", and the session file is always missing.

I use brew-installed powershell and VSCode Universal Edition (M1 Edition produces the error too).

### PowerShell Version

```console
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
❯ code --version

1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
arm64
```

### Extension Version

```console
❯ code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

The extension is not started.

### Visuals

<img width="1132" alt="截屏2022-01-23 03 15 39" src="https://user-images.githubusercontent.com/5832170/150652495-cf5a432e-12a1-4e2b-8e40-3eb902c16459.png">

### Logs

1/23/2022 3:02:52 AM [NORMAL] - Visual Studio Code v1.63.2 64-bit
1/23/2022 3:02:52 AM [NORMAL] - PowerShell Extension v2021.12.0
1/23/2022 3:02:52 AM [NORMAL] - Operating System: MacOS 64-bit
1/23/2022 3:02:52 AM [NORMAL] - Language server starting --
1/23/2022 3:02:52 AM [NORMAL] -     PowerShell executable: /usr/local/bin/pwsh
1/23/2022 3:02:52 AM [NORMAL] -     PowerShell args: -Login -NoProfile -NonInteractive -EncodedCommand SQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgACcALwBVAHMAZQByAHMALwBuAGkAaABlAGEAdgBlAG4ALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AbQBvAGQAdQBsAGUAcwAvAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC8AUABvAHcAZQByAFMAaABlAGwAbABFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBwAHMAZAAxACcAOwAgAFMAdABhAHIAdAAtAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAgAC0ASABvAHMAdABOAGEAbQBlACAAJwBWAGkAcwB1AGEAbAAgAFMAdAB1AGQAaQBvACAAQwBvAGQAZQAgAEgAbwBzAHQAJwAgAC0ASABvAHMAdABQAHIAbwBmAGkAbABlAEkAZAAgACcATQBpAGMAcgBvAHMAbwBmAHQALgBWAFMAQwBvAGQAZQAnACAALQBIAG8AcwB0AFYAZQByAHMAaQBvAG4AIAAnADIAMAAyADEALgAxADIALgAwACcAIAAtAEEAZABkAGkAdABpAG8AbgBhAGwATQBvAGQAdQBsAGUAcwAgAEAAKAAnAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC4AVgBTAEMAbwBkAGUAJwApACAALQBCAHUAbgBkAGwAZQBkAE0AbwBkAHUAbABlAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBuAGkAaABlAGEAdgBlAG4ALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AbQBvAGQAdQBsAGUAcwAnACAALQBFAG4AYQBiAGwAZQBDAG8AbgBzAG8AbABlAFIAZQBwAGwAIAAtAFMAdABhAHIAdAB1AHAAQgBhAG4AbgBlAHIAIAAnACcAIAAtAEwAbwBnAEwAZQB2AGUAbAAgACcARABpAGEAZwBuAG8AcwB0AGkAYwAnACAALQBMAG8AZwBQAGEAdABoACAAJwAvAFUAcwBlAHIAcwAvAG4AaQBoAGUAYQB2AGUAbgAvAC4AdgBzAGMAbwBkAGUALwBlAHgAdABlAG4AcwBpAG8AbgBzAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AMgAwADIAMQAuADEAMgAuADAALwBsAG8AZwBzAC8AMQA2ADQAMgA4ADcAOAAxADcAMgAtADIAYwA1AGEAOQA5ADgAYQAtAGIAZgAwADUALQA0ADgANQA5AC0AYQA3ADkAMQAtADIAMwAyADIANAA3AGEAZABhAGQAMgBiADEANgA0ADIAOAA3ADgAMQA0ADIAMwA2ADEALwBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBsAG8AZwAnACAALQBTAGUAcwBzAGkAbwBuAEQAZQB0AGEAaQBsAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBuAGkAaABlAGEAdgBlAG4ALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AcwBlAHMAcwBpAG8AbgBzAC8AUABTAEUAUwAtAFYAUwBDAG8AZABlAC0AOAAxADMANQA2AC0ANwA4ADEANQA3ADEAJwAgAC0ARgBlAGEAdAB1AHIAZQBGAGwAYQBnAHMAIABAACgAKQAgAA==
1/23/2022 3:02:52 AM [NORMAL] -     PowerShell Editor Services args: Import-Module '/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Diagnostic' -LogPath '/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/logs/1642878172-2c5a998a-bf05-4859-a791-232247adad2b1642878142361/EditorServices.log' -SessionDetailsPath '/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/sessions/PSES-VSCode-81356-781571' -FeatureFlags @() 
1/23/2022 3:02:52 AM [NORMAL] - pwsh started.
1/23/2022 3:02:52 AM [NORMAL] - Waiting for session file
1/23/2022 3:06:53 AM [NORMAL] - Timed out waiting for session file to appear.
1/23/2022 3:06:53 AM [NORMAL] - Language server startup failed.
1/23/2022 3:06:53 AM [ERROR] - The language service could not be started: 
1/23/2022 3:06:53 AM [ERROR] - Error: Timed out waiting for session file to appear.

**Comment by andschwa** [comment]
Hm, I'm happy to help you figure out your setup, but I am developing on an Apple M1 with this almost exclusively (so I can say it definitely works), which means this must be an issue with environment.

For what it's worth, I installed PowerShell on my macOS system via [direct download](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2#installation-via-direct-download); however, the Brew system is setup as a Cask (which means it just downloads that same installer and runs it). I am also using VS Code 1.63.2 (Universal).

Can you check if files are being created under `/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/sessions/`?

Also, would you try the PowerShell Preview extension too? Not that I can think of any changes around startup between PSES v2 and v3, but it would help to verify.

**Comment by niheaven** [comment]
I found more log:

1/25/2022 3:46:59 AM [NORMAL] -     PowerShell Editor Services args: Import-Module '/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Diagnostic' -LogPath '/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/logs/1643053618-41bb4420-86e0-421c-85b7-0c34c716a82c1643053613227/EditorServices.log' -SessionDetailsPath '/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/sessions/PSES-VSCode-16042-302933' -FeatureFlags @() 
1/25/2022 3:46:59 AM [NORMAL] - pwsh started.
1/25/2022 3:46:59 AM [NORMAL] - Waiting for session file
1/25/2022 3:46:59 AM [VERBOSE] - <qo>: Unable to send getCommand request
1/25/2022 3:46:59 AM [VERBOSE] - <qo>: Unable to send getCommand request
1/25/2022 3:47:24 AM [VERBOSE] - <qo>: Unable to send getCommand request
1/25/2022 3:50:59 AM [NORMAL] - Timed out waiting for session file to appear.
1/25/2022 3:50:59 AM [NORMAL] - Language server startup failed.
1/25/2022 3:50:59 AM [ERROR] - The language service could not be started: 
1/25/2022 3:50:59 AM [ERROR] - Error: Timed out waiting for session file to appear.

1. Sesson file doesn't be created, `sessions` folder is always blank during extension start.
2. Tried with PowerShell (2021.12.0) and PowerShell Preview (2022.1.0), results are same (no sessions file created)

BG programs are (all latest version):

- AdGuard
- CleanMyMac
- Little Snitch

**Comment by andschwa** [comment]
Hm, try extending the timeout?

https://github.com/PowerShell/vscode-powershell/blob/ddb877f1cd7fc7e1e46c0898ab1962831e005a1c/package.json#L836-L840

Are you seeing anything from Little Snitch? I know PowerShell itself has some telemetry (that you can, of course, disable) and I wonder if it's starting up, trying to send that telemetry, and is stuck by Little Snitch.

**Comment by niheaven** [comment]
Nope, every traffic from VSCode or pwsh is passed, and after I multiple the times by 10, the session file is not there...

> Unable to send getCommand request

This is the only unusual one.

**Comment by andschwa** [comment]
So I looked into `Unable to send getCommand request` and it's coming from the Command Explorer feature. I don't _think_ that would break startup, but maybe try disabling the command explorer?

**Comment by niheaven** [comment]
Yes, you are right, they just affect Command Explorer, and the extension is still not started...

**Comment by andschwa** [comment]
Are you able to _manually_ create an item in `/Users/niheaven/.vscode/extensions/ms-vscode.powershell-2021.12.0/sessions/`? It sounds like a permissions issue. If you open System Preferences and go to the security section, do you see any requests for `pwsh` to write to "Documents" or something?

**Comment by niheaven** [comment]
Yes, I could manually create files (using New-Item in PS) in the sessions folder, and I've just give VSCode full disk permission manually. There isn't any `pwsh`-related requests here. It's really strange ...

**Comment by StevenBucher98** [comment]
@niheaven Can you disable the Clean my Mac and Little Snitch programs and see if that is what is causing this issue?

**Comment by niheaven** [comment]
Nothing changed... I remove `~/.vscode` and clean `settings.json` and reinstall the extension, nothing changed... No session file.

**Comment by niheaven** [comment]
I just remove `$PROFILE.CurrentUserAllHosts` (which contains `brew` and `starship` startup code), remove `powershell` in brew, remove `VSCode` app, and reinstall `VSCode`, `powershell`, and restore `$PROFILE.CurrentUserAllHosts`, the extension works 😄 

I don't know why, but the issue solved... Thanks you guys, I'll reopen it when it occurs again (hope not).

**Comment by andschwa** [comment]
Glad to hear it's resolved!

**Comment by cabneydp** [comment]
I am actually having this same issue on multiple M1 macOS devices. No sessions are generated and so the extension never loads. I tried reinstalling VSCode and Powershell as mentioned above but it's still failing to load.

## Powershell Version
    ❯ $PSVersionTable
    
    Name                           Value
    ----                           -----
    PSVersion                      7.2.2
    PSEdition                      Core
    GitCommitId                    7.2.2
    OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101
    Platform                       Unix
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    WSManStackVersion              3.0

## VS Code Version

    ❯ code --version
    
    1.65.2
    c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
    arm64

## Extension Version

	code --list-extensions --show-versions | Select-String powershell
	
	ms-vscode.powershell@2021.12.0

## Logs

    3/28/2022  1:46:51 PM [NORMAL] - PowerShell args: -Login -NoProfile -NonInteractive -EncodedCommand SQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgACcALwBVAHMAZQByAHMALwBjAGgAcgBpAHMALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AbQBvAGQAdQBsAGUAcwAvAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC8AUABvAHcAZQByAFMAaABlAGwAbABFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBwAHMAZAAxACcAOwAgAFMAdABhAHIAdAAtAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAgAC0ASABvAHMAdABOAGEAbQBlACAAJwBWAGkAcwB1AGEAbAAgAFMAdAB1AGQAaQBvACAAQwBvAGQAZQAgAEgAbwBzAHQAJwAgAC0ASABvAHMAdABQAHIAbwBmAGkAbABlAEkAZAAgACcATQBpAGMAcgBvAHMAbwBmAHQALgBWAFMAQwBvAGQAZQAnACAALQBIAG8AcwB0AFYAZQByAHMAaQBvAG4AIAAnADIAMAAyADEALgAxADIALgAwACcAIAAtAEEAZABkAGkAdABpAG8AbgBhAGwATQBvAGQAdQBsAGUAcwAgAEAAKAAnAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC4AVgBTAEMAbwBkAGUAJwApACAALQBCAHUAbgBkAGwAZQBkAE0AbwBkAHUAbABlAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBjAGgAcgBpAHMALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AbQBvAGQAdQBsAGUAcwAnACAALQBFAG4AYQBiAGwAZQBDAG8AbgBzAG8AbABlAFIAZQBwAGwAIAAtAFMAdABhAHIAdAB1AHAAQgBhAG4AbgBlAHIAIAAnAD0APQA9AD0APQA+ACAAUABvAHcAZQByAFMAaABlAGwAbAAgAEkAbgB0AGUAZwByAGEAdABlAGQAIABDAG8AbgBzAG8AbABlACAAdgAyADAAMgAxAC4AMQAyAC4AMAAgADwAPQA9AD0APQA9AAoAJwAgAC0ATABvAGcATABlAHYAZQBsACAAJwBOAG8AcgBtAGEAbAAnACAALQBMAG8AZwBQAGEAdABoACAAJwAvAFUAcwBlAHIAcwAvAGMAaAByAGkAcwAvAC4AdgBzAGMAbwBkAGUALwBlAHgAdABlAG4AcwBpAG8AbgBzAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AMgAwADIAMQAuADEAMgAuADAALwBsAG8AZwBzAC8AMQA2ADQAOAA0ADgAOQA2ADEAMQAtADkAOQA3ADcAZQA3ADkAOAAtADIAZABmAGMALQA0AGUANgBiAC0AYgA5AGQAYwAtAGQAMwA0ADgAMgAzADYANgA0ADUAMABiADEANgA0ADgANAA4ADkANgAwADMANwA1ADQALwBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBsAG8AZwAnACAALQBTAGUAcwBzAGkAbwBuAEQAZQB0AGEAaQBsAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBjAGgAcgBpAHMALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AcwBlAHMAcwBpAG8AbgBzAC8AUABTAEUAUwAtAFYAUwBDAG8AZABlAC0AMwAzADMAOAAtADQAOAAyADEAMQA2ACcAIAAtAEYAZQBhAHQAdQByAGUARgBsAGEAZwBzACAAQAAoACkAIAA=
    
    3/28/2022  1:46:51 PM [NORMAL] - pwsh started.
    
    3/28/2022  1:46:51 PM [NORMAL] - Waiting for session file
    
    3/28/2022  1:46:51 PM [NORMAL] - PowerShell executable: /usr/local/bin/pwsh
    
    3/28/2022  1:46:51 PM [NORMAL] - Language server starting --
    
    3/28/2022  1:46:51 PM [NORMAL] - PowerShell Editor Services args: Import-Module '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.12.0 <=====
    
    ' -LogLevel 'Normal' -LogPath '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/logs/1648489611-9977e798-2dfc-4e6b-b9dc-d3482366450b1648489603754/EditorServices.log' -SessionDetailsPath '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/sessions/PSES-VSCode-3338-482116' -FeatureFlags @()
    
    3/28/2022  1:50:51 PM [NORMAL] - Timed out waiting for session file to appear.
    
    3/28/2022  1:50:51 PM [NORMAL] - Language server startup failed.
    
    3/28/2022  1:50:51 PM [ERROR] - The language service could not be started:
    
    3/28/2022  1:50:51 PM [ERROR] - Error: Timed out waiting for session file to appear.
