### ISSUE TITLE
Display the command that is running in the PowerShell console on the same line

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3786]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I know this is nitpicking but somehow in the new Preview I dislike that it shows the execution on the next line rather than on same line:

![image](https://user-images.githubusercontent.com/15063294/150972431-24cc1642-9a48-47a9-9657-6ca20dd043b6.png)

Production:

![image](https://user-images.githubusercontent.com/15063294/150972656-a59cdf7b-d6af-4923-b334-af4a55536698.png)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ironmansoftware.powershell-universal@2.5.0
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.1.1
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

Run code with F5

**Comment by JustinGrote** [comment]
Thanks for raising! It is a change in behavior and can be jarring to users so I think it's a valid ask. There's a couple other related issues e.g. debug doesn't issue newline after prompt

**Comment by andschwa** [comment]
Yeah there's a lot of work around redisplaying the prompt properly that we need to do! This is definitely valid and thank you for reporting.

**Comment by andschwa** [comment]
I'm looking at this, but I'm not sure how addressable it is. Technically when running a script via F5 or arbitrary selected code via F8, we cancel the current prompt and just run the code...so it is explicitly _not_ running on that prompt but entirely separately. Note that if you add anything to that prompt but don't hit enter, and then hit F8, everything at the prompt is thrown away instead. So what it's currently displaying is more accurate. That said, I think we could re-render the prompt in front of the command we're about to run.

**Comment by PrzemyslawKlys** [comment]
That sounds good. Btw I have a lot of issues around the display (clear-host helping partially) where the text goes over text, and even new lines stop working under debugging. Should I create separate issues or update it here?

**Comment by andschwa** [comment]
Let's see how much https://github.com/PowerShell/PowerShellEditorServices/pull/1690 and https://github.com/PowerShell/PowerShellEditorServices/pull/1691 help out with that. I'll get a new Preview out soon, and then for any more problems yes please new issues!
