### ISSUE TITLE
`Find/Install PowerShell Modules from the Gallery` command not working

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/vscode-powershell#3788]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When I try to use the command `PowerShell.PowerShellFindModule` it says it begins to load all the available modules from (pressumably) the PS Gallery and get hung and goes no where

<img width="361" alt="image" src="https://user-images.githubusercontent.com/20605456/151072774-4d697fbf-c6fe-493a-afa2-9112714e8965.png">

### PowerShell Version

```console
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
code --version
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.1.1
```

### Steps to Reproduce

`Ctrl + Shift + P` to open cmd palette, and then select the `Find/Install PowerShell Modules from the Gallery`. It does nothing. As I am not sure what it is suppose to do, I do not know what to expect what the expected output would be. Not sure if you know @SydneyhSmith?

**Comment by SydneyhSmith** [comment]
We should consider removing the feature
