### ISSUE TITLE
Collapse all or expand all functions

### ISSUE THREAD

**Issue by JoeBrunsTR** [PowerShell/vscode-powershell#3791]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Would be nice if this plug-in had a way with either a right click or keyboard shortcut to collapse all functions or expand all functions in Powershell code.

### Proposed Design

Would be nice if this plug-in had a way with either a right click or keyboard shortcut to collapse all functions or expand all functions in Powershell code.

**Comment by JustinGrote** [comment]
@JoeBrunsTR have you tried Fold?
![image](https://user-images.githubusercontent.com/15258962/151445526-83a2c5ad-1006-404e-b39e-7d8fa354e8c7.png)

**Comment by PrzemyslawKlys** [comment]
I wonder why this is hidden from the GUI. I believe it used to be visible, and now it's just under CTRL+SHIFT+P

**Comment by JustinGrote** [comment]
Never has been a "button" for it that I'm aware at least in vscode. There might be an extension that contributed one.
https://code.visualstudio.com/docs/editor/codebasics#_folding

**Comment by SeeminglyScience** [comment]
There's a UI element to fold *individual* items if you hover your mouse slightly to the right of the line numbers. I don't know of there ever being a "fold all" button though.

**Comment by PrzemyslawKlys** [comment]
There seems to be an extension https://marketplace.visualstudio.com/items?itemName=georgejames.thefoldingstuff that helps: 

![image](https://user-images.githubusercontent.com/15063294/151673319-403e6c62-7b85-4fbc-917f-126718b6476e.png)

**Comment by andschwa** [comment]
> Never has been a "button" for it that I'm aware at least in vscode. There might be an extension that contributed one.
> https://code.visualstudio.com/docs/editor/codebasics#_folding

Since this is built into VS Code, and the extension supports that feature, I'm going to mark this as answered!
