### ISSUE TITLE
[Preview] AutoComplete doesn't show types

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3797]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Preview:
![image](https://user-images.githubusercontent.com/15063294/151655312-777b426d-8cfd-438c-bc4a-a1d151fa90b4.png)

Production:
![image](https://user-images.githubusercontent.com/15063294/151655323-aa1a9c8a-364d-4e8d-b01f-393ed0f403fb.png)

Also not sure why but in production the ctrl+space gives the black window with just a type

![image](https://user-images.githubusercontent.com/15063294/151655333-7c34772f-c1cd-44e6-b03f-ec6a0d04dd4c.png)

In preview it gives more information but it's a bit stuck on first entry (DataStore) rather than following thru what's missing.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ironmansoftware.powershell-universal@2.5.0
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.1.1
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

Just run the code and try autocomplete

**Comment by JustinGrote** [comment]
Might have something to do with the module you're using, works with "built-in" commands just fine, even overloads for different parameter sets
![image](https://user-images.githubusercontent.com/15258962/151671160-157a8f43-ea73-4b5c-ad38-1b97141b4034.png)

**Comment by PrzemyslawKlys** [comment]
I mean the type in here.

![image](https://user-images.githubusercontent.com/15063294/151671220-c27c61e1-5acf-47f9-961d-413e234a2094.png)

Actually when it shows up automatically it has no type, and once i type ctrl+space it fills that in.

**Comment by JustinGrote** [comment]
I can't reproduce, I didn't hit ctrl-space here:
![image](https://user-images.githubusercontent.com/15258962/151671307-64637535-ae68-4b5c-a2c3-2ade7c49878f.png)

**Comment by PrzemyslawKlys** [comment]
ok, let it show up and then press ctrl+space multiple times - does it switch back and forth?

**Comment by JustinGrote** [comment]
I also imported pswritehtml and it worked fine, no ctrl-space
![image](https://user-images.githubusercontent.com/15258962/151671350-02ad9710-a8d1-446c-a81f-6788e544966b.png)

When using ctrl-space it pops out, as expected. Maybe your pop out location setting is messed up? I know there's a toggle for it.
![image](https://user-images.githubusercontent.com/15258962/151671377-d3a1655f-1d3d-42d5-910b-6252b24ed321.png)

**Comment by PrzemyslawKlys** [comment]
Ok, maybe it's just me. And maybe it's just my module - The window with more information doesn't follow the parameters

![image](https://user-images.githubusercontent.com/15063294/151671454-1976deb1-282d-4fc6-b952-5d149bae1780.png)
