### ISSUE TITLE
Provide npm-like feature for installing development dependency modules

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#380]
npm/package.json has the concept of "devDependencies" which are modules that get pulled down to assist with development.  The PowerShell extension should leverage some metadata, probably in the .psd1, to figure out the module/version for each dependency so that it can prompt the user to install them.  This will help module authors who need a specific version of a tool (like PSake or platyPS) pull the correct version that their project code expects.

**Comment by TylerLeonhardt** [comment]
This should be a feature in either PowerShell or PowerShellGet
