### ISSUE TITLE
`Write-Progress` not cleaned up unless `-Complete` is explicitly specified

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3807]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

![image](https://user-images.githubusercontent.com/15258962/152263409-c8bfba8a-a8a8-4d0d-9f8a-61bc94a2c737.png)

If you do a -complete it will go away. In normal PS it will go away at end of execution and return to prompt, so the "return to prompt" handling that happens in progress must not be happening in our host.

### PowerShell Version

```console
Preview
```

### Visual Studio Code Version

```console
Insiders
```

### Extension Version

```console
Preview
```

### Steps to Reproduce

`Write-Progress 'test'`

Hit enter a few times

**Comment by andschwa** [comment]
I can repro this. Any thoughts on how to fix?

**Comment by andschwa** [comment]
FWIW I tried using `_consoleHostUI` instead of `_underlyingHostUI` and it made no difference.

**Comment by andschwa** [comment]
The fix for this is out in [PowerShell Preview v2022.2.2](https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell-preview)!
