### ISSUE TITLE
Adding invalid string-interpolated watch expression puts watch window in bad state

### ISSUE THREAD

**Issue by NeoXtreem** [PowerShell/vscode-powershell#3812]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Adding an invalid string-interpolated watch expression as a third watch expression puts the watch window in bad state and makes it unusable.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.64.0
5554b12acf27056905806867f251c859323ff7e9
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

1. Debug PowerShell script and hit a breakpoint.
2. Add expression `a` to watch window.
3. Add expression `a` to watch window again.
4. Add expression `"a${a[a]}"` to watch window.

The entry for the last watch expression added shows `:`. If double-clicked, it shows `"a${a[a]}":`. However, at this point, it is impossible to change, add or remove watch expressions without killing the PowerShell terminal.

**Comment by StevenBucher98** [comment]
Thanks for opening this issue @NeoXtreem! Is this currently breaking any workflows for you?

**Comment by NeoXtreem** [comment]
@StevenBucher98 No, but it does require me to restart Visual Studio whenever it happens.

**Comment by andyleejordan** [comment]
I can't seem to repro this in v2023.8.0.
