### ISSUE TITLE
Have the Stable extension disable itself if it notices the preview extension installed 

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/vscode-powershell#3822]
### Summary of the new feature / enhancement

If a user has installed the preview extension, the stable version should disable itself as to avoid any conflicts and issues with having both extensions enabled.

**Comment by StevenBucher98** [comment]
Oops put in wrong repo

**Comment by csandfeld** [comment]
I have both extensions installed, and tend to go back and forth between the two. Would be sweet if enabling one, would automatically disable the other if present, and vice versa.

**Comment by JustinGrote** [comment]
This would ideally be solved by a unified marketplace entry with prerelease versions (https://github.com/PowerShell/vscode-powershell/issues/3716) but that's blocked on https://github.com/microsoft/vsmarketplace/issues/50 right now.

**Comment by JustinGrote** [comment]
Just noting this probably would have proactively avoided https://github.com/PowerShell/vscode-powershell/issues/3835, so there is a value to doing this.

**Comment by andschwa** [comment]
I'm actually just going to close this in favor of https://github.com/PowerShell/vscode-powershell/issues/3716.
