### ISSUE TITLE
Addition to #3741 - Microsoft Code Signing PCA certificate not installed by VS Code installer

### ISSUE THREAD

**Issue by bucmic** [PowerShell/vscode-powershell#3823]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

I would like to know how Microsoft will solve the issue regarding missing Code Signing certificates. Will the certificate be installed to Trusted Publisher store by any future VS Code installer? It's no very practicable for every user to import the certificate from the module file into the Trusted Publisher store manually.

### PowerShell Version

```console
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.63.1
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

1. Set PowerShell Execution MachinePolicy = AllSigned
2. Start VS Code 1.63.1 or higher with latest PowerShell extension installed.
3. Open PowerShell Command Explorer.
=> You'll get a message in the terminal that the publisher ist not trusted as the certificate is not installed in Trusted Publishers store.
![2022-02-11_14h48_07](https://user-images.githubusercontent.com/33121436/153602777-b44cd553-ce0e-4c10-8881-e8710f930bca.png)
Btw, the certificate is no longer valid.

**Comment by andschwa** [comment]
You are running on with an explicit AllSigned policy, it is up to you to manage your certificate trust. Trusting the certificate for you in an installer would defeat the purpose of the AllSigned policy. You should evaluate if that's a policy you actually want enforced on your system considering the trouble it's giving you.

This repository is for the PowerShell _extension_ for VS Code. Please see [Code's](https://github.com/Microsoft/vscode) for issues around their installer.

**Comment by bucmic** [comment]
@andschwa I figured out that we are using newer and some older MS Code Signing Certificates. I'm not fimiliar about all the Code  Signing Certificates used by Microsoft but wouldn't it help if you sign the extension with a current common one?

**Comment by bucmic** [comment]
Thanks, tested it. I got a security warning but I can accept the certificate without any error.
I have found quite the same certificate in my Trusted Publishers store, only difference is the creation time (by 2 mins) and the thumbprint (left one is the certificate of the extension, right one I found in my store on the client):
![image](https://user-images.githubusercontent.com/33121436/163422127-af9a9364-27fe-469b-bb9a-f9690bf21fc4.png)
