### ISSUE TITLE
Semantic Highlighting should recognize a function that doesn't follow noun-verb format if defined in the same document

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3830]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

See visual

### PowerShell Version

```console
7.2.1
```

### Visual Studio Code Version

```console
Insiders
```

### Extension Version

```console
preview
```

### Steps to Reproduce

```
function test {}

test
```

F1 -> Inspect Editor Tokens and Scopes -> hover `test` and see that support.function scope is missing

### Visuals

![image](https://user-images.githubusercontent.com/15258962/154104202-2409e4e4-ef0a-4dcf-922c-3a819af3c59e.png)

**Comment by JustinGrote** [comment]
This looks like it has been fixed.
![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/97a5340a-4ce8-4465-b67b-2bab905d9129)

**Comment by andyleejordan** [comment]
Probably in the symbol rework from abound this time last year. Though are you sure this was specifically "Semantic Highlightling" and not just regular highlighting?

**Comment by JustinGrote** [comment]
@andyleejordan note the "semantic token type" in the inspector.

**Comment by andyleejordan** [comment]
Weiiird then because we haven't touched the semantic highlighting whatsoever. Oh well, I like that it's fixed!
