### ISSUE TITLE
CTRL+C stops debugging when stopped on breakpoint

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3832]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When you start debugging and you are on a breakpoint I often go into powershell console and start doing some checks. Sometimes I do `$Value | ft` and it goes for minutes. So I often cancel after 2-3 seconds, which in new preview kills debugging. In production version it doesn't. 

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.2.0
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

1. Run Debugging
2. Stop on breakpoint
3. Type something in the console that takes time and cancel it with CTRL+C
4. Debugging ends

**Comment by andschwa** [comment]
@PrzemyslawKlys I am confused, you literally asked for Ctrl-C to stop debugging in https://github.com/PowerShell/vscode-powershell/issues/3700

It is currently working as intended: if a task is running, hitting Ctrl-C cancels it. If it was under the debugger, that exits the debugging session.

**Comment by andschwa** [comment]
See https://github.com/PowerShell/PowerShellEditorServices/commit/0f52aa2fe126add8f44852a21e3d3ee454bd8f18

**Comment by PrzemyslawKlys** [comment]
No. I asked for current command from powershell console to stop.

**Comment by PrzemyslawKlys** [comment]
No. Those are 2 different things.

1. Press F5 - code goes and pressing ctrl+c should stop it - good - you fixed it

Second problem:

1. Press F5 - code goes
2. Hits breakpoint
3. Code is stopped at this point
4. Now I can type code in console, it runs for too long - it should cancel only the command that is running, not the whole debugger session

That's how it works in prod version.

**Comment by andschwa** [comment]
The fix for this is out in [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell-preview)!
