### ISSUE TITLE
The menu 'Go to Definition' does not support 'Module-Qualified Cmdlet Names' syntax

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/vscode-powershell#3838]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Once added a module name to a function name, 'the menu' considers this syntax as a full function name. 

see: https://github.com/PowerShell/vscode-powershell/issues/928

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.1320}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.2.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

Use the 'Module-Qualified Cmdlet Names' syntax into a script.

### Visuals

**Before**

inside the module
![image](https://user-images.githubusercontent.com/4894452/154795962-0f7a458b-3ede-4abf-a9ec-82b4324257fb.png)

inside a script
![image](https://user-images.githubusercontent.com/4894452/154796027-d0730a8f-3ff1-4ab4-baa7-2ceb508e56ee.png)

**After**

inside a script
![image](https://user-images.githubusercontent.com/4894452/154796061-7c93222a-341f-4a72-9191-3fcef3aa37bb.png)

inside the module
![image](https://user-images.githubusercontent.com/4894452/154796087-d68aa754-df35-4d0d-9a18-6b79d23c2d38.png)

**Comment by SydneyhSmith** [comment]
Thanks @LaurentDardenne for opening this issue and for providing the repro steps!

**Comment by andschwa** [comment]
This is _mostly_ fixed. That is, the problem where the command name's when qualified with a module name treated the whole string as the command name has been fixed by stripping the module name when building the reference tables. However, we still have a separate "problem" where we can't jump to definition (or find references) in modules that are only imported via the import statement in a piece of code; the actual definition/references must be in script files within the workspace.
