### ISSUE TITLE
Typo in the Troubleshooting Guide:

### ISSUE THREAD

**Issue by ChessGeekBoy** [PowerShell/vscode-powershell#3840]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

There is a small typo in the troubleshooting guide.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

This was a typo in the troubleshooting guide, so there is no way to reproduce it.

### Visuals

![image](https://user-images.githubusercontent.com/81440771/154815346-35e2eac5-db6c-4fe5-b00b-21af661773ba.png)
It should be spelled "completion"

**Comment by andschwa** [comment]
@ChessGeekBoy Did you know that you can click this edit button? GitHub has really good integration for markdown documentation, it'll let you edit the file in a browser based GUI, and still in the browser, commit the fix to a branch on your fork (which it will also automatically create for you) and open a PR. Give it a try! It's slick.

<img width="1249" alt="Screen Shot 2022-02-22 at 9 16 04 AM" src="https://user-images.githubusercontent.com/2226434/155183742-0299f34e-0ee4-4337-b4cd-bd9db9161bf8.png">
