### ISSUE TITLE
IntelliSense depends on the PowerShell Integrated Terminal

### ISSUE THREAD

**Issue by ChessGeekBoy** [PowerShell/vscode-powershell#3841]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When I terminate the instance of the PowerShell Integrated Terminal, the only IntelliSense that shows up is code snippets.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

Terminate the PS Integrated Terminal and check whether IntelliSense works.

**Comment by andschwa** [comment]
This is by design. The integrated terminal is the process hosting the PowerShell module [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which powers the extension (like IntelliSense).
