### ISSUE TITLE
Intellisense preventing snippet choice function from working

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3843]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

See below.

### PowerShell Version

```console
7.2.1
```

### Visual Studio Code Version

```console
insiders
```

### Extension Version

```console
preview
```

### Steps to Reproduce

```json
  "Test Choice": {
    "prefix": "test-choice",
    "description": "Demonstrates that intellisense completion overrides the snippet choice",
    "body": [
      "${1|Test1,Test2,Test3|}"
    ]
  },
```

Expected choice of test1/test2/test3, but instead get contextual intellisense.

### Visuals

![{BFA9C473-46DF-4D4E-8037-6D9720A17255}](https://user-images.githubusercontent.com/15258962/154860477-d28e177a-ecd3-4bf5-b392-a128f98fb6d6.png)
![{9F14A99C-2866-41CA-B1D7-201D9C9FD1EA}](https://user-images.githubusercontent.com/15258962/154860487-98f38b19-a4eb-447b-8365-3bdd7091678f.png)

**Comment by andschwa** [comment]
Yeah, I'm not sure what to do about this. Is it something we caused with our extension? Is there something we don't know about how to trigger IntelliSense vs snippets?

**Comment by JustinGrote** [comment]
@andschwa I think I meant to file this in the vscode repo, sorry
