### ISSUE TITLE
Suggestion: Expandable objects in the debug console

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#386]
While going through release notes for VS Code 1.8 I came across [this enhancement](https://github.com/Microsoft/vscode/issues/15796) and thought that it would be really handy if the same would work for objects sent by PowerShell script to the standard output (pipeline) and possibly even for Verbose, Debug and Error channels. What do you think?

**Comment by daviwil** [comment]
Yep, it'd be interesting, but as we transition to using the Integrated Terminal UI for our console experience, this possibility may go away.  There may still be some way to do it from the debug console, though, will have to investigate.

**Comment by rkeithhill** [comment]
> would work for objects sent by PowerShell script to the standard output 

I don't think you'd want every object diverted from `Out-Default`.  Given this UI is specific to VSCode, perhaps PSES could export a command like `Write-ExpandableObject` when it is loaded into VSCode?

**Comment by SydneyhSmith** [comment]
Closing this as we have chosen to go with the integrated console experience.
