### ISSUE TITLE
PSReadline 2.2.2 Predictive IntelliSense not working in VSCode, but works in PowerShell and Windows Terminal

### ISSUE THREAD

**Issue by adambrubaker** [PowerShell/vscode-powershell#3861]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

After installing the new version of psreadline the Predictive IntelliSense does not work at all in vscode.  But it works wonderfully in traditional PowerShell and Windows Terminal.  I can see that the module is imported in my session and it shows the correct version.  I feel like I'm missing something easy, so hopefully this is a quick one. 

Thanks!

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

Open VSCode and start typing into the PowerShell Integrated Terminal.

### Visuals

![get-content](https://user-images.githubusercontent.com/65352063/156385095-38ecee65-fee8-4211-8897-4dd9e2693c01.PNG)

### Logs

3/2/2022 9:57:09 AM [NORMAL] - Shutting down language client...
3/2/2022 9:57:09 AM [NORMAL] - Terminating PowerShell process...
3/2/2022 9:57:09 AM [NORMAL] - Language server starting --
3/2/2022 9:57:09 AM [NORMAL] -     PowerShell executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
3/2/2022 9:57:09 AM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\abrubaker-sa\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\abrubaker-sa\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.12.0 <=====
' -LogLevel 'Diagnostic' -LogPath 'c:\Users\abrubaker-sa\.vscode\extensions\ms-vscode.powershell-2021.12.0\logs\1646233029-51660f15-6abe-4675-99d2-4332332ab0ef1646070284163\EditorServices.log' -SessionDetailsPath 'c:\Users\abrubaker-sa\.vscode\extensions\ms-vscode.powershell-2021.12.0\sessions\PSES-VSCode-9768-134348' -FeatureFlags @() 
3/2/2022 9:57:09 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\abrubaker-sa\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\abrubaker-sa\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.12.0 <=====
' -LogLevel 'Diagnostic' -LogPath 'c:\Users\abrubaker-sa\.vscode\extensions\ms-vscode.powershell-2021.12.0\logs\1646233029-51660f15-6abe-4675-99d2-4332332ab0ef1646070284163\EditorServices.log' -SessionDetailsPath 'c:\Users\abrubaker-sa\.vscode\extensions\ms-vscode.powershell-2021.12.0\sessions\PSES-VSCode-9768-134348' -FeatureFlags @() 
3/2/2022 9:57:09 AM [NORMAL] - powershell.exe started.
3/2/2022 9:57:09 AM [NORMAL] - Waiting for session file
3/2/2022 9:57:13 AM [NORMAL] - Session file found
3/2/2022 9:57:13 AM [NORMAL] - Registering terminal close callback
3/2/2022 9:57:13 AM [NORMAL] - Registering terminal PID log callback
3/2/2022 9:57:13 AM [NORMAL] - powershell.exe PID: 7784
3/2/2022 9:57:13 AM [NORMAL] - Language server started.
3/2/2022 9:57:13 AM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_a4vfxzrc.hav","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_y4sq3dxy.iff"}
3/2/2022 9:57:13 AM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_a4vfxzrc.hav...
3/2/2022 9:57:13 AM [NORMAL] - Language service connected.
3/2/2022 9:57:21 AM [WARNING] - Invalid Version: null

**Comment by adambrubaker** [comment]
Hey @JustinGrote.  I use the $profile.AllUsersAllHosts for everything so that I get the same settings for any app.  I'm setting a few PSReadLineOptions in my profile.ps1 file (see below).  But I don't seem to have to import the module for it to work.  If I open a new session and type "get-module psreadline" it comes back with version 2.2.2.  Do I need to do something else to "enable" it in VSCode?

Set-PSReadLineOption -PredictionSource History
Set-PSReadLineOption -Colors @{InlinePrediction = "DarkGray"}
Set-PSReadLineOption -PredictionViewStyle ListView

Thanks!

**Comment by SeeminglyScience** [comment]
@adambrubaker Can you try with the preview version of the extension?

Also try making sure the window is large enough for `ListView` to work. You can test this by attempting to manually set the setting like this:

![image](https://user-images.githubusercontent.com/24977523/156618404-dee04253-b522-4a27-8ad4-54f711c43a77.png)

**Comment by adambrubaker** [comment]
@SeeminglyScience  the preview version on the extension works perfectly.  I also tried setting the PredictionViewStyle to Inline and List in the non-preview.  Neither threw a warning or seemed to make a difference.

Thanks!
