### ISSUE TITLE
Please, in Word, Como fazer, Brazil, criar, Novos comando e Experiencia

### ISSUE THREAD

**Issue by eror123r** [PowerShell/vscode-powershell#3864]
Issue Type: <b>Feature Request</b>

Como, posso Fazer criar, Novos experimentos e Etc, Social novas, Comandos e Pessoas, Social e Pessoas.

Extension version: 2022.2.2
VS Code version: Code - Insiders 1.66.0-insider (6dca4c1a1f7bb3529074601eb32938526fa9ecc7, 2022-03-04T05:15:52.197Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by andschwa** [comment]
Um, this translated to "Please, in Word, How To, Brazil, Create, New Command and Experience" (title) and "How, can I do create, New experiments and etc, new Social, Commands and People, Social and People" (body). I'm sorry, I'm not sure what you're asking.
