### ISSUE TITLE
PSES doesn't start during SSH remoting to Windows 2022 Azure Edition Nano

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3868]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

PSIC opens just fine, but the PSES eventually times out after 4 minutes. What's weird is that intellisense works fine for the first bit just fine. This may be more than just this OS.

### PowerShell Version

```console
7.2.1
```

### Visual Studio Code Version

```console
Insiders
```

### Extension Version

```console
Preview
```

### Steps to Reproduce

Set up SSH remoting to Windows Server 2022 Azure Edition

### Logs

3/9/2022 1:54:48 AM [NORMAL] - pwsh.exe started.
3/9/2022 1:54:48 AM [NORMAL] - Waiting for session file
3/9/2022 1:54:48 AM [NORMAL] - Shutting down language client...
3/9/2022 1:54:48 AM [NORMAL] - Terminating PowerShell process...
3/9/2022 1:54:48 AM [NORMAL] - Language server starting --
3/9/2022 1:54:48 AM [NORMAL] -     PowerShell executable: C:\Powershell7\pwsh.exe
3/9/2022 1:54:48 AM [NORMAL] -     PowerShell args: -NoProfile -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\SHDLDevAdmin\.vscode-server-insiders\extensions\ms-vscode.powershell-preview-2022.2.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.2.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\SHDLDevAdmin\.vscode-server-insiders\extensions\ms-vscode.powershell-preview-2022.2.2\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Normal' -LogPath 'c:\Users\SHDLDevAdmin\.vscode-server-insiders\extensions\ms-vscode.powershell-preview-2022.2.2\logs\1646790888-1a3b69c0-46c8-408d-80f2-bcf1d4b1c2f31646790492936\EditorServices.log' -SessionDetailsPath 'c:\Users\SHDLDevAdmin\.vscode-server-insiders\extensions\ms-vscode.powershell-preview-2022.2.2\sessions\PSES-VSCode-undefined-422714' -FeatureFlags @() 
3/9/2022 1:54:48 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\SHDLDevAdmin\.vscode-server-insiders\extensions\ms-vscode.powershell-preview-2022.2.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.2.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\SHDLDevAdmin\.vscode-server-insiders\extensions\ms-vscode.powershell-preview-2022.2.2\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Normal' -LogPath 'c:\Users\SHDLDevAdmin\.vscode-server-insiders\extensions\ms-vscode.powershell-preview-2022.2.2\logs\1646790888-1a3b69c0-46c8-408d-80f2-bcf1d4b1c2f31646790492936\EditorServices.log' -SessionDetailsPath 'c:\Users\SHDLDevAdmin\.vscode-server-insiders\extensions\ms-vscode.powershell-preview-2022.2.2\sessions\PSES-VSCode-undefined-422714' -FeatureFlags @() 
3/9/2022 1:54:48 AM [NORMAL] - pwsh.exe started.
3/9/2022 1:54:48 AM [NORMAL] - Waiting for session file
3/9/2022 1:54:50 AM [NORMAL] - Session file found
3/9/2022 1:54:50 AM [NORMAL] - Registering terminal close callback
3/9/2022 1:54:50 AM [NORMAL] - Registering terminal PID log callback
3/9/2022 1:54:50 AM [NORMAL] - pwsh.exe PID: 5084
3/9/2022 1:54:50 AM [NORMAL] - Language server started.
3/9/2022 1:54:50 AM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_35a4fmo0.q1s","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_0mhcxs2x.45j"}
3/9/2022 1:54:50 AM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_35a4fmo0.q1s...
3/9/2022 1:54:50 AM [NORMAL] - Language service connected.
3/9/2022 1:58:48 AM [NORMAL] - Timed out waiting for session file to appear.
3/9/2022 1:58:48 AM [NORMAL] - Language server startup failed.
3/9/2022 1:58:48 AM [ERROR] - The language service could not be started: 
3/9/2022 1:58:48 AM [ERROR] - Error: Timed out waiting for session file to appear.

**Comment by andschwa** [comment]
@JustinGrote do you think this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/3466?

**Comment by JustinGrote** [comment]
@andschwa probably, seems like similar environmental conditions.

**Comment by JustinGrote** [comment]
Closing as dupe of #3466 unless we find unrelated causes
