### ISSUE TITLE
Variables in snippets now being treated as placeholders

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#387]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: macOS Sierra
- VS Code version: 1.8
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`: PS v6 alpha 13

### Issue Description

Variables inside of PowerShell snippets are now being treated as placeholders. For example, these are the exact same thing now:

$var
${var}

**Comment by adbertram** [comment]
To get around this, I've had to replace all PowerShell variables with double $. They are still treated as placeholders but if I don't change them, at least they stay that way.

**Comment by daviwil** [comment]
Fixed with #384, it'll be in today's update!
