### ISSUE TITLE
Current Preview does not have an option anymore to switch from Core-->Desktop and back

### ISSUE THREAD

**Issue by MrFly72** [PowerShell/vscode-powershell#3874]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Since the latest preview the option bottom right to change to the "other" version of powershell is missing.
Going back to production, the switch is back again

### PowerShell Version

```console
PS 30.99 ms | C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS 512.5 ms | C:\> code --version
1.65.2
c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
x64
```

### Extension Version

```console
PS 452.61 ms | C:\> code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.3.0
tobysmith568.run-in-powershell@1.1.1
```

### Steps to Reproduce

Install preview.
Try switching from PS 7.2.1 to Desktop 5.1.

On older versions, clicking on 7.2 (in the picture) brings the change option

### Visuals

![image](https://user-images.githubusercontent.com/65505278/158195853-6f2c0a2f-94c7-474f-89e3-e4fc79e0b080.png)

before:
![image](https://user-images.githubusercontent.com/65505278/158196395-86c38bc7-9e0d-4c3a-bfcb-59a53c176dfb.png)

C

**Comment by MrFly72** [comment]
Puh. Never mind. In the moment posting this, I hoovered over some of the buttons and wondered when this came up:
![image](https://user-images.githubusercontent.com/65505278/158197004-ab3f9988-2298-4b65-abdd-4a53b0a17026.png)

Sorry, but did not find this change anywhere in the docs ???

**Comment by JustinGrote** [comment]
@MrFly72 it was this PR, it will be in the docs for the stable release
https://github.com/PowerShell/vscode-powershell/pull/3869

**Comment by MrFly72** [comment]
No problem at all. its in my eyes not really comfortable if you switch Desktop<--> Core, as it would be one click more. I pinned it right away to get the second click away.
Additionally to that, what I dont like is, to figure which version I use, I now have to hoover and can not see with one view.
I am constantly switching between editions, as I use 7.x a lot for big datasets, as it is a lot faster then 5.1 in sort, group, select on big data arrays (usually 150.000 - 1.000.000 datasets).
but i need 5.1 as some of the module i have to use for products is not 7.x ready.
in my eyes dual work (5.1 + 7.x) in VSCode should be massively improved to not switch, but have both versions running and can easily decide which one to use. Switching is very time consuming.

**Comment by JustinGrote** [comment]
@MrFly72 if you click the "pin" command then you will have similar behavior to the "old" method.

**Comment by MrFly72** [comment]
@JustinGrote I did Pin it already. It is not full the same behaviour. As stated above it does not show the release choosen anymore.
For the modules. I do know, that I can import modules from 5.1 in 7.x.
BUT there are modules as stated which cannot be imported as the developers did not make the modules compatible with 7.x.
eg. Citrix Virtual Apps an Desktops, which is basically a wrapper to Add-PSSnapin, I know this is nonsense, but nevertheless I have to use it in my everyday work. My own modules are always 7.x aware, which is also not easy, as there are a couple of things where you have to script workarounds, eg:
- Missing Test-NetConnectiion --> Have to program around it to use test-connection in 7.x to make the code univeral and linux compatible
- Escapehandling in convertto-json, which is missing in 7.x and 7.x invoke-restmethods sometimes needs it for umlauts, but 5.1 invoke-restmethod seems to do it by itself.

**Comment by andschwa** [comment]
@MrFly72 We can put the version back next to the icon, I think that totally makes sense. I'll re-open this and get it into the next preview.
