### ISSUE TITLE
Canceling prompt is not possible in preview extension

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3876]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

When you use mandatory parameters and it prompts you to enter value it's impossible to cancel it with CTRL+C or SHIFT+F5.  You need to go thru the whole process and then it stops.

```powershell
function Test-Me {
    [cmdletBinding()]
    param(
        [Parameter(Mandatory = $true)] $Test
    )
}

Test-Me
```

Same thing applies to `Read-Host`

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.65.2
c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.3.0
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

1. Run any command that has mandatory parameters
2. Try to cancel it
3. Alternatively try with `Read-Host`
4. Try to cancel it

**Comment by andschwa** [comment]
Thanks @PrzemyslawKlys! I'm planning to look into this tomorrow.

**Comment by andschwa** [comment]
This is not reproducing for me with PowerShell 7.2.

**Comment by andschwa** [comment]
Hm, it's also not reproducing with Windows PowerShell 5.1 for me either.

**Comment by andschwa** [comment]
Yeah, I can't repro this _at all_. Not with the latest released preview (nor master) on Windows nor Mac with 5.1 nor 7.2, neither running `Test-Me` in the IC by itself nor from running it via F5 in the script, even with a breakpoint set.

Can you find a more specific way to repro this?

**Comment by andschwa** [comment]
```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andschwa** [comment]
Funny thing though: executing `Read-Host` directly in the IC just loops into a PSReadLine stacktrace over and over, but that's a separate bug 😆

**Comment by PrzemyslawKlys** [comment]
For me, I can reproduce CTRL+C every single time. And Shift+F5 requires at least 2 enters to get out of it. 

CtrlC example:
![CtrlC](https://user-images.githubusercontent.com/15063294/158951289-2b45be15-28a4-4ac2-b3b9-58dc1679c924.gif)

Read Host example:
![ReadHost](https://user-images.githubusercontent.com/15063294/158951298-803af3a5-68ec-4b3b-90fc-4d0c9eed2e78.gif)

**Comment by andschwa** [comment]
@PrzemyslawKlys Can you test this build?
[powershell-preview-2022.3.0.vsix.zip](https://github.com/PowerShell/vscode-powershell/files/8319779/powershell-preview-2022.3.0.vsix.zip) It has commit https://github.com/PowerShell/PowerShellEditorServices/commit/4cadd73c7f1b437e5699fb2ed3e49276a094a367 which I want to see the effects of...

**Comment by PrzemyslawKlys** [comment]
It doesn't work :) 

![image](https://user-images.githubusercontent.com/15063294/159428356-c5f84166-1779-430a-a4ca-5b788b240c8c.png)

![image](https://user-images.githubusercontent.com/15063294/159428416-93d70a0e-5355-4574-ae3f-ce20667e6d94.png)

**Comment by PrzemyslawKlys** [comment]
Weirdly enough I cannot use the old preview anymore, i have to go back 3 weeks and use the 3 weeks old version. Otherwise I get this whenever i try to update to newest version (not even your version). 

![image](https://user-images.githubusercontent.com/15063294/159428920-31384243-91f4-4e19-ab26-2642a8801359.png)

I've broken something ;)

**Comment by andschwa** [comment]
Ok, I have no idea what's happened to your environment there, oops 😅 but I tried again, on Windows with PS 5.1 too, and can always Ctrl-C to cancel `Test-Me`. @SeeminglyScience You said you were able to repro this?

**Comment by andschwa** [comment]
I still can't repro this at all. How up-to-date is your Windows environment @PrzemyslawKlys, and is this a major blocker for you?

**Comment by PrzemyslawKlys** [comment]
I'm on cutting edge Windows 11 ;) It's not a blocker at all. Lately, I'm really enjoying the plugin and its features. don't have to restart, everything seems to work. This is one of those things that shows up, but I know I can just press CTRL+C, and a few times enter and it will work ;) 

I typed the command, it prompted - i typed text ... pressed CTRL+C, it didn't work, I pressed enter - and as you see below it didn't assign the value to anything.
![image](https://user-images.githubusercontent.com/15063294/160002122-2782f25c-b82f-4150-92ce-dcb80932ed21.png)

That means CTRL+C actually worked, but I think it's related to other issue that sometimes you need to press ENTER to see the prompt when the script is "done". It may be just visual bug.

**Comment by andschwa** [comment]
It's strange, for sure, and I want to get it fixed. Thank you for the kind words, we're really working on launching this soon to the stable channel. We know it's not perfect, but are increasingly convinced that it's _much_ better than it was. Preparing hopefully the second-to-last preview right now!

**Comment by andschwa** [comment]
Ok, it's a long shot, but does this continue to repro with the new release yesterday? v2022.3.1-preview.

**Comment by andschwa** [comment]
Hm, 2.2.2 is the latest. I wish I could repro this myself 🥲

**Comment by PrzemyslawKlys** [comment]
If you need any logs I can provide ;) If you need any other help - i'm here...

**Comment by andschwa** [comment]
Hi there, we just released [v2022.4.0-preview](https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.4.0-preview)! Could you please try [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) and check if this is fixed? I could still never repro it myself, _but_ I implemented what I hope to be a much better way to cancel `Console.ReadKey` and so avoid deadlocks like this.

**Comment by PrzemyslawKlys** [comment]
No luck ;) 

![Didnthelp](https://user-images.githubusercontent.com/15063294/163118461-36a43447-d515-49b6-b17b-53ffcc0ee1a0.gif)

**Comment by andschwa** [comment]
Dumb question, but what about other terminals in Code, or other PowerShell versions? At this point I feel like there's something configured in Code that's taken that key handler, and I still can't repro 😭 Underneath the covers, it really is just `Console.ReadKey` now!

**Comment by PrzemyslawKlys** [comment]
You're correct. If I paste Read-Host into a separate terminal in code it acts the same. So the big question is - how to track it ;)

**Comment by andschwa** [comment]
AH! I hate to do this to you...but file a bug with [Code](https://github.com/microsoft/vscode).

**Comment by andschwa** [comment]
Just be _very_ clear that it repros in standard PowerShell terminals in VS Code, no extension required!

**Comment by PrzemyslawKlys** [comment]
But it doesn't repro for you...

**Comment by SeeminglyScience** [comment]
> But it doesn't repro for you... so maybe some of my settings is affecting this.

Try enabling `Developer: Toggle Keyboard Shortcuts Troubleshooting`, selecting the terminal panel, pressing <kbd>Ctrl</kbd> + <kbd>C</kbd> and the go back to `Output`. See what you have there

Here's mine for instance:

![image](https://user-images.githubusercontent.com/24977523/163238144-361a2cb5-1b20-45aa-a267-e6067eb2c19b.png)

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/163238400-76e8a8f7-5c07-4908-b323-55956aeea9c7.png)
![image](https://user-images.githubusercontent.com/15063294/163238496-d76b5d09-68ab-4960-9d92-2ad23301fbf9.png)

**Comment by SeeminglyScience** [comment]
What about `    "terminal.integrated.windowsEnableConpty": true,` you got that on?

**Comment by SeeminglyScience** [comment]
Also the original issue says 5.1, can you check if 7 has the same behavior?

**Comment by PrzemyslawKlys** [comment]
I have it disabled `    "terminal.integrated.windowsEnableConpty": false,` after enabling it ---> IT WORKS!

**Comment by PrzemyslawKlys** [comment]
I had it disabled based on: https://github.com/PowerShell/vscode-powershell/issues/2377

**Comment by SeeminglyScience** [comment]
WOOT

Yeah conpty solves **a lot** of input related issues. Even when that bug was still going I just grit my teeth through it as it's fixes were worth the very frustrating bug. I forgot all about that... that was rough 😁

**Comment by andschwa** [comment]
It wasn't false! Something was buggy, and I'm glad @SeeminglyScience knew what was up, woo 🥳
