### ISSUE TITLE
Debug may not start if file has special characters in its name

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#3882]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Issue From PS Discord

If you have special characters like # or ' in the filename, the debug won't start with a pipeline error

### PowerShell Version

```console
5.1
```

### Visual Studio Code Version

```console
Unknown
```

### Extension Version

```console
Unknown
```

### Steps to Reproduce

Create a file with special characters like # or ' and try to debug it

### Visuals

![image](https://user-images.githubusercontent.com/15258962/158860760-747daedb-c6c9-49fc-9932-61f12a0bc46b.png)

**Comment by SydneyhSmith** [comment]
@JustinGrote thank so much for this issue! Do you happen to know if this is a regression in preview?

**Comment by JustinGrote** [comment]
This came from Discord, I'm not sure if it is a regression or not

**Comment by SydneyhSmith** [comment]
hmmm I am unable to reproduce this on latest preview with 5.1 or 7.2
