### ISSUE TITLE
1.7.2 freezes on debugging with Visual Studio Code 1.8

### ISSUE THREAD

**Issue by baileyjames9** [PowerShell/vscode-powershell#389]
**Please fill in these details so that we can help you!**

### System Details
Visual Studio Code 1.8.0 
Powershell extension 1.7.2

- Operating system name and version:2012
- VS Code version:1.8
- PowerShell extension version:1.7.2
- Output from `$PSVersionTable:

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am experiencing a problem with debugging powershell scripts and the ide freezing as I step into the script on various lines of code. 

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
May be related to https://github.com/PowerShell/vscode-powershell/issues/378, will investigate.

**Comment by daviwil** [comment]
Hey @baileyjames9, if you can still reproduce this issue, do you mind capturing logs with the following instructions and send them to me:

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

If you'd prefer not to send the logs in the open you can send them via email: *daviwil [at] microsoft.com*

**Comment by Hummer311** [comment]
I'm also xperiencing the same issue. I'll follow the above instructions and you the log hn I get home.

**Comment by Hummer311** [comment]
Some additional logs - I believe I started experiencing  problems when I configured a launch.json. [logs2.zip](https://github.com/PowerShell/vscode-powershell/files/797931/logs2.zip)

**Comment by SiloReed** [comment]
@daviwil it appears that I see something similar when debugging a PowerShell script that executes the 'Login-AzureRMAccount' cmdlet. I workaround the problem by first connecting to Azure in the interactive terminal before debugging the script. I have the VS Code logs if you would like me to email them to you.

**Comment by rjmholt** [comment]
Closing as defunct
