### ISSUE TITLE
Powershell Extension fails to Initialize on macOS (M1, Apple Silicon)

### ISSUE THREAD

**Issue by cabneydp** [PowerShell/vscode-powershell#3894]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

When I attempt to load the PowerShell extension on macOS it says "Loading PowerShell extension is taking longer than expected" and will eventually time out. 

The log will stop at "Waiting for session file", and no session file is generated. I have installed Powershell via Brew and installed VSCode from the website download. This is a very recent issue, I did not have this issue a week or so ago. I have tried reinstalling both VSCode and Powershell with no success.

It appears to be the same issue as this. https://github.com/PowerShell/vscode-powershell/issues/3782

### OS & Device
M1 Mac Mini
macOS Monterey 12.3

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.65.2
c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
arm64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

Attempt to load PowerShell Extension in VSCode

### Visuals

![image](https://user-images.githubusercontent.com/97906386/160459307-528aac08-3b43-4865-90ce-a8550bd90352.png)

![image](https://user-images.githubusercontent.com/97906386/160459347-eff5f015-1865-473f-aa59-1bbc667f2180.png)

### Logs

3/28/2022 1:46:51 PM [NORMAL] - Visual Studio Code v1.65.2 64-bit
3/28/2022 1:46:51 PM [NORMAL] - PowerShell Extension v2021.12.0
3/28/2022 1:46:51 PM [NORMAL] - Operating System: MacOS 64-bit
3/28/2022 1:46:51 PM [NORMAL] - Language server starting --
3/28/2022 1:46:51 PM [NORMAL] -     PowerShell executable: /usr/local/bin/pwsh
3/28/2022 1:46:51 PM [NORMAL] -     PowerShell args: -Login -NoProfile -NonInteractive -EncodedCommand SQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgACcALwBVAHMAZQByAHMALwBjAGgAcgBpAHMALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AbQBvAGQAdQBsAGUAcwAvAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC8AUABvAHcAZQByAFMAaABlAGwAbABFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBwAHMAZAAxACcAOwAgAFMAdABhAHIAdAAtAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAgAC0ASABvAHMAdABOAGEAbQBlACAAJwBWAGkAcwB1AGEAbAAgAFMAdAB1AGQAaQBvACAAQwBvAGQAZQAgAEgAbwBzAHQAJwAgAC0ASABvAHMAdABQAHIAbwBmAGkAbABlAEkAZAAgACcATQBpAGMAcgBvAHMAbwBmAHQALgBWAFMAQwBvAGQAZQAnACAALQBIAG8AcwB0AFYAZQByAHMAaQBvAG4AIAAnADIAMAAyADEALgAxADIALgAwACcAIAAtAEEAZABkAGkAdABpAG8AbgBhAGwATQBvAGQAdQBsAGUAcwAgAEAAKAAnAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC4AVgBTAEMAbwBkAGUAJwApACAALQBCAHUAbgBkAGwAZQBkAE0AbwBkAHUAbABlAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBjAGgAcgBpAHMALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AbQBvAGQAdQBsAGUAcwAnACAALQBFAG4AYQBiAGwAZQBDAG8AbgBzAG8AbABlAFIAZQBwAGwAIAAtAFMAdABhAHIAdAB1AHAAQgBhAG4AbgBlAHIAIAAnAD0APQA9AD0APQA+ACAAUABvAHcAZQByAFMAaABlAGwAbAAgAEkAbgB0AGUAZwByAGEAdABlAGQAIABDAG8AbgBzAG8AbABlACAAdgAyADAAMgAxAC4AMQAyAC4AMAAgADwAPQA9AD0APQA9AAoAJwAgAC0ATABvAGcATABlAHYAZQBsACAAJwBOAG8AcgBtAGEAbAAnACAALQBMAG8AZwBQAGEAdABoACAAJwAvAFUAcwBlAHIAcwAvAGMAaAByAGkAcwAvAC4AdgBzAGMAbwBkAGUALwBlAHgAdABlAG4AcwBpAG8AbgBzAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AMgAwADIAMQAuADEAMgAuADAALwBsAG8AZwBzAC8AMQA2ADQAOAA0ADgAOQA2ADEAMQAtADkAOQA3ADcAZQA3ADkAOAAtADIAZABmAGMALQA0AGUANgBiAC0AYgA5AGQAYwAtAGQAMwA0ADgAMgAzADYANgA0ADUAMABiADEANgA0ADgANAA4ADkANgAwADMANwA1ADQALwBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBsAG8AZwAnACAALQBTAGUAcwBzAGkAbwBuAEQAZQB0AGEAaQBsAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBjAGgAcgBpAHMALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AcwBlAHMAcwBpAG8AbgBzAC8AUABTAEUAUwAtAFYAUwBDAG8AZABlAC0AMwAzADMAOAAtADQAOAAyADEAMQA2ACcAIAAtAEYAZQBhAHQAdQByAGUARgBsAGEAZwBzACAAQAAoACkAIAA=
3/28/2022 1:46:51 PM [NORMAL] -     PowerShell Editor Services args: Import-Module '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.12.0 <=====
' -LogLevel 'Normal' -LogPath '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/logs/1648489611-9977e798-2dfc-4e6b-b9dc-d3482366450b1648489603754/EditorServices.log' -SessionDetailsPath '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/sessions/PSES-VSCode-3338-482116' -FeatureFlags @() 
3/28/2022 1:46:51 PM [NORMAL] - pwsh started.
3/28/2022 1:46:51 PM [NORMAL] - Waiting for session file
3/28/2022 1:50:51 PM [NORMAL] - Timed out waiting for session file to appear.
3/28/2022 1:50:51 PM [NORMAL] - Language server startup failed.
3/28/2022 1:50:51 PM [ERROR] - The language service could not be started: 
3/28/2022 1:50:51 PM [ERROR] - Error: Timed out waiting for session file to appear.

**Comment by andschwa** [comment]
Hello! The latest code is available in the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview), and includes a myriad of fixes (including better support for Apple M1 processors). Could you verify if this issue still reproduces using the preview extension? Please note that this preview is likely to include other bugs, and you should feel free to file new issues for those so we can work through them. Thanks again!

**Comment by andschwa** [comment]
Glad to hear it!
