### ISSUE TITLE
Immediate Write-Host after Invoke-WebRequest

### ISSUE THREAD

**Issue by dperez83** [PowerShell/vscode-powershell#3895]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

Immediate Write-Host after Invoke-WebRequest should be written on console, but it's not shown.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.65.2
c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

```
Write-Host "before dl"
Invoke-WebRequest -Uri https://github.com/Naunter/BT_BlockLists/releases/download/master/bt_blocklists.gz -OutFile bt_blocklists.gz 
Write-Host "test 1"
Write-Host "test 2"
Write-Host "test 3"
Write-Host "test 4"
```

### Visuals

![image](https://user-images.githubusercontent.com/42227137/160500871-99245469-f544-454a-9938-0afd947e0edd.png)

### Logs

[exthost1.zip](https://github.com/PowerShell/vscode-powershell/files/8366868/exthost1.zip)

**Comment by andschwa** [comment]
Hello! The latest code is available in the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview), and includes a myriad of fixes. Could you verify if this issue still reproduces using the preview extension? Please note that this preview is likely to include other bugs, and you should feel free to file new issues for those so we can work through them. Thanks again!

**Comment by dperez83** [comment]
> Hello! The latest code is available in the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview), and includes a myriad of fixes. Could you verify if this issue still reproduces using the preview extension? Please note that this preview is likely to include other bugs, and you should feel free to file new issues for those so we can work through them. Thanks again!

Yes it's fixed in the preview, thank you!

![image](https://user-images.githubusercontent.com/42227137/160528156-8c18f980-45e9-4712-9bf3-87cbc30f82e2.png)
