### ISSUE TITLE
Breakpoint on return doesn't behave properly

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3896]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

I have been debugging something and noticed that my

```powershell
function TestMe {
    [cmdletBinding()]
    param(

    )

    $Test = Get-Verb

    Write-Host "Test"
    return
}

TestMe
```

![image](https://user-images.githubusercontent.com/15063294/160709619-8ec5b0e1-f4a0-471b-9bc4-3bbc57412642.png)

This can lead to some problems when trying to understand where I'm at for more complicated code:

![image](https://user-images.githubusercontent.com/15063294/160709842-e0c1a61f-7243-425f-8184-6ffc85af7ab3.png)

```powershell
function TestMe {
    [cmdletBinding()]
    param(

    )

    $Test = Get-Verb

    Write-Host "Test"
    return
}

function TestMe2 {
    [cmdletBinding()]
    param(

    )

    $Test = Get-Verb


    if ($test.count -eq 5) {
        Write-Host "test1"
        return
    } elseif ($test.count -eq 1) {
        Write-Host "test"
        return
    }
    Write-Host "Test"
    return
}

TestMe2
```

According to @SeeminglyScience it's a PowerShell bug so I'll link it there, but I do hope it could be somehow addressed for PowerShell 5.1 in code as well.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.588
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.588
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.65.2
c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.3.1
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

Run the code, set breakpoint on return, notice it stops on next line rather than on return.

**Comment by SydneyhSmith** [comment]
Thanks @PrzemyslawKlys we are going to mark this as answered
