### ISSUE TITLE
New Project experience doesn't open project folder correctly in some cases

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#390]
Destination paths like the following don't open correctly:

- `~/MyNewModule`
- `$HOME/MyNewModule`

We should resolve these paths in the language server and send back the full path to the new workspace so that VS Code doesn't need to resolve the path (especially in the case of using PowerShell variables like `$HOME`).

**Comment by daviwil** [comment]
Ultimately depends on https://github.com/PowerShell/Plaster/issues/218 being wired up through Editor Services.

**Comment by rkeithhill** [comment]
I'll look into this today.
