### ISSUE TITLE
Support New VS Code Shell Integration Feature

### ISSUE THREAD

**Issue by juvtib** [PowerShell/vscode-powershell#3901]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

VS Code introduced the [shell integration](https://code.visualstudio.com/updates/v1_64#_terminal-shell-integration) feature in January. When the PowerShell extension launches its Integrated Console, the shell integration is not launched with it. It is not obvious if or how to manually launch the new feature. 

Please respect the `terminal.integrated.shellIntegration.enabled` setting. And allow the new VS Code feature to work with the terminal launched by the PowerShell extension.

**Comment by JustinGrote** [comment]
I noticed in the documentation they said they shim in a .ps1, so that wouldn't be that hard to just add a setting to call it if that's all it is, not sure if there's more to it though.

**Comment by juvtib** [comment]
Are extensions able to read the preferences for VS Code? Or is there some benefit to creating a new preference besides `terminal.integrated.shellIntegration.enabled`?

**Comment by JustinGrote** [comment]
There are cases where you might want it for your integrated terminal but not PSIC, but yes, extensions can read settings and it would probably be gated behind both these settings, e.g.

`powershell.enableShellIntegration` and `terminal.integrated.shellIntegration.enabled` would both have to be specified in order for it to inject the .ps1 (or whatever else is required for shell integration)

**Comment by danielniccoli** [comment]
> It's still an experimental feature: https://code.visualstudio.com/docs/editor/integrated-terminal#_shell-integration
> 
> So it's unlikely to be the _default_, however we could look into adding a feature flag for it. The PSIC is not a normal integrated terminal so I'm not sure if there will be related regressions or something to tell vscode to flag the PSIC as an "integrated" terminal.

[Shell integration iw now enabled by default](https://code.visualstudio.com/updates/v1_70#_shell-integration-enabled-by-default)

**Comment by andschwa** [comment]
We are working on this actively!

**Comment by juvtib** [comment]
Thanks for addressing this issue. I'm not sure how PowerShell Editor Services is integrated into the PowerShell extension and VS Code. How will I know when this feature makes it to VS Code or the Insiders edition?

**Comment by JustinGrote** [comment]
@juvtib PSES is basically the LSP for the plugin. If this has been committed to PSES I would expect to see it in the next preview release of the PowerShell extension which comes out pretty regularly.

**Comment by andschwa** [comment]
Like today is the plan lol
