### ISSUE TITLE
Not in file Scriptblock debugging create empty temporary file

### ISSUE THREAD

**Issue by ili101** [PowerShell/vscode-powershell#3904]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

On stable a temporary file is created with the content of the scriptblock and debugged normally.
On preview temporary empty file is created.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.66.0
e18005f0f1b33c29e81d732535d8c0e47cafb0b5
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.3.1
```

### Steps to Reproduce

```powershell
$X = {
    Set-PSBreakpoint -Variable Foo
    $Foo = 0
    1
    2
    3
}.ToString()

. ([Scriptblock]::Create($X))
```

### Visuals

![image](https://user-images.githubusercontent.com/6960531/161400497-8c5e2588-ec09-4ec4-b5b5-6247d2d9355e.png)

**Comment by SeeminglyScience** [comment]
I noticed this as well while working on something attach to process related. Glad to know it's not something I just broke :)

Lookin' into it, thanks @ili101!

**Comment by andschwa** [comment]
Has this continued to repro?

**Comment by ili101** [comment]
Yes still broken in preview

**Comment by SeeminglyScience** [comment]
Yep it's on my list but I haven't actually done anything to fix it yet.

I was initially thinking it wouldn't be a blocker but this might make debugging pester tests in particular a huge PITA.

**Comment by andschwa** [comment]
From Patrick: The remote file manager is for some reason not populating the file in this scenario, but is creating it.

**Comment by andschwa** [comment]
Easy way to repro: type "Wait-Debugger" in console.

**Comment by andyleejordan** [comment]
Ok I have a partial answer. Debugging this, in the `DebugService` we have this bit of code that _should_ be getting the lines of the script...and it's not:

```c#
                    PSCommand psCommand = new PSCommand().AddScript($"list 1 {int.MaxValue}");

                    IReadOnlyList<PSObject> scriptListingLines =
                        await _executionService.ExecutePSCommandAsync<PSObject>(
                            psCommand, CancellationToken.None).ConfigureAwait(false);
```

Hence why that temporary file is empty. `scriptListingLines` is quite empty!

**Comment by andyleejordan** [comment]
Sorry this took so long @ili101 but it will be fixed in the next pre-release!
