### ISSUE TITLE
Some _other_ way to get the PowerShell Integrated Console when I set `showOnStartup` to false

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#3918]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I don't like the integrated terminal popping up in the beginning. I understand _why_ it does that, but for me, I set `showOnStartup` to `false` because I want it to be in the background. However, when I _do_ want it, I only have one option: the command palette: `Show Integrated Console` or probably another one is starting a debug session.

It would be nice if there was another way to get at this.

### Proposed Design

Couple options... still thinking out loud though:

---

Could the PowerShell extension contribute a Terminal Profile so that it shows up in this list:
![image](https://user-images.githubusercontent.com/2644648/163067285-2f384877-3b19-47d8-a36c-a96ed0f6b5c6.png)

Then if you click on it, it will show up? The only thing I'm not so sure about is how does this work if you choose that profile multiple times (since there currently can only be 1 (ish) Integrated Console)? (an interesting thought @Tyriar @meganrogge)

---

Maybe there could be another Language Status entry for showing the Integrated Console?

---

Perhaps a button in the top right that shows the Integrated Console (when it's hidden)?
![image](https://user-images.githubusercontent.com/2644648/163067704-0c2cd72b-e4a9-4b2a-911b-0a4855d2d50a.png)

**Comment by meganrogge** [comment]
You called out a concern I'd have with putting it in the dropdown - that the integrated console can't get created multiple times whereas the other profiles can be.

Once it's been created, we could handle this by either removing the item from the dropdown or disabling it. 

That would require new API on `ExtensionTerminalOptions`, for example:

```
singleton?: boolean;
```

**Comment by TylerLeonhardt** [comment]
Of course https://github.com/PowerShell/vscode-powershell/issues/2418 would make this issue invalid. It's something I always wanted to experiment with... essentially having multiple Integrated Consoles (and thus multiple langugage servers) and then the most recent active PSIC would "take over" as the active language server. This is how ISE does it.

but that's a "run" where we should probably crawl and walk first :)

**Comment by andschwa** [comment]
Yeah for real, this is annoying (just set this setting myself and I'm like...where on earth is the console).

**Comment by JustinGrote** [comment]
I'm pretty sure running `Restart Integrated Terminal` command makes it pop up again, not really intuitive but an alias command to run the same process could be made that says "Start Integrated Terminal"

**Comment by Tyriar** [comment]
I don't think the singleton idea would be generally useful to other extensions so I'm not a fan.
