### ISSUE TITLE
Quick Fix action is not working 

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#392]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: Windows 10, 
- VS Code version: 1.8.0
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.479
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.479
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with...Quick fix actions do not seem to work either with accessing the light bulb prompt or actually applying the quick fix. At times it seems the light bulb disappears and code things I'm adding breakpoints.

![quickfixissue](https://cloud.githubusercontent.com/assets/11204251/21283288/ae28cb00-c3c5-11e6-8a50-7dcc441503bb.gif)

### Attached Logs

[vscode-powershell.txt](https://github.com/PowerShell/vscode-powershell/files/658580/vscode-powershell.txt)
[EditorServices.txt](https://github.com/PowerShell/vscode-powershell/files/658581/EditorServices.txt)

**Comment by kapilmb** [comment]
Looks like the document is unsaved. The current implementation of quick fix does not work in unsaved (untitled-1) documents.

**Comment by wsmelton** [comment]
Ok here it is in a saved file, same version and computer...

![quickfix_issue_savedfile](https://cloud.githubusercontent.com/assets/11204251/21290156/318dbb2c-c475-11e6-87e3-cd2539328bdc.gif)

**Comment by daviwil** [comment]
Hey Shawn, this could be a UI issue with VS Code.  When you see this happen, try pressing <kbd>Ctrl+.</kbd> when your cursor is on `gci` and see if it gives you the corrections menu.  If it still works in that case we might need to file a bug at the VS Code repo.

**Comment by wsmelton** [comment]
Yep, `CTRL + .` brings up the content menu for me to use.

**Comment by daviwil** [comment]
Thanks for verifying Shawn!  I filed issue https://github.com/Microsoft/vscode/issues/17540 on the VS Code repo to see if they can fix the disappearing lightbulb issue.
