### ISSUE TITLE
The language service could not be started after installing powershell 7

### ISSUE THREAD

**Issue by Gt3pccb** [PowerShell/vscode-powershell#3922]
## Summary

Hello I installed PowerShell 7, and after that I get this error
4/13/2022 6:31:31 PM [NORMAL] - Visual Studio Code v1.66.2 64-bit
4/13/2022 6:31:31 PM [NORMAL] - PowerShell Extension v2021.12.0
4/13/2022 6:31:31 PM [NORMAL] - Operating System: Windows 64-bit
4/13/2022 6:31:31 PM [NORMAL] - Language server starting --
4/13/2022 6:31:31 PM [NORMAL] -     PowerShell executable: C:\Program Files\PowerShell\7\pwsh.exe
4/13/2022 6:31:31 PM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\astolfor\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\astolfor\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.12.0 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\astolfor\.vscode\extensions\ms-vscode.powershell-2021.12.0\logs\1649899891-bb788c33-453e-475b-b44a-7b764215800c1649899883245\EditorServices.log' -SessionDetailsPath 'c:\Users\astolfor\.vscode\extensions\ms-vscode.powershell-2021.12.0\sessions\PSES-VSCode-13624-676034' -FeatureFlags @() 
4/13/2022 6:31:31 PM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\astolfor\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\astolfor\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.12.0 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\astolfor\.vscode\extensions\ms-vscode.powershell-2021.12.0\logs\1649899891-bb788c33-453e-475b-b44a-7b764215800c1649899883245\EditorServices.log' -SessionDetailsPath 'c:\Users\astolfor\.vscode\extensions\ms-vscode.powershell-2021.12.0\sessions\PSES-VSCode-13624-676034' -FeatureFlags @() 
4/13/2022 6:31:31 PM [NORMAL] - pwsh.exe started.
4/13/2022 6:31:31 PM [NORMAL] - Waiting for session file
4/13/2022 6:35:32 PM [NORMAL] - Timed out waiting for session file to appear.
4/13/2022 6:35:32 PM [NORMAL] - Language server startup failed.
4/13/2022 6:35:32 PM [ERROR] - The language service could not be started: 
4/13/2022 6:35:32 PM [ERROR] - Error: Timed out waiting for session file to appear.

I have uninstalled and installed the Powershell extension, PS7 and VSCode but VSCode still having this error.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z (2 days ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

[OK] [Copy]
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

Launch VScode after installing PS7

### Visuals

![image](https://user-images.githubusercontent.com/50630795/163300915-b63b6071-c2b9-4aff-87bb-c27935bd022c.png)

### Logs

[20220413T183029.zip](https://github.com/PowerShell/vscode-powershell/files/8485753/20220413T183029.zip)

**Comment by andschwa** [comment]
Hello! The latest code is available in the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview), and includes a myriad of fixes. Could you verify if this issue still reproduces using the preview extension? Please note that this preview is likely to include other bugs, and you should feel free to file new issues for those so we can work through them. Thanks again!

**Comment by Gt3pccb** [comment]
I have the latest code.

**Comment by andschwa** [comment]
I see a strange thing in your logs:

> WARNING: In development mode but PowerShellEditorServices dev module path cannot be found (or has not been built yet)

**Comment by Gt3pccb** [comment]
How do I make code to start in its default mode? I do not know this was set.  How do I revert back to its default. I have uninstall Vs Code a few times and right from the very first VS Code open I get these errors.

**Comment by andschwa** [comment]
It's a command line flag, you should start `code` without it. How are you starting Code?

**Comment by Gt3pccb** [comment]
Click VS code in the Start menu, nothing else.

**Comment by Gt3pccb** [comment]
interesting behaviors, if I use the powershell to start code, Code runs fine, if I right click on the code.exe and create a shortcut  or if I pin it to the task bar I get the errors.

Here is how the shortcut startup settings are 
Target = "C:\Users\---\AppData\Local\Programs\Microsoft VS Code\Code.exe"
Start = "C:\Users\---\AppData\Local\Programs\Microsoft VS Code"
 I can repro every time.

**Comment by andschwa** [comment]
That's...weird. Contact the Code team?

**Comment by andschwa** [comment]
What happens with other extensions? This flag is pretty much just for extension developers: https://code.visualstudio.com/api/working-with-extensions/testing-extension It shouldn't be set unless you explicitly did so.
