### ISSUE TITLE
VSCode (Powershell) starts with two terminals open: Powershell Integrated and "pwsh"

### ISSUE THREAD

**Issue by github-account1111** [PowerShell/vscode-powershell#3925]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

Same exact issue as https://github.com/microsoft/vscode/issues/136609 except that one was seemingly ignored and closed.

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS> code --version
1.66.2
dfd34e8260c270da74b5c2d86d61aee4b6d56977
x64
```

### Extension Version

```console
PS> code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

Open a .ps1 file.

**Comment by andschwa** [comment]
Hi there,

The PowerShell extension opens the "PSIC" (PowerShell Integrated Console) on activation as it's hosting the LSP server.

VS Code opens a regular `pwsh` terminal.

You can configure _both_ of these options, the extension's with:

```json
"powershell.integratedConsole.showOnStartup": false
```

(Note that if you do this, you'll have to manually run "PowerShell: Show Integrated Console" to get it open later, see #3918.)

And VS Code's terminal documentation is [here](https://code.visualstudio.com/docs/editor/integrated-terminal).

**Comment by github-account1111** [comment]
Does hosting the LSP server require opening an extra Powershell session?

Also worth noting that this was not happening before I installed Powershell 7.

**Comment by andschwa** [comment]
> Does hosting the LSP server require opening an extra Powershell session?

It requires the PSIC session, yes. But as shown, you can hide that if you wish.

> Also worth noting that this was not happening before I installed Powershell 7.

I don't think that VS Code will open a `pwsh` terminal on startup unless you install `pwsh` (which is PowerShell 7).

**Comment by github-account1111** [comment]
"Extra" was the keyword in my question.
Can't it switch to pwsh for PSIC, given that Powershell 7 is a superset of Powershell 5.1, instead of spawning an extra session?

**Comment by andschwa** [comment]
No, as I stated, the _extension_ only starts PSIC. It is not an "extra" is is the one and only that the extension spawns and hides control over. You may hide it at startup if you wish.

You can set VS Code to do _whatever you wish_ with your other terminals. You seem to not want it to start a `pwsh` terminal on startup, go configure that. I linked you to the documentation earlier. I can't answer why VS Code doesn't start a `powershell` by default; I'm not a VS Code maintainer.

Thanks for using the extension!

**Comment by github-account1111** [comment]
@andschwa You seem to have misunderstood my question.
I'm asking why _the extension_ doesn't opt to use 7 for PSIC instead of 5.1.
It can obviously see that 7 is present because it opens it along with 5.1.

>You seem to not want it to start a pwsh terminal on startup, go configure that. 

No.
I want it to start pwsh only (i.e. 7).
I don't want it to start 5.1 (whether it be hidden or not).

**Comment by andschwa** [comment]
> @andschwa You seem to have misunderstood my question.
> I'm asking why _the extension_ doesn't opt to use 7 for PSIC instead of 5.1.
> It can obviously see that 7 is present because it opens it along with 5.1.

The extension does use PowerShell 7 if available. You can actually [choose](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#how-do-i-change-the-powershell-version) which installed copy of PowerShell you want to use!

**Comment by github-account1111** [comment]
>The extension does use PowerShell 7 if available
But that's obviously not the case.
Here 7 is available, yet it still uses 5.1.
That is literally the point of this entire issue.
It _should_ do it, but it doesn't do it.

**Comment by andschwa** [comment]
You didn't follow the bug report and provide any logs or screenshots. It _does_ use PowerShell 7, as many users can attest to. Please give us more information if you need further assistance!

**Comment by github-account1111** [comment]
I think this is a case of selective reading.
I never said it doesn't use 7, period.
This is what I said:

>I'm asking why the extension doesn't opt to use 7 _for PSIC_ instead of 5.1.

I didn't think a screenshot is needed given I'm experiencing the exact same issue as the one I linked, and that one does contain a screenshot, but here you go:

![image](https://user-images.githubusercontent.com/5728319/164341949-c41689df-9870-488a-90b1-3a732e726789.png)

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/8526105/logs.zip)

**Comment by andschwa** [comment]
Ok run $PSVersionTable in PSIC. If it's not the version want, follow the instructions I linked you to earlier to change it.

**Comment by github-account1111** [comment]
It's the one I want.
Both pwsh and PowerShell Integrated Console are version 7.
Why does it do that?

**Comment by andschwa** [comment]
I'm sorry, I don't understand your question or what you're having trouble with.

**Comment by github-account1111** [comment]
Why does it open two Powershell 7 terminals instead of opening one?
It makes no sense.
Am I supposed to use one over the other for certain tasks?

**Comment by joe-miller-hgs** [comment]
i am having the same problem as **github-account1111**. 
when i open vscode powershell extension, i get two terminals:
![image](https://user-images.githubusercontent.com/84777053/226537459-2d567859-f547-4344-9494-be22b432f019.png)
and
![image](https://user-images.githubusercontent.com/84777053/226537521-14c00b58-af99-4ed3-8d80-b1d30b950968.png)

i don't want two terminals.
this problem started when i installed pwsh.
the dual terminals only appear when i select pwsh in the session menu.
if i caused the problem somehow when i installed pwsh, i have no idea how and no idea how to fix it.

here's my session menu:
![image](https://user-images.githubusercontent.com/84777053/226538152-7621e553-8be2-4be9-83fc-491b0a29d3ae.png)

i prefer to have only the PSIC terminal when i open vscode with pwsh selected.
i don't need or want a duplicate terminal.
at minimum, it causes a big chunk of my terminal window to be consumed by the two-terminal list on the right, as shown in the first two images.
it also causes problems if i accidently close the wrong terminal when i try to restore my full terminal window.

what other info can i provide to help you diagnose this problem?
thanks for your time.

**Comment by Lingxi-Li** [comment]
Since PSIC is used by LSP server, it should be treated as an implementation detail and not be exposed to user as this causes confusion. E.g., when I saw the two sessions, I mistakenly thought that one is using PowerShell 7 and the other is using PowerShell 5.x shipped with Windows and I killed the latter. That said, the PSIC should be hidden by default.

**Comment by andyleejordan** [comment]
The vast majority of users request that the integrated terminal _is_ exposed, as it's useful for debugging etc. As pointed out above, you can set it to be hidden on startup and behave exactly as you want. No default will satisfy everyone.

**Comment by toni1elias** [comment]
I have the same issue.
If I open a ` .PS1` file using `File > Open File...` menu option, only one terminal is shown.
If I opened the file by right-clicking it and choosing `Open in VS Code`, two terminals will show up.

**Comment by begna112** [comment]
I think the issue is not the PSIC appearing, but the useless secondary pwsh terminal that also opens. Having an extra terminal open in every vscode window that's working in PS projects isn't great for resource management.

![image](https://github.com/PowerShell/vscode-powershell/assets/10567958/28819a71-d4a2-48c1-b86f-0df4b4d6cd5f)
![image](https://github.com/PowerShell/vscode-powershell/assets/10567958/df38653f-353c-40c1-86e9-581274e68243)

**Comment by andyleejordan** [comment]
Agreed, but that's an issue with VS Code that you can't disable that `pwsh` from opening; as an extension author I cannot prevent that.
