### ISSUE TITLE
Weird formatting issues

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3928]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

From time to time I have these weird formatting issues with new previews where even tho there are no errors and everything is great when I do formatting - this:
![image](https://user-images.githubusercontent.com/15063294/164019011-00318771-8b7a-416f-998e-52c7a6d6f00e.png)

changes to: 

![image](https://user-images.githubusercontent.com/15063294/164018987-6a2352fc-2d05-4beb-9786-82e251368ab8.png)

Restarting the session fixes the issue, but I have not been able to track why this even happens. It's like the engine randomly thinks something different is being tracked. 

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.588
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.588
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.66.2
dfd34e8260c270da74b5c2d86d61aee4b6d56977
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.4.1
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

Unfortunately no idea.

**Comment by JustinGrote** [comment]
Possibly related/dupe of https://github.com/PowerShell/vscode-powershell/issues/3926

**Comment by andschwa** [comment]
Does it ever repro when you're using PowerShell 7?

**Comment by PrzemyslawKlys** [comment]
Hard to say, I run PS 7 occasionally, but I'll keep this in mind if it happens again.
