### ISSUE TITLE
PSIC displayed in console while editing during breakpoint stop

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3929]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

I was debugging some code, it stopped on the breakpoint. I totally forgot about it and started editing the code. Then this pops up:

![image](https://user-images.githubusercontent.com/15063294/164082332-7af45e3e-3a7f-4901-814a-e4b32828d715.png)

Some logs as discussed with @SeeminglyScience 

[1650376314-b6647fe8-2334-4a0a-b629-b27df5c49dbe1650355061864.zip](https://github.com/PowerShell/vscode-powershell/files/8516037/1650376314-b6647fe8-2334-4a0a-b629-b27df5c49dbe1650355061864.zip)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.588
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.588
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.66.2
dfd34e8260c270da74b5c2d86d61aee4b6d56977
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.4.1
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

1. Start debug
2. Reach breakpoint
3. Start editing 
4. Hopefully things show up

**Comment by andschwa** [comment]
I believe @SeeminglyScience just fixed this in https://github.com/PowerShell/PowerShellEditorServices/pull/1762

**Comment by PrzemyslawKlys** [comment]
Doesn't seem to happen anymore. Closing
