### ISSUE TITLE
Powershell Integrated Console uses PSReadline 2.1 despite 2.2.x being installed

### ISSUE THREAD

**Issue by smj389** [PowerShell/vscode-powershell#3932]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

Inside the Integrated Console, I see this output

```
get-module | format-list

Name              : PSReadLine
Path              : C:\Users\smjos\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PSReadLine\2.1.0\PSRe 
                    adLine.psm1
Description       : Great command line editing in the PowerShell console host
ModuleType        : Script
Version           : 2.1.0
PreRelease        : 
NestedModules     : {Microsoft.PowerShell.PSReadLine2}
ExportedFunctions : PSConsoleHostReadLine
ExportedCmdlets   : {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler,
                    Set-PSReadLineKeyHandler…}
ExportedVariables : 
ExportedAliases   : 


```
In another Powershell instance,

```

Name              : PSReadLine
Path              : F:\OneDrive\Documents\PowerShell\Modules\P 
                    SReadLine\2.2.3\PSReadLine.psm1
Description       : Great command line editing in the
                    PowerShell console host
ModuleType        : Script
Version           : 2.2.3
PreRelease        : 
NestedModules     : {Microsoft.PowerShell.PSReadLine2}
ExportedFunctions : PSConsoleHostReadLine
ExportedCmdlets   : {Get-PSReadLineKeyHandler,
                    Get-PSReadLineOption,
                    Remove-PSReadLineKeyHandler,
                    Set-PSReadLineKeyHandler…}
ExportedVariables : 
ExportedAliases   : 

```

I would like to the later version of PSReadline in the integrated console.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22598    
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
➜  code --version

1.66.2
dfd34e8260c270da74b5c2d86d61aee4b6d56977
x64
```

### Extension Version

```console
➜  code --list-extensions --show-versions | Select-String powershell


ms-vscode.powershell@2021.12.0
```

### Steps to Reproduce

1. Install PSReadline 2.2.x into powershell.
2. Open the integrated console.
3. Get-module

**Comment by andschwa** [comment]
Please install the PowerShell preview extension. This bug has been resolved, and it will use only the bundled version of PSReadLine. If you wish to wait, we're looking to move the preview to stable in the upcoming week.
