### ISSUE TITLE
Type completion doesn't work when using "Using namespace" statements

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/vscode-powershell#3940]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

```
using namespace System
[System.Object<Ctrl+Space>
```
The above scenario doesn't work.  
If you remove the using statement or point it to something else like `System.Management` it works like you would expect.  
I'm guessing the completion code doesn't handle the namespace text removal properly.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.67.0-insider
ab86e0229d6b4d0cb49cfd6747c92cafcd2bd4af
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2022.4.2
```

### Steps to Reproduce

1: Type in the following:
```
using namespace System
[System.Object
```
2: Try to complete the type

**Comment by SydneyhSmith** [comment]
@MartinGC94 thanks for opening this issue, we will need to look into what we are receiving from VSCode to resolve this issue

**Comment by SydneyhSmith** [comment]
@MartinGC94 we think this issue may be fixed, can you let us know if you are still experiencing it? Thanks!

**Comment by MartinGC94** [comment]
Can confirm, works for me.
