### ISSUE TITLE
F8 during debug session forces continuation

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#3944]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

If you use a breakpoint, run code with F5 and wait for it to hit a breakpoint, and then use F8 to run code within Visual Studio Code - debugging will continue instead of doing nothing. I am not sure when it went bonkers, but I just noticed it now. It used to work fine.

My suspect is related to:
- https://github.com/PowerShell/PowerShellEditorServices/pull/1781

> I'm curious, does this problem go away if we write a line after invoking readline if the task has been canceled?
> See this part of the change (which was what allowed us to "re-use" the existing prompt for F5 and F8 input):

But this is just a guess based on F8 being included in the text :)

Edit: After speaking to @SeeminglyScience it seems to be related to: 
- https://github.com/PowerShell/PowerShellEditorServices/pull/1777

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.652
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.652
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.66.2
dfd34e8260c270da74b5c2d86d61aee4b6d56977
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.12.0
ms-vscode.powershell-preview@2022.4.3
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.5
```

### Steps to Reproduce

1. Open code
2. Set breakpoint
3. Run F5
4. Wait for breakpoint to be hit
5. Once hit, press F8 with selected text or without 

### Visuals

![F8 continue](https://user-images.githubusercontent.com/15063294/166145235-d8143c98-9045-41ab-ab37-0711edb23d79.gif)

**Comment by SeeminglyScience** [comment]
> Edit: After speaking to @SeeminglyScience it seems to be related to:
> 
> * [Consolidate `InterruptCurrentForeground` and `MustRunInForeground` PowerShellEditorServices#1777](https://github.com/PowerShell/PowerShellEditorServices/pull/1777)

Note: turned out to be unrelated and was just a logic error on my part at some point
