### ISSUE TITLE
Add back "PowerShell" text indicator when running a "Editor Command"

### ISSUE THREAD

**Issue by ghost** [PowerShell/vscode-powershell#3954]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

In previous versions of the PowerShell extension, when I ran an Editor Command associated with PS1 file, it would show the text "PowerShell" in the bottom left corner.  When the command finished running, the PowerShell text would go away.  This was a nice indicator letting me when the command had finished, and I knew I could go look for the results.  In my case, my command (by use of Microsoft.VSCode_profile.ps1 with the script block registered as an Editor Command) signs the script, compiles the PS1 into an EXE format (for both .NET 4.8 and .NET 6.x formats), and then signs the executables.  This whole process takes a bit of time...long enough that the "PowerShell" text indicator "going away" really helped let me know when it was done.  With the current version, I have to wait "until I think it should be done" to check it.

![image](https://user-images.githubusercontent.com/61813693/167066675-692a9bd3-fc31-4c68-bcd4-e7bf1f80a991.png)

As of version v2022.5.0, this feature no longer exists.

### Proposed Design

Please add the "PowerShell" text (or some other indicator) to the bottom (or other obvious location) of VSCode when an Editor Command is running and then hide it when the command finishes.  For an example of this, check out any previous version of the extension prior to v2022.5.0.  Hopefully this is an easy add, since it already worked in previous versions.

**Comment by SydneyhSmith** [comment]
Thanks @NJK-HOME we will keep this issue open for investigation

**Comment by shangles** [comment]
Thanks for posting about this before I could.  The removal of any kind of visual cue that PowerShell is running a command has been frustrating for me.

**Comment by shangles** [comment]
There's an animated spinning icon in the lower-right that appears when PowerShell is "starting"  It makes sense to have the same area animate progress when a script is running.

**Comment by shangles** [comment]
Just curious.  I see "2 tasks done" at the top of this issue.  I'm a github newbie and can't see what tasks are completed... and which ones are remaining to be completed.  Does this mean there's progress on this enhancement for a future update?

**Comment by panekj** [comment]
It refers to this
![image](https://user-images.githubusercontent.com/50457605/170838854-63b4aed4-9cbc-4755-899e-b06c2b3c5172.png)

If there will be an ongoing fix or something else, it will most likely show up as update between comments

**Comment by shangles** [comment]
Any update on when we might see this feature implemented?

**Comment by shangles** [comment]
Monthly bump

**Comment by shangles** [comment]
I love this update.  Thank you!
