### ISSUE TITLE
Cannot install the extension

### ISSUE THREAD

**Issue by bytepl** [PowerShell/vscode-powershell#3955]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

I cannot install latest version of the extension. When I click on "Install', the progress indicator starts to move but that's the only thing that really happens. It keeps moving until I close VS Code. I kept the installation process running for 15 minutes and all I could saw in the logs was:

[2022-05-06 09:47:38.886] [sharedprocess] [info] Getting Manifest... ms-vscode.powershell
[2022-05-06 09:47:38.893] [sharedprocess] [info] Installing extension: ms-vscode.powershell
[2022-05-06 09:47:40.054] [sharedprocess] [info] Downloaded extension: ms-vscode.powershell c:\Users\XXXXXX\AppData\Roaming\Code\CachedExtensionVSIXs\ms-vscode.powershell-2022.5.0

I had the previous version installed and it was working fine but when I tried to update it, VS Code failed to do so. I found information in the log that I should remove a subfolder the extension uses in  \.vscode\extensions and then try again.. I removed it but now I am unable to install it from scratch.

I tried to install the extension using command line but it also seems to be stuck with the only output being:

Installing extensions...
(node:28388) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)

I also tried to install version 2021.12.0 (from the command line) but it cannot be installed (the output is exactly the same as above).

I tried to install several other extensions in the meantime and I can install them all.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      5.1.19041.1645
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1645
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.67.0
57fd6d0195bb9b9d1b49f6da5db789060795de47
x64
```

### Extension Version

```console
no output
```

### Steps to Reproduce

Start VS Code, go to Marketplace, search for "PowerShell", click on install.

**Comment by JustinGrote** [comment]
Have you tried a fresh install of vscode? One way to do this is download the zip and create a "data" folder, it will create a completely self-contained install.
https://code.visualstudio.com/docs/editor/portable

**Comment by bytepl** [comment]
> Have you tried a fresh install of vscode? One way to do this is download the zip and create a "data" folder, it will create a completely self-contained install. https://code.visualstudio.com/docs/editor/portable

Just now. It did not help. The only output in the shared log:

[2022-05-09 15:56:33.534] [sharedprocess] [info] Getting Manifest... ms-vscode.powershell
[2022-05-09 15:56:33.539] [sharedprocess] [info] Installing extension: ms-vscode.powershell
[2022-05-09 15:56:51.182] [sharedprocess] [info] Downloaded extension: ms-vscode.powershell c:\Users\XXXXX\Downloads\VSCode-win32-x64-1.67.0\data\user-data\CachedExtensionVSIXs\ms-vscode.powershell-2022.5.1

Just as before, the installation process creates a subfolder in C:\Users\XXXXX\Downloads\VSCode-win32-x64-1.67.0\data\extensions with some GUID-like name and puts all the extension files and folders there but that's about it.

I noticed something interesting: not all folders and files from the VSIX file are there, some are missing. 

![files and folders](https://user-images.githubusercontent.com/4518860/167428322-78477086-f374-4b62-bebc-66545bc82cc0.jpg)

**Comment by bytepl** [comment]
OK, I think it may have something to do with a proxy I am behind. When I download the extension manually (using Edge), I can unzip it with no problem. When VSCode downloads it, the file has the same length but 7zip reports issues when unzipping the archive.

**Comment by andschwa** [comment]
That's really interesting...good work finding the cause @bytepl.
