### ISSUE TITLE
Extension commands loaded in PowerShell profile are not being registered

### ISSUE THREAD

**Issue by gerane** [PowerShell/vscode-powershell#396]
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.9.0 Insiders
- PowerShell extension version: 8.0
- Output from `$PSVersionTable`:

```

Name                           Value                                                               
----                           -----                                                               
PSVersion                      5.1.14393.187                                                       
PSEdition                      Desktop                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                             
BuildVersion                   10.0.14393.187                                                      
CLRVersion                     4.0.30319.42000                                                     
WSManStackVersion              3.0                                                                 
PSRemotingProtocolVersion      2.3                                                                 
SerializationVersion           1.1.0.1                                                             
```

### Issue Description

When trying to load the Editor Command menu, v8.0 throws the following error

`No extension commands have been loaded into the current session.`

The logs show that my Editor Commands were successfully registered. They are in my VSCode profile.

### Attached Logs

Here are the logs [Gist](https://gist.github.com/anonymous/1ca076ef7943a2c6c3506893bbb80aef)

**Comment by daviwil** [comment]
I might have broken something here, will investigate for 0.8.1

**Comment by nightroman** [comment]
Same issue here. I think it happened on upgrading VSCode-PowerShell from 0.7.2 to 0.8.0. Upgrading VSCode itself to 1.8.0 did not cause this problem.

**Comment by gerane** [comment]
@daviwil same on my work desktop. Let me know if I can help with anything else or could help test any changes.

**Comment by daviwil** [comment]
I just checked it, looks like I broke profile loading in general.  Looking into it now

**Comment by daviwil** [comment]
Profile loading is fine, was just testing with the wrong profile path :/  This looks like it's caused by an event sequence I hadn't accounted for when I totally redesigned the extension code.  Fixed it, PR incoming!  I'll be shipping an update in the next couple of days so this fix will go out with it.

**Comment by gerane** [comment]
@daviwil yeah, was going to say that this also doesn't work when using f8 or running the register command either. Profile is running and commands output as being registered, but not showing up as having any registered.

Anyway I can get the fix for my local build for the time being? I may have to revert to previous version if not. Totally kills my workflow without them lol.

**Comment by daviwil** [comment]
@gerane It should be working when you use F8 on an editor command registration after the profile has been loaded.  Are you saying it isn't working in that case?

Here's a preview drop, I didn't bump the version number so you might need to uninstall the existing 0.8.0:

[PowerShell-0.8.0.zip](https://github.com/PowerShell/vscode-powershell/files/661385/PowerShell-0.8.0.zip)

Rename **.zip** to **.vsix** and use the VSIX installation command in VS Code.

**Comment by gerane** [comment]
@daviwil ok, that is working now actually. It wasn't working on my laptop though.

**Comment by gerane** [comment]
@daviwil is there a cli for installing a vsix, or only the one in the GUI?

**Comment by daviwil** [comment]
I've only seen the one in the GUI, not sure if they give a CLI path.

**Comment by gerane** [comment]
@daviwil I may see if just highlighting and running one works out. When I registered one, they all were visible. I couldn't get that to work on my laptop, but this is likely ok for me until you get that fix out.

I can test that one if you need me to though.

**Comment by daviwil** [comment]
I'm pretty sure highlighting and running will work.  The only problem I saw in the code was when the commands are registered in your profile, the registration events happen too early for the extension command code in the extension to catch them.

**Comment by gerane** [comment]
@daviwil hmm, let me retest. Just noticed the window I was in still had 7.2 loaded and hadn't been reloaded since the update

**Comment by gerane** [comment]
@daviwil yeah, running f8 still doesn't register the commands.

**Comment by gerane** [comment]
@daviwil let me grab that zip and try that out.

**Comment by daviwil** [comment]
If it doesn't work, grab logs and send them to me?

**Comment by gerane** [comment]
@daviwil Yup, that worked. However, highlight + f8 didn't work prior to the fix. I tested f8 as well just to make sure, and it works with the changes.

**Comment by gerane** [comment]
@daviwil Now to test out multi select =)
