### ISSUE TITLE
Missing '$' in `try-catch` snippet

### ISSUE THREAD

**Issue by jmilliron808** [PowerShell/vscode-powershell#3964]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

The try-catch snippet is missing it's '$' for the first tab stop.

Line 609 in /snippets/PowerShell.json should be:
"\t${1:<#Do this if a terminating exception happens#>}",
Instead of:
"\t{1:<#Do this if a terminating exception happens#>}",

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS> code --version
1.67.0
57fd6d0195bb9b9d1b49f6da5db789060795de47
x64
```

### Extension Version

```console
PS> code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2022.5.1
```

### Steps to Reproduce

Type 'try-catch' > hit tab > the cursor moves to $0 cursor position

It should move to $1 tab stop but it's missing the '$'

**Comment by andschwa** [comment]
@JustinGrote I can't remember, was this fixed?

**Comment by JustinGrote** [comment]
Probably not, I'll keep it on my free time to do list.
