### ISSUE TITLE
When trying to call an application from PowerShell Code, Code adds ��� to the string sent to CMD

### ISSUE THREAD

**Issue by jasonmohyla** [PowerShell/vscode-powershell#3969]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

I am trying to call a test application from PowerShell and then parse the input. The way I am calling the test application is with following snippet. This works as is in PowerShell ISE. The error is that the text that is sent to cmd has three added characters added to the front of the string (���).
`$testApp = "notepad.exe"
$params = ""
$response = "$testApp $params" | CMD 
$response`

Terminal
$params = ""
$response = "$testApp $params" | CMD
$response }
'���notepad.exe' is not recognized as an internal or external command,
operable program or batch file.
Microsoft Windows [Version 10.0.19042.1645]
(c) Microsoft Corporation. All rights reserved.

D:\_Projects>���notepad.exe

### PowerShell Version

```console
PS D:\_Projects\HD\SandK\Configuration> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1645
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1645
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
PS D:\_Projects\HD\SandK\Configuration> code --version
1.67.1
da15b6fd3ef856477bf6f4fb29ba1b7af717770d
x64
```

### Extension Version

```console
PS D:\_Projects\HD\SandK\Configuration> code --list-extensions --show-versions | select-string PowerShell

ms-vscode.powershell@2022.5.1
```

### Steps to Reproduce

Run this code fragment. When ran from PowerShell ISE, notepad will open. 
From VS Code, the error is given:
'���notepad.exe' is not recognized as an internal or external command,
operable program or batch file.

### Visuals

![image](https://user-images.githubusercontent.com/44871602/167906568-4e4bfd0e-076e-4a7f-8aad-bb847b4a497d.png)

**Comment by JustinGrote** [comment]
This works fine in PS7, 5.1 has a lot of known unicode issues.

I know this is a contrived example you presented but you really shouldn't be using stdin for this, using the call operator `&` or `start-process` is the better approach.

**Comment by jasonmohyla** [comment]
Thanks for the review, after the submittal, found it working in 7.

Best regards

Sr. Technical Lead - Software Jason Mohyla

Business Digital Organization - Aftersales Support and Solutions (AA/BDO31)
Robert Bosch LLC | 15000 Haggerty Road | Plymouth, MI 48170 | USA | www.bosch.us
Tel. +1 734 462-5257 | Fax +1 734 462-5201 | ***@***.******@***.***>
​

**Comment by JustinGrote** [comment]
@jasonmohyla no worries, and congratulations on opening your first issue on GitHub!

**Comment by andschwa** [comment]
Hey @jasonmohyla does this still repro with PowerShell 5.1? I remember we fixed _some_ encoding issue with running external commands, wondering if that fixed this too.

**Comment by jasonmohyla** [comment]
I updated the PS version and got it to work.

Best regards

Sr. Technical Lead - Software Jason Mohyla

Business Digital Organization - Aftersales Support and Solutions (AA/BDO31)
Robert Bosch LLC | 15000 Haggerty Road | Plymouth, MI 48170 | USA | www.bosch.us
Tel. +1 734 462-5257 | Fax +1 734 462-5201 | ***@***.******@***.***>
​
