### ISSUE TITLE
Non-standard install of PowerShell does not load at session opening 

### ISSUE THREAD

**Issue by sangafabrice** [PowerShell/vscode-powershell#3977]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

Hi,
When starting a new session of vscode-powershell, the default powershell execution path is used `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe` although a non-standard install location was set.
Here is how the extension is set in `settings.json`:
```json
{
  "powershell.powerShellAdditionalExePaths": [
      {
          "exePath": "X:\\Pwsh\\7\\pwsh.exe",
          "versionName": "PowerShell Core 7"
      }
  ],
  "powershell.powerShellDefaultVersion": "PowerShell Core 7",
}
```
Assuming that the non-standard location points to the `PowerShell Core 7.2.3` executable, this is what is returned from the `PowerShell Integrated Console` instead:
```powershell
PS > $PSVersionTable.PSVersion.Major
5
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.67.1
da15b6fd3ef856477bf6f4fb29ba1b7af717770d
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.5.1
```

### Steps to Reproduce

- Opens Visual Studio Code: `code . --extensions-dir "X:\extensions"`
- Start Powershell Integrated Console

### Visuals

![Resume Preview](https://scontent.fcai19-4.fna.fbcdn.net/v/t39.30808-6/279916545_167649358997252_7859710129578400631_n.jpg?_nc_cat=104&ccb=1-6&_nc_sid=730e14&_nc_ohc=S1gesBBIw4YAX-72d9f&_nc_ht=scontent.fcai19-4.fna&oh=00_AT-mZ7g-RLUYpYwiQct7RWPZ_qj7Gw6Xi6Hookf2DrgARg&oe=62823722)

**Comment by sangafabrice** [comment]
It works perfectly. Thank you.

**Comment by andschwa** [comment]
Related to change made in https://github.com/PowerShell/vscode-powershell/pull/3919
