### ISSUE TITLE
Get session menu doesn't show what we defined in powershell.powerShellAdditionalExePaths

### ISSUE THREAD

**Issue by frankchen76** [PowerShell/vscode-powershell#3978]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

for recent update, I no longer see what I defined in powershell.powerShellAdditionalExePaths showed up from session menu. the below is what settings I have
```JSON
    "powershell.powerShellDefaultVersion": "PowerShell 5.1",
    "powershell.powerShellAdditionalExePaths":[
        {
            "exePath": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "versionName": "PowerShell 5.1"
        },
        {
            "exePath": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
            "versionName": "PowerShell 7"
        }
    ]

```
I don't see those options are displayed at session menu below: 
![image](https://user-images.githubusercontent.com/9618662/168224780-4116d86b-b28a-4e94-8138-ef765582ec68.png)

when I checked my settings, I also see the below yellow line to indicate the error which I've never seen before
![image](https://user-images.githubusercontent.com/9618662/168225213-fccb2817-0b78-47d3-a801-339fb3e5f622.png)

any ideas how to correct that?

### PowerShell Version

```console
PS C:\AzureDevOps\PFEProjects-Private\PS-Samples> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
C:\AzureDevOps\PFEProjects-Private\PS-Samples>code --version
1.67.1
da15b6fd3ef856477bf6f4fb29ba1b7af717770d
x64
```

### Extension Version

```console
C:\AzureDevOps\PFEProjects-Private\PS-Samples>code --list-extensions --show-versions powershell                 
alefragnani.Bookmarks@13.3.0
ms-azuretools.vscode-azurefunctions@1.6.2
ms-azuretools.vscode-azureresourcegroups@0.4.0
ms-azuretools.vscode-azurestorage@0.13.0
ms-dotnettools.csharp@1.24.4
ms-vscode.azure-account@0.10.1
ms-vscode.powershell@2022.5.1
ms-vscode.vs-keybindings@0.2.1
msjsdiag.debugger-for-chrome@4.13.0
msjsdiag.debugger-for-edge@1.0.15
msoffice.microsoft-office-add-in-debugger@0.3.0
pnp.polacode@0.3.4
quicktype.quicktype@12.0.46
TeamsDevApp.ms-teams-vscode-extension@3.8.0
yzhang.markdown-all-in-one@3.4.3
```

### Steps to Reproduce

include the below JSON into settings
```JSON
    "powershell.powerShellAdditionalExePaths":[
        {
            "exePath": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "versionName": "PowerShell 5.1"
        },
        {
            "exePath": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
            "versionName": "PowerShell 7"
        }
    ]
```
click "Command palette" -> "PowerShell:Show Session menu", I should be able to see above options.

**Comment by sangafabrice** [comment]
@frankchen76, here's a solution: [Issue #3977](https://github.com/PowerShell/vscode-powershell/issues/3977#issuecomment-1126141804). Change the `settings.json` this way:
```json
"powershell.powerShellAdditionalExePaths": {
    "PowerShell 5.1": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "PowerShell 7": "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
}
```

**Comment by andschwa** [comment]
Sorry about that, I think this was an unexpected change in behavior due to https://github.com/PowerShell/vscode-powershell/pull/3919 (but now you can do this in the GUI!)

**Comment by JustinGrote** [comment]
@andschwa maybe this should actually be a new setting name so we can flag the old setting name/style as deprecated?
![image](https://user-images.githubusercontent.com/15258962/168343813-862e12c3-b332-4e94-a4f8-f3c49dd33c29.png)

**Comment by andschwa** [comment]
It's a little late now 🤷

**Comment by frankchen76** [comment]
> @frankchen76, here's a solution: [Issue #3977](https://github.com/PowerShell/vscode-powershell/issues/3977#issuecomment-1126141804). Change the `settings.json` this way:
> 
> ```json
> "powershell.powerShellAdditionalExePaths": {
>     "PowerShell 5.1": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
>     "PowerShell 7": "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
> }
> ```

@sangafabrice, thanks for your help. I confirmed that your suggestion works fine on my side. 
![image](https://user-images.githubusercontent.com/9618662/168402214-178af694-be93-4c78-b30b-4a061b99f06e.png)

**Comment by cardin** [comment]
v2022.5.1 of the Extension has not updated the documentation.

😅 took me a long while of digging before I found this GitHub Issue that mentions what the new syntax for the field was.
![image](https://user-images.githubusercontent.com/553816/170643561-99aeda4d-d7ef-4157-8a1d-dd6daab82296.png)
