### ISSUE TITLE
List events (eg Winforms events) in the Explorer/Outline sidebar (outline.showEvents)

### ISSUE THREAD

**Issue by thegraffix** [PowerShell/vscode-powershell#3983]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I would like the Outline sidebar to list events (Winforms, for example) using the vscode setting "outline.showEvents"
PowerShell Winforms event code example: `$btnSave.Add_Click({  <code here>  })`

**Comment by SydneyhSmith** [comment]
Thanks @thegraffix for this request, its a really interesting idea, however it isnt possible with the current architecture of vscode/this extension so I am going to close this issue...thanks!
