### ISSUE TITLE
VSCode psm1 no longer formats files

### ISSUE THREAD

**Issue by ebmarquez** [PowerShell/vscode-powershell#3985]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

Powershell formatting no longer works on psm1 files.
[1652748482-6f8b89da-20d3-431c-b6ac-4806d008e37d1652748059737.zip](https://github.com/PowerShell/vscode-powershell/files/8704279/1652748482-6f8b89da-20d3-431c-b6ac-4806d008e37d1652748059737.zip)

### PowerShell Version

```console
$psversiontable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
> code --version
1.67.1
da15b6fd3ef856477bf6f4fb29ba1b7af717770d
x64
```

### Extension Version

```console
ms-vscode.[7mpowershell[0m@2022.5.1
ms-vscode.[7mpowershell[0m-preview@2022.5.1
```

### Steps to Reproduce

```powershell
function Restore-Packages() {


    BEGIN {
        Write-Verbose -Message "=======================================================" -Verbose
        Write-Verbose -Message "Enter $($MyInvocation.MyCommand.Name)" -Verbose
        $message = "At: {0}:{1}`n         Line: {2}" -f $MyInvocation.ScriptName, $MyInvocation.ScriptLineNumber, $MyInvocation.Line
        Write-Verbose -Message "Invoked $message"
        Write-Verbose -Message "-------------------------------------------------------" -Verbose

    }
PROCESS {
write-host "test"
}
END{
Write-Verbose -Message "Enter $($MyInvocation.MyCommand.Name)" -Verbose
}
```

### Logs

[1652748482-6f8b89da-20d3-431c-b6ac-4806d008e37d1652748059737.zip](https://github.com/PowerShell/vscode-powershell/files/8704291/1652748482-6f8b89da-20d3-431c-b6ac-4806d008e37d1652748059737.zip)

**Comment by andschwa** [comment]
Hi, based on your logs you need to update PowerShell Core:

```
Failed to handle request textDocument/codeAction 55
System.Management.Automation.CmdletInvocationException: Minimum supported version of PSScriptAnalyzer for PowerShell Core is 7.0.3 but current version is '7.0.0'. Please update PowerShell Core.
```

Can you please update PowerShell and try again? Thank you!
