### ISSUE TITLE
Select PSScriptAnalyzer Rules terminating PowerShell session

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/vscode-powershell#400]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version:
- VS Code version: 1.8.0
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`:
PSVersion                      5.0.10240.17146
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

### Issue Description
When launching `Select PSScriptAnalyzer Rules` via the command pallet right 
after opening VS Code it causes the current PowerShell session to crash. If I wait a few minutes after this and try again it works without issue.

### Attached Logs
[1482161990-77f69162-77ea-4364-b2e9-db8739fcd2f41482161989523.zip](https://github.com/PowerShell/vscode-powershell/files/661475/1482161990-77f69162-77ea-4364-b2e9-db8739fcd2f41482161989523.zip)

![powershell-crash](https://cloud.githubusercontent.com/assets/24547864/21318779/40173a18-c5d0-11e6-838b-3087b8250abe.png)

**Comment by daviwil** [comment]
Thanks for the report!  I see the problem, looks like we're asking for the available PSScriptAnalyzer rules while Script Analyzer is already running so it throws an exception.  Need to find a good way to deal with this.

**Comment by daviwil** [comment]
Fixed by PowerShell/PowerShellEditorServices#329
