### ISSUE TITLE
do-while extra parenthesis on snippet

### ISSUE THREAD

**Issue by gaston-senac** [PowerShell/vscode-powershell#4002]
Issue Type: <b>Bug</b>

If you type do-while and accept the auto-complete snippet it will add an extra trailing  parenthesis.

do {
    
} while (
    <# Condition that stops the loop if it returns false #>)
)
 
Extension version: 2022.5.1
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (6.11GB free)|
|Process Argv|--crash-reporter-id 05b54849-6b60-4ab2-a4e4-8ff75972923f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by JustinGrote** [comment]
Thanks! Might be an intellisense miss.

**Comment by th3d00rw4y** [comment]
I the same issue, but not just for do-while.
Using snippet for an If statement gives me:

`if (condition) {
    <# Action to perform if the condition is true #>
}`

foreach:

`foreach ($currentItemName in $collection) {
    <# $currentItemName is the current item #>
}`

**Comment by gaston-senac** [comment]
> I the same issue, but not just for do-while. Using snippet for an If statement gives me:
> 
> `if (condition) { <# Action to perform if the condition is true #> }`
> 
> foreach:
> 
> `foreach ($currentItemName in $collection) { <# $currentItemName is the current item #> }`

Maybe I'm missing something, but I don't see any problem with those examples, just the do-while.
And while we are at it, don't you think the "foreach-item" is redundant? as it's already covered by the normal "foreach" snippet

**Comment by JustinGrote** [comment]
> And while we are at it, don't you think the "foreach-item" is redundant? as it's already covered by the normal "foreach" snippet

Probably, it was maintained for backwards compatibility for anyone expecting it but we can probably clean that up.
