### ISSUE TITLE
Syntax checker not detecting change of files. 

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/vscode-powershell#4003]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

I can not see this as an issue and I think it is the extension but it may be VS code itself (if so I'll close this and and open there).

I'm working with some scripts which generate other PowerShell scripts, so the process goes

- Edit generator or Edit instructions in VSCode
- Run the generator script from the PowerShell integrated console 
- Edit the resulting code

What I'm finding is the error highlighting is marking thing in the text as errors which were in a previous version. What seems to cause this is the change made to the file outside VS code, as if there is a copy cached, which is still used when the updated file is opened.

### PowerShell Version

```console
Name                           Value[0m
----                           -----[0m
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.5.1
```

### Steps to Reproduce

1. Add  extra lines containing a syntax error to an otherwise valid file. Problems should be displayed correctly
2. Close it, and edit it **outside** VS Code to remove the error
3. Reopen in VSCode and note the problems show before are still show.  (see Visuals below)

### Visuals

![image](https://user-images.githubusercontent.com/16209593/170673280-22304da2-5a8b-4958-81f5-ffd90877740b.png)

**Comment by jhoneill** [comment]
Postscript - this also seems to impact folding. If the file has changed in the middle folding tries to fold were the old file should have folded.

**Comment by SydneyhSmith** [comment]
@jhoneill thanks for the issue report...if you edit the open file at all in VSCode, does this problem go away?

**Comment by jhoneill** [comment]
No - not quite. 
I opened the file in notepad and vscode.
I made a couple of breaking edits an extra } at the end and unused variable , saved & closed, in Code, and then saved from notepad to back out out the changes. 
If I add and delete spaces at the end, it stops complaining about the extra } but nothing seems to get rid of the complaint about the unused variable, and folding is off by one line as if the extra variable line is still there.

<img  alt="image" src="https://user-images.githubusercontent.com/16209593/171731416-b74d05ed-744a-4733-8a1c-ee3117e60c17.png">

**Comment by jhoneill** [comment]
And if I close and re-open the file it adds an extra instance of the erroneous message each time 
<img  alt="image" src="https://user-images.githubusercontent.com/16209593/171733183-8e306778-f82f-4527-8eaf-5f17647d2fe3.png">

**Comment by andschwa** [comment]
@jhoneill the latter is sadly known: https://github.com/PowerShell/vscode-powershell/issues/3252

**Comment by jhoneill** [comment]
@SydneyhSmith  the bot shouldn't have closed this - do you need any more repro info ?

**Comment by SydneyhSmith** [comment]
Thanks, reopening

**Comment by SydneyhSmith** [comment]
Thanks @jhoneill we discussed today and we believe fixing #3252 will resolve both issues, so we will link the issues and mark this as a duplicate for now...thanks!

**Comment by jhoneill** [comment]
@SydneyhSmith  If both get fixed together that will be great.
