### ISSUE TITLE
Debugger retains selected, script-generated artifacts of prior debugger use in same VSCode session

### ISSUE THREAD

**Issue by arencambre** [PowerShell/vscode-powershell#4009]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

I have a folder opened in VSCode. I am debugging a ps1 in the root folder that uses `Import-Module` to import a module in a subfolder. This module references another ps1 file.

If I make a change to the module-referenced ps1 file, save it, go back to the main ps1 file, and use F5 to restart debugging, the debugger uses a cached version of the module's ps1, not the current version that is saved to disk.

Expected behavior: Whenever I initiate a debugging session, the latest, saved version of all files are used, not some mysteriously cached version.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.5.1
```

### Steps to Reproduce

Create an **x.ps1** file that uses `Import-Module` to import module M, which is in a subdirectory under **x.ps1**.

M's psm1 file imports ps1 files using this pattern: https://stackoverflow.com/questions/44509704/creating-powershell-modules-from-multiple-files-referencing-with-module/44512990#44512990. **y.ps1** is one of these files.

With **x.ps1** as the current file in the editor, press F5 to start a debugging session. Note the behavior of **y.ps1**, whose contents are run since **x.ps1** uses **y.ps1** via M.

When done with the debug, change **y.ps1** so that its behavior is different. Save **y.ps1**.

Go back to **x.ps1** in VSCode, hit F5 once again, and observe **y.ps1**'s behavior. You'll notice that **y.ps1**'s behavior reflects its state when you first debugged **x.ps1**, and it does not represent the new state that you just saved.

If you close and reopen VSCode and restart debugging of **x.ps1**, only then does **y.ps1**'s most recently saved state get reflected in execution.

**Comment by JustinGrote** [comment]
This is not a vscode specific problem, you need to use `Import-Module -Force` to get the changes if you are continually saving and updating.

**Comment by arencambre** [comment]
Oh, I think I see what's going on. The top of the `Import-Module` [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.2) has this:

> Adds modules to the current session.

I am used to debuggers where every instance of the debugger starts a generally new session of the code's environment. I guess that is not the case here. That seems counterintuitive as it allows artifacts from prior runs of the debugger to pollute the current run. But I can also appreciate there are bigger issues at play that can make session restarts difficult.

**Comment by MartinGC94** [comment]
You can set the option: `"powershell.debugging.createTemporaryIntegratedConsole": true` to have the debugger start a new session every time you run it.

**Comment by arencambre** [comment]
@MartinGC94 thank you for the idea.

Since it permits retention of artifacts from prior debugging sessions, PowerShell debugging in VSCode does not work like other IDEs. Is there a reason for this? Should the default behavior be modified to act like other debuggers?

**Comment by JustinGrote** [comment]
@arencambre It's designed to do what PowerShell does. You'll get the same result on the Powershell command line. Other Powershell IDEs (Sapien Powershell Studio, ISE, etc.) have the same behavior to my knowledge.

**Comment by arencambre** [comment]
When I am debugging while developing, I'm having a hard time understanding why the it's desirable that I have leftover artifacts of prior debugging attempts. How does that mimic a common production-like scenario? I can only think of boundary cases.

**Comment by JustinGrote** [comment]
@arencambre that's how it works in a normal pwsh console. If you do `import-module mymodule`, and then do the same in a pwsh console again in the same PSIC session, it will not load the changes unless you specify `-force`. Changing this would change how PowerShell works and lead to undesired situations where it works in your testing in VSCode but not when you actually deploy the script to the customer (and in an environment like Azure Functions where artifacts *do* persist between runspace runs that can be a big problem)

As mentioned, you can add `"createTemporaryIntegratedConsole": true` to your launch.json for when you start a debug, and it will start in a new PSIC each time, which will satisfy your use case, but we aren't going to make that the default behavior for the reasons above.

**Comment by arencambre** [comment]
I'll bet you a fresh $2 bill that typical, production uses of PowerShell scripts are once per shell session. Examples include:

* a scheduled script
* a manually invoked use of a script to help with a task

I'll further bet that it is unusual for PowerShell scripts to run repeatedly _in the same console session_. On the face, that smells like a poor design choice, something that could have been automated with looping. Beyond that, we're deep in edge-case territory.

A sensible default would have the PowerShell Extension responsive to what is typical, which means it should be configured with `"powershell.debugging.createTemporaryIntegratedConsole": true`.

Instead, the default is oriented towards either edge cases or poor script design. Those facing edge cases are who need to change defaults, not everyone else. Those using poor design need to improve their design.

**Comment by andschwa** [comment]
> A sensible default would have the PowerShell Extension responsive to what is typical, which means it should be configured so that artifacts of prior runs of the debugger don't infiltrate the current run (it could mean `"powershell.debugging.createTemporaryIntegratedConsole": true`, but not sure that is the intent of that option?).

I'll just add that "typical" is highly arbitrary. As Justin pointed out, the PowerShell _Extension for VS Code_ is trying to behave as close to a regular PowerShell session as possible. With that in mind, for it to act "typically" is for it to act just like regular PowerShell, where one session is _one_ session, and you can create new sessions with an option already provided. With that understood, if you think PowerShell should default to using `-Force` when importing modules, you should take that discussion to the PowerShell repo itself (not the extension here), though I find it exceedingly unlikely such a breaking change would be taken. As it is, this is working as expected by the vast majority of users, and as by design.
