### ISSUE TITLE
Suggestions for parameters interfering with typing

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#4014]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

In some recent updates, you now get help from the engine with auto-complete. This is great as you no longer have to type CTRL+Space. While this is great for functions, parameters with validate sets and so on, it's pretty much destructive for typing standard strings. 

It would be great if auto-fill for parameters where it's a string without autocomplete it would not suggest anything.

![Showproblem](https://user-images.githubusercontent.com/15063294/172806077-3fd3dad7-a3c1-4401-903b-032d550cb09c.gif)

Of course workaround to it is - as soon as it shows up, press escape and continue typing. I can live with this if this is something not fixable. 

### PowerShell Version

```console
PSVersion                      7.3.0-preview.4
PSEdition                      Core
GitCommitId                    7.3.0-preview.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.5.1
ms-vscode.powershell-preview@2022.5.5
tobysmith568.run-in-powershell@1.1.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.6
```

### Steps to Reproduce

Already did above.

**Comment by SeeminglyScience** [comment]
The accepting of the completion result is my bad, I forgot adding quote as a commit trigger would include at the *start* of a string literal. This is fixed with PowerShell/PowerShellEditorServices#1819

The greater issue of file completions in general not being useful most of the time is something that will take a hot minute to resolve, but I am working on it. First I must solve PowerShell/PowerShellEditorServices#1810, then I can exclude them when you aren't already typing a path.
