### ISSUE TITLE
vs code with pwsh external console: array gets closed immediately after the open bracket

### ISSUE THREAD

**Issue by kathodion** [PowerShell/vscode-powershell#4015]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

VS Code Version:1.67.2
OS Version: Win11 21H2
Steps to Reproduce:
vs code with pwsh external console: array gets closed immediately after the open bracket.

create an array in the editor
run it with pwsh, external console
Input
$groupName = @(
'c-s-aad-pim-role-globaladmin',
'c-s-aad-pim-role-securityadmin',
'c-s-aad-pim-role-teamsladmin',
'c-s-aad-pim-role-sharepointadmin',
'c-s-aad-pim-role-complianceadmin',
'c-s-aad-pim-role-priviledgeroleadmin',
'c-s-aad-pim-role-useradmin',
'c-s-aad-pim-role-guestinviter',
'c-s-aad-pim-role-billingadmin',
'c-s-aad-pim-role-cloudapplicationadmin',
'c-s-aad-pim-role-clouddeviceadmin',
'c-s-aad-pim-role-conditionalaccessadmin',
'c-s-aad-pim-role-exchangeadmin',
'c-s-aad-pim-role-xreader',
'c-s-aad-pim-role-globaladmin',
'c-s-aad-pim-role-intuneladmin',
'c-s-aad-pim-role-globaladmin',
'c-s-aad-pim-role-globaladmin'
)

Output
$groupName = @()
'c-s-aad-pim-role-globaladmin',

'c-s-aad-pim-role-securityadmin',
'c-s-aad-pim-role-teamsladmin',
'c-s-aad-pim-role-sharepointadmin',
'c-s-aad-pim-role-complianceadmin',
'c-s-aad-pim-role-priviledgeroleadmin',
'c-s-aad-pim-role-useradmin',
'c-s-aad-pim-role-guestinviter',
'c-s-aad-pim-role-billingadmin',
'c-s-aad-pim-role-cloudapplicationadmin',
'c-s-aad-pim-role-clouddeviceadmin',
'c-s-aad-pim-role-conditionalaccessadmin',
'c-s-aad-pim-role-exchangeadmin',
'c-s-aad-pim-role-xreader',
'c-s-aad-pim-role-globaladmin',
'c-s-aad-pim-role-intuneladmin',
'c-s-aad-pim-role-globaladmin',
'c-s-aad-pim-role-globaladmin'
ParserError:
Line |
1 | )
| ~
| Unexpected token ')' in expression or statement.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.5.1
```

### Steps to Reproduce

create an array in the editor
run it with pwsh, external console
Input
$groupName = @(
'c-s-aad-pim-role-globaladmin',
'c-s-aad-pim-role-securityadmin',
'c-s-aad-pim-role-teamsladmin',
'c-s-aad-pim-role-sharepointadmin',
'c-s-aad-pim-role-complianceadmin',
'c-s-aad-pim-role-priviledgeroleadmin',
'c-s-aad-pim-role-useradmin',
'c-s-aad-pim-role-guestinviter',
'c-s-aad-pim-role-billingadmin',
'c-s-aad-pim-role-cloudapplicationadmin',
'c-s-aad-pim-role-clouddeviceadmin',
'c-s-aad-pim-role-conditionalaccessadmin',
'c-s-aad-pim-role-exchangeadmin',
'c-s-aad-pim-role-xreader',
'c-s-aad-pim-role-globaladmin',
'c-s-aad-pim-role-intuneladmin',
'c-s-aad-pim-role-globaladmin',
'c-s-aad-pim-role-globaladmin'
)

### Visuals

![image](https://user-images.githubusercontent.com/10939437/172889998-36ad90da-9377-4eea-b6f3-5f26b6e3c14e.png)

### Logs

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/8871918/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/8871920/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/8871921/vscode-powershell.log)

**Comment by SeeminglyScience** [comment]
Can you try the preview version of the extension?

Alternatively try creating a blank file at `$profile.CurrentUserAllHosts`

---

From the log it looks like the PowerShell Integrated Console is not actually starting, and you're pressing F8 without the aid of the extension. In that case it just sends the script as input, causing PSRL to trip there.

**Comment by kathodion** [comment]
Same behaviour with the preview extention version of powershell

**Comment by andschwa** [comment]
Are you selecting the integrated console before running the script? It looks like you're running it in a regular VS Code terminal.

**Comment by SeeminglyScience** [comment]
> Same behaviour with the preview extension version of PowerShell.
> 
> blank file as in no file type, I guess. blank file did not help either

So if you type `$profile.CurrentUserAllHosts` into a PowerShell prompt it'll return a path like this:

![image](https://user-images.githubusercontent.com/24977523/173915893-a4dac48e-d053-4268-aa75-8eddbd9c8bb0.png)

Can you create a file at that path (including the `.ps1` extension) and give that a go?

**Comment by kathodion** [comment]
@SeeminglyScience created the file but still facing the same behaviour.
After i clear this file here 
[Microsoft.PowerShell_profile.txt](https://github.com/PowerShell/vscode-powershell/files/8916262/Microsoft.PowerShell_profile.txt)
at C:\Program Files\PowerShell\7.

Any idea what could create this behaviour?

**Comment by kathodion** [comment]
it looks like this has caused the problem

`Set-PSReadLineKeyHandler -Key '(','{','[' `
                         -BriefDescription InsertPairedBraces `
                         -LongDescription "Insert matching braces" `
                         -ScriptBlock {
    param($key, $arg)

    $closeChar = switch ($key.KeyChar)
    {
        <#case#> '(' { [char]')'; break }
        <#case#> '{' { [char]'}'; break }
        <#case#> '[' { [char]']'; break }
    }

    $selectionStart = $null
    $selectionLength = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetSelectionState([ref]$selectionStart, [ref]$selectionLength)

    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    
    if ($selectionStart -ne -1)
    {
      # Text is selected, wrap it in brackets
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace($selectionStart, $selectionLength, $key.KeyChar + $line.SubString($selectionStart, $selectionLength) + $closeChar)
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($selectionStart + $selectionLength + 2)
    } else {
      # No text is selected, insert a pair
      [Microsoft.PowerShell.PSConsoleReadLine]::Insert("$($key.KeyChar)$closeChar")
      [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($cursor + 1)
    }
}

Set-PSReadLineKeyHandler -Key ')',']','}' `
                         -BriefDescription SmartCloseBraces `
                         -LongDescription "Insert closing brace or skip" `
                         -ScriptBlock {
    param($key, $arg)

    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)

    if ($line[$cursor] -eq $key.KeyChar)
    {
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($cursor + 1)
    }
    else
    {
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert("$($key.KeyChar)")
    }
}`

**Comment by SeeminglyScience** [comment]
@kathodion that's more a symptom of the problem. The issue is that the extension is not loading period so it's sending the selection as raw input. This causes some things like PSRL key handlers to trigger where they would not normally.

Can you try the latest preview? (one was released yesterday) and provide new logs if it still doesn't work?

**Comment by kathodion** [comment]
@SeeminglyScience sorry, no luck with the latest preview. still the same behaviour
Extension version v2022.6.1 **Last updated 15/06/2022, 21:17:14**

**Comment by SeeminglyScience** [comment]
Thanks for trying that @kathodion any chance we could get new logs now that 2022.6.1 is installed?
