### ISSUE TITLE
Support Azure-Pipeline-YAML's inline PowerShell scripts

### ISSUE THREAD

**Issue by rklec** [PowerShell/vscode-powershell#4017]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I use [Microsoft's official Azure Pipelines for VS Code extension](https://github.com/microsoft/azure-pipelines-vscode) to lint, check and write Azure Pipelines YAML files, which are CI configuration files.
Now there are often some inline PowerShell scripts and they are just shown as a big block of text and no help like syntax highlighting or even linting, code snippets, IntelliSense or so is provided.

An example:
```yaml
  - task: PowerShell@2
    displayName: 'Do something...'
    inputs:
      targetType: 'inline'
      script: |
        # ...
````

### Proposed Design

It would be great if you could integrate with Azure Pipelines for VS Code extension, so that they can use your features inline in some other syntax etc.
IMHO it is fine to require to install both extensions, if one wants to use that feature.

To do so, I have also created a corresponding issue on their repo: https://github.com/microsoft/azure-pipelines-vscode/issues/477

### Workaround / Alternative solutions

I know I could switch to external PowerShell scripts as it's own `.ps1` files, but these also complicate the Azure Pipelines a lot, given that I know also need to clone the correct repository (if you have multiple repositories) and (always) provide the correct path.
In complex scenarios it thus would be great to just keep using inline PowerShell scripts, but have the full power of the PS extension linting and syntax highlighting.

**Comment by JustinGrote** [comment]
Syntax highlighting is potentially doable via grammar injection but Intellisense/etc. is not due to a fundamental limitation in vscode.
https://github.com/microsoft/vscode/issues/1751#issuecomment-919998146

**Comment by andschwa** [comment]
And the grammar files for the syntax highlighting are available [here](https://github.com/PowerShell/EditorSyntax) for the Azure Pipelines for VS Code extension to use.
