### ISSUE TITLE
When changing PSScriptAnalyzer rules in settings dropdown, do not force scrolling

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#403]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: MacOS Sierra
- VS Code version: 1.8
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`: PSv6 alpha 13

As-is, when invoking PowerShell: ScriptAnalyzer Rules from the settings menu, when I'm changing a rule where I had to scroll down, it will immediately scroll all the way back up and force me to scroll back down over and over again. It would be nice if the menu would stay in the same position.

**Comment by daviwil** [comment]
We don't have control over that right now unfortunately, we're using VS Code's showQuickPick API which doesn't allow us to place the selection where we want.  Eventually we need a better UI for this but showQuickPick worked for now.

**Comment by SydneyhSmith** [comment]
Closing as we no longer have the PowerShell: ScriptAnalyzer rules in the settings menu, and already have an issue tracking its return.
