### ISSUE TITLE
PowerShell extension v2022.6.1 is considerably slower than v2022.5.1 when debugging

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/vscode-powershell#4038]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

PowerShell extension v2022.6.1 is considerably slower than v2022.5.1 when stepping through the code with F10 or F11.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.6.1
TylerLeonhardt.vscode-inline-values-powershell@0.0.6
```

### Steps to Reproduce

Update to v2022.6.1 and start debugging.

### Visuals

v2022.6.1

![Animation](https://user-images.githubusercontent.com/16168755/174975978-2a6d6304-7040-4036-bd7a-dd53457685e3.gif)

vs

v2022.5.1

![Animation2](https://user-images.githubusercontent.com/16168755/174976658-898390b5-5375-4d49-be19-a57358804c6c.gif)

### Logs

[1655885189-747fa844-e7ea-41df-8507-281d6e9351021655885186880.zip](https://github.com/PowerShell/vscode-powershell/files/8955689/1655885189-747fa844-e7ea-41df-8507-281d6e9351021655885186880.zip)

**Comment by andschwa** [comment]
Bisected, first bad release seems to be v2022.5.2-preview. (@kborowinski where were you for the previews?! 😜)

**Comment by kborowinski** [comment]
@andschwa Sorry 😅, didn't want to ruin your day. In my defense - I can't use preview versions of VSC or extensions at work. So there you have it 😋

**Comment by andschwa** [comment]
So, good news first, narrowed it down to https://github.com/PowerShell/PowerShellEditorServices/pull/1799. Reverted that on top of master and everything was back to normal. Bad news: that's a big PR and we definitely want the functionality in it, so now we got some troubleshooting to do.

**Comment by kborowinski** [comment]
@andschwa Thanks! It works like a charm!
