### ISSUE TITLE
When opening session logs folder from settings, don't open a workspace

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#404]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: MacOS Sierra
- VS Code version: 1.8
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`: PSv6 alpha 13

When I open the session logs folder, it opens up a new workspace and if I have one open already, forces me to reopen the workspace I had open after I'm done reviewing the logs.

**Comment by daviwil** [comment]
Is it opening the logs folder in the existing VS Code window?  If so, this might be a bug in VS Code's `vscode.openFolder` command on macOS because I'm explicitly telling it to open in a new window.

**Comment by adbertram** [comment]
Apologies. You're correct.

**Comment by daviwil** [comment]
No problem!
