### ISSUE TITLE
Path to script inserted into console on F5

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#4047]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Whenever I run PowerShell script I get the path to the script in the console

![image](https://user-images.githubusercontent.com/15063294/175823183-8daa09fe-03cf-482a-b7ec-9154f378e452.png)

You can see this in GIF

![RandomStuff](https://user-images.githubusercontent.com/15063294/175823274-bc678150-4337-44c2-8c6a-da9332679943.gif)
 
It's a bit of random.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.653
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.653
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.6.1                                                                                     
ms-vscode.powershell-preview@2022.6.2                                                                             
tobysmith568.run-in-powershell@1.1.1                                                                              
TylerLeonhardt.vscode-inline-values-powershell@0.0.6
```

### Steps to Reproduce

Run script with F5

**Comment by fflaten** [comment]
Also occurs using Pester code lense. 
It mostly/only occurs after you've executed something in the terminal. Ex. F5, ctrl+c to remove the invoked command, then f5 -> nothing. "dir" + enter, then F5 -> command is left in console.
