### ISSUE TITLE
Run Selection [F8] Double sends 

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/vscode-powershell#4055]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

This has been driving me mad in recent days, and I just tried the using the Windows 11 Sandbox for 
* Clean OS, 
* fresh install of VS Code 1.68.1
* no user settings (changed color theme), 
* no PowerShell Profile, 
* no extensions except for PowerShell  (2022.6.1) / PowerShell Preview (2022.6.2) 
* Windows PowerShell 5.1 (also happens with PowerShell 7.2.4 / 7.2.5)

### PowerShell Version

```console
$PSVersionTable                     

Name                           Value
----                           -----
PSVersion                      5.1.22000.653
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.653
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
.\code.cmd --version

1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
```

### Extension Version

```console
> .\code.cmd --list-extensions --show-versions
ms-vscode.powershell@2022.6.1
ms-vscode.powershell-preview@2022.6.2
```

### Steps to Reproduce

Create a new PS1 file 
Insert a couple of lines I used
```
$PSVersionTable
 
$psr = Get-Module PSReadLine

````
Highlight one and press F8, if that doesn't produce double output try the other. 

### Visuals

<img width="781" alt="image" src="https://user-images.githubusercontent.com/16209593/176306820-15a72575-9c34-4aa5-b035-0f4c7468d440.png">

### Logs

Let me know if logs are needed - the above should be sufficient

**Comment by andschwa** [comment]
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/4041, you indicated that you followed this instruction:

> I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

I am curious what you searched such that it did not come up? Thanks!

**Comment by jhoneill** [comment]
sorry @andschwa   

Here's the search results
<img width="976" alt="image" src="https://user-images.githubusercontent.com/16209593/176318724-dcdccf19-0a86-4fec-a713-17218090ec4c.png">

I didn't remove the IsOpen , it first happened to less than a week ago, and I didn't allow for a fix being reported and the issue closed in such a short space of time.  You're too darned efficient :-)

**Comment by andschwa** [comment]
Thank you! It was a serious question, I'm going to update the template to be sure it mentions open _and closed_ results!
