### ISSUE TITLE
Duplication of last command into terminal

### ISSUE THREAD

**Issue by martincrothers** [PowerShell/vscode-powershell#4056]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When executing PowerShell code in Visual Studio Code, the executed command(s) get re-inserted into the terminal on the next line after completion (pic for clarity).
![image](https://user-images.githubusercontent.com/52473634/176307837-f78f6687-ab1b-42a9-a152-42377b83d089.png)

Versions I was running:
Extension: 2022.6.1
VS Code: 1.68.1
PowerShell: 7.2.5
OS: Windows 10 (OS Build 19043.1766)

I rolled back the extension to 2022.5.1 and the issue went away. Before rolling back the extension I tried rolling back VSCode to the previous version (1.67.2), but that did not resolve the issue. Rolling back the extension worked on both versions of VSCode. I did not try rolling back PowerShell.

### PowerShell Version

```console
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS C:\> code --version
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
x64
```

### Extension Version

```console
PS C:\> code --list-extensions --show-versions | Select-String powershell
ms-vscode.powershell@2022.5.1
```

### Steps to Reproduce

With code in the editor window, press F5 or the run button; or select some code and press F8 or the run selection button.

The example I had in the screenshot was a .ps1 file that only contained:
```
$pwd
```
...to keep the screenshot simple.

**Comment by martincrothers** [comment]
Apologies.  I looked for permutations of "repeated" and "duplicated".

**Comment by andschwa** [comment]
No worries! I'm going to edit that issue with those words so it comes up! We'll have a new release out soon with the fix. Thank you!
