### ISSUE TITLE
Intellisense not working properly

### ISSUE THREAD

**Issue by functionkey-12** [PowerShell/vscode-powershell#4059]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Intellisense is no longer working consistently. cmdlets that have not been used earlier within the workspace will not tab-complete, or provide any information. 

This is very similar to [#179](https://github.com/PowerShell/vscode-powershell/issues/179). As suggested in #179, I have uploaded the editorservices.log

I have disable, uninstalled, and re-installed the PowerShell extension. I have rebooted VSCode many times, and have rebooted my machine as well. No change. 

### PowerShell Version

```console
PS 7.2.5> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS 7.2.5> code --version 
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
```

### Extension Version

```console
PS 7.2.5> code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2022.6.1
ms-vscode.powershell-preview@2022.6.3
```

### Steps to Reproduce

Typing get-pro will not autocomplete to any cmdlet. Instead it inserts a tab. The same happens with new-obj. Pressing ctrl+space yields no results. 

However, Get-PSCallstack, which has been used earlier in the .ps1, and elsewhere in the workspace, autocompletes fine. 

### Visuals

![VSCode-GetPSCallStack](https://user-images.githubusercontent.com/92338167/176772573-7f141db2-afa8-437d-8492-36eb7243d7c1.png)
![VSCode-GetProcess](https://user-images.githubusercontent.com/92338167/176772575-a208a5d4-2253-49c1-9022-5b7a85a7a33d.png)
![VSCode-NewObject](https://user-images.githubusercontent.com/92338167/176772577-a8f58581-7c8b-4344-a75a-da683665ef51.png)

### Logs

[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/9023183/EditorServices.log)

**Comment by andschwa** [comment]
Hi, I can't seem to repro this, it's working fine for me:
<img width="911" alt="Screen Shot 2022-06-30 at 2 22 08 PM" src="https://user-images.githubusercontent.com/2226434/176780503-d4798b01-b80d-4f31-b080-bcebf8fbab8c.png">

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

@andys-mac-mini ~/src/vscode-powershell main ≡
> $psEditor      

EditorServicesVersion Workspace                                                      Window
--------------------- ---------                                                      ------
3.4.5.0               Microsoft.PowerShell.EditorServices.Extensions.EditorWorkspace Microsoft.PowerShell.EditorServices.Extensions.EditorWindow
```

Can you share your `settings.json`?

**Comment by andschwa** [comment]
> However, Get-PSCallstack, which has been used earlier in the .ps1, and elsewhere in the workspace, autocompletes fine.

This makes me think you have `editor.wordBasedSuggestions` enabled (which is just Code suggesting completions based on other tokens in your open files, which is what you're describing), but I think perhaps you don't have actual LSP completions enabled, or your extension isn't correctly started.

Can you share the value of `$psEditor` in your integrated console?

**Comment by functionkey-12** [comment]
`PS 7.2.5> $psEditor     

EditorServicesVersion Workspace                                                      Window
--------------------- ---------                                                      ------
3.4.3.0               Microsoft.PowerShell.EditorServices.Extensions.EditorWorkspace Microsoft.PowerShell.EditorServices.Extensions.EditorWindow`

[settings - Copy.txt](https://github.com/PowerShell/vscode-powershell/files/9024328/settings.-.Copy.txt)

**Comment by functionkey-12** [comment]
I did have `editor.wordBasedSuggestions` enabled. I have turned it off, and the problem persists.

**Comment by tmknight** [comment]
I am seeing that the language service isn't fully loading since "PowerShell Integrated Console v2022.6.1" on two different machines (albeit with settings sync):
![image](https://user-images.githubusercontent.com/548588/176890231-c45ca533-b736-41f2-a1ef-8e75988ae9ff.png)
![image](https://user-images.githubusercontent.com/548588/176890404-7d9c8a57-5ede-4175-afd6-82585485fb28.png)

**Comment by functionkey-12** [comment]
I assume [Needs: Repro Info 🤔](https://github.com/PowerShell/vscode-powershell/labels/Needs%3A%20Repro%20Info%20%F0%9F%A4%94) means I need to give reproduction information. 

I type in a cmdlet, or a function that is loaded into running memory and then press tab. Tab completion does not work, nor do I get any information on the cmdlet. Pressing ctrl+space does not yield any results. 

--

Updated PowerShell extension to v2022.6.3, and there has been no change. 

I do not get the same notification from the extension that tmknight gets.

**Comment by andschwa** [comment]
@functionkey-12 I believe your issue is simply that your extension is not starting correctly. Let's diagnose that. Can you and @tmknight both follow [these steps](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#providing-information-about-your-environment) to get us detailed logs around the startup?

**Comment by andschwa** [comment]
@tmknight your log points me to this [code](https://github.com/PowerShell/PowerShellEditorServices/blob/bd4f5b0a1e0232a1f9ce75988b0e7bb35a1f0252/src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs#L271-L276). Can you please check your setting for the initial working directory, and be certain that it a) exists and b) has open enough permissions for the extension to `cd` to it?

**Comment by functionkey-12** [comment]
Here are my logs. It should all logs after a restart of the application.

I continued to add new code to my workspace, and due to this New-Object now auto-completes. However, get-pr does not suggest anything. 
[2022-07-01-Logs.zip](https://github.com/PowerShell/vscode-powershell/files/9031215/2022-07-01-Logs.zip)

**Comment by tmknight** [comment]
> @tmknight your log points me to this [code](https://github.com/PowerShell/PowerShellEditorServices/blob/bd4f5b0a1e0232a1f9ce75988b0e7bb35a1f0252/src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs#L271-L276). Can you please check your setting for the initial working directory, and be certain that it a) exists and b) has open enough permissions for the extension to `cd` to it?

Took some digging through settings.json, but found this to resolve my issue (now commented):
`// "powershell.cwd": "",`
I believe this settings was added automatically?  Hard to remember if I added it, though had no issues until the upgrade to the current PS integrated console the other day,

**Comment by andschwa** [comment]
Woah, good catch @tmknight! Yes, we recently fixed the initialization sequence so that non-VS Code clients would work again, and in doing so now directly execute essentially `cd <that string>`. Thing is, it seemed like we wouldn't need to test that it exists, since the client checks too...but you found the edge case where the client is happy and the server is not. We'll get it fixed! Thank you for checking.

**Comment by functionkey-12** [comment]
I have never set the `powershell.cwd` setting, so it was not present in my settings.json. 

I decided to set it and see if anything changes. It did not. I have since removed it.

**Comment by functionkey-12** [comment]
I started in on my settings.json file, and commented out everything to see if the issue was still present. It was not. slowly uncommented sections till the problem re-emerged. Then narrowed it down to the setting `editor.suggest.showfunctions`, which was set to false. set it to true, and the uncommented the reset of my settings, and... no issue. 

So this is not an issue with the powershell extension, just an issue with me. Don't ever remember setting this preference, but regardless, intellisense is back for me. I will go ahead and close this issue.

**Comment by Pxtl** [comment]
I just hit the same failure.

Reviewing my logs:

```
The variable '$IsWindows' cannot be retrieved because it has not been set.
```

**Comment by andyleejordan** [comment]
@Pxtl the only thing in PSES which uses that is the shell integrations script, can you try disabling it via `terminal.integrated.shellIntegration.enabled`?

**Comment by Pxtl** [comment]
> @Pxtl the only thing in PSES which uses that is the shell integrations script, can you try disabling it via `terminal.integrated.shellIntegration.enabled`?

Yes, I tried that and it has resolved the issue, thanks.  I don't love it as a workaround but since I don't recall ever noticing any impressive integration on the integrated powershell console, I doubt I'll miss it.  I tend to use an external powershell console anyways unless I'm running in the debugger.  Hopefully the VSCode team resolves the issue properly... or Microsoft force-updates everybody to PSCore so I no longer have to support PS5.1 machines.  But I suppose the PS Core team finds it easier to develop a language when they don't have actual users.
