### ISSUE TITLE
No way to disable either move logs

### ISSUE THREAD

**Issue by irvnriir** [PowerShell/vscode-powershell#4067]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

even `"powershell.developer.editorServicesLogLevel":`  doesn't have a full disable option .

sometimes, for security, logs is required to not be kept in folders with executable files ,

i also periodically get this notification
![Capture](https://user-images.githubusercontent.com/13949704/178316975-f08c1c58-3597-4157-a779-6ea9023c129c.PNG)

i did the comparison, the only extension that gets modified is `ms-vscode.powershell-<<..>>` .

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
```

### Visual Studio Code Version

```console
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.6.3
```

### Steps to Reproduce

get syntax errors in Powershell files

**Comment by andschwa** [comment]
@irvnriir have you been able to test this in the preview?

**Comment by irvnriir** [comment]
nothing changed
![Capture](https://user-images.githubusercontent.com/13949704/179961054-7614acf4-7737-4757-84fb-d9d263e26877.PNG)

**Comment by andschwa** [comment]
@irvnriir did you clean that directory up, and can you test the new `None` option?

**Comment by andschwa** [comment]
You have to have a workspace open for the workspace storage directory to be available for saving logs there.

**Comment by irvnriir** [comment]
@andschwa there is no `none` option . one present in `powershell.pester.debugOutputVerbosity` , but not `powershell.developer.editorServicesLogLevel` .

so it doesn't fix half of the cases, and still uses Extension's dir instead of userfiles storage ?

**Comment by andschwa** [comment]
😬 I thought I'd included it in the last preview, it was not. I'll ping you when the next one is out 😅

**Comment by andschwa** [comment]
Hey @irvnriir I just released v2022.7.1-preview, with this fix! Can you test it out and verify for me? Let me know if you find anything else being written to the extension installation directory instead of the workspace storage!

**Comment by irvnriir** [comment]
seems working . though its very wrong that it saves logs to workspace storage and not globalStorage .

**Comment by andschwa** [comment]
...I swear I was pointed at workspace storage as the correct place to put them. Moving to global storage.

> how you expect logs that are no longer relevant be cleared ?

IDK, what's the current behavior?

**Comment by irvnriir** [comment]
well, i didn't point there, i pointed userfiles -- (global)  .

> IDK, what's the current behavior?
the issue appears if you use the W. Storage .

**Comment by irvnriir** [comment]
leave it . all s fine

> Moving to global storage.
