### ISSUE TITLE
Else statement is ignoring the setting "powershell.codeFormatting.openBraceOnSameLine"

### ISSUE THREAD

**Issue by thegraffix** [PowerShell/vscode-powershell#4072]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Currently using:
- VSCode v1.69.0
- PowerShell VSCode extension v2022.6.3
- Windows 10 21H2 (19044.1806
<HR></HR>

I'm not sure if this is related to the bug reported in https://github.com/PowerShell/vscode-powershell/issues/462 or a feature request - it strikes me as more of a feature request and I'm not certain if that setting is even supposed to affect the `else` statement indenting.

<HR></HR>

Regardless if powershell.codeFormatting.openBraceOnSameLine is checked or not, typing `else` and hitting &lt;ENTER&gt; produces:
```
else {
    <# Action when all if and elseif conditions are false #>
}
```

### Proposed Design

If the setting powershell.codeFormatting.openBraceOnSameLine is _unchecked_ I'd like to be able to type `else`, hit &lt;ENTER&gt; and have it appear like:
```
else
{
    <# Action when all if and elseif conditions are false #>
}
```

**Comment by andschwa** [comment]
You look like you're using the [`else` snippet](https://github.com/PowerShell/vscode-powershell/blob/92f5f6d2fcd9b261b5c85da4d65fd6af04ea2373/snippets/PowerShell.json#L101-L109), and that is just going to insert what you see:

```
else {
}
```

You need to run the formatter after inserting the snippet to get it to format to:

```
else
{
}
```

You can either run the "Format Document" command directly in VS Code, or enable settings such as `editor.formatOnSave` and `editor.formatOnType`.

**Comment by thegraffix** [comment]
Thank you for the insight!  I was able to edit the `else` snippet located in:
`%userprofile%\.vscode\extensions\ms-vscode.powershell-2022.6.3\snippets\PowerShell.json`
and changed
```
  "else": {
    "prefix": "else",
    "description": "else defines what is done when all if and elseif conditions are false. More: Get-Help about_If",
    "body": [
      "else {",
      "\t${0:${TM_SELECTED_TEXT:<# Action when all if and elseif conditions are false #>}}",
      "}"
    ]
  },
```
to
```
  "else": {
    "prefix": "else",
    "description": "else defines what is done when all if and elseif conditions are false. More: Get-Help about_If",
    "body": [
      "else",
      "{"
      "\t${0:${TM_SELECTED_TEXT:<# Action when all if and elseif conditions are false #>}}",
      "}"
    ]
  },
```

Now it's working as I prefer.  Thank you again!

**Comment by andschwa** [comment]
Glad to hear it!
