### ISSUE TITLE
Exchangeonlinemanagement module commands cache to the temp directory but are not read on next app restart.

### ISSUE THREAD

**Issue by Gumbyohson** [PowerShell/vscode-powershell#4074]
### Prerequisites

- [X] I have written a descriptive issue title.
- [x] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [x] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [x] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [x] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When I want to use the exchangeonlinemanagement module commands I need to "connect-exchangeonline" to get the current commands. When this happens in ISE this is stored and remembered as a TMPEXO*.* file in the %localappdata%\temp directory. When this occurs in VSCode powershell this is forgotten between app restarts.

### PowerShell Version

```console
Name                           Value                                                           ----                           -----                                                           
PSVersion                      5.1.22000.653
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.653
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.69.1
b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.6.3
```

### Steps to Reproduce

1. Install or import the exchangeonlinemanagement powershell module
2. Connect-exchangeonline to a valid tenancy
3. TMPEXOxxxxxx.xxx file will be created in your appdata\local\temp directory and referenced for the commands
4. Commands will work and "get help" loads online page
5. Restart vscode
6. Commands context or "get help" no longer function.

### Visuals

![image](https://user-images.githubusercontent.com/1866263/178666868-3f3583b2-5b70-468d-b542-872993f9303f.png)
![image](https://user-images.githubusercontent.com/1866263/178666957-2270353b-8323-4650-9a27-ac3e1b30519b.png)
![image](https://user-images.githubusercontent.com/1866263/178667067-d6f3c1a3-fc39-48cf-830b-cfbcb695e4dc.png)
![image](https://user-images.githubusercontent.com/1866263/178667148-1a60c724-7a69-424a-ab17-3798b26fe081.png)

**Comment by Gumbyohson** [comment]
It is possible to temporarily workaround this issue by manually copying the file into the Documents\WindowsPowerShell\Modules directory but this is obviously a manual process and doesn't get updated on next connect if the commands are updated.
![image](https://user-images.githubusercontent.com/1866263/178667466-3e57f39c-f706-4a0a-9367-ba552376d8fa.png)

**Comment by SydneyhSmith** [comment]
Thanks @Gumbyohson does this work in an ordinary PowerShell terminal (as in not ISE or VSCode)?

**Comment by Gumbyohson** [comment]
@SydneyhSmith yes works as expected in ise and powershell.
