### ISSUE TITLE
powershell.powerShellAdditionalExePaths setting: Incorrect type. Expected "object".

### ISSUE THREAD

**Issue by mjarends** [PowerShell/vscode-powershell#4079]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I receive the following error in the VS Code Settings window/settings.json when defining the powershell.powerShellAdditionalExePaths property. My settings file looks like the following:

```json
 {
    <additional settings>,
    "powershell.powerShellDefaultVersion": "Powershell Core",
    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "C:\\Users\\username\\scoop\\apps\\pwsh\\current\\pwsh.exe",
            "versionName": "Powershell Core"
        }
    ]
}
```

The configuration results in the following error in the Settings UI and in the config file:

Incorrect type. Expected "object".

Because of this I am unable to launch the Integrated Console using Powershell Core 7.x 

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.69.0
92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.6.3
```

### Steps to Reproduce

1. Open the the settings.json and add the following configuration:

```json
 {
    <additional settings>,
    "powershell.powerShellDefaultVersion": "Powershell Core",
    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "C:\\Users\\username\\scoop\\apps\\pwsh\\current\\pwsh.exe",
            "versionName": "Powershell Core"
        }
    ]
}
```

2. The settings editor will display the following error:

`Incorrect type. Expected "object".`

![image](https://user-images.githubusercontent.com/4975514/179059168-6cef65fd-34b3-431c-9355-b0f39aedea6d.png)

3. I am unable to update the Powershell Integrated Console to use Powershell Core 7.x

**Comment by JustinGrote** [comment]
See https://github.com/PowerShell/vscode-powershell/issues/3978#issuecomment-1126309548

**Comment by andschwa** [comment]
@JustinGrote Oof, we really should add this to the troubleshooting document.

**Comment by mjarends** [comment]
Thanks! All of the documentation and examples still show the old configuration style. When I updated to add the values in the referenced issue I was able to get the Integrated Terminal to use my custom PowerShell installation.

**Comment by andschwa** [comment]
🤷 Live and learn.
