### ISSUE TITLE
Getting Started Walkthrough

### ISSUE THREAD

**Issue by S-Hakim** [PowerShell/vscode-powershell#4080]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

#3647 

### Summary

Currently, The PowerShell Extension in VS Code does not have an introductory experience.  

To make the getting started experience more convenient, users will be offered a Visual Studio Code Walkthrough that:
1.	gives step-by-step explanations on how to set up the PowerShell environment
2.	sets up their PowerShell environment automatically rather than manually.
3.	introduces them to settings and features of the VS Code PowerShell extension that they might not be aware of.  
4.	Provides clarity regarding setting, features, and versions of the PowerShell extension

Feel free to leave feedback, suggestions, or topics you would like to see covered in upcoming Walkthroughs!

### Proposed Design

![PowerShell Extension Walkthrough Wire Frame (1)-1](https://user-images.githubusercontent.com/107946016/181631937-e6067235-eb2a-40de-96c9-3f2389601b0d.png)
![PowerShell Extension Walkthrough Wire Frame (1)-2](https://user-images.githubusercontent.com/107946016/181631941-7309d23f-cc9c-4e12-b4ba-ca827a3f4f72.png)
![PowerShell Extension Walkthrough Wire Frame (1)-3](https://user-images.githubusercontent.com/107946016/181631945-04724c8f-47b1-43a8-8d79-5f9a4370ef6e.png)
![PowerShell Extension Walkthrough Wire Frame (1)-4](https://user-images.githubusercontent.com/107946016/181631947-4aa8de41-3fdd-42f5-99a1-03a339d6a3b9.png)
![PowerShell Extension Walkthrough Wire Frame (1)-5](https://user-images.githubusercontent.com/107946016/181631950-06a67a36-dc55-4005-b054-42efe0c53eb4.png)
![PowerShell Extension Walkthrough Wire Frame (1)-6](https://user-images.githubusercontent.com/107946016/181631951-815376df-4d0c-4d7e-b8f6-02bc19828f6a.png)
![PowerShell Extension Walkthrough Wire Frame (1)-7](https://user-images.githubusercontent.com/107946016/181631953-063ae33e-52bf-44a1-ab30-7e542904bf19.png)
![PowerShell Extension Walkthrough Wire Frame (1)-8](https://user-images.githubusercontent.com/107946016/181631955-bb89f460-1a33-4cb3-8649-7443df66ec1e.png)
![PowerShell Extension Walkthrough Wire Frame (1)-9](https://user-images.githubusercontent.com/107946016/181631961-e72aefa2-ce50-4e1e-9050-c69230572306.png)

**Comment by TylerLeonhardt** [comment]
This is looking really nice. Couple of comments:

* this walkthrough is contributed by the PowerShell extension so you have to already have the extension installed so the first step isn't needed
* I ❤️ the Install PowerShell 7 step
* I think the ISE mode step should be a toggle instead of an Enable so that the user can click it once, see what it looks like, and decide if they want it and if not click toggle again
* Does the Set PowerShell as your default shell set it as the default in VS Code or the default for the OS? I think the language needs to be clearer here
* Does the "Open PowerShell Terminal" toggle the setting or does it open a terminal?

I think this is a great set of steps. I'm excited to see PowerShell contribute a walkthrough!

**Comment by StevenBucher98** [comment]
Would setting PS7 as default require you to click and install PS7 link above the button? Or would they be blocked if they only have  Windows PowerShell, or would the button lead them to install PS7?

**Comment by StevenBucher98** [comment]
Also is the `Mark Done` button needed to navigate to the next option? Maybe a more progressional button would be better like `Next>`

**Comment by fflaten** [comment]
> I think the ISE mode step should be a toggle instead of an Enable so that the user can click it once, see what it looks like, and decide if they want it and if not click toggle again

+1 for the toggle. Or even a preview image on the right side with picture that you could switch between.

Should there be a step to introduce with images some of the basic controls like the play-buttons above the editor + common keybindings like F5/F8 (could that be read from user settings?)? This could be their first PowerShell editor experience.

**Comment by S-Hakim** [comment]
> Would setting PS7 as default be blocked if they only have Windows PowerShell, or would the button lead them to install PS7?

The button would lead to a link where they can get the most updated version of PowerShell! They would then return to the Walkthrough to complete the other steps.

**Comment by S-Hakim** [comment]
> The Mark Done button isn't necessary to navigate to the next step, but is an option to complete the checklist with one click rather than clicking each checkpoint manually. The user can go through the steps by clicking the block, so the Next> button won't be needed.

**Comment by S-Hakim** [comment]
> 

The Mark Done button isn't necessary to navigate to the next step, but is an option to complete the checklist with one click rather than clicking each checkpoint manually. The user can go through the steps by clicking the block, so the Next> button won't be needed.

**Comment by S-Hakim** [comment]
> Also is the Mark Done button needed to navigate to the next option? Maybe a more progressional button would be better like Next>

The Mark Done button isn't necessary to navigate to the next step, but is an option to complete the checklist with one click rather than clicking each checkpoint manually. The user can go through the steps by clicking the block, so the Next> button won't be needed.
