### ISSUE TITLE
PowerShell Syntax Highlighting not working - VSCode on Windows 10

### ISSUE THREAD

**Issue by drewjanderson** [PowerShell/vscode-powershell#409]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: Windows 10.0.14393 Build 14393
- VS Code version: 1.8.1
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`: 
PSVersion                      5.1.14393.576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

### Issue Description

I am experiencing a problem with PowerShell Syntax Tagging not working in VSCode. Tested same script on another Windows 10 PC (don't have versions/builds atm) and it is working properly.
[1482253281-1534fccc-792f-4f1b-ae33-653a6f6abcfc1482253272267.zip](https://github.com/PowerShell/vscode-powershell/files/664327/1482253281-1534fccc-792f-4f1b-ae33-653a6f6abcfc1482253272267.zip)

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Thanks Drew!  So by "syntax tagging", do you mean the red squiggle syntax errors?  In your logs I see script diagnostics being run but I don't see any errors being sent back.

**Comment by drewjanderson** [comment]
Sorry by this I meant syntax highlighting for cmdlets, params, etc. This is how it looks right now (attached).
![image](https://cloud.githubusercontent.com/assets/24446757/21364170/af41145c-c6bd-11e6-9d41-3d583953d0a9.png)

**Comment by daviwil** [comment]
Ahhh, that makes sense.  Use the `Preferences: Color Theme` command to change your color theme to "Dark+":

![image](https://cloud.githubusercontent.com/assets/79405/21364299/13792536-c6a5-11e6-8d11-66df7adb5da7.png)

The "Dark (Visual Studio)" theme is really bland by comparison:

![image](https://cloud.githubusercontent.com/assets/79405/21364311/21b3cff2-c6a5-11e6-8b8c-b803820111da.png)

**Comment by drewjanderson** [comment]
You're kidding me!!!! Wow I'm such an idiot.

Thanks for not beating me up on that one. Your solution "fixed" my "problem."

The head condition might require more work.

**Comment by daviwil** [comment]
Heh, don't worry about it, it's not the first time that color theme has caused confusion!

**Comment by DevenSuji** [comment]
This is helpful. I too had the same issue. Changing the Colour theme to Dark + fixed that. Thanks

**Comment by PramodKumarYadav** [comment]
I was looking for something similar to Powershell ISE color coding in VSCode and found it also hereunder View-> Command Palette -> Preferences:Color Theme -> Powershell ISE
