### ISSUE TITLE
Don't notify the user about updates

### ISSUE THREAD

**Issue by Tyriar** [PowerShell/vscode-powershell#4100]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

We are trying to reduce "notification fatigue" and this one seems very much not useful:

<img width="467" alt="Screen Shot 2022-07-31 at 5 13 57 pm" src="https://user-images.githubusercontent.com/2193314/182051408-c0e75cbd-5f55-48b4-abea-042278050b1e.png">

The update's content was:

- [vscode-powershell](https://github.com/PowerShell/vscode-powershell)
✨ 💭 [vscode-powershell #4093](https://github.com/PowerShell/vscode-powershell/pull/4093) - Change storageUri to globalStorageUri for log and session files.
- [PowerShellEditorServices](https://github.com/PowerShell/PowerShellEditorServices) v3.4.7

Which definitely doesn't seem important enough to interrupt the user. Also consider if all of a user's extensions do this they could be getting 1+ notifications a day on average? Some users have over 100 extensions installed based on issues we've seen.

This is the VS Code issue tracking a generic extension has updated announcement https://github.com/microsoft/vscode/issues/123906

### PowerShell Version

```console
-
```

### Visual Studio Code Version

```console
Version: 1.70.0-insider
Commit: 12b08be500f8a307f30e92cbc3ee39ba115eab69
Date: 2022-07-29T10:50:40.282Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0
```

### Extension Version

```console
ms-vscode.powershell-preview@2022.7.2
```

### Steps to Reproduce

Wait for an update with auto updates on

**Comment by andschwa** [comment]
To be fair, that's the preview extension you're seeing an update for. The changelog for the one stable release rolled out last month was [much longer](https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.7.2).

**Comment by Tyriar** [comment]
Personally I don't like any extensions doing this even on stable, but VS Code Insiders for example only pops up the release notes webview when a major insiders version change happens

**Comment by andschwa** [comment]
Yeah it's a reasonable ask, I don't like extra noise either. And the ideal situation is that the extension always "just works" and gets better in the background.

**Comment by SeeminglyScience** [comment]
I agree that it'd be better if we kept the notification to large changes. Even ignoring the fact that it can be annoying, the more folks click `Show Release Notes` and it's a small change the less likely they are to click that button next time.

Also a "Don't show again" button might be advisable.

**Comment by andschwa** [comment]
I doubt anyone would miss it if we turned it off.

**Comment by fflaten** [comment]
If/when there are new user-facing features and documented like VSCode release notes, then it would be nice to get a notification. With the current issue-list format, its probably not necessary.

**Comment by Tyriar** [comment]
Thanks @andschwa 👍
