### ISSUE TITLE
Extension doesn't start with when workspace is defined with zero folders

### ISSUE THREAD

**Issue by opmdsm** [PowerShell/vscode-powershell#4102]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Hi,

Just updated PowerShell extension to v2022.7.2 and all powershell files within an existing workspace does not work anymore.

For instance:
1. Switching from PowerShell x86 and x64 does not work anymore (command PowerShell: ShowSessionMenu not found).
2. Executing only a selection of commands also does not work (command PowerShell: RunSelection not found).

If I open those files separately (open file, without open workspace) the above commands runs successfully.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.69.2
3b889b090b5ad5793f524b5d1d39fda662b96a2a
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.7.2
```

### Steps to Reproduce

Open an existing workspace and try to execute what's described in the issue.

### Visuals

Commands executed within an opened workspace:

Command PowerShell: ShowSessionMenu not found:
![image](https://user-images.githubusercontent.com/107676477/182338130-dc7e158c-334f-4609-8eed-169471bec03a.png)

PowerShell: RunSelection not found:
![image](https://user-images.githubusercontent.com/107676477/182338429-4beef063-ddef-4e4c-986f-ae97b2d7d6be.png)

Same commands executed with open files one by one:

Command PowerShell: ShowSessionMenu:
![image](https://user-images.githubusercontent.com/107676477/182340871-42342568-db90-4cb1-b8a5-5c0b1ee8ead9.png)

PowerShell: RunSelection:
![image](https://user-images.githubusercontent.com/107676477/182340997-17410e9a-fc90-46e1-9101-c3b121e34080.png)

**Comment by andschwa** [comment]
I can open an existing workspace just fine. Can you give us some more details, maybe share your workspace file?

**Comment by opmdsm** [comment]
I can also open an existing workspace just fine. The problem is when opening a file within that workspace, i cannot execute anything. Even simple commands like Get-ExecutionPolicy or Write-Host "test" does not work.

Let's assume i have a workspace W1 with a PowerShell file F1.

Steps:
Not working:
1. Open workspace W1
2. Open file F1
3. Try to execute something from that file (Write-Host for ex), it will not work.

Working:
1. Close any workspaces and just open file F1, without opening workspace W1
2. Try to execute something from that file (Write-Host for ex), it will work.

This is an example of workspace file, but is almost empty:
{
	"folders": []
}

Note:
If is possible, we can have a Teams session.

**Comment by andschwa** [comment]
Ah ha, I can repro when I set `folders` to an empty array. That is...a very strange use case. I need to check what happens with other extension like this, and I'll see if there's an easy workaround, but can you please add your workspace's folder to the workspaces' `folders` and test again?

**Comment by opmdsm** [comment]
> Ah ha, I can repro when I set `folders` to an empty array. That is...a very strange use case. I need to check what happens with other extension like this, and I'll see if there's an easy workaround, but can you please add your workspace's folder to the workspaces' `folders` and test again?

I'm glad that you are able to reproduce it. I don't know if is a strange use case or not, but just for curiosity I've checked some of other workspaces I work with and none of them have any folder configured.

Ex:
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {}
}

Because I don't have the option to create a workspace in Visual Studio Code, what I do to create one is this:
1. New text file and change it to PowerShell type, save it
2. Then File -> Save Workspace As...
Maybe that's why I end with empty folders and I'm wondering if this is not causing also https://github.com/PowerShell/vscode-powershell/issues/4012#event-6917284186.

I can add workspace's folder to the workspaces' `folders` and test it, but how should look like?

Like this?
{
"folders": [{"path": "C:\Temp"}]
}

**Comment by opmdsm** [comment]
I have replaced workspace file
{
"folders": []
}

With this:
{
"folders": [
{
"path": "."
}
],
"settings": {}
}

And it works.

**Comment by andschwa** [comment]
@opmdsm Can you repro with your prior settings with the latest code, v2022.8.0-preview? I fixed that edge case where `folders` was an empty array.

**Comment by opmdsm** [comment]
Hmm... I don't know how to install a preview version... But I prefer to install a release version and anyway I will be off for the next 2 weeks, so I can try then. Thank you very much for help so far.

**Comment by andschwa** [comment]
It is simply [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) on the marketplace. You can disable the regular one, install this and test, and then uninstall it.
