### ISSUE TITLE
Terminal stops displaying Variable output

### ISSUE THREAD

**Issue by Fimlore** [PowerShell/vscode-powershell#4114]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [x] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

During usage of the Powershell Extension, it all of a sudden stops displaying data contained in Variables, like in the example below:
![Powershell_Terminal_Exampla1](https://user-images.githubusercontent.com/20944149/183434766-ff659e17-3dcf-4f02-94f4-4750d8485ff5.png)

All of a sudden, it will completly stop echoing data and I have to force it with Write-Host, or Output-GridView
![Powershell_Terminal_Exampla2](https://user-images.githubusercontent.com/20944149/183435145-5f355382-9534-4074-b6b8-852984b3d18c.png)

As you can see in the screenshot above, not a single variable outputs any data.

![Powershell_Terminal_Exampla3](https://user-images.githubusercontent.com/20944149/183435489-29a53c2f-2747-4ffe-a17d-caf56c6b9c9c.png)

I dont feel like Im doing anything weird, I have scripts open that I work on, and as soon as I kill the Terminal, it will start working again ---  but then I will loose the variables I was working with, and also all connections I have with services like MS Teams and Azure. 

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22000.653
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.653
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.70.0
da76f93349a72022ca4670c1b84860304616aaa2
x64
```

### Extension Version

```console
code --list-extensions --showversions | Select-String powershell

ms-vscode.powershell
```

### Steps to Reproduce

Have script open, get input stored into variable (I think, save the script) - variables no longer output.

**Comment by Fimlore** [comment]
It seems the issue does not occur in Powershell Core 7.1.2

**Comment by SydneyhSmith** [comment]
Thanks this seems related to #3991 
@Fimlore could you please provide logs when this happens

**Comment by andschwa** [comment]
@Fimlore do you know if you have `Start-Transcript` somewhere before all this happens?
