### ISSUE TITLE
do-while shortcut gives too many parentheses

### ISSUE THREAD

**Issue by ncook-hxgn** [PowerShell/vscode-powershell#4119]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Open VS Code and create a new PowerShell script. In the new PowerShell script, write `do-` and select the `do-while` snippet. Yields this buggy code:
![image](https://user-images.githubusercontent.com/36889813/183679445-123dc7a9-745d-4200-b213-fb8a4f5f5d18.png)

Doesn't happen with `do-until` snippet.

Plz fix

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.70.0
da76f93349a72022ca4670c1b84860304616aaa2
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.7.2
```

### Steps to Reproduce

Open VS Code and create a new PowerShell script. In the new PowerShell script, write `do-` and select the `do-while` snippet. 

### Visuals

![image](https://user-images.githubusercontent.com/36889813/183679445-123dc7a9-745d-4200-b213-fb8a4f5f5d18.png)

**Comment by andschwa** [comment]
That snippet is right here:

https://github.com/PowerShell/vscode-powershell/blob/2d3a3c26fa9b5e54bdc4087b64f9729df30d01d0/snippets/PowerShell.json#L90-L100

If you want to fix it and submit a PR, I'd be more than happy to merge it!

**Comment by andschwa** [comment]
Resolved, thanks! New preview will be out soon.
