### ISSUE TITLE
Add an option to run powershell.exe with a parameter like "-Version 2"

### ISSUE THREAD

**Issue by FrankMuraschow** [PowerShell/vscode-powershell#412]
### System Details

- Operating system name and version: Windows Server 2008 R2 Standard
- VS Code version: 1.8.1
- PowerShell extension version: 0.8.0

- Output from `$PSVersionTable`:
PSVersion                      4.0                                                                                     
WSManStackVersion              3.0                                                                                     
SerializationVersion           1.1.0.1                                                                                 
CLRVersion                     4.0.30319.42000                                                                         
BuildVersion                   6.3.9600.16406                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                    
PSRemotingProtocolVersion      2.2           

### Issue Description

I am experiencing a problem with running scripts for SharePoint 2010. This is a known issue for PowerShell 4. The normal fix for me is to run powershell.exe with the parameter _-Version 2_ 
I could not find a way to do this with the powershell extension.

**Comment by daviwil** [comment]
Not sure whether our code will work in PowerShell 2 compatibility mode but we'll look into it.  Thanks!

**Comment by TylerLeonhardt** [comment]
In the next version of the extension, we will only support Windows PowerShell 5.1, PowerShell Core 6.2, and PowerShell 7+.

Because of this, we will not be supporting the `-version 2` parameter.

The extension hasn't worked with v2 for a very long time anyway.
