### ISSUE TITLE
Uncaught Exception: SyntaxError: Unexpected end of JSON (extension host crash)

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#413]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: Windows 10 Enterprise
- VS Code version:
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:49:23.350Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

Periodically, when scrolling through the scripts, I'm getting an error saying 'Extension host terminated unexpectedly. Please reload the window to recover.'

Looking at the Debug Console I see this:
...
extensionHost.ts:293[Extension Host] powershell.exe started, pid: 35008, exe: C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe
extensionHost.ts:293[Extension Host] Uncaught Exception:  SyntaxError: Unexpected end of JSON inputA.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] SyntaxError: Unexpected end of JSON input
    at Socket.powerShellProcess.stdout.on (C:\Users\seriavio\.vscode\extensions\ms-vscode.PowerShell-0.8.0\out\session.js:149:37)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)A.logExtensionHostMessage @ extensionHost.ts:293
messageService.ts:126Extension host terminated unexpectedly. Please reload the window to recover.e.doShow @ messageService.ts:126
extensionHost.ts:332Extension host terminated unexpectedly. Code:  7  Signal:  nullA.onExit @ extensionHost.ts:332
...

That made me think that it's indeed the PowerShell extension that causes the host to crash, however I'm not sure exactly why that's happening. 

I did look through the logs, but couldn't find anything special there.

Maybe you can figure it out.

### Attached Logs
Attaching the extension logs generated today:
[Log.zip](https://github.com/PowerShell/vscode-powershell/files/670612/Log.zip)

Thanks in advance!

**Comment by daviwil** [comment]
That's really weird...  The extension logs don't show any error.  I've seen a similar "Unexpected end of JSON input" error while debugging the extension but I've never seen that crash the extension host before.  If you reload the window after this happens do things usually work OK after that?

**Comment by Glober777** [comment]
This time it didn't crash after I reloaded, but I'm not sure about all the other cases (whether those were caused by the JSON input or not).

**Comment by TylerLeonhardt** [comment]
This is a very old bug... @Glober777 do you know if you're still seeing this?

If not, we can probably close this

**Comment by Glober777** [comment]
I don't remember seeing it lately. Will close it out.

Thanks!
