### ISSUE TITLE
command 'PowerShell.RunSelection' not found

### ISSUE THREAD

**Issue by D1StrX** [PowerShell/vscode-powershell#4135]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Since specifically version 2022.7.2 the Powershell Extention is having some issues on my end. My 2 workstations (sharing the same account ofc) getting the following errors: 
When pressing F8: command 'PowerShell.RunSelection' not found
When pressing F5:
![image](https://user-images.githubusercontent.com/40062371/184863545-3a6ef5d3-d716-45c0-902b-e7916569ea5c.png)

Trying to upload a bug from within VSCode:
![image](https://user-images.githubusercontent.com/40062371/184863569-de2fa972-bce5-4fd1-9a51-9101e17b6d03.png)

Found some similar issues from the past, e.g.: https://github.com/PowerShell/vscode-powershell/issues/2526
Also not getting logs in the Logs folder, when setting the log level to diagnostic.

Version 2022.6.3 is still working fine. Works with Powershell 7.2.5 and 7.2.6 & vscode 1.70/1.70.1.
Reinstalling VSCode and/or the PowerShell extension didn't solve the issue.

My debug profile contains this for PowerShell:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "PowerShell: Launch Current File",
      "type": "PowerShell",
      "request": "launch",
      "script": "${file}",
      "cwd": "${file}"
    }
  ]
}
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.70.1
6d9b74a70ca9c7733b29f0456fd8195364076dda
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.7.2
```

### Steps to Reproduce

Any piece of powershell code will trigger the issue when pressing F5 or F8 for a single row in a new 
$token = Read-Host -Prompt "Enter Authentication token"

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "PowerShell: Launch Current File",
      "type": "PowerShell",
      "request": "launch",
      "script": "${file}",
      "cwd": "${file}"
    }
  ]
}
```

### Logs

None available.

**Comment by andschwa** [comment]
The latest code is available in the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview), and includes a myriad of fixes. Could you verify if this issue still reproduces using the preview extension? Please note that this preview is likely to include other bugs, and you should feel free to file new issues for those so we can work through them. Thanks again!

**Comment by D1StrX** [comment]
I managed to solve and found the issue. Apparently 2022.7.2 does actually 'read' the .workspace file? 
I had a faulty json config (missing a ','). 
Tried to figure it out by doing the following: Opening a new VSCode Window -> new file -> PowerShell -> PowerShell code (whatever you want) -> F5/F8
That was working fine, reason for me to look at the workspace file. Fixed it, and PowerShell was running again after confirming '"powershell.cwd question":'

I guess that that the reason is why it couldn't start PowerShell. It tries to write "powershell.cwd": to the settings section, but faulty json config (folder configurations) above it stops it from doing so.

**Comment by andschwa** [comment]
Woah, very interesting. Thanks so much @D1StrX. As we're working to resolve https://github.com/PowerShell/vscode-powershell/issues/2153, we started utilizing the workspace file in startup. I'll try to repro this and see if there's an error we can catch and ignore rather than hang.

**Comment by andschwa** [comment]
I couldn't get this to repro, but I added a try/catch around where we update the setting which _should_ take care of it.

**Comment by andschwa** [comment]
Ok, new preview will be out momentarily. Could you please confirm you can no longer repro this?

**Comment by D1StrX** [comment]
I'll try to test it. Will misconfigure the workspace file and install the preview version.

**Comment by D1StrX** [comment]
Good news, it does indeed not hang on the cwd part. It ignores it and continues. 
Perhaps nice if a popup could be displayed, that something is skipped and you should check your workspace file?

**Comment by andschwa** [comment]
Awesome, thanks for testing! And that's a good idea.
