### ISSUE TITLE
Command 'PowerShell: Show Extension Terminal' resulted in an error (command 'PowerShell.ShowSessionConsole' not found)

### ISSUE THREAD

**Issue by bender-the-greatest** [PowerShell/vscode-powershell#4136]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

The current version of the PowerShell plugin does not load when I open `.ps1` files any longer. When I try to launch the integrated terminal with `PowerShell: Show Extension Terminal` from the command pallete, I get the following error (re-stated from title):

> Command 'PowerShell: Show Extension Terminal' resulted in an error (command 'PowerShell.ShowSessionConsole' not found)

Rolling back to the prior version fixes this (albeit with the old `PowerShell Integrated Console` name for the terminal). I've found at least one other person today experiencing the same issue. I've also tried the related `PowerShell: Restart Current Session` command which results in a similar "command not found" error.

Recently-created issue #4135 seems like it could be related although it's for a specific plugin feature. My issue here is that the terminal not launching causes the plugin to entirely not function.

### PowerShell Version

```console
> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
> code --version
1.70.1
6d9b74a70ca9c7733b29f0456fd8195364076dda
x64
```

### Extension Version

```console
> code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2022.7.2
```

### Steps to Reproduce

1. Open `.ps1` file for editing.
2. No plugin features are available. Quick evidence of this is no syntax checking is performed against the opened file.
3. Try to open the plugin terminal with the `PowerShell: Show Extension Terminal` pallete command. Modal dialog with the following error is displayed:

   > Command 'PowerShell: Show Extension Terminal' resulted in an error (command 'PowerShell.ShowSessionConsole' not found)

### Logs

No logs are generated when running `PowerShell: Show Extension Terminal` from the command pallete. I set logging to `Diagnostic` before attempting this.

**Comment by andschwa** [comment]
Hello! The latest code is available in the [PowerShell Preview for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview), and includes a myriad of fixes. Could you verify if this issue still reproduces using the preview extension? Please note that this preview is likely to include other bugs, and you should feel free to file new issues for those so we can work through them. Thanks again!

**Comment by andschwa** [comment]
Could you also check your workspace file and ensure it's valid JSON?

**Comment by dbaileyut** [comment]
I'm reproducing on v2022.7.2 when I have a workspace with no folders. If I add a folder, the extension behaves as expected.

I'm not seeing it on the preview v2022.8.2.

Test workspace is just:
```
{
	"folders": []
}
```

In the VSCode developer tools console, I see:
```
mainThreadExtensionService.ts:111 Activating extension 'ms-vscode.powershell' failed: Cannot read properties of undefined (reading 'uri').
$onExtensionActivationError @ mainThreadExtensionService.ts:111
console.ts:137 [Extension Host] testLog: >>> activateInternal
console.ts:137 [Extension Host] testLog: >>> registerUIExtensionVariables
console.ts:137 [Extension Host] testLog: >>> activateInternal end
```

**Comment by bender-the-greatest** [comment]
I will try the preview tomorrow, I am off for the rest of today.

I saw that other issue mentioning the invalid JSON in the workspace file but my workspace is valid JSON. I checked that earlier.

My workspace is also not completely empty as the other person mentioned in their reproduction of the issue.

All emails in this message string and any attachments are the confidential information of CSG Systems International, Inc. (CSG), or its affiliates and subsidiaries, and may contain privileged and/or confidential material. If you are not an intended recipient, please delete it immediately and notify the sender; unintended recipients are not authorized to read or otherwise use the information contained herein.

**Comment by dbaileyut** [comment]
> My workspace is also not completely empty as the other person mentioned in their reproduction of the issue.

Sorry, saw this on Reddit and it looked like what I experienced. Mine issue is actually a dupe of #4102

**Comment by andschwa** [comment]
If it's not reproducing with v2022.8.2 then it's fixed 😆

**Comment by andschwa** [comment]
Oh, you're not the OP.

**Comment by bender-the-greatest** [comment]
I updated to the Preview extension (`v2022.8.2`) and I am still getting the same behavior.

**Comment by bender-the-greatest** [comment]
I was able to get a little more information from the logs during VS Code startup this time (with the Preview extension still installed). Not sure why I didn't get this the last time I went through the logs, but I'm getting the following error now when the extension tries to load:

```text
[2022-08-17 09:59:27.834] [exthost] [error] Activating extension ms-vscode.powershell-preview failed due to an error:
[2022-08-17 09:59:27.834] [exthost] [error] Error: Can not delete in empty document
    at R (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:19:2203)
    at T.getEdits (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2692:4143)
    at T.updateConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2692:3377)
    at T.doWriteConfiguration (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2692:2981)
    at async Object.factory (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2692:2641)
```

**Comment by andschwa** [comment]
That makes sense given what other people have seen. I just need to get a local repro. Essentially around where we read and write to the workspace (if you have multiple root folders, we ask you to select which folder for the `cwd` and then remember the selection), I need a catch to handle bad workspaces Code is having trouble reading/writing.

**Comment by bender-the-greatest** [comment]
Would it help if I share my workspace file?

**Comment by bender-the-greatest** [comment]
Okay, I just got this to work with the Preview plugin, but I'm not sure why I haven't gotten this prompt up until this point. It asked me to select a working directory for the PowerShell extension. Now it remembers and loads up every time.

I think this might be the crux of the issue, if the extension needs a working directory selected by the end user. But the current stable extension was not asking me this for some reason, and the first few times I launched the Preview version of the extension it did not prompt me either. Is there a way we can manually set the extension working directory if not prompted?

**Comment by bender-the-greatest** [comment]
Additionally, after setting the plugin working directory, removing the preview extension, and installing the stable extension `v2022.7.2`, the stable extension indeed works fine now.

**Comment by bender-the-greatest** [comment]
I found the extension setting for setting the workspace. I tested setting this to a different location than I picked in the prompt and the PS extension continues to work fine. If you don't get the prompt to pick a working directory for the plugin, the following setting is where you can set this:

```json
"powershell.cwd": "c:\\path\\to\\working\\directory\\"
```

I have this set now to my root workspace folder. To re-state, if you don't get prompted to set the extension working directory and the extension fails to load, setting the above setting in your workspace should fix this issue (don't forget to use a real path).

**Comment by andschwa** [comment]
I think I need to get the preview extension out sooner rather than later 😆 The setting is `powershell.cwd`. Previously we just defaulted to the first folder of the list of folders in a multi-root workspace. In an effort to properly support multi-root workspaces I added the choice option to pick and remember which one. I think there was a bug that made it's way into stable around testing the existence of the folder, and that's fixed in preview. Keep in mind, it should _only_ ask if you have setup a workspace file with multiple named items under the `folders` key (e.g. VS Code's multi-root workspace feature). Can you confirm your workspace is setup like that?

**Comment by andschwa** [comment]
@bender-the-greatest I'm losing track of bugs here. Your first post in this issue was about a multi-root workspace with the edge case of zero folders. That _has_ been fixed in the preview extension: https://github.com/PowerShell/vscode-powershell/pull/4104, and so this issue is actually a duplicate of https://github.com/PowerShell/vscode-powershell/issues/4102.

**Comment by andschwa** [comment]
@bender-the-greatest what's your workspace file that repros this? Would be very helpful. I want to get a proper try/catch for this and for https://github.com/PowerShell/vscode-powershell/issues/4135 into the preview before rolling it to stable.

**Comment by bender-the-greatest** [comment]
> Can you confirm your workspace is setup like that?

I have multiple folders added to the workspace if that's what you mean. In the `code-workspace` JSON there are multiple directories listed under the `folders` array.

> Your first post in this issue was about a multi-root workspace with the edge case of zero folders.

That was someone else, I have multiple folders added to my workspace.

**Comment by bender-the-greatest** [comment]
I don't think the workspace file will help at this point. The issue seems to have been that `powershell.cwd` was not set, and I was not prompted to set this until after a few attempts of trying to get the plugin to load.

**Comment by bender-the-greatest** [comment]
Alright, while I can't reproduce the prompt not appearing at all anymore, I _can_ replicate the erroneous extension behavior by clicking away rather than selecting a working directory when two or more folders are added to the workspace, and `powershell.cwd` is also not set:

# repro-issue.code-workspace
```json
{
	"folders": [
		{
			"name": "ChocolateyPackages",
			"path": "ChocolateyPackages"
		},
		{
			"path": "scratch"
		}
	]
}
```

**Comment by andschwa** [comment]
Ok, new preview will be out momentarily. Could you please confirm you can no longer repro this?
