### ISSUE TITLE
Walkthrough recommends `-UseMSI` but I'm on a mac that can't install things via MSIs

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#4149]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I was looking at the new Walkthrough and noticed that I got some text that says to use the `-UseMSI` switch that I can't use on my platform.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
code-insiders --version    
1.71.0-insider
28f604dec81b609dd7e69362585f7a99d4c48f88
arm64
```

### Extension Version

```console
ms-vscode.powershell-preview@2022.8.4
```

### Steps to Reproduce

Open the Walkthrough on macOS

### Visuals

![image](https://user-images.githubusercontent.com/2644648/185727739-558be854-2db5-4163-b8dd-8ac148b81d1f.png)

**Comment by andschwa** [comment]
@TylerLeonhardt I know, we just wanted to get the intern project out. I'm going to replace that step with OS-specific ones using `when` (or would welcome a PR from you to do so).
