### ISSUE TITLE
Scriptblock Intellisense does not work as expected

### ISSUE THREAD

**Issue by MrFly72** [PowerShell/vscode-powershell#4159]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Dont know how to describe the feature, I will try in description:
When adding a new block like foreach, there is a intellisense feature which can add an empty block.
This feature somehow reacts weird, dont know if it is only me....
It will add some kind of "Fill-in-variables" and has a very weird behavior in deleting or adding characters.
I added a video to show that.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.70.2
e4503b30fc78200f846c62cf8091b76ff5547662
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.8.5 (Disabled)
ms-vscode.powershell-preview@2022.8.5 (Active)
tobysmith568.run-in-powershell@1.1.1
```

### Steps to Reproduce

Use foreach from the intellisense menu

### Visuals

https://user-images.githubusercontent.com/65505278/187616012-526e58ba-bcba-459e-86cb-4eb7d1eaf2c7.mp4

**Comment by SydneyhSmith** [comment]
Thanks @MrFly72 looks like you are using multi cursor in the video which is the feature that is causing this behavior...that being said it looks like there may also be an issue with the snippet

**Comment by MrFly72** [comment]
Puh, I am not aware of anything I changed in this direction. To me it is basically default.
I have this on these plattforms and never changed the setting you mention, not that I even know what it means ;-)
- Server 2019
- Win10
- Debian Linux

**Comment by andschwa** [comment]
So, what you're using is one of the built-in snippets (which is technically not IntelliSense), and the way that it's written it uses VS Code's built-in feature of "multiple cursors" so that both the variable name and comment are filled out at the same time. Take a look here:

https://github.com/PowerShell/vscode-powershell/blob/1c1452710e903edab3c2bb7494376752f794604c/snippets/PowerShell.json#L146-L154

The problem with these built-in snippets is that they can't please _everyone_. @JustinGrote put a lot of effort into making some quite nice and up-to-date snippets that are now provided by the extension. If that snippet isn't working how you would like it to, I'd suggest writing your own, or turning off snippets as suggestions.

I have marked this as up-for-grabs because we're always willing to take an improvement to the snippets; however, it comes with that some caveat that they'll never please everyone.

**Comment by andschwa** [comment]
See the VS Code [documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets) on snippets.

**Comment by MrFly72** [comment]
Dont take me wrong on this, it might just be me handling it wrong ?
It is not clear to me how it is supposed to work?
What should I fill in to do it right ?
I actually never got it to work, thats why I thought it is a bug.

**Comment by MrFly72** [comment]
I just tested around and finally figured: TAB through all the parameters, is that right ?
It was not logical to me to use tab in the editor except for indenting, so far.

**Comment by MrFly72** [comment]
> See the VS Code [documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets) on snippets.

Ok, my bad. Sorry for confusion. I have to admit, that I only read the docs so far when looking for a specific thing and never stumbled across snippets docs.
You can close this

**Comment by andschwa** [comment]
No worries at all, and yes I think it is "tab," it should move to the other "fillable" fields in the snippet. They can be weird! I remember when I first started using Snippets in Emacs (of course, we called them "skeletons" back then), and they can get super complicated but also amazing. When porting PowerShell to Linux, I created a skeleton that would let me mark a block of code, and then wrap it in in an `#ifdef WINDOWS <marked code> #else <leave cursor here> #endif`, and it got _so much use_.

**Comment by MrFly72** [comment]
I think I just got confused as I would never try to use "Tab" in the middle of a text.
Additionally "breaking" out of this was tough and had some issues I ran into.
I finally realized now that ESC seems to take me out of the "automation" and will not have the issues in the movie anymore.
