### ISSUE TITLE
Assembly could not be found

### ISSUE THREAD

**Issue by Semy000** [PowerShell/vscode-powershell#416]
### System Details: 

- Operating system name and version: Windows 10 Enterprise
- VS Code version: 1.8.0
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`:

PSVersion                      5.1.14393.576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I'm trying to login to azure using Login-AzureRmAccount. If I execute this script not in the vs code all is working correct.
But when I execute my script in the vs code an error is thrown:

```
Login-AzureRmAccount : Loading an assembly required for interactive user authentication failed. Make sure assembly 
'Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms, Version=2.28.3.860, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35' exists: Could not load file or assembly 
'Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms, Version=2.28.3.860, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
```

By design, Login-AzureRmAccount cmdlet require this assembly, even if i don't use gui interface to login.

I have tried to use 
`[System.Reflection.Assembly]::LoadWithPartialName("Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms")`
but it has no effect. After that I have tried
`Add-Type -Assembly Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms` 
and an another error was thrown
`Add-Type : Cannot add type. The assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms' could not be 
found.`

I have tried many different ways to load it, but none of them worked. How can i do this?

**Comment by SETOL** [comment]
The only one way that works in this case it's to download specific version of assembly with NuGet and use Add-Type with the path of this assembly. Is there is some supported way to avoid this steps? If we run script outside of vs code there is no need to load some assemblies by itself.

**Comment by SydneyhSmith** [comment]
@SETOL I am wondering if with our updates you are still experiencing this issue?

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
