### ISSUE TITLE
Workspace folder pick pops up if a predefined variable is used for the `powershell.cwd` setting

### ISSUE THREAD

**Issue by lewis-yeung** [PowerShell/vscode-powershell#4163]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

The description for the `powershell.cwd` setting says:

> Predefined variables can be used (i.e. ${fileDirname} to use the current opened file's directory).

However, even if a predefined variable (e.g., `${fileDirname}` or `${fileWorkspaceFolder}`) is used for `powershell.cwd`, whenever I open a PowerShell (.ps1) file in a **multi-root workspace for the first time**, it prompts me to choose a workspace folder as the working directory:

> Select a folder to use as the PowerShell extension's working directory.

This is so annoying and should not happen. While if I use a literal path such as `C:\`, it works fine and the workspace folder pick does not pop up.

Other possibly related settings I use:

```json
{
  "powershell.startAutomatically": true,
  "powershell.integratedConsole.showOnStartup": false,
  "powershell.integratedConsole.startInBackground": true
}
```

Possibly related code:

https://github.com/PowerShell/vscode-powershell/blob/c3c857db669d97908df93267c6d3763468594e80/src/settings.ts#L326-L331

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.71.0
784b0177c56c607789f9638da7b6bf3230d47a8c
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.8.5
```

### Steps to Reproduce

1. Apply the following settings:
	```json
	{
	  "powershell.cwd": "${fileWorkspaceFolder}",
	  "powershell.startAutomatically": true,
	  "powershell.integratedConsole.showOnStartup": false,
	  "powershell.integratedConsole.startInBackground": true
	}
	```
	where any other predefined variable (e.g., `${fileDirname}`) can be used for `powershell.cwd`.
2. Open a **multi-root workspace** in a new VS Code window.
3. Open a PowerShell (.ps1) file, and the workspace folder pick will pop up.

**Comment by andschwa** [comment]
Hm, I'll have to check when the pre-defined variable is getting interpolated.

**Comment by andschwa** [comment]
@lewis-yeung can you confirm that this _used_ to work as you expected?

**Comment by andschwa** [comment]
I actually can't imagine that `${fileWorkspaceFolder}` or `${fileDirname}` _could_ work, because the `cwd` setting is an initialization setting, it's read and processed long before any file is opened. Put another way: it's a workspace-scoped variable, not a file-scoped variable.

**Comment by lewis-yeung** [comment]
> I actually can't imagine that `${fileWorkspaceFolder}` or `${fileDirname}` _could_ work, because the `cwd` setting is an initialization setting, it's read and processed long before any file is opened. Put another way: it's a workspace-scoped variable, not a file-scoped variable.

@andschwa Then the following description should be adjusted since it's really misleading, IMO.

https://github.com/PowerShell/vscode-powershell/blob/60af2cea5fcb3663bc68bb5649bda8b2b386b791/package.json#L647

**Comment by lewis-yeung** [comment]
> can you confirm that this _used_ to work as you expected in a prior version of the extension?

@andschwa I can confirm that [v2022.6.3](https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.6.3) works fine, even I don't customize `powershell.cwd`. I believe the bug has appeared since [v2022.7.1-preview](https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.7.1-preview) as I see an entry in the changelog:

> Add multi-root choice experience to `powershell.cwd`.

which is related to #4064.

**Comment by andschwa** [comment]
I _don't_ think that v2022.6.3 worked as you expected. While I believe that there was no error being thrown, I think the given value was still not having the predefined variables resolved. In that version, this was a silent error and the value was just passed along unvalidated, and the server ignored it since it wasn't a proper path. In the latest version, the setting is now validated and an error thrown.

Unfortunately, VS Code has yet to provide an API for extension's to resolve their pre-defined variables in our contributed settings: https://github.com/microsoft/vscode/issues/46471

Until that API is available, this sadly isn't something we can support. I _don't_ know why the existing setting says it was ever supported; that must just be a historical error. The best I can do right now is update `package.json` to stop lying about that.
