### ISSUE TITLE
Cannot activate extension

### ISSUE THREAD

**Issue by memory-yiyi** [PowerShell/vscode-powershell#4169]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

PowerShell extension is always in "activating state", shell integration cannot be activated.
<img width="87" alt="image" src="https://user-images.githubusercontent.com/87287779/189298275-a9c195ad-dcba-498e-b336-00703adb2aeb.png">

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22622
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.71.0
784b0177c56c607789f9638da7b6bf3230d47a8c
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.8.5
```

### Steps to Reproduce

1. Open a PS1 file
2. Waiting for extension activation
3. After a long time, it is still activated

### Visuals

<img width="784" alt="image" src="https://user-images.githubusercontent.com/87287779/189299350-97ef7593-49b1-48db-b11b-61db4ec46603.png">

**Comment by memory-yiyi** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/87287779/189677653-908daf26-03aa-4c5a-a0b7-4d23de7cd1a2.png">

**Comment by andschwa** [comment]
Hi,

Could you please provide more [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)?

Thanks!

Regarding shell integration, that is not yet supported in the extension, but it's on our upcoming list.

**Comment by memory-yiyi** [comment]
I'm sorry to tell you that the extension can't be activated, so you can't get logs through the extension, but you can get these.
![image](https://user-images.githubusercontent.com/87287779/189782636-4fb1d13f-463d-4ceb-ad3e-5b2e1d34cdb8.png)

**Comment by memory-yiyi** [comment]
It is worth noting that the same version of Linux can be activated, although I am not sure whether it is just because of system differences.
<img width="665" alt="image" src="https://user-images.githubusercontent.com/87287779/189783122-e8c2278f-8490-4ba8-8875-0be0e62352b4.png">

**Comment by andschwa** [comment]
The screenshot you've provided indicates that enough of the extension has started that you should be able to get much of those logs we're looking for, specifically the ones from PowerShell Editor Services.

**Comment by memory-yiyi** [comment]
Came out this time, hope it's useful.
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/9552809/EditorServices.log)

**Comment by memory-yiyi** [comment]
It is always in the process of activation. It was not like this a few weeks ago. It happened suddenly.
I tried to roll back the extended version, but it didn't solve the problem.

**Comment by memory-yiyi** [comment]
This is another bug of win11. The last time vs2022 had a similar fault. The problem has been solved by updating to 22622.598. Thank you for your answer.

**Comment by memory-yiyi** [comment]
I'm sorry to say that it only works once after the update. When I turn off the computer and turn it on again, it returns to the problem mentioned earlier.

**Comment by memory-yiyi** [comment]
I found a rule. At present, the normal startup of the extension must meet this condition:
- After turning on the computer, the first application to be opened must be a vscode extension to start normally.

In other words, the common operations listed below will cause the extension exception:
1. After starting up, open other desktop applications, and then start vscode.
2. Restart vscode.

The situation is somewhat complicated. I am not sure whether it is an extension problem, a vscode problem or an operating system problem.

**Comment by memory-yiyi** [comment]
Locked problem cause:
In the process of continuous troubleshooting, it was unexpectedly found that extension in safe mode works normally under any condition. Go to the normal environment. When there is no networking, the expansion works normally under any conditions.
Based on this, please check what problems the Internet has brought. I don't have relevant knowledge and can do nothing about it, so please.

**Comment by andschwa** [comment]
Hey @memory-yiyi, what are the contents of your PowerShell profiles? It seems like you have something running in your profile that's causing it to hang.

**Comment by memory-yiyi** [comment]
I have not modified the configuration file. I always use the default configuration. Through your reminder, we are checking whether it is due to module update. It may be caused by the module of SQL Server. After all, there will be no problem if the network is not connected

**Comment by memory-yiyi** [comment]
I think this may be the problem of module update.
There is no problem after reinstalling the system, which indicates that the plug-in is OK. Since the powershell was installed through the application store before, I did not care about the configuration of environment variables, which resulted in the inability to use nuget, that is, the module cannot be updated through it.
If the plug-in will update the module during initialization, please add an option to allow it to be selected. If not, please let me know so that I can continue the analysis.

**Comment by andschwa** [comment]
Hey you know, it doesn't auto-update modules but it _does_ try to query GitHub to see if PowerShell needs an update. I don't know if that's causing your issue, but you can try disabling it with the setting `powershell.promptToUpdatePowerShell` (and I just checked, despite the name, this does indeed skip checking if there's an update in the first place).

**Comment by memory-yiyi** [comment]
You know, I have executed Fresh Start.
This option has no effect and is almost the same configuration. Only Windows is updated (from 22622.601 to 22623.730) and the SQL server module is not installed.
If this is a problem with Windows, let's end the discussion. However, before we do, we would like you to check the relevant configuration, such as whether the plug-in works normally after the psmodulepath is not configured and the module is installed.
Because this situation really occurs after installing the sqlserver module, I have and only have this external module, and I know that I have not configured psmodulepath at all, that is, pwsh has not configured it, so it may use the powershell5 module.
If you are sure that this is not the problem, we can end the discussion, because I have executed Fresh Start, and the environment has been refreshed, so it is difficult to do research.

**Comment by andschwa** [comment]
Or, @memory-yiyi have you manually set `PSModulePath`?

**Comment by memory-yiyi** [comment]
<p>You know it's impossible. <code>code.exe</code> starts on icon.</p>
<p><code>PSModulePath</code> is not configured. As you can see:</p>
<blockquote>
<p>[DBG] Updated PSModulePath to: &lsquo;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;D:\Personal Tools\pwsh\Modules;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules;C:\Users\stardust\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\windowsapps\microsoft.powershell_7.2.6.0_x64__8wekyb3d8bbwe\Modules;c:\Users\stardust.vscode\extensions\ms-vscode.powershell-2022.8.5\modules&rsquo;</p>
</blockquote>
<p>It is worth noting this paragraph:</p>
<blockquote>
<p>C:\Users\stardust\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\windowsapps\microsoft.powershell_7.2.6.0_x64__8wekyb3d8bbwe\Modules;</p>
</blockquote>
<p>These are automatically configured (we will not talk about another one after vscode). But they came last, <code>Terminal.exe</code> or <code>pwsh.exe</code> expands at the beginning rather than at the end.</p>
<p>As you know, the priority of environment variables is higher than that of the following ones. If vscode places them behind, the module of powershell5 will be imported first, which is why the <code>Terminal.exe</code> looks normal.</p>

**Comment by andschwa** [comment]
@SeeminglyScience thinks we should try ruling something else out. Can you try using a version of PowerShell 7 installed _not_ through the Windows Store? The simplest thing to do would be to grab a zip from the [PowerShell releases](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.6), extract it, and then add a new additional exe in the VS Code settings to point there and try starting a session with that PowerShell.

**Comment by memory-yiyi** [comment]
I have reinstalled the system. At present, I use the winget command to install `pwsh`. I installed it at the system level. The expansion can be used normally, but the problem may still exist.

**Comment by andschwa** [comment]
Let us know!

**Comment by bryanlavalley-mil** [comment]
I think I am having the same issue. This is what I found.
![image](https://user-images.githubusercontent.com/117288568/199509512-f74f23fa-7864-479c-bf8c-49983f292bae.png)
Text in the middle of the command line doesn't look correct to me.

**Comment by andschwa** [comment]
@bryanlavalley-mil you've got `-WaitForDebugger` in yours, can you check your settings if you have `powershell.developer.editorServicesWaitForDebugger` enabled?

**Comment by memory-yiyi** [comment]
I think the configuration of `PSModulePath` is wrong. Why do the key ones come to the end? Shouldn't they be on the head?

**Comment by bryanlavalley-mil** [comment]
> @bryanlavalley-mil you've got `-WaitForDebugger` in yours, can you check your settings if you have `powershell.developer.editorServicesWaitForDebugger` enabled?

I sure did. Not sure when or how that was checked. I removed and update extension to 2022.10.0 and it still loads. Thanks!

**Comment by andschwa** [comment]
Ok @memory-yiyi I'm going to mark this as resolved as I think we narrowed the problem down to the Windows Store installation. Let me know if you're still having an issue!
