### ISSUE TITLE
ChannelClosedException: The channel has been closed - Intellisense and F8 stop working

### ISSUE THREAD

**Issue by dbrennand** [PowerShell/vscode-powershell#4177]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Hi,

I've been experiencing an issue where predictive intellisense and F8 (run line/code selection) stop working.
I've collected some diagnostic logs and noticed the following error:

```
2022-09-21 10:20:25.349 +01:00 [VRB] Could not write to output handler, perhaps serialization failed?
System.Threading.Channels.ChannelClosedException: The channel has been closed.
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at OmniSharp.Extensions.JsonRpc.OutputHandler.ProcessOutputStream(CancellationToken cancellationToken)
```

Once this error occurs in the logs, I have to restart the integrated terminal for it to work again.

I noticed a similar error reported in #3800 and when this error occurs, I also have the endless formatting behaviour, but also intellisense and F8 stop working for me. This issue occurs for me on the latest PowerShell extension and preview extension.

Logs to follow via email.

### PowerShell Version

```console
PowerShell Extension v2022.8.5
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.

PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.71.2
74b1f979648cc44d385a2286793c226e611f59e7
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.8.5
```

### Steps to Reproduce

1. Launch project in VSCode: `code .`
2. Open PowerShell script file and extension with integrated terminal is loaded.
3. All is working for a short time and then predictive intellisense and F8 stop working.

Apologies for the lack of repo steps 😞 but I'm really not sure what exactly is causing this issue.

### Logs

Logs sent via email.

**Comment by dbrennand** [comment]
Issue persists on latest preview `ms-vscode.powershell-preview@2022.9.0`

**Comment by andschwa** [comment]
Do you have any anti-virus running?

**Comment by dbrennand** [comment]
Apologies for the delayed response, yes there is anti-virus running on the device I'm experiencing this issue with.

**Comment by andschwa** [comment]
That would be my best guess. Can you temporarily disable it, especially any real-time setting, and see if it continues to repro? We have seen aggressive anti-virus software kill the process before.

**Comment by dbrennand** [comment]
> That would be my best guess. Can you temporarily disable it, especially any real-time setting, and see if it continues to repro? We have seen aggressive anti-virus software kill the process before.

Hmmm 🤔 OK, I've checked the event logs and I can't see any indication that the process is being blocked/killed. Unfortunately, I cannot disable it 🙁

**Comment by andschwa** [comment]
Oof, that's unfortunate. Do you have a similar machine without the AV that you can try to repro on? Or does your AV allow you to add folder exceptions?

**Comment by andschwa** [comment]
FWIW we also looked at the logs you emailed us (thank you) but unfortunately found nothing helpful. It seems like the last thing that happens is a code action is responded to by the server, but then a full two minutes go by and _then_ the channel closed exception happens.

**Comment by dbrennand** [comment]
Hi @andschwa

> FWIW we also looked at the logs you emailed us (thank you) but unfortunately found nothing helpful. It seems like the last thing that happens is a code action is responded to by the server, but then a full two minutes go by and _then_ the channel closed exception happens.

Thank you for taking a look at the logs I sent.

> Oof, that's unfortunate. Do you have a similar machine without the AV that you can try to repro on? Or does your AV allow you to add folder exceptions?

Unfortunately I do not, and I'm not permitted to add folder exceptions either. I think there is not much that can be done from your side. Thanks again for your time spent on this.
