### ISSUE TITLE
ERROR: Could not load file or assembly 'Microsoft.Identity.Client' (ExchangeOnlineManagement + PS 7.2.6)

### ISSUE THREAD

**Issue by robertcaretta** [PowerShell/vscode-powershell#4178]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When using this extension I get the error below. However if I run the same commands in a regular powershell 7.2 window (not VS Code) the code below runs fine.

----------------------------------
ERROR:
OperationStopped: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.41.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxx'.
----------------------------------

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.71.2
74b1f979648cc44d385a2286793c226e611f59e7
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.8.5
```

### Steps to Reproduce

Could you please test out this combination of tools?
1) VS Code 1.71.2
2) PowerShell Extension v2022.8.5 
3) Powershell 7.2.6
4) ExchangeOnlineManagement 3.0.0

Then try running these commands:
Import-Module ExchangeOnlineManagement
Connect-ExchangeOnline -InlineCredential
Connect-ExchangeOnline -CertificateThumbprint 'YOURTHUMB' -AppID 'YOURAPP' -Organization 'YOURORG'

----------------------------------
ERROR:
OperationStopped: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.41.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxx'.
----------------------------------

**Comment by mhokanson** [comment]
Bump

**Comment by Paxxi** [comment]
I ran into this as well yesterday and today I ran into it in a plain powershell terminal window as well.

In my case you cannot run `Connect-ExchangeOnline` after you have imported the `MicrosoftTeams` module, if you run it before importing the teams module everything works fine.

**Comment by andschwa** [comment]
@robertcaretta does @Paxxi's findings explain your original issue?

**Comment by robertcaretta** [comment]
I don't recall testing this with Teams. To be honest, I run into all kinds of oddities with modules that still seem to require 5.1. 
I guess my question would be has anyone else been able to reproduce the issue with just the items I listed?

**Comment by andschwa** [comment]
Yeah, unfortunately PowerShell 5.1 is restricted to using the GAC (Global Assembly Cache) on Windows, which is an old-fashioned way of loading DLLs and causes _loads_ of issues, since only one DLL of a name can be in the cache at a time. So modules can real easily have dependency collisions. PowerShell 7 uses an ALC (Assembly Load Context) that allows modules (such as PowerShell Editor Services, etc.) to isolate their dependencies from other modules.

**Comment by seanboltman** [comment]
> I ran into this as well yesterday and today I ran into it in a plain powershell terminal window as well.
> 
> In my case you cannot run `Connect-ExchangeOnline` after you have imported the `MicrosoftTeams` module, if you run it before importing the teams module everything works fine.

So I am getting this error as well, but I DO NOT have MicrosoftTeams module installed.  Get-InstalledModule reports:
3.0.0  ExchangeOnlineManagement and 1.11.0 PnP.PowerShell.  Nothing else is installed. Running Powershell 7.2.6.  This env was set up against latest VCCode  yesterday.

I get the same exact error as the poster on this line of code:

Connect-ExchangeOnline -UserPrincipalName sp_admin@geoengineers.com -Credential $cred

OperationStopped: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.41.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'.

Same exact code was functioning fine in Powershell 5.1.   which also has earlier version of ExchangeOnline powershell module 1.0.1.

So knowing I only have Powershell 7.2.6, ExchangeOnlineManagement 3.0.0, and PnP.PowerShell 1.11.0, what is the issue with this error?

**Comment by andschwa** [comment]
Yeah, unfortunately PnP.PowerShell also causes issues for PowerShell 5.1, https://github.com/PowerShell/vscode-powershell/issues/3510.

**Comment by cameronove** [comment]
Please reopen and respond - this is happening today just as described in OP.

**Comment by robertcaretta** [comment]
I'm still having issues with this using VS Code and PS 7.3.

**Comment by andschwa** [comment]
That sounds likely, the authors of those modules unfortunately need to implement proper `AssemblyLoadContext` classes and resolvers to isolate their dependencies from each other. From the last time I looked, at least one of those modules had a bug that was isolating only a single dependency.

**Comment by andschwa** [comment]
Found it: https://github.com/PowerShell/vscode-powershell/issues/3510#issuecomment-1438960031

PnP.PowerShell needs to update its ALC workaround to load `Microsoft.Identity.Client` from its dependency directory (as well as `Microsoft.ApplicationInsights`, and any other potentially conflicting dependency it ships).

**Comment by Stuipidsw3ltrd** [comment]
> I ran into this as well yesterday and today I ran into it in a plain powershell terminal window as well.
> 
> In my case you cannot run `Connect-ExchangeOnline` after you have imported the `MicrosoftTeams` module, if you run it before importing the teams module everything works fine.

Paxxi's answer saves my day

**Comment by Steltek** [comment]
> I ran into this as well yesterday and today I ran into it in a plain powershell terminal window as well.
> 
> In my case you cannot run `Connect-ExchangeOnline` after you have imported the `MicrosoftTeams` module, if you run it before importing the teams module everything works fine.

I've got the exact same issue, except it's the other way round for me. I cannot Connect-MicrosoftTeams after doing Connect-ExchangeOnline:

```
Import-Module: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.62.0.0, Culture=neutral,
PublicKeyToken=0a613f4dd989e8ae'. The located assembly's manifest definition does not match the assembly reference.
(0x80131040)
```

**Comment by JustinGrote** [comment]
@Steltek please see https://github.com/PowerShell/vscode-powershell/issues/4727#issuecomment-2158859368

This is for Az but the same for these cmdlets. They don't properly implement Assembly Load Context and that causes this problem. It's something we cannot fix here.
