### ISSUE TITLE
Intellisense not working for properties and methods of .net classes like in powershell_ise

### ISSUE THREAD

**Issue by DennisBergemann** [PowerShell/vscode-powershell#4179]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

**Hello all,**

unlike in poershell_ise it's not working to have intellisense for properties and methods of.net classes.

**Expected:
[System.Text.ASCIIEncoding]:: <== here opens the list of properties and methods**

if it's not so a big thing (requesting reflections) for you, i would like to have it as it is in powershell ise.

Thanks a lot

Best Regards

**Comment by SeeminglyScience** [comment]
Thanks for the report! This is a known issue being tracked in PowerShell/PowerShellEditorServices#1810. 

For a temporary workaround, you can press <kbd>Ctrl</kbd> + <kbd>Space</kbd> when it happens. If that just comes up saying "no completions" you can usually press <kbd>Esc</kbd> to close the completions window and then <kbd>Ctrl</kbd> + <kbd>Space</kbd> to trigger it again.

**Comment by DennisBergemann** [comment]
Thank you. I will give it a try next days
