### ISSUE TITLE
Debugger should retry until extension loads or give error when it times out

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#418]
### System Details

- Operating system name and version: Windows 10 Enterprise
- VS Code version: 1.8.1
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Hi,

Today I've noticed an issue where a debug adapter terminates immediately when I try to debug one of my scripts. Interestingly, the popups regarding termination repeats twice, and if you look into the 'Developer Tools' console there's this:
messageService.ts:126Debug adapter process has terminated unexpectedlye.doShow @ messageService.ts:126

Neither EditorServices.log nor vscode-powershell.log logs for the session have any mention of the issue.

While trying to figure out a reliable repro, I discovered that this issue occurs if VSCode is started and debugging is initiated while PowerShell is being loaded:
![image](https://cloud.githubusercontent.com/assets/18121861/21542413/2b45f2ac-cdc6-11e6-9d26-8482d3516ecf.png)

If I wait for loading to finish and start debugging afterwards, all goes fine. Is it possible to add some logic so that VSCode would wait for PowerShell to finish loading instead of crashing?

Thanks!

### Attached Logs
I haven't attached the logs as there are no errors and it has some sensitive data. If needed, I can send it over the email.

**Comment by daviwil** [comment]
Thanks @Glober777! This is part of the reason why I added the loading indicator, to make it more obvious when the extension hasn't finished loading yet.  The missing piece here is some clear indication from the debugger that the PowerShell extension is still loading.  Unfortunately they don't give me a way to return an explicit error message (or I haven't found a way yet, at least).  I'll keep looking into it!
