### ISSUE TITLE
Set default location for Powershell extension terminal window

### ISSUE THREAD

**Issue by krishankanumuri** [PowerShell/vscode-powershell#4181]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Currently whenever powershell extensions starts it opens a terminal window in VS Code editor area, I would like a setting to set the default location for terminal windows e.g., in editor area, in Terminal tab.

This will help optimize the workflow where users are configured to open terminal in lower panel instead of in Editor window. Currently It requires manual intervention to move the extension terminal window to lower panel.

**Comment by andschwa** [comment]
Have you tried just hiding it at startup? Then you can put it (and all the other VS Code terminals) wherever you want using their APIs. It's this setting: `powershell.integratedConsole.showOnStartup`.

**Comment by code2mars** [comment]
Hi @andschwa, seems ```powershell.integratedConsole.showOnStartup``` is disabled. I tried enabling this setting, but I see no difference. Whenever Powershell extension is initialized, it starts the terminal in editor area. From the description I understand when ```showOnStartup```setting is disabled Intergrated powershell terminal window should not be visible and I need to run show terminal command but that doesn't seem to be the case.


Basically, what I am looking for is some sort of setting like ```powershell.integratedConsole.startupLocation``` and this setting accepts like Terminal area or in Editor area.

Please let me know if I can provide any further details/logs.

**Comment by andschwa** [comment]
The `showOnStartup` setting should be working to hide the terminal on startup, please let me know if that's still the case with the latest version.

**Comment by Peter-Schneider** [comment]
I had the same issue. For me the setting ```"powershell.integratedConsole.startInBackground": true``` worked.

**Comment by krishankanumuri** [comment]
> I had the same issue. For me the setting ```"powershell.integratedConsole.startInBackground": true``` worked.

@Peter-Schneider yes, but I want powershell terminal session to be started in lower panel.

**Comment by krishankanumuri** [comment]
> The `showOnStartup` setting should be working to hide the terminal on startup, please let me know if that's still the case with the latest version.

Thanks. I want the terminal to be visible but just start in lower panel not in main workspace.

**Comment by andschwa** [comment]
Right now the default should be with the panel position set to lower. Once created you can move it around as you wish, but we're not currently exposing any settings for the location of the terminal. We'll think about it though!

**Comment by krishankanumuri** [comment]
> Right now the default should be with the panel position set to lower. Once created you can move it around as you wish, but we're not currently exposing any settings for the location of the terminal. We'll think about it though!

Thanks @andschwa, if this is something not planned please close the issue.

**Comment by krishankanumuri** [comment]
Hi @andschwa, I have created a PR for this issue. Please review and provide feedback.

This is my first time working with VS code extension and typescript, so apologies if my changes do not meet coding standards. But I am happy to update it based on feedback.

**Comment by andschwa** [comment]
You did great! I'm out at a conference right now but I looked briefly and liked it. When I'm back at work I'll give it a test and review and get it merged, thank you!
