### ISSUE TITLE
Debugging is broken in v2022.9.0

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/vscode-powershell#4185]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

After upgrading extension to latest preview version v2022.9.0 I can't start interactive debugging or attach to existing PowerShell session.

**Downgrading extension to v2022.8.5 solves the problem.**

*launch.json:*
```json
{
    "name": "PowerShell: Interactive Session",
    "type": "PowerShell",
    "request": "launch"
},
{
    "name": "PowerShell Attach to Host Process",
    "type": "PowerShell",
    "request": "attach",
    "runspaceId": 1
},
{
    "name": "PowerShell Attach Interactive Session Runspace",
    "type": "PowerShell",
    "request": "attach",
    "processId": "current"
}
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.72.0-insider
835d39cfac9ede6c7c90678c8d6c3d4d0171ed6d
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2022.9.0
TylerLeonhardt.vscode-inline-values-powershell@0.0.6
```

### Steps to Reproduce

1. Upgrade extension to latest preview version v2022.9.0.
2. Start debugging interactive session or attach to existing PowerShell session

### Visuals

Interactive debugging:
![image](https://user-images.githubusercontent.com/16168755/192750291-07039046-18e0-4896-9dbc-c1a8184fb886.png)

Attaching to existing session:
![image](https://user-images.githubusercontent.com/16168755/192750394-bc48a60d-6d53-40bc-9594-e40aebe243dc.png)

### Logs

[20220928T120302.zip](https://github.com/PowerShell/vscode-powershell/files/9663815/20220928T120302.zip)

**Comment by andschwa** [comment]
Good find! I'll ping you on Discord to test something for me.
