### ISSUE TITLE
Running Visual Studio Code as administrator - Powershell extension is not running with admin rights

### ISSUE THREAD

**Issue by PeterBizz** [PowerShell/vscode-powershell#4190]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Running Visual studio as administrator.
Starting powershell terminal 
Enter Set-ExecutionPolicy unrestricted

PS C:\Users\peter> set-executionpolicy unrestricted
Set-ExecutionPolicy: Access to the path 'C:\Program Files\PowerShell\7\powershell.config.json' is denied.
To change the execution policy for the default (LocalMachine) scope, start PowerShell with the "Run as administrator" option. To change the execution policy for the current user, run "Set-ExecutionPolicy -Scope CurrentUser".

Obviously not running as administrator

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.71.2
74b1f979648cc44d385a2286793c226e611f59e7
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.8.5
```

### Steps to Reproduce

Running Visual studio as administrator. (started with runas). 
Current user is in administrator group

Starting powershell terminal 
Enter Set-ExecutionPolicy unrestricted
Administrator rights needed.

**Comment by andschwa** [comment]
Well, that's odd. Do other integrated terminals within VS Code start as an administrator if Code itself did? If so, then it's our problem, if not, then it's upstream with Code.

**Comment by PeterBizz** [comment]
Problem disappeared - user error I think.
