### ISSUE TITLE
PowerShell Extension Terminal does not return commands back to display 

### ISSUE THREAD

**Issue by baywack** [PowerShell/vscode-powershell#4204]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Unable to determine the root cause.  However it happens numerous times daily.  PowerShell terminal will not return value back to display.  Restarting VSCode fixes the issue until the issue appears again.

When the issue happens here is what is noted (any command in terminal does this).

**Example**
C:\users...\scripts> $PSVersionTable
returns nothing back to display

**Example**
C:\users...\scripts> $PSVersionTable | write-host
System.Collections.Hashtable
Write-host returns data back to terminal display - in this example "System.Collections.Hashtable"

### PowerShell Version

```console
Only way I was able to run this command was using out-gridview

PSVersion - 5.1.19041.1682
PSEdition - Desktop
PSCompatibleVersions - {1.0, 2.0, 3.0, 4.0...}
BuildVersion - 10.0.19041.1682
CLRVersion - 4.0.30319.42000
WSManStackVersion - 3.0
PSRemotingProtocolVersion - 2.3
SerializationVersion - 1.1.0.1
```

### Visual Studio Code Version

```console
1.71.2
74b1f979648cc44d385a2286793c226e611f59e7
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.8.5
```

### Steps to Reproduce

Unable to determine the root cause.  However it happens numerous times daily.  PowerShell terminal will not return value back to display.  Restarting VSCode fixes the issue until the issue appears again.

**Comment by andschwa** [comment]
@SeeminglyScience this looks like https://github.com/PowerShell/vscode-powershell/issues/3991

**Comment by andschwa** [comment]
@baywack can you use PowerShell 7? If this is the same as the issue I just linked, it's only affecting PowerShell 5.1.

**Comment by baywack** [comment]
@andschwa I can confirm PSVersion 7.2.6 doesn't seem to have the same issue so far today.  I can confirm that running as admin or regular user - same results as #3991.  Assuming it's the same bug looking through the notes.

**Comment by andschwa** [comment]
Thanks for the confirmation @baywack, I'm going to mark this as a duplicate. Appreciate it!
