### ISSUE TITLE
Issue with PowerCLI in Powershell Extension - Intellisense

### ISSUE THREAD

**Issue by cajunitalian** [PowerShell/vscode-powershell#422]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.8.1
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.0.10240.17146
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

### Issue Description

Unable to use intellisense w/ PowerCLI Module Cmdlets. See my screenshot, you'll see the PowerCLI Module path is clearly in $env:PSModulePath (C:\VMware\Infra\PowerCLI\Modules)*

*Yes, I am writing in a .ps1 file. Powershell is working, just not intellisense for that module.

### Attached Screenshots
Here's an example of the module paths, showing that $env is good

![image](https://cloud.githubusercontent.com/assets/1809840/21782963/efd4f6b0-d67a-11e6-82e4-680b325c1bf9.png)

Here's an example of Connect-VIServer, you can see it's not working.

![image](https://cloud.githubusercontent.com/assets/1809840/21782975/fc7d0ae2-d67a-11e6-8605-9b8dcf9170ff.png)

**Comment by daviwil** [comment]
Hey Matteo, you might need to load the module into the session before IntelliSense appears.  For now the best way to do this is add `Import-Module PowerCLI` to your VS Code profile:

`$HOME\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1`

After adding that, restart VS Code and you should get IntelliSense for the module.

**Comment by cajunitalian** [comment]
That profile doesn't exist - how can I create it?  Do I just manually build it?

I know in typical POSH you just run the commands but the integrated terminal in VSC is using my local logged in AD Profile which has it's own POSH Profile.

*Micorsoft.Powershell_profile.ps1

**Comment by rkeithhill** [comment]
Create it like so:
```
notepad $home\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1
```
Notepad should ask you if you want to create the file.

**Comment by cajunitalian** [comment]
That did the trick.  Thanks guys, trying to convert from heavy VS2016 over the VSC
