### ISSUE TITLE
PowerShell Integrated Console, loading "Core" version, not the "Desktop" version

### ISSUE THREAD

**Issue by mcc85s** [PowerShell/vscode-powershell#4224]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Greetings (**PowerShell + VSCode**) Team,

Today is **Saturday, October 22nd 2022** @ about **12:42pm EST**.
I've written a (document/PDF) that has all of the details of this [bug report](https://www.github.com/mcc85s/FightingEntropy/blob/main/Docs/2022_1022-(Bug_Report).pdf).

I'm looking at the options in the prerequisites, and though I'm certain that this issue has been reported before...? 

I am making an indication that I have followed the suggestions of those previously reported issues, and yet, the issue remains.

I've decided to go ahead and draft this [PDF file](https://www.github.com/mcc85s/FightingEntropy/blob/main/Docs/2022_1022-(Bug_Report).pdf) (it is the same file in the link above).

Regardless of the circumstances...? I still really enjoy using **Visual Studio Code**, basically all the time, to do various things related to _programming_, _document editing_, or just _general, all-around tomfoolery_ (such as an excerpt in the PDF I wrote).

Mainly because **Tyler Leonhardt** convinced me to give it a real shot. He was like:

| Guy | Statement |
|:----|:----|
| **Tyler** | Hey dude. |
| **Me** | Sup...? |
| **Tyler** | **PowerShell ISE** isn't getting anymore upgrades... | 
| **Me** | Nah...? | 
| **Tyler** | Nah... |
| **Me** | Well, bummer. =`( |
| **Tyler** | Hey, don't fret... You should totally use **Visual Studio Code**, dude. |
| **Me** | Yeh...? |
| **Tyler** | Yeh. It's what the experts use, these days. |
| **Me** | Oh really...? |
| **Tyler** | Yeh. |
| **Me** | Well, if that's what the experts use these days, then... |
| **Tyler** | ...you probably wanna use **Visual Studio Code** now, huh...? |
| **Me** | Yeh. |
| **Tyler** | Good~! You should. |
| **Me** | Fine~! I will~! |
| **Tyler** | Glad to hear it~! |
| **Me** | It'll probably be my new favorite thing to use at some point... |

And then, that is exactly what happened.
I had to create a brand-new, never before made, color theme for **Visual Studio Code** that I call [BossMode](https://github.com/mcc85s/FightingEntropy/blob/main/Functions/Install-BossMode.ps1).

Once I did that...? I've been using it ever since.

Anyway... whenever I am NOT partaking in _general, all-around tomfoolery_...? 
I make videos that feature **Visual Studio Code**, like:
| Date | Name | Url |
|:-----|:-----|:-----|
| 03/09/21 | A Deep Dive: PowerShell and XAML       | https://youtu.be/NK4NuQrraCI |
| 06/27/21 | Advanced System Administration Lab     | https://youtu.be/xgffIccX1eg |
| 09/23/21 | PowerShell Deployment FE Wizard        | https://youtu.be/lZX5fAgczz0 |
| 10/20/21 | Advanced Domain Controller Promotion   | https://youtu.be/O8A2PDfQOBs |
| 12/04/21 | [FightingEntropy(π)][FEInfrastructure] | https://youtu.be/6yQr06_rA4I |
| 04/05/22 | Wireless Network Scanning Utility      | https://youtu.be/35EabWfh8dQ |

The first entry was BEFORE I was using **Visual Studio Code** on a _consistent_ basis.
The rest of them are essentially me using it somehow. It's not all of em, either.

Look. Sometimes in life, you just gotta call it like you see it...
**Visual Studio Code**, is hands down... the best there is.
There's really no other way to slice it...

| Date | Name | Url |
|:-----|:-----|:-----|
| 09/26/22 | God Mode Cursor (1) | https://youtu.be/tW80Zj_H6Fw |
| 10/04/22 | God Mode Cursor (2) | https://youtu.be/dU_5rdVkCD8 |

AND, whoever this mysterious entity is behind that god mode cursor...? 
Keep up the good work.

**PowerShell and Visual Studio Code** just so happen to be, the best there is.

MCC/SDP

### PowerShell Version

```console
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS Prompt:\> code -version
Warning: 'e' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'i' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'o' is not in the list of known options, but still passed to Electron/Chromium.
1.72.2
d045a5eda657f4d7b676dedbfa7aab8207f8a075
x64
PS Prompt:\>
```

### Extension Version

```console
PS Prompt:\> code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2022.10.0

PS Prompt:\>
```

### Steps to Reproduce

1) Open Visual Studio Code
2) Run any code that uses my module
3) Oops... this PowerShell console thinks you're a real menace to society, and has decided to throw an error.

### Visuals

[Screenshots of the PDF](https://drive.google.com/drive/folders/1cP4VjlVtchCjmulzT-6lazbDZQ2lKYrG)

**Comment by andschwa** [comment]
Hey there, can you try clicking the language status icon and choosing Desktop instead of Core? See here: https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#how-do-i-change-the-powershell-version

**Comment by mcc85s** [comment]
I was able to switch to Windows PowerShell after reading that particular
post regarding the "{ } | Language" menu.

Thank you.

**Comment by andschwa** [comment]
Awesome!
