### ISSUE TITLE
Debug after update not work 

### ISSUE THREAD

**Issue by DonRP** [PowerShell/vscode-powershell#4229]
### Prerequisites

- [ ] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

why this first work and now not (after update)?

(launch.json)
```json
"version": "0.2.0",
"configurations": [
    {
        "name": "Ren'Py: Setup",
        "type": "PowerShell",
        "request": "launch",
        "script": "echo \"test\" > .renpy-sdk",
    },
]
```

### PowerShell Version

```console
PowerShell 5.1
```

### Visual Studio Code Version

```console
last
```

### Extension Version

```console
v2022.10.0
```

### Steps to Reproduce

run this launch.json:
```json
"version": "0.2.0",
"configurations": [
    {
        "name": "Ren'Py: Setup",
        "type": "PowerShell",
        "request": "launch",
        "script": "echo \"test\" > .renpy-sdk",
    },
]
```

### Visuals

![image](https://user-images.githubusercontent.com/67595890/197841853-06dc1506-7ea1-4f68-93e6-871653de7857.png)

**Comment by andschwa** [comment]
Duplicate of https://github.com/PowerShell/vscode-powershell/issues/4223, just fixed it, working on getting a preview out today.
