### ISSUE TITLE
Extension fails to start - timed out waiting for session file

### ISSUE THREAD

**Issue by JTUoB** [PowerShell/vscode-powershell#4245]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I'm trying to open the extension, but every time it fails with the below log output after 4 minutes. This is on a fresh install of VS Code, Pwsh 7 and the Pwsh extension. I've checked the file path for the session file and it doesn't exist. I also immediately get an error stating that the terminal process that starts .dotnet\tools\pwsh.exe has terminated with exit code 1.

04/11/2022 16:55:36 [NORMAL] - pwsh.exe started.

04/11/2022 16:55:36 [NORMAL] - Waiting for session file...

04/11/2022 16:59:40 [NORMAL] - Timed out waiting for session file to appear!

04/11/2022 16:59:40 [NORMAL] - PowerShell process failed to start.

04/11/2022 16:59:40 [ERROR] - PowerShell process failed to start: 

04/11/2022 16:59:40 [ERROR] - Error: Timed out waiting for session file to appear!

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.73.0
8fa188b2b301d36553cbc9ce1b0a146ccb93351f
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.10.0
```

### Steps to Reproduce

Open VS Code, open any .ps1 file, error occurs every time

### Logs

Logs folder doesn't exist, command palette 'open powershell extension logs folder' does nothing, even with log level set to diagnostic

**Comment by andschwa** [comment]
There seem to be issues with the `dotnet` installed version of PowerShell. Can you install it another way? You can use the `powershell.powerShellAdditionalExePaths` setting to point the extension to another `pwsh.exe`.

**Comment by JTUoB** [comment]
Thanks for your quick response @andschwa. I've changed the additional exe paths to include the normal pwsh.exe path (key=PowerShell, value=C:\Program Files\PowerShell\7\pwsh.exe), but still getting the below output when the extension starts up which shows it trying to start the .dotnet version:

05/11/2022 12:23:01 [NORMAL] - Visual Studio Code v1.73.0 64-bit

05/11/2022 12:23:01 [NORMAL] - PowerShell Extension v2022.10.0

05/11/2022 12:23:01 [NORMAL] - Operating System: Windows 64-bit

05/11/2022 12:23:02 [NORMAL] - Language server starting --

05/11/2022 12:23:02 [NORMAL] -     PowerShell executable: C:\Users\zg19442\.dotnet\tools\pwsh.exe
...

I've also set terminal.integrated.shell.windows to the same path and the profile doesn't have a path specified. I can't find any other extension or terminal settings to affect the path chosen at that step? It seems to occur before PowerShellEditorServices module is loaded

**Comment by JTUoB** [comment]
I also noticed trying today that the extension opens a terminal (which then closes quickly) saying it can't find the System.Runtime 4.2.2.0 dll. Any versions I can find on my system are 4.0.30319. Managed to grab the below before the terminal closed:

Import-Module : Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
At line:1 char:1
+ Import-Module 'c:\Users\zg19442\.vscode\extensions\ms-vscode.powershe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

Looks like the .dotnet version of PowerShell is a V6 hanging over from uninstall. I tried renaming the \.dotnet\tools\pwsh.exe and the extension picked the correct version and everything's working. Looks to be a problem with the V6 uninstall/upgrade to V7 process (whichever it is I did) leaving things lying around.

**Comment by andschwa** [comment]
Hey @JTUoB, just FYI `terminal.integrated.shell.windows` won't have any effect on the PowerShell extension. What you're looking for once you've added to `powershell.powerShellAdditionalExePaths` is to either use the "Show Session Menu" command from the palette (or click the PowerShell extension icon in the bottom right corner), or set `powershell.powerShellDefaultVersion` to the name of what you added.

**Comment by JTUoB** [comment]
Yes, I was just trying anything PowerShell I could find to get it to work. I did change the default version as well, but the only thing that worked was deleting/renaming the .dotnet version of the pwsh.exe. All good now!

**Comment by andschwa** [comment]
Oh good! Yeah I'm not sure why the `dotnet` version is so touchy, glad it's all worked out for you!
