### ISSUE TITLE
Variables used in paths do not get "document highlighted" correctly due to bad extents

### ISSUE THREAD

**Issue by Leon99** [PowerShell/vscode-powershell#425]
Example:

![image](https://cloud.githubusercontent.com/assets/6840381/21870591/393f2a5e-d8b1-11e6-8aa7-afcc52adb3b4.png)

Though 

![image](https://cloud.githubusercontent.com/assets/6840381/21870765/16405464-d8b2-11e6-8622-6307dc28291d.png)

Code:
``````
$thisDirectory = (Split-Path -parent $MyInvocation.MyCommand.Definition)

. $thisDirectory\functions\Write-FunctionCallLogMessage.ps1
``````

**Comment by rkeithhill** [comment]
Where is the variable (presumably `$thisDirectory`) not being recognized? Syntax colorization, IntelliSense, during debug?  Also, can you provide version information of PowerShell, VSCode and the PowerShell extension?  Thanks.

**Comment by Leon99** [comment]
Syntax colorization and 'go to definition'.
PSExt: 0.8.0, PS: 5.1
VSC: 1.8.1

**Comment by rkeithhill** [comment]
I can't repro the syntax colorization issue:

![image](https://cloud.githubusercontent.com/assets/5177512/21879579/e712a4cc-d856-11e6-9328-99dd55dbf728.png)

But I can repro the issue with go to definition on the variable.

**Comment by Leon99** [comment]
The main difference between your and my screenshots is that in my screenshot the cursor is positioned on the variable, but the whole expression is highlighted with a background. In your screenshot the cursor is positioned on the next line, therefore I don't expect to see any highlighting.

**Comment by daviwil** [comment]
That's a different thing, it's symbol occurrence highlighting.  We might have a bug in judging the extents of the variable, it would affect both Go to Definition and occurrence highlights.  I'll take a look at it, thanks!

**Comment by rjmholt** [comment]
Closing as defunct
