### ISSUE TITLE
Wrong indent for pipelines

### ISSUE THREAD

**Issue by aelij** [PowerShell/vscode-powershell#4252]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

PowerShell allows line breaks in pipelines without a backtick. I would expect the editor to indent it as if the backtick was present.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.73.0
8fa188b2b301d36553cbc9ce1b0a146ccb93351f
```

### Extension Version

```console
ms-vscode.powershell@2022.10.0
```

### Steps to Reproduce

Expected:

```powershell
Get-ChildItem |
  Select-Object Name

Get-ChildItem | `
  Select-Object Name
```
 
Actual:

```powershell
Get-ChildItem |
Select-Object Name

Get-ChildItem | `
  Select-Object Name
```

**Comment by aelij** [comment]
`Invoke-Formatter` works as expected

```powershell
> Invoke-Formatter -ScriptDefinition 'Get-ChildItem |
>> Select-Object Name'
Get-ChildItem |
    Select-Object Name
```

**Comment by RansomVO** [comment]
I have a similar issue which started after I did an update last week. In my case formatting is ignoring the Code Formatting settings:
- New Line After Close Brace
- New Line After Open Brace
- Open Brace On Same Line
And it reformats my scripts completely.
![formatter](https://user-images.githubusercontent.com/30580736/203657262-ba41a212-8b0a-474a-90d9-9c3f741ddb04.png)

**Comment by aelij** [comment]
@RansomVO I suggest you open a separate issue for this

**Comment by andschwa** [comment]
@aelij What do you have your `powershell.codeFormatting.preset` set to? If it's anything other than `Custom` (the default) then my understanding is that it will override the other settings.

**Comment by andschwa** [comment]
@aelij oh, re-reading your issue, I think for your expected scenario you just need to configure `powershell.codeFormatting.pipelineIndentationStyle`. The default (and I don't know why) is `NoIndentation` but if you set it to `IncreaseIndentationForFirstPipeline` it will (mostly) do what you want. In testing, though, I discovered that the second block of code will double-indent, and I'm not sure why, but probably because scripts aren't really expected to use `| <backtick>` at the end of a line since both `|` and `<backtick>` are line-continuations in PowerShell scripts.

**Comment by aelij** [comment]
@andschwa Can we change the default? It doesn't make sense IMO
