### ISSUE TITLE
F5 with script containing single quotes results in 'not recognized as a ....' error

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/vscode-powershell#4269]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Following #4238, anytime an argument is quoted, it needs to have existing quotes escaped.  On Windows, single quotes can appear in the file name/file path, but double quotes cannot, but on 'nix, both can.

I created a script with quotes in the file name (this is not at all unusual for me), added something simple to the script file, and then pressed F5 to attempt to run it, and received an error that the path was invalid.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.11.0        
ms-vscode.powershell-preview@2022.11.0
```

### Steps to Reproduce

Create script with single quotes and press F5 to run.

### Visuals

![image](https://user-images.githubusercontent.com/26179051/202543963-7eddaf2a-1e01-4cdf-a044-b632e0f53f5d.png)

**Comment by andschwa** [comment]
You'll need to escape the single quotes. We had to switch from double to single quotes to avoid interpolating `$foo` as a PowerShell variable, and single quotes is what PowerShell also uses when tab-completing so the semantics are more in line with PowerShell now.

**Comment by andschwa** [comment]
Err, I guess with F5 we'll need to escape the single quotes.

**Comment by andschwa** [comment]
@SeeminglyScience I swear we were running this through an escaper at one point?

**Comment by msftrncs** [comment]
Ideally PowerShell would provide an argument escaper, as it has one as part of the Completer, but I am not sure it has a public interface.

**Comment by andschwa** [comment]
Ok so once upon a time we did run this through some amount of escaping per https://github.com/PowerShell/PowerShellEditorServices/pull/1611. In fact, there's a comment that "For a saved file we just execute its path (after escaping it)." But we stopped escaping it! I think the course of action here is to continue to single-quote the file, so we don't have to escape anything _except_ single quotes.
