### ISSUE TITLE
Ctrl+Alt+ keybindings should not be used by default under Windows.

### ISSUE THREAD

**Issue by dustinmoris** [PowerShell/vscode-powershell#427]
The PowerShell keybindings offend the convention that Ctrl+Alt+ should not be used under Windows by default:

![image](https://cloud.githubusercontent.com/assets/4580714/21887565/569a208e-d8b8-11e6-83ed-72bd8a385502.png)

This is the warning from the developer tools in VS Code under Windows.

The exact offender is this one:

```
{ "key": "ctrl+alt+e",            "command": "PowerShell.ExpandAlias",
                                     "when": "editorTextFocus && editorLangId == 'powershell'" }
```

**Comment by daviwil** [comment]
It's more of a warning than an error so it can be safely ignored.  That said, we haven't come up with a better unused key combination for this command, any suggestions?

**Comment by dustinmoris** [comment]
Hi, I just checked and Shift+Alt+E is a free keybinding and Shift is just above Ctrl, so the muscle memory in our hand should quickly get used to Shift+Alt+E after a change :)

**Comment by daviwil** [comment]
Ahhh great idea!  I'll change it to that.
