### ISSUE TITLE
v2022.11.1-preview butchers terminal prompt using WinPS 5.1

### ISSUE THREAD

**Issue by Hetshu** [PowerShell/vscode-powershell#4279]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Powershell Extension terminal prompt shows escape characters:

![image](https://user-images.githubusercontent.com/50502257/203252668-85571416-8883-4c2d-aee4-c7f7803ee397.png)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2022.11.1
```

### Steps to Reproduce

Open a powershell script to activate the extension, switch to WinPS 5.1 and watch the prompt

**Comment by PrzemyslawKlys** [comment]
Can confirm:

![image](https://user-images.githubusercontent.com/15063294/203297241-54effdbf-8b4d-45f4-8fb2-ff215d80f228.png)

**Comment by DarkLite1** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/10828570/203341307-c6b7dc8b-bc3c-4d7a-8a24-c075a99ccfa9.png)

**Comment by andschwa** [comment]
Is shell integration supposed to work in PowerShell 5.1 in the first place? If not, I'll have to put a guard around it.

**Comment by andschwa** [comment]
> Note: On Windows, you'll need PowerShell 7 (pwsh) for shell integration support.

Ahh.

**Comment by MrFly72** [comment]
Can confirm, too.
I have to go back to Production release, as I need to change between 5.1 and 7.x quite frequently as I have some old PSSnappin-Sh*t....

**Comment by andschwa** [comment]
@MrFly72 we've got a fix at the ready, and we got it upstream too! Sorry about the temporary inconvenience, but won't be a problem next preview!
