### ISSUE TITLE
Integrated Terminal icons break positioning after `ClearScreen`

### ISSUE THREAD

**Issue by ninmonkey** [PowerShell/vscode-powershell#4280]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Terminal Integration icons lose their positioning after clearing screen. `ctrl+l` . 
I have the default binding where the PSReadLine function is `ClearScreen`

![image](https://user-images.githubusercontent.com/3892031/203416451-6e5ff89c-27f0-48b1-bcab-6f9e6dea567c.png)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2022.11.1
```

### Steps to Reproduce

- Open a fresh `Powershell Extension` terminal 
- Enter a few commands
- Hit `ctrl+l`
- scroll up and down

It seems to stay broken until you reload

### Visuals

![vscode ┐ PsIntegratedTerm ┐ jumping offsets - 2022-10e3](https://user-images.githubusercontent.com/3892031/203415319-dacefecf-e3bc-4605-a5c5-016665380175.gif)

**Comment by andschwa** [comment]
Does this repro outside of the extension terminal?

**Comment by ninmonkey** [comment]
> Does this repro outside of the extension terminal?

Yes.

I noticed something new: When it's broken, some jumps of the `ctrl+up/down` hotkeys goes out of order.
If you can see this horizontal gray bar

![image](https://user-images.githubusercontent.com/3892031/203467382-40748baa-7ba3-46e0-9261-c704d93dc740.png)

Watch it move on the  bottom right corner of the gif

![vscode ┐ PsIntegratedTerm ┐ jumping offsets - B - 2022-10e2](https://user-images.githubusercontent.com/3892031/203465925-72a9a116-f076-4356-b261-761976b8e99a.gif)

**Comment by andschwa** [comment]
Ahh, good find, thank you. I imagine we're doing something in our clear screen implementation that acts like a command, but I certainly missed adding an escape sequence there.

**Comment by andschwa** [comment]
Yeah, in Code's extension terminal, I only get the behavior you see when I sets `terminal.integrated.allowChords`, which is allowing the `Ctrl-L` through to PSReadLine; but that setting is _not_ affecting the Extension Terminal. So what does VS Code do when it intercepts that...(and what are we doing either way?)

**Comment by andschwa** [comment]
<img width="641" alt="Screenshot 2022-11-23 at 11 53 03 AM" src="https://user-images.githubusercontent.com/2226434/203634838-c9f2e6a1-d10c-4554-b0bc-14ccc9f15630.png">

Are you _sure_ you don't see this in a regular VS Code integrated terminal? I seem to be able to repro it there. That's using PowerShell 7.3 on Windows, not in the extension but in a Code integrated terminal, hitting Ctrl-L, and the dots are losing their locations.

**Comment by andschwa** [comment]
> Yes. This new gif is from the non-extension term.

Oh! I read this wrong. So it _isn't_ an extension terminal issue. Ok! I can work with @Tyriar and @SeeminglyScience to figure out how we can fix this. My bet sincePSReadLine's `ClearScreen` [implementation](https://github.com/PowerShell/PSReadLine/blob/dc38b451bee4bdf07f7200026be02516807faa09/PSReadLine/Movement.cs#L506-L511) is sending the clear screen terminal sequence and then invoking the prompt, we're "missing" that prompt invocation, since Code's shell integration wraps `PSConsoleHostReadLine` to send it, and in our host we add it in our own `InvokeReadLine` wrapper.

I suppose we could intercept `Ctrl-L` somehow, or override `ClearScreen`, either way we need to know that the user asked PSReadLine to clear the screen and then handle updating shell integration.

**Comment by andschwa** [comment]
@ninmonkey can you execute:

```powershell
Set-PSReadLineKeyHandler -Chord "Ctrl+l" -ScriptBlock {
	[Console]::Write("$([char]0x1b)]633;C`a")
	[Microsoft.PowerShell.PSConsoleReadLine]::ClearScreen()
}
```

and then see if everything works as expected with `Ctrl+l`? Seems to on my end!

**Comment by Tyriar** [comment]
We're tracking this in https://github.com/microsoft/vscode/issues/166864, it's not clear to me whether this is a pwsh, conpty or our issue. I believe we clear the decorations when certain erase in display sequences happen.

**Comment by ninmonkey** [comment]
Weird, I have force clear off. here's some settings

| settings.json | . |
|---:|---|
| terminal.integrated.persistentSessionReviveProcess | <a href="https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-process-reconnection">never</a> |
| terminal.integrated.allowChords | true |
| terminal.integrated.sendKeybindingsToShell | true |
| powershell.integratedConsole.forceClearScrollbackBuffer | false |

### New debug tool -- Easier virtual environments 

Recent patches make it **a lot** easier to create mini-virtual environments, without doing anything crazy. 

```ps1
[object[]]$c_args = '--extensions-dir', $addons_dir, '--user-data-dir', $user_data_dir, '--profile', 'pwsh-debug', '--add', (Get-Item $Path)
& code.cmd @c_args
```



>  don't have a custom ClearScreen implementation any more, unl
> unless it lintercepts that...(and what are we doing either way?)

The description mentions the language server, maybe that's causing unexpected behavior?

> Use the vscode API to clear the terminal since that's the only reliable way to clear the scrollback buffer. **Turn this on if you're use to 'Clear-Host' clearing scroll history as `wellclear-terminal-via-lsp`**.

I don't remember exactly why I have `terminal.integrated.sendKeybindingsToShell` enabled, my guess is it had to do with getting console keybings to work. Or it could be from when terminal panes were first movable into editor tabs -- Some or most of those aren't required anymore

- `alt+enter` , `shift+enter`, `ctrl+enter`
- `ctrl+c`, `ctrl+v` *in the past you had to prevent VSCode's binding for filepaths had non-ascii runes. Also when pasting multiple lines as a single command


## What to Test? 

Do you recommend anything I can test for?, for this issue or others? I can get more data on potential errors or traces and log captures -- If I know what to look for. 

- Do you know how to capture the ansi escapes being sent to the term?
- I wanted to dig into them for clues on whether the prompt-location-ansi-escapes were being generated as expected, or if it was coming from another level

So I'm wondering where to start, I think

- I'd need to build the dotnet c# Pwsh SDK, to be able to inspect what PSReadLine is doing ?
- Or by running and building the vs-code typescript extension 
- Or jumping into the language server


## for completeness here's some loosely related settings

| settings.json | . |
|---|---|
| terminal.integrated.smoothScrolling | True |
| powershell.integratedConsole.focusConsoleOnExecute | True |
| powershell.integratedConsole.forceClearScrollbackBuffer | False |
| powershell.integratedConsole.showOnStartup | True |
| powershell.integratedConsole.useLegacyReadLine | False |
| terminal.integrated.allowChords | True |
| terminal.integrated.customGlyphs | True |
| terminal.integrated.sendKeybindingsToShell | True |
| terminal.integrated.shellIntegration.history | 200 |
| terminal.integrated.shellIntegration.decorationsEnabled | both |
| terminal.integrated.defaultLocation | editor |
| terminal.integrated.persistentSessionReviveProcess | never |
| powershell.helpCompletion | BlockComment |
