### ISSUE TITLE
Extension ignores `powershell.developer.editorServicesLogLevel` setting when launching EditorServices

### ISSUE THREAD

**Issue by ninmonkey** [PowerShell/vscode-powershell#4282]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

The extension always uses Log Level  `verbose` when launching EditorServices. My global profile seems to be ignored.
Is `Diagnostic` the level that captures the most logging possible? 

```ps1
"powershell.developer.editorServicesLogLevel": "Diagnostic", 
"powershell.developer.editorServicesLogLevel": "Warning", // and also
```
Starts as `LogLevel = 'Verbose'`

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2022.11.1
```

### Steps to Reproduce

Set `settings.json`
```jsonc
"powershell.developer.editorServicesLogLevel": "Diagnostic",
"powershell.developer.editorServicesLogLevel": "Warning", // or also 
```
- Restart VS Code completely
- Open the Extension Terminal, and run `[System.Environment]::CommandLine`

### Logs

```ps1
Pwsh> [System.Environment]::CommandLine
"C:\Program Files\PowerShell\7\pwsh.dll" -NoProfile -ExecutionPolicy Bypass -Command "Import-Module 'c:\Users\nin\.vscode\extensions\ms-vscode.powershell-preview-2022.11.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.11.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\nin\.vscode\extensions\ms-vscode.powershell-preview-2022.11.1\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Verbose' -LogPath 'c:\Users\nin\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\logs\1669418680-362e2b21-323b-4ee6-8e62-ac2a3dee5f551669418670380\EditorServices.log' -SessionDetailsPath 'c:\Users\nin\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\sessions\PSES-VSCode-9188-985259.json' -FeatureFlags @() "
```
```ps1
    Import-Module 'c:\Users\nin\.vscode\extensions\ms-vscode.powershell-preview-2022.11.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'
    $startEditorServicesSplat = @{
        AdditionalModules = @('PowerShellEditorServices.VSCode')
        BundledModulesPath = 'c:\Users\nin\.vscode\extensions\ms-vscode.powershell-preview-2022.11.1\modules'
        EnableConsoleRepl = $true
        FeatureFlags = @()
        HostName = 'Visual Studio Code Host'
        HostProfileId = 'Microsoft.VSCode'
        HostVersion = '2022.11.1'
        LogLevel = 'Verbose'
        LogPath = 'c:\Users\nin\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\logs\1669418680-362e2b21-323b-4ee6-8e62-ac2a3dee5f551669418670380\EditorServices.log'
        SessionDetailsPath = 'c:\Users\nin\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell-preview\sessions\PSES-VSCode-9188-985259.json'
        StartupBanner = ''
    }

    Start-EditorServices @startEditorServicesSplat
```

**Comment by andschwa** [comment]
@ninmonkey I cannot repro this. It is passing the value of the VS Code's `powershell.developer.editorServicesLogLevel` correctly every time, even when changed.

What is the second block of code in your post, are you manually importing the module and launching it?

**Comment by ninmonkey** [comment]
> the second block of code

The only code I ran was `[System.Environment]::CommandLine`
The 2nd block is that, the original ES command, splatted for readability. 

> reproduction failing 

I can't reproduce it today. I re-tested a couple of log levels, and using both my
- regular / global  profile, in the Debug term
- and a clean ["virtual env" using --profile ](https://github.com/ninmonkey/Ninmonkey.Console/blob/587062e81cc7169e9a30a22e16803868bd7cb10f/zeroDepend_autoloader/Invoke-VsCodeProfileVenv.ps1#L237-L250), in the Debug term

Which is strange, because IIRC I tried different workspaces, and relaunching. 
Now I'm doubting my sanity. The only thing I can think of, is maybe if I was editing the wrong file, or it was stale -- or maybe changing branches in `git` had the effect of silently changing the setting on me.

----

That last one could explain why it occurred across workspaces, while failing today -- using the same versions of the extensions. 
Maybe mark this as resolved as operator error, until there's a new reproduction

**Comment by andschwa** [comment]
No worries, I feel you on that. I've definitely been sure I've found something wrong only for it not to occur the next day, and the only real explanation available is cache / user error. Let's call it a Heisenbug.
