### ISSUE TITLE
IntelliSense shows $true or $false is of the type of the parameter in scope if an attribute of the parameter is also set to $true or $false

### ISSUE THREAD

**Issue by AndrewJoncas** [PowerShell/vscode-powershell#4293]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

If you create a parameter and an attribute of that parameter is set to $true or $false, within the scope of the parameter declaration, IntelliSense will show that the parameter type for either $true or $false is that of the type of the parameter.

### PowerShell Version

```console
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
code --version
1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64
```

### Extension Version

```console
code --list-extensions --show-versions | select-string powershell

ms-vscode.powershell@2022.11.0
```

### Steps to Reproduce

1. Copy and paste the following into VS Code:
```Powershell
[CmdletBinding()]
Param
(
    # Parameter help description
    [Parameter(Mandatory=$true)]
    [ParameterType]
    $ParameterName
)

$true # IntelliSense displays that the type is ParameterType
```
2. Place cursor at the end of $true and press CTRL+Space and notice $true is shown as the same type as the preceding parameter.
3.  Copy and paste the following into VS Code:
```Powershell
[CmdletBinding()]
Param
(
    # Parameter help description
    [Parameter(Mandatory=$false)]
    [ParameterType]
    $ParameterName
)

$false # IntelliSense displays that the type is ParameterType
```
4. Place cursor at the end of $false and press CTRL+Space and notice $false is shown as the same type as the preceding parameter.

### Visuals

![image](https://user-images.githubusercontent.com/29053424/204662520-18236dc7-d9c1-4e41-8cea-9c928f98cac2.png)
![image](https://user-images.githubusercontent.com/29053424/204663581-35e9ba9f-772a-426e-8953-b234d6545115.png)

**Comment by SeeminglyScience** [comment]
Thanks for the report! This is a bug in PowerShell's completion API. I've opened PowerShell/PowerShell#18688 to track
