### ISSUE TITLE
Enhancement: Ability to call external programs like nuget.exe in Debug mode

### ISSUE THREAD

**Issue by maximpashuk** [PowerShell/vscode-powershell#43]
Extension is not useful for real-world powershell scripts, if in Debug mode I cannot step into line where call to nuget.exe with parameters.

Now I receive an NotImplemented exception in this case.

**Comment by daviwil** [comment]
Thanks Maxim, agreed, will get this fixed in a future release.

**Comment by daviwil** [comment]
Hey Maxim, can you try this in the latest release (0.4.1)?  Calling native apps such as NuGet.exe should work now.  I just tried calling NuGet.exe in the debugger and it worked for me.  Will close this issue for now, please feel free to let me know if you still have an issue and I'll reopen this for you.  Thanks!

**Comment by maximpashuk** [comment]
Wow, I works!!!

Now I can run my build scripts directly from VS Code !!!!
Bye-bye PowerGUI !!!

**Comment by daviwil** [comment]
Glad to hear that it worked for you!
