### ISSUE TITLE
PSScriptAnalzyer corrupts multi-line code during replace-aliases

### ISSUE THREAD

**Issue by lansalot** [PowerShell/vscode-powershell#430]
Platform
Win7 x64

To replicate (note use of backtick to split line)

```
$Pools = gwmi -query "select * from IIsApplicationPoolSetting" -computer $server `
   -namespace "root\microsoftiisv2" -Authentication PacketPrivacy -erroraction SilentlyContinue
```

PSScriptAnalyzer pulled that up at gwmi being an alias, so I hit the lightbulb to convert it to Get-WMIObject. This happened.

```$Pools = Get-WmiObjectroot\microsoftiisv2" -Authentication PacketPrivacy -erroraction SilentlyContinue```

![anim](https://cloud.githubusercontent.com/assets/9885921/21930187/8a378920-d98c-11e6-8b0c-01829f955b9a.gif)

As you can see, it cut out a heap of code and merged the two lines.
![pic4](https://cloud.githubusercontent.com/assets/9885921/21927144/b69cf78a-d97c-11e6-94ba-32cde1529143.jpg)

**Comment by lansalot** [comment]
With logging turned up:

13/01/2017 10:52:03 [VERBOSE] - Method "ReadMessage" at line 111 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": 47,
      "method": "textDocument/codeAction",
      "params": {
        "textDocument": {
          "uri": "file:///c%3A/scripts/powershell/Miscellaneous/ScanIISPools.ps1"
        },
        "range": {
          "start": {
            "line": 31,
            "character": 11
          },
          "end": {
            "line": 31,
            "character": 15
          }
        },
        "context": {
          "diagnostics": [
            {
              "range": {
                "start": {
                  "line": 31,
                  "character": 11
                },
                "end": {
                  "line": 31,
                  "character": 15
                }
              },
              "message": "'gwmi' is an alias of 'Get-WmiObject'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.",
              "severity": 2,
              "code": "6b422a03-8ccf-4e54-9a65-bad319e5c43a"
            }
          ]
        }
      }
    }

13/01/2017 10:52:03 [VERBOSE] - Method "WriteMessage" at line 59 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "jsonrpc": "2.0",
      "id": "47",
      "result": [
        {
          "title": "Replace gwmi with Get-WmiObject",
          "command": "PowerShell.ApplyCodeActionEdits",
          "arguments": [
            {
              "File": "",
              "Text": "Get-WmiObject",
              "StartLineNumber": 32,
              "StartColumnNumber": 12,
              "StartOffset": 0,
              "EndLineNumber": 33,
              "EndColumnNumber": 16,
              "EndOffset": 0
            }
          ]
        }
      ]
    }

**Comment by daviwil** [comment]
Yep, we've got this issue fixed in the PSScriptAnalyzer side, just need to ship an update.  We'll have everything updated on Tuesday.

**Comment by lansalot** [comment]
I like the sound of that. Thanks!
