### ISSUE TITLE
Untrusted PowerShellEditorServices.Commands.types. ps1xml in Visual Studio Code

### ISSUE THREAD

**Issue by Candelit** [PowerShell/vscode-powershell#4300]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I start VS code, open a PowerShell terminal and get a prompt if I want to run this extension.
If I say no, PS fails.

Full dialogue:
PowerShell Extension v2022.11.0
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.

Do you want to run software from this untrusted publisher?
File 
C:\Users\MyUserName\.vscode\extensions\ms-vscode.powershell-2022.11.0\modules\PowerShellEditorServices\Commands\PowerShellEditorServices.Commands.types.
ps1xml is published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from 
trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): 

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.11.0
```

### Steps to Reproduce

Start VS code, the first PS terminal to open gives the error
I have tried to uninstall the extension, but when I run the script the error still comes.

**Comment by andschwa** [comment]
Hi @Candelit, you need to answer in the affirmative to trust Microsoft as a publisher in order to run the script and therefore the extension. As you can see in the prompt, the type is correctly published by "Microsoft Corporation" but that you have not yet trusted that publisher on your system.
