### ISSUE TITLE
Debugger is not showing various properties in variable panel

### ISSUE THREAD

**Issue by AlexHimself** [PowerShell/vscode-powershell#4314]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When debugging PowerShell relating to the `PnP-SharePoint` module and reviewing variables in the debugger, not all properties are being displayed.

Using the below code (see screenshot), the various properties are missing. This happens with other PS SharePoint objects as well.

I would expect at a minimum to see `$item.Name` visible in the debugger.

```
$siteURL = "https://MyOrg.sharepoint.com/sites/MyTeamSite"

Connect-PnPOnline -Url $siteURL -UseWebLogin

Get-PnPFolderItem -FolderSiteRelativeUrl "/Shared Documents" -ItemType File | ForEach-Object {
    $item = $_
    $item.Name # Set breakpoint here
}
```

Also `$item | Get-Member -MemberType Properties -Name "Name"` or even `$item | Get-Member` both return various properties not exposed by the debugger.

Similarly, even commands like `Get-ChildItem` aren't showing properties? See screenshot.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
code --version
1.74.0
5235c6bb189b60b01b1f49062f4ffa42384f8c91
x64
```

### Extension Version

```console
code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2022.11.0
```

### Steps to Reproduce

1. Add files to a document library or the Share Document library
2. Change `$siteURL` to your SharePoint site
3. Change `-FolderSiteRelativeUrl` to your document library that contains some files
4. Set breakpoint on `$item.Name` and examine the debugger for the local variable `$item` and expand the node.
5. **Issue:** After expanding the node, you should not see various properties such as `Name`

### Visuals

![image](https://user-images.githubusercontent.com/10466466/206309913-36617039-9e5f-4cb5-8644-ff15250ae658.png)

![image](https://user-images.githubusercontent.com/10466466/207427406-f455ac8b-057e-4cf4-9edd-011f497bc2fe.png)

**Comment by AlexHimself** [comment]
Other users have confirmed the same results when using some basic functions like `Get-ChildItem`.

This seems like something is pretty wrong? The debugger is broken for a lot of things unless I'm doing it wrong?

**Comment by andschwa** [comment]
@SeeminglyScience it turns out that most of these wanted fields are marked as `NonPublic` properties. The C# extension includes them, so I added that flag and now all the properties we'd expect are here. Working on a PR that I'll write tests for Monday.

**Comment by andschwa** [comment]
Actually, they were _not_ missing because they were `NonPublic`, that was a red herring. They were missing because the error handling happened outside the loop, so the first field that failed to have its value retrieved caused the logic to short circuit and not load anything else. That's fixed, along with a regression test for this.

**Comment by AlexHimself** [comment]
Thanks @andschwa!! Any idea when the update will be available on the marketplace?

**Comment by andschwa** [comment]
It'll be in the preview extension later today!

**Comment by andschwa** [comment]
@AlexHimself it's out!

**Comment by AlexHimself** [comment]
Great! I'll give it a shot tomorrow!

**Comment by AlexHimself** [comment]
> @AlexHimself it's out!

Hmm...are you sure it's released? I verified my VSCode is up to date and have the `PowerShell Preview` extension, which is showing Dec 12 as the last changelog date.

**Comment by andschwa** [comment]
Yes, I see v2022.12.1 released 12/20 on https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview, and in the embedded marketplace in VS Code. Maybe restart Code?

**Comment by AlexHimself** [comment]
I've tried from two different computers with the same result. I show `v2022.12.1` released on `12/12`?

![image](https://user-images.githubusercontent.com/10466466/208992266-0c5c16c9-5c9f-4776-af07-122cbf5575d0.png)

![image](https://user-images.githubusercontent.com/10466466/208992290-dc080b9f-641b-4f90-b467-a388a2150436.png)

**Comment by andschwa** [comment]
Uhh, I'm sorry, you're right, it should be v2022.12.2...funny because it shows the date as updated and the publish step didn't fail. Looking...

**Comment by andschwa** [comment]
For now you can download the preview from https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.12.2-preview and install the VSIX manually. Something must have failed on the marketplace end because the pipeline that released it literally got a "success" result from it.

**Comment by andschwa** [comment]
I tried to manually publish and got this:

 INFO  Publishing 'ms-vscode.powershell-preview v2022.12.2'...
 ERROR  ms-vscode.powershell-preview v2022.12.2 already exists.

I think they're having server issues. I suggest waiting that out or using the VSIX manually.

**Comment by AlexHimself** [comment]
That makes sense and I already installed it manually to get the `v2022.12.2` version and I can confirm the debugger is working as expected! So much easier to figure out what I'm working on now with it! Thanks so much!
