### ISSUE TITLE
allow to set a default starter .ps1 file

### ISSUE THREAD

**Issue by damnmso** [PowerShell/vscode-powershell#4321]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I have a powershell project containing about 10 files. 1 .ps1 and 9 .psm1. whenever i hit the "run" button, i want to have vscode start the .ps1 and not the .psm1 - starting a .psm1 makes absolutely no sense. what happens then is that the psm1 is opened in notepad.

Version: 1.73.1 (user setup)
Commit: https://github.com/microsoft/vscode/commit/6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

copied from https://github.com/microsoft/vscode/issues/168055

### Proposed Design

intellij and others have per-project "start"-files which act as entry point when the application starts (e.g. containing a main() in c/java). i am highly missing something like that.

**Comment by AlexHimself** [comment]
I think the exact think you're describing is `launch.json` configuration settings. See:

- https://code.visualstudio.com/docs/editor/debugging
- https://github.com/PowerShell/vscode-powershell/blob/main/examples/.vscode/launch.json

**Comment by andschwa** [comment]
That is definitely the right way to go about this, thanks @AlexHimself!
