### ISSUE TITLE
Can't use PowerShell Daily without fully resolved path

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#4329]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

```
12/14/2022 10:34:46 AM [WARNING] - Additional PowerShell 'PowerShell Daily' not found at '~/.powershell-daily/pwsh'! 
```
but if I:
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/2644648/207691236-00ba31b2-0677-4a5f-9ad8-06c332f3d6c4.png">

problem seems to be that node and vscode APIs don't handle `~` well

### PowerShell Version

```console
N/A
```

### Visual Studio Code Version

```console
Version: 1.75.0-insider
Commit: d7b1e2a1c892511a125e4ceb9758ec8ddf907775
Date: 2022-12-12T12:42:54.079Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: Yes
```

### Extension Version

```console
v2022.12.1
```

### Steps to Reproduce

```
"powershell.powerShellAdditionalExePaths": {
      "PowerShell Daily": "~/.powershell-daily/pwsh"
    },
    "powershell.powerShellDefaultVersion": "PowerShell Daily",
```

reload. Get this:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/2644648/207691750-fed9d3d4-2930-4b41-836f-fdc3cae08ef4.png">

**Comment by TylerLeonhardt** [comment]
Maybe PowerShell Daily could be automatically discovered but only used if explicitly set in the powerShellDefaultVersion?

**Comment by andschwa** [comment]
This is another reason why https://github.com/microsoft/vscode/issues/46471 would be _so useful_ because then you could just use `${userHome}`, as you would expect to be able to for a VS Code setting!
