### ISSUE TITLE
connect enoent error

### ISSUE THREAD

**Issue by Mlsoun** [PowerShell/vscode-powershell#4332]
### Prerequisites

- [X] I have written a descriptive issue title.
- [x] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [x] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [x] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [x] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

restart pwsh konsole (click on Trash icon). After this press F5 for Debug. Error message "connect enoent \\.\pipe\pses_jvpn4k2y.dfi"

### PowerShell Version

```console
7.3.1
```

### Visual Studio Code Version

```console
1.74.1
```

### Extension Version

```console
Powershell v2022.11.0
```

### Steps to Reproduce

restart pwsh konsole (click on Trash icon). After this press F5 for Debug. Error message "connect enoent \\.\pipe\pses_jvpn4k2y.dfi"

### Visuals

![image](https://user-images.githubusercontent.com/53565012/207921636-828c2d10-5371-4ca1-8d95-709f040173f3.png)

**Comment by andschwa** [comment]
If you've clicked the trash icon, you've closed the PowerShell Extension Terminal, so then trying to debug isn't going to work unless you restart the terminal. Can you first ensure the extension terminal is started?

**Comment by Mlsoun** [comment]
Yes - you are absolutely right. Terminal is not running and Error occurs. This is the reason.
I have the news. Normally two notifications windows are popup and I click on Yes - it restart the powershell extension terminal and then I can start debugging again without problem. 
![image](https://user-images.githubusercontent.com/53565012/209010743-46364e11-403d-4908-b2ab-cf37cb1f0353.png)
Now I discovered the real procedure to simulate the error -
 I press F5 for debugging the code and when terminal is waiting for user input on Read-Host instruction and I click on Trash icon, the second notification windows **does not appear** and I cannot click on Yes for restarting terminal. When I press F5 for debugging, the reported Error message "connect enoent \.\pipe\pses_jvpn4k2y.dfi" occurs.  Now helps only close and start the VSCode

**Comment by Mlsoun** [comment]
Next progress - Close the VSCode is not needed - just press Ctrl +Shift+P , type "restart" and select "Powershell: Restart session"
![image](https://user-images.githubusercontent.com/53565012/209016366-817ae64f-e59c-461f-aef6-71e3b5d0186b.png)

**Comment by andschwa** [comment]
Sounds good. Just make sure you keep that Extension Terminal up if you want to use it. As that notice notes, IntelliSense and other features (such as debugging and F5 etc.) will not work without it! I would recommend just not clicking the trash icon.

**Comment by Mlsoun** [comment]
The reason why I click on the Trash icon is because IntelliSense has stopped working. Now should I find How can i reset the Intellisense  :-)
