### ISSUE TITLE
Integrated Terminal won't load

### ISSUE THREAD

**Issue by thisjustin816** [PowerShell/vscode-powershell#4336]
Type: <b>Bug</b>

The integrated terminal for the powershell extension won't load, it just hangs on the intro text. I've commented out all profiles, removed all extension settings and tried rolling back to the previous extension version. It was previously working.

Extension version: 2022.11.0
VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (11.97GB free)|
|Process Argv|--folder-uri file:///c%3A/azrepos/PipelineTasks --crash-reporter-id 50c76677-d175-4d77-87f8-f82b2959c282|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by andschwa** [comment]
Can you try the latest version, v2022.12.1?

**Comment by thisjustin816** [comment]
That’s actually when the issue started. My extension was updated this morning to that version.

**Comment by winperec** [comment]
The same issue, I have installed the latest extension version [v2022.12.1](https://github.com/PowerShell/vscode-powershell/releases/tag/v2022.12.1)
This is the log file.
>12/19/2022 9:49:39 AM [NORMAL] - Visual Studio Code v1.74.1 64-bit
12/19/2022 9:49:39 AM [NORMAL] - Language server starting --
12/19/2022 9:49:39 AM [NORMAL] - PowerShell Extension v2022.12.1
12/19/2022 9:49:39 AM [NORMAL] -     PowerShell executable: C:\Program Files\PowerShell\7\pwsh.exe
12/19/2022 9:49:39 AM [NORMAL] - Operating System: Windows 64-bit
12/19/2022 9:49:39 AM [NORMAL] -     PowerShell args: -NoProfile -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\iv\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.12.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\iv\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2022.12.1
Copyright (c) Microsoft Corporation.
https://aka.ms/vscode-powershell
Type 'help' to get help.
" -LogLevel 'Normal' -LogPath 'c:\Users\iv\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\logs\1671432579-f579290c-1ee1-4b4a-ad46-168f5e6ec3f01671432562939\EditorServices.log' -SessionDetailsPath 'c:\Users\iv\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSCode-1544-883503.json' -FeatureFlags @('PSReadLine') 
12/19/2022 9:49:39 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\iv\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.12.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\iv\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2022.12.1
Copyright (c) Microsoft Corporation.
https://aka.ms/vscode-powershell
Type 'help' to get help.
" -LogLevel 'Normal' -LogPath 'c:\Users\iv\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\logs\1671432579-f579290c-1ee1-4b4a-ad46-168f5e6ec3f01671432562939\EditorServices.log' -SessionDetailsPath 'c:\Users\iv\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSCode-1544-883503.json' -FeatureFlags @('PSReadLine') 
12/19/2022 9:49:39 AM [NORMAL] - pwsh.exe started.
12/19/2022 9:49:39 AM [NORMAL] - Waiting for session file...
12/19/2022 9:50:10 AM [WARNING] - Loading the PowerShell extension is taking longer than expected. If you're using privilege enforcement software, this can affect start up performance.

When I tried import module manually:

> Import-Module 'c:\Users\iv\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'

I got this error:
![image](https://user-images.githubusercontent.com/10044618/208367582-a22fa22f-9873-4153-b3f8-2a32ca7c467d.png)
I'm not sure it is relevant

But when install previous version 2022.11.0 from vsix it works fine

**Comment by andschwa** [comment]
What version of PowerShell are you using? I.e. the output of `$PSVersionTable`.

**Comment by winperec** [comment]
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by andschwa** [comment]
Ah, as I suspected. So PowerShell 7.1 is past [end-of-life](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle) and not supported. The current LTS is 7.2, please update your PowerShell and that should fix it!

**Comment by thisjustin816** [comment]
I saw it on 5.1. Whatever the latest is on Windows 11 Enterprise. Using PowerShell 7 isn’t an option in this scenarios.

**Comment by andschwa** [comment]
PowerShell 5.1 is supported on a best effort basis. Can you get me more logs?

**Comment by andschwa** [comment]
Get [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

Thanks!

**Comment by thisjustin816** [comment]
[ps-logs.zip](https://github.com/PowerShell/vscode-powershell/files/10274433/ps-logs.zip)

**Comment by andschwa** [comment]
I see in your logs that this is your PSModulePath:

> [VRB]: Updated PSModulePath to: 'C:\azrepos\PipelineTasks\Content\packages;;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\AppvPkgConverter;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\AppvSequencer;c:\program files\powershell\7\Modules;C:\Program Files\PowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;c:\Users\jbeeson\.vscode\extensions\ms-vscode.powershell-2021.10.2\modules;c:\Users\jbeeson\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules;c:\Users\jbeeson\.vscode\extensions\ms-vscode.powershell-2021.6.2\modules;c:\Users\jbeeson\.vscode\extensions\ms-vscode.powershell-2022.10.0\modules;c:\Users\jbeeson\.vscode\extensions\ms-vscode.powershell-2022.7.2\modules;C:\Users\jbeeson\OneDrive - Nuvasive Inc\Documents\PowerShell\Modules;C:\Users\jbeeson\OneDrive - Nuvasive Inc\Documents\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\AppvPkgConverter;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\AppvSequencer;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\;c:\Users\jbeeson\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules'

The main problem supporting PowerShell 5.1 is that the GAC means _any_ dependency from another module can cause a conflict that leads to things failing...rather cryptically like this.

Can you try loading the extension with your PSModulePath set manually without most of those extra modules (and your profiles empty), and then if that works, I'd suggest trying half and half at a time in a bisection search to figure out which one is conflicting.

**Comment by andschwa** [comment]
Interestingly the very last thing I see in the logs is this:

> 2022-12-20 20:15:25.285 -08:00 [VRB] Could not write to output handler, perhaps serialization failed?
System.Threading.Channels.ChannelClosedException: The channel has been closed.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at OmniSharp.Extensions.JsonRpc.OutputHandler.<ProcessOutputStream>d__18.MoveNext()

and based on previous bug reports, that often seems to occur when an overly active anti-virus shuts down the named pipe. Do you have any AV running you could temporarily disable?

**Comment by thisjustin816** [comment]
I’ll try your debugging steps after the Christmas break, thanks. As for that last part, that’s good to know because we do have an enterprise AV that has been know to be invasive so I’ll check with our IT department.

**Comment by thisjustin816** [comment]
Just now coming back from vacation to look into this and saw that my issue was from having the PowerShell 7 built-in modules directory in my main PSModulePath, so PowerShell 5.1 was trying to load those. Removed that entry and everything is working.

**Comment by andschwa** [comment]
Ah, fantastic. Thanks for following up!
