### ISSUE TITLE
PowerShell terminal hangs when running scripts from VS Code

### ISSUE THREAD

**Issue by florinangelescu** [PowerShell/vscode-powershell#4344]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Run a script file using "run" or F5. The console execution hangs.
It doesn't happen if you run one liners or directly in the console. Only when you run entire scripts.
If I revert to previous version of PowerShell extension, the behaviour is gone so I must be something in the latest version.
Also, the issue did appear after I upgraded (on Thursday).

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.74.2
e8a3071ea4344d9d48ef8a4df2c097372b0c5161
arm64
```

### Extension Version

```console
PowerShell: v2022.12.1
```

### Steps to Reproduce

Run a script file using "run" or F5.
It doesn't happen if you run one liners or directly in the console. Only when you run entire scripts.

### Visuals

![image](https://user-images.githubusercontent.com/45992068/208989177-06a332ea-8f82-4dfe-80b2-03e06b828a8a.png)

**Comment by andschwa** [comment]
Can you please share the script you are running and the logs?

**Comment by andschwa** [comment]
I've marked this as need repro info because given the current information, I cannot repro.
<img width="1548" alt="Screenshot 2022-12-21 at 12 19 34 PM" src="https://user-images.githubusercontent.com/2226434/208995761-2939aa19-2f93-4356-a8a9-080bbb509880.png">

**Comment by jamcguire** [comment]
I am experiencing the same issue.  I have rolled back to 7.3.0 from 7.3.1 and am not having the problem any more.  I am not able to share the script I'm afraid.
