### ISSUE TITLE
Terminal randomly become unresponsive (reloading module in the background)

### ISSUE THREAD

**Issue by SwissPowershell** [PowerShell/vscode-powershell#4345]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I am experiencing a problem when in a regular basis my Terminal become unresponsive

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.74.0
5235c6bb189b60b01b1f49062f4ffa42384f8c91
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.12.1
```

### Steps to Reproduce

1. Have some heavy / verbose module (in my case VMWare Cli)
2. Work normally with VSCode PS Extension on your scripts / modules

it will somehow "Randomly" (did not exactly get why and when) reload all my modules (I can see them loading if I put $VerbosePreference = 'Continue')

is there a way to prevent all my module to be constantly reloaded ?

**Comment by andschwa** [comment]
Does this recur when using PowerShell 7?
