### ISSUE TITLE
Comments on same line as Function not styled when opening brace is on next line

### ISSUE THREAD

**Issue by fredskis** [PowerShell/vscode-powershell#436]
### System Details

- Operating system name and version: Windows 10 1607 (14393.576)
- VS Code version: 1.8.1
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When adding comments on the same line as a function where the opening brace is on the next line, the comment doesn't get formatted correctly. 
I'm using the Dark+ (default dark) theme and comments are green, however, when entered into this line they appear as grey.

As an example: 
```
Function New-Function { #comment here
}
```
formats fine with a green comment, however, 
```
Function New-Function #comment here
{
}
```
doesn't format correctly and the comment remains grey.

**Comment by rkeithhill** [comment]
PowerShell syntax colorization is handled in a separate project: [EditorSyntax](https://github.com/powershell/editorsyntax).  Would you mind posting this issue on that repo?

**Comment by fredskis** [comment]
Will do, thanks
