### ISSUE TITLE
Corrupted prompt in the terminal

### ISSUE THREAD

**Issue by Aviw13** [PowerShell/vscode-powershell#4362]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

In the latest version (v2022.12.1) the terminal prompt is corrupted, contains some additional symbols:
![image](https://user-images.githubusercontent.com/5618778/211281994-582e0150-c66a-4db4-ab23-34335c2ac6b8.png)

In the previous version (v2022.11.0) there is no such a problem.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.14409.1029
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1029
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.74.2
e8a3071ea4344d9d48ef8a4df2c097372b0c5161
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.12.1
```

### Steps to Reproduce

The issue appeared after an upgrade to the latest version. Downgrading resolves the issue.
No extra steps to reproduce, just open the terminal

### Logs

[Logs.zip](https://github.com/PowerShell/vscode-powershell/files/10372234/Logs.zip)

**Comment by andschwa** [comment]
Those are the ANSI escape codes used by [VS Code's Shell Integration feature](https://code.visualstudio.com/docs/terminal/shell-integration). That _should_ work even with PowerShell 5.1, can you give more details about your environment? Can you also test the latest preview (where we updated the shell integration script)?

Important question: what version of VS Code are you running? Is shell integration working in terminals other than the Extension Terminal?

If you need to get by, you can disable the feature by setting `terminal.integrated.shellIntegration.enabled` to false.

**Comment by Aviw13** [comment]
Hi!
I've tested the Preview version and the issue is occurring there too.
The regular terminal is working well:
![image](https://user-images.githubusercontent.com/5618778/212382302-9e597235-84bf-4ed5-919e-60fa978ac80d.png)

I also tried to disable other extensions to have cleaner environment, but that didn't help.

**Comment by andschwa** [comment]
What's your setting for `terminal.integrated.shellIntegration.enabled`?

**Comment by Aviw13** [comment]
Default, not changed:
![image](https://user-images.githubusercontent.com/5618778/212490888-35be920a-6d4e-4c6a-97f7-08c541b9b58d.png)

**Comment by Aviw13** [comment]
Yes, disabling resolves the issue
Thank you! :)

**Comment by andschwa** [comment]
Great! I'm not certain why shell integration is failing so badly for you, but at least we've narrowed it down and can clear things up for you.
