### ISSUE TITLE
VSCode Pester support for PSKoans filenames

### ISSUE THREAD

**Issue by Manbearpiet** [PowerShell/vscode-powershell#4363]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Dear VSCode PowerShell hero's,
I'd like VSCode to have the same Pester Support for [PSKoans](https://github.com/vexx32/PSKoans) as it does for Pester files.  As this makes it very easy for new PowerShell users to reflect on their progress within a Koan, by clicking "Run Tests". At this time, I manually rename the Koans to `SomeKoan.Koans.Tests.ps1` to get the Pester VScode Support, but this breaks the PSKoans module. I hope there is a way to support Pester language features with filenames ending  with"Koans.ps1" 

![image](https://user-images.githubusercontent.com/43993129/211353020-564ada79-581f-44b1-b6c1-be5448830aec.png)

**Comment by andschwa** [comment]
Thanks so much for the suggestion @Manbearpiet!

**Comment by fflaten** [comment]
Support for Run/Debug tests specifically makes sense. Low cost and promotes learning. 😃
