### ISSUE TITLE
Loading the PowerShell extension is taking longer than expected

### ISSUE THREAD

**Issue by dmumladze** [PowerShell/vscode-powershell#4371]
### Prerequisites

- [x] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [x] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I cannot debug PowerShell files in Visual Studio Code. As soon as I start vscode, it displays following two errors in the Terminal:

`Import-Module: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

`Start-EditorServices: The term 'Start-EditorServices' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Then the Terminal pane clears and several popup alerts appear saying PowerShell failed to start.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.74.3
97dec172d3256f8ca4bfb2143f3f76b503ca0534
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.12.1
```

### Steps to Reproduce

N/A

### Visuals

![image](https://user-images.githubusercontent.com/4098572/212373400-a7abf3ab-7232-4926-ac01-31cbc477f3ba.png)

### Logs

1/13/2023 10:55:51 AM [NORMAL] - Visual Studio Code v1.74.3 64-bit
1/13/2023 10:55:51 AM [NORMAL] - Language server starting --
1/13/2023 10:55:51 AM [NORMAL] - PowerShell Extension v2022.12.1
1/13/2023 10:55:51 AM [NORMAL] -     PowerShell executable: C:\Program Files\PowerShell\7\pwsh.exe
1/13/2023 10:55:51 AM [NORMAL] - Operating System: Windows 64-bit
1/13/2023 10:55:51 AM [NORMAL] -     PowerShell args: -NoProfile -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\david\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.12.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\david\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Normal' -LogPath 'c:\Users\david\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\logs\1673625351-7c79dfb0-5e11-49f2-8f28-22219e4a7c461673625349867\EditorServices.log' -SessionDetailsPath 'c:\Users\david\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSCode-28444-434897.json' -FeatureFlags @() 
1/13/2023 10:55:51 AM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\david\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.12.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\david\.vscode\extensions\ms-vscode.powershell-2022.12.1\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Normal' -LogPath 'c:\Users\david\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\logs\1673625351-7c79dfb0-5e11-49f2-8f28-22219e4a7c461673625349867\EditorServices.log' -SessionDetailsPath 'c:\Users\david\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSCode-28444-434897.json' -FeatureFlags @() 
1/13/2023 10:55:51 AM [NORMAL] - pwsh.exe started.
1/13/2023 10:55:51 AM [NORMAL] - Waiting for session file...
1/13/2023 10:56:22 AM [WARNING] - Loading the PowerShell extension is taking longer than expected. If you're using privilege enforcement software, this can affect start up performance.
1/13/2023 10:59:54 AM [NORMAL] - Timed out waiting for session file to appear!
1/13/2023 10:59:54 AM [ERROR] - PowerShell process failed to start: 
1/13/2023 10:59:54 AM [ERROR] - Timed out waiting for session file to appear!
1/13/2023 10:59:54 AM [ERROR] - Unknown session status 'undefined' with reason 'undefined

**Comment by dmumladze** [comment]
This popup appears several minutes later:
![image](https://user-images.githubusercontent.com/4098572/212374288-bb77b7b4-a582-449c-bbf7-42cf45ce9cd4.png)

**Comment by andschwa** [comment]
Hi,

Could you please provide more [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)?

Thanks!

**Comment by schwinbp** [comment]
My Logs...

1/18/2023 1:27:13 PM [NORMAL] - Visual Studio Code v1.74.3 64-bit

1/18/2023 1:27:13 PM [NORMAL] - Creating log directory at: 'file:///Users/schwinbp/Library/Application%20Support/Code/User/globalStorage/ms-vscode.powershell/logs/1674066432-d4869f1f-9c9d-43c0-a908-2589a79c9bd21674066431924'

1/18/2023 1:27:13 PM [NORMAL] - PowerShell Extension v2022.12.1

1/18/2023 1:27:13 PM [NORMAL] - Operating System: MacOS 64-bit

1/18/2023 1:27:14 PM [NORMAL] - Language server starting --

1/18/2023 1:27:14 PM [NORMAL] -     PowerShell executable: /usr/local/bin/pwsh

1/18/2023 1:27:14 PM [NORMAL] -     PowerShell args: -Login -NoProfile -EncodedCommand ********

1/18/2023 1:27:14 PM [NORMAL] -     PowerShell Editor Services args: Import-Module '/Users/schwinbp/.vscode/extensions/ms-vscode.powershell-2022.12.1/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.12.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/schwinbp/.vscode/extensions/ms-vscode.powershell-2022.12.1/modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2022.12.1
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
" -LogLevel 'Normal' -LogPath '/Users/schwinbp/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/logs/1674066432-d4869f1f-9c9d-43c0-a908-2589a79c9bd21674066431924/EditorServices.log' -SessionDetailsPath '/Users/schwinbp/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/sessions/PSES-VSCode-21752-370789.json' -FeatureFlags @() 

1/18/2023 1:27:14 PM [NORMAL] - pwsh started.

1/18/2023 1:27:14 PM [NORMAL] - Waiting for session file...

1/18/2023 1:27:44 PM [WARNING] - Loading the PowerShell extension is taking longer than expected. If you're using privilege enforcement software, this can affect start up performance.

1/18/2023 1:31:15 PM [NORMAL] - Timed out waiting for session file to appear!

1/18/2023 1:31:15 PM [ERROR] - PowerShell process failed to start: 

1/18/2023 1:31:15 PM [ERROR] - Timed out waiting for session file to appear!

1/18/2023 1:31:15 PM [ERROR] - Unknown session status 'undefined' with reason 'undefined

**Comment by andschwa** [comment]
> Is there some permissions we need to give in System Settings to allow this extension to run?

That is probably the case. But can you enable _diagnostic_ logging?

**Comment by schwinbp** [comment]
1/18/2023 2:06:59 PM [DIAGNOSTIC] - Loaded settings:
{
  "powerShellAdditionalExePaths": {},
  "powerShellDefaultVersion": "",
  "powerShellExePath": "",
  "promptToUpdatePowerShell": false,
  "startAsLoginShell": {
    "osx": true,
    "linux": false
  },
  "startAutomatically": true,
  "enableProfileLoading": true,
  "helpCompletion": "BlockComment",
  "scriptAnalysis": {
    "enable": true,
    "settingsPath": "PSScriptAnalyzerSettings.psd1"
  },
  "debugging": {
    "createTemporaryIntegratedConsole": false
  },
  "developer": {
    "featureFlags": [],
    "bundledModulesPath": "../../PowerShellEditorServices/module",
    "editorServicesLogLevel": "Diagnostic",
    "editorServicesWaitForDebugger": false,
    "waitForSessionFileTimeoutSeconds": 240
  },
  "codeFormatting": {
    "autoCorrectAliases": false,
    "avoidSemicolonsAsLineTerminators": false,
    "preset": "Custom",
    "openBraceOnSameLine": true,
    "newLineAfterOpenBrace": true,
    "newLineAfterCloseBrace": true,
    "pipelineIndentationStyle": "NoIndentation",
    "whitespaceBeforeOpenBrace": true,
    "whitespaceBeforeOpenParen": true,
    "whitespaceAroundOperator": true,
    "whitespaceAfterSeparator": true,
    "whitespaceBetweenParameters": false,
    "whitespaceInsideBrace": true,
    "addWhitespaceAroundPipe": true,
    "trimWhitespaceAroundPipe": false,
    "ignoreOneLineBlock": true,
    "alignPropertyValuePairs": true,
    "useConstantStrings": false,
    "useCorrectCasing": false
  },
  "integratedConsole": {
    "showOnStartup": true,
    "startInBackground": false,
    "focusConsoleOnExecute": true,
    "useLegacyReadLine": false,
    "forceClearScrollbackBuffer": false,
    "suppressStartupBanner": false
  },
  "sideBar": {
    "CommandExplorerVisibility": true,
    "CommandExplorerExcludeFilter": []
  },
  "pester": {
    "useLegacyCodeLens": true,
    "outputVerbosity": "FromPreference",
    "debugOutputVerbosity": "Diagnostic"
  },
  "buttons": {
    "showRunButtons": true,
    "showPanelMovementButtons": false
  },
  "cwd": "",
  "enableReferencesCodeLens": true,
  "analyzeOpenDocumentsOnly": false
}
1/18/2023 2:07:00 PM [NORMAL] - Language server starting --
1/18/2023 2:07:00 PM [NORMAL] - pwsh started.
1/18/2023 2:07:00 PM [NORMAL] -     PowerShell executable: /usr/local/bin/pwsh
1/18/2023 2:07:00 PM [NORMAL] - Waiting for session file...
1/18/2023 2:07:00 PM [NORMAL] -     PowerShell args: -Login -NoProfile -EncodedCommand SQBtAHAAbwByAHQALQBNAG8AZAB1AGw******
1/18/2023 2:07:00 PM [NORMAL] -     PowerShell Editor Services args: Import-Module '/Users/schwinbp/.vscode/extensions/ms-vscode.powershell-2022.12.1/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.12.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/schwinbp/.vscode/extensions/ms-vscode.powershell-2022.12.1/modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2022.12.1
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
" -LogLevel 'Diagnostic' -LogPath '/Users/schwinbp/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/logs/1674068819-4c14146b-6a8b-435b-ba43-ab7681d2a3c21674068808976/EditorServices.log' -SessionDetailsPath '/Users/schwinbp/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/sessions/PSES-VSCode-22402-204135.json' -FeatureFlags @() 
1/18/2023 2:06:59 PM [NORMAL] - Visual Studio Code v1.74.3 64-bit
1/18/2023 2:06:59 PM [NORMAL] - PowerShell Extension v2022.12.1
1/18/2023 2:06:59 PM [NORMAL] - Operating System: MacOS 64-bit
1/18/2023 2:07:30 PM [WARNING] - Loading the PowerShell extension is taking longer than expected. If you're using privilege enforcement software, this can affect start up performance.
1/18/2023 2:11:01 PM [NORMAL] - Timed out waiting for session file to appear!
1/18/2023 2:11:01 PM [ERROR] - PowerShell process failed to start: 
1/18/2023 2:11:01 PM [ERROR] - Timed out waiting for session file to appear!
1/18/2023 2:11:01 PM [ERROR] - Unknown session status 'undefined' with reason 'undefined

**Comment by AdamGrossTX** [comment]
I was able to repro this issue and resolve it by switching `"powershell.powerShellDefaultVersion": "PowerShell (x64)",` to `"powershell.powerShellDefaultVersion": "Windows PowerShell (x64)",` in my settings.json. It appears there's an issue where the PowerShell extension doesn't load if PowerShell 7 is the default PowerShell used.

**Comment by dmumladze** [comment]
> I was able to repro this issue and resolve it by switching `"powershell.powerShellDefaultVersion": "PowerShell (x64)",` to `"powershell.powerShellDefaultVersion": "Windows PowerShell (x64)",` in my settings.json. It appears there's an issue where the PowerShell extension doesn't load if PowerShell 7 is the default PowerShell used.

Neither settings worked for me.

**Comment by andschwa** [comment]
Hi all, is this still recurring with [v2023.1.0](https://github.com/PowerShell/vscode-powershell/releases/tag/v2023.1.0)?

**Comment by soulshined** [comment]
This is a major roadblock. As of now, the only thing that at least gets this from failing is by doing what @dmumladze mentioned by setting the `powershell.powerShellDefaultVersion` to Windows Powershell (x64) AND installing a different version: click on the extension cog and install version 2022.12.1

The most recent version this works without changing any settings or keeping everything as I have been, is version 2022.11.0

**Comment by pcgeek86** [comment]
Same issue here. Haven't used PowerShell Extension on MacOS for a while, but just tried opening it up and ran into this problem. This computer is running MacOS Ventura.

* Intellisense does not work
* Errors show up when PowerShell Extension initializes (see below)

<img width="469" alt="Screenshot 2023-01-31 at 2 30 56 AM" src="https://user-images.githubusercontent.com/466713/215721857-c80a7b5c-1e9a-44b5-8d99-58a345226e96.png">

> Unknown session status 'undefined' with reason 'undefined

```

1/31/2023 2:23:08 AM [NORMAL] - pwsh started.

1/31/2023 2:23:08 AM [NORMAL] - Waiting for session file...

1/31/2023 2:23:38 AM [WARNING] - Loading the PowerShell extension is taking longer than expected. If you're using privilege enforcement software, this can affect start up performance.

1/31/2023 2:27:09 AM [NORMAL] - Timed out waiting for session file to appear!

1/31/2023 2:27:09 AM [ERROR] - PowerShell process failed to start: 

1/31/2023 2:27:09 AM [ERROR] - Timed out waiting for session file to appear!

1/31/2023 2:27:09 AM [ERROR] - Unknown session status 'undefined' with reason 'undefined
```

In my VSCode settings, I have the following configuration:

```json
    "powershell.powerShellAdditionalExePaths": {
        "pwshcore": "c:\\users\\trevorsullivan\\scoop\\apps\\pwsh\\current\\pwsh.exe",
        "pwshcoremacos": "/usr/local/microsoft/powershell/7/pwsh"
    }
```

**Comment by andschwa** [comment]
I've so far been unable to repro 😭

> It seems that using Mac Homebrew to upgrade PowerShell Core from 7.3.1 to 7.3.2 immediately fixed the issue.

Glad to hear this, perhaps a step others can try? (Updating to 7.3.2 that is.)

**Comment by andschwa** [comment]
Hey we were reviewing in triage and @SeeminglyScience caught that @dmumladze, you're trying to use PowerShell 7.1 still. However, that version of PowerShell is [past its official end of life](https://learn.microsoft.com/en-us/powershell/scripting/install/PowerShell-Support-Lifecycle?view=powershell-7.3) (as of May 2022), and therefore [support for it was removed](https://github.com/PowerShell/PowerShellEditorServices/pull/1967), hence the error you're getting. Please upgrade to PowerShell 7.2 LTS or 7.3, latest release.

**Comment by andschwa** [comment]
@schwinbp, @AdamGrossTX, and @soulshined can you please confirm exactly what version of PowerShell you're using?

**Comment by soulshined** [comment]
> @schwinbp, @AdamGrossTX, and @soulshined can you please confirm exactly what version of PowerShell you're using?

```
> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7        0        2
```

I can't update my PowerShell, it's locked under a group policy. I'll continue to uses default tasks.

I see now in the Readme the required version is clearly stated, but as demonstrated by the previous reports, the surprise of the error messages and lack of concise reasoning was a tad frustrating to deal with. I think a more of a direct message in the alert box or log in the output channel would clear a lot of this up instead of what it does now would be helpful. It just runs and runs until it says "taking too long" or status 'undefined' reason 'undefined'. Those are very ambiguous and hard to troubleshoot, therefore hard to get you the info you need to reproduce. 

But thanks for the update!

**Comment by andschwa** [comment]
@soulshined _please_ inform your administrator that the group policy is enforcing an end-of-life version of PowerShell. That is, it is _not_ receiving any updates, [nor is the underlying version of .NET](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) and this is actually quite risky:

> Your use of out-of-support .NET versions may put your applications, application data, and computing environment at risk. You are strongly recommended to not use out-of-support software.

You are right, a better error message would be great. We've so far not done a "pre-emptive" version test of PowerShell because of the amount of time it takes to determine the version of PowerShell being executed. That is, PowerShell has to start before we can get its version (like, we'd need to run `pwsh -Command '$PSVersionTable'`) and that can actually take quite some time, so it would slow down startup significantly. But you're giving me the idea that, upon failure to start the server, we should _then_ run that command and check the version, and if it's out of date, say so.

Hey, at least we got the update notifier working 😄

**Comment by soulshined** [comment]
> @soulshined _please_ inform your administrator that the group policy is enforcing an end-of-life version of PowerShell. That is, it is _not_ receiving any updates, [nor is the underlying version of .NET](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) and this is actually quite risky:
> 
> 
> 
> > Your use of out-of-support .NET versions may put your applications, application data, and computing environment at risk. You are strongly recommended to not use out-of-support software.
> 
> 
> 
> You are right, a better error message would be great. We've so far not done a "pre-emptive" version test of PowerShell because of the amount of time it takes to determine the version of PowerShell being executed. That is, PowerShell has to start before we can get its version (like, we'd need to run `pwsh -Command '$PSVersionTable'`) and that can actually take quite some time, so it would slow down startup significantly. But you're giving me the idea that, upon failure to start the server, we should _then_ run that command and check the version, and if it's out of date, say so.
> 
> 
> 
> Hey, at least we got the update notifier working 😄 

Not the end of the world to use tasks. Just glad it's sorted out and future users can find this. And trust me I would love to update. Enterprise is enterprise what ya gonna do. 

Sorry I don't know what all goes into the extension as I haven't looked that deep into it. If vscode doesn't offer prequiste flags outside of package json I would assume spawning a simple node child process to grab the version would suffice prior to trying to load the language server and such. Just slightly confused by your verbiage of 'Powershell must start' But I'll leave that up to you pros! I'm just living in your world

**Comment by andschwa** [comment]
> If vscode doesn't offer prequiste flags outside of package json I would assume spawning a simple node child process to grab the version would suffice prior to trying to load the language server and such.

This is exactly what I meant, it takes a few seconds to do this because .NET / PowerShell is slow to start, so doing it _every time_ before we start the server has been a no-go. But the idea you gave me in this thread is to do it after connection fails, and use the info to make an informed error message.

**Comment by teekay** [comment]
I had the exact same problem, and upgrading PowerShell from `7.1.0` to `7.3.1`, which is currently the last version, solved this for me.

**Comment by Ted-A** [comment]
I was experiencing the same issue. Downgrading the VS Code PS extension version to 2022.11.0 resolved the issue.

Error with the latest PS extension:
![image](https://user-images.githubusercontent.com/44957527/217413704-33faec3c-c56d-480f-811a-861c9fdb3167.png)

Current PS Version:
![image](https://user-images.githubusercontent.com/44957527/217413779-7952e1d5-524e-4c03-a5cd-934b9e4bffeb.png)

VS Code PS Extension version:
![image](https://user-images.githubusercontent.com/44957527/217414165-d633c3ee-b18d-4a7f-930f-c1d9deb754f9.png)

**Comment by andschwa** [comment]
@Ted-A you're trying to use PowerShell 7.1 still. However, that version of PowerShell is [past its official end of life](https://learn.microsoft.com/en-us/powershell/scripting/install/PowerShell-Support-Lifecycle?view=powershell-7.3) (as of May 2022), and therefore [support for it was removed](https://github.com/PowerShell/PowerShellEditorServices/pull/1967), hence the error you're getting. Please [upgrade to PowerShell 7.2 LTS or 7.3](https://github.com/PowerShell/PowerShell), latest release.

**Comment by schwinbp** [comment]
Hey gang...sorry for delayed response but I was on vacation. I just upgraded to PS 7.3.* and it is working now. Upgrade took awhile. Thanks for the help.

**Comment by andschwa** [comment]
Great news, thanks for the follow up @schwinbp!

**Comment by vexx32** [comment]
So I get deprecating these versions, I do. 

Is there really no way to give users a better error, though? That's a really confusing error to get and doesn't at all point anyone in the right direction to fix things. A short and sweet "the version of PowerShell you're using might be out of date, please update it" would be _significantly_ more helpful.

**Comment by pcgeek86** [comment]
> Is there really no way to give users a better error, though?

Providing vague and obscure error messages is the "_way of the developer._" How dare you expect a developer to actually expose useful error messages with suggested corrective actions?

**Comment by SeeminglyScience** [comment]
> Is there really no way to give users a better error, though?

There sure is! Andy talks about the plan to add one a few comments up :P ([here](https://github.com/PowerShell/vscode-powershell/issues/4371#issuecomment-1411300606)) (I missed it too initially FWIW)

**Comment by aarondel4** [comment]
> I was experiencing the same issue. Downgrading the VS Code PS extension version to 2022.11.0 resolved the issue.

Same here.  Maybe because this extension uses the year as it's major version number, this issue crops up in January to bring work to a halt.

The downgrade option is found by going to Extensions, scrolling through your Installed extensions to find your Powershell extension.  Uncheck Auto Update, then hit the arrow next to Uninstall to install specific version.

![Image](https://github.com/user-attachments/assets/fb9abb85-d2a0-4fe6-94ac-6c3e10f487d4)

**Comment by JustinGrote** [comment]
If you are in an environment that cares more about running an unsupported version of PowerShell, with all the potential CVEs and vulnerabilities that will go unfixed because it is *unsupported*, than it does the effort to run an MSI or automated windows update to the latest LTS version at a minimum (7.4 as of this writing), then yes, I suppose it would be a viable workaround, but we don't recommend it.

**Comment by aarondel4** [comment]
> If you are in an environment that cares more about running an unsupported version of PowerShell, with all the potential CVEs and vulnerabilities that will go unfixed because it is _unsupported_, than it does the effort to run an MSI or automated windows update to the latest LTS version at a minimum (7.4 as of this writing), then yes, I suppose it would be a viable workaround, but I don't recommend it.

You don't understand what a constrained environment is.  I leave it at that since you're taking such an adversarial stance.  Not really pertinent to this thread.

**Comment by JustinGrote** [comment]
> You don't understand what a constrained environment is. I leave it at that since you're taking such an adversarial stance. Not really pertinent to this thread.

Constrained or not, the version you are running is unsupported. Simple as that.

**Comment by aarondel4** [comment]
> > You don't understand what a constrained environment is. I leave it at that since you're taking such an adversarial stance. Not really pertinent to this thread.
> 
> Constrained or not, the version you are running is unsupported. Simple as that.

I didn't request support. Simple as that.
