### ISSUE TITLE
Make the editor more context aware, as not to unnecessarily show snippets in the wrong places

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/vscode-powershell#4374]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

If I am splatting a command, currently I have to have to either have all snippets show, which is unneeded noise, or have my editor configured to show no snippet suggestions, where ideally it should be able to be context aware and not show me snippets, instead of disabling snippet suggestions outright

**Comment by andschwa** [comment]
Hm, interesting idea, but this probably something you should ask of the VS Code team. While the extension does bundle some snippets, the logic around "when to show the snippet" is not owned by the extension but by Code (and it just shows all snippets).

**Comment by kilasuit** [comment]
Done, now lets see what they say :-)
