### ISSUE TITLE
Use Of Variables in For-EachObject -Begin block Not Recognized Correctly

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/vscode-powershell#4380]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

The VS Code PowerShell extension doesn't correctly identify the use of variables declared in a `For-EachObject` `-Begin` block.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Datum: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
Betriebssystem: Windows_NT x64 10.0.19044
Sandkasten: No
```

### Extension Version

```console
v2022.12.1
```

### Steps to Reproduce

```powershell
ForEach-Object -Begin { $idx = 1 } -Process { ++$idx; $idx; }
```

### Visuals

![PowerShell iterator issue](https://user-images.githubusercontent.com/9283914/212769851-abb9e5ae-4ce2-419c-88ba-4329b8634986.png)

**Comment by SeeminglyScience** [comment]
Duplicate of PowerShell/PSScriptAnalyzer#1641

**Comment by SeeminglyScience** [comment]
Thanks for the report! We're tracking this in the linked issue above.
