### ISSUE TITLE
Terminal does not display Variable output

### ISSUE THREAD

**Issue by lotekjunky** [PowerShell/vscode-powershell#4390]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When using the "PowerShell Extension" terminal, none of the values are ever echoed back to the terminal. When typing a bad command, i receive feedback, but not when attempting to display output.

I think this is the same issue as #4114 which was closed unresolved.

This is what I expect (regular psh window):
![image](https://user-images.githubusercontent.com/29106552/214151065-2023fa02-41b2-4c3b-ba67-ac72af46fbdd.png)

This is how the terminal responds:
![image](https://user-images.githubusercontent.com/29106552/214151330-96e8a514-d0a0-44ae-bf08-09827e33521d.png)

As you can see, the variable contains data but the terminal will not show it.
![image](https://user-images.githubusercontent.com/29106552/214151687-2b338f9a-bcba-44ea-9a47-c9fea1809d11.png)

Here the terminal is not reacting to any output from commands unless there is an actual error:
the "code" command returns no output
the $psversintable returns no output
get-aduser followed by real user alias (a valid command) returns nothing
get-aduser FAKEUSER is expected to produce an error, and it does.
![image](https://user-images.githubusercontent.com/29106552/214423258-f564e4d4-0f51-42e4-a162-02cfc645ac84.png)

Note that if I open a new terminal using a newer version of powershell, the output works as expected, but I must keep 5.1 for legacy scripts.
![image](https://user-images.githubusercontent.com/29106552/214154015-2e43a162-d241-4cb3-97d8-f0bf1e0b3149.png)

### PowerShell Version

```console
PS C:\WINDOWS\system32> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.963}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
PS C:\> code --version
1.74.3
97dec172d3256f8ca4bfb2143f3f76b503ca0534
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.1.0
```

### Steps to Reproduce

Have script open, get input stored into variable (I think, save the script) - variables no longer output.

**Comment by SydneyhSmith** [comment]
Thanks @lotekjunky looks related to #3991

**Comment by lotekjunky** [comment]
Why was this closed without fixing? #4114 was closed due to inactivity and it was stated to reopen the ticket in the future. Well, I recreated the ticket with sufficient data, it took a good hour to collect all that info... and it still doesn't work. Now this issue is closed too.

**Comment by andschwa** [comment]
This is a duplicate of #3991, as was #4114, so we're already tracking it in the former and so closed the latter and this one as duplicates.

**Comment by lotekjunky** [comment]
Oh, so why did #4114 say to reopen because there had not been any updates in a week. Whatever.

**Comment by andschwa** [comment]
Because we're not perfect and it got mislabeled.

**Comment by andschwa** [comment]
@lotekjunky do you know if you have `Start-Transcript` somewhere before all this happens?

**Comment by lotekjunky** [comment]
> @lotekjunky do you know if you have `Start-Transcript` somewhere before all this happens?

Nobody ever fixed it, it still doesn't work, it makes vs code terrible to use.
