### ISSUE TITLE
Introduce ILanguageClient facade to simplify IFeature implementations

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#440]
We need an `ILanguageClient` (or `ISession`?) interface that will enable the creation of a `LanguageClientWrapper` class which will abstract away the use of the real `LanguageClient` when the language server is started or restarted.  It needs to support the following features:

- Holding on to request and event subscriptions so that they can be re-subscribed for new `LanguageClient` instances
- Queueing events and requests that are sent while the `LanguageClient` is still in the process of connecting to the language server
- Providing general information about the current session, like the version of the PowerShell runspace we're using

This will make our existing `IFeature` implementations simpler by removing the requirement that they respond to `LanguageClient` changes when the session (re)starts.

**Comment by rjmholt** [comment]
Closing as defunct
