### ISSUE TITLE
Pwsh editor services can't reach server

### ISSUE THREAD

**Issue by natedawg20** [PowerShell/vscode-powershell#4404]
Type: <b>Bug</b>

When I open and edit a .ps1 file, the PowerShell (extension) terminal doesn't prompt for user input, just stuck on "startup". It should automatically show an interactive shell. When I close the "frozen" prompt, I get 3 errors mentioning "PowerShell Editor Services" can't reach the server and connection got "disposed".

Extension version: 2023.1.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics          (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.37GB (18.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>
![image](https://user-images.githubusercontent.com/99000334/216758919-894eb6b6-d90b-4ed0-8a0b-333c93c335b0.png)
![image](https://user-images.githubusercontent.com/99000334/216758923-0d1172d4-bdce-4eab-99bb-de6c095a5acf.png)

<br>
<br>
Edit: Added screenshots

**Comment by andschwa** [comment]
Hi,

Could you please provide more [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)?

Thanks!

**Comment by natedawg20** [comment]
@andschwa 

Sure, please see below and attached for requested details.

Note: I replaced my username with `<user>`, but let me know if there's anything else I need to provide.

- VS Code Version: 
  - 1.75.0
  - e2816fe719a4026ffa1ee0189dc89bdfdbafb164
  - x64
- PowerShell Extension Version:
   - ms-vscode.powershell@2023.1.0
- PowerShell Version Table results:
PSVersion:                      7.3.2
PSEdition:                      Core
GitCommitId:                    7.3.2
OS:                             Microsoft Windows 10.0.19044
Platform:                       Win32NT
PSCompatibleVersions:           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion:      2.3
SerializationVersion:           1.1.0.1
WSManStackVersion:              3.0
[support.zip](https://github.com/PowerShell/vscode-powershell/files/10693736/support.zip)

Thanks!

**Comment by SydneyhSmith** [comment]
Thanks based on the logs it looks like it was started and connected but then shut down, diagnostic logging would help us pin point the issue

**Comment by natedawg20** [comment]
Hey @SydneyhSmith ,

I believe I added doagnostic logs into my last reply. If you click the linked "support.zip" link. 
Let me know if there's anything I am missing though

**Comment by andschwa** [comment]
I'm only seeing normal/error/info in your logs sadly. One of those however is:

> [INF] ReadLine overridden with 'Microsoft.PowerShell.EditorServices.Services.PowerShell.Console.PsrlReadLine'


Which at least indicates that PSES (the server) _has_ started and actually gotten pretty [far along](https://github.com/PowerShell/PowerShellEditorServices/blob/ca227b506517f3439aa52efba8d1a5c2a829b7b1/src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs#L1168-L1169) in the start-up sequence. So if you can get the [`powershell.developer.editorServicesLogLevel`](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#logs) set to `Diagnostic` and try again, I can figure out where it's getting stuck.

**Comment by natedawg20** [comment]
@andschwa ,

Hmm....strange....
<br>
I can't say I'm surprised it's hard to track down as the steps to reproduce have a super small window for errors to show.

I'm having trouble seeing an obvious error myself as it literally goes through pwsh's "startup" sequence before halting completely. If I delete the extension's session, click "relaunch" when VSCode notices it was killed, I get a column of different errors saying it can't find the "Editor Services" connection (that server you mentioned, I believe). I also tried setting the log to diagnostic, but after recreating the issue and closing VSCode, it never created a "Logs" folder (at least, per the linked document). See below screenshots for what I was (or wasn't) seeing
<br>
![image](https://user-images.githubusercontent.com/99000334/219849016-669af4e8-4a0e-4670-926a-43f5c280e5eb.png)

<br>
![image](https://user-images.githubusercontent.com/99000334/219848872-6f8f985e-6eb2-4f17-86ab-87865fd4fa60.png)

<br>

![image](https://user-images.githubusercontent.com/99000334/219848885-65ba6f9e-545a-4d1e-88f1-70880f12027c.png)

**Comment by andschwa** [comment]
Bad bot!

**Comment by andschwa** [comment]
Do you have any extra security software running on your computer? It sure looks like the Extension Terminal and associated language server started just fine, but that it and the client weren't able to establish a connection over the named pipe.
