### ISSUE TITLE
Problems tab does not include all problems reported by PSScriptAnalyzer

### ISSUE THREAD

**Issue by david-tap** [PowerShell/vscode-powershell#4421]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Here is a sample function:
```
function Set-Numeric {[CmdletBinding()] param([Parameter(ValueFromPipeline)]$a,[string]$b,$c) $a.save(); $c |%{
    @($a.$b.cells['A1:Z1'].value).indexof($_)+1 |set-ExcelColumn -ExcelPackage $a -WorksheetName $b -NumberFormat '$#,##0.00;-$#,##0.00;"- "'};
$a.save()}
```
When opening this in a file, I see a single problem:
`[{
	"resource": "Untitled-1",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "PSAvoidUsingCmdletAliases",
	"severity": 4,
	"message": "'%' is an alias of 'ForEach-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.",
	"source": "PSScriptAnalyzer",
	"startLineNumber": 1,
	"startColumn": 110,
	"endLineNumber": 1,
	"endColumn": 111
}]`

![Code_duFbPD8P7d](https://user-images.githubusercontent.com/30057778/219111173-771e09b5-ee7a-40e4-af53-73bfecea32a5.png)
Running the script analyzer on this definition shows 4 issues.

### PowerShell Version

```console
PS> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS > code --version
1.75.1
441438abd1ac652551dbe4d408dfcec8a499b8bf
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.1.0
```

### Steps to Reproduce

Here is a sample function:
```
function Set-Numeric {[CmdletBinding()] param([Parameter(ValueFromPipeline)]$a,[string]$b,$c) $a.save(); $c |%{
    @($a.$b.cells['A1:Z1'].value).indexof($_)+1 |set-ExcelColumn -ExcelPackage $a -WorksheetName $b -NumberFormat '$#,##0.00;-$#,##0.00;"- "'};
$a.save()}
```
When opening this in a file, I see a single problem:
`[{
	"resource": "Untitled-1",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "PSAvoidUsingCmdletAliases",
	"severity": 4,
	"message": "'%' is an alias of 'ForEach-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content.",
	"source": "PSScriptAnalyzer",
	"startLineNumber": 1,
	"startColumn": 110,
	"endLineNumber": 1,
	"endColumn": 111
}]`

![Code_duFbPD8P7d](https://user-images.githubusercontent.com/30057778/219111173-771e09b5-ee7a-40e4-af53-73bfecea32a5.png)
Running the script analyzer on this definition shows 4 issues.

### Visuals

![image](https://user-images.githubusercontent.com/30057778/219111635-c01eb3fe-1667-45c8-b5ee-5169af816307.png)
![image](https://user-images.githubusercontent.com/30057778/219111708-9e95d065-4400-4b5a-9270-a40bd8289022.png)

**Comment by andschwa** [comment]
I don't think it's particularly well documented, but there's essentially a [default set of rules](https://github.com/PowerShell/PowerShellEditorServices/blob/bbdf98db30af3dd423bb2d6ae4d425d13fb01d5b/src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs#L253-L344) based on a combination of settings in the client and defaults server-side that we provide to PSScriptAnalyzer, but you should be able to [use your own settings](https://github.com/PowerShell/vscode-powershell/blob/main/examples/PSScriptAnalyzerSettings.psd1) file to enable _all_ of them if you wish.

**Comment by david-tap** [comment]
> I don't think it's particularly well documented, but there's essentially a [default set of rules](https://github.com/PowerShell/PowerShellEditorServices/blob/bbdf98db30af3dd423bb2d6ae4d425d13fb01d5b/src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs#L253-L344) based on a combination of settings in the client and defaults server-side that we provide to PSScriptAnalyzer, but you should be able to [use your own settings](https://github.com/PowerShell/vscode-powershell/blob/main/examples/PSScriptAnalyzerSettings.psd1) file to enable _all_ of them if you wish.

Those rules affect only the Code Formatting features, as far as I can see. I see no list of default rules at that link.

**Comment by andschwa** [comment]
Hmm I'll check with @SeeminglyScience
