### ISSUE TITLE
Request: Terminal Change "Run Code" 

### ISSUE THREAD

**Issue by Shxpard** [PowerShell/vscode-powershell#4424]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I would like to have the terminal show: 
`PS> C:\Example`
`Hello World`

Instead of:
`PS> `
*Run*
`PS>. 'C:\Example'`
`Hello World`
`PS> C:\`
*Run*
`PS>. 'C:\Example'`
`Hello World`
`PS> C:\`

This occurs with the ISE and works with v2021.12.0.
However with the newer version of the Powershell Extension it seems to really clutter the output.
![WantedBehavior](https://user-images.githubusercontent.com/38823837/219735736-09117746-b119-4222-8b7c-7b91cb1d3608.png)
<img width="1240" alt="UnwantedBehavior" src="https://user-images.githubusercontent.com/38823837/219735818-2befad80-437f-4eea-bcce-cb591cad44c3.png">

### Proposed Design

I have no idea how the design of this works. I do think there was some intention behind the change but figured I would post this. I'm not a power user as others may be, so I'm not sure if this aesthetic design is actually practical or not.

**Comment by andschwa** [comment]
Hi, the change is to show _exactly_ what's bring run. In this case, a dot-source of the file (as opposed to an ampersand-call, like #4327 asks to make as an option). As it is, the implementation is simply just showing what exactly is being run, so we don't really want to add any special logic to hide that `. ` prefix if (and only if!) it was requested by the Run Code command. It's less aesthetics and more...precision. Does that make sense?

**Comment by Shxpard** [comment]
Of course. I expected as much that it would be for precise for users. Thank you for your help.
