### ISSUE TITLE
Impossible to hide the integrated terminal

### ISSUE THREAD

**Issue by TooManyDots** [PowerShell/vscode-powershell#4427]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I have this configuration copy-pasted from your site ( https://code.visualstudio.com/docs/typescript/typescript-debugging ).

Whenever i start this configuration the UI switches to the terminal tab ( which i never wanted to begin with, why do you that? ).
Then i rightclick the tab to hide this terminal that i never wanted to see. It disappears.
I relaunch the configuration.
The tab appears again, despite me having it hidden. You can even see in the UI that i have it marked as hidden.

![image](https://user-images.githubusercontent.com/35289254/220032928-1e52a166-3305-4068-b252-3478fb7ac7a7.png)

Bug A: The editor is randomly changing which tab is displayed without me saying so.
Bug B: My setting of not showing the terminal-tab is not respected.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.75.1
441438abd1ac652551dbe4d408dfcec8a499b8bf
x64
```

### Extension Version

```console
An empty string is returned, but your great interface doesn't allow me to put an empty string here, so i have to type something. Very competent.
```

### Steps to Reproduce

I am not supporting your bureaucracy by copy pasting my description.

**Comment by andschwa** [comment]
Hey @TooManyDots this repo is for the PowerShell extension, I think you're looking for VS Code's repo at: https://github.com/microsoft/vscode
