### ISSUE TITLE
Add some way to generate overrides for PowerShell classes

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/vscode-powershell#4432]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

When writing classes that need to override members, like a custom validation attribute:
```
class DemoValidationAttribute: System.Management.Automation.ValidateArgumentsAttribute
{
}
```
You need to manually specify the overrides. It would be nice if it was like the C# experience in VS where you get to pick the members to override and it generates some boilerplate code you can modify:
![image](https://user-images.githubusercontent.com/42123497/221290046-d8e6e490-4424-496c-bfe0-aa60abc01b4d.png)
![image](https://user-images.githubusercontent.com/42123497/221290695-1314eeaf-447d-4ba2-82c6-2a1d5b5c7908.png)
Maybe it would make sense to implement some of the analysis work needed to do this in PowerShell itself so other editors gets to benefit from this work as well?

**Comment by SydneyhSmith** [comment]
Thanks @MartinGC94 this is available today in https://github.com/SeeminglyScience/EditorServicesCommandSuite
