### ISSUE TITLE
Powershell Extension do not start

### ISSUE THREAD

**Issue by alexappiani** [PowerShell/vscode-powershell#4439]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Powershell Extension do not start.
It says:
"PowerShell extension has not finished starting up yet. Please try again in a few moments."

It happens on both my "PC": Windows 11 & MacOS (M1 chip).
Powershell core 7.3.2 on both platform.
Info below based on macos.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

### Extension Version

```console
Published
11/18/2015, 01:50:38
Last released
2/23/2023, 21:26:31
Last updated
2/24/2023, 16:44:50
Identifier
ms-vscode.powershell
```

### Steps to Reproduce

Powershell extensions do not start. It says:
"PowerShell extension has not finished starting up yet. Please try again in a few moments."
It happens on both my "PC": Windows 11 & MacOS (M1 chip).
Powershell core 7.3.2 on both platform.
Execution policy (on Macos):
PS /Users/alex/Temp> Get-ExecutionPolicy -List                       

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    Unrestricted
   UserPolicy    Unrestricted
      Process    Unrestricted
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted

Please let me know!
Thanks,
Alessandro

**Comment by SydneyhSmith** [comment]
Thanks @alexappiani appreciate you opening the issue, could you please also provide logs? Thanks!
