### ISSUE TITLE
Intellisense does not work for commands only existing in 5.1

### ISSUE THREAD

**Issue by AlexHimself** [PowerShell/vscode-powershell#4440]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I'm typing the command `New-JobTrigger` and expecting `-Once` to be available from intellisense, but it is not.

I'm not sure if this is for other 5.1 only commands or just some.

https://learn.microsoft.com/en-us/powershell/module/psscheduledjob/new-jobtrigger?view=powershell-5.1&viewFallbackFrom=powershell-7.3

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.75.1
441438abd1ac652551dbe4d408dfcec8a499b8bf
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.2.1
ms-vscode.powershell-preview@2023.2.1
```

### Steps to Reproduce

1. Type `New-JobTrigger`
2. Then type `-O` and press `Ctrl+Space`
3. Verify if `-Once` is suggested.

### Visuals

![image](https://user-images.githubusercontent.com/10466466/222238499-45afdde8-1f8f-42f7-8220-d324afc6eb66.png)

**Note:** I see `-Onc` in my screenshot, which appears to be an artifact from typing that previously?

Works in stand-alone PS.
![image](https://user-images.githubusercontent.com/10466466/222238775-850c9926-61df-4b3a-a2d8-35d8c560b78e.png)

This image is from a different server:
![image](https://user-images.githubusercontent.com/10466466/222239037-6e449a8d-bb39-4fd3-89cb-68a33ae52f56.png)

### Logs

Can provide if needed, but since this is very simple to reproduce (or not) they probably won't be.

**Comment by andschwa** [comment]
I think this is related to the poor support of parameter signature help (that's what you're triggering) and I identified while rewriting the symbols work that we do some _weird_ stuff to parameter completions. If I remember correctly, for some reason we only supply the "sets" as completions and that means we lose most parameters. It was weird and needs fixing!

**Comment by SeeminglyScience** [comment]
We get completion options from PowerShell itself, so make sure you've selected 5.1 as the version for the Extension terminal:

📌 __UI__
    🔸 Click the brackets (`{}`) in the lower right corner
    🔸 Click `Show PowerShell Session Menu`
    🔸 (Optional: Click the pin next to `Show PowerShell Session Menu` to add a clickable version number to the status bar)
    
📌 __Command Palette__
    🔸 Press `Ctrl` + `Shift` + `P`
    🔸 Type `Session`
    🔸 Select `PowerShell: Show Session Menu`

**Comment by AlexHimself** [comment]
> We get completion options from PowerShell itself, so make sure you've selected 5.1 as the version for the Extension terminal:
> 
> 📌 **UI** 🔸 Click the brackets (`{}`) in the lower right corner 🔸 Click `Show PowerShell Session Menu` 🔸 (Optional: Click the pin next to `Show PowerShell Session Menu` to add a clickable version number to the status bar)
> 
> 📌 **Command Palette** 🔸 Press `Ctrl` + `Shift` + `P` 🔸 Type `Session` 🔸 Select `PowerShell: Show Session Menu`

I just tried that and I'm getting (PS Preview):

> Additional PowerShell 'PS 5.1' not found at '%windir%\System32\WindowsPowerShell\v1.0\powershell.exe'!

I confirmed I do have `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe` and ran VSCode as both admin and non-admin.

**Comment by andschwa** [comment]
Well that's weird. Can you check that file's attributes, is it a "regular" file or maybe a symlink? (I mean, it should be fine if it's a symlink, and it'd be weird if it were a symlink). Could you also check what `%windir%` resolves to in the VS Code environment?

**Comment by andschwa** [comment]
I wonder if it's failing due to an unexceptional exception like talked about in https://github.com/microsoft/vscode/issues/171440 since that's what we use underneath to check for existence.

**Comment by SeeminglyScience** [comment]
> We get completion options from PowerShell itself, so make sure you've selected 5.1 as the version for the Extension terminal:
> > 📌 **UI** 🔸 Click the brackets (`{}`) in the lower right corner 🔸 Click `Show PowerShell Session Menu` 🔸 (Optional: Click the pin next to `Show PowerShell Session Menu` to add a clickable version number to the status bar)
> > 📌 **Command Palette** 🔸 Press `Ctrl` + `Shift` + `P` 🔸 Type `Session` 🔸 Select `PowerShell: Show Session Menu`
> 
> I just tried that and I'm getting (PS Preview):
> 
> > Additional PowerShell 'PS 5.1' not found at '%windir%\System32\WindowsPowerShell\v1.0\powershell.exe'!
> 
> I confirmed I do have `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe` and ran VSCode as both admin and non-admin.

Can you post your `settings.json`? That sounds like you've manually configured an additional entry for 5.1, but I don't think that setting has support for expanding environment variables with that syntax
