### ISSUE TITLE
'Go To Definition' does not work when the variable is defined with type hint

### ISSUE THREAD

**Issue by ALiwoto** [PowerShell/vscode-powershell#4443]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When defining a variable using type hint (e.g. `[string]$helloStr = "hi"`), Go to definition no longer works; however if I remove the `[string]` part the the beginning, it will work fine.

**Does not work:**
```ps1
[string]$hello = "test"
Write-Host $hello # no definition found for '$hello'
```

**works fine:**
```ps1
$hello = "test"
Write-Host $hello # it goes to the line of definition
```

### PowerShell Version

```console
PS> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS> code --version


1.76.0
92da9481c0904c6adfe372c12da3b7748d74bdcb
x64
```

### Extension Version

```console
PS> code --list-extensions --show-versions | Select-String powershell


ms-vscode.powershell@2023.2.1
```

### Steps to Reproduce

Define a variable while specifying its type behind it and try to press `F12` (or `ctrl + left-click` or click on `Go to definition` from right-click context menu).

### Visuals

![image](https://user-images.githubusercontent.com/70187458/222891250-6ce69a2c-8f14-4e60-9387-573b37177541.png)

![image](https://user-images.githubusercontent.com/70187458/222891231-52c0e753-d728-4e08-a77e-bf72f00aba9e.png)

**Comment by andschwa** [comment]
Oo, good find! I'll see if I can get this fixed soon.
