### ISSUE TITLE
Language Service 0.8.0 exits with exception in code insiders 1.9.0

### ISSUE THREAD

**Issue by marking** [PowerShell/vscode-powershell#445]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: Windows 10 64bit (1607 -- 14393.693)
- VS Code version: insiders 1.9.0
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Language service exits with exception. I believe it is because the path of a newly added file to the folder is being sent as `git:/c%3A/path/to/file.ps1`

### Attached Logs
[Logs.zip](https://github.com/PowerShell/vscode-powershell/files/717047/Logs.zip)

**Comment by daviwil** [comment]
Yep, found and fixed that one already.  Fix will be coming out with 0.9.0 within a couple hours.

**Comment by marking** [comment]
At least I know I'm not crazy.

**Comment by daviwil** [comment]
Yeah, it's a weird new thing that popped up in yesterday's Insider release.  Thanks for taking the time to report it!
