### ISSUE TITLE
Script formatting should allow setting for space between keyword and opening paren

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#446]
For instance, I prefer to see:
```powershell
if (Test-Path foo) {
   "Foo exists!"
}
```
instead of
```powershell
if(Test-Path foo) {
   "Foo exists!"
}
```
Same would apply to other keywords: `elseif`, `for`, `foreach`, `while`, `switch`, etc.

**Comment by daviwil** [comment]
This should also cover spaces around equals signs, like in this example:

```powershell
foreach($thing in $list){$result=Get-Thing $thing}
```

The resulting output should be:

```powershell
foreach ($thing in $list) {
    $result = Get-Thing $thing
}
```

**Comment by Jaykul** [comment]
And the space after the closing parenthesis that you *both* added. 
And making sure it's only *one* space. Currently it doesn't even do that.
