### ISSUE TITLE
Get-Content does not support Byte Streams 

### ISSUE THREAD

**Issue by RandyDotCom** [PowerShell/vscode-powershell#4463]
A parameter cannot be found that matches parameter name 'AsByteStream'.
A parameter cannot be found that matches parameter name 'Encoding'. 
Neither Parameter is available in the VS Code Terminal 
This is a breaking change for me 
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core 
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

_Originally posted by @RandyDotCom in https://github.com/PowerShell/PowerShell/issues/14537#issuecomment-1472857542_

**Comment by andschwa** [comment]
I can't repro this. `-AsByteStream` and `-Encoding` are both showing up in the PowerShell Extension terminal for me.

**Comment by RandyDotCom** [comment]
The appear as a parameter in vs code intelligence, but not on execution
I am using this against 509 Certificates "pfx" files 
 
$fileContentBytes = get-content "$cerpath" -AsByteStream
   A parameter cannot be found that matches parameter name 'AsByteStream'.

$fileContentBytes = get-content "$cerpath" -Encoding Byte 
   A parameter cannot be found that matches parameter name 'Encoding'.


using the command *-Encoding Byte* in** powershell 
PSVersion                      5.1.19041.2364                                                                                                                                                                         
PSEdition                      Desktop  

Still works

**Comment by aguzev** [comment]
> The appear as a parameter in vs code intelligence, but not on execution I am using this against 509 Certificates "pfx" files
> 
> $fileContentBytes = get-content "$cerpath" -AsByteStream A parameter cannot be found that matches parameter name 'AsByteStream'.

The content of the **$certpath** variable might be important. Could you share its value?

The following code produces same error on PS 5.1 and PS 7.3.3.

```powershell
PS> gci cert:* | Get-Content -Encoding Byte
Get-Content : Cannot use interface. The IContentCmdletProvider interface is not implemented by this provider.
At line:1 char:14
…
```

```powershell
PS> gci cert:* | get-Content -AsByteStream
Get-Content: Cannot use interface. The IContentCmdletProvider interface is not implemented by this provider.
```

**Comment by RandyDotCom** [comment]
The -encoding Byte in PS version 5.0 Works on any Valid PFX file, The Path is irrelevant.,

**Comment by SeeminglyScience** [comment]
@RandyDotCom The way you retrieve bytes from a file is different between the two PowerShell versions. In 5.1 you use `-Encoding Byte`, in 7+ you use `-AsByteStream`.

You can change the version of PowerShell running in the PowerShell extension terminal like this:

📌 __UI__
    🔸 Click the brackets (`{}`) in the lower right corner
    🔸 Click `Show PowerShell Session Menu`
    🔸 (Optional: Click the pin next to `Show PowerShell Session Menu` to add a clickable version number to the status bar)
    
📌 __Command Palette__
    🔸 Press `Ctrl` + `Shift` + `P`
    🔸 Type `Session`
    🔸 Select `PowerShell: Show Session Menu`

**Comment by aguzev** [comment]
> The -encoding Byte in PS version 5.0 Works on any Valid PFX file, The Path is irrelevant.,

This is only the case when the path points to a file. For instance, the **cert:** drive is not provided by FileSystemProvider, and **cert:…** paths are not pointing pointing at files.
