### ISSUE TITLE
Crash running formatter on new, untitled document

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/vscode-powershell#447]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version:
Windows 10 AU
- VS Code version:
1.9.0-Insider
- PowerShell extension version:
0.9.0
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
Crash when calling format document on a new unsaved document.

### Steps to repro
Create a New File
Set the Syntax to PowerShell
Write something in it, like
```posh
foreach($thing in $list){$result=Get-Thing $thing}
```
Then hit "Format Document" (e.g. `alt+shift+f`)

### Attached Logs

[1484856115-dfce8230-a989-4c8e-85bd-d9a055a6031d1484856005946.zip](https://github.com/PowerShell/vscode-powershell/files/717645/1484856115-dfce8230-a989-4c8e-85bd-d9a055a6031d1484856005946.zip)

**Comment by daviwil** [comment]
This is happening for new script files that haven't been saved yet, they are still marked as "Untitled".  If you create a new file, paste in Joel's example script, click the file type selector in the status bar and turn it to PowerShell then hit <kbd>Shift+Alt+F</kbd>, you'll see the crash.  Here's the exception from the logs:

```
System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Microsoft VS Code Insiders\Untitled-1'
```

We basically just need to handle untitled files correctly.

/cc @kapilmb
