### ISSUE TITLE
Is there a way to not enable the powershell extension for WSL and only enable it locally?

### ISSUE THREAD

**Issue by markfaine** [PowerShell/vscode-powershell#4472]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I'd rather not have it in WSL but specifically for outside of WSL

**Comment by SydneyhSmith** [comment]
Thanks for opening the issue @markfaine! We don't fully understand what you are asking for, could you please provide additional context. Thanks!
