### ISSUE TITLE
Failed to start PowerShell Extension VsCode on Mac Ventura 13.3 M1

### ISSUE THREAD

**Issue by jcstorino** [PowerShell/vscode-powershell#4497]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

PowerShell extension not load...

`05/04/2023 11:35:44 [NORMAL] -     PowerShell Editor Services args: Import-Module '/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2023.3.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2023.3.3
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
" -LogLevel 'Normal' -LogPath '/Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/logs/1680705343-b7385f7a-9f47-4169-9977-ce5d2963e2861680705342975/EditorServices.log' -SessionDetailsPath '/Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/sessions/PSES-VSCode-66251-378352.json' -FeatureFlags @() 

05/04/2023 11:35:44 [NORMAL] - pwsh started.

05/04/2023 11:35:44 [NORMAL] - Waiting for session file...

05/04/2023 11:36:14 [WARNING] - Loading the PowerShell extension is taking longer than expected. If you're using privilege enforcement software, this can affect start up performance.

05/04/2023 11:39:45 [NORMAL] - Timed out waiting for session file to appear!

05/04/2023 11:39:45 [ERROR] - PowerShell process failed to start: 

05/04/2023 11:39:45 [ERROR] - Timed out waiting for session file to appear!

05/04/2023 11:39:45 [ERROR] - Unknown session status 'undefined' with reason 'undefined
`

### PowerShell Version

```console
PS VSC > $psversionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS VSC > code --version                                                   
1.77.0
7f329fe6c66b0f86ae1574c2911b681ad5a45d63
arm64
```

### Extension Version

```console
PS VSC > code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2023.3.3
```

### Steps to Reproduce

Just open VSC and wait for extension load.

### Visuals

<img width="2032" alt="Captura de Tela 2023-04-05 às 11 45 58" src="https://user-images.githubusercontent.com/19559870/230117493-f914519e-cd93-4c12-b550-a54111a98f15.png">

### Logs

[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/11160232/vscode-powershell.log)

**Comment by jcstorino** [comment]
> 

Yes, I can open any pwsh in this path, and I have permission to write and write on it! Leaving only in the user's root the problem also occurs equally.

**Comment by andschwa** [comment]
Interesting...anyway you can enable more [logging and environment information by following these steps](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)?

Thanks! I'm especially interested in the server-side (PSES) logs.

**Comment by jcstorino** [comment]
Hi @andschwa ,
The powershell Log is being generated correctly and is the same one I have attached before, but the Language Server Log could not generate, the combo option does not appear in the list of Output Logs. What am I doing wrong?

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/19559870/230198798-c00397d4-85f4-4a79-983c-37e2669107f4.png">


[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/11162719/vscode-powershell.log)

**Comment by andschwa** [comment]
Per that link you gotta run the command `PowerShell: Open PowerShell Extension Logs Folder`, and then you should have a folder with three separate logs!

**Comment by jcstorino** [comment]
@andschwa 
I've been analyzing here, and only have one log file in the folder that is opened by the informed command !

<img width="1624" alt="Captura de Tela 2023-04-06 às 09 37 22" src="https://user-images.githubusercontent.com/19559870/230382209-04107e0d-d6bf-46da-8a94-bb9ef577acee.png">

<img width="1316" alt="Captura de Tela 2023-04-06 às 09 42 19" src="https://user-images.githubusercontent.com/19559870/230382195-ad18f5fb-6eec-4046-a414-4e7e8af8c703.png">

**Comment by andschwa** [comment]
HUH well, that indicates `pwsh` either never started at all, or crashed _really early_ in the initialization process (like before logging starts).

**Comment by andschwa** [comment]
I'm copying this out of your log, what happens if you try to run from a regular terminal (outside of VS Code) the startup command it was trying:

```
/usr/local/bin/pwsh -NoProfile -EncodedCommand SQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgACcALwBVAHMAZQByAHMALwBqAGMAcwB0AG8AcgBpAG4AbwAvAC4AdgBzAGMAbwBkAGUALwBlAHgAdABlAG4AcwBpAG8AbgBzAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AMgAwADIAMwAuADMALgAzAC8AbQBvAGQAdQBsAGUAcwAvAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC8AUABvAHcAZQByAFMAaABlAGwAbABFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBwAHMAZAAxACcAOwAgAFMAdABhAHIAdAAtAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAgAC0ASABvAHMAdABOAGEAbQBlACAAJwBWAGkAcwB1AGEAbAAgAFMAdAB1AGQAaQBvACAAQwBvAGQAZQAgAEgAbwBzAHQAJwAgAC0ASABvAHMAdABQAHIAbwBmAGkAbABlAEkAZAAgACcATQBpAGMAcgBvAHMAbwBmAHQALgBWAFMAQwBvAGQAZQAnACAALQBIAG8AcwB0AFYAZQByAHMAaQBvAG4AIAAnADIAMAAyADMALgAzAC4AMwAnACAALQBBAGQAZABpAHQAaQBvAG4AYQBsAE0AbwBkAHUAbABlAHMAIABAACgAJwBQAG8AdwBlAHIAUwBoAGUAbABsAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAuAFYAUwBDAG8AZABlACcAKQAgAC0AQgB1AG4AZABsAGUAZABNAG8AZAB1AGwAZQBzAFAAYQB0AGgAIAAnAC8AVQBzAGUAcgBzAC8AagBjAHMAdABvAHIAaQBuAG8ALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADMALgAzAC4AMwAvAG0AbwBkAHUAbABlAHMAJwAgAC0ARQBuAGEAYgBsAGUAQwBvAG4AcwBvAGwAZQBSAGUAcABsACAALQBTAHQAYQByAHQAdQBwAEIAYQBuAG4AZQByACAAIgBQAG8AdwBlAHIAUwBoAGUAbABsACAARQB4AHQAZQBuAHMAaQBvAG4AIAB2ADIAMAAyADMALgAzAC4AMwAKAEMAbwBwAHkAcgBpAGcAaAB0ACAAKABjACkAIABNAGkAYwByAG8AcwBvAGYAdAAgAEMAbwByAHAAbwByAGEAdABpAG8AbgAuAAoACgBoAHQAdABwAHMAOgAvAC8AYQBrAGEALgBtAHMALwB2AHMAYwBvAGQAZQAtAHAAbwB3AGUAcgBzAGgAZQBsAGwACgBUAHkAcABlACAAJwBoAGUAbABwACcAIAB0AG8AIABnAGUAdAAgAGgAZQBsAHAALgAKACIAIAAtAEwAbwBnAEwAZQB2AGUAbAAgACcARABpAGEAZwBuAG8AcwB0AGkAYwAnACAALQBMAG8AZwBQAGEAdABoACAAJwAvAFUAcwBlAHIAcwAvAGoAYwBzAHQAbwByAGkAbgBvAC8ATABpAGIAcgBhAHIAeQAvAEEAcABwAGwAaQBjAGEAdABpAG8AbgAgAFMAdQBwAHAAbwByAHQALwBDAG8AZABlAC8AVQBzAGUAcgAvAGcAbABvAGIAYQBsAFMAdABvAHIAYQBnAGUALwBtAHMALQB2AHMAYwBvAGQAZQAuAHAAbwB3AGUAcgBzAGgAZQBsAGwALwBsAG8AZwBzAC8AMQA2ADgAMAA3ADIANQAyADEAMwAtAGYAYQAxAGUAZAA5ADUAMwAtAGQANwA2ADgALQA0AGYAYwBiAC0AYgBkADIAMAAtADMAMwBlAGEANQA3AGYAZABkADcANABiADEANgA4ADAANwAyADUAMQA1ADQANgA3ADgALwBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBsAG8AZwAnACAALQBTAGUAcwBzAGkAbwBuAEQAZQB0AGEAaQBsAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBqAGMAcwB0AG8AcgBpAG4AbwAvAEwAaQBiAHIAYQByAHkALwBBAHAAcABsAGkAYwBhAHQAaQBvAG4AIABTAHUAcABwAG8AcgB0AC8AQwBvAGQAZQAvAFUAcwBlAHIALwBnAGwAbwBiAGEAbABTAHQAbwByAGEAZwBlAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC8AcwBlAHMAcwBpAG8AbgBzAC8AUABTAEUAUwAtAFYAUwBDAG8AZABlAC0ANwA4ADYAOAAzAC0ANQA3ADAAOAA5ADIALgBqAHMAbwBuACcAIAAtAEYAZQBhAHQAdQByAGUARgBsAGEAZwBzACAAQAAoACkAIAA=
```

That string is just these arguments encoded as base64:

```
Import-Module '/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2023.3.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2023.3.3
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
" -LogLevel 'Diagnostic' -LogPath '/Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/logs/1680725213-fa1ed953-d768-4fcb-bd20-33ea57fdd74b1680725154678/EditorServices.log' -SessionDetailsPath '/Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/sessions/PSES-VSCode-78683-570892.json' -FeatureFlags @() 
```

**Comment by jcstorino** [comment]
Running the entire command by pwsh (outside VSC), it seems to work correctly, see below!

`PS jcstorino > Import-Module '/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2023.3.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2023.3.3     
Copyright (c) Microsoft Corporation.  
https://aka.ms/vscode-powershell
Type 'help' to get help.
" -LogLevel 'Diagnostic' -LogPath '/Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/logs/1680725213-fa1ed953-d768-4fcb-bd20-33ea57fdd74b1680725154678/EditorServices.log' -SessionDetailsPath '/Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/sessions/PSES-VSCode-78683-570892.json' -FeatureFlags @()
DEBUG: Logging started
DEBUG: Beginning EndProcessing block
VERBOSE: Removing PSReadLine
VERBOSE: Removed PSReadLine
DEBUG: Creating host configuration
DEBUG: Determining REPL kind
DEBUG: REPL configured as PSReadLine
DEBUG: Configuring LSP transport
DEBUG: Configuring debug transport
DEBUG: Session file writer created
VERBOSE: Adding AssemblyResolve event handler for new AssemblyLoadContext dependency loading
VERBOSE: Loading EditorServices
VERBOSE: PID: 13184
VERBOSE: 
== Build Details ==
- Editor Services version: 3.8.3
- Build origin:            Release
- Build commit:            98e28e9638a9f355aaed861527c251542e456f4f
- Build time:              27/03/2023 00:00:00

VERBOSE: 
== Host Startup Configuration Details ==
 - Host name:                 Visual Studio Code Host
 - Host version:              2023.3.3
 - Host profile ID:           Microsoft.VSCode
 - PowerShell host type:      System.Management.Automation.Internal.Host.InternalHost

 - REPL setting:              PSReadLine
 - Session details path:      /Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/sessions/PSES-VSCode-78683-570892.json
 - Bundled modules path:      /Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules
 - Additional modules:        PowerShellEditorServices.VSCode
 - Feature flags:             

 - Log path:                  /Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/logs/1680725213-fa1ed953-d768-4fcb-bd20-33ea57fdd74b1680725154678/EditorServices.log
 - Minimum log level:         Diagnostic

 - Profile paths:
   + AllUsersAllHosts:       /usr/local/microsoft/powershell/7/profile.ps1
   + AllUsersCurrentHost:    /usr/local/microsoft/powershell/7/Microsoft.VSCode_profile.ps1
   + CurrentUserAllHosts:    /Users/jcstorino/.config/powershell/profile.ps1
   + CurrentUserCurrentHost: /Users/jcstorino/.config/powershell/Microsoft.VSCode_profile.ps1

DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: Microsoft.PowerShell.Security, Version=7.3.3.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
VERBOSE: 
== Console Details ==
 - Console input encoding: Unicode (UTF-8)
 - Console output encoding: Unicode (UTF-8)
 - PowerShell output encoding: Unicode (UTF-8)

VERBOSE: 
== PowerShell Details ==
- PowerShell version: 7.3.3
- Language mode:      FullLanguage

VERBOSE: 
== Environment Details ==
 - OS description:  Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
 - OS architecture: Arm64
 - Process bitness: 64

VERBOSE: Updated PSModulePath to: '/Users/jcstorino/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/usr/local/microsoft/powershell/7/Modules:/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules'
DEBUG: Validating configuration
VERBOSE: Loading PowerShell Editor Services
DEBUG: Assembly resolve event fired for Microsoft.PowerShell.EditorServices, Version=3.8.3.0, Culture=neutral, PublicKeyToken=null
VERBOSE: Loading PSES DLL using new assembly load context
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.PowerShell.EditorServices, Version=3.8.3.0, Culture=neutral, PublicKeyToken=null
VERBOSE: Starting EditorServices
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.Extensions.Logging, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog.Sinks.Async, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog.Extensions.Logging, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog.Sinks.File, Version=5.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.Extensions.Options, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
DEBUG: Creating/running editor services
DEBUG: Creating startup info object
VERBOSE: Starting server, deregistering host logger and registering shutdown listener
PowerShell Extension v2023.3.3
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
`

<img width="974" alt="image" src="https://user-images.githubusercontent.com/19559870/230465186-d0fe62e5-d2af-4ea5-920c-9b5f14065c7d.png">

**Comment by andschwa** [comment]
Even when the `cwd` is `/Users/jcstorino/Library/Mobile Documents/com~apple~CloudDocs/Work/VSC`?

...cause that's strange. If it's starting then it _should_ also be starting when the extension tries the same thing.

**Comment by jcstorino** [comment]
Yes! Even in this folder, the result is the same! It seems to work right!

`PS VSC > pwd

Path
----
/Users/jcstorino/Library/Mobile Documents/com~apple~CloudDocs/Work/VSC

PS VSC > Import-Module '/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2023.3.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2023.3.3
>> Copyright (c) Microsoft Corporation.
>> 
>> https://aka.ms/vscode-powershell
>> Type 'help' to get help.
>> " -LogLevel 'Diagnostic' -LogPath '/Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/logs/1680725213-fa1ed953-d768-4fcb-bd20-33ea57fdd74b1680725154678/EditorServices.log' -SessionDetailsPath '/Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/sessions/PSES-VSCode-78683-570892.json' -FeatureFlags @() 
DEBUG: Logging started
DEBUG: Beginning EndProcessing block
VERBOSE: Removing PSReadLine
VERBOSE: Removed PSReadLine
DEBUG: Creating host configuration
DEBUG: Determining REPL kind
DEBUG: REPL configured as PSReadLine
DEBUG: Configuring LSP transport
DEBUG: Configuring debug transport
DEBUG: Session file writer created
VERBOSE: Adding AssemblyResolve event handler for new AssemblyLoadContext dependency loading
VERBOSE: Loading EditorServices
VERBOSE: PID: 3002
VERBOSE: 
== Build Details ==
- Editor Services version: 3.8.3
- Build origin:            Release
- Build commit:            98e28e9638a9f355aaed861527c251542e456f4f
- Build time:              27/03/2023 00:00:00

VERBOSE: 
== Host Startup Configuration Details ==
 - Host name:                 Visual Studio Code Host
 - Host version:              2023.3.3
 - Host profile ID:           Microsoft.VSCode
 - PowerShell host type:      System.Management.Automation.Internal.Host.InternalHost

 - REPL setting:              PSReadLine
 - Session details path:      /Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/sessions/PSES-VSCode-78683-570892.json
 - Bundled modules path:      /Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules
 - Additional modules:        PowerShellEditorServices.VSCode
 - Feature flags:             

 - Log path:                  /Users/jcstorino/Library/Application Support/Code/User/globalStorage/ms-vscode.powershell/logs/1680725213-fa1ed953-d768-4fcb-bd20-33ea57fdd74b1680725154678/EditorServices.log
 - Minimum log level:         Diagnostic

 - Profile paths:
   + AllUsersAllHosts:       /usr/local/microsoft/powershell/7/profile.ps1
   + AllUsersCurrentHost:    /usr/local/microsoft/powershell/7/Microsoft.VSCode_profile.ps1
   + CurrentUserAllHosts:    /Users/jcstorino/.config/powershell/profile.ps1
   + CurrentUserCurrentHost: /Users/jcstorino/.config/powershell/Microsoft.VSCode_profile.ps1

DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: Microsoft.PowerShell.Security, Version=7.3.3.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
VERBOSE: 
== Console Details ==
 - Console input encoding: Unicode (UTF-8)
 - Console output encoding: Unicode (UTF-8)
 - PowerShell output encoding: Unicode (UTF-8)

VERBOSE: 
== PowerShell Details ==
- PowerShell version: 7.3.3
- Language mode:      FullLanguage

VERBOSE: 
== Environment Details ==
 - OS description:  Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
 - OS architecture: Arm64
 - Process bitness: 64

VERBOSE: Updated PSModulePath to: '/Users/jcstorino/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/usr/local/microsoft/powershell/7/Modules:/Users/jcstorino/.vscode/extensions/ms-vscode.powershell-2023.3.3/modules'
DEBUG: Validating configuration
VERBOSE: Loading PowerShell Editor Services
DEBUG: Assembly resolve event fired for Microsoft.PowerShell.EditorServices, Version=3.8.3.0, Culture=neutral, PublicKeyToken=null
VERBOSE: Loading PSES DLL using new assembly load context
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.PowerShell.EditorServices, Version=3.8.3.0, Culture=neutral, PublicKeyToken=null
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: System.Reflection.Metadata, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
DEBUG: Loaded into load context "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0: System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
VERBOSE: Starting EditorServices
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.Extensions.Logging, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog.Sinks.Async, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog.Extensions.Logging, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Serilog.Sinks.File, Version=5.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
DEBUG: Loaded into load context "PsesLoadContext" Microsoft.PowerShell.EditorServices.Hosting.PsesLoadContext #1: Microsoft.Extensions.Options, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
DEBUG: Creating/running editor services
DEBUG: Creating startup info object
VERBOSE: Starting server, deregistering host logger and registering shutdown listener
PowerShell Extension v2023.3.3
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
`

**Comment by jcstorino** [comment]
I Find some log files today.. But I don't know in what situation they were generated..

[Log Files.zip](https://github.com/PowerShell/vscode-powershell/files/11190558/Log.Files.zip)

**Comment by juliostorino** [comment]
For information... @andschwa 

I tried in every way to find the problem, but I was unsuccessful.

I had to do a clean installation of my MACOS and reinstall everything... 
this time I'm using VSC Insider, and after installing the extension it started correctly and it's functional.

Probably something related to MACOS permissions.

Tks !

**Comment by andschwa** [comment]
Of the whole OS?! That's so awkward but I'm so glad to hear it fixed things!

**Comment by juliostorino** [comment]
@andschwa 

🥹 yes... i maked a clean install...

As I am not a specialist in Linux/Unix, search for the right permission that was causing the problem did not seem very simple to me... opting for reinstallation turned out to be more effective !
