### ISSUE TITLE
PowerShell Local Configuration Manager Autocomplete adds extra characters 

### ISSUE THREAD

**Issue by Duffney** [PowerShell/vscode-powershell#45]
When writing LCM configuration with Code I found that it adds an extra character at the beginning of the code when using the intelisense. Example seen below, if you use intelisense to autocomplete the settings of the LCM it leaves the first character you typed to search for completion. 

```powershell
[DscLocalConfigurationManager()]
Configuration LCMPull {
	Node Localhost {
		Settings {
			aActionAfterReboot = 'ContinueConfiguration'
			
			
		}
	}
}
```

**Comment by daviwil** [comment]
Thanks Josh!

**Comment by daviwil** [comment]
Now fixed in PowerShellEditorServices, look for this is the next release!
