### ISSUE TITLE
EditorServices crashes after running code formatter

### ISSUE THREAD

**Issue by kapilmb** [PowerShell/vscode-powershell#450]
### System Details

- Operating system name and version: Windows 10 Enterprise
- VS Code version: 1.8.1
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
Sometimes. editorservices crashes after running code formatter.

### Attached Logs

[1484869858-someValue.sessionId.zip](https://github.com/PowerShell/vscode-powershell/files/718224/1484869858-someValue.sessionId.zip)

This is probably happening because `invoke-scriptanalyzer` calls `Cmdlet.WriteObject` from a different thread than the one calling `Cmdlet.ProcessRecord`.

**Comment by daviwil** [comment]
I believe Kapil has resolve this issue.
