### ISSUE TITLE
Ubuntu CI Tests do not appear to be running

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#4502]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Ubuntu is completing 5 minutes before the others and looking at the output pane it does not appear that tests are running.

![image](https://user-images.githubusercontent.com/15258962/230758882-8b957611-4b66-4145-a97b-3ac89ccfe819.png)

**Comment by andschwa** [comment]
That's correct, the VS Code test suite doesn't support being run on Linux so it's skipped. If that's changed...let me know.

**Comment by JustinGrote** [comment]
@andschwa pretty sure it has if you add xvfb to your azure pipeline it will now work
https://github.com/microsoft/vscode-test/blob/addc23e100b744de598220adbbf0761da870eda9/sample/azure-pipelines.yml#L25-L29
