### ISSUE TITLE
I think this should be…

### ISSUE THREAD

**Issue by mateuszficner746** [PowerShell/vscode-powershell#4520]
I think this should be…
```suggestion
      filesAdded + filesModified + filesRemoved + filesRenamed > 0
```

_Originally posted by @sergiou87 in https://github.com/desktop/desktop/pull/15165#discussion_r1089111046_

**Comment by JustinGrote** [comment]
@mateuszficner746 this appears to be a wayward repost. If this issue is specific to this extension if you can provide some more detail that'd be great! Otherwise I'm going to close for now.
