### ISSUE TITLE
Better error message when using unsupported PowerShell

### ISSUE THREAD

**Issue by saeedt2** [PowerShell/vscode-powershell#4521]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I am getting this error every time I start VS code
4/16/2023 1:10:06 PM [NORMAL] - pwsh.exe started.

4/16/2023 1:10:06 PM [NORMAL] - Waiting for session file...

4/16/2023 1:10:36 PM [WARNING] - Loading the PowerShell extension is taking longer than expected. If you're using privilege enforcement software, this can affect start up performance.

4/16/2023 1:14:08 PM [NORMAL] - Timed out waiting for session file to appear!

4/16/2023 1:14:08 PM [ERROR] - PowerShell process failed to start: 

4/16/2023 1:14:08 PM [ERROR] - Timed out waiting for session file to appear!

4/16/2023 1:14:08 PM [ERROR] - Unknown session status 'undefined' with reason 'undefined

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
ms-vscode.powershell@2023.3.3

1.77.3
704ed70d4fd1c6bd6342c436f1ede30d1cff4710
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.3.3
```

### Steps to Reproduce

the error is produced at each start of Visual studio Code, both by standard or run as admin. Tried to uninstall extension and reinstall. does not fix
get this error
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe '-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', 'Import-Module 'c:\Users\ahmads\.vscode\extensions\ms-vscode.powershell-2023.3.3\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2023.3.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\ahmads\.vscode\extensions\ms-vscode.powershell-2023.3.3\modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2023.3.3 Copyright (c) Microsoft Corporation. https://aka.ms/vscode-powershell Type 'help' to get help. " -LogLevel 'Normal' -LogPath 'c:\Users\ahmads\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\logs\1681614605-ae62c778-393e-45ea-aa23-844718bebce11681614602721\EditorServices.log' -SessionDetailsPath 'c:\Users\ahmads\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSC...

### Visuals

![image](https://user-images.githubusercontent.com/42429449/232264288-076c5600-c6ed-4fac-bac3-0f57f7aa53f9.png)

**Comment by JustinGrote** [comment]
Do you potentially have a profile configured? Does it open normally otherwise?

**Comment by saeedt2** [comment]
Thanks for reaching out to me. 
Don't think I have a profile setup. I do not get prompt to chose profile when I open VS-Code. When I go to Cont+Shift+P and type profile and select show profile, I see settings.jason with following contents
{
    "workbench.colorTheme": "Default Dark+",
    "files.autoSave": "afterDelay",
    "workbench.editor.untitled.hint": "hidden",
    "editor.fontFamily": "Fira Code",
    "editor.minimap.enabled": false
}

**Comment by JustinGrote** [comment]
I meant your powershell profile. If you open powershell and type `gc $profile.currentuserallhosts`, does anything come up?

**Comment by saeedt2** [comment]
HI Justine. this is the output of the profile command 
running the cmmand I get this output ( I have replaced my login name with XXXX )
PS U:\> gc $profile.currentuserallhosts
gc : Cannot find path 'C:\Users\XXXXX\OneDrive - XXXXX\Documents\WindowsPowerShell\profile.ps1' because it does not exist.
At line:1 char:1
+ gc $profile.currentuserallhosts
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\XXXXX...ell\profile.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by JustinGrote** [comment]
OK just checking. It's not common for PowerShell to lock up, however I noticed your current verson is 7.1.4. That version is out of support. You may want to try the latest 7.2 or 7.3, there may be bugfixes that resolve the issue.
https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.3

**Comment by andschwa** [comment]
Ah, this is similar to https://github.com/PowerShell/vscode-powershell/issues/4371. Deprecated versions of PowerShell (such as 6.x and 7.1) will fail to load the module (because since they're deprecated the module isn't compatible with their out-of-date versions of .NET). Unfortunately, our error messaging around this is poor, and as we identified in that last issue we _should_ say "hey! You're using 6.x or 7.1, you need to update" instead of this "undefined" message. That's on me, I'll get to it this week!

**Comment by saeedt2** [comment]
That is perfect. I downloaded the MSI of the new powershell module<https://github.com/PowerShell/PowerShell/releases/download/v7.3.4/PowerShell-7.3.4-win-x64.msi> and it fixed my issue. Really appreciate your assistance to fix this issue.
Best regards
saeed

**Comment by andschwa** [comment]
Way better error handling for this in the works too!
