### ISSUE TITLE
Folding no longer available with PowerShell extension

### ISSUE THREAD

**Issue by santisq** [PowerShell/vscode-powershell#4523]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I've recently noted that the PowerShell code no longer has [Folding](https://code.visualstudio.com/docs/editor/codebasics#_folding) available, this seems to be an issue with the PowerShell Extension only.

### PowerShell Version

```console
PS ..\pwsh> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS ..\pwsh> code --version

1.77.3
704ed70d4fd1c6bd6342c436f1ede30d1cff4710
x64
```

### Extension Version

```console
PS ..\pwsh> code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2023.4.0
```

### Steps to Reproduce

N/A

### Visuals

![image](https://user-images.githubusercontent.com/23342410/232597953-6b03bc26-d521-4fe5-a014-6d6ef8248f11.png)

![image](https://user-images.githubusercontent.com/23342410/232597860-074a1e68-b21f-4959-b70f-f7ba818544be.png)

### Logs

N/A

**Comment by JustinGrote** [comment]
CC @SeeminglyScience

**Comment by andschwa** [comment]
Since this was resolvable by being re-enabled, the extension is still working. I checked and all the defaults are still `true`, so I'm not sure why in your instance it appears to have been set to `false` in your settings without your knowledge.

Let me know if it crops up again!

**Comment by santisq** [comment]
@andschwa hey, I was chatting with @SeeminglyScience and he seemed to have the same problem though for him the setting was not present so something might have changed at some point. Should I close this issue?
