### ISSUE TITLE
Option to get start line for a keyword

### ISSUE THREAD

**Issue by majkinetor** [PowerShell/vscode-powershell#4529]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I am using pester to test an REST API. 

Its cumbersome to always have to press with the mouse Run/Debug test option above It:

![image](https://user-images.githubusercontent.com/85767/232775579-2697e03d-361f-42f4-873a-1a7685598c9d.png)

It would be way more efficent to have command line hotkey for this - run/debug current test, so I don't have to use a mouse and scroll around - for tests that don't fit on single screen I need to constantly scroll around in order to run a test. In above case, cursor is already in the line belonging to the test, so simpy hitting something like ALT + R would be way more faster to debug it.

I opened a [discussion ticket](https://github.com/pester/Pester/discussions/2342) at pester and got suggestion to request a feature here.

**Comment by fflaten** [comment]
Would like some feedback and approval from the team before committing to this.

A separate extension could implement this and use VSCode's document symbol provider to get `Describe/Context/It`-positions from this extension's Pester-symbols (similar to [inline values extension](https://github.com/TylerLeonhardt/vscode-inline-values-powershell/blob/49c62613375883ef30fc8fdf7b87f0b270f5b414/src/documentParser.ts#L30-L46)). Implementing it here would allow for more code reuse.

Any thoughts @JustinGrote? Make sense here? The experimental Pester VSCode-extension? A third-party extension?

A few questions:
- Which blocks should it support? Only `It` or should it pick the closest parent `Describe/Context/It`? It could feel "unpredictable", ex if cursor is placed right after closing curly brace.
- Would require two new commands, likely without default key bindings. Too noisy for this extension?

**Comment by JustinGrote** [comment]
Testing API already has support for this, works with my pester tests extension.
![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/96754917-a0f2-4a4e-a3d0-63249d187604)

**Comment by fflaten** [comment]
I knew it was smart to ping you 😄
