### ISSUE TITLE
Variable assignment with if else construct should stay in same line

### ISSUE THREAD

**Issue by Aculeo** [PowerShell/vscode-powershell#453]
I often end up writing something like this, because PowerShell does not have a null coalescing operator (??):

```powershell
$bar = if ($foo -eq $null) { 'none' } else { $Foo }
```

However, the code formatter ends up reformatting this (with `powershell.codeFormatting.newLineAfterOpenBrace` set to `false`):

```powershell
 $bar = if ($foo -eq $null) { 'none' 
} else { $foo 
}
```

IMO this should stay in the same line, could also be an option.

### System Details

- VS Code version: 1.8.1
- PowerShell extension version: 0.9.0

**Comment by daviwil** [comment]
Thanks for the feedback!  We're definitely considering having such a rule.  Should there be a setting to say that below a specified line length, the single-line assignment should be prserved?  Or should we just preserve all single-line assignments?

**Comment by Aculeo** [comment]
Yes, I think that would be great if it honored my prefered line length. I usually stick with a 100.  If I remember correctly Visual Studio does a great job with reformatting code, often putting just the assignment into the next line if it exceeds the specified length, like this:

```
$someRatherLongVariableName = 
    if ($foo -eq $null) { 'none' } else { $Foo }
```
