### ISSUE TITLE
Extension does not working unless i manually press "switch to: powershell (x64)"

### ISSUE THREAD

**Issue by soredake** [PowerShell/vscode-powershell#4530]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [x] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [x] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [x] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

After every vscode startup i need to press "switch to: powershell (x64)" in order for extension to be working, by default in "show powershell session menu" i see "current session: unknown"

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.77.3
704ed70d4fd1c6bd6342c436f1ede30d1cff4710
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.3.3
```

### Steps to Reproduce

1) Install [vscode](https://code.visualstudio.com/).
2) Install [powershell-core](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell)
3) Install [powershell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell).
4) Open any .ps1 file.

### Visuals

What i see after startup:
![Screenshot 2023-04-19 125842](https://user-images.githubusercontent.com/5204968/233042276-2655c05e-0968-4ad9-b9c1-b9c98209ba2a.png)
![Screenshot 2023-04-19 125908](https://user-images.githubusercontent.com/5204968/233042332-6e35cd36-f2b9-47c4-b1fe-18f1855b3278.png)

What i see after doing "switch to: powershell (x64)":
![Screenshot 2023-04-19 130007](https://user-images.githubusercontent.com/5204968/233042534-297d899c-b7e9-4b1c-a394-01c94d65fa1a.png)
![Screenshot 2023-04-19 130649](https://user-images.githubusercontent.com/5204968/233042539-a8981091-f839-4012-8ae8-9293741c1527.png)

My relevant powershell extension settings:
![Screenshot 2023-04-19 125932](https://user-images.githubusercontent.com/5204968/233042608-009da9c7-a27b-4880-a428-a0435cee5214.png)

### Logs

[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/11271740/vscode-powershell.log)

**Comment by andschwa** [comment]
What do you have in Additional Exe Paths?

**Comment by SydneyhSmith** [comment]
Thanks @soredake we fixed some startup issues in the latest stable version, could you please upgrade and let us know if you are still hitting this?

**Comment by soredake** [comment]
@SydneyhSmith unfortunately, nothing changed for me with newer version.

**Comment by PiotrWachulec** [comment]
@SydneyhSmith I see the same issue. My setup:
VS Code : `Version: 1.78.2 (Universal)`
Extension:
```
Name: PowerShell
Id: ms-vscode.powershell
Description: Develop PowerShell modules, commands and scripts in Visual Studio Code!
Version: 2023.5.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell
```
`PowerShell 7.3.4`

Also, I'm getting message `There is no formatter for 'powershell' files installed.`

**Comment by soredake** [comment]
I realized that i had `"powershell.startAutomatically": false,` in my vscode configuration....

**Comment by soredake** [comment]
No need for reopen, my problem is created by myself, there is no problem with powershell extension.
