### ISSUE TITLE
How to add sessions button to taskbar?

### ISSUE THREAD

**Issue by TESTER-sec** [PowerShell/vscode-powershell#4535]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

"That means the PowerShell icon button in the status bar now exists under the language status menu, which looks like: {}. You can then pin the icon back to the status bar by hovering over that menu and clicking the pin button. The PowerShell icon will show you the current session's version, and clicking it will let you change to another session."

What and where is the "language status menu"? The above makes no sense.

Don't use Discord. So won't go there.

### PowerShell Version

```console
7.3.4
```

### Visual Studio Code Version

```console
1.77.3
```

### Extension Version

```console
2023.4
```

### Steps to Reproduce

Install VS 1.77.3
In the PowerShell Extension Welcome it says what is reported above

### Visuals

Provided

### Logs

None

**Comment by andschwa** [comment]
<img width="581" alt="Screenshot 2023-04-24 at 9 17 09 AM" src="https://user-images.githubusercontent.com/2226434/234056321-a333391c-e278-4773-b0cc-bb706f89e4b8.png">

See the blue arrows ☺️

**Comment by andschwa** [comment]
I've been meaning to update the help doc for a while, I've shared a lot of screenshots lately that are just a _lot_ more useful than the text. It'll be a "tech debt day" thing for sure!
