### ISSUE TITLE
Text color changes depending on stage of the file.

### ISSUE THREAD

**Issue by FranciscoNabas** [PowerShell/vscode-powershell#4542]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When opening a new tab, and selecting PowerShell as the language mode, the text between brackets "[ ]" starts green, and changes to yellow when using some predefined texts.
When I safe the text as a new file, the color changes to blue.
I'm not quite sure if this is the expected behavior.
To be clear, this don't affect the functionality in any way, and it's just an aesthetic issue.
Is there a way of choosing the default color for all occasions? It would be nice to be able to choose these colors.  
P.S.: I have tried different PowerShell and Visual Code versions, preview and insiders.

Hope you all have a great week!
Thanks!

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.78.0-insider
545d981034e010e2e31396faf224996c31eceab1
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.3.3
```

### Steps to Reproduce

- Open a new tab with 'Ctrl + N' or right click tab list, and 'New Text File'.
- Select the PowerShell Language Mode with 'Ctrl + K + M' or clicking the 'Select Language Mode' option in the bottom-right part of the screen.
- Write text between square brackets '[ ]', it could be:
     - Types
     - Parameter attributes
     - CmdletBinding attribute
- Input default text by typing 'Parameter' and selecting any option, such as 'parameter-path'.
- Observe the text color.
- Save the file with 'Ctrl + S' or 'File -> Save'.
- Observe the color change once more.

### Visuals

![image](https://user-images.githubusercontent.com/40699992/234091270-2d604a3f-5087-435b-b465-ba0bc09015c2.png)
  
![image](https://user-images.githubusercontent.com/40699992/234091305-acb4f7c4-71d7-4b86-90d8-40106f41eae3.png)
  
![image](https://user-images.githubusercontent.com/40699992/234091373-be803076-6122-4b15-863d-ed9be7b2eeac.png)

**Comment by SydneyhSmith** [comment]
Thanks @FranciscoNabas do you have semantic highlighting on? Also wondering if you have format on save on?

**Comment by FranciscoNabas** [comment]
Hi! Thanks for the response.

Semantic highlighting is on. Format on save is off.

![image](https://github.com/PowerShell/vscode-powershell/assets/40699992/d5406337-65b7-45c4-81b7-334d00b06fcf)
![image](https://github.com/PowerShell/vscode-powershell/assets/40699992/902e65c5-eaa2-4658-aa5a-5a71dbdebda0)

**Comment by andschwa** [comment]
Ah, we would recommend disabling semantic highlighting for PowerShell files. We contribute a default value of `false` for PowerShell files, but if you've overridden that, then you should switch it back. See more explanation [here](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#problems-with-syntax-highlighting).
