### ISSUE TITLE
autocompletion doesn't work for items defined in array-assignment

### ISSUE THREAD

**Issue by irvnriir** [PowerShell/vscode-powershell#4558]
### Prerequisites

- [X] I have written a descriptive issue title.
- [x] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [x] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [x] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [x] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

i wanna do this
```
{ (
$st_sc,
([string] $te)
) = $args[0]

}
```

instead of having to use this
```
{ [string] $te = $null; (
$st_sc,
$te			# type: `[string]`
) = $args[0]

}
```

### PowerShell Version

```console
Windows Powershell 5.1
```

### Visual Studio Code Version

```console
1.57.1
```

### Extension Version

```console
v2023.5.0
```

### Steps to Reproduce

-

**Comment by SydneyhSmith** [comment]
@irvnriir thanks so much for opening this issue, unfortunately this a PowerShell issue not controlled by the extension so I will mark this as external
