### ISSUE TITLE
Terminal cursor style not being honored when not in focus

### ISSUE THREAD

**Issue by NJK-Work** [PowerShell/vscode-powershell#4559]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

This is minor annoyance - maybe something to fix in someone's copious spare time:

I have "Terminal › Integrated: Cursor Style" set to "line".  This works correctly when the terminal has focus.  If you switch focus back to something else, like the editor or settings pane, the cursor changes back to a "block".

This was not the case prior to the 1.78 VSCode and PowerShell v2023.5.0 extension - both changes happened on the same date.  Figured I would start with the PowerShell extension issues board first - but can post this to the VSCode issues board instead if someone thinks it is more of a problem with VSCode itself.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.78.0
252e5463d60e63238250799aef7375787f68b4ee
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.5.0
```

### Steps to Reproduce

See screenshots.

### Visuals

Without Focus:
![WithoutFocus](https://user-images.githubusercontent.com/24608858/236539950-218342a5-f67c-4961-8804-df3a6dda9ab4.jpg)

With Focus:
![WithFocus](https://user-images.githubusercontent.com/24608858/236539963-a2775367-3db9-4fda-adea-266a9944718d.jpg)

**Comment by andschwa** [comment]
> but can post this to the VSCode issues board instead if someone thinks it is more of a problem with VSCode itself.

You can test this actually! If the issue reproduces in terminals that are labeled `PowerShell Extension` then it's an upstream issue with Code which will require their help to solve.

**Comment by NJK-Work** [comment]
Yep - it says "1: PowerShell Extension" in the drop-down list.  I will post this in the VSCode issues board.  Thanks for the tip.

**Comment by NJK-Work** [comment]
No worries.  It does happen on both ``pwsh`` and ``PowerShell Extension``.  Thanks again.
