### ISSUE TITLE
Streamline the extension development experience

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#456]
Now that PowerShell Editor Services [can be built from VS Code](https://github.com/PowerShell/PowerShellEditorServices/pull/351) using cross-platform tools, it's time to make the extension development experience much more smooth.

Here's the ideal experience starting from zero:

0. User installs PowerShell for their platform if necessary
1. User clones the vscode-powershell repo and opens it in VS Code
2. User presses F5 to compile the code and run it under the debugger
3. The compilation script recognizes that there's no PowerShellEditorServices repo available and clones it
4. The compilation script builds PowerShellEditorServices and the extension code
5. The debug configuration launches VS Code with the dev extension, configured to use PSES from its repo path
6. **BONUS:** The C# debugger automatically attaches to the language server for an end-to-end debugging experience

It'd be ideal if the user never has to set their `bundledModulesPath`, the debug configuration should set that up automatically.

**Comment by TylerLeonhardt** [comment]
This is basically done except for "The compilation script recognizes that there's no PowerShellEditorServices repo available and clones it" and we don't do the bonus.

**Comment by TylerLeonhardt** [comment]
I'm actually not quite sure the bonus is possible...

Because of that, we can probably just close this.
