### ISSUE TITLE
Extension host keeps restarting

### ISSUE THREAD

**Issue by Shrp77** [PowerShell/vscode-powershell#4560]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Opened up VS Code, continuing my previous session where I was debugging some PowerShell scripts. Within seconds I get a notification from VS Code that the extension host terminated unexpectedly 3 times within the last 5 minutes.

Using the Extension Bisect functionality I narrowed it down to the PowerShell extension.

Without this extension I cannot debug my powershell scripts. Please fix!

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.78.0
252e5463d60e63238250799aef7375787f68b4ee
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.5.0
TylerLeonhardt.vscode-inline-values-powershell@0.0.7
```

### Steps to Reproduce

Open VS Code with the Terminal Window open to PowerShell and the Debug Variables panel open. Wait a few seconds.

### Visuals

![image](https://user-images.githubusercontent.com/8106071/236569753-5df6eed3-0dfa-4bbc-b6a6-f65f0fc61e8f.png)

**Comment by SydneyhSmith** [comment]
Thanks @Shrp77 so sorry to hear you are hitting this issue! Could you please provide us with additional information such as logs and a list of extensions you are using...thanks!

**Comment by Shrp77** [comment]
Hi Sydney,

I was able to resolve it by completely wiping out VS Code (and every single .vscode folder on my machine), rebooting and reinstalling it. Unfortunately I cannot assist further with this issue as I'm no longer in the broken state.

Cheers,

Arvind
