### ISSUE TITLE
Bitdefender Internet Security prevents to install the VS code extension properly

### ISSUE THREAD

**Issue by EnricoMassone** [PowerShell/vscode-powershell#4561]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Hello, I'm unable to properly install the VS code PowerShell extension on my laptop.

Basically the extension is unable to starting up because of the Bitdefender Internet Security antivirus preventing it.  

This is the error message reported by the VS code extension: 

> PowerShell extension has not finished starting up yet. Please try again in a few moments.

This is the message reported by Bitdefender Internet Security: 

> PowerShell tried to load a malicious resource detected as Heur.BZC.ZFV.Boxter.803.B56308FC and was blocked. Your device is safe

Here are some information about my OS: 

Edition	Windows 11 Pro
Version	22H2
OS build	22621.1635

My antivirus is Bitdefender Internet Security Build version 26.0.35.174

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.78.0
252e5463d60e63238250799aef7375787f68b4ee
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.5.0
```

### Steps to Reproduce

1. open VS code
2. go to the extensions search panel 
3. search for PowerShell extension
4. install the PowerShell extension
5. wait a few minutes for the installation process to start 
6. look at the suspicious activities blocked by Bitdefender Internet Security from the Notifications menu of the antivirus UI. 
7. the following message is reported by Bitdefender Internet Security: _PowerShell tried to load a malicious resource detected as Heur.BZC.ZFV.Boxter.803.B56308FC and was blocked. Your device is safe._ This prevents the VS code extension to start running properly.

**Comment by EnricoMassone** [comment]
> Have you tried reaching out to Bitdefender? Looks like their support email is [bitsy@bitdefender.com](mailto:bitsy@bitdefender.com).

Hello and thanks for replying. 
I opened a [new discussion](https://community.bitdefender.com/en/discussion/95904/bitdefender-internet-security-prevents-installation-of-powershell-vs-code-extension#latest) about this issue on the Bitdefender community forum.

**Comment by EnricoMassone** [comment]
Hello, I just want to write a quick update on this issue. 
The Bitdefender technical support team has investigated this issue and has confirmed this is a false positive. They will remove this detection in one of the future updates of the product.

**Comment by andschwa** [comment]
Thank you @EnricoMassone!
