### ISSUE TITLE
Make `editor.autoClosingBrackets` smarter?

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/vscode-powershell#4567]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Is there any way to make the auto closing bracket functionality of VSCode any smarter for PowerShell?

With both

```json
"[powrshell]": {
  "editor.autoClosingBrackets": "always"
}
```

and

```json
"[powrshell]": {
  "editor.autoClosingBrackets": "languageDefined"
}
```

this functionality is not very helpful. Example, say you've created:

```powershell
Write-Output -InputObject 'Test'
```

Now you find out you want the input object inside paranthesis, and start with the `(`. `editor.autoClosingBrackets` does this:

```powershell
Write-Output -InputObject ()'Test'
```

I'm used to PowerShell ISE, so I'll just turn off `editor.autoClosingBrackets` for now.

**Comment by SydneyhSmith** [comment]
Thanks @o-l-a-v this would need to first be supported by VSCode
