### ISSUE TITLE
Debugger hangs on scripts with long running commands

### ISSUE THREAD

**Issue by troshko111** [PowerShell/vscode-powershell#457]
### System Details

- Operating system name and version:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
```
- VS Code version: `1.8.1`
- PowerShell extension version: `0.9.0`
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Debugger would almost always hang if stepping through a script running some long operations (in my case calling separate script provisioning Azure resources). 

Stepping through it won't hit the breakpoint after long running operation, putting a single breakpoint after some long running operaion also hangs, once the operation finishes extension reports the breakpoint has been hit but debugger won't respond to step requests and entire vscode has to be reloaded (even subsequent debugging sessions will hang). Repros most of the time. 

Long running = minutes

**Comment by daviwil** [comment]
Hi Taras, it'd be great if you could capture logs and send them to me so that I can look into this issue further.  Here are some instructions:

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
