### ISSUE TITLE
Fallback to default tab-completion behavior in the presence of an IValidateSetValuesGenerator class

### ISSUE THREAD

**Issue by wi-fr** [PowerShell/vscode-powershell#4575]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I am experiencing erroneous fallback to default tab-completion behavior in the VSCode editor when a PowerShell function parameter is decorated with a ValidateSet Attribute, whose ValuesGenerator class is defined in the same script as the function itself.

### PowerShell Version

```console
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.78.2
b3e4e68a0bc097f0ae7907b217c1119af9e03435
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.5.1
```

### Steps to Reproduce

Define the class and the function in the VSCode Editor:
```
class Colors : System.Management.Automation.IValidateSetValuesGenerator {
  [String[]] GetValidValues() { return 'Red', 'Green', 'Blue' }
}
Function Get-Color {
  Param(
    [ValidateSet([Colors])]
    [string] $Color
  )
}
```

in the VSCode Editor, type: Get-Color, space, tab, ...

Comment out the class definition at the top of the script, then repeat: Get-Color, space, tab, ...

**Comment by SydneyhSmith** [comment]
Thanks for opening this issue @wi-fr this issue is not caused by the PowerShell extension, this is actually caused by the way that PowerShell works
