### ISSUE TITLE
Not showing debugging options

### ISSUE THREAD

**Issue by marcosaguilar015** [PowerShell/vscode-powershell#4595]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Recently i have installed VSCode and the Powershell extension in a new machine and tried to solve a little issue without success. In VSCode/Run and Debug/Breakpoints, the checkboxes for conditional breakpoints that usually are shown by default ("Uncaught exceptions", "User Uncaught Exception", "All Exceptions"...) are not present. All the others debugging functionalities seems to work just fine.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.78.2
b3e4e68a0bc097f0ae7907b217c1119af9e03435
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.5.0
```

### Steps to Reproduce

No especific steps are necessary to recreate it. I believe that it's something exclusive for my machine.

Just create or open any ps1 file.

Go to debug tab.

### Visuals

![Capturar](https://github.com/PowerShell/vscode-powershell/assets/95425881/6231709e-c8d4-4370-be2a-2911273f4582)

**Comment by JustinGrote** [comment]
`the checkboxes for conditional breakpoints that usually are shown by default ("Uncaught exceptions", "User Uncaught Exception", "All Exceptions"...) are not present. All the others debugging functionalities seems to work just fine.`

The PowerShell extension doesn't expose these as I recall, those are only for other languages (C#, typescript, etc.), are you sure you weren't debugging in another language or had multiple debuggers running?
