### ISSUE TITLE
error Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by keithgb** [PowerShell/vscode-powershell#46]
On Windows 7 I cannot seem to get the debugger to work.

**Comment by daviwil** [comment]
Hi Keith, can you open the DebugAdapter.log file in the following location and copy/paste the error at the very end of the file?

`c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell\bin`

Thanks!

**Comment by keithgb** [comment]
​Sure thank you!

​ System.MissingMethodException: Method not found: 'Void
System.Management.Automation.Debugger.SetDebugMode(System.Management.Automation.DebugModes)'.
       at
Microsoft.PowerShell.EditorServices.PowerShellContext.Initialize(Runspace
initialRunspace)
       at Microsoft.PowerShell.EditorServices.PowerShellContext..ctor()
       at
Microsoft.PowerShell.EditorServices.EditorSession.StartSession(IConsoleHost
consoleHost)
       at
Microsoft.PowerShell.EditorServices.Host.MessageLoop.<ListenForMessages>d__4.MoveNext()
    --- End of stack trace from previous location where exception was
thrown ---
       at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
       at
Microsoft.PowerShell.EditorServices.Host.MessageLoop.<StartMessageLoop>d__1.MoveNext()
    --- End of stack trace from previous location where exception was
thrown ---
       at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
       at Nito.AsyncEx.AsyncContext.<>c__DisplayClass3.<Run>b__1(Task t)
       at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
    --- End of stack trace from previous location where exception was
thrown ---
       at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
       at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
       at Microsoft.PowerShell.EditorServices.Host.MessageLoop.Start()
       at Microsoft.PowerShell.EditorServices.Host.Program.Main(String[]
args)


Keith G. Broussard
keithbroussard@gmail.com

**Comment by daviwil** [comment]
What version of PowerShell are you using?  It looks like you aren't using PowerShell v5.  Currently only PowerShell v5 is supported though some things may work with earlier versions of PowerShell.  If you aren't using v5 then I'm pretty impressed that you've only just hit an issue while trying to debug :)

**Comment by keithgb** [comment]
​you are correct I am on  3.0.

[image: Inline image 2]

I will attempt to install 5 to see if that resolves.

Windows Management Framework 5.0 Production Preview
http://www.microsoft.com/en-us/download/details.aspx?id=48729

​

Keith G. Broussard
keithbroussard@gmail.com

**Comment by daviwil** [comment]
Yep, that's the one!

**Comment by keithgb** [comment]
Thanks for the quick response!!


Keith G. Broussard
keithbroussard@gmail.com

**Comment by daviwil** [comment]
I'm going to track this issue over at the PowerShellEditorServices repo with this issue:

https://github.com/PowerShell/PowerShellEditorServices/issues/73

Thanks again for the report!

**Comment by ConnectedReasoning** [comment]
I'm getting this error on a Mac. Where should I look for the log?

**Comment by daviwil** [comment]
Hi @ConnectedReasoning, the debugging feature doesn't work on OSX because PowerShell is not supported on that platform. All language and debugging features (aside from syntax highlighting and snippets) need the PowerShell runtime to operate.

**Comment by FaffeF** [comment]
Still getting this error with PowerShell v6.0.0-alpha.9 installed on OSX El Capitan.

The DebugAdapterClient.log is empty 😿

**Comment by daviwil** [comment]
Hey @FaffeF, you may need to install OpenSSL on your Mac for the extension to work correctly. Check out our installation instructions here:

https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/using-vscode.md

Check out the 'NOTE' in the OS X installation instructions for VS Code.

**Comment by FaffeF** [comment]
OpenSSL was already installed. Updated the extension to 0.7.1 this morning, and suddenly debugging worked!

- Then it worked again! 
- Then it didn't work (same error, showing me launch.json)
- Then it worked a lot across different files.
- Then it failed a lot.
- After a restart debugging works again...


Log files look like below, with the error the only difference between successful and failed attempts.

```
Connecting to port: 13596
Connected to socket!

Socket connect ERROR: Error: read ECONNRESET
Socket closed, shutting down.
```

**Comment by daviwil** [comment]
So sometimes it works and sometimes it doesn't work in the same session...  That's strange, but it gives me some clues.  Let's continue this discussion over on issue #243 because others are seeing similar issues there.
