### ISSUE TITLE
launch.json arguments are not being processed

### ISSUE THREAD

**Issue by galenus** [PowerShell/vscode-powershell#460]
### System Details

- Operating system name and version: Win10 Pro
- VS Code version: 1.9.0-insiders
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.0.10586.672
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.672
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with debugger: the arguments specified in the launch.json are not passed into the session launched with F5 command.

**Comment by rkeithhill** [comment]
Can you list your `launch.json` file here?

**Comment by galenus** [comment]
Here it is:

    {
        "version": "0.2.0",
        "configurations": [
            {
                "type": "PowerShell",
                "request": "launch",
                "name": "PowerShell Launch (current file)",
                "script": "${file}",
                "args": ["./development"],
                "cwd": "${file}"
            }
        ]
    }

And the parameters declaration from the script I debug:

    param(
        [string]$envFolder="./",
        [string]$outputFolder="./out",
        [bool]$updateOnly=$false
    )

I receive the current folder inside `$envFolder`.

**Comment by rkeithhill** [comment]
You are specifying a relative path and the launch.json sets the current working dir to the dir that ${file} (the script being debugged) is in.    Is it possible that is the problem?  For `"cwd":` you can use a value of `"${workspaceRoot}"` IIRC.

**Comment by galenus** [comment]
Same launch.json running in the stable VS Code Stable (1.8.1) works as expected.

**Comment by daviwil** [comment]
I'll take a look, maybe I broke something with my debugging changes.

**Comment by rkeithhill** [comment]
Hmm, I can't repro it.

**Comment by rkeithhill** [comment]
Hmm, I can reproduce the extension not passing environment variables across:
```
    "configurations": [
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch (DebugTest.ps1)",
            "script": "${workspaceRoot}/DebugTest.ps1",
            "args": [ "-Foo 42 ${env.HOME}"],
            "cwd": "${workspaceRoot}"
        },
```
in the log file I see:
```
    READ MESSAGE:
    
    {
      "command": "launch",
      "arguments": {
        "type": "PowerShell",
        "request": "launch",
        "name": "PowerShell Launch (DebugTest.ps1)",
        "script": "c:\\Users\\Keith\\Scripts/DebugTest.ps1",
        "args": [
          "-Foo 42 "
        ],
        "cwd": "c:\\Users\\Keith\\Scripts"
      },
      "type": "request",
      "seq": 2
    }
```
No sign of the env var that the VS Code docs claim is supported: https://code.visualstudio.com/docs/editor/debugging#_variable-substitution

**Comment by galenus** [comment]
Not sure it's the same thing, in my case I didn't get the arguments at all.

**Comment by rkeithhill** [comment]
Ignore my issue. `${env.HOME}` doesn't get sent across because Windows doesn't define a HOME env var.  The `$env:HOME` available in PowerShell must have been created by PowerShell (I guess).  In the launch.json file, `${env.USERNAME}` works just fine.

**Comment by galenus** [comment]
Works both in VS Code 1.9.1 and 1.10.0 - Insider. Can be closed.

**Comment by daviwil** [comment]
Thanks for confirming @galenus!  Let us know if you see it happen again.
