### ISSUE TITLE
visual studio code startup slow and not responding

### ISSUE THREAD

**Issue by MilanAhir227** [PowerShell/vscode-powershell#4601]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

i usually use vscode for my work but some day ago thay problems started i stared vs code and thay delay to 30s  

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.78.2
b3e4e68a0bc097f0ae7907b217c1119af9e03435
x64
```

### Extension Version

```console
not show this
```

### Steps to Reproduce

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/all.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
            text-decoration: none;
        }

        #box {
            height: 300px;
            width: 300px;
            background-color: black;
            display: none;            
        }

        .btn {
            padding: 10px 20px;
            background-color: black;
            border: 1px solid white;
            color: white;
            border-radius: 10%;
        }
        i{
            color: white;
            font-size: larger;
        }
    </style>
</head>

<body>

    <div id="box">
        
        <div><i class="fa-solid fa-xmark" onclick="none()"></i></div>

    </div>
    <button class="btn" onclick="line()">click</button>

    <script type="text/javascript">
       
    </script>
</body>

</html>

### Visuals

![Welcome - Visual Studio Code 29-05-2023 15_08_52](https://github.com/PowerShell/vscode-powershell/assets/127586866/abbdc705-b19e-40d5-be63-6836efbe7217)

**Comment by andschwa** [comment]
Could you please file a bug with VS Code itself? This repository is for the PowerShell Extension. Thanks!
