### ISSUE TITLE
Option to disable alias warning

### ISSUE THREAD

**Issue by soredake** [PowerShell/vscode-powershell#4621]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

It would be nice if there is option to disable this alias warning:
![image](https://github.com/PowerShell/vscode-powershell/assets/5204968/b0ea0a47-b58a-4fb1-a8c0-6b140a42d59e)

**Comment by andschwa** [comment]
For now you can use `SuppressMessageAttribute` to ignore it.

**Comment by andschwa** [comment]
Here's the documentation on the usage of that attribute with PSScriptAnalzyer!

https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/using-scriptanalyzer?view=ps-modules#suppressing-rules

**Comment by soredake** [comment]
@andschwa sorry but it still doesn't work globally or for plain commands like this:
![изображение](https://github.com/PowerShell/vscode-powershell/assets/5204968/adfa3573-15fd-410b-9c58-ae16aa1d6e76)

**Comment by andschwa** [comment]
Could you open an issue with [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer)? All the extension can do is run it :/
