### ISSUE TITLE
High Memory Usage: Not decreasing after debugging ended

### ISSUE THREAD

**Issue by DesuNinshu** [PowerShell/vscode-powershell#4629]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I am experiencing very high memory usage and sometimes debugging fails to start.

I have 32 GB of RAM. I am attempting to debug to check the properties of a response from the `Invoke-WebRequest` command.

My editor started to freeze and variables where not populating in the launch pane. So, I checked task manager. I was at 96% memory usage. I turned off my PowerShell profile and tried a few other things but when I debug and start looking at the variables in my editor, memory keeps climbing. When I exit debugging it doesn't drop. If I start debugging again it continues to climb.

I created a DMP file of the pwsh.exe sub-process of vscode. I cannot attach it, I also have a video saved I cannot attach it because is 2:37. I am happy to provide them. Please let me know the best way to get them to you guys.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.79.2
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

1. Create a PowerShell script with the following code.
```powershell

$Response = Invoke-WebRequest -Method Get -Uri 'https://aka.ms/downloadazcopy-v10-windows'
$Response
```
2. Set a break point on the second $Response variable.
3. Start debugging and hover your mouse over the variable.
4. Observe that it takes a long time for the pop-up to display, and vscode becomes unresponsive temporarily.
5. When the pop-up shows the properties of the response, start expanding the properties.
Observe that in task manager the memory usage of the pwsh subprocess for vscode has started to climb.
Stop debugging, and observe that the memory usage does not decrease.
Start debugging, and follow steps 3-5 again, observe that the memory usage continues to increase.

**Comment by DesuNinshu** [comment]
Edit:
Here is a link to a message in the PowerShell community discord where I have posted a video of the issue.
https://discord.com/channels/180528040881815552/447579065877266454/1121190913721516052

**Comment by SydneyhSmith** [comment]
Thanks @DesuNinshu can you try running [GC]::Collect()

**Comment by DesuNinshu** [comment]
While the script is running? or? I have a `finally` statement in my script that ensures the zip is removed after its downloaded and extracted. Refer to the code below for the full function. It's the debugging view that is causing my memory to go wild. I can't change how the debuggers memory usage is affected with [GC]::Collect()

```powershell

function Install-AzCopy {
    [OutputType([hashtable])]
    [CmdletBinding(DefaultParameterSetName = "Auto", PositionalBinding = $false)]
    Param (
        [Parameter(ParameterSetName = "Auto")]
        [Parameter(ParameterSetName = "SingleOrMultiple")]
        [ValidateSet([AzCopyPlatformSet])]
        [string[]]$Platform = $(Get-OSPlatform),

        [Parameter(ParameterSetName = "All")]
        [switch]$All,

        [Parameter()][ValidateNotNullOrEmpty()]
        [string]$Path = '.'
    )
    Begin {
        if (Test-Path Variable:/PSDebugContext) {
            $ErrorActionPreference = "Break"
        }
        $ToDownload = [Collection[string]]::new()
        try {
            if ($PSCmdlet.ParameterSetName -eq "All") {
                $ToDownload = [Collection[string]]::new($Platforms);
            }
            elseif ($PSCmdlet.ParameterSetName -eq "SingleOrMultiple") {
                $Platform.ForEach(
                    {
                        $null = $ToDownload.Add($_);
                    }
                );
            }
            else {
                $null = $ToDownload.Add($Platform)
            }
        }
        catch {
            Write-Error $_
        }
    }
    Process {
        foreach ($Download in $ToDownload) {
            try {
                $TempZip = New-TemporaryFile
                $Response = Invoke-WebRequest -Uri $DownloadUri[$Download]
                $Response.BaseResponse.EnsureSuccessStatusCode() | Out-Null;
                [File]::WriteAllBytes($TempZip.FullName, $Response.RawContentStream.ToArray())
                $ExpandedArchive = Expand-Archive $TempZip.ResolvedTarget -Force -PassThru
                $OutputPath = New-Item -ItemType "Directory" -Path ".\AzureCopy" -Name $Download -Force
                $AzCopyVersions[$Download] = ($ExpandedArchive | Where-Object -Property Name -Contains -Value "azcopy.exe" | Select-Object -First 1 | Get-Item | Copy-Item -Destination $OutputPath.FullName -Force -PassThru).FullName
            }
            catch {
                Write-Error $_
            }
            finally {
                $TempZip.Delete();
                $Response.BaseResponse.Dispose();
                if ($ExpandedArchive) {
                    $OutPath = $ExpandedArchive | Select-Object -First 1 -Property FullName -ExpandProperty FullName | Split-Path -Parent 
                    if (Test-Path $OutPath) {
                        Remove-Item -Path $Outpath -Recurse -Force
                    }
                }
            }
        }
    }
    End {
        return $AzCopyVersions
    }
}
```

**Comment by andschwa** [comment]
Bad bot, it's broken, sorry about that.
