### ISSUE TITLE
Power Shell

### ISSUE THREAD

**Issue by IshwarGade123** [PowerShell/vscode-powershell#4642]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

i am experiencing issue with powershell it's not opening and not working....

### PowerShell Version

```console
i dont know
```

### Visual Studio Code Version

```console
1.79.2
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

i dont know

### Visuals

i dont know

### Logs

i dont know

**Comment by SydneyhSmith** [comment]
@IshwarGade123 thanks for opening this issue, unfortunately we can't help with the info you provided, we'd love to help but please open a new issue with more information, logs, screenshots, repro steps etc.
