### ISSUE TITLE
Extension Terminal session memory leak when having local PowerShell module folder in Workspace

### ISSUE THREAD

**Issue by DEberhardt** [PowerShell/vscode-powershell#4654]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Hello,

### Issue
every time the PowerShell extension starts the terminal session, after a few seconds I see this:
![image](https://github.com/PowerShell/vscode-powershell/assets/44290340/01c74960-b98a-44a8-871d-0cf3da55630e)
CPU around 10-20% and Memory slowly increasing.

This behaviour is consistent with the session, and memory is released as soon as I close the corresponding session in VScode.
The logs do not produce any meaningful output (other than tell me that the session was closed).

### Troubleshooting steps (so far)
I have
- Used bisect without conclusion (cannot force it to open excluding one extension up-front)
- Disabled all extensions. It is only active with the Terminal session running
- Removed my profile - still gobbling up memory
- Removed my settings, both user and workspace to see if it makes a difference, it does not.

So with VScode and the PowerShell extension running as soon as the terminal runs it will eat memory and hog 20% CPU
![image](https://github.com/PowerShell/vscode-powershell/assets/44290340/8be2d212-26b0-4320-b263-eca83b5cac4c)

This is happening on two different computers, though I use both for developing and have settings sync active and roughly all the same extensions installed...

I cannot find out why nor do I know how I could troubleshoot this any more.

### History
I have had used (and flipped between) the PowerShell Preview version in VScode. It is now deprecated, so no longer in use
I have installed PowerShell 7 and 7 preview from the Windows store and use them with Windows Terminal.
The issue does not surface in Windows Terminal.

I have had used PowerShell 5 as the main environment in VScode, but have now switched to v7 as I finally migrated all my scripts to Graph.

### Question
What is happening to my system?
What can I do to further find out what is causing this?
Are there temporary files that may impact this?

Any help is appreciated, I have no clou how to tackle this one

Thank you,
David

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22623
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.80.0
660393deaaa6d1996740ff4880f1bad43768c814
x64
```

### Extension Version

```console
DougFinke.powershellexcel-snippets@0.5.1
ironmansoftware.powershellprotools@2023.6.0
justin-grote.powershell-extension-pack@0.0.7
ms-vscode.powershell@2023.6.0
TylerLeonhardt.vscode-inline-values-powershell@0.0.7
xKoloblicin.powershell-ise-dark@1.0.1
```

### Steps to Reproduce

Start VsCode
Create Workspace and add local PowerShell folder and/or WindowsPowerShell folder to the workspace
Save the workspace
Stop VsCode

Start VsCode (loading the last workspace)
Select PowerShell File from any project in the workspace
Verify PowerShell Extension terminal session loads and profile is executed
Watch Memory consumption rise

### Visuals

![image](https://github.com/PowerShell/vscode-powershell/assets/44290340/0b9e3808-da28-4401-9c9a-76c668cfbc15)

### Logs

[20230709T135806.zip](https://github.com/PowerShell/vscode-powershell/files/11995201/20230709T135806.zip)
[20230709T140551.zip](https://github.com/PowerShell/vscode-powershell/files/11995215/20230709T140551.zip)

**Comment by DEberhardt** [comment]
I am now trying to get this to trigger more consistently and found that in some of my workspaces, it does not show up...

Could this be because I added the PowerShell Modules folder to my workspace (both WindowsPowerShell and Powershell)?

**Comment by DEberhardt** [comment]
ok. I _think_ I figured out what happens, though I cannot explain why it happens.

I have multiple workspaces containing different environments, some with, some without the Local PowerShell folders (MyDocuments\PowerShell and MyDocuments\WindowsPowerShell) in the workspace

Workspace settings file:
```json
{
	"folders": [
		{
			"path": "Personal/Orbit"
		},
		{
			"path": "E:/Documents/PowerShell"
		}
	]
}
```

Whenever I do, I can reproduce tthis
However, merely starting vscode and the PowerShell Extension Services terminal session will not trigger it.

I have to have a PS1 file open and focused (clicking into it) for it to occur. 
Don't know what the extension then does, but that is the closest I can pinpoint it.

**Comment by andschwa** [comment]
How large are those two folders of PowerShell code? Does the issue go away if you enable the setting: `powershell.analyzeOpenDocumentsOnly`?

**Comment by DEberhardt** [comment]
The folders are 4.5 and 5.5GB respectively - just over 10GB in total (many thanks to the myriad of Az and Graph modules and versions...)
Adding `analyzeOpenDocumentsOnly` does calm it down though, cheers!

**Comment by JustinGrote** [comment]
Going to mark this as closed as it is "working as expected", there could theoretically be a follow-up to automatically exclude PSModulePaths from indexing to avoid this behavior, but this might be undesierable for people who like to edit code documents. That would be a separate issue though.

For now the guidance would be to only open workspaces for your specific project and not "general" high level folders like your user profile, or if you do need to do that, use the settings as mentioned.
