### ISSUE TITLE
Can't debug when using PowerShell 7.4

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#4668]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

It seems that VSCode doesn't stop on breakpoints when debugging in PS 7.4

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.80.1
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

1. Create empty file
2. Add some code

```

Write-Host "Test 1"

Write-Host "Test 2"
```

3. Set breakpoint

4. Press F5
5. Notice it doesn't stop

### Visuals

![Debugging not working](https://github.com/PowerShell/vscode-powershell/assets/15063294/97d93919-c81d-457f-9670-0be71695ef45)

**Comment by sba923** [comment]
Confirmed here with PowerShell 7.4.0-preview.4 on Windows 10, with v2023.6.0 of the extension.

**Comment by andschwa** [comment]
Thanks, am looking at this with high priority.

**Comment by andyleejordan** [comment]
Yup, reproduces locally. Going to start testing versions backwards to see when it first breaks.

**Comment by andyleejordan** [comment]
Whelp, works in preview.3 and not preview.4 so at least that's pretty narrow!

**Comment by andyleejordan** [comment]
"Narrow" as I look at the diff...my current guess is from https://github.com/PowerShell/PowerShell/pull/14953 but I need to figure out exactly what.

**Comment by fflaten** [comment]
I can only reproduce on Windows, not Ubuntu. What about MacOS?

**Comment by fflaten** [comment]
Looks like the issue is a change to [case-sensitive path comparison in PowerShell (bug)](https://github.com/PowerShell/PowerShell/issues/20044#issuecomment-1656716810) *and* extension/PSES registering breakpoint with lowercase driveletter.

```powershell 
# breakpoint set in vscode
> Get-PSBreakpoint | fl * 

Column   : 0
Line     : 29
Action   : 
Enabled  : True
HitCount : 1
Id       : 1
Script   : c:\Users\Frode\Desktop\Demo\HelperModule.psm1

Script   : c:\Users\Frode\Desktop\Demo\HelperModule.psm1

# reference - notice driveletter
> dir .\HelperModule.psm1 | % fullname
C:\Users\Frode\Desktop\Demo\HelperModule.psm1
```

**Comment by andyleejordan** [comment]
@fflaten I can at least say that the server is registering with that driver letter being lowercase because it's literally coming across the wire that way (that is, in the `SetBreakpointsArguments` request of the `SetBreakpointsResponse` handler with OmniSharp). Not sure if it's something O# is doing, or if it's coming from the client like that. If I can fix that, theoretically this issue is "solved" (though I still think we should fix the behavioral regression in PowerShell until we do it intentionally).

**Comment by andyleejordan** [comment]
Uhh actually, more info! I see the _same behavior_ in the logs of the C# extension (also built on top of O#) where the drive letter is being lower-cased for every LSP request with a path. So it's definitely an O# thing. Grr.

**Comment by fflaten** [comment]
Might be intentional to align with VSCode API. `URI.fspath` also lowercases it ([source](https://code.visualstudio.com/api/references/vscode-api#Uri))

> **fsPath**: string
>
>The string representing the corresponding file system path of this Uri.
>
>Will handle UNC paths and normalize windows drive letters to lower-case. Also uses the platform specific path separator.

**Comment by andyleejordan** [comment]
@fflaten yup, that was exactly it! Ha, just saw this and figured out the same thing from a different investigation.
