### ISSUE TITLE
The 'powerShellDefaultVersion' setting was 'PowerShell (x64)' but this was not found!

### ISSUE THREAD

**Issue by TESTER-sec** [PowerShell/vscode-powershell#4669]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

1. Run PowerShell Command Explorer
2. Doing Step 1 above generates the following errors and logs:

7/20/2023 1:05:39 AM [NORMAL] - Visual Studio Code: v1.80.1 64-bit on Windows 64-bit
7/20/2023 1:05:39 AM [NORMAL] - PowerShell Extension: v2023.6.0
7/20/2023 1:05:39 AM [WARNING] - The 'powerShellDefaultVersion' setting was 'PowerShell (x64)' but this was not found! Instead using first available installation 'Windows PowerShell (x64)' at 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe'!
7/20/2023 1:05:39 AM [NORMAL] - Starting 'Windows PowerShell (x64)' at: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
7/20/2023 1:05:39 AM [NORMAL] - PowerShell process started with PID: 9080

3. The PowerShell Command Explorer never loads; VSCode hangs at:

![image](https://github.com/PowerShell/vscode-powershell/assets/97270395/87483f9d-dd6f-4f6c-a93c-d53295f14966)

![image](https://github.com/PowerShell/vscode-powershell/assets/97270395/57b11402-091b-41ef-b7a9-b1e4975b3923)

[Warn  - 1:10:41 AM] OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OmniSharp.Extensions.JsonRpc.RequestCancelled | @Request='OmniSharp.Extensions.JsonRpc.RequestCancelled'
[Error - 1:13:26 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:13:26 AM] Connection to PowerShell Editor Services (the Extension Terminal) was closed. See below prompt to restart!
[Error - 1:13:26 AM] PowerShell Editor Services client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
  
  

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.80.1
74f6148eb9ea00507ec113ec51c489d6ffb4b771
x64

Version: 1.80.1 (system setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

1. Install latest version of VSCode
2. Install latest version of VSCode PowerShell extension
3. Attempt to update the PowerShell Command Explorer

**Comment by kvietmeier** [comment]
I'm getting a subtly different error:
```
The 'powerShellDefaultVersion' setting was 'Windows PowerShell (64)' but this was not found! Instead using first available installation 'Windows PowerShell (x64)' at 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe'!
```
```
8/2/2023 2:36:16 PM [NORMAL] - Visual Studio Code: v1.81.0-insider 64-bit on Windows 64-bit

8/2/2023 2:36:16 PM [NORMAL] - PowerShell Extension: v2023.6.0

8/2/2023 2:36:16 PM [WARNING] - The 'powerShellDefaultVersion' setting was 'Windows PowerShell (64)' but this was not found! Instead using first available installation 'Windows PowerShell (x64)' at 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe'!

8/2/2023 2:36:16 PM [NORMAL] - Starting 'Windows PowerShell (x64)' at: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe

8/2/2023 2:36:16 PM [NORMAL] - PowerShell process started with PID: 27688

8/2/2023 2:36:22 PM [NORMAL] - Started PowerShell v5.1.22621.
```

It does load a second terminal for the extension but I can't run common commanmdlets - 
```
KV C:\Users\ksvietme\repos> # Create a throw away SA
$Foobar = New-AzStorageAccount -ResourceGroupName $ResourceGroup `
  -Name deleteme${RandomStorageACCT} `
  -Location $Region `
  -SkuName Standard_LRS `
  -Kind StorageV2

$Foobar
New-AzStorageAccount : Cannot validate argument on parameter 'ResourceGroupName'. The argument is null or empty. Provide an argument that is 
not null or empty, and then try the command again.
At line:2 char:51
+ $Foobar = New-AzStorageAccount -ResourceGroupName $ResourceGroup `
+                                                   ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzStorageAccount], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Management.Storage.NewAzureStorageAccountCommand

**Comment by andyleejordan** [comment]
@TESTER-sec Windows PowerShell is supported on a best-effort basis, can you please try installing PowerShell 7 (since that's what your setting indicates you're trying to use)? It could be that your Windows PowerShell session is very slow, you could also try increasing the timeout for startup with the setting `powershell.developer.waitForSessionFileTimeoutSeconds`.

@kvietmeier it looks like you're trying to pasted code that refers to a variable, `$ResourceGroup`, which you have not assigned in your session. This is unrelated, the logs indicate you'd set the default as `Windows PowerShell (64)` but this has a typo, as the name of the default you're trying to use is `Windows PowerShell (x64)` (note the X before the 64), which it correctly found and loaded for you.

**Comment by SydneyhSmith** [comment]
Thanks for your response @TESTER-sec , our extension does check which version of PowerShell is installed to set as the default, however if a version of PowerShell is set as the default then the user's choice is respected. 

There is a way to have VSCode ignore a particular setting in the sync if you prefer that...thanks!

"settingsSync.ignoredSettings": [ "settingNameHere" ]
