### ISSUE TITLE
default debugger configuration "PowerShell Launch Script" doesn't work

### ISSUE THREAD

**Issue by peetrike** [PowerShell/vscode-powershell#4670]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [x] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [x] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When creating VS Code Debugger configuration, using precreated configuration **PowerShell: Launch Script**, it doesn't work right after creating.  The problem is with attribute _script_: it has just a comment about what it could be.

Instead it could use input variable that would prompt for script name to launch.

### PowerShell Version

```console
PS Version: 7.3.6
```

### Visual Studio Code Version

```console
PS ❯ code --version
1.80.1
74f6148eb9ea00507ec113ec51c489d6ffb4b771
x64
```

### Extension Version

```console
PS ❯ code --list-extensions --show-versions | select-string powershell

ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

add configuration to debugger.  It will add:

```json
{
  "name": "PowerShell Launch Script",
  "type": "PowerShell",
  "request": "launch",
  "script": "enter path or command to execute e.g.: ${workspaceFolder}/src/foo.ps1 or Invoke-Pester",
  "cwd": "${cwd}"
},
```

**Comment by peetrike** [comment]
it seems that the same configuration is discussed in #2995

**Comment by andschwa** [comment]
It is a provided default meant to be configured. If you want a "click and run" experience you can just use the triangular "play" button on a PowerShell editor in VS Code, that will launch the script in the current file (also F5 will do it).
