### ISSUE TITLE
POWERSHELL "client is not running" 

### ISSUE THREAD

**Issue by Codex1012** [PowerShell/vscode-powershell#4677]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Can't conect to powershel server tryed using a bypass but still the problem persists.

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.3031                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.3031                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.80.1
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

all vscode no particular case.
every project is failing to conect

**Comment by SydneyhSmith** [comment]
@Codex1012 thanks for opening this issue, can you please provide more information such as logs and screenshots? Also can you let us know if this repros with PowerShell 7? Thanks!

**Comment by ThiloLangbeinHUK** [comment]
<img width="347" alt="image" src="https://github.com/PowerShell/vscode-powershell/assets/71653492/ea85a0c4-1c2f-4498-af9b-0ad021dfe98a">

**Comment by andyleejordan** [comment]
@ThiloLangbeinHUK can you please open a separate issue, following the issue template? We need more information from the original poster here (as requested) in order to help them, and we'll need the same from you. Thank you!
