### ISSUE TITLE
Get-WebApplication broken in VSCode, works in powershell terminal

### ISSUE THREAD

**Issue by jmiedreich** [PowerShell/vscode-powershell#4683]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When running vscode as administrator in windows and running Get-WebApplication, the following error occurs:

 Import-Module -Name WebAdministration
 Get-WebApplication 

Get-WebApplication : Object reference not set to an instance of an object.
At C:\VistaInstall\Env Audit Dev\Modules\Get-IIS-Web-Applications.ps1:6 char:5
+     Get-WebApplication -Site 'Default Website'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WebApplication], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.IIs.PowerShell.Provider.GetWebApplicationCommand

The command works fine in ISE and a PowerShell terminal, just not the integrated terminal.

Please advise, 
thanks
Jeremy

### PowerShell Version

```console
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.79.2
695af097c7bd098fbf017ce3ac85e09bbc5dda06
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

Run the code:

 Import-Module -Name WebAdministration
 Get-WebApplication

**Comment by SydneyhSmith** [comment]
@jmiedreich thanks for opening this issue, unfortunately I don't think there is anything we can do about this issue-- can you please open an issue on the module in feedback hub?
