### ISSUE TITLE
DateTime string arguments are being detected and mutated by the Debugger prior to invoking script

### ISSUE THREAD

**Issue by meop** [PowerShell/vscode-powershell#4685]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Consider the following snippet from launch.json:

`
{
            "name": "Pwsh - Upload Logs",
            "args": [
                "-StartDateTimeISOLowerBound",
                "2023-08-02T22:59:27.384Z",
            ],
            "type": "PowerShell",
            "request": "launch",
            "script": "${workspaceFolder}/scripts/upload_script.ps1",
            "cwd": "${workspaceFolder}",
 }
 `
 
 VS Code Powershell Debugger will show that it is being launched like this:
 
 . "<path>/scripts/upload_logs.ps1" -StartDateTimeISOLowerBound 08/02/2023 22:59:27
 
 But if I change the argument, like add an extra T to make it not a valid ISO format, it will launch correctly:
 
 . "<path>/scripts/upload_logs.ps1" -StartDateTimeISOLowerBound 2023-08-02TT22:59:27.384Z

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.80.2
2ccd690cbff1569e4a83d7c43d45101f817401dc
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

Already added in Summary.

**Comment by andyleejordan** [comment]
Have you tried single quotes around it?

**Comment by meop** [comment]
I did now. That worked. Interesting. Would not have thought to try that. Is that a workaround, or by design? Thank you.

**Comment by SydneyhSmith** [comment]
It is just how VSCode is parsing, not related to the extension
