### ISSUE TITLE
Debug adapter process has terminated unexpectedly error

### ISSUE THREAD

**Issue by vamichael** [PowerShell/vscode-powershell#469]
I'm getting this error after stopping a debugging session.  I have to restart code each time.

**Comment by daviwil** [comment]
Hey @vamichael, can you capture verbose logs and send them to me?  Here are some instructions:

https://github.com/PowerShell/vscode-powershell#reporting-problems

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
