### ISSUE TITLE
Windows 11 issue. terminal failure. Opening in separate window. commands not working. 

### ISSUE THREAD

**Issue by ANVLISTENER** [PowerShell/vscode-powershell#4695]
### Prerequisites

- [x] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

The integrated terminal feature in the VS Code not working. It opens seperate powershell terminal. Yet the commands are not working as expected. 

### PowerShell Version

```console
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
Version: 1.77.1 (system setup)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

WIndows 11. Windows Terminal. 

Ctrl + `

### Visuals

python
Program 'python.exe' failed to run: The create operation failed because the name contained at least one mount point
which resolves to a volume to which the specified device object is not attachedAt line:1 char:1
+ python
+ ~~~~~~.
At line:1 char:1
+ python
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

### Logs

8/11/2023 2:39:56 PM [NORMAL] - Visual Studio Code: v1.77.1 64-bit on Windows 64-bit

8/11/2023 2:39:56 PM [NORMAL] - PowerShell Extension: v2023.6.0

8/11/2023 2:39:58 PM [NORMAL] - Starting 'Windows PowerShell (x64)' at: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

8/11/2023 2:39:59 PM [NORMAL] - PowerShell process started with PID: 1096

8/11/2023 2:40:12 PM [NORMAL] - Started PowerShell v5.1.22621.

8/11/2023 2:41:07 PM [WARNING] - PowerShell process terminated or Extension Terminal was closed, PID: 1096

8/11/2023 2:41:07 PM [ERROR] - The PowerShell Extension Terminal has stopped, would you like to restart it? IntelliSense and other features will not work without it!

8/11/2023 2:41:10 PM [NORMAL] - Restarting session...

8/11/2023 2:41:10 PM [NORMAL] - Starting 'Windows PowerShell (x64)' at: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

8/11/2023 2:41:10 PM [NORMAL] - PowerShell process started with PID: 70916

8/11/2023 2:41:16 PM [NORMAL] - Started PowerShell v5.1.22621.

8/11/2023 2:41:37 PM [WARNING] - PowerShell process terminated or Extension Terminal was closed, PID: 70916

8/11/2023 2:41:37 PM [ERROR] - The PowerShell Extension Terminal has stopped, would you like to restart it? IntelliSense and other features will not work without it!

**Comment by andyleejordan** [comment]
That seems like an issue with Python, please file a bug with them.
