### ISSUE TITLE
PowerShell 7 not available

### ISSUE THREAD

**Issue by EnnexMB** [PowerShell/vscode-powershell#4697]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

VS Code with the PowerShell extension is able to run PowerShell 5.1 code, but not PS 7 code, and does not allw me to switch to PS 7.

### PowerShell Version

```console
PS> $PSVersionTable 

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
PS> code --version
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64
```

### Extension Version

```console
PS> code --list-extensions --show-versions | Select-String powershell 

ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

1. Running in Windows 11 Pro 64.
2. Installed PowerShell 7 and VS Code. I'm able to run PS 7 directly in Windows, which brings up a window titled "PowerShell 7 (x64)".
3. In VS Code, installed the PowerShell extension. 
4. In VS Code, I'm able to run Windows PowerShell 5.1, but PS 7 does not appear to be available.
5. I know VS Code is running PS 5.1 and not 7 because when I call `Get-Content ... -AsByteStream`, it doesn't recognize the parameter `AsByteStream`.
6. In VS Code, under "Get Started with PowerShell", there's an item, "Switch Sessions", which says, "To switch between PowerShell 7 and Windows PowerShell 5.1, use the menu: 'Open PowerShell Sessions Menu'" When I click on that button, I get a menu at the top that offers two versions of Windows PowerShell, but no PS 7, as shown in the attached display image.

![Screenshot 2023-08-11 111916_50%](https://github.com/PowerShell/vscode-powershell/assets/40837471/715d25cb-1fc1-464e-a054-347ae58d3e40)

### Logs

[1691799117-289d41fd-c657-4022-8f85-0e0dc89fe7521691799024611.zip](https://github.com/PowerShell/vscode-powershell/files/12326163/1691799117-289d41fd-c657-4022-8f85-0e0dc89fe7521691799024611.zip)

**Comment by EnnexMB** [comment]
I installed it with the MSI.
I installed it to "C: \Program Files\_added\Microsoft\ PowerShell\".
My $env:PATH includes "C:\Program Files\_added\Microsoft\PowerShell\7".

How can I find out where VS Code is currently looking for PS 7?

**Comment by andyleejordan** [comment]
It should be the full path including the name of the executable, so if it's at `C:\Program Files\_added\Microsoft\PowerShell\7\pwsh.exe` use that.

I think we've found the "issue" too and that's that we're definitely not checking that `_added` folder in our search logic, as it's a custom location!

And `$env:PATH` is not checked...though I suppose it could be a reasonable fallback if PowerShell isn't found at any of the "known" locations...I'll have to think about that.

**Comment by EnnexMB** [comment]
Okay, I added that setting, and the key for it now comes up in the sessions menu and I'm able to run the script with the parameter `AsByteStream`.

So PS 7 is now available to me in VS Code. Thank you.

I still would like to know how to find out what locations VS Code is looking in for PS 7.

**Comment by andyleejordan** [comment]
This is the search logic: https://github.com/PowerShell/vscode-powershell/blob/main/src/platform.ts

The success test cases here are bit more useful in understanding what that logic is doing: https://github.com/PowerShell/vscode-powershell/blob/24d6dcbb9a4535ced3bb8137367f116187c67b91/test/core/platform.test.ts#L78

**Comment by EnnexMB** [comment]
Oh, that's a lot of code for what I thought was a simple question! I thought maybe there'd be a variable like `$env:PATH` that would tell me all the places VS Code was looking for PS. But I guess it's not needed often enough to justify that.

Anyway, my problem is solved. Thank you.
