### ISSUE TITLE
Debugger hangs after adding watch expression with missing parameters

### ISSUE THREAD

**Issue by mrward** [PowerShell/vscode-powershell#470]
### System Details

- Operating system name and version: Mac El Capitan and Windows 10
- VS Code version: 1.8.1
- PowerShell extension version: v6.0.0-alpha.14 and 5.1.14393.693 (Windows).

### Issue Description

To repro:

1) Put a breakpoint on a line in a PowerShell script.
2) Run the debugger.
3) When the breakpoint is hit add "Write-Debug" without the quotes into the watch window.
4) The Debug Console shows a message:
```
cmdlet Write-Debug at command pipeline position 1.
Supply values for the following parameters:
Message:
```
5) The debugger now does not respond. You cannot step or continue.
6) Stopping the debugger and then starting again causes an error to be displayed: `Debug adapter process has terminated unexpectedly`.

### Attached Logs

There are no errors in the logs. The last thing output is the WriteMessage with the information about the Write-Debug command needing extra parameters.

**Comment by daviwil** [comment]
Thanks for the details!  I've seen a few reports about watch variables having issues with the latest release so I'll get this fixed for this week's patch update.

**Comment by SydneyhSmith** [comment]
Closing as this issue has been resolved
