### ISSUE TITLE
Binary Module Debugging with Script specified causes a terminal error exit -1 at the end of the debugging session on Windows only

### ISSUE THREAD

**Issue by ALIENQuake** [PowerShell/vscode-powershell#4702]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I'm getting a crash when I attempt to debug the binary module using a new configuration. The module is the not altered example binary module.

```
        {
            "name": "PowerShell: Binary Module Interactive",
            "type": "PowerShell",
            "request": "launch",
            "script": "Import-Module -Force ${workspaceFolder}/DebugPSModule/bin/Debug/net8.0/DebugPSModule.dll",
            "createTemporaryIntegratedConsole": true,
            "attachDotnetDebugger": true
          }
```
Launching test script works: `Test-SampleCmdlet -FavoriteNumber 8 -FavoritePet Dog`
```
VERBOSE: Begin!

VERBOSE: End!
FavoriteNumber FavoritePet
-------------- -----------
             8 Dog
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.23521
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23521
```

### Extension Version

```console
PowerShell Extension v2023.6.0
C# Dev Kit v0.3.21
NET Install Tool for Extension Authors v1.7.0
Inline Values support for PowerShell v0.0.7
```

### Steps to Reproduce

- Hit F5

### Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/12362810/logs.zip)
[sessions.zip](https://github.com/PowerShell/vscode-powershell/files/12362812/sessions.zip)

**Comment by JustinGrote** [comment]
@ALIENQuake what kind of "crash"? Full system crash? vscode crash? Can you use a tool like screen2gif or zoomit to record what happens?

The process just triggers the omnisharp debugger so anything that would make that crash would make this crash.

**Comment by ALIENQuake** [comment]
@JustinGrote His is how it looks at my side:

https://github.com/PowerShell/vscode-powershell/assets/365255/eb88547e-725d-4e32-afd7-4c2f24403f50

**Comment by JustinGrote** [comment]
@ALIENQuake I see an F: drive in use here. Is this a local drive or a network share?

**Comment by ALIENQuake** [comment]
@JustinGrote All drives are local ones.

**Comment by JustinGrote** [comment]
Also according to the logs, your import module resolves to `Import-Module -Force C:\\Users\\ALIEN\\Desktop\\a1/DebugPSModule/bin/Debug/net8.0/DebugPSModule.dll` which may not be correct? What does your debug config look like?

**Comment by ALIENQuake** [comment]
@JustinGrote The path to the dll is correct as I'm able to import it before launching Test-SampleCmdlet. This is my launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PowerShell: Launch Current File",
            "type": "PowerShell",
            "request": "launch",
            "script": "${file}",
            "args": []
        },
        {
            "name": "PowerShell: Binary Module Interactive",
            "type": "PowerShell",
            "request": "launch",
            "script": "Import-Module -Force ${workspaceFolder}\\DebugPSModule\\bin\\Debug\\net8.0\\DebugPSModule.dll",
            "createTemporaryIntegratedConsole": true,
            "attachDotnetDebugger": true
        }
    ]
}
```

**Comment by JustinGrote** [comment]
OK, I'm seeing this too, I think it may have something to do with the major 2.0 C# update.

**Comment by JustinGrote** [comment]
So the command and debug session itself work fine, I just think when the pwsh process ends, it's not being handled correctly. You shouldn't have any problem debugging in-and-of-itself, this looks to just be a cosmetic cleanup thing, thanks for reporting!

![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/bf816879-2c3f-4d50-8fef-24364f5f4fb7)

**Comment by JustinGrote** [comment]
@andyleejordan is there anything in PSES that would cause it to `exit -1`?

**Comment by ALIENQuake** [comment]
@JustinGrote I still can't debug anything. I simply want to recreate the debugging experience that you have presented at https://github.com/PowerShell/vscode-powershell/pull/3903 but no matter what I do, I'm getting crash and debugged doesn't stop at the .cs file breakpoints.

**Comment by andyleejordan** [comment]
> @andyleejordan is there anything in PSES that would cause it to `exit -1`?

Not that I can think of!

**Comment by JustinGrote** [comment]
@ALIENQuake debugging and breakpoints work just fine for me, I can't reproduce:
![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/600a0e1f-c084-4d53-ac09-d22e9cbccf7e)

**Comment by ALIENQuake** [comment]
I confirm that debugging works, thumbs up for resolving remaining error.

**Comment by JustinGrote** [comment]
@ALIENQuake glad to here, I'm going to retitle this issue and reuse it for solving the terminal error

**Comment by JustinGrote** [comment]
The problem is that the attach being stopped actually kills the process rather than disconnecting, but there doesn't appear to be an extension api to initiate a disconnect, so this is blocked on:
https://github.com/microsoft/vscode-discussions/discussions/767

**Comment by andyleejordan** [comment]
Thanks for debugging @JustinGrote!

**Comment by ALIENQuake** [comment]
@JustinGrote Thank you!
