### ISSUE TITLE
Issue with Intune's EPM (Endpoint Privilege Management)

### ISSUE THREAD

**Issue by ThiloLangbeinHUK** [PowerShell/vscode-powershell#4705]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

If there is an elevation policy (https://learn.microsoft.com/en-us/mem/intune/protect/epm-policies#about-windows-elevation-rules-policy) for powershell.exe, there is an error "PowerShell Language Server process didn't start!" on starting a PowerShell session. 

It seems a similarsame problem as stated here: https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#known-issues-in-the-extension 

"The Language Service could not be started" but it does start with the x86 version of PowerShell.

Do you use Avecto / BeyondSoft? We've received reports that Avecto, BeyondSoft and other privilege management software dramatically slow down the start up of Windows PowerShell x64. Please give the privilege management software feedback.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

- start vs code
- open a ps1 file

**Comment by andyleejordan** [comment]
Hm, this is useful information to have thank you. I am not sure there is anything actionable we can do here (other than update the troubleshooting documentation). We're not requesting that the PowerShell process start with elevated privileges, so this seems like something very Intune EPM specific, and maybe a bug with them.

**Comment by ThiloLangbeinHUK** [comment]
I run vscode as *User setup* (https://code.visualstudio.com/docs/setup/windows#_user-setup-versus-system-setup) without admin proviledges. So PowerShell extension should/cannot run powershell.exe with elevated priviledges.

**Comment by andyleejordan** [comment]
Then yeah, it should be working.

**Comment by kevinjum** [comment]
endpoint privilege management run elevation access with visual studio failed.
