### ISSUE TITLE
E2E CWD Path test flaky in ADO since CWD changes

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#4706]
### Summary

![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/dac27b00-cfc8-42b4-b49b-0d46a119fcd1)

**Comment by andyleejordan** [comment]
Definitely flaky, I saw this and wasn't sure what was causing it.

**Comment by andyleejordan** [comment]
(Also it's a _new_ test that is flaky.)

**Comment by andyleejordan** [comment]
After migrating everything over to GitHub Actions properly, I haven't seen _any_ flakiness!
