### ISSUE TITLE
Enable IntelliSense in the debug console

### ISSUE THREAD

**Issue by komal436** [PowerShell/vscode-powershell#471]
**Please fill in these details so that we can help you!**
The details are as follows:
https://github.com/Microsoft/vscode/issues/19430 
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

### Issue Description

I am experiencing a problem with...

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Hey @komal436, we are planning to replace the Debug Console with a real interactive terminal experience for our debugger, so you should get full tab completion there.  I'll keep this bug open until then.  Thanks!

**Comment by daviwil** [comment]
Closing this in favor of #10, that's where we're tracking the integrated console work.  This will be released soon!
