### ISSUE TITLE
Issue with Syntax Coloring

### ISSUE THREAD

**Issue by Roadkill4545** [PowerShell/vscode-powershell#472]
### System Details

- Operating system name and version:  Windows 8.1
- VS Code version:  1.8.1 
- PowerShell extension version:  0.9.0
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Evaluate $PSVersionTable in PowerShell and paste the output here

### Issue Description

This should be an easy one (I hope!).  I am experiencing a problem with syntax highlighting and color.  The syntax coloring becomes off when I use the following line of code in my script:

    [ValidatePattern("^([0-9A-Ha-h][0-9A-Ha-h](:|-)?){7}[0-9A-Ha-h][0-9A-Ha-h]`$")][String[]] $Wwpn,

Specifically, it takes issue with the backtick-dollarsign combination.  If I remove the dollar sign, the coloring in all of the code below this line works again.  Note the code itself works correctly, its simply the syntax color highlighting in VS Code that breaks.  Here is an example of how to reproduce:

1)  Create a new script in VS Code.  
2)  Save it as a .ps1 file.
3)  Paste this code function snippet inside.

   ```
 function Test-Function1()
    {
      param
      (
        [ValidatePattern("^([0-9A-Ha-h][0-9A-Ha-h](:|-)?){7}`$")][String[]] $Wwpn,
        [string] $p1,
        [string] $p2
      )
      Write-Host ("All of the text colors are correct, but they will be broken below.")
    }
    
    function Test-Function2()
    {
      param
      (
        [ValidatePattern("^([0-9A-Ha-h][0-9A-Ha-h](:|-)?){7}[0-9A-Ha-h][0-9A-Ha-h]`$")][String[]] $Wwpn,
        [string] $p1,
        [string] $p2
      )
      Write-Host ("The [0-9A-Ha-h][0-9A-Ha-h] sequence in function1 above breaks the code coloring.  Not sure why...")
    }

    # Observe the oddness in code coloring.  However the functions above indeed do work!

```

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by Roadkill4545** [comment]
I munged up the formatting on the code.  I updated it above.  (Sorry about that).

**Comment by rkeithhill** [comment]
The syntax highlighting for PowerShell is done in the https://github.com/PowerShell/EditorSyntax project.  Can you post this defect there?

**Comment by daviwil** [comment]
This issue was moved to PowerShell/EditorSyntax#32

**Comment by daviwil** [comment]
Thanks @Roadkill4545, I just moved the issue over to the PowerShell/EditorSyntax repo so that we can track it there.

**Comment by Roadkill4545** [comment]
Thank you!  Sorry for the misunderstanding.

**Comment by daviwil** [comment]
No misunderstanding at all, we need to be more clear about where to file syntax bugs.
