### ISSUE TITLE
PowerShell extension fails to start when the log level is set to None

### ISSUE THREAD

**Issue by skycommand** [PowerShell/vscode-powershell#4735]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
  - Not necessary in this case.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).
  - Not a security issue.

### Summary

Hello. After installing the PowerShell extension, several new settings get added to Visual Studio Code, one of them is called "PowerShell › Developer: Editor Services Log Level" (`powershell.developer.editorServicesLogLevel`). The UI offers me several choices for this setting:

- Diagnostics
- Verbose
- Normal
- Warning
- Error
- None

However, it appears the "None" setting is invalid.

Today, I set `powershell.developer.editorServicesLogLevel` to `None` (via the UI). The extension prompted for a restart. Open the restart, the extension failed to start, generating the following error message:

> The terminal process "C:\Program Files\PowerShell\7\pwsh.exe [...]" terminated with exit code: 1.

<details><summary>Full error message (click me)</summary>

> The terminal process "C:\Program Files\PowerShell\7\pwsh.exe '-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', 'Import-Module 'c:\Users\BRAINZ\.vscode\extensions\ms-vscode.powershell-2023.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2023.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\BRAINZ\.vscode\extensions\ms-vscode.powershell-2023.6.0\modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2023.6.0
> Copyright (c) Microsoft Corporation.
> 
> https://aka.ms/vscode-powershell
> Type 'help' to get help.
> " -LogLevel 'None' -LogPath 'c:\Users\BRAINZ\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\logs\1694633969-3d04be6b-b942-463a-8b12-1455353dd7661694633907551\EditorServices.log' -SessionDetailsPath 'c:\Users\BRAINZ\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSCode-8676-414595.json' -FeatureFlags @() '" terminated with exit code: 1.

</details>

I tried simulating the launch process explained in the message by issuing the following commands:

```PowerShell
& 'C:\Program Files\PowerShell\7\pwsh.exe' -NoProfile -ExecutionPolicy 'Bypass'

Import-Module 'e:\Programs\Visual Studio Code\data\extensions\ms-vscode.powershell-2023.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'

Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2023.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'e:\Programs\Visual Studio Code\data\extensions\ms-vscode.powershell-2023.6.0\modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2023.6.0
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
" -LogLevel 'None' -LogPath 'e:\Programs\Visual Studio Code\data\user-data\User\globalStorage\ms-vscode.powershell\logs\1694635914-512c5bcf-1a69-4a92-94a7-14df9ca2e3c21694635892002\EditorServices.log' -SessionDetailsPath 'e:\Programs\Visual Studio Code\data\user-data\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSCode-9504-479834.json' -FeatureFlags @()
```

And here is the output:

```Output
Start-EditorServices:
Line |
   6 |  " -LogLevel 'None' -LogPath 'e:\Programs\Visual Studio Code\data\user …
     |              ~~~~~~
     | Cannot bind parameter 'LogLevel'. Cannot convert value "None" to type "Microsoft.PowerShell.EditorServices.Hosting.PsesLogLevel". Error: "Unable to match the identifier name None to a valid enumerator name. Specify one of the following enumerator names and try again:
Diagnostic, Verbose, Normal, Warning, Error"
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.82.0
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

1. Install Visual Studio Code 1.82.0, which is the latest version as of this moment.
2. Install the PowerShell extension.
3. Open a new file (Ctrl+N).
4. Set the language to PowerSehll.
5. Wait for the PowerShell console to launch. (Some people call it PowerShell's terminal.)
6. Open Settings (Ctrl+,).
7. Find "Editor Services Log Level". Confirm that it corresponds to `powershell.developer.editorServicesLogLevel`.
8. Use the drop down box to set the setting to None.
9. Agree to restart the PowerShell language server.

### Visuals

The `powershell.developer.editorServicesLogLevel` in its default mode.
![1](https://github.com/PowerShell/vscode-powershell/assets/17097175/e0b96980-0f9a-45af-ae9c-b804b87edd4e)

Changing it:
![2](https://github.com/PowerShell/vscode-powershell/assets/17097175/15ae4d4d-ee32-4bf6-835b-79cdc69b829c)

The restart prompt:
![3](https://github.com/PowerShell/vscode-powershell/assets/17097175/dbf6d1e0-671f-4de6-a6b8-d1b83fe2c742)

A PowerShell error message briefly flashes across the screen, then disappears.
![4](https://github.com/PowerShell/vscode-powershell/assets/17097175/a6e517a0-cdc8-497b-ac10-f6a05d0aa7a5)

Visual Studio Code reports error.
![5](https://github.com/PowerShell/vscode-powershell/assets/17097175/ca40f54c-f198-4c0c-95c3-6bd5f36a1e9b)

### Logs

This issue is about logs themselves.

**Comment by andyleejordan** [comment]
Oops, server-side change must have never made it in.
