### ISSUE TITLE
PowerShell extension settings placed in `'~\AppData\Roaming\Code\User\settings.json'` dont work at all

### ISSUE THREAD

**Issue by RalfReddings** [PowerShell/vscode-powershell#4746]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I am trying to set up my PowerShell development environment to my liking by using the various PowerShell settings found in the `defaultSetting.json` file in my `settings.json` file. But none of them are working at all. I have 
- Uninstalled the extension, then reinstalled it
- Uninstalled Code, then reinstalled it
- Cleared out all my settings and other extensions etc 

I have no other idea what is going on, I can only assume this is a bug. 

I have provided a gif below to demonstrate this issue better:

![](https://i.imgur.com/9smT4t7.gif)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
Version:          Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS Version:       Windows_NT x64 10.0.22621
CPUs:             AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)
Memory (System):  127.93GB (99.32GB free)
VM:               0%
Screen Reader:    no
```

### Extension Version

```console
v2023.6.0
```

### Steps to Reproduce

- Disable all other extensions but PowerShell and then reload the code window
- Empty out all settings from `'~\AppData\Roaming\Code\User\settings.json'` and place `{"powershell.integratedConsole.focusConsoleOnExecute": false}` in it, reload window.
- Focus another terminal, with a `.ps1` focused start debugging
- The `PowerShell Extension` terminal gets activated despite `{"powershell.integratedConsole.focusConsoleOnExecute": false}`

**Comment by SydneyhSmith** [comment]
Thanks @RalfReddings these settings are controlled by VSCode, so you will need to open an issue in their repo, unfortunately we are having difficulty reproducing this issue... thanks for the repro steps
