### ISSUE TITLE
Skip all Write-Host when debugging

### ISSUE THREAD

**Issue by ALIENQuake** [PowerShell/vscode-powershell#4748]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Hi,

recently I've been facing many 'Write-Host' instances and it slows down executing the next lines.

Any way to skip such lines? Does the debugger can skip some lines at all?

**Comment by SydneyhSmith** [comment]
Thanks for the issue, @ALIENQuake 

We actually believe that the slowness is due to PowerShell being in a debugging state which takes away some of the optimizations

**Comment by ALIENQuake** [comment]
That might be true but even so, this feature request is not about slowdowns during step-by-step debugging. It's about not having to press F10/F11 several times without losing any valuable information when debugging. Let's consider the following example:

```powershell
New-MyCommand -Value '1'
Write-Host "Title:"
Write-Host "Output A: $A"
Write-Host "Output B: $B"
Write-Host "Output C: $C"
Write-Host "Preparing next steps"
New-MyOtherCommand -Value '1'
```

When I'm debugging this code several times, I don't really care about what Write-Host lines will show. I only care about the effect of two commands that actually do stuff.

Please reconsider this.

**Comment by SeeminglyScience** [comment]
It's not an uncommon practice for folks to actively step `Write-Host`s that contain state to see the values as execution happens. While log points or utilizing hover/variable pane may be a more (subjectively) efficient pattern, skipping `Write-Host` would be confusing for a lot of users.

If you have a large portion of code you'd like to quickly step over, the easiest workaround is enclosing them in their own scriptblock:

```powershell
New-MyCommand -Value '1'
& { 
    Write-Host "Title:" # Once you step here, use "Step Out" to get to `New-MyOtherCommand`
    Write-Host "Output A: $A"
    Write-Host "Output B: $B"
    Write-Host "Output C: $C"
    Write-Host "Preparing next steps"
}

New-MyOtherCommand -Value '1'
```
