### ISSUE TITLE
> I think your regex has multiple issues. I don't have time at the moment to really dig into it, but wanted to offer an alternative approach.

### ISSUE THREAD

**Issue by rotsen11** [PowerShell/vscode-powershell#4749]
> I think your regex has multiple issues. I don't have time at the moment to really dig into it, but wanted to offer an alternative approach.
> 
> ```powershell
> switch -regex ($vssadmin){
>     "^\w.*'(?<Name>.*)'$" {$ht = @{Name = $matches.name}}
>     "^\s+(?<Name>\w[\w\s]*): (?<Value>.*)$" {
>         $ht.Add($matches.Name,$matches.Value)
>         if($matches.Name -like '*err*'){
>             [PSCustomObject]$ht
>         }
>     }
> }
> ```

I miss some output with this code

_Originally posted by @B-Art in https://github.com/PowerShell/PowerShell/issues/19754#issuecomment-1579286313_

**Comment by andyleejordan** [comment]
I don't understand why this was opened here.
