### ISSUE TITLE
When powershell.integratedConsole.showOnStartup:True, two terminals appear on startup.

### ISSUE THREAD

**Issue by begna112** [PowerShell/vscode-powershell#4750]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Related issues:
* https://github.com/PowerShell/vscode-powershell/issues/3925
* https://github.com/PowerShell/vscode-powershell/issues/4471

When `powershell.integratedConsole.showOnStartup:True`, the expectation is that a singular PS Integrated Console will open in whichever version of PS (5.1/7) that you use. This is needed for the LSP server in the extension. 

The problem is that when `powershell.integratedConsole.showOnStartup` is set to `True` and both versions of PS are installed, two terminals launch: a pwsh native terminal and a PS Integrated Console terminal. 

![image](https://github.com/PowerShell/vscode-powershell/assets/10567958/28819a71-d4a2-48c1-b86f-0df4b4d6cd5f)

The additional pwsh terminal is useless if you're using F5/F8 executions, PSScriptAnalyzer, and Intellicode. It just takes up memory. 

![image](https://github.com/PowerShell/vscode-powershell/assets/10567958/df38653f-353c-40c1-86e9-581274e68243)

When `powershell.integratedConsole.showOnStartup` is set to `False`, the behavior is actually corrected, _**however**_, you then can't see a terminal on startup. Note in Task manager, there's no pwsh process and when I execute code with F5/F8, no pwsh window opens—just the PSIC, and PS extension functions work as expected. 

![image](https://github.com/PowerShell/vscode-powershell/assets/10567958/8a4ed727-acd0-471b-9a99-8fef1cd12c77)

I find value in having a terminal open on startup, but I don't want the extra pwsh terminal to open every time. So setting it to false is not a valid solution to this issue. Please don't suggest that, as it was in the other related issues. This is a _bug_ that needs to be resolved. 

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
code --version
1.82.2
abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
x64
```

### Extension Version

```console
code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

1. Open a PS file in VSCode. Contents can be anything, for example: `Write-Host "hello"`
2. Change Setting: `powershell.integratedConsole.showOnStartup` to `False`
3. Close VSCode and reopen the PS file. 
4. No terminal should open.
5. Select a line of code and press F8. The background PSIC terminal (labeled "Powershell Extension") should appear. No *_additional_* pwsh terminal should be open. Checking Task Manager, only the single powershell or pwsh process should be open under the VSCode process category.
6. Change Setting: `powershell.integratedConsole.showOnStartup` to `True`
7. Close VSCode and reopen the PS file. 
8. Both `pwsh` and `Powershell Extension` PSIC terminals should open. Running F8 code will go to the PSIC terminal.

Point 8's behavior is the bug.

**Comment by SydneyhSmith** [comment]
Unfortunately that's an issue with VS Code that you can't disable that pwsh from opening; as an extension author I cannot prevent that.

Thanks for the issue @begna112

**Comment by begna112** [comment]
> Unfortunately that's an issue with VS Code that you can't disable that pwsh from opening; as an extension author I cannot prevent that.
> 
> Thanks for the issue @begna112

Honestly, that doesn't make any sense. If it works when opening it in the background, why would it behave differently when opened in the foreground?
