### ISSUE TITLE
PowerShell could not be started, Starting the CLR failed with HRESULT 80040153

### ISSUE THREAD

**Issue by fdncred** [PowerShell/vscode-powershell#476]
### System Details

- Operating system name and version: Windows 10 Enterprise, Version1607, Build 14393.693
- VS Code version: 1.9.0-insider
  -Version 1.9.0-insider
  -Commit fcac9b686abe4292e69a774f61c8c4ce17768bf5
  -Date 2017-01-31T00:57:46.157Z
  -Shell 1.4.6
  -Renderer 53.0.2785.143
  -Node 6.5.0
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

|Name                           |Value
|-------------------------|-----------------------
|PSVersion                     |5.1.14393.693
|PSEdition                      |Desktop
|PSCompatibleVersions |{1.0, 2.0, 3.0, 4.0...}
|BuildVersion                 |10.0.14393.693
|CLRVersion                   |4.0.30319.42000
|WSManStackVersion    |3.0
|PSRemotingProtocolVersion      |2.3
|SerializationVersion      |1.1.0.1

### Issue Description

I am experiencing a problem with powershell projects .I've had this problem with the past few released. I open a folder with a powershell script and I get this error, "PowerShell could not be started, click 'Show Logs' for more details.  powershell.exe terminated with exit code: 4294901760

### Attached Logs
[vscode-powershell.zip](https://github.com/PowerShell/vscode-powershell/files/742049/vscode-powershell.zip)

**Comment by daviwil** [comment]
Your log contains a very strange COM error:

```
Starting the CLR failed with HRESULT 80040153
```

Based on a little research, it seems that this error code is [REGDB_E_INVALIDVALUE](https://msdn.microsoft.com/en-us/library/cc704587.aspx?f=255&MSPPError=-2147217396), "Invalid value for registry".  This sounds like a problem on the system rather than a problem with the PowerShell extension.

Do you get any similar errors or crashes when you try to launch PowerShell under normal circumstances?  What about when you try running powershell.exe with `-NoProfile` or `-ExecutionPolicy Unrestricted` parameters?

**Comment by fdncred** [comment]
I can run powershell from the command prompt just fine with either -NoProfile or -ExecutionPolicy Unrestricted. I can also run it as administrator or regular user without issue or with ISE and without. I looked for a way to repair powershell but didn't see one.

**Comment by daviwil** [comment]
What happens if you run VS Code as administrator?

**Comment by fdncred** [comment]
Thanks for continuing to help me troubleshoot.  

The same thing happens. I just ran it and this was the output.


    powershell.exe started --
        pid: 14936
        exe: C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe
        bundledModulesPath: C:\Users\20396600\.vscode-insiders\extensions\ms-vscode.PowerShell-0.9.0\modules
        args: C:\Users\20396600\.vscode-insiders\extensions\ms-vscode.PowerShell-0.9.0\scripts\Start-EditorServices.ps1 -EditorServicesVersion '0.9.0' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '0.9.0' -BundledModulesPath 'C:\Users\20396600\.vscode-insiders\extensions\ms-vscode.PowerShell-0.9.0\modules' -LogLevel 'Verbose' -LogPath 'C:\Users\20396600\.vscode-insiders\extensions\ms-vscode.PowerShell-0.9.0\logs\1485962016-467ada30-8152-4089-92e1-ba9cac57d77b1485962013160\EditorServices.log' 

    ERROR: Starting the CLR failed with HRESULT 80040153

    PowerShell could not be started, click 'Show Logs' for more details.
    powershell.exe terminated with exit code: 4294901760

I've also noticed that there is no EditorServices.log created.

**Comment by daviwil** [comment]
Yep, no EditorServices.log will be created because powershell.exe never fully started up.  I'll have to ask someone internally if they've seen this error before.

**Comment by fdncred** [comment]
I'm not sure how helpful this is but I used procmon.exe to see the command line that is being issued by vscode and ran it.

    C:\Users\20396600>C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'C:\Users\20396600\.vscode-insiders\extensions\ms-vscode.PowerShell-0.9.0\scripts\Start-EditorServices.ps1' -EditorServicesVersion '0.9.0' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '0.9.0' -BundledModulesPath 'C:\Users\20396600\.vscode-insiders\extensions\ms-vscode.PowerShell-0.9.0\modules' -LogLevel 'Verbose' -LogPath 'C:\Users\20396600\.vscode-insiders\extensions\ms-vscode.PowerShell-0.9.0\logs\1485975503-97af0dca-64a2-4195-a63c-0eeb7bcd642b1485975498333\EditorServices.log' "
    {"debugServicePort":29954,"status":"started","channel":"tcp","languageServicePort":23601}

I only changed it from Sysnative to System32.

It appears to have started just fine and even created the editorservices.log. However, the same error exists in the vscode-powershell.log.  So i'm not sure what's going on here.

Attached are the newer logs.
[logs-02-01-2107.zip](https://github.com/PowerShell/vscode-powershell/files/745859/logs-02-01-2107.zip)

**Comment by daviwil** [comment]
Oh!  Is this 32-bit Windows?

**Comment by fdncred** [comment]
No, was I not supposed to use System32?  My system is 64-bit.

**Comment by daviwil** [comment]
Nah, 64-bit should be fine.  I'm just confused why running the `c:\Windows\sysnative` variant would cause this error.  VS Code runs as a 32-bit process, so the default behavior of the PowerShell extension is to run the 64-bit powershell.exe from `c:\Windows\sysnative` so that the 32-bit version doesn't get run by default.  

There are two things you can try:

- Change the `powershell.useX86Host` setting to `true`
- Change the `powershell.developer.powerShellExePath` setting to `C:/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe` (note the slash direction)

Either of those will force the 32-bit version of PowerShell to be used.  I'm curious to hear if this fixes the problem, but also uncertain of what to do about it if this fixes it.

**Comment by fdncred** [comment]
Your suggestions didn't make any difference.  Same "Error starting blah blah blah".

I also tried my command line again substituting sysWOW64 in place of Sysnative and it runs fine.  I then tried to change the settings to usex86Host to false and changing the powerShellExePath to use sysWOW64. None of that made any difference.  Everything still fails with the same error. :(

**Comment by daviwil** [comment]
Is this only happening on a particular machine?  Anything special about that machine like restrictive security or group policy settings?

**Comment by fdncred** [comment]
I only have 1 machine with vscode-insiders. It happens on that machine.  I run vscode (non-insiders) on another machine and things work close to normal.

**Comment by daviwil** [comment]
On the machine which has trouble, have you tried this with non-insiders to see if it works there?  It'd be good to know if they broke me somehow with the latest changes.

**Comment by fdncred** [comment]
I'll install non-insiders on that machine and get back with you shortly.

**Comment by fdncred** [comment]
Unfortunately, non-Insiders fails exactly like vscode-Insiders.

**Comment by daviwil** [comment]
Thanks for trying that out, it's sort of a relief that vscode-stable has the same behavior.  I'll keep looking for answers.

**Comment by wsmelton** [comment]
Just noting, I'm on Windows 10 (same PS Version and Build Number), but my Commit of VS Insider has a different value. I have no issues running either edition on my machine.

[Note I just updated Insider version on my machine today.]

![image](https://cloud.githubusercontent.com/assets/11204251/22532444/bd2c1b64-e8ac-11e6-919a-0a5cd4328e60.png)

Have you tried removing and reinstalling VS Code (both editions)?

**Comment by fdncred** [comment]
This morning I uninstalled vscode and vscode-insiders and removed all the .vscode folders from AppData so everything was gone.  I then reinstalled vscode-insiders, installed settings-sync plugin and all my plugins were reinstalled.  I opened a folder with a ps1 file and it is still broken as before.  I'm running the same version of insider as the above screenshot.

Any other ideas?

**Comment by wsmelton** [comment]
My opinion this is to specific to your machine configuration. If you are on a domain it could be policies, even if you are not could be AV software or any number of things.

1. Disable all your plugins except for PS Extension. Just open VS Code (no folder, no ps1 file) and set integrated terminal to open PowerShell and see if it opens.
2. If that does not work, login to your machine as a new user account (one that has never been used on your machine) and see if VS Code opens PowerShell.

**Comment by fdncred** [comment]
Integrated terminal with PowerShell works fine. Always has, with or without all my extensions. I'll try another account after while.  Any thoughts on using/installing PowerShell 6.0 alphas?

**Comment by fdncred** [comment]
I tried these versions:

* 0.6.0
* 0.7.1
* 0.7.2
* 0.8.0

All give the same type of error but slightly different from version 0.9.0.

    ERROR: & : AuthorizationManager check failed.

    PowerShell could not be started, click 'Show Logs' for more details.
    ERROR: At line:1 char:3
    + & 'C:\Users\20396600\.vscode-insiders\extensions\ms-vscode.PowerShell ...
    +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : SecurityError: (:) [], PSSecurityException
        + FullyQualifiedErrorId : UnauthorizedAccess


    powershell.exe terminated with exit code: 1

Is there some way to tell what is giving the UnauthorizedAccess error?  I assume it's some registry key since that's what 0.9.0 seems to indicate.

**Comment by daviwil** [comment]
Thanks for trying all of those!  The AuthorizationManager error is interesting, but those are generally related to execution policy settings.  Since you said earlier that you are able to run the same command string that the PS extension runs, I'm guessing that your PC has no problem running with an Unrestricted execution policy.

At this point it seems like this must be caused by running PowerShell as a child process of VS Code (Node.js).  Not sure how it could be happening though.  I'll think on it some more.

**Comment by fdncred** [comment]
Here's a screenshot from vscode-insiders with my Execution policies.  Should they all be set the same?

![code - insiders_2017-02-03_09-29-34](https://cloud.githubusercontent.com/assets/343840/22597004/6333713c-e9f3-11e6-8e9c-fff6d8757536.png)

**Comment by daviwil** [comment]
I don't think so, here's what it looks like on my machine where everything works fine:

![image](https://cloud.githubusercontent.com/assets/79405/22597090/088a7ad8-e9e3-11e6-9b8b-96eca5cffc14.png)

**Comment by fdncred** [comment]
Is there anything else I could try?  Do you have any tips of how to debug deeper into the issue to figure out what's going on?  I'm up for anything.

**Comment by daviwil** [comment]
Hey Darren, thanks for continuing to look into this.  I found [this link](https://community.spiceworks.com/topic/849064-authorizationmanager-check-failed) which has a couple of suggestions.  One that seems interesting is to run `sfc /scannow` to check if there are any corrupted Windows system files.  Maybe give that a shot and see if it returns anything interesting?

They also mention checking for WMI corruption so that might also be helpful:

http://nmsiam.blogspot.co.uk/2013/01/monitoring-for-wmi-corruption-issues.html

**Comment by fdncred** [comment]
I ran sfc /scannow and it reported, "Windows Resource Protection did not find any integrity violations." I then downloaded and ran WMIDiag.vbs from Microsoft and it found errors!  So then I ran the batch file from monitoring-for-wmi-corruption-issues and it renamed and recreated my wmi repository.  Then reboot. Then I ran winmgmt /verifyrepository and there were no inconsistencies!

Unfortunately, I'm in the same place I started and still have HRESULT 80040153.  I was so hopeful and now I'm so bummed.

Thanks for the attempt. At least my WMI repo is fixed now. LOL.

**Comment by fdncred** [comment]
Is there something I can to do help debug this?

**Comment by fdncred** [comment]
FYI - This issue seems to be resolved with the latest build. I can debug with breakpoints and such and don't get the errors I used to.

![image](https://cloud.githubusercontent.com/assets/343840/24050014/a4046940-0afb-11e7-9a94-4346d27b1ebc.png)
and
![image](https://cloud.githubusercontent.com/assets/343840/24050045/b5e887ae-0afb-11e7-9e74-8e91200528cc.png)

Thanks!!!

**Comment by daviwil** [comment]
I am so happy to hear that!  Looks like the VS Code team changed something about how they launch processes.  Let me know if you ever run into this again and we can ask them about it.  Thanks!
