### ISSUE TITLE
`Troubleshooting.md` has outdated info on log location

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/vscode-powershell#4774]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

[`Troubleshooting.md#logs`](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#logs) says following is the log location:

> Logs are located at ~/.vscode[-insiders]/extensions/ms-vscode.powershell[-preview]-<version>/logs. For example: ~/.vscode/extensions/ms-vscode.powershell-2019.5.1/logs

I found no `logs` directory at this location (`%USERPROFILE%\.vscode\extensions\ms-vscode.powershell-2023.6.0` in my scenario).

I then ran the `PowerShell: Open PowerShell Extension Logs Folder` command, and found that logs are located at:

* `%APPDATA%\Code\User\globalStorage\ms-vscode.powershell\logs\<new_directory_for_each_session\`

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.83.0
e7e037083ff4455cf320e344325dacb480062c3c
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

Look for `vscode-powershell` logs.

**Comment by andyleejordan** [comment]
Oh yeah I think they were moved to a VS Code provided location for extension storage...
