### ISSUE TITLE
Stuck at Starting Powershell

### ISSUE THREAD

**Issue by musaugurlu** [PowerShell/vscode-powershell#478]
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.8.1
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

| Name                      |          Value          |
|---------------------------|:-----------------------:|
| PSVersion                 |      5.1.14393.693      |
| PSEdition                 |         Desktop         |
| PSCompatibleVersions      | {1.0, 2.0, 3.0, 4.0...} |
| BuildVersion              | 10.0.14393.693          |
| CLRVersion                | 4.0.30319.42000         |
| WSManStackVersion         | 3.0                     |
| PSRemotingProtocolVersion | 2.3                     |
| SerializationVersion      | 1.1.0.1                 |

```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

### Issue Description

I have Powershell profile that prompts me 3 times. When I open a powershell file in VSCode or chnage the language to powershell, the VSCode promts me only once and the status bar on bottom-right cornet stucks at "Starting Powershell". Syntax colors still works but auto completion doesn't work. Probably extension cannot get powershell properties since it cannot start powershell modules.

below are the promts
- `$o365 = Read-Host "Do you Want to Connect Office 365 and EA Portal?"`
- `$skype = Read-Host "Do you Want to Connect Skype Administration?"`
- `$spoint = Read-Host "Do you Want to Connect Sharepoint Administration?"`

### Attached Logs

[Screenshot](https://mugurlu.tinytake.com/sf/MTMxMDUyNl80ODU5NDg4)

[Logs.zip](https://github.com/PowerShell/vscode-powershell/files/745668/Logs.zip)

**Comment by rkeithhill** [comment]
There is a setting for the PowerShell extension that allows you to enable/disable profile loading.  Set it to false and see if that gets you going.

**Comment by musaugurlu** [comment]
Yes. If I disable profile loading. It works.

Thank you for quick reply

**Comment by daviwil** [comment]
Another thing you can do is change your profile to skip those prompts if not in the ConsoleHost.  For example:

```powershell
if ($host.Name -ne "ConsoleHost") {
   $o365 = Read-Host "Do you Want to Connect Office 365 and EA Portal?"
   ...
}
```

**Comment by musaugurlu** [comment]
That's great. I'll add it to my profile. Thanks.
