### ISSUE TITLE
Script outline doesn't show correct indentation anymore

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/vscode-powershell#4783]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

It looks like the outline is not working properly anymore

using this sample code
```powershell
Class plop {
    $var1

    [string]SayWhat() {
        return "whaaat!"
    }
}

function woop {
    $var2

    $a = [plop]::New()
    $a.SayWhat()
}
```

![image](https://github.com/PowerShell/vscode-powershell/assets/6302961/47ff2d66-cf40-44b0-bb4d-a9c7af8bd66c)

Everything is shown on the same line. The method SayWhat() is not 'in' the Plop Class. The $a variable is not under the 'woop' function

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

Open vscode and sample script
press CTRL+ALT+B

indentation is not respected

**Comment by andyleejordan** [comment]
That is correct, I have a work-in-progress fix for it here https://github.com/PowerShell/PowerShellEditorServices/pull/2084

**Comment by Stephanevg** [comment]
Hi @andyleejordan thank you so much for working on this bug! I see the status is now merged in main, does that mean that this fix is already present in the latest version of vscode? From which version ?

Because I just downloaded the latest version (see below) and the bug still exists there😿 

```
Version: 1.84.1 (system setup)
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:35:59.022Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22000
```

Or maybe I am just being to impatient.... 🙄 😊 ?
Thanks again!

**Comment by andyleejordan** [comment]
It's in the pre-release! Give that a try.

**Comment by andyleejordan** [comment]
I lied, there isn't a pre-release with that out yet.

**Comment by Stephanevg** [comment]
😭

**Comment by andyleejordan** [comment]
Working on it! A pre-release should be out today if all goes according to plan.

**Comment by andyleejordan** [comment]
@Stephanevg got a pre-release out for you last night!

**Comment by Stephanevg** [comment]
Hey @andyleejordan  thank you so much in beeing so quick to release these fixes!
(I was actually not a VSCode insider user). But just downloaded everything, and I actually still have the issue (Or am I not using the latest release? )
```
Version: 1.85.0-insider (user setup)
Commit: 345c8d0927402d41f42402411d856eeec4013e5e
Date: 2023-11-13T05:39:23.476Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22000
```
![image](https://github.com/PowerShell/vscode-powershell/assets/6302961/58f368fa-0c66-459d-844c-f5de940677a9)

**Comment by andyleejordan** [comment]
That is VS Code Insiders, which is not necessary. The extension has a "pre-release" channel in the marketplace 
![image](https://github.com/PowerShell/vscode-powershell/assets/2226434/654456cd-4470-4d6a-8b3b-4f057ab2a914)

Try that!

**Comment by Stephanevg** [comment]
Ok, in the preview version the bug is actually fixed! 🥳  Thanks so much @andyleejordan 👍 🦄   👍
