### ISSUE TITLE
References are doubled the same filepath with .git extension

### ISSUE THREAD

**Issue by silverqx** [PowerShell/vscode-powershell#4784]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

All references are doubled, they have __the same__ path but with the `.git` extension. The project must be a GIT project, must contain `.git/` folder.

### PowerShell Version

```console
λ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
λ code --version

1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

### Extension Version

```console
λ code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

Create the pwsh function that has more than 0 references and the file is inside a git repository.

### Visuals

![references_doubled](https://github.com/PowerShell/vscode-powershell/assets/86900/bcc0fa4d-2390-4cbd-b3de-0401f24ecfa4)

**Comment by andyleejordan** [comment]
Does this `.git` file exist on the file system?

**Comment by silverqx** [comment]
Of course that no why would I have all the files doubled with .git extension. 🙂

**Comment by andyleejordan** [comment]
Well, I can't repro it. Can you tell me what other extensions you have installed? Does it repro when you run an VS Code instance with _only_ the PowerShell Extension?

**Comment by silverqx** [comment]
I try it and let know, I need to find a little time for it but I do it, I have a lot of extensions installed and will have to disable them one by one to find out. GitHub actions or similar extension could cause this, will see.

**Comment by silverqx** [comment]
I can reproduce it on a clean vscode profile (I moved ~/.AppData/Roaming/code and ~/.vscode to .bak).

To reproduce it you must open the folder that is also a GIT repository, must contain `.git` folder.

**Comment by silverqx** [comment]
If it's not a git repository it works well.

**Comment by andyleejordan** [comment]
Sorry, do you mean you're opening the `.git` folder itself? I definitely tested this in a Git repository and am not seeing this behavior. Do you see this with references in files provided by other extensions (like can you repro this in a C# or a Python file)?

**Comment by andyleejordan** [comment]
Well, I _can_ repro it very specifically in your project https://github.com/silverqx/TinyORM/tree/main/tools/private

**Comment by andyleejordan** [comment]
Well, it would appear that in some instances VS Code hands us "Git" documents (like where `DocumentUri` starts with `git:/` similar to real files with `file:/`). I want to know _when and why_ it does this, because I've seen it before but sure do see it in your repo. At least the fix is to filter those out...working on it.

**Comment by silverqx** [comment]
> It would appear that in some instances VS Code hands us "Git" documents (like where `DocumentUri` starts with `git:/` similar to real files with `file:/`).

Hmm

> I want to know _when and why_ it does this, because I've never seen it before but sure do see it in your repo.

I absolutely don't know too and I'm also confused about why is this happening.

> At least the fix is to filter those out...working on it.

Great that is a good idea, I tried to find how to filter them out but I was not successful.

**Comment by silverqx** [comment]
I have also another problem with these references, it doesn't directly depend to this issue but I ask here and will not create another issue.

Is there any vscode setting how I can tell the PowerShell extension to exclude some folders?

Eg. look at this, it's from my `dotfiles`, the problem is that my dotfiles also contain the vscode profile in the git repo:

![references_1](https://github.com/PowerShell/vscode-powershell/assets/86900/d841d7eb-5718-4e13-b5bb-a0236f29c973)

There are 5 references in total, 2 in the `pms.ps1` script and 3 in the `pmu.ps1`, but the PowerShell extension of course counts references from all the `.ps1` files in the current project. What can I do about this?

**Comment by andyleejordan** [comment]
> I have also another problem with these references, it doesn't directly depend to this issue but I ask here and will not create another issue.
> 
> Is there any vscode setting how I can tell the PowerShell extension to exclude some folders?
> 
> Eg. look at this, it's from my `dotfiles`, the problem is that my dotfiles also contain the vscode profile in the git repo:
> 
> ![references_1](https://user-images.githubusercontent.com/86900/276223402-d841d7eb-5718-4e13-b5bb-a0236f29c973.png)
> 
> There are 5 references in total, 2 in the `pms.ps1` script and 3 in the `pmu.ps1`, but the PowerShell extension of course counts references from all the `.ps1` files in the current project. What can I do about this?

Hi, can you please open a separate issue for this. I _think_ we respect the default search ignore settings in VS Code but want to double-check that with my team, which will happen when we triage new and open issues. Thanks!

**Comment by silverqx** [comment]
Ok, thank you for fix this, how can I test it? Or when it will be released?

**Comment by silverqx** [comment]
Thx, for fixing this

**Comment by andyleejordan** [comment]
You're very welcome! I hope that's a complete fix, that is, that there isn't anything _else_ sending `git` files over to the server. But I didn't see when debugging! Still don't know exactly why VS Code is sending `didOpen` notifications for files that we (the users) definitely didn't open.

**Comment by silverqx** [comment]
From my experience is best to ask the author, if you know which code is responsible for that then look to git blame or GitHub history, find the author's name, create an issue, and ask why, an author will know it right away, maybe it's a bug.
