### ISSUE TITLE
Allow to exclude folders from processing

### ISSUE THREAD

**Issue by silverqx** [PowerShell/vscode-powershell#4787]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Is there any vscode setting how I can tell the PowerShell extension to exclude some folders?

Eg. look at this, it's from my `dotfiles`, the problem is that my dotfiles also contain the vscode profile in the git repo:

![references_1](https://github.com/PowerShell/vscode-powershell/assets/86900/d841d7eb-5718-4e13-b5bb-a0236f29c973)

There are 5 references in total, 2 in the `pms.ps1` script and 3 in the `pmu.ps1`, but the PowerShell extension of course counts references from all the `.ps1` files in the current project (what is the correct behavior). What can I do about this?

I tried to add the path to the `files.exclude` and it isn't accepted, I don't even know if the `files.exclude` would be a good solution for this.

I am lacking some vscode setting that allows excluding for this extension, eg. `powershell.exclude`.

### PowerShell Version

```console
λ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
λ code --version
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

### Extension Version

```console
λ code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

none

**Comment by silverqx** [comment]
@andyleejordan

**Comment by SydneyhSmith** [comment]
"search.exclude": {
        "vscodeglobpatternhere": true,
    },
    // or
    "powershell.analyzeOpenDocumentsOnly": true,

Thanks @silverqx this should be the setting

**Comment by andyleejordan** [comment]
Essentially the extension respects the built-in `search.exclude` setting:

```json
  // Configure glob patterns for excluding files and folders in fulltext searches and quick open. Inherits all glob patterns from the `files.exclude` setting.
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/*.code-search": true
  },
```

https://code.visualstudio.com/docs/getstarted/settings

**Comment by silverqx** [comment]
The `search.exclude` doesn't work for me, it doesn't affect these References.

Also I discovered that I already had these folders in the `search.exclude` and also in `files.exclude` but references still counts from these folders.
