### ISSUE TITLE
PowerShell extencion isn't working or incorrect setup

### ISSUE THREAD

**Issue by RodnyPHP** [PowerShell/vscode-powershell#4790]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

![image](https://github.com/PowerShell/vscode-powershell/assets/76241306/e407b56f-5a5f-4ac0-aeac-423be5944cb3)

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22621.2428                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22621.2428                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.83.1
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

Testing now the .js 
![image](https://github.com/PowerShell/vscode-powershell/assets/76241306/5e851f29-4b58-4625-a5f1-5ef02ae9ee0c)

### Visuals

![image](https://github.com/PowerShell/vscode-powershell/assets/76241306/caff5737-78c1-4b89-92e5-f67612da87b2)

**Comment by SydneyhSmith** [comment]
Thanks @RodnyPHP are you having any success with PowerShell commands?
