### ISSUE TITLE
Format Document

### ISSUE THREAD

**Issue by Air-Git** [PowerShell/vscode-powershell#4791]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Code does not format

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.2428
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2428
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

Open a Powershell script
View command palette, select Format document
Message is "There is no formatter for PowerShell files installed".
The extension is working otherwise. Code is auto-completed, new code is indented, code is colour-coded, errors are highlighed.

**Comment by SydneyhSmith** [comment]
Thanks @Air-Git could you include a screen shot of what your VSCode window looks like when this happens? Is the extension terminal running?

**Comment by Air-Git** [comment]
Extension seems fine apart from the formatting: 
![image](https://github.com/PowerShell/vscode-powershell/assets/31771283/998a705a-d7f7-4f65-bf83-c93ee70bdb7e)

**Comment by andyleejordan** [comment]
Can you set it with `Configure Default Formatter...`?

**Comment by a1ch3mist** [comment]
I have the same issue. Everything looks fine - I've tried setting global default formatter to powershell, as well as just powershell components, and nothing seems to be working.

All the rest of the extension seems to be working like auto-complete, etc.

Very frustrated.

**Comment by SydneyhSmith** [comment]
Can you share $host ?

**Comment by andyleejordan** [comment]
My bad on the bot, I adjusted the timing so it would add the stale label _after_ seven days and then close right after that...obviously breaks in the case of the stale label already having been added!

**Comment by Air-Git** [comment]
`Name             : ConsoleHost
Version          : 5.1.22621.2506
InstanceId       : 956860de-9345-4ffa-99d7-c98e6b5259e7
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-GB
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace`

**Comment by Air-Git** [comment]
It is a vanilla install of VS Code on W11. The extension seems to work, but not the formatting. There is no other formatter installed.

**Comment by Air-Git** [comment]
I tried Preview, but that was the same.

**Comment by andyleejordan** [comment]
> Name : ConsoleHost Version : 5.1.22621.2506 InstanceId : 956860de-9345-4ffa-99d7-c98e6b5259e7 UI : System.Management.Automation.Internal.Host.InternalHostUserInterface CurrentCulture : en-GB CurrentUICulture : en-GB PrivateData : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy DebuggerEnabled : True IsRunspacePushed : False Runspace : System.Management.Automation.Runspaces.LocalRunspace

This tells me you don't actually have the extension activated yet. Can you make sure the PowerShell Extension Terminal is up and running?

**Comment by Air-Git** [comment]
The terminal is running: 
![image](https://github.com/PowerShell/vscode-powershell/assets/31771283/239ebadb-d1c7-4f8c-ab8b-33db2052349f)
I ran the installation on a different Windows 10 laptop, installed the extension and it just works. I also tried two earlier versions. They don't work on this computer either.
I have the MS Security Baseline set up on this computer, and I think perhaps some aspect of the extension is blocked, although there is no notification. I can't think what else it might be.

**Comment by andyleejordan** [comment]
> I have the MS Security Baseline set up on this computer, and I think perhaps some aspect of the extension is blocked, although there is no notification. I can't think what else it might be.

That would make a lot of sense actually.

**Comment by LarryC42** [comment]
This is also blocked for me at work on Windows 10 & Windows Server 2016.  It does work for me on Windows 11 at home.  If there's any information on what might be blocked or how to troubleshoot it, it would be helpful.

**Comment by ianatgrafton** [comment]
I had this error and I found that the PS add-in was disabled because the current workspace was not trusted. I switched the workspace to trusted and the formatting worked again.

It still did the syntax highlighting and indentation as well as matching the code blocks, so wasn't obvious that it was disabled.

**Comment by Air-Git** [comment]
I just did a fresh install, installed the extension, opened and trusted a folder, opened a PowerShell script, ran "Format Document" and got exactly the same message.
I think it is something to do with Baseline Security settings, but I don't see a way to find out which setting.

**Comment by jalbiero** [comment]
In my case the formatter works Ok in a PC with Win10, but it shows the same error that others posted here ("There is no formatter for 'powershell' files installed") in a PC with Win11. The extension has the same default configuration on both PCs.

**Comment by eric-gitta-moore** [comment]
for me. just run this vscode command `PowerShell.RestartSession`
