### ISSUE TITLE
Powershell.exe cannot be found or is not accessible at path /usr/local/bin/powershell

### ISSUE THREAD

**Issue by AbhimanyuAryan** [PowerShell/vscode-powershell#480]
I have installed Powershell extension for macOS sierra but when ever I open VS code I get these strange errors. 
<img width="655" alt="screen shot 2017-02-03 at 5 54 33 am" src="https://cloud.githubusercontent.com/assets/8083613/22574577/cc174d22-e9d5-11e6-9ebc-733ad65eb396.png">
<img width="787" alt="screen shot 2017-02-03 at 5 54 24 am" src="https://cloud.githubusercontent.com/assets/8083613/22574582/d3564e30-e9d5-11e6-886f-e07dcb7ab86b.png">

**Comment by daviwil** [comment]
Have you installed PowerShell for macOS?  That's a prerequisite for using the extension.

https://github.com/PowerShell/PowerShell/releases

**Comment by daviwil** [comment]
Here are the installation instructions: 

https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#macos-1011

**Comment by jackfruh** [comment]
I have the same problem, but mine is looking for powershell alpha 9, which is old. I'm on beta 7 now.

`9/21/2017 1:43:07 PM [ERROR] - powershell.exe cannot be found or is not accessible at path /usr/local/microsoft/powershell/6.0.0-alpha.9/powershell`

Where is it getting the path above from - I can probably just update a configuration and fix this.

**Comment by daviwil** [comment]
@jackfruh Check your `powershell.powerShellExePath` setting, can you clear it out and restart VS Code?  I wonder if something I'm doing is causing a symbolic link path to be followed so that the version-specific PowerShell path is getting stored in that variable.

**Comment by jackfruh** [comment]
No, it was me being stupid - I looked at the extension, and then the instructions for the extension and there was a step to point to a specific version - I had that in my preferences.
removed it and it appears to be ok now.

Thanks!

**Comment by daviwil** [comment]
Hmmm, can you point me to that instruction?  I don't want other people to be tripped up by that too.

**Comment by jackfruh** [comment]
Hi, to be clear the error was mine. I think the install docs are ok. I must have followed these instructions back in the alpha 9 days,  there is a section that talks about specifying a specific version of Powershell.

![screenshot1](https://content.screencast.com/users/basementjack/folders/Snagit/media/2161e3b6-7c42-4db6-a4de-f6ece21a0d50/2017-09-21_16-19-17.png)

![screenshot2](https://content.screencast.com/users/basementjack/folders/Snagit/media/506fe4a7-3a26-49fb-b11e-c9b41b544f3c/2017-09-21_16-22-41.png)
