### ISSUE TITLE
PowerShell Extension terminal unusable when using Windows PowerShell with PSReadLine >= 2.2.5

### ISSUE THREAD

**Issue by sba923** [PowerShell/vscode-powershell#4804]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Using the latest PowerShell Extension v2023.9.5, that comes with `PSReadLine` 2.3.4, is not possible with Windows PowerShell:

![image](https://github.com/PowerShell/vscode-powershell/assets/12860484/3633daa3-805b-4ec4-856b-c9cc2aa387c8)

Reverting to `PSReadLine` 2.0.0, works, anything >= 2.2.5 yields the same behavior.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.9.5
TylerLeonhardt.vscode-inline-values-powershell@0.0.7
```

### Steps to Reproduce

Launch VScode, open any `.ps1` file, and switch the PowerShell session to "Windows PowerShell (x64)"

### Logs

[1698477220-9012415f-77ca-49e4-a3a8-c49c6146ab011698477191238.zip](https://github.com/PowerShell/vscode-powershell/files/13194761/1698477220-9012415f-77ca-49e4-a3a8-c49c6146ab011698477191238.zip)

**Comment by andyleejordan** [comment]
@daxian-dbw do we know of any issues affecting PSReadLine and Windows PowerShell compatibility?

**Comment by SydneyhSmith** [comment]
@StevenBucher98 are you aware of any issues with PSReadLine and Windows PowerShell?

**Comment by sba923** [comment]
Sorry, forgot to share _here_ that we determined with @jandedobbeleer that removing the "shell_integration": true" statement from my oh-my-posh profile makes the issue go away.

See https://twitter.com/SBarizien/status/1719646419416490051?t=8tUVSUirC7DB3X2oEan2pA&s=19 and https://github.com/PowerShell/vscode-powershell/issues/4731
