### ISSUE TITLE
No linting error on `Export-ModuleMember -Variable $variable`

### ISSUE THREAD

**Issue by Malix-off** [PowerShell/vscode-powershell#4806]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

No linting error on `Export-ModuleMember -Variable $variable`, while [it should](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/export-modulemember?view=powershell-7.3#-variable:~:text=Enter%20the%20variable%20names%2C%20without%20a%20dollar%20sign%20character%20(%24))

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.9.5
```

### Steps to Reproduce

```powershell
$variable = 0
Export-ModuleMember -Variable $variable
``` 

### Visuals

![No problems have been detected on the workspace.](https://github.com/PowerShell/vscode-powershell/assets/76160668/081cf178-e72e-4a90-afa9-7bab1b88a307)

**Comment by SydneyhSmith** [comment]
Thanks @Malix-off this would be a custom PSScriptAnlyzer rule, we wouldn't be able to support this generically because we don't know the naming pattern people would be passing in for variable names

**Comment by Malix-off** [comment]
@SydneyhSmith:
> Thanks @Malix-off this would be a custom PSScriptAnalyzer rule, we wouldn't be able to support this generically because we don't know the naming pattern people would be passing in for variable names 

So it's impossible to parse from your side?

**Comment by andyleejordan** [comment]
As Sydney mentioned, this would be need to be a new rule in [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer). The extension just hosts and runs PSScriptAnalyzer. Please open an issue there!
