### ISSUE TITLE
No linting error on wrong array types

### ISSUE THREAD

**Issue by Malix-off** [PowerShell/vscode-powershell#4807]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

No linting error on wrong array types

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.9.5
```

### Steps to Reproduce

```powershell
[string[]]$stringArray = @(
	1
	2
)

$stringArray += 2
```

### Visuals

![No problems have been detected on the workspace.](https://github.com/PowerShell/vscode-powershell/assets/76160668/7ed31014-0b85-4cde-a976-2f3536078d43)

**Comment by SydneyhSmith** [comment]
Thanks @Malix-off this is actually correct as to how PowerShell works...if you want a custom rule about this check out PSScriptAnalyzer

**Comment by Malix-off** [comment]
@SydneyhSmith:
> Thanks @Malix-off this is actually correct as to how PowerShell works...if you want a custom rule about this check out PSScriptAnalyzer 

Can you explain?
2 is converted from an int type to a string type in the process?

**Comment by andyleejordan** [comment]
@Malix-off that is correct, try it out in PowerShell:

```pwsh
@andyjordane318 ~
> [string[]]$myArray = @(1, 2)
@andyjordane318 ~
> $myArray | %{ $_.GetType() }

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String                                   System.Object
True     True     String                                   System.Object

@andyjordane318 ~
```
