### ISSUE TITLE
Cannot use latest Az module in integrated PowerShell in VSCode

### ISSUE THREAD

**Issue by hendersonandrade** [PowerShell/vscode-powershell#4808]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Using Az module in latest version 10.4.1, I am unable to use any cmdlets in VS Code PowerShell integrated console. The output error is:

Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.PowerShell.Clients.ResourceManager,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
At line:1 char:1
+ connect-azaccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-AzAccount], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

![image](https://github.com/PowerShell/vscode-powershell/assets/32583573/167a90cb-e6b2-4456-9b50-88775d94f69e)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.3570
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3570
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.9.5
```

### Steps to Reproduce

Execute Connect-AzAccount with latest module Az version in PowerShell integrated console

**Comment by SydneyhSmith** [comment]
@hendersonandrade thanks for opening this issue, it looks like an assembly load context issue with the Az module, are you able to use PowerShell 7?

**Comment by hendersonandrade** [comment]
> @hendersonandrade thanks for opening this issue, it looks like an assembly load context issue with the Az module, are you able to use PowerShell 7?

Whit any version of PowerShell (Windows PowerShell or PowerShell Core) this error occurs when using integrated terminal with VS Code.
If I try to use Az module cmdlets in PowerShell outside VS Code, I get it without problem.

I noticed that this error only occurs in the latest versions of the Az module. If I rollback to about 6 or 7 previous versions of the Az module, I am able to execute cmdlets like Connect-AzAccount without assembly load error.
Unfortunately, this workaround doesn't work in my case as I need to use Az module cmdlets that only exist in newer versions.

**Comment by andyleejordan** [comment]
The Az module needs to isolate their dependencies and they do not do this consistently. My best suggestion is to just use a separate integrated terminal in VS Code (like, not the named "Extension Terminal").

**Comment by hendersonandrade** [comment]
> The Az module needs to isolate their dependencies and they do not do this consistently. My best suggestion is to just use a separate integrated terminal in VS Code (like, not the named "Extension Terminal").

Hi @andyleejordan 

Ok. Got it, I will open an issue with Az module developers also. Thank you!

**Comment by andyleejordan** [comment]
Thanks for doing that @hendersonandrade!

**Comment by bandlor** [comment]
Please note that this issue still exists. I just confirmed today on two independent Windows 10 machines with the latest VS Code that Connect-AzAccount called from the command prompt with the PowerShell extension active will throw the error mentioned above. Using the non-extension PowerShell terminal works and is usable as a workaround.

**Comment by SchottGun** [comment]
> Please note that this issue still exists. I just confirmed today on two independent Windows 10 machines with the latest VS Code that Connect-AzAccount called from the command prompt with the PowerShell extension active will throw the error mentioned above. Using the non-extension PowerShell terminal works and is usable as a workaround.

I am also still having this issue. I have to uninstall the powershell extension in order to use the AZ modules within the terminal

**Comment by Ily83** [comment]
Was the issue fixed?

**Comment by JustinGrote** [comment]
@SchottGun FYI you can just open a separate terminal, no need to uninstall the extension, just don't use the "PowerShell Extension" window.

The major problem is not the extension in and of itself, but the intellisense/scriptanalyzer ends up loading the modules in the "wrong" order. The latest extension fixes a serilog conflict, so as long as the extensions are loaded in the "right" order, it should be fine.

**Comment by kudorgyozo** [comment]
What if I want to run/debug a powershell script inside vscode that uses azure powershell?

**Comment by JustinGrote** [comment]
I would recommend having a profile script or part of your testing load the module you want immediately, or at least one with the higher version of azure.identity. Using a debug profile with temporary console enabled is also an option.
