### ISSUE TITLE
"editor.formatOnPaste": true does not format

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#481]
Copy/Paste into a `ps1` file, but does not format on paste. Press `alt+shift+f` and it formats.

```powershell
function x {
$a=1
}
```
`"editor.formatOnPaste": true`

![image](https://cloud.githubusercontent.com/assets/67258/22576177/24c3a18a-e988-11e6-88bc-486b4c96a4df.png)

![image](https://cloud.githubusercontent.com/assets/67258/22576257/77b1a342-e988-11e6-984f-cb68b4e7b3d1.png)

![image](https://cloud.githubusercontent.com/assets/67258/22576272/895b2140-e988-11e6-9c84-de9228c02027.png)

**Comment by GHRoss** [comment]
I also have this problem, for what it's worth.
