### ISSUE TITLE
Opening the home folder on macOS generates prompt to allow access to iCloud Drive, Reminders etc.

### ISSUE THREAD

**Issue by craftzneko** [PowerShell/vscode-powershell#4814]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

isolated a prompt that vs code requests access to iCloud data drive and reminders, why is It trying to access my reminders?

<img width="257" alt="Screenshot 2023-10-25 at 23 03 11" src="https://github.com/PowerShell/vscode-powershell/assets/662108/ebc69f99-ae1f-4ac2-afc0-a8f6a598e539">
<img width="257" alt="Screenshot 2023-10-31 at 23 51 31" src="https://github.com/PowerShell/vscode-powershell/assets/662108/8d2fffa8-5b1f-4f16-86f7-3dc4f9f2e428">

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Darwin 23.0.0 Darwin Kernel Version 23.0.0: Fri…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z (3 wks ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

### Extension Version

```console
v2023.8.0
```

### Steps to Reproduce

run powershell extension added to vs code, powershelgl installed via home-brew

**Comment by SydneyhSmith** [comment]
This may be related to #4821 , does this reproduce without the PowerShell extension?

**Comment by SydneyhSmith** [comment]
@craftzneko are you in a workspace?

**Comment by craftzneko** [comment]
@SydneyhSmith I was not in a workspace, hopefully above resolves.

**Comment by andyleejordan** [comment]
This should be resolved in the next pre-release. The bug was that if no workspace folder was given, we added the initial working directory (often the home directory, as that was the final fallback but also what many users set the `cwd` setting to) as the "first" workspace. That's obviously wrong given that it would trigger enumeration of all files under that folder. Instead we just let the list of workspace folders be empty, so if you haven't opened a workspace, no files will be enumerated (for symbol analysis).

**Comment by andyleejordan** [comment]
Re-opening and asking if you can verify for us that it's fixed in the upcoming pre-release (which I will try to get out tomorrow).

**Comment by craftzneko** [comment]
@andyleejordan happy to try, is the pre release out

**Comment by andyleejordan** [comment]
It's going out right now!
