### ISSUE TITLE
Citrix remote SDK stop working in VS code

### ISSUE THREAD

**Issue by torck82** [PowerShell/vscode-powershell#4815]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Citrix CVAD remote SDK stopped working in VS code. It works fine in ise and posh.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.2428
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2428
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

install citrix remote sdk. You will need an api key or a citrix daas local account.

get-xdauthentication - then signin

### Logs

PS E:\TOOLS\win-vmdeploy2> Get-XDAuthentication -ErrorAction Stop -ProfileName "Rundeck" -Verbose
VERBOSE: __AllParameterSets
VERBOSE: Get-XDAuthentication: Enter
VERBOSE: invoking Get-XDAuthenticationEx:
VERBOSE: __AllParameterSets
VERBOSE: Get-XDAuthenticationEx: Enter
VERBOSE: Get-XDAuthenticationEx: Using config environment: com
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: transactionId: 567583f8-081b-475e-afa7-98e15358d70d
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: ERROR: System.TypeInitializationException: The type initializer for 'Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient' threw an
exception. ---> System.MissingMethodException: Method not found: 'Void System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.set_SerializerSettings(Newtonsoft.Json.JsonSerializerSettings)'.
at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..cctor()
--- End of inner exception stack trace ---
at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, ConnectionSettings connectionSettings, RequestSettings settings, HttpMessageHandler handler, Boolean
disposeHandler)
at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, HttpMessageHandler handler, Boolean disposeHandler)
at Citrix.Sdk.Proxy.Cmdlets.GetXDAuthenticationExCmdlet.d__53.MoveNext() in
C:\tc\work\16815f2b41abb80\Cloud\PoshSdkProxySnapIn\Components\Snapin\Cmdlets\GetXDAuthenticationEx.cs:line 686
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: transactionId: 03ed2421-cdce-4bb4-a621-84afb2528f40
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: ERROR: System.TypeInitializationException: The type initializer for 'Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient' threw an
exception. ---> System.MissingMethodException: Method not found: 'Void System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.set_SerializerSettings(Newtonsoft.Json.JsonSerializerSettings)'.
at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..cctor()
--- End of inner exception stack trace ---
at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, ConnectionSettings connectionSettings, RequestSettings settings, HttpMessageHandler handler, Boolean
disposeHandler)
at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, HttpMessageHandler handler, Boolean disposeHandler)
at Citrix.Sdk.Proxy.Cmdlets.GetXDAuthenticationExCmdlet.d__53.MoveNext() in
C:\tc\work\16815f2b41abb80\Cloud\PoshSdkProxySnapIn\Components\Snapin\Cmdlets\GetXDAuthenticationEx.cs:line 686
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: transactionId: 7f5578aa-86fc-4467-b4c2-f21ff8743d42
VERBOSE: Get-XDAuthenticationEx: GetBearerToken: ERROR: System.TypeInitializationException: The type initializer for 'Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient' threw an
exception. ---> System.MissingMethodException: Method not found: 'Void System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.set_SerializerSettings(Newtonsoft.Json.JsonSerializerSettings)'.
at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..cctor()
--- End of inner exception stack trace ---
at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, ConnectionSettings connectionSettings, RequestSettings settings, HttpMessageHandler handler, Boolean
disposeHandler)
at Citrix.CloudServices.ServiceRuntime.ApiClient.ServiceClient..ctor(String serviceUri, HttpMessageHandler handler, Boolean disposeHandler)
at Citrix.Sdk.Proxy.Cmdlets.GetXDAuthenticationExCmdlet.d__53.MoveNext() in
C:\tc\work\16815f2b41abb80\Cloud\PoshSdkProxySnapIn\Components\Snapin\Cmdlets\GetXDAuthenticationEx.cs:line 686
VERBOSE: Get-XDAuthenticationEx: Exit
VERBOSE: Get-XDAuthentication: Exception: AuthenticationFailed
VERBOSE: Get-XDAuthentication: Exit
Get-XDAuthentication : AuthenticationFailed

**Comment by andyleejordan** [comment]
The Citrix module probably requires a different version of Newtonsoft.Json than is used by the extension. Can you try this with PowerShell Core instead of Windows PowerShell?

**Comment by torck82** [comment]
I downgraded the extension and it worked again.On Nov 2, 2023, at 4:01 PM, Andy Jordan ***@***.***> wrote:﻿
The Citrix module probably requires a different version of Newtonsoft.Json than is used by the extension. Can you try this with PowerShell Core instead of Windows PowerShell?

**Comment by torck82** [comment]
Also core does not work since the SDKs only supports version 5.1.On Nov 2, 2023, at 6:55 PM, Khanh Thai ***@***.***> wrote:﻿I downgraded the extension and it worked again.On Nov 2, 2023, at 4:01 PM, Andy Jordan ***@***.***> wrote:﻿
The Citrix module probably requires a different version of Newtonsoft.Json than is used by the extension. Can you try this with PowerShell Core instead of Windows PowerShell?

**Comment by SydneyhSmith** [comment]
@torck82 the workaround in this case would be to use a regular PowerShell 5.1 terminal within VSCode, rather than the extension terminal which is unable to support this SDK unfortunately, you could also open an issue on the SDK asking them to support PS 7 with their dependencies properly isolated...thanks!

**Comment by torck82** [comment]
Thanks, i just used the downgraded extension which still works in vscode.On Nov 8, 2023, at 2:44 PM, Sydney Smith ***@***.***> wrote:﻿
@torck82 the workaround in this case would be to use a regular PowerShell 5.1 terminal within VSCode, rather than the extension terminal which is unable to support this SDK unfortunately, you could also open an issue on the SDK asking them to support PS 7 with their dependencies properly isolated...thanks!
