### ISSUE TITLE
When the built-in `$null` was watched its value was incorrect

### ISSUE THREAD

**Issue by thegraffix** [PowerShell/vscode-powershell#4816]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

The debugging WATCH pane shows `$null: ""`

![image](https://github.com/PowerShell/vscode-powershell/assets/57874058/0e5c0cc0-8e45-410d-b231-44c152d3eb16)

<BR></BR>
  - The way `$null` is represented makes it difficult to distinguish between an empty string value `$MyStringVar = ""` vs an uninitialzed variable `$VarThatDoesNotExist`.
  - I'm not certain if this is VSCode or the PowerShell extension

### PowerShell Version

```console
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0, 7.2.0, 7.3.9}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
PS C:\> code --version
1.84.0
d037ac076cee195194f93ce6fe2bdfe2969cc82d
x64
```

### Extension Version

```console
PS C:\> code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

Add `$null` to the debugging WATCH list.

**Comment by SydneyhSmith** [comment]
Thanks @thegraffix for the bug report
