### ISSUE TITLE
Run PowerShell code in a terminal window with F8 key, instead of PowerShell Output window

### ISSUE THREAD

**Issue by AndrewRichardson2** [PowerShell/vscode-powershell#482]
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.9.0
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

```
PSVersion                      5.1.14393.693                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.693                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1      
```

### Issue Description

It would be fantastic if the PowerShell extension could be configured to run code in the terminal window with F8, rather than the "PowerShell Output" window.  It's really handy to be able to interact with a real live terminal when debugging a script, and being able to manually create variables that can be used by the code snippets you run.  This basically describes how the PowerShell ISE works.

Thanks!

**Comment by Plork** [comment]
try this in your keyboard shortcuts

// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "f8",
        "command": "workbench.action.terminal.runSelectedText",
        "when": "editorTextFocus && editorLangId == 'powershell'"
    }
]

**Comment by daviwil** [comment]
This is coming out in 0.10.0 in an hour or less.

**Comment by AndrewRichardson2** [comment]
That's awesome David!  Thanks!

**Comment by daviwil** [comment]
Update is out, give it a shot and let me know what you think!

**Comment by AndrewRichardson2** [comment]
Already have, it does exactly what I was hoping it would do.  I don't know if you guys already had this feature on the roadmap, but regardless thanks for getting it implemented!

**Comment by Plork** [comment]
Awesome update. Does everything i hope so far. No more switching back to
ISE. Only thing i miss is go to defenition in modules. But that's in the
works. 😀

Op 15 mrt. 2017 1:27 a.m. schreef "AndrewRichardson2" <
notifications@github.com>:
