### ISSUE TITLE
Powershell extension is consuming high memory

### ISSUE THREAD

**Issue by handrade-xom** [PowerShell/vscode-powershell#4821]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Install the extension and open VS Code, this will consume between 2GB and 3GB of RAM memory

### PowerShell Version

```console
Name                           Value                                                                                                                                                                             
----                           -----                                                                                                                                                                             
PSVersion                      5.1.19041.3570                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                           
BuildVersion                   10.0.19041.3570                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                               
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.84.1
2b35e1e6d88f1ce073683991d1eff5284a32690f
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

Install the extension and open VS Code, this will consume between 2GB and 3GB of RAM memory

**Comment by SydneyhSmith** [comment]
Thanks @handrade-xom have you also opened a workspace? Or an untitled workspace? How many files are in your workspace?

**Comment by hendersonandrade** [comment]
> Thanks @handrade-xom have you also opened a workspace? Or an untitled workspace? How many files are in your workspace?

hi @SydneyhSmith , I solved the issue here. It was necessary to change some of the extension's settings:

1. the first one was the PowerShell Cwd:

![image](https://github.com/PowerShell/vscode-powershell/assets/32583573/36787c8a-2dba-47ad-8814-f9e7b99ceb79)

2. the second change was check the Analyze Open Documents Only option:

![image](https://github.com/PowerShell/vscode-powershell/assets/32583573/e0f2c27a-b26a-4c5b-9e4c-5b43329904dd)
