### ISSUE TITLE
Cannot attach debugger to PS 7.4.0 processes

### ISSUE THREAD

**Issue by nightroman** [PowerShell/vscode-powershell#4843]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [x] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Cannot attach debugger to an interactively selected PS 7.4.0 processes.
This operation takes long time, then results in this error

![image](https://github.com/PowerShell/vscode-powershell/assets/927533/546171f3-f963-4f95-9757-b3bd77c03cc7)

### PowerShell Version

```console
PS C:\ROM\SET\VSCode\debug-psf> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.84.2
1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.8.0
I have also tried the latest pre-release, same issue.
```

### Steps to Reproduce

- Select launch profile "PowerShell attach" (below)
- Hit F5
- Select one of PS 7.4.0 choices

Launch profile:

```json
{
  "launch": {
    "version": "0.2.0",
    "configurations": [
      {
        "type": "PowerShell",
        "request": "attach",
        "name": "PowerShell attach",
        "processId": "${command:PickPSHostProcess}",
        "runspaceId": 1
      }
    ]
  }
}
```

**Comment by nightroman** [comment]
Bump...

**Comment by SydneyhSmith** [comment]
Thanks for the issue @nightroman we will need to do some more investigation into this

**Comment by andyleejordan** [comment]
Are you perhaps using the Windows Store installed version of PowerShell? I can never seem to attach to that installation, but can attach to 7.4 installed in pretty any other manner.

**Comment by nightroman** [comment]
I use the `PowerShell-7.4.0-win-x64.zip` from Releases -- https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0

**Comment by nightroman** [comment]
Here is the latest status, changed with new versions, still not working but differently

![image](https://github.com/PowerShell/vscode-powershell/assets/927533/4350eb28-a450-4622-b5fc-309cacf77c3d)


```
VSCode version:
1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
x64

ms-vscode.powershell version:
ms-vscode.powershell@2024.0.0

$PSVersionTable; $Host

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.0.0
InstanceId       : 8b608c97-927c-4d67-abc2-488fec552269
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by andyleejordan** [comment]
Thanks for the update, that's very helpful and has led me to find a bug (or two).

**Comment by andyleejordan** [comment]
So I think VS Code got stricter about type matching in variable substitutions, and these were mismatched. The original design allowed the PID to be an int or a string (which was just a special case for "current") but that led to a lot of unnecessary complication.

**Comment by nightroman** [comment]
When can we try the fix?

**Comment by JustinGrote** [comment]
@nightroman every commit has a build, here is the one for the PR:
https://github.com/PowerShell/vscode-powershell/actions/runs/7549834396/artifacts/1173960040

Extract the VSIX and use "install with VSIX" in vscode and then reload your vscode.

**Comment by nightroman** [comment]
Thank you. Same result so far, maybe the fix is not in this VSIX yet
![image](https://github.com/PowerShell/vscode-powershell/assets/927533/abc22a01-04d6-4893-a36d-97b2db7d0e1d)

**Comment by JustinGrote** [comment]
Can confirm I reproduced on the VSIX after choosing host process 80488.

@andyleejordan surprised type checking didn't catch this but I think this needs to be Promise<number> instead of Promise<string>
https://github.com/PowerShell/vscode-powershell/blob/d367094238902da9251a9de8296bbb454d7f833a/src/features/DebugSession.ts#L620

**Comment by andyleejordan** [comment]
Yup, it is fixed in the PR: https://github.com/PowerShell/vscode-powershell/pull/4888/files#r1462216399 which build did you guys grab?

**Comment by JustinGrote** [comment]
I thought I grabbed the PR build so I probably screwed up, let me double check

**Comment by andyleejordan** [comment]
Well you did grab the right artifact...but when I build locally I go from being able to repro to not.

**Comment by andyleejordan** [comment]
![image](https://github.com/PowerShell/vscode-powershell/assets/2226434/b6b6f732-79f7-4c3f-ac56-a092cb4bb6a3)

Now with the changes made, the input to `"processId"` in the JSON _should_ be an int so it does throw a squiggly warning about it being `"${command:PickPSHostProcess}"`. This way of doing it continues to work, but I set it up so just not setting `"processId"` at all for an attach configuration will run `PickPSHostProcess`. So you can delete the whole line.

**Comment by nightroman** [comment]
Removing the line with `processId` seems to be doing the trick, it's a very good news and progress, thank you.
Looking forward to the official update. Any ETA?

NB I believe this attached debugger flow was not well documented. But it's formally a breaking change. Please mention this in release notes. For your consideration.

**Comment by JustinGrote** [comment]
@nightroman the goal is to not break existing configs, we are working on it in the linked PR and will note back here if we find it.
