### ISSUE TITLE
Command decoration indicates success (blue dot) if the command failed (exit code > 0)

### ISSUE THREAD

**Issue by insaneinvader** [PowerShell/vscode-powershell#4854]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

It appears that the PowerShell extension confuses VSCode terminal decorations.

Left - using VSCode integrated PowerShell terminal - a red dot appears to indicate that the command failed.
Right - using PowerShell Extension terminal - a blue dot appears to indicate that the failed command was successful.
![img](https://github.com/PowerShell/vscode-powershell/assets/87144792/825f9ddf-06c4-4cca-899c-3350f9b51518)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name             : Visual Studio Code Host
Version          : 2023.8.0
InstanceId       : 8e54ba22-67da-47b2-b060-3887d7a8ce58
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : pl-PL
CurrentUICulture : en-GB
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.84.2
1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

Execute `throw "foo"`

**Comment by andyleejordan** [comment]
@Tyriar hm, any change recently to the escape codes used by shell integration? I'll do a diff here soon and update what's embedded in PSES. I wonder if this is probably us having an extra `catch` instead though.

**Comment by Tyriar** [comment]
The only recent change I can think of is the introduction of a nonce to verify the command name. This is optional and should not affect the exit code though

**Comment by insaneinvader** [comment]
Hope this helps:
v2023.1.0 - blue dot regardless of exit code - bad
v2022.12.1 - red|blue dot decoration works - OK
v2022.11.0 - no decorations - no feature, no bug

**Comment by andyleejordan** [comment]
@insaneinvader that helps a lot actually, thank you! Looking at this now.

**Comment by andyleejordan** [comment]
Yup, figured it out. We broke it when we added `Set-StrictMode` above where we save the exit code. Fixing!
