### ISSUE TITLE
Disconnect icon missing in VS Code 1.9.0 when attached to PowerShell host process

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#486]
### System Details

- Operating system name and version: Windows 10 AU
- VS Code version: 1.9.0
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`: 5.1.14393.693

### Issue Description

VS Code 1.9.0 doesn't seem to be using the "disconnect" icon in the debug actions pane when I'm attached to a PowerShell host process.  In 1.8.1 I saw this:

![image](https://cloud.githubusercontent.com/assets/5177512/22631656/973fb9cc-ebce-11e6-9bc0-b30d78b5e6df.png)

But in 1.9.0 I see this when I'm attached:
![image](https://cloud.githubusercontent.com/assets/5177512/22631665/a63ab422-ebce-11e6-81ba-e387fc1492dd.png)

**Comment by daviwil** [comment]
Weird...  Maybe they changed it?  I'll look into it.

**Comment by rkeithhill** [comment]
Fixed in vscode.

**Comment by daviwil** [comment]
Nice!  Thanks for following up on that.  I noticed it yesterday also but didn't have time to file it.
