### ISSUE TITLE
PowerShell Extension Terminal does not work with GH Copilot quick fix "twinkles"

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/vscode-powershell#4864]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

The GitHub Copilot extension terminal integration does not seem to have the quick fix button when an error occurs on the terminal. 

### PowerShell Version

```console
PS /Users/stevenbucher/Documents/Testing> $PSVersionTable; $Host

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Darwin 23.1.0 Darwin Kernel Version 23…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2023.8.0
InstanceId       : ef4a1084-d50a-47b3-8359-d898d3a6d070
UI               : System.Management.Automation.Internal.Host.Internal
                   HostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspac
                   e
```

### Visual Studio Code Version

```console
1.84.2                              
1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
arm64
```

### Extension Version

```console
ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

Have any error in the Terminal of VSCode while using the PowerShell Extension terminal.

### Visuals

Expected experience in PowerShell Extension terminal: 
<img width="1120" alt="image" src="https://github.com/PowerShell/vscode-powershell/assets/20605456/7e10f02c-bd1b-477f-906f-74cbb1242b48">

What it actually looks like:
<img width="1154" alt="image" src="https://github.com/PowerShell/vscode-powershell/assets/20605456/fc3c7022-9cd8-46cc-b9c8-83155ba739f5">

**Comment by JustinGrote** [comment]
This is likely something in how the Shell Integration Github script works that doesn't read or otherwise the PowerShell extension host doesn't provide over a normal pwsh shell.

My guess would be is that it isn't capturing the exit code, as the exit code error also does not show up if you do a simple throw or other error.

**Comment by JustinGrote** [comment]
Pretty sure this is a dupe of #4584
