### ISSUE TITLE
Command PowerShell.RunSelection not found

### ISSUE THREAD

**Issue by DerfOh** [PowerShell/vscode-powershell#488]
### System Details

- Operating system name and version: Windows 7
- VS Code version: 1.9.0
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

Name                           Value
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am experiencing a problem with running PowerShell scripts within vscode after updating to 1.90

### Attached Logs

No log directory is being generated within $HOME\.vscode\extensions\ms-vscode.PowerShell-0.9.0

**Comment by daviwil** [comment]
Do you ever get any error messages from within VS Code other than the one about RunSelection not being found?  The extension would write out some manner of log file if it had tried to start.

**Comment by DerfOh** [comment]
Nope VS Code starts up without any other error messages. The log file does not get written despite.

``` "powershell.developer.editorServicesLogLevel": "Verbose" ```

I also disabled all other extensions except PowerShell and also attempted specifying the path to powershell.exe to no avail. 

Another member of my team (who is experiencing the same issue) seems to have gotten it working normally by downgrading VS Code to 1.8 and turning off the auto update function.

**Comment by daviwil** [comment]
Oh interesting, so somehow VS Code 1.9 caused the issue?  You are able to use PS extension 0.9.0 normally with VS Code 1.8?

**Comment by emmdeeess** [comment]
I am using VS Code 1.8 with PS Extension 0.9.0 successfully. Upgrading to 1.9 breaks all PS functionality, besides the "Command 'PowerShell.RunSelection' not found" error when trying to use f8 to run snippets, all Intellisense, etc does not work.

**Comment by daviwil** [comment]
That's really strange.  I just tried VSC 1.9 with PS extension 0.9 on a Windows 7 machine with PS v3, started up just fine.  I'm not sure why the extension wouldn't even try to start.  Do you see this status bar item show up when you open a PowerShell file for the first time:

![image](https://cloud.githubusercontent.com/assets/79405/22663430/6c59ea64-ec61-11e6-88cc-88bde6c4f9ef.png)

**Comment by DerfOh** [comment]
@daviwil That appears to be the case for both of us.

**Comment by daviwil** [comment]
@emmdeeess which version of Windows are you using?

**Comment by DerfOh** [comment]
It says PowerShell for the file type when opening a ps1 file but it doesn't display "Starting Powershell..." or any other indication of the extension being loaded.

**Comment by daviwil** [comment]
Can you try removing and re-installing the PowerShell extension in VSC 1.9?  Maybe it's not being activated due to an issue caused by upgrading VS Code.

**Comment by emmdeeess** [comment]
Windows 7 here. Tried all variations of installing / uninstalling extension, could not get it to load in 1.9.

Tried fresh install, deleted .vscode folder in home folder and Code folder in AppData. Fresh install of 1.9 and fresh install of 0.9.0, no dice.

**Comment by DerfOh** [comment]
Same here, reinstall of plugin as well as editor did not resolve the issue, there is still no indicator for powershell starting either.

**Comment by daviwil** [comment]
Just filed an issue on the VS Code repo to see if they know of any other things we can try.

**Comment by DerfOh** [comment]
Looks like some key endpoints were changed in 1.9 that were not accounted for in our firewall exception list. Closing as this issue has been resolved for us, thanks for your time @daviwil.

**Comment by daviwil** [comment]
Very happy to hear it's been fixed for you guys!
