### ISSUE TITLE
cannot be loaded because running scripts is disabled 

### ISSUE THREAD

**Issue by darkoe3** [PowerShell/vscode-powershell#4881]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I am trying to run my Django server in my VS code but receives error message as "cannot be loaded because running scripts is disabled "

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.3803                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.3803                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.85.1
x64
```

### Extension Version

```console
ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

na

### Visuals

![django server erro](https://github.com/PowerShell/vscode-powershell/assets/25689543/313169c5-de9f-4f20-be70-d9d9f99bf029)

### Logs

na

**Comment by andyleejordan** [comment]
You'll need to enable running scripts on your system in order to run the script you're trying to run. See more about PowerShell execution policies here: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies
