### ISSUE TITLE
Powershell Extension Terminal produces warning error when it is closed

### ISSUE THREAD

**Issue by alanlivio** [PowerShell/vscode-powershell#4884]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I am experiencing an error "Connection to PowerShell Editor Services (the Extension
Terminal) was closed" when I opened the integrated terminal. I think it shouldn't happen, and the the service should be attached to an integrated terminal.

### PowerShell Version

```console
> $PSVersionTab1e; $Host

Name             : ConsoleHost
Version          : 7.4.0
InstanceId       : c3011b4a-f06e-46fa-890b-1f7782de3038
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
> code --version
1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
x64
```

### Extension Version

```console
> code --list-extensions --show-versions | select-String powershell

ms-vscode.powershell@2023.8.0
```

### Steps to Reproduce

- Open a ps1 file
- Close integrated opended

### Visuals

![Screenshot 2024-01-07 131848](https://github.com/PowerShell/vscode-powershell/assets/604808/58206446-b2cc-4eed-b5b1-3b86303718f2)

**Comment by SydneyhSmith** [comment]
Thanks, @alanlivio what happens when you press "Yes" on the prompt? Does the terminal start? Thanks!

**Comment by alanlivio** [comment]
Thanks @SydneyhSmith. Yes. The extension terminal hosting editor services start. 
For me, the language service should be running in background. Many other language services (e.g., python, C++) do not require a terminal and run in background.

**Comment by JustinGrote** [comment]
> Thanks @SydneyhSmith. Yes. The extension terminal hosting editor services start. For me, the language service should be running in background. Many other language services (e.g., python, C++) do not require a terminal and run in background.

The PowerShell Extension is very different than other language services, it requires a running PowerShell instance to provide a PowerShell ISE like experience and REPL as well as real time intellisense of available session values.

**Comment by andyleejordan** [comment]
There's one more option that does completely background the terminal: `"powershell.integratedConsole.startInBackground": true` but do heed the warning in its description!
