### ISSUE TITLE
The top part of the console doesn't move when scrolling (sometimes)

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#4889]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Since some time I've noticed that whenever I run code and then scroll back the top 3-4 rows stay on top of console window. if i scroll up and down it attaches/detaches. 

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22621.2506                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22621.2506                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.86.0-insider
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.1.0
```

### Steps to Reproduce

1. Run code
2. Scrollback

### Visuals

![ScrollBackWeird](https://github.com/PowerShell/vscode-powershell/assets/15063294/a5009d25-0797-4b33-b58a-f01d51b81736)

**Comment by SydneyhSmith** [comment]
Thanks @PrzemyslawKlys does this repro for you in the PowerShell terminal in VSCode, rather than the PowerShell extension terminal? Or does it repro if you turn off the shell integration setting `"terminal.integrated.shellIntegration.enabled":  false,`?

**Comment by PrzemyslawKlys** [comment]
Unfortunately it behaves the same even if i just run it in terminal without disabling integration. Seems like a global problem.

**Comment by andyleejordan** [comment]
That's helpful. Probably an xTerm.js issue. Can you please file with VS Code themselves?
