### ISSUE TITLE
Discussion: Deprecate RunCode Feature

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#4892]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

The `RunCode` feature was added 5 years ago by @TylerLeonhardt to support the related codelens feature at the time, but now all codelens is driven via PSES, so this command is never used anywhere in the codebase, and is exposed as a command with no keybinding that, when bound to a key, executes with no arguments and basically crashes because all the parameters it requires are undefined.

### Proposed Design

Either completely remove the library or stub out the command with a warning that it is no longer supported.

**Comment by andyleejordan** [comment]
Lol of course, let's delete it!
