### ISSUE TITLE
OSX The language service could not be started:  Error: spawn EACCES

### ISSUE THREAD

**Issue by 1Mystogan1** [PowerShell/vscode-powershell#491]
### System Details

- Operating system name and version: MasOS Sierra version 10.12.3 
- 
[vscode-powershell.log.zip](https://github.com/PowerShell/vscode-powershell/files/757705/vscode-powershell.log.zip)

Kernel Version:	Darwin 16.4.0
- VS Code version: 1.9.0
- PowerShell extension version: 0.9.0

Hi, 

Every time it try and and run the PowerShell or the debug i get the following Error

The language service could not be started: 
Error: spawn EACCES

Please Help

**Comment by daviwil** [comment]
Can you run `powershell` in the Terminal app, does it load correctly?

**Comment by 1Mystogan1** [comment]
Hi, 

Thanks you for the quick response! 

I have just this minuet got it working.
 
It was a combination of PowerShell not running in the terminal and .Net not working correctly. 

After installing Powershell from https://github.com/PowerShell/PowerShell/releases/ and installing .NET from https://www.microsoft.com/net/core#macos and following the install instructions resolved the issue. 

Visual Code will not run load and run PowerShell.

**Comment by daviwil** [comment]
Glad to hear you got it working!  I will improve the experience on OSX so that it is clear PowerShell needs to be installed for the extension to work.
