### ISSUE TITLE
Ctrl-space results in writing a character

### ISSUE THREAD

**Issue by cveld** [PowerShell/vscode-powershell#4939]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

After having run at least one command, ctrl-space starts resulting in writing the `a` character.

### PowerShell Version

```console
$PSVersionTable; $host

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.0.0
InstanceId       : d6120c4f-e131-4116-8466-5b2ead5f2d8c
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : nl-NL
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
code --version
1.87.2
863d2581ecda6849923a2118d93a088b0745d9d6
x64
```

### Extension Version

```console
code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2024.0.0
```

### Steps to Reproduce

1. Start an integrated shell.
2. Run a random command, e.g. `dir`
3. Start pressing ctrl-space. Every ctrl-space results in a `a`

### Visuals

![image](https://github.com/PowerShell/vscode-powershell/assets/6196260/32c1b0c1-e3cc-4cec-832f-dd37f57b2c3a)

**Comment by andyleejordan** [comment]
Hi, can you please file a bug upstream with VS Code? The value of your `$host` indicates this is happening in a regular VS Code integrated terminal running PowerShell, not (just) in the unique PowerShell Extension Terminal. Thanks!

**Comment by cveld** [comment]
@andyleejordan 
I have created a new ticket from with: https://github.com/PowerShell/vscode-powershell/issues/4940
Why is #4939 marked as resolved?

But I think I read your comment wrong. The issue does not happen with the regular PowerShell terminal. Only with the extension integrated terminal.
I will update the description text. I erroneously run the command from the wrong prompt.

**Comment by andyleejordan** [comment]
Thanks for confirming the terminal. In that case we'll get this triaged.

**Comment by cveld** [comment]
@andyleejordan any update? the issue is still present.

**Comment by cveld** [comment]
I found this line in Microsoft.PowerShell_profile.ps1:
```
if ($env:TERM_PROGRAM -eq "vscode") { . "$(code --locate-shell-integration-path pwsh)" }
```

It contains this exciting piece of code:
```powershell
function Send-Completions {
        $commandLine = ""
        $cursorIndex = 0
        # TODO: Since fuzzy matching exists, should completions be provided only for character after the
        #       last space and then filter on the client side? That would let you trigger ctrl+space
        #       anywhere on a word and have full completions available
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$commandLine, [ref]$cursorIndex)
        $completionPrefix = $commandLine

        # Get completions
        $result = "`e]633;Completions"
        if ($completionPrefix.Length -gt 0) {
                # Get and send completions
                $completions = TabExpansion2 -inputScript $completionPrefix -cursorColumn $cursorIndex
                if ($null -ne $completions.CompletionMatches) {
                        $result += ";$($completions.ReplacementIndex);$($completions.ReplacementLength);$($cursorIndex);"
                        $result += $completions.CompletionMatches | ConvertTo-Json -Compress
                }
        }
        $result += "`a"

        Write-Host -NoNewLine $result
}
```

Do you see the         `$result += "`a"`   ?

I am on to something.........

**Comment by andyleejordan** [comment]
So...we don't add anything to `Microsoft.PowerShell_profile.ps1`. That's certainly the name of the VS Code-specific profile which we'll load if present. The shell integration script is automatically loaded in the extension's host (and can be turned off). You're right, I think this is the culprit because the contents of your profile are causing the integration to get setup twice, which I think would result in what you're seeing. Perhaps you added that to the profile once-upon-a-time to manually enable shell integrations. Try removing it!

**Comment by cveld** [comment]
I ran vscode / PowerShell extension with a clean `Microsoft.PowerShell_profile.ps1` and `C:\Users\username\Documents\PowerShell\Microsoft.VSCode_profile.ps1` but the issue is still there.
I assume only the latter plays a role in the extension's shell.

**Comment by cveld** [comment]
@andyleejordan ctrl+space matches with 
```
{ "key": "ctrl+space",            "command": "workbench.action.terminal.sendSequence",
                                     "when": "terminalFocus && terminalShellIntegrationEnabled && !accessibilityModeEnabled && terminalShellType == 'pwsh'",
                                     "args": {"text":"\u001b[24~a"} },
```

Based on this log record from the shortcut key diagnostics:
```
INFO [KeybindingService]: \ From 5 keybinding entries, matched workbench.action.terminal.sendSequence, when: terminalFocus && terminalShellIntegrationEnabled && !accessibilityModeEnabled && terminalShellType == 'pwsh', source: built-in.
```


and this yields the `a` character. On Discord there is this helpful user `@ninmonkey` which shared his shortcut key diagnostics. At his/her side ctrl+space does not match any when clause ("no when clauses matches the context").

**Comment by cveld** [comment]
I added `"terminal.integrated.shellIntegration.enabled": false` and that works. Also disabling the key binding works:
```
 {
        "key": "ctrl+space",
        "command": "-workbench.action.terminal.sendSequence",
        "when": "terminalFocus && terminalShellIntegrationEnabled && !accessibilityModeEnabled && terminalShellType == 'pwsh'"
    }
```

But it sounds illogical that shell integration should be disabled?

**Comment by andyleejordan** [comment]
It sounds like there's a mismatch between Code's keybinding and the extension terminal's shell integration logic which is supposed to interpret it into something other than writing a character. I'm updating the extension terminal to use VS Code's shell integration script directly: https://github.com/PowerShell/PowerShellEditorServices/pull/2156

**Comment by andyleejordan** [comment]
@cveld can you test the latest pre-release, v2024.3.2-preview and let me know if it still happens?

**Comment by cveld** [comment]
I believe the issue went away with vscode 1.88.1 and PowerShell extension 2024.2 🥳
