### ISSUE TITLE
The use of "-" in snippet prefixes should be prohibited.

### ISSUE THREAD

**Issue by vadhbka** [PowerShell/vscode-powershell#4941]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

In the settings of Visual Studio Code, by setting editor.snippetSuggestions to "top", 
snippets are displayed at the top of the suggestions, making it easier to write code. 
However, unnecessary snippets may be prioritized and displayed, which can reduce productivity.

For example
```PowerShell
Get-ChildItem -
```
When I type this, the expected candidates should be these options.
![ex000000](https://github.com/PowerShell/vscode-powershell/assets/96918428/7daa7dc9-f2eb-4fe5-bccd-f65f76892d90)

However, actually, unnecessary snippets are prioritized for display.
![ac000000](https://github.com/PowerShell/vscode-powershell/assets/96918428/4756d80a-7af4-488d-877b-9c7a0226c569)

The reason for this is that when "-" is typed, snippets containing "-" in the prefix are prioritized for display.
I think this is a specification that reduces productivity.

### Proposed Design

I think that the use of "-" in snippet prefixes should be prohibited.

For example
"prefix": "do_until"
"prefix": "doUntil"

Many prefixes use "-" in snippets\PowerShell.json, 
but I don't think it's absolutely necessary to use "-".
I was able to address this issue by replacing all "-" in the prefix of "PowerShell.json" to "_".

Please consider this. Thank you.

**Comment by JustinGrote** [comment]
Thanks for the suggestion! Have you tried setting `editor.snippetSuggestions` to `bottom`? That'll get you the behavior you are looking for without us having to take a breaking change on all the snippets. You will also want to make sure that your PowerShell Extension terminal is running and unblocked otherwise it cannot generate parameter intellisense.

![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/da27757e-cc39-47c6-87f8-a9590de49753)

**Comment by vadhbka** [comment]
I already tried setting `editor.snippetSuggestions` to `bottom` once. 
However, when set to `bottom`, the snippets are displayed at the very bottom, which becomes inconvenient. 
I am looking for snippets in most situations. Therefore, I have it set to `top`. 
However, when I want to input command options, snippets are unnecessary. 
That's because what I'm looking for at that time are options. 
I believe that the most appropriate suggestion should be displayed according to the situation.

**Comment by JustinGrote** [comment]
For customizing snippet suggestions on context, that would have to be a vscode feature update to allow it to be customizable per symbol type, and not something we can do here.

The insert snippet command (default keybinding ctrl-alt-J) is there if you explicitly want to select and search a snippet list.

You can also use the Control Snippets (https://marketplace.visualstudio.com/items?itemName=svipas.control-snippets) extension to disable the powershell snippets and replace them with your own versions that don't have the dash, the snippets are transferrable from the snippets file: https://github.com/PowerShell/vscode-powershell/blob/main/snippets/PowerShell.json and then fix the snippet names yourself.

I know this isn't the answer you want to hear but introducing a breaking change to the snippets may have someone else coming here that they are annoyed they now have to type underscores which is an extra shift-key and slows them down and whatnot, so unless there is a really strong justification and support to change, it's probably not going to happen (sorry), but there are ways to get the environment you want.

**Comment by vadhbka** [comment]
> introducing a breaking change to the snippets may have someone else coming here that they are annoyed they now have to type underscores which is an extra shift-key and slows them down and whatnot, so unless there is a really strong justification and support to change.

It is not always necessary to use “_”. 
“prefix”: “doUntil” 
CamelCase like this is also acceptable. 
At least, I don’t think it’s appropriate to include a “-” that has no necessity, as it would conflict with the option's “-”.

**Comment by JustinGrote** [comment]
@andyleejordan would have the ultimate say on this.

**Comment by andyleejordan** [comment]
I agree with Justin. Hindsight being 20/20 I don't think we should have shipped snippets in the extension to begin with, but they're there now and removing/changing them drastically would be very irritable to our users. To be honest, the snippet/auto-complete/IntelliSense/Copilot experience of VS Code is, in my _personal_ opinion, incredibly overloaded and confusing (as you've found). I can never actually select the completion that I want, half the time I'm trying to take a Copilot suggestion I get an unshown IntelliSense completion instead, and I've disabled showing snippets at all! Justin's provided some great information and workarounds here to help control and configure this experience to the best of our ability as users, thanks so much!

**Comment by vadhbka** [comment]
I Understood. I will address this issue personally.


> I don’t think we should have shipped snippets in the extension to begin with

In my personal experience, the snippet itself was helpful to me because it is easy to understand the basic code.
