### ISSUE TITLE
Extension do not work

### ISSUE THREAD

**Issue by GregBuchie** [PowerShell/vscode-powershell#4947]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

If i use the Editor to write a script and I press run, it says it is activating the Extension and then nothing happens. Right at the beginning it asked me if I wanted to run code from an untrusted location on my laptop, to which i choose All the time. If i enter the code into the terminal the code will run. I have also uninstalled VS code and deleted:
"%USERPROFILE%/AppData/Local/Programs/Microsoft VS Code/uninst000.exe"
 "%USERPROFILE%/AppData/Roaming/Code"
"%USERPROFILE%/.vscode"

This is the error I get:

[Error - 10:01:11 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:01:11 AM] Connection to PowerShell Editor Services (the Extension Terminal) was closed. See below prompt to restart!
[Error - 10:01:11 AM] PowerShell Editor Services client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22621.2706                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22621.2706                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.87.2
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.0.0
```

### Steps to Reproduce

ping 8.8.8.8

### Visuals

![image](https://github.com/PowerShell/vscode-powershell/assets/141267162/febd25c1-2475-4d5f-8611-939ca48a0efd)

### Logs

2024-03-19 10:00:52.417 [info] Revived process, old id 94f37c9d341b134745595779c933fd0a-3 -> new id 1
2024-03-19 10:00:52.565 [info] Expanding terminal instance, old id 94f37c9d341b134745595779c933fd0a-2 -> new id undefined
2024-03-19 10:00:52.565 [warning] Couldn't get layout info, a terminal was probably disconnected Could not find pty on pty host

**Comment by GregBuchie** [comment]
Please close this issue. Turns out I had not installed Powershell 7 on my device.

**Comment by andyleejordan** [comment]
No worries, thanks for the follow up!
