### ISSUE TITLE
Azure Repos Virtual Filesystem: Intellisense stops working on branches other than "main". Only returns "no suggestions". Works fine on "main" branch.

### ISSUE THREAD

**Issue by GeldHades27355** [PowerShell/vscode-powershell#4951]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Intellisense only works as expected on "main" branch.

### PowerShell Version

```console
>> ----                           -----
>> PSVersion                      5.1.26085.1
>> PSEdition                      Desktop
>> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
>> BuildVersion                   10.0.26085.1
>> CLRVersion                     4.0.30319.42000
>> WSManStackVersion              3.0
>> PSRemotingProtocolVersion      2.3
>> SerializationVersion           1.1.0.1
>>
>> Name             : ConsoleHost
>> Version          : 5.1.26085.1
>> InstanceId       : 05c90193-ac0a-4077-a637-8f32e2058d98
>> UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
>> CurrentCulture   : de-DE
>> CurrentUICulture : en-US
>> PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
>> DebuggerEnabled  : True
>> IsRunspacePushed : False
>> Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.87.2
863d2581ecda6849923a2118d93a088b0745d9d6
arm64
```

### Extension Version

```console
ms-vscode.powershell@2024.3.1
```

### Steps to Reproduce

1. Ensure you are in a "main" branch, working off an Azure Repo. PowerShell extension is installed.
2. Write .ps1 code. Observe VS Code declares code correctly as PS.
3. Type `get-system`, then `<ctrl>+<space>` Observe intellisense suggestions as expected. They are identical to those of PowerShell ISE.
4. Switch to another branch of the repo - such as "DevTest". Begin editing the same .ps1 file.
5. Observe VS Code also correctly detects code as "PowerShell".
6. Repeat intellisense test. Type `get-system`, then `<ctrl>+<space>.` Observe "no suggestions".
7. This is 100% reproducible when switching between branches.

### Visuals

[intellisense_vscode.zip](https://github.com/PowerShell/vscode-powershell/files/14775755/intellisense_vscode.zip)

### Logs

[StartEditorServices-16948.zip](https://github.com/PowerShell/vscode-powershell/files/14775853/StartEditorServices-16948.zip)

**Comment by JustinGrote** [comment]
Not able to reproduce:
![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/4c946382-d0bf-48b2-a66d-a2efdff9ac54)

Can you provide an example repo? `Get-System` is not a built-in command, is that a custom command in your repo? I tried opening your Steps Recorder attachment and did not find any images there.

You may want to make sure your PowerShell extension terminal is unblocked with whatever you are doing, intellisense only works if the PowerShell Extension terminal is unblocked. For an example, type "sleep 60" into the powershell extension terminal and then observe that intellisense stops working until the sleep ends.

**Comment by GeldHades27355** [comment]
Odd. Here, try this screen capture vid:
[https://soloproworkplace-my.sharepoint.com/:v:/g/personal/dcote_solopro_work/EVqlSRbiV8lBujwxePqEYJ4BWvI-Wmp-a---boKUE4Wzag?e=E6T1gG](url)
Hopefully it shows better what's going on.

`get-system` is not a complete cmdlet. By default, there should be three cmdlets starting on `get-system*` on every Windows 11 box:
`Get-SystemDriver`
`Get-SystemLanguage (also exists on default Windows 10)`
`Get-SystemPreferredUILanguage`

intellisense will pop those up in any Powershell and also in VSCode - but ONLY when working off the "main" branch of an Azure DevOps repo. Autocomplete with "tab" also is consistent.

NOTE: intellisense comes back with "no suggestions".
When I `sleep 60`, it just stays on "loading..." until sleep time is up.
These are different behaviors, suggesting different mechanisms or root causes.

Anything else I can do to help?

**Comment by JustinGrote** [comment]
FYI you can now paste/drag/drop/etc. MP4s, etc. directly into github comments, no need to host them separately.

Sorry for the confusion about `Get-System<tab>`, I see what you are saying now.

If you check out the Azure Repo locally via git clone and have the Azure Repos extension disabled, does the same thing happen? My thought seeing "Azure Repos" in the bottom left means its owning the session and might be using its own virtual filesystem which might be messing with something.

**Comment by GeldHades27355** [comment]
BINGO. After cloning it locally, it seems intellisense works on both branches. Didn't have to disable Azure Repos, either.

But for remote Azure DevOps repo access, it still only works on the "main" branch.

What's next?

**Comment by JustinGrote** [comment]
@GeldHades27355 well, that's tricky, we'd have to know what conflict Azure Repos is creating, but my guess is that:
1. Azure Repos creates a virtual filesystem (which is a thing in vscode)
2. Intellisense is expecting a file to be provided for context, and is getting a virtual file url (which is different than an untitled document)
3. Our intellisense handler barfs on virtual file URLs because PS usually doesn't run in that context anyways.

I'd have to say this is gonna probably be an up-for-grabs, it's gonna take a lot of debugging to figure it out for the edge case when a suitable workaround of cloning locally exists, will defer to @andyleejordan on that.

**Comment by GeldHades27355** [comment]
ugh.... sounds like a nightmare. Look, let me try working with locally synced repos. I gotta admit, I'm still very new to VSCode (used PS ISE till now). First time I'm setting up some CI/CD on Azure DevOps and I just thought I'd give VSCode a shot.
(I tried full VS Pro too, but that's a BEAST).

So unless anyone objects, I'll go ahead and close this for now. I'll reopen if this causes issues again.
