### ISSUE TITLE
Debug string [DBG] not displayed in the terminal

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/vscode-powershell#4961]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

After installing vscode on a new server we noticed that the string `[DBG]` is no longer displayed on the terminal when debugging code.

Desired result when debugging:
![image](https://github.com/PowerShell/vscode-powershell/assets/10828570/3604d5ce-7361-47c7-8561-d43793768d9b)

Current result when debugging:
![image](https://github.com/PowerShell/vscode-powershell/assets/10828570/0bc001ea-b3df-4313-854c-088946050884)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.3.2
InstanceId       : 364a3969-9b4f-47b8-91a1-447cc6ec0cf8
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.87.2
863d2581ecda6849923a2118d93a088b0745d9d6
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.3.2
```

### Steps to Reproduce

Add a breakpoint and press `F5`

**Comment by andyleejordan** [comment]
Hm, the only thing we updated was the [Terminal Shell Integration](https://code.visualstudio.com/docs/terminal/shell-integration). Does this repro with it disabled via `terminal.integrated.shellIntegration.enabled` set to `false`?

**Comment by andyleejordan** [comment]
Hey, actually. You mentioned you have a new machine. Have you put:

```powershell
if (Test-Path variable:/PSDebugContext -ErrorAction SilentlyContinue) {
    $prompt += Write-Prompt "[DBG] "
  }
```

in the profile on that machine?

**Comment by andyleejordan** [comment]
Yeah, I just confirmed it still works so long as it's been setup. I think you may have just forgotten to add it. It sure _seems_ like something that could be the default, but as far I can tell, it is not.

**Comment by DarkLite1** [comment]
Sorry for the late reply, was a bit busy yesterday. Looking in [all profiles](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4) on the machine where it works, I can see any modification of the prompt. Also, I never modified this myself, so I even didn't think about looking there. 

Sreenshot as prove
![image](https://github.com/PowerShell/vscode-powershell/assets/10828570/e90c5da1-6087-4374-9834-2e138008f332)

**Comment by DarkLite1** [comment]
> Hm, the only thing we updated was the [Terminal Shell Integration](https://code.visualstudio.com/docs/terminal/shell-integration). Does this repro with it disabled via `terminal.integrated.shellIntegration.enabled` set to `false`?

On the affected machine this setting is false by default, as the string `terminal.integrated.shellIntegration.enabled` is not there:
![image](https://github.com/PowerShell/vscode-powershell/assets/10828570/ba0bb15e-3469-45f2-a084-630d8f74b768)

There is no [workspace settings file](https://code.visualstudio.com/docs/getstarted/settings#_workspace-settingsjson-location), as I can't find it in the folder `.vscode`

**Comment by DarkLite1** [comment]
> Hey, actually. You mentioned you have a new machine. Have you put:
> 
> ```powershell
> if (Test-Path variable:/PSDebugContext -ErrorAction SilentlyContinue) {
>     $prompt += Write-Prompt "[DBG] "
>   }
> ```
> 
> in the profile on that machine?

No, we didn't. Even if we try to add this to `code $PSHOME\Profile.ps1` which is `C:\Program Files\PowerShell\7\Profile.ps1`, it doesn't display the string `[DBG]`.

**Comment by DarkLite1** [comment]
I think the bot `github-actions` is a bit too aggressive

**Comment by DarkLite1** [comment]
@andyleejordan thanks for your help. Finally figured it out:

The `[DBG]` string is displayed when loading the `posh-git` module and starting the debugger. That wasn't clear to me, I always thought it was a part of the PowerShell extension. 

So for anyone else who would like to see if they are in debugger mode by simply looking at the prompt, add this to your profile:

```powershell
Import-Module posh-git
```

**Comment by andyleejordan** [comment]
> I think the bot `github-actions` is a bit too aggressive

Agreed 😓

**Comment by andyleejordan** [comment]
> @andyleejordan thanks for your help. Finally figured it out:
> 
> The `[DBG]` string is displayed when loading the `posh-git` module and starting the debugger. That wasn't clear to me, I always thought it was a part of the PowerShell extension.
> 
> So for anyone else who would like to see if they are in debugger mode by simply looking at the prompt, add this to your profile:
> 
> ```powershell
> Import-Module posh-git
> ```

Ahh that makes sense, glad you found it! I'll try to remember that next time it comes up.

**Comment by JustinGrote** [comment]
I just want to clarify that `[DBG]` does NOT come from posh-git, it's part of PowerShell native:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_debuggers?view=powershell-7.4#the-debugger-environment

The prompt is however customizable, for example:
![image](https://github.com/PowerShell/vscode-powershell/assets/15258962/0b3683dc-f9ff-4901-9e6f-0cb5adeb5912)

**Comment by JustinGrote** [comment]
> @JustinGrote hm...perhaps our host isn't doing it? I know it at least ensure `$PSDebugContext` is set appropriately when `prompt` is executed.

That's a good point it might be injected by The console host so we should take a look

**Comment by andyleejordan** [comment]
Heh, sure is: https://github.com/PowerShell/PowerShell/blob/1a52a93345d00eab3bd16cab31c1f3fafcb803b6/src/System.Management.Automation/engine/debugger/debugger.cs#L1836

**Comment by andyleejordan** [comment]
And it looks like it _only_ does it if the prompt was the default prompt, which explains why this probably hasn't come up before...at least, not in this way.

**Comment by DarkLite1** [comment]
> I just want to clarify that `[DBG]` does NOT come from posh-git, it's part of PowerShell native:

That wasn't clear to me. The console only started to display the `[DBG]` string after installing and loading the module `posh-git`.
