### ISSUE TITLE
Launching VSCode Also Opens cmd.exe Console Behind VSCode

### ISSUE THREAD

**Issue by TESTER-sec** [PowerShell/vscode-powershell#4964]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

No matter what system or version of Windows, when I launch the most recent version of VSCode it simultaneously launches a cmd.exe console window behind the VSCode GUI. This is reproducible every single time at-will on any system.

### PowerShell Version

```console
$PSVersionTable, $Host

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : ConsoleHost
Version          : 7.4.1
InstanceId       : c42ba18d-ed46-44b1-852e-2b5ce1168124
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
code --version
1.88.0
5c3e652f63e798a5ac2f31ffd0d863669328dc4c
x64
```

### Extension Version

```console
code --list-extensions --show-versions | Select-String powershell 

ms-vscode.powershell@2024.0.0
```

### Steps to Reproduce

1. WIN key + _R_
2. Enter "code"

### Visuals

<img width="235" alt="WindowsTerminal_im364Hs5jD" src="https://github.com/PowerShell/vscode-powershell/assets/97270395/08ec8ff3-2374-4fb8-9272-4e83498bc43b">

<img width="867" alt="msedge_gQyunn2idS" src="https://github.com/PowerShell/vscode-powershell/assets/97270395/4cbdfa0d-65f1-4696-ade5-a7cd096299a9">

**Comment by andyleejordan** [comment]
Ok, can you open a bug with VS Code? This is the PowerShell extension repository.
