### ISSUE TITLE
Intellisense not working for properties of the same type as the class

### ISSUE THREAD

**Issue by Yaekiou** [PowerShell/vscode-powershell#4967]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Intellisense not working for properties of the same type as the class

### PowerShell Version

```console
PS> $PSVersionTable; $Host

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.0.0
InstanceId       : 4136162e-f7f8-42c2-8765-d2d8b5c350b3
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : zh-HK
CurrentUICulture : zh-TW
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.88.0
```

### Extension Version

```console
v2024.0.0
```

### Steps to Reproduce

```PowerShell
class Command {
    [string[]]$Name
    [Command[]]$Subcommands
}

$abc = [Command]::new()

# No suggestions on <ctrl+space>
$abc.Subcommands.
```

### Visuals

![1](https://github.com/PowerShell/vscode-powershell/assets/87524932/529801f7-6ba1-4dfe-88d4-243fd5fe202c)
![2](https://github.com/PowerShell/vscode-powershell/assets/87524932/6f6ef7fe-ca14-4a73-9d3f-b6db8f6127bb)
![3](https://github.com/PowerShell/vscode-powershell/assets/87524932/ea6b501c-a3a0-42b5-babe-4a62d3b96992)

**Comment by andyleejordan** [comment]
Have you sourced your script into the extension terminal?

**Comment by Yaekiou** [comment]
Thank you. Intellisense is working after I sourced my script.
