### ISSUE TITLE
Format Document doesn't format correctly subexpressions like this

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#497]
*Before*

```powershell
$a=$(
    $x=@{
        
    }
)
```
*After*
```powershell
$a=$(
$x=@{
        
}
)
```

**Comment by daviwil** [comment]
I think @kapilmb just fixed this.  Kapil, can you verify it works with your latest changes?

**Comment by kapilmb** [comment]
Yes, this issue has been fixed!

_Before_
```powershell
$a=$(
    $x=@{
        
    }
)
```

_After_
```powershell
$a=$(
    $x=@{
        
    }
)
```

**Comment by daviwil** [comment]
Thanks for confirming!  Closing this for now, we can reopen it if other cases are still broken after the update.
