### ISSUE TITLE
Add ability to create submenu addons as you can in ISE.

### ISSUE THREAD

**Issue by adambirds** [PowerShell/vscode-powershell#498]
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.9.1
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

```
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

You should add the ability to create submenu addons as you can in ISE using your profile. 

Useful for shortcuts like below:

```
$psISE.CurrentPowerShellTab.AddOnsMenu.SubMenus.Add(
    "Connect to Exchange Online", {
        $LiveCred= Get-Credential
        $o365Session= New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/powershell/ -Credential $LiveCred -Authentication Basic -AllowRedirection
        Import-PSSession $o365Session
    },
    "Control+Alt+2"
)
```

**Comment by rkeithhill** [comment]
The PowerShell extension lets you write & register commands using PowerShell syntax.  At the moment, these commands appear only in the command palette menu IIRC.  For a deeper level of customization, Visual Studio Code has a very rich extensibility model.  See http://code.visualstudio.com/docs/extensions/overview
