### ISSUE TITLE
Feature request: "Go to Definition" works across all files in a workspace

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#499]
It'd be super-convenient for me if I could right-click on a function call click "Go to Definition" and it would find the module (if exists) that's in my current workspace, open up that file and then go to the function declaration.

**Comment by daviwil** [comment]
Yep, we have a lot of work to do on the symbol features in PowerShell Editor Services.  We need to start working on module-level analysis to enable this.

**Comment by tylerl0706** [comment]
This sounds close to #420. There should be some overlap but I'm not certain if/what unique changes there are to these two issues.

**Comment by rfoust** [comment]
Hi, any updates on this? I stumbled across this issue when figuring out if CodeLens was supposed to look for function names across multiple modules in the workspace.  I think this is related?

**Comment by TylerLeonhardt** [comment]
There's been some work to improve this. Probably not in the space you're hoping. I don't think I quite understand your comment - can you give an example, @rfoust?

**Comment by rfoust** [comment]
@TylerLeonhardt oops it's been a year, guess I'll reply now lol. :) I mean if I have multiple module folders open in the workspace and I'm looking at a function definition "function Get-Something" then right above it, it says "0 references" but there are really all kinds of references to it in other modules that I'm editing in my workspace, it just isn't seeing them.

![Screen Shot 2019-11-05 at 12 28 19 PM](https://user-images.githubusercontent.com/2991296/68230856-ed84f800-ffc7-11e9-93b6-6791444db1ba.png)

**Comment by fflaten** [comment]
What's the scope of this issue?
Initial post reads like definitions in same workspace. That should work in general now. **Multi-root workspaces (introduced later I believe) will still need some work**.

Be aware that the lookup is not module-aware, so conflicting function names might cause multiple returned definitions and wrong reference count.

Tracking definitions across `Import-Module` (and PSIC-imported modules outside workspace?) sounds like a separate issue.

**Comment by andschwa** [comment]
@fflaten actually I just made multi-root workspaces work in the last preview! I believe this is finished, besides what you point out with imported modules. So let's close this and leave #420 open I think.
