### ISSUE TITLE
On Linux when launching current file /usr/bin and /bin command are not reconized

### ISSUE THREAD

**Issue by VGib** [PowerShell/vscode-powershell#500]
### System Details

- Operating system name and version: archlinux (linux)
- VS Code version: 1.9.1-1
- PowerShell extension version: 0.9
- powershell git compiled today
- Output from `$PSVersionTable`: 
Name                           Value                                                                                                                                              
----                           -----                                                                                                                                              
PSVersion                      6.0.0-alpha                                                                                                                                        
PSEdition                      Core                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                            
BuildVersion                   3.0.0.0                                                                                                                                            
GitCommitId                    Could not find file '/usr/lib/powershell/ubuntu.16.04-x64/powershell.version'.                                                                     
CLRVersion                                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                
SerializationVersion           1.1.0.1   

### Issue Description
When I launch a powershell file with "PowerShell Launch (current file)", the command in /usr/bin and /bin can't be executed. all works fine otherwise.

If Iaunch an interactive session;, and execute my script in the terminal, I can debug and the /bin and /usr/bin command are executed.

**Comment by daviwil** [comment]
Hmmm, interesting.  Can you grab verbose logs and send them to me?

https://github.com/PowerShell/vscode-powershell#reporting-problems

Also, are you compiling the PowerShell extension from Git to get the latest changes just to try them out?  I'm planning to provide a way to install "Insiders" builds of the latest changes for those who want to try them.

**Comment by VGib** [comment]
I mistake it was powershell which was compuiled from git.
I send you the errors

**Comment by VGib** [comment]
Le vendredi 10 février 2017, 20:08:46 CET David Wilson a écrit :
> Hmmm, interesting.  Can you grab verbose logs and send them to me?
> 
> https://github.com/PowerShell/vscode-powershell#reporting-problems
> 
> Also, are you compiling the PowerShell extension from Git to get the latest
> changes just to try them out?  I'm planning to provide a way to install
> "Insiders" builds of the latest changes for those who want to try them.

Hello,

here are the files you asked for.

Regards,

Vincent Gibault

**Comment by daviwil** [comment]
Hey Vincent, the files didn't get attached to the GitHub issue.  Can you email them to me at *daviwil at microsoft.com*?  Thanks!

**Comment by VGib** [comment]
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/768740/logs.zip)
oups here they are

**Comment by VGib** [comment]
Fix in the last version, I close the bug

**Comment by daviwil** [comment]
Glad to hear that it was resolved!  Please let me know if you ever see the problem again.
