### ISSUE TITLE
VS Code PowerShell Extension Fails to Load: Continuous Spinning Indicator and Console Prompt Absence

### ISSUE THREAD

**Issue by ioxterminal** [PowerShell/vscode-powershell#5001]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

The order of the PS module paths on Windows seems to influence the loading behavior of the PowerShell extension in VS Code. If Windows PowerShell module paths are placed on top of the PowerShell 7 module paths, it results in a continuous spinning indicator and the PowerShell terminal never reaching a prompt.

### PowerShell Version

```console
PS C:\temp\Posh> $PSVersionTable; $Host

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.2.2
InstanceId       : c42fd1f7-2a51-4cdb-a300-22f718f1375a
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-GB
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
code --version
1.90.0
89de5a8d4d6205e5b11647eb6a74844ca23d2573
x64
```

### Extension Version

```console
code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2024.2.2
```

### Steps to Reproduce

Steps to Set Up PowerShell 7 in VSCode on Windows 11
**Install PowerShell 7:**
Download the installer for PowerShell 7 from the [official GitHub repository](https://github.com/PowerShell/PowerShell).
Run the installer and follow the on-screen instructions to complete the installation.

**Install Visual Studio Code (VSCode):**
Download VSCode from the [official Visual Studio Code website](https://code.visualstudio.com/).
Run the installer and follow the on-screen instructions to install VSCode.
Install the PowerShell Extension for VSCode:

**Open VSCode.**
Go to the Extensions view by clicking on the Extensions icon in the Activity Bar on the side of the window or pressing Ctrl+Shift+X.
In the Extensions view, search for "PowerShell".
Click on the PowerShell extension and then click Install.

**Change System Variable PSModulePath:**
Open the Start Menu and search for "Environment Variables".
Select "Edit the system environment variables".
In the System Properties window, click the Environment Variables button.
In the Environment Variables window, find and select the PSModulePath variable under System variables, then click Edit.
Ensure that the PSModulePath includes both the paths for PowerShell 7 and Windows PowerShell. It should look something like:
`**C:\Windows\System32\WindowsPowerShell\v1.0\Modules**;C:\Program Files\PowerShell\7\Modules;...`
Make sure the path for **Windows PowerShell** modules is placed on top to reproduce the issue.

**Open VSCode.**
Open or create a new PowerShell script file (.ps1).
Run the script by pressing F5 or by right-clicking the script file and selecting Run from the context menu.

You should see that the prompt does not appear and the continuous Spinning Indicator

### Visuals

<img width="1121" alt="2024-06-09 12_35_19-Settings" src="https://github.com/PowerShell/vscode-powershell/assets/31781969/217930b6-0127-4b4d-b462-ccd68e779a35">
<img width="1276" alt="2024-06-09 12_37_55-" src="https://github.com/PowerShell/vscode-powershell/assets/31781969/37f75eed-223f-4dc3-bed7-2b7d46b70759">
<img width="1117" alt="2024-06-09 12_42_44-C__onedrive_Desktop_temp_powershell ticket_2024-06-09 12_37_55- png - Greenshot " src="https://github.com/PowerShell/vscode-powershell/assets/31781969/04ff171e-bf18-4057-beaa-9f227e0585e7">

**Comment by JustinGrote** [comment]
Is there a particular reason you're adding in the WindowsPS psmodulespath? You should be using Windows compatibility for those. Have you also tried putting it at the bottom of the psmodulepath search order? My guess is you are loading in an odler module from WinPS that is clobbering a needed PS one.

**Comment by seanGSISG** [comment]
I am having the same issue

**Comment by erez-zone** [comment]
I had the same issue only uninstall vs code and installing older version (1.98.2) revived the PowerShell extension.

**Comment by wadea80434** [comment]
I had the same problem, followed the guidance from ioxterminal

Moving the V1.0\MODULES to the bottom resolved the issue

I'm running VS Code version (1.102.3) with extension version (2025.2.0)

<img width="896" height="297" alt="Image" src="https://github.com/user-attachments/assets/1d20777e-ff23-482a-a759-c05d587eb8e4" />
