### ISSUE TITLE
The PowerShell icon is not showing in the activity bar

### ISSUE THREAD

**Issue by rumson77** [PowerShell/vscode-powershell#5006]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I have installed the latest version of PowerShell and the PowerShell extension in vscode.  However, the extension for PowerShell does not show in the activity bar.  I'm trying to follow the book "PowerShell in a month of lunches" and this extension is asked for, but their example looks very different from mine.  I did look for the issue in the issues and troubleshooting, but did not find the answer I'm looking for.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : ConsoleHost
Version          : 7.4.2
InstanceId       : 7d3b5618-d082-4f44-a14d-0eb32f826ef6
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
PS C:\Users\richh> code --version
1.90.1
611f9bfce64f25108829dd295f54a6894e87339d
x64
PS C:\Users\richh>
```

### Extension Version

```console
PS C:\Users\richh> code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2024.2.2

PS C:\Users\richh>
```

### Steps to Reproduce

Opening VScode and the PowerShell extension does not show in the activity bar

### Visuals

![VScode](https://github.com/PowerShell/vscode-powershell/assets/99087467/043611a2-0afb-4e11-80d5-c38d13cfb98e)

**Comment by andyleejordan** [comment]
The Command Explorer visibility was set to default off a few months ago, as it's a feature that is a bit "sunsetted" (it exists, you can turn it on and use it, we're not planning to enhance it as we don't have much feedback indicating we should). Its visibility is on by default in ISE Mode, which is where it was originally added (as an ISE-like feature).

You can add it back (or remove it) with the setting `powershell.sideBar.CommandExplorerVisibility`.

**Comment by GaneshMSFT** [comment]
@rumson77, here is how you can enable that setting. I had the same issue as yours. So, I enabled this by following the instructions above. I am adding the following instructions to make it easier for you to follow along. 

**Open the settings.json file:** You can do this by clicking on the gear icon in the lower left corner, selecting "Settings," add the following line to your settings.

`"powershell.sideBar.CommandExplorerVisibility": true`

**Save and Restart:** Save the file and restart VS Code.


![Image](https://github.com/user-attachments/assets/df5b77c0-7858-43bc-945e-c2036200e545)

**Comment by iamkk-iam** [comment]
> [@rumson77](https://github.com/rumson77), here is how you can enable that setting. I had the same issue as yours. So, I enabled this by following the instructions above. I am adding the following instructions to make it easier for you to follow along.
> 
> **Open the settings.json file:** You can do this by clicking on the gear icon in the lower left corner, selecting "Settings," add the following line to your settings.
> 
> `"powershell.sideBar.CommandExplorerVisibility": true`
> 
> **Save and Restart:** Save the file and restart VS Code.
> 
> ![Image](https://github.com/user-attachments/assets/df5b77c0-7858-43bc-945e-c2036200e545)



This is worked for me. Appreciated your help.
