### ISSUE TITLE
Problema ao clonar um repositório

### ISSUE THREAD

**Issue by olegario-th** [PowerShell/vscode-powershell#5012]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Estou tentando clonar um repertório no VSCode, porém não aparece a opção git: clone.

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22621.3810                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22621.3810                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.90.2
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.2.2
```

### Steps to Reproduce

Logar no github através do VS
Apertar Ctrl + Shift + P
Escrever Git: clone

### Visuals

![image](https://github.com/PowerShell/vscode-powershell/assets/92459033/eb4bdf83-7b83-41ba-b0de-9539fd07c6b7)

**Comment by JustinGrote** [comment]
Thanks for your submission!

The clone button is vscode specific, and not related to the PowerShell extension, you will need to open your issue there:
https://github.com/microsoft/vscode

That said, have you tried:
1. Making sure your source control pane shows git is available?
2. Checking the git output log to make sure there are no errors there?
3. Checking the internet for similar issues like being in restricted mode?
https://github.com/microsoft/vscode/issues/169116

It seems to work fine to me so it must be something specific to your setup. Good luck fixing it! Closing this as not related to powershell vscode extension.
