### ISSUE TITLE
No output coming after giving command as "node mongotest.js" as command in powershell

### ISSUE THREAD

**Issue by Amalthomas-2002** [PowerShell/vscode-powershell#5018]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

The powershell of VScode is not giving the response for "node mongotest.js" input. There is a line console.log(....) which should give the response in powershell but nothing is coming.

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.4648                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.4648                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.91.1
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.2.2
```

### Steps to Reproduce

const {MongoClient} = require("mongodb");
// mongodb://localhost:27017
var mongo=require("mongodb").MongoClient;
var url= "mongodb://localhost:27017/";

MongoClient.connect(url,function(err,db) {
    if (err){
        throw err;
    }
    else{
        var mydb=db.db("studentdb");
        mydb.createCollection("students",function(err,res){
            if (err){
                throw err;
            }
            else{
            console.log("collection is creaated !");
            console.log(res);
            db.close();}
        })
        console.log("database created !");
        db.close();
    }
})

Output produced for this in power shell is:
PowerShell Extension v2024.2.2
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.

PS C:\Users\HP\Desktop\MyWebproject> node mongotest.js

### Visuals

![image](https://github.com/user-attachments/assets/210a30dc-4cc1-4b07-aed2-16678bccbd34)

**Comment by andyleejordan** [comment]
Without debugging your code for you my guess is that it's hung at createCollection and so has not entered its callback which has the console.log statements. If you think it's specifically the extension terminal, have you tried in other terminals?
