### ISSUE TITLE
PSExtension not retrieving all packages with Find-PackageProvider

### ISSUE THREAD

**Issue by markcagatandavis** [PowerShell/vscode-powershell#5020]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When performing the following, not all packages are available:

Find-PackageProvider -Name *

Bellow when executed from Windows Terminal
![image](https://github.com/user-attachments/assets/332f6997-f796-48f4-9e7f-cf7e8ca45550)

Bellow when executed from VSCode PowerShell Extension
![image](https://github.com/user-attachments/assets/b5de3924-dd9a-4b74-b89d-8778055e6b90)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.3880
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.3880
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name             : ConsoleHost
Version          : 5.1.22621.3880
InstanceId       : 405721b7-b9c0-4b24-a29c-afe9d3af86fa
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-AU
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.91.1
f1e16e1e6214d7c44d078b1f0607b2388f29d729
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.2.2
```

### Steps to Reproduce

Type the following in both console and vsextension 

`Find-Package -Name *`

**Comment by SydneyhSmith** [comment]
Inside your vscode window can you run $psversiontable? Thanks!
