### ISSUE TITLE
Powershell terminal rendering cuts off text or scrambles text

### ISSUE THREAD

**Issue by thadguidry** [PowerShell/vscode-powershell#5024]
Type: <b>Bug</b>

1. Open Terminal window in VSCode-Insiders and Powershell Extension v2024.3.2 and using Powershell 7.4.4
2. Paste some long command text
3. Execute the long command successfully
4. Tap up arrow to show previous long command and use left/right arrow keys to move along command.
5. The cursor is sometimes moved pass the command beginning and instead inside a few characters into the end of the prompt.
6. Other times the cursor might be sitting in the middle of the long command and the command is cutoff from either end.
7. I cannot reproduce this in the regular PowerShell Windows Terminal, but seems to exhibit this weird rendering issue only in VSCode Terminal.

![image](https://github.com/user-attachments/assets/d32dd4b9-af1e-4562-9bc9-382577de6312)

Extension version: 2024.3.2
VS Code version: Code - Insiders 1.93.0-insider (4693ac3d4dce852b747d08d4bc54db5e35afe268, 2024-08-09T06:29:39.564Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.93GB (52.64GB free)|
|Process Argv|--crash-reporter-id ec828980-5f99-4b3a-9589-b598d2900347|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
0ee40948:31013168
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nb_pri_only:31057983
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31105043
wkspc-onlycs-c:31111717
nativeloc2:31111756
wkspc-ranged-c:31111712
3ad50483:31111987
fcdif617:31111928

```

</details>

**Comment by tokKurumi** [comment]
Have the same problem with my laptop on Windows 11:
```
> code --list-extensions --show-versions | select-string powershell
> ms-vscode.powershell@2024.2.2
```
```
> code --version
> 1.92.1
> eaa41d57266683296de7d118f574d0c2652e1fc4
> x64
```
```
> $PSVersionTable
> Name                           Value
> ----                           -----
> PSVersion                      7.4.4
> PSEdition                      Core
> GitCommitId                    7.4.4
> OS                             Microsoft Windows 10.0.19045
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
```

**Comment by mark-vw** [comment]
Thanks for opening the issue on this. I've been experiencing the same issue for several months and it's quite frustrating to work with an unreliable terminal.

```
> code --version
1.92.1
eaa41d57266683296de7d118f574d0c2652e1fc4
x64
```

```
> $psVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by andyleejordan** [comment]
Hi, can you tell me if this reproduces when you have terminal shell integration disabled?

**Comment by thadguidry** [comment]
I cannot reproduce this any longer after the newest update.

```
Version: 1.93.0-insider (user setup)
Commit: 26a90463972295bcb960b7487a7c69afa06626eb
Date: 2024-08-19T10:25:17.637Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26120

PowerShell for Visual Studio Code:  v2024.3.2 (pre-release)
```

**Comment by tokKurumi** [comment]
By enabling shell integration my problem was solved. For some reason it was disabled by default.
For any body else have the same issue, make sure it is enabled. Here is [guideline](https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation) to enable it
