### ISSUE TITLE
Extension fails to activate when starting a script.

### ISSUE THREAD

**Issue by jason-collab** [PowerShell/vscode-powershell#5027]
Type: <b>Bug</b>

When starting a PowerShell script in VS Code, the Powershell extension hangs in "Activating extentions..." state. Reinstalling the extension did not resolve the issue.

Extension version: 2024.2.2
VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by andyleejordan** [comment]
We need a lot more repro info to help with this. Please follow our bug template when filing an issue. Thanks!
