### ISSUE TITLE
PNP.PowerShell scripts not working in VS Code with PowerShell extension

### ISSUE THREAD

**Issue by nirmala24** [PowerShell/vscode-powershell#5032]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I am having issues running PnP PowerShell scripts in VS Code with PowerShell extension. Using normal PowerShell (pwsh), all PnP commands work as expected. The issue is only occurring while debugging the .ps1 script files using the PowerShell extension in VS Code. 

Executing the script with the PowerShell extension Integrated console terminal are running as expected, but unable to debug the same .ps1 script with pnp powershell commands as none of the CMDlets are working.

I have read an issue about the PowerShell extension issue with VS Code(#3510), but I am having issues using debugging the scripts with PowerShell extension.

Details of my environment:

PnP.PowerShell-Module Version 2.9.0
PnP.PowerShell 7.4.5

**VSCode version**
1.92.2
fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
x64

**PowerShell extension for VS Code**
ms-vscode.?[7mpowershell?[0m@2024.2.2

This was working fine couple of days before

### PowerShell Version

```console
PS C:\> $PSVersionTable; $Host

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.2.2
InstanceId       : 971bdbc3-d8ee-4683-bc48-2e4994688114
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace


PS C:\>
```

### Visual Studio Code Version

```console
PS C:\> code --version
1.92.2
fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
x64
PS C:\>
```

### Extension Version

```console
PS C:\> code --list-extensions --show-versions | Select-String powershell

ms-vscode.?[7mpowershell?[0m@2024.2.2

PS C:\>
```

### Steps to Reproduce

Install PnP.PowerShell module
Install VS Code
Get the PowerShell extension for VS Code
Open a file and save it as .ps1 with the below pnp PowerShell commands.

Connect-PnPOnline -site "https://abc.sharepoint.com/sites/testsite1" -Interactive
$DL = Get-PnPList -Identity "Shared Documents"

Debug the saved .ps1 with the PowerShell extension integrated console as the selected terminal

### Visuals

![Github_PowerShellIssue](https://github.com/user-attachments/assets/e1c56cd4-3e41-48ee-9f8d-bfcaf3c95177)

![Screenshot 2024-08-23 173122](https://github.com/user-attachments/assets/d14302ab-d40d-4e66-a53a-2f66c32b814b)

**Comment by andyleejordan** [comment]
Please see the pinned issue https://github.com/PowerShell/vscode-powershell/issues/3510

**Comment by JustinGrote** [comment]
@nirmala24 I know you noted you read it, but to expand, because of the way PnP.PowerShell doesn't isolate all of its dependencies, it causes conflicts with the pieces that make vscode work. This has to be fixed by PnP.PowerSehell.

**Comment by nirmala24** [comment]
> Please see the pinned issue #3510

Thank you for the reply.

I have gone through #3510 before raising the issue and the suggested workaround doesn't work for me. My issue is, I couldn't debug the .ps1 script using powershell extension for VS code.

**Comment by nirmala24** [comment]
> This issue has been labeled as resolved, please verify the provided fix (or other reason).

I do not believe this was resolved. This is still an outstanding issue for me. This started happening in the past couple of days.

**Comment by nirmala24** [comment]
> @nirmala24 I know you noted you read it, but to expand, because of the way PnP.PowerShell doesn't isolate all of its dependencies, it causes conflicts with the pieces that make vscode work. This has to be fixed by PnP.PowerSehell.

@JustinGrote - Any idea on how or when this will be fixed. Or any workarounds other than the ones mentioned in #3510. Or any other alternate editors other than VS code for PnP.PowerShell

**Comment by JustinGrote** [comment]
@nirmala24 I opened a relevant issue in the repo: https://github.com/pnp/powershell/issues/4192, you can comment and follow the status there.

**Comment by jackpoz** [comment]
Cannot confirm the issue, debugging works fine:
![image](https://github.com/user-attachments/assets/38250721-ab70-4475-9700-a4da264bd862)

Using ms-vscode.powershell@2024.2.2 , PnP PowerShell 2.9.9, VS Code 1.92.2, PSVersion 7.4.5 .
