### ISSUE TITLE
Does not recognize PowerShell because of errors.

### ISSUE THREAD

**Issue by michaelleepow90** [PowerShell/vscode-powershell#5037]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Apparently, PowerShell is broken in the Visual Code App, it keeps telling me to relaunch PowerShell to fix the error. Happens every time I start Visual Code.

### PowerShell Version

```console
7.5
```

### Visual Studio Code Version

```console
1.93
```

### Extension Version

```console
12.216.114
```

### Steps to Reproduce

1. I open up Visual code
2. The PowerShell extension starts up.
3. It then tells me to restart the extension to fix errors.
4. This also happens with Terminal Tools extension.
5. If I try to save the fix, it will not save it.

**Comment by SydneyhSmith** [comment]
Thanks @michaelleepow90  we are having trouble getting a repro could you add screenshots and/or logs?
