### ISSUE TITLE
Never ending loop to trying to activate extention when trying to run PS script

### ISSUE THREAD

**Issue by jason-collab** [PowerShell/vscode-powershell#5045]
Type: <b>Bug</b>

Even with simple scripts, the PowerShell extension does't appear to ever fullly activate...just loops. VSC and all extensions are up to date. It even occurs for a simple script like as follows:

Connect-MicrosoftTeams
Get-CsOnlineUser -Identity <UPN>

Extension version: 2024.2.2
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (4.00GB free)|
|Process Argv|--crash-reporter-id 0f61217d-3470-41e0-8842-8e86025f25a9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
pme_test_c:31118331
ei213698:31121563
iacca2:31138163

```

</details>

**Comment by JustinGrote** [comment]
Thanks for the submission! Could you s[ubmit us some logs so maybe we can see something](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#logs)? Have you also tried disabling your profile in the settings?

**Comment by SydneyhSmith** [comment]
@jason-collab do you have a powershell profile? Can you clarify how did you start the extension? Do you have trouble with any other extensions? Thanks!

**Comment by JustinGrote** [comment]
@jason-collab I'm not seeing anything in the logs, looks pretty normal, not sure what it would be hanging on. Have you tried starting a new `vscode` fresh profile with no settings or extensions specified, only install the PS extension, and see if it reoccurs there (don't log in to sync settings either into that profile)

https://code.visualstudio.com/docs/editor/profiles

**Comment by JustinGrote** [comment]
Does the same occur on another computer? I unfortunately cannot reproduce this in any combination and without a solid reproduction we have no way of knowing how to fix it.

**Comment by JustinGrote** [comment]
Certainly these kind of intermittent or "immediate death" issues can be caused by antivirus and other products seeing pwsh.exe as a threat and halting the execution.
