### ISSUE TITLE
Powershell profile not being loaded in terminal

### ISSUE THREAD

**Issue by flamableassassin** [PowerShell/vscode-powershell#5049]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

To get around https://github.com/PowerShell/PSResourceGet/issues/1494 I've been modifying `$env:PSModulePath` to include a folder where my modules are stored _done using `Save-Module`_. Due to the extension not loading my Powershell profile the env isn't being modified and is breaking access to modules. 

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core 
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.2.2
InstanceId       : 15edc23a-1b05-4c1c-bf82-ffc23928363a
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-GB
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.94.0-insider
527e41ff551bb1001d2f224c2dec2e2ea3b66832
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.2.2
```

### Steps to Reproduce

NaN

**Comment by o-l-a-v** [comment]
You might have to use a different path for profile with vscode. See:

* <https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/creating-profiles?view=powershell-7.4>
* <https://til.secretgeek.net/vs_code/vscode_powershell_profile.html>

**Comment by flamableassassin** [comment]
Well I missed the fact that my vscode profile was named `Microsoft.VSCode_profile.ps1.ps1`
