### ISSUE TITLE
very  strange   ,isn't vscode    built-in   Powershell7 ?   And it  already support   auto-complete ,  history suggestion  

### ISSUE THREAD

**Issue by Super1Windcloud** [PowerShell/vscode-powershell#5050]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

very  strange   ,isn't vscode    built-in   Powershell7 ?   And it  already support   auto-complete ,  history suggestion

**Comment by JustinGrote** [comment]
Thanks for your submission! Could you please provide more details as to what you are asking?

If you are asking why PS7 doesn't ship in the vscode extension, it's because you can easily install it separately and they have different lifecycles.
