### ISSUE TITLE
`vscode-powershell` messes up `Microsoft.Graph.Authentication`

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/vscode-powershell#5053]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

---

* Windows 11 23H2 22631.4169 x64
* PowerShell v7.4.5
* VSCode v1.93.1 x64
* vscode-powershell v2024.2.2
* Microsoft.Graph.Authentication v2.23.0

Related issue:

* <https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2284>
  * And comment: <https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2284#issuecomment-2346632980>

---

I can't get the following to work from a `vscode-powershell` terminal, but it works in a barebone PowerShell v7.4.5 terminal, and the same PowerShell version through Windows Terminal.

```pwsh
Connect-MgGraph -ContextScope 'Process' -NoWelcome -UseDeviceCode -Scopes (
    'PrivilegedAccess.Read.AzureADGroup',
    'PrivilegedEligibilitySchedule.Read.AzureADGroup'
)
```

In VSCode this throws:

```
Connect-MgGraph: Method not found: 'System.Threading.Tasks.Task`1<Azure.Identity.AuthenticationRecord> Azure.Identity.DeviceCodeCredential.AuthenticateAsync(Azure.Core.TokenRequestContext, System.Threading.CancellationToken)'.
```

### PowerShell Version

```console
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS > $host

Name             : Visual Studio Code Host
Version          : 2024.2.2
InstanceId       : bfa40465-f731-49c5-8c6c-950b1358e6ae
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-SE
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

PS >
```

### Visual Studio Code Version

```console
PS > code --version

1.93.1
38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
x64

PS >
```

### Extension Version

```console
PS > code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2024.2.2

PS >
```

### Steps to Reproduce

```powershell
# Run in VSCode with the VSCode-PowerShell extension in the "PowerShell Extension" terminal = Crash
Microsoft.Graph.Authentication\Connect-MgGraph -ContextScope 'Process' -NoWelcome -UseDeviceCode -Scopes (
    'PrivilegedAccess.Read.AzureADGroup',
    'PrivilegedEligibilitySchedule.Read.AzureADGroup'
)
```

**Comment by JustinGrote** [comment]
Thanks for your submission!
I'm going to mark as dupe of https://github.com/PowerShell/vscode-powershell/issues/4727 as the method error is a dead giveaway you are having an assembly conflict.

**Comment by o-l-a-v** [comment]
@JustinGrote 

I quickly read through linked thread. Seems Az has issues with vscode-powershell due to inproper dependency isolation. Microsoft.Graph too then I guess.

It's easy to close this vscode-powershell issue and blame it on other parts of the stack.

What I then want to know is: What's the progress on having Microsoft modules play nice with the Microsoft official way of authoring PowerShell scripts these days? Do you have any insight on that?

The experience of using VSCode with a regular pwsh terminal is not as nice. Many times running multiple lines in a script file with F8 fails, because all info did not get sent to the terminal before it tries to execute.

**Comment by JustinGrote** [comment]
@o-l-a-v as a community member I cannot answer that question, but the Az, Microsoft.Graph, and Vscode team members are part of separate organizations within Microsoft.

I want to be clear I closed it as a duplicate of the other issue, but the other issue is open and is definitely a known thing we'd like to address if possible, because it frustrates me just as much as it does you too :)

CC @andyleejordan @SteveL-MSFT

**Comment by o-l-a-v** [comment]
I deleted the comment @JustinGrote replied to as I started doing deeper research into where I should send this feedback. For context, here is what I wrote:

---

I quickly read through linked thread. Seems Az has issues with vscode-powershell due to inproper dependency isolation. Microsoft.Graph too then I guess.

It's easy to close this vscode-powershell issue and blame it on other parts of the stack. And it might not be up to vscode-powershell to solve, I get that.

What I then want to know is: What's the progress on having Microsoft modules play nice with the Microsoft official way of authoring PowerShell scripts these days? Do you have any insight on that?

This should probably be a combined effort between vscode-powershell, Az and Microsoft.Graph authors/maintainers.

The experience of using VSCode with a regular pwsh terminal is not as nice. Many times running multiple lines in a script file with F8 fails, because all info did not get sent to the terminal before it tries to execute.
