### ISSUE TITLE
Debugger hangs on break points in PowerShell code

### ISSUE THREAD

**Issue by weinand** [PowerShell/vscode-powershell#506]
_From @wmc777 on February 14, 2017 18:40_

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|azuretoolsforvscode|bradygaster|1.2.1|
|PowerShell|ms-vscode|0.9.0|
|azurerm-vscode-tools|msazurermtools|0.3.4|

---

Steps to Reproduce:

1. Set a break point 
2. Press F10 to step the break point
3. The debugger hangs and Code must be restarted

1. Set a break point on a different line than the one that caused the debugger to hang.
2. Press F10 to step the break point
3. The debugger hangs and Code must be restarted

The same PowerShell code runs fine if there is not break points set.

_Copied from original issue: Microsoft/vscode#20608_

**Comment by rkeithhill** [comment]
@wmc777 Do you have any watch expressions defined in the Debug view?  If so, that is a known issue that is being worked on for the next release.

**Comment by wmc777** [comment]
No, I did not have watch expressions defined. I just had a couple of break points set.

**Comment by daviwil** [comment]
@wmc777 can you capture verbose logs while debugging and send them to us?

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

**Comment by wmc777** [comment]
I captured the logs and will send it to you via email. Here is an example of the hang>
![ms-vscode powershell_hangs](https://cloud.githubusercontent.com/assets/6521260/23074966/c141c0d8-f508-11e6-9a2b-020e1e4522a7.gif)

**Comment by wmc777** [comment]
@daviwil I sent the the captured logs to in an email. Did you have  a chance to review them?

**Comment by daviwil** [comment]
Looking at the GIF, there's a watch expression defined there so this could be the same issue.  I'll investigate briefly before we ship 0.10.0.

**Comment by yobyot** [comment]
Debugger still hangs in 1.10.2 for me with _no_ watch expressions explicitly set. 95% of my ps1s use either the AWSPowerShell cmdlets (Windows) or AWSPowerShell.NetCore cmdlets (macOS). I wonder if these are part of the issue.

It's a shame vscode can't debug PowerShell worth a spit.

**Comment by daviwil** [comment]
@yobyot Please send logs so I can look into your issue:

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

**Comment by yobyot** [comment]
Hi, David.

Log files attached. Thanks for taking a look.

[vscode-log.zip](https://github.com/PowerShell/vscode-powershell/files/839446/vscode-log.zip)

**Comment by daviwil** [comment]
Can either of you verify whether this issue still occurs for you?  In theory it should be fixed in 0.10.1 of the PowerShell extension.  Note that this update uses the PowerShell Integrated Console for debugging instead of the old Debug Console.  Thanks!

**Comment by yobyot** [comment]
Looks good so far. I was able to repeatedly debug a function, something I couldn't do previously.

Thanks so much for the incredibly fast turnaround.

You guys on the PowerShell team are _awesome_.

**Comment by daviwil** [comment]
Great, glad to hear it!  If you see the issue again, just leave a comment on this issue and I'll reopen it.
