### ISSUE TITLE
Enable Windows PowerShell vs PowerShell selection based on (user defined) paths or hidden file?

### ISSUE THREAD

**Issue by S-dn-Y** [PowerShell/vscode-powershell#5067]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Hi everyone,

I've searched through the open and closed issues and in the documentation and I think this doesn't exist yet, please correct me if I'm wrong.
We've started putting effort into making PowerShell 7 the standard in our company not too long ago.
We still have a legacy code base where only Windows PowerShell code is used and maintained but new development efforts will/should go in the repo that houses PowerShell 7+ compatible code.

However when I am developing Windows PowerShell code, using the VS Code extension with pwsh backing it up is kind of prone to error as it's quite easy to mistake the Title parameter on Get-Credential to have been there forever (for example).

Being able to predefine our paths that house Windows PowerShell code, so that the VS Code extension fires of powershell.exe instead of pwsh.exe would be a very handy addition in these cases.
Or maybe a small hidden file in the root of the directory like the .gitignore file that instructs the plugin to overrule the default engine?

Any help is appreciated!
Thanks.

Best regards,
Sidney Ligthart

**Comment by JustinGrote** [comment]
You can create a [workspace file](https://code.visualstudio.com/docs/editor/workspaces) (or a [workspace setting](https://code.visualstudio.com/docs/getstarted/settings)) that specified which version of powershell to use for that folder or workspace file. The setting is `powershell.powerShellDefaultVersion`

**Comment by JustinGrote** [comment]
If what you're asking is to restart the engine every time you open a "powershell" vs "windows powershell" file, we're likely not going to do that, the code just isn't really built to work that way. PowerShell 7 is backwards compatible to 5.1 and you can author 5.1 scripts in 7 and then test them using 5.1 pester and whatnot.

**Comment by S-dn-Y** [comment]
Hi Justin!

> You can create a [workspace file](https://code.visualstudio.com/docs/editor/workspaces) (or a [workspace setting](https://code.visualstudio.com/docs/getstarted/settings)) that specified which version of powershell to use for that folder or workspace file. The setting is `powershell.powerShellDefaultVersion`

This was exactly what I was after, thank you very much. I'm sorry, I feel like some more Google must have pointed me in this direction as well.



> What I would recommend is create a workspace file that sets your default to "Windows PowerShell" and have two editors open, one for 7 and one for 5.1, and do corresponding work in the appropriate editor.

Yes, exactly this. Both folders are Git repositories so we would usually open a new window or use the "Open folder" option to open the folder, which will restart the extension as well.
I've amended the gitignore file (had .vscode excluded) to include at least the settings.json file so my fellow developers will benefit from the setting as well :)

I'll go ahead and resolve this one again.
PS: Thanks for the chat during your preparations for the community demo's during PSConf in Antwerp. We spoke briefly on getting PowerShell 7 implemented. Appreciate the help!!

Have a great day.
Best regards,
Sidney Ligthart
