### ISSUE TITLE
Add CodeLens support for PowerShell function references

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#507]
It would be really handy if there were some CodeLens capabilities added into the vscode-powershell extension, like the number of references for a function\cmdlet, class and its methods from current and all other scripts within the project folder.

**Comment by daviwil** [comment]
Yep, we'll be getting to that soon.

**Comment by rkeithhill** [comment]
Of course, until the extension works across a scripts in a workspace, code lens support won't be super useful.

**Comment by daviwil** [comment]
CodeLens is more than just "find references" you can add arbitrary markers which launch arbitrary actions on any line of code.  I'm curious to see what people will use it for when I add it to the $psEditor API.

**Comment by mattmcnabb** [comment]
I love the function reference capability in ISESteroids, so this would be a win in VSCode assuming we can get all references in a project. Sounds like that could be a ways off.

@daviwil Could you use the markers for something like "to-do" comments? Any chance these could also be used to fold region comments?

**Comment by daviwil** [comment]
We're trying to get cross-module find references going within the next month or two, Codelens support will line up with that.

What would you expect to see for todo comments?  We don't have any control over region folding unfortunately.

**Comment by rkeithhill** [comment]
@mattmcnabb RE region-based code-folding see https://github.com/Microsoft/vscode/issues/3422#issuecomment-189576426

**Comment by mattmcnabb** [comment]
@daviwil Just thinking out loud. For instance, in WIP projects we could add to-do comments to sections and then could "goto" those areas.

@rkeithhill I'm aware of that particular issue. I was just thinking we could use the above "arbitrary actions" to fold content between region comments.

**Comment by jmiller76** [comment]
@mattmcnabb 
I have a Regex to match any tokens of [TokenKind]::Comment that look like todo. This returns the Extent for Todo items.  I have only used this for reporting.  It could be run as a task with a ProblemMatcher entry for the output to generate a clickable list.

I am looking at two VSCode extensions  wayou.vscode-todo-highlight and MattiasPernhult.vscode-todo

The highlight extension needed a few tweaks to settings.json to ID my preferred case of Todo as the default is TODO.  

The vscode-todo extension makes the todo list accessible via the Command Pallet.
