### ISSUE TITLE
Code formatting should place cuddled else on new line when openBraceOnSameLine is false 

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/vscode-powershell#508]
In an attempt to conform to the `Allman` style indenting preferred by my team, I set `powershell.codeFormatting.newLineAfterOpenBrace": false` and Format Document converted this:

 ```posh
    if(Test-Path "C:\Program Files (x86)\PHP\5.6.26\CACert") {
        $PEM = Get-Content $PEM.FullPath -raw
        Add-Content "C:\Program Files (x86)\PHP\5.6.26\CACert\rootCA.pem" $Pem -Encoding ascii
    } else {
        Write-Warning "Failed to deploy PHP cert"
    }
```

to this:

```posh
    if(Test-Path "C:\Program Files (x86)\PHP\5.6.26\CACert")
    {
        $PEM = Get-Content $PEM.FullPath -raw
        Add-Content "C:\Program Files (x86)\PHP\5.6.26\CACert\rootCA.pem" $Pem -Encoding ascii
    } else
    {
        Write-Warning "Failed to deploy PHP cert"
    }
```

I don't know what you call that half-cuddled else, but I just call it wrong 😉 

If people have set `"powershell.codeFormatting.openBraceOnSameLine": false,` you need to ditch the cuddled else as well -- or add a setting for `elseOnSameLine` 😀

**Comment by daviwil** [comment]
@kapilmb looks like a minor bug in the brace formatting rule

**Comment by Jaykul** [comment]
P.S.: my vote is to not add the `elseOnSameLine` setting.

Just do full Allman style for `openBraceOnSameLine = false` and OTBS otherwise.

**Comment by rkeithhill** [comment]
Uh, if `openBraceOnSameLine = true` I still don't want a cuddled else/elseif/catch/finally.  So if the formatting is doing that now, I would prefer a setting disable that.  

As long as I can get the formatter to format to:
```powershell
if ($true) {
    ...
}
else {
    ...
}
```
I'll be happy.  :-)

**Comment by kapilmb** [comment]
@rkeithhill With PowerShell/PSScriptAnalyzer#713 checkin, the codeformatter will allow only the following options

### Style 1
`"powershell.codeFormatting.openBraceOnSameLine": true`

```powershell
if (...) {
...
}
else {
...
}
```

### Style 2
`"powershell.codeFormatting.openBraceOnSameLine": false`

```powershell
if (...) 
{
...
}
else
{
...
}
```

### Style 3
`"powershell.codeFormatting.ignoreOneLineBlock": true`
```powershell
if (...) {...} else {...}
```

**Comment by daviwil** [comment]
And the new `NewLineAfter` setting is true by default, meaning that cuddled else is opt-in by setting `NewLineAfter` to false.

**Comment by kapilmb** [comment]
@daviwil We haven't exposed that switch via codeformatter - Should we expose that here? Then it would look something like this: '"powershell.codeFormatting.newLineAfterCloseBrace": true`

**Comment by daviwil** [comment]
Yep, definitely.

**Comment by kapilmb** [comment]
PR #512 adds the `newLineAfterCloseBrace` switch .

**Comment by Jaykul** [comment]
This is a travesty 😜 
```posh
if (...) {
...
}
else {
...
}
```

You're choosing "Stroustrup" style over the One True Brace Style? With "cuddled else" like the OTBS, you can safely insert a line (even a blank line) anywhere you like without breaking things. Why push Stroustrup?

**Comment by rkeithhill** [comment]
@Jaykul What do you think this is - JavaScript?  :-)  Picking a default brace style is sort of a no-win situation.  I "_don't believe sermons, fairy tales or stories about a OTBS_" (name that movie).  :-)

I think the best that can be done is provide settings to allow folks to configure brace style to their own taste.  They can configure that setting both per user and per workspace.  With that in mind, maybe we need a `"powershell.codeFormatting.cuddleBrace": false` or something to that effect.  My preference would be that it defaults to `false`.

**Comment by ctsstc** [comment]
How can I get stroustrup style for my if else statement blocks, I'm going crazy here.

**Comment by daviwil** [comment]
@ctsstc follow this issue, we're fixing it soon: https://github.com/PowerShell/vscode-powershell/issues/740

**Comment by daviwil** [comment]
But before I go too far in assuming what you mean, can you give an example of what you're looking for?

**Comment by ctsstc** [comment]
@daviwil http://eslint.org/docs/rules/brace-style
```
if (foo) {
  bar();
}
else {
  baz();
}
```

**Comment by Jaykul** [comment]
@ctsstc Stroustrup and Allman are the only styles it does right now. Worst of the worst. 😛 

I think it works like this:

## Stroustrup
```
    "powershell.codeFormatting.openBraceOnSameLine": true,
    "powershell.codeFormatting.newLineAfterOpenBrace": true,
    "powershell.codeFormatting.newLineAfterCloseBrace": true,
```

## Allman
```
    "powershell.codeFormatting.openBraceOnSameLine": false,
    "powershell.codeFormatting.newLineAfterOpenBrace": true,
    "powershell.codeFormatting.newLineAfterCloseBrace": true,
```

**Comment by daviwil** [comment]
@ctsstc your desired style is the default in our code formatter.  Can you give an example of where our default formatting does not follow that style?

**Comment by ctsstc** [comment]
Oh wow, I've failed, I thought this was the main VSCode Repo; /facepalm...

**Comment by daviwil** [comment]
No problem!  Yeah, that's one of the downsides I suppose, each extension has its own way of configuring code formatting (if it's even supported).  You might take a look at the "javascript.format.*" settings and see if you can find the setting you need there.
