### ISSUE TITLE
VS Code, Powershell, Cannot load PSReadline module.  Console is running without PSReadline.

### ISSUE THREAD

**Issue by YorkEarwaker** [PowerShell/vscode-powershell#5080]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Probably the wrong place to post this but following a trail of advice. :-)

Reported issue in PSReadline. Was advised to install latest version of PowerShell. 
https://github.com/PowerShell/PSReadLine/issues/4243

Instaled version 2.3.6 from link provided. updated PowerShell to 2.3.6 . The latest version. Windows system32.
Rebooted machine. Reopened Visual Studio Code. Shell integration failed to activate.
Was advised in email chain to procede here.

*** However

Standalone PowerShell intance reports
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Cannot load PSReadline module.  Console is running without PSReadline.
PS C:\Users\yorke>

Have not tried installing pscore6 as awaiting advice on best way forward. Concerned installing pscore6 might make things worse.

*** Additional information

> code --list-extensions
ms-azuretools.vscode-docker
ms-python.debugpy
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode.cpptools
redhat.java
visualstudioexptteam.intellicode-api-usage-examples
visualstudioexptteam.vscodeintellicode
vscjava.vscode-gradle
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven

> code --status

Version:          Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS Version:       Windows_NT x64 10.0.19045
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  31.85GB (19.77GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id f1b8b665-4d1b-4dae-8466-c8eac86a224e
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               enabled_on
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  skia_graphite:                          disabled_off
                  video_decode:                           enabled
                  video_encode:                           enabled
                  vulkan:                                 disabled_off
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 enabled
                  webnn:                                  disabled_off

CPU %   Mem MB     PID  Process
    0      126    3972  code main
    5      240    3544  window [1] (Settings - jena - Visual Studio Code)
    0      164    5772  extensionHost [1]
    0      662   13960       "C:\Program Files\Eclipse Adoptium\jdk-21.0.4.7-hotspot\bin\java" --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -DDetectVMInstallationsJob.disabled=true -Dfile.encoding=utf8 -XX:+UseParallelGC 
-XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -Xlog:disable -javaagent:c:\Users\yorke\.vscode\extensions\redhat.java-1.36.0-win32-x64\lombok\lombok-1.18.35.jar -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=c:\Users\yorke\AppData\Roaming\Code\User\workspaceStorage\a4849b20ab7b7bebd21edb1cfb410d65\redhat.java -Daether.dependencyCollector.impl=bf -jar c:\Users\yorke\.vscode\extensions\redhat.java-1.36.0-win32-x64\server\plugins\org.eclipse.equinox.launcher_1.6.900.v20240613-2009.jar -configuration c:\Users\yorke\AppData\Roaming\Code\User\globalStorage\redhat.java\1.36.0\config_win -data c:\Users\yorke\AppData\Roaming\Code\User\workspaceStorage\a4849b20ab7b7bebd21edb1cfb410d65\redhat.java\jdt_ws --pipe=\\.\pipe\lsp-433766974457e9b01908e2971edabae4-sock
    0       48   14088     utility-network-service
   10      250   17192     gpu-process
    0      117   17724  ptyHost
    0        7    6864       conpty-agent
    0       71   15836       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\yorke\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0       74   17552       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\yorke\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0        5    9300         C:\WINDOWS\system32\cmd.exe /c ""C:\Users\yorke\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd" --status"
    0      104   17720           electron-nodejs (cli.js )
    1      128   18772             "C:\Users\yorke\AppData\Local\Programs\Microsoft VS Code\Code.exe" --status
    0      105   19196               gpu-process
    0       85   19900               crashpad-handler
    0       90   20492               utility-network-service
    0        7   21196       conpty-agent
    0       32   17860     crashpad-handler
    0       96   22228  fileWatcher [1]
    0       12   22464     C:\Users\yorke\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6.exe /verysilent /log /update="C:\Users\yorke\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0       43    2692       "C:\Users\yorke\AppData\Local\Temp\is-AF1SU.tmp\CodeSetup-stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6.tmp" /SL5="$70884,102294767,828416,C:\Users\yorke\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6.exe" /verysilent /log /update="C:\Users\yorke\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0      134   22644  shared-process

Workspace Stats:
|  Window (Settings - jena - Visual Studio Code)
|    Folder (jena): 204 files
|      File types: ttl(24) class(17) java(17) rdf(16) txt(13) nq(12) nt(12)
|                  trig(12) jsonld(10) pbrdf(6)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: java(2)

https://github.com/PowerShell/vscode-powershell/issues/1834
Ran some of the suggested scripts from this issue listed above.

> (Get-Module PSReadLine).ModuleBase
<nothing was returned>

> code --list-extensions | rg powershell
rg : The term 'rg' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:26
+ code --list-extensions | rg powershell
+                          ~~
    + CategoryInfo          : ObjectNotFound: (rg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

> $env:PSModulePath.Split(';')
C:\Users\yorke\Documents\WindowsPowerShell\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules

> Get-Module -List PSReadLine | select Name, Version, ModuleBase

Name       Version ModuleBase
----       ------- ----------
PSReadline 2.3.6   C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.3.6
PSReadline 2.0.0   C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0

### PowerShell Version

```console
> $PSVersionTable; $Host

Name                           Value
----                           -----
PSVersion                      5.1.19041.5007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.5007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name             : ConsoleHost
Version          : 5.1.19041.5007
InstanceId       : 629784c9-7b00-42d1-a5ca-593c81d8050e
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-GB
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
> code --version
1.95.0
912bb683695358a54ae0c670461738984cbb5b95
x64
```

### Extension Version

```console
> code --list-extensions --show-versions | Select-String powershell
<nothing was returned>
```

### Steps to Reproduce

Update powershell to version 2.3.6 window32 .
Reboot.
Open VS Code.
Open PowerShell console in VS Code. or run debug console in VS Code.

### Visuals

![image](https://github.com/user-attachments/assets/05a60b22-d2bc-4717-bf4c-a506a39ab9b4)
![image](https://github.com/user-attachments/assets/a2e0304c-41b6-48f5-b36d-891c005078d8)
![image](https://github.com/user-attachments/assets/3ef6304c-c905-472f-9271-d687f542fd44)
![image](https://github.com/user-attachments/assets/1cde8c38-e089-4af2-9c26-e3fca289425c)

**Comment by JustinGrote** [comment]
Thanks for your submission!

You can install PowerShell 7 (formerly PS core) side-by-side with Windows PowerShell and it won't affect Windows PowerShell, they are effectively different programs (pwsh.exe vs powershell.exe). You can continue to author 5.1 scripts using PS7 as the main vscode powershell version, and you will generally find it to be faster and more feature-rich with better intellisense, etc. 

I would highly recommend trying this route, as 5.1 is deprecated and has best effort support in the editor currently. If you try 7 and you still can't get PSReadline to load, we can investigate further.

**Comment by YorkEarwaker** [comment]
Dear PowerShell/vscode-powershell,
Installed VS Code pwsh
$PSVersionTable
Name                           Value----                           -----PSVersion                      7.4.6PSEdition                      CoreGitCommitId                    7.4.6OS                             Microsoft Windows 10.0.19045Platform                       Win32NTPSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}PSRemotingProtocolVersion      2.3SerializationVersion           1.1.0.1WSManStackVersion              3.0
Problem has at this time is resolved.
Yours,York
_________________________________________________York Earwaker | London UK | Mb: +44 (0)77 8990 7102_________________________________________________ 

    On Saturday 2 November 2024 at 18:07:26 GMT, github-actions[bot] ***@***.***> wrote:  
 
 


This issue has been labeled as resolved, please verify the provided fix (or other reason).
