### ISSUE TITLE
Assembly Conflict: System.Runtime.Interopservices.Marshal for Excel

### ISSUE THREAD

**Issue by FKramerJr** [PowerShell/vscode-powershell#5081]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When running [Visual Studio Code PS script there is an error when running [System.Runtime.Interopservices.Marshal]::GetActiveObject('Excel.Application'.  This same code works in PS or PS ISE

### PowerShell Version

```console
$PSVersionTable; $Host

Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.5.0
InstanceId       : aa2c81c1-9b98-41c1-b330-e63a5d54db90
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.95.1
65edc4939843c90c34d61f4ce11704f09d3e5cb6
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.5.0
```

### Steps to Reproduce

$Excel = new-object -comobject Excel.Application
$Excel.workbooks.Add() 
$Excel.Visible = $true
$Wb = $Excel.ActiveWorkbook
$Ws = $Excel.ActiveSheet

[System.Runtime.Interopservices.Marshal]::GetActiveObject('Excel.Application')

InvalidOperation: Method invocation failed because [System.Runtime.InteropServices.Marshal] does not contain a method named 'GetActiveObject'.

### Visuals

![VSC Error](https://github.com/user-attachments/assets/b0f53b99-940f-4db8-b348-526ac95b981d)

### Logs

[PowerShellEditorServices-22300.log](https://github.com/user-attachments/files/17602651/PowerShellEditorServices-22300.log)
[StartEditorServices-22300.log](https://github.com/user-attachments/files/17602652/StartEditorServices-22300.log)
[vscode-powershell.log](https://github.com/user-attachments/files/17602653/vscode-powershell.log)

**Comment by JustinGrote** [comment]
Thanks for your submission! Have you tried using PowerShell 7? Due to the way PowerShell 5.1 works, there are some assemblies that we cannot "hide" from the runtime environment, and may cause certain assembly conflicts. We have a tool in PowerShell 7 called Assembly Load Context (ALC) that helps avoid some (but not all) of these conflicts.

Also, I would recommend you check out the `ImportExcel` module which lets you manipulate Excel files without needing excel installed.
