### ISSUE TITLE
2024.4.0: Unable to start when using Windows PowerShell if older Serilog is already present

### ISSUE THREAD

**Issue by ajacks88** [PowerShell/vscode-powershell#5084]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Attempting to launch vscode's powershell extension and get an error. Googling found others with the same issue.

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22621.4249                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22621.4249                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.95.1
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.4.0
```

### Steps to Reproduce

Launch vscode, get the following error:

Exception encountered starting EditorServices. Exception logged in C:\__w\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 239 in EndProcessing:
System.MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Serilog.SerilogLoggerFactoryExtensions.AddSerilog(Microsoft.Extensions.Logging.ILoggerFactory, Serilog.ILogger, Boolean)'.
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesServerFactory.Create(String logDirectoryPath, Int32 minimumLogLevel, IObservable`1 hostLogger)
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesRunner..ctor(HostLogger logger, EditorServicesConfig config, ISessionFileWriter sessionFileWriter, IReadOnlyCollection`1 loggersToUnsubscribe)
   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesLoader.LoadAndRunEditorServicesAsync()
   at Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing()

**Comment by JustinGrote** [comment]
@andyleejordan I think it might be time for us to start catching these methodNotFound errors during startup and reporting some added guidance in this regard.

**Comment by Azburkabas** [comment]
I have the same problem.  After update to v.2024.4.0 it can not load powershell 5.1 sessions (powershell 7 works but I need pwsh 5.1).

Error code:
The terminal process "C:\WINDOWS\SysWOW64\WindowsPowerShell\v1.0\powershell.exe '-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', 'Import-Module 'c:\Users\xxxxxxxxx\.vscode\extensions\ms-vscode.powershell-2024.5.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2024.5.0' -BundledModulesPath 'c:\Users\xxxxxxxx\.vscode\extensions\ms-vscode.powershell-2024.5.0\modules' -EnableConsoleRepl -StartupBanner "PowerShell Extension v2024.5.0
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
" -LogLevel 'Normal' -LogPath 'c:\Users\xxxxxxx\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\logs\1730969275-a948b417-6923-477c-a612-450319746a041730968940191' -SessionDetailsPath 'c:\Users\marko.deverlija\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSCode-21020-286160.json' -FeatureFlags @() '" terminated with exit code: 1.

[ERROR] - PowerShell Language Server process didn't start!

**When i roll back to v2024.2.2 it works just fine.**

**Comment by Phillip-Ian** [comment]
Nothing new to add, just reinforcing the issue.  Exact same symptoms, and rolling back to v2024.2.2 did the trick.

**Comment by JustinGrote** [comment]
@ajacks88 @Phillip-Ian @Azburkabas we can't reproduce this anywhere, so we have to figure out what is different about your environment. 

- Have you tried with PowerShell 7 and do you still have the same problem? A reminder that PS 5.1 is best effort support but we certainly aren't making any moves to actively break it.
- Have you tried on another computer, preferably with a clean profile and a clean modules folder with no third party modules installed?
- If the "other computer" works, we will need a list of your installed modules and maybe we can identify an early loader, but in PS 5.1 we don't have access to isolation tech that we have in 7 and are possibly unlikely to solve an incompatability with that specific module and will recommend you use 7 instead (you can still author 5.1 scripts in 7)

**Comment by JustinGrote** [comment]
@ferjea01 thanks! As previously stated we can't reproduce so if you can provide the info requested here:
https://github.com/PowerShell/vscode-powershell/issues/5084#issuecomment-2465996039

It might help us narrow it down.

**Comment by Azburkabas** [comment]
> * a

Hi, i wrote above that powershell 7 works, but i needed pws 5.1 for all msonline/graph etc... pws modules.

I tried uninstalling vscode and cleaning all config folders and install everyting from scratch  (with no other vs code extensions except powershell extension and it still didn't work). Reverting to v2024.2.2. works just fine

**Comment by ferjea01** [comment]
Hi @JustinGrote , 

We need powershell 5.1 for Windows related module (msmq and iis stuff such as webbinding, appPool configuration, etc) .
The most important modules we use are WebAdministration and SqlServer, Microsoft.SqlServer.Smo and System.Messaging.

My collegue also had the same problem on his computer. 

We have Windows 10 Enterprise 22h2 19045.5011. Could any security update created that glitch?

**Comment by andyleejordan** [comment]
Hm, this was tested against Microsoft Windows Server 2022 [10.0.20348](https://github.com/PowerShell/PowerShellEditorServices/actions/runs/11599805714/job/32298775863#step:1:4).

@dkattan was hitting almost this exact same failure scenario with the "mission method" from the logger in https://github.com/PowerShell/PowerShellEditorServices/issues/1477#issuecomment-863154520...seems like there's an incompatible version of Serilog in the GAC on these versions of Windows where it's failing, and that's getting picked up before our own, and we [did](https://github.com/PowerShell/PowerShellEditorServices/commit/41fce39f491d5d351b4ac5864e89857ec070e107) bump the versions of Serilog [twice](https://github.com/PowerShell/PowerShellEditorServices/commit/a56d8e2993d03d112765456b3ff11c8ebb620c59).

In my opinion @JustinGrote and @SeeminglyScience we should dump Serilog and Microsoft.Extensions.Logging entirely, since we're required to keep it up-to-date, but doing so results in package incompatibles for 5.1 thanks to the GAC. We just need to minimize our dependencies entirely.

**Comment by JustinGrote** [comment]
@andyleejordan been working extensively on a logging rewrite on another branch, so I know a lot of the internals here.

MEL is part of the omnisharp LSP server so I don't think we can ditch that, but we can ditch serilog for sure in favor of a simple MEL fileprovider, or, in my model, I've been transitioning the logging to go over the LSP as logMessage once the bootstrap completes.

**Comment by andyleejordan** [comment]
Yeah, MEL looks like it will stick around for a bit. Serilog should really go though. While there are hits for Serilog in [OmniSharp](https://github.com/search?q=repo%3AOmniSharp%2Fcsharp-language-server-protocol%20serilog&type=code) as far as I can tell they're only in tests, so if we get rid of it, I think it's _gone_.

I would much prefer logging over LSP anyway, and yes as you say, just keep a file (probably not even on by default?) for logs pre-LSP for when we need to debug that bit. If we make that diagnostic only it can probably be a dead simple file logger.

**Comment by andyleejordan** [comment]
Also we'd get to resolve https://github.com/PowerShell/PowerShellEditorServices/issues/1477 since that `IDisposable` mess exists just thanks to Serilog being under the covers.

**Comment by JustinGrote** [comment]
https://github.com/PowerShell/vscode-powershell/issues/2538 reopened for historical as well, should be addressed and closed with whatever PR fixes this.

**Comment by JustinGrote** [comment]
For anyone else potentially experiencing this issue, [please capture a diagnostic trace](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#logs) and upload to this issue. If you aren't getting the MEL logger exception, your issue may be different, but this is most likely being caused by the Serilog version bump as @andyleejordan  noted.

**Comment by JustinGrote** [comment]
Hopefully https://github.com/PowerShell/PowerShellEditorServices/pull/2197 fixes this. In the meantime please downgrade to the previous version.

**Comment by JustinGrote** [comment]
Hey everyone, thanks for your patience, @andyleejordan should get out a preview release tomorrow that should have this fixed, we will notify here and if you still have issues let us know.

**Comment by jsantoro339as** [comment]
After updating the extension to the preview release I now get the following error

hell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing()

== Press any key to close terminal ==
Start-EditorServices : Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Serialog.SerialogLoggerFactoryExtensions.AddSerialog(Microsoft.Extensions.Logging.ILoggerFactory, Serialog.ILogger, Boolean)'.
At line:1 char:148
+...ices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' ...
+
    + CategoryInfo                  : NotSpecified: (Microsoft.Power...ServicesCommand:StartEditorServicesCommand) [Start-EditorServices], MissingMethodException
    + FullyQualifiedErrorId      : PowerShellEditorServicesError,Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand

**Comment by JustinGrote** [comment]
@jsantoro339as the new prerelease hasn't been released yet, very soon! We ran into an internal verification build problem, I expect @andyleejordan will get that sorted today or tomorrow.

**Comment by JustinGrote** [comment]
It's out! Go to your extensions and choose "switch to pre-release" in the right click menu and let us know if this fixes it for you!

**Comment by jsantoro339as** [comment]
@JustinGrote  Yes, I just updated it and it is working again.  Thank you team, for addressing the issue and getting the fix out.

**Comment by andyleejordan** [comment]
So glad to hear it!

**Comment by andyleejordan** [comment]
Hey @ajacks88 the fix for this is in the pre-release version of the extension, can you please give it a try? Thanks!
