### ISSUE TITLE
Error in foreach-progress snippet

### ISSUE THREAD

**Issue by kakogawa** [PowerShell/vscode-powershell#5086]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Error in foreach-progress snippet

ms-vscode.powershell-2024.4.0\snippets\PowerShell.json
![1](https://github.com/user-attachments/assets/02233359-4c36-4527-aa48-ce14ec0b8558)

Run the snippet
![2](https://github.com/user-attachments/assets/9ff76e1d-4938-40cd-8621-b76a0f6642f4)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Name             : Visual Studio Code Host
Version          : 2024.4.0
InstanceId       : e7b09809-d6fd-41fc-ab3a-73c61a4278aa
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : ja-JP
CurrentUICulture : ja-JP
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.95.2
e8653663e8840adaf45af01eab5c627a5af81807
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.4.0
```

### Steps to Reproduce

use foreach-progress snippet

**Comment by kakogawa** [comment]
I find many aspects of this snippet puzzling.
Line 168 is clearly unnecessary code as it is already in line 174.  
Also, if you're going to use $i and $total, isn't it more natural to use for and $array.Count instead of foreach?  
In the first place, $total is not even defined.

**Comment by andyleejordan** [comment]
@kakogawa the snippets are community maintained. @o-l-a-v has a (great) PR ensuring the JSON is valid, please feel free to submit an update to the snippet after that making it more PowerShell-y.
