### ISSUE TITLE
Additional terminal not loading my profile.ps1

### ISSUE THREAD

**Issue by adambrubaker** [PowerShell/vscode-powershell#5089]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Hello.  I noticed that I now have two different terminals for powershell in VSCode.
![image](https://github.com/user-attachments/assets/da0b880d-f516-4433-8525-fcac4cce6e3e)

The top one (powershell) loads my profile (C:\Windows\system32\WindowsPowerShell\v1.0\profile.ps1) correctly but is not the terminal that gets used when I hit F5 to execute a script.  When I do that, it uses the second terminal (PowerShell Extension) which is not loading my profile and causing issues.  Is this something new that I missed?

I really just want one terminal that will load my profile and execute with F5.  I'm happy to make any config changes to get there.  Thanks!

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.4249
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.4249
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name             : ConsoleHost
Version          : 5.1.22621.4249
InstanceId       : e6dc8ad8-8db3-4346-83f5-8f0ec410aad7
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.95.3
f1a4fb101478ce6ec82fe9627c43efbf9e98c813
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.4.0
```

### Steps to Reproduce

Open file, press F5, the script executes in the "PowerShell Extension" terminal, which is not loading my profile (C:\Windows\system32\WindowsPowerShell\v1.0\profile.ps1).

**Comment by JustinGrote** [comment]
Thanks for your submission!

Is there a reason you're using a system profile and not a user profile? And have you verified that you don't have the `powershell.enableProfileLoading` set to false?

**Comment by adambrubaker** [comment]
Hey Justin

I use multiple clients for PowerShell on that system (PowerShell, Terminal, and VSCode).  I like just having to set one profile that works across all of them.  Also, I don't have `powershell.enableProfileLoading` set to false?  Not in my setttings file but it's checked here.

![image](https://github.com/user-attachments/assets/0a0af0e3-83c0-4246-9c5d-54ec50d4606c)

**Comment by JustinGrote** [comment]
Are you aware of the `$profile.CurrentUserAllHosts` path that is in your user space and works for all PowerShell hosts (vscode, powershell, terminal, etc.)? Have you tried setting it there?

**Comment by adambrubaker** [comment]
I did not know that was a thing.  I just moved my stuff over there and it works great!  Thank you.

Last question.  How do I get rid of that second terminal?  The one that just says 'powershell' not 'PowerShell Extension'

**Comment by JustinGrote** [comment]
Unfortunately there's a bug in upstream vscode that prevents us from totally hiding that one, you mostly just have to close it on startup or just ignore it. There's an issue on it but I can't find it at the moment. @andyleejordan?

Closing for now since your issue is solved. Thanks!
