### ISSUE TITLE
"whilespace" in PSScriptAnalyzer(PSMisleadingBacktick)

### ISSUE THREAD

**Issue by FrankCarius** [PowerShell/vscode-powershell#5091]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Small cosmetic issue "whilespace" instead of "whitespace" in PSScriptAnalyzer/PSMisleadingBacktick

### PowerShell Version

```console
PS C:\> $PSVerionstable;$host

Name             : Visual Studio Code Host
Version          : 2024.4.0
InstanceId       : e1ae2ce0-f26b-461b-9b42-ff74648528f8
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : de-DE
CurrentUICulture : de-DE
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
PS C:\> code --version
1.95.3
f1a4fb101478ce6ec82fe9627c43efbf9e98c813
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.4.0
```

### Steps to Reproduce

Start VSCode with an empty PowerShell File. (ps1)
Add the following code (there is a space after the backtick)

get-item `
-path c:\temp

Wait for the hint about "PSMisleadingBacktick" from PSScriptAnalyzer
click on "quick fix" and the menu offers "Remove training whilespace" "l" instead of "t"

### Visuals

![image](https://github.com/user-attachments/assets/cc22c005-9d4c-41c0-be2f-4969a6214581)

**Comment by JustinGrote** [comment]
Thanks for your submission! 

That needs to be fixed in PSScriptAnalyzer, here is the line. You could easily submit a PR by clicking edit there, I would suggest it so you get credit in the next release!

https://github.com/PowerShell/PSScriptAnalyzer/blob/a744b6cfb6815d8f8fcc1901e617081580751155/Rules/MisleadingBacktick.cs#L75
