### ISSUE TITLE
Running any PowerShell script crashes the terminal before it even launches

### ISSUE THREAD

**Issue by jsantoro339as** [PowerShell/vscode-powershell#5092]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Once I try to run vscode and it starts the PowerShell session, it always fails.  I have uninstalled all extensions, then I have completely removed vscode including deleting any leftover components. Rebooted and reinstalled vscode.  Once I opened the PS1 file it asked me if I wanted to install the PowerShell extension, I did and once installed it immediately crashes and fails with the error hell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing() 

My PowerShell script I am using to test is only containing the below line. get-childitem "c:\temp" -depth 0

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.4391
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.4391
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name             : ConsoleHost
Version          : 5.1.22621.4391
InstanceId       : b2ca931a-2fac-41e3-a1bb-a1fcdd2eed43
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.95.2
e8653663e8840adaf45af01eab5c627a5af81807
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.4.0
```

### Steps to Reproduce

I am only creating a new ps1 file and adding the below line

Get-ChildItem c;\temp -depth 0

I get the below error before I execute

Exception encountered starting EditorServices. Exception logged in C:\__w\1\s\src\PowerShellEditorServices.Hosting\Commands\StartEditorServicesCommand.cs on line 239 in EndProcessing:
hell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing()

### Visuals

![image](https://github.com/user-attachments/assets/8848ef08-d222-4811-823e-4ea3d1e1e1f7)

### Logs

[vscode_logs.zip](https://github.com/user-attachments/files/17804102/vscode_logs.zip)

**Comment by JustinGrote** [comment]
Dupe of https://github.com/PowerShell/vscode-powershell/issues/5084, see there for workarounds until a new release is published.
