### ISSUE TITLE
if powershell extension dies, error message is hidden under terminal window

### ISSUE THREAD

**Issue by jtaseff-gfms** [PowerShell/vscode-powershell#5102]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

Using Powershell extension in VSC to run and debug some scripts. Sometimes if there is some error in a script, the terminal will die or get frozen, and hitting F5 again starts doing weird things like giving odd errors or freezing. Once I realize what happened, I kill the powershell terminal window with the trash can icon. Only then does the panel close and reveal a pop-up that was hidden underneath it that seemed to have been hiding the whole time, saying "powershell has died would you like to restart it"

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.4.0
InstanceId       : db0853a3-35c7-4ac7-b616-9a2dbd6462cb
UI               : System.Management.Automation.Internal.Host.InternalHostUserInte
                   rface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.95.3
f1a4fb101478ce6ec82fe9627c43efbf9e98c813
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.4.0
```

### Steps to Reproduce

- Open a terminal within VS Code
- Move the panel position to the right side
- make a script that is invalid or would cause an error
- Run it within VS Code editor with F5
- extension and terminal will freeze, not obvious what is happening
- close terminal with trash can icon
- now the error is visible that would have explained and recovered

### Visuals

This should be shown, but is hidden by the terminal itself when the panel is on the right.

![image](https://github.com/user-attachments/assets/aac1710b-be50-4878-b286-560ce3f00a6a)

**Comment by JustinGrote** [comment]
Thanks for your submission!

These are standard error popups in vscode, there's not much we can do to fix any kind of terminal popup overlay problems. Haven't really been able to reproduce the overlay problems, can you try a screen recording to show us what's going on? You can hit Win+Shift+R in Windows 11 to start screen recorder, and when finished there'll be a copy button in the upper right that you can paste directly into GitHub.
