### ISSUE TITLE
AWSHistory wrecking the debugger display

### ISSUE THREAD

**Issue by Rom265** [PowerShell/vscode-powershell#5106]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When I run code with the debugger to step through my code and I hit an AWS command, like get-ec2instance or something, I get between 4 and 10 times the following line shows up in the terminal window: "AWSHistory is deprecated and will be removed in the next major release. Instead, use '-Select *' when it is necessary to return the entire service response as cmdlet output."
So, maybe this is an AWS problem, but I don't understand at all how this is happening, and it only happens when I am debugging in VS Code. And, crucially, every command that I step through after the first time this happens causes that line to appear 4 to 10 times, even non-AWS commands.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.4.0
InstanceId       : 9b6858bd-e56e-4caa-ad16-01b1a8eacde1
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.95.3      
f1a4fb101478ce6ec82fe9627c43efbf9e98c813
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.4.0
```

### Steps to Reproduce

step through code that calls a cmdlet from an AWS.Tools module. I just ran this command:

> wait-debugger;C:\scripts\aws\Get-EC2instanceCommonProps-dev.ps1

It opened a new tab with that text and wait-debugger highlighted. The instant that happened, before I even hit F11 to get into the script, it printed the AWSHistory line 36 times.

**Comment by JustinGrote** [comment]
Added my note there. It's just standard write-warning behavior, can you maybe do win+shift+r and record what "wrecked" display behavior looks like? 
https://github.com/aws/aws-tools-for-powershell/issues/364#issuecomment-2506787249

**Comment by JustinGrote** [comment]
Closing as wontfix - external as noted in the other thread, they will fix upstream.
https://github.com/aws/aws-tools-for-powershell/issues/364#issuecomment-2506848838
