### ISSUE TITLE
Powershell Terminal Window Constantly Hanging

### ISSUE THREAD

**Issue by schwinbp** [PowerShell/vscode-powershell#5114]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
The Powershell Terminal window randomly, however very often, hangs while running powershell commands and scripts throughout the day. There is no specific commmand or script that causes this. It happens on many. I then have to either wait for it to spew the Last 200 keystrokes(like below) out or restart the Terminal Session. 

fwd-i-search: _
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.4.0-beta0+923a890f2e7ea10465f3a80a2bc030121a1c2f68
PowerShell: 2024.4.0
OS: Microsoft Windows 10.0.22631
BufferWidth: 155
BufferHeight: 25

Last 200 Keys:

 p p p p p p p p p p p p p Ctrl+s p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p Enter
 c l s Enter
 p p p p p p p p

### Exception

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 26.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://github.com/user-attachments/assets/84d952f1-5bea-4278-8688-a4ed9c718332)

### Environment data

```console
PS Version: 7.4.6
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.4.0-beta0
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 301
BufferHeight: 52
```

### Steps to reproduce

Run powershell commands or scripts. Eventually it will occur. 

### Expected behavior

Does not randomly hang the terminal window and allows me to run commands when I need to. 

### Actual behavior

Randomly hangs through the daay.

**Comment by daxian-dbw** [comment]
@andyleejordan I transferred this issue to the vscode-powershell repo given that this issue happens only in the VSCode terminal with the PowerShell VSCode extension. See https://github.com/PowerShell/vscode-powershell/issues/5114#issuecomment-2523898164

**Comment by schwinbp** [comment]
Ok will give extension update a try

**Comment by andyleejordan** [comment]
> Update here... I updated PSReadline this morning and rebooted. Verified that the 2.4.0 beta was running. I have already hit a hang while running some git commands.
> 
> ![image](https://private-user-images.githubusercontent.com/7315782/393280724-84668294-7cfd-4913-af7b-fdf5949780b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MTk3NjcsIm5iZiI6MTczMzUxOTQ2NywicGF0aCI6Ii83MzE1NzgyLzM5MzI4MDcyNC04NDY2ODI5NC03Y2ZkLTQ5MTMtYWY3Yi1mZGY1OTQ5NzgwYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMjExMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGViNTE3MDkzNjE3ZmU0YzM2ZGRiZmMzODllOWExZGNjNmE0N2YxOThiYTczYTU1NmNhMWI5YWQzMmNlYThhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3JJJE8itpzMJx_MWP8H68ns-4wZs3iBtQp_5bDWvPU0)

Now that you've updated your regular (not VS Code) PowerShell session to use the same version, 2.4.0-beta, can you reproduce it outside of VS Code?
