### ISSUE TITLE
Extension does not recognize local Visual Studio Build Tools installation for Cython compilation

### ISSUE THREAD

**Issue by dfischerqunevo** [PowerShell/vscode-powershell#5119]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

In our project we use a git hook to compile several cython files when pulling from git. This is automated with an environment variable pointing to the local powershell.exe installed with windows. This automated workflow works as intended. During programming, we need to sometimes invoke cython compilation by hand, thus triggering the ps1 script without the provided environment variable. This starts the powershell extension which is apparently not a subprocess of the local installation of powershell and tries to compile the cython files. In previous versions, this was so issue. With the recent version, the extension is not able to detect installed C++ compilers on the system, thus resulting in an error. The compilation process with other shells is possible and works as intended. We isolated the problem down to this extension.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name             : Visual Studio Code Host
Version          : 2024.4.0
InstanceId       : c42d8070-1fcc-4865-8b53-45bb9d0d7ee8
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : de-DE
CurrentUICulture : de-DE
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visual Studio Code Version

```console
1.96.2
fabdb6a30b49f79a7aba0f2ad9df9b399473380f
x64
```

### Extension Version

```console
empty (Maybe issue lies here?)
```

### Steps to Reproduce

Compile cython files with powershelll extension.

**Comment by JustinGrote** [comment]
Thanks for your submission!

When you say you invoke a ps1 script, how are you doing it? Starting a ps1 script from a process should make it a child process, the fact it's ending up in the extension window implies you are using a vscode api command or similar to launch the script.
