### ISSUE TITLE
can not install some environment

### ISSUE THREAD

**Issue by dothuan2114** [PowerShell/vscode-powershell#5120]
### Prerequisites

- [X] I have written a descriptive issue title.
- [ ] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [ ] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [ ] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [ ] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

.\myenv\Scripts\Activate
>> 
.\myenv\Scripts\Activate : The term '.\myenv\Scripts\Activate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ .\myenv\Scripts\Activate
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\myenv\Scripts\Activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### PowerShell Version

```console
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22621.4391                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22621.4391                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.96.2
x64
```

### Extension Version

```console
ms-vscode.powershell@2024.4.0
```

### Steps to Reproduce

.\myenv\Scripts\Activate
>> 
.\myenv\Scripts\Activate : The term '.\myenv\Scripts\Activate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ .\myenv\Scripts\Activate
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\myenv\Scripts\Activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by JustinGrote** [comment]
Thanks for you submission! Are you sure your script exists in this path? Is this something that only happens in the vscode-powershell extension? It looks to me like your script doesn't exist, did you forget the extension at the end (.ps1), can you tab-complete the path?

This repository is for the PowerShell vscode extension, and is for issues specifically related to its operation. I recommend aka.ms/PSDiscord for general PowerShell assistance, unless you can demonstrate this is a problem specifically with the PowerShell VSCode extension.
