### ISSUE TITLE
Unable to activate PIM roles

### ISSUE THREAD

**Issue by azaman004110-az** [PowerShell/vscode-powershell#5121]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Hi,

I am issues with activating my PIM roles via Visual studio with Connect-AzureAD: This module does not support PowerShell Core edition. Retry the operation with PowerShell Desktop edition (Windows PowerShell).

I am running this command Enable-DCAzureADPIMRole -RolesToActivate 'Exchange Administrator', 'Global Reader', 'Teams Administrator', 'Sharepoint Administrator' -UseMaximumTimeAllowed -Reason 'Digital Workplace tasks' 

![pim role 1](https://github.com/user-attachments/assets/fd0b2355-0391-4abc-a6f2-404552ecc21a)

I don't get the pop window of MFA anymore

I get the error below screenshot
![image (34)](https://github.com/user-attachments/assets/e45b40d3-e180-4278-8fc7-7255b757a86c)

I have Powershell version installed Version
2023.5.0

Is anyone able to advise why i am getting error?

**Comment by JustinGrote** [comment]
Thanks for your submission!

This is for the vscode extension specifically, not general PowerShell support. Some obvious things however:
1. You are probably using PowerShell 7, whereas the module you are using needs powershell 5.1
2. Your vscode powershell version is very out of date, the current is 2024.5.2
3. The AzureAD module is deprecated and no longer supported. https://techcommunity.microsoft.com/blog/identity/important-update-deprecation-of-azure-ad-powershell-and-msonline-powershell-modu/4094536

You may want to try the Microsoft Graph module for activating the PIM role you are trying to do (an entra ID role), and there is also my JAz.PIM module that simplifies this task:
https://github.com/justingrote/jaz.pim
