### ISSUE TITLE
Feature request: intellisense in integrated terminal (like ISE)

### ISSUE THREAD

**Issue by ahubbard** [PowerShell/vscode-powershell#514]
### System Details

any/any

```
any/any
```

### Issue Description

I am experiencing a problem with... syntax in the integrated terminal.  ISE has intellisense not just in the editor, but also in the integrated terminal.  That would be extremely useful in VS Code as well.

### Attached Logs

none

**Comment by wellsluo** [comment]
+1, and colorful characters is also needed.

**Comment by daviwil** [comment]
Both IntelliSense in the terminal and colored output are coming as part of the "integrated console" feature, #10.  This work is completing soon, subscribe to that issue to be notified when it's done.

**Comment by westerdaled** [comment]
Hi, I know this issue as been closed but for some reason I am really struggling to get intellisense in my terminal or indeed debug window.   You can see this the img below.  I won't move from the ISE until this is resolved.
![PS Integrated terminal but no Intellisense](https://user-images.githubusercontent.com/937208/54368057-5bf8fc80-466b-11e9-8fcb-ffbea3c08b9b.png)

**Comment by TylerLeonhardt** [comment]
@westerdaled Have you tried the [PowerShell Preview extension](https://devblogs.microsoft.com/powershell/announcing-the-powershell-preview-extension-in-vscode/)? It has PSReadLine support in the integrated terminal.

**Comment by westerdaled** [comment]
Thanks done now.  I had to disable the existing PowerShell Extension, so I am guessing I will be loosing the intellisense and code analysing in the code editor windows.

**Comment by westerdaled** [comment]
Hi I have enabled it will test shortly-  I have added The shell switcher for PS 6 and it seems to have stopped step over function in  debugger so will back it out.

**Comment by westerdaled** [comment]
@TylerLeonhardt  .  I had to reinstall the PowerShell Extension to the debugger to work again.  I then disabled it to allow the PowerShell Preview to work . Unfortunately, I am still not get intellisense to work in the PowerShell integrated terminal .

**Comment by SydneyhSmith** [comment]
@westerdaled sorry to make this so complicated, but PSReadLine actually needs to be enabled with a feature flag to work: 
To enable PSReadLine support in the Preview version on Windows, please add the following to your user settings:
```
"powershell.developer.featureFlags": [ "PSReadLine" ]
```

**Comment by westerdaled** [comment]
@SydneyhSmith  Alas the gods are against me! Run he debugger till my break point .  Var is populated but cannot get the intellisense to work.  Is there a different key combination I should use?
```
 "window.zoomLevel": 2,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "powershell.developer.featureFlags": [ "PSReadLine" ],
    "git.autofetch": true,
```

**Comment by SydneyhSmith** [comment]
@westerdaled what is the output of $PSVersionTable for you?

**Comment by TylerLeonhardt** [comment]
@westerdaled intellisense in the editor or in the terminal? (screenshots are helpful 😄 )

**Comment by westerdaled** [comment]
@SydneyhSmith 

Here you go

PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by westerdaled** [comment]
Here is a screen dump whereby  I pause the debugger and see if I can inspect any of my vars - here I have written the term name to standard output so I should be able inspect any of the other property values.
![PS Integrated terminal but no Intellisense 2](https://user-images.githubusercontent.com/937208/54391646-5c11f000-469d-11e9-8093-0dcd5d9f7272.PNG)

**Comment by TylerLeonhardt** [comment]
@westerdaled does nothing happen when you hit TAB?

**Comment by westerdaled** [comment]
@TylerLeonhardt   

Doh! Ok that works but no pop up scrollable  list  like the ISE just each function shown on each Tab

**Comment by TylerLeonhardt** [comment]
Unfortunately, we cannot have that kind of a dialog in vscode like the ISE... However, you can rely on PSReadLine's MenuComplete!

```powershell
Set-PSReadLineKeyHandler -Chord 'Ctrl+@' -Function MenuComplete
```

and then do `$termGroup.` and hit `Ctrl+SPACE`. You should see the PSReadLine experience which is identical to what you get in regular pwsh.exe.

Here are a few others that a useful - which can go right into your profile:

```
if ($env:TERM_PROGRAM -eq "vscode") {
    Set-PSReadLineKeyHandler -Chord 'Ctrl+w' -Function BackwardKillWord
    Set-PSReadLineKeyHandler -Chord 'Alt+D' -Function KillWord
    Set-PSReadLineKeyHandler -Chord 'Ctrl+@' -Function MenuComplete    
}
```

**Comment by westerdaled** [comment]
@TylerLeonhardt 

This looks good 
```
D:\Dev\PS> $profile   
C:\Users\[MYNAME}\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1
D:\PS> notepad $profile

```
I pasted your lines in , saved and hit  F1  (Command Palette)  and selected Reload Window.  My profile is now active.

Liking Ctrl Space as you suggested . The other two PSReadLine commands I guess I will need to use more.

**Comment by TylerLeonhardt** [comment]
@westerdaled quick tip:

```pwsh
Open-EditorFile $profile
```

Opens the file in vscode :)

```pwsh
New-EditorFile $profile
```

Creates the file if it doesn't exist and opens it in vscode :)

**Comment by westerdaled** [comment]
Btw, I have started to use this more instead of  ISE  as the editing experience is good. The only issues I have is that the debug doesn't always start quickly and VSCode just seem to hang. Indeed you sometimes get a timeout message.  I stop,  then flip back to ISE  if I am in a hurry.

**Comment by TylerLeonhardt** [comment]
Thanks for the info! When this happens, can you open up a new issue and also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) to the new issue so we can get a better idea of what's going on?

**Comment by westerdaled** [comment]
@TylerLeonhardt  yes will do.

**Comment by westerdaled** [comment]
I am really liking the preview experience which I gather has taken a lot of effort by the team. Is the intention to enable the fully PSReadline experience as referenced in [Scott Hanselman'](https://www.hanselman.com/blog/TowardsABetterConsolePSReadLineForPowerShellCommandLineEditing.aspx)s blog post?

**Comment by TylerLeonhardt** [comment]
That's the intention. It's the same PSReadLine module that Scott points out so the experience should be almost identical to what you expect in the regular console.
