### ISSUE TITLE
Feature Request: Add intellisense from Specific PS1 Files and between editor and Terminal

### ISSUE THREAD

**Issue by bruckect** [PowerShell/vscode-powershell#515]
### System Details

any/any
$PSVersiontTable:
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I work with the PowerShell App Deployment Toolkit on a daily basis. They have a main.ps1 and extension.ps1 file that contain all cmdlets that you can reference when authoring new files. Altough they talk about converting this to a module, it is not something that is on the horizon at the moment. Today in ISE/PowerShell studio, I have the ability to either run these files in the current terminal by pressing F8 or in PowerShell Studio, I can include the main.ps1 and extension.ps1 by running it in the current terminal. Once run/included, I gain intellisense within the editors. 

I don't believe that this is a duplicate request, although it is similar to the other intellisense feature requests by adding intellisense. I wasn't able to find one that was asking for intellisense between the terminal and the editor. 

I could see this working in two ways, either add an option to "Include" a .ps1 file in the current context so that VSCode runs the code and imports the cmdlets/help into the current running session (so I can have intellisense). OR allow me to dot source the code in terminal and include that into the current intellisense so that I can use it in the editor.

ISE and PowerShell Studio may get away with this because they use the same PowerShell runspace, i'm not sure how this behaves in VSCode works.

I hope this makes sense, I'm happy to elaborate more if necessary. If there is another way of accomplishing this currently, I'm happy to test it out. VSCode is quickly becoming my editor of choice. If this functionality can be integrated, it will be my primary editor.

**Comment by daviwil** [comment]
This is coming very soon, the work is done and I'm doing final polish now.  Closing this in favor of the original "interactive console" feature request #10, subscribe to that to be notified when this work is done.
