### ISSUE TITLE
Indefinitely Starting PowerShell

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#516]
- Operating system name and version: Windows 10 Enterprise (Anniversary Edition)
- VS Code version: 1.9.1
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Today I've started experiencing a strange issue, where VSCode can no longer start up PowerShell engine. The 'Starting PowerShell...' status message is being displayed indefinitely. It was working yesterday, and the only thing that I've done about VSCode since then (other than working on my PS modules) was update of a few extensions (GitLense and Settings Sync, but disabling didn't make any difference).

Looking at the Extension logs, the only thing in there is this:
![image](https://cloud.githubusercontent.com/assets/18121861/23405746/648e5ada-fdc4-11e6-9e03-64840a2cb413.png)

It appears that PowerShell terminates almost immediately after it starts.

I've tried launching the script listed in the args section manually in a separate PowerShell console, and it seems to launch fine (at least doesn't crash immediately).

The Developer Tools console doesn't seem to have anything related. Last record states about start of the PowerShell process (with the same PID as on the screenshot) but there is no process with such a PID running on the machine at the moment.

Tried rebooting the system, but the issue is still there.

Are there any suggestions?

Thanks!

**Comment by daviwil** [comment]
Hmmm, no EditorServices.log got created?  Has any group policy changed on your machine which might affect PowerShell?

**Comment by Glober777** [comment]
No recent GPO changes. Is there any more verbose logging that could be turned on? If I capture procmon or WPR trace, would that be of any help?

**Comment by Glober777** [comment]
I've been digging further and think that the issue is not related to the PowerShell extension or VSCode at all. While trying to reproduce the steps outside of the VSCode, I've discovered that running the following (from within cmd) produces nothing on my machine (while it does work on others):
`C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Unrestricted -NoExit -Command "& {Write-Host 'Hello World!'}"`

Surprisingly, the powershell.exe process starts and runs for about a second (as per procmon), however, it exits out without any complaints. Neither does it leave any traces in the Event Log and\or the file system even with Transcripting and ScriptBlockLogging enabled. Running PowerShell console interactively, on the other hand, works fine and leaves traces behind as expected.

This made me think how much attached I got to VSCode with the PowerShell extension. Even with the lack of several ISE capabilities, without VSCode I now feel almost like I got a hand chopped off. Anyway, I'll keep digging.

**Comment by Glober777** [comment]
In the end the issue turned out to be caused by the antivirus.

**Comment by daviwil** [comment]
Interesting...  What was your antivirus doing to kill the process?  Did you just have to disable it for your $HOME/.vscode folder?  I wonder if others have hit a similar issue.

**Comment by Glober777** [comment]
Ok, so I've just found out what exactly in my antivirus (McAfee Endpoint Security 10.5) was causing the issue. Apparently, there's a default Application Protection rule (created by McAfee) within Threat Prevention, called 'Microsoft Windows POWERSHELL'. It didn't seem like there's a way to tweak it, other than disable it altogether to make it work. Hope it helps others.
