### ISSUE TITLE
Add code fix or formatting rule to generate splatted parameters from command invocation

### ISSUE THREAD

**Issue by mpearon** [PowerShell/vscode-powershell#517]
Sapien's PowerShell Studio has a feature that will allow you to convert single line commands to be splatted.
For a visual of what I'm talking about, [click here](https://www.sapien.com/assets/facebook/SplatCommand.gif)

This would be a great enhancement, I think!

### System Details

- Operating system name and version:  Windows 10, 1511
- VS Code version: v1.9.1
- PowerShell extension version: v0.9.0
- Output from `$PSVersionTable`:
                                                                                              
```                                                                                              
PSVersion                      5.0.10586.672                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                        
BuildVersion                   10.0.10586.672                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                
WSManStackVersion              3.0                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                            
SerializationVersion           1.1.0.1                                                                                                        

```

**Comment by daviwil** [comment]
Yep, I think we could add this as a command in the editor.  What do you think @kapilmb?

**Comment by kapilmb** [comment]
Or a code-action, perhaps? 

Not sure about the timeline though. I would say this will be a great post-1.0 addition. What do you say?

**Comment by daviwil** [comment]
It could be a suggested code action if the line was longer than a certain length, for sure.  However, I think it'd be nice if this was something that could be invoked anytime on a command in a script file.

We could try it post-1.0 unles @Jaykul gets to it first ;)

**Comment by Jaykul** [comment]
If there was a rule that gave a `warning` on lines longer than 120char, but an `information` on all commands with more than one parameter ... would that be enough to let you surface it the way you're imagining, @daviwil?

**Comment by daviwil** [comment]
Yeah, that could work.  For the "invoke any time" approach, I think we'd basically just run the rule on the current script line (including any backticked lines following that) and see if a marker gets returned.  If yes, apply the correction.

**Comment by mpearon** [comment]
@daviwil  - Has there been any more planning and/or movement on this project?

**Comment by daviwil** [comment]
We've been occupied with other work lately so we haven't been able to focus on this particular issue.  I think the ideal way to add this feature would be through an extension module.  Thankfully @SeeminglyScience has done just that :)

https://github.com/SeeminglyScience/EditorServicesCommandSuite

Check out the Demo section for a GIF that demonstrates its features.

**Comment by TylerLeonhardt** [comment]
@SeeminglyScience did a great job in EditorServicesCommandSuite and we shouldn't stomp on his toes in that.

That said, @Jaykul hinted at something that this would make an awesome PSScriptAnalyzer rule.

I'll close this since folks should either grab ESCS or refer to the issue in PSSA that Rob will post here.

**Comment by snewfie** [comment]
Can't get EditorServicesCommandSuite  to work with the latest vscode and PowerShell extension 

is there a new setting or config that I am missing?

**Comment by TylerLeonhardt** [comment]
@snewfie can you open an issue over in https://github.com/SeeminglyScience/EditorServicesCommandSuite and provide as much info as you can?
