### ISSUE TITLE
Debugger hangs after continuing when watch expressions are set

### ISSUE THREAD

**Issue by yobyot** [PowerShell/vscode-powershell#519]
### System Details

- Operating system name and version: Windows 10.0.14393
- VS Code version: 9.1
- PowerShell extension version: 0.9.0
- Output from $PSVersionTable:

![image](https://cloud.githubusercontent.com/assets/14332263/23476674/884d46c8-fe89-11e6-971c-9bca4ae0b68b.png)

### Issue Description

I am experiencing a problem with...

Debug hangs.

I cannot successfully repeat a debug session with a breakpoint. If I pick a breakpoint, reach it and then continue, sometimes the script will continue, sometimes it won't. In the attached image I attempt to illustrate the problem by pointing to the progress indication, which never stops. Sometimes, I cannot even start a debugging session. 

It's a shame PowerShell debugging doesn't work well since I'd love to adopt vscode over the ISE.

![2017-03-01_14-10-53](https://cloud.githubusercontent.com/assets/14332263/23476993/85e508a2-fe8a-11e6-8b73-447062089582.png)

### Attached Logs
[PS090-logs.zip](https://github.com/PowerShell/vscode-powershell/files/811803/PS090-logs.zip)

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
Remove the two watch expressions and try again.  There is a known issue evaluating watch expressions in 0.9.0 that has (hopefully) been fixed in the next drop - due soon.

**Comment by daviwil** [comment]
This has been fixed in PowerShell Editor Services, PowerShell extension update coming soon.
