### ISSUE TITLE
Change debug adapter registration to pass /debugAdapter parameter

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#52]
VS Code debug adapter configurations have now been updated to accept an `args` array:

https://github.com/Microsoft/vscode/issues/1199

This can be used to replace the current .cmd file hack we use to pass the `/debugAdapter` parameter to the PowerShell Editor Services host process.

**Comment by rkeithhill** [comment]
That will be a nice change for those of us debugging the debugger.  :-)

**Comment by daviwil** [comment]
Yeah!  We'll be able to throw `/waitForDebugger` in there now too :)

**Comment by daviwil** [comment]
Woohoo!  They fixed it.  Adding `/waitForDebugger` is very easy now so that we don't have to go to so much trouble to debug the debugger ;)
