### ISSUE TITLE
PowerShell Interactive debugging does not break on non-code lines

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#521]
### System Details

- Operating system name and version: Windows 10 Pro
- VS Code version: 1.10.1
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                                  
----                           -----                                                                                                  
PSVersion                      5.1.14393.693                                                                                          
PSEdition                      Desktop                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                
BuildVersion                   10.0.14393.693                                                                                         
CLRVersion                     4.0.30319.42000                                                                                        
WSManStackVersion              3.0                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                    
SerializationVersion           1.1.0.1                                                                                                
```

### Issue Description

Trying out interactive debugging of a module, dbatools in VSCode. It was referenced in #349 that using the debug consoles should work.  I opened a function within the module and set a breakpoint, then launched the interactive session but the breakpoint is not being hit.

Trying to see if this is an issue or I'm just missing something?

### Reproduce

I cloned [dbatools module](https://github.com/sqlcollaborative/dbatools) from GitHub. Opened up the Get-DbaDatabase.ps1 file and set a breakpoint at line 132.

My launch.json:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "dbatools Interactive",
            "cwd": "${workspaceRoot}"
        }
    ]
}```

I start the debugger. I issue following commands:
```powershell
Import-Module dbatools.psd1
Get-Database -SqlInstance MyServer
```

The command outputs data instead of hitting the breakpoint, which is set prior to where it should output anything.

![image](https://cloud.githubusercontent.com/assets/11204251/23515575/286a92cc-ff30-11e6-8780-e847a354de87.png)

### Attached Logs

[vscode-powershell.txt](https://github.com/PowerShell/vscode-powershell/files/814377/vscode-powershell.txt)
[EditorServices.txt](https://github.com/PowerShell/vscode-powershell/files/814378/EditorServices.txt)

**Comment by daviwil** [comment]
Hey Shawn, sorry I missed this somehow.  Looks like you're setting a breakpoint on a line which doesn't contain any code.  Have you tried this in the ISE, does it work there?

**Comment by wsmelton** [comment]
Breakpoints don't have to be on line of code when using the `current file` launch config.
![image](https://cloud.githubusercontent.com/assets/11204251/23903895/1b9c38b2-0894-11e7-95ea-06307a50a129.png)

**Comment by tylerl0706** [comment]
Triaging a bit - I'm updating this title to reflect the issue. PowerShell Interactive debugging does not break on non-code lines.

**Comment by Zhunya** [comment]
Can this be answered or just closed? :) A good explanation or blog post will be awesome expirience sharing for developers!

**Comment by SeeminglyScience** [comment]
The module doesn't dot source it's ps1 files, instead it reads the file directly and creates script blocks on the fly for a little bit of performance.  Specifically [this line](https://github.com/sqlcollaborative/dbatools/blob/fb003dfeefaeca9e9042aa25fe40aad6ce482f44/dbatools.psm1#L27).

When a script file is loaded with that method, any `ScriptExtent` objects associated with the generated script blocks will not contain the file path.  If the `ScriptExtent` doesn't have the file path, the PowerShell engine will never hit any associated line breakpoints.

@tylerl0706 This issue can be closed.  @daviwil and I worked this out with @wsmelton on Slack a few months ago.

**Comment by tylerl0706** [comment]
Sounds good! Thanks @SeeminglyScience!
