### ISSUE TITLE
Alias 'select' and 'sort' are not highlighted

### ISSUE THREAD

**Issue by MovGP0** [PowerShell/vscode-powershell#524]
### System Details

- Operating system name and version: Windows 10.0.14393.0
- VS Code version: 1.10.1
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
In the following snippet
```powershell
Get-AzureVMImage 
| where ImageFamily -eq $imageFamily
| sort PublishedDate -Descending 
| select -ExpandProperty ImageName -First 1 
```
the aliases `sort` and `select` are not highlighted like the `where` alias, besides representing the same type of filter/alias. 

Expected behavior: 
* all alias should be highlighted the same way. 
* use `Get-Alias` to enumerate all defined alias in the powershell session.

**Comment by MovGP0** [comment]
When expanding the snippet to 
```powershell
Get-AzureVMImage `
| Where-Object ImageFamily -eq $imageFamily `
| Sort-Object PublishedDate -Descending `
| Select-Object -ExpandProperty ImageName -First 1
```
Then on my computer, `Where` of `Where-Object` will be highlighted in violet, `Sort-Object` won't be highlighted and `Select-Object` will be highlighted in yellow.

**Comment by rkeithhill** [comment]
I've observed the same thing.  However, syntax highlighted is provided by a different project.  Can you post this issue on https://github.com/powershell/editorsyntax?  Thanks.

**Comment by MovGP0** [comment]
*see also:* https://github.com/PowerShell/EditorSyntax/issues/39

**Comment by rkeithhill** [comment]
@MovGP0 Thanks!
