### ISSUE TITLE
regions with here-strings do not fold

### ISSUE THREAD

**Issue by michaelburch** [PowerShell/vscode-powershell#525]
The region folds everything except the here-string. This same code folds correctly in ISE

#region AmbariHostGroup specific
if ($HostGroup -eq 'Ambari') {
    nxPackage ambariServer
    {
        Name = "ambari-server"
        Ensure = "Present"
        PackageManager = $packageManager
        DependsOn = @('[nxScript]ambariRepo','[nxEnvironment]javaHome','[nxPackage]ambariAgent')
    }
    $cfsignalDeps += '[nxScript]registerBlueprint'
    
    nxScript registerBlueprint
    {
        SetScript = @'
#!/bin/bash
BLUEPRINT_NAME=$(awk -F "=" '/BLUEPRINT_NAME/ {print $2}' /etc/profile.d/rptenv.sh)
logger "[DSC]: Registering Blueprint"
# Register Blueprint
curl -H "X-Requested-By: ambari" -X POST -u admin:admin http://127.0.0.1:8080/api/v1/blueprints/$BLUEPRINT_NAME -d @/tmp/ambariBlueprint.json
'@
        TestScript = @"
#!/bin/bash
exit 1
"@
        GetScript = @"
#!/bin/bash
"@
        DependsOn = @('[nxScript]installAmbariServer','[nxEnvironment]javaHome')

   }
#endregion 
 
### System Details

- Operating system name and version: Windows 10 Pro 1607
- VS Code version: 1.10.2
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:

```
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

regions with here-strings do not fold

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
There is nothing we can do about this in the PowerShell extension at this time.  Code folding is completely controlled by VSCode and is based **purely** on indentation which as you've observed, doesn't work with PowerShell here strings.  I suggest you +1 this issue on the VSCode issue - [Microsoft/vscode#3422 (comment)](https://github.com/Microsoft/vscode/issues/3422#issuecomment-189576426)
