### ISSUE TITLE
VSCode auto completion for custom modules with relative path

### ISSUE THREAD

**Issue by JBaltika** [PowerShell/vscode-powershell#527]
Hi guys,

I spend an hour plus researching on web and trying to work auto-completion for VSCode   then import custom modules.  Its work for fine for *.psm1. How to make works for custom CmdLet as I am C# guy and have limited knowledge of PS. I appreciate any help, or some hack or way doing. Its just not nice to use help then we have VSCode editor  :) 

Thanks J.B

PS Code

Import-Module "..\.msbuild\MyCompany.PowerShell.Commands.dll" -Verbose

Nuget-PackAndPush (No auto-completion)

C# code

    [Cmdlet("Nuget", "PackAndPush")]
    public sealed class NugetPackAndPushCommand : Cmdlet
    {
        /// <summary>
        /// Gets or sets the working directory.
        /// </summary>
        /// <value>The working directory.</value>
        [Parameter(Position = 0, Mandatory = true, ValueFromPipeline = true, ValueFromPipelineByPropertyName = true)]
        [ValidateNotNullOrEmpty]
        public string WorkingDirectory { get; set; }
......

**Comment by rkeithhill** [comment]
You have several options.  I recommend that you create a `MyCompany.PowerShell.Commands.psd1` file using the `New-ModuleManifest` command.  Point the `RootModule` entry at your dll and enter the exported commands in the `CmdletsToExport` section.  Now, assuming your dll/psd1 files are in $env:PSModulePath, PowerShell can automatically import your module whenever someone accesses a cmdlet that it exports.

Another option is to create a file named `Microsoft.VSCode_profile.ps1` under `$Home\Documents\WindowsPowerShell` directory.  Put the following command in the file (with the correct path):
```posh
Import-Module "...msbuild\MyCompany.PowerShell.Commands.dll" -Verbose
```
Now restart VSCode and it should recognize your module's cmdlets.  

Yet another option is that you can highlight the import command in a script, press F8 to run it and after that your cmdlets will show up in Intellisense.

**Comment by JBaltika** [comment]
Thank you for sharing your superb knowledge in PS. That is awesome answer ...

**Comment by rkeithhill** [comment]
No problem.
