### ISSUE TITLE
"Powershell: Select PSScriptAnalyzer Rules" does nothing

### ISSUE THREAD

**Issue by andrewducker** [PowerShell/vscode-powershell#528]
### System Details

- Operating system name and version: Windows 7
- VS Code version: 1.10.1
- PowerShell extension version: 0.9.0
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

### Issue Description

I am experiencing a problem with "Powershell: Select PSScriptAnalyzer Rules"
I try to run this from the command list, and nothing happens.
Turning on Verbose Log Level meant this appeared at the top of the screen:
![image](https://cloud.githubusercontent.com/assets/91378/23852240/b2e6b64a-07de-11e7-8515-0ab2904b81b4.png)

"Command 'PowerShell.SelectPSSARules' not found"

### Attached Logs

[VSCodeIssue.zip](https://github.com/PowerShell/vscode-powershell/files/838010/VSCodeIssue.zip)

**Comment by andrewducker** [comment]
Started working in 0.10.0 (noticed yesterday), and is still working for me in 0.10.1

**Comment by daviwil** [comment]
Thanks for letting me know!  We changed some seemingly unrelated things in the PSScriptAnalyzer integration for 0.10.0 and it looks like it fixed whatever the problem was.  Definitely let me know if it ever stops working for you again.
