### ISSUE TITLE
Scoped functions trigger code analysis

### ISSUE THREAD

**Issue by Lee303** [PowerShell/vscode-powershell#53]
When a function is scoped (e.g. function Global:DoSomething(){}), code analysis (warning) is triggered with 'Reserved character in name'.

**Comment by daviwil** [comment]
Hi Lee,

I believe this issue was fixed in Script Analyzer 1.2.0 so you should see it get resolved when I integrate that version in the next release of the VS Code extension.

Thanks!

**Comment by daviwil** [comment]
It seems this has been fixed with Script Analyzer 1.3.0 which will be included with this week's release of the extension.  Let me know if you still see the problem after you install the update once it's released.
