### ISSUE TITLE
Intellisense Broken

### ISSUE THREAD

**Issue by raakeshn** [PowerShell/vscode-powershell#531]
### System Details

- Operating system name and version: Microsoft Windows Server 2012 R2 Standard
- VS Code version: No idea what this is.
- PowerShell extension version: Powershell host version is 5.0.10586.117
- Output from `$PSVersionTable`:

```
Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.0.10586.117                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.10586.117                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1
```

### Issue Description

Hi, I am experiencing an issue with intellisense going haywire and a broken powershell/ISE, especially after upgrading to the version 5. The auto completion (when Tab is pressed) does not respond at times. Powershell ISE displays the message "Running script / selection.  Press Ctrl+Break to stop" during startup with no script being run, on an empty "untitled.ps1" file and stops automatically after a while.

**Comment by daviwil** [comment]
Hi @raakeshn, this GitHub repo is for the PowerShell language support for [Visual Studio Code](https://code.visualstudio.com), not the PowerShell ISE.  I will see if I can reproduce your issue if I get a few moments.

**Comment by raakeshn** [comment]
Hi @daviwil, I am sorry, was unaware being a non-dev person. I am new to PowerShell and using it only for Azure deployments. Your help is much appreciated. Thanks.
