### ISSUE TITLE
Backspace doesn't work in integrated console on Linux and macOS

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#533]
The backspace key isn't working in the integrated console on Linux and macOS.  This is likely a simple issue, just needs to be investigated.

In the meantime, a workaround is to press <kbd>Ctrl+H</kbd> to emulate backspace.

**Comment by oliswiss** [comment]
Seems to affect my Windows 10 client as well. I can't enter backspace by typing or copy & paste (will get stripped from pasted strings).
Let me know if I can provide any details for troubleshooting.

**Comment by daviwil** [comment]
@oliswiss are you using a non-US keyboard layout?

**Comment by gmckeown** [comment]
I'm seeing this issue on Ubuntu 16.10 with VSCode 1.10.2, PowerShell extension 0.10.1, and PowerShell 6.0.0 alpha 17. Keyboard layout is United Kingdom English.

As indicated above, ctrl-H does backspace. Shift-Backspace also works. Both result in "^H" appearing on-screen briefly before the backspace occurs.

**Comment by daviwil** [comment]
I've got a fix in progress for this but it may take a few more days to fully validate it.  Should fix all of the key handling issues and the `^H` printing issue.
