### ISSUE TITLE
ERROR: Starting the CLR failed with HRESULT 80040153.

### ISSUE THREAD

**Issue by 5nowx** [PowerShell/vscode-powershell#539]
### System Details

- Operating system name and version: Windows 10 LTSB Win32_OperatingSystem
- VS Code version: 1.10.2
- PowerShell extension version: 0.90
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Problem when starting Powershell, powershell could not be started

### Attached Logs

powershell.exe started --
    args: C:\Users\user\.vscode\extensions\ms-vscode.PowerShell-0.9.0\scripts\Start-EditorServices.ps1 -EditorServicesVersion '0.9.0' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '0.9.0' -BundledModulesPath 'C:\Users\user\.vscode\extensions\ms-vscode.PowerShell-0.9.0\modules' -LogLevel 'Verbose' -LogPath 'C:\Users\user\.vscode\extensions\ms-vscode.PowerShell-0.9.0\logs\1489527421-145d15e2-67a7-4f68-b383-90fc8157f7f01489526949702\EditorServices.log' 

    pid: 10404
    bundledModulesPath: C:\Users\user\.vscode\extensions\ms-vscode.PowerShell-0.9.0\modules
    exe: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
ERROR: S t a r t i n g   t h e   C L R   f a i l e d   w i t h   H R E S U L T   8 0 0 4 0 1 5 3 . 
 
 
PowerShell could not be started, click 'Show Logs' for more details.

powershell.exe terminated with exit code: 4294901760

**Comment by daviwil** [comment]
Another user has hit the same issue: #476.  Closing this issue in favor of the other.  I'll look into this again soon.
