### ISSUE TITLE
Package Latest Release for Side-Loading

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/vscode-powershell#54]
Is there any intention to package 3.1 as a .zip release for sideloading? My work environment is disconnected - without a way to mirror the packages for sideloading, I can't distribute to my team. I would vastly prefer to grab the package from here for this purpose.

**Comment by daviwil** [comment]
Thanks for reminding me Michael!  I'll put this together sometime today and will let you know when it's up.

**Comment by michaeltlombardi** [comment]
No worries, I just got approval for VSCode and was going about setting up my own workstation when I noticed.

**Comment by daviwil** [comment]
A little slow on getting this one resolved, but we're adding side-load packages to each new GitHub release now (as you've already seen :).
