### ISSUE TITLE
Get-Credential on OSX Integrated Console displays password

### ISSUE THREAD

**Issue by drewjanderson** [PowerShell/vscode-powershell#542]
### System Details

- Operating system name and version: OSX 10.12.3
- VS Code version: Version 1.10.2 (1.10.2)
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:

UserName                      Password
--------                      --------
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.14
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am experiencing a problem with Get-Credential password entry showing password
<img width="506" alt="screen shot 2017-03-14 at 9 27 31 pm" src="https://cloud.githubusercontent.com/assets/24446757/23929596/a7d5f9f8-08fd-11e7-895e-43a33e201c43.png">

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by drewjanderson** [comment]
Updated PS on OSX and it had the same issue: v6.0.0-alpha.17

**Comment by daviwil** [comment]
Thanks!  There are weird issues with characters echoing when they shouldn't on Linux and macOS.  I think I have a general fix for this, will try to get it out this week.

**Comment by daviwil** [comment]
I've got a fix for this now, shipping an update tomorrow.
