### ISSUE TITLE
No back slash '\' in Powershell Integrated Console

### ISSUE THREAD

**Issue by yaphet666** [PowerShell/vscode-powershell#543]
### System Details

- Operating system name and version: Windows 7 Enterrpise (german language pack and Keyboard)
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14394.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14394.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I can't type a back slash '\' in the Pwoershell Integrated console. The Problem is only within the new integrated console. It works fine in the standard Terminal (cmd or powershell) and in the editor pane.

**Comment by mbsj** [comment]
Same issue. However it extends to all special characters that require AltGr (or Ctrl + Alt) to enter, including dollar-sign (AltGr + 4 or Ctrl + Alt + 4)... Which is a problem :)

**Comment by DamirZelenic** [comment]
Same here, AltGr + anything is not working. Even if I paste Get-Process | Get-Member in Integrated console I get Get-Process  Get-Member (| is missing).

**Comment by mbsj** [comment]
@DamirZelenic I just noticed that too. Copying a variable name and pasting it in the console strips the dollar sign from the text.

**Comment by DanielTheCoder** [comment]
Same issue on Windows 10 Enterprise

**Comment by daviwil** [comment]
I know what's causing this, will get a fix out soon.  Thanks for the report!
