### ISSUE TITLE
Ctrl + Shift + <ArrowKey> does not work in new IntegratedTerminal

### ISSUE THREAD

**Issue by dotps1** [PowerShell/vscode-powershell#545]
### System Details

- Operating system name and version: Windows 10 Enterprise x64 1607
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:

```
$ > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When using the new integrated terminal, i can use the ctrl key modifier and arrow key to move to the next logical break in the text.  Or use the shift to highlight.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Coming with PSReadline support: https://github.com/PowerShell/vscode-powershell/issues/535
