### ISSUE TITLE
Cannot insert special characters to Get-Credential with AltGr

### ISSUE THREAD

**Issue by stwehrli** [PowerShell/vscode-powershell#546]
### System Details

- Operating system name and version: Win 10 Build 14393
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:

```
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Probably a dupe. I cannot enter special characters in Get-Credential like '@' or '[' which require Alt Gr in my keyboard layout.

**Comment by daviwil** [comment]
Yep, it's been reported here too: https://github.com/PowerShell/vscode-powershell/issues/543, closing in favor of the earlier issue.  Working on a fix for this now!
