### ISSUE TITLE
Host prompts are no longer going to the UI

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/vscode-powershell#549]
### System Details

- Operating system name and version: Windwos Seven Fr sp1
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:

```
Evaluate $PSVersionTable in PowerShell and paste the output here
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

I am experiencing a problem with 'Plaster' menu.
Version 0.10.0 no longer use the GUI menu but CLI :
![image](https://cloud.githubusercontent.com/assets/4894452/23952956/6a4e00d0-0993-11e7-8d34-44a9786349a4.png)

When I insert text (ABCDFGHI), it is inserted on two lines

### Attached Logs
[logs.gz](https://github.com/PowerShell/vscode-powershell/files/844779/logs.gz)

**Comment by daviwil** [comment]
Thanks Laurent!  This is a general change to how prompting works in the extension.  I need to provide a way for code to redirect its prompt back to the UI and then update Plaster to use it.

**Comment by daviwil** [comment]
This change depends on #526.

**Comment by SydneyhSmith** [comment]
Closing as resolved
