### ISSUE TITLE
Interactive Console displays strangely after code execution

### ISSUE THREAD

**Issue by steviecoaster** [PowerShell/vscode-powershell#554]
### System Details

- Operating system name and version: Windows 8.1 Enterprise
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.0.10514.6
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10514.6
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

### Issue Description

The console displays in a weird manner after script execution or resizing the window:
![broken console](https://cloud.githubusercontent.com/assets/8674240/23966587/4b62c314-0992-11e7-9800-6ce9ef633ea0.png)

After typing in a simple command (Clear-Host for example), the prompt returns to normal:
![working console](https://cloud.githubusercontent.com/assets/8674240/23966614/6713900c-0992-11e7-989b-e2cb4e8fc474.png)

### Attached Logs
No logs yet collected. Would you like some? Which ones?

**Comment by daviwil** [comment]
Thanks @steviecoaster!  Logs probably won't help in this case.  When I start looking into this I might bug you to see if I can better understand the scenarios in which it happens.

**Comment by daviwil** [comment]
Hey @steviecoaster, do you still see this issue in the latest PowerShell extension?  I believe we fixed it for 1.0, so try 1.2 and let me know if it still occurs for you.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
