### ISSUE TITLE
Enable debugging of untitled script files

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#555]
VS Code will soon be gaining the ability to launch the debugger on untitled, unsaved files.  Since this is a scenario that works in the ISE, we should leverage VS Code's new feature to provide it in the PowerShell extension too.

https://github.com/Microsoft/vscode/issues/19415

/cc @dfinke

**Comment by rkeithhill** [comment]
ISE does not allow you to set a breakpoint in an unsaved file.  The same applies to the VSCode PowerShell extension.  Internally, it uses the `Set-PSBreakpoint` command which, for a line breakpoint, requires a path.  

You can set a command breakpoint and the debugger will hit that e.g.:
```posh
 function foo {}
 
 foo
 $a = 7
 $b = 36
 $c = 42
```
Set a command breakpoint on `foo` and the debugger will break there and then you can single step through the rest of the code.  It would be nice if this feature supported a "break on entry" option.  Then you wouldn't need the dummy function hack to get the debugger to break.  That said, it can be challenging to debug without line breakpoints so it is best to just save the file.

**Comment by rkeithhill** [comment]
Wait a tic, if I hit the command breakpoint I see another editor window open that uses a temp (saved) file so you can set line breakpoints.  The bug here @daviwil is that this `script listing.ps1` file isn't showing up by default.  It doesn't show up if I don't have the command breakpoint set.  Ideally it should show up when you start the debugger.  Maybe this is a case where the script is so short it completes before this other windows opens?

**Comment by grumpkin** [comment]
Maybe I'm still doing this wrong but I still can't get it to break.  I have the unsaved script file that, creates a dummy function called `foo`, calls that function, then does what I actually want.  In the PowerShell Integrated Console I run `Set-PSBreakpoint -Command foo` (I don't know if that is actually what you meant by "Set a command breakpoint"), press F5 and it still just runs the entire script.

**Comment by rkeithhill** [comment]
Trying setting the breakpoint in the VSCode Debug panel.  At the bottom, open the Breakpoints view, press the `+` button and type in `foo`:

![image](https://user-images.githubusercontent.com/5177512/27930338-7133399c-6253-11e7-837d-bc7d7d370ffe.png)

**Comment by grumpkin** [comment]
That worked. Thanks very much.
