### ISSUE TITLE
Enable the use of WebSocket channel for PowerShell Editor Services

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#56]
Adam Driscoll's new WebSocket channel in PowerShell Editor Services makes it possible to connect to a remote Editor Services host.  We should figure out how to make it possible to connect to such a server via the VS Code extension (including having settings to configure the connection).

**Comment by tylerl0706** [comment]
Ah. There it is :)

**Comment by TylerLeonhardt** [comment]
Closing this.

I made something similar here:
https://github.com/TylerLeonhardt/monaco-powershell

It had a wrapper that would forward websocket messages to the stdio version of PSES.
