### ISSUE TITLE
Interactive console hangs when stopping the debugger

### ISSUE THREAD

**Issue by ThePSAdmin** [PowerShell/vscode-powershell#560]
### System Details

- Operating system name and version: Windows 10.0.14393
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When debugging with an interactive session, if you click the stop debugging button whilst on a breakpoint, the integrated console hangs and crashes
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/847364/logs.zip)
. 

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rjmholt** [comment]
This is probably related to https://github.com/PowerShell/vscode-powershell/issues/1494

**Comment by JustinGrote** [comment]
I cannot reproduce this anymore (yay!), though https://github.com/PowerShell/vscode-powershell/issues/2377 is a similar but different crashing issue that is still relevant.
