### ISSUE TITLE
Uppgrade to powershell embedded terminal breaks elevation 

### ISSUE THREAD

**Issue by clmcgrath** [PowerShell/vscode-powershell#561]
After latest update scripts and modules that require elevation no longer will work 
It seems that the powershell terminal is not inheriting elevation permissions when running vscode as administrator as it did before the upgrade to 0.10.0

**Comment by daviwil** [comment]
Seems it's working for me:

![image](https://cloud.githubusercontent.com/assets/79405/23997999/e31efb86-0a10-11e7-856b-13aa2f708feb.png)

Can you capture and upload logs so I can take a look?

https://github.com/PowerShell/vscode-powershell#reporting-problems

**Comment by clmcgrath** [comment]
ok,  this seems to have magically started working  ... will close issue .
