### ISSUE TITLE
Extension startup times out too soon on lengthy (7-10 sec) language server startup

### ISSUE THREAD

**Issue by aurbjo** [PowerShell/vscode-powershell#562]
### System Details

- Operating system name and version: Windows Server 2012 R2
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:
PSVersion                      5.0.10514.6
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10514.6
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3`

### Issue Description

I am experiencing a problem when i try to start the Integrated terminal. Ii hangs at "Starting Powershell" for some time and finally fails with the following error:
Could not start language service: 
Timed out waiting for session file to appear.

![image](https://cloud.githubusercontent.com/assets/10774456/23998786/7aa2e25c-0a56-11e7-9223-3c1044ece3d0.png)

![image](https://cloud.githubusercontent.com/assets/10774456/23998840/b713d642-0a56-11e7-8be5-f3c0da29f818.png)

![image](https://cloud.githubusercontent.com/assets/10774456/23998809/98be0f78-0a56-11e7-80d3-023fa337d9f4.png)

### Attached Logs
[vscode-powershell.zip](https://github.com/PowerShell/vscode-powershell/files/847821/vscode-powershell.zip)

**Comment by daviwil** [comment]
Hey Bjørn, thanks for filing this!  I think you forgot to turn on Verbose logging, your log file seems to be missing some lines:

```
"powershell.developer.editorServicesLogLevel": "Verbose"
```

**Comment by aurbjo** [comment]
Sorry about that. here's the correct logs with Verbose logging enabled, i wrote "Debug" instead of "Verbose" the first time :)

[1489672155-12b1df75-c9e1-481c-9072-9837761f96e61489672141705.zip](https://github.com/PowerShell/vscode-powershell/files/847854/1489672155-12b1df75-c9e1-481c-9072-9837761f96e61489672141705.zip)

**Comment by daviwil** [comment]
Thanks, that did the trick!  So it looks like nothing is failing during startup, I think the extension is just not waiting long enough for the language server to initialize before timing out.  I'll bump up the timeout length in the patch update I'm shipping today, that'll should fix it for you.

**Comment by aurbjo** [comment]
Thank you 👍
