### ISSUE TITLE
PowerShell Integrated Console: Unable to type symbols

### ISSUE THREAD

**Issue by OCram85** [PowerShell/vscode-powershell#563]
### System Details

- Operating system name and version: Win7 Pro 64bit (6.1.7601.65536) German
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
- Unfortunately it's not possible to prompt keys like `| <> [ ] {} @` into the interactive console.
  - It seems like all inputs with the keys `ctrl` + `alt` + `<key>`, or `alt gr` + `<key>` doesn't work. 
- Copy & Paste from other sources doesn't work either.

**Comment by daviwil** [comment]
Fixed this issue yesterday (https://github.com/PowerShell/vscode-powershell/issues/543), I'll ship an update with the fix in a few hours.

**Comment by OCram85** [comment]
Srry, didn't search for previous tasks. :(

Thanks for your awesome work.!

**Comment by daviwil** [comment]
No problem!
