### ISSUE TITLE
Intellisense stops working when stopped on a breakpoint 

### ISSUE THREAD

**Issue by clmcgrath** [PowerShell/vscode-powershell#566]
### System Details

- Windows 10 1607 
- VS Code version: 3.10.9
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`: 

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Intellisense stops working when stopped on a breakpoint 
if i am coding normally intellisense works as expected 
if i set a breakpoint enter debug mode and try to write code i get no intellisense 

**Not Debugging**

![not-debugging](https://cloud.githubusercontent.com/assets/452012/24003884/12f59e08-0a3b-11e7-882f-c41377b4e301.png)

**Debugging**

![debugging](https://cloud.githubusercontent.com/assets/452012/24003919/31169b1c-0a3b-11e7-911c-a6ce1e7a98f6.png)
 
### Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/848139/logs.zip)
[vscode-powershell.txt](https://github.com/PowerShell/vscode-powershell/files/848142/vscode-powershell.txt)
[EditorServices.txt](https://github.com/PowerShell/vscode-powershell/files/848141/EditorServices.txt)
.

**Comment by daviwil** [comment]
Thanks!  I know what's causing this, will see if I can fix it quickly.

**Comment by clmcgrath** [comment]
@daviwil  Looks like this is happening again since 0.11 was release looks like it is affecting the symbol search as well (ctrl-shift-o) now 

doesn't give me the option to reopen the issue  should I create a brand new one?

I will try and get you a new log on Monday morning or over the weekend if I am doing any coding at home

**Comment by daviwil** [comment]
Hmmm, that shouldn't have been affected in this update.  Definitely send along logs when you get a chance.  I'll reopen this issue when I verify what's going on.  Thanks!

**Comment by clmcgrath** [comment]
Ok,  so it seems to be happening  with long running commands 
adding my logs from most recent session this happened in 
[vscode-powershell.txt](https://github.com/PowerShell/vscode-powershell/files/879821/vscode-powershell.txt)
[EditorServices.txt](https://github.com/PowerShell/vscode-powershell/files/879822/EditorServices.txt)
