### ISSUE TITLE
Prompts from registered $psEditor commands are not displaying correctly

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/vscode-powershell#567]
### System Details

- Operating system name and version:
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.0
- Output from `$PSVersionTable`:
```

Name                           Value                                                                                  
----                           -----                                                                                  
PSVersion                      5.1.15058.0                                                                            
PSEdition                      Desktop                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                
BuildVersion                   10.0.15058.0                                                                           
CLRVersion                     4.0.30319.42000                                                                        
WSManStackVersion              3.0                                                                                    
PSRemotingProtocolVersion      2.3                                                                                    
SerializationVersion           1.1.0.1                                                                                



```

### Issue Description

I am trying out $PSEditor and was trying to duplicate the prompt for choice example from http://brandonpadgett.com/powershell/Getting-Started-With-Editor-Commands/.

I am using this code:
```
Function DemoChoice {
    [cmdletbinding()]
    param
    (
        [Microsoft.PowerShell.EditorServices.Extensions.EditorContext]$context
    )

    $Options = "Apple","Blueberry","Cherry"
    $caption = "Select a filling"
    $message = "Inserts filling string"
    [int]$defaultChoice = 0
    $Choices = [System.Management.Automation.Host.ChoiceDescription[]] @($Options)
    $Name = $host.ui.PromptForChoice($caption,$message, $choices,$defaultChoice)
    $context.CurrentFile.InsertText($options[$name],$context.CursorPosition)
}

Register-EditorCommand -Name DemoChoice -DisplayName "Demo choices" -Function DemoChoice -suppressOutput
```
But when I run the editor command, the prompt is in the new integrated console and not the editor which is where I expect and want it to be. I suppose I could live with it in the console, but display gets trashed when I try to click in the console and type an answer.

### Attached Logs
[ps-vscode-logs.zip](https://github.com/PowerShell/vscode-powershell/files/848207/ps-vscode-logs.zip)

**Comment by daviwil** [comment]
Yep, I think I know why the display is getting trashed.  The prompts not going to the UI is another issue: https://github.com/PowerShell/vscode-powershell/issues/549.

**Comment by jdhitsolutions** [comment]
I even tried Brandon's insert emoji example and I end up with this in the terminal.

![image](https://cloud.githubusercontent.com/assets/12089920/24014633/1a340d64-0a5c-11e7-9f3f-7f6109cd0227.png)

**Comment by JustinGrote** [comment]
I can't reproduce this one however its **very important** to remove the -suppressoutput parameter in the example, otherwise the PromptForChoice won't work.
