### ISSUE TITLE
Integrated console should allow setting Write-* message colors through PrivateData

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#571]
This is supported by the ConsoleHost and some people (like @Jaykul) use it to customize their message colors.

**Comment by AspenForester** [comment]
Just checking in on this.  I'm sure there are conflicting dev commitments between this and PSReadLine integration.

**Comment by TylerLeonhardt** [comment]
I think this should be fixed now in Preview thanks to the work @SeeminglyScience did to bring over the original host?

**Comment by SeeminglyScience** [comment]
Nah that was thanks to @KeroroLulu with PowerShell/PowerShellEditorServices#654.

I'll go ahead and close it either way, should be in stable.  Thanks again @KeroroLulu!
