### ISSUE TITLE
Language server startup errors without a stack trace should not keep terminal open

### ISSUE THREAD

**Issue by Bill-Stewart** [PowerShell/vscode-powershell#572]
Still giving an error when using PowerShell 2.0. Information box says:

    Error  Could not start language service:

Log data:

    powershell.exe started --
        pid: 544
        exe: C:\Windows\Sysnative\WindowsPowerShell\v1.0\powershell.exe
        args: C:\Users\<username>\.vscode\extensions\ms-vscode.PowerShell-0.10.0\scripts\Start-EditorServices.ps1 -EditorServicesVersion '0.10.0' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '0.10.0' -BundledModulesPath 'C:\Users\<username>\.vscode\extensions\ms-vscode.PowerShell-0.10.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\<username>\.vscode\extensions\ms-vscode.PowerShell-0.10.0\logs\1489695383-e4f9b666-4c44-4c37-819c-6f08c3b1a0671489695377337\EditorServices.log' -SessionDetailsPath 'C:\Users\<username>\.vscode\extensions\ms-vscode.PowerShell-0.10.0\sessions\PSES-VSCode-31532' 
    
    powershell.exe terminated or terminal UI was closed
    
    Could not start language service: 
    Timed out waiting for session file to appear.

**Comment by daviwil** [comment]
You're a little ahead of me :)  I just shipped 0.10.1 with the fix for this, let me know if it's fixed for you now.

**Comment by daviwil** [comment]
Going to close this now since it should be fixed, if you find that it's not I am happy to reopen it :)

**Comment by Bill-Stewart** [comment]
Thanks!

Is there any way to hide the error info box, though?

**Comment by daviwil** [comment]
Which one, the one at the top of the screen, or the box at the bottom which would have been the integrated console?  If the one at the bottom, I will make that one go away automatically in cases where there's no error message to be copied.

**Comment by Bill-Stewart** [comment]
The error box at the top of the screen:

![image](https://cloud.githubusercontent.com/assets/22036935/24058176/b77709f6-0b0f-11e7-9226-3123368ccb99.png)

Displaying it once is fine, but it would be nice to be able to disable this message.

The "initialization error" at the bottom also persists. Perhaps a single option could disable both? Or have an option that enables the language highlighter only?

**Comment by daviwil** [comment]
Yep, good point.  I think I'll add a new setting to disable the language server completely, that would prevent you from ever seeing that error again.  Someone else just asked for that feature in #580 so I'll fix that there.

**Comment by zhoufwind** [comment]
Hi, still got this error all the time, looking forward to hide it, thanks!
`[11:45:18] Language server starting...
powershell.exe started --
    pid: 8078
    exe: /usr/local/bin/powershell
    args: /Users/<username>/.vscode/extensions/ms-vscode.powershell-1.2.1/scripts/Start-EditorServices.ps1 -EditorServicesVersion '1.2.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.2.1' -BundledModulesPath '/Users/zhoufeng/.vscode/extensions/ms-vscode.powershell-1.2.1/modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath '/Users/<username>/.vscode/extensions/ms-vscode.powershell-1.2.1/logs/1496979918-009b2400-1b81-4659-a41e-04cda0ee56f41496979900311/EditorServices.log' -SessionDetailsPath '/Users/<username>/.vscode/extensions/ms-vscode.powershell-1.2.1/sessions/PSES-VSCode-563-237610' -FeatureFlags @()


[11:46:18] Language server startup failed.
Could not start language service: 
Timed out waiting for session file to appear.

powershell.exe terminated or terminal UI was closed`

**Comment by daviwil** [comment]
@zhoufwind do you have any additional logs that might indicate what issue you are experiencing?  Follow these steps and see if an EditorServices.log file gets created:

https://github.com/PowerShell/vscode-powershell#reporting-problems

**Comment by pythoninthegrass** [comment]
Hi @daviwil. I emailed you my logs from my Napster work address. I'll be happy to help test with whatever you'd like to try. Also, forgot to mention my environment is OS X 10.10.5, VSCode 1.13.1.

Thanks for your help!

**Comment by TylerLeonhardt** [comment]
The whole point of the PowerShell extension is the language server... so I'm going to go ahead and close this.

I think we've come a long way since the original issue was opened. If there's anything else in this thread that you'd like to see still, let us know.
