### ISSUE TITLE
UNC path and tab completion

### ISSUE THREAD

**Issue by pchalabi** [PowerShell/vscode-powershell#574]
### System Details

- Operating system name and version: Win10 x64 -build 14393
- VS Code version: 1.10.2
- PowerShell extension version:  0.10.1
- Output from `$PSVersionTable`:
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description
Something I noticed when using tab completion while using a UNC path:
\\servername\folder\<tab here>
Returns:
\servername\folder\2ndfolder

Tested with Tab Return and Click.  I also tried uninstall of powershell extension and reloading it.  Same issue.

**Comment by mpearon** [comment]
I encountered this same behavior, and opened an issue, which received a response.
[#681](https://github.com/PowerShell/vscode-powershell/issues/681)

**Comment by daviwil** [comment]
Hey @pchalabi, sorry for missing this issue in the past.  I'm tracking this issue on #681 with plans to fix it for the next release.  Will close this issue now, please subscribe to the other issue to be notified when the issue gets resolved.

**Comment by mpearon** [comment]
Hey, @pchalabi - there is good news!  1.13.0 corrected this behavior!

**Comment by daviwil** [comment]
Awesome!  Thanks for confirming Matthew!
