### ISSUE TITLE
Adding an exception to the 'newLineAfterCloseBrace' setting

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#576]
### System Details

- Operating system name and version: MacOS Sierra
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.1
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.15
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I like the newLineAfterCloseBrace setting but I'd rather it not apply all the time. For example, in the scenario where I'm using a `where` or `foreach` method.  https://www.screencast.com/t/KFWP9dDE66z0

This is how I'd like it to format:
```
@().foreach({

})
```

However, this is how it does:
```
@().foreach({

    })
```

You can see that a bracket ending with a new line isn't always involved with a control statement.

**Comment by DarkLite1** [comment]
Same issue here and I was almost filing a new issue until GitHub suggested it existed already. Verry annoying formatting:

![image](https://user-images.githubusercontent.com/10828570/54030306-79c9eb80-41ab-11e9-9e95-e9657e70dd53.png)


```
Version: 1.33.0-insider (user setup)
Commit: 9b849d9de7168eb4f685823bf9b9e27a0a8dae74
Date: 2019-03-08T06:59:35.464Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.2.9200
```

**Comment by rkeithhill** [comment]
All of the formatting features are provided by the PSScriptAnalyzer.  If this issue hasn't already  been submitted to that project, please submit it there where the PSSA owners will see it.  https://github.com/powershell/psscriptanalyzer

**Comment by DarkLite1** [comment]
Thank you @rkeithhill , opened a new [issue here](https://github.com/PowerShell/PSScriptAnalyzer/issues/1168) as you suggested.

**Comment by bergmeister** [comment]
@DarkLite1 I will take a look at this issue tonight (by looking at it I think it might already be fixed in the next upcoming version of PSSA). I think we can close this issue now that the issues has been moved to PSSA
