### ISSUE TITLE
Feature request: full size terminal

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/vscode-powershell#577]
I'd love to see a way to have the integrated terminal panel be "full screen" and be able to toggle between a "full screen" editor and console like I can in the ISE. I'm not talking about the full screen app, just the editor and terminal panels. I can close the terminal to get a "full" editor, but there's no way hide the editor without manually resizing panels.

**Comment by daviwil** [comment]
VS Code provides a command for this "View: Toggle Maximized Panel".  You can bind that to a hotkey and then toggle maximized state on and off at will.

**Comment by rkeithhill** [comment]
See the ctrl+shift+q binding here https://gist.github.com/rkeithhill/30c35f023c074392fd59793c9e30a2ae

**Comment by jdhitsolutions** [comment]
That sort of works. I have that key binding. It doesn't fully hide the editor, which I suppose I could live with.  Of course once the terminal panel is maximized I haven't found a key combination or series to minimize it and make the editor full panel. I may just have to experiment with custom key bindings.

**Comment by dotps1** [comment]
and it would be super duper awesome if you could actually pop the terminal out.  Like you can with ISESteriods.  be able to edit on one monitor and have it execute on the other.

**Comment by rkeithhill** [comment]
@dotps1 You should make that request on the https://GitHub.com/Microsoft/vscode repo.

**Comment by dotps1** [comment]
https://github.com/Microsoft/vscode/issues/15038 I guess the pop out console has already been requested.

**Comment by rkeithhill** [comment]
> That sort of works. 

Jeff, that is the best we can do with VSCode AFAIK but come 'on that's pretty good, right?  :-)   Seriously, if you'd like to see the ability to fully maximize the panel you should submit an issue on https://github.com/microsoft/vscode

>  I haven't found a key combination or series to minimize it 

You can toggle the panel on/off with <kbd>Ctrl</kbd>+<kbd>J</kbd>.

**Comment by rkeithhill** [comment]
Given that the PowerShell extension can't provide what you're asking for (only VSCode can), I'm closing this issue.   If you feel I've closed this in error, you can re-open it.
