### ISSUE TITLE
Allow customization of powershell.scriptAnalysis in settings.json

### ISSUE THREAD

**Issue by ChrisLynchHPE** [PowerShell/vscode-powershell#578]
### System Details

- Operating system name and version: 10.15060.RS2
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.1
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.15060.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15060.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I would like the ability to control the script analysis engine to ignore certain conditions.  For instance, I use `%` instead of `ForEach-Object` or `?` instead of `Where-Object`.  I really do not want to go back and change those values.  Yet, I would like to be warned if I have a `[CmdletBinding()]` declaration, the Cmdlet Verb is `Remote` and am say missing `$PSCmdlet.ShouldContinue()` in my function or missing the `SupportsShouldProcess` parameter in the `[CmdletBinding()]` declaration.

### Attached Logs

Do you need logs?

**Comment by daviwil** [comment]
That's what the [`powershell.scriptAnalysis.settingsPath`](https://github.com/PowerShell/vscode-powershell/blob/develop/examples/.vscode/settings.json#L4) setting is for.  Take a look at this example settings file for an example of how to configure PSScriptAnalyzer rules:

https://github.com/PowerShell/vscode-powershell/blob/develop/examples/PSScriptAnalyzerSettings.psd1

You can remove any rule you don't want to use from the list in that file.

**Comment by rkeithhill** [comment]
Open the examples that come with the PS ext via "open examples" command in command palette. Look at PSScriptAnalyzerSettings.psd1 and .vscode\settings.json file. The former allows you to control pssa rules including alias whitelist.

**Comment by ChrisLynchHPE** [comment]
Ah...  I wasn't aware of this.  So, I just create and place the `PSScriptAnalyzerSettings.psd1` file into the root directory where my module resides that contains 'PSAvoidUsingCmdletAliases` in the `ExcludeRules` section?  I don't want to have to whitelist all Cmdlet aliases.

**Comment by daviwil** [comment]
Yep, you can use ExcludeRules.  The fields in the .psd1 correspond with the parameters to Invoke-ScriptAnalyzer.

**Comment by ChrisLynchHPE** [comment]
Thanks!
