### ISSUE TITLE
IntelliSense results for command names should be sorted alphabetically

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#579]
The ISE sorts IntelliSense results alphabetically.  The PowerShell extension should be consistent with that.

/cc @dotps1

**Comment by rkeithhill** [comment]
What sort of IntelliSense?  For instance ISE does not alpha-sort parameters e.g.:
![image](https://cloud.githubusercontent.com/assets/5177512/24067558/79be4c5e-0b4c-11e7-8902-ce69e624f8cf.png)
The common parameters go at the end and even then the non-common parameters aren't sorted alphabetically.  I think it puts the required parameters at the top of the list (perhaps sorting on position?).

FWIW parameters used to be sorted alphabetically and we got complaints so we changed the order to be like ISE as described above.

**Comment by daviwil** [comment]
I was referring to command name IntelliSense, glad that you clarified that.

**Comment by rkeithhill** [comment]
Ah yeah, the command list could be sorted better.  I wish VSCode had support for Intellisense filtering like VS 2017 has now. I could easily see having a filter for applications vs cmdlets/functions vs scripts.

**Comment by daviwil** [comment]
Yeah, that would be pretty handy.  I would guess they'll get around to something like that eventually, seems like most features are only a matter of time ;)
