### ISSUE TITLE
Extension install path in docs needs to include version

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#58]
Both the README.md and the contents of the VSCode Marketplace page for this extension (https://marketplace.visualstudio.com/items/ms-vscode.PowerShell) should include a placeholder for the version number e.g. `c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell-<ext_version>\examples`.

**Comment by daviwil** [comment]
Is this a new folder convention that they're introducing?  I haven't seen that before

**Comment by rkeithhill** [comment]
That's what I see when I've installed later versions of the extension on both 0.10.5 and 0.10.6 e.g.:
```
C:\Users\hillr\.vscode\extensions\ms-vscode.PowerShell-0.3.1
```
Makes sense in that it would solve the issue of installing a newer version of an extension while the current version is loaded.

**Comment by daviwil** [comment]
Hah, so that's how they decided to solve that problem. Works for me!
