### ISSUE TITLE
Feature Request: Ability to run highlighted code via right-click?

### ISSUE THREAD

**Issue by cobdev** [PowerShell/vscode-powershell#581]
### System Details

- Operating system name and version: Windows 10 Enterprise v1607
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.1
- Output from `$PSVersionTable`:
PSVersion                      5.1.15061.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15061.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Request Description

In addition to hitting F8 to run the currently highlighted code, could we have the ability to right-click and select an option to run the code as well?  Similar to PowerShell ISE's option? (See Attached)

![2017_03_17_14_27_27_greenshot](https://cloud.githubusercontent.com/assets/10552026/24064039/9bdcc6da-0b1f-11e7-9e9a-97d043a2bb4d.png)

**Comment by daviwil** [comment]
Yep, I can add that.

**Comment by cobdev** [comment]
Thank you sir! :)

**Comment by jboeshart** [comment]
+1 to this, and any chance we could get a couple buttons added to the PowerShell terminal window as well, similar to the ISE? One for run script and one for run selection?

**Comment by daviwil** [comment]
Unfortunately I can't manipulate the terminal window UI so adding new buttons won't be likely.  I'll add the context menu items for the next release, though.

**Comment by jboeshart** [comment]
No prob, worth an ask. Having the context menu items will be great though. Thanks for the work on this!

**Comment by daviwil** [comment]
Adding a screenshot for the changelog:

![image](https://cloud.githubusercontent.com/assets/79405/24670885/a18513fe-1924-11e7-91d3-dc14c6cbfad9.png)
