### ISSUE TITLE
Create comprehensive User Guide for 1.0 release

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#584]
We need a comprehensive User Guide that will bring a new user up to speed and help familiar users learn how to use more advanced features.

**Comment by jmiller76** [comment]
@daviwil Do you want this guide as a bridge from console/ISE to VSCode?

I started a .MD for a usergroup meeting two weeks ago. I was skimming the VSCode docs for things that I thought would be relevant to the group.  Including some of the in progress issues.

Mostly this is key combinations and links to other documentation, as it was more talking points.  It may make a good enough starting point though.

**Comment by daviwil** [comment]
@jmiller76 both an ISE migration guide and a general guide to using VS Code for PowerShell development if you've never used a PowerShell editor before.  I would love to have some contributions from the work you've done already!  I'm planning to merge the initial frame of the document today, would you like to send a PR to fill in some gaps with your info at some point?

**Comment by jmiller76** [comment]
@daviwil , I'm glad to add what I can.
Are you updating vscode-powershell/docs/UserGuide.md from the  user-guide branch?

**Comment by SydneyhSmith** [comment]
Closing as we have documented a migration guide from ISE to VSCode
