### ISSUE TITLE
"Run Selected" Fails to Execute in v0.2.0

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/vscode-powershell#59]
Side-loaded the v0.2.0 release for testing and experimentation today.  Have noticed that the F8 functionality ceases to work and the output window for PowerShell is unavailable.

**Comment by daviwil** [comment]
I was noticing this problem as well so I fixed it in 0.3.1.  We'll keep this open until you have that version and verify it works for you :)

**Comment by daviwil** [comment]
Hey Michael, have you tried Run Selected in the latest releases to see if it works for you?  If so we can close this issue :)

**Comment by tylerl0706** [comment]
I'm going to close this since David fixed it and this thread has been quiet. Feel free to open a new issue if you're still having trouble!
