### ISSUE TITLE
Sort Editor Commands by the -Name parameter.

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#591]
_From @gerane on June 5, 2016 17:4_

I think it makes sense to sort Editor Commands by their `Name` instead of their `DisplayName`. Since `Name` includes a Prefix for the module name or similar, it will group all commands with the same prefix together. 

Since this might also change what a user sees, I think showing both `Name` and `DisplayName` would be beneficial. I am unsure of what Code gives you access to in the command palette lists, but the PromptForChoice options have the option of displaying a slightly dimmed Message to the right of the Choice. Here is an example from Plaster.

![Plaster](https://raw.githubusercontent.com/gerane/PowerShell/master/Images/prompt.png)

One option that I like, would be to display the `Name` on the left, and then the `DisplayName` dimmed on the right in the Editor Command list. Though, this may change if you change around where Editor Commands are listed. I know normal command at the Extension label have the far right area for keybindings, so unsure if they have the option to have a dim description. You could also do something like

```
MyModule.MyCommand - Does really cool stuff
MyModule.DoesAwesome - Does Awesome stuff
MyModule.DoesSuper - Does Super stuff
YourModule.YourCommand - Does some other Module's stuff
```

_Copied from original issue: PowerShell/PowerShellEditorServices#250_

**Comment by daviwil** [comment]
_From @gerane on February 23, 2017 16:46_

@daviwil is there any update on your plans for this or similar features like #246 or some of the related things we have spoken about? I hadn't talked to you about it in a while so figured I'd ask to see if any of the newer things you have been working on might impact this.

It is getting increasingly harder to use the editor commands I want to use most or use most often. I'd like to be able to force the top 3 or do something that I can have my most used at the top. 

As I move more and more of my commands into modules, it makes it incredibly hard to control the order of the commands in the menu. They just show up in the order they are imported atm, and if they are being extracted from the vscode profile to modules, this becomes much more difficult to control.

**Comment by daviwil** [comment]
I'm fixing this on the vscode-powershell side because PSES only sends an event when a new command is added, not a whole list.  It'll come out with the next update.

**Comment by gerane** [comment]
Nice,  I can never decide which repo to open issues on 😀

**Comment by daviwil** [comment]
Heh, well in this case I didn't know where the fix would be until I started working on it ;)
