### ISSUE TITLE
Powershell extension consumes full core of CPU when formatting

### ISSUE THREAD

**Issue by latkin** [PowerShell/vscode-powershell#595]
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.10.2
- PowerShell extension version: 0.10.1
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
WSManStackVersion              3.0
CLRVersion
SerializationVersion           1.1.0.1
PSEdition                      Core
BuildVersion                   3.0.0.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.15
```

### Issue Description

If I open a powershell script and make a few edits, I get a message "Formatting PowerShell document..." spinning forever in the footer of VS Code

![image](https://cloud.githubusercontent.com/assets/5943573/24156154/00ef5aba-0e13-11e7-9506-dcc4ad9a7b1a.png)

Meanwhile, the powershell process which is powering the editor features consumes a cull core of CPU:

![image](https://cloud.githubusercontent.com/assets/5943573/24156302/6d45269a-0e13-11e7-8623-59096b9530ac.png)

### Attached Logs

`EditorServices.log` is over 300MB at this point, so hopefully something relevant in there. Do you have a suggested way to share? Or maybe I can just let it run for a few seconds to generate 5-10MB of logs.

**Comment by daviwil** [comment]
Hmmm, it shouldn't get hung like that.  Capturing a shorter log file would be helpful, you can e-mail it to me at `daviwil at microsoft.com`.

In the meantime, you could turn off `editor.formatOnType` for all languages or just for for PowerShell in your user settings:

```json
"[powershell]": {
    "editor.formatOnType": false
}
```

**Comment by latkin** [comment]
Just emailed logs from a short session.  Issue repros 100% for me - CPU starts spinning when editing any ps1 script.

**Comment by daviwil** [comment]
Got it!  Thanks.
