### ISSUE TITLE
Replace Script Aliases

### ISSUE THREAD

**Issue by guidooliveira** [PowerShell/vscode-powershell#598]
One of the things i like in ISE Steroids is the ability to remove Aliases and replace it with the proper cmdlet name, and it's parameters, it'd be a huge game changer for me if VSCode had this feature with the powershell extension.

**Comment by rkeithhill** [comment]
This is supported in two ways.  First, you can run a command `PowerShell: Expand Alias` to invoke this operation on all command aliases.  Second, and more flexible, is to let VSCode squiggle aliases in your script, you can then click on the Code Fix icon and have it replace the alias:
![image](https://cloud.githubusercontent.com/assets/5177512/24171962/21264ad0-0e4c-11e7-9e27-bdbb3e113f75.png)
The nice thing about the latter approach is that you can configure a PSScriptAnalyzerSettings.psd1 file in your workspace which will allow you to whitelist certain aliases.  Perhaps you're OK with `cd`, `pushd` and `popd` for instance. Those can be put in the whitelist.

**Comment by guidooliveira** [comment]
Thank you Keith, i wasn't aware of that

**Comment by daviwil** [comment]
Guido, let us know if you run into any problems with these methods of expanding aliases and we'll be happy to reopen the bug.  Thanks!
