### ISSUE TITLE
PowerShell integrated Console - version no.

### ISSUE THREAD

**Issue by rebornix** [PowerShell/vscode-powershell#599]
_From @lw-schick on March 22, 2017 13:4_

Description
-------------

I can't import the PowerShell module [SSASCMDLETS](https://msdn.microsoft.com/en-us/library/hh213141.aspx) from SQL Server Analytics Service.

Steps to Reproduce:
-----------------------
- VSCode Version: 1.10.2
- OS Version: Windows 7 64x

1. Install SQL Server with Analytics Service
2. Run Import-Module [SSASCMDLETS](https://msdn.microsoft.com/en-us/library/hh213141.aspx)

Results in:
-----------
``` powershell
PS C:\myfolder> Import-Module SQLASCMDLETS
Import-Module : The current Windows PowerShell host is: 'Visual Studio Code Host' (version 0.10.1). The module 'C:\Program Files (x86)\Microsoft SQL
Server\110\Tools\PowerShell\Modules\SQLASCMDLETS\SQLASCMDLETS.psd1' requires a minimum Windows PowerShell host version of '1.0' to run.
At line:1 char:1
+ Import-Module SQLASCMDLETS
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...LASCMDLETS.psd1:String) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_InsufficientPowerShellHostVersion,Microsoft.PowerShell.Commands.ImportModuleCommand

PS C:\myfolder>
```

The PSVersionTable looks OK:
``` powershell
PS C:\myfolder> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\myfolder>
```

_Copied from original issue: Microsoft/vscode#23017_

**Comment by rebornix** [comment]
It's very likely a Powershell issue, please file against the powershell extension you are using :)

**Comment by daviwil** [comment]
This seems like an unnecessary limitation of the SQL module, it is throwing an error because the `$host.Version` reported inside of the Integrated Terminal is below 1.0.  I'm reluctant to bump our host version to 1.0 just to make the SQL module happy but I doubt they'd be able to respond to this in the short term to unblock you.  I'll fix it for 0.11.0, coming out later today.

**Comment by lw-schick** [comment]
Thanks @daviwil

**Comment by daviwil** [comment]
@lw-schick did the 0.11.0 update fix it for you?

**Comment by lw-schick** [comment]
Yes:
``` powershell
Starting PowerShell...

PS C:\git\OlapDbMetaData> Import-Module SQLASCMDLETS
PS C:\git\OlapDbMetaData>
```

now all is fine

**Comment by daviwil** [comment]
Great, thanks for confirming!

**Comment by szhivotovsky** [comment]
Ran across this closed case. I'm running into the same issue with a different module. I'm on v0.12.2.

import-module : The current Windows PowerShell host is: 'Visual Studio Code Host' (version 1.0.0). The module
'/usr/local/microsoft/powershell/6.0.0-alpha.18/Modules/Okta-PSModule-master/Okta.psd1' requires a minimum Windows PowerShell host version of '3.0' to run.
At line:1 char:1

PS /usr/local/microsoft/powershell/6.0.0-alpha.18/Modules> $host

Name             : Visual Studio Code Host
Version          : 1.0.0

Can anything be done here? Thanks!

**Comment by daviwil** [comment]
@szhivotovsky Do you know why the module is looking for a specific host and host version?  That seems like a bad idea in general because it prevents that module from being loaded in any other host.  Can you ask the module author to loosen their check?

**Comment by vikashdaya** [comment]
@szhivotovsky ... found this while looking for the same issue.
If you change the version of the host in the Okta.psd1 file to 1.0, the module with load and work...
 
# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = '1.0'

**Comment by jschmitter** [comment]
@daviwil Are you saying that to use the vs code powershell debugger I need to make all my powershell modules backwards compatible with PowerShell v 1?  I must be misunderstanding something.

I'm experiencing the same issue, and definitely can't decrease the minimum version of my powershell modules.

**Comment by tylerl0706** [comment]
@jschmitter 

> backwards compatible with PowerShell v1? 

that's not quite right. The version of PowerShell itself, and the version of the host represents 2 different things.

A good example of this is... Open actual pwsh.exe (or powershell.exe) and type `$Host.Version`. Then open the vscode PowerShell extension's PowerShell Integrated Console and to the same. They're different - yet both are using the same version of PowerShell.

The "host version" is just the version of the thing that's giving you access to PowerShell otherwise known as the host.

There's a line of code in the extension that [sets the host version](https://github.com/PowerShell/vscode-powershell/blob/master/src/session.ts#L74). As David said before, we don't necessarily want to have to change this just for a specific module to work...

What do your modules want it to be set to?

**Comment by SeeminglyScience** [comment]
@jschmitter `PowerShellHostVersion` does not refer to the PowerShell version, it refers the version of the external host stored by `$Host`.  In a normal session this is typically the engine's host `ConsoleHost`.  However, other applications can supply their own `PSHost` implementations to supply custom logic for things like prompting the user.

Honestly the idea of manifest field `PowerShellHostVersion` would only make sense if it wasn't possible to write a custom host, or if the intention when using it is to target a specific custom host only.  `PowerShellHostVersion` just shouldn't be used unless you are explicitly not supporting custom hosts, which I can't think of a reason to do.

If you are aiming to declare a minimum version of PowerShell, use `PowerShellVersion` instead.

**Comment by rjmholt** [comment]
For reference, our host version *is* the extension version:
https://github.com/PowerShell/vscode-powershell/blob/bb545ab75ab4ffa9f12213924235b09944e95d90/src/session.ts#L74-L79
