### ISSUE TITLE
PowerShell F5 doesn't set current working directory to file or folder path, you end up in the extension directory

### ISSUE THREAD

**Issue by codemonkeychris** [PowerShell/vscode-powershell#6]

**Comment by daviwil** [comment]
Good point, I think this is a bug on my part.  I'll get this fixed.

**Comment by daviwil** [comment]
I think we're good on this now in the 0.4.1 release.  As a bonus, if you ever want a different working directory open your launch.json file and set the 'cwd' parameter to any path.  Closing this for now, let me know if you run into any trouble with the new release.  Thanks!
