### ISSUE TITLE
Debugging doesn't work when the script requires parameters

### ISSUE THREAD

**Issue by clazette** [PowerShell/vscode-powershell#60]

**Comment by daviwil** [comment]
Hi clazette, I could have sworn there was a bug filed for this already but I wasn't able to find it.  Either way, you're right, this is a missing feature at the moment.  Will look into getting it added soon.  Thanks!

**Comment by clazette** [comment]
I looked for it as well before opening a new issue. Thanks for the response. Take care.

**Comment by sameer-kumar** [comment]
I logged-in to log an issue for the same but realized that there is already a one :-)
My script starts with **[CmdletBinding()] param()** and debugging doesn't work.
Thanks for considering this in future release! :+1:

**Comment by daviwil** [comment]
I'm making some changes right now that may actually enable this in a basic way.  When you run a script that requires parameters to be entered, it causes prompts to show up in the console.  I'm currently finishing up an implementation of this prompting mechanism in the debug console.  This should allow you to run/debug your script though we don't yet have a way to set those parameters before running the script.

**Comment by rkeithhill** [comment]
> we don't yet have a way to set those parameters before running the script.

I believe we just might have a way to do that now.

**Comment by daviwil** [comment]
Ahhh, I knew there was another issue filed for this already!  Check out https://github.com/PowerShell/vscode-powershell/issues/24

We're looking into fixing this bug for next week's release, keep an eye on that issue :)  I'll close this one for now.
