### ISSUE TITLE
Extension should support running in constrained language mode

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#606]
Right now we show an error message on startup of constrained language mode is turned on via AppLocker policy.  We should do the necessary work to make the extension operate at some level with this mode turned on.  The PowerShell ISE supports it.

**Comment by caparkaya** [comment]
Hello, is there an established roadmap, plan for this?

**Comment by tylerl0706** [comment]
Closing this in favor of #754

**Comment by rjmholt** [comment]
I'm doing work now to move PSES over to a binary module to make this easier, but it looks like there are still issues because of how PSReadLine works. I'm not sure if those are the only issues, but that's the current blocker; we invoke a PSReadLine static method in PowerShell script directly for the prompt. So to enable constrained language mode, that's the next issue to solve.

**Comment by rjmholt** [comment]
Another facet here is that we have dependencies that aren't signed:

```
> ls .\module\PowerShellEditorServices\bin\Common\ | Get-AuthenticodeSignature | ? Status -eq 'NotSigned' | ft Status,Path

   Status Path
   ------ ----
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\MediatR.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\MediatR.Extensions.Microsoft.DependencyInjectio…
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\Microsoft.PowerShell.EditorServices.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\Newtonsoft.Json.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\OmniSharp.Extensions.DebugAdapter.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\OmniSharp.Extensions.DebugAdapter.Server.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\OmniSharp.Extensions.JsonRpc.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\OmniSharp.Extensions.LanguageProtocol.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\OmniSharp.Extensions.LanguageServer.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\Serilog.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\Serilog.Extensions.Logging.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\Serilog.Sinks.Async.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\Serilog.Sinks.Console.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\Serilog.Sinks.File.dll
NotSigned C:\Users\roholt\Documents\Dev\PowerShellEditorServices\module\PowerShellEditorServices\bin\Common\UnixConsoleEcho.dll
```

**Comment by TylerLeonhardt** [comment]
@rjmholt I believe there's a way for us to sign things as "external deps" but need to do the research.

**Comment by romero126** [comment]
Has there been any additional update on this? I am fairly interested in a desirable outcome from this.

**Comment by TylerLeonhardt** [comment]
We talked offline but to capture it here as well...

First comment out this line so you can actually test this:
https://github.com/PowerShell/PowerShellEditorServices/blob/d8fc936bea002b897046e6e4952ae2c837216aa8/src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs#L190

Then see where it breaks with ConstrainedLanguage mode turned on...

Here is a good list to start:​​​​
![image](https://user-images.githubusercontent.com/2644648/72922512-0321d800-3d02-11ea-8ea9-56df56a47e1b.png)

These are hits for `]::` in PowerShellEditorServices. Any method invocations will have to either be done a different way, or wrapped in a binary cmdlet.

**Comment by dkattan** [comment]
Has anyone started working on this? I'd also love for this to work and can contribute if there is an existing branch.

**Comment by TylerLeonhardt** [comment]
Hi @dkattan I don't think anyone is actively working on this. Are you interested in getting involved?

My steps in the comment above yours are still accurate. The way I'd approach this is:

* uncomment the code I mention above
* try to start up with constrainedlanguage mode
* see what goes sideways and try to fix them

You're more than willing to drop any questions you have here.

Once start up works, we can get a PR out to support this... then we can start filling in what doesn't work (like the expand alias feature, remoting feature etc)

**Comment by TylerLeonhardt** [comment]
ConstrainedLanguage mode is now supported in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension.

**Comment by craig-martin** [comment]
Exciting!  This should allow us to use it on admin workstations where constrained language mode is enforced.

**Comment by nyannios** [comment]
Well add me to this too!   The security gestapos have everything locked up here and I am getting this too
[ ](url
![Untitled](https://user-images.githubusercontent.com/8931200/87862416-d3086a00-c91d-11ea-8067-e11333878f1b.png)
)

**Comment by TylerLeonhardt** [comment]
@nyannios what version of PowerShell are you using? The PowerShell extension only supports v5.1 and higher.

**Comment by nyannios** [comment]
Hey, I downloaded and installed PowerShell 7 for windows and now it's working!    Thanks!    I was on 4.0
