### ISSUE TITLE
Debugger steals console focus, output overwrites prompt when stepping quickly

### ISSUE THREAD

**Issue by mattmcnabb** [PowerShell/vscode-powershell#609]
### System Details

```
PS > code -v
1.10.2
8076a19fdcab7e1fc1707952d652f0bb6c6db331

PS > $pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
0      11     0      0

PS > code --list-extensions --show-versions
alefragnani.project-manager@0.13.5
chriseckenrode.vscode-chester-atom@0.1.7
ms-vscode.csharp@1.8.0
ms-vscode.PowerShell@0.11.0
robertohuertasm.vscode-icons@7.4.0


PS > $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When I try to use the debug commands in the PowerShell Integrated Terminal, the cursor skips between the Terminal Window and the Editor. So I type 's', the press Enter and it steps through one line, then places the cursor on the previous line of code in the editor. If I press 's' again it enters the character into my script rather than the Terminal.

Also noticed some display issues in the terminal when debugging and pressing F11 several times rapidly. Rendering the prompt was delayed after each keypress, and it resulted in some of the prompt lines overlapping, so when I tried to type a command in the Terminal it was entering characters over top of the prompt lines.

Thanks!

**Comment by daviwil** [comment]
Thanks for reporting the focus jumping issue, I need to file a bug on the VS Code team about that.  Haven't seen the prompt overwrite issue yet but I think some changes I'm making for the next release should handle that.

**Comment by daviwil** [comment]
Filed this bug to track the focus issue: https://github.com/Microsoft/vscode/issues/23117

**Comment by pcgeek86** [comment]
This is also happening when I hit F8 to run the "current line" in the PowerShell Extension. The Integrated Terminal is capturing focus, so I have to click back into my code in order to continue working.

**Comment by daviwil** [comment]
@pcgeek86 you can use this setting to control that behavior: `"powershell.integratedConsole.focusConsoleOnExecute": false`

**Comment by rkeithhill** [comment]
Bummer, the defaults for both debug and run selection are exactly the opposite of what you'd expect.  Hopefully, the VSCode team can fix the debug case.

**Comment by daviwil** [comment]
At least in our case for F8, it's on by default due to accessibility reasons.  I have been told that the focus needs to move to wherever an action's resulting activity is taking place in case the user is using a screen reader.

**Comment by rkeithhill** [comment]
Ah. I guess there is no way to detect if a screen reader is being used?

**Comment by brwilkinson** [comment]
@daviwil Please make the following the default setting.

"powershell.integratedConsole.focusConsoleOnExecute":false

People mostly use the ISE environment and this is a show stopper for developing scripts until you set this to false.

**Comment by daviwil** [comment]
@brwilkinson unfortunately I can't, I was told that it must change focus by default for accessibility reasons.

**Comment by brwilkinson** [comment]
@daviwil oh wow. That seems odd. . . . did you know the details?

**Comment by SydneyhSmith** [comment]
Closing as this should be fixed in our latest release.
