### ISSUE TITLE
Validator attributes not suggested through intellisense

### ISSUE THREAD

**Issue by bgelens** [PowerShell/vscode-powershell#613]
### System Details
```powershell
code -v
1.10.2
8076a19fdcab7e1fc1707952d652f0bb6c6db331

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
0      11     0      0

code --list-extensions --show-versions
ms-vscode.PowerShell@0.11.0

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with completing parameter validator attributes (e.g. ```[ValidateNotNullOrEmpty()]``` on a string parameter). 

```powershell
function foo {
    param (
        [Vali]
        [string] $Name
    )
}
```
When I try ctl+space, I get no suggestion. This is also the case within DSC Class attributes on DscProperties.

**Comment by ThePSAdmin** [comment]
I hade this exact same problem, literally 5 minutes ago, but with parameter attributes (i.e ValueFromPipeline). I changed focus to another file in my project, then went back and it was suddenly working again.

**Comment by daviwil** [comment]
Thanks guys!  I'll take a look for next week's patch update.

**Comment by SydneyhSmith** [comment]
From our testing looks like this is no longer an issue, will close as resolved.
