### ISSUE TITLE
The Debug Console is no longer used for PowerShell debugging.

### ISSUE THREAD

**Issue by Norbert88** [PowerShell/vscode-powershell#615]
### System Details

- Operating system name and version: Win Server 2012R2
- VS Code version: 1.10.2
- PowerShell extension version: 0.11.0
- Output from `$PSVersionTable`: 

```
1.10.2
8076a19fdcab7e1fc1707952d652f0bb6c6db331

Major  Minor  Build  Revision
-----  -----  -----  --------
0      11     0      0

azemoh.one-monokai@0.2.4
casualjim.theme-desertex@0.0.6
DavidAnson.vscode-markdownlint@0.7.1
donjayamanne.githistory@0.2.0
donjayamanne.python@0.6.0
felipecaputo.git-project-manager@1.2.1
gerane.Theme-azure@0.0.2
gerane.Theme-Bliss@0.0.2
gerane.Theme-Eden@0.0.2
gerane.Theme-FlatDark@0.0.2
gerane.Theme-Hail@0.0.3
gerane.Theme-peel@0.0.2
gerane.Theme-TwoStones@0.0.2
ivanzusko.theme-chrome-devtools-dark@0.0.1
LaurentTreguier.vscode-simple-icons@1.0.1
mphasiswyde.ewamvscadaptor@0.3.4
ms-vscode.cpptools@0.10.5
ms-vscode.PowerShell@0.11.0
robertohuertasm.vscode-icons@7.4.0
sharksym.theme-cobalt0@0.0.5
superzadeh.theme-solarized-obsidian@0.0.8

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

This is my first time submitting an issue. I apologize in advance if I had missed anything. I did not get this error message prior to updating the PowerShell extension 0.11.0. When I try to debug my script the Debug Console spits out; The Debug Console is no longer used for PowerShell debugging.  Please use the 'PowerShell Integrated Console' to execute commands in the debugger.  Run the 'PowerShell: Show Integrated Console' command to open it.

In addition, I noticed that when I launch VS Code, PowerShell loads twice;

Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

Starting PowerShell...

launch.json, see below ;

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "Get-Templates",
            "script": "${workspaceRoot}/lib/Get-Templates.ps1",
            "args": [],
            "cwd": "${workspaceRoot}"
        }
    ]
}

settings.json, see below;

{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\SysNative\\WindowsPowerShell\\v1.0\\PowerShell.exe",
    "window.zoomLevel": 0,
    "git.confirmSync": false,
    "workbench.welcome.enabled": true,
    "workbench.iconTheme": "simple-icons",
    "[cpp]": {
        "editor.quickSuggestions": false
    },
    "[c]": {
        "editor.quickSuggestions": false
    }
}

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Hey Norbert, as you might have noticed that message is there to guide you to use the new PowerShell Integrated Console instead of the Debug Console.

Regarding the double-terminal issue, I've filed an issue with the VS Code team about they need to provide us a way to deal with this issue.
