### ISSUE TITLE
Debugger does not show column indicator when stopped at a breakpoint

### ISSUE THREAD

**Issue by grumpkin** [PowerShell/vscode-powershell#616]
### System Details

- Operating system name and version: Windows 10 - 1607
- VS Code version: 1.9.1
- PowerShell extension version: 0.11.0
- Output from `$PSVersionTable`:
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
 - 1.9.1
f9d0c687ff2ea7aabd85fb9a43129117c0ecf519

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
0      11     0      0

code --list-extensions --show-versions
be5invis.vscode-icontheme-nomo-dark@1.2.5
ms-vscode.PowerShell@0.11.0

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

In a statement that has multiple commands, for instance a string where you're referencing a variable property or a foreach statement can we highlight the actual statement being executed.  ISE does this so in a statement such as `$UpdateValue = "User moved to $($Matches['ou']) by $($Object.MovedByName) on $($Object.MovedOn)"` ISE will highlight each of those statements to show what it's actually executing, right now in Code it just highlights the entire line and appears to execute it three times

**Comment by daviwil** [comment]
Can you give me a screenshot of what you see in the ISE that you expect to see in VS Code?  I'm not sure how the ISE is highlighting each statement separately.

**Comment by grumpkin** [comment]
If I run the code in the screenshots, when it hits line 11, it initially highlights the entire line, if I then step through that line with F10 it highlights each statement that it's evaluating.

![dbg_step_1](https://cloud.githubusercontent.com/assets/24529102/24315280/ce8cff3c-10ab-11e7-8239-a52048858093.png)
![dbg_step_2](https://cloud.githubusercontent.com/assets/24529102/24315282/d009d524-10ab-11e7-8c8e-dee3eca417b2.png)
![dbg_step_3](https://cloud.githubusercontent.com/assets/24529102/24315284/d17c2920-10ab-11e7-8275-ecae78a7a1cd.png)

**Comment by daviwil** [comment]
Thank you! I wasn't aware you were referring to the debugger.  VS Code now has a way to indicate in-line where the debugger has stopped in these cases but it looks like we didn't implement this correctly.  Thanks for catching the bug, I'll get it fixed for the next patch update.

**Comment by grumpkin** [comment]
Apologies, I really wasn't very clear in the initial description.

That's awesome, looking forward to the next update.

**Comment by daviwil** [comment]
Here's what it looks like in VS Code's way:

![image](https://cloud.githubusercontent.com/assets/79405/24316990/2157480e-10b0-11e7-8a61-19fde63edfb7.png)

The yellow arrow indicator shows the column number where the breakpoint is hit.  Doesn't seem like they select the actual region that I'm returning but maybe they'll change that in the future.
