### ISSUE TITLE
Stopping a script while being prompted for mandatory parameter input crashes integrated shell

### ISSUE THREAD

**Issue by dotps1** [PowerShell/vscode-powershell#617]
### System Details

- Operating system name and version: 10.0.14393
- VS Code version: 1.10.2
- PowerShell extension version: 0.11.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

create a basic script with this param block:

```powershell
param (
    [Parameter(
        Mandatory = $true
    )
    [String[]]
    $MandatoryParameter
)
```

execute the script with F5, then hit the `Stop` to stop debugging, the integrated shell is still looking for input.  hit enter, and the shell crashes, and cannot get reopend with out starting a new instance of code.

hitting F5 again causes this to pop up:
![image](https://cloud.githubusercontent.com/assets/1016996/24310624/0aac87bc-10a7-11e7-945b-4b8b9c6c27f7.png)

### Attached Logs

let me know if you cannot recreate and ill get some logs.

**Comment by daviwil** [comment]
Thanks!  I'll take a look for next week's patch update.

**Comment by daviwil** [comment]
This should be fixed now with the fix to https://github.com/PowerShell/PowerShellEditorServices/issues/428, update coming soon!
