### ISSUE TITLE
Add a "restart" command to integrated console to easily restart the session

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#622]
It'd be helpful to have a "restart" (alias of "Restart-EditorSession"?) command in the integrated console so that it's quick and easy to get a clean session at any time.

When developing this, we should make sure that the restart behavior is stable and consistent.  One user reported the following behavior when trying to restart their session repeatedly for development purposes:

> 1)	If you close the PowerShell Interactive Window, debugging stops working.
a.	Close the PowerShell Integrated Console
b.	Press “F5” to debug a script
c.	“Debug adapter process has terminated unexpectedly” error is raised (or it just sits in a terminally idle state)
d.	Even if launching a new Integrated Console, it doesn’t seem to recover. Only workaround is to restart VSCode
> 2)	“Show Integrated Console” doesn’t work reliably after closing.
> 3)	Closing (trashcan) the Integrated Console often raises an unexpected termination error (The PowerShell session has terminated due to an error, would you like to restart it?)

**Comment by mpearon** [comment]
Could this be added to the **New Terminal** list?

**Comment by tylerl0706** [comment]
> Even if launching a new Integrated Console, it doesn’t seem to recover. Only workaround is to restart VSCode

This doesn't seem to be true anymore (which is great!). This would still be useful to some, I think, this will still be on my radar.

**Comment by rjmholt** [comment]
I believe a restart command is now available. Closing
