### ISSUE TITLE
Feature Request: Go to Symbol to support Pester scopes

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#623]
It would be really handy if "Go to Symbol" feature (Ctrl+Shift+O) would also list the names of Pester script sections, like Describe, Context, InModuleScope, It to make it easier to browse through large Pester scripts.

**Comment by daviwil** [comment]
Yep, that would be nice, need to find a good way to provide intelligence for DSL-based script code like Pester tests.

**Comment by daviwil** [comment]
Ahhh, just saw this, added it in 1.3.0 :)  Closing for now, let me know if you find anything missing from that!
