### ISSUE TITLE
Debugger does not start in the correct window when multiple windows are open.

### ISSUE THREAD

**Issue by daleecc** [PowerShell/vscode-powershell#626]
### System Details

- Operating system name and version: Windows 7 (64-bit)
- VS Code version: 1.10.2
- PowerShell extension version: 0.11
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When debugging with multiple VSCode windows open (both with PowerShell), the debugging may not be performed in the correct window.

Steps to reproduce:
1. Open a VSCode window and load a PowerShell file. Wait for the Integrated Terminal to start.
2. Open a second VSCode window and load a different PowerShell file. Wait for the Integrated Terminal to start.
3. Start the debugger for the PowerShell in the first window. The script will be executed in the Integrated Terminal of the second window.

**Comment by daviwil** [comment]
Wow!  Does this happen every time you try it?  I have a theory on why it's happening, will try to fix it for an update this week.

**Comment by daleecc** [comment]
Yep I can reproduce this consistently with the method above.

**Comment by Bounz** [comment]
I can reproduce this bug also.
VS Code version: 1.10.1
PowerShell extension version: 0.12.2
$PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
