### ISSUE TITLE
Wrong character encoding when using Nordic characters

### ISSUE THREAD

**Issue by mbsj** [PowerShell/vscode-powershell#629]
### System Details

- Operating system name and version: Windows 7
- VS Code version: 1.10.2
- PowerShell extension version: 0.11.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

When using Nordic characters (don't know if others) in a string, the characters are converted, but only when running for a script file. See the attached image. 

![test](https://cloud.githubusercontent.com/assets/13234250/24446377/81bbf468-146d-11e7-9447-3eda2cdf3a5b.png)

**Comment by johlju** [comment]
Might be the same issue as #108?

**Comment by mbsj** [comment]
It looks to be the same as #108. I tried saving the file as UTF8 with BOM and it works as expected again. So at least there is a workaround :)

**Comment by sbakkis** [comment]
Any news regarding this? I am having this issue also.. A drag going back to ISE again.

**Comment by rjmholt** [comment]
Closing now that encoding is documented in https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/understanding-file-encoding?view=powershell-7
