### ISSUE TITLE
Snippets discussion - productivity feature or teaching feature

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#63]
I guess I've gotten used to C# snippets that are "functional/productive".  I find snippets like this in the PowerShell extension to be an awkward hybrid:
```powershell
switch ($x)
{
    'value1' {  }
    {$_ -in 'A','B','C'} {}
    'value3' {}
    Default {}
}
```
Seriously, what are the odds that I'll have `value1` as a case or a second or third case as shown above.  I believe these were written to **show how to use a feature** i.e. they are teaching.  That is admirable but as soon as the user **learns** the features of switch, this snippet becomes cumbersome because now it is a toss-up WRT how much code they have to "delete" to make the snippet conform to their intent versus how much they would have typed in the first place without using the snippet.  

I propose that at the very least the "common" language features lean more towards being productivity snippets and not "teaching" snippets.  I recommend changing the switch statement snippet to something like:
```powershell
switch ($variable) {
    condition { action; break }
    Default {}
}
```
Where the cursor is put on a `condtion placeholder` second after `$variable` and then the `action placeholder` would be third.

BTW here are a few more examples of what I'm talking about:
```powershell
try
{
    1/0
}
catch [DivideByZeroException]
{
    Write-Host "Divide by zero exception"
}
catch [System.Net.WebException],[System.Exception]
{
    Write-Host "Other exception"
}
finally
{
    Write-Host "cleaning up ..."
}

for ($i = 1; $i -lt 99; $i++)
{
    
}
```
Everybody who uses the try/catch/finally snippet is going to have to remove the DivideByZeroException and likely have to change the last catch to use an exception they want to catch (or not specify one at all).  I believe there should a single exception there and it should be a placeholder.  Likewise **everybody** is going to have to replace `99` in the for snippet.  Might as well make it a placeholder.

**Comment by daviwil** [comment]
Agree completely, snippets should be functions to speed up coding.  If we want to have educational snippets, it would be better as a different feature that doesn't overload the expectations of the snippets feature.  Feel free to fix up any existing snippets that have extraneous stuff that isn't immediately useful!

**Comment by rkeithhill** [comment]
OK, I've retained the "example" style snippets but they all begin with `ex-` in the auto-completion list.  All of the rest of the non `ex-` examples are focused on `productivity`, not on `teaching`.  I've modified the organization of the snippets file to put all the example snippets at the top of the file.

I also added some new snippets to try out `proph`, `enum`, `dsc ensure enum`, `parameter`, `parameter-path`, `parameter-literalpath` and `ex-path-processing`.

**Comment by daviwil** [comment]
That's a great way to do it.

**Comment by rkeithhill** [comment]
Before the Feb drop I was thinking about updating the snippets to include the word "snippet" in the description.  I find myself seeing foreach or while twice in the completion list where one is a keyword completion and the other is the snippet and I'm not sure which I will get.  Thoughts?

**Comment by daviwil** [comment]
That sounds like a good idea to me. I've been confused by it in the past too.

**Comment by KirkMunro** [comment]
Just to add to the discussion, snippets in PowerShell is a sore point with me because they are just examples, not snippets in the sense of productivity as you guys already mentioned.  With productivity in mind, if the productivity snippets for keywords are useful enough that I'd always want to use them, I'd prefer not seeing two choices (the keyword or the snippet), and having the snippet automatically applied when I apply completion to the word I'm typing.  That might be a nice feature to offer as an option, especially since keyword completion by itself is pretty useless (there aren't a lot of really long keywords out there).

**Comment by daviwil** [comment]
Yeah, good point.  It looks like the ISE gets around this by requiring you to invoke a different IntelliSense list that's solely for snippets.  Since the PowerShell engine is returning the completion for these keywords, we'd need a way to filter them out in editors which have snippets.  I think 'foreach' as a keyword completion is pretty pointless in an editor that has snippets.

Maybe we can just identify a set of keywords which will most often have snippets and just filter them out of code completion results entirely so that the snippets only show up?  What do you think, Keith?

**Comment by daviwil** [comment]
This also could be an option that gets set in the LanguageService so that it can be enabled/disabled for different editors.

**Comment by rkeithhill** [comment]
> snippets in PowerShell is a sore point with me because they are just examples

The snippets in PSES are now by default productivity oriented.  Auto-completing the foreach snippet gives:
```powershell
foreach ($item in $collection) {
    <== cursor place here
}
```
Where you get to tab between `$item` and `$collection` to change the variable name.  There are still some "example" snippets but all of these are prefixed `ex-` e.g. `ex-DSC resource provider (class-based)`.

>Maybe we can just identify a set of keywords which will most often have snippets and just filter them out of code completion results entirely so that the snippets only show up? What do you think, Keith?

Or we could just filter out all keywords.  Hmm, perhaps that is too extreme.  Yeah, we could filter based on a blacklist.  Would that list be static (in the code)? Or a setting?

**Comment by daviwil** [comment]
I'm fine with filtering them all out if we have reasonable snippet replacements for all of them, I just haven't evaluated what that would amount to yet.  I'd say maybe having an on/off setting without any granularity might be nice until we see what kind of feedback we get.

**Comment by daviwil** [comment]
I'd also say we shouldn't even expose the setting to the user at first.  Maybe people won't even care?

**Comment by rkeithhill** [comment]
Hmm, I think the `keyword` issue was a false alarm. I saw `foreach` twice in the list - one a snippet but the other was the "alias" for `Foreach-Object` - not the keyword.  I think we are good on this issue for 0.4.0.  Going to close it.

**Comment by daviwil** [comment]
Cool, good to know!
