### ISSUE TITLE
Powershell Terminal Window Navigation Keyboard Shortcuts

### ISSUE THREAD

**Issue by Jrouzies** [PowerShell/vscode-powershell#630]
Hello,

### Issue Description

Some navigation keyboard shortcuts doesn't work in the PowerShell Terminal.

Example : CTRL - LEFT ARROW / RIGHT ARROW to move from words to words.

### Reproduce steps

1. Open VSCode and go to the PowerShell terminal
2. Type some words
3. Try to use shortcut like CTRL - LEFT ARROW to move from words to words

A pain to move from args to args when calling a command 👎 :)

Thanks !

**Comment by daviwil** [comment]
Hey @Jrouzies, this will come as part of the PSReadline integration in a few weeks: https://github.com/PowerShell/vscode-powershell/issues/535.
