### ISSUE TITLE
Keboard shortct Ctrl + L does not work in integrated console to clear screen

### ISSUE THREAD

**Issue by dzampino** [PowerShell/vscode-powershell#634]
### System Details

- Operating system name and version: Windows 10 Pro Build 14393
- VS Code version: 1.10.2
- PowerShell extension version: 0.11.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
NOTE: Couldn't get command to work
$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
0      11     0      0
code --list-extensions --show-versions
NOTE: Couldn't get command to work
$PSVersionTable
```

### Issue Description

The keyboard shortcut Ctrl + L appears to do nothing at this time, while this shortcut works in VSCode's terminal.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by dotps1** [comment]
OMG!  I didn't know `ctrl+l` was even a thing!

**Comment by dzampino** [comment]
I believe it's a bash shortcut. VSCode uses it and once you start using it, you never go back.

**Comment by daviwil** [comment]
This feature comes from PSReadline, it will appear in the Integrated Console once we finish the work to integrate that module.  Follow issue #535 to know when this gets done.
