### ISSUE TITLE
Prompt written on Linux or macOS has black background

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#637]
Originally reported by @joeyaiello, and I've seen it too on macOS:

https://github.com/PowerShell/vscode-powershell/issues/594#issuecomment-290576005

Need to keep using the existing Console.BackgroundColor instead of changing it to black.

**Comment by Happycoil** [comment]
With VS Code 1.12.0 you can work around this issue by adding the following to settings.json:
```json
"workbench.colorCustomizations": {
    "terminal.ansiBlack": "#1E1E1E"
}
```
This is for Dark+, replace `1E1E1E` with the appropriate color for your theme.

**Comment by mklement0** [comment]
Unfortunately, this is still broken as of v1.4.3 on macOS 10.13, shown here with the "Light+" color theme:

![image](https://user-images.githubusercontent.com/588825/31863780-acfb4128-b720-11e7-93f6-80a81033d201.png)

To spell out the workaround for white-background themes, courtesy of @Happycoil's tip:

```json
   "workbench.colorCustomizations": {
      "terminal.ansiBlack": "#fff"
    }
```

**Comment by daviwil** [comment]
The fix for this issue hasn't actually been shipped yet, hoping to get it out this week.
