### ISSUE TITLE
Error message "is a file type that cannot be debugged by the powershell debug" with capital file extension .PS1

### ISSUE THREAD

**Issue by wellsluo** [PowerShell/vscode-powershell#641]
### System Details

- Operating system name and version:  Windows 10
- VS Code version: 1.10.2
- PowerShell extension version: 0.11.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```
code -v
1.10.2
8076a19fdcab7e1fc1707952d652f0bb6c6db331
PS D:\> $pseditor.EditorServicesVersion
>>
PS D:\> code --list-extensions --show-versions
>>
Adrien.VisualStudioDarkTheme@1.0.1
alefragnani.Bookmarks@0.12.0
emilast.LogFileHighlighter@1.1.1
emmanuelbeziat.vscode-great-icons@1.1.47
IBM.output-colorizer@0.1.0
ms-vscode.cpptools@0.10.5
ms-vscode.PowerShell@0.11.0
ms-vscode.wordcount@0.1.0
msazurermtools.azurerm-vscode-tools@0.3.4
robertohuertasm.vscode-icons@7.4.0
slevesque.vscode-hexdump@1.2.1

PS D:> $PSVersionTable
>>

Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
### Issue Description

When the file extension is capital, it reports error like:
"is a file type that cannot be debugged by the powershell debug"

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by wellsluo** [comment]
Add comments to commit: https://github.com/PowerShell/vscode-powershell/commit/47b4c5fd396391ea6ebcc4dd0298f4b270006207

**Comment by daviwil** [comment]
Thanks Wei!  We'll get that fixed.

**Comment by DrYSG** [comment]
@rkeithhill  Hey, I was having this issue with lowercase .ps1 and changed it to .PS1 and it works.  VSCODE 1.12.2

**Comment by daviwil** [comment]
@DrYSG You're still having this issue with PowerShell extension 1.0?

**Comment by DrYSG** [comment]
```
ame                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

![image](https://cloud.githubusercontent.com/assets/2865368/26120160/cc8ca366-3a3d-11e7-8e9f-10221e57f984.png)

**Comment by rkeithhill** [comment]
What version of the PowerShell extension do you have?

![image](https://cloud.githubusercontent.com/assets/5177512/26120422/f0d80a36-3a2d-11e7-9a5c-99e3689d94c7.png)

**Comment by DrYSG** [comment]
![image](https://cloud.githubusercontent.com/assets/2865368/26120660/79bbf05e-3a3f-11e7-86b7-c0a77462a7c0.png)

**Comment by rkeithhill** [comment]
So you have 1.0.0 of this extension installed into VSCode?  The original bug was the opposite of what you are reporting.   PS1 did not work while ps1 did work.  Can you provide some repro steps?  Thanks.

**Comment by DrYSG** [comment]
Yes, that is the funny thing. I am reporting the opposite. PS1 works and ps1 does not.

Steps

1. Create a powershell script named foobar.ps1 put some commands in it.
2. Use this launch.json shown below
2. Run the the debugger the "Launch current File" script
Make sure that the open tab is the PS1 file

Perhaps what I should be using is the 2.0.0 version of the launch.json?

**Comment by rkeithhill** [comment]
The version of launch.json should be `0.2.0`.

**Comment by StingyJack** [comment]
If I start by opening a folder with with a `.ps1`. and try to debug that `.ps1` I get the OP error.   I can rename the file to `.ps1` within VSC and then it debugs. If I rename it back to `,ps1` again, I can now debug it. 

I looked through the commits tied to this, and the extension handling looks correct (not using locale, but I dont think that matters), so there is probably something wrong with the `currentDocument.languageId` thats evaluated. 

Is there a way to dump out the current documents language id property without setting up a debug session?

**Comment by rkeithhill** [comment]
@StingyJack Are you on the latest VSCode release?  Also, what OS are you using?

VSCode should indicate the document's language in the lower right part of the status bar.  In looking at this I noticed the following in the VSCode docs:

> A language identifier is often (but not always) the lowercased programming language name. Note that casing matters for exact identifier matching ('Markdown' != 'markdown'). Unknown language files have the language identifier plaintext.

We've had this warning in our package.json file for a long time:

![image](https://user-images.githubusercontent.com/5177512/38124252-9ea06d70-339d-11e8-9b3a-18d4def4446b.png)

But that is just the package name so I guess the warning doesn't matter?  This is where we activate based on the language:

```
  "activationEvents": [
    "onDebugResolve:powershell",
    "onLanguage:powershell",
```
In looking at the list of [VSCode langauge identifiers](https://code.visualstudio.com/docs/languages/identifiers), they have misspelled `Powershell` - it should be `PowerShell` but maybe that is just on the web page.

**Comment by StingyJack** [comment]
case sensitive language identifiers is a bug =D  (seriously, whoever wrote that doc isnt thinking. These are human-used identifiers like someone's name and would be capitalized based on i18n sometimes, not machine understood data where casing may be important)

It does show PowerShell as the language. 
![image](https://user-images.githubusercontent.com/15381181/38138656-001056f4-33fa-11e8-8741-a6ef2418c52b.png)

I'm just not sure if it is setting that correctly in the code when its making the evaluation. Only a debug session will tell for sure.

**Comment by rkeithhill** [comment]
This is hard for me to debug since I can't repro it.  BTW I debug workspaces with `.ps1` files in them all the time.  Maybe you could tell me how you are debugging i.e. what is the debug configuration you are using.  

Also, this doesn't quite parse for me:

> If I start by opening a folder with with a `.ps1`. and try to debug that `.ps1` I get the OP error. I can rename the file to `.ps1` within VSC and then it debugs. If I rename it back to `,ps1` again, I can now debug it.

You say you rename the file from a `.ps1` to `.ps1` in VSC.  What am I missing here because it looks like you are not making **any** change to the extension.  And when you rename it back to `,ps1` I assume that's a typo because `,ps1` does not specify a file extension.

**Comment by StingyJack** [comment]
it should say 

If I start by opening a folder with with a powershell script ending in `.ps1`. and try to debug that `.ps1` I get the OP error. I can rename the file to `.PS1` within VSC and then it debugs. If I rename it back to `.ps1` again, I can now debug it.

This is more or less fresh install, as I don't use VSC often at all.

**Comment by rkeithhill** [comment]
Thanks for clarifying. That is pretty weird though. Hmm....
