### ISSUE TITLE
F5 on Untitled-1 file in 0.12.1 with existing .vscode\launch.json from prev version hangs debugger

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#650]
_From @dfinke on April 4, 2017 22:9_

This is the log.
[EditorServices.txt](https://github.com/PowerShell/PowerShellEditorServices/files/894657/EditorServices.txt)

and the launch.json
[launch.txt](https://github.com/PowerShell/PowerShellEditorServices/files/894658/launch.txt)

_Copied from original issue: PowerShell/PowerShellEditorServices#417_

**Comment by daviwil** [comment]
Thanks Doug!  I see the problem here, I wonder if other people will hit it too.  Might ship another patch update tomorrow.

**Comment by dfinke** [comment]
Not a show stopper.

**Comment by daviwil** [comment]
I *believe* this will be fixed in 0.12.2 but I'm keeping this open so we can verify just in case.

**Comment by daviwil** [comment]
Just checked with Doug, this is fixed in 0.12.2!
