### ISSUE TITLE
Exchange objects no detail in variable debug

### ISSUE THREAD

**Issue by Jrouzies** [PowerShell/vscode-powershell#651]
Hello !

When debugging and storing Exchange powershell objects in variable, there is no details in the actual variable. See screenshot bellow : 

No object information (same in SyncRoot) :

![image](https://cloud.githubusercontent.com/assets/26656800/24695679/fa3e0344-19e6-11e7-83e9-ebcc2f129e74.png)

Awaited info (write-host of $queues) : 

![image](https://cloud.githubusercontent.com/assets/26656800/24695700/09d10806-19e7-11e7-8377-36bd1dd73ccc.png)

I don't know if it is an issue with the Powershell module or VSCode directly.

Thanks,

**Comment by rkeithhill** [comment]
What version of the PowerShell extension and VSCode are you using?

**Comment by Jrouzies** [comment]
Hello, 

Sorry for lack of details : 

-VSCode version : 1.10.2
-Powershell extension : 0.12.1 (issue was the same in 0.11.0)

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
