### ISSUE TITLE
Prompts get garbled during debugging if you press and hold the F10 key

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#657]
### System Details

- Operating system name and version: Windows 10 AU
- VS Code version: 1.11.0
- PowerShell extension version: 0.12.1
- Output from `$PSVersionTable`:

```

Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

While debugging, press and hold the <kbd>F10</kbd> key.  You'll get garbled prompts like this:

![image](https://cloud.githubusercontent.com/assets/5177512/24735425/15354208-1a40-11e7-851d-6869ad8ee128.png)

### Attached Logs
[1491445592-9ac066f4-460a-4aec-b182-a60425e99dd41491445468628.zip](https://github.com/PowerShell/vscode-powershell/files/901326/1491445592-9ac066f4-460a-4aec-b182-a60425e99dd41491445468628.zip)

**Comment by SydneyhSmith** [comment]
Closing as this should be fixed in our latest release.
