### ISSUE TITLE
F8: Linux sudo password prompt not getting password correct on every first try

### ISSUE THREAD

**Issue by bgelens** [PowerShell/vscode-powershell#661]
### System Details

- Operating system name and version: CentOS 7.3 x64
- VS Code version: 1.11.1
- PowerShell extension version: 0.12.1
- Output from `$PSVersionTable`:
```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.17
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with ```sudo``` passwords prompts when sending commands to the Integrated Terminal using F8. The first entry is always wrong (and I'm sure it's not my typing skills :) )

Example:

![0c7e0f4d-edd1-4a0d-8e21-b2da16304d61](https://cloud.githubusercontent.com/assets/10071039/24789206/3c1243f2-1b72-11e7-9358-2b3674daac11.GIF)

**Comment by daviwil** [comment]
Thanks!  I'll give this a try to see what's going on.

**Comment by bgelens** [comment]
I have the same behavior on Windows when using scp.exe / ssh.exe

**Comment by rjmholt** [comment]
I believe this works now that the prompt functionality has been overhauled
