### ISSUE TITLE
Extension won't start with alpha 18 on CentOS

### ISSUE THREAD

**Issue by bgelens** [PowerShell/vscode-powershell#662]
### System Details

- Operating system name and version: CentOS 7.3 x64
- VS Code version: 1.11.1
- PowerShell extension version: 0.12.1
- Output from `$PSVersionTable`:
```powershell
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.18                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1 
```

### Issue Description

I am experiencing a problem with the extension not being started since PowerShell alpha 18 installation.
![2799bb4b-0edb-4cc3-bccb-4db618018214](https://cloud.githubusercontent.com/assets/10071039/24789814/c671c4e4-1b74-11e7-9a44-a4d6e83677c7.GIF)

### Attached Logs
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/904832/logs.zip)

**Comment by daviwil** [comment]
Not sure what the deal is with that module failure, I'll check it out as soon as I spin up a Linux VM.

**Comment by daviwil** [comment]
Apparently the new change to PSModulePath casing caused it!  Just need to change the startup script.
