### ISSUE TITLE
Cursor navigation only one letter at a time within PowerShell Integrated Console

### ISSUE THREAD

**Issue by adamrushuk** [PowerShell/vscode-powershell#666]
### System Details

- Operating system name and version: Windows 10 Pro
- VS Code version: 1.11.1
- PowerShell extension version: 0.12.2
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
PowerCLI C:\> code --list-extensions --show-versions
donjayamanne.githistory@0.2.0
DotJoshJohnson.xml@1.7.0
HookyQR.beautify@1.0.2
ms-mssql.mssql@0.3.0
ms-vscode.PowerShell@0.12.2
robertohuertasm.vscode-icons@7.5.1
PowerCLI C:\>
PowerCLI C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Within the PowerShell Integrated Console I can only move the cursor one letter at a time. I use CTRL + Arrow Keys, or CTRL + BACKSPACE to move the cursor one word at a time. 

This works as expected in the main Editor window, so would also be great to work in the console when doing interactive tasks.

**Comment by daviwil** [comment]
Hey Adam, this functionality come when we integrated PSReadline in a month or so.  Please follow issue #535 to be notified when this is done.  Thanks!

**Comment by adamrushuk** [comment]
Thanks David; yet more great features to look forward to!
