### ISSUE TITLE
PowerShell Integrated Terminal prompt jumps up to the moment debug started

### ISSUE THREAD

**Issue by johlju** [PowerShell/vscode-powershell#667]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
PS> code -v
1.11.1
d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39

PS> $pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
0      12     1      0

PS> code --list-extensions --show-versions
DavidAnson.vscode-markdownlint@0.7.1
donjayamanne.githistory@0.2.0
IBM.output-colorizer@0.1.0
ms-vscode.csharp@1.8.1
ms-vscode.PowerShell@0.12.2
PeterJausovec.vscode-docker@0.0.13
robertohuertasm.vscode-icons@7.5.1
ryu1kn.annotator@0.10.1
seanmcbreen.Spell@0.9.1

PS> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### Issue Description

When debugging and trying to type something in the PowerShell Integrated Terminal the prompt jumps up to the moment before the output started (or the moment debug started).

I trying to enter `$availabilityGroupObject` in the terminal window, pressing <kbd>AltGr + 4</kbd> to get a `$` sign (Swedish keyboard layout), but then the prompt jumps to the beginning and when I continue typing it jumps back to the end.

![vscodeterminalbug](https://cloud.githubusercontent.com/assets/7189721/24830038/11c648fc-1c7e-11e7-9aae-68b685a6668c.gif)

### Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/907543/logs.zip)

**Comment by johlju** [comment]
I have tested with English keyboard layout as well, same behavior when pressing <kbd>Shift+4</kbd>.

**Comment by daviwil** [comment]
Yep, this happens for me sometimes too.  I know what's causing it, I'll try to fix it for 0.13.0.  Thanks Johan!

**Comment by daviwil** [comment]
This should be fixed in 1.0.0, do you still see the issue anymore?

**Comment by johlju** [comment]
@daviwil  I can't see this issue anymore (tested in v1.1.0.). Thanks a lot for fixing this. Saves seconds each debug. 😄

**Comment by daviwil** [comment]
No problem, thanks for confirming!
