### ISSUE TITLE
PowerShell workflow default param string value shows error

### ISSUE THREAD

**Issue by dotps1** [PowerShell/vscode-powershell#669]
### System Details

- Operating system name and version: Windows 10 1607 x64
- VS Code version: 1.11.1
- PowerShell extension version: 12.2
- Output from `$PSVersionTable`: (the `code` commands don't have any output on my system?)

```
PS C:\> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
0      12     1      0

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

in powershell workflow, a string default parameter is showing an error saying it needs to be a "simple value" like an int or a string.  and it is a string.

### Attached Logs

![image](https://cloud.githubusercontent.com/assets/1016996/24878897/ee4783b0-1e02-11e7-850d-69e4db935f76.png)

**Comment by daviwil** [comment]
Do you get the same marker in the ISE?  I think that would be coming from PowerShell.

**Comment by dotps1** [comment]
I do get the same thing in the ISE, but based on the error I just don't understand, it says must be simple values, int or string.  that is a string.

**Comment by SydneyhSmith** [comment]
I am having trouble reproducing this, @dotps1 are you still running into this issue?

**Comment by dotps1** [comment]
its been like a year ¯\_(ツ)_/¯

**Comment by dotps1** [comment]
but yes it is still happening:
![image](https://user-images.githubusercontent.com/1016996/50833207-7e466500-131e-11e9-9a9b-06871f782824.png)

**Comment by dotps1** [comment]
good enough for me.

**Comment by robe070** [comment]
@dotps1 Hi Thomas, do you debug Workflows in VS Code? Can you point me at any resources that can instruct me how to do it?
Thank you
