### ISSUE TITLE
F8: New-PSSession requires selecting terminal windows and hit enter to show result

### ISSUE THREAD

**Issue by bgelens** [PowerShell/vscode-powershell#670]
### System Details

- Operating system name and version: CentOS 7.3 x64
- VS Code version: 1.11.1
- PowerShell extension version: 0.12.2
- Output from `$PSVersionTable`:
```powershell
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.18                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1 
```

### Issue Description

I need to select the terminal and hit enter after sending New-PSSession using f8 to refresh / show the result.

![c404f52e-dbc4-4898-82a4-5c0d98ea5f83](https://cloud.githubusercontent.com/assets/10071039/24879132/1ba174aa-1e36-11e7-8dd5-110c6344b317.GIF)

**Comment by daviwil** [comment]
That is really strange...  I'll look into it!

**Comment by TylerLeonhardt** [comment]
I get the feeling this is probably fixed... @bgelens any idea if this is a still a problem for you?

**Comment by bgelens** [comment]
v6.0.0-alpha.18 :) Have not experienced this behavior recently. I'll close
