### ISSUE TITLE
Auto Formatting:  option to have the next line after a grave symbol indented

### ISSUE THREAD

**Issue by madlovin** [PowerShell/vscode-powershell#674]
In  my code, I like to follow the Allman-8 indentation style, but have gravitated towards K&R for PowerShell.
In settings.json, I have `"editor.formatOnType": true` added.
Imagine I were to write the following line:
```powershell
$message = "This is a long line of text"
    + "that continues to the next line in the editor"
```
This would be my desired formatting.
However, the following auto-formatting occurs:
```powershell
$message = "This is a long line of text" `
+ "that continues to the next line in the editor"
```
This situation gets worse with more indentation:
```powershell
if ($someCondition) {
    if ($anotherCondition) {
        $message = "This is a long line of text" `
 + "that continues to the next line in the editor"
    }
}
```
Is my formatting desires something that could be addressed through a PowerShell Configuration option in the settings.json?  Apologies if this belongs in a different board.

**Comment by kapilmb** [comment]
@madlovin You've posted on the correct board! 

This looks like a bug. We will have a fix soon for this.
