### ISSUE TITLE
Snippets for Advanced Functions, DSC Configs, etc.

### ISSUE THREAD

**Issue by EdGrant63** [PowerShell/vscode-powershell#675]
Are snippets going to be added to the PowerShell module in VSCode? This would make it much easier to create advanced function and DSC Configurations.

**Comment by rkeithhill** [comment]
There is a snippet for advanced functions: `cmdet`.  There are more "example" like snippets that are prefixed `ex-` for DSC and advanced functions e.g. `ex-cmdlet`.
