### ISSUE TITLE
F8: Doesn't auto scroll integrated terminal to end if terminal was scrolled up before

### ISSUE THREAD

**Issue by bgelens** [PowerShell/vscode-powershell#676]
### System Details

- Operating system name and version: All platforms
- VS Code version: 1.11.1
- PowerShell extension version: 0.12.2
- Output from `$PSVersionTable`: All versions

### Issue Description

When I inspected output in the Integrated Terminal by scrolling up, I then run the next command from the file by pressing F8. Expected behavior would be that the Integrated Terminal would scroll down automatically when the code is executed. Instead it stays at the current scrolled to line.

![8f6cf09c-74f5-4d20-9bc4-6e5a037aac5b](https://cloud.githubusercontent.com/assets/10071039/24974705/6d783cf8-1fc3-11e7-90e8-8636cbcb4668.GIF)

In the gif, I'm scrolling the terminal manually after I ran code using F8 and the Terminal did  not scroll down automatically

**Comment by daviwil** [comment]
Thanks Ben!  This probably something to ask @Tyriar about: any way for us to cause the terminal to scroll to the end when output is written?

**Comment by Tyriar** [comment]
@daviwil `sendText` (including run selected text/file) should probably scroll down just like any keyboard input, would this solve the problem?

**Comment by daviwil** [comment]
At the moment I'm not using `sendText` for this behavior in the PowerShell extension, though I'm probably going to switch to it in the future.  An optional boolean param to scroll on send might help with this!

**Comment by Tyriar** [comment]
@daviwil the run selected text command uses `sendText` behind the scenes. I guess it should be optional for the actual sendText API though.

**Comment by daviwil** [comment]
Currently in the PowerShell extension, F8 is bound to a custom command that sends a request to my language server to run the selected text, so we're not using the built in "Run Selection" command.  This will change in the future once I get PSReadline hooked up in the Integrated Console; the default behavior of the "Run Selection" command will work for us then.

Weird and confusing, I know :)

**Comment by SydneyhSmith** [comment]
I am having trouble re-producing this so I am guessing it has been fixed in updates, will reopen if this is still an issue.
