### ISSUE TITLE
Detachable Integrated Terminal

### ISSUE THREAD

**Issue by GHRoss** [PowerShell/vscode-powershell#678]
It would be great to be able to detach the integrated terminal to help with increasing screen real estate.

**Comment by daviwil** [comment]
Yep!  I'm hearing this request a lot lately.  I don't believe VS Code will get the ability to pop out the terminal for a while (if ever) but I might be able to host the Integrated Console experience in a normal console window.  Will look into it after 1.0.

**Comment by TylerLeonhardt** [comment]
VS Code has given the ability to maximize the Integrated Terminal and allow code and terminal side-by-side. I think we can close this now.
