### ISSUE TITLE
Saving files throw System.AggregateException

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/vscode-powershell#680]
### System Details

- Operating system name and version: Seven sp1 Fr
- VS Code version: 1.11.2
- PowerShell extension version: 0.12.2
- Output from `$PSVersionTable`:
name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
PowerShell Integrated Terminal :

PS C:\Temp\TestVS> code -v
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e
PS C:\Temp\TestVS>
PS C:\Temp\TestVS> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
0      12     1      0


PS C:\Temp\TestVS>
PS C:\Temp\TestVS> code --list-extensions --show-versions
alefragnani.Bookmarks@0.14.1
alefragnani.project-manager@0.14.0
dananicc.theme-doucenuit@0.3.0
dbankier.vscode-instant-markdown@1.1.0
DotJoshJohnson.xml@1.7.0
ms-vscode.csharp@1.8.1
ms-vscode.PowerShell@0.12.2
psake.psake-vscode@0.1.0
PS C:\Temp\TestVS>
PS C:\Temp\TestVS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Change the directory when files are unsaved throw an exception.

### Steps to repro :
create C:\Temp\TestVS
create C:\Temp\TestVS2
open VScode
Menu File -> open directory -> C:\Temp\TestVS

Menu File -> New file
insert text
Menu file -Save -> F1.ps1 ( under C:\Temp\TestVS)
insert one new line

Menu File -> New file
insert text
Menu file -Save -> F2.ps1 ( under C:\Temp\TestVS)
insert one new line

Menu File Open directory -> click on Select  OR Menu File Close directory 

OpenDialog -> Save the files (f1 and f2)  -> Click save all

Open the logs :
```
14/04/2017 11:34:21 [ERROR] - Method "OnListenTaskCompleted" at line 337 of C:\projects\powershelleditorservices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageDispatcher.cs

    MessageDispatcher loop terminated due to unhandled exception:
    
    System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
       à Microsoft.PowerShell.EditorServices.Protocol.LanguageServer.RunspaceDetails..ctor(RunspaceDetails eventArgs)
       à Microsoft.PowerShell.EditorServices.Protocol.Server.LanguageServer.<PowerShellContext_RunspaceChanged>d__50.MoveNext()
...  
[EOF]
```
### Attached Logs
**!** Remove .txt extension **!**
[Logs.ZIP.txt](https://github.com/PowerShell/vscode-powershell/files/921962/Logs.ZIP.txt)

**Comment by daviwil** [comment]
Thanks Laurent!  I'll check it out.
