### ISSUE TITLE
Tab Completion removes backslash in UNC Path

### ISSUE THREAD

**Issue by mpearon** [PowerShell/vscode-powershell#681]
### System Details

- Operating system name and version: **Windows 10 v1607, build 14393.970**
- VS Code version:  **1.11.2**
- PowerShell extension version:  **0.11.2**
- Output from `$PSVersionTable`:

**PSVersion                      5.1.14393.953**
**PSEdition                      Desktop**
**PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}**
**BuildVersion                   10.0.14393.953**
**CLRVersion                     4.0.30319.42000**
**WSManStackVersion              3.0**
**PSRemotingProtocolVersion      2.3**
**SerializationVersion           1.1.0.1**

### Issue Description

Tab completion is removing the initial backslash from UNC Paths.
For instance:
\\\CorpServer\  becomes \CorpServer\ when one of the subdirectories is selected.
This occurs at every level, not just at the root of the server/share.

**Comment by daviwil** [comment]
Wow, that's weird, I'll take a look!

**Comment by mpearon** [comment]
I just recently learned that I could embed GIFs, and grabbed a copy of LICEcap, so I've decided to attach a demonstration, so that others can see what's happening.

![uncissue](https://cloud.githubusercontent.com/assets/7157790/25559570/ff6ac6d4-2d02-11e7-83d2-87ee65f379d3.gif)

**Comment by AspenForester** [comment]
I hadn't noticed this behavior before, but I can report that I can duplicate the issue with:
VSCode: 1.12.0
PowerShell Extension: 1.0.0

Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by daviwil** [comment]
This seems to be fixed in the latest Visual Studio Code Insiders build, can you try it there and let me know if it's resolved for you?

**Comment by mpearon** [comment]
@daviwil 
I checked in Insiders, and you are correct - it appears to be working as expected! :)

**Comment by daviwil** [comment]
Great, thanks for confirming! I'll keep this issue open until that fix comes to the stable VS Code release.

**Comment by mpearon** [comment]
Great news, @daviwil!  As of 1.13.0, this behavior seems to have been corrected! :)

**Comment by daviwil** [comment]
That's great, thanks a lot!
