### ISSUE TITLE
PowerShell Editor Services hangs when VSCode debugger is stopped at "Confirm"

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#682]
### System Details

- Operating system name and version: Mac OS Sierra

```
PS /Users/tsulli> code -v
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e
PS /Users/tsulli> $pseditor.EditorServicesVersion
PS /Users/tsulli> code --list-extensions --show-versions
Alexander.theme-sublime-oceanicnext@0.0.3
Nuuf.theme-hackershaze@1.3.1
PeterJausovec.vscode-docker@0.0.13
abusaidm.html-snippets@0.1.0
akamud.vscode-theme-onedark@1.3.2
aws-scripting-guy.cform@0.0.9
azemoh.one-monokai@0.2.4
christian-kohler.npm-intellisense@1.3.0
donjayamanne.python@0.6.2
ecmel.vscode-html-css@0.1.1
eg2.vscode-npm-script@0.1.9
fknop.vscode-npm@3.3.0
jakeboone02.mediawiki@2.1.0
jprestidge.theme-material-theme@1.0.1
ms-vscode.csharp@1.8.1
ms-vscode.PowerShell@0.12.2
searKing.preview-vscode@1.1.5

PS /Users/tsulli> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

The Integrated Terminal in Visual Studio Code hangs when you have an interactive prompt waiting for input, but stop the debugging interface.

![screen shot 2017-04-17 at 8 00 22 am](https://cloud.githubusercontent.com/assets/466713/25092760/f11b916c-2343-11e7-9854-1cce5cae7289.png)

In order to resume coding, I need to invoke the `PowerShell: Restart Current Session` command in the Visual Studio Code Command Palette.

### Repro Steps

1. Create a script with: `Stop-Process -Confirm -Name zsh` (you might need to change the process name)
2. Run the script in the debugger (F5)
3. When the confirmation appears in the integrated terminal, stop the debugger
4. Notice that the PowerShell Editor Services / Integrated Terminal is now hung (including broken Intellisense)

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

Cheers,
Trevor Sullivan

**Comment by rkeithhill** [comment]
Likely related to (or the same issue as) #628.

**Comment by pcgeek86** [comment]
Closing as duplicate.
