### ISSUE TITLE
PowerShell extension fails to start powershell

### ISSUE THREAD

**Issue by mjbvz** [PowerShell/vscode-powershell#685]
_From @reddwarf666 on April 18, 2017 17:54_

Updated VSCode on my Mac and after that, VSCode fails to load PowerShell in the terminal window
Re-installed PowerShell and re-installed PowerShell extension.
No installs of any other extension, first startup of VSCode of the day, VSCode & PowerShell combo was working yesterday, got a message that I needed to restart VSCode because there was a new version/update of VSCode and it needed to finalize this update.

Have not yet re-installed VSCode as I don't want to lose settings I have set up until now.

- VSCode Version: 1.11.2
- OS Version: macOS Sierra 10.12.4

$PSVersionTable                                                                            
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-alpha                                                                             
PSEdition                      Core                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   3.0.0.0                                                                                 
GitCommitId                    v6.0.0-alpha.17                                                                         
CLRVersion                                                                                                             
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1

Error Messages:
- Language server startup failed.
- The terminal process terminated with exit code: 1
- Log dump from "Output" window:
[19:32:28] Language server starting...
powershell.exe started --
powershell.exe started --
powershell.exe started --
powershell.exe started --
powershell.exe terminated or terminal UI was closed
[19:33:29] Language server startup failed.
Could not start language service: 
Could not start language service: 

The Terminal window does show some red text in the Terminal window but it disappears too quickly for me to be able to read.
PS: the Terminal window is able to start powershell if I type manually "powershell"

_Copied from original issue: Microsoft/vscode#24966_

**Comment by mjbvz** [comment]
Moved this over to powershell for further investigation. Please let me know if this looks to be an issue in VSCode itself

**Comment by daviwil** [comment]
@reddwarf666 Please update to [PowerShell 6.0.0-alpha.18](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.18), there was a breaking change we had to address for it in 0.12.2:

https://github.com/PowerShell/vscode-powershell/blob/develop/CHANGELOG.md#friday-april-7-2017

**Comment by reddwarf666** [comment]
Hi daviwil & mjbvz,

Installing alpha.18 fixed the issue! Thanks!

**Comment by nkasco** [comment]
This was my issue as well, same fix just needed to update to alpha 18.

**Comment by cixelsyd** [comment]
I had this issue with powershell-6.0.0-beta.2-osx.10.12-x64 but installing powershell-6.0.0-alpha.18-osx.10.11-x64 fixed it.

**Comment by daviwil** [comment]
@cixelsyd this problem is caused by PowerShell Core 6 releases older than `alpha.18`, but `beta.2` is newer.  I think you may be hitting a different issue, can you provide more details about what happened in your case?  Logs would be helpful:

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us
