### ISSUE TITLE
scrollbar tab does not appear in new terminal after debug run and output, on hover or focus

### ISSUE THREAD

**Issue by bughit** [PowerShell/vscode-powershell#686]
vscode 1.11.2, win7 x64, vscode-powershell 0.12.2

1. kill the terminal
2. start a new one
3. debug something with lots of output
4. a click or hover on the terminal shows no scroll tab

**Comment by daviwil** [comment]
Hey @bughit, this is related to a bug in VS Code, see this issue for more details: https://github.com/PowerShell/vscode-powershell/issues/536.  Anytime you see this problem you can just try resizing the VS Code window, the scrollbar should show up after that.
