### ISSUE TITLE
Linting for when a backtick is followed only by white space

### ISSUE THREAD

**Issue by AndrewGaspar** [PowerShell/vscode-powershell#69]
I've been bitten by this bug a few times:

```powershell
$oven = Toast-Bread ` 
    -Bread Wheat
```

You probably can't see the problem - there's a space after the backtick, which causes the parser not to take the next line as part of the command, causing the command to be issued without the Bread parameter. It would be great if vscode-powershell highlighted this issue because I'm sure it's almost never done intentionally.

This seems to be a PowerShell problem generally - why isn't a backtick followed only by white space and a newline handled the same as a backtick immediately followed by a newline?

**Comment by rkeithhill** [comment]
This extension pulls in the [PSScriptAnalyzer](https://github.com/powerShell/PsscriptAnalyzer) as a submodule to do all the linting.  It is a reasonable suggestion but you should probably file the bug on that project.  

By you might think about setting this user preference in VSCode (I do):
```json
// When enabled, will trim trailing whitespace when you save a file.
"files.trimTrailingWhitespace": true
```

**Comment by AndrewGaspar** [comment]
Sounds good. Moved to PSScriptAnalyzer. Thanks for the suggestion!

**Comment by daviwil** [comment]
Ideally the PS parser would either accept this syntax or give a helpful error, but the next best thing is a Script Analyzer rule.  Thanks for filing this over there!
