### ISSUE TITLE
PSSession error in integrated console

### ISSUE THREAD

**Issue by ScriptMigo** [PowerShell/vscode-powershell#691]
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.11.2
- PowerShell extension version: 0.12.2
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Note: This works in the ISE without issue. I only encounter the issue in VSCode.

1. `$creds = Get-Credential`
2.  `New-PSSession -computername 'computername' -credential $creds`
3. Verify session created, `get-pssession`
4. Attempt to enter session, `enter-pssession -id <Session ID>`

Results:

```
enter-pssession : Object reference not set to an instance of an object.
At line:1 char:1
+ enter-pssession -id 1
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enter-PSSession], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.EnterPSSessionCommand

```

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Thanks @ScriptMigo! Looks like we're not handling that case properly.

**Comment by daviwil** [comment]
Just tried this on my machine, seems to be working fine.  Could you send verbose logs to me so I can see why it's giving you this error?

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

Thanks!

**Comment by ScriptMigo** [comment]
Will do David. Will be tomorrow when I'm in the office.

Thanks!

**Comment by ScriptMigo** [comment]
David,
Attached are my verbose logs from when I attempt to enter-pssession.

-Scott

**Comment by daviwil** [comment]
Files attached to issue emails don't make it to GitHub unfortunately, can you e-mail the logs directly to me?  `daviwil` at `microsoft.com`

**Comment by jurelab** [comment]
I am having same issue. ScriptMigo did you manage to solve it?

Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

ThanksJ

**Comment by ScriptMigo** [comment]
J, I've not yet found a solution to my (our) issue. Recently upgraded to VSCode x64, but that did not resolve the problem either (one could hope, right?).

**Comment by jurelab** [comment]
Thanks for quick response. I also use VSCode x64. Hope this gets fixed soon.
J

**Comment by dezren39** [comment]
I am also receiving this error when I attempt to enter a pssession. Can send logs if needed.

**Comment by TylerLeonhardt** [comment]
Hi all, this should be working in the latest extension so I'm going to close this. If you're still seeing the problem - let us know!
