### ISSUE TITLE
installing powershell extension for VS code removes run script context menu

### ISSUE THREAD

**Issue by mjbvz** [PowerShell/vscode-powershell#692]
_From @rambutan2000 on April 20, 2017 22:9_

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.2|
|PowerShell|ms-vscode|0.12.2|;

---

After I installed the powershell extension for VS code (from within VS code the usual way) it removed the run powershell context menu option in Windows Explorer

Steps to Reproduce:
1.  Install the powershell extensions
2.  In windows explorer, right-click on a *.ps1 file, the "Run Powershell script" content menu item is missing

_Copied from original issue: Microsoft/vscode#25099_

**Comment by mjbvz** [comment]
_From @rambutan2000 on April 20, 2017 22:12_

Looks like others have had a similar problem, looks like its to do with changing the default editor of ps1 files
https://community.spiceworks.com/topic/1083434-can-t-recover-run-with-powershell-context-menu-entry

**Comment by daviwil** [comment]
Isn't this caused by VS Code though?  The PowerShell extension doesn't mess with default file configurations in Windows.

**Comment by rambutan2000** [comment]
The root cause is some kind of shell bug, but maybe the VS code extension should not automatically associate VS Co

de with .ps1 files.  I've attached a .reg file which fixes the issue.  Maybe compare what the extension is doing to register ps1 files with against the reg file contents.

**Comment by daviwil** [comment]
Definitely a shell bug, but the PowerShell extension itself doesn't touch the system's file associations.  In theory this should be happening when you install VS Code itself, not the PowerShell extension.  Did the problem only occur after you installed the PowerShell extension?  Could you double-check?

**Comment by rambutan2000** [comment]
I'm 90% it was after the powershell extension install.  I tried to open a ps1 file then VS code showed the recommendation bar above the code view.  I then installed the extension and tried to run the ps1 file from win explorer.  I'd been running ps1 files earlier today and this is the only change to my system.

**Comment by daviwil** [comment]
That's extremely strange if so.  I wonder if VS Code has some logic for associating the file extension when a language extension for a known file extension is installed.

FWIW, the only place where the PowerShell file extensions are registered is in the built-in PowerShell syntax extension: https://github.com/Microsoft/vscode/blob/master/extensions/powershell/package.json#L9

**Comment by mpearon** [comment]
I don't think I agree with the OP's observations here.  I've only seen this behavior if I changed the default association of PS1s, and I've installed on every machine I've has the opportunity to.
I use a registry modification similar to the one listed above.

**Comment by JackUkleja** [comment]
I just noticed today that my "Run with PowerShell" shell menu item is missing. I'm using VSCode 1.13.1 with the 1.4.1 PowerShell extension.

**Comment by JackUkleja** [comment]
@rambutan2000 Your .reg script didn't seem to fix the issue for me. Strange.

**Comment by f0nt4** [comment]
I don't think this is an issue of the extension, but from Code itself.
After opening a ps1 file with "Windows PowerShell ISE", the option "Run with PowerShell" is back.
As soon as you open a ps1 with code, the option disappears.
After that when you again open with PowerShell ISE, the option returns 
and so it continues.
This also happens when the PowerShell addon is not installed.

**Comment by BrianMakes** [comment]
I am experiencing the same issue @f0nt4 describes.

If VS Code is associated with the PS1 file type, the following behavior occurs:

"Run with PowerShell" shell menu item is missing. (after installing VS Code or Powershell Extension)
Opening PS1 file in ISE returns the "Run with PowerShell" shell menu item.
Opening PS1 file in VS Code removes the menu item.

Associating the PS1 filetype with something else (I tested with Notepad) correct the issue.

**Comment by rjmholt** [comment]
> This also happens when the PowerShell addon is not installed.

It sounds like this issue should be moved to VSCode. One sec
