### ISSUE TITLE
IntelliSense popup does not close when focus changes to terminal

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#695]
### System Details

- Operating system name and version: Mac OS X Sierra

```
PS /Users/tsulli> code -v
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e
PS /Users/tsulli> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
0      12     1      0

PS /Users/tsulli> code --list-extensions --show-versions
Alexander.theme-sublime-oceanicnext@0.0.3
Nuuf.theme-hackershaze@1.3.1
PeterJausovec.vscode-docker@0.0.13
abusaidm.html-snippets@0.1.0
akamud.vscode-theme-onedark@1.3.2
aws-scripting-guy.cform@0.0.9
azemoh.one-monokai@0.2.4
christian-kohler.npm-intellisense@1.3.0
dlech.chmod@1.0.0
donjayamanne.python@0.6.3
ecmel.vscode-html-css@0.1.2
eg2.vscode-npm-script@0.1.9
fknop.vscode-npm@3.3.0
jakeboone02.mediawiki@2.1.0
jprestidge.theme-material-theme@1.0.1
ms-vscode.cpptools@0.10.5
ms-vscode.csharp@1.9.0
ms-vscode.PowerShell@0.12.2
searKing.preview-vscode@1.1.5
```

### Issue Description

The Intellisense / auto-completion window is hanging around after running a bit of code.

Repro steps:

1. Fire up a new VSCode PowerShell session
2. Quickly type `gps` and hit <kbd>F8</kbd>

What actually happens:

1. Current line of code is sent to Integrated Terminal
2. Integrated Terminal gets focus
3. Intellisense window is still visible

Expected result:

1. Intellisense window shouldn't be visible if focus is in Integrated Terminal.

![2017-04-23 powershell extension bug](https://cloud.githubusercontent.com/assets/466713/25315435/8ab97928-2809-11e7-9397-d4fbccf79ec6.gif)

Cheers,
Trevor Sullivan

**Comment by daviwil** [comment]
Thanks for the GIF!  That's helpful.  Not sure why the IntelliSense pane isn't being cleared, I'll look into it.

**Comment by pcgeek86** [comment]
@daviwil I should've made the font bigger, will do next time. :)

**Comment by daviwil** [comment]
Don't worry, it was readable enough to tell what was going on :)

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.

**Comment by pcgeek86** [comment]
I just tested on Windows 10, and can't reproduce. Perhaps it's specific to MacOS, or perhaps it randomly got fixed in the last two years.
