### ISSUE TITLE
PowerShell debug console doesn't word wrap correctly

### ISSUE THREAD

**Issue by codemonkeychris** [PowerShell/vscode-powershell#7]
If you issue a command line "gci", the terminal output is word wrapped to a very narrow window, instead of occupying the full space available. If you resize the window, the output doesn't adjust.

**Comment by daviwil** [comment]
Yep, I've been talking to the VS Code team about this, hopefully we'll get some improvements for long output lines in the next release.

**Comment by daviwil** [comment]
Tracked in the VS Code repo with this issue:

https://github.com/Microsoft/vscode/issues/255

**Comment by kliemohn** [comment]
This issue is really important.  It makes VS Code almost unusable for PowerShell use in my opinion.

**Comment by daviwil** [comment]
I agree, it makes the console pretty useless when you can't see multi-line output from a command.  Hopefully the VS Code team will get this fixed for their next release.

**Comment by daviwil** [comment]
Hi guys, this situation should improve a lot in the upcoming 0.10.7 and 0.4.0 releases of VS Code and the PowerShell extension.  Once those are out I'll comment back here so you can go try it out and let me know what you think.

**Comment by rkeithhill** [comment]
It is definitely better but the output seems to be wrapping for at column 80 and my Debug Console window is much wider than that.
```
    Directory: C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\Po
    werShellEditorServices.Host\bin\Debug


Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
               2/2/2016  10:46 PM         114427 DebugAdapter.log              
               2/2/2016  10:35 PM        1101753 EditorServices.log            
-a----         2/2/2016  10:35 PM         118272 Microsoft.PowerShell.EditorSer
                                                 vices.dll 
```
If we can't detect the column width of the output window perhaps we make this a debug setting the user can set in their preferences.  Then we run output through something like `Out-String -Width <n>`.

**Comment by daviwil** [comment]
That's a great point actually, we should add a config setting for that.  In the meantime I'll increase the width of the virtual console.  What would be a good default width, 100?  120?

**Comment by daviwil** [comment]
Filed an issue for the configuration setting here: https://github.com/PowerShell/vscode-powershell/issues/80

**Comment by daviwil** [comment]
Also created this issue for increasing the default console width: https://github.com/PowerShell/PowerShellEditorServices/issues/129

**Comment by rkeithhill** [comment]
Given the horizontal debug window in 0.10.7, I suggest 120.

**Comment by daviwil** [comment]
Keith has fixed this in PowerShell Editor Services, you should have better output wrapping in the 0.4.0 release next week!
