### ISSUE TITLE
"throw" not offered as keyword in autocompletion

### ISSUE THREAD

**Issue by carlocardella** [PowerShell/vscode-powershell#703]
### System Details

VSCode Version:
Version 1.11.2
Commit 6eaebe3
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

$PSVersionTable
PSVersion                      5.1.15063.138
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.138
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

OS Version: 10.0.14393

### Issue Description
Just start typing "throw", they keyword is colored properly once typed but does not appear as suggestion in autocompletion:

![image](https://cloud.githubusercontent.com/assets/5784415/25557101/0fb612da-2cbf-11e7-82c0-04a884e18f6b.png)

**Comment by iricigor** [comment]
Similar thing is with continue keyword
![image](https://cloud.githubusercontent.com/assets/15923171/25921151/b0a119d8-35d4-11e7-8875-c3f687f033da.png)

**Comment by daviwil** [comment]
This is because PowerShell doesn't return completion results for either of these keywords.  I don't get completions for either of them in the ISE either.  We could definitely try to insert them as results, though!

**Comment by Cirzen** [comment]
Does this need doing for all keywords?
There's nothing in there for try / catch / finally either. This frequently results in me over-writing catch with another cmdlet name instead after pressing enter:
![allman_catch](https://user-images.githubusercontent.com/13346199/36741161-4f9ba6fa-1bdc-11e8-8911-dafe1b2d4834.png)

**Comment by moymike** [comment]
Just tested on a .JS file, and the try, catch and finally all work with intellisense.  
With .PS1 only the try is recognized.

**Comment by Cirzen** [comment]
I can only see try as a snippet, not as a known keyword. 
![image](https://user-images.githubusercontent.com/13346199/36743207-9c11b36c-1be1-11e8-89be-e03437eb34d7.png)

**Comment by moymike** [comment]
Okay, you are right, somehow I managed to disable the Powershell extension.  Now I am seeing the same thing, just the snippets try, trycf and tryf ... typing catch or finally are not recognized at keywords.

**Comment by tylerl0706** [comment]
so we have:

throw, continue, try, catch & finally.

I think we should open an issue on PowerShell (https://github.com/powershell/powershell) to see if adding completion results for these keywords is needed.

@SteveL-MSFT, do you have any thoughts on this?

**Comment by SteveL-MSFT** [comment]
I think we should open an issue in PowerShell repo rather than special case this for PSEditorServices

**Comment by TylerLeonhardt** [comment]
I'm going to close this now that we have https://github.com/PowerShell/PowerShell/issues/7891 over in the PowerShell repo.
