### ISSUE TITLE
Run Script in External PowerShell Console, accepting parameter

### ISSUE THREAD

**Issue by mpearon** [PowerShell/vscode-powershell#705]
### System Details

- Operating system name and version:  **Windows 10 v1607 Build 14939.1066**
- VS Code version:  **1.11.2**
- PowerShell extension version:  **0.12.2**
- Output from `$PSVersionTable`:
                                                                                                            
**PSVersion                      5.1.14393.1066**
**PSEdition                      Desktop**
**PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}**
**BuildVersion                   10.0.14393.1066**
**CLRVersion                     4.0.30319.42000**
**WSManStackVersion              3.0**
**PSRemotingProtocolVersion      2.3**
**SerializationVersion           1.1.0.1**

### Issue Description

The ability to run a script in an external console from within vsCode would be awesome.
This feature was present in PowerGUI, but broke with the release of Win10 v1607 - and I don't have a machine pre-1607 around, so I can't demonstrate the feature in its entirety...but what I can show follows.

There were two ways to execute a script, and a way to pass a parameter to both methods:
     1.  Running in integrated terminal
          This did just want vsCode does, but it offered an extra feature that I'll mention in No. 3.
![powergui-1](https://cloud.githubusercontent.com/assets/7157790/25558805/eaa4da50-2cf3-11e7-9a2d-eebcaeb2b985.gif)

     2.  Running in external console
          I can't demonstrate this one (afore mentioned reasons), but this is what I would love to see.  This saved a temporary copy of the script, then launched PowerShell externally with the path to the temporary script as the -File parameter.  This helped eliminate any "ISE-style" weirdness, and showed me exactly how the end-user's experience would be - which was awesome.

     3.  You could pass an argument list to both methods via an input box in editor.
![powergui-3](https://cloud.githubusercontent.com/assets/7157790/25558821/47a6abca-2cf4-11e7-892c-95edc83238c0.gif)

**Comment by mpearon** [comment]
I'm not sure why, but the descriptions on points 2 and 3 are showing as code.  Sorry!

**Comment by rkeithhill** [comment]
When you run in the integrated terminal you *can* pass parameters to this script.  Click on the gear icon in the debug view to edit the launch.json file:
```
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch (current file)",
            "program": "${file}",
            "args": [],
            "cwd": "${file}"
        },
```
Add your args to the `args:` field and they will be passed to the script when you debug.  

For the external console debug support, you can `attach` to an external console.  I would stick a temporary `Read-Host "press enter to continue"` at the start of your script. Before running the script, execute `$pid` and note the process id on the console.  Then run the script from the console.  Then in VSCode, edit the launch file, add the "PowerShell: Attach to PowerShell Host Process" configuration.  Save the file and then select that config in the debug view and press F5.  Then select your external PowerShell process (via the pid) and you'll be attached to that external console and you can debug it.

**Comment by mpearon** [comment]
@rkeithhill 
As far as the parameter solution goes, that isn't a very easy solution - and I haven't quite gotten it to work, but that is probably operator error.  Here is what I've done to my config:
```
{
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch (current file)",
            "script": "${file}",
            "args": ["test"],
            "cwd": "${file}"
        },
```
...and this is the test script I'm try to run:
```
Param(
    $test = 'not defined'
)
Write-Host $test
```
The editor's status bar turns orange, but the script doesn't appear to execute.


Regarding the external launch:
I'm not really interested in the debugging functionality (although that is a neat feature).  It's more of the ability to quickly launch the script (like an end-user would), and see how it behaves outside of the editor.  It's probably too niche to really get anything done about it.

**Comment by rkeithhill** [comment]
That config looks good. Two things. First, make sure you have that config selected in the Debug view drop down e.g.:

![image](https://cloud.githubusercontent.com/assets/5177512/25559069/1e813c72-2cf1-11e7-965a-dd68ee546c59.png)

Second, make sure the script you want to run is in the active editor window.

**Comment by mpearon** [comment]
@rkeithhill 
I need to start by saying that I really appreciate your assistance with this.  Communities like this are awesome, and are what make me proud to be a geek.

I bounced the editor, and now the debugger is actually running the script - so that bit is better now.
Here is what I'm still encountering:
_Note: I've spun up a duplicate launch configuration to demonstrate that I'm using the correct one (and so I can easily switch to a functional one)._
![args1](https://cloud.githubusercontent.com/assets/7157790/25559168/bc6b11d8-2cfb-11e7-84b6-23d8ae8a204b.gif)

So, if I understand how this is supposed to be working, the `Write-Host` should return `test` instead of the default value of `undefined`, right?

**Comment by rkeithhill** [comment]
This seems to be a bug in the handling of an `unsaved` file w/launch.json.  Trivial workaround though, save the file to a .ps1 file and it works as expected (at least on my machine).

**Comment by mpearon** [comment]
@rkeithhill 
That did the trick, sir!  Thank you!

Is it possible to have the editor interactively prompt you for this value (like it does for the PID)?
I have tried `"args": ["${args}"]` and `"args": "${args}"` to no avail.  The first does nothing, and the second causes the debug to churn endlessly.

**Comment by rkeithhill** [comment]
OK I looked into the ignored arguments issue.  The problem doesn't reside in VSCode.  The args get passed to the PowerShellEditorServices:
```
    READ MESSAGE:
    
    {
      "command": "launch",
      "arguments": {
        "type": "PowerShell",
        "request": "launch",
        "name": "PowerShell Launch (current file)",
        "script": "untitled:Untitled-1",
        "args": [
          "test"
        ],
        "cwd": "c:\\Users\\Keith\\temp",
        "internalConsoleOptions": "neverOpen"
      },
      "type": "request",
      "seq": 2
    }
```
The problem in PSES is that we execute the unsaved editor contents by essentially asking PowerShell to execute the string `param($test='undefined')\nWrite-Host`.  Same as if you pasted this into the console.  In this scenario, there is no named command in which to pass the parameters.  And in fact, the internal method that executes the script, doesn't take the parameters to start with.

@daviwil We might be able to work around this by wrapping the string like so:
```csharp
if (arguments != null)
{
    scriptString = string.Forma("& {{ {0} }} {1}", scriptString, arguments);
}
psCommand.AddScript(scriptString);
```
There are probably several ways to make this work.   What do you think?

**Comment by rkeithhill** [comment]
@mpearon RE prompting for arguments ... this is a feature from PowerGUI editor that I miss.  I think we might be able to do this. I'm going to look into it.  If I can make it work, you'll probably have to replace the `"args:"` value with something like `"${command:SpecifyScriptArguments}".

**Comment by rkeithhill** [comment]
That was relatively easy to prototype:
![image](https://cloud.githubusercontent.com/assets/5177512/25560389/dd9f1930-2d0f-11e7-9b13-f675e55da2d0.png)
Looks like:
![image](https://cloud.githubusercontent.com/assets/5177512/25560503/e60e9822-2d12-11e7-9837-29464d077082.png)
You can enter say `50 100` or `test` or just press `Enter` to send no arguments.
I wonder if we should just add this as-is or maybe add a debug configuration snippet that uses this?  Not sure what we would call it.  Perhaps `PowerShell Launch w/args (current file)`?  Or maybe `PowerShell Launch w/args UI (current file)`?

**Comment by rkeithhill** [comment]
I want this UI to remember the args you typed in the previous debug session so you don't have to keep re-entering the same values (at least during the same VSCode session).  But there appears to be a bug in VSCode (or I'm using it wrong).  Waiting to get resolution on this before finalizing the PR for this feature.

**Comment by mpearon** [comment]
@rkeithhill  @daviwil 
It is awesome to see this in the 1.0.0 release!  It might be worth mentioning that the script **must be saved** for this to work.

**Comment by mpearon** [comment]
If there are no objections from @rkeithhill  and @daviwil , I'll close this issue.

**Comment by daviwil** [comment]
Ahh!  I didn't realize we hadn't closed it out yet :)  Thanks Matthew!
