### ISSUE TITLE
Auto set breakpoints

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#708]
Automatically generate breakpoints for all the functions in the script.

It'd be cool if the vs code API was surfaced to be able to do this from `$psEditor`.

https://channel9.msdn.com/coding4fun/blog/Breaking-the-Breakpoint-Blues-with-the-Breakpoint-Generator?WT.mc_id=dlvr_twitter_ch9

**Comment by daviwil** [comment]
Cool idea!  This will definitely be possible with `$psEditor` in the future.

**Comment by rkeithhill** [comment]
You could do something like this once editing has started (works only for the current file but you get the idea):
```posh
$psEditor.GetEditorContext().CurrentFile.Ast.FindAll({param($p) $p -is [System.Management.Automation.Language.FunctionDefinitionAst]}, $true) | Foreach-
Object { Set-PSBreakpoint -Command $_.Name }
```
Unfortunately, pasting into the integrated console breaks the line into two invalid command lines.

But yeah, it would be nice to have access to a debug API off of $psEditor.

**Comment by daviwil** [comment]
Cool!  Yeah, we'll definitely have a debug API and also one for easily grabbing the symbols in a file so that you don't have to walk the AST yourself.

**Comment by SydneyhSmith** [comment]
Closing as Keith's suggestion should work now, and we do not currently intend to make this enhancement in the near future
