### ISSUE TITLE
Tab Completion breaks UNC path

### ISSUE THREAD

**Issue by willprather** [PowerShell/vscode-powershell#709]
### System Details
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e
$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
0      12     1      0

code --list-extensions --show-versions
ms-vscode.csharp@1.9.0
ms-vscode.PowerShell@0.12.2

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with tab completion. When I hit tab to auto complete a UNC path, it removes one of the '\' at the beginning.
\\serverA\c$\windows
becomes
\serverA\c$\windows\system32
when I hit tab.

Tab completion does not work for the path at all at that point because it is no longer a valid path.

**Comment by daviwil** [comment]
Hey Will, this issue is being traced with #681 so I'll close this one in favor of the other.  I'd recommend subscribing to that issue to be notified when the issue gets resolved.  Thanks!
