### ISSUE TITLE
"Open in ISE" needs a better default keybinding

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#71]
Thanks to @janegilring we now have an "Open in ISE" command!  Unfortunately VS Code seems to dislike keybindings starting with `ctrl+alt` so it would be good to find a better sequence that VS Code will accept.  I looked at the current keybindings and it seems most `ctrl+shift+<letter>` combinations are taken already.

Any thoughts?

**Comment by rkeithhill** [comment]
ISE uses `Ctrl+Shift+P` to launch PowerShell.  So perhaps `Ctrl+Shift+I` to launch ISE?  I don't think that shortcut is currently mapped but I'm not 100% sure of that.

**Comment by daviwil** [comment]
That is a pretty good option since it isn't currently taken but there's a conflict in VS Code's development mode, it opens the embedded Chrome Debugging Tools.  Maybe that isn't a big deal though?  Would only affect people who are running VS Code in development mode because they're adding a new feature.

**Comment by daviwil** [comment]
Hey @janegilring, just letting you know that I'm about to change the shortcut to `Ctrl+Shift+i` instead of `Ctrl+Alt+i`.

**Comment by daviwil** [comment]
Forgot to close that one, thanks!
