### ISSUE TITLE
Cannot Create New-WebServiceProxy

### ISSUE THREAD

**Issue by lifebound** [PowerShell/vscode-powershell#712]
### System Details

- Operating system name and version: Microsoft Windows 7 Professional
- VS Code version: 1.11.2
- PowerShell extension version: 0.12.2
- Output from `$PSVersionTable`: 

```
code -v
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e
PS C:\Users\lifebound\scripts>
PS C:\Users\lifebound\scripts> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
0      12     1      0


PS C:\Users\lifebound\scripts>
PS C:\Users\lifebound\scripts> code --list-extensions --show-versions
formulahendry.code-runner@0.6.16
ms-vscode.csharp@1.9.0
ms-vscode.PowerShell@0.12.2
ms-vsts.team@1.117.1
```

### Issue Description

I am experiencing a problem with creating a New-WebServiceProxy object.

Steps to reproduce:

`PS C:\> $zip = New-WebServiceProxy -Uri "http://www.webservicex.net/uszip.asmx?WSDL"`

This will throw an error, stating that it cannot download the wsdl.

```
New-WebServiceProxy : The remote name could not be resolved: 'www.webservicex.net'
At line:1 char:1
+ New-WebServiceProxy -Uri http://www.webservicex.net/uszip.asmx?WSDL
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (http://www.webs...uszip.asmx?WSDL:Uri) [New-WebServiceProxy], WebException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.NewWebServiceProxy

PS C:\Users\lifebound\scripts> $Error[1].Exception
There was an error downloading 'http://www.webservicex.net/uszip.asmx?WSDL'.
PS C:\Users\lifebound\scripts> $Error[1].Exception.InnerException
The remote name could not be resolved: 'www.webservicex.net'
```

this error can be replicated by multiple users, both on public and private networks, when using VSC with the powershell plugin. It cannot be replicated in PowerGUI, Powershell ISE, or the PoSH CLI.

### Attached Logs

Logs have been emailed for security, with this issue referenced.

**Comment by Glober777** [comment]
@lifebound, it seems that Webservicex no longer presents the uszip service, hence you're getting the error. Doesn't seem to be related to PowerShell extension
