### ISSUE TITLE
NoProfile arg is ignored in tasks.json

### ISSUE THREAD

**Issue by lipkau** [PowerShell/vscode-powershell#713]
### System Details

- Operating system name and version: 10.0.14393.953
- VS Code version: 1.12.0-insider
- PowerShell extension version: 0.12.2
- Env:
```
1.12.0-insider
31a5fb236ddeed969a0021a2f94e7695ffbfb66b
abusaidm.html-snippets@0.1.0
alefragnani.Bookmarks@0.14.1
Andreabbondanza.ignoregit@1.0.1
annsk.alignment@0.3.0
anseki.vscode-color@0.4.1
austin.code-gnu-global@0.2.1
bcmarinacci.theme-material@1.3.0
christian-kohler.path-intellisense@1.2.0
codezombiech.gitignore@0.5.0
dbaeumer.vscode-eslint@1.2.8
dbankier.vscode-gist@0.5.3
dkundel.vscode-new-file@2.1.0
donjayamanne.githistory@0.2.0
donjayamanne.python@0.6.4
DotJoshJohnson.xml@1.7.0
eamodio.gitlens@3.4.9
EditorConfig.EditorConfig@0.9.3
emallin.phpunit@1.0.0
fabianlauer.vs-code-xml-format@0.1.5
felixfbecker.php-debug@1.10.0
felixfbecker.php-intellisense@1.2.1
fknop.vscode-npm@3.3.0
formulahendry.auto-close-tag@0.3.12
formulahendry.code-runner@0.6.16
HookyQR.beautify@1.0.2
humao.rest-client@0.14.2
idleberg.emoji-code@0.1.11
ikappas.composer@0.5.0
jchannon.csharpextensions@1.3.0
Kasik96.format-indent@1.3.0
luggage66.VBScript@0.0.1
lukasz-wronski.ftp-sync@0.3.3
magicstack.MagicPython@1.0.10
mohsen1.prettify-json@0.0.3
ms-vscode.cpptools@0.11.0
ms-vscode.csharp@1.9.0
ms-vscode.PowerShell@0.12.2
ms-vscode.sublime-keybindings@2.0.1
msjsdiag.debugger-for-chrome@3.1.1
PKief.material-icon-theme@2.0.5
qinjia.view-in-browser@0.0.5
rafa-acioly.laravel-helpers@0.2.0
rubbersheep.gi@0.2.10
Rubymaniac.vscode-paste-and-indent@0.0.8
ryannaddy.laravel-artisan@0.0.6
sandy081.todotasks@0.4.0
shinnn.stylelint@0.24.0
slevesque.vscode-autohotkey@0.2.0
stevencl.addDocComments@0.0.8
thekalinga.bootstrap4-vscode@2.3.3
Tyriar.theme-sapphire@0.2.0
v4run.transpose@0.0.5
vittorioromeo.expand-selection-to-scope@0.2.0
vsmobile.cordova-tools@1.2.7
wcwhitehead.bootstrap-3-snippets@0.0.9
Zarel.sublime-commands@0.1.0

Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When I run a Task configured in `tasks.json` with
```
"version": "2.0.0", 
```
the arg `-NoProfile` is ignored

**Comment by rkeithhill** [comment]
I don't believe this is an issue with the VSCode extension.  VSCode itself handles execution of tasks.json. 

It may also be how you're passing the `-NoProfile`.  Can you post your tasks.json file here?

**Comment by daviwil** [comment]
I asked Oliver to file this here so that we can figure out the right setup for the new task runner.  It turns out that setting `"isShellCommand": true` in `tasks.json` is the wrong thing to do when launching tasks in PowerShell.  When you have it set to true it seems that the arguments to powershell.exe don't get passed along.

My guess is that "is shell command" means "this is a command that will be run in the system's default command shell" rather than "this is a process to be launched where task commands may be executed".  Looks like we need to remove this setting from all of our tasks.json files.

Does that make sense?  Happy to be proven wrong if my understanding is incorrect.

**Comment by rkeithhill** [comment]
Gotcha.  I think I just copied those tasks from a node example.

**Comment by rkeithhill** [comment]
We only provide this is two places.  One is internal to the extension's tasks.json and the other is in the Examles\.vscode dir.  

Should we default tasks.json to version 2.0.0?  I'm personally not liking the fact that each `test` session ends with `Press any key to close the terminal`.  PR coming.

**Comment by daviwil** [comment]
Yeah, I'm not crazy about the message either but it's pretty easy to ignore.  If you just keep running the task the same terminal will get reused without having to press a key to close it first.  Defaulting to 2.0.0 is nice because the PowerShell output gets written correctly.

**Comment by rkeithhill** [comment]
Will do.  BTW I'll submit a separate PR for Plaster's NewModuleTemplate.

**Comment by daviwil** [comment]
Cool!
