### ISSUE TITLE
Bug with the "PowerShell: Expand Alias" feature

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#714]
### System Details

- Operating system name and version: Mac OS Sierra
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
PS > code -v
1.12.1
f6868fce3eeb16663840eb82123369dec6077a9b
PS > $pseditor.EditorServicesVersion
PS > code --list-extensions --show-versions
Alexander.theme-sublime-oceanicnext@0.0.3
Nuuf.theme-hackershaze@1.3.1
PeterJausovec.vscode-docker@0.0.13
abusaidm.html-snippets@0.1.0
akamud.vscode-theme-onedark@1.3.2
arcticicestudio.nord-visual-studio-code@0.1.1
aws-scripting-guy.cform@0.0.9
azemoh.one-monokai@0.2.4
christian-kohler.npm-intellisense@1.3.0
dlech.chmod@1.0.0
donjayamanne.python@0.6.4
ecmel.vscode-html-css@0.1.2
eg2.vscode-npm-script@0.1.9
fknop.vscode-npm@3.3.0
jakeboone02.mediawiki@2.1.0
jprestidge.theme-material-theme@1.0.1
mrcrowl.hg@1.0.4
ms-vscode.cpptools@0.11.0
ms-vscode.csharp@1.9.0
ms-vscode.PowerShell@0.12.2
searKing.preview-vscode@1.1.5
```

### Issue Description

I'm seeing some bugs when I try to use the `PowerShell: Expand Alias` VSCode command. The first time I tried to use it, I received an exception saying the "sequence contains no elements," but now that I've restarted the PowerShell session, it's just prompting over and over, without actually doing anything.

All I've typed is: `gps` followed by `ALT / OPTION + SHIFT + E` to invoke `Expand Alias`.

<img width="627" alt="screen shot 2017-05-06 at 2 08 55 pm" src="https://cloud.githubusercontent.com/assets/466713/25775939/bac1a51c-3265-11e7-89f6-4f0a4b87fd69.png">

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
Interesting. I see one more prompt string appear after exansion (with no linebreak like you're seeing).

**Comment by daviwil** [comment]
I think it shows multiple times in his screenshot because he's run Expand Aliases a bunch of times.  Looks like the way we're running that command in the session isn't properly causing a newline to be written.  Also, I'm betting that the expansion is actually happening but there's just nothing in the file to expand.  If you use `gci` in the file, does it get expanded?

**Comment by rkeithhill** [comment]
I should have mentioned that all the aliases I tested were expanded but then again, I'm testing on Windows / Windows PowerShell.

**Comment by pcgeek86** [comment]
@daviwil @rkeithhill That's the weird thing, expansion isn't actually occurring for me. I tried both `gci` and `gps`. Will send logs over.

**Comment by daviwil** [comment]
Thanks a lot!

**Comment by pcgeek86** [comment]
This line is getting printed repeatedly in the `EditorServices.log` file. Also e-mailed you the full log.

```
The term 'Sort' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by daviwil** [comment]
Thanks Trevor!  I think the alias for `Sort-Object` may not be available on Linux/macOS, just need to update the logic for the alias expansion command.

**Comment by SydneyhSmith** [comment]
Closing as this should be resolved
