### ISSUE TITLE
Feature Request: Add "fix this for me" in Errors and Warnings (aka. Problems)

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#717]
Right now, the VSCode PowerShell Extension is showing useful errors and warnings under the **Problems** section. When I right-click on one of these issues, I get a context menu with a single `Copy` command. However, it would be useful if certain items could automatically be fixed, especially as an entire batch (eg `PowerShell: Fix All Warnings and Errors`). Granted, not every single issue can easily be resolved, but a lot of basic warnings like using command aliases, parameter aliases, or using positional instead of named parameters, can be automatically fixed. 

Providing a standard framework for other contributors to add new "fixes" would be convenient. If this could be implemented in VSCode, that would enable any language author to benefit from this feature.

<img width="488" alt="screen shot 2017-05-07 at 8 48 58 am" src="https://cloud.githubusercontent.com/assets/466713/25782547/085c86e2-3302-11e7-8c7e-60f494e1e831.png">

Cheers,
Trevor Sullivan

**Comment by daviwil** [comment]
Unfortunately we don't have control over what shows up in the context menu in the Problems panel.  We'll definitely be adding a "fix all errors" command of some sort.

We do actually have a standard framework for contributing new fixes in PowerShell files, it's through PSScriptAnalyzer's SuggestedCorrection property on the DiagnosticRecord type.  If you develop a PSScriptAnalyzer rule that specifies SuggestedCorrections and then configure that rule to be loaded in VS Code, your corrections will be usable in the editor.  More info here:

https://github.com/PowerShell/PSScriptAnalyzer#violation-correction

**Comment by pcgeek86** [comment]
I actually found that out by clicking the light bulb next to issues. I kinda figured it might already be supported somewhere else. It was able to fix my alias --> command full name issue, for example. Neat stuff!!

**Comment by daviwil** [comment]
The lightbulb UI is definitely too hidden, I wish they'd make it more obvious without having to click on the marked text.  Glad you figured it out!

**Comment by pcgeek86** [comment]
@daviwil It would be pretty cool if you could batch-fix them, too though. Unfortunately clicking the lightbulb isn't scalable. :) If you could check off boxes next to each item under the `Problems` heading, and batch-fix issues across many files in a project, that would be pretty awesome.
