### ISSUE TITLE
Lint message on ShouldContinue does not recognize Force [switch] parameter

### ISSUE THREAD

**Issue by heaths** [PowerShell/vscode-powershell#72]
Version 0.2.0 is giving me a lint error on `$PSCmdlet.ShouldContinue` that a Boolean Force parameter is required. My cmdlet defines a `[switch]` parameter named `$Force`, which is actually the recommended way (does not require an argument).

**Comment by rkeithhill** [comment]
Can you try updating the PowerShell extension to version 0.3.1 - type `Ctrl+Shift+P` and then `ext` and select `Extensions: Show Outdated Extensions`.  You may need to restart VSCode.  I believe a number of the PSScriptAnalyzer rules that are enabled by default have been reduced.  What I don't remember is if those changes made it into 0.3.1 or if they'll be in the upcoming 0.4.0.

You can also disable script analysis (in 0.3.1) by adding this line to the end of your user settings:
```
// Enables real-time script analysis using PowerShell Script Analyzer.
"powershell.scriptAnalysis.enable": false
```

**Comment by daviwil** [comment]
Yep, as Keith suggests, the rule reduction went in place for 0.3.1 so you should try upgrading.  I just tried this code snippet:

```powershell
function Test-Linting
{
    [cmdletbinding(SupportsShouldProcess=$true)]
    param([Switch]$Force)
    
    process
    {
        if ($PSCmdlet.ShouldContinue("Are you sure?"))
        {
        }
    }
}
```

I don't get any linting markers for the rule you mentioned, so I think you'll be happier after you upgrade :)

**Comment by heaths** [comment]
Mainly I just wanted to point out the rule is wrong, but updating did help. :) I also realize after I started looking into contributing a fix that you're just calling into the PS editor host so I'll file a bug with them that it should be properly recognized.

**Comment by daviwil** [comment]
Yep, sorry about that, I should have pointed you to the PSScriptAnalyzer repo to begin with.  Seems like you found it already!
