### ISSUE TITLE
Specific Folder Crashes PowerShell on Close

### ISSUE THREAD

**Issue by Rick-2CA** [PowerShell/vscode-powershell#722]
### System Details
- Operating system name and version:
    Win 8.1 Pro
- VS Code version:  
    1.12.1
    f6868fce3eeb16663840eb82123369dec6077a9b
- PowerShell extension version:  
    christian-kohler.path-intellisense@1.4.0
    emilast.LogFileHighlighter@1.1.1
    ms-vscode.PowerShell@0.12.2
    ms-vsts.team@1.117.3
- Output from `$PSVersionTable`:  
    PSVersion                      5.1.14409.1005
    PSEdition                      Desktop
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.14409.1005
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1

### Issue Description

The application reports that the PowerShell console has crashed when a specific folder is closed (Either with Close Folder or by changing folders via Open Folder).  

### Attached Logs

Logs being sent to David.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
