### ISSUE TITLE
Arrow keys not working during debug session

### ISSUE THREAD

**Issue by DanielSturm** [PowerShell/vscode-powershell#728]
### System Details

- Operating system name and version: Windows 10 Professional x64 
- VS Code version: 1.12.1
- PowerShell extension version: 1.0.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      0      0

code -v
1.12.1
f6868fce3eeb16663840eb82123369dec6077a9b

code --list-extensions --show-versions
ms-vscode.PowerShell@1.0.0
```

### Issue Description
In a debug session I cannot use the arrow keys to go to previous commands. For example:
```
$x = 100  <enter>
<arrow up> # line stays empty instead of showing the previous command again. 
```
The behavior works as expected in the normal terminal.

**Comment by daviwil** [comment]
Hi Daniel, this is a known issue currently tracked by bug #550.  Please subscribe to that issue to be notified when the bug gets resolved.  I'll get this fixed soon!
