### ISSUE TITLE
Add a runspace picker menu for the attach debug configuration

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#731]
When debugging DSC configurations, it'd be helpful to optionally show a runspace picker so that the user can select the correct runspace in the LCM when attaching to its process.  We can use a debug config variable to invoke the picker as we do with the process selector.

/cc @bgelens

**Comment by rkeithhill** [comment]
Hopefully you can control the order VSCode invokes the pickers (process first, then pid).  Then you just need to pass the process id to PSES to get back the available rs ids.

**Comment by daviwil** [comment]
I **hope** that VS Code evaluates them in the order in which they're in the file but you never know...  Good point though, I dunno if we can get the list of runspaces in a process without actually entering the process first.  Might be a little nasty...

**Comment by SydneyhSmith** [comment]
Closing as resolved.
