### ISSUE TITLE
Add the functionality for Get-Help <commandlet> -ShowWindow to command console

### ISSUE THREAD

**Issue by asilverman** [PowerShell/vscode-powershell#735]
### System Details

- Operating system name and version: Windows 8.1 Enterprise 64-bit (6.3, Build 9600)
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
1.12.1
f6868fce3eeb16663840eb82123369dec6077a9b

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      0      0

code --list-extensions --show-versions
ms-vscode.csharp@1.7.0
ms-vscode.PowerShell@1.0.0

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
### Issue Description

I am experiencing a problem with the fact that it is not possible to pop a window with the command help when performing the following command on the PS TERMINAL
 Get-Help Copy-Item -ShowWindow

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Thanks Ariel!  This is actually a facet of a general issue in the integrated console, tracked by issue #621.  You can subscribe to that issue to be notified when the issue gets fixed.
