### ISSUE TITLE
Feature request: Generate splatting command from command

### ISSUE THREAD

**Issue by skest3qc** [PowerShell/vscode-powershell#736]
Hi,

it would be nice to be able to create a splatting command, f.e selecting the long command -> right click -> create splatting command

Before:
`Get-Process -Name explorer -ComputerName localhost  -Verbose: $true -ErrorAction Stop`

After the conversion it could look like this:

$params=@{
   Name = "explorer"
   Computername = "localhost"
   Verbose = $true
   ErrorAction = "Stop"
}
Get-Process @params

This is helpful if you have long commands and it makes it easier to read the code.

Thanks

**Comment by daviwil** [comment]
Definitely, we've thought about this in the past.  @kapilmb, want to give that a shot at some point?

**Comment by kapilmb** [comment]
@daviwil Sure. Most likely July iteration though.

**Comment by mpearon** [comment]
This is the same as [#517](https://github.com/PowerShell/vscode-powershell/issues/517).  There was a little bit of strategic planning going on in that one, just in case it matters.
I'm excited to see this one happen!

**Comment by daviwil** [comment]
Good catch!  I'll close this one in favor of the other since it came first.  Please subscribe to #517 to be notified when this feature gets implemented.
