### ISSUE TITLE
Switching between PowerShell versions on Windows is unreliable

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#737]
It appears that after the latest upgrade to `vscode-languageserver`  we've lost the ability to switch between PowerShell versions cleanly using the status bar menu.  Sometimes it hangs at startup causing the extension host to crash after a timeout.  Other times it seems to work fine.  There must be some initialization step that we need to clean up when using the newer version of that library.

/cc @jpsnover

**Comment by csandfeld** [comment]
For me the integrated console hangs when I run the "PowerShell: Restart Current Session" command. Not sure if that is related, or if it should be logged as an issue of its own.

**Comment by daviwil** [comment]
I think it's the same issue, I'll look into it today.
