### ISSUE TITLE
Debugger crashes when stepping-in

### ISSUE THREAD

**Issue by yobyot** [PowerShell/vscode-powershell#738]
### System Details

- macOS 10.12.4
- VS Code version: 1.12.1
- PowerShell extension version: 1.0.0
- Output from `$PSVersionTable`:
PSVersion:                      6.0.0-beta
PSEdition:                      Core
BuildVersion:                   3.0.0.0
CLRVersion:
GitCommitId:                    v6.0.0-beta.1
OS:                             Darwin 16.5.0 Darwin Kernel Version 16.5.0: F...
Platform:                       Unix
PSCompatibleVersions:           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion:      2.3
SerializationVersion:           1.1.0.1
WSManStackVersion:              3.0

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

PS /Users/alex/Documents/PowerShell> code -v
1.12.1
f6868fce3eeb16663840eb82123369dec6077a9b
PS /Users/alex/Documents/PowerShell> $pseditor.EditorServicesVersion
PS /Users/alex/Documents/PowerShell> code --list-extensions --show-versions
HookyQR.beautify@1.0.2
donjayamanne.githistory@0.2.0
eriklynd.json-tools@1.0.2
ms-vscode.PowerShell@1.0.0
robertohuertasm.vscode-icons@7.7.0
PS /Users/alex/Documents/PowerShell> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Darwin 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am experiencing a problem with...
debugging a script using module AWSPowerShell.NetCore. Script runs fine _UNTIL_ it's debugged, at which point, a step-in will crash VS Code as shown in the attached screenshot

### Attached Logs
[Archive.zip](https://github.com/PowerShell/vscode-powershell/files/997543/Archive.zip)

### Image
![2017-05-12_13-51-46](https://cloud.githubusercontent.com/assets/14332263/26010620/ad388de2-371b-11e7-855c-5e251de09135.png)

**Comment by daviwil** [comment]
Hey Alex, thanks for the report!  I can't see an obvious issue in the logs, could you possibly provide me with the simplest script that reproduces the issue so I can try to catch it in the debugger?

**Comment by yobyot** [comment]
Thanks, David.

Is there an email address I can send the script to? To make sure you can run it, I have supplied read-only keys to an AWS account. I'd prefer not to post that here.

In the meantime, I am attaching the logs for a test of the script I'd send you which crashed in vscode (but not in a macOS PowerShell console).

[debug.zip](https://github.com/PowerShell/vscode-powershell/files/1002694/debug.zip)




Best,
Alex

**Comment by daviwil** [comment]
Yep!  Send it along to `daviwil` at `microsoft.com`.  Thanks a lot!

**Comment by yobyot** [comment]
Hi.

My symptoms have changed! Now, when debugging a PowerShell script on macOS in vscode 1.13.1 and PowerShell module 1.4.1 on beta 3 of PowerShell six, the first couple of step-ins execute. Then everything just hangs. It's usually after an `Import-Module AWSPowerShell.NetCore`, which is the latest version at 3.3.113.0.

What could I attach to this problem to help debug this issue? It's really the same issue as it's been: something about the combo of vscode and module AWSPowerShell.NetCore and debugging is not working.

Thanks.

Alex

![image](https://user-images.githubusercontent.com/14332263/27559177-9399ad22-5a8d-11e7-9bef-5f00d00694c6.png)

**Comment by yobyot** [comment]
Inadvertently closed by hitting the wrong button. ;-)

**Comment by hoetz** [comment]
This happens to me as well but it only came up in the last month or so. When I hit F10 really fast the session almost always crashes. 

Here is my EditorServices.log [https://gist.github.com/hoetz/ebc0cdf889ce86ec64022ed0614b14d1](https://gist.github.com/hoetz/ebc0cdf889ce86ec64022ed0614b14d1)

This is my vscode-powershell.log

12/6/2018 11:44:30 AM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
12/6/2018 11:44:30 AM [NORMAL] - Language server starting --
12/6/2018 11:44:30 AM [NORMAL] -     exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
12/6/2018 11:44:30 AM [NORMAL] -     args: C:\Users\flo\.vscode\extensions\ms-vscode.powershell-1.10.0\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.10.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\flo\.vscode\extensions\ms-vscode.powershell-1.10.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\flo\.vscode\extensions\ms-vscode.powershell-1.10.0\logs\1544093070-323e7eab-7c56-4501-b9e3-09020ca276001544093066202\EditorServices.log' -SessionDetailsPath 'C:\Users\flo\.vscode\extensions\ms-vscode.powershell-1.10.0\sessions\PSES-VSCode-6932-919620' -FeatureFlags @()
12/6/2018 11:44:30 AM [NORMAL] - powershell.exe started, pid: 10624
12/6/2018 11:44:34 AM [NORMAL] - Language server started.
12/6/2018 11:44:34 AM [NORMAL] - {"languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_qth3mhkg.5mp","debugServiceTransport":"NamedPipe","status":"started","debugServicePipeName":"\\\\.\\pipe\\PSES_305zfmut.yua"}
12/6/2018 11:44:34 AM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_qth3mhkg.5mp...
12/6/2018 11:44:34 AM [NORMAL] - Language service connected.
12/6/2018 11:46:15 AM [NORMAL] - powershell.exe terminated or terminal UI was closed
12/6/2018 11:49:07 AM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
12/6/2018 12:46:23 PM [NORMAL] - Shutting down language client…

## Environment Information ##

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17134 |
| VSCode | 1.29.1|
| PowerShell Extension Version | 1.10.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17134.407|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17134.407|
|BuildVersion|10.0.17134.407|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

**Comment by TylerLeonhardt** [comment]
@hoetz I think your issue should go into #1183 like you did.

@yobyot are you still having your original issue on macOS
