### ISSUE TITLE
Error Command 'PowerShell.*' not found

### ISSUE THREAD

**Issue by kensel** [PowerShell/vscode-powershell#741]
### System Details

- Operating system name and version: Windows 10 enterprise eval
- VS Code version: 1.12.1
- PowerShell extension version: 1.0
- Output from `$PSVersionTable`: 

```
PS C:\Users\> code -v
1.12.1
f6868fce3eeb16663840eb82123369dec6077a9b
PS C:\Users\> $pseditor.EditorServicesVersion
PS C:\Users\> code --list-extensions --show-versions
formulahendry.code-runner@0.6.16
joffreykern.markdown-toc@1.4.0
ms-vscode.PowerShell@1.0.0
yzhang.markdown-all-in-one@0.5.2
PS C:\Users\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Using the PowerShell tools by Ctrl + Shift + P but it gives the error the command is not found for the powershell commands as seen in the image.

![2017-05-13_16h54_01](https://cloud.githubusercontent.com/assets/6167437/26029909/b9e7da82-37fe-11e7-8543-efddaa107ddd.png)

This was a clean install of the evaluation of Windows 10 Enterprise 170317 with updates installed.  It is installed in VMware virtual machine with VMware tools.

### Attached Logs

Tried to generate the logs but no logs were generated.  Will try disabling the other installed extensions.

**Comment by daviwil** [comment]
Hey @kensel, generally you see these errors when the PowerShell extension hasn't been loaded yet.  When you tried running these commands, did you have a PowerShell file open?

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
