### ISSUE TITLE
Git merge doesn't understand UTF16 and that's what PSD1 files are created as.

### ISSUE THREAD

**Issue by andrewducker** [PowerShell/vscode-powershell#745]
### System Details

1.12.1
f6868fce3eeb16663840eb82123369dec6077a9b

Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      0      0

ms-vscode.PowerShell@1.0.0

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

### Issue Description

Git comparisons of PSD1 files show nonsense characters.  I believe this is because PSD1 files are automatically generated as UTF-16 LE, and Git doesn't recognise this as a text format.
If VSCode is going to be the default tool for editing Powershell files then it should be able to diff powershell module files.

### Attached Logs
![image](https://cloud.githubusercontent.com/assets/91378/26066549/331a69ba-398f-11e7-9cbc-daee22c7278f.png)

**Comment by rkeithhill** [comment]
I suggest you file this issue on https://GitHub.com/powershell/powershell since that is where the `New-ModuleManifest` command is implemented.  Also, if you use the PowerShell extension command to create a new module template, it will create the PSD1 file using UTF8.  :-)

**Comment by andrewducker** [comment]
Thanks.

Raised https://github.com/PowerShell/PowerShell/issues/3789 and https://github.com/Microsoft/vscode/issues/26722
