### ISSUE TITLE
Problems getting the debug system to behave

### ISSUE THREAD

**Issue by johnbeh** [PowerShell/vscode-powershell#746]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

PS C:\JHScripts> code -v

1.12.1
f6868fce3eeb16663840eb82123369dec6077a9b
PS C:\Windows\System32> $pseditor.EditorServicesVersion


Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      0      0


PS C:\Windows\System32> code --list-extensions --show-versions

ms-vscode.PowerShell@1.0.0
PS C:\Windows\System32> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Windows\System32>
```

### Issue Description

DEBUG  

I can't persuade the F5 on the standard install to behave anything like sensibly.  If I have ONE PS1 file open it will run sensibly.

If I have a second file open it doesn't run at all. The little blue line just under the DEBUG line and above the VARIABLES section moves back and forward for ever.  I've given it 10 minutes to run a script that the POWESHELL ISE runs in 2 or 3 seconds.

It seems  that this is solved by changing the Version in Launch.json from 
"version": "0.2.0", to  
"version": "0.1.0",

BUT this can't possibly be the right answer although it suffices for the moment

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
You shouldn't have a different experience when opening more than one file, the debugger will only launch the currently active file when using the "current file" configuration.  Can you attach logs from a session where the debugger exhibits this behavior?

https://github.com/PowerShell/vscode-powershell#reporting-problems

**Comment by daviwil** [comment]
@johnbeh I'd like to take a look at this issue soon, could you capture and attach (or send via email) your logs so that I can take a look?

https://github.com/PowerShell/vscode-powershell#reporting-problems

**Comment by johnbeh** [comment]
Sorry not to have commented earlier.
In recent days I have **not** been able to reproduce this.
I **think** it was related to the issue of "long running formatting" which has been raised by other people and has been solved.
Part of the problem is that I am a complete novice with VSCode and didn't realise what the system was doing at the time.

Just as an aside - I am very pleased and grateful for the tremendous efforts that are going on with this project.

Thank you all very much.

Regards

John

**Comment by daviwil** [comment]
Thanks for the kind words John, glad the issue has been resolved for you!  Let us know if you see anything similar again :)
