### ISSUE TITLE
HOST is not available in Debug Scriptblocks

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/vscode-powershell#747]
I set a breakpoint with an action like:
Set-PSBreakpoint -Script C:\temp\f1.ps1 -Line 5 -Action {if ($n -eq 4) {write-host -ForegroundColor red "************"}}

In ISE - this works
In VSCode - it does not

**Comment by daviwil** [comment]
Thanks!  I'll take a look.

**Comment by rkeithhill** [comment]
This works if you use `continue` e.g.:
![image](https://cloud.githubusercontent.com/assets/5177512/26081939/68844bb6-398a-11e7-9850-100eea9469fd.png)

**Comment by daviwil** [comment]
Strangely this doesn't seem to be 100% reproable, I just watched Jeffrey try it a couple times and it worked part of the time.  He'll send logs the next time he sees it.

**Comment by TylerLeonhardt** [comment]
An old issue that might be fixed

**Comment by SydneyhSmith** [comment]
I am having trouble reproducing this so I will close as fixed for now, and will re-open if this occurs again. Thanks!
