### ISSUE TITLE
Ctrl+Alt+ keybindings should not be used by default under Windows

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#75]
Saw this in the vs code console.

`Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  40999  for  PowerShell.OpenInISE`

![image](https://cloud.githubusercontent.com/assets/67258/12616792/d8bc1c18-c4da-11e5-9e88-9aa67da4ec84.png)

cc: @janegilring

**Comment by daviwil** [comment]
I recently filed an issue for this here: https://github.com/PowerShell/vscode-powershell/issues/71

I wonder if it even matters that much.  I don't know why they decided Ctrl+Alt was bad on Windows except for that they might overshadow built-in keybindings.  I don't see anything happen when I use that keybinding.

**Comment by dfinke** [comment]
Oops, should have searched the issues before posting

**Comment by daviwil** [comment]
Don't worry man ;)

**Comment by evandrocoan** [comment]
> I don't know why they decided Ctrl+Alt was bad on Windows except for that they might overshadow built-in keybindings

On windows I use several of the `Ctrl+Alt+` key available for system wide shortcuts/operations. So I expect my applications do not require them, as they are already taken by me for my stuff.
