### ISSUE TITLE
Keybinding for PowerShellFindModule (ctrl+k ctrl+f) conflicts with vscode defaults

### ISSUE THREAD

**Issue by ajansveld** [PowerShell/vscode-powershell#751]
### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.12.2
- PowerShell extension version: 1.0.0
- Output from `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When using the default keyboard shortcut for Format Selection (ctrl+k ctrl+f) in a PowerShell script with selected text, the PowerShellFindModule action launches instead.

Suggest removing the keybinding for PowerShellFindModule or setting it to an unused key combination (e.g. ctrl+k ctrl+n) in package.json.

**Comment by daviwil** [comment]
Great point, I'll change that!  This action probably shouldn't even have a keybinding since it's not something that would be used very frequently.
