### ISSUE TITLE
Stuck on "Starting Powershell..."

### ISSUE THREAD

**Issue by jpalo** [PowerShell/vscode-powershell#752]
### System Details
- OS Version: WIn 10 (Windows_NT ia32 10.0.16193)
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- PowerShell extension version: 1.0.0
- Output from `$PSVersionTable`:

```
PS C:\Users\jussi> code -v
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de
PS C:\Users\jussi> $pseditor.EditorServicesVersion
PS C:\Users\jussi> code --list-extensions --show-versions
DotJoshJohnson.xml@1.7.0
HookyQR.beautify@1.0.2
ms-vscode.PowerShell@1.0.0
PS C:\Users\jussi> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16193.1001
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16193.1001
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

1. Start VS Code
2. Either open existing .ps1 file OR switch editor mode from Plain Text to Powershell (from bottom right in VS Code window)
3. Terminal window shows "Starting PowerShell..." and gets stuck there
4. You can kill terminal to recover, but haven't figured way to get past the actual issue

Tried updating to latest PowerShell 6.0.0 beta, but it made no difference. Tried also disable all other extension, no effect.

![image](https://cloud.githubusercontent.com/assets/6917905/26141679/bf4d1bb0-3ae5-11e7-96a3-a775b3be8857.png)

### Attached Logs
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1006772/logs.zip)

**Comment by demyte** [comment]
Same issue. Details:

*WINDOWS*
Windows 10 16188.rs_prerelease.170430-1928

*PORWERSHELL*
PSVersion                      5.1.16188.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16188.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

*CODE*
Version 1.13.0-insider
Commit 9843623452cbb9eea0c57e2ccc371b4d2c3c2d37
Date 2017-05-17T06:12:09.634Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

*POWERSHELL EXTENSION*
v1.0.0

**Comment by bgelens** [comment]
Probably the same as #742 
Please check workaround https://github.com/PowerShell/vscode-powershell/issues/742#issuecomment-301915916

**Comment by jpalo** [comment]
Thanks, same as [#742](https://github.com/PowerShell/vscode-powershell/issues/742) and that workaround works in my case ase well, so closing.

**Comment by daviwil** [comment]
Thanks Ben! :)
