### ISSUE TITLE
F8 selection on code

### ISSUE THREAD

**Issue by Graham-Beer** [PowerShell/vscode-powershell#754]
### System Details

- Operating system name and version: Windows 10 Latest version
- VS Code version: 1.12.2
- PowerShell extension version: 1.0
- Output from `$PSVersionTable`:
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      0      0
code --list-extensions --show-versions
AdamCaviness.theme-monokai-dark-soda@0.0.5
akamud.vscode-theme-onelight@1.3.2
anoff.theme-monokai-light@1.0.3
DougFinke.vscode-PSStackoverflow@0.0.2
dustinsanders.an-old-hope-theme-vscode@2.0.0
formulahendry.code-runner@0.6.16
gerane.Theme-monokai-best@0.0.2
jmrog.vscode-nuget-package-manager@1.1.3
karyfoundation.theme-karyfoundation-themes@12.0.0
Kipters.codeshell@0.2.2
ms-vscode.csharp@1.9.0
ms-vscode.PowerShell@1.0.0
remcoros.startanyshell@0.3.1
robertohuertasm.vscode-icons@7.7.0

$PSVersionTable
As Above
```

### Issue Description

When highlighting more than one line of PowerShell code in VS Code and pressing F8, the integrated console try to run each line separately. So i have to save the code in a file and run the file from the prompt.  

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Hey Graham, check your keybindings and see if you have F8 bound to `workbench.action.terminal.runSelectedText`.  If so, remove that binding so that the PowerShell extension's `PowerShell.RunSelection` binding gets used.

**Comment by Graham-Beer** [comment]
Hi David, 
Thank you for getting back so quickly.

I've checked and its in the list but not bound to F8 : 
  // A set of command IDs whose keybindings will not be sent to the shell and instead always be handled by Code. This allows the use of keybindings that would normally be consumed by the shell to act the same as when the terminal is not focused, for example ctrl+p to launch Quick Open.
  "terminal.integrated.commandsToSkipShell": [
    "editor.action.toggleTabFocusMode",
    "workbench.action.debug.continue",
    "workbench.action.debug.pause",
    "workbench.action.debug.restart",
    "workbench.action.debug.run",
    "workbench.action.debug.start",
    "workbench.action.debug.stop",
    "workbench.action.focusActiveEditorGroup",
    "workbench.action.focusFirstEditorGroup",
    "workbench.action.focusSecondEditorGroup",
    "workbench.action.focusThirdEditorGroup",
    "workbench.action.openNextRecentlyUsedEditorInGroup",
    "workbench.action.openPreviousRecentlyUsedEditorInGroup",
    "workbench.action.quickOpen",
    "workbench.action.showCommands",
    "workbench.action.terminal.clear",
    "workbench.action.terminal.copySelection",
    "workbench.action.terminal.focus",
    "workbench.action.terminal.focusAtIndex1",
    "workbench.action.terminal.focusAtIndex2",
    "workbench.action.terminal.focusAtIndex3",
    "workbench.action.terminal.focusAtIndex4",
    "workbench.action.terminal.focusAtIndex5",
    "workbench.action.terminal.focusAtIndex6",
    "workbench.action.terminal.focusAtIndex7",
    "workbench.action.terminal.focusAtIndex8",
    "workbench.action.terminal.focusAtIndex9",
    "workbench.action.terminal.focusNext",
    "workbench.action.terminal.focusPrevious",
    "workbench.action.terminal.kill",
    "workbench.action.terminal.new",
    "workbench.action.terminal.paste",
    "workbench.action.terminal.runActiveFile",
    "workbench.action.terminal.runSelectedText",
    "workbench.action.terminal.scrollDown",
    "workbench.action.terminal.scrollDownPage",
    "workbench.action.terminal.scrollToBottom",
    "workbench.action.terminal.scrollToTop",
    "workbench.action.terminal.scrollUp",
    "workbench.action.terminal.scrollUpPage",
    "workbench.action.terminal.toggleTerminal"
  ],

**Comment by daviwil** [comment]
That list comes from your user settings, it doesn't reflect your keybindings.  Try opening the Keyboard Shortcuts view with `File -> Preferences -> Keyboard Shortcuts` and then search for `F8` or `workbench.action.terminal.runSelectedText`.

**Comment by dfinke** [comment]
Hey @Graham-Beer here's mine.

![image](https://cloud.githubusercontent.com/assets/67258/26158542/2bbd0464-3aea-11e7-9e23-acd8e458cfed.png)


hth

**Comment by Graham-Beer** [comment]
Hi Doug,
I have the same in mine as well. Does it matter if the source is different ?

![image](https://cloud.githubusercontent.com/assets/12196171/26158766/a21ab500-3b14-11e7-8dc0-820e2162cfdf.png)

**Comment by Graham-Beer** [comment]
Actually I have two, one for 'user' and one for 'default'

![image](https://cloud.githubusercontent.com/assets/12196171/26158839/e1995286-3b14-11e7-9c14-994d0d1ab34d.png)

**Comment by daviwil** [comment]
That's the one that is causing the problem, if you remove the binding for F8 there it will start working correctly.

**Comment by Graham-Beer** [comment]
For the user ?

**Comment by daviwil** [comment]
Yep

**Comment by Graham-Beer** [comment]
Awesome, removed the 'User' Entry and tested, working like a dream ! Thank you David and Doug for helping so quickly :)

**Comment by daviwil** [comment]
No problem Graham!
