### ISSUE TITLE
Format Document is removing tabs

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#758]
Does this in both Editions of Code.

### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.12.2 (and Insiders 1.13.0
- PowerShell extension version: 1.0.0
- Output from `$PSVersionTable`:

```
C:\WINDOWS\system32> code -v
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de
C:\WINDOWS\system32> $pseditor.EditorServicesVersion
C:\WINDOWS\system32> code --list-extensions --show-versions
donjayamanne.githistory@0.2.0
eamodio.gitlens@3.4.9
gerane.Theme-Blackboard@0.0.2
gerane.Theme-earthsong-light@0.0.2
karyfoundation.theme-karyfoundation-themes@12.0.0
LaurentTreguier.vscode-simple-icons@1.2.2
michelemelluso.gitignore@1.0.1
ms-mssql.mssql@1.0.0
ms-vscode.PowerShell@1.0.0
ms-vscode.Theme-TomorrowKit@0.1.4
ms-vscode.wordcount@0.1.0
sensourceinc.vscode-sql-beautify@0.0.4
Shan.code-settings-sync@2.7.0
swyphcosmo.spellchecker@1.2.13
Tyriar.theme-sapphire@0.2.1
C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

I am experiencing a problem with...tabs/spaces when using "format document". If you go the command pallete and run format document, some of the tabs (not all) are converted to spaces.

![tabsspaces](https://cloud.githubusercontent.com/assets/11204251/26177764/ad07d798-3b20-11e7-97c4-252191aad172.gif)

**Comment by daviwil** [comment]
Thanks for the report!  This is already covered by #530 so we'll keep tracking it there.  Great GIF though, I'll steal that for the other issue :)
