### ISSUE TITLE
Syntax highlighting for variables incorrect where ? is treated as token separator

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/vscode-powershell#759]
$foo?bar = 1

"$foo?bar"

only $foo is highlighted as a variable, this causes confusion to the customer as PowerShell treats $foo?bar as the variable (which is allowed)

PSReadline highlights correctly

**Comment by daviwil** [comment]
This issue was moved to PowerShell/EditorSyntax#49

**Comment by daviwil** [comment]
Thanks Steve!  Moved it to the proper repo.
