### ISSUE TITLE
Update default launch.json to use $file

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#76]
The VS Code team has fixed the $file variable so that it always gets updated to the most recently opened file path when the debugger is started.  We should use this in the default launch configuration so that it's easier for users to get started debugging their scripts.

https://github.com/Microsoft/vscode/issues/1667

**Comment by rkeithhill** [comment]
I can make this update.  Any word on when the insiders update for the next VSCode release will drop?  I thought they were shooting for the 26th?

**Comment by daviwil** [comment]
Thanks Keith!  I think they're doing their final validation now.  I don't know when it's going to happen, but all of their testing work items just got finished up today:

https://github.com/Microsoft/vscode/issues?page=1&q=label%3Atestplan-item+milestone%3A%22Jan+2016%22

I'm guessing we'll see the preview drop in the next few days.
