### ISSUE TITLE
Powershell Integrated Console hangs when starting

### ISSUE THREAD

**Issue by namngo** [PowerShell/vscode-powershell#761]
### System Details

- Operating system name and version: Windows 10 x64 build 16193.
- VS Code version: 1.12.2
- PowerShell extension version: v1.0.0
- Output from `$PSVersionTable` (From Window's powershell, not VSCode):
>$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16193.1001
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16193.1001
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am experiencing a problem with Powershell Integrated Console. My Integrated Console hangs when started. It will say: "Starting Powershell..." and then keeps hanging there, I can't enter commands, nor see any output. 

Same thing happens when I start a debugging session for Powershell. I can step in, step out, step over my code. I can see local variables value. However, since the Integrated Console is hanging, I can't execute any statements, nor I can see my script's output.

Here's a screenshot of the problem: [https://i.stack.imgur.com/zhMl2.png](https://i.stack.imgur.com/zhMl2.png)

I also posted to StackOverflow with no result: [http://stackoverflow.com/questions/44012931/vscode-powershell-integrated-terminal-hangs-when-starting](http://stackoverflow.com/questions/44012931/vscode-powershell-integrated-terminal-hangs-when-starting)

### Attached Logs

I emailed daviwil [at] microsoft.com the log.

Thanks,
Nam

**Comment by daviwil** [comment]
This is an issue in the latest Windows Insider builds, see issue #742.  The workaround that should unblock you for now is here:  https://github.com/PowerShell/vscode-powershell/issues/742#issuecomment-301915916
