### ISSUE TITLE
Comment help snippet should optionally allow placement inside of function definition

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#763]
It seems there are a number of people requesting the ability for our new comment help snippet to place the help string inside of the function body.  We should enable this to work there based on where the user is typing (above function, inside of function above param block, or bottom of function).  Better to be smart about it and place it where the user is typing than making them set an option.

**Comment by pcgeek86** [comment]
You beat me to filing this bug. :)

**Comment by rkeithhill** [comment]
Choice is good. :-)

**Comment by daviwil** [comment]
PSScriptAnalyzer can already do it, we've just got to wire it up :)

https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/ProvideCommentHelp.md
