### ISSUE TITLE
Integrated Console hanging...

### ISSUE THREAD

**Issue by Graham-Beer** [PowerShell/vscode-powershell#766]
### System Details

- Operating system name and version: Windows 10 Build 16199.rs_prerelease.170513-2252
- VS Code version: 1.12.2
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```
PS C:\Users\gbeer> code -v
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de
PS C:\Users\gbeer> $pseditor.EditorServicesVersion
PS C:\Users\gbeer> code --list-extensions --show-versions
AdamCaviness.theme-monokai-dark-soda@0.0.5
akamud.vscode-theme-onelight@1.3.2
anoff.theme-monokai-light@1.0.3
DougFinke.vscode-PSStackoverflow@0.0.2
dustinsanders.an-old-hope-theme-vscode@2.0.0
formulahendry.code-runner@0.6.16
gerane.Theme-monokai-best@0.0.2
jmrog.vscode-nuget-package-manager@1.1.3
karyfoundation.theme-karyfoundation-themes@12.1.0
Kipters.codeshell@0.2.2
ms-vscode.csharp@1.9.0
ms-vscode.PowerShell@1.1.0
remcoros.startanyshell@0.3.1
robertohuertasm.vscode-icons@7.7.0
sapegin.Theme-SquirrelsongLight@0.0.10
uloco.theme-bluloco-light@1.2.0
PS C:\Users\gbeer> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16199.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16199.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

Integrated console does not load, just hangs on 'PowerShell Starting'

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by bgelens** [comment]
Same as #742. See workaround https://github.com/PowerShell/vscode-powershell/issues/742#issuecomment-301915916

**Comment by Graham-Beer** [comment]
Thanks bgelens, missed that one :)

**Comment by daviwil** [comment]
Thanks Ben!
