### ISSUE TITLE
Built-in PowerShell snippets can't be tabbed through

### ISSUE THREAD

**Issue by lipkau** [PowerShell/vscode-powershell#767]
### System Details
- Operating system name and version: `10.0.14393.1066`
- VS Code version: `1.13.0-insider    613724d43b4d50f6052bbb8007447ca96e687f26`
- PowerShell extension version: `ms-vscode.PowerShell@1.1.0`

### Issue Description
When using a snippet from the extension, the placeholder are missing and the tab jumps are not working.
Screen recording of the problem: 
![2017-05-19_13-16-38](https://cloud.githubusercontent.com/assets/4992870/26246968/06bf7e2c-3c9c-11e7-8bd6-9a653472be9a.gif)

**Comment by PowerSchill** [comment]
I can confirm the same issue on MacOS

ProductName:    Mac OS X
ProductVersion: 10.12.5
BuildVersion:   16F73

1.13.0-insider
ec76a9fc5146b822cdb14b982ac3e5b470dd646a

**Comment by daviwil** [comment]
Argh, they probably changed something again, I'll look into it.
