### ISSUE TITLE
Please add extra functionality to $pseditor similar to $psise

### ISSUE THREAD

**Issue by brwilkinson** [PowerShell/vscode-powershell#773]
I would like to save files using the command line in VSCODE.

Please add $psise.CurrentFile.SaveAs()

**Comment by PowerSchill** [comment]
Tagging on to this request, I would also like to be able to get information about VSCode as well. Specifically the version of VSCode.

**Comment by brwilkinson** [comment]
Just to add a comment.

The SaveAs() method, I believe would be on the Type: Microsoft.PowerShell.EditorServices.Extensions.FileContext

$psEditor.GetEditorContext().currentfile | gm

**Comment by tylerl0706** [comment]
https://github.com/PowerShell/PowerShellEditorServices/pull/590 we've added `.Save`which will be out this week in 1.6.0. That said, a SaveAs where you pass a string as the name for untitled files might be interesting.

I'll keep this open for that... but this issue should be moved to https://github.com/powershell/powershelleditorservices/

**Comment by rjmholt** [comment]
https://github.com/PowerShell/vscode-powershell/pull/1261 Adds `SaveAs()` support. Please give it a try and open a new issue if you have feedback.

**Comment by tylerl0706** [comment]
This is out the door already :)

**Comment by rjmholt** [comment]
The version information is the next thing, although maybe not as high priority. The only tricky part is we will need to define a way for arbitrary editors to provide information about themselves. Very possible, but we should consult maintainers for Atom, Sublime and any other editor front-ends.

**Comment by brwilkinson** [comment]
@rjmholt is this one merged, however not released?

https://github.com/PowerShell/vscode-powershell/pull/1305

**Comment by rjmholt** [comment]
@brwilkinson Yep, precisely that.

**Comment by rjmholt** [comment]
It is possible to grab the most recent build from CI if you'd like it.

**Comment by rjmholt** [comment]
https://ci.appveyor.com/api/buildjobs/94ytj9luo738rls2/artifacts/PowerShell-insiders.vsix
