### ISSUE TITLE
Pressing enter does not cause the prompt to be redisplayed

### ISSUE THREAD

**Issue by PowerSchill** [PowerShell/vscode-powershell#774]
### System Details

- Windows 10 Build 10586
- VS Code version: 1.13.0
- PowerShell extension version: 1.1.0

Name                           Value
----                           -----
PSVersion                      5.0.10586.672
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.672
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

When I hit enter on a blank line in the integrated console is does not redisplay the prompt. Instead it waits for more typing. See screencast at https://www.screencast.com/t/2KmLaAeAVmna

**Comment by daviwil** [comment]
Thanks Mark!
