### ISSUE TITLE
Change "Starting PowerShell" message when Integrated Console starts up

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/vscode-powershell#777]
Integrated terminal is awesome, especially when it is PowerShell.
But it always shows "Starting PowerShell..." even if is started.

![image](https://cloud.githubusercontent.com/assets/12897753/26291248/9fff902e-3eca-11e7-8c44-74bd458a274e.png)

We would like our awesome editor to its maximum perfection.

### System Details

- Operating system name and version: Windows 10 (10586.916)
- VS Code version: 1.10.2

- PowerShell extension version: 1.0.0
- Output from `$PSVersionTable`: 5.0.10586.672

**Comment by daviwil** [comment]
That's because "Starting PowerShell..." is output.  If you type "Get-Process", the output will push it out of the screen.  Are you asking for it to never be displayed?

**Comment by PowerSchill** [comment]
He might be referring to #742

**Comment by daviwil** [comment]
That's what I thought at first, but he's not using a Windows Insider build.

**Comment by rkeithhill** [comment]
You can put `Clear-Host` in your `C:\Users\<username>\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1` and that will clear this message when the profile script is processed.

**Comment by daviwil** [comment]
I wonder if more people are annoyed by the message?  I considered that when I added it, but I thought that maybe having it there was helpful to indicate that you're in the Integrated Console.

**Comment by rkeithhill** [comment]
Maybe it's the transient nature of the message that might be teensy bit confusing.  Taking a page from the powershell.exe:
![image](https://cloud.githubusercontent.com/assets/5177512/26361968/d06aee6e-3f99-11e7-8062-e21b7768b083.png)
What if you modified the message to:
```
PowerShell Integrated Console <version #?>
PS C:\> 
```

**Comment by daviwil** [comment]
Yeah, I think that's the right way to do it.

**Comment by kvprasoon** [comment]
or We can have the Starting PowerShell message in the Status bar, where we see icons of error and warning !!! (and clear it once started).

![image](https://cloud.githubusercontent.com/assets/12897753/26385374/d9502120-405c-11e7-940d-aa9a2534e607.png)

**Comment by rkeithhill** [comment]
The status bar message already exists:
![image](https://cloud.githubusercontent.com/assets/5177512/26385432/e775c576-3ffc-11e7-86ac-e4dee42d13b0.png)
The "want", as @daviwil says above, is to provide a way to help folks know when they are in the `PowerShell Integrated Console` vs a normal `PowerShell` terminal.

**Comment by kvprasoon** [comment]
@rkeithhill  my bad, I didn't noticed it. Then I think that is more than sufficient .

**Comment by rkeithhill** [comment]
@kvprasoon Does the 1.2.1 release address the issue sufficiently to close it?

**Comment by kvprasoon** [comment]
Thanks for addressing this, This is address elegantly in 1.2.1
