### ISSUE TITLE
Extension host crashes after closing Integrated Console terminal

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#782]
### System Details

- Operating system name and version: Windows 10 Pro
- VS Code version: 1.13.0-insider
- PowerShell extension version: 5.1
- Output from `$PSVersionTable`:

```
C:\WINDOWS\system32> code -v
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de
C:\WINDOWS\system32> $pseditor.EditorServicesVersion
C:\WINDOWS\system32> code --list-extensions --show-versions
donjayamanne.githistory@0.2.0
dustinsanders.an-old-hope-theme-vscode@2.0.0
eamodio.gitlens@3.4.9
gerane.Theme-Blackboard@0.0.2
jprestidge.theme-material-theme@1.0.1
LaurentTreguier.vscode-simple-icons@1.2.2
michelemelluso.gitignore@1.0.1
ms-mssql.mssql@1.0.0
ms-vscode.PowerShell@1.1.0
ms-vscode.Theme-TomorrowKit@0.1.4
ms-vscode.wordcount@0.1.0
sensourceinc.vscode-sql-beautify@0.0.4
Shan.code-settings-sync@2.8.0
swyphcosmo.spellchecker@1.2.13
Tyriar.theme-sapphire@0.2.1
C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

In cases where the integrated terminal is causing code to run differently (can't explain fully but it does not compared to PowerShell.exe), I want to close the PowerShell Integrated Terminal. 

Whenever I delete that from the terminal and perform an action that requires the extension to perform an action (intellisense, ect.) I get a prompt at the top of the window and am forced to reload Code.

I'm not sure if there is a consensus on this but if I'm not using the Integrated session I'd prefer it to not start at all.

![vscode_ps](https://cloud.githubusercontent.com/assets/11204251/26449218/a0d3b662-4116-11e7-8a2c-5d2044533d4a.gif)

[Logs.zip](https://github.com/PowerShell/vscode-powershell/files/1028869/Logs.zip)

**Comment by daviwil** [comment]
There seems to be a bug here in general, thanks for letting me know about it.  You can disable loading of the integrated console entirely by using this setting:

```json
"powershell.startAutomatically": false
```

Note that this will disable all language features so IntelliSense, etc won't work while this is set to false.  Another option is just to not show the PowerShell Integrated Console when you first open a PowerShell file:

```json
"powershell.integratedConsole.showOnStartup": false
```

Language features will still be available with this setting.
