### ISSUE TITLE
psedit is missing when in a "remote" session to a container or VM

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#789]
Seems that we might not be handling connections through named pipes or VMBus correctly. Also need to check SSH remoting to make sure it works.

/cc @alexandair

**Comment by tylerl0706** [comment]
SSH remoting works as of this PR: https://github.com/PowerShell/PowerShellEditorServices/pull/599

**Comment by tylerl0706** [comment]
Autocomplete is kinda busted when remoting into Containers... so "pse" does not autocomplete to "psedit"... but that also happens in powershell.exe.

That said, I can confirm that psedit DOES work in a container and I was able to open a file, edit it, and debug it.
