### ISSUE TITLE
Feature request: add the ability to select text and execute that line

### ISSUE THREAD

**Issue by codemonkeychris** [PowerShell/vscode-powershell#8]

**Comment by daviwil** [comment]
Yep!  I'd like to see this too.  If we get the persistent REPL #10 then we'd just need an API method that can send a line of text to the REPL for execution.

**Comment by daviwil** [comment]
Just realized that this was still open.  This feature was added in the 0.2.0 release that went out yesterday. Select some PowerShell script an press F8 to run it.  Let me know what you think!
