### ISSUE TITLE
Add configuration setting for console width in REPL

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#80]
We should have a configuration setting that allows the user to choose their own console width for the REPL experience if they don't like the default value.

**Comment by rkeithhill** [comment]
BTW output that is generated by the script under execution seems to take advantage of the full width of the debug console. Where I notice output wrapping at 80 chars is when I execute a command from the debug console prompt.  Perhaps that would be a more localized fix (and makes this a bit more corner case)?

**Comment by rjmholt** [comment]
Closing this now that we've moved to PSRL
