### ISSUE TITLE
Feature-Request -Built in method to codesign PS code.

### ISSUE THREAD

**Issue by daGup** [PowerShell/vscode-powershell#805]
This is something small and just a pet peeve I guess.  Is it possible to add in an option to quickly sign PS code.  Its a feature in some other PS Editors and just saves some boilerplate code I always have to run.  Ability to sign on save that sort of thing.

**Comment by daviwil** [comment]
Thanks for the request!  We're tracking this issue over at #548 so I'll close this issue in favor of that one.  I've got some thoughts on this, I'll add a comment over there.
