### ISSUE TITLE
Restarting PowerShell session doesn't retain PowerShell Core selection

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#807]
For some reason when I select one of the new PowerShell Core entries from the session menu, let the new session load, then try to reload it, it goes back to selecting the built-in Windows PowerShell install.  I would expect it to reload the session that was selected most recently.

**Comment by rkeithhill** [comment]
Same thing happens when you switch to built-in x86.  :-(

**Comment by daviwil** [comment]
Weird...  Not sure how that broke!

**Comment by daviwil** [comment]
In other words, I don't think your changes caused it :)

**Comment by rkeithhill** [comment]
It's like you're a mind reader.  :-p

**Comment by daviwil** [comment]
I'm pretty sure it didn't, the more likely culprit is the changes around adoption of the newer vscode-languageclient library, that broke other stuff too.

**Comment by daviwil** [comment]
Ok, I'm wondering if this ever worked...

https://github.com/PowerShell/vscode-powershell/blob/master/src/session.ts#L713

**Comment by rkeithhill** [comment]
Guess that should be passing in the current sessionConfiguration, eh?

**Comment by daviwil** [comment]
Yep.  I'm about to submit a PR
