### ISSUE TITLE
Integrated Console hanging on switch to PS 6.1 only

### ISSUE THREAD

**Issue by Graham-Beer** [PowerShell/vscode-powershell#814]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
S C:\Users\gbeer> code -v

1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de
PS C:\Users\gbeer> $pseditor.EditorServicesVersion


Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      0      0


PS C:\Users\gbeer> code --list-extensions --show-versions

AdamCaviness.theme-monokai-dark-soda@0.0.5
akamud.vscode-theme-onelight@1.3.2
anoff.theme-monokai-light@1.0.3
DougFinke.vscode-PSStackoverflow@0.0.2
dustinsanders.an-old-hope-theme-vscode@2.0.0
formulahendry.code-runner@0.6.17
gerane.Theme-monokai-best@0.0.2
jmrog.vscode-nuget-package-manager@1.1.3
karyfoundation.theme-karyfoundation-themes@14.0.0
Kipters.codeshell@0.2.2
ms-vscode.csharp@1.10.0
ms-vscode.PowerShell@1.2.0
remcoros.startanyshell@0.3.1
robertohuertasm.vscode-icons@7.8.1
sapegin.Theme-SquirrelsongLight@0.0.10
Tyriar.shell-launcher@0.1.1
uloco.theme-bluloco-light@1.2.0
PS C:\Users\gbeer> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.16199.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16199.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\gbeer>
```

### Issue Description

I am experiencing a problem with...
I'm running the latest windows 10 insider preview, and to get PowerShell 5.1 integrated console to work i've added '[System.Console]::OutputEncoding = [System.Text.Encoding]::ASCII' to my profile. With the new upgrade this still works fine, however if i switch to 6.1 the integrated console hangs again. 

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Hey Graham, the problem here is that PowerShell Core 6 has a separate set of profile scripts than Windows PowerShell does so you'll have to use the same workaround in that version's $profile too.

**Comment by Graham-Beer** [comment]
Hi David.
Looks like the profile is in C:\Users\gbeer\Documents\PowerShell and needs a Microsoft.PowerShell_profile.ps1 file. I've added in [System.Console]::OutputEncoding = [System.Text.Encoding]::ASCII but still hangs.

**Comment by Graham-Beer** [comment]
Sorted did '$PROFILE | Format-List -Force' and found for all users it required a profile.ps1. Thanks for your help again David.

**Comment by daviwil** [comment]
For the PowerShell extension the CurrentUserCurrentHost profile is `Microsoft.VSCode_profile.ps1`, so that would explain why putting the workaround in `Microsoft.PowerShell_profile.ps1` didn't work.  Your solution to put it in `profile.ps1` is fine, though!

Closing this issue since the problem has been resolved, thanks!
