### ISSUE TITLE
vertical scrollbar is missing when host screen buffer size is larger than windows width

### ISSUE THREAD

**Issue by jeernest** [PowerShell/vscode-powershell#817]
### System Details

- Windows 7 Enterprise
- VS Code version: 1.12.2, 19222cdc84ce72202478ba1cec5cb557b71163de
- PowerShell extension version: 1.0
- Output from `$PSVersionTable`:

```powershell


PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      1      0      0

idleberg.hopscotch@0.1.4
ms-vscode.csharp@1.10.0
ms-vscode.PowerShell@1.1.0
qub.qub-msbuild@0.6.3
```

### Issue Description

my script sets buffer size in following way:
$host.UI.RawUI.BufferSize = New-Object System.Management.Automation.Host.Size(8192,50)
then it writes some long string to output and the current result is that the output is truncated and it's not possible to the whole message

### Attached Logs

Github doesn't allow to drop .zip file, let me know if you need them

**Comment by daviwil** [comment]
Thanks for the report!  Not sure what's causing this, will investigate.

**Comment by SydneyhSmith** [comment]
Closing as this should be resolved
