### ISSUE TITLE
integrated terminal doesnt support Ctrl+Arrow and Ctrl+Shift+Arrow for moving and selecting text in console

### ISSUE THREAD

**Issue by jeernest** [PowerShell/vscode-powershell#818]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```powershell

PS G:\products\sam> code -v

1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de

PS G:\products\sam> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      1      0      0

PS G:\products\sam> code --list-extensions --show-versions

idleberg.hopscotch@0.1.4
ms-vscode.csharp@1.10.0
ms-vscode.PowerShell@1.1.0
qub.qub-msbuild@0.6.3
PS G:\products\sam> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

when I switch to the terminal tab of the Integrated console, I can move left and right using arrows, but I'm not able to move using Ctrl+left, Ctrl+right which moves by words and I'm not able to select words using Ctrl+Shift+left, Ctrl+Shift+right.

**Comment by daviwil** [comment]
This will be resolve when we enable PSReadline support in the console, follow bug #535 to be notified when this is done!

**Comment by JanoshRiebesell** [comment]
@daviwil Any news yet regarding this issue? Particularly about the whole-word selection using <kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>-></kbd> | <kbd><-</kbd>?

**Comment by rkeithhill** [comment]
Work on this issue is being done here - https://github.com/PowerShell/PowerShellEditorServices/pull/672
