### ISSUE TITLE
Feature Request: Add command to automatically generate  the information requested when creating a new issue.

### ISSUE THREAD

**Issue by PowerSchill** [PowerShell/vscode-powershell#819]
The information generated will include the information requested below. 

> 
> ### System Details
> 
> - Operating system name and version:
> - VS Code version:
> - PowerShell extension version:
> - Output from `$PSVersionTable`:
> 
> ```
> Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here
> 
> code -v
> $pseditor.EditorServicesVersion
> code --list-extensions --show-versions
> $PSVersionTable
> ```
> 
> ### Issue Description
> 
> I am experiencing a problem with...
> 
> ### Attached Logs
> 
> Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
> about capturing and sending logs

**Comment by daviwil** [comment]
Whoops, didn't realize you were also filing one :)  Let's track it with the other issue since there's more details there. #820
