### ISSUE TITLE
MS HTML prompt isn't brought to front focus when using Connect-AzureAD or Login-AzureRmAccount

### ISSUE THREAD

**Issue by jeremytbrun** [PowerShell/vscode-powershell#828]
### System Details

- Operating system name and version: Windows 10 1607
- VS Code version: 1.12.2
- PowerShell extension version: 1.2.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de
$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      1      0
code --list-extensions --show-versions
ms-vscode.PowerShell@1.2.1
robertohuertasm.vscode-icons@7.8.1
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Running Connect-MsolService or Login-AzureRmAccount results in the MS HTML prompt window being created, but always behind the VS Code editor window giving the appearance of the PowerShell Integrated Console hanging. PowerShell ISE brings the window to front focus. Can this be done in the VS Code Extension?

**Comment by daviwil** [comment]
This is an ongoing issue, still need to find a way to fix it.  Currently tracking it with issue #621, subscribe to that issue for updates.  Thanks for the report!
