### ISSUE TITLE
Support to delete with CTRL Backspace in Powershell Integrated Console

### ISSUE THREAD

**Issue by skest3qc** [PowerShell/vscode-powershell#832]
Hi,
could you add the feature that we can delete with CTRL Backspace in Intergrated Console?
Thanks

**Comment by adamrushuk** [comment]
I believe this feature will come with PSReadline support, which is already logged in #535

**Comment by daviwil** [comment]
Adam is correct (thanks Adam!), this will come with the PSReadline integration.  Planning to start work on that next week, though it might take a little while before it gets shipped.  Follow #535 to be notified when it's done!
