### ISSUE TITLE
focusConsoleOnExecute setting should be respected when debugger stops at a breakpoint

### ISSUE THREAD

**Issue by replicaJunction** [PowerShell/vscode-powershell#835]
### System Details

- Operating system name and version: Windows 7 x64 / Windows 8.1 x64
- VS Code version: 1.12.2
- PowerShell extension version: 1.2.1

- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de

Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      1      0

donjayamanne.python@0.6.4
eamodio.gitlens@3.6.0
ms-vscode.csharp@1.10.0
ms-vscode.PowerShell@1.2.1


Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

**Current VSCode behavior:**
1. Press F5 to run the current script OR press F8 to run the current line / selection
2. Script / line / selection runs in the Terminal pane
3. Window focus remains in the Terminal. Click or use a keyboard shortcut to move focus back to edit the script.

**Current ISE behavior:**
1. Press F5 to run the current script OR press F8 to run the current line / selection
2. Script / line / selection runs in the Terminal pane
3. Window focus remains in the editor pane. Continue editing, or highlight another line / selection to run.

**Desired VSCode behavior:**
Set focus back to editor pane after running a script to match ISE behavior.

When testing a file and running commands one-by-one, it's tedious to need to change focus back after each F8 press. If this would affect current workflows, perhaps it could be a config option instead.

Thanks to everyone for their work on this! This extension is truly a game-changer for my PowerShell work.

### Attached Logs

[1496766630-76369ed6-2e9e-4667-b114-030dee623f731496766613166.zip](https://github.com/PowerShell/vscode-powershell/files/1055782/1496766630-76369ed6-2e9e-4667-b114-030dee623f731496766613166.zip)

**Comment by daviwil** [comment]
If you want to retain focus in the editor when pressing F8 you can use this setting:

```
"powershell.integratedConsole.focusConsoleOnExecute": false,
```

Unfortunately we don't have control over the focus behavior when the debugger stops at a breakpoint so there's no way around that yet.  I might be able to implement a workaround, though, I'll give it a shot in an upcoming release.

**Comment by replicaJunction** [comment]
Awesome. That setting will work for me for the time being, and I'll look forward to seeing what happens with that workaround.

**Comment by BjornNordblom** [comment]
Can't reproduce. The setting `"powershell.integratedConsole.focusConsoleOnExecute": false,` works as intended on VSCode 1.44.1 with Powershell extension 2020.3.0. Tested on both PS7 and PS5.1.
