### ISSUE TITLE
Right clicking variable in debugger and selecting "Add to Watch" doesn't copy variable name to watch input

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#838]
For some reason the variable name is not being transferred to the Watch pane when you click "Add to Watch" in the Variables tree.

Example: https://youtu.be/DxFQ4uf9d7k?t=36m49s

**Comment by daviwil** [comment]
This is caused by a new mandatory parameter in the latest VS Code:

evaluateName attribute mandatory for Add to Watch and Copy Value actions

VS Code previously tried to implement the Add to Watch and Copy Value actions by using the data from the VARIABLES view and a JavaScript-biased heuristic for building expressions that can be used with the evaluate request.

Since this approach does not work for all languages, we've introduced the evaluateName attribute for variables some time ago. It is now mandatory for debug adapters to support the evaluateName attribute if they want that Add to Watch and Copy Value actions work properly.

From latest changelog: https://code.visualstudio.com/updates/v1_13#_tasks

**Comment by rkeithhill** [comment]
Fixed by https://github.com/PowerShell/PowerShellEditorServices/pull/504

**Comment by daviwil** [comment]
Sweet, thanks a lot!
