### ISSUE TITLE
Step Out doesn't seem to be stepping out of functions

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#839]
When stopped at a breakpoint inside of a while loop, clicking Step Out does not actually step out of the loop, it just continues to the next iteration of the loop.

Example: https://youtu.be/DxFQ4uf9d7k?t=36m5s

**Comment by wsmelton** [comment]
Same issue for me but in a foreach loop. I hit the break point but then try to step out and looks like it just stops. I was doing this in a psm1 file for dbatools module.

**Comment by BjornNordblom** [comment]
Can't reproduce. Step out executed the remaining iterations in both a for and while loop, and stopped on the row after the function.

Tested code. Breakpoint in while loop. When triggered, remove breakpoint and press Step Out or shift-F11. Control returns on row after function:

https://gist.github.com/BjornNordblom/8b6ce7fbcb0d452e1b179b25b1438f2a

Tested on VSCode 1.44.1 with Powershell extension 2020.3.0. Tested on both PS7 and PS5.1.

**Comment by wsmelton** [comment]
Yeah, can confirm I no longer see this now.

**Comment by TylerLeonhardt** [comment]
Thanks folks :)
