### ISSUE TITLE
Installing clone behind http proxy

### ISSUE THREAD

**Issue by andydtoma** [PowerShell/vscode-powershell#84]
I have cloned the project on a Win7 workstation behind enterprise proxy.
When trying to install the package dependencies with npm install I get ETIMEDOUT:

> Error installing vscode.d.ts: Error: connect ETIMEDOUT 192.30.252.126:443

> npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\DTOMA\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! PowerShell@0.3.1 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PowerShell@0.3.1 postinstall script 'node ./node_modules/vscode/bin/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PowerShell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/vscode/bin/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PowerShell
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PowerShell
npm ERR! There is likely additional logging output above.

> npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DTOMA\Documents\GitHub\vscode-powershell\npm-debug.log

I have tried with both last versions of node.js v4.2.6 and v5.5.0 with the same result.
Attached the result npm-debug.log:
[npm-debug.log.txt](https://github.com/PowerShell/vscode-powershell/files/119183/npm-debug.log.txt)

The proxy settings in settings.json are fitted to the environment.

On the same system, when I installed the marketplace version of the extension I had to apply the @joaomoreno workaround (Jan 4th) from the vscode issue [https://github.com/Microsoft/vscode/issues/69](url)

I think there is something similar in the dependency hierarchy.

**Comment by daviwil** [comment]
Hey Andy, this seems to be related to the new VS Code type definition installation script.  I've filed a bug on their GitHub repo so that they can help us figure out the issue:  https://github.com/Microsoft/vscode-extension-vscode/issues/8

Thanks for the report!

**Comment by andydtoma** [comment]
thanks @daviwil 
I've just seen their response, and I will test it.
Honestly I don't like too much using environment variables.

I will keep informed about the result.

**Comment by daviwil** [comment]
Yes, I also agree that it is not ideal.  If the fix works for you, I will document it in the development instructions here and possibly find some way to automate it if I can.

**Comment by andydtoma** [comment]
Hey David,
The install passed well.
from now on I will spend more time examinig this project.
Have a nice weekend,

Andy

**Comment by daviwil** [comment]
Thanks Andy, glad to hear it worked!
