### ISSUE TITLE
Attach to Process debugging is not hitting breakpoints on attach

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#840]
Something got broken recently with the Attach to Process debugging configuration.  When you attach to a process the breakpoint you set in your code doesn't get hit when the attach completes.

Example: https://youtu.be/DxFQ4uf9d7k?t=1h7m42s

Psychic debugger tells me this has something to do with the flag I'm using to determine whether I'm currently in debug mode for passing breakpoints from language server to debug adapter.

**Comment by JustinGrote** [comment]
@TylerLeonhardt  @SydneyhSmith breakpoints within a script while attached works for me, this can be closed.
![image](https://user-images.githubusercontent.com/15258962/80007857-b7570a00-847b-11ea-9a3c-1ce3c3739cdf.png)
