### ISSUE TITLE
psedit cannot open an empty file in a remote PSSession

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#842]
It seems that psedit is having an issue opening an empty file in a remote PSSession, need to investigate.

/cc @sstodd7532

**Comment by sstodd7532** [comment]
Here are a copy of the logs that I had from the test that I just ran
[1496861214-ed36508f-ecf3-45d3-a463-97d6a9111dbb1496857080988.zip](https://github.com/PowerShell/vscode-powershell/files/1059008/1496861214-ed36508f-ecf3-45d3-a463-97d6a9111dbb1496857080988.zip)

**Comment by sstodd7532** [comment]
It also does not appear to be saving the edits that I make to a file once I have content in them.

**Comment by muzzar78** [comment]
When I remote into a server within the integrated console, run psedit the file appears in VSCode. However, when I make an edit and save the file the changes aren't getting saved back to the remote server. I have attached the verbose log output.
[vscode-powershell-psedit.zip](https://github.com/PowerShell/vscode-powershell/files/1309888/vscode-powershell-psedit.zip)
