### ISSUE TITLE
I do not want PowerShell integrated console to open when I open a PowerShell file

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/vscode-powershell#848]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|plantuml|jebbs|1.7.1|
|VS-code-vagrantfile|marcostazi|0.0.5|
|PowerShell|ms-vscode|1.2.1|
|qub-xml|qub|1.2.0|;

---

Steps to Reproduce:

1. Open a .ps1 file.
2. Observe that PowerShell Integrated Console window opens (as seen in screenshot).

I do not want the PowerShell terminal to open - I just want to edit my script in peace. This is an unwanted intrusion on my screen real estate.

Illustration of problem:

![image](https://user-images.githubusercontent.com/9914262/26963399-100a99ee-4cf5-11e7-8b05-e6ce9a57d0e0.png)

```
PS C:\Source\p-windows> code -v

1.13.0
376c52b955428d205459bea6619fc161fc8faacf
PS C:\Source\p-windows> $pseditor.EditorServicesVersion


Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      1      0


PS C:\Source\p-windows> code --list-extensions --show-versions

dbaeumer.vscode-eslint@1.2.11
donjayamanne.githistory@0.2.0
jebbs.plantuml@1.7.1
marcostazi.VS-code-vagrantfile@0.0.5
ms-vscode.PowerShell@1.2.1
qub.qub-xml@1.2.0
PS C:\Source\p-windows> $PSVersionTable
```

**Comment by adamrushuk** [comment]
You can use "powershell.integratedConsole.showOnStartup": false to ensure the PowerShell Integrated Console does not open :)

**Comment by sandersaares** [comment]
Aha, you are right! I must have simply missed that setting somehow. Thanks for the hint!

**Comment by adamrushuk** [comment]
No worries, happy to help!

**Comment by daviwil** [comment]
Thanks a lot Adam!
