### ISSUE TITLE
"Debug tests" auto-fills wrong test name

### ISSUE THREAD

**Issue by rebro-msft** [PowerShell/vscode-powershell#852]
### System Details

- Operating system name and version:  Windows 10 Enterprise
- VS Code version: 1.13.0
- PowerShell extension version: 1.3.0
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

PS C:\ > code -v
1.13.0
376c52b955428d205459bea6619fc161fc8faacf

PS C:\ >$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      3      0      0

PS C:\ > code --list-extensions --show-versions
DavidAnson.vscode-markdownlint@0.9.1
dbankier.vscode-instant-markdown@1.1.0
ms-vscode.csharp@1.10.0
ms-vscode.PowerShell@1.3.0
ms-vscode.Theme-MarkdownKit@0.1.4
ms-vscode.wordcount@0.1.0
seanmcbreen.MDTools@1.0.1
streetsidesoftware.code-spell-checker@1.1.0

PS C:\ > $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with debugging Pester tests using the "Debug tests" link above a Describe block.  It is auto-filling in the wrong TestName:

![debug-tests-testname-issue](https://user-images.githubusercontent.com/10780862/26994502-be8cf2f6-4d1c-11e7-812e-eec29b176a80.PNG)

If I put the Describe name in quotes, I get a different error:

![debug-tests-testname-issue2](https://user-images.githubusercontent.com/10780862/26994535-dc1f247e-4d1c-11e7-8a7f-b9479eb99252.PNG)

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.  
I will send them to David directly.

**Comment by daviwil** [comment]
Thanks for sending this!  I'm about to ship an update with a couple fixes, will get this one in too.
