### ISSUE TITLE
ISE theme has incorrect colour for a variables dollar 

### ISSUE THREAD

**Issue by lukemgriffith** [PowerShell/vscode-powershell#858]
Hate to be that guy, but the dollar should be red. 

![Example](http://i.imgur.com/5GBal9I.png)

**Comment by daviwil** [comment]
Totally valid feedback, though this is a known issue with our syntax grammar: https://github.com/PowerShell/EditorSyntax/issues/23.  Once the grammar is fixed the theme should work correctly!

**Comment by daviwil** [comment]
Keeping this bug open for now because I imagine other people will come here to report the same issue :)

**Comment by SydneyhSmith** [comment]
Closing this as it is an editor syntax issue tracked  PowerShell/EditorSyntax#23
