### ISSUE TITLE
Slow intellisense when workspace contains a DSC module

### ISSUE THREAD

**Issue by dandiddy** [PowerShell/vscode-powershell#861]
### System Details

- Operating system name and version: Windows 7 x64
- VS Code version: 1.3.1.0
- PowerShell extension version: 1.13.0
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I'm finding intellisense incredibly slow in some circumstances (often several tens of seconds). This also affects the time take for the great new code lens stuff to appear. I have quite a large repo, but by trial and error I found that knocking out all the DSC modules makes things blindingly fast. Adding even one DSC module back in makes things noticeably slower. I tried third party DSC modules (xPSDesiredStateConfirugation or xWebAdministration) and the behaviour's the same.

### Attached Logs
The logs below are from two vscode workspaces: one has a third-party MySQL module, and the other has that module plus xPSDesiredStateConfiguration version 6.4.0.0. All I am doing is opening the MySQL module file and waiting for the code lens to appear in front of the first function. You can see from the timing that there's a 8-second lag before line 1537 of the version with DSC.

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1068636/logs.zip)

**Comment by daviwil** [comment]
Thanks @dandiddy!  I'll take a look.

**Comment by kapilmb** [comment]
This is somewhat related to #869 - whenever a script contains `Import-DSCResource` keyword, parsing seems to slow down significantly.

**Comment by zachChilders** [comment]
Is there any update on this?  We're working on a very DSC intensive project and VSCode has become almost unusably slow in the last month or so.  vscode-Powershell Version 1.5.1 VSCode  Version 1.18.1

**Comment by chriskuech** [comment]
This issue is causing many significant problems, as we've grown to rely significantly on correct linting for PSScriptAnalyzer issue resolution and this issue can deceptively create false errors.  @dandiddy cited 8-second lag; however, my team has seen significantly higher lag and I believe that the linter has actually timed out.

Is there any update on this issue?

**Comment by tylerl0706** [comment]
@rkeithhill I saw your example over in #869. Do you think the slow Invoke-ScriptAnalyzer would affect intellisense at al? Or would those two pieces be separate?

**Comment by rkeithhill** [comment]
When I analyze the OP's log file, it seems like the delay is code lens resolve response:
```
Id Method                      ElapsedMSecs
-- ------                      ------------
   textDocument/didOpen                1000
0  initialize                             0
1  powerShell/getVersion                  0
2  textDocument/codeAction                0
3  textDocument/codeLens                  0
4  textDocument/documentSymbol            0
5  textDocument/codeAction                0
6  textDocument/codeLens                  0
7  textDocument/documentSymbol            0
8  textDocument/codeAction                0
9  codeLens/resolve                    4000
```
#9 is a resolve references message which uses the ReferencesCodeLensProvider in PSES. That looks be using parsing and not PSSA from a quick peruse.

**Comment by SeeminglyScience** [comment]
DSC uses thread static fields for caching keywords and CIM classes.  We may need to check documents for DSC related commands/keywords before parsing.  If we find any, we can either get on the interactive pipeline thread before attempting to parse, or possibly even dedicate a separate thread to just parsing.

For reference, here's the the test to see [if DSC modules need to be loaded](https://github.com/PowerShell/PowerShell/blob/09f54713466f6c2ada2741d15c84984d24581383/src/System.Management.Automation/engine/parser/Parser.cs#L2937).  Things really slow down if this test fails, importing modules and possibly even running `Get-Module -ListAvailable`.

**Comment by SydneyhSmith** [comment]
we recently published an update which has addressed a number of underlying architectural issues, would you mind giving it a try and letting us know if you are still hitting this issue?

**Comment by dandiddy** [comment]
Can confirm that the experience is vastly superior with the latest updates. Thanks for keeping this issue updated :)
