### ISSUE TITLE
Intellisense loading modules?

### ISSUE THREAD

**Issue by andystumph** [PowerShell/vscode-powershell#867]
### System Details

PS C:\> code -v
1.13.0
376c52b955428d205459bea6619fc161fc8faacf

PS C:\> $psEditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      3      1      0

PS C:\> code --list-extensions --show-versions
arcticicestudio.nord-visual-studio-code@0.3.0
bradygaster.azuretoolsforvscode@1.2.7
formulahendry.azure-iot-toolkit@0.1.0
gerane.Theme-azure@0.0.2
johnpapa.azure-functions-tools@0.2.0
ms-mssql.mssql@1.0.0
ms-vscode.PowerShell@1.3.1
ms-vscode.vscode-azureextensionpack@0.0.4
msazurermtools.azurerm-vscode-tools@0.3.5
PeterJausovec.vscode-docker@0.0.16
PKief.material-icon-theme@2.0.8
rprouse.theme-obsidian@0.2.0
usqlextpublisher.usql-vscode-ext@0.2.2
zehfernando.theme-actual-obsidian@2.1.0

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Is Intellisense supposed to be automatically loading modules? When typing in commands in the editor, it's automatically loading any/all modules that match the partial command. 

For example, typing "Invoke-Az" and pausing will automatically load several Azure modules. Or typing "Invoke-Po" loads SQLPS.

**Comment by daviwil** [comment]
I need to change that behavior indeed.  I've got a partially completed fix for it, need to finish it up.  This fix is being tracked with issue #715 so keep an eye on that issue to know when it gets completed.  Thanks!
