### ISSUE TITLE
$PSCmdlet.ThrowTerminatingError results in no error details on debugging

### ISSUE THREAD

**Issue by nightroman** [PowerShell/vscode-powershell#870]
### Issue Description

(1) Create and open the script in VSCode:

```powershell
    [CmdletBinding()]
    param()

    trap {$PSCmdlet.ThrowTerminatingError($_)}

    throw 'oops'
```

(2) Ensure the debugger configuration is "PowerShell Current File".

(3) Start debugging (<kbd>F5</kbd>).

**Actual output:**

```
    0> c:\ROM\SET\VSCode\z\_170519_180339_debug\trap-throw\app1.ps1


    oops
```

Note two empty lines after the command before the error (not a bug deal) and
totally missed error details (this is the real problem).

**Expected output: (shown when we invoke in PSIC manually)**

```
    0> c:\ROM\SET\VSCode\z\_170519_180339_debug\trap-throw\app1.ps1
    oops
    At line:1 char:1
    + c:\ROM\SET\VSCode\z\_170519_180339_debug\trap-throw\app1.ps1
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (oops:String) [app1.ps1], RuntimeException
        + FullyQualifiedErrorId : oops,app1.ps1
```

The example uses `trap` and `throw`. The problem is not specific to them. This
script shows similar issues:

```powershell
    [CmdletBinding()]
    param()

    try {
        $ErrorActionPreference = 'Stop'
        Get-Variable miss1
    }
    catch {
        $PSCmdlet.ThrowTerminatingError($_)
    }
```

The problem has something to do with `$PSCmdlet.ThrowTerminatingError($_)`. If
we replace it with just `throw` then expected errors are printed.

But the construct `$PSCmdlet.ThrowTerminatingError($_)` has useful features, it
is used deliberately, replacing it with `throw` is not a solution.

NB: The original problem was found on debugging Invoke-Build tasks started
by [Invoke-TaskFromVSCode.ps1](https://github.com/nightroman/Invoke-Build/blob/master/Invoke-TaskFromVSCode.ps1). It also uses `$PSCmdlet.ThrowTerminatingError($_)`.
The piece of `launch.json`:

```json
      {
        "type": "PowerShell",
        "request": "launch",
        "name": "Invoke-Build Current Task",
        "script": "Invoke-TaskFromVSCode",
        "args": [],
        "cwd": "${workspaceRoot}"
      },
```

***
### System Details

- Operating system name and version: Windows 10 x64 v10.0.10586.0
- VS Code version: 1.13.0
- PowerShell extension version: 1.3.2
- Output from `$PSVersionTable`:

```
    0> $pseditor.EditorServicesVersion

    Major  Minor  Build  Revision
    -----  -----  -----  --------
    1      3      2      0

    0> code --list-extensions --show-versions
    donjayamanne.githistory@0.2.0
    Ionide.Ionide-fsharp@2.26.1
    ms-vscode.PowerShell@1.3.2

    0> $PSVersionTable
    Name                           Value
    ----                           -----
    PSVersion                      5.0.10586.672
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.10586.672
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
```

### Attached Logs

```
    [6:33:6] Language server starting...
    powershell.exe started --
        pid: 9364
        exe: C:\windows\Sysnative\WindowsPowerShell\v1.0\powershell.exe
        args: C:\Users\rjq\.vscode\extensions\ms-vscode.powershell-1.3.2\scripts\Start-EditorServices.ps1 -EditorServicesVersion '1.3.2' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.3.2' -BundledModulesPath 'C:\Users\rjq\.vscode\extensions\ms-vscode.powershell-1.3.2\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\rjq\.vscode\extensions\ms-vscode.powershell-1.3.2\logs\1497331986-3a98ee26-bcac-460d-896a-075051c10a101497331985995\EditorServices.log' -SessionDetailsPath 'C:\Users\rjq\.vscode\extensions\ms-vscode.powershell-1.3.2\sessions\PSES-VSCode-10668-238655' -FeatureFlags @()


    [6:33:8] Language server started.
    {"debugServicePort":22385,"status":"started","channel":"tcp","languageServicePort":13621}
    Connecting to language service on port 13621...

    Language service connected.
```

**Comment by daviwil** [comment]
Thanks Roman, I appreciate all the details!  There must be something wrong with how I'm executing the script when debugging, I'll take a look.

**Comment by sandscap-sc** [comment]
VS Code 1.44.1, doesn't show any error information from even `throw 'Throw the Test Error'` in the terminal where version 1.42.1 does show it.

**Comment by TylerLeonhardt** [comment]
This is fixed in the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension. It's just waiting on another release of stable which will probably go out tomorrow or Thursday.

**Comment by TylerLeonhardt** [comment]
proof:

![image](https://user-images.githubusercontent.com/2644648/79271196-42207f00-7e54-11ea-83da-bf6772beea6a.png)
