### ISSUE TITLE
Debug Watch Variable does not show usefull information for non-simple variable types 

### ISSUE THREAD

**Issue by Josverl** [PowerShell/vscode-powershell#872]
### Issue Description
Variable Watches show less detail than the Auto variable view 

While debugging a piece of code that uses a variable such as a hash table, the Wacth window is less than helpful.
#Code 
$Groups = @{}
$Groups.Add( 'foo', 'bar' )

>AUTO 
$Groups:  [Hashtable: 1 ]
and then the actual content of the hashtable 

>WATCH 
$Groups: "System.Collection.Hashtable..."

Expected : 
I would expect the WATCH view to show the same detail level as the AUTO view ( Which is great , but sometimes is not convenient to track a specific variable.

### System Details
1.13.0
376c52b955428d205459bea6619fc161fc8faacf
Andreabbondanza.ignoregit@1.0.1
dansilver.typewriter@1.0.1
eamodio.gitlens@4.1.1
ms-mssql.mssql@1.0.0
ms-vscode.PowerShell@1.3.2
ms-vsts.team@1.118.2
samverschueren.yo@0.9.3
VisualStudioOnlineApplicationInsights.application-insights@0.4.1

Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I am experiencing a problem with...

**Comment by rkeithhill** [comment]
Yup, I've seen this.  Will look into it shortly.

**Comment by mrboring** [comment]
@Josverl Thanks, I was just going to create an issue for this. 

$pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0


[DBG]: > code --list-extensions --show-versions
ajhyndman.jslint@1.2.1
dbaeumer.vscode-eslint@1.2.11
dkundel.vscode-new-file@3.1.0
eg2.tslint@0.15.0
emmanuelbeziat.vscode-great-icons@2.1.8
HookyQR.beautify@1.1.1
ms-vscode.omnisharp@0.3.2
ms-vscode.PowerShell@1.4.1
qinjia.view-in-browser@0.0.5
stevencl.addDocComments@0.0.8
xabikos.JavaScriptSnippets@1.4.0

[DBG]: > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.413
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.413
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by rkeithhill** [comment]
PR is on the way.  Hopefully will make it into the next drop.

**Comment by rkeithhill** [comment]
Fixed by https://github.com/PowerShell/PowerShellEditorServices/pull/534

**Comment by daviwil** [comment]
This will come out in a patch update over the next few days.  Thanks Keith!
