### ISSUE TITLE
Allow user to customize the working dir that the debugger starts in

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#88]
Technically you can do this without any change to the package.json file but without `cwd` being defined in the `configurationProperties`, VSCode will whine when you edit a launch.json file and add the property.

**Comment by daviwil** [comment]
Can we add `cwd` to our default configurations and set it to `${workspaceRoot}`?  I guess I'm still sort of wondering whether it should be the script's path by default if no other working path is set.  We could try setting it to `${file}` by default and then grab the directory path of whatever the user passed in.

**Comment by rkeithhill** [comment]
> Can we add  cwd  to our default configurations and set it to  ${workspaceRoot} ?

Yes.  That's what I was going to do after the PSES side PR got merged.  That is what both the mono-debug and node-debug packages do.

>  I guess I'm still sort of wondering whether it should be the script's path by default if no other working path is set.

Good question. That was the way I was previously going to implement it (and what you get if VSCode passes cwd = null) except that it gets the directory of launchParams.Program (which defaults to ${file}).  Hmm, but the user can override Program in their launch.json file so if the user wanted this behavior all they (or we by default) need to do is set cwd to null.  Cool.  So how should be initialize cwd by default?  ${workspaceRoot} or null?

**Comment by daviwil** [comment]
I'd say try it with null first to see if it does in fact set the current working directory to the script's path.  Since we're auto-executing the currently opened script in the debugger now, I think it'd make more sense if the cwd was the script's path rather than the workspace path.  Users who know they need the workspacePath set instead will figure out how to set it.

**Comment by rkeithhill** [comment]
Will do.

**Comment by rkeithhill** [comment]
OK so neither `null` or empty string worked as a sentinel value.  If I use either of those two values in launch.json, VSCode just passes in the workspace root dir.  So I'll default it to `${file}`.

**Comment by daviwil** [comment]
Sounds good!  That may require another change in the PR we just merged in Editor Services, though.  I think we need to call `Path.GetDirectoryName` on [this line](https://github.com/PowerShell/PowerShellEditorServices/blob/83aed94d30b0fcc32cc613c1dbd1d433ce9462a8/src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs#L80).  I think it's the right thing to do, so it's working making another PR for that.

**Comment by daviwil** [comment]
Err, to be more specific, we need to call `Path.GetDirectoryName` on the value of cwd which came from LaunchRequest.

**Comment by rkeithhill** [comment]
Heheh, yup working on that. Here is what I have:
```csharp
// Set the working directory for the PowerShell runspace to something reasonable
// such as the cwd passed in via launch.json. And in case that is null, use the
// the folder of the script to be executed.  If cwd is a file path then extract the 
// directory and use that.
string workingDir = launchParams.Cwd ?? launchParams.Program;
try
{
    if ((File.GetAttributes(workingDir) & FileAttributes.Directory) != FileAttributes.Directory)
    {
        workingDir = Path.GetDirectoryName(workingDir);
    }
}
catch (Exception ex)
{
    Logger.Write(LogLevel.Error, "cwd path is bad: " + ex.Message);
}

var setWorkingDirCommand = new PSCommand();
setWorkingDirCommand.AddCommand(@"Microsoft.PowerShell.Management\Set-Location")
    .AddParameter("LiteralPath", workingDir);

await editorSession.PowerShellContext.ExecuteCommand(setWorkingDirCommand);
```
Note that I can't seem to set a default cwd value of `${file}` in package.json.  VSCode just sends in the workspace root dir as cwd **fi** cwd is not set in launch.json  I think this is probably OK since the launch.json that will get created should have `"cwd": "${file}"` set in it.  What do you think?

**Comment by daviwil** [comment]
Yep, sounds fine.  New changes look good!
