### ISSUE TITLE
Powershell Code format (PSScriptAnalyzer) flags variable as unused

### ISSUE THREAD

**Issue by kapilmb** [PowerShell/vscode-powershell#889]
_From @cryptonym64 on June 15, 2017 19:15_

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.2|         <----------
|theme-stayfresh|piotrekfracek|1.1.2|
|theme-cobalt0|sharksym|0.0.5|;

---

Steps to Reproduce:

1. code this:
$a = 0
$b = @(1,2)
$b | ForEach-Object {
    $a += 1
}
Write-Host $a

2. Ctrl-Alt-F to format.

3. Notice that it warns: 
file: 'untitled:Untitled-1' severity: 'Warning' message: 'The variable 'a' is assigned but never used.  (PSUseDeclaredVarsMoreThanAssignments)' at: '4,5' source: 'PSScriptAnalyzer'

_Copied from original issue: Microsoft/vscode#28835_

**Comment by TheIncorrigible1** [comment]
I'm running into this issue in some of my scripts, especially when dealing with `$global:` scoped variables that are defined at the beginning of a script, manipulated in a function, and used at the end.  *In this use-case, it's for a logging object that gets sent in an email for automation errors*

**Comment by ciejepro** [comment]
I am running into this issue in several of my scripts.
in one such case (code-exceprt) below:

If ($script:DNsThatHaveBeenACLReset -notcontains $MyDN.ToLower())
{
	$script:DNsThatHaveBeenACLReset += $MyDN.ToLower()
	#RunDSACLs """\\$DC\$MyDN"" /S"
		
	$CommandlineParameters = """\\$DC\$MyDN"" /N "
		
	$script:AccessRightsName_ACEArray["Defaults"] | ForEach-Object {$CommandlineParameters += $_}

	RunDSACLs $CommandlineParameters
}

The analyzer is only flagging the instance of the variable within the ForEach-Object portion of this.

**Comment by tylerl0706** [comment]
Thanks for this! I tried running Script Analyzer on its own against the original repro and I'm seeing the warning. Here's the repro:

In the file `repro.ps1`:
```powershell
$a = 0
$b = @(1, 2)
$b | ForEach-Object {
    $a += 1
}
Write-Host $a
```
in a terminal:
```powershell
Install-Module -Name PSScriptAnalyzer

Invoke-ScriptAnalyzer -Path path/to/repro.ps1 -Settings PSGallery -Recurse
```
The output:
```
RuleName                            Severity     ScriptName Line  Message
--------                            --------     ---------- ----  -------
PSUseDeclaredVarsMoreThanAssignment Warning      repro2.ps1 4     The variable 'a' is assigned but never used.
```

Let me go ahead and open this in https://github.com/PowerShell/PSScriptAnalyzer

**Comment by tylerl0706** [comment]
Actually, it looks like it's already open here!: https://github.com/PowerShell/PSScriptAnalyzer/issues/827 

Thanks again for the report - feel free to add more details and +1 that issue!
