### ISSUE TITLE
CodeLens appearance causes horizontally-scrolled window to snap back

### ISSUE THREAD

**Issue by johlju** [PowerShell/vscode-powershell#894]
### System Details

- Operating system name and version: Windows 10 
```
PS> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      15063  0
```
- VS Code version: 1.13.1
- PowerShell extension version: 1.3.2
- Output from `$PSVersionTable`: See below

`$pseditor.EditorServicesVersion` does not work since PowerShell Integrated Terminal i crashing.
```
PS > code -v
1.13.1
379d2efb5539b09112c793d3d9a413017d736f89
PS > $pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      3      2      0
PS > code --list-extensions --show-versions
DavidAnson.vscode-markdownlint@0.9.1
donjayamanne.githistory@0.2.0
eamodio.gitlens@4.1.1
ms-vscode.csharp@1.10.0
ms-vscode.PowerShell@1.3.2
PeterJausovec.vscode-docker@0.0.16
ryu1kn.annotator@0.10.1
streetsidesoftware.code-spell-checker@1.2.0
Tyriar.theme-sapphire@0.2.1
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.413
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.413
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
able
```

### Issue Description

Screen jumps back to beginning of row when row is long while cursor remains. I think this is CodeLens also.
I edit at the end twice, in the second you see CodeLens appearing.

![cursorjumptobeginningofrow-crash](https://user-images.githubusercontent.com/7189721/27254810-d5539830-5390-11e7-9425-70471b34e8a3.gif)

### Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1082683/logs.zip)

**Comment by johlju** [comment]
I have attached logs. I can reproduce.
For some reason PowerShell Integrated Console hanged when it started. Saw that now. That is why I couldn't reproduce at first.

**Comment by daviwil** [comment]
Hmmm, I wonder if the CodeLens is causing it, VS Code may have a bug there.  I'll look into it!

**Comment by SydneyhSmith** [comment]
I will close this as this is an old issue in VSCode that has likely been fixed, please let us know if that is not the case.
