### ISSUE TITLE
Feature request: Convert PowerShell command invocation to Splatting

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#898]
Back before VSCode PowerShell was emerging, I was often using the PowerShell ISE to author PowerShell code. While writing PowerShell code, I typically call a PowerShell command, and then convert that to a Splatting invocation, which took a bit of manual effort. The more parameters a command invocation has the more effort it takes to manually convert the command invocation to Splatting syntax. This manual effort gets boring over time, and reduces the amount of time that I can focus on business logic. 

To speed up that manual process, I wrote a PowerShell module called [SplatHelper](https://www.powershellgallery.com/packages/SplatHelper/0.1). It offers two commands: 

* One that converts a command invocation to Splatting in ISE
* One that's intended to work from the command line

![vscode splatting](https://user-images.githubusercontent.com/466713/27257858-a6f3ddea-539c-11e7-8a11-a7bca9a96dab.gif)

I'd like to be able to achieve the same goal using VSCode.

Cheers,
Trevor Sullivan
https://trevorsullivan.net

**Comment by SeeminglyScience** [comment]
You can do the same type of thing with editor commands and some of the EditorServices commands. For example this will splat whatever CommandAst is closest to your cursor.

```powershell
Register-EditorCommand -Name ConvertToSplatting -DisplayName 'Splat closest command' -ScriptBlock {
    $ast = Find-Ast -AtCursor | Find-Ast -Ancestor { $_.GetType().Name -eq 'CommandAst' }
    $ast | Set-ScriptExtent -Text (ConvertTo-Splatting $ast.Extent.Text)
}
```

**Comment by kapilmb** [comment]
I think this issue is identical to that of #517.

**Comment by pcgeek86** [comment]
Thanks for pointing that out @kapilmb. Looks like SAPIEN implemented it into their editor based on my original release of `SplatHelper`. I'll close this one since the two issues are closely related.

![image](https://user-images.githubusercontent.com/466713/27264620-558df378-5437-11e7-878e-8891b4288c19.png)

**Comment by jkavanagh58** [comment]
I will work with it but the Register-EditorCommand does not seem to work for me.

**Comment by PowerSchill** [comment]
@pcgeek86 I am going to see if I can add this to the PowerShellEditorServices code. Do you mind if I use your splatting module's code?

**Comment by pcgeek86** [comment]
@PowerSchill  Go or it :)

**Comment by it-praktyk** [comment]
It looks like Sapien implemented it in [PowerShell Studio 2017: Service Release v5.4.141](https://www.sapien.com/blog/2017/06/27/powershell-studio-2017-service-release-v5-4-141/).
