### ISSUE TITLE
Feature request: Should be able to right click and run a specific script

### ISSUE THREAD

**Issue by codemonkeychris** [PowerShell/vscode-powershell#9]

**Comment by daviwil** [comment]
Good idea!  Another good feature request for the VS Code team.

**Comment by daviwil** [comment]
There doesn't seem to be a way to add a context menu action for a command so I'll have to add this in a later release.

**Comment by tylerl0706** [comment]
This would be the equiv of running `F5`, right?

**Comment by SydneyhSmith** [comment]
Closing as this is available
