### ISSUE TITLE
debugger is loading variables stored in the profile. 

### ISSUE THREAD

**Issue by tadcrazio** [PowerShell/vscode-powershell#900]
### System Details

- Windows 8.1
- VS Code version: 1.13.1
- PowerShell extension version: 1.3.2
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
1.13.1
379d2efb5539b09112c793d3d9a413017d736f89

$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      3      2      0

code --list-extensions --show-versions
AdamCaviness.theme-monokai-dark-soda@0.0.5
eamodio.gitlens@4.1.3
emmanuelbeziat.vscode-great-icons@2.1.8
ms-mssql.mssql@1.0.0
ms-vscode.csharp@1.10.0
ms-vscode.PowerShell@1.3.2
PKief.material-icon-theme@2.0.9
sensourceinc.vscode-sql-beautify@0.0.4
vip32bit.theme-monokai-black@0.1.0


$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When using the debugger variables from my profile c:\Users\myuser\Documents\windowspowershell\profile.ps1  are being included in the debugger. It causes some confusion and makes the debugger look a little convoluted.

**Comment by rkeithhill** [comment]
Add the following setting to your user profile to prevent VSCode from processing your profile scripts:
```
  "powershell.enableProfileLoading": false
```
After saving your settings file, restart the PowerShell session (or restart VSCode).

This will impact the editor as well i.e. if you preload modules you won't see them in the editor (intellisense) until you go into the PowerShell Integrated Console and import them.  Also, if you have a custom prompt you won't see that in the integrated console.  

Another approach is to move host specific script out of profile.ps1 and put that stuff into a script like Microsoft.Powershell_prorfile.ps1.  You can even put VSCode specific stuff in Microsoft.VSCode_profile.ps1.  Of course, if you got this route, leave the above setting set to true.

**Comment by tadcrazio** [comment]
Awesome thank you
