### ISSUE TITLE
Debugging breakpoints now won't work on any script except debugexample.ps1

### ISSUE THREAD

**Issue by ironsalsa** [PowerShell/vscode-powershell#902]
### System Details

- Operating system name and version: Windows 8.1 Enterprise 6.3.9600 Build 9600
- VS Code version: 1.13.1
- PowerShell extension version: 1.3.2
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

PS C:\WINDOWS\system32> code -v
1.13.1
379d2efb5539b09112c793d3d9a413017d736f89
PS C:\WINDOWS\system32> $pseditor.EditorServicesVersi
PS C:\WINDOWS\system32> code --list-extensions --show
ms-vscode.PowerShell@1.3.2
Pendrica.Chef@0.6.3
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

I am experiencing a problem with debug breakpoints after the Monday update to the Powershell Extension (1.3.1 to 1.3.2). Breakpoints no longer are respected except in the DebugTest.ps1 - debugging any other file runs through the whole script without stopping at breakpoints. I've even tried pasting in the script in question into the debug examples folder to ensure that the ,json files are identical, and have the same results.

Also, if I paste code above the param[] in the DebugTest.ps1, it doesn't respect breakpoints, but if placed in the for loop it does. It's maddening.

Something in the 

### Attached Logs

No logs to attach, the editor isn't crashing or returning any errors - it's like the breakpoints just aren't there.

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by ironsalsa** [comment]
Update: it only happens when breakpoints are outside of for loops - breakpoints in for loops are still respected.

**Comment by daviwil** [comment]
@ironsalsa thanks for the report!  I'll take a look.

**Comment by ContrarianChris** [comment]
I can replicate the same steps and am seeing exactly the same behavior.

All breakpoints in any of my scripts are ignored, except if the breakpoint exists inside a foreach loop.
With a script that has no for/foreach loops in it, which right now results in a straight through execution, adding a simple loop with a breakpoint inside immediately works and the breakpoint is hit during execution. All the existing breakpoints are still ignored though.

Windows 10 Pro 1703 15063.608
VS Code 1.16.1 x64
PowerShell Extension 1.4.3

`PS D:\Repos\Kubernetes\acs-engine\scripts> code -v
1.16.1
27492b6bf3acb0775d82d2f87b25a93490673c6d
PS D:\Repos\Kubernetes\acs-engine\scripts> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0


PS D:\Repos\Kubernetes\acs-engine\scripts> code --list-extensions --show-versions
ms-vscode.PowerShell@1.4.3
PS D:\Repos\Kubernetes\acs-engine\scripts> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
`

@daviwil any luck with tracking this down?

**Comment by rjmholt** [comment]
Closing as defunct
