### ISSUE TITLE
New temporary console debugging should probably not close until user presses key

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/vscode-powershell#907]
On 1.4.0 the new temporary console feature is nice but after the debug run is done, I usually want to sift through and inspect output.  Perhaps we need a "Press any key to close the terminal"?

If the user presses F5 again to debug in a temp console, I'm fine if the extension forcibly closes the previous one.

**Comment by tylerl0706** [comment]
Totally agree. This should be a thing.

**Comment by tylerl0706** [comment]
This is a part of https://github.com/PowerShell/vscode-powershell/pull/1201 , right @rkeithhill?

**Comment by rkeithhill** [comment]
Yes, except that you don't press a key. You can close the terminal window using the little trashcan icon.  Or you can let it hang around.  The next temp integrated console debug session will close the previous session before it creates the new one.

**Comment by tylerl0706** [comment]
Sounds good. We can probably close this then unless you think the "press a key" should be kept around.

**Comment by rkeithhill** [comment]
Fixed by PR #1201 and PSES PR https://github.com/PowerShell/PowerShellEditorServices/pull/625.

**Comment by mklement0** [comment]
@rkeithhill: 

That's a great improvement, but it doesn't seem to have made it into v1.6.0, neither on Windows nor on macOS (haven't tried Linux).

Is there a problem with the PRs, or should we expect it in a future release and, if so, which one?

**Comment by rkeithhill** [comment]
There's a bug that has been fixed and will show up in the next release.  It works today for the Pester Run/Debug Tests code lens.  What it doesn't work for is launch configurations unless you specifically add the field `"createTemporyIntegratedConsole": true`.

**Comment by tylerl0706** [comment]
We can probably release a 1.6.1 relatively soon to get that fix out.
