### ISSUE TITLE
Write-VSCodeHtmlContentView AppendBodyContent should accept pipeline input

### ISSUE THREAD

**Issue by stefanstranger** [PowerShell/vscode-powershell#909]
### System Details

- Operating system name and version: Windows 7
- VS Code version: 1.13.1
- PowerShell extension version: 1.4.0
- Output from `$PSVersionTable`:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.0.10586.117                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.10586.117                                                                          
CLRVersion                     4.0.30319.18063                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

1.13.1
379d2efb5539b09112c793d3d9a413017d736f89
ms-vscode.PowerShell@1.4.0

Name                           Value                                                                            
----                           -----                                                                            
PSVersion                      5.0.10586.117                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                          
BuildVersion                   10.0.10586.117                                                                   
CLRVersion                     4.0.30319.18063                                                                  
WSManStackVersion              3.0                                                                              
PSRemotingProtocolVersion      2.3                                                                              
SerializationVersion           1.1.0.1  
```

### Issue Description

When using the new Write-VSCodeHtmlContenView cmdlet the parameter AppendBodyContext does not accept input from the pipeline.

get-command Write-VSCodeHtmlContentView -syntax

Write-VSCodeHtmlContentView [-HtmlContentView] <IHtmlContentView> [-AppendedHtmlBodyContent] <string> [<CommonParameters>]

Would it not be possible to use an object from Convertto-HTML as input for this Cmdlet directly via the Pipeline?

Example feature request:
Get-Service | Select Name, Status | Write-VSCodeHtmlContentView -View $View

### Attached Logs

Not applicable

**Comment by daviwil** [comment]
Looks like `Write-Host -Object` accepts input from the pipeline so I'll make the `Write-VSCodeHtmlContentView` follow that same standard.  Thanks Stefan!

**Comment by stefanstranger** [comment]
Thank you David.
