### ISSUE TITLE
Set-VSCodeHtmlContentView should allow passing stylesheets and JavaScript files as a parameter

### ISSUE THREAD

**Issue by mattmcnabb** [PowerShell/vscode-powershell#910]
It would be great if we could style our HTML with the new *-VSCodeHtml cmdlets available with v1.4.0. It could possibly be implemented by giving us access to use <head> tags, or by passing in stylesheets to a parameter.

**Comment by daviwil** [comment]
Yep, passing stylesheets as a parameter is coming next!

**Comment by kamilkosek** [comment]
Hi Guys,
and what about JavaScript ? 
I´ve played a little bit and removed the restriction from [here](https://github.com/PowerShell/vscode-powershell/blob/master/src/features/CustomViews.ts#L182) and embedded some JavaScript to achieve a 'Out-GridView' like behaviour
![20170622_160401](https://user-images.githubusercontent.com/3264948/27438293-0d23e8c8-5765-11e7-9351-4f5fbc24c00c.gif)

**Comment by daviwil** [comment]
That's awesome Kamil :)  Yes, I'll be adding the ability to pass JavaScript paths too!  Just needed to enable it in a fairly secure way (no dynamic loading of JavaSscript from files on disk).  There's a way I can set it up to work with that content policy so that we get the best of both worlds.

**Comment by kamilkosek** [comment]
Thanks :)
And the absolute cherry on the cake would be if there were be an ability to trigger events from the ContentView to communicate with the LanguageServer  😈

**Comment by daviwil** [comment]
Yep, this will ultimately be possible through PSES "editor commands" but we need to make it possible to send them parameters first.

VS Code allows you to invoke commands registered in the editor (like PSES editor commands) from within this HTML view, you just need to encode URIs in a certain way:

https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands#_links

Not sure if there's a way to invoke them without having the URI inside of a link, though.

**Comment by kamilkosek** [comment]
Cool :) 
I just tested it, you don´t need to encode the command with encodeURI() if you a invoke a parameterless command. 
I assume with 
> but we need to make it possible to send them parameters first.
you mean that we need to register a new vscode.command, maybe _PowerShell.InvokeEditorCommand_ which accepts the desired command-name as a parameter and then invoke the command on the LanguageServer through the LanguageClient?
