### ISSUE TITLE
Get-Help -ShowWindow causes window to appear below VS Code

### ISSUE THREAD

**Issue by tmmuessig** [PowerShell/vscode-powershell#913]
### System Details

- Operating system name and version: Windows 10 Version 1703 (OS Build 15063.413)

code -v =1.13.1       379d2efb5539b09112c793d3d9a413017d736f89
$pseditor.EditorServicesVersion
code --list-extensions --show-versions = ms-vscode.PowerShell@1.4.0
$PSVersionTable = 
Name                           Value
----                           -----
PSVersion                      5.1.15063.413
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.413
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I use PowerShell help with the -ShowWindow parameter.  This does not appear to work in VS Code.  Would be nice if this worked the same way as the shell or ISE does and enable me to have a popup window that allows me to see the help and my code as the same time.

When I run Help Get-Command -ShowWindow nothing is returned.

**Comment by daviwil** [comment]
Hey Tim, the window does actually appear, it just shows up **below** the VS Code window.  Try hitting Alt-Tab or looking in your taskbar, you'll find it.

Definitely need to fix the issue where it doesn't show up on top, though, I'll look into that for the next patch update.

**Comment by tmmuessig** [comment]
That is where my problem was. I never saw it come up.

Thanks for the update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rkeithhill** [comment]
From my testing, I believe this was executed in the normal PowerShell terminal and not PoweShellEditorServices.  The PowerShell terminal is not related to this extension. It is just regular PowerShell running in a VSCode terminal window.  This has to do with the fact `$host.PrivateData["Window"]` returns $null in the PowerShell terminal.  If PowerShell has no Window to attach the help window to, it will attach it to the desktop. Unfortunately, that will not cause the window to appear on top of VSCode.

Further, if you try this in the PowerShell Integrated Console, you will get an error.  See #753 

I'm closing this issue as there is nothing the extension can do about the interaction between VSCode and the installed version of Windows PowerShell you're using in the terminal window.
