### ISSUE TITLE
Opened HTML-Content causes PowerShell.ShowAdditionalCommands failing

### ISSUE THREAD

**Issue by kamilkosek** [PowerShell/vscode-powershell#916]
Hi,
when you have an opened HTMLContent View you have to re-register you EditorCommands in order to make them available. I don´t know if this issue is PSES or vscode-powershell related
![20170623_005218](https://user-images.githubusercontent.com/3264948/27459490-cdb1a08c-57ae-11e7-8469-e5147779e3d2.gif)

**Comment by daviwil** [comment]
Weird, not sure why that's happening.  I'll look into it!

**Comment by TylerLeonhardt** [comment]
@kamilkosek any idea if you're still seeing this issue? It's been a minute and work has been done in this space

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
