### ISSUE TITLE
Colliding key shortcuts: Open in ISE & Toggle Developer Tools

### ISSUE THREAD

**Issue by kamilkosek** [PowerShell/vscode-powershell#920]
Both use Ctrl + Shift + i

**Comment by daviwil** [comment]
We've been using Shift+Alt to replace old keybindings that clash, maybe that's a good way to fix this one too. Would you like to send a PR for that? Should be a one-liner, just change package.json :)

**Comment by rkeithhill** [comment]
<kbd>Ctrl+Shift+i</kbd> is not a VSCode shortcut but an Electron shortcut for the dev tools.  Does F12 open the dev tools?

**Comment by rkeithhill** [comment]
Nevermind on <kbd>F12</kbd>. That is specific to another Electron app I work on.  For now <kbd>Crtl+Shift+i</kbd> still works if you use it before the PowerShell extension gets loaded.  But yeah, that is annoying if you need the dev tools.

**Comment by kamilkosek** [comment]
F12 goes to definition 😄 
Didn´t know its electron related.
