### ISSUE TITLE
createTemporaryIntegratedConsole in Interactive Debug session does not catch breakpoints

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#925]
### Issue Description

Modifying my debug configuration for the interactive to include `"createTemporaryIntegratedConsole": true` and it does not acknowledge breakpoints.

### Steps to Replicate
Add that setting to my configuration:
```json
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Interactive Session",
            "cwd": "${workspaceRoot}",
            "createTemporaryIntegratedConsole": true
        },
```
Add breakpoints to the psm1 file of my module. 
Select that configuration in debug side bar.
Then start debug session.
Session does start, as status bar goes organge.
Recieve a new integrated terminal.
Issue command to load module.
Command completes or errors and breakpoint is never hit.

Remove that setting from the configuration.
Reload window.
Same breakpoint is set in psm1 file.
Start debug session.
Current integrated terminal window comes to focus.
Issue command to load module
Breakpoint is hit in the psm1 file and I can step through the file.

### Attached Logs
[1498571203-569d5631-0818-43f6-9fca-86c496b678ea1498571198487.zip](https://github.com/PowerShell/vscode-powershell/files/1105729/1498571203-569d5631-0818-43f6-9fca-86c496b678ea1498571198487.zip)

**Comment by daviwil** [comment]
Thanks Shawn!  I'll take a look.

**Comment by JustinGrote** [comment]
@TylerLeonhardt @SydneyhSmith looks like it works fine now, this can be closed.
![image](https://user-images.githubusercontent.com/15258962/80012089-a3160b80-8481-11ea-8af7-5a002bbff0f2.png)
