### ISSUE TITLE
Feature Request: Intellisense for DSC (just like ISE)

### ISSUE THREAD

**Issue by glaisne** [PowerShell/vscode-powershell#932]
I was a bit surprised it wasn't already there. I think adding the Intellisense features for DSC in the PowerShell extension would be a great addition.

Example: 
```powershell
File "SomeFile"
{
    # <ctrl+space> here shows a list of available options for the File DSC
}
```
or 
```powershell
File "SomeFile"
{
    Ensure = #<ctrl+space> here shows intellisense options of Absent or Present
}
```

Gene

**Comment by daviwil** [comment]
Hey Gene,

IntelliSense already works for DSC configurations:

![image](https://user-images.githubusercontent.com/79405/27748899-1354fb8e-5d86-11e7-931a-6473599c4848.png)

![image](https://user-images.githubusercontent.com/79405/27748929-322118fe-5d86-11e7-9f0a-42b989383f25.png)

Can you tell me exactly the steps you took where the DSC IntelliSense didn't work?  Providing logs from a session where you try this would also be helpful:

https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us

**Comment by glaisne** [comment]
Huh, Seems to be working now. Must have been a fluke. It wasn't working, but I can't seem to reproduce it now. If it happens again, I'll take better notes.

Sorry to bother.
