### ISSUE TITLE
Begin, Process, End opening brace is not properly placed during formatting

### ISSUE THREAD

**Issue by bgelens** [PowerShell/vscode-powershell#934]
### System Details
```powershell
code -v
1.13.1

$pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

code --list-extensions --show-versions
ms-vscode.PowerShell@1.4.1
```

### Issue Description

Begin, process, end are not put on new lines when ```"powershell.codeFormatting.preset": "Allman"``` or ```"powershell.codeFormatting.openBraceOnSameLine": false```

Example code:

```powershell
begin {

} process {

} end {

}
```

**Comment by TylerLeonhardt** [comment]
This is really old (sorry for the delay!) and would be powered by PSScriptAnalyzer since it supplies formating.

@bgelens is this still happening for you?

**Comment by bgelens** [comment]
It's really old yes :)  Probably had something to do with DSC resource work as I normally use OTBS and cuddle.

I'll close it!
