### ISSUE TITLE
[Read-Host], NotSupportedException

### ISSUE THREAD

**Issue by mojinxun** [PowerShell/vscode-powershell#936]
vs2015 
I use nuget by tools [install.ps1]

$name = Read-Host "Enter your name"

but throw an exception:

Read-Host : 不支持所指定的方法。所在位置 E:\YYSoft.Example\WindowsService1\packages\Sodao.Test.1.4.1\tools\install.ps1:28 字符: 1
+ read-host
+ ~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Read-Host], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.PowerShell.Commands.ReadHostCommand

**Comment by rkeithhill** [comment]
I'm a bit confused.  You mention `vs2015`.  This extension is for `Visual Studio Code` and not `Visual Studio 2015`.   If the issue is with VS 2015, then you might try submitting the issue here: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/category/167481-nuget-package-manager

**Comment by daviwil** [comment]
Yes, this is an issue with NuGet's custom PowerShell host.  I'd recommend speaking with their team about it as Keith suggests.

**Comment by mojinxun** [comment]
thank you
