### ISSUE TITLE
Powershell ISE profile won't load (Terminal freezes for a couple of minutes)

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/vscode-powershell#939]
***
I openend a first ticket here --> https://github.com/Microsoft/vscode/issues/30041, it got closed, and I were asked to open one here, so here it is. Thanks in advance!
***

Hi VSCode team,

As mentionned in the title, I have a PowerShell profile (see gist here under) that works flawlessly on the regular powershell console and the powershell ISE.

Once the file Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 exists, the ISE terminal seems like it is frozen. (nothing is responding in the ISE Terminal). After a couple of minutes (3/4) the ISE terminal finally responds, but doesn't load the profile (which actually contains only a prompt function) but didn't load the prompt function.

Using this function we can see the prompt didn't got loaded:

(get-command prompt).Definition

VSCode Version:
1.13.1
image
![image](https://user-images.githubusercontent.com/6302961/27901419-53f7871e-6232-11e7-81f7-4984fe872c41.png)

Powershell Extension version:
1.4.1

OS Version:
Windows 10 Build 16.3.2
Version: 1511
OSBuild: 10586.916

Steps to Reproduce:

Create profiles using the following prompt function --> https://gist.github.com/Stephanevg/c91e8d674da8805bab6fc2c8133f60d5

Copy into the following files
"\ServerName\UserName$\Documents\WindowsPowerShell\Microsoft.PowerShellISE_profile.ps1"
"\ServerName\UserName$\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"

Open a powershell script with vscode

Reproduces without extensions: No

Thanks in advance!

**Comment by Stephanevg** [comment]
Hi,

any news on this?

thanks

**Comment by daviwil** [comment]
Hey Stephane, the PowerShell extension does not load either of these profiles so this wouldn't be causing your problem.  VS Code's profile path is:

`\ServerName\UserName$\Documents\WindowsPowerShell\Microsoft.PowerShellISE_profile.ps1`

What's the contents of your $PSVersionTable?

**Comment by Stephanevg** [comment]
Hey David!

Indeed, It is related to the PSVersion I am using:

I am facing the issue on my main computer with the following psversionTable:

Name                           Value
----                           -----
PSVersion                      5.0.10586.962
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.962
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I tried on a VM, which had the following psversiontable, and where it worked as expected:

Name                           Value
----                           -----
PSVersion                      5.1.14407.1003
PSEdition                          Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14407.1003
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Does this means that  to have this to work, I have to upgrade to ps5.1?

**Comment by Stephanevg** [comment]
Hi,

More information on this:

Same result for when I add the function to $HOME\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1 

I noticed that the prompt function is *only* not loaded in the terminal: 2: PowerShell Integrated.

![image](https://user-images.githubusercontent.com/6302961/28516281-efdbf0c0-7060-11e7-8a9f-2a15703c1c96.png)


It works fine in the terminal 1: powershell.exe though

![image](https://user-images.githubusercontent.com/6302961/28516266-e2fc7a64-7060-11e7-8c6f-af9db9da50e8.png)


Correct me if I am wrong, but If I add this code:
`write-host "Hello" -foregroundColor cyan`

 to the file:  

> $HOME\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1

shouldn't that show up when I start vscode in the terminal? (It works like that with the ISE if I am not mistaken).

When I add that same line to the file

> $HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1

I have it displayed in the **1: Powershell.exe** terminal when I start vscode

![image](https://user-images.githubusercontent.com/6302961/28516652-3ecf3f6a-7062-11e7-8777-91b8a1dda900.png)

**Comment by Stephanevg** [comment]
Hi guys, any news on this? Could this be related to https://github.com/PowerShell/vscode-powershell/issues/535 ?

**Comment by rkeithhill** [comment]
> shouldn't that show up when I start vscode in the terminal?

It depends on **which** terminal window you are referring to.  If you've put something in `Microsoft.VSCode_profile.ps1`, it will not show up in the `powershell.exe` terminal, because it uses the same current host profile that a regular PowerShell console uses. 
![image](https://user-images.githubusercontent.com/5177512/28642284-1aa86298-720f-11e7-867c-9291fbb921f1.png)

BTW this is why you see the text when you put that command in `Microsoft.PowerShell_profile.ps1`:

You should see that output from `Microsoft.VSCode_profile.ps1` if you switch to the `PowerShell Integerated Console` terminal:
![image](https://user-images.githubusercontent.com/5177512/28642418-9b224fe2-720f-11e7-8664-68542d52ebf6.png)

**Comment by Stephanevg** [comment]
So, the ISE profile is NEVER read by vscode, I got that. 

But my issue still remain. As mentionned above, the function located in the vscode profile is not loaded. On a test server with the same version of vscode, but with $psversion 5-1 it works though..

Do you guys need more to troubleshoot this?

**Comment by rkeithhill** [comment]
I don't have access to a 5.0 machine at the moment.  Can you add timing code around the parts of your prompt function to identify the problematic command?  For example:

```posh
$sw = [System.Diagnostics.Stopwatch]::StartNew()
... first line of script
$sw.Stop()
"At line XX, elapsed mSecs: $($sw.ElapsedMilliseconds)" >> $Home\promptProfiling.txt

$sw.Restart()
... another line of script
"At line XX, elapsed mSecs: $($sw.ElapsedMilliseconds)" >> $Home\promptProfiling.txt
```
Then load the profile and see what results you get for the prompt function.  Maybe to start with, you simply time the entire prompt function to see if the delay is in the prompt function.

Also, execution policy could be set differently between the machines.  Is your profile on the 5.0 machine signed i.e. has an ExecutionPolicy of `AllSigned` (or maybe `RemoteSigned`).  Check the policy with `Get-ExecutionPolicy`.

**Comment by SeeminglyScience** [comment]
Another thing to try, run this in the console that isn't loading it

```powershell
code $profile
```
This should load your VSCode profile.  If it doesn't load the file you expect, double check the path and name.

**Comment by rkeithhill** [comment]
It would really help if you could first reproduce the problem and then grab the session log file and attach it to this request.  

You can do the latter by opening the command palette (<kbd>Ctrl+Shift+P</kbd>) and executing the command `PowerShell: Open PowerShell Extension Logs Folder`.  A new VSCode instance will start.  Open the `EditorServices.log` file.  Right click on the editor window's title tab for EditorServices.log and select `Copy path`.  Use that path to zip the log file and then attach that zip file to this issue.  Just make sure the log file is from a session where you've reproduced the problem.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
