### ISSUE TITLE
Scripts fail to launch in debugger (or open in ISE) if working directory path contains spaces

### ISSUE THREAD

**Issue by durmiun** [PowerShell/vscode-powershell#94]
Example: D:\powershell code\Get-Something.ps1 will fail to launch with the following error:

d:\powershell : The term 'd:\powershell' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ d:\powershell code\Get-OutlookPublicFolders.ps1
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (d:\powershell:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

launch.json contains the default settings (as of 0.4.0 release of Powershell extension):

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "PowerShell",
			"type": "PowerShell",
			"request": "launch",
			"program": "${file}",
			"args": [],
			"cwd": "${file}"
		}
	]
}
```

I have also tried placing the full path name in the cwd parameter, using escaped double quotes, single quotes, etc.

**Comment by daviwil** [comment]
Perfect, thanks for filing this! Should be an easy fix.

**Comment by rkeithhill** [comment]
We should switch to using PathIntrinsics to set the working dir.   For now you should be able to work around this by specifying the full path with spaces escaped e.g.:
```json
"cwd": "C:\\Users\\Keith\\Foo` Bar"
```

**Comment by daviwil** [comment]
Ah yes! The back tick is the trick.

**Comment by rkeithhill** [comment]
BTW this issue also impacts the "Open file in ISE" command.  :-(

**Comment by daviwil** [comment]
Ouch! That's OK, should be relatively easy to make a backtick escaper in JavaScript.

**Comment by rkeithhill** [comment]
Hmm, I was planning on fixing it in PSES.  Do you think it would be better to do in the extension JavaScript?

**Comment by daviwil** [comment]
The debug program path issue will need to be fixed in PSES but the 'Open in ISE' command is done purely in TypeScript (for now)

**Comment by durmiun** [comment]
Awesome, thank you for the quick turn around on this!

**Comment by daviwil** [comment]
Keith is the man! We're planning to ship an update sometime next week with this fix and a few others.
