### ISSUE TITLE
Temporary console debugging hangs on PowerShell Integrated Console prompt

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/vscode-powershell#942]
### System Details

- Operating system name and version: Windows 10.0.15063 x64
- VS Code version: 1.13.1
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.15063.447
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.447
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Temporary console debugging hangs on PowerShell Integrated Console prompt.

*Note:* When "createTemporaryIntegratedConsole" is set to *false* debugging works as exptected.

### Steps to recreate

- Enable temporary intergrated console debugging in settings
```javascript
"powershell.debugging.createTemporaryIntegratedConsole": true
```
- Set breakpoint in script or module and hit F5
- Debugging hangs on PowerShell Inegrated Console message

![](https://user-images.githubusercontent.com/11281622/27659060-3d3bd70a-5ca6-11e7-9529-7dda44376d5b.png)

### Attached Logs
[1499442772-8c16997c-e92b-442f-949d-94aa6756e65b1499442771245.zip](https://github.com/PowerShell/vscode-powershell/files/1131540/1499442772-8c16997c-e92b-442f-949d-94aa6756e65b1499442771245.zip)

**Comment by daviwil** [comment]
Hey Kris, which debugging configuration are you using, is it the one called "PowerShell Interactive Session"?

**Comment by kborowinski** [comment]
Exactly David. It's "PowerShell Interactive Session" configuration.

**Comment by daviwil** [comment]
Cool!  Just fixed it, it'll be in the next update.

**Comment by kborowinski** [comment]
Do I miss something? It still does not work in PowerShell 1.4.2 extension.

**Comment by daviwil** [comment]
Hey @kborowinski, sorry for the delay on this, it's going out with the update I'm shipping today!
