### ISSUE TITLE
'Go to Definition' not opening the correct file

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/vscode-powershell#946]
### System Details

- Operating system name and version: Windows Server 2012 64 bit
- VS Code version: 1.15.0-insider
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the pa
th is correct and try again.
At line:1 char:1
+ code -v
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS S:\Prod> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0


PS S:\Prod> code --list-extensions --show-versions
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the pa
th is correct and try again.
At line:1 char:1
+ code --list-extensions --show-versions
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Issue Description

We have a function called `Get-Foo`, this function is available in a module located in the standard module path. On top of this, this specific function is also created with the same name within a workflow in one specific script. When I now open another script, and press F12 `Go to Definition` it will redirect me to the script containing the PowerShell Workflow and not to the desired location. the module file.

**So what do we have?**

- Module `C:\Program Files\WindowsPowerShell\Modules\MyModule\MyModule.psm1` containing the function `Get-Foo`.
- Script `S:\Prod\Script A.ps1` containing a PowerShell Workflow where this function is recreated in in an `InlineScript` clause with a simple copy paste of the original function from the module..
- Script `S:\Prod\Script B.ps1` where we simply use function `Get-Foo` and get redirected to `Script A` instead of the module, when we want to go to the definition using `F12`.

**Comment by PrzemyslawKlys** [comment]
This seems to be old and solved already. It should be good to close.
