### ISSUE TITLE
Incompatible with insider version

### ISSUE THREAD

**Issue by unuunc** [PowerShell/vscode-powershell#95]
Getting following Issue -
[C:/Users/{}/.vscode-insiders/extensions/ms-vscode.PowerShell-0.4.0]: Extension is not version compatible with VSCode. VSCode version: 0.10.7-insider, extension's declared engine: ^0.10.8

**Comment by unuunc** [comment]
to fix modified package.json to look for VSCode version: 0.10.7-insider. no longer getting error. but we need to handle insider versions also.

**Comment by daviwil** [comment]
Yep!  Another user reported that yesterday.  I need to ask the VS Code team how to support both versions.

**Comment by daviwil** [comment]
Filed a bug to ask the VS Code team how to deal with this problem: https://github.com/Microsoft/vscode/issues/2894

**Comment by daviwil** [comment]
I believe the VS Code team has updated their Insider release to 0.10.8 now so the extension should work in both that and the mainline release.  We'll update our package.json once they provide a supported way to mark the extension available for both mainline and insider releases.
