### ISSUE TITLE
Formatter does not run at all with certain unusual string line continuation construct

### ISSUE THREAD

**Issue by poshcodebear** [PowerShell/vscode-powershell#951]
### System Details

- Operating system name and version: Windows 10 RS2
- VS Code version: 1.14.0
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
```
1.14.0
b8cd5b9556d8b70ea560d35b903422363f6c5c40

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

abusaidm.html-snippets@0.1.0
alefragnani.project-manager@0.18.1
dbaeumer.vscode-eslint@1.2.11
donjayamanne.python@0.6.7
eg2.tslint@0.16.0
formulahendry.code-runner@0.6.25
jchannon.csharpextensions@1.3.0
johnpapa.Angular2@2.3.3
lonefy.vscode-JS-CSS-HTML-formatter@0.2.3
ms-vscode.csharp@1.11.0
ms-vscode.PowerShell@1.4.1
robertohuertasm.vscode-icons@7.10.1
Shan.code-settings-sync@2.8.2
xabikos.JavaScriptSnippets@1.4.1
Zignd.html-css-class-completion@1.7.0

Name                           Value
----                           -----
PSVersion                      5.1.15063.413
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.413
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

When running the code formatter, it will not work at all when a certain construct is used.  Here's a sample bit of code to demonstrate:
```
Write-Output ("this is a test" +
              " Just a test")

if ($true) {
    "It's true"}
```
If you run the code formatter on that bit of code, I would expect at the very least the final curly brace to be moved to the following line, but nothing happens.  If you remove the parentheses around the string, though, it works fine; however, this outputs a string array instead of a flat string.

### Attached Logs
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1143205/logs.zip)

**Comment by kapilmb** [comment]
I think I understand the issue regarding the closing brace in the `if` statement. However, I do not understand the issue with regarding the `write-output` statement. Can you please provide more explanation about it? Thanks.

**Comment by poshcodebear** [comment]
The Write-Output statement (more specifically, the string) causes the formatter to do nothing.  If you add that line or one with a string formatted similarly to it, the formatter will not make any changes to the document at all.  I just included the if statement as an example.

**Comment by kapilmb** [comment]
Thanks for the clarification. The `write-output` statement is actually messing up the formatter in some way. If you remove or even comment out the `write-output` statement, the formatter handles the `if` statement properly.

**Comment by SydneyhSmith** [comment]
Closing as this issue is resolved.
