### ISSUE TITLE
Formatter does not handle foreach method correctly

### ISSUE THREAD

**Issue by poshcodebear** [PowerShell/vscode-powershell#952]
### System Details

- Operating system name and version: Windows 10 RS2
- VS Code version: 1.14.0
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
```
1.14.0
b8cd5b9556d8b70ea560d35b903422363f6c5c40

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

abusaidm.html-snippets@0.1.0
alefragnani.project-manager@0.18.1
dbaeumer.vscode-eslint@1.2.11
donjayamanne.python@0.6.7
eg2.tslint@0.16.0
formulahendry.code-runner@0.6.25
jchannon.csharpextensions@1.3.0
johnpapa.Angular2@2.3.3
lonefy.vscode-JS-CSS-HTML-formatter@0.2.3
ms-vscode.csharp@1.11.0
ms-vscode.PowerShell@1.4.1
robertohuertasm.vscode-icons@7.10.1
Shan.code-settings-sync@2.8.2
xabikos.JavaScriptSnippets@1.4.1
Zignd.html-css-class-completion@1.7.0

Name                           Value
----                           -----
PSVersion                      5.1.15063.413
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.413
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When using the foreach method on an array, the formatter does not indent or space correctly.  For example, if you do something like this:
```
$items.foreach({
    # Do things
})
```
the formatter will format it like this:
```
$items.foreach( {
        # Do things
    })
```
It probably has something to do with having two open and two close braces right next to each other like that; when done this way, though, they should be treated as a single open and single close.

### Attached Logs

I don't think this needs logs since it's not causing errors per se, but if you want them, I can produce them for you.  Just let me know.

**Comment by kapilmb** [comment]
We are tracking an identical issue at #576. Please subscribe to that issue for updates regarding this issue.

**Comment by poshcodebear** [comment]
Thanks!

I looked through the formatter issues but didn't spot that one.  Sorry for the duplicate.

**Comment by kapilmb** [comment]
No problem at all!

**Comment by msftrncs** [comment]
This is not the same issue as #576, and now another new issue was opened instead at #1168, but then ultimately closed because the entire formatting comes from an upstream.

(just linking the issues together)
