### ISSUE TITLE
Ctrl+C not working

### ISSUE THREAD

**Issue by bgraeb** [PowerShell/vscode-powershell#955]
In integrated console, it's not longer possible to interrupt script execution via `Ctrl+C`. It throws the error: `Cannot read property 'length' of undefined` at the top of VS Code

### System Details

- Operating system name and version: Windows 10.0.15063
- VS Code version: 1.14.0
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
```
1.14.0
b8cd5b9556d8b70ea560d35b903422363f6c5c40

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0       

bbenoist.vagrant@0.5.0
chrmarti.regex@0.1.0
DavidAnson.vscode-markdownlint@0.9.1
donjayamanne.githistory@0.2.1
DotJoshJohnson.xml@1.9.2
eamodio.gitlens@4.3.1
formulahendry.code-runner@0.6.25
luggage66.VBScript@0.0.1
ms-vscode.csharp@1.11.0
ms-vscode.PowerShell@1.4.1
PKief.material-icon-theme@2.0.10
psake.psake-vscode@0.1.0
rebornix.Ruby@0.12.1
Shan.code-settings-sync@2.8.2
streetsidesoftware.code-spell-checker@1.2.1
                                                                                                                                                      
PSVersion                      5.1.15063.483                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                     
BuildVersion                   10.0.15063.483                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                             
WSManStackVersion              3.0                                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                                         
SerializationVersion           1.1.0.1                                                                                                                                                                     
```

### Issue Description

When running a command in integrated console (e.g. `Start-Sleep 10`) and trying to stop the execution via `Ctrl+C`, VS Code throws the error: `Cannot read property 'length' of undefined`. I deactivated all other extensions to verify. Issue's still there.

### Attached Logs

No logs, as it failes consistent.

**Comment by bgraeb** [comment]
Looks like this issue was created and fixed by the last two vs code updates. this can be closed

**Comment by wsmelton** [comment]
This is still happening to me in version 1.14.2 for both 32-bit and 64-bit version of Code. I'm on extension 1.4.1. 

@bgraeb If it was fixed what version should we be on?

Just hit CTRL+C in the integrated terminal with nothing running or a command that is stuck in a loop and I get this bar:

![image](https://user-images.githubusercontent.com/11204251/28746258-488a8128-744e-11e7-88a6-96a0b0c8c4bb.png)

**Comment by wsmelton** [comment]
It is odd but after reloading the window a few times it started working again.

**Comment by rkeithhill** [comment]
Heisenbugs like this are a pain to track down & fix. :-(  BTW is there anywhere in your prompt function you are access the `length` property on an object?
