### ISSUE TITLE
When I type a parameter with a whitespace, why there's not list the value list for this parameter? just like powershell ISE did.

### ISSUE THREAD

**Issue by SilenceHe** [PowerShell/vscode-powershell#958]
![tim 20170714153408](https://user-images.githubusercontent.com/4414171/28203249-71f63ed4-68ab-11e7-916a-bd00fcccb034.png)
### Issue Description

When I type a parameter with a whitespace, why there's not list the value list for this parameter? just like powershell ISE did.

### Example：
Invoke-RestMethod -Method 

Note: see attachment for details

**Comment by kamilkosek** [comment]
I think it´s because IntelliSense isn´t triggered after a whitespace.
You could press <kbd>Ctrl</kbd> + <kbd>Space</kbd> to trigger it manually.

**Comment by SilenceHe** [comment]
Looks it's not work for me with Ctrl + Space

By the way, the VS Code version is 1.14.1 and the powershell extension version is 1.4.1

**Comment by kapilmb** [comment]
I am not able to reproduce it. Here is what I observe. 
![psesissue](https://user-images.githubusercontent.com/14225543/28226765-229a67d0-688c-11e7-825b-e9feec30d9a5.gif)

Maybe the completion request is getting timed out. Can you please provide the 'verbose' logs? Thanks.

**Comment by SilenceHe** [comment]
@kapilmb My pleasure, but how to get the 'verbose' logs in this case? I don't know how to do that

**Comment by DarkLite1** [comment]
Having the same issue in vs code `1.15.0 Insider`:

![image](https://user-images.githubusercontent.com/10828570/28262391-176d1bec-6ae3-11e7-987d-c5cd436ea5da.png)

**Comment by kapilmb** [comment]
@SilenceHe Sorry for the delay in response. To enable `verbose` logging open `user settings`. (To open `user settings`, open the `command palette` and type `user settings`.). Once your settings are open, search for `powershell.developer.editorServicesLogLevel` setting and set it to `verbose`. 

@DarkLite1 You *need* to press <kbd>ctrl</kbd>+<kbd>space</kbd> for the pop-up to show up for argument completion. It does pop-up on its own as opposed to when a pop-up shows up when writing a parameter name that starts with `-`.
