### ISSUE TITLE
Make formatter capitalize cmdlets and parameters

### ISSUE THREAD

**Issue by Hvid** [PowerShell/vscode-powershell#960]
Please make it possible to capitalize cmdlets and parameters by pressing tab like ISE. 

In ISE, when cursor is placed in the middle of the line "write-host" and you press tab, it becomes "Write-Host". Same goes for parameters - "-erroraction" becomes "-ErrorAction"

Maybe the "Format Document" command could do the same?

**Comment by kapilmb** [comment]
Here is a similar issue: PowerShell/PSScriptAnalyzer#767

**Comment by DarkLite1** [comment]
+1 on this

**Comment by krissmilne** [comment]
As Powershell isn't a case sensitive language, it would be good to provide the case formatting options for the developers preference.

Something along the lines of:

//Changes the case for powershell reserved words (if, else, elseif, function, switch, param etc...) to either UPPER, lower or First (capitalises the first letter)
"powershell.codeFormatting.reservedWordCase": "lower", "upper", "first"

//Changes the case for powershell variables declared in the global or script scope to either UPPER, lower or FirstUpper (PascalCase) or firstLower (camelCase)
"powershell.codeFormatting.globalVariableCase": "lower", "upper", "FirstUpper", "firstLower"

//Changes the case for powershell variables declared in the local or private scope (within functions) to either UPPER, lower or FirstUpper (PascalCase) or firstLower (camelCase)
"powershell.codeFormatting.privateVariableCase": "lower", "upper", "FirstUpper", "firstLower"

//Autocorrects the case for recognised cmdlets and functions
"powershell.codeFormatting.cmdletCase": true, false

//Autocorrects the case for recognised parameters of cmdlets and functions
"powershell.codeFormatting.parameterCase": true, false

**Comment by tylerl0706** [comment]
This is actually an issue to be solved in PSScriptAnalyzer. I'm going to close this favor of this:
PowerShell/PSScriptAnalyzer#767
