### ISSUE TITLE
Passing Arguments to vscode-powershell

### ISSUE THREAD

**Issue by jbruns2015** [PowerShell/vscode-powershell#965]
### System Details

- Operating system name and version:
- VS Code version:
- PowerShell extension version:
- Output from `$PSVersionTable`:

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

Another stupid question.  How do I pass in arguments when running Powershell code in VS code Powershell editor?

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
Have a look at:

https://blogs.technet.microsoft.com/heyscriptingguy/2017/02/06/debugging-powershell-script-in-visual-studio-code-part-1/
https://blogs.technet.microsoft.com/heyscriptingguy/2017/02/13/debugging-powershell-script-in-visual-studio-code-part-2/

Specifically part 2, section "Launch configuration settings / variables".  You can also add a new Debug Configuration (open your .vscode/launch.json file and press the Add Config button) called "PowerShell: Launch Current File w/Args".  This configuration will prompt you for the arguments.

**Comment by jbruns2015** [comment]
Does this look right?

I just want to pass a string “qa” as argument zero.

The top portion of my launch.json file

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File w/Args Prompt",
            "script": "${file}",
            "args": ["-myArg qa"],
            "cwd": "${file}"


-Joe B.

**Comment by rkeithhill** [comment]
If you want VSCode to prompt you for the args, make your set your args to:
```
"args": [ "${command:SpecifyScriptArgs}" ]
```
If you want to specify the args directly in the launch.json, what you have should work.  Just make sure the file you want to debug is in the active editor window when you press <kbd>F5</kbd>.

**Comment by jbruns2015** [comment]
My issue was I was opening ps1 directly with VS Code which suppresses the gear icon, confusing the hell out of me.

[cid:image001.png@01D2FFC5.7C0AABC0]

-Joe B.

**Comment by rkeithhill** [comment]
Glad you got it working.

**Comment by diman82** [comment]
@jbruns2015 Can you please share with me how you resolved this issue?
I'm having trouble understanding where should I put this launch.json file, and also if this workd olny in debug mode or also in "Run Code" mode..
Plz contact me at: diman82@gmail.com
