### ISSUE TITLE
PowerShell Integration Console is not returning a prompt

### ISSUE THREAD

**Issue by johlju** [PowerShell/vscode-powershell#967]
### System Details

- Operating system name and version: Windows 10 Pro Insider Preview (build 16232_rs_prerelease.170624-1334)
- VS Code version: 1.14.2
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`: See below

```
PS> code -v
1.14.2
cb82febafda0c8c199b9201ad274e25d9a76874e
PS> $pseditor.EditorServicesVersion # Unable to run this.
PS> code --list-extensions --show-versions
DavidAnson.vscode-markdownlint@0.10.0
donjayamanne.githistory@0.2.2
eamodio.gitlens@4.3.2
ms-vscode.csharp@1.11.0
ms-vscode.PowerShell@1.4.1
PeterJausovec.vscode-docker@0.0.16
ryu1kn.annotator@0.10.1
streetsidesoftware.code-spell-checker@1.3.0
Tyriar.theme-sapphire@0.2.1
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16232.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16232.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
PowerShell Integration Console is not giving me a prompt. But I can debug. This started a while back. Not sure when exactly. Haven't had the need for the prompt (until today), so have waited it out if this would be solved.

This does work on a Windows Server 2016 with the same version of everything (VS Code, and all the extensions). So guessing something is wrong with my installation or vscode-powershell has some issues with the current Windows build? Anyone else having issues? 

![powershellintegrationconsolenotstarting](https://user-images.githubusercontent.com/7189721/28489963-989edf12-6ecf-11e7-94d1-2e7e7ade961d.gif)

### Attached Logs
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1167240/logs.zip)

**Comment by nromyn** [comment]
I'm seeing this too.

**Comment by daviwil** [comment]
You have two options:


- Upgrade to Windows Insider Fast Ring build 16241 (or higher)

- Use the workaround here: https://github.com/PowerShell/vscode-powershell/issues/742#issuecomment-301915916

**Comment by johlju** [comment]
@daviwil Installed the latest fast ring. Now it works again. Thanks! 😄
