### ISSUE TITLE
Debugger does not return pointer in powershell when using call operator (&)

### ISSUE THREAD

**Issue by weinand** [PowerShell/vscode-powershell#968]
_From @mohakraaj on July 22, 2017 21:0_

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9
xml|Dot|1.9.2
intellij-idea-keybindings|k--|0.2.12
MagicPython|mag|1.0.11
mssql|ms-|1.1.0
csharp|ms-|1.11.0
mono-debug|ms-|0.15.6
PowerShell|ms-|1.4.1
resharper9-keybindings|ms-|1.1.0
vscode-docker|Pet|0.0.16
python|tht|0.2.3

---

Steps to Reproduce:

1. Start debugging powershell script 
2. If script has '&' operator, debug does not return pointer

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#31264_

**Comment by weinand** [comment]
Powershell debugging is provided by an extension; it is not part of VS Code.

**Comment by rkeithhill** [comment]
I believe this is a misunderstanding of what the `&` operator is for in PowerShell. It does **not** return a `pointer`.  It merely invokes the command "named" by the string following the `&` operator e.g.:

```posh
$ipconfigPath = "${env:windir}\system32\ipconfig.exe"
& $ipconfigPath
```
This execute ipconfig.exe - nothing more.  

If the command to execute was a PowerShell scriptblock, then the scriptblock is invoked and executed e.g.:
```posh
& {param($name) "Name is $name"} "Valentine Michael Smith"
```
This invokes the scriptblock (aka anonymous method) with the one parameter.  Again, no `pointer` is returned.
