### ISSUE TITLE
Formatter inserts space in between open brace and curly brace for .Where() and .ForEach() methods

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/vscode-powershell#970]
### System Details

- Operating system name and version: Windows 10.0.15063 x64
- VS Code version: 1.14.2
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.15063.483
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.483
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Formatter inserts space in between open brace and curly brace for .Where() and .ForEach() methods.

![formatting](https://user-images.githubusercontent.com/16168755/28501883-bcc9b5e4-6fe5-11e7-9f85-8d796e3a7a0e.gif)

**Comment by DarkLite1** [comment]
Duplicate with #576

**Comment by TylerLeonhardt** [comment]
Thanks @DarkLite1! Yes that looks like a duplicate. This is being/has been fixed on the PSScriptAnalyzer side.

Take a look at #576 for more info.
