### ISSUE TITLE
Markdown file formating breaks when file is added into git staging area.

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/vscode-powershell#976]
Hi all,

I have an issue that breaks the formating of a markdown file as soon as we add it into a git repository.

the gif here under shows what the issue is, and how to reproduce it.

![2017-07-25_14-17-20](https://user-images.githubusercontent.com/6302961/28571642-287a0a14-7144-11e7-83f3-cdf291e05a29.gif)

I double checked, the file was of file format 'ASCI' before and **after** I added it to the staging area.

The Gist of the readme.md is available here --> https://gist.github.com/Stephanevg/dc3e11a64c89047e0e8794a3816a442b

**Should this go to EditorSyntax repo?**

System Details

Operating system name and version: seen on Windows 10

$pseditor.EditorServicesVersion

1.14.1
2648980a697a4c8fb5777dcfb2ab110cec8a2f58

code --list-extensions --show-versions
ms-vscode.PowerShell@1.4.1

$PSVersionTable
$PsVersionTable:

Name                           Value
----                           -----
PSVersion                      5.0.10586.962
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.962
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by rkeithhill** [comment]
This is very unlikely to be a PowerShell extension issue.  I suggest you file this on https://github.com/microsoft/vscode/issues since Markdown file editing is a feature of VSCode.

From the animated GIF, I said you have a file encoding change that has happened after editing the file in VSCode.  Perhaps the file was Unicode and got switch to UTF8 (or vice versa).

**Comment by Stephanevg** [comment]
Yeah, makes sense actually. 
Thanks for pointing me to the right place. I have open an issue there with the following number -> https://github.com/Microsoft/vscode/issues/31432 

Santé!
