### ISSUE TITLE
Debug attached process has terminated unexpectedly

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/vscode-powershell#978]
### System Details

- Operating system name and version: Windows 10.0.15063 x64
- VS Code version: 1.14.2
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.15063.483
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.483
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Issue Description

Debugger crashes every time when debugging attached process.

![debugerror](https://user-images.githubusercontent.com/16168755/28624078-39515890-7218-11e7-83f3-8605a4d2282f.gif)

### Attached Logs

[1501075112-0b3568e5-41ec-45e6-8da2-0693897f51661501075109351.zip](https://github.com/PowerShell/vscode-powershell/files/1176698/1501075112-0b3568e5-41ec-45e6-8da2-0693897f51661501075109351.zip)

**Comment by mklement0** [comment]
I'm seeing the same thing when attaching to a host process as of 1.5.0, except that it doesn't always crash; sometimes it hangs. On Windows 7 it _never_ works for me, on Windows 10 it _sometimes_ does.

It crashes / hangs during the process of attaching.

The info below is from a Windows 7 machine.

* Operating system name and version: Windows 7 x64 (Version 6.1.7601 Service Pack 1 Build 7601)
* VS Code version: 1.17.2
* PowerShell extension version: 1.5.0
* Output from $PSVersionTable:

````
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Logs from a hang:

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1429033/logs.zip)

**Comment by TylerLeonhardt** [comment]
We've done a ton of work on debugging and I don't believe this is still happening.

I'm going to close this but if you're still seeing this, please let me know!
