### ISSUE TITLE
Consider providing an FAQ 

### ISSUE THREAD

**Issue by kamilkosek** [PowerShell/vscode-powershell#979]
Hi, 
I was browsing through some issues and saw a lot of them where people were asking the same things: 

- Is PSReadLine Supported ? 

- What it is all about with the Terminals (powershell, PowerShell Integrated Console)?

- Why is Code Folding so weird ? 
etc...
What you guys think about it ?

**Comment by rkeithhill** [comment]
Great idea. This is a start.  And it needs to be linked to from the README.md file.  https://github.com/PowerShell/vscode-powershell/wiki/FAQ
