### ISSUE TITLE
Comments in body of function break function

### ISSUE THREAD

**Issue by MustQ** [PowerShell/vscode-powershell#982]
### System Details

- Operating system name and version: Windows 10
- VS Code version:  latest 1.14.2
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable

1.14.2
cb82febafda0c8c199b9201ad274e25d9a76874e
ms-vscode.PowerShell@1.4.1
slevesque.perforce@2.1.1
```

### Issue Description
When I put a comment within the body of a function, VScode seems to not recognize that the lines beyond the comment are still part of the same function. 

Repro example:

Function Remove-P4User {
[cmdletbinding()]
    Param (
    [Parameter(Helpmessage='Enter a username with admin rights to run the command')]
    $p4user,
    [Parameter(Helpmessage='Enter a server in perforce format %servername%:%port%')]
    $p4port,
    [Parameter(Mandatory=$True,HelpMessage='Enter the username you wish to delete from Perforce')]
    $Username
    )

#$ErrorActionPreference = "Stop"

try{
    $workspaces = p4 -u $p4user -p $p4port -Ztag -F "%client%" clients -u $Username
        foreach ($workspace in $workspaces){
        p4 -u $p4user -p $p4port client -df -Fs $workspace
        }
    p4 -u $p4user -p $p4port user -d -F $Username
    }

catch {
    ($Error[0] -split '\n')[0]
    }
}

If you paste that into VScode, you'll see that the commented #$erroractionpreference breaks the function.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by daviwil** [comment]
Hey @MustQ, when you say "breaks the function", do you mean that it breaks syntax highlighting?

**Comment by AspenForester** [comment]
Environment:
1.17.2
b813d12980308015bcd2b3a2f6efa5c810c33ba5
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0
ms-vscode.PowerShell@1.4.3
robertohuertasm.vscode-icons@7.16.0
Name                           Value
----                           -----
PSVersion                      5.1.15063.632
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.632
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Unable to reproduce any "breakage"
Syntax highlighting highlighting continues to work.
Can't vouch for what p4(.exe???) may or may not be doing.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue/repro is provided--thanks!
