### ISSUE TITLE
Problems with Powerhsell cmdlet Get-ItemProperty

### ISSUE THREAD

**Issue by mariodeleon** [PowerShell/vscode-powershell#983]
### System Details

- Operating system name and version:
OS Name:                   Microsoft Windows Server 2012 Standard
OS Version:                6.2.9200 N/A Build 9200

- VS Code version: 1.14.2
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:
Name                           Value                                                                                                   
----                           -----                                                                                                   
PSVersion                      5.1.14409.1005                                                                                          
PSEdition                      Desktop                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                 
BuildVersion                   10.0.14409.1005                                                                                         
CLRVersion                     4.0.30319.42000                                                                                         
WSManStackVersion              3.0                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                     
SerializationVersion           1.1.0.1 

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```
PS C:\Program Files\NSClient\scripts> 
code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable

1.14.2
cb82febafda0c8c199b9201ad274e25d9a76874e

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0
ms-vscode.PowerShell@1.4.1

Key   : PSVersion
Value : 5.1.14409.1005
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.14409.1005
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion

```

### Issue Description

I am experiencing a problem when I run the following:

**On Visual Studio Code**
------------------------------------------------------------------
$AppName = "Bladelogic"
Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | where {$_.displayname -match $AppName} | select -ExpandProperty displayname 

OUTPUT:
The property 'displayname' cannot be found on this object. Verify that the property exists.
At line:2 char:80
+ ... tVersion\Uninstall\* | where {$_.displayname -match $AppName} | selec ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Where-Object], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.WhereObjectCommand

**On OS Builtin Powershell_ISE**
------------------------------------------------------------------
$AppName = "Bladelogic"
Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | where {$_.displayname -match $AppName} | select -ExpandProperty displayname 

OUTPUT:
BMC BladeLogic Server Automation RSCD Agent

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
Can you check the process architecture of both by running `[intptr]::size`?

**Comment by mariodeleon** [comment]
From Visual Studio Code
[intptr]::size = 8
------------------------------
From OS Builtin Powershell_ISE
[intptr]::size = 8

**Comment by mariodeleon** [comment]
These are my only changes in Visual Studio Code configurations

launch.json
--------------------------------------------------
{
    "version": "0.2.0",
    "configurations": [
       
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File",
            "script": "${file}",
            "args": [],
            "cwd": "${file}"
        }
    ]
}


settings.json
----------------------------------------------------
// Place your settings in this file to overwrite default and user settings.
{
"powershell.scriptAnalysis.enable": false, 
"terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"  
}

**Comment by mariodeleon** [comment]
Yo can now close this issue:
-------------------------------------------------------------
I had to change my code in Visual Studio Code to:
$AppName = "bladelogic"
$RegQry = Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*  
$BladeLogicRegQry = $RegQry | where {$_ -match $AppName} | select displayname

**Comment by daviwil** [comment]
Glad to hear you figured it out!
