### ISSUE TITLE
Debug Service crash stepping through PowerShell module

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#985]
### System Details

- Operating system name and version: Windows Server 2016
- VS Code version: 1.4.1 (x64 bit)
- PowerShell extension version: 1.4.1
- Output from `$PSVersionTable`:

```
C:\Windows\system32> code -v
1.14.2
cb82febafda0c8c199b9201ad274e25d9a76874e
C:\Windows\system32> $pseditor.EditorServicesVersion
C:\Windows\system32> code --list-extensions --show-versions
CoenraadS.bracket-pair-colorizer@0.10.7
donjayamanne.githistory@0.2.2
DotJoshJohnson.xml@1.9.2
dustinsanders.an-old-hope-theme-vscode@2.0.0
eamodio.gitlens@4.3.3
fabiospampinato.vscode-statusbar-debugger@1.0.3
ms-mssql.mssql@1.1.0
ms-vscode.PowerShell@1.4.1
ms-vscode.wordcount@0.1.0
RoscoP.ActiveFileInStatusBar@1.0.2
sensourceinc.vscode-sql-beautify@0.0.4
Shan.code-settings-sync@2.8.2
streetsidesoftware.code-spell-checker@1.3.2
tnaseem.theme-seti@0.0.2
Tyriar.shell-launcher@0.1.1
waderyan.gitblame@2.0.2
C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1480
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1480
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with...debug services crashing. 

Oddly enough I've had it step through this before, but after it crashing 2 or 3 times figured I'd post these logs. I get to a certain line in the module that builds an object using `Microsoft.SqlServer.Managemenet.Smo.Server`. It steps past the first few lines but while I step into the command more it seems like it is pausing, then it just crashes.

Logs are attached below from extension log.

### Attached Logs

[temp.zip](https://github.com/PowerShell/vscode-powershell/files/1202080/temp.zip)

**Comment by daviwil** [comment]
Thanks Shawn, I'll take a look.

**Comment by SetTrend** [comment]
This still frequently happens.

**Comment by SydneyhSmith** [comment]
@SetTrend thanks for the feeback! If you experience more crashes it really helps us in terms of debugging/getting to the root of these issues if you are able to provide logs --instructions for how to do that are [here ](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment)

**Comment by SetTrend** [comment]
@SydneyhSmith:

Sorry for my late reply. Holidays intercepted an early answer.

Attached please find the log files you requested:

[PowerShell extension error log.zip](https://github.com/PowerShell/vscode-powershell/files/3596853/PowerShell.extension.error.log.zip)

I stripped all personal data so far, including the code that's been executed, as it's propietary to my customers'. I might PN the code to you if requested, perhaps at Gitter.

**Comment by SydneyhSmith** [comment]
@SetTrend thanks for the logs, looks like you are hitting a race condition---we are always working to improve performance in our extension, one thing to try is our PowerShell Preview Extension which has the latest performance updates we have made...thanks for opening the issue!

**Comment by JustinGrote** [comment]
@SydneyhSmith @TylerLeonhardt seems fixed to me on new version, I haven't been able to create any race conditions by mashing F10 through a debug.

**Comment by SetTrend** [comment]
At the moment I don't have access to a large PowerShell script, I'm afraid. The customer's project has finished.

If you believe this issue is fixed, please feel free to close. I will happily agree and test sometime later.
