### ISSUE TITLE
Login-AzureRmAccount command stuck in Powershell Integrated Console

### ISSUE THREAD

**Issue by solomonsunder** [PowerShell/vscode-powershell#986]
### System Details

- Operating system name and version:

Windows 10 Pro, Version 1703, OS Build 15063.502

- VS Code version:

1.14.2

- PowerShell extension version:

bradygaster.azuretoolsforvscode@1.2.9
donjayamanne.githistory@0.2.3
formulahendry.azure-iot-toolkit@0.1.3
johnpapa.azure-functions-tools@0.3.0
ms-mssql.mssql@1.1.0
ms-vscode.azurecli@0.1.0
ms-vscode.csharp@1.11.0
ms-vscode.PowerShell@1.4.1
ms-vscode.vscode-azureextensionpack@0.0.4
msazurermtools.azurerm-vscode-tools@0.3.6
PeterJausovec.vscode-docker@0.0.16
usqlextpublisher.usql-vscode-ext@0.2.4
 
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

$pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0

### Issue Description

I am unable to login using Login-AzureRmAccount command. It is stuck and never comes up with the GUI pop up. It works fine on normal powershell. 
Login-AzureAsAccount command works fine and it triggers the GUI popup to login to my organisation ID.

I have tried reinstalling VS Code, updating powershell modules etc using both Web PI and command line to no help.

### Attached Logs

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1203185/logs.zip)

**Comment by dfinke** [comment]
I believe the Azure Login Window pops up behind the other windows, that's what happens on my system, I have the latest vsc + pses. It doesn't show up on top.

**Comment by solomonsunder** [comment]
@dfinke Thanks. I just found that out. I was reading another bug issue which mentioned it'd appear on Alt+Tab but didn't appear on mine. But when I minimised my browser etc, I could see it there.
However, it appearing on the top for the other command, made me miss that. Not sure if this is still a bug.

**Comment by willam-gregoire** [comment]
Same happens with **Add-AzureAccount**, appears behind the console.

**Comment by dfinke** [comment]
IIRC, it's a VS Code issue, don't know the timeline on it.

**Comment by daviwil** [comment]
Tracked by issue #621, will hopefully have a fix for it soon.

**Comment by simeyla** [comment]
Is there a `Ctrl+C` type command? 
Or if we can't find the login dialog is it permanently stuck?
