### ISSUE TITLE
Minor Foreach issue in script analyser

### ISSUE THREAD

**Issue by tsiemons** [PowerShell/vscode-powershell#990]
PS C:\Users\TonSiemons\OneDrive\Powershell\SSP> code --list-extensions --show-versions
Kipters.codeshell@0.2.2
ms-mssql.mssql@1.1.0
ms-vscode.PowerShell@1.4.1
PS C:\Users\TonSiemons\OneDrive\Powershell\SSP> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I am experiencing a problem with...
severity: 'Warning'
message: ''foreach' is an alias of 'ForEach-Object'. Alias can introduce possible problems and make scripts hard to maintain. Please consider changing alias to its full content. (PSAvoidUsingCmdletAliases)'
at: '159,69'
source: 'PSScriptAnalyzer'
Foreach is not always an alias of foreach-object. if you use foreach at the start of a line it's a powershell statement. Not an alias.

**Comment by daviwil** [comment]
Moving this issue to the PSScriptAnalyzer repo.

**Comment by daviwil** [comment]
This issue was moved to PowerShell/PSScriptAnalyzer#812
