### ISSUE TITLE
Intellisense is broken in VSCode when using pipes

### ISSUE THREAD

**Issue by r12f** [PowerShell/vscode-powershell#992]
### Issue Description
Hi Team, I just started using vscode-powershell extension. And I like it a lot so far. But I was running into an issue, which intellisense will be broken after using pipes with ForEach-Object. 

The code is really simple:
```
Get-ChildItem | ForEach-Object { return $_.Name } | Where-Object { $_.<type here to trigger intellisense>}
```

And from the screenshot below, we can see the completion suggestions we get are actually for the files/dictionaries, not for the names. So we cannot find the "IndexOf" function in the list.
![powershell](https://user-images.githubusercontent.com/1533278/29246357-36af2ca6-7fac-11e7-892f-a5e032ced910.png)

But if we run this command in the powershell window directly. It is totally fine.
![powershell-2](https://user-images.githubusercontent.com/1533278/29246392-4403f9b2-7fad-11e7-994b-5f09d720ebc2.png)

### System Details
```
PS C:\Users\r12f> code -v
1.15.0
8b95971d8cccd3afd86b35d4a0e098c189294ff2
PS C:\Users\r12f> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0


PS C:\Users\r12f> code --list-extensions --show-versions
formulahendry.terminal@0.0.10
ms-vscode.PowerShell@1.4.1
tariky.easy-snippet-maker@0.0.6
vscodevim.vim@0.9.0
PS C:\Users\r12f> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16251.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16251.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Attached Logs
[logs.zip](https://github.com/PowerShell/vscode-powershell/files/1220275/logs.zip)

**Comment by daviwil** [comment]
Thanks @r12f, I'll look into it.

**Comment by r12f** [comment]
Cool! Thanks @daviwil! Please let me know, if you need any other information.

**Comment by massimonewsuk** [comment]
I am having the same issue when using Select-Object. I raised an issue with PowerShell thinking it's a PS issue, but it turns out it works perfectly fine in PS. Here's the issue: https://github.com/PowerShell/PowerShell/issues/6330

**Comment by TylerLeonhardt** [comment]
@r12f This seems to be a PowerShell issue... can you try it in `powershell.exe` and confirm?

This is from PowerShell Core:
```
❯❯❯ Get-ChildItem | ForEach-Object { return $_.Name } | Where-Object { $_.<type here to trigger intellisense>}
Attributes                 LastWriteTimeUtc           CreateSubdirectory         GetLifetimeService
BaseName                   Length                     CreateText                 GetObjectData
CreationTime               LinkType                   Decrypt                    GetType
CreationTimeUtc            Mode                       Delete                     InitializeLifetimeService
Directory                  Name                       Encrypt                    MoveTo
DirectoryName              Parent                     EnumerateDirectories       Open
Exists                     PSStandardMembers          EnumerateFiles             OpenRead
Extension                  Root                       EnumerateFileSystemInfos   OpenText
FullName                   Target                     Equals                     OpenWrite
IsReadOnly                 VersionInfo                GetDirectories             Refresh
LastAccessTime             AppendText                 GetFiles                   Replace
LastAccessTimeUtc          CopyTo                     GetFileSystemInfos         ToString
LastWriteTime              Create                     GetHashCode

❯❯❯ Get-ChildItem | ForEach-Object { return $_.Name } | Where-Object { $_.}
```

**Comment by SydneyhSmith** [comment]
@SteveL-MSFT looks like this is a PowerShell Core issue, could you please transfer it?

**Comment by rjmholt** [comment]
@massimonewsuk I tried your repro, but get the same result in both VSCode and PSCore (array completions, which is essentially correct).

Do other things give you completions after that point?

The PowerShell extension does almost no manipulation of completions, it just passes through the results from PowerShell's completion engine.

**Comment by SydneyhSmith** [comment]
Marking this as external PowerShell bug
